### ISSUE TITLE
Inconsisent mapping for private FKs one-one vs one-many

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#10014]
I have two entities, both with a private FK property back to a 3rd entity:

`private int CharacterId { get;  set; }`

One of the entities is the dependent end of a 1:1 relationship with that 3rd entity, the other is the many end of a 1:* relationship.

In order for dbcontext to see them I have to explicitly configure the mappings. But the HasForeignKey syntax for the 1:1 is different than the 1:many.  1:1 requires that I specify the type in the parameters, but 1:* wants only a string. I get compiler errors if I do them differently than this:

 ```
modelBuilder.Entity<Character> ()
        .HasOne (typeof (Entrance), "Entrance")
        .WithOne ().HasForeignKey(typeof (Entrance),"CharacterId");
modelBuilder.Entity<Character> ()
        .HasMany (typeof (Quote), "Quotes")
        .WithOne ().HasForeignKey("CharacterId");
    

```
The resulting migrations are correct. I am guessing there is a reason for this difference (given the only other diff is 1:1 and 1:*) and am just curious why that is.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Code 1.17 (current)

**Comment by smitpatel** [comment]
From my understanding the difference of being 1:1 & 1:* is the reason for having different API. For one-to-many relationship, principal & dependent side are already determined so which entityType to look for FK property from HasForeignKey call is fixed. For one-to-one the principal/dependent side determination cannot be done with just Hasone/WithOne call. Unless there is matching FK property found on _only_ one side by convention, we throw exception asking to configure the FK explicitly. By taking the type in argument of `HasForeignKey` we ask uses to specify which type would be dependent (hence hosting the FK). Similar differences are found in 'HasPrincipalKey` API too.

This is not just private FK properties, the difference is in string based API. You would see same difference when using explicit shadow FKs instead of private FKs.

The expression lambda based version APIs are also different for the same reason.
OneToMany -> `HasForeignKey(e => e.CharacterId)`
OneToOne -> `HasForeignKey<Entrance>(e => e.CharacterId)`

**Comment by julielerman** [comment]
Thanks!
