### ISSUE TITLE
Nullable DateTime issue with SQLite

### ISSUE THREAD

**Issue by SamuelLioult** [dotnet/efcore#10027]
I have an issue with a nullable DateTime. I create an instance of a model which contains a nullable DateTime. When I want to update the datetime value in te database, the saved value is always 01/01/0001 in the SQLite database. This issue only appears in RELEASE mode but not in DEBUG mode.

If you are seeing an exception, include the full exceptions details (message and stack trace).

I describe my issue [here](https://stackoverflow.com/questions/46651149/uwp-efcore-sqlite-issue-with-nullable-datetime) with a sample code to reproduce the issue.

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore.SQLite 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SQLite
Operating system: Windows 10 15063.608
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@SamuelLioult Is this a UWP app?

**Comment by ajcvickers** [comment]
@SamuelLioult Never mind--I see that it is from the link. It could be an issue with .NET Native, and may already be fixed in 2.0. We will investigate.

**Comment by SamuelLioult** [comment]
@ajcvickers Yes it is a UWP app

**Comment by AndriySvyryd** [comment]
This is fixed in 2.0.3/2.0.1 with UWP 6

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

**Comment by dahovey** [comment]
Are there any possible workarounds for this issue, with using version 1.1.4 of EF Core?

Since using version 2.x of EF Core with UWP requires the  Windows Fall update this isn't possible with the project I'm working on.

The only possible workaround I can think is to use Raw Sql to insert or update entity that has any nullable DateTime/DateTimeOffset values. Is there anything that can be overridden by a consumer to fix the issue?
