### ISSUE TITLE
NO   DbQuery

### ISSUE THREAD

**Issue by cnmediar** [dotnet/efcore#10056]
public class DbSet<TEntity> : DbQuery<TEntity>, IDbSet<TEntity>, IInternalSetAdapter

DbContext().Database.SqlQuery<T>(sql, parameters).AsQueryable()

 IS Rong!

**Comment by ajcvickers** [comment]
@cnmediar If you are asking why there is no DbQuery class, it's because EF Core is a new code base and has an entirely different implementation from EF6 or earlier versions--think of it as a new framework rather than an update to the old framework. It is not intended that code written for EF6 will work without changes on EF Core.

**Comment by cnmediar** [comment]
Thank you very much!

How to do now ,I need stat Order by date, the result have two column,date and num?
