### ISSUE TITLE
Add-Migration return Path not found after update to 15.04

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#10058]
From VS Feedback:

Unable to resolve startup project ''.
Remove-Migration : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:1
+ Add-Migration
    + CategoryInfo          : InvalidData: (:) [Add-Migration], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Add-Migration

**Comment by oldsand** [comment]
I have spent 2 days to figure out the root course of this issue~ And I sure this is new bug caused by the update.

First my .Net Core sdk is updated to 2.02 after the VS2017 updated to 15.04, after that I got the same problem as you do and cannot use EF core commands.

Finally, I found that once the project folder is placed at some special character named folder, it will cause this issue.
In my case, I use to name the folder like [Sample], [Test], with these brackets, but once I add the brackets, the issue occurs!

**Comment by ajcvickers** [comment]
@bricelam Is #9280 the duplicate you were referring to in triage? In that issue, the exception was a NullReferenceException instead of a ParameterBindingValidationException. Is this still the same root cause?

@oldsand That looks like a different issue. Could you file a new issue on here with a complete project or code listing to allow us to reproduce what you are seeing?

**Comment by bricelam** [comment]
Yes, that's the issue I was thinking of. This might be something else...

**Comment by bricelam** [comment]
> Unable to resolve startup project ''.

I haven't seen this before.

**Comment by bricelam** [comment]
I can't repro this. If anyone has additional information, please let us know so we can investigate further.

**Comment by davidsheardown** [comment]
Just FYI..
Although this is closed, I had a similar issue in VS2017 (15.6.5) using dotnet core 2.02 and EF core 2.0.3 using Sqlite.

I added a migration which went well - generated the migration c# file.
Tried the update-database command and received the error reported above.

The only difference for me is I went to get a coffee, came back and re-tried and it worked fine!

**Comment by smitpatel** [comment]
@davidsheardown - ☕️ is solution to all the developer problems. 😉

**Comment by jasonneurohr** [comment]
@davidsheardown @smitpatel I agree, I had the same error (below). Found this issue thread, decided to run the command again after two minutes and it ran fine with no changes. I should have tried the coffee method!

PM> update-database
update-database : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:1
+ update-database
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-Database], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Update-Database

**Comment by iamwyza** [comment]
I also have this happening only it's not time.  It's just repeating the command.  First time fails with the above message, second time works.

**Comment by ntzfx** [comment]
You have to manually created the database, then update-database will be fine.
