### ISSUE TITLE
Question: Model Metadata

### ISSUE THREAD

**Issue by tonysneed** [dotnet/efcore#10068]
Does EF Core support expressing model metadata in a standard format?

Tooling for EF classic expressed model metadata as CSDL (part of EDMX), so that tools could read the metadata and perform things like code generation based on the metadata.

OData, for example, exposes the CSDL as an endpoint, and VS Code has an [extension](https://github.com/apazureck/odatatools) that reads it in order to generate TypeScript files, as does [Breeze](https://github.com/Breeze/breeze.tooling/blob/master/MetadataGenerator/README.md).  And OData does has a [spec](http://docs.oasis-open.org/odata/odata-json-csdl/v4.0/odata-json-csdl-v4.0.html) for JSON-formatted CSDL.

**Comment by ajcvickers** [comment]
@tonysneed EF Classic was built around the Entity Data Model (EDM) specification, which is why it used CSDL. EDM made a lot of things hard/costly to implement, so one of the main architecture changes for EF Core was to not use EDM, which means CSDL is not native to EF Core.

That being said, it should be possible to build something on top of EF Core to create CSDL, possibly as part of adding support for OData. This is something we would likely not do in the main code base--it would likely be better to have an external extension do it. I'm not aware of anything like this existing at the moment, but @divega may know more.

**Comment by tonysneed** [comment]
@ajcvickers [OData's port to .NET Core](https://github.com/OData/WebApi/issues/939#issuecomment-325814348) could benefit from work on this.  Also, I imagine tools on the npm side could consume the CSDL for things like code-gen, which would be great for SPA's and the like.

**Comment by ajcvickers** [comment]
@tonysneed We discussed this in triage and we certainly agree that this could be useful. However, it's not something we plan to implement and it seems like it should be something that is driven by demand from the community and probably implemented as a community project. We might re-consider this, but for now we're going to close this as something we won't do directly in EF Core.

(@divega pointed out that it may be difficult to map to CSDL given that EF Core has a very open type-system--that is, any CLR type can be in the model.)

**Comment by tonysneed** [comment]
@ajcvickers Got it ... thanks for answering!
