### ISSUE TITLE
Migration 1.1 -> 2.0 column name issue

### ISSUE THREAD

**Issue by grayver** [dotnet/efcore#10085]
After migrating from .NET Core 1.1 to .NET Core 2.0 I discovered issue with querying my complex data model. Here is minimal example model for reproducing:

```c#
public abstract class Organization
{
        public int Id { get; set; }
        public string Name { get; set; }
};

public abstract class NonProfitOrganization : Organization
{
        public string Mission { get; set; }
}

public class CharityFund : NonProfitOrganization
{
        public decimal CollectedAmount { get; set; }
}

public class Hospital : NonProfitOrganization
{
        public string Location { get; set; }
}

public class MyContext : DbContext
{
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<CharityFund> CharityFunds { get; set; }
        public DbSet<Hospital> Hospitals { get; set; }

        public MyContext(DbContextOptions<MyContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Organization>()
                .HasDiscriminator<string>("Type")
                .HasValue<CharityFund>("charity-fund")
                .HasValue<Hospital>("hospital");
        }
}
```

In EF.Core 1.0-1.1 this data model was automatically scaffolded to the following table:
- Id
- Name
- Mission
- CollectedAmount
- Location

But after migrating to EF.Core 2.0 my application tries to query both **Mission** and **Hospital_Mission** fields from Organizations table in runtime and suggests me to add Hospital_Mission field to Organizations table in design-time (dotnet ef migrations add).

The same situation for another case - when inherited models have exactly same field with same signature (same name and same type).

As a workaround I used following explicit column name Fluent API calls:
```c#
            modelBuilder.Entity<CharityFund>()
                .Property(cf => cf.Mission)
                .HasColumnName("Mission");

            modelBuilder.Entity<Hospital>()
                .Property(h => h.Mission)
                .HasColumnName("Mission");
```

Here are my questions:
1. As this is breaking change - why there is no any mention about it in migration guides?
2. Why EF.Core doesn't want to reuse the same table field for different inherited models if this field has exactly same signature?

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: MS Windows 7, MS Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@grayver For your first question, because we made a mistake. I have filed https://github.com/aspnet/EntityFramework.Docs/issues/529 to add better docs here.

For your second question, because in the general case where the columns have different configurations they cannot be shared. We could try to determine, based on the configuration facets that we know about, that the column could be shared. But then if one of those facets changes, we would end up now not being able to map to the same column and the model would change. This kind of change is usually unexpected and hard to debug. So instead we made it an explicit choice by the developer that two properties can share a column. This way there is less "magic" and, for those who want column sharing they can get it, but for those who don't care their mappings will always be functionally correct and their model will not unexpectedly change.
