### ISSUE TITLE
AddDbContextPool and WithExtension

### ISSUE THREAD

**Issue by kimbell** [dotnet/efcore#10138]
I'm trying to use DbContext in an ASP.NET Core application. 
I'm trying to pass some custom data to the DbContext based class. 

If I change to the constructor to have more arguments, I soon get an exception say that it can only have one argument of type DbContextOptions. So I started to look into Extensions. 

I've created a `CustomExtension` with a single property called `ApplicationName`.
If I use the following code, the extension is not available inside the DbContext class. 

```c#
services.AddDbContextPool<SomeDbContext>(optionsAction =>
{
        var op = optionsAction.Options.WithExtension(new CustomExtension
	{
		ApplicationName = "bob"
	});
	optionsAction.Options.WithExtension(new CustomExtension
	{
		ApplicationName = "bob"
	});
	optionsAction.UseSqlServer("some connection string");
});
```
In the `op` variable, the custom extension is shown, but in the `optionsAction.Options` property, it's not listed. Since `optionsAction.Options` is read-only, there is no way of changing it. 

How can we use AddDbContextPool and WithExtensions together?

**Comment by ajcvickers** [comment]
@kimbell Options extensions are not really designed for application code. If you need additional objects injected into your context, then I would recommend using AddDbContext (instead of AddDbContextPool) and then use constructor injection on the context instance in the normal way.

If you have done perf testing and are seeing context pooling to be beneficial in your application, then consider using `context.GetService<IMyService>()` to obtain the service without using constructor injection. Note, however, that when using pooling you have to be very careful with this since the service may be obtained from a different service provider than you are expecting.

**Comment by kimbell** [comment]
@ajcvickers  AddDbContext() did the trick. Thanks! Once you start down the wrong rabbit hole, you may not end up in Wonderland.
