### ISSUE TITLE
Query: improve ValueBuffer logic

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#10163]
There are some issues with current ValueBuffer implementation:

https://github.com/aspnet/EntityFrameworkCore/blob/1030467f778be6ac77ef8b76d8bb927cbd97fc84/src/EFCore/Storage/ValueBuffer.cs#L93

this logic doesn't work for OffsetValueBuffer

**Comment by anpete** [comment]
Is this causing a specific issue in dev?

@ajcvickers You added IsEmpty, was it by-design that it ignored offset? @smitpatel You added use of IsEmpty in MemberAccessBindingExpressionVisitor, was your expectation that it would work for offset > 0?

**Comment by ajcvickers** [comment]
@anpete I don't remember. It was added for places we are using value buffers outside of query where they may be lazily initialized. So it was supposed to mean the equivalent of `== null` if ValueBuffer were a ref type instead of a value type.

**Comment by smitpatel** [comment]
@maumar added the check so he can give exact reasoning to have it.

What my expectation around here,
A new SelectExpression is started with valueBufferShaper. Eventually we end up adding nothing to the projection hence there will be no rows. ValueBufferFactory creates ValueBuffer.Empty for that. If you call `IsEmpty` on that value buffer result is true.

Now if this SelectExpression ever get lifted in a join, without pulling out the projection, we have an offset value buffer and now semantics are all different. That breaks the concept of transparency between a valueBuffer & OffsetValueBuffer. We did not have to treat OffsetValueBuffer as specific apart from setting the offset. And it should work the same for IsEmpty case.

This came when Maurycy was working on correlation. If the Include collection query started, putting inner shaper then since it is not materialized it will be a OffsetValueBuffer with no data in it where IsEmpty couldn't work.

**Comment by AndriySvyryd** [comment]
@smitpatel Not needed?

**Comment by smitpatel** [comment]
No more offset value buffer
