### ISSUE TITLE
Want to migrate on dnx to cli with entity framework core

### ISSUE THREAD

**Issue by ankurjasoria** [dotnet/efcore#10196]
Hi Team,

I want to migrate from dnx to cli with entity framework but unable to find proper update and 
unable to run dotnet ef cli command and find below error.

Error : 
PS C:\test2\hwapp> dotnet ef
No executable found matching command "dotnet-ef"

I am sharing reference url below
http://www.bricelam.net/2014/09/14/migrations-on-k.html

Please update me any solution or any other reference url regarding same.

**Comment by ralmsdeveloper** [comment]
Hi @ankurjasoria , There is a great evolution since the DNX.

Do you have a project in DNX and would you like to migrate?

Regarding the migration there is a content, is a bit outdated and you can have an idea.

https://docs.microsoft.com/en-us/dotnet/core/migration/from-dnx

**Comment by ajcvickers** [comment]
@ankurjasoria In addition to the links from @ralmsdeveloper, so much has changed since the dnx days (which was only shipped as a preview) that you may be better off starting with a new application so that things are setup cleanly and then move you code over into the new application, wiring it up as necessary.

**Comment by ankurjasoria** [comment]
Hi Rafael/Arthur ,
Thanks for updating !!
I have followed below url as reference 
https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md

and found below issue with migrate command
Error :
PS C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform> dotnet migrate
No executable found matching command "dotnet-migrate"

I have created separate console application with the use of below cli command

    dotnet new
    dotnet restore
    dotnet build
    dotnet run

 All command working fine but unable to proceed further like What is my next step ?
 I am sharing you my powershall command and status as below

PS C:\test3\myApp> dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

myApp -> C:\test3\myApp\bin\Debug\netcoreapp2.0\myApp.dll

Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:01.02
PS C:\test3\myApp> dotnet run
Hello World!
PS C:\test3\myApp> dotnet migrate
No project.json file found in 'C:\test3\myApp'.
Migration failed.
PS C:\test3\myApp>

Please suggest me for same ?

**Comment by ajcvickers** [comment]
@ankurjasoria I don't believe that dotnet migrate exists anymore--I'm not sure if it ever shipped or not. As I said before, this kind of transition is is now so old that you are better off starting with a new application so that things are set up cleanly and then move your code over into the new application, wiring it up as necessary. For example, anything you find about migrating from dnx to .NET Core will be fore pre-release bits. But things also changed for the second major release of .NET Core, so anything you find for coming from dnx is likely to be out of date and you would also need to find what to do to get from there to where you need to be now.
