### ISSUE TITLE
Add Structured details to SqlException

### ISSUE THREAD

**Issue by inlineHamed** [dotnet/efcore#10248]
When saving DB changes I want to be aware of exception details to for example change and localize error message that is sent to the end user
currently I ended up using this approach:

```
try
{
    await _context.SaveChangesAsync();
}
catch (DbUpdateException ex) when (ex.InnerException is SqlException sqlException)
{
    switch (sqlException.Number)
    {
        //case 2627:  // Unique constraint error
        //case 547:   // Constraint check violation
        case 2601:  // Duplicated key row error
            if (sqlException.Message.Contains("Student_Number"))
            {
                throw new ModelErrorException(nameof(student.Number), "A {0} with this {1} is already registerd")
                    .AddMessageParam("Student", _localizedDisplayNameProvider.GetDisplayName<Student>(c => c.Number));
            }
            // And so on
    }
    throw;
}
```

I think it would be much more better if entity framework in someway provide detail info  for example by using different child type exception like DuplicatedKeyException,  UniqueConstraintException and so on.

**Comment by roji** [comment]
One interesting related question is about detecting certain common relational exceptions in a database-independent way. In other words, it's currently impossible to test for a unique constraint violation in the same way across SQL Server, PostgreSQL, etc.

On the other hand, it could be argued that this is more of an ADO.NET-level requirement than an EF Core feature.

**Comment by ajcvickers** [comment]
@hmdhasani To add to what @roji said, this would require a fair amount of work to do in a way that would enable providers to integrate with it and give a consistent experience. We have discussed this on several occasions in the past and decided that the value is not high enough.

One of the reasons for this is that their don't seem to be many real scenarios where it would be used. These errors usually indicate a bug in the application--it's unusual to write an application where one of the expected behaviors is that a user tries to save, gets some kind of database error, and then is informed what that database error is so that the user can take some action. It's much more common that the error is captured/logged in some way and then reported to the application developer. This logging is usually going to happen at a lower level than EF--for example, in SQLClient--where the additional information needed to debug the error message should be accessible.

**Comment by hmdhasani** [comment]
@roji @ajcvickers thank you

**Comment by roji** [comment]
@ajcvickers I tend to agree about the limited usefulness of this...
