### ISSUE TITLE
SqlServerValueGeneratorSelector: my cheese has been moved

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#10299]
Upgrading from EF 1.1.0 to 2.0. 
I have a class:
```
public class CustomSqlServerValueGeneratorSelector : SqlServerValueGeneratorSelector
{
        // empty constructor; signature has changed since EF 1.1.0
        public override ValueGenerator Create(IProperty property, IEntityType entityType)
        {
          ...
        }
}
```
which i hooked in to my data context like so:
```
        private static readonly IServiceProvider _serviceProvider = new ServiceCollection()
             .AddEntityFrameworkSqlServer()
             .AddScoped<SqlServerValueGeneratorSelector, CustomSqlServerValueGeneratorSelector>()
             .BuildServiceProvider();

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            var connectionString = ConfigurationManager.ConnectionStrings["MyConnection"].ConnectionString;
            options
                .UseInternalServiceProvider(_serviceProvider)
                .UseSqlServer(connectionString);
        }
```
This used to work; the `Create()` method of my custom class would return the right value generator. Now it doesn't even hit a breakpoint on the first line of the method.

What changes do I need to make to get this working again?

Thanks in advance.

**Comment by smitpatel** [comment]
You would need to add constructor probably like this

https://github.com/aspnet/EntityFrameworkCore/blob/e4ab5ad430871e63083287cb8d00ffdd5c2109cf/src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorSelector.cs#L26-L37

Also the service registration is like this 
https://github.com/aspnet/EntityFrameworkCore/blob/e4ab5ad430871e63083287cb8d00ffdd5c2109cf/src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs#L80
So you may need to add scoped service of `IValueGeneratorSelector` instead of concrete type.

**Comment by shaulbehr** [comment]
Thanks @smitpatel, I changed my code from:
```
private static readonly IServiceProvider _serviceProvider = new ServiceCollection()
             .AddEntityFrameworkSqlServer()
             .AddScoped<SqlServerValueGeneratorSelector, CustomSqlServerValueGeneratorSelector>()
             .BuildServiceProvider();
```
to
```
private static readonly IServiceProvider _serviceProvider = new ServiceCollection()
             .AddEntityFrameworkSqlServer()
             .AddScoped<IValueGeneratorSelector, CustomSqlServerValueGeneratorSelector>()
             .BuildServiceProvider();
```
and now it works!
Thank you for your help!
