### ISSUE TITLE
Many-to-many implementation: will linking tables happen automatically or will we still need to map?

### ISSUE THREAD

**Issue by electricessence** [dotnet/efcore#10336]
As described here (for many-to-many), is this set in stone, or will it evolve to automatically map using attributes?

Also, is there any potential helper methods for adding (or removing) an entity to this linking without having to return an identity before continuing to add to the linking table?

https://docs.microsoft.com/en-us/ef/core/modeling/relationships
```cs
class MyContext : DbContext
{
    public DbSet<Post> Posts { get; set; }
    public DbSet<Tag> Tags { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PostTag>()
            .HasKey(t => new { t.PostId, t.TagId });

        modelBuilder.Entity<PostTag>()
            .HasOne(pt => pt.Post)
            .WithMany(p => p.PostTags)
            .HasForeignKey(pt => pt.PostId);

        modelBuilder.Entity<PostTag>()
            .HasOne(pt => pt.Tag)
            .WithMany(t => t.PostTags)
            .HasForeignKey(pt => pt.TagId);
    }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public List<PostTag> PostTags { get; set; }
}

public class Tag
{
    public string TagId { get; set; }

    public List<PostTag> PostTags { get; set; }
}

public class PostTag
{
    public int PostId { get; set; }
    public Post Post { get; set; }

    public string TagId { get; set; }
    public Tag Tag { get; set; }
}
```

**Comment by ajcvickers** [comment]
@electricessence Not 100% sure what you are asking, but many-to-many without join tables is tracked by #1368. It should be possible to do this with just attributes/conventions once implemented.

Not sure what you mean on your second question. Can you be more specific and include some code showing what you mean?

**Comment by electricessence** [comment]
@ajcvickers ...
1) "once implemented" is the question... I have the cross definitions in place...  (HasOne/WithMany etc.)  The question is, do I need them anymore?  Will keeping them be problematic?  When can I remove them?

2) Right now, if you want to create a link, you simply add an entry to the linking table no?  Before, you could add an entry to the 'linkage'... 

```cs
// Old way:
book.Categories.Add(category);
context.Save();
```

```cs
// New way:
book.BookCategories.Add(new BookCategory() { BookID=book.ID, CategoryID=category.ID } );
context.Save();
```

I can imagine writing some extensions to simplify this.  So I'm asking if there is already a better way?

Also, I was struggling with the case where you create a new entry and it's linking at the same time...

```cs
// Categories already defined previously.
var book = new Book();

// Old way:
book.Categories.Add(category);
books.Add(book);
context.Save();

// New way:
// ????
var bc = new BookCategory(){ CategoryID = category.ID };
book.BookCategories.Add(bc);
// Does it automatically figure out the Book identity for bc?

books.Add(book);
context.Save();
```

**Comment by ajcvickers** [comment]
@electricessence Sorry, but I'm really struggling to understand what you are referring to. Can you explain what you mean by "old way" and "new way"? Old and new with respect to what? Are you referring to many-to-many relationships in EF6 verses how they are in EF Core 2.0 or are you asking about how they are going to be once #1368 is implemented?

**Comment by electricessence** [comment]
I apologize if I'm not making sense.  I'm migrating an older EF to new EF Core.

> Are you referring to many-to-many relationships in EF6 verses how they are in EF Core 2.0 or are you asking about how they are going to be once #1368 is implemented?

1) "once implemented" meaning, it is not yet. Correct?
2) What is the right way _right now_, and is there a difference _once implemented_?  ==> The link and sample I provided is directly from Microsoft docs and it includes _in addition to_ the key mappings, the dual unidirectional relationship maps for respective tables.  Will this still be true when finally released?  Or will you only need the link table class definitions and not need the explicit mappings.

**Comment by electricessence** [comment]
> Can you explain what you mean by "old way" and "new way"?

I'm simply a little foggy on the optimal way to add a many-to-many link/reference when updating a table.  I'm concerned about how the identity of a new item is properly passed to the link-entity.

**Comment by ajcvickers** [comment]
@electricessence Still finding it a little difficult to understand everything you are asking (for example, where are the unidirectional relationships?) but I'll try to answer in a general way.

* To map a many-to-many relationship in EF Core currently requires the join table to mapped. I wrote a series of blog posts on this which might be useful: https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/
* Mapping many-to-many relationships without explicitly mapping the join table (as in classic EF) is tracked by #1368. You can tell this is not implemented because the issue is not closed. It's also not planned for 2.1 since it is in the Backlog milestone.
* As it stands now, you will need to do some configuration of at least the join table primary key. The full configuration you showed above is not needed for simple cases where the relationships are bi-directional and PK and FK names match conventions, but it doesn't do any harm. My blog post contains some info on this too.
* You'll need to add explicit join entities when creating a new many-to-many links. However, you should not need to use key values directly--navigation fixup should work just fine.
  * There are ways to work around this, as covered in later parts of my blog posts, but under the covers they all end up adding join entities.

In general, many-to-many relationships now are just two one-to-many relationships, and they work like any other one-to-many relationships.
