### ISSUE TITLE
Help on decoding Model with 'foreign key to same table' when using table splitting

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#10345]
I am building a tool that can compare the DbContext's `Model` with a database (I get the database model via the design-time scaffolder). The idea is to to provide feedback to the user when the DbContext's `Model` and the database don't match - rather like a user-friendly version of EF6.x's `context.Database.CompatibleWithModel`, with human-readable error messages.

I have got it to work with pretty much every combination of table mapping, but I have run into problems with table splitting. Basically the `context.Model` says there is a foreign key to the table, but because its the same table it doesn't exist. *NOTE: owned types do the same, but I was able to find/fix that.*

Obviously EF Core works out that a foreign key isn't needed, but I couldn't find how to detect that in the `Model`.

## UPDATE: I have found a way to detect the problem and fix it. The code below has been updated.

My code is quite large, and I have given you the section that goes wrong out of the `Stage1Comparer` class (found [here](https://github.com/JonPSmith/EfCore.TestSupport/blob/master/TestSupport/EfSchemeCompare/Internal/Stage1Comparer.cs)). The bit I want to fix is the method `IgnoreForeignKeyIfInSameTable` at the bottom.

The whole project is an open-source on Github at [JonPSmith/EfCore.TestSupport](https://github.com/JonPSmith/EfCore.TestSupport) and on Nuget as [EfCore.TestSupport](https://www.nuget.org/packages/EfCore.TestSupport/). There is some documentation [in the wiki](https://github.com/JonPSmith/EfCore.TestSupport/wiki/9.-EfSchemaCompare)

```c#
private void CompareForeignKeys(CompareLog log, IEntityType entityType, DatabaseTable table)
{
    var fKeyDict = table.ForeignKeys.ToDictionary(x => x.Name);

    foreach (var entityFKey in entityType.GetForeignKeys())
    {
        var entityFKeyprops = entityFKey.Properties;
        var constraintName = entityFKey.Relational().Name;
        var logger = new CompareLogger(CompareType.ForeignKey, constraintName, log.SubLogs, _ignoreList, () => _hasErrors = true);
        if (IgnoreForeignKeyIfInSameTable(entityType, entityFKey , table))
            continue;
        if (fKeyDict.ContainsKey(constraintName))
        {       
            //Now check every foreign key
            var error = false;
            var thisKeyCols = fKeyDict[constraintName].Columns.ToDictionary(x => x.Name);
            foreach (var fKeyProp in entityFKeyprops)
            {
                var pRel = fKeyProp.Relational();
                if (!thisKeyCols.ContainsKey(pRel.ColumnName))
                {
                    logger.NotInDatabase(pRel.ColumnName);
                    error = true;
                }
            }
            error |= logger.CheckDifferent(entityFKey.DeleteBehavior.ToString(), 
                fKeyDict[constraintName].OnDelete.ConvertReferentialActionToDeleteBehavior(entityFKey.DeleteBehavior), 
                    CompareAttributes.DeleteBehaviour);
            if (!error)
                logger.MarkAsOk(constraintName);
        }
        else
        {
            logger.NotInDatabase(constraintName, CompareAttributes.ConstraintName);
        }
    }
}

private bool IgnoreForeignKeyIfInSameTable(IEntityType entityType, IReadOnlyList<IProperty> keyProperties, DatabaseTable table)
{
    if (entityType.DefiningEntityType != null &&
        entityType.DefiningEntityType.Relational().TableName == table.Name)
        //if a owned table, and the owned entity's table matches this table then ignore
        return true;

    //see https://github.com/aspnet/EntityFrameworkCore/issues/10345#issuecomment-345841191
    if (entityFKey.Properties.All(x => x.DeclaringEntityType.Relational().TableName == table.Name)
         && entityFKey.Properties.Select(p => p.Relational().ColumnName)
            .SequenceEqual(entityFKey.PrincipalKey.Properties.Select(p => p.Relational().ColumnName)))
        //If all the declaring entity type of the foreign key are all in this table, then we ignore this (table splitting case)
        return true;


    //Otherwise we should not ignore it
    return false;
}
```

The unit test that fails is `CompareSpecializedDbContext` fact in [`CompareSpecialised` class](https://github.com/JonPSmith/EfCore.TestSupport/blob/master/Test/UnitTests/EfSchemaCompare/ComparerSpecialized.cs). The database has a `BookDetails` and `BookSummary` class which do the table splitting. (Ignore the second error - that is due to issue #9652)
## UPDATE: Unit test has been updated - it works now.

```c#
[Fact]
public void CompareSpecializedDbContext()
{
    //SETUP
    using (var context = new SpecializedDbContext(_options))
    {
        var comparer = new CompareEfSql();

        //ATTEMPT
        var hasErrors = comparer.CompareEfWithDb(context);

        //VERIFY
        hasErrors.ShouldBeTrue();
        var errors = CompareLog.ListAllErrors(comparer.Logs).ToList();
        errors.Count.ShouldEqual(1);
        errors[0].ShouldEqual(
            "DIFFERENT: BookSummary->Property 'BookSummaryId', value generated. Expected = OnAdd, found = Never");
    }
}
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (and others)
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@JonPSmith Can you explain a bit what you mean by, "Basically the context.Model says there is a foreign key to the table, but because its the same table it doesn't exist?" Are you saying that EF is not creating FK constraints in the database for this case?

**Comment by JonPSmith** [comment]
Hi @ajcvickers,

In getting the information to explain the problem I found a way around it, so **this isn't a problem any more** (I have updated the original code with my fix).

However, the basic problem is that foreign key information is incorrect in the the `context.Model` for *table splitting* classes. I have worked around the problem, so you can close the issue, but I thought you might like to know what is going on.

## The incorrect information in the `context.Model`

For *table splitting* the `context.Model` incorrectly says that there is one foreign key between the two classes involved in the *table splitting*  arrangement, i.e. it has a foreign key that points to the same table. When EF Core creates the table it doesn't include that foreign key. The code below shows my set up.

I have two tables that are involved in table splitting, `BookSummary` and `BookDetail`, which both map to the table called `Books`. Here are the entity classes and the configuration code.

```c#
public class BookSummary
{
    public int BookSummaryId { get; set; }
    public string Title { get; set; }
    public string AuthorsString { get; set; }
    public BookDetail Details { get; set; }
}
```
```c#
public class BookDetail
{
    public int BookDetailId { get; set; }
    public string Description { get; set; }
    public decimal Price { get; set; }
}
```
The configuration code is 
```c#
public void Configure
    (EntityTypeBuilder<BookSummary> entity)
{
    entity.HasKey(p => p.BookSummaryId);

    entity
        .HasOne(e => e.Details).WithOne()
        .HasForeignKey<BookDetail>(e => e.BookDetailId);
    entity.ToTable("Books");
}
```
and
```c#
public void Configure
    (EntityTypeBuilder<BookDetail> entity)
{
    entity.ToTable("Books");
}
```
The actual SQL table looks like this, i.e. there is no foreign key.
```SQL
Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [Books] (
    [BookSummaryId] int NOT NULL,
    [Description] nvarchar(max) NULL,
    [Price] decimal(18, 2) NOT NULL,
    [AuthorsString] nvarchar(max) NULL,
    [Title] nvarchar(max) NULL,
    CONSTRAINT [PK_Books] PRIMARY KEY ([BookSummaryId])
);
```

If I look at the `context.Model.GetEntityTypes()` and look at the `BookDetails` entityType then the `entityType.GetForeignKeys()` returns one foreign key, which is wrong because the foreign key points to the same table.

Note: *Owned types* have the same problem (i.e., an incorrect foreign key in the `context.Model`) and also defines a primary key, which is also incorrect. These were much easier to work around because of the `entityType.DefiningEntityType` property.

**Comment by smitpatel** [comment]
It is correct model.
At core level, you have 2 entity types with a unique one to one relationship defined with them. From perspective of Core, every entity type has their own storage. The `ToTable` calls sets a relational annotation on EntityType indicating what should be the table at "relational" level. This is by design. Relational has concept of table splitting but non-relational providers do not have it that way. (It would map with nested json more than table splitting). Hence when you look at model in core, yes there is foreign key defined.

The code which makes FK go away is in relational and multi step.
1. `SharedTableConvention` - This convention configures owned entity to map to same table as the owner entity. It also unique-fy column names for sharing the table.
2. RelationalPropertyAnnotations.GetDefaultColumnName() maps column name of dependent PK (which is also FK to principal PK. (In above case it will map BookDetailId to BookSummaryId column.
3. `TableMapping` class in migration which is the final key to swallow the FK.

https://github.com/aspnet/EntityFrameworkCore/blob/c7c7d455ed9877f56164e6531d23fedffa104dc7/src/EFCore.Relational/Metadata/Internal/TableMapping.cs#L77-L83

If you look at `TableMapping.GetForeignKeys()` method, what it does is, finds all FK defined on all entityTypes and removes FK which are pointing to the same table & where column names for FK properties are same as principal columns (set in step 2 above). For table splitting case, the FK is between PK to PK and we just use 1 column to store value and using implicit relationship rather than creating an FK. This is the place where FK from core gets swallowed by Migrations because it is unnecessary to create.

Since the whole concept of table sharing and mapping is relational, if you are just looking at core metadata it will not match your database table till you apply relational level transformations to it.

In your case the diffing method,
For dependent shared table of (BookDetail), you need to find all FKs defined on the PK of it which are pointing to entityType (BookSummary) being stored in same table (Books) and uses the same column name for FK properties as Principal properties (BookSummaryId). Such FKs will be swallowed and ignored. Your updated check is almost true but you also need to do structural comparison over FK properties for their column names.

**Comment by JonPSmith** [comment]
Thanks @smitpatel for taking the time to provide me with a very detailed answer. Excellent stuff. I will look at that and make some changes.
