### ISSUE TITLE
Connectionstring Azure Active Directory Account

### ISSUE THREAD

**Issue by eflorespalma** [dotnet/efcore#10351]
Hi, everybody i have a services account in my sql azure associated to my azure active directory.. i can connect to sql azure through sql managment using the credentials of my Azure AD account with the method **Active Directory Password**, but now i want that my net core app use authenthication via azure ad account and i dont know how to do it, because i put Authentication = Active Directory Password and throw me an error saying that Authentication attribute is not valid. Im using net core 1.1. Is this is posible?

**Comment by ErikEJ** [comment]
Have you tried with full .NET Framework - the System.Data.SqlClient for .NET Core is not "feature complete"

**Comment by ajcvickers** [comment]
@eflorespalma This is really a question for SQLClient, since EF Core doesn't play a part in understanding/using the actual contents of the connection string. If you want to continue to follow up on this, then I would file an issue on the [corefx repo](https://github.com/dotnet/corefx), but you may have better luck just asking a question on Stack Overflow.
