### ISSUE TITLE
No values for shadow properies when using `AsNotracking`

### ISSUE THREAD

**Issue by mpawelski** [dotnet/efcore#10387]
When I use shadow property and `AsNotracking` there is no value in `PropertyEntry.CurrentValue` or `PropertyEntry.OriginalValue` but for other properties that are defined in entity class I can access their values.

### Steps to reproduce
For example I have this code in my `OnModelCreating` method

```c#
modelBuilder.Entity<Department>().ForNpgsqlUseXminAsConcurrencyToken();
modelBuilder.Entity<Department>().Property<string>("ShadowTest");
```
and `ForNpgsqlUseXminAsConcurrencyToken` inside is just 
```c#
  entityTypeBuilder.Property<uint>("xmin")
                .HasColumnType("xid")
                .ValueGeneratedOnAddOrUpdate()
                .IsConcurrencyToken();
```
but when I access `_context.Entry(department).Property("ShadowTest").CurrentValue`
I get null and for `_context.Entry(department).Property("xmin").CurrentValue` i get 0 (default of uint).

However other properties (not shadow ones) in my entity have proper values in `OriginalValue` and `CurrentValue`.

Is would be good if the behavior for shadow property and normal was consistent. I figured that right now to get the value of shadow property and use `AsNoTracking` I can write something like:
```c#
_context.Departments
                .AsNoTracking()
                .Select(d => new {
                    Department = d,
                    xmin = EF.Property<uint>(d, "xmin"),
                    ShadowTest = EF.Property<string>(d, "ShadowTest"),
                })
```
The SQL is the same, this shadow properties are fetched from db. Can we allow getting their values by using standard `ChangeTracker` API?

**Comment by Tarig0** [comment]
Why would you want the shadow properties unless you are tracking the entity?

Seems to me you want to have your cake and eat it to.

The only way you would be able to get the shadow properties without tracking them after the initial query is to query the DB again.

**Comment by ajcvickers** [comment]
@mpawelski To add a bit more to what @Tarig0 says, shadow properties are properties that do not exist in the entity's CLR type and hence must be stored somewhere else. That "somewhere else" is an entry associated with the entity when it is tracked by the context. So when you run a tracking query, then the shadow property values are associated with the entry in the context that tracks the entity.

If you run a no-tracking query, then once the query has completed, EF no longer has any reference to the returned entities--that's what a no-tracking query is. Consequentially, there is no place to store the shadow property values and they are lost.

When you call context.Entry, then one of two things happen:
* If the entity is being tracked, then you get back access to the entry for that tracked entity, which contains values for the shadow properties.
* If the entity is not being tracked, then you get back a new entry for the entity such that you can do things like start tracking it. However, this is a new entry because the entity was not previously being tracked, and as such it does not contain the shadow property values.

There are several things you could do here to access shadow property values. Some of the common ones are:
* Use a tracking query
* Project out the shadow properties in the query--i.e. provide your own storage for these properties rather than just letting EF do it
* Consider using private properties or fields instead of shadow properties so that the properties are not in the entity type public surface, but the values are still stored with the entity.

**Comment by mpawelski** [comment]
Thank you guys for this great answers! It really helped me in learning EF Core.
