### ISSUE TITLE
It should be possible to create ILoggerFactory (or custom ef logger) for each dbContext and inject it as regular dependency without side effects

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/efcore#10397]
https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging wrotes: 

> It is very important that applications do not create a new ILoggerFactory instance for each context instance. Doing so will result in a memory leak and poor performance.

Is it a final design decision or a bug?

Requiring "only one ILoggerFactory instance per app"   means "it is impossible to create logging when each dbcontext logs to each own buffer (e.g. to each own string list)"

How to configure logging to concreete buffer for concreate session depending e.g on user name? pooling loggingFactories? Really? 

Or may be this is just wrong documentation? And disposing loggerFactory with dbContext is enough to solve a memorey leak problem? May be custom LoggerFactory can solve a performance problem?

P.S. I have checked. Dispose doesn't help. Creating new LoggerFactory instances create leaks of whole "DbContextOption" and all classes where it is referenced (a lot, including connections). And root is a
`Static variable Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<Instance>k__BackingField`

Why simple loggin function `Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)` should be cached? Add to it `categoryName` and give us a normal standard way to Inject this dependency : through constructor. No more those crazy overdesigned solutions as `dbContext.GetService<ILoggerFactory>().AddProvider(loggerProvider)` which adds logger to all dbContext, or `optionsBuilder.UseLoggerFactory(loggerFactory)` which adds the only one and the same logger with the same static source.

**Comment by ajcvickers** [comment]
@rpokrovskij If you are using ASP.NET Core, then it may be worth following up with the ASP.NET team since EF mainly makes use of the infrastructure setup for an ASP.NET application. This includes a single, singleton ILoggerFactory registered in the application's service provider.

With regard to the EF use of ILoggerFactory, we optimized for the case where services do not need to depend on a context instance just because they do logging, which in turn means that more services can be singletons (instead of scoped) which in turn gives a performance boost and an architectural simplification.

While the documentation is correct in general, if you have a small number of context instances, then you can use a different ILoggerFactory for each instance. It will result in EF building a new root for singleton services internally, which in turn has implications on memory and performance. However, if the number is small, then it may be manageable.

All that being said, it would be good to allow logs to be filtered by context. However, this mechanism likely wouldn't work well with ILogger since it doesn't fit well into the structured logging that it provides, but would instead use the alternate DiagnosticsSource approach and likely exposed through EF as part of #1199.

**Comment by rpokrovskij** [comment]
Yes, I have created pooling solution: 
https://stackoverflow.com/questions/43680174/entity-framework-core-log-queries-for-a-single-db-context-instance/43818769?noredirect=1#comment81955801_43818769

But the fact that you explain EF Core (over)design with "we want to do it ASP.NET way" - it is just a facepalm. Do you have your own minds about arhcitecture you desinging? Compare "pooling" with EF6 context.Database.Log  event  and explain what had won by using service locators in the same documentation where you state "It is very important that applications do not create a new ILoggerFactory instance ". Otherwise it looks like  EF Core architects do not understand basics of DI.
