### ISSUE TITLE
[Tools] [Enhancement] Extend dotnet ef scripting

### ISSUE THREAD

**Issue by joacar** [dotnet/efcore#10393]
Hi,

I would like to see some extension to the scripting via command line (or PMC for that matter)

## dotnet ef migrations revert
1. Update the database to the previous migrations and apply it `dotnet ef database update Migrations-1`
2. Remove the last not applied migrations `dotnet ef migrations remove`

## File extension for additional data
In many of my web projects the DbContext is definied in an assembly different from where the app is hosted, so I tend to write `dotnet ef migrations add MyMigration -c MyContext -p ... -o ...` very frequently. This is now a custom script, which works fine. I can just `dotnetef migrations add MyMigration`.
For new people this is something that they would need to learn and get acustom to, and I want it to be as simple as possible to get started and just do "the normal way": `dotnet ef migrations add MyMigration`.

Perhaps this can be fixed by a file with configurations that can be read (if exists). For example

`.ef.config`
```
MyContext: -p ... -o ...
MyOtherContext: -p ... -o ...
```

## dotnet ef migrations squash
If working on a feature branch this would be very useful to creata a single migration from many experimental. Currently I do the "revert" step over and over again.

A lot of stuff here and I will gladly help submitting a PR if someone could point me in the direction where to start; if this is something that the community would like to see. 

Otherwise point me in the right direction anyway so that perhaps I can build it as an extension :)

Good work with EF

**Comment by bricelam** [comment]
Some thoughts:

#1972 is about adding a `--revert` option (or similar) to `dotnet ef migrations remove`

I think we support response files (or can easily enable it):
``` cmd
dotnet ef migrations add @MyContext.ef.config
```

#2174 is tracking a squash command.

**Comment by ajcvickers** [comment]
@joacar Thanks for the suggestions. As @bricelam says above, two of these issues are already being tracked, and I just filed #10409 for ensuring the response files can be used. We would be happy to help you get started if you would like to work on a PR for any of these issues.

**Comment by joacar** [comment]
@ajcvickers I would be glad to contribute! Perhaps response files I a good starting point and after completion move to tackling the others. I'll move the discussion to the appropriate issue!

**Comment by jsacapdev** [comment]
@bricelam this is a feature that i would find useful and so i have had a go with the changes and it works as you explained. do you have any guidance on unit testing?

For me I created a project and at the command line ran something like dotnet ./dotnet-ef.dll migrations list @BloggingContext.ef.config. Because the entry point is calling the command line, I am unsure on your preferred approach as to how to achieve this in an automated way (is there an expectation for automated testing at the command line level)? Or is it sufficient for the entry point to just test CommandLineApplication::ExpandResponseFiles().

If you do have any further thoughts and/or guidance on how to approach the unit testing that would be appreciated.
