### ISSUE TITLE
Unexpected delete statement when SaveChanges called

### ISSUE THREAD

**Issue by marcusholmgren** [dotnet/efcore#10391]
I have tested to have a Domain Driven-Design aggregate root (Blog) that have child entities (Post). The Blog have private setters so the internal set can only be modified through the add method on the Blog. When loading Blog and including posts the behaviour changes and adding new posts generates a unexpected delete statement that removes previous post from the blog.

1. Open new DB context and create a new Blog and add one Post. 2 insert statements created as expected.
2. Open new DB context and read Blog including posts. Add one Post. Delete statement that removes the first Post and then insert statement for the new Post.

The GitHub repository have extract from database tables after running the program. The sequence PostId is missing number 1 post.

### Steps to reproduce
Please see this repository for details [https://github.com/marcusholmgren/efcore-test](https://github.com/marcusholmgren/efcore-test)

Sql Server version used `docker pull microsoft/mssql-server-linux:2017-latest`

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7, macOS High Sierra 
IDE: Visual Studio 2017, Visual Studio Mac and Visual Studio Code

**Comment by smitpatel** [comment]
https://github.com/marcusholmgren/efcore-test/blob/master/Program.cs#L82

This line seems somewhat in-accurate. When Include pipeline tries to get `Posts` to add retrieved posts from database, it will get a new instance of hashset since field `posts` is null. But when you add another post, it will initialize field `posts` and the instance of hashset where include added post was gone due to `??` in posts. So when diffing between 2 hashsets, we see that posts retrieved from database is no longer there hence the delete statement.

Try this instead
`public IEnumerable<Post> Posts  => posts ?? (posts = new HashSet<Post>());`

**Comment by marcusholmgren** [comment]
Thank you @smitpatel. Your suggested change solves this reported incident. 

Since the mapping isn't explicitly stating that the private member `posts` is the field to be change tracked I can see why this causes diffing problems.
