### ISSUE TITLE
Support for readonly backing fields

### ISSUE THREAD

**Issue by glucaci** [dotnet/efcore#10400]
Using readonly backing fields is currently not supported. It's any plan for this?

```
Exception message: System.InvalidOperationException: 
'Field '_name' of entity type 'Customer' is readonly and so cannot be set.'

Stack trace: 
at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateFieldMapping(IModel model)
```

Considering next model:
```c#
public class Customer
{
   private readonly string _name;

   protected Customer() { }

   public Customer(string name)
   {
       _name = name;
   }

   public string Name => return _name;
}
```

**Comment by ajcvickers** [comment]
@glucaci We plan to support this by allowing non-parameterless constructors to be used--see #240. We did investigate attempting to force writing of the readonly field, but the CLR protects it pretty well, even when building/executing expression trees. We didn't want to revert to pure Reflection since this would result in a non-obvious perf bottleneck.

**Comment by glucaci** [comment]
Thanks for explanation @ajcvickers. I'll follow the discution on #240
