### ISSUE TITLE
Joining tables with "xmin" defined as concurrency token throws "column x.xmin does not exist" (PostgresSQL)

### ISSUE THREAD

**Issue by olivierr91** [dotnet/efcore#10405]
AppDbContext.cs:

```
modelBuilder.Entity<User>().ToTable("user").HasKey(u => u.Id);
modelBuilder.Entity<User>().Property(u => u.Id).HasColumnName("id");
modelBuilder.Entity<User>().Property(u => u.FriendlyId).HasColumnName("friendly_id").HasDefaultValueSql("nextval('user_friendly_id_seq')").IsRequired();
modelBuilder.Entity<User>().Property(u => u.ConcurrencyToken).HasColumnName("xmin").HasColumnType("xid").HasColumnType("xid").ValueGeneratedOnAddOrUpdate().IsConcurrencyToken();
modelBuilder.Entity<User>().Property(u => u.Username).HasColumnName("username");
modelBuilder.Entity<User>().HasOne(u => u.AccountPicture).WithOne().HasForeignKey<User>(u => u.AccountPictureId);

modelBuilder.Entity<UserFile>().ToTable("user_file").HasKey(uf => uf.Id);
modelBuilder.Entity<UserFile>().Property(uf => uf.Id).HasColumnName("id");
modelBuilder.Entity<UserFile>().Property(uf => uf.FriendlyId).HasColumnName("friendly_id").HasDefaultValueSql("nextval('user_file_friendly_id_seq')").IsRequired();
modelBuilder.Entity<UserFile>().Property(uf => uf.ConcurrencyToken).HasColumnName("xmin").HasColumnType("xid").HasColumnType("xid").ValueGeneratedOnAddOrUpdate().IsConcurrencyToken();
modelBuilder.Entity<UserFile>().Property(uf => uf.OriginalFileName).HasColumnName("original_file_name");
modelBuilder.Entity<UserFile>().Property(uf => uf.SizeInBytes).HasColumnName("size_in_bytes");
modelBuilder.Entity<UserFile>().Property(uf => uf.SubDirectoryName).HasColumnName("sub_directory");

modelBuilder.Entity<UserImageFile>().ToTable("user_file");
modelBuilder.Entity<UserImageFile>().Property(uif => uif.Width).HasColumnName("width");
modelBuilder.Entity<UserImageFile>().Property(uif => uif.Height).HasColumnName("height");
```
Where `UserImageFile` inherits from `UserFile` and `User.AccountPicture` is of type` UserImageFile`.

UserRepository.cs:

`_dbContext.Users.Include(u => u.AccountPicture).ToList();`

Generated SQL by Entity Framework:

```
SELECT "u"."id", 
       "u"."xmin", 
       "u"."username", 
       "t"."id", 
       "t"."xmin", 
       "t"."discriminator", 
       "t"."original_file_name", 
       "t"."size_in_bytes", 
       "t"."sub_directory", 
FROM   "user" AS "u" 
       LEFT JOIN (SELECT "u.AccountPicture".* 
                  FROM   "user_file" AS "u.AccountPicture" 
                  WHERE  "u.AccountPicture"."discriminator" = 'UserImageFile') 
                 AS "t" 
              ON "u"."account_picture_id" = "t"."id" 
ORDER  BY "u"."id";
```
Throws "column t.xmin does not exist". This query isn't valid because PostgreSQL will not select xmin as part of `"u.AccountPicture".*` . EFCore should implicitly select all columns (including xmin) for this query to be valid.

**Comment by roji** [comment]
For context, `xmin` is a PostgreSQL system column that contains the ID of the last transaction to update the row. The column implicitly exists in all tables, and can be used for optimistic concurrency (a bit like SQL Server's `rowversion`).

However, I'm not sure why EF Core generates a query where the outer select includes it but the inner select doesn't.

**Comment by smitpatel** [comment]
The inner select expression is `SELECT *` so EF core assumes it would be implicitly available. In this case of reference include, the related table is converted to * because of discriminator predicate causing a subquery. The explicit columns are only put together when pulling data out of the related table regardless of it being just a table or subquery.

Are there any special rules around xmin being absent in * projection? If it is then it may need special processing in provider level.

**Comment by roji** [comment]
Apologies, I didn't read the SQL close enough. By default `xmin` is indeed no included in star queries, as it's an implicit system that's always there and seldom of interest.

However, I'm not sure how I'd go about including `xmin` explicitly in the inner select with Npgsql... Any tips on that?

**Comment by orobert91** [comment]
Forgot the Discriminator part of the context modeling in my original post, it is now updated.

**Comment by smitpatel** [comment]
It turns out that this is not something providers can control directly. It is being generated here
https://github.com/aspnet/EntityFrameworkCore/blob/6281180714df2659604bce00bee793ced5788cf1/src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs#L1567-L1577

It is at the intersection of many issues. The code specifically solve #8375 for Left outer join case. The code would become more concise in #8094 . There is also a floating idea to disallow star projection fully and always expand but we haven't made decision on that. I tried to achieve that but ran into minor issue of materialization when we don't have to materialize whole entity but need to do DISTINCT on QSRE we need star projection.

But there is still hope!
@roji - Can you manually expand star projection whenever xmin is referenced?
This is how we post-process SelectExpression after translation and before compilation.
https://github.com/aspnet/EntityFrameworkCore/blob/6281180714df2659604bce00bee793ced5788cf1/src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs#L287-L291

You can identity case where xmin is being pulled out of star projection and just call `ExplodeStarProjection` on that and it should expand automatically. Let me know if you run into issues.

**Comment by roji** [comment]
@smitpatel thanks for the guidance, I'll try to find some time to look at this soon...

**Comment by roji** [comment]
BTW opened https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/271 to track as it's an Npgsql issue, you may consider closing this issue unless you wish to investigate EF Core changes related to it etc.

**Comment by smitpatel** [comment]
Thanks @roji I have subscribed to that issue so if you run into issue, I can help out.
I attempted to expand all star projections in EF Core level, and ran into binding issue (hence #10424), I am looking to fix it more appropriate way.
Another side effect which came into picture #10433 I got some ideas around fixing that too. But if you do this restrictive enough in Postgre then it should work.
Closing this as external.

**Comment by roji** [comment]
@smitpatel just to be sure I understand... are you working on avoiding star projections for cases which would include the one described above (with xmin)? If so I wouldn't really have anything to do here, right? Otherwise I'll take a look on my side.

**Comment by smitpatel** [comment]
I will be fixing making sure that `SelectExpression._starProjections` is accurate enough for all cases. Removing all star projection does not seem best idea because of smaller SQL with * projection. So eventually all the cases where explicit listing of columns needed like #10433 EF or provider could expand star projection into list. It would be similar to xmin scenario but xmin is provider specific and postgre would need to identify the case and do the necessary thing. There could be 2 ways to achieve it. 1. When translating xmin column when it is added to projection, if it is coming from star projection then expand star. This would make the SelectExpression in correct syntax all the time.
2. Another easier way could be to expand once whole query is translated at the end. Plumbing for this would be really easy (just like `JoinEliminator`). Though SelectExpression at intermediate state would be some invalid sql (but we don't run it anyway).

You can fix it in postgre at anytime. I would be fixing the binding issue next week. If you can wait till then. 😄
