### ISSUE TITLE
Question: How can I detect that a primary key will be provided in software and not by the database?

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#10415]
In my [`EfSchemaCompare`](https://github.com/JonPSmith/EfCore.TestSupport/wiki/9.-EfSchemaCompare) tool I compare the `IProperty`'s `ValueGenerated` value with the `DatabaseColumn`'s `ValueGenerated` value. One of my users of  `EfSchemaCompare` has pointed out that if the primary key is of a type where the value is provided by the software then my tool incorrectly says that there is a difference. That is because I don't spot primary keys that are provided by software.

I am therefore looking for a way to detect this, but I couldn't find anything to help. Could you suggest how I would do that.

### Steps to reproduce
entity class with non-database generated primary key
```c#
public class NormativeReference
{
    [MaxLength(50)]
    public string NormativeReferenceId { get; set; }
    public string Name { get; set; }
}
```

* The `IProperty`'s `ValueGenerated` correctly has the value `OnAdd`.
* The `DatabaseColumn`'s `ValueGenerated` (returned by the design-time service `IDatabaseModelFactory` on the database created by `Database.EnsureCreated`) correctly has the value `null`.

What I am looking for is a way to decide that the key value is set in software and not in the database. I haven't found anything in the `IProperty`, or the `IRelationalPropertyAnnotations`, nor the `IKey` information. I also looked in the `IRelationalTypeMapper` to see if that had anything, but nothing stood out.

Can you point me to how I can detect that. Thanks.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@JonPSmith When you say, " value is provided by the software" do you mean the key value is set by the application, or it is set by EF, or both?

I ask because because I don't think it is possible to detect in a provider-agnostic way where a key's values (or any other generated value) will come from. It's up to the database provider to determine the best strategy, which might be store-generated or might be client-generated by EF. Also, even if the property is configured this way, it is still possible for the application to supply an explicit value, in which case neither EF or the store will generate a value.

I suspect the best you can do without reading provider-specific metadata is to look for ValueGenerated OnAdd. This means that the property will get a value generated in some way as long as it has not been set explicitly,

**Comment by JonPSmith** [comment]
Thanks @ajcvickers. Your understanding of my question is correct, and you suggested implementation makes sense. I have two extra questions, which might allow me to produce a richer test:

1. I know that a `Guid` has a `ValueGenerator` automatically applied. Is that always done, or does it depend on the database provider?
2. If the developer adds their own `ValueGenerator<T>` to a column can I detect that?

**Comment by ajcvickers** [comment]
@JonPSmith Any "OnAdd" property on a key will need to have a value generator of some sort. There are broadly two kinds:
* Generators that immediately generate the real key value--for example, the default for GUIDs
* Generators that create temporary values that will be replaced on SaveChanges--for example, the default for ints.

So for your first question, as long as the GUID key property is OnAdd, then it will always have a value generator, but it may be a different kind of generator depending on the provider and other aspects of the model. For example, with the SQL Server provider, if the key property also has DefaultValueSql defined, then the value generator will instead generate temp values and these will be update to the real store-generated GUIDs on SaveChanges,

For the second question, yes, there should be an annotation on the property for it.

**Comment by smitpatel** [comment]
Just to chime in
I looked at the issue https://github.com/JonPSmith/EfCore.TestSupport/issues/2
It is showing difference because it is indeed mismatch between model & database.
PK are set as valuegenerated by convention. While reverse engineering, if database column does not have auto generated values, we explicitly call fluent API `ValueGeneratedNever` on the property in `OnModelCreating`

**Comment by JonPSmith** [comment]
Thanks for your input @smitpatel.

I agree that the Model and the database are different, but the idea of my tool is to report differences that suggests the database isn't in the right state for the EF Core application's model. In this case the Model/database difference is correct for the situation. I'm trying to find a way to spot this and not raise an error. 

The feedback you guys have given is great and I will attempt to update the tool to fix this. Thanks, and I am closing this issue.
