### ISSUE TITLE
Feature request - migrations add <automaticIncrementalName>

### ISSUE THREAD

**Issue by kmolerov** [dotnet/efcore#10413]
Current bahaviour:
dotnet ef migrations add -> Missing required argument '\<NAME>'.

Required behaviour:
dotnet ef migrations add -> Create new migration based on previous name with autoincremented index.
example:
Previous migration name is "migration_12". After execution command "dotnet ef migrations add", new migration is created with name "migration_13".

Use case - Business model is under development and is constantly changing. User is going to make hundreds of changes in a couple of days. User wants to continuously sync model with db schema.
There is no need to make migrations with semantic naming. 

Note: Is there a better alternative to automatically sync db schema to the data model without creating migration?

**Comment by bricelam** [comment]
Looking for #3053?

**Comment by ajcvickers** [comment]
@kmolerov As @bricelam says, the underlying motivation here seems a lot like #3053, so I'm going to close this as a duplicate. However, any solution to #3053 is likely to involve not creating explicit migrations rather than using auto-incrementing IDs. For explicit migrations, we think that using a semantic name is better practice that ID numbers. This doesn't mean you can't use numbers manually, but rather that we won't promote it by building it into the API.
