### ISSUE TITLE
Make StringBuilderExtensions public?

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#10429]
Would it be possible to make `StringBuilderExtensions` public? Especially for provider writers the methods there are useful and reimplementing/copying these doesn't make much sense.

**Comment by ajcvickers** [comment]
@cincuranet The problem is that we don't want to be in the business of shipping (and supporting) extension methods over basic types that we don't own. So for simple helpers like this we opted to make them internal. I believe other provider writers have copied the ones they use or source linked to the file in some way. @ErikEJ @roji may have more details.

**Comment by cincuranet** [comment]
Fair enough. I suppose, given it's closed now, it wouldn't make sense to discuss creating a separate NuGet package from these (i.e. `Microsoft.EntityFrameworkCore.[Shared|Extensions]`) and marking it as "internal" (with the same reasoning behind as internal namespaces), right? ;)

**Comment by ajcvickers** [comment]
@cincuranet We've discussed that in the past as well and concluded that we don't want to do that for basically the same reasons, but that if somebody in the community wanted to create and maintain such a package, then we would consider using it and potentially even contributing to it. (I say "consider" because taking a new dependency is something that can impact more than just EF, so we have to be careful.)

**Comment by cincuranet** [comment]
OK. I'll keep that in mind. Maybe later we can extract some base layer for providers.
