### ISSUE TITLE
Unable to add duplicate usernames/roles with different company IDs (Multi-tenant users/roles)

### ISSUE THREAD

**Issue by whizkidwwe1217** [dotnet/efcore#10489]
**Use case**: I'm using a multi-tenancy for my asp.net core app however, different tenants/companies are stored on the same schema and the same database. Since each tenant/company is different from each other and have no access to each other, the app should allow registering users that are unique within a company. In otherwords, it should allow saving users to the database with the same username but have different tenant/company id.
**Issue**: ASP.NET Core 2 is creating a UniqueUsername index that does not allow me to add a user with the same username. Is there another way to override this index in Code-First approach? Something like transforming this UniqueUsername index to UniqueUsername+company id, wherein the user is unique per username per company. The issue also applies to Roles.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@whizkidwwe1217 Unfortunately, the Identity framework does not support multi-tenancy. Even if you managed to get the index created appropriately, the remainder of the model and the Identity provider framework around it would still have issues. It would probably be better to write a custom Identity provider or some different approach that doesn't use Identity at all for this case, rather than trying to extend the EF provider for Identity. /cc @blowdart @HaoK

**Comment by HaoK** [comment]
You might be able to get this to work if you use a convention like {tenantId}-{userName} as the user name for identity
