### ISSUE TITLE
I want eager loading whitout  query filter, how can i do?

### ISSUE THREAD

**Issue by 2501272126** [dotnet/efcore#10550]
I want eager loading whitout  query filter, how can i do?

why eager loading use query filter default?

```
SELECT `m`.`MeetingId`
FROM `InsideAttendee` AS `m`
INNER JOIN (
    SELECT `m0`.*
    FROM `Meeting` AS `m0`
    WHERE (`m0`.`IsDeleted` = 0) AND (`m0`.`TenantId` = @___tenantId_0)
) AS `t` ON `m`.`MeetingId` = `t`.`Id`
WHERE (`m`.`IsDeleted` = 0) AND (`m`.`TenantId` = @___tenantId_0)
```

### I want like this
```
SELECT `m`.`MeetingId`
FROM `InsideAttendee` AS `m`
INNER JOIN (
    SELECT `m0`.*
    FROM `Meeting` AS `m0`
    
) AS `t` ON `m`.`MeetingId` = `t`.`Id`
WHERE (`m`.`IsDeleted` = 0) AND (`m`.`TenantId` = @___tenantId_0)
```

### use IgnoreQueryFilters result
```
SELECT `m`.`MeetingId`
FROM `InsideAttendee` AS `m`
INNER JOIN (
    SELECT `m0`.*
    FROM `Meeting` AS `m0`
    
) AS `t` ON `m`.`MeetingId` = `t`.`Id`

```

**Comment by ajcvickers** [comment]
@2501272126 It seems that you are asking for the query filter to be disabled for one entity type while still being enabled for another entity type. This is not something we plan to implement. Instead, you should either make your query filters more dynamic, or inline the filtering with the query rather than using a global filter.

**Comment by 2501272126** [comment]
I think global query filter work with Include is meaningless.
It's not include filtering.
When i including related entities, I'm not care it is soft deleted or not.
That's include filtering's work
