### ISSUE TITLE
Foreign Keys that Might not Exist

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/efcore#10614]
Hi All,
I have an EF core app that I'm building that continually mirrors certain data from a web source.  The mirroring happens one record at a time and because of that, it is normal for me to have references to objects that don't exist yet.  For example, I might have:

Locations:
{ID=1, Name="New York"}
{ID=2, Name="DC"}

Products:
{ID=1, Name="Book", LocationID=1}
{ID=2, Name="CD", LocationID=3} (Notice Location3 doesn't exist yet).

Is there a way to implement "weak" foreign keys such that the object will be pulled in if it exists but not if it doesnt?

**Comment by ajcvickers** [comment]
@TonyValenti There isn't any support for this in EF Core. However, here are some thoughts that might help:
- EF won't care that there is no Location with ID 3 for it's internal tracking--this is because there is no way to distinguish that the Location does not exist from the Location is not loaded
- A relationship/foreign key constraint can be defined in the EF model even if that constraint does not exist in the database
  - However, queries that bring in both sides of the relationship make the assumption that if there is an FK with value 3, then there will be a row with the corresponding PK, so this will likely cause issues
- Rather than mapping this as a relationship it could be mapped as a normal property, and then joins could be written explicitly using the key values
