### ISSUE TITLE
sqlite: sometimes IgnoreCase throws null exception

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#10658]
I have this table:
```
CREATE TABLE [Contenidos](
    [IDContenido] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    [Titulo] VARCHAR NOT NULL COLLATE NOCASE, 
    [TituloOriginal] VARCHAR COLLATE NOCASE, 
    [IDTipoContenido] INTEGER NOT NULL CONSTRAINT [FK_Contenidos_IDTipoContenido] REFERENCES TiposContenidos([IDTipoContenido]), 
    [Observaciones] VARCHAR COLLATE NOCASE, 
    [Año] INTEGER, 
    [Pendiente] BOOL, 
    [Valoracion] DECIMAL);

CREATE INDEX [IX_Contenidos_IDTipoContenido]
ON [Contenidos](
    [IDTipoContenido]);
```

And when I want to search by "Titulo" I use this code:

```C#
IQueryable<Contenidos> miIqContenidos = miDbContext.Contenidos;
miIqContenidos = miIqContenidos.Where(x => x.Titulo.Contains(paramCriterios.Titulo, StringComparison.InvariantCultureIgnoreCase));
return await miIqContenidos.ToListAsync();
```

It works fine. It ignores case, it is the expected behavior. If I don't use StringComparasion, it isn't case sensitive. If I don't use it, it is case sensitve. So it works as I exepect.

If I do the same with "TituloOriginal", then I get a null reference exception.

The unique difference is that "Titulo" doesn't allow null value and "TituloOriginal" allows it.

If I don't use StringComparasion parameter it works, but then it is case sensitive.

I have tried to set "TituloOriginal" to not allow null and then it works as expected and I can use StringComparasion parameter, but I would like to have this column to allow null values.

Another solution it is to use ToLower(), but I would prefer to use the StringComparation option.

My doubt is if this is a bug or for some reason StringCompartion can't be used with columns that allows null.

Thank so much.

**Comment by smitpatel** [comment]
`Contains` with no `StringComparison` parameter will translate to server as `WHERE ... IN (...)` SQL.
`Contains` with `StringComparison` parameter causes evaluation on client. 
The where clause `x.Titulo.Contains(paramCriterios.Titulo, StringComparison.InvariantCultureIgnoreCase)` is calling `Contains` method on `Titulo`. If you call it on `TituloOriginal` which can be null too then it is going to throw null-ref because you are calling `Contains` method on null object.

The exception has nothing to do with EF Core, it is expected behaviour for linq in memory. You need to make null check before calling any instance method on nullable object otherwise it is not safe.
