### ISSUE TITLE
QueryClientEvaluation in Select doesn't throw when configured to throw

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#10677]
Say I have a Post-Blog model and the Post has a member function ViewCount() (which is not a mapped property or anything like that, just a plain old member function). My Context.OnConfiguring contains:
`optionsBuilder.ConfigureWarnings(warning => warning.Throw(RelationalEventId.QueryClientEvaluationWarning));`

I would expect the following line to throw a "warning as exception, QueryClientEvaluation". Instead it quietly evaluates ViewCount() on the client:
`foreach(var count in ctx.Posts.Select(post => post.ViewCount())) { }`

During the Evaluation of ViewCount(), the post is not yet in the context (i.e. just like usual QueryClientEvaluation, and something that should never happen if I disabled QueryClientEvaluation).

Edit: Still no answer? I guess it'll be another Wednesday response of "we discussed this in triage and came to the conclusion that it's by design" :trollface:

**Comment by ajcvickers** [comment]
@Wain123 Can you explain why you want this to generate a warning? i.e. what problem would it solve?

**Comment by Wain123** [comment]
Short answer: #10471 

Long answer:
My business objects always live in a context, and they know which context they're in. Any non-trivial logic requires navigation properties, collections, change tracking and LINQ. If a BO is not in a context, it can't do anything useful.

QueryClientEvaluation breaks this, because it executes on in-memory entities outside of a context. This never happens without QueryClientEvaluation - either the query is done as SQL in the DB, or it's done following a ToList() which puts the BOs into the context.

Even if a contextless BO could figure out which context asked it to do QueryClientEvaluation, that wouldn't solve the problem, because the context would already be busy and couldn't execute another query at the same time.

Therefore, I can't support QueryClientEvaluation. The correct way for me to write that example query would be with a ToList():
`foreach(var count in ctx.Posts.ToList().Select(post => post.ViewCount())) { }`

If I accidentally write a query that gets client-evaluated, I want to make sure I notice the bug and fix it. That's why I need it to generate a warning.

**Comment by ajcvickers** [comment]
@Wain123 Thanks for the additional info. The warning was intended to identify when we execute on the client something that might result in more work (e.g. bringing back more data) being done on the client that would be ideal because we cannot translate something to be done on the store. Opaque parts of the projection are not considered part of this because they generally don’t impact the amount of work done, and also many people expect these to be evaluated on the client by-design.

Maybe it would have been better to name the warning something else, and possibly a new warning for this kind of case could be done, but as of yet it doesn't seem compelling. We can't update the existing warning to include these cases without it being a breaking change. So all in all you are correct that this is by-design.

**Comment by Wain123** [comment]
@ajcvickers Thanks for the answer, I guess I'll somehow manage to work around it... I have two questions, though:

First: Which LINQ extensions, other than Select(), will be evaluated on the client without generating a warning?

Second: Am I using EF wrong? There have now been multiple cases where I opened an issue about something that seems natural and obvious to me, but was either closed-by-design or labeled as an "obscure" feature. For example, it's very surprising to me that using navigation properties and LINQ in a member function is apparently not common. This issue has turned client evaluation into an obstacle instead of a feature for me, and while I can live with that, I'm now afraid that more serious problems might arise in some future EF version.

**Comment by ajcvickers** [comment]
@Wain123 Depends exactly what you mean by client evaluation. Obviously, if you make a projection, then creation of that projection is done on the client, but I expect you don't mean that. So can you give a rigorous definition of what client evaluation is to you and then I will attempt to find the answer. Also, what specifically do you mean by LINQ extensions? In the example above, ViewCount is client evaluated, but it isn't a LINQ extension.

To your second question, there is a fundamental problem with needing all navigations to be loaded before any method can be called on your entity when combined with attempting to call that method in a query. That problem is that query is about deciding which objects to bring back and LINQ is a fundamentally streaming API. In general, navigations cannot be considered fully loaded for a given query until the query has been fully executed and consumed.

The separation of things that are conceptually queries from things that are domain behaviors that happen after a query has loaded, possibly generating more queries, but not fundamentally part of a query, seems to be the direction that most people go. I don't know if this is natural or pragmatic, but either way it seems to be where people are before they even start asking questions. So in a nutshell, my guess is that it would help to separate behaviors into queries, which are about deciding which entities to bring back and load, from domain operations, which operate on loaded entities, possibly executing queries, but not actually being part of a query.

**Comment by Wain123** [comment]
@ajcvickers By "LINQ extensions", I mean extension methods on `IQueryable` and `IEnumerable` which are found in `System.Linq` - for example `OrderBy(...)` or `Where(...)`. I'm not sure I can give a *rigorous definition* of client evaluation without missing some special case, so I'll give you multiple symptoms which I hope describe it well enough that you know what I mean.

In the example above, `Select(...)` is client-evaluated. What I mean by that is, if you consider the following 2 versions of `Select(...)` (let's call them `SelectQ` and `SelectE` for convenience):
```
public static IQueryable<TResult> Select<TSource, TResult>(this IQueryable<TSource> source, Expression<Func<TSource, TResult>> selector);
public static IEnumerable<TResult> Select<TSource, TResult>(this IEnumerable<TSource> source, Func<TSource, TResult> selector);
```
In the original example, at compile time, I am using `SelectQ` and I am passing `(post => post.ViewCount())` as an `Expression<Func<Post, int>>` into it. If I give EF an `Expression`, I am doing so in hopes that it will translate the `Expression` to SQL - and indeed EF attempts to do so, but only at runtime discovers that it can't translate `ViewCount()`, so instead it treats `(post => post.ViewCount())` as a `Func<Post, int>` and invokes it instead of translating it. Basically, at runtime it decides to behave very much like `SelectE`, despite being a `SelectQ` at compile-time. At runtime, it decides to *evaluate* `(post => post.ViewCount())` on the *client*, just like a SelectE would do.
Now compare this to the behavior or `Where(...)`. If I pass an `Expression` to `WhereQ`, then either it will be translated to SQL, or the source will be enumerated on the client and the `Expression<Func<TSource, bool>>` will be cast to a `Func<TSource, bool>` and invoked. The crucial difference is: if `Where` invokes instead of translating, it gives me a QueryClientEvaluation warning, which `Select` doesn't.

When client evaluation happens, it creates entities (or other objects) that I didn't explicitly tell it to create, and it does so by fetching data from the database that I didn't explicitly tell it to fetch. In the example above, `ctx.Posts.Select(post => post.ViewCount())` is an `IQueryable<int>`. Therefore, if I enumerate it, I would expect only a bunch of `int` to be returned from the DB. Instead, the DB gives me a bunch of `Post`, i.e. a lot more data.
This point also makes me a bit confused in combination with your statement
> The warning was intended to identify when we execute on the client something that might result in more work (e.g. bringing back more data) being done on the client that would be ideal because we cannot translate something to be done on the store

And the final symptom: client evaluation lets my code run on entities that are not in a context. In the example above, `(post => post.ViewCount())` is invoked on a `Post` that is not attached to any context. The only code I expect to execute on an entity that is not in a context is the constructor of the entity.


I don't need all navigations to be loaded before any method can be called on my entity. I will use lazy loading of navigations as soon as you support it, and until then I will use some hacky workaround that approximates lazy loading. So, when I access a navigation property, I would like to be able to just assume that it's there, without writing code that looks like
```
if (!ItIsLoaded) {
   if (IHaveAContextToLoadItIn) {
      LoadIt();
   } else {
      OhNo();
   }
}
```

Completely separating queries from everything else would indeed avoid this problem, but I can't do that because I'm porting PLSQL code where queries are totally interconnected with logic code.

**Comment by Wain123** [comment]
@ajcvickers So, can I get an answer? I don't mean to hurry you, I just thought you might have forgotten since the issue is closed and you haven't written in 2 weeks.

**Comment by ajcvickers** [comment]
@Wain123 Ultimately I don't think that I can answer the question in the way that you are asking. I can see your perspective, but it's just not the way things are implemented right now. As I said above, we have considered changing the warning or when it is generated, but the value of doing so does not seem to outweigh the problems it will cause. In terms of being explicit about when client eval may happen without a warning, then based on your (possibly correct) definition I think it would take a long time to come up with something and my feeling is that even then it probably wouldn't be very useful, certainly to most people. If more feedback in this area indicates that others are hitting similar issues, then we will revisit, but for now I think it is what it is with regard to client evaluation and warnings.

**Comment by Wain123** [comment]
> If more feedback in this area indicates that others are hitting similar issues, then we will revisit

There are now 4 issues marked as duplicates of #10471, is that enough for you to revisit?

In particular, I would appreciate a response to this one point I mentioned in the previous post. You said:
>The warning was intended to identify when we execute on the client something that might result in more work (e.g. bringing back more data) being done on the client that would be ideal because we cannot translate something to be done on the store

And this seems inconsistent with the example I gave:
>In the example above, `ctx.Posts.Select(post => post.ViewCount())` is an `IQueryable<int>`. Therefore, if I enumerate it, I would expect only a bunch of `int` to be returned from the DB. Instead, the DB gives me a bunch of `Post`, i.e. a lot more data.

**Comment by smitpatel** [comment]
> Can you clarify whether the "bringing back more data" part of your statement applies to my example?

Bringing back in terms of size of result set rather than individual result. Suppose each row in database correspond to one row in result on client side, then a client where can get more rows from database which may not appear in result. But a client projection will fetch same amount of rows. It is true that it may fetch more data in each row but that still maintain 1:1 correspondence. Yes, it is more data but user asked us to generate result in particular way which requires fetching extra data per row (EF6 also worked this way).
