### ISSUE TITLE
Owned Type as Primary Key?

### ISSUE THREAD

**Issue by hikalkan** [dotnet/efcore#10682]
Hi,

Suppose that we have an entity like that:

````C#
public class ClientGrantType
{
    public virtual ClientGrantTypeId Id { get; set; } //primary key on the entity

    protected ClientGrantType()
    {

    }

    public ClientGrantType(ClientGrantTypeId id)
    {
        Id = id;
    }
}
````

And ``ClientGrantTypeId`` is defined as:

````C#
public class ClientGrantTypeId
{
    public virtual string GrantType { get; protected set; }

    public virtual Guid ClientId { get; protected set; }

    protected ClientGrantTypeId()
    {
            
    }

    public ClientGrantTypeId(Guid clientId, string grantType)
    {
        ClientId = clientId;
        GrantType = grantType;
    }
}
````

`ClientGrantTypeId` is owned type of `ClientGrantType` entity and I want to set `ClientGrantTypeId` type as Id of `ClientGrantType` entity.
I expect that `ClientGrantType` entity has a composite PK in the database (as ClientId, GrantType).

As I see it's not possible to define such a primary key as owned type.

* Is there a way of it?
* Is it a good practice and do you consider to allow such a definition in next releases?

**Comment by ajcvickers** [comment]
We discussed this in triage and decided that this does not fit the conceptual model for owned types, since the identity of the owned type is handled by the parent type, but it in this case the child type has the identity properties. However, it could be supported as part of #9906, and that seems like a much better fit conceptually, so closing this issue and adding a note to consider when implementing #9906.

**Comment by hikalkan** [comment]
Thank you @ajcvickers for your explanation and consideration.
