### ISSUE TITLE
Set MaxLength on TPH discriminator property by convention

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#10691]
The Discriminator column in TPH is created nvarchar(max) by default.

Can we set it to a fixed length (say nvarchar(200)) and index it globally with one setting.

Thanks

**Comment by ajcvickers** [comment]
@satyajit-behera I just sent a PR to update the docs for it: https://github.com/aspnet/EntityFramework.Docs/pull/601. Here's the update:

## Configuring the discriminator property

In the examples above, the discriminator is created as a shadow property on the base entity of the hierarchy. Since it is a property in the model, it can be configured just like other properties. For example, to set the max length when the default, by-convention discriminator is being used:

```C#
modelBuilder.Entity<Blog>()
    .Property("Discriminator")
    .HasMaxLength(200);
```

The discriminator can also be mapped to an actual CLR property in your entity. For example:
```C#
class MyContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
            .HasDiscriminator<string>("BlogType");
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    public string BlogType { get; set; }
}

public class RssBlog : Blog
{
    public string RssUrl { get; set; }
}
```

Combining these two things together it is possible to both map the discriminator to a real property and configure it:
```C#
modelBuilder.Entity<Blog>(b =>
{
    b.HasDiscriminator<string>("BlogType");

    b.Property(e => e.BlogType)
        .HasMaxLength(200)
        .HasColumnName("blog_type");
});
```

**Comment by satyajit-behera** [comment]
Thanks. This fixes for each entity individually. Is there any way where I can set it for all the discriminators across Context in one setting.

**Comment by ajcvickers** [comment]
@satyajit-behera Run through all the entity types at the end of OnModelCreating and add configuration. For example, something like this:
```C#
foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
    entityType.FindProperty("Discriminator")?.SetMaxLength(200);
}
```

**Comment by satyajit-behera** [comment]
@ajcvickers Thanks a lot

**Comment by Schuttrim** [comment]
I couldn't set the max Length using the `b.Property(e => e.BlogType).HasMaxLength(200)` syntax, ince I'm using the `ToTable(string)` Method which isn't available after using the `Entity<TEntity>([NotNull] Action<EntityTypeBuilder<TEntity>> buildAction)` Method, since it returns a `ModelBuilder` instead of `EntityTypeBuilder`.

Thats why I added the configuration right after with the following code:

`modelBuilder.Model.GetEntityTypes(typeof(Blog)).Single().FindProperty("BlogType").SetMaxLength(200);`

**Comment by ajcvickers** [comment]
Note from triage: consider using an approach like shown here: https://github.com/dotnet/EntityFramework.Docs/pull/4000, possibly using power-of-two buckets to avoid a migration on every change to discriminator value length.
