### ISSUE TITLE
Recommended context factory injection method?

### ISSUE THREAD

**Issue by kierenj** [dotnet/efcore#10694]
I'm looking to run some queries in parallel and understand that I'll need to create multiple context instances for this.  As such I'm looking to inject a factory rather that single instance.  Would you be able to give a little guidance please as to a recommended approach?

It looks like runtime context factories aren't something built-in, and the current DI helper:

https://github.com/aspnet/EntityFrameworkCore/blob/03bcb5122e3f577a84498545fcf130ba79a3d987/src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs#L142

...just registers the context type, of course.

Should I just implement my own `IEfContextFactory<TContext>` type which depends on `DbContextOptionsFactory<TContext>`?  Is there a method you guys use for this scenario?

**Comment by sam-wheat** [comment]
This might be overkill for what you want but it will certainly get the job done - [AdaptiveClient](https://github.com/leaderanalytics/AdaptiveClient) pattern demonstrates a factory pattern that disposes the context correctly after each call.  AdaptiveClient uses Autofac.


    Task<User> userTask =  client.CallAsync(x => x.GetUser(userID));
    Task<Order> orderTask = client.CallAsync(x => x.GetUser(userID));
    await Task.WhenAll(userTask, orderTask);


I suggest you take a look at the [simple console application demo](https://github.com/leaderanalytics/AdaptiveClient.SimpleConsoleDemo).

**Comment by bradmarder** [comment]
You can try this.

```
// inject IServiceScopeFactory _factory into ctor
using (var scope = _factory.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<DbContext>();
}
```

When `scope` is disposed, it will automatically dispose all instances resolved from it.

**Comment by kierenj** [comment]
Thanks sam, brad, although I'm more comfortable using a lightweight factory pattern where possible.  Injecting a service factory would seem to be taking the Service Locator pattern a step too far (at least, for me), and AdaptiveClient looks great but indeed is probably again a bit overkill for me.

I guess my point is in terms of "doing DI right", I truly am only dependent on a factory for the context.  I really need only to inject something which just creates a new context.

**Comment by sam-wheat** [comment]
>> I really need only to inject something which just creates a new context.

You might try something like this:

    Func<string,DbContext> contextFactory = connectionString => {return new DbContext(connectionString); }

    // register contextFactory with your DI container of choice

    public class MyService
    {
        private DbContext db;

        public MyService(Func<string, DbContext> dbFactory)
        {
             string connectionString = // read from config
             db = dbFactory(connectionString);  
        }
    }

**Comment by kierenj** [comment]
Thanks Sam, indeed I know I can create a factory (though I wouldn't have the consuming component have to read config - kind of the point of the factory, to take away those details).

I'm just wondering if there's a preferred or recommended method from the EF Core devs.

**Comment by flensrocker** [comment]
IMO you don't need to use DI for everything. Just `new`  the needed DbContext instances. If you need DbContextOptions or whatever from DI, feed your part of the app with that.

This is also the way to go if you need to reset the ChangeTracker of your DbContext.

**Comment by kierenj** [comment]
Ok sure - I used to use IDbContextFactory, but that's deprecated for some design-time thing.  Just checking there wasn't a replacement, really.

**Comment by jesslilly** [comment]
For others coming here from a web search, here is a cool way to register a DbContextFactory https://stackoverflow.com/a/38418080/1804678

**Comment by simeyla** [comment]
One important reason this would be necessary is for retryable transactions.

The current examples in the docs for ['Connection Resiliency'](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency) just create a new context as needed. 

It is clearly necessary not to continue with the same context if you're 'adding' items to a table, and then retrying the entire operation again if it fails - you'll get duplicates.

That's what led me here, and I'm using connection pooling so I thought perhaps there ought to be a well defined way to reset a context - especially since I know that functionality exists as that's how connection pools work!

**Comment by ajcvickers** [comment]
@simeyla Pooling is controlled via the `IDbContextPoolable` API, which is implemented explicitly by the context. However, be very careful if you intend to use this API for your own purposes. First, it's designed for pooling, not general DbContext re-use. Second, it's internal code, so it may be changed in breaking ways in later versions of EF Core.

**Comment by simeyla** [comment]
@ajcvickers Thanks for the info. Trying to stay clear of anything with 'Internal' in the name.

I'm still quite puzzled looking at the sample code for '[Resiliant connections](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency)', where they are just 'new-ing' up a context as needed. 

Obviously I realize it doesn't make sense for every sample piece of code to use every possible best practice, but it did seem odd that if you're 'advanced' enough to be concerned about connection resiliance, that you'd be using DI, likely context pooling and therefore not happy with `new context()` anymore.

Personally, I ended up injecting the `DbContextOptions<T>` object, and I'm using that to create a new context when the transactions fails (following the sample code linked to above). It just so happens that for me, the operations I have that truly require 'resiliance'  only happen every 30 seconds - so I'm not too worried about memory leaks! 

I feel like there either needs to be :

- A way to 'request a fresh' context from the pool 
- A public way to 'reset' a context - aka. `_db as IDbContextPoolable).ResetState()`
- Or better documentation if I'm missing something.

**Comment by ajcvickers** [comment]
@simeyla That code is using `new` as a convenient way to demonstrate using explicit transactions with resiliency. This isn't needed unless you're using explicit transactions--this whole section is a somewhat advanced feature. It's much more common to let EF handle the transaction for you. Further, using resiliency does not require creating a new context instance on failure, and in fact doing so would be wrong. Likewise, it's unusual to create a new context instance just because the transaction failed, but that would depend on how you intend to handle the failure.

**Comment by flensrocker** [comment]
Explicit transactions are always needed if multiple things are changed with the `UserManager` or with the `UserManager` and the `DbContext` at the same time. They appear more often than one thinks... :)

**Comment by flensrocker** [comment]
In my tests with a scoped DbContext, UserManager and SQL Server it works like expected. It will not work with a transient DbContext, of course. An official transactional API on the UserManager would be great...

**Comment by syndicatedshannon** [comment]
> Thanks Sam, indeed I know I can create a factory (though I wouldn't have the consuming component have to read config - kind of the point of the factory, to take away those details).
@kierenj 

Yes, I'm at the same place. Honestly, I need this ability to do something temporary, but I still need it. Having to refer to `new DbContext()` is challenging because we rely on various other configuration-specific steps to get a properly-configured context in production cloud, dev, and test environments, such as Azure keys and such. I really don't want to rebuild all that system-specific configuration for this temporary component.

One solution for ASP.NET Core DI; you can inject a simple model which holds the provider you have in-mind, using `Microsoft.Extensions.DependencyInjection.IServiceCollection.ServiceCollectionServiceExtensions.Add*`, e.g.

```
public override void Configure(IServiceCollection services) {
	services.AddSingleton(f => new MyProvider { Factory = f.GetRequiredService<DbContext> });
```

I think I've done this before, but I didn't verify. Sorry! Inject your provider and you have your factory. I think the only simplification missing is the ability to inject delegates directly via .NET Core DI, not sure.
