### ISSUE TITLE
EF Core Include with FromSql extension without sub SELECT

### ISSUE THREAD

**Issue by imarkevych90** [dotnet/efcore#10713]
I have some query to get companies from database like this:

```C#
var fullTextSearchVal = "test";
var sql = $"SELECT * FROM Companies WHERE CONTAINS(*, '\"*{fullTextSearchVal}*\"')";
var result = _context.Companies.Include(i => i.Address).FromSql(sql).ToList();
```

It works well, but have a little problem after I run Sql Server Profiler and check selector. It's look like this:

```sql
SELECT [i].[Id], [i].[AddressId], [i].[Email], [i].[Name], [i].[PhoneNumber], [i.Address].[Id], [i.Address].[Address], [i.Address].[City], [i.Address].[Country], [i.Address].[ZipCode]
FROM (
   SELECT * FROM Companies WHERE CONTAINS(*, '"*test*"')
) AS [i]
LEFT JOIN [Address] AS [i.Address] ON [i].[AddressId] = [i.Address].[Id]
```

The problem is in selector. Can I get query like following using Include and FromSql extensions(without sub SELECT)?

```sql
SELECT [i].[Id], [i].[AddressId], [i].[Email], [i].[Name], [i].[PhoneNumber], [i.Address].[Id], [i.Address].[Address], [i.Address].[City], [i.Address].[Country], [i.Address].[ZipCode]
FROM [Companies] AS [i]
LEFT JOIN [Address] AS [i.Address] ON [i].[AddressId] = [i.Address].[Id]
WHERE CONTAINS([i].*, '"*test*"')
```

**Comment by ajcvickers** [comment]
@imarkevych90 To a large degree the SQL passed to FromSql is opaque to EF. This is important because if EF were to try to parse it, then it wouldn't be possible to uses for cases where EF doesn't know how to parse. Based on this it is not possible in general to do the type of transformation show above. It might be possible to special case some things and transform them, but the value proposition for should a change doesn't look very favorable based on current feedback, so for now we're not planning to make changes here.

**Comment by lshrinivas-msft** [comment]
This shouldn't be a real issue, since any reasonable database query optimizer will rewrite the first query into the 2nd.
