### ISSUE TITLE
EntityEntry instance does not track changes in State

### ISSUE THREAD

**Issue by ileve** [dotnet/efcore#10798]
An `EntityEntry` instance returned by an `Add` operation, does not track correctly changes in `State`. If for example we modify the previously added record, then `State` changes to  `EntityState.Modified` but it is not tracked by the `EntityEntry` instance.

### Steps to reproduce
1. create a xunit test in Visual Studio 2017, by selecting .NET Core -> xUnit Test Project (.NET Core).
2. We execute the following commands in Package Manager Console:

`Install-Package Microsoft.EntityFrameworkCore.Tools`
`Install-Package Microsoft.EntityFrameworkCore.SqlServer`

3. We run the following unit test, after excuting the commands `Add-Migration` and `Update-Database`.

```c#
using Microsoft.EntityFrameworkCore;
using System;
using Xunit;

namespace EntityEntryTrackingStateBug
{
    public class Employee
    {
        public Guid EmployeeID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }

    class CompanySQLDbContext : DbContext
    {
        public CompanySQLDbContext() { }

        public CompanySQLDbContext(DbContextOptions<CompanySQLDbContext> options)
            : base(options) { }

         public DbSet<Employee> Employees { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string conn = "Server=(localdb)\\mssqllocaldb;Database=TRACKINGSTATE;Trusted_Connection=True;MultipleActiveResultSets=true";
            optionsBuilder.UseSqlServer(conn);
        }

    }

    public class UnitTest1
    {
        [Fact]
        void TrackingPropertiesBug()
        {
            Employee emp = new Employee
            {
                Name = "George Lucas",
                Age = 42,
            };

            //add record
            using (var context = new CompanySQLDbContext())
            {
                context.Database.ExecuteSqlCommand("TRUNCATE TABLE dbo.Employees");
                var entry = context.Add(emp);
                Assert.True(entry.State == EntityState.Added);
                Assert.Equal(1, context.SaveChanges()); //one record was added
                //modify property
                emp.Age = 44;
                //entity state is Modified but it is not tracked correctly by entry instance of EntityEntry
                Assert.Equal(EntityState.Unchanged, entry.State);
                //checking EntityEntry state via context, works correctly
                Assert.Equal(EntityState.Modified, context.Entry(emp).State);
                Assert.Equal(44, context.Entry(emp).Property<int>(e => e.Age).CurrentValue);
                //changes in property values are tracked correctly
                Assert.Equal(44, entry.Property<int>(e => e.Age).CurrentValue);
            }

        }
    }
}

```

In the previous unit test the following line should have failed, but it was successful
`Assert.Equal(EntityState.Unchanged, entry.State);`

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win7SP1x64
IDE: Visual Studio 2017 15.3.1

**Comment by ajcvickers** [comment]
@ileve EF has no way to know that Age has changed unless it runs a scan to detect the change--this is triggered by a call to `context.ChangeTracker.DetechChanges()`. EF calls DetectChanges automatically in some strategic places, but not everywhere since it can be an expensive operation. Calling `context.Entry` will cause DetectChanges to run, but not just looking at the state on an existing EntityEntry, which is why the state shows as Unchanged first and then Modified.

The obvious way to deal with this is to call DetectChanges when needed, or to always get the entry from the context rather than holding onto it. Another way its to have your entities implement INotifyPropertyChanged and configure EF to use this when building the model. This allows the entities to inform EF when a property has changed such that DetectChanges is not needed.
