### ISSUE TITLE
Query: optimize queries where operation is performed after projection

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#10811]
Reported as part of #9282 - Telerik's RadGrid (and potentially others?) produces queries that EF doesn't know how to efficiently translate - complex projection (that includes correlated collections) with filter/sorting/paging applied afterwards on on of the projected collections. This results in inefficient QM that we don't know how to properly translate, which leads to client evaluation what perhaps could be avoided.

We could recognize some of the patterns and push the operation before the projection

**Comment by MT-UE** [comment]
Getting this sorted out would allow to define some sort of "custom view" to a data model (i.e. to expose it over OData or other LINQ related client query capabilities).

**Comment by harsh-chaturvedi** [comment]
@ajcvickers  - Any updates on this backlog item?

**Comment by ajcvickers** [comment]
@harsh-chaturvedi Since this issue is in the backlog, it means it is not going to happen for the 3.0 release. We will re-assess the backlog following the 3.0 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by smitpatel** [comment]
We don't do N+1 evaluation anymore.
