### ISSUE TITLE
Query: translate stringColumn.FirstOrDefault() using SUBSTRING on SqlServer

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#10912]
query:

```
context.Customers.Select(c => c.Name.FirstOrDefault())
```

currently we evaluate this on the client, we could translate this using SUBSTRING. Same goes for LastOrDefault

**Comment by dvoreckyaa** [comment]
Hi, I am ready to work on this. Shoud it be assign on me?

**Comment by roji** [comment]
Note: we can also use LEFT and RIGHT here - not sure there's a any specific benefit but would be slightly terser.

**Comment by roji** [comment]
@dvoreckyaa feel free to submit a PR on this. Ideally yes, Cosmos support would also be implemented, but if you run into issues we can also merge support for SQL Server/Sqlite for now.

**Comment by dvoreckyaa** [comment]
@roji, thanks. I am going to use SUBSTRING (substr) for both SQL and sqlite to have more consistent code. Beacuse, as I understand, sqlite does not have left/right.
I've digged a little into Cosmos DB and implemented  this functionality, but when I was trying to run unit test, I got an error. It seems due to an unexpected (for me) mapping from net char to Cosmos DB var type. 
 `        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task String_FirstOrDefault_MethodCall(bool async)
        {
            return AssertQuery(
                async,
                ss => ss.Set<Customer>().Where(c => c.ContactName.FirstOrDefault() == 'A'),
                entryCount: 10);
        }`

This linq is converted as:
`
SELECT c
FROM root c
WHERE ((c["Discriminator"] = "Customer") AND (RIGHT(c["ContactName"], 1) = 52))`

So 0 records are returned.  Is it expected beharviour or an known issue?

**Comment by dvoreckyaa** [comment]
I am going to use SUBSTRING (substr) for both SQL and sqlite to have more consistent code. Beacuse, as I understand, sqlite does not have left/right.
I've dug a little into Cosmos DB and implemented  this functionality, but when I was trying to run unit test, I got an error. It seems due to an unexpected (for me) mapping from net char to Cosmos DB var type. 
 `        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task String_FirstOrDefault_MethodCall(bool async)
        {
            return AssertQuery(
                async,
                ss => ss.Set<Customer>().Where(c => c.ContactName.FirstOrDefault() == 'A'),
                entryCount: 10);
        }`

This linq is converted as:
`
SELECT c
FROM root c
WHERE ((c["Discriminator"] = "Customer") AND (LEFT(c["ContactName"], 1) = 52))`

So 0 records are returned.  Is it expected behaviour or a known issue?

I think it's related to #16919

**Comment by maumar** [comment]
fixed by external contribution from @dvoreckyaa in f4db6271510ebebb09aed3989c85a8460fe83839
