### ISSUE TITLE
Severed association exception on UPDATE - affected by DeleteBehavior.Restrict

### ISSUE THREAD

**Issue by piotrkolodziej** [dotnet/efcore#10954]
Hello,

I have the following one-to-many relationship:

```c#
entity
	.ToTable("OrderItem");
entity
	.HasOne<Order>()
	.WithMany(oi => oi.OrderItems)
	.HasForeignKey(oi => oi.OrderId)
	.IsRequired()
	.OnDelete(DeleteBehavior.Restrict);

public class Order
{
	public int OrderId { get; set; }
	...
	public ICollection<OrderItem> OrderItems { get; set; }
}

public class OrderItem
{
	public int OrderItemId { get; set; }
	...
	public int OrderId { get; set; }
}

public void UpdateOrder(int id, DomainModels.EditOrderModel editOrderModel)
{
	var order = GetSingleOrder(id);
	var orderItems = _mapper.Map<ICollection<DataModels.OrderItem>>(editOrderModel.OrderItems);
	order.OrderItems = orderItems;
	_orderRepository.Save();
}

private DataModels.Order GetSingleOrder(int id)
{
	var query = _orderRepository.Filter(
		0,
		0,
		null,
		o => o.OrderId == id);
	return query
		.Include(o => o.OrderItems)
			.ThenInclude(oi => oi.Offer)
		.Include(o => o.Registration)
			.ThenInclude(r => r.Guest)
		.Include(o => o.RoomRegistration)
			.ThenInclude(rr => rr.Room)
		.SingleOrDefault();
}

```

When I am trying to update a tracked order (with OrderItems included) with NEW collection I am getting the following exception:

```
Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'HotelManager.Data.HotelManagerContext'.
      System.InvalidOperationException: The association between entity types 'Order' and 'OrderItem' has been severed but the foreign key for this relationship cannot be set to null. If the dependent entity should be deleted, then setup the relationship to use cascade deletes.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
System.InvalidOperationException: The association between entity types 'Order' and 'OrderItem' has been severed but the foreign key for this relationship cannot be set to null. If the dependent entity should be deleted, then setup the relationship to use cascade deletes.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
```

 The problem does not occur when I am changing the DeleteBehavior to Cascade. I would like to understand how is it that the delete behavior affects an update operation. Since OrderItems were being loaded, shouldn't EF automatically delete old OrderItems before inserting a new collection?

### Further technical details
EF Core version: 2.0.1
Database Provider: npgsql
Operating system: macos
IDE: VS Code

**Comment by roji** [comment]
This seems like a more general EF Core question, you'd have better luck posting this at https://github.com/aspnet/EntityFrameworkCore/ (sorry, but I don't have enough time to deal with non-Npgsql-specific questions at the moment...).

If this turns out to be specifically-related to Npgsql please post back here and we'll rediscuss.

**Comment by piotrkolodziej** [comment]
Hi,

I thought I did post it to EntityFrameworkCore—I double checked. What did I do wrong?

Piotr

**Comment by ajcvickers** [comment]
@piotrkolodziej Can you please post a runnable project/solution or complete code listing that will let us reproduce the behavior you are seeing?

**Comment by piotrkolodziej** [comment]
@ajcvickers [here](https://drive.google.com/file/d/1IkCPsyqixPJMrSxq2cTdSfAfjNq924pR/view?usp=sharing) is a simple console app that isolates the issue. I've uploaded the ZIP archive to my google drive, I hope this will do. Also, to anyone who will have questions regarding this issue, I will be happy to help.

**Comment by ajcvickers** [comment]
@piotrkolodziej This is what is happening:
* The Order is queried and the two OrderItems are included into the list on the OrderItems navigation property
* The OrderItems navigation property is reset to a new list containing one new item
* EF detects this change--two items have been removed from the relationship, one item has been added
* Since the relationship is required, meaning the FK is non-nullable, then these OrderItems cannot exist without being associated with an Order--because this would require setting the FK to null
* Therefore, they can be associated with another Order, or they can be deleted
* EF normally does this delete using the DeleteBehavior.Cascade, which is the default for required relationships. 
* However, changing the DeleteBehavior tells EF to not delete the entities in this case, but instead detect this situation as, essentially, a constraint violation and throw.

**Comment by sajadghobadi** [comment]
@ajcvickers  but when i load one object with related(many side) object with simple change same as change modifiedDate, then try to update get this error.
i do not change any of related objects.
` T exist = await context.Set<T>().FindAsync(key);
            exist.ModifiedDate = DateTime.Now;
            await context.SaveChangesAsync();
            return exist;`

**Comment by ajcvickers** [comment]
@sajadghobadi Please open a new issue and post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment]
@alisufian270 Please open a new issue and post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
