### ISSUE TITLE
Disable Unique constraint before update and re-enable it after

### ISSUE THREAD

**Issue by Davilink** [dotnet/efcore#11013]
It would be nice EF Core could expose a way to drop a constraint before updating the entities and re-create it after the update with the use of a transaction to be able to rollback if the constraints can not be apply because some of the new value violate the constraint. 

if i try to update these entities, normally and exception will be thrown.

Before:
id: 1, childId: 1
id: 2, childId: 3

now:
id: 1, childId: 3,
id: 2, childId: 1

It would be event better if that could be do in the Update method of the context.

When updating context, it's save the constraint and recreate the same way it was in Database.

Context.Parent.UpdateRange(ParentList);

So EF core will translate to something like : 

1- Create transaction 
2- Get constraint for the table used by the entities that we try to update
3 - Drop the constraint
4- Update entities
5- Recreate the constraint
6- If no error, commit the transaction, otherwise rollback and throw UpdateDBException 

The other alternative is to use a dummy column (updateInProgress) that we populate with the id of the entities that we update and after the update we clear the dummy column, but it cumbersome to do manually (using the repository pattern will remove some of the cumbersomeness).

**Comment by ajcvickers** [comment]
@Davilink This is not something we are planning to implement in EF Core. Dropping and recreating constraints can be a can of worms in several ways--other constraints may need to be dropped first, permissions issues, etc. Also, even if we did this, SaveChanges would likely not work because it wouldn't be able to find a safe other to make the changes. The typical workaround is to go through an intermediate state where a temporary value is used as a placeholder and then updated in a second step.

**Comment by NullVoxPopuli** [comment]
is there a way to just disable implicit foreign key constraints entirely?

**Comment by ajcvickers** [comment]
@NullVoxPopuli EF doesn't care whether the database actually has FK constraints or not. So if you would prefer that they not be there, then you can remove them. However, if EF attempts to read data that doesn't align with your EF model, then the behavior is undefined, so you will need to be very careful to have consistent data when accessing it through EF.
