### ISSUE TITLE
Value Generated On Add or Update in Entity Framework Core does not work

### ISSUE THREAD

**Issue by luistejadaa** [dotnet/efcore#11059]
​I am having a problem when generating a default value with Entity Framework Core, it is supposed to generate a `getdate()` value but it does not work. This is what I have in my fluent Api

```
modelBuilder.Entity<Loteria>()
                .Property(p => p.FechaCreacion)
                .HasColumnType("datetime")
                .HasDefaultValueSql("getdate()")
                .ValueGeneratedOnAdd()
                .IsRequired();

            modelBuilder.Entity<Loteria>()
                .Property(p => p.FechaModificacion)
                .HasColumnType("datetime")                
                .HasDefaultValueSql("getdate()")
                .ValueGeneratedOnAddOrUpdate()
                .IsRequired();
```

​I have also tried like this

 ```
modelBuilder.Entity<Loteria>()
                .Property(p => p.FechaCreacion)
                .HasColumnType("datetime")
                .HasDefaultValueSql("getdate()")
                .IsRequired();


            modelBuilder.Entity<Loteria>()
                .Property(p => p.FechaModificacion)
                .HasColumnType("datetime")                
                .HasDefaultValueSql("getdate()")
                .IsRequired();

```

But all I get is:

[> An unhandled exception occurred while processing the request.
> 
> SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.  
> System.Data.SqlClient.SqlCommand+  
> <>c.<ExecuteDbDataReaderAsync>b__108_0(Task<SqlDataReader> result)
>
> DbUpdateException: An error occurred while updating the entries. See the inner exception for details.  
> Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch+<ExecuteAsync>d__32.MoveNext()](url)

**Comment by smitpatel** [comment]
If you want to update `FechaModification` during every update then you would need to use `HasComputedColumnSql` rather than `HasDefaultValueSql`

**Comment by ajcvickers** [comment]
@luistejada4 If @smitpatel's comment doesn't help, then can you please provide a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by luistejada4** [comment]
@ajcvickers Sorry for taking a long time to answer, but what I want to do is the following:

CreateDate: It has to generate a value at the time of creation "GetDate ()"
UpdateDate: It has to generate a value at the time of creation and when it is modified.

If I'm not wrong HasDefaultValue will only work when I do not pass any value to the column, but DateTime is a structure that will never be null and has a wrong date value at the time of the statement that is below the allowed range which is between: 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
That is why the overload of dates in the exception.

@smitpatel 
A computed value is not going to work for me since: FechaCreacion is Create Date and FechaModificacion is UpdateDate, I do not want the value to be generated, I want to store a generated value at the time of the update or add.

**Comment by ajcvickers** [comment]
@luistejada4 There currently isn't a way to do this without setting up some kind of trigger on the database. There was some discussion and suggested workarounds in #10769.

**Comment by baltermia** [comment]
seven years later and I face the exact same issue with no solution...
