### ISSUE TITLE
Comparer needed for ByteArrayTypeMapping

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#11073]
Just pointing out that ByteArrayTypeMapping doesn't currently have a comparer, and so won't detect changes properly. Based on the discussion #11071, it may be a good idea to implement a comparer internally in ByteArrayTypeMapping (and not necessarily accept an external one).

**Comment by ajcvickers** [comment]
@roji In my experience, typically byte arrays are used for binary data. This means two things:
* The byte arrays can be quite big
* It is unusual to mutate them, as opposed to swap out the byte array for a new one

Based on this we decided a long time ago that byte array properties should use reference comparison. This avoids doing an expensive deep compare in DetectChanges when it is unlikely to be helpful. For cases where you do want to mutate and save it was considered okay to explicitly mark the mutated property as modified. I thought about this again when implementing the value comparers and it still seems like the right decision, at least based on my experience, but I would certainly be open to discussing more.

However, this does remind me of one thing--when a byte array is used as a key, then we do do a structural comparison. Because it's very unlikely that a foreign key property would have the same instance as primary key property. This is ability to do a different comparison when used as a key is missing from ValueComparer--I will file an issue for this.

**Comment by roji** [comment]
@ajcvickers ok, I can see that makes sense... I tend to think that the same isn't true for arrays, i.e. that value comparison makes sense more than reference equality, what do you think?

**Comment by ajcvickers** [comment]
@roji It depends how the arrays are used, of which I don't have much experience. I expect you have seen a lot more examples than I have, so I would trust your judgement on this.

**Comment by roji** [comment]
It's hard to know... It's true that byte[], as binary data, seems to generally behave as you said. But arrays can have arbitrary element types... I can see many cases where people will have an array of string tags on their blog - it makes sense to do value comparison there I think.

Anyway, thanks for your answers.

**Comment by ajcvickers** [comment]
Agreed. It does feel like the structural comparison is much more likely to be the right thing for arrays of non-byte types.
