### ISSUE TITLE
Discriminator not exposed to Linq except by way of call to GetType

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/efcore#11150]
I have a set of classes where they are derived from a base class and used in EntityFramework Core. I use a discriminator to derive the correct class and that works fine. However I have run into the following issues:

- I cannot access the member in linq queries e.g. to filter on the class type so have to write logic that uses a call to GetType() and this in turn means Linq falls back to client side not database side logic.
- If I create a text discriminator I cannot set its length and it becomes a VARCHAR(MAX)
- I cannot join the discriminator column to other tables as a child side foreign key

EntityFramework Core v2.01 with SQL Server 2008 latest service pack.

**Comment by ajcvickers** [comment]
@MCFHTAGENTS [The documentation](https://docs.microsoft.com/en-us/ef/core/modeling/relational/inheritance) shows how the discriminator can be mapped to a CLR property and how it can be configured for things like max-length. Also, if you want to leave it as a shadow property, then it can be [accessed in queries using the EF.Property method](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties).

Having said all that, you can also use `.OfType<>` in queries as well as the `is` operator, both of which are translated rather than client evaluated.
