### ISSUE TITLE
IDbContextOptionsBuilderInfrastructure seems too esoteric

### ISSUE THREAD

**Issue by tuespetre** [dotnet/efcore#11172]
There is an interface, `IDbContextOptionsBuilderInfrastructure`, that exists solely for this purpose:

```
((IDbContextOptionsBuilderInfrastructure)optionsBuilder).AddOrUpdateExtension(extension);
```

This is kind of a weird thing to figure out while writing an extension. The `DbContextOptionsBuilder` exposes a nice set of extensibility hooks already:

- `ReplaceService<T>`
- `UseApplicationServiceProvider`
- `UseInternalServiceProvider`

These hooks keep the nice 'fluent API' spirit and are easily discoverable even though they are arguably seldom-used. Can there be a similar method, like `UseExtension<T>(T extension) where T : class, IDbContextOptionsExtension`?

**Comment by tuespetre** [comment]
Oops, let this one slip me.

I am writing an extension that provides an alternative query compiler subsystem. It needs to register some things with the service collection.

**Comment by ajcvickers** [comment]
@tuespetre That's reasonable. The reason it is done like this is because we wanted to keep it out of the API that is seen by application developers since they should never need to use this. Agreed that it is a bit ugly, but given that it is for advanced scenarios I'm not sure there is enough value in trying to put something prettier over the top of it.
