### ISSUE TITLE
Duplicate Foreign Key creation

### ISSUE THREAD

**Issue by viniciusmiguel** [dotnet/efcore#11189]
```
Table Project
{
  Guid Id;
}
Table Document
{
 Guid ProjectId;
 Guid Id;
}
```
when I try to create the composite key

```
      public void Configure(EntityTypeBuilder<Document> builder)
        {
            builder.ToTable("FAPI_SK_Documents");

            builder.HasKey(t => new {t.ProjectId , t.Id});
                 
            builder.Property(t => t.ProjectId)
                .HasColumnName("ProjectId")
                .HasColumnType("UUID")
                .IsRequired();

            builder.Property(t => t.Id)
                .HasColumnName("Id")
                .HasColumnType("UUID")
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("gen_random_uuid()");
            builder.HasOne(t => t.Project)
                .WithMany(p => p.Documents)
                .HasForeignKey(t => t.ProjectId);
        }
```
With the Foreign Key to Project
the migration is generated this way:

```
           migrationBuilder.CreateTable(
                name: "FAPI_SK_Documents",
                columns: table => new
                {
                    ProjectId = table.Column<Guid>(type: "UUID", nullable: false, 
                    Id = table.Column<Guid>(type: "UUID", nullable: false, defaultValueSql: "gen_random_uuid()"),
                    ProjectId1 = table.Column<Guid>(nullable: true),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FAPI_SK_Documents", x => new { x.ProjectId, x.Id });
                    table.UniqueConstraint("AK_FAPI_SK_Documents_Id", x => x.Id);
                    table.ForeignKey(
                        name: "FK_FAPI_SK_Documents_FAPI_SK_Projects_ProjectId",
                        column: x => x.ProjectId,
                        principalTable: "FAPI_SK_Projects",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_FAPI_SK_Documents_FAPI_SK_Projects_ProjectId1",
                        column: x => x.ProjectId1,
                        principalTable: "FAPI_SK_Projects",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });
```

I can't have this duplicate ProjectId1 on my model

### Further technical details
EF Core version: 2.0.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.0.1
Operating system: Windows 7
IDE: Visual Studio 2017 15.5.7

**Comment by viniciusmiguel** [comment]
Seems to me, a bug when I try to declare

`builder.HasOne<Project>()`
instead
`builder.HasOne(t => t.Project)`

the second one seems to resolve the problem

I can't find any documentation referring to a different behavior using generics or not.

**Comment by ajcvickers** [comment]
@viniciusmiguel When HasOne is called with no navigation property (`HasOne<Project>()`) it explicitly means this relationship does not have a navigation property. In other words, it says that even if there is a property that connects these two types, it still should not be used for the relationship. This is turn means that any such property that does exist must be part of a different relationship between the two types, which is why the additional foreign key is created. If the property should not be part of any relationship (uncommon) then it can be removed from the mapping with `[NotMapped]` or `.Ignore()`. This is documented in [the section on building relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships).
