### ISSUE TITLE
Configuring a relationship that uses Table Splitting in EF Core 2

### ISSUE THREAD

**Issue by hitaspdotnet** [dotnet/efcore#11192]
I'm trying to build my first Table Splitting in EF Core 2 using fluent configuration. <br> 
I have two simple entities named `User` and `Customer` and I want use them in single table named "AppUsers". So I created a simple entity classes for both:

**User.cs**
```C#
    public partial class User
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public Customer Customer { get; set; }
    }
```
And:

**Customer.cs**
```C#
    public partial class Customer
    {
        public long Id { get; set; }

        public Guid CustomerGuid { get; set; }

        public User User { get; set; }
    }
```
Then I make changes to `MyDbContext` as:

**MyDbContext.cs** 
```C#
    public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options)
            : base(options)
        {
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .HasOne(c => c.Customer).WithOne(c => c.User)
                .HasForeignKey<Customer>(e => e.Id);

            modelBuilder.Entity<User>().ToTable("AppUsers");
            modelBuilder.Entity<Customer>().ToTable("AppUsers");
            base.OnModelCreating(modelBuilder);
        }
    }
```
And then I created a migration using `Add-Migration "Simple_Test"` without errors. So I run `Update-Database` that worked fine without console error but when I trying to run app getting this error:

> The entity of 'User' is sharing the table 'AppUsers' with 'Customer', but there is no entity of this type with the same key value that has been marked as 'Added'

I cant understand this. I'm student just started learning about relationship configuration. Any idea please?

**Comment by ajcvickers** [comment]
@CS-beglnner The issue is that each row in the database table now contains fields from two entities--one User and one Customer. This means that every time a User is created and saved, there must also be a Customer created and saved with the same Id, because the database row cannot hold only a User or only a Customer, it must have both.

Table splitting is most often used when the row contains data about a single "thing", but you want to split that into two entity types for use in your application. For example, Product and ProductDetail--a Product always has a ProductDetail and they are saved in the same row of the database, but result in two different objects in the model.

**Comment by CS-beglnner** [comment]
@ajcvickers Thanks a lot. That's both data's is about a single thing. I'm using IdentityServer4. Server4 user entities response many useless per context query and a eShop solution need many call's to User table. So I used table splitting to make clean call with my Db. Is it wrong?

**Comment by ajcvickers** [comment]
@CS-beglnner Impossible for me to say. I would follow up with the IdentityServer people.
