### ISSUE TITLE
Should not require [NotMapped] when using a Database First development approach

### ISSUE THREAD

**Issue by jonreis** [dotnet/efcore#11231]
I am using the Database first approach generating my classes using the EF Core Power Tool extension with HandleBars.

https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools

The EF Core Power Tools generates partial classes in one set of files and I add <classname>.Partial.cs files to extend the functionality of the generated classes, by adding properties that are outside of the data model.

If I do not remember to add [NotMapped] on a particular Property in my partial class file, then I get a exception from EF during a query, or update.

It seems there should be some way of telling EF to ignore the standard convention of adding all properties to the data model. After all, the EF Core Power Tools adds all relevant properties to the modelbuilder so it should know which properties are part of the model, and which are not.

This could be an attribute that is placed on the class, or a configuration option in the model builder.

The rationale as I see it is that I don't think someone adding an extra property should cause the application to break. In a Database First approach, the model is already strictly defined, so having to remember to add [NotMapped] to properties that are not part of the model is redundant and error prone.

**Comment by ajcvickers** [comment]
@ErikEJ Do the power tools do exhaustive configuration or only where conventions would result in something different? (I'm assuming it's the latter, but the above implies that it is the former.)

**Comment by ErikEJ** [comment]
The Power Tools just wraps the EF Core reverse engineering... And sprinkles a little bit of sugar on top

**Comment by jonreis** [comment]
@ajcvickers, it looks exhaustively configured to me. Please see below:

From the following sqlite definition:

CREATE TABLE [Schema] (
[SchemaId] INTEGER NOT NULL
, [SchemaVersion] nvarchar(16) NOT NULL
, [DatabaseVersion] int NOT NULL
, [Expression] ntext NULL
, [Description] nvarchar(1024) NULL
, [ReadOnly] bit NOT NULL
, [ModifiedDateTime] datetime NOT NULL
, CONSTRAINT [sqlite_master_PK_Schema] PRIMARY KEY ([SchemaId])

EFP generates:

            modelBuilder.Entity<Schema>(entity =>
            {
                entity.ToTable("Schema");

                entity.Property(e => e.SchemaId).ValueGeneratedNever();

                entity.Property(e => e.DatabaseVersion)
                    .IsRequired()
                    .HasColumnType("nvarchar(16)");

                entity.Property(e => e.Description).HasColumnType("nvarchar(1024)");

                entity.Property(e => e.Expression).HasColumnType("ntext");

                entity.Property(e => e.ModifiedDateTime)
                    .IsRequired()
                    .HasColumnType("datetime");

                entity.Property(e => e.ReadOnly)
                    .IsRequired()
                    .HasColumnType("INTEGER");

                entity.Property(e => e.SchemaVersion)
                    .IsRequired()
                    .HasColumnType("nvarchar(16)");
            });

**Comment by ajcvickers** [comment]
@jonreis We discussed this cam to some conclusions below, but let me first explain what is going on. When a database is reverse-engineered (whether using the Power Tools or the command line) this results in a Code First model being created. Code First just means that the code represents the model--i.e. there isn't some other underlying model definition; it's just the code. Also, because partial classes are resolved into a single class by the compiler there is no way to determine that a member came from one partial or another. So, at runtime, the code generated by reverse engineering is not distinguishable from the code added afterwards.

We could consider combining an exhaustive mapping mode together with configuration of the context such that only explicitly configured types are brought in, and not anything by convention. However, this would not fundamentally change what is going on--it's still a code-based model, there still isn't inherently anything different about the code in different parts of the partial classes. Therefore, while we can certainly see your perspective on the "database first" flow, we think it is probably more beneficial in the long run to understand what is happening (code-based model) rather than adding additional configuration in an attempt to hide it and make it seem like the model is defined somewhere else. This means that there is no different "mode" and code will work the same way (sometimes needing NotMapped, for example) regardless of where the code came from. In the long run this will help keep things simpler.

**Comment by jonreis** [comment]
I think it would be reasonable in the future to have a mode that requires attributes for all database properties, or exhaustively configured. I think it would be helpful in the database first workflow, but it is not critical.

@ajcvickers , thank you for taking the time to think about it..

**Comment by cello99d** [comment]
I second this request. It would be very useful if we could tell EF that the mapping for a class is complete.
Right now, we need to include something like the following code in all our mappings to prevent the mapping of addiotonal fields by EF conventions:
foreach (var prop in typeof(Posts).GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)) {
				if (MappedProperties.Contains(prop.Name)) {
					continue;
				}
				builder.Ignore(prop.Name);
			}
This leads to our code having to scan all preoperties of the class, which is followed by EF scanning all properties again juist to detect that they have the flaf 'Ignore' set. This is work that could be completely left out.
