### ISSUE TITLE
DBSET as List in dbcontext, dynamic loading dbset from assembly (Concept Question)

### ISSUE THREAD

**Issue by Diaskhan** [dotnet/efcore#11230]
Good day friends.
It is possible to make DBSET as list ?

For example there a many dbset in DbContext And all types must defined directly
```
public class MyAppContext : DbContext
{
    public MyAppContext () : ;

    public DbSet<Table1> Table1 { get; set; }
    public DbSet<Table2> Table2 { get; set; }
    /////Many dbset references
}
```

It's possible to make this kinf of code.
1.Motivation, add entity in dbset dynamically, clear code of dbcontext!
2.Loading Entities from dynamic assembly ! Dynamic Linking!
```
public class MyAppContext : DbContext
{
    public MyAppContext () : ;
    public List <DbSet<T>> EntityList{ get; set; }

    public MyAppContext () ;
    {
     List<type> Types= Scanassebly(internal_assembly).types;

          for each(typ in Types)
          {
           list.add(typ)
          }
    }

}
```
A have seen this repo
https://github.com/bricelam/Sample-SplitMigrations
But in code of dbcontext we must have defined manually all dbset that will use !
I know about SET<T> method, but it not so comfortable to used with reflection!

**Comment by Diaskhan** [comment]
A have seen this repo
https://github.com/bricelam/Sample-SplitMigrations
But in code of dbcontext we must have defined manually all dbset that will use !

**Comment by ajcvickers** [comment]
@Diaskhan There is no need to create DbSet properties on the context in order to get entity types into the model. Instead, use an `.Entity` call on the ModelBuilder in OnModelCreating.

We have discussed in the past doing dynamic discovery for you, but ultimately decided against it, partly because scanning assemblies can be a tricky business to do correctly across all platforms. It's much easier if you know, because you control it, that certain problematic cases will not arise--for example, certain kinds of security exception in .NET Framework due to certain kinds of types in the assembly. Therefore, we leave it up to you to do the scanning, followed by a simple call to .Entity to register the type once found.

**Comment by Diaskhan** [comment]
How !!!
Acrtually I do it that way.

Just i'am searching more comfortable way to access to entityes !

```

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
			var myAssembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(@"c:\Users\TOTEM\YandexDisk\0PROJECTS\Assembly_DAL\ClassLibrary1\ClassLibrary1\bin\Debug\netcoreapp2.0\ClassLibrary1.dll");
            
             var myType = myAssembly.GetType("ClassLibrary1.Record1");
            var myInstance = Activator.CreateInstance(myType);

            // код динамически добавляет 
            
            Type[] paramTypes = { myType };
            foreach (Type type in paramTypes)
                {
                    if (type.IsClass)
                    {

                        var method= modelBuilder.GetType().GetMethod("Entity", new Type[] { });
                        method = method.MakeGenericMethod(new Type[] { type });
                        method.Invoke(modelBuilder, null);
                    }
                }
				
				   base.OnModelCreating(modelBuilder);

        }
		
		
		//And usage
		
        [HttpGet]
        public DefinitionEntity GetEntity(long id)
        {
            var myAssembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(@"C:\Users\diaskhani0112\YandexDisk\0PROJECTS\Assembly_DAL\ClassLibrary1\ClassLibrary1\bin\Debug\netcoreapp2.0\ClassLibrary1.dll");
            Type myType = myAssembly.GetType("ClassLibrary1.Record1");

            var dbSetMethodInfo = typeof(DbContext).GetMethod("Set");
            dynamic dbSet = dbSetMethodInfo.MakeGenericMethod(myType).Invoke(_context, null);
            
             dynamic Rec = Activator.CreateInstance(myType);
            ///Женерики мать его так 
            ///active не найден, нужно пробрасывать интерфейс !
            Rec.active = true;
            dbSet.Add(Rec);
            _context.SaveChanges();

            return null;

        }

```

**Comment by Diaskhan** [comment]
i guesse context.Database.Migrate(); dosent work, why I dont know !

**Comment by ajcvickers** [comment]
@febrynas You'll need to create a migration before calling Migrate will do anything.

**Comment by Diaskhan** [comment]
The main problem that when we compile assembly net core doesnt provide unload assemlbyes! And each change we must reload our net core app? Do u think is right ?

**Comment by Diaskhan** [comment]
@febrynas the main problem that I need to create not only tables, I want that migrations runs in runtime !
Creating column.deleting columns.

**Comment by febrynas** [comment]
@Diaskhan for migration at runtime you can follow code below, it will create __EFMigrationsHistory table 
context.Database.EnsureCreated();
context.Database.Migrate();

For deleting column at runtime, it is a lot of work since EF Core doesn't support automatic migration 
You can refer to this article [https://www.bricelam.net/2014/12/16/ef7-migrations-designtime.html#automatic-migrations](url)  

I think below is a good article which tell us the logic to do automatic migration, but i don't know to code this
[https://github.com/aspnet/EntityFrameworkCore/issues/6214#issuecomment-239519498](url) 

1. Compare the current model to the previous model (see step 4) using the MigrationsModelDiffer
2. Convert the resulting operations into SQL using the MigrationsSqlGenerator
3. Execute the SQL using the MigrationCommandExecutor
4. Store a serialized version of the model in the database. In EF6, we stored a gziped copy of the EDMX in the [__MigrationHistory].[Model] column. Note, there is currently no serialized model format in EF Core.

**Comment by imaa** [comment]
check  out my rep https://github.com/imaa/DynamicDbContext it's new still under development
