### ISSUE TITLE
DbContext Pooling does not dispose LazyLoader

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#11308]
https://github.com/aspnet/EntityFrameworkCore/blob/2bdb72f0206ef0f4657f565b5a5bf7226564befc/src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs#L1602

Enable pooling with above switch. 12 tests fails in LazyLoadProxySqlServerTest.
In non pooling case when we dispose context, we also dispose lazy loader. And tests verify that we throw appropriate exception.
In pooling case we are not disposing lazy loaders so the lazy loading works without exception hence test failure.

Also enable pooling for test base when fixing this issue.

**Comment by ajcvickers** [comment]
This is a known issue with pooling and lazy loading. Pooling relies on reusing services which means the scope and the therfore the lazy loader service is never disposed. However, we decided this was okay beacause it is unlikely to cause issues, and if issues do exist, then the solution is to stop using pooling.

**Comment by ajcvickers** [comment]
Updated: https://github.com/aspnet/EntityFramework.Docs/issues/501

**Comment by raymens** [comment]
We've actually ran our services with this combination for a few months. Fortunately due to our constant deployments the memory was freed due to restarts. Until we hit a slower period and we did hit the 100% memory. It took quite some figuring out, including looking at memory dumps, to see what was going on. Once the use of Pool and Proxies stood out, this issue was found quite quickly and thus also the fix.

Although the docs mention the issue of keeping state with a DbContext can be troublesome, it might help to emphasize lazy loading specifically. As this feels more like a built-in feature where you only figure out after quite some time that it's also considered state.

I've created https://github.com/dotnet/EntityFramework.Docs/pull/3472 in case anyone agrees
