### ISSUE TITLE
Non-hardcoded types (enums, plugins) and migrations

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#11324]
Yes, it's me again with more enum-related type mapping issues. PostgreSQL enum support is almost done but I've ran into a snag when trying to do migrations.

I've reached a point where everything works well as long as I create my database without migrations (`EnsureCreated()`). My TypeMappingSource has a mapping from the CLR enum to the PostgreSQL one (by communicating with the ADO.NET layer), my migrations SQL generator creates the PostgreSQL enum based on a model annotation, everything works great.

However, when generating a migration, an int column is created instead of my enum type. This happens because of [this line](https://github.com/aspnet/EntityFrameworkCore/blob/13b4f7da77f6cad405f08d9b74d4d168ad382154/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L954), which unwraps the enum type to its underlying integral type.

But the deeper issue here, is that even if I set the store type explicitly, enum support requires the application to globally map the enum, so that the TypeMappingSource can be aware of it. In other words, any mapping which isn't hardcoded into the TypeMappingSource is absent when command-line tools are executed (e.g. add migration), because they are outside the application.

The same problem will occur with any sort of external plugin modifying mappings - I'm about to add such plugins to support Nodatime, NetTopologySuite spatial support, and possibly JSON.NET, etc. So the scope here is a larger than just PostgreSQL enums.

I do realize this is really non-trivial ask - how to allow application-defined mappings to be injected into the TypeMappingSource for the command-line tools - but it does block several exciting features. What are your thoughts?

**Comment by ajcvickers** [comment]
@roji With regard to, "is absent when command-line tools are executed (e.g. add migration), because they are outside the application." This is probably a case where the application needs to implement IDesignTimeContextFactory.

The issue with global configuration and tooling is one of the reasons we have tried to avoid it. In the old stack it lead to the abomination that is DbConfiguration.

**Comment by roji** [comment]
> @roji With regard to, "is absent when command-line tools are executed (e.g. add migration), because they are outside the application." This is probably a case where the application needs to implement IDesignTimeContextFactory.

Yeah, I see what you mean, but there still has to be a place where my user says "use this type plugin", or "here's this enum mapping", and I'm not aware of one... Yeah, all this definitely goes in the direction of global configuration, and I know it's not a simple subject.

**Comment by roji** [comment]
It's OK if at the end of the day you guys say "we don't want to support this kind of scenario", although it would be a bit of a shame - the idea is to get us thinking about it (it's also obviously OK if you're busy with more important preview2 stuff...).

**Comment by ajcvickers** [comment]
@roji Are you asking about applications specifying type mappings separately from the provider, or about making sure the provider has the information it needs to setup the type mappings?

**Comment by roji** [comment]
I'm talking about applications specifying type mappings, yeah (or the provider pulling them from some application-managed place). Some examples of use:

* In my application I want database date/time types to be mapped to Nodatime instead of the built-in BCL types (e.g. DateTime)
* In my application I want a certain CLR enum type to be mapped to a PostgreSQL enum type, rather than to a database integer or string.
* In my application I want the database json types to be mapped to Newtonsoft Json.NET types, or better yet, to use Json.NET to serialize/deserialize them transparently to my own types. In other words, on my entity I have some arbitrary POCO which, when saved, will be serialized to JSON at the ADO.NET level.

All the above is actually really within reach on PostgreSQL, with the notable exception of migrations - because all the above requires the user to express that they want to do these things, and there doesn't seem to be a place for that currently when running `dotnet ef` (or the Powershell commands).

Hope that makes it a bit clearer...

**Comment by ajcvickers** [comment]
@roji We don't have a way for applications to easily set their own type mappings. We may well get to the point where we do this, but so far we have been focusing on allowing the application to change verious facets of the mapping and have that work with the provider to generate the correct mapping. This is inherently more provider-agnostic than just having the application set an explicit mapping because mappings are very provider-specific.

So, for example, if we take the Nodatime case, ideally EF should support Nodatime across all providers. This likely involves value conversions for most databases, together with a means to influence SQL translation that we don't have yet.

Now, if Postgres can natively use Nodatime types, then the provider is free to map those types by returning appropriate type mappings. Same for natively mapped enums. But that should not involve the application setting type mappings explicitly. Instead, the Postgres EF provider should generate those mappings based on being given the Nodatime or enum type to map. My understanding from our previous conversations is that the ADO.NET provider needs some configuration to make this work, and that the EF Provider would also need some global configuration, but once that configuration is done, then the application should not need to do anything else. Is that correct?

Assuming the above is correct, then for this to work in tooling, the application just needs to make sure that the configuration of the ADO.NET provider and the EF provider is run before the model is built. That would be done by the application in the implementation of IDesignTimeContextFactory. This doesn't seem bad at all--so what am I missing?

**Comment by roji** [comment]
> So, for example, if we take the Nodatime case, ideally EF should support Nodatime across all providers. This likely involves value conversions for most databases, together with a means to influence SQL translation that we don't have yet.
> 
> Now, if Postgres can natively use Nodatime types, then the provider is free to map those types by returning appropriate type mappings.

That's right - there are two ways to approach Nodatime support (in Npgsql) - doing it either at the ADO.NET level, or at the EF Core level (once you guys provide support for that). There are advantages either way - it seems cleaner to directly convert Nodatime to PostgreSQL representations and vice versa, rather than having to go through DateTime intermediaries (in some cases the impedance between all these types becomes a real problem). On the other hand clean, cross-provider support in EF Core is an attractive approach.

> Now, if Postgres can natively use Nodatime types, then the provider is free to map those types by returning appropriate type mappings. Same for natively mapped enums. But that should not involve the application setting type mappings explicitly. Instead, the Postgres EF provider should generate those mappings based on being given the Nodatime or enum type to map.

Well... I could take a reference to NodaTime (or Json.NET or whatever) from the Npgsql EF Core provider, and simply map NodaTime to PostgreSQL date/time types. This would have the following problems:
1. I'd be forcing Nodatime on people who may not want it, without any opt-in or opt-out. 
2. This is made worse in cases where there really are several legitimate options for mapping, and the provider imposes one of them without letting the user choose (e.g. NetTopologySuite vs. Microsoft.Spatial).
3. I'd be breaking backwards compatibility with all existing applications, which are written to expect DateTime rather than NodaTime.
4. I'd be adding references from my provider to lots of 3rd-party dependencies which people may not be interested in at all (e.g. spatial support with NetTopologySuite).

For these reasons, up to now I've been working under the assumption that users need to configure mappings somehow, i.e. opt into things. That's exactly the part that creates the issue for migration.

> My understanding from our previous conversations is that the ADO.NET provider needs some configuration to make this work, and that the EF Provider would also need some global configuration, but once that configuration is done, then the application should not need to do anything else. Is that correct?

That's right, some mapping configuration has to happen at both levels, although again, the problem is where this application-provided configuration (or opt-in) happens.

> Assuming the above is correct, then for this to work in tooling, the application just needs to make sure that the configuration of the ADO.NET provider and the EF provider is run before the model is built. That would be done by the application in the implementation of IDesignTimeContextFactory. This doesn't seem bad at all--so what am I missing?

Ah, maybe the misunderstand is mine - I should have read through before posting the comments above. Are you saying that an application can provide its own `IDesignTimeContextFactory`, which is instantiated and used when migration commands are executed etc? Do you have any sort of sample to point me to?

**Comment by ajcvickers** [comment]
@roji Yes--that's what IDesignTimeContextFactory is for. See the docs here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation

**Comment by roji** [comment]
That looks perfect, I wasn't aware of it... sorry for all the roundabout explaining/questioning.

I'll post back here if I encounter any more issues.

**Comment by roji** [comment]
@ajcvickers just to let you know that migrations seem to be working well with enums (barring #11368), thanks again for the guidance here.
