### ISSUE TITLE
EFCore Linq Query Could not be translated and will be evaluated locally

### ISSUE THREAD

**Issue by CodeSwimBikeRunner** [dotnet/efcore#11335]
This is more of an enhancement. I have seen other posts, and I understand there are numerous possibilities as to why a Linq Query could not be translated. However, I believe this should not only be a fairly simple enhancement, but it should serve a great many developers. Below is the warning message provided by EF Core, then the steps to reproduce the error, then the suggested enhancement.

Warning:
```
Microsoft.EntityFrameworkCore.Query:Warning: The LINQ expression 'where Invoke(__isActiveItem_0, [x])' could not be translated and will be evaluated locally.
```
```
### Steps to reproduce
```
Create a Func and predicate scenario. It can be extremely simple:
```
public static class DisplayFilters
    {
        /// the business need here is to still use the deleted item for internal reports and looking good if the client accidentally deletes the item.
        public static Func<DisplayItem, bool> isActiveItem = (x) => x.IsDeleted == false;
        .... 
       (n) number of composable filter functions. More complex functions could rely on multiple nested  functions
       ///additional pure/transparent functions could be created not just based on filtering, but grouping/joining etc
    }
```
Create a simple controller with get logic to use the function

```
using  f = namespace.DisplayFilters;
...
       [HttpGet]
        public IActionResult Get()
        {
            IEnumerable<DisplayItem> xItem = _context.DisplayItem.Where(x => f.isActiveItem(x));
            return Ok(xItem);
        }
```
```
### Further technical details
EF Core version: (2.0.2)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (Visual Studio 2017)
```

This ultimately is a simple example. But this is the start of a larger need. An application can quickly grow where all our statements are becoming more complex, and the logic for this business rule can be strewn everywhere.

Imagine dealing with dozens of linq queries, and statically referencing `x.isDeleted == false` hundreds of times, when now, the business says active items also rely on the created date property to be greater than 30 days.

Since a composable function like above will always require the object itself `DisplayItem` to be passed in, a linq to sql query should always know what `Where` clause to be modifying, what sub Select query or otherwise to modify.

Thank you

**Comment by smitpatel** [comment]
Is there any specific reason you are using `Func<DisplayItem, bool>` instead of `Expression<Func<DisplayItem, bool>>` ?

The reason I ask this because, unless the expression is passed into the linq query, the function call itself would become opaque to EF Core. The Expression tree generated by compiler when you use func does not allow us to inspect what is inside of the Func, hence EF Core cannot translate the body of the func and has to do client evaluation. If you use `Expression<Func<>>` inside linq query then EF Core would translate that to Server.

**Comment by ChristopherLClark** [comment]
I am not sure how to use `Expressions`. It does look like it could work if I fully understand them. I tried a quick snippet example to see if it would work, and I had the same problem, this could be I implemented `Expression` incorrectly. I will do more digging. Thank you for providing me this option.

**Comment by ChristopherLClark** [comment]
Okay, I'm reopening because this was close to what I needed. For the specific example `Func<DisplayItem, bool> The expression worked as follows.

usage.
```
IEnumerable<DisplayItem> xItem = _context.DisplayItem
                .Where(f.isActiveItem)
```
and then the actual expression
```
public static Expression<Func<DisplayItem, bool>> isActiveItem = (x) => x.IsDeleted == false;
```

Success! However, for another simple where clause I want to pass in a value, and get the results of the where clause. So I try.

`public static Expression<Func<DisplayItem, int, bool>> byItemOwnerId = (x, y) => x.OwnerIdFk == y;`

```           
 IEnumerable<DisplayItem> xItem = _context.DisplayItem
                .Where(f.isActiveItem)
                .Where(f.byItemOwnerId());
```
However, I cannot use byItemOwnerId like a method. I can't pass it any parameters!

**Comment by smitpatel** [comment]
Enumerable.Where takes lambda expression with one parameter which is of type of Enumerable being iterated and returns bool value. Hence you need to pass `Expression<Func<DisplayItem, bool>>` as in your first case.
In the second case, what is y? Where is that int value coming from? Where cannot accept lambda of (x,y) therefore it does not work. Creating a function which would take value of y and returns Expression<Func> may not work since parameter would not reflect actual closure of y and would not updated when sending in new value of `y`. You may need to drop down to creating lambda expression manually.

**Comment by ChristopherLClark** [comment]
My point is why should `Where` be that limited though?
 `Select * From Table as t Where t.Property = 5`
Should be exactly the same as 
`.Where( x => x.Property == 5)`
That's where the `y` is coming from. This isn't far fetched that `.Where` should accept the same parameters as `Func` since the function I'm developing is a `bool` return regardless. To me, that's what Where clauses are in SQL or any other language, its returning the Entities, Rows, etc, based on an expression that will always return true or false. Why can't I supplant that expression with an integer or even a nested query? So the ideal world would give me this.

`.Where(f.byItemOwnerId(5))`
This will still evaluate on each `Enumerable` as either true or false.

**Comment by smitpatel** [comment]
> To me, that's what Where clauses are in SQL or any other language, its returning the Entities, Rows, etc, based on an expression that will always return true or false. 

That row is the input to where clause. When you write `t.Property = 5` in SQL you are getting access to `t` which comes from the row being processed when evaluating the predicate. Same goes for Linq. The LambdaExpression inside Where takes the type being enumerated and returns bool value. When you write `Where(x => x.Property == 5) in linq, there x is of particular type and only one type.

It is not possible to write `Where((x, y) => /* return some bool value */)` in linq. You can use whatever variable you want inside `LambdaExpression.Body` in your where predicate but `LambdaExpression.Parameters` has to have only 1 parameter for it to be allowed inside `Where`. Otherwise C# compiler would complain. All other variables you use can come from outer closure or defined locally inside. (in complex case). As i  said earlier, if you need to construct such complex expression, then you may need to manually construct expression tree.

It is not EF Core which disallows you to write such where predicate. It is construct of underlying language and linq.

There is nothing actionable on EF side here. If you have questions about how to construct Expression tree like that to be passed in where predicat, i suggest asking question on stackoverflow.

**Comment by ChristopherLClark** [comment]
Thank you for taking the time to explain the issue, and provide me with enough information to research ExpressionTrees. For anyone who stumbles across this in the future, this is what I did. 

The Expression:
```
public static class DisplayFilters
    {

        public static Expression<Func<DisplayItem, bool>> byProperty(int val)
        {
            ConstantExpression constant = Expression.Constant(val, typeof(int));
            ParameterExpression iParam = Expression.Parameter(typeof(DisplayItem), "x");
            MemberExpression prop = Expression.Property(iParam, "Property"); /// be sure it's the property on the generated model.
            BinaryExpression equalTo = Expression.Equal(constant, prop);
            return Expression.Lambda<Func<DisplayItem, bool>>(equalTo, iParam);
        }
    }
```
And its usage:
```
using df = namespace.DisplayFilters;
...
        [HttpGet("GetByPropValue/{prop}")]
        public IActionResult GetAllActive(intprop)
        {

            return Ok(_context.DisplayItem.Where(
                        df.byProperty(prop)
                 ));
        }
```

This will generate the correct sql on the server side.
