### ISSUE TITLE
Take in projecting navigation collection causes N+1 queries

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#11340]
In EF Core 2.1.0-preview1-final, following select causes n+1 queries:

```csharp
var blogsWithPostTitles = db.Blogs.Select(blog => new
{
    Name = blog.Name,
    PostTitles = blog.Posts.Select(p => p.Title).Take(5).ToArray()
}).ToArray();
```

However, without ToArray() it generates only one or two queries:

```csharp
var blogsWithPostTitles = db.Blogs.Select(blog => new
{
    Name = blog.Name,
    PostTitles = blog.Posts.Select(p => p.Title).Take(5)
}).ToArray();
```

I think it would be useful, if we could do some client side transformations, like ToArray, ToList etc, without n+1 queries.

[ConsoleApp1.zip](https://github.com/aspnet/EntityFrameworkCore/files/1828580/ConsoleApp1.zip)

BTW, in the second example, I see only this generated SQL statement(in VS Diagnostic Tools ADO.NET events), which is obviously enough, since it does not select titles.:

```SQL
USE [BloggingContext];

GO

SELECT [blog].[Name], [blog].[BlogId]
FROM [Blogs] AS [blog]
```

![image](https://user-images.githubusercontent.com/3494407/37645374-f02a3e24-2c26-11e8-80bb-8f6d4d6af603.png)

**Comment by maumar** [comment]
Problem here is Take(5) - it's a current limitation of our correlated collection optimization. If you remove it, you should get two queries, with ToArray or ToList(). The reason why the second query (one without ToArray()) generated only one SQL statement is because this causes us to stream the result, i.e. no data for related Posts has been fetched yet. Once you enumerate over the PostTitles, you will see N+1 queries also.

When we translate queries that project collections, e.g. 

```
from c in customers
where c.Name != "John Doe"
select new
{
    c.Name,
    c.Products.Where(p => p.City == "London").Select(p => p.Name)
}
```

we try to split it into 2 queries, first to fetch all the necessary customer data:

```
from c in customers
where c.Name != "John Doe"
select new
{
    c.Name,
    c.Id
}
```

and second query to fetch matching products for the all those customers (in the same order:

```
from p in products
where p.City == "London"
join c in (from c in customers
              where c.Name != "John Doe"
              select c.Id) on p.CustomerId equals c.Id
select p.Name
```

and then we match them together on the client to form final result.

Problem with Take is that with current design we have no good way of putting it into the second query, because we are fetching all products at once.

**Comment by Liero** [comment]
I understand that it may be difficult to translate the IQueryables to SQL, but we should at least get damn good warning if N+1 queries suddenly appears. 
IMO, it should throw exception by default, but you are basically saying that not only I get no warning for N+1 queries, I also get lazy loading so even logs does not help me? Can the design be even more developer hostile?

**Comment by ajcvickers** [comment]
Notes from triage: 
* Putting this on the backlog to track improving this specific case
* Created issue #11380 to add warnings when EF generates n+1 queries like in this case and others

**Comment by smitpatel** [comment]
N+1 evaluation has been removed in 3.x query pipeline. We generate single SQL for both scenarios.
