### ISSUE TITLE
LoadAsync syntax on grouped query

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#11353]
I posted [this question](https://stackoverflow.com/questions/49376560/loadasync-syntax-on-grouped-query) on StackOverflow.

According to the [documentation](https://msdn.microsoft.com/en-us/library/system.data.entity.queryableextensions.loadasync(v=vs.113).aspx#M:System.Data.Entity.QueryableExtensions.LoadAsync%28System.Linq.IQueryable%29) LoadAsync "...is equivalent to calling ToList and then throwing away the list without the overhead of actually creating the list."

I don't understand how to actually use LoadAsync on a query that groups.  My objective is execute the query asynchronously and avoid the overhead of ToList.  

How would I use LoadAsync on this query?:

    var query = context.Products.GroupBy(x => x.VendorID);

    foreach(var grp in query)
	{
		...
	}

**Comment by ajcvickers** [comment]
@sam-wheat Load and LoadAsync are used to load entities into the context where they can later be referenced. This is typically used for data binding. Since the groups are part of the query results it makes no sense to use Load or LoadAsync for a GroupBy query. Or to put it another way, only use Load or LoadAsync if all that you care about is that the entities are tracked. If the specific results of the query or the specific shape of the results is needed, then Load and LoadAsync are not appropriate.
