### ISSUE TITLE
Inherited private DbSet property isn't found

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#11383]
My context has private `DbSet` properties that EF recognizes and uses. But if my context derives from some base type that has private `DbSet` properties, then the `DbSet` on the base type aren't found by EF - they remain null instead of getting initialized.

My `DbSet` need to be private because I need to wrap them with some `MyDbSet` class that has additional logic. However, I can't make `MyDbSet` derive from `DbSet`, because EF automatically constructs `DbSet`. So, instead of deriving from `DbSet`, the `MyDbSet` just wraps it. My context has a public `MyDbSet` that I use and a private `DbSet` that EF uses.

**Comment by MarcoLoetscher** [comment]
Maybe [protected](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected) works for you.

**Comment by divega** [comment]
__EF Triage:__ at first glance it seems that we could enable this. Assigning to @ajcvickers to get this opinion.

**Comment by ajcvickers** [comment]
Honestly, I didn't remember that we enabled private DbSet properties at all! Yes, we could also look on the base class for private properties. However, we have generally avoided doing anything much to enhance DbSet property discovery because it is so easy to do your own thing in your context by calling `context.Set` to create the DbSet and use in any way it can be desired.

Marking for re-triage. I'm fine with this going on the backlog as an enhancement (and probablu up-for-grabs) but I'd also be fine with just closing it and saying use `context.Set` to create DbSets wherever they are needed.

**Comment by ajcvickers** [comment]
Discussed in triage and we're not going to do this because the value seems very minimal. However, if anybody in the community wants to send a PR to add support for this, then we would take a look and would likely accept such a PR.
