### ISSUE TITLE
How to enumerate grouped query asynchronously?

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#11400]
[Related question](https://github.com/aspnet/EntityFrameworkCore/issues/11353)

My table is too large to load into memory in one gulp.  I would like to enumerate the query asynchronously.  How do I do that? 

	public virtual async Task GetSeriesTags(Func<List<DTOSeriesTag>, Task> func, int takeSize)
	{
		var query = db.DTOSeriesTags.GroupBy(x => new { x.CreatedDate, x.GroupID, x.Name, x.Notes, x.Popularity })
			.OrderBy(x => x.Key.GroupID).ThenBy(x => x.Key.Name); // nay nay .ToListAsync();

		List<DTOSeriesTag> tags = new List<DTOSeriesTag>(takeSize);
		int counter = 0;

		foreach (var grp in query) // UI freezes here
		{
			tags.Add(grp.First());

			if (counter++ % takeSize == 0)
			{
				await func(tags);
				tags = new List<DTOSeriesTag>(takeSize);
			}
		}
		
		if(tags.Any())
			await func(tags);
	}

**Comment by divega** [comment]
@sam-wheat can you try with `ForEachAsync`? If the query is translated to the server and we can stream, then that should help. Otherwise, if we need to bring all the results to the client, then you may run out of memory.

If that happens, consider writing the GROUP BY yourself in SQL, pass it to `FromSql` taking advantage of the new [query types feature](https://docs.microsoft.com/en-us/ef/core/modeling/query-types).

**Comment by sam-wheat** [comment]
Excellent, thanks very much.
