### ISSUE TITLE
Can not link two table

### ISSUE THREAD

**Issue by tttrrryyyyeer** [dotnet/efcore#11423]
How can I link two tables by foreign key. I tried Sqlite and mysql, but I get null in the data model. Specified attributes [ForeignKey("Id")] and try through the fluent api.

**Comment by ralmsdeveloper** [comment]
Put here your Fluent API configuration and its Models.

**Comment by cinik89** [comment]
[Table("RecyclePoint")]
    public class RecyclePoint
    {
        [Key]
        public int Id { get; set; }
        public int LocationId { get; set; }
        [ForeignKey("LocationId")]
        public Location Location { get; set; }
        public IEnumerable<RecycleType> Types { get; set; }
        [JsonConverter(typeof(StringEnumConverter))]
        public Days WorkDays { get; set; }
        [ForeignKey("CompanyId")]
        public Company Company { get; set; }
    }

-----------------------------------------------------------------------

protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RecyclePoint>()
                .HasOne(p => p.Location)
                .WithOne()
                .HasForeignKey("RecyclePoint", "LocationId")
                .IsRequired();

            base.OnModelCreating(modelBuilder);
        }

For example.

**Comment by cinik89** [comment]
In the dotnet framework 4.6 this code works without problems without using fluent api.

**Comment by smitpatel** [comment]
@cinik89 - What is the error from code? Can you post relevant code?

**Comment by divega** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).
