### ISSUE TITLE
Dbcontext opens new connection for every query in one request.

### ISSUE THREAD

**Issue by rkdrnfds** [dotnet/efcore#11496]
For every query in one injected dbContext, it opens new connection.

How can I provide one opened connection for dbcontext to avoid such overheads for opening / closing multiple connections?

Environments:
 EF Core: 2.1.0-preview1
 Data Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.1.0-preview1

**Comment by roji** [comment]
Unless you've disabled pooling (by setting `Pooling=false` in your connection string), opening and closing connections has negligible overhead and there shouldn't be any reason to avoid it. When a connection is closed it is returned to the pool, and when one is opened it is taken from the pool. This is the default/recommended way to work, rather than trying to implement your own connection reuse.

Npgsql (and other ADO.NET drivers) has a high-performance pool (the upcoming 4.0 version improves performance even more in this area).

**Comment by rkdrnfds** [comment]
Thanks for reply. It had very little overhead indeed.
