### ISSUE TITLE
Rerun Migrations Issues.

### ISSUE THREAD

**Issue by AlexAslam** [dotnet/efcore#11580]
If you run migrations more then one time then it will give you an error say this table is already exists. There is no validation in the code. It just put long lengthy errors.

**Comment by ajcvickers** [comment]
@AlexAslam Migrations can generate [idempotent scripts](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/) if you need them. If this isn't what you are looking for, then please provide all the information asked for in the issue template (see below) so that we can effectively understand and reproduce the issue you are seeing.

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by AlexAslam** [comment]
Seriously Guys, the thing is I run migrations multiple times on the specific context, then migration on specific context will give me the error table already exists in the database. I try to find solution of this error on the net but what I find is many guys facing this issue.

Please try to understand what I’m talking about.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by anpete** [comment]
@AlexAslam This is not how Migrations works. If you apply Migration A to Database A and then try and apply the migration again, it will be a no-op - We store a list of applied migrations in a table in the target database.
