### ISSUE TITLE
Dbcontext options issues for another dbcontext.

### ISSUE THREAD

**Issue by AlexAslam** [dotnet/efcore#11583]
I cant customize the code of migration. I want to migrate one dbcontext and other dbcontext automatively run migrations. But there is no option for that. I cant fetch all the dbcontext dynamically. I cant run migrations on other dbcontext by run migrations on one dbcontext.

**Comment by ajcvickers** [comment]
@AlexAslam Please provide all the information asked for in the issue template (see below) so that we can effectively understand and reproduce the issue you are seeing.

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by AlexAslam** [comment]
I want to migrate one dbcontext on the migration of another dbcontext. I find nothing about in docs or from internet. There is no way to edit the code for migration. And there is no generic way to get all the dbcontexts from the main dbcontext class.

And if I didn’t find any solution of this so how could I provide you the code?

Please Help me on this.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ajcvickers** [comment]
@AlexAslam 
* "I want to migrate one dbcontext on the migration of another dbcontext." I don't know what this means, so I am unable to answer.
* "There is no way to edit the code for migration." Migrations can be edited just like any other code file.
* "And there is no generic way to get all the dbcontexts from the main dbcontext class." There is nothing built in to EF to do this, since it doesn't seem to be an EF concern, but you can always just use normal Reflection in .NET.
