### ISSUE TITLE
Schema based database.

### ISSUE THREAD

**Issue by AlexAslam** [dotnet/efcore#11581]
In dbbuilderoptions, there is no schema options. There is no full access to the database. No database create functions, no proper database validation options. I know about the database.ensureCreated function, but i didn't find any usefull. You people need to work on database access like whole of the tables in schema or give schema in connection string.

**Comment by ajcvickers** [comment]
@AlexAslam Please provide all the information asked for in the issue template (see below) so that we can effectively understand and reproduce the issue you are seeing.

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by AlexAslam** [comment]
I want to use customly make schema except the public schema of the database for my specific block of users. But DbOptionBuilder didn’t give the full options for this. Currently ef core allow us use public schema but I want to use my own created schema, your ef core didn’t allow to do this.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by anpete** [comment]
Did you see https://docs.microsoft.com/en-us/ef/core/modeling/relational/default-schema?
