### ISSUE TITLE
There is no schema based access to the database.

### ISSUE THREAD

**Issue by AlexAslam** [dotnet/efcore#11584]
There is no any options to access the schema of the database. And there is no db acesss to schema create update validations nothing functions.

**Comment by ajcvickers** [comment]
@AlexAslam Please provide all the information asked for in the issue template (see below) so that we can effectively understand and reproduce the issue you are seeing.

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ajcvickers** [comment]
@AlexAslam Migrations will create the schema if one is specified in the model.
