### ISSUE TITLE
There is no table validation.

### ISSUE THREAD

**Issue by AlexAslam** [dotnet/efcore#11582]
There is no database table validations if it exists in database or not.

**Comment by ilmax** [comment]
@AlexAslam  What you mean with "there is not database table validations...."? Can you provide a code example and your expectations?

**Comment by AlexAslam** [comment]
Actually I want to run migration on DbContext by the .net core code. And I need to validate the table if it exists in the database or not. And I didn’t find any code and docs about this kind of database validation. And how could I provide the code if I didn’t find any solution of it?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ajcvickers** [comment]
@AlexAslam Migrations can generate [idempotent scripts](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/) if you need them. If this isn't what you are looking for, then please provide all the information asked for in the issue template (see below) so that we can effectively understand and reproduce the issue you are seeing.

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by AlexAslam** [comment]
I was not talking the migrations, I was talking the validate on database whether the specific table is in the database or not. Like I have created the database in PostgreSQL and now I want to write code to go in the table and find the required details, but this thing will give the error if table is not exists in the database.
Again I’m not talking about migrations.
Im Talking about Database whether the specific table is exists in the database or not. <=========== need help on this.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ajcvickers** [comment]
@AlexAslam EF does not check for table existence at runtime because it would kill performance. Use Migrations or some other database management flow to ensure that your database schema is up-to-date.
