### ISSUE TITLE
2.1-preview2 - breaking changes?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#11632]
Just updated SQLCE provider from 2.1 preview1 to 2.1 preview2..

Had to change a couple of files - are these "breaking changes" ?? (Just a heads up)

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/15a43663d3712b388530e90c518ce21259b98716

**Comment by Eilon** [comment]
Was this a "breaking change" from preview1 to preview2? If so, we don't generally consider those breaking changes. But if it was a breaking change from 2.0.x, that's another story...

**Comment by ajcvickers** [comment]
@Eilon We have reviewed them and there is nothing concerning here--will reply in detail soon.

**Comment by ErikEJ** [comment]
I understand, this was just fyi, since I discovered breaking chsnges when moving from 2.0 to prewiev1

**Comment by ajcvickers** [comment]
@ErikEJ Details:
* IProviderCodeGenerator was only added in 2.1, so rename is okay
* Likewise for UseProviderMethod
* The interesting one is SqlCeConventionSetBuilder.cs. In [this PR](https://github.com/aspnet/EntityFrameworkCore/pull/10900) we introduced a new pattern for doing this which avoids using internal code and will therefore not break when internal code changes. It would be great if you could update to use this pattern. In the meantime, since other providers may still be using the old pattern we will investigating reverting this change to the internal code.

**Comment by ajcvickers** [comment]
@ErikEJ Actually, looks like you must have already updated that code for preview1, so the additional break is a preview1 to preview2 change, and hence is okay. 2.0 code should not be broken. Would still be great if you could use the new pattern!

**Comment by ErikEJ** [comment]
Thanks - fixed!
