### ISSUE TITLE
Inconsistent collection navigation property projection

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#11631]
_From @joshmouch on April 11, 2018 15:1_

I have the following in latest versions of EF Core:

```
var entityOnes = await dbContext.EntityOnes.Where(blah)
    .Include(a => a.EntityTwos)
    .Include(a => a.EntityThrees)
    .ToListAsync();
```

After this executes, the following works fine, as expected:

```
var test = entityOnes[0].EntityTwos[0].EntityThrees[0];
```

However, the following could possibly throw a null exception because the `EntityThrees` property is null:

```
var test = entityOnes[0].EntityTwos[1].EntityThrees[0];
```

It seems like the `EntityThree` collection property only gets set if there are values to add to the collection.  If the collection is empty, then it leaves the property null.

This seems like inconsistent behavior to me.  I'm initializing these properties as null as a safeguard to let me know if EntityFramework has already projected values onto the relationship or not.

For example, if the following throws a null exception, then I know that I forgot to add EntityTwo as an Include() in EF query:
```
var test = entityOnes[1].EntityTwos[0];
```

_Copied from original issue: dotnet/core#1426_

**Comment by divega** [comment]
_From @Petermarcu on April 11, 2018 16:24_

@divega

**Comment by ajcvickers** [comment]
@joshmouch Putting the two snippets together, it looks like EntityThrees must exist both on EntityOne (otherwise the Include calls would not compile) and on EntityTwo (otherwise the `test =` line would not compile.) Given this, the EntityThrees on EntityTwo is not getting included. Now, if some of the EntityThree instances are also related to EntityTwo instances, then the state manager will fix those up, including populating the navigation property, but if there are none, then it will do nothing. Conversely, if you actually include the EntityThrees on EntityTwo, then Include will ensure that the navigation is non-null even if there are no entities in it. For example:
```C#
var entityOnes = await dbContext.EntityOnes.Where(blah)
    .Include(a => a.EntityTwos)
        .ThenInclude(e => e.EntityThrees)
    .Include(a => a.EntityThrees)
    .ToListAsync();
```
