### ISSUE TITLE
If some of navigation properties contains wrong id - ef makes whole entity null

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#11658]
Hi. I'v spent HOURS to find out what the ... going on with it. I see no any logic in this. Why EF returns null on FirstOrDefaultAsync, FirstAsync and seems generally filters it out when it has a wrong navigation to another table(with id that doesn't exist there)? Why don't just leave the navigation property null?

UPD: it does the same if the navigation was filtered by HasQueryFilter

I'm using .net core 2.0 and ef core must be the same

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by 777olexandr** [comment]
Hi. Steps are easy:

1. create an entity containing single navigation property to another entity, by making one-to-many relationship with no reverse navigation property on that side( like WithMany() )
2. load database with one element of data that has wrong(non-existent) Id for the navigation into the first table
3. query the first table
4. that's it. You will receive null value, or empty list just because the navigation property contains Id to the second table where is no such row. Also EF as I remember makes INNER JOIN to that table. In other words EF hides the row from the first table even though it actually exist! 

The same goes when navigation property contains a relation to the row in second table which was filtered by HasQueryFilter. Like in my case, the second table has property indicating whether to show it for current domain: EnabledOnDomains which gets used in filtering in EF configuration file.

Sorry for my bad English. I have problems with those articles and trying to explain myself fast now.
