### ISSUE TITLE
Support of immutable "Owned Entity Types"

### ISSUE THREAD

**Issue by Rookian** [dotnet/efcore#11774]
I have the following immutable class:

```
public class Cost
{
    public decimal PurchasePrice { get;  }
    public decimal EstimatedRetailPrice { get;  }
    public decimal SalesPrice { get;  }

    public Cost() {}

    public Cost(decimal purchasePrice = 0, decimal estimatedRetailPrice = 0, decimal salesPrice = 0)
    {
        PurchasePrice = purchasePrice;
        EstimatedRetailPrice = estimatedRetailPrice;
        SalesPrice = salesPrice;
    }
}
```
If I just use `modelBuilder.Entity<Order>().OwnesOne(x => x.TotalCost)` EF won't recognize my readonly properties (`TotalCost `is of type `Cost`).

To use my immutable `Cost `class I wrote the following extension:

```
public static class EntityTypeBuilderExtensions
{
    /// <summary>
    /// Allows an immutable object to be defined as an 'Owned Entity Type' in EF .
    /// </summary>
    /// <typeparam name="TEntity"></typeparam>
    /// <typeparam name="TRelatedEntity"></typeparam>
    /// <param name="entityTypeBuilder"></param>
    /// <param name="expression"></param>
    public static void OwnsOneImmutable<TEntity, TRelatedEntity>(this EntityTypeBuilder<TEntity> entityTypeBuilder, Expression<Func<TEntity, TRelatedEntity>> expression)
        where TEntity : class
        where TRelatedEntity : class
    {
        var constructor = typeof(TRelatedEntity).GetConstructor(Type.EmptyTypes);
        if (constructor == null)
            throw new InvalidOperationException($"Class '{typeof(TRelatedEntity).Name}' does not contain a parameterless constructor.");

        var builder = entityTypeBuilder.OwnsOne(expression);

        var fieldInfos = typeof(TRelatedEntity).GetFields(BindingFlags.NonPublic | BindingFlags.Instance).ToList();
        var propertyInfos = typeof(TRelatedEntity).GetProperties(BindingFlags.GetProperty | BindingFlags.Instance | BindingFlags.Public);

        foreach (var propertyInfo in propertyInfos)
        {
            var fieldInfo = fieldInfos.Single(x => x.Name == $"<{propertyInfo.Name}>k__BackingField");
            builder.Property(propertyInfo.PropertyType, propertyInfo.Name).HasField(fieldInfo.Name);
        }
    }
}
```

But EF still throws an exception `Field '<EstimatedRetailPrice>k__BackingField' of entity type 'Cost' is readonly and so cannot be set.`

Please support immutable 'Owned Entity Types'.

**Comment by ajcvickers** [comment]
@Rookian This is because the code generated by the compiler marks the backing field as read-only. This means that building and compiling an expression tree to set the field value will still fail--the expression compiler won't let the value of a read-only field be set. It would be possible to set the field by pure Reflection, but doing so would be a big perf hit, and since this is very perf sensitive code that would often result in a bad experience. Also, it would be making an end-run around the efforts of the compiler to prevent this happen.

The workaround for his compiler limitation is to make the fields not read-only. This can be done by adding private setters, or by declaring the backing fields explicitly and not marking them as read-only.

**Comment by ajcvickers** [comment]
@Rookian Also, you can try removing the parameterless constructor--this should allow EF to map the entity and create instances of it so long as there is never attempt to actually modify it--that will throw. See discussion on #10703 and issue #11457
