### ISSUE TITLE
New Many to Many relationship record uses same record for both parent and child

### ISSUE THREAD

**Issue by Metritutus** [dotnet/efcore#11786]
I'm attempting to set up a Many to Many relationship in EF Core, but for some reason it's using the same record for both the parent and the child, discarding one of the new records I'm trying to create.

I've only found one other reference to what sounds like the same issue, [here](https://github.com/aspnet/EntityFrameworkCore/issues/10698#issuecomment-366546939), but it doesn't look like they posted an issue about it.

Anyway, I've gone ahead and replicated it in a small .NET Core 2.1 Console App project, and the source code is below.  I'm following a database first approach, and I mostly generated the context and model classes below using `Scaffold-DbContext`, however I did rename some of the properties containing multiple entities, just in case anyone is wondering why they don't quite match up with the names of the tables, and why I'm using `entity.ToTable()`.  Everything else is as it was originally generated.

I'm fairly new to Entity Framework Core, and indeed Entity Framework itself, so it's possible this is due to something I've done incorrectly, but I've no idea what that may be.

SQL Script for creating the tables:
```SQL
CREATE DATABASE EFCoreRelationshipTest
GO

USE EFCoreRelationshipTest

 CREATE TABLE [MainRecord]
    ([Id]   INTEGER IDENTITY    NOT NULL    PRIMARY KEY,
    [Value] VARCHAR(MAX)        NOT NULL
)

CREATE TABLE [MainRecordLink]
(
    [Id]                        INTEGER IDENTITY    NOT NULL    PRIMARY KEY,
    [ParentMainRecordLinkId]    INTEGER             NOT NULL    FOREIGN KEY REFERENCES [MainRecord]([Id]),
    [ChildMainRecordLinkId]     INTEGER             NOT NULL    FOREIGN KEY REFERENCES [MainRecord]([Id])
)
```

The two models:
```cs
public partial class MainRecord
{
    public MainRecord()
    {
        MainRecordLinkChildMainRecordLinks = new HashSet<MainRecordLink>();
        MainRecordLinkParentMainRecordLinks = new HashSet<MainRecordLink>();
    }

    public int Id { get; set; }
    public string Value { get; set; }

    public ICollection<MainRecordLink> MainRecordLinkChildMainRecordLinks { get; set; }
    public ICollection<MainRecordLink> MainRecordLinkParentMainRecordLinks { get; set; }
}
```

```cs
public partial class MainRecordLink
{
    public int Id { get; set; }
    public int ParentMainRecordLinkId { get; set; }
    public int ChildMainRecordLinkId { get; set; }

    public MainRecord ChildMainRecordLink { get; set; }
    public MainRecord ParentMainRecordLink { get; set; }
}
```

The context (although I've removed the server name, userid and password):
```cs
public partial class EFCoreRelationshipTestContext : DbContext
{
    public virtual DbSet<MainRecord> MainRecords { get; set; }
    public virtual DbSet<MainRecordLink> MainRecordLinks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer("Server=;Database=EFCoreRelationshipTest;User ID=;Password=;");
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MainRecord>(entity =>
        {
            entity.ToTable(nameof(MainRecord));

            entity.Property(e => e.Value)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<MainRecordLink>(entity =>
        {
            entity.ToTable(nameof(MainRecordLink));

            entity.HasOne(d => d.ChildMainRecordLink)
                .WithMany(p => p.MainRecordLinkChildMainRecordLinks)
                .HasForeignKey(d => d.ChildMainRecordLinkId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MainRecor__Child__1367E606");

            entity.HasOne(d => d.ParentMainRecordLink)
                .WithMany(p => p.MainRecordLinkParentMainRecordLinks)
                .HasForeignKey(d => d.ParentMainRecordLinkId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MainRecor__Paren__1273C1CD");
        });
    }
}
```

And this is the code itself that actually replicates the issue.  I've got two versions of this.  The first, creates just one `MainRecord` record, and a `MainRecordLink` record that has the Id of that `MainRecord` for both the `ParentMainRecordLinkId` and the `ChildMainRecordLinkId`.

Now my understanding is that I should only need to call the `Add` function for one of my entities, and any new records that I'm also adding in relation to that entity will also be added when `SaveChanges()` is called.  In case I was wrong though, I also tried this:

```cs
static void Main(string[] args)
{

    var context = new EFCoreRelationshipTestContext();

    var mr = new MainRecord() { Value = "Record 1" };
    var mr2 = new MainRecord() { Value = "Record 2" };

    mr.MainRecordLinkChildMainRecordLinks = new List<MainRecordLink>()
    {
        new MainRecordLink()
        {
            ParentMainRecordLink = mr,
            ChildMainRecordLink = mr2
        }
    };

    context.MainRecords.Add(mr);
    context.MainRecords.Add(mr2);
    context.SaveChanges();

    Console.Write("Press any key to continue . . . ");
    Console.ReadKey();
}
```
This one does create two `MainRecord` records, but the `MainRecordLink` record it creates still uses the Id for the first `MainRecord` record that gets created, for both the parent and the child.

Am I doing something wrong here or is this a bug of some kind?  I'm kind of hesitant to assume it is a bug because of my newness to this.

**Comment by smitpatel** [comment]
```
mr.MainRecordLinkChildMainRecordLinks = new List<MainRecordLink>()
    {
        new MainRecordLink()
        {
            ParentMainRecordLink = mr,
            ChildMainRecordLink = mr2
        }
    };
```
This piece of code is conflicting.
Navigations `MainRecord.MainRecordLinkChildMainRecordLinks` & `MainRecordLink.ChildMainRecordLink` are part of 1 relationship. So when you add a `MainRecordLink` to `MainRecordLinkChildMainRecordLinks` collection, it will set `MainRecordLink.ChildMainRecordLink` navigation to pointing to `MainRecord`.
In your case, this means that while setting collection for `mr`, `MainRecordLink.ChildMainRecordLink` gets set to `mr` due to collection navigation, which is different from `mr2` so it gets overridden and you are left with `MainRecordLink` with both parent, child pointing to `mr`

**Comment by Metritutus** [comment]
@smitpatel Following reading your post, I've adjusted my code so that it works, but I'm still a but fuzzy as to why.

If I replace `MainRecordLinkChildMainRecordLinks` with `MainRecordLinkParentMainRecordLinks`, the code works as expected.  If I do use `MainRecordLinkChildMainRecordLinks`, I can set the parent, but not the child.

The weird thing with the old code though, is  the values I'm seeing in the debugger.  Before `context.MainRecords.Add(mr)` is called, the parent and the child records show as 'Record 1' and 'Record 2', respectively.  Once it's called, they're both 'Record 1'.

Alternatively, if  `context.MainRecords.Add(mr)` is called before setting `MainRecordLinkChildMainRecordLinks`, the parent and child records again show as 'Record 1' and 'Record 2', this time until `SaveChanges()` is called.


Is there any documentation you can recommend that explains what's going on here?  Or is this all fundamental data management knowledge that I should just know when working with this?

**Comment by smitpatel** [comment]
Essentially, when you set one side of navigation or FK property value, you are configuring a relationship between 2 entities. So when you added `MainRecordLink` (let's call it `link`) to `mr.MainRecordLinkChildMainRecordLinks` you defined the relationship. Since `link` & `mr` are connected through `MainRecordLinkChildMainRecordLinks` collection, `link.ChildMainRecordLink` which is inverse navigation of the collection navigation you set, will be set to point at `mr`. So that both navigation define same relationship.

In your `MainRecordLink` definition, you are setting `ChildMainRecordLink` to point to `mr2`, thinks work if you add that `MainRecordLink` to `mr2.MainRecordLinkChildMainRecordLinks`.

All these happens, because you are setting both navigations of a single relationship to point to different entities. So when you fix things up, one of the navigation win and the other conflicting one will be set to a different value. Hence you see incorrect records set. So best thing to do would be, set only one side of navigation and let EF fix up the other side for you.

The debugging experience you are seeing is because EF Core will `DetectChanges` and fix up navigation only when you call `SaveChanges`. This is done for perf. If you manually call `DetectChanges`, you would see the values are getting changed at that point.
