### ISSUE TITLE
Data migrations command file with an error in asp.net core 2.0.6

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#11798]
From VS Feedback:

I have been getting ef core data migrations command error and i have searched the community forums but did not find any solution but most of them have suggested to add missing reference file in csproj file but i did not any of them is missing from my csproj file but still error popups. I have attached/snipped in csproj file for reference. Any suggestions?

![image](https://user-images.githubusercontent.com/1430078/39199376-2cca729e-479e-11e8-8a13-d34b94b8dc72.png)

**Comment by smitpatel** [comment]
Most likely this is due to incorrect directory. In VS the default directory of PMC is the dir where solution lives. When invoking PMC commands, VS uses the project from Default Project drop down menu alongwith startup project set in VS. So even though you are not in project directory they work. When invoking `dotnet ef`, it does not interact with VS in anyway. Hence you need to invoke command from the directory where your project file (.csproj containing Tools.DotNet package) lives.

With global tools coming in 2.1, you can invoke dotnet ef in any directory but to use it to do ef related task, you would still need to invoke it in directory of the project which contains reference to EFCore.Design package.
