### ISSUE TITLE
Migration Table name override not honored

### ISSUE THREAD

**Issue by snovak7** [dotnet/efcore#11843]
First I create my custom DbContext

```c#
public class DbContext : 
    IdentityDbContext<User, Role, Guid, UserClaim, UserRole, UserLogin, RoleClaim, UserToken> {}
```

My User looks like this

```c#
[Table("MyCustomUser", Schema = "users")]
    public class User : IdentityUser<Guid> {}
```

I setup environment that I can generate my migration code.
For the test case I included Schema, which worked...

```c#
            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                schema: "users",
```

```c#
                    b.ToTable("AspNetUsers","users");
```

### Further technical details
EF Core version: 2.0.2-rtm
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Npsql.EntityFrameworkCore.PostgreSQL
Operating system: MacOS High Sierra 10.13.4
IDE: dotnet cli for Migrations, Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.5 Preview (7.5 build 1222)

**Comment by smitpatel** [comment]
Identity defines the schema and configuration in `OnModelCreating`. One of those thing is setting table for `ApplicationUser` to `AspNetUsers`. Since it is configured explicitly, you cannot use Data Annotations to override it.
To set the custom table name, add this to `ApplicationDbContext.OnModelCreating` method
`builder.Entity<ApplicationUser>().ToTable("MyCustomUser", "users");`

**Comment by smitpatel** [comment]
This issue was moved to aspnet/Identity#1774
