### ISSUE TITLE
IgnoreQueryFilters in Joins disable filter for all entities

### ISSUE THREAD

**Issue by lcriscola** [dotnet/efcore#11853]
If I include the IgnoreQueryFilters method in one of the entities in the join I would expect other entities to keep the filter.

### Steps to reproduce

Lest assume the following code on the Context.OnModelCreating

			builder.Entity<Entity1>().HasQueryFilter(x => x.IsActive);
			builder.Entity<Entity2>().HasQueryFilter(x => x.IsActive);

and the following LINQ expression:

var q = from e1 in _context.Entity1.IgnoreQueryFilters ()
             join e2 in _context.Entity2 on e1.ParentId equals e2.Id
            select e1;

I would expect the generated sql  to put a where clause on the Entity2. But no where clause is generated.

If no IgnoreQueryFilters is present, the generated sql includes a where clause of both tables.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.6.6

**Comment by anpete** [comment]
@lcriscola IgnoreQueryFilters is currently a query-level operator and so affects all entities in the query.

**Comment by douglasg14b** [comment]
Any comment on why this is considered not planned?

**Comment by roji** [comment]
One main difficulty in doing this, is that EF adds SQL JOINs - or correlated subqueries - in various situations when translating without an explicit LINQ Join operator. For example, in `context.Blogs.Where(b => b.Posts.Any())`, a correlated subquery will be generated against the Posts table. But there's no real place for the user to place an IgnoreQueryFilters(), since Posts is just a `List<Post>` and not a DbSet (we can't introduce extension methods over List).

Overall, a better solution here is probably to implement named query filters (#8576), at which point you should be able to selectively disable specific filters (but still at the query level).

**Comment by Lilk** [comment]
> [@lcriscola](https://github.com/lcriscola) one way to selectively suppress query filters, is to add flags on your derived DbContext. E.g. it would look something like this:
> 
> builder.Entity<Entity1>().HasQueryFilter(x => this.IgnoreFilterOnEntity1 || x.IsActive);
> builder.Entity<Entity2>().HasQueryFilter(x => this.IgnoreFilterOnEntity2 || x.IsActive);
> Then you can set the flags to the right value before and after executing the query.

This generates an OR expression which in SQL could up causing a SCAN instead of a SEEK since the boolean property is evaluated once per row instead of letting it be optimized away. It is not the same as allowing the filter to be conditionally disabled by a field on the DbContext.

**Comment by roji** [comment]
@Lilk that's very true, but note that we've implemented named query filters for EF 10 (#8576), so you can now selectively disable filters on a per-query basis.
