### ISSUE TITLE
EF Core 2.0: Unable to determine the relationship

### ISSUE THREAD

**Issue by etairi** [dotnet/efcore#11883]
I'm using EF Core 2.0 and ASP.NET Core API 2.0, and I have an entity defined like this:

```c#
    public class Follower
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public virtual StoreUser User { get; set; }

        public string FollowerId { get; set; }

        [ForeignKey("FollowerId")]
        public virtual StoreUser FollowerUser { get; set; }

        public DateTime CreatedAt { get; set; }
    }
```

where `StoreUser` is basically defined as:

```c#
      public class StoreUser : IdentityUser
      {
        public string FirstName { get; set; }
        public string LastName { get; set; }
      }
```

The problem is that when I run `dotnet ef database update` command it throw an error saying that it cannot figure out the relationship and I should manually specify it inside the `OnModelCreating` function. Any ideas what the problem might be and how to overcome it with the `OnModelCreating` function?

**Comment by smitpatel** [comment]
I am not able to reproduce this issue. Steps I followed:
- Create new ASP.NET web app with individual accounts.
- Rename ApplicationUser to StoreUser and replace with above class.
- Add Follower class as above and register it with model by adding a DbSet in ApplicationDbContext.
- Add Migration
- Update Database

It create table with 2 FKs as expected.
Further, adding migration builds the model so if your model is incorrect then it should have caught at that stage rather than during database update.

Please provide a full solution which demonstrate issue you are seeing.
