### ISSUE TITLE
The Old Range

### ISSUE THREAD

**Issue by keithnicholson** [dotnet/efcore#11913]
Hi all!

I cannot find any documentation one way or the other about using Range on a property with EF Core.  I know it can still be used as an Attribute, but our team prefers to use Fluent.  Since many new options are not available with Attributes, and only through Fluent, we feel more confident with that approach now.  So what would it take to create a Range extension method?  We want it not only for the constraint creation on the back end but also for validation on the in the controller we put the model into.

**Comment by ajcvickers** [comment]
@keithnicholson Some comments:
* EF6 has built-in support for validation of entities in SaveChanges. This is not built-in to EF Core as often validation is done at different layers making the EF validation superfluous. Also, having it built-in doesn't provide much value over applications doing it themselves.
* EF6 would process the Range attribute as part of this validation just because it is a data annotation used for validation. However, it was never used by the model building process to impact the EF model or database constraints.
* Validation on a controller is outside the scope of EF. MVC validation typically uses data annotations, but any extension method to change the EF model would have not influence on this.

Given this, I don't think it is possible to create the extension method you are asking for.
