### ISSUE TITLE
Using 0's for FKs instead of NULL

### ISSUE THREAD

**Issue by wasabii** [dotnet/efcore#11987]
Okay, crappy database. I know.

I have a table which has a compound primary key, with four columns. Each of those columns is actually itself a FK to another table.

But in their infinite wisdom, the authors decided to not make them actual FK constraints, and to use 0 to represent no value. There is no 0-record in the other table. And thus no RI.

```System.InvalidOperationException: The property 'FilingCategoryId' on entity type 'CourtCaseFilingType' has a temporary value. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.```

This is because the Id field is left as 0. And I'm trying to save it. And it should be zero. Is there a way to work around this?

EF Core 2.0.

**Comment by wasabii** [comment]
I think what I'm looking for, which probably does not exist, is something like EmptyRelationshipValue(object), which would let me specify something other than 'null' to represent a missing relationship. And which of course would be smart enough on insert and select.

**Comment by embryologist** [comment]
Certainly challenging.
Hope this helps,
https://github.com/aspnet/EntityFrameworkCore/issues/9552

**Comment by ajcvickers** [comment]
@wasabii There are several interrelated things here:
* Store-generated keys (e.g. Identity columns) require the CLR default (zero) to be used as a sentinel value, which then results in EF generating temporary key values--this is why you see the exception above. This can be turned off with `ValueGeneratedNever()` on the key properties in OnModelCreating. (Or use the DatabaseGeneratedAttribute if you prefer.)
* Without using store generated keys, EF should send and receive zero values just like any other. However, EF will still not treat zero as null, so you may need to be creative in dealing with clearing relationships, etc--likely you will need to explicitly set FK values to zero instead of just making changes to navigation properties.
* EF most of the time won't care if there actually exists a parent row for the zero key value. However, make sure to configure your relationships as optional (even though EF assumes they are required because the FK is non-nullable) so that EF understands that there may be some rows in the child table that do not have any rows in the parent table. (Mostly this means inner joins won't be used for returning children.)

Taking all that into account I expect you will be able to make something work. I would be interested to hear how it goes.
