### ISSUE TITLE
InMemoryDatabase provider not persisting data in test method.

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#12027]
I'm trying to write an integration test using the InMemoryDatabase, however I'm finding the data not persisting from the context resolved by the container in the repository and the one I resolve in my test.

I can see that when SaveChanges() is executed the database contains the entity. But then it is empty in the test method when I want to verify the dbset contains at least one record.

### Steps to reproduce
**Test Method:**
```c#
        [Fact]
        public async Task TestMethod()
        {
            var entryPoint = Server.Host.Services.GetService<IEntryPoint>();

            using (var scope = Server.Host.Services.CreateScope())
            {
                var context = scope.ServiceProvider.GetService<MyDbContext>();
                await entryPoint.Start();
                Assert.True(await context.EntityTable.CountAsync() > 0);
            }
        }
```

**IntegrationTests Base Class:**

I use this class to setup the test server and register all services with container.

```c#
public class IntegrationTests
    {
        protected TestServer Server;

        protected IntegrationTests()
        {
            Server = new TestServer(new WebHostBuilder()
                .UseStartup<Startup>()
                .UseEnvironment("IntegrationTests"));
        }
    }
```

**Startup:**

```c#
        public void ConfigureServices(IServiceCollection services, IHostingEnvironment hostingEnvironment)
        {
            services.AddTransient<IEntryPoint, EntryPoint>();
            services.AddScoped<IMyRepository, MyRepository>();

            if (hostingEnvironment.IsEnvironment("IntegrationTests"))
            {

                services.AddDbContext<MyDbContext>(options =>
                    options.UseInMemoryDatabase("IntegrationTestDatabase"));
            }
            else
            {
                services.AddDbContext<MyDbContext>(options => options.UseSqlServer(ConnectionString));
            }
        }
```

**Repository Class:**

```c#
public class MyRepository : IMyRepository
    {
        private readonly MyDbContext _myDbContext;

        public MyRepository(MyDbContext myDbContext)
        {
            _myDbContext = myDbContext;
        }

        public async Task Create(MyEntity myEntity)
        {
            _myDbContext.EntityTable.Add(myEntity);
            await _myDbContext.SaveChangesAsync();
        }
    }
```

### Further technical details
EF Core version: 2.0.3
Test Framework: xUnit 2.3.1
IDE: Visual Studio 2017 15.6.7

**Comment by ajcvickers** [comment]
@JakeFrancis The usual cause of issues like this is a different internal service provider being used where the DbContext instance is created to insert the data compared to where it is created to read the data. This matters because the in-memory data is rooted in the service provider.

#9613 is the issue for this. Things to try:
* Make sure that the DbContext is added to and resolved from the service provider in the same way everywhere. That is, don't mix AddDbContext with using new in other places.
* Make sure that anything like Loggers are configured exactly the same, since changes in these between context instances can cause EF to rebuild it's service provider.

If this doesn't help, then please post a runnable project/solution, github repo, or code listing that demonstrates the behavior you are seeing so that we can investigate.

**Comment by JakeFrancis** [comment]
Having looked at issue #9613 and the merge into 2.1.0-rc1-final: https://github.com/aspnet/EntityFrameworkCore/commit/c1bf9cc33d0b9b3b2b1f4c74a65daa202c3bd06c 

I was able to get it working by updating to 2.1.0 rc1 a passing the in InMemoryDatabaseRoot object when registering the DbContext in Startup.
