### ISSUE TITLE
EntityFramework misses changes made outside context

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/efcore#12074]
I have a webjob that fetches job objects, changes their state, adds some child objects, saves to DB.
The fetches use EF core and change tracking.
Another process also affects the same objects, changing their state and removing children.
Once the webjob has seen a given state and children, it doesn't see the changed state or removed children next time I fetch these objects from the DB. It appears to be caching these objects, so even thought they are gone or updated in the DB, it justs sees their cached state.
My webjob uses DI with a Scoped lifetime for the DbContext (but that scope is forever, basically a singleton).
Is this correct behavior? Is there a way to tell the context to forget its caches state once saved to the DB? Or should I be creating new DbContext instances for each iteration of my job loop?

**Comment by pmiddleton** [comment]
This is by design.  

EF Core will cache all entities in the change tracker by default.  It doesn't have a two way connection with the database so the cache can become stale if you have other processes touching the data outside of your context.

Given the type of work you are doing you should move to a per call lifetime on the DbContext.  Beyond the caching issue you are having DbContext is not thread safe.  Sharing a single context in a web job application is going to cause major issues.

**Comment by johnkwaters** [comment]
Thanks! I switched to creating a new instance for each iteration of the job loop. But... one thing about the original problem seems like a bug to me. I get it that there is not two way Db connection. But here is what was happening;

1. I fetch an entity through the DbContext, with change tracking on. It has a Status field, and it is 1. In the code I update the Status to 3, and do SaveChanges. Not the context has cached this entity, with Status 3.
2. I change the Status back to 1 in the DB, unbeknownst do the DbContext.
3. I fetch the same object again, using the same DbContext object, again with change tracking.  
4. Then I change it to 3 again and call SaveChanges. The change is not saved. The context doesn't think it is modified. 

But here's my question: in Step 3, it SAW the entity with Status 1, yet didn't update the cached Status to 1, so in 4 it did the wrong thing. If the context fetches an object from a Db query - shouldn't it update it's cached state?

Is what is happening in 3 that is doesn't actually fetch the cached object from the DB, it just hits the stale cache? Its in a query like DbSet<Job>.AsTracking().Where().... and it fetches this object and others... does the emitted SQL actually EXCLUDE the objects in the cache? Or is there a bug here?

**Comment by pmiddleton** [comment]
In step 3 the entity will come out of the cache.  That cached item will still have it's Status set to 3.  Therefore when you set it to 3 again EF will detect that the value didn't change and therefore not update the database when SaveChanges is called.

In your example you can manually mark the Status as being modified and then the database will be updated.

```chsarp
context.Entry(myEntityHere).Property(e => e.Status).IsModified = true; 
```

**Comment by johnkwaters** [comment]
Thanks Paul. Yes, that is what I did. But then after reviewing the whole bigger picture I switched to the scoped DbContext per loop scenario I detailed above. So then by design, if you read from the DB and it is in the cache, the DB is never checked, and so the changed value is not seen. Just one last point before I stop flogging this horse:

In my code I select all the jobs with State != completed (which would return that one in State 3 in the cache, that is now 1 in the DB). Something like

DbSet<Job>.AsTracking().Where( j => j.State != 11 and j.State != 99).ToListAsync();

So is it either 

a) the SQL fetches my job with state 1 but ignores it when processing the result set from the SELECT statement, thus preserving its stale cached value of state=3?
b) the SQL generated has a (AND id NOT IN (...list of ids cached)) so it never sees the new value?

**Comment by ajcvickers** [comment]
@johnkwaters The intended use pattern for DbContext is as a short-lived object used only for a single unit-of-work. Queries are always run against the database, but any objects already tracked will be used in the results of the query. For cases where multiple updates may conflict (and last-one-wins is not appropriate) it is recommended that [optimistic concurrency handling](https://docs.microsoft.com/en-us/ef/core/saving/concurrency) be used.

**Comment by lukos** [comment]
@ajcvickers Re. your comment, "Queries are always run against the database, but any objects already tracked will be used in the results of the query", is there something that explains that? I am trying to use dbcontext to cache objects but if the query is still run against the database, what is the value of the object caching?

In my code, I can see the same query called twice on the same dbcontext, so should I be using a caching mechanism on top of EFCore?

**Comment by ajcvickers** [comment]
@lukos I agree that this is unintuitive--it's on my list to write better documentation for. In short it's because in general queries need to run against the database (except for Find) but combining a graph of results from the database with a graph of tracked results involves both complexity and ambiguity.

> what is the value of the object caching?

While the context does cache objects, that is not its primary reason for existence. Instead, it exists to keep track of the state of a graph of entities such that it can be used for identity resolution and updates.

> so should I be using a caching mechanism on top of EFCore?

This is commonly referred to as a "second level cache"--see https://github.com/dotnet/efcore/issues/5858. This used to be quite common around 10 years ago, but caching at other levels in the stack has largely replaced it.
