### ISSUE TITLE
HasComputedColumnSql data type

### ISSUE THREAD

**Issue by mholec** [dotnet/efcore#12071]
When I define mapping for Computed SQL column, it is does not take into account the data type.

### Example 1 (OK)
```c#
 modelBuilder.Entity<Person>()
            .Property(p => p.DisplayName)
            .HasComputedColumnSql("[LastName] + ', ' + [FirstName]");
```
This mapping creates nvarchar computed column. That is OK, because `LastName `and `FirstName `are strings in my model.

### Example 2 (Maybe OK ?)
```c#
 modelBuilder.Entity<Person>()
            .Property(p => p.DisplayName)
            .HasComputedColumnSql("[Id] + ', ' + [FirstName]");
```
Note that `Id `column is INT data type. This mapping generates Computed SQL column of datatype INT in my database.

### Example 3 (NOT OK)
```c#
 modelBuilder.Entity<Person>()
            .Property(p => p.DisplayName)
            .HasComputedColumnSql("[Id] + ', ' + [FirstName]")
            .HasColumnType("nvarchar(200)");
```
The same result as Example 2. It generates Computed SQL column of datatype INT in my database. 

It is interesting that migration contains this:

```txt
DisplayName= table.Column<string>(type: "nvarchar(200)", nullable: true, computedColumnSql: "[Id] + ', ' + [FirstName]"),
```
I expected auto conversion to nvarchar.

## Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
DB: Sql Server 2017 Express

**Comment by bricelam** [comment]
CAST Id to nvarchar in the SQL

**Comment by divega** [comment]
> CAST Id to nvarchar in the SQL

We should probably investigate if wrapping the whole expression in a CAST in the DDL we generate would be enough. Apparently there is no way to flow the type explicitly and the logic SQL Server uses to infer the type from the expression is brittle. 

In the meanwhile the workaround would be to add the in the expression, e.g.:
``` C#

 modelBuilder.Entity<Person>()
            .Property(p => p.DisplayName)
            .HasComputedColumnSql("CAST([Id] as varchar(200)) + ', ' + [FirstName]")
            .HasColumnType("nvarchar(200)");

```

**Comment by mholec** [comment]
CAST Id to nvarchar make sense. But `HasColumnType ` is ignored, because the length of virtual column is calculated from length of (Id, FirstName and ', ' constant). It can be confusing for many developers, who do not know how the things works in target DBS and they expect that EF Core will do some magic. Wrapping the query this way `CAST([Id] + ', ' + [FirstName] as nvarchar(200));` works fine and do exactly what developer expect.

**Comment by ajcvickers** [comment]
Additional investigation for triage:
* When using `.HasComputedColumnSql("[Id] + ', ' + [FirstName]")`, doing an insertion results in "SqlException: Conversion failed when converting the varchar value ', ' to data type int."
* Even when using `.HasComputedColumnSql("[Id]")` on a string property, doing an insertion still throws because we can't read the value back: "InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'"
* Assuming data is inserted not by EF, then query throws "System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'"

**Comment by ajcvickers** [comment]
Triage: Given what we now know about the way the computed column works in SQL Server, which requires casts to make the expression work, and given that EF doesn't want to be in the business of guessing what casts will be needed when, we are not going to change any behavior here. In other words, if something is setup that will work with SQL Server, then EF should have no issues, but if it isn't setup correctly then the thing to do is fix the SQL Server expression.

**Comment by mholec** [comment]
I agree that if someone will use `HasComputedColumnSql("[NumberOne] +[NumberTwo]")`, ORM can not guess what developer wants. On the other hand it is strange when I use `HasColumnType("nvarchar(200)")` and ORM just allow to create migration without warning. EF migration tool could write message like: "Warning: you are using HasComputedColumnSql + HasColumnType and final data type of column will be setup by destination DBS". It could be similar like a developer wants to remove a class property and migration tool tells me that I will lose data.

I just think that HasColumnType has different behavior than in common case:

### Example
If I have table:

```
Brands
-----------------------
BrandId - Int32, Not Null, PK
Title - String, Nullable
InternalNumber - Int32, Not Null
```

I can write this mapping rule:

```c#
builder.Property(x => x.InternalNumber).HasColumnType("nvarchar(200)");
```

It will create migration

```
InternalNumber = table.Column<int>(type: "nvarchar(200)", nullable: false),
```

And final datatype in DBS is really **nvarchar(200).** This is different behavior than in case of `HasComputedColumnSql` + `HasColumnType`.

**Comment by divega** [comment]
@mholec but the problem is a bit more general than that: Even if the column type is not configured explicitly, EF Core will choose one and will assume that the actual type of the column will be one compatible with TProperty, however because of how the computed column is setup in the SQL, we have no control.

In other words, we would need to raise a warning any time HasComputedColumn is used with SQL Server, regardless of whether HasColumnType is used. This is possible, but a warning that is raised every time you use an API becomes noise and provides little positive value, so we usually avoid it. 

Also, in the cases in which the SQL expression ends up producing a column of an incompatible type, as https://github.com/aspnet/EntityFrameworkCore/issues/12071#issuecomment-391853192 showed, most likely there will be runtime errors on first use with any data, which may not me as good as a warning but it isn’t as bad as a runtime error that happens only rarely.

**Comment by mholec** [comment]
@divega all your arguments makes sense and I agree with you. Thank you.
