### ISSUE TITLE
Question: Plugin/modular architecture with EF Core

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#12117]
I'm trying to use EF Core code first with plugin architecture using `AssemblyLoadContext` to load plugins/modules dynamically. 

Basically what I want is to have a core module and core entities and my plugins can define their own entities and use my core entities and define relations between them. Everything should be in the same database. Plugins are supposed to be loaded at runtime.

Is this possible that each plugin defines it's own `DbContext` and share this context with context defined in the core assembly?

How should I manage `DbContext` and migrations in this kind of architecture?

**Comment by ajcvickers** [comment]
@enemyofthedawn Keep in mind that the non-core module will not be able to impact the shape of the entity types in the core module--specifically, they can only be referenced as principals since you won't be able to add new FKs to them.

With regard to Migrations, the core context should handle the migrations for its entity types. For the other contexts, after generating a migration edit it to remove the parts that reference tables from the core. This scenario and the work to make it less manual is covered by #2725.

**Comment by enemyofthedawn** [comment]
@ajcvickers thanks Arthur!
