### ISSUE TITLE
Does HasKey / HasAlternateKey affect SQL generation?

### ISSUE THREAD

**Issue by asido** [dotnet/efcore#12113]
I use EF Core as an object mapper and SQL generator from LINQ. The rest, such as database migrations, object tracking, lazy loading, is not done via Entity Framework.

I use `DbContext.OnModelCreating` to configure the mappings. In order for EF to function, every entity has to have a key specified via `EntityTypeBuilder.HasKey()`.

Suppose I have the following table:

```sql
create table entity
(
  key uuid not null,
  other_key uuid not null,
  prop1 int not null,
  prop2 text not null,
  primary key (other_key, prop1, prop2)
);

create index entity_index on entity (key);
```

I wonder, if I don't use `DbSet<TEntity>.Find()` does it make a difference for SQL generation whether I specify the keys as
```csharp
config.HasKey(new { e.OtherKey, e.Prop1, e.Prop2 });
```
or
```csharp
config.HasKey(new { e.Key });
```
or
```csharp
config.HasKey(new { e.OtherKey, e.Prop1, e.Prop2 });
config.HasAlternateKey(new { e.Key });
```

**Comment by GertArnold** [comment]
It will certainly affect generated SQL for joins. As long as you just query the `DbSet` without explicit LINQ join statements or implicit joins (`Include` or projections) the generated SQL will only depend on the predicate expression, i.e. not on what EF knows about the primary key or alternate keys.

Of course object materialization by EF will be affected, but that's not the issue here.

**Comment by Asido** [comment]
@GertArnold thanks a lot.
