### ISSUE TITLE
On Query cases: Microsoft.EntityFrameworkCore.dll: 'Value cannot be null.'

### ISSUE THREAD

**Issue by Jonatthu** [dotnet/efcore#12147]
Repro repository
https://github.com/Jonatthu/efcore-examples

On line 120 of program.cs and line 130 as well.

```
// Is not working
county = dbContext.User
              .Select(lambda)
	      .Where(x => 
	         new []{ 44, 5, 546, 99 }.Contains(x.Blogs.Count())
	      )
              .ToList();
```

The first 2 examples are workarounds but only will generate more request to the database, it should work with the examples below those.

I have included console logs for the queries that are being generated. The repro should work as soon as you clone it a hit f5 on vscode or vs. :)

```
Exception has occurred: CLR/System.ArgumentNullException
Exception thrown: 'System.ArgumentNullException' in Microsoft.EntityFrameworkCore.dll: 'Value cannot be null.'
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp4.Program.Main(String[] args) in /Users/jonatthu/Documents/Jonatthu/efcore-examples/ConsoleApp4/Program.cs:line 121
```

**Comment by smitpatel** [comment]
Unless, I am missing something this should be expected behaviour. You are projecting out a custom user using `.Select(lambda)` which does not set `User.Blogs` property which means it is set to null (the default value). Doing `x.Blogs.Count()` is null ref as the stack trace says above. Without custom lambda projecting into new `User` it is EF entity and in that case the navigation access will be made null safe by EF. Once you created your own object, we don't have any information to make accesses null safe. For DTO we cannot make this work.

Leaving this open as given the custom object here is of type which is registered as an EntityType, we can discuss in triage if we want to give nav expansion here. Afaik, we don't track entities which are constructed like that even if its entity type.

**Comment by Jonatthu** [comment]
@smitpatel check it out the second use case I am usen a Select(x => new User...

**Comment by Jonatthu** [comment]
@smitpatel If this is by design so we are skeping the possibility of custom selects and filterings

**Comment by smitpatel** [comment]
@Jonatthu - In the second case while you are using custom lambda you are not using nav props. No `x.Blogs.Count()` The error arises because `x.Blogs` is null.

**Comment by smitpatel** [comment]
> check the second use case out, I am using a Select(x => new User { ...})

**Comment by Jonatthu** [comment]
How EF Core would do this custom select and filtering then?

**Comment by smitpatel** [comment]
You could do any filtering without custom selector, so move filtering first and then do custom selector at the end.

**Comment by Jonatthu** [comment]
@smitpatel  How about a context setter helper when using custom selects like .Select<T>(custom), because all the goal of custom select is to not move huge amount data from db to Server when we are just requiring two fields

**Comment by Jonatthu** [comment]
@smitpatel I think we need to find a way, or EFCore will always have the negative side of a select *

**Comment by smitpatel** [comment]
Even if you move the custom selector at the end, EF Core is not going to move huge amount of data from db. It will only fetch the data you asked for. You could move the selector to the end or you can assign correct value of `c.Blogs` in your custom selector. Even if EF made it null safe, it will return 0 results because the custom object you created has Blogs property null, so null safe `Count` will get 0 which will not satisfy the where clause.

**Comment by Jonatthu** [comment]
But how many calls to the db will be?
One for count and one for selects?

**Comment by smitpatel** [comment]
It depends on your where predicate. If it translates to server then it would be 1 query only. If it doesn't then it could be N + 1. In which case you should rewrite your query to avail server eval.
Regardless of EF throws exception like above or not, since you custom selector sets `user.Blogs` to null, the query is never going to give you back any results.

**Comment by Jonatthu** [comment]
@smitpatel Let’s say I want to get users 
With only Username and Birthday fields
Where Blogs Count are > than 10 
And Where Friends Count are > than 20

The way I was trying would have a single query to the db.

But as this issue is going means that I need to do 3 separated queries for achieve this, Right?

**Comment by smitpatel** [comment]
Nope
```C#
var result = db.Users.Where(u => u.Blogs.Count() > 10 && u.Friends.Count() > 20)
                       .Select(u => new { u.Username, u.Birthday })
                      .ToList()
```
Which should generate SQL like
```SQL
SELECT [u].[Username], [u].[Birthday]
FROM [Users] AS [u]
WHERE (
    SELECT COUNT(*)
    FROM [Blogs] AS [b]
    WHERE [u].[Id] = [b].[UserId]) > 10 AND (
    SELECT COUNT(*)
    FROM [Friends] AS [f]
    WHERE [u].[Id] = [f].{UserId]) > 20
```

**Comment by Jonatthu** [comment]
@smitpatel Oh now it make sense, sorry I was not understanding good, Is this actually working with the repository that I made? Would be very nice, Will this work with a custom lamda?

**Comment by Jonatthu** [comment]
I am working in a GraphQL CLI, so I am planning to add multiple Generated filters just as GraphQLcool, but I want to do it with EF Core and migration tools. I need more performance that’s why I need this 🤗

**Comment by smitpatel** [comment]
I haven't tested it with the repository you shared. But it should work. Custom lambda would also work as long as they are appearing after Where.

**Comment by Jonatthu** [comment]
@smitpatel I will test and get va k to you thanks!

**Comment by Jonatthu** [comment]
@smitpatel works nice!
