### ISSUE TITLE
How to always attach Enumeration classes?

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/efcore#12150]
I have been using Enumeration classes as described [here](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types). My issue is I always need to attach any of my Enumeration class when adding a related entity to the database. For example:

```C#
public class Order
{
  public Order(OrderStatus orderStatus)
  {
    OrderStatus = orderStatus;
  }
  public int OrderId { get; private set; }
  public OrderStatus OrderStatus { get; private set; }
}

public class OrderStatus : Enumeration
{
  public static OrderStatus Submitted = new OrderStatus(1, "Submitted");
  public static OrderStatus Cancelled = new OrderStatus(2, "Cancelled");
  public OrderStatus(int id, string name) : base(id, name) { }
  public static IEnumerable<OrderStatus> GetAll() => new[] { Submitted, Cancelled };
}

public class OrderingContext :DbContext
{
  public DbSet<Order> Orders { get; set; }
  public DbSet<OrderStatus> OrderStatus { get; set; }
  public OrderingContext(DbContextOptions<OrderingContext> options) : base(options) { }
  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    modelBuilder.Entity<OrderStatus>().HasKey(o => o.Id);
    modelBuilder.Entity<Order>().HasOne(o => o.OrderStatus);
  }
}

//usage
using (var context = new OrderingContext(options))
{
  context.Database.EnsureCreated();

  //seed
  context.AddRange(OrderStatus.GetAll());
  context.SaveChanges();
}

using (var context = new OrderingContext(options))
{
  //context.OrderStatus.Attach(OrderStatus.Submitted); //uncomment to attach
  context.Orders.Add(new Order(OrderStatus.Submitted)); //throws exception if OrderStatus not attached
  context.SaveChanges();
}
```

Is there any way to always attach Enumeration classes to the context?

**Comment by ajcvickers** [comment]
@gojanpaolo As mapped above, OrderStatus is an entity type. As such having these "always attached" is equivalent to having reference data pre-loaded into the context. I created #12206 to track this.

However, in the case above, it would likely be more appropriate to not map the enumeration class as an entity type, but to instead use a value converter to transform into a string. Something like:

```C#
public class Order
{
    public Order(OrderStatus orderStatus)
    {
        OrderStatus = orderStatus;
    }
    
    public int OrderId { get; private set; }
    public OrderStatus OrderStatus { get; private set; }
}

public class OrderStatus
{
    public static OrderStatus Submitted = new OrderStatus("Submitted");
    public static OrderStatus Cancelled = new OrderStatus("Cancelled");

    private readonly string _name;

    public OrderStatus(string name) =>_name = name;

    public override string ToString() => _name;

    public static IEnumerable<OrderStatus> GetAll() => new[] { Submitted, Cancelled };
}

public class OrderingContext : DbContext
{
    public DbSet<Order> Orders { get; set; }

    public OrderingContext(DbContextOptions<OrderingContext> options) : base(options) { }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Order>()
            .Property(e => e.OrderStatus)
            .HasConversion(
                v => v.ToString(), 
                v => OrderStatus.GetAll().Single(s => s.ToString() == v));
    }
}
```

Note that on looking at the linked code for Enumeration I saw several issues:
* It uses an unstable Equals (depends on a mutable property) which is likely to cause issues in identity resolution for EF.
* It overrides Equals but not GetHashCode, which will cause issues with things like dictionary storage
* The IComparable implementation is inconsistent with the Equals implementation

Also, EF would not be able to use the constructor defined on Order because other entity types cannot be used as constructor parameters as of EF Core 2.1.

**Comment by gojanpaolo** [comment]
@ajcvickers Thanks for the response. I just tried the value converter approach but we would prefer to keep having an OrderStatus table with all its possible values and then use a surrogate key to relate it with other entities.

Another thing to consider is when a read-only entity class has other properties aside from a string name which should be reflected in the database.

**Comment by ajcvickers** [comment]
@gojanpaolo In that case, what you are asking for is being tracked by #12206.

**Comment by gojanpaolo** [comment]
Ah yes. I guess pre-loading the entities would cover those instances.
Thank you! :)
