### ISSUE TITLE
Unchanged byte array contents (but not same array instance) causes unnecessary update

### ISSUE THREAD

**Issue by slubowsky** [dotnet/efcore#12231]
I have a picture field in my entity class. It is declared as a byte [] and becomes a varbinary column. To apply a patch I map my entity to a DTO, apply the patch, and then map back to the entity object. During the mapping, the byte [] is mapped to a base 64 string going into the DTO and then back to a byte [] when coming back to the entity. If the picture has not been updated, the contents of the byte [] are identical but the actual array instance is different.

When I SaveChanges, the picture column is always included in the update even though the picture didn't actually change.

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8 P2

**Comment by ajcvickers** [comment]
@slubowsky This is likely because normal `byte[]` properties are compared using reference equality, so EF will detect that the property has changed if and only if the property now points to a different byte array instance than it did before. This is because doing instead a deep compare of the bytes is very expensive in the common case where no change has been made.

There are several things you could do to mitigate this:
* Avoid serializing the image to and from the DTO whenever possible, since this is in itself expensive.
* If you know that the image hasn't changed, then explicitly mark is as not modified before saving.
* Change the way EF does comparisons for the property to use a deep comparison. There isn't nice API for this yet, but this should work:
```C#
modelBuilder
    .Entity<Blog>()
    .Property(e => e.Image)
    .Metadata
    .SetValueComparer(
        new ValueComparer<byte[]>(
            (l, r) => StructuralComparisons.StructuralEqualityComparer.Equals(l, r),
            v => StructuralComparisons.StructuralEqualityComparer.GetHashCode(v),
            v => v.ToArray()));

```

**Comment by slubowsky** [comment]
I had basically done the 3rd option but not by setting the ValueComparer. I did it myself by saving a reference to the original and then comparing it after the mapping was complete using StructuralEqualityComparer.Equals and setting it back to the original before saving if unchanged. This way is more elegant and does seem to work for me.
Thanks!
