### ISSUE TITLE
Missing element in collection after SaveChanges when Equals is overridden

### ISSUE THREAD

**Issue by Materix** [dotnet/efcore#12257]
I have three model class:

- Container
- Item
- Link (many-to-many between Container and Item)

In Link I have overridden Equals as follow
```c#
        public override bool Equals(object obj)
        {
            return obj is Link link &&
                   ContainerId == link.ContainerId &&
                   ItemId == link.ItemId;
        }
```

In test I created one container and two items. One item is attached to container by link and save.

In new context I completely replace collection of links in Container to attach both item (so I created two new link, first of them is Equals to old one in manner of `Equals` function). After save changes, first new link disappear from collection. Even when I load that container again, it has only one link (second new)

When I create new context and load that container in new context, it has two links.

Full repro was in https://github.com/Materix/MissingCollectionElements

### Further technical details
EF Core version: 2.1.0 (from Microsoft.AspNetCore.App metapackage)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.InMemory)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.7.3)

**Comment by ajcvickers** [comment]
@Materix The issue here is that EF requires that one and only one object instance be used to represent a specific tracked entity. Doing otherwise introduces many ambiguities in how to handle the duplicates when dealing with graphs of entities. This means that it is not possible to replace one instance with a given ID using another instance with that given ID, which is what the code posted is doing.
