### ISSUE TITLE
The right way to insert when there is an concurrent issue.

### ISSUE THREAD

**Issue by lousaibiao** [dotnet/efcore#12279]
I has a table, named Table1, with tow columns, Id(primary key, auto increase), Name(string).
I want to prevent duplicate Names, so, each time before insert, I check if same name records exist like below.
```csharp
if (await dbContext.Table1.AsNoTracking().FirstOrDefaultAsync(w=>w.Name==name)!=null)
{
  dbContext.Table1.Insert(new Table1(){Name=name});
  await dbContext.SaveChangesAsync();
}
```
it works fine if their only one request each time.
But if there two requests with same name in the same time,  for example, second request occurs before SaveChangesAsync(), there will be two same name request inserted into table.

**Comment by ajcvickers** [comment]
@lousaibiao See the docs on optimistic concurrency handling: https://docs.microsoft.com/en-us/ef/core/saving/concurrency

**Comment by qidydl** [comment]
@ajcvickers That documentation covers concurrency control regarding Update statements, but not Insert statements. Failed Inserts result in a more generic `DbUpdateException` and the documentation does not provide any explanation of how to recover from this scenario.

**Comment by ajcvickers** [comment]
@lousaibiao @qidydl You are correct; sorry. We had a brief discussion about it, but if there can really be concurrent insertions of the same record, then it probably either requires use of a transaction or a stored procedure.

**Comment by lousaibiao** [comment]
@ajcvickers So, could you show us some examples about using transaction and store procedure?

**Comment by ajcvickers** [comment]
@lousaibiao Have you read the docs on transactions?

**Comment by Lordfirespeed** [comment]
Hi, I still have this issue. Both the docs on optimistic concurrency and the docs on transactions are not helpful for this usecase. 

When an insert fails due to concurrent inserts in `SaveChangesAsync` I would like my `DbContext`'s change tracker to accept `Add`ed objects which have already been created in the database so that I can retry `SaveChangesAsync`. I can't find any documentation that demonstrates a neat way to do this without creating a fresh `DbContext` and redoing business logic.
