### ISSUE TITLE
How to update tables when connection is made

### ISSUE THREAD

**Issue by lsvMoretti** [dotnet/efcore#12283]
Hello, I'm using this in a C# .net-core application that's linked to a game server. I'm able to create tables with the blank database however I am unable to update my code and get the new changes in the database. I have used Entity Framework before, though I am kinda new to all this. I've tried enabling Migrations and also EnsureCreated, but that just checks if the database is created and not the tables if I believe right?

Context:
```c#
using LSV.Database_Tables;
using Microsoft.EntityFrameworkCore;

namespace LSV
{
    public class Context : DbContext
    {
        public DbSet<Account> Account { get; set; }
        public DbSet<Character> Character { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (Main.TestServer)
            {
                optionsBuilder.UseMySql("server=localhost;database=rageserver;user=root;password=;SslMode=none");
            }
            else
            {
                optionsBuilder.UseMySql("server=localhost;database=library;user=user;password=password");
            }
        }
    }
}
```

Start up:

```c#
[ServerEvent(Event.ResourceStart)]
        public void ResourceStart()
        {
            using (var context = new Context())
            {
                context.Database.EnsureCreated();
                NAPI.Util.ConsoleOutput(context.Account.ToList().Count.ToString());
            }
        }
```

**Comment by ajcvickers** [comment]
@theonethatownz EnsureCreated is intended for testing/prototyping where you are okay with blowing away the entire database. It is usually coupled with EnsureDeleted. EF Core Migrations should be used to manage the database in other situations--documentation is here: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/

If you're still hitting issues after following the docs, then please open a new issue including a runnable project/solution or complete code listing so that we can investigate more.
