### ISSUE TITLE
How can IMigrationsModelDiffer be injected in SqliteMigrationsSqlGenerator?

### ISSUE THREAD

**Issue by leak** [dotnet/efcore#12357]
For creating table rebuilds to get unsupported SQLite migrations working i need `IMigrationsModelDiffer` in `SqliteMigrationsSqlGenerator`

Since version 2.1.0 IMigrationsModelDiffer itself has a lot more dependencies and it seems like it should be ctor injected instead of manually newed up.

Problem is when I do this:

````
        public SqliteMigrationsSqlGenerator(
            [NotNull] MigrationsSqlGeneratorDependencies dependencies,
            [NotNull] IMigrationsAnnotationProvider migrationsAnnotations,
            [NotNull] IMigrationsModelDiffer modelDiffer)
            : base(dependencies)
            => _migrationsAnnotations = migrationsAnnotations;
````

without any further code being added, there is an exception during startup.

`MyDbContext.Database.Migrate()` throws
```
System.ArgumentNullException: 'Value cannot be null.
Parameter name: provider'
```

What is the proper way of accessing `IMigrationsModelDiffer ` in `SqliteMigrationsSqlGenerator`?

### Further technical details
EF Core version: 2.1.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: win10 1709
IDE: Visual Studio 2017 15.7.3

**Comment by ajcvickers** [comment]
@bricelam to provide some guidance here.

**Comment by bricelam** [comment]
`IMigrationsModelDiffer` is a scoped service while `IMigrationsSqlGenerator` is a singleton, so it can't be injected. Do you really need to diff models? If you just need to go from an `IEntityType` to a `CreateTableOperation`, the code should be trivial enough just to copy into SqliteMigrationsSqlGenerator.

When implementing #329, I expect I'll refactor that code into a component shared by both the differ and the Migrations SQL generators.

**Comment by leak** [comment]
I tried copying the relevant parts from `MigrationsModelDiffer` but it is just not feasible, after copying the 10th depending method I ask myself why there is DI in the first place and what service scopes I need to change to make it work again. 
In 2.0 this was way simpler, but now in 2.1 it is just not possible for someone without in-depth knowledge without burning away endless hours.

What is a straight forward pragmatic approach to "just" use the `IMigrationsModelDiffer` via injection? I do not care about scope-correctness or potentially wasteful injected services during runtime.

**Comment by bricelam** [comment]
@ajcvickers Is it possible for applications to change the lifetime of a service?

**Comment by ajcvickers** [comment]
@bricelam Yes, but it is not recommended since it can break things in quite unexpected ways. To do it, the application needs to take over building the internal service provider and register the service with the scope that they want before calling AddEntityFrameworkXxx. Since we TryAdd everything, if the service is already registered, then EF will leave the registration alone.

**Comment by bricelam** [comment]
@leak Register `IMigrationsSqlGenerator` and any of its dependencies as Scoped.

**Comment by leak** [comment]
Looks like adding those manually gets me straight trapped in dependency hell (dependencies of dependencies of dependencies....)

````
            services.AddScoped<CommandBatchPreparerDependencies>();
            services.AddScoped<IChangeDetector, ChangeDetector>();
            services.AddScoped<StateManagerDependencies>();
            services.AddScoped<IRelationalTypeMappingSource, SqliteTypeMappingSource>();
            services.AddScoped<TypeMappingSourceDependencies>();
            services.AddScoped<ValueConverterSelectorDependencies>();
            services.AddScoped<IValueConverterSelector, ValueConverterSelector>();
            services.AddScoped<RelationalTypeMappingSourceDependencies>();
            services.AddScoped<MigrationsAnnotationProviderDependencies>();
            services.AddScoped<IMigrationsAnnotationProvider, MigrationsAnnotationProvider>();
            services.AddScoped<IMigrationsModelDiffer, MigrationsModelDiffer>();
````

This is what I'm currently adding at the end of `ConfigureServices()` and there are still errors about missing dependencies trying to get the differ out of DI without exceptions...
````
            var host = CreateWebHostBuilder(args).Build();
            var differ = host.Services.GetService<IMigrationsModelDiffer>();
````
I guess by the time i have them all listed my list is equally long to what EF would have built on its own...

I was already struggling with this in 2.0. Back then I was getting away with injecting `IMigrationsAnnotationProvider` into `SqliteMigrationsSqlGenerator` and then instanciating the differ myself  `var modelDiffer = new MigrationsModelDiffer(Dependencies.TypeMapper, _migrationsAnnotations);`

Now in 2.1 EF seems fully trapped in dependency hell where individual parts become unusable outside of their intended scope..

**Comment by ajcvickers** [comment]
@leak It is certainly feasible to replace EF services with similar services that have different behavior. This should not involve changing scope. On the other hand, where an architectural decision has been made about how these services should function and work together as a system, then attempting to do something that goes against that decision is generally not feasible. In some cases this includes changing the scope of services, since that is fundamental to the internal architecture of EF Core.

In cases like this, a better approach would be to:
* Attempt to see if what you want to do can fit into the existing architecture/design. In this case, that means not using the differ in SQL generation.
* If this leads to an understanding of how the architecture can be improved, then create an issue for this proposed architecture/design change in order to get feedback from the team and community. For example, in this case that might be the refactoring that @bricelam suggested.
* Assuming the feedback is positive, then consider making a PR for the change, such that you can then extend EF in the way you want.
