### ISSUE TITLE
Provide overload of EntityFrameworkQueryableExtensions.ForEachAsync<T>() that accepts async lambda.

### ISSUE THREAD

**Issue by andrewslavin** [dotnet/efcore#12425]
The issue, as well as the proposed solution, are described here: https://stackoverflow.com/questions/50920636/unexpected-behaviour-with-microsoft-entityframeworkcore-entityframeworkqueryable. 

In a nutshell: `ForEachAsync()` takes `Action<T>` as second argument, but if I provide `Func<T, Task>` (async lambda) instead, the code still compiles. But obviously it will not work as expected, because the async lambdas will not be awaited.

**Comment by divega** [comment]
@andrewslavin thank you for making this request here. 

We are currently holding off adding new functionality to the implementation of async enumerables we use, because we hope to integrate the work on [new async stream interfaces and language support](https://github.com/dotnet/csharplang/blob/master/proposals/async-streams.md) in an upcoming version. 

This is indeed valid feedback you should make sure is either contemplated in the spec of raise an issue in https://github.com/dotnet/csharplang/).

There are also deeper reasons having an overload of ForEachAsync that takes a Func<TElement,Task> could be a pit of failure. These are detailed in https://github.com/dotnet/reactive/issues/194#issuecomment-234262986 and are related to a high number of unnecessary Task allocations. 

Other than that, if in the meanwhile you need something like this, it should be possible for you to create an extension method that does it. 

Take a look at how our ForEach extension method obtains the underlying IAsyncEnumerable (note that this requires using EF Core internal API that we will break for sure in EF Core 3.0):

https://github.com/aspnet/EntityFrameworkCore/blob/2d1767e767a8446d3ed5ae6adbc9c55d6c7823d2/src/EFCore/EntityFrameworkQueryableExtensions.cs#L2867-L2871

And then you can implement a modified version of System.Interactive.Async's ForEachAsync that takes a Func<T, Task> and awaits on it on every loop:

https://github.com/dotnet/reactive/blob/5e77cabaacf2caa84916c3305524b0b566524203/Ix.NET/Source/System.Interactive.Async/ForEach.cs#L76-L89
