### ISSUE TITLE
How to refresh EF cache after using raw SQL?

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/efcore#12441]
What are my options to refresh/clear the EF cache after using raw SQL to update/insert/delete data?

## Example
This is an oversimplified example. What I'm really doing is mass inserts/updates. When the mass operation is executed then there *should* be no records in the `StateManager` of the type the raw SQL changes but I don't want to rely on that.

Given is table/DbSet `Products` with properties `Id` and `Name`.

1) At first we add a new product using EF.
```
_ctx.Products.Add(new Product(){ Id = 42, Name = "Name" });
_ctx.SaveChanges();
```

2) Later, the product is updated via raw SQL
```
_ctx.Database.ExecuteSqlCommand("UPDATE Product SET Name = 'New name' WHERE Id = 42");
```

3) And then we load the products using EF

```
var products =_ctx.Products.ToList();
```

The problem is that the name of the product with `Id` = 42 isn't changed after fetching the data.

## Solutions (?)
* No-Tracking behavior be default
`_ctx.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;`
* Create new instance of `DbContext`
* Detach products
```
var entriesToDetach = _ctx.Products.Local
		                          .Select(p =>
	                                  {
		                                  var entry = _ctx.Entry(p);

		                                  if (entry.State != EntityState.Unchanged)
			                                  throw new Exception("<< error msg >>");

		                                  return entry;
	                                  })
	                          .ToList();

entriesToDetach.ForEach(e => e.State = EntityState.Detached);
```

**Comment by ajcvickers** [comment]
@PawelGerr Recommendation is to create a new context instance. Generally, it is could practice to create a new short-lived context instance for each unit-of-work.

**Comment by wasabii** [comment]
I want to leave another comment on this issue, since I think the recommendation misses a key point.

I open a transaction. Do a lot of EF work. And then do some bulk SQL loads. And then do more EF work. And then commit the transaction.

This leaves no possibility for using multiple DB contexts. They would not be able to span the transaction.

Previous frameworks I've used (NHibernate) just updated the objects, if a query was run that happened to have data, and the object wasn't dirty. Why can't there just be a way to do this? A setting on a specific query to force an update of all the entities?
