### ISSUE TITLE
EF Core 2.2 roadmap discussion

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#12465]
Discussion thread for the EF Core 2.2 roadmap announcement at https://github.com/aspnet/Announcements/issues/308.

**Comment by GorelH** [comment]
Many-to-Many relationships [1368](https://github.com/aspnet/EntityFrameworkCore/issues/1368) is one of the most demanded feature right now, is there a plan to support it in this roadmap?

**Comment by SSkovboiSS** [comment]
Hi @GorelH 
According to #10508, many-to-many relationships are currently in 3.0 milestone.

**Comment by GorelH** [comment]
size 2~4-weeks of dev works, this blocked our adoption of .NETCore since v1.

**Comment by leak** [comment]
I really wish someone could make the SQLite provider actually production ready after 4 years by solving #329.
So far I've been filling that gap myself but the recent changes in 2.1 made it so annoyingly complicated (#12357) that I can't even guess how many hours I would have to put into it to make it work again.

Not being able to create simple rename column migrations is just not realistic for any reasonable application.

**Comment by ErikEJ** [comment]
@leak Have you considered using another database engine?

**Comment by leak** [comment]
@ErikEJ Yes, also I think we've had that exchange before ;)
https://github.com/aspnet/EntityFrameworkCore/issues/329#issuecomment-323261847

**Comment by bricelam** [comment]
@leak you are one of a few people who could contribute improvements in this area. Please don't hesitate to start a discussion with us on a proposed design and start working on a PR.

**Comment by dzins** [comment]
We switched from NHibernate to EF 6 a few years ago, we are in the same boat as some of the other people commenting on the topic of many-to-many relationships.  We have an existing application used by many partners and customers and it is not an option to just go in and change all of the many-to-many properties in the object model, but we really really need to get to .NET Core.

We are now evaluating switching back to NHibernate.

**Comment by NetTecture** [comment]
Personally I literally do not care about m:n relationships as long as half my queries that are non-trivial (i,.e. not just simple table queries) generate exceptions, invalid sql and other stuff. I seriously consider moving back to ef6 - too many thigns do not seem to get fixed, with bug fixes not coming like at all. Yeah ,2.2 - nice. First preview in August, release end of the year.

Where is 2.1.2? Even as preview? Where is 2.1.3 (because hey, milesotne 2.1.2 never made it into milestones)? What about weekly/byweekly previews on nuget so we can hope some of the stuff that blocks gets fixed?

Literally foced to consider moving back to ef6 - that at least works in non trivial sql cases, it seems.

**Comment by scharada** [comment]
EF core was supposed to be the "problem solver" and "the framework to use" ... when such important and critical features as m to m are in the bottom of the todo list, when the daily used operations in development are not supported and you have to rely on workarounds, you start thinking if you made the right choice going for ef core.... 
this is not to talk about performance ... EF is known to produce poor quality queries and can be dramatically improved... MS sells cloud based Db technology but provides disparate frameworks that do not provide the best results ... besides the really costly queries ef core produces, ms just released a first  preview for ef core for cosmosdb, the supposed universal cloud db platform ... how in the world can we  build systems using ef core when the current technology either does not do all what you want and if it does, it does it is incomplete or has no support for the DB you want to use .... if you are stubborn and still go for it using the current frameworks, your cloud costs skyrocket ... the ef core framework has to take a real deep look at the situation if they want to keep people to use it. there are other options around and if one moves away and goes for another tech,, it's unlikely the comeback, if any,  will be any time soon ...

**Comment by marchy** [comment]
Could we please get an EF6 roadmap put up as well? (similar to the Core one: https://github.com/aspnet/Announcements/issues/308)

For many reasons the community has beat to death at this point – including no migration paths from EF6 to EFCore – EF6 is the only framework that any production team can sanely consider for the foreseeable time in the future (ie: 2019/2020).

Please shed some light on future EF 6.X releases.
Would be great to have some innovation moving on that front – ESPECIALLY with the support for running on the .NET Core 3 runtime (THANK YOU guys).

#noplansoftryingefcoreeveragain

**Comment by marchy** [comment]
Thanks for that clarification @ErikEJ.

I hope the team can focus on migration paths from EF6 to EFCore once it's ready if that's the case then.

In particular, how a team is to take a set of existing EF6 migrations and switch over to EFCore migrations.
The [current guidance](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code#existing-migrations) is insufficient since it doesn't tackle how a new developer/database can be created with an initial migration, while simultaneously supporting new incremental migrations. The current guidance seems to require manually copying over an initial starting database rather than the EFCore migrations being able to generate the database from scratch.

Would be great to have the team's explanation of a more thorough strategy – possibly including porting over each EF6 migration into an equivalent EFCore one – or more illumination of a practical porting strategy for production-grade codebases. Right now the only path seems to be re-mapping the entire database manually one EFCore migration at a time, then bulk copying the resulting data into this new database. I hope you can appreciate the difficulty/effort/frustration of this, and the fact that we are forced to indefinitely delay this effort until the EFCore team can have a real solution to it.


Thanks!
