### ISSUE TITLE
Default value for new 'Role' column get's 'dbo'

### ISSUE THREAD

**Issue by Jonesie** [dotnet/efcore#12488]
I added a 'Role' column to my User entity persisted to SQL Server.
I set a default for the role in OnModelCreating as 'User'.
After migration the column has 'dbo' as the value for existing users.

Funky :)

### Steps to reproduce

1. Create any entity with a Role string property.
2. Add the following to OnModelCreating:

```
builder.Entity<ENTITYNAME>()
            .Property(b => b.Role)
            .HasDefaultValueSql("Something");
```

3. Create migration and update db.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Insider 17692
IDE: Visual Studio 2017 15.7.4

**Comment by ajcvickers** [comment]
@Jonesie This is because the `HasDefaultValueSql`  the defines the _SQL_ use use in the default constraint of the column. Which for "User" means return me the current user--that is, "dbo".

If you want to set a constant value, rather than a SQL expression, then use `HasDefaultValue("User")` instead.
