### ISSUE TITLE
querying with datetime add minutes failing

### ISSUE THREAD

**Issue by andrewr93** [dotnet/efcore#12512]
![image](https://user-images.githubusercontent.com/34843070/42130376-a7adb276-7ce3-11e8-932d-2a83f2067534.png)

![image](https://user-images.githubusercontent.com/34843070/42130383-dfaf6bd8-7ce3-11e8-918f-548eb9f84f7a.png)

Not sure if i need to explain anything else, core/ef 2.1.0, running on windows 10

**Comment by ralmsdeveloper** [comment]
Hello @andrewr93,

There are some quirks here:

1 - You are making a query using criteria on the server and the second query is bringing all records and doing the eval on the client, this means that you may have non-real information, because the SQL server time may not be synchronized with your machine.

**Your first query generates something like this:**
```sql
SELECT [p].[LastCheck]
FROM [MonitorEntries] AS [p]
WHERE DATEADD(minute, 10E0, [p].[LastCheck]) < GETDATE()
```

**Already the second one (bad query):**
```sql
SELECT [p].[LastCheck]
FROM [MonitorEntries] AS [p]
```

For the SQL Server provider there is something more precise for you to use:
```csharp
context
    .MonitorEntries
    .Where(entry => EF.Functions.DateDiffMinute(entry.LastCheck,DateTime.Now) < 0 )
    .ToList()
```


My advice is not to use a validation with dates using an expression, instead use the subtraction between the dates. 

`DateTime.Now.Subtract (x) .TotalMinutes> 0`
