### ISSUE TITLE
[question] Understanding "GenerateOrdering"

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#12519]
What is the purpose of GenerateOrdering with "(SELECT 1)"

It seems to simply generate unneccessary SQL ORDER BY statement - if it is required, would 
"ORDER BY 1" work? (I have issues with an engine that only supports ordering on columns)

### Further technical details
EF Core version: 2.1
Database Provider: any
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by ralmsdeveloper** [comment]
Hello @ErikEJ,

The 1 would be the ordinal numeral of the select, so I observed this instruction will only be printed when there is a constant.

Example: `select 'x' from bar order by 1 desc`.

it's just a guess, it makes sense to you!

**Comment by ErikEJ** [comment]
I am not sure that (SELECT 1) refers to the first column in the SELECT list, but I am well aware that 1 does - that is the reason for my question - why not just use "1" iso (SELECT 1) ?

**Comment by ralmsdeveloper** [comment]
Yes, I understood, I looked for information on why and did not find it, I really believe that we could use only "1" instead of "(SELECT 1)", since this is no longer an expression and becomes a sub-query, looking at some tests I realize that does not make much sense!

For Exemple:
https://github.com/aspnet/EntityFrameworkCore/blob/dev/test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs#L6290-L6301

**Comment by ajcvickers** [comment]
@smitpatel to respond.

**Comment by smitpatel** [comment]
`Order by 1` indicates that ordering should be done on first column in projection. (same for other numbers). Same is true for parameters too (using their values). Hence if linq has `OrderBy(e => 42)` we cannot generate `Order By 42` in SQL since it would be incorrect.

We cannot ignore Order By fully either. If SelectExpression has Limit/Offset then there must be an Order by clause else its invalid SQL. So we need a "cookie". `Order By (Select 1)` is same as ordering by a constant in linq. 

Further, side effect of current implementation, by the time we realize that ordering is by a constant value and it may not be needed (not skip/take), we have already printed `ORDER BY ` in SQL so we have print the cookie 😉

**Comment by ErikEJ** [comment]
@smitpatel any suggestions for workarounds for an engine that only supports ORDER BY a column?

**Comment by smitpatel** [comment]
@ErikEJ - What do you intend to do if the ordering is by non-column? This part is just SQL printing. If you need to cause a client eval then better place is in provider specific QueryModelVisitor VisitOrderByClause method.

**Comment by ErikEJ** [comment]
Thanks!
