### ISSUE TITLE
Provider: best way to translate Any() to something other than SELECT CASE WHEN EXISTS

### ISSUE THREAD

**Issue by dfyx** [dotnet/efcore#12532]
Not a bug, just some help needed for writing a provider.

I'm writing a provider that sends SQL statements via COM to a legacy Visual FoxPro 9 application. By default EF Core translates `var any = X.Any(x => x.Foo == 0)` to something like the following:

```sql
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM X x
        WHERE x.Foo = 0)
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
```

Sadly VFP9 doesn't supports neither `CASE` nor `SELECT` without `FROM`.

One version that would work is:

```sql
SELECT IIF(COUNT(*) > 0, 1, 0)
FROM X x
WHERE x.Foo = 0
```

Sadly I couldn't find the right spot to implement it.

### Further technical details
EF Core version: 2.1.0.0
Database Provider: writing my own, inspired by the default ones
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.3

**Comment by dfyx** [comment]
Another version that works is what ActiveRecord does:

```sql
SELECT 1 AS one
FROM X x
WHERE x.Foo = 0
LIMIT 1
```

Or translated to VFP (yes it looks funny but we can't do much about the `TOP` syntax and its requirement for an order)

```
SELECT TOP 1
    1 AS one
FROM X x
WHERE x.Foo = 0
ORDER BY one ASC
```

(Note that in this case it doesn't return a row with `0` for "not found" but instead no rows at all)

**Comment by ajcvickers** [comment]
@smitpatel to follow up.

**Comment by smitpatel** [comment]
@dfyx - Not able to write a SelectExpression without From clause is pretty serious limitation when it comes to queries generated by EF Core. Since almost all SQL based providers supports such queries (even with dummy From Dual in Oracle), there would be multiple places where such queries could arise. (Simplest case, `All` operator which translates to Not Exists same as above).
You should consider finding a way to modify such SQL to make it work in your provider.
If you want to go hard way and for this case only then you can provider implementation of `IRelationalResultOperatorHandler` derived from `RelationalResultOperatorHandler` and handle such result operators by providing suitable translation.
Another easier and more generalized way would be to let EF Core generate SelectExpression and post-process it to change its shape by identifying patterns like above.
