### ISSUE TITLE
Add option to ignore data seeding on database update

### ISSUE THREAD

**Issue by lslv1243** [dotnet/efcore#12648]
When I run the `ef core update database` command I would like to be able to specify that the seed operations (Insert, Update, Remove) should be ignore (a flag).

**Comment by lslv1243** [comment]
I need this option because when I run migrations in production I do not want to seed.

**Comment by luishkraus** [comment]
+1

**Comment by clockwiseq** [comment]
Or maybe you want to seed data that is specific to that migration.  In my case, I have a migration that added a new type and/or status table and I want to go ahead and seed that new table with some values even in production that I plan on using.  The having() method didn't work for me as it threw an exception since I have database generated values for my Id (Key) field.

**Comment by bricelam** [comment]
``` csharp
if (Environment.GetEnvironmentVariable("ASPNET_ENVIRONMENT") != "Production)
{
    migrationBuilder.Insert(...);
    ...
}
```

**Comment by clockwiseq** [comment]
What is the migrationBuilder object?

**Comment by clockwiseq** [comment]
Do you mean [InsertData](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.migrationbuilder.insertdata?view=efcore-2.1#Microsoft_EntityFrameworkCore_Migrations_MigrationBuilder_InsertData_System_String_System_String___System_Object___System_String_)?

**Comment by AndriySvyryd** [comment]
`HasData` is for specifying data that will be managed by migrations as your database evolves. Unless you need to preserve the data in the test database as the migrations are applied it would be best to use a different approach to add seed data.
