### ISSUE TITLE
Support ExpandoObject for HasData

### ISSUE THREAD

**Issue by iamkarlson** [dotnet/efcore#12689]
It's not possible to use ExpandoObject for HasData since EF using reflection for getting properties of the passed object. When you apply reflection on ExpandoObject it returns dictionary with properties and not the properties itself. Then EF just aborts migration building.

### Further technical details
EF Core version: 2.1.1

**Comment by divega** [comment]
@iamkarlson could you please provide example usage so that we (and others) can assess the value of this feature?

**Comment by iamkarlson** [comment]
@divega it's a must-have feature when you add some properties for you models manually. 

For example, you have an entity User. It exposes Id, Name, and Password. However, you want to add some auditing fields which won't be available for your app developers, but context will add values to these fields using following instruction in overridden SaveChanges method of your context 				
```
entry.Property<string>(CREATED_BY).CurrentValue = initiator;
```

Such auditing fields usually implemented with triggers in the database. But since we're all in the code first world it's a good option to have that managed by DatabaseContext. 

Now, let's imagine a situation, you're seeding some users by default. 

```
var data = new []{ new User { Id = 1, Name = "Admin", Password = "qwerty" }};
builder.Entity<User>().HasData(data.ToArray());
```

Thus, when you're trying to insert seeded data without that auditing values your migration fails. 

You can either insert your data with anonymous type 

```
var data = new []{ new { Id = 1, Name = "Admin", Password = "qwerty", CreatedBy = "Seeding" }};
builder.Entity<User>().HasData(data.ToArray());
```

or to re-create your type with reflection and runtime types with all the fields in place. 

If you prefer anonymous types over the reflection, you're loosing strongly typed validation for seeding. 
Recreation of the type is considerable but I would like to keep my codebase as much as possible easy to understand.

Both of the problems can be solved with Expando object. You just copy all properties of your object to expando and add required new. However, EF is getting properties by reflection and here we come to the issue. ExpandoObject is just a type. Specially implemented but it's still the same as others. So in response to reflection it returns back only properties which is used to trick you with dynamics (i.e. dictionary for storing properties). If EF could distinct expando as an exclusive type (or even all its derived types) and parse properties from the properties list it would help solve that problem. I suppose reflection is the simplest instrument to achieve what EF is particularly  trying to achieve here but it just doesn't work in elaborated scenarios.

**Comment by divega** [comment]
@iamkarlson Thanks for the detailed explanation. I asked you specifically about **example usage**, meaning how the call to `HasData` would look like, because I was hoping to understand better the advantage.

When you said that using anonymous types you lose "strongly typed validation", my first read is that you are concerned that if you make a typo in the name of a member of the anonymous type and have that data you put on that member go nowhere, or even be of the wrong type.

But if that is what you mean, then I don't understand how ExpandoObject helps. 

Don't get me wrong, I think it would be interesting to support even property bags (i.e. IDictionary<string,object> in HasData. What I am really looking for is reasons this could be higher priority than what I think it is.

**Comment by ajcvickers** [comment]
This scenario is covered by #9999, so closing this as a duplicate with a pointer to this discussion.

**Comment by iamkarlson** [comment]
@ajcvickers thanks, exactly what I am looking for
