### ISSUE TITLE
Provide a way to control client evaluation behavior on a per query basis

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#12844]
Based on the feedback we usually see this is very common and something like an `AsServerOnly()` query operator would be more usabel than the current way to turning client evaluation warnings into errors.

**Comment by optiks** [comment]
An extension method on IQueryable<T> for this would be great.

My main use case is where `.ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning))` has been configured on the context, but where I still want to allow _some_ client evaluation to occur (most likely because there is no server-side support).

i.e. I don't want an error thrown if there's nothing I can do to fix it.

**Comment by smitpatel** [comment]
@optiks - Calling `AsEnumerable` method on `IQueryable` will allow you to do client evaluation even when warnings are configured to throw.

**Comment by ajcvickers** [comment]
Added to Qu3ry issue.

**Comment by optiks** [comment]
@smitpatel, `AsEnumerable()` isn't discoverable enough nor explicit enough IMO. I don't see how `AsEnumerable()` implies that client-evaluation is acceptable?

**Comment by smitpatel** [comment]
`AsEnumerable` is similar to calling `ToList`. You are asking EF to materialize query results upto that point, whatever happens afterwards is outside of EF scope (aka client eval). If client eval in EF is throwing exception then it would also tell you what failed to translate which gives easy pointer where to put `AsEnumerable` in your query.

**Comment by optiks** [comment]
Please also consider whether it would make sense to provide a predicate on `Throws`, i.e. something like `warnings.Throw(RelationalEventId.QueryClientEvaluationWarning, query => /* some logic* / true)`. I'm not sure what the appropriate type for `query` would be.

I think this would let us them implement this behaviour ourselves.

**Comment by ajcvickers** [comment]
Closing as not needed now since the query changes for 3.0.
