### ISSUE TITLE
Global Filter Cause Case Sensitive Issue

### ISSUE THREAD

**Issue by tianxiaaiwojs** [dotnet/efcore#12848]
After apply global filter, I notice that data return from EF core is been case sensitive, 
eg. Context.User.Where(x=>x.LoginId == viewModel.LoginId).FirstOrDefault();

inside database have records with loginId is a and b, before apply Global filter, EF core will return record a when viewModel.LoginId is a or A, but after apply Global filter, only when viewModel.LoginId is a will return record a.

```c#
builder.HasQueryFilter(x => !ExcludeEntity.IsExcludeUser(x)); // only when viewModel.LoginId is a will return record. 
builder.HasQueryFilter(x => !(x.IsDel.HasValue ? x.IsDel.Value : false)); // only when viewModel.LoginId is a will return record. 
builder.HasQueryFilter(x => !(x.IsDel.Value)); // only when viewModel.LoginId is a will return record. 
builder.HasQueryFilter(x => x.LoginId != "b"); // viewModel.LoginId is a or A both will return record. 
```
ExcludeEntity.IsExcludeUser
```c#
public static bool IsExcludeUser(User user)
{
	//return ExcludeUser.Contains(user.LoginId);
	return user.LoginId != "b";
}
```

after check SQL profile and debug inside VS, i notice global filter is not apply in sql command, seems it's done after data been retrieved.

I have checked MSDN document, it's say: "Filters cannot contain references to navigation properties." I dont whether it's because of this.

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6

**Comment by smitpatel** [comment]
It has nothing to do with any limitation of filter. It is general case of passing in opaque or untranslatable code in Expression tree in your query which in this case comes through query filters.
1. First filter contains static method call (instead of `Expression<Func<>>`). Hence we cannot look inside the method and we need to evaluate the whole method on client.
2 & 3. EF Core cannot translate `HasValue` or `Value` members which causes client eval. It is easy to get around this. e.g. `x => !(x.IsDel ?? false)` which would be translated to server.
4. This one is translated to server correctly.

When string comparisons are evaluated on server it is case insensitive by default in SqlServer. Same thing when run on client is case sensitive since that is how string clr type works.

Best course of action would be to write a query filter which is not using client methods and can be server translated.
