### ISSUE TITLE
ChangeTracker.AcceptAllChanges not called

### ISSUE THREAD

**Issue by amoorthaemer** [dotnet/efcore#12850]
Hi,

I have implemented a ChangeTracker (derived from the standard one) that does auditing on entities, but ChangeTracker.AcceptAllChanges never gets called. I suspect that its StateManager instance gets called directly bypassing ChangeTracker...

Bert

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS Enterprise latest

**Comment by ajcvickers** [comment]
@amoorthaemer ChangeTracker is a facade class that just provides an API over the services that implement the operations.

Note for triage: We can look into routing the internal call through the ChangeTracker for this and maybe also for DetectChanges, which would allow people to override these. However, the state manager already knows which entries to AcceptChanges on, so it would add work to call the public method and calculate again. Also, IChangeTrackerFactory is internal, so there is currently no public way for an overridden ChangeTracker to be used.

**Comment by amoorthaemer** [comment]
@ajcvickers .... IChangeTrackerFactory is public... therefore I was able to implement my own version which in turn instantiates my own version of ChangeTracker. It works without any issues, except for the ChangeTracker’s overridden methods

**Comment by amoorthaemer** [comment]
@ajcvickers .. Just to inform you ... I'm using overrides for SaveChanges(Async) to circumvent this issue and that will do the job well... Anyway thanks for looking into this

Bert

**Comment by ajcvickers** [comment]
@amoorthaemer [IChangeTrackerFactory](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/src/EFCore/ChangeTracking/Internal/IChangeTrackerFactory.cs) is internal in the sense that it is in an Internal namespace and documented as internal. We do this so that people can, at their own risk, work with the internals of EF without having to resort to Reflection, etc. However, API documented as internal may change in a breaking way in any release, so it should only be used in situations where such a break is considered acceptable.

**Comment by ajcvickers** [comment]
Triage: we decided for now not to make any changes in this area.
