### ISSUE TITLE
"Project not found" when trying to "update database" over published assemblies

### ISSUE THREAD

**Issue by StefanRiedmann** [dotnet/efcore#12933]
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

dotnet ef database update --startup-assembly ./Backend.WebApp.dll --assembly ./Backend.Data.dll --verbose
Microsoft.EntityFrameworkCore.Tools.CommandException: No project was found. Change the current working directory or use the --project option.
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.FindProjects(String path, String errorWhenNoProject, String errorWhenMultipleProjects)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
No project was found. Change the current working directory or use the --project option.

### Steps to reproduce
- Create a .NET Core App with a dedicated migrations assembly
- Run 'dotnet publish -c Release'
- Execute dotnet ef database update --startup-assembly ./Backend.WebApp.dll --assembly ./Backend.Data.dll --verbose

### Further technical details
EF Core version: 2.1
Database Provider: MS SQL Server for Linux (in Docker)
Operating system: Mac
IDE: Command Line, Visual Studio for Mac

**Comment by ajcvickers** [comment]
@StefanRiedmann The intention is for ef.dll be used for this kind of situation, since it contains the actual code over which the tools are a shim. However, this can be a bit tricky at the moment. We have a [docs issue](https://github.com/aspnet/EntityFramework.Docs/issues/691) to help make some things clearer--this could in turn result in project changes as well. For now, check out this [post and tool](https://www.benday.com/2018/07/05/deploy-entity-framework-core-2-1-migrations-from-a-dll/) from @benday which has some good guidance.

**Comment by StefanRiedmann** [comment]
Ok, thank you very much guys. I already decided to go with a built-in solution, so the application should check&run the migrations on startup. 

Cheers
Stefan
