### ISSUE TITLE
Change/Set DbSchema for every request

### ISSUE THREAD

**Issue by masoud-bahrami** [dotnet/efcore#12939]
Hello.
I have a Multitenant Application.
I want to change the default schema, which used by EF Core, based on Tenant's DbSchema and connection 
each time a new instance of DbContext  is creating.
Can any one suggest a good solution with minimum overhead?

**Comment by ajcvickers** [comment]
@masoud-bahrami [This post from @bricelam](https://stackoverflow.com/questions/41979215/how-to-implement-imodelcachekeyfactory-in-ef-core) shows how to use OnModelCreating to build a different model for each tenant. This is probably the best approach to use for now, although it can result in a lot of models being created if a lot of tenants are in use at the same time. Issue #9965 is tracking an enhancement that would make this better by allowing the model to be paramterized on teh schema.

**Comment by masoud-bahrami** [comment]
@ajcvickers Many thanks.
@bricelam 's solution is okay.

But i'm a little bit confusing about IModelCacheKeyFactory. In _OnModelCreating_ every time i populate _DbSets_ . So i want to ignore calling  _OnModelCreating_ ,if the current tenant already used the context.

The internal use of IModelCacheKeyFactory is confusing for me, and I'm dumb on it.

**Comment by ajcvickers** [comment]
@masoud-bahrami OnModelCreating is called when EF needs to build a model. It does this when there isn't a model in the cache that can be used. The ModelCacheKey is used to determine whether there is a model in the cache. Normally the key is made up only of the DbContext type. This means that the first time a DbContext of a given type is used, there will be no model in the cache, and OnModelCreating will be called as the model is built. The next time a context of the same type is used, the model will be found in the cache, and OnModelCreating will not be called. In your case, instead of just using the context type in the key you will also need to add something that identifies the tenant. This means that the first time a context for a given tenant is used, OnModelCreating will be called, and the schema can be set appropriately in the model.
