### ISSUE TITLE
Expressions: Create Navigation Property

### ISSUE THREAD

**Issue by Condra963** [dotnet/efcore#12965]
Hi all,

I was wondering how to create an Expression where you can assign a Navigation Property? What do i have to take into account?

I tried something like this `Expression.Bind(propertyInfo, EFPropertyExtensions.CreateEFPropertyExpression(memberExpression, propertyInfo))` but this is still not creating my Navigation Property.

Why is this an issue? Now everytime i convert my Expression my Navigation Properties are included. So i should create an `EntityType` with `EntityProperties` when i use `Expression.New`.

Does this make sense what i try to do?

Thanks.

**Comment by ajcvickers** [comment]
@Condra963 Can you describe/show how you intend to use the expression once it is built? This will help us understand what kind of expression you want to create.

**Comment by Condra963** [comment]
@ajcvickers I tried to make a short example for you. `EntityParent` is a Navigation Property. I understand why in this case the Navigation Property is loaded. But i want that it stays just an Navigation Property that is not loaded until i `Include` the Property.

Now i try to do this in `Expressions`, it's completely clear for me how to do this, but instead creating a `Type` i want to create an `EntityType` with a Navigation Property `EntityParent` for example. And that's the part where i could use some explanation. I think i just miss something i should take in account so this keeps working as a normal query in `EntityFrameworkCore`.

```
var test = _testsDbContext.Entities
    .AsNoTracking()
    .GroupJoin(
        _testsDbContext.Joins,
        e => e.Name,
        t => t.Key,
        (e, t) => new { Entity = e, Joins = t })
    .SelectMany(
        group => group.Joins.DefaultIfEmpty(),
        (group, t) => new { group.Entity, JoinName = t.Value })
    .Select(group => new Entity()
    {
        Id = group.Entity.Id,
        Name = group.JoinName ?? group.Entity.Name,
        TwoLetterCode = group.Entity.TwoLetterCode,
        ThreeLetterCode = group.Entity.ThreeLetterCode,
        EntityParentId = group.Entity.EntityParentId,
        EntityParent = group.Entity.EntityParent
    })
    .ToList();
```

**Comment by Condra963** [comment]
Here is the SQL i want to execute, if i execute this i still want to have the result `Test` object instead of an `Anonymous` object and i also want that my navigation properties are still navigation properties. Makes this sense? 

```
SELECT c.Id, COALESCE(t.[Value], c.[Value])
FROM [Alvey.Tests].Tests.Tests c
LEFT OUTER JOIN [Alvey.Tests].Tests.Joins t
ON t.[Key] = c.[Name]
ORDER BY c.Id
```

**Comment by smitpatel** [comment]
@Condra963 - If I understand what you are trying to achieve correctly then this is by design.
When you create a `MemberAssignment` like that in your projection, EF Core will project out that navigation always (without requiring include). If you want to control the navigation behavior based on existence of `Include` then you don't need anything specific to do with navigations. You just need to project out the Entity as is. Include will do its work by own.
Additionally, if in your projection if you are constructing `EntityType` by yourself, we still do not consider it as an `entity`. This is by design. The reasoning behind this is, to track entities (which would be stored back in database), entities needs to have correct Primary keys through which we track them and make sure database is updated correctly. If user is manually constructing the entities, then we cannot be certain of that. Therefore we don't track it or treat them like normal entities. Hence, when you use `Include`, since root entity is not projected out (rather user constructed entity is), we ignore the include.

**Comment by Condra963** [comment]
@smitpatel - I understand it in some cases, but is there no way to go around that? Because i have multiple cases where i want to do this and even sometimes recursive. But it's a little bit crazy that every time i want to `Coalesce` a property or modify a property of an entity that every Navigation Property is loaded as well. Or am i the only one which such database designs?
And what about `EFPropertyExtensions.CreateEFPropertyExpression` for which use is this? Is this something i can use? Because the `Query` and the `Linq` i show you is something i actually want to do in `Expressions`. So maybe if i go deep enough with my expressions there is a possibility?

Sorry if i say some weird things, but i just try to brainstorm about a workaround or a solution for this case.

**Comment by smitpatel** [comment]
We have started thinking in that direction in https://github.com/aspnet/EntityFrameworkCore/issues/12668
But as of now, there is no way. Entity constructions through user and EF Core are different types for us. To be more precise what you intend to do is not possible in LINQ so expressions is out of question already. As for the design, it is quite unique. I am not sure why you would want to assign a entity property based on another table inside querying. We recommend using DTOs for most data passing tasks instead of using entity types. Worst-case as a work-around you would do this. (untested code)
```C#
var query = db.Entities.... // Perform GroupJoin/SelectMany
    .Select(group => new { group.Entity, group.JoinName }
    .ToList()
    .Select(e => new Entity() {..../* entity projection as you wish */)
    .ToList()
````
In above query since you are projecting out the Entity, the include will work as usual and EF Core will allow to do everything. Calling `ToList` will make database query. Based on your Select in query you posted, this will not fetch any additional data from server. Once EF Core gets results from server, you can turn the anonymous object in whatever shape you want. (even entity type). Since we don't track user constructed entities in query, your results here won't be tracked but since you projected out entities in EF selector, those entities will be tracked. You can do AsNoTracking query and attach your resulting entities if you want. Or another alternative is, instead of writing custom client side projection, you can just do assignment based on the anonymous type object to use coalesce on that particular property. Once you are able to get this running in LINQ, converting to Expression shouldn't be difficult.

As for `EFPropertyExtensions.CreateEFPropertyExpression` method, it is code in `.Internal` namespace. I recommend not using it. APIs inside `.Internal` namespace are available to public but we can break them in between minor releases. So you should only use them if you are fine with us breaking you. Else it would be easy to just write similar reflection code yourself.

**Comment by Condra963** [comment]
Well the query you suggest is a solution but like you say in worse case because when you will look into performance this will not be a decent solution i think.

For the `internal` namespace i'm fine with it because i could use this temporary until there comes a solution for this situation.

But i will start with look into EF Core source code how you handle your `Include` methods, because there you also create an `Entity` into your `Entity` if i understand the working of EF Core correctly. And i also saw things like `TableExpression` and `ColumnExpression`. And i will follow the discussion so i know when there are changes about this because my opinion is that this is not such a strange action.

If you could direct me to useful code i could look into that would be very helpful, even if it's internal, that would spare me some search work in EF Core source code.

Anyway already thanks for the help!
