### ISSUE TITLE
DateTimeOffset? different behavior GetValueOrDefault and Value depends on the context of the request

### ISSUE THREAD

**Issue by voronov-maxim** [dotnet/efcore#13015]
```c#
class Order
{
public DateTimeOffset? Date { get; set; }
}

dbContext.Orders.Where(o => o.Date.GetValueOrDefault().Year == 2018).ToArray();
```
```
Exception message:
System.InvalidOperationException: 'Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'where ([o].Date.GetValueOrDefault().Year == 2018)' could not be translated and will be evaluated locally.'. 
```
```c#
dbContext.Orders.Where(o => o.Date.Value.Year == 2018).ToArray();
```
No throw exception

```c#
dbContext.Orders.Select(o => o.Date.Value.Year).ToArray();
```
```
Exception message:
System.InvalidOperationException: 'Nullable object must have a value.'
```
```c#
dbContext.Orders.Select(o => o.Date.GetValueOrDefault().Year).ToArray();
```
No throw exception

Cannot write test use EF InMemory provider, it works fine with GetValueOrDefault.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 8.1
IDE: (e.g. Visual Studio 2017 15.8)

**Comment by ajcvickers** [comment]
@voronov-maxim 
The first case is client-evaluated due to #10153, with some cases being fixed for 2.2.
The second case is fully translated and hence works.
The third and forth cases do not give a client evaluation warning because we don't warn for this in the projection selector--it's to some degree always client evaluation.
The third case, if Date comes back as null, then this will throw in the normal C# way.
The forth case works because it handles the null coming back.
