### ISSUE TITLE
Expand RelationalDbContextOptionsBuilder with MigrationsAssembly(Assembily assembly)

### ISSUE THREAD

**Issue by generik0** [dotnet/efcore#13012]
HI

Would it not be optimal to add a extra method in RelationalDbContextOptionsBuilder that allows for MigrationsAssembly(Assembily assembly)? 

That way we are sure the assembly is loaded. With DI and decoupling it is not always a sure thing that things are loaded.

Thanks for you time...

**Comment by ajcvickers** [comment]
@generik0 It's often not possible to load the assembly directly due to circular dependencies, so this would often require dynamically loading from a name anyway. In either case, EF tooling will load the assembly again because there is some isolation between your application code and tooling. Therefore, we don't think this overload is particularly useful. However, if you want to ensure your application can load the assembly, or you have it loaded anyway, then passing Assembly.Name is easy.
