### ISSUE TITLE
Cannot compile query returning IQueryable<?>

### ISSUE THREAD

**Issue by Angelinsky7** [dotnet/efcore#13040]
I would like to compile a query that return an IQueryable<?>
But because of this :  https://github.com/aspnet/EntityFrameworkCore/blob/d59be61006d78d507dea07a9779c3c4103821ca3/src/EFCore/Query/Internal/QueryCompiler.cs#L27-L29 

and 

https://github.com/aspnet/EntityFrameworkCore/blob/d59be61006d78d507dea07a9779c3c4103821ca3/src/EFCore/Query/Internal/QueryCompiler.cs#L145-L147

the following exception occurs
```
Exception message:
Stack trace:

System.InvalidCastException: Unable to cast object of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.QueryContext,System.Collections.Generic.IEnumerable`1[ch.infodev.core.asp.sys.model.bon.BonEchange]]' to type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.QueryContext,System.Linq.IQueryable`1[ch.infodev.core.asp.sys.model.bon.BonEchange]]'.
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CreateCompiledQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQuery`2.CreateCompiledQuery(IQueryCompiler queryCompiler, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.<>c__DisplayClass6_0.<EnsureExecutor>b__0(TContext c, LambdaExpression q)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam1,TParam2,TValue](TValue& target, TParam1 param1, TParam2 param2, Func`3 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.EnsureExecutor(TContext context)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, CancellationToken cancellationToken, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQuery`2.Execute(TContext context)
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
public class DataContext : DbContext {
    public DbSet<Data> Datas { get; set; }
}

public static class DataContextExtensions {
  private static readonly Func<DataContext , IQueryable<Data>> _DatasView =
     EF.CompileQuery<DataContext, IQueryable<Data>>((DataContext context) =>
       context.Datas /* a lot more things happening here... */
     );
  }
}

public static IQueryable<Data> DataRepository(this DataContext context) {
   return _DatasView (context);
}
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10 64bits
IDE: Visual Studio 2017 15.8

**Comment by smitpatel** [comment]
The methods you are calling is query compiler in the EF. We take an ExpressionTree and return a func which takes QueryContext (which is different from DbContext. It defines set of options for given particular query) and returns IEnumerable of results. Since your return type is `IQueryable<TResult>` (instead of `IEnumerable`) hence exception message.

**Comment by Angelinsky7** [comment]
@smitpatel thanks for you answer, yes i understood that, my question was more "why do you force cast to ienumerable instead of letting the user choose" i don't see any reason not to let the user use an iqueryable... (or any other compatible interface)

**Comment by smitpatel** [comment]
@Angelinsky7 - That is something not in hands of EF Core. As you point out, yes `IQueryable` allows composing further so you can re-use it. Except when you have IQueryble, any composing operator will grow the expression tree further (composition part). `IQueryable` does not return results. When you compile the `IQueryable` to `IEnumerable` that is what actually execute the query (single result operators are also terminating one). Hence the only way you can actually have a hook in EF Core to run the query is to convert to `IEnumerable` by calling `AsEnumerable`/`GetEnumerator`/`ToList` etc. methods. So that is the reason we return `IEnumerable` because that is the return type when you actually managed to invoke EF Core from C# world.
As for `EF.CompileQuery` expression, that is a compiled expression which knows how to execute to return results. Its a delegate (compiled code), so you can re-use it as many times as you want. It will run the code and return results. If you want to compose further then you are changing whole semantics of result calculation. The changes you cause in Expression tree may require the query to execute differently. And we may need to recompile whole expression tree again. CompileQuery method is not intended for that purpose. Consider passing IQueryable around yourself.

**Comment by Angelinsky7** [comment]
@smitpatel thanks a lot for you explanation, now i understand why you made this decision and that it was not the correct choice for me
