### ISSUE TITLE
DbContext caches the same tracked query, but still fires SQL queries against database

### ISSUE THREAD

**Issue by Rookian** [dotnet/efcore#13057]
When a tracked query is cached by EF Core, I would expect that no second SQL query is fired against SQL Server.

### Steps to reproduce
```
var order = await db.Orders.SingleOrDefaultAsync(x => x.Id == 1);
// Now Change a value from order in Database
var order1 = await db.Orders.SingleOrDefaultAsync(x => x.Id == 1);
```

order1 still has the old value. order and order1 have the same object id. So far so good.

**But why does EF Core still fires a SQL query, especially if it does not use the updated value?**

### Further technical details
EF Core version: 2.1.1

**Comment by ajcvickers** [comment]
@Rookian Queries are always executed against the database, not against in-memory data. This is because in the general case it is impossible to return consistent results without having the server evaluate the query. We are tracking #2982 to potentially change this, but it is a complex change. For more specific cases, the `Find` method can be used to return a single entity that is being tracked without hitting the database, and we are tracking #1948 to do this automatically for certain LINQ queries.
