### ISSUE TITLE
Store DB as JSON for SQLLite Unit Testing

### ISSUE THREAD

**Issue by arunprasathv** [dotnet/efcore#13059]
@bricelam
@smitpatel 

Is it possible to havea  json file  with all the tables to ingest into sqllite for unitesting, as its tedious to fake the data manually.

**Comment by bricelam** [comment]
Just check in the database?

**Comment by arunprasathv** [comment]
@bricelam Lets say JSON with 100 rows for each table

**Comment by bricelam** [comment]
Instead of checking in JSON and using it to generate a SQLite database, just check in the SQLite database itself.

**Comment by arunprasathv** [comment]
I'm creating SQLite Database using JSON. My understanding is we create SQLLite DB on the fly for unit testing.

**Comment by smitpatel** [comment]
You have multiple options here:
1. As @bricelam said, just commit a sample database used for testing. Data is not going to change. So instead of saving JSON you can store the DB file itself.
2. If you don't want to commit the DB file, (or using in memory mode for SQLite), then you can also use SQL script which will create and populate the data for you. We do that for our northwind data in SQL Server [here](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/test/EFCore.SqlServer.FunctionalTests/Northwind.sql) You can use https://sqlify.io/convert/json/to/sqlite to convert your JSON to SQL for one time.
3. If you don't want to commit SQL script either then you can write a parser which will take your JSON and convert to objects and insert them into db for you. There are several code snippets available to do so on internet in variety of languages including C#/Python/Java/Perl.

Hope above options help you achieve what you want to do.
