### ISSUE TITLE
Select inside Include in EF Core

### ISSUE THREAD

**Issue by etairi** [dotnet/efcore#13120]
I have an entity that looks like this (partially removed for brevity, it includes many other properties):
```C#
public class Tender
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    public string CreatorId { get; set; }
    [ForeignKey("CreatorId")]
    public virtual AppUser Creator { get; set; }
    public ICollection<TenderCircle> TenderCircles { get; set; } = new List<TenderCircle>();
}
```

The `TenderCircles` property is used to provide many-to-many relationship with another entity called `Circle`. `TenderCircle` entity looks like this:

```C#
public class TenderCircle
{
    public int TenderId { get; set; }
    [ForeignKey("TenderId")]
    public Tender Tender { get; set; }
    public int CircleId { get; set; }
    [ForeignKey("CircleId")]
    public Circle Circle { get; set; }
}
```

So, I'm doing the following query (partially removed for brevity, normally it includes many other `Include` and `ThenInclude` statements):
```C#
return _context.Tenders
               .Include(t => t.Creator)
               .Include(t => t.TenderCircles.Select(tc => new { CirlceId = tc.CircleId, TenderId = tc.TenderId }))
               .ToList();
```
But, it simply doesn't work. What I want to achieve is that I only want to get the `TenderId` and `CircleId` properties from `TenderCircle` and ignore the actual `Tender` and `Circle` objects. How can I achieve this in EF Core?

**Comment by SSkovboiSS** [comment]
Hi @etairi 

This should work fine with simply including `TenderCircles`.
```C#
return _context.Tenders
               .Include(t => t.Creator)
               .Include(t => t.TenderCircles)
               .ToList();
```

EF Core will not load navigations unless you explicitly include them. Like that:
```C#
return _context.Tenders
               .Include(t => t.Creator)
               .Include(t => t.TenderCircles)
                   .ThenInclude(tc => tc.Circle) 
               .ToList();
```

But note that Entity Framework Core will automatically fix-up navigation properties to any other entities that were previously loaded into the context instance. So even if you don't explicitly include the data for a navigation property, the property may still be populated if some or all of the related entities were previously loaded. That's why `Tender` navigation will be populated just because you load it anyway.

**Comment by ajcvickers** [comment]
@etairi Include only supports simple access expressions for navigation properties and is used to bring entire entities into the results. As @SSkovboiSS indicated, if you just include TenderCircles, then the "Circle" navigation property on TenderCircle will not be included, but CircleId will be. Since TenderCircle.Tender is an inverse navigation to the already included relationship from Tender to Circle, then, again as @SSkovboiSS points out it will be populated so as to keep the object graph consistent.

**Comment by etairi** [comment]
@ajcvickers 

> Since TenderCircle.Tender is an inverse navigation to the already included relationship from Tender to Circle, then, again as @SSkovboiSS points out it will be populated so as to keep the object graph consistent.

Yes, this indeed happens, and Tender is included, but I basically want to ignore it. Is there any way to force it to ignore Tender and Circle?

**Comment by ajcvickers** [comment]
@etairi Not currently, no. This is because the Tender entity is loaded, and the relationship from Tender to TenderCircles is loaded. Since the navigation property is part of a relationship that is being explicitly loaded it will always be set. The navigation property could be removed if it is not needed, but if the navigation exists and the relationship is loaded, then the navigation will be set.

**Comment by etairi** [comment]
@ajcvickers  Okay. Thanks for info! (Y)
