### ISSUE TITLE
EF Core relationship fixup interferes with Lazy Loading

### ISSUE THREAD

**Issue by lxh7** [dotnet/efcore#13166]
Updating an existing entity using TryUpdateModelAsync causes all navigation properties to be read, and through Lazy Loading the related entities are loaded.

This causes numerous queries to the database (in test case over 1000). After everything is loaded, the application hangs (in the real scenario, not in the simple example).

### Steps to reproduce
- use enclosed project [LazyLoadingTooEager.zip](https://github.com/aspnet/EntityFrameworkCore/files/2336188/LazyLoadingTooEager.zip) (Created following the steps in https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db, then added a Controller for Posts (same steps as the one for Blogs), Update the Edit method in PostsController to load the Post first and then use TryUpdateModelAsync() (pattern required for optimistic locking), add NuGet Package "Microsoft.EntityFrameworkCore.Proxies" 2.1.2, accept all updates, enable Lazy Loading by updating StartUp.cs (add the proper using Microsoft.EntityFrameworkCore.Proxies;, add .UseLazyLoadingProxies() to BloggingContext injection configuration in ConfigureServices() )
- run Create-Database from e.g. the NuGet Package Manager console
- Run the application
- Navigate to <appurl>/Blogs and Create a Blog (and Save)
- Navigate to <appurl>/Posts and Create a Post (and Save)
- Edit the Post, change some data and Save

Please check the debug log to see that during the TryUpdateModelAsync, the Blog is loaded. If LazyLoading is disabled, the Blog is not loaded.

An option/workaround might be to have EF Core populate properties through backing fields? (this is not the case in 2.1.2)

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Microsoft Visual Studio Community 2017 - Version 15.8.1

**Comment by ajcvickers** [comment]
@lxh7 Any code that traverses a graph automatically through property accesses will trigger lazy loading and potentially cause the whole graph to be loaded. Typically this is handled by temporarily turning off lazy-loading while the graph traversal happens. For example:

```C#
try
{
    context.ChangeTracker.LazyLoadingEnabled = false;
    TryUpdateModelAsync(...);
}
finally
{
    context.ChangeTracker.LazyLoadingEnabled = true;
}
```
When you say, "have EF Core populate properties through backing fields", this is what EF Core does (and in fact must do) for lazy-loading. For example, this is what prevents DetectChanges from having the same issues you are seeing. If you are seeing otherwise, then please open a new issue and post a runnable project/solution or complete code listing that demonstrates this behavior.

Keep in mind that `TryUpdateModelAsync` is not part of EF and so if you're having issues with that code (for example, is this where you are suggesting it should access fields?) then please follow up on the MVC repo: https://github.com/aspnet/Mvc
