### ISSUE TITLE
InMemory provider doesn't work when mixing enabling/disabling proxies

### ISSUE THREAD

**Issue by genne** [dotnet/efcore#13165]
If you add one entity to the database using proxies, and then try to query it with proxies disabled, you won't receive any data. It seems like enabling vs disabling proxies creates two separate databases.

### Steps to reproduce
```c#
class MyContext : DbContext 
{
    private bool _useProxies;

    public MyContext (bool useProxies)
    {
        _useProxies = useProxies;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase("Test");
        optionsBuilder.UseLazyLoadingProxies(_useProxies);
    }

    public DbSet<MyEntity> MyEntities { get; set; }
}

var proxyContext = new MyContext(true);
proxyContext.MyEntities.Add(new MyEntity());
proxyContext.SaveChanges();

var nonProxyContext = new MyContext(false);
var entities = nonProxyContext.MyEntities.ToArray();
Assert.That(entities, Is.Not.Empty); // Will fail
```

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

**Comment by ajcvickers** [comment]
@genne This is a manifestation of #9613 since model built for lazy-loading proxies is different than the one built for non-proxies, causing in this case a different service provider to be built. See PR #9692 for the way to force use of the same in-memory database database. See also #12895 which will allow proxy creation to be switched on and off without this side effect.

**Comment by genne** [comment]
Ok great I see. Thanks for the reply!
