### ISSUE TITLE
Migration change field length from field which is used in primary/foreign key

### ISSUE THREAD

**Issue by ice1e0** [dotnet/efcore#13178]
When I change the field length of a field which is used in a primary key or foreign key the migration only adds an `migrationBuilder.AlterColumn` but does not drop/create the primary key and foreign keys which 're using the field.

When I then run the migration script the SQL server throws an error because a change of a field which is used in a primary key / foreign key is not allowed.

I would expect that the migration script should automatically implement the drop and re-create of the primary key or foreign key.

p.s.: I don't know if that applies to indexes as well.

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 8
IDE: Visual Studio 2017 15.6.6

**Comment by bricelam** [comment]
Part of #329. Like indexes, it may work when increasing the max length--just not when narrowing.

**Comment by marcoz-tsn** [comment]
Please prioritize this issue, don't just enqueue in another one opened since 2 years before..

This is not about a new feature, rather a smarter logic in SQL server scaffolder, to automate a job that otherwise would require tons of manual and error-prone refactoring of migrations...

Think about the case a lookup table referenced in dozens of other tables, with an int PK that needs to be refactored to long...

**Comment by clement911** [comment]
I see this was closed as 'not planned'. 
Is there a recommended work around?

**Comment by 1Saurus2Saurus** [comment]
Would really like an update on this aswell, it'd be a great feature to have if there's a solution to re-creating the primary keys and foreign keys when a type or length changes.
