### ISSUE TITLE
SaaS应用资源有限的情况下如何自动回收内存使用量

### ISSUE THREAD

**Issue by qibunext** [dotnet/efcore#13194]
```c#
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "2.1.2"
    },
    "configProperties": {
      "System.GC.Concurrent": false,
      "System.GC.Server": false
    }
  }
}
```
SaaS应用资源有限的情况下如何自动回收内存使用量
数据访问使用的是 Entity framework + Pomelo.EntityFrameworkCore.MySql 
服务器配置
2核4G内存
当应用程序运行在.net core 2.0上时内存使用量会缓存增加，但使用量最大化时会自动重启应用程序，会停止一会，（目前只能先用.net core 2.0）
应用程序运行在.net core 2.1上时内存使用量也会缓存增加，使用量最大化时不会自动重启，一直停留在最大的使用量。导致静态文件访问不了，mysql数据库访问也会超时

Translation:

"How to automatically reclaim memory usage when SaaS application resources are limited
Data access using Entity framework + Pomelo.EntityFrameworkCore.MySql
server configuration
2 core 4G memory
When the application runs on .net core 2.0, the memory usage will increase, but when the usage is maximized, the application will be restarted automatically and will stop for a while. (At present, only .net core 2.0 can be used first)
When the application runs on .net core 2.1, the memory usage will also increase. When the usage is maximized, it will not restart automatically, and it will stay at the maximum usage. Resulting in static file access, mysql database access will also time out"

**Comment by qibunext** [comment]
```c#
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "2.1.2"
    },
    "configProperties": {
      "System.GC.Concurrent": false,
      "System.GC.Server": false
    }
  }
}
```

"How to automatically reclaim memory usage when SaaS application resources are limited
Data access using Entity framework + Pomelo.EntityFrameworkCore.MySql
server configuration
2 core 4G memory
When the application runs on .net core 2.0, the memory usage will increase, but when the usage is maximized, the application will be restarted automatically and will stop for a while. (At present, only .net core 2.0 can be used first)
When the application runs on .net core 2.1, the memory usage will also increase. When the usage is maximized, it will not restart automatically, and it will stay at the maximum usage. Resulting in static file access, mysql database access will also time out"

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by qibunext** [comment]
```c#
Thread 53 (Thread 0x7f4b5b9e3700 (LWP 28690)):
#0  0x00007f4b5e2b1f9d in open64 () from /lib64/libpthread.so.0
#1  0x00007f4b5ce0895f in TwoWayPipe::WaitForConnection() () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#2  0x00007f4b5ce01431 in DbgTransportSession::TransportWorker() () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#3  0x00007f4b5ce00149 in DbgTransportSession::TransportWorkerStatic(void*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#4  0x00007f4b5cf10ce2 in CorUnix::CPalThread::ThreadEntry(void*) () from /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.7/libcoreclr.so
#5  0x00007f4b5e2aae25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f4b5d7b5bad in clone () from /lib64/libc.so.6
```

**Comment by ajcvickers** [comment]
@qibunext We're really not going to be able to do anything with this kind of information. If you believe that there is a big in EF Core, then please post a runnable project/solution or complete code listing that demonstrates that bug.

**Comment by qibunext** [comment]
@ajcvickers 
https://github.com/qibunext/QibuOSS2/invitations
There are 120 or so memories in the site that are not enough to recycle without problems, but when there are many sites, 330 sites will have memory leaks.

**Comment by ajcvickers** [comment]
@qibunext As far as I can tell, the code there does not use Entity Framework.

**Comment by ajcvickers** [comment]
@qibunext You're asking a very broad question in what appears to be the wrong place. This issue tracker is specifically for bugs with Entity Framework Core.

An appropriate way forward for you would be:
* Debuig and distill the problem until you have some understanding of where the problem might be coming from and how it might be reproduced by somebody else
* Based on the results of doing that, find the appropriate place to file a bug or ask for help.

**Comment by qibunext** [comment]
@ajcvickers  I don't know how to refine, I have been looking for a long time, I have changed a lot of places, I still haven't made progress. I hope you can help me. I have been suffering from this problem for a long time.
我不知道如何提炼，找了很久，改了很多地方，还是没有进展，希望你们能帮帮我，这个问题我苦脑了很久

**Comment by qibunext** [comment]
@ajcvickers

**Comment by qibunext** [comment]
@ajcvickers

**Comment by qibunext** [comment]
@ajcvickers
