### ISSUE TITLE
EF Core, how can I configure it to target both different database system like SQL Server and MYSQL both together.

### ISSUE THREAD

**Issue by kunalpgithub** [dotnet/efcore#13218]
We are using EF core for our new project.

But we have one team member using Mac machine for development. So all other developers are using EF Core with SQL Sever but we want to use EF Core with MySQL for our Mac Developer.

It seems like we can configure DB Context to use either only SQL Server or MySQL.

Is there a way to tell EFCore to use SQL Server or MYSQL using some kind of factory method instead of using Static method like .UseSQLServer or .UseMySQL

**Comment by kjbetz** [comment]
I'm interested in the answer to your question as well. As I've had a very similiar scenario.

One way to go about it though would be to have Mac developers run MS SQL Server for Linux in Docker container... or it might even be able to run natively. That way everyone is using MS SQL Server.

**Comment by sam-wheat** [comment]
Will your you application target both MSSQL and MySQL? If so, you can use [AdaptiveClient](https://github.com/leaderanalytics/AdaptiveClient) and [AdaptiveClient.EntityFramework](https://github.com/leaderanalytics/AdaptiveClient.EntityFramework).  AdaptiveClient will help you target multiple database platforms using EntityFramework Core.  You can also easily expose services via REST, WCF, etc.

Please see the fully functional [Zamagon Demo](https://github.com/leaderanalytics/AdaptiveClient.EntityFramework.Zamagon) for a demonstration.

**Comment by kunalpgithub** [comment]
@sam-wheat  No, applicaiton does not target both MSSQL and MySQL. Just for development we want to use mySQL on some of machine and others are using SQL Server.

**Comment by ajcvickers** [comment]
@kunalpgithub This is not an approach I would recommend because SQL Server and MySQL do not always support the same set of features or exactly the same behavior. So, while you can develop an application that can use either type of database, this requires specifically designing for this and testing against both databases, and for any non-trivial application usually requires compromises and/or provider-specific code.

With regard to the question about factory methods, the answer is no because the provider integration is not designed like this for EF Core. Providers play a big part in the defining the actual API surface, and hence there needs to be an explicit reference to the provider code for this to work.

**Comment by kunalpgithub** [comment]
Thanks @ajcvickers .

Does that mean its not possible to achieve database persistence using EF core?

**Comment by ajcvickers** [comment]
@kunalpgithub Persistence, yes. :-) If you mean "persistence ignorance", then yes, but it requires developing and testing that way. It is not a goal of EF Core to make every database system behave exactly the same way as every other database system, but rather to provide common, useful abstractions where they make sense, while not hiding or compromising the unique features and behavior of each system that differentiate it and make one system better for one job, while another may be better for another job.
