### ISSUE TITLE
Lazy loading detached items when using reinitializing

### ISSUE THREAD

**Issue by johnybravo666** [dotnet/efcore#13264]
https://stackoverflow.com/questions/52236367/list-clear-vs-new-list-asp-net-core-entity-framework-core-lazy-loadi

**Comment by ajcvickers** [comment]
@johnybravo666 In this code:
```C#
FooParentEntity fooParentEntityDb = fooDbContext.FooParentEntities.ToList().FirstOrDefault();
fooParentEntityDb.FooChildEntities = new List<FooChildEntity>();
fooParentEntityDb.FooChildEntities.Add(new FooChildEntity { Name = "ThirdChild" });
```
The first line loads parent entities; child entities are not loaded. The second line sets child entities to a new empty list, but since the child entities are not loaded this is essentially a no-op. The third line then lazy-loads the child entities, since they have not been loaded, and then adds a new child entity to the list.

The reason it behaves differently in the debugger is because when the debugger accesses the FooChildEntities property is causes the property to be lazy-loaded.

**Comment by ajcvickers** [comment]
Question for triage: should setting the property to a new empty collection cause it to be marked as loaded and empty? (Note that this is difficult--it likely means that the setter will have to trigger lazy loading, because otherwise we would not know which entities to mark as deleted.)

**Comment by ajcvickers** [comment]
Triage: we will consider for 3.0 that if a proxy is tracked, then calling the setter should cause all entities to be loaded and then marked as deleted before setting the new empty collection.  We can do something similar for references.

**Comment by ajcvickers** [comment]
Notes from planning. We discussed this again with reference to #14086 and will likely not implement this because of the issues mentioned there. In addition, it's hard to know that setting an empty collection is really intended to do this, as opposed to just setting the collection so that things can be added, even if the setter is called after the entity is already tracked.
