### ISSUE TITLE
InMemoryDb Returns Local (cached) DbSet entity when Context is set to NoTracking

### ISSUE THREAD

**Issue by altmank** [dotnet/efcore#13319]
I'm trying to understand if there is an issue here or if my understanding of the intended behavior is incorrect.

I create an InMemoryDatabase DbContext with UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking).

I create an instance of my DbContext inside of the unit test, I then add an entity with some specific data and SaveChanges();

My unit test then calls a service and that service will create its own DbContext and perform data modification on the same entity created and saved to the InMemoryDatabase in the unit test.

Coming back to the unit test after the service logic, I use the same DbContext that originally created the entity to begin with an I perform a call to Find() on it to retrieve the entity that should now have modified data. What I get back is the same version of the entity that was originally created at the start of the unit test and not the version that was modified by the service.

If I make a new DbContext or explictly use AsNoTracking, then I get the correct modified entity.

I'm confused why I would be getting the cached entity in the DbSet.Local collection when my DbContext is explicitly configured with NoTracking behavior as part of initialization. 

Is this behavior correct or is something wrong here?

### Further technical details
EF Core version: 2.1.1.0
Database Provider: InMemoryDatabase 
Operating system: Windows 10
IDE: Visual Studio 2017 15.4

**Comment by ajcvickers** [comment]
@altmank Because the entity is being tracked by the call to `Add` or similar that you use to start tracking the entity. This is required since SaveChanges operates on tracked entities. It sounds like there are multiple units of work in this test. The best practice would be to use a new context instance for use of these.

**Comment by altmank** [comment]
@ajcvickers I'm not sure it makes sense still, if an entity starts being tracked by the usage of Add, why would my Find command bypass the Context behavior of NoTracking?

**Comment by altmank** [comment]
[Example.zip](https://github.com/aspnet/EntityFrameworkCore/files/2380097/Example.zip)

I've attached a sample project demonstrating this issue.

**Comment by ajcvickers** [comment]
@altmank Find is always a tracking call. The semantics of Find is to always return a tracked entity if possible without performing a query. If you want to force a query, no-tracking or otherwise, then use a query instead of using Find.

**Comment by altmank** [comment]
@ajcvickers Okay, that's good to know. Is there a document somewhere that details which calls override the context tracking behavior?

**Comment by ajcvickers** [comment]
@altmank The query-tracking behavior applies only to queries. It's not that it is overridden by anything, it's that it only applies to queries.

**Comment by altmank** [comment]
@ajcvickers I switched my test project to use a call to Single() instead of Find() and the behavior continues. Is Single() not a query?

[Example2UsingQuery.zip](https://github.com/aspnet/EntityFrameworkCore/files/2380117/Example2UsingQuery.zip)

**Comment by ajcvickers** [comment]
@altmank I ran your code and it shows an interesting behavior. The reason that you don't see the updated value is that it is never saved. The reason it is never saved is that, contrary to what I said above, the Find call is resulting in a no-tracking query when the entity is not already tracked. This is interesting and something we should discuss.

If I change the Find to a tracking query:
```C#
TestEntity entityToBeChanged = testContextThatChangesEntity.TestEntities.AsTracking().Single(e => e.Id == 1);
```
then it starts tracking the entity, and hence the change to the property is tracked and saved.

**Comment by altmank** [comment]
@ajcvickers Actually, I think that makes sense. If I have turned tracking off, I would not expect my field modification to be captured only by SaveChanges(). I would expect I would need to call DbContext.Update() on the modified entity first.

If you agree, then I think the only issue here was my lack of understanding that query tracking does not apply to Find()

**Comment by ajcvickers** [comment]
@altmank Except that is half does apply to find--this is what I want to discuss with the team.

**Comment by altmank** [comment]
Okay, sounds good.

**Comment by ajcvickers** [comment]
Triage: discussed at length the behavior of Find when query-tracking behavior is no-tracking at the context level. Options discussed were:
* All parts of Find are treated as no-tracking, including not returning a tracked entity if one exists.
* All parts of Find are treated as tracking
* Current behavior, where if an entity is tracked already, then it is returned, but otherwise the query is no-tracking.

There are scenarios where each of these can make sense, but looking at the combination of how context-level no-tracking is commonly used, it feels like the current behavior is good. That is, if I have in my current unit-of-work started tracking an entity in some way--for example, through Add--then it is likely that that instance should continue to be used within that unit-of-work.
