### ISSUE TITLE
Migrations are not database brand agnostics

### ISSUE THREAD

**Issue by ctrl-alt-d** [dotnet/efcore#13333]
[EF Core generated migration has database brand annotations.](https://stackoverflow.com/questions/52310236/ef-core-generated-migration-has-database-brand-annotations-looking-for-database) Digging into auto generated migrations files (`dotnet ef migrations add mymigration1`) I see references to specific database brand:

```c#
    Id = table.Column<int>(nullable: false)
        .Annotation("SqlServer:ValueGenerationStrategy", //<-- here
                     SqlServerValueGenerationStrategy.IdentityColumn), //<--here
```

I use EF2 core to be able to deploy and run application on several database brands, because this, I include in app references to several database providers:

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" ... />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" ... />
```

EF is able to generate specific sql for each database branch from the same linq expression, it is impressive. The only dependency to a database brand I have found in whole framework is in migrations.
In my opinion EF2 should be full agnostic about database brand on migrations files. Something like:

```c#
    Id = table.Column<int>(nullable: false, autofield: true ),
```

Is there a way to generate automatically migrations files, with all needed information (indent fields), and database brand agnostics?

### Steps to reproduce
Just make a migration and inspect files.

### Further technical details
EF Core version: 2.1.3
Database Provider: Sqlite, SqlServer, ...
Operating system: Any
IDE: Any

**Comment by ajcvickers** [comment]
@ctrl-alt-d Documentation for supporting multiple providers in Migrations is here: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers

We are not planning to implement full scafolding and management for migrations to multiple providers because the cost is very high while the value is relatively low compared to many other things. Also, sometimes multiple migration sets are appropriate, while sometimes a single migration is appropriate.
