### ISSUE TITLE
Support for mapping entity types to defining queries

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#13358]
In EF Core 2.1 we added [query types](https://docs.microsoft.com/ef/core/modeling/query-types), which can be mapped in the model to "defining query" specified using the ToQuery API. 

Such defining query is generally a LINQ query that becomes the source of data for read operations for the query type.  

This issue is about adding the ToQuery API and the ability to map regular entity types to defining queries as well. 

We need to consider that query types are read-only and so they don't need to be mapped to a table or underlying collection for the purpose of CUD operations.

Since entity types are not read-only, defining query mapping for entity types would work best in combination with custom CUD mapping, e.g. stored procedure mapping.

**Comment by ajcvickers** [comment]
See also the discussion in #15239

**Comment by divega** [comment]
Reactivating and marking as punted for 3.0 since we are disabling this again as per https://github.com/aspnet/EntityFrameworkCore/issues/17157.

**Comment by divega** [comment]
Issue #17158 contains some new data what we need to take into account when we implement this.

**Comment by smitpatel** [comment]
@AndriySvyryd - I believe this is going to work in 5.0. How do you want to track it?

**Comment by AndriySvyryd** [comment]
Related to https://github.com/dotnet/efcore/issues/17063

**Comment by AndriySvyryd** [comment]
Note to implementor: use `IRawSqlResult` to store the mapping in the relational model. Also add overload for it and `IStoreFunction` to `IRelationalAnnotationProvider`

**Comment by smitpatel** [comment]
We allow mapping entity type to TVF/View/Table. When generating projection in the query, we create appropriate table source and use relevant mappings.
For non-query root translation like TVF, we are going to use function mapping (since we have mapped store function info too).

For ad-hoc translation like FromSql, we don't have anything in model to get mappings. Additionally we are going to add ToSqlQuery which will make SQL a mix of both words (in/out of the model). Further FromSql can use any number of parameters which can change ad-hoc.
Currently for FromSql we use the column names from view if available or from Table. We can use mapping from IRawSqlResult once implemented.

For any other ad-hoc translation which are none of the above, we could also have default mappings.

**Comment by AndriySvyryd** [comment]
`IRawSqlResult` would also have parameter mapping and have a unique name to allow multiple `FromSql` shapes for the same entity type.
