### ISSUE TITLE
InMemory DbContext does not respect CancellationToken on SaveChangesAsync

### ISSUE THREAD

**Issue by MatthewLymer** [dotnet/efcore#13368]
When using an InMemory DbContext, the `SaveChangesAsync` does not respect the cancellation token being passed in.

### Steps to reproduce
1. Create a DbContext called TenantDbContext
1. Create a type called `Setting`, expose a `DbSet<Settings>`
1. Run the following unit test:

```c#
	[Fact]
	public async Task ShouldPersistResultIfScrapeTimesOut()
	{
		var options = new DbContextOptionsBuilder<TenantDbContext>()
			.UseInMemoryDatabase(Guid.NewGuid().ToString())
			.Options;

		using (var dbContext = new TenantDbContext(options))
		{
			var setting = new Setting
			{
				Name = "Foo", 
				Value = "Bar"
			};
			
			dbContext.Settings.Add(setting);
			
			await Assert.ThrowsAnyAsync<OperationCanceledException>(
				() => dbContext.SaveChangesAsync(new CancellationToken(true)));
		}

		using (var dbContext = new TenantDbContext(options))
		{
			var settings = await dbContext.Settings.ToListAsync(
				CancellationToken.None);
			
			Assert.Empty(settings);
		}
	}
```

### Further technical details
EF Core version
* Microsoft.EntityFrameworkCore.Design v2.1.0
* Microsoft.EntityFrameworkCore.InMemory v2.1.1

Database Provider
* Microsoft.EntityFrameworkCore.InMemory

Operating system
* Windows 10

IDE
* Visual Studio 2017 15.8.0

**Comment by pmiddleton** [comment]
@MatthewLymer 

The InMemory provider does not make any async calls and therefore does not use the cancellationToken.  Internally it it just performs a Task.FromResult inside of SaveChangesAsync

**Comment by MatthewLymer** [comment]
I assumed as much, however I assume the entire purpose of the InMemory database is to facilitate testing, so I think having behavior closely match other providers would be desirable.

**Comment by hannahchan** [comment]
So it's been a number of years since this was reported and I thought I should mention that I've just run into the same issue. I'm trying to unit test my repository class for cooperative cancellation by making sure it's passing through the CancellationToken.

**Comment by smitpatel** [comment]
See #18457

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.

**Comment by slaneyrw** [comment]
@ajcvickers 

Just like to add that you cannot just replace the InMemory database with SQLite as a testing replacement for a SQL Server based context.  Whilst new features are available ( Tx ), some are removed... like Concurrency ( timestamp/rowversion ) support.  The suggested "solution" involves modifying the real code under test if running SQLite - not an acceptable approach IMHO.   If the InMemory is removed, EF based solution may become untestable in some circumstances.

Please respect the cancellationToken in the InMemory provider... it's a real simple check.  It avoids us from having to insert "ThrowIfCancellationRequested()" everywhere our code because we want to test exception handling.

The debate about a suitable test DB engine replacement for Unit tests is not a simple one, but all DB providers MUST respect cancellation tokens in all async methods.
