### ISSUE TITLE
IQueryable.Select ignores value literal in selector for valuetype

### ISSUE THREAD

**Issue by ackava** [dotnet/efcore#13402]
I am using release 2.1

Here is the entity

```c#
public class Product {
     public string Name { get; set; }
     public bool Archived { get; set; }
}
```

Query
```c#

   db.Products.Where( .... ).Select( x => new Product {
        Archived = false,
        Name = x.Name
   } );

   SELECT [x].[Name] FROM [Products] as [x]

```

Generated sql does not contain "Archived" column.

```c#
   bool archived = false;
   db.Products.Where( .... ).Select( x => new Product {
        Archived = archived,
        Name = x.Name
   } );

   SELECT @p0 as [Archived], [x].[Name] FROM [Products] as [x]
```
Now generated sql does contain "Archived" which is bound to a parameter.

This is important as I am using generated SQL as sub query to a bulk insert and update procedure.

I found this accidentally, work around for passing parameter for every default type is difficult.

**Comment by ajcvickers** [comment]
@ackava Curious: in your first example, as you saying that you expect Product.Archived to be queried even when it isn't referenced anywhere?

**Comment by smitpatel** [comment]
@ackava - In top level projection if you are using a constant then we don't put it in generated SQL. This is by design. Since the constant value is known we can always plug it in client side when generating the results.  (For nested projection we always send constant to server so that we can lift the subquery). This is specifically helpful by avoiding sending large constant to the server when we get the same value back. In case of parameter it is added to SQL so that we can use caching of parameters without recompiling the query.

Using SQL generated by EF in bulk insert/update is not the intended use for query compiler as it can also cause multiple queries in certain cases. If it works for you then you can surely use it but if the SQL is not what you are expecting then feel free to modify it.

**Comment by ajcvickers** [comment]
@ackava It is a goal of EF Core to produce simple, readable queries. It's not currently a goal to produce queries that can then act as an input to something else. With regard to bulk updates, that's an important feature, but as with all teams we have limited resources and many important things to work on.
