### ISSUE TITLE
Base exception and enum for database-transaction errors

### ISSUE THREAD

**Issue by DeuxAlpha** [dotnet/efcore#13425]
Good morning!

I was looking for a place to submit suggestions [over here](https://data.uservoice.com/forums/72025--closed-entity-framework-core-feature-suggestions) and was directed to post them here so if this isn't the place to do so I apologize.

My suggestion is rather simple, but I believe it could be quite beneficial in streamlining error responses from various implementations of EFCore. I have used a [MySQL](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) and [PostgreSql](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL) implementation of EFCore and each time, I had to dig into the exceptions and messages to filter for why an error occurred when writing to the database (i.e. foreign key missing, unique ID restraint, etc.). If EFCore would provide a base exception, along with an enum that specifies those possible scenarios, it would be a lot easier to filter and give accurate responses to the developers without the need to dive deep into the exceptions themselves.

All you'd be required to do is check for that BaseException, check the enum value, and return a simple error message based on that to the user.

All of this, without needing different implementations based on what database provider you use (the libraries you'd use would throw those specific exceptions in their code).

Thanks for your consideration, and please let me know if you have further questions or concerns!

Regards

**Comment by ajcvickers** [comment]
@DeuxAlpha We have discussed this many times in the past, but we haven't done anything because:
1. There is no common way to get this information from the database exception. This means that we would have to create a mechanism for providers to give EF that information in an abstract way that EF can consume. This is doable, but it isn't a trivial amount of work.
2. These errors typically indicate an error in the application. In other words, it's not good practice to let the database throw and then attempt to use that information to impact the flow control in code. Instead, if one of these errors is thrown it typically means application code is violating some invariant, and the error needs to be understood by a developer to fix the bug. For this case, the database error is the source of truth and an EF abstraction over it doesn't help that much.
