### ISSUE TITLE
Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project.

### ISSUE THREAD

**Issue by blackn1ght** [dotnet/efcore#13436]
I'm attempting to create a DbContext from an existing SqlServer database via the `Scaffold-DbContext` command.  When passing the command, with the `Microsoft.EntityFrameworkCore.SqlServer`, I get the error message: "Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project."

Command:
`Scaffold-DbContext "Server=(devsql-uk02);Database=Phenix;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Phenix\Models -Tables Place`

```
Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project.
```

I'm running the command on the `CaliberDestinationsImporter.Data` project, where `Microsoft.EntityFrameworkCore.SqlServer 2.1.3` is installed.

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

[Sample Repository](https://github.com/blackn1ght/CaliberDestinationsImporter)

### Further technical details
Dotnet Core version: 2.1
EF Core version: 2.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Microsoft Windows 10 (Version 1803, OS Build 17134.165)
IDE: Visual Studio 2017 15.5.2

**Comment by mickm77** [comment]
> It's a PEBCAK issue. I hadn't installed the `Microsoft.EntityFrameworkCore` package, but had instead directly installed the `Microsoft.EntityFrameworkCore.SqlServer` package.

Also, after installing packages, don't forget to build before trying to scaffold again.

**Comment by tombohub** [comment]
> It's a PEBCAK issue. I hadn't installed the `Microsoft.EntityFrameworkCore` package, but had instead directly installed the `Microsoft.EntityFrameworkCore.SqlServer` package.

@blackn1ght what does that mean? How did you solve it? I have both of those packages and it doesn't work

**Comment by enderandpeter** [comment]
@tombohub I believe I just experienced this issue, but with `Microsoft.EntityFrameworkCore.Sqlite`. 

I was trying to setup [this project](https://github.com/markjprice/cs10dotnet6/blob/main/vscode/PracticalApps/Northwind.Common.EntityModels.Sqlite/Northwind.Common.EntityModels.Sqlite.csproj) from an excellent tutorial book. As you see, the expectation is that you only need the following:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.11" />
  </ItemGroup>
```

However, as as I ran the command 
```
dotnet ef dbcontext scaffold "Filename=../Northwind.db" Microsoft.EntityFrameworkCore.Sqlite --namespace Packt.Shared --data-annotations
```
I kept getting the error: `Unable to find provider assembly 'Microsoft.EntityFrameworkCore.Sqlite'. Ensure the name is correct and it's referenced by the project.`

Even though I installed `Microsoft.EntityFrameworkCore.Sqlite` and `Microsoft.EntityFrameworkCore.Design` as NuGet packages from Visual Studio for Mac, I was getting this error.

Resolving it required installing just `Microsoft.EntityFrameworkCore` as a NuGet package. Things may have changed over time, because this was not the author's experience. I'm sure there's more going on here...

**Comment by CoZyMiKe77** [comment]
I have all the packages, rebuilt and still have the same error
I don't know what else do. Someone please help. I'm using visual studio 2022 version

***Unable to find provider assembly '0 Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Tables nd_users,v_BillPrintAll -DataAnnotations -force**

**Comment by roji** [comment]
@CoZyMiKe77 @enderandpeter there's generally not much we can to to help with just an error message. Verify that you're referencing the correct nuget packages (and versions), and if things still aren't working, try creating a minimal project that reproduces the error. That process should help you find the problem in your real project; and if not, you'll have a minimal project that you can point us to for investigation; at that point we can help more.

**Comment by enderandpeter** [comment]
Yes I do hear you. Fortunately, the resolution in my case was exactly [what the OP reported](https://github.com/dotnet/efcore/issues/13436#issuecomment-425361047) in that I needed the parent `Microsoft.EntityFrameworkCore` package in addition to `Microsoft.EntityFrameworkCore.SqlServer`. You will find [a link to the project](https://github.com/markjprice/cs10dotnet6/blob/main/vscode/PracticalApps/Northwind.Common.EntityModels.Sqlite/Northwind.Common.EntityModels.Sqlite.csproj) in my comment, which is actually a tutorial project. Since the tutorial author did not mention needing that parent package, I suspected something was off, but nevertheless I am happy to say it has been working. It sounds like some are reporting they definitely have both packages yet there are still issues, and yes I agree more details would help.
