### ISSUE TITLE
Question: Translation of MemberExpression

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#13527]
Could anybody explain me the next code from SqlServerStringLengthTranslator:

https://github.com/aspnet/EntityFrameworkCore/blob/92b902d81c56ad2235c70a5d92f2d7523c4e01a3/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringLengthTranslator.cs#L20-L23

1. When "memberExpression.Expression" may be null?

2. Why it checkes a "memberExpression.Expression.Type", but not "memberExpression.Member.DeclaringType"?

Thanks.

**Comment by smitpatel** [comment]
1. MemberExpression.Expression is null for static members. The Expression property is instance on which member is called.
2. It checks for inner Expression's type to be string rather than declaring type because it would have been translated before coming to this code path. If for some reason the SqlExpression on server is not of type string, we don't want to apply the code (when value converter is in effect probably).
