### ISSUE TITLE
Question: How to check for unsuccessful migration

### ISSUE THREAD

**Issue by lkts** [dotnet/efcore#13820]
Hi.

I am using `IMigrator` to execute migrations in my app and I want to ensure successful migration process before application start. However from https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.imigrator.migrateasync?view=efcore-2.1 it is not clear if `Migrate` methods throw exceptions which i can check. How can i achieve this?

Thanks.

EF Core version: 2.1.2

**Comment by ajcvickers** [comment]
@lkts If you mean are there specific exception types that indicate specific types of failures, then no, not currently. While there are specific cases where this might be helpful, we have generally found this not to be the case since it is very unlikely that an exception being thrown can be recovered from without fixing the issue and restarting the process, at which point all exceptions can be treated the same.
