### ISSUE TITLE
EF Core 2.1 can't cast datetime to string

### ISSUE THREAD

**Issue by aoiste** [dotnet/efcore#13909]
This code works fine with .net core 2.0, but got error under .net core 2.1.

The error says: approveTime expect stirng, but got Datetime

```c#
        private DateTime _approveTime;
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string approveTime
        {
            get
            {
                if (_approveTime.ToString("yyyy-MM-dd HH:mm:ss") == "0001-01-01 00:00:00")
                {
                    return "";
                }
                return _approveTime.ToString("yyyy-MM-dd HH:mm:ss");
            }
            set
            {
                _approveTime = DateTime.Parse(value);
            }
        }
```

### Further technical details
EF Core version: 2.1.4
Database Provider: MySql.Data.EntityFrameworkCore
Operating system: Windows 10
IDE: Visual Studio 2017 15.9 Preview 5.0

**Comment by kevindqc** [comment]
Just some ideas:

Is the `approveTime` column in your table a datetime? If so, I think your c# property `approveTime` should also be a `DateTime` instead of a `string`?

Shouldn't the formatting be done somewhere else (ie: the UI)? Also it seems like your date can be empty -
maybe you could use `DateTime?` instead, to get rid of the check on `"0001-01-01 00:00:00"` (which should probably have been a check on `DateTime.MinValue` instead, ie: `if (_approveTime == DateTime.MinValue)`)?

Why are you using `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]`? It means that your approveTime will not be sent to the database when inserting/updating data, but it will get fetched for queries. Is that the intent? Or you added that to go with your custom get/set? Ideally your entities should have the normal auto -implemented getters and setters (ie: `public DateTime approveTime { get; set; }`)

**Comment by ajcvickers** [comment]
@ztytotoro I'm surprised this worked in 2.0--it's hard to see how it would have. Is the column type a string or a datetime? What is the SQL for the computed column?

It's not clear this is what you want, but if the idea is to have a computed datetime column in the database but map it to a string in the model, then consider using a ValueConverter, and consider making   it read-only. For example:
```C#
modelBuilder
    .Entity<Blog>()
    .Property(e => e.approveTime)
    .HasComputedColumnSql("getdate()")
    .HasConversion(
        v => DateTime.Parse(v),
        v => v.ToString("yyyy-MM-dd HH:mm:ss"));
```

If this doesn't help, then please provide a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ztytotoro** [comment]
@kevindqc I used `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]` because the `approveTime` is generated by MySQL default value `CURRENT_TIMESTAMP`. I made this conversion just want to simplify front-end works because I also write a lot JavaScript code and need to make many conversions for display.

**Comment by ztytotoro** [comment]
@ajcvickers I tried this before but I gave `approveTime` a `DateTime` type and caused an error. Now it works, thanks a lot. Just a pity that I cannot process these conversions separately now.
