### ISSUE TITLE
Entity is deleted when Navigation property of the entity is set to null.

### ISSUE THREAD

**Issue by motz-art** [dotnet/efcore#13913]
`SaveChanges` for updated Entity with navigation property is reset to `null` results in `Delete` SQL statement for the entity.

### Steps to reproduce
```c#
                var post = ctx.Posts.Find(id);
                ctx.Entry(post).Reference(x => x.Blog).Load();

                post.Blog = null;
                post.Title = "New title.";

                ctx.SaveChanges(); // results in DELETE FROM [Blogs] WHERE [ID] = @p0;
```

Full source can be found here: https://github.com/motz-art/EFCore-Update-To-Delete-Bug.git

I understand that this happened because of Cascade behavior, but on the other hand I'm updating the entity I do not expect this to result on delete of any sort.

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer Version: 2.1.4
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.9

**Comment by ajcvickers** [comment]
@motz-art What do you expect to happen instead?

**Comment by motz-art** [comment]
In best case:
I would expect it just to ignore `null` assignment as `BlogId` still has it's value and just update `Title` of the `Post`. As well as, in case if `Blog` would be set to `null` and `BlogId` would be set to another value, I would expect EF to just update the foreign key.

In worse case:
I would expect exception from `SaveChanges` like it's when delete behavior set to `Restricted`.

In our project we are using unit of work, and load of parent entity happened conditionally at the beginning of request processing. Then later when child entity update is started another call to the `Find` method (this time without `Entry().Reference(x => x...).Load()`) returned cached entity with parent loaded.   Then `AutoMapper` reset parent navigation property to `null`. That result in a `DELETE` request to the child.

**Comment by motz-art** [comment]
After a bit of thinking, I see having both `BlobId` and `Blob` properties as a source of unexpected behavior. Consider next case:

``` c#
post.BlogId = request.NewBlogId;
post.Blog = null;
ctx.SaveChanges();
```
outcome varies on:
1. whether `Blog` was loaded before or not;
2. `NewBlogId` matches current value `BlogId` or differs;
3. whether `BlogId` is nullable or not (if `NewBlogId` matches current value of `BlogId`);
4. whether `OnDelete` behavior is `Cascading` or `Restricted`.

Ideally I would like to have possibility to say which property is the source of truth. 

If `BlogId` is the master, then changing `Blog` to `null` should not meter. Changing `Blog` to other value should have corresponding change of `BlogId` with value that matches `Blog.Id`, otherwise exception.
To allow `Blog` inserting during `Post` save, `BlogId` should be set to 0 (even when `BlogId` is nullable) and `Blog` to detached instance with `Id == 0`.

If none is the master, then updating based on what has changed. If both has changed and `Blog != null && Blog.Id != BlogId` - then exception.

I don't see the point in possibility to set `Blog` as the master.

**Comment by ajcvickers** [comment]
@motz-art Those are some interesting thoughts, but we try to keep the rules quite a lot simpler than that. Given that the FK and the navigation properties all represent the same thing, we try to reflect a change made to either of the navigation properties or the FK such that the others stay in sync. For example, setting the navigation property to null is the same as setting the FK to null. You should be able to also or instead set the FK property to a new value and that value will be respected and saved.

The only place this really runs into issues is if the FK has been set to null, either directly or through changing one of the navigation properties and that FK remains set this way even though the FK is not nullable in the database. This means that the entities cannot be saved as is. If the relationship is setup to cascade delete, then this case triggers the cascade delete as part of saving--which is what you are seeing. If not, then the save will throw because it's not possible to save the null FK value to the database.
