### ISSUE TITLE
SqlDataAdapter is missing from NetStandard System.Data.SqlClient

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/efcore#13929]
I'm attempting to build an utility library using NetStandard and I have installed System.Data.Common and System.Data.SqlClient. When I attempt to use a SqlDataAdapter I get the error "The type or namespace name "SqlDataAdapter" could not be found.

What am I supposed to do to resolve?

**Comment by divega** [comment]
@EdLichtman can you please report this issue at https://github.com/dotnet/corefx/issues/new. That is were issues for the System.Data.SqlClient packages are tracked. 

Also, I haven't tried that @dallancarr suggest but it seems worth trying. Even if it turns out the Microsoft.Windows.Compatibility pack helps, I am not sure that should be necessary, so it seems to be this is a valid issue.

**Comment by dallancarr** [comment]
Example here using netcoreapp.2.0 using preview version of the SqlClient library.

https://github.com/jhealy/aspdotnetcore/blob/master/SqlClientPlay20/SqlClientPlay20/SqlClientPlay20.csproj

**Comment by divega** [comment]
Keeping the issue open until next triage to make sure someone reports it to corefx.
