### ISSUE TITLE
Question related to object states

### ISSUE THREAD

**Issue by armanpetrosyan23** [dotnet/efcore#13936]
1. I would like to change only Pilot entity but all entities change  their state from Unchanged to Modified

Here is my source code.
![capture-code](https://user-images.githubusercontent.com/35919382/48351413-a1002880-e6a3-11e8-80ac-79e789f5d501.PNG)

Here is my result.
![capture](https://user-images.githubusercontent.com/35919382/48351469-cab94f80-e6a3-11e8-8d59-5701a3bb891d.PNG)

2. When I use  EntityEntry for flight entity ( var entry = ctx.Entry(flight);  ) after modification Pilot navigation property result for "entry" and its properties remain  Unchanged. But when calling "entry = ctx.Entry(flight);" again its state is Modified.
Here is my changed source code.

![capture-1](https://user-images.githubusercontent.com/35919382/48351936-f557d800-e6a4-11e8-9b66-4345fe2f6cc9.PNG)

Here is my result

![result](https://user-images.githubusercontent.com/35919382/48352078-4f589d80-e6a5-11e8-845c-526d31ccc6ab.PNG)

Please could you explain the reasons?

**Comment by ajcvickers** [comment]
@armanpetrosyan23 For 1, you're printing out the same entity state for each property. The entity is modified because the FK property has changed.

For 2, the context needs to detect that the Pilot navigation property has changed because the state change will be reflected. Calling `Entry` or `Entries` causes `DetectChanges` to happen automatically, but just looking at the State property of an existing entry does not.
