### ISSUE TITLE
Suggestion: Generate typed Find methods for type safe access using PKs

### ISSUE THREAD

**Issue by Liero** [dotnet/efcore#14049]
Currently  `DBSet<T>` class has `T Find(params object[] keyValues)` method.

Using Database First approach, I would welcome autogenerated methods like:

```csharp
Product Find(this DbSet<Product> dbSet, Guid productId);
ProductCategory Find(this DbSet<ProductCategory> dbSet, Guid productId, Guid categoryId);
```

My motivation is not only type safety, but in case of composite primary keys also **order of the key values**, which can become quite tricky to debug. These errors could be easily avoided using named arguments:

```csharp
db.ProductCategories.Find(
   productId: queryData.ProductId, 
   categoryId: queryData.CategoryId)
```

**Comment by ajcvickers** [comment]
@Liero Thanks for the suggestion. These overloads will likely not help greatly in practice because if somebody does try to use the wrong key type, then the object overload will be chosen by the compiler anyway and so effectively it just behaves the same as now.

Beyond this, even if there is value due to documenting code, etc., it's not something we plan to add by default, but #4038 should allow the reverse engineering process to be extended so that it could generate methods like this.

**Comment by Liero** [comment]
Yeah, the generated methods should not be overloads, but have different name instead. If #4038 allowed this, I would be perfectly happy with it. Thanks
