### ISSUE TITLE
Inheritance creating child tables

### ISSUE THREAD

**Issue by longinos10** [dotnet/efcore#14102]
```C#    
       public class Product
    {
        public string Name { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }

    }
    public class CartItem : Product
    {
        public int CartItemId { get; set; }

        public string CartId { get; set; }
    }
    public class OrderLine : Product
    {
        public int OrderLineId { get; set; }

        public int OrderId { get; set; }
    }

    public class Kititem : Product
    {
        public int KititemId { get; set; }

        public int OrderId { get; set; }
    }

    public class SampleContext : DbContext
    {
        public DbSet<CartItem> CartItems { get; set; }
        public DbSet<OrderLine> OrderLines { get; set; }
        public DbSet<Kititem> Kititems { get; set; }
    }
```

As you can see in this I am not including the parent class Product in the DbContext, and when doing the migrations it creates a table for each derived class with all the properties form the parent class, and it does not create the parent class because is not included in the Dbcontext, for me it was what I was exptecting and is working, and I am happy with it so far
Mi question is if that is a bad practice and maybe I am not using ef core Inheritance the way I can take all the advantages ?
I am confuse and want to start a new project and do it the best way, so I don't have to redo it again

And last thing, I don't know if to put this here because is not en issue is more of a question,  should I put it in stackoverflow instead ?

**Comment by ajcvickers** [comment]
@longinos10 There are advantages and disadvantages of mapping the base type explicitly into the model. Typically, it needs to be in the model if:
* There is a need to query for all entities that extend the base type; that is you want use the base type directly in queries
* Other parts of the model reference the base type directly, as opposed to only referencing the derived types.

If you don't need these things, then it usually makes sense to leave the base type not mapped (as in your example above) because it allows greater flexibility in the database layout. Once you map the base type, then everything will collapse down into one TPH table.
