### ISSUE TITLE
Include in EF Core 2.0 create infinite nested child Entities using One-to-One relationships

### ISSUE THREAD

**Issue by juanjinario** [dotnet/efcore#14141]
### Describe what is not working as expected.
When I use Include method in a entity that have a One-to-one relationship with another one, I get a infinite nested structure.

### Steps to reproduce
I Create two models with a optional One-to-One relationship, generate data and when I want to get the Parent model with the Child data using the INCLUDE method I have a infinite nested structure.

```
Parent 
           id
           name
          -> Child 
                          id
                          name
                         -> Parent
                                          id
                                          name 
                                          -> Child...
```

```c#

public class Asset
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public TrackingDevice TrackingDevice { get; set; }
    }

public class TrackingDevice
    {
        public int Id { get; set; }
        public string Imei { get; set; }
        public int? AssetId { get; set; }
        public Asset Asset { get; set; }
    }

var Devices = _appContext.TrackingDevices
         .Include(td => td.Asset)
         .ToListAsync();
```

If I erase the Include, the List works without Asset information, I think that is not work correctly.
When apply AutoMapper for this structure the system collapse.

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/querying/related-data#eager-loading 
Including the tip box below the sample

**Comment by juanjinario** [comment]
@smitpatel I need more information, I cant understand which **tip box**, I am using Eager-loading when using INCLUDE (I think so), but I dont know for what reason my code generate a infinite nested structure.

I can solve the problem with a quick implementation: 
```
return await _appContext.TrackingDevices
                .Select(t => new TrackingDevice
                {
                    Asset = t.Asset,
                    AssetId = t.AssetId,
                    Id = t.Id,
                    Imei = t.Imei
                })
                .OrderBy(t => t.Imei)
                .ToListAsync();
```

But I want use INCLUDE and understad if is normal this behavior.

**Comment by smitpatel** [comment]
![image](https://user-images.githubusercontent.com/1528107/49960176-7b458980-fec4-11e8-9e86-e5d9414d0453.png)

**Comment by smitpatel** [comment]
It is just fix-up connecting all the navigations between all the loaded entities. So you can get deep level nesting based on the data. Though, EF Core is not pulling any additional data from server in the process. It is just connecting them on client. It is by-design behavior because people want fix up to happen. So I am unable to see what is exact issue here.

If nested structure is an issue, especially with serializing the results, then you need to configure your serializer to ignore loops. Or perhaps, AsNoTracking query could also help.

**Comment by ajcvickers** [comment]
@juanjinario Lots of people use AutoMapper with EF Core without any issues. I would suggest you formulate a well-structured question, including code, and ask a question on Stack Overflow.

**Comment by MasoudShah** [comment]
I have this problem too. I have two models: category and product. When I want to load a specific category details, I want to load its products as a list too, so I include the products in my query. the category field in product model is virtual, so it's lazy loading, and I expect that if I don't include category in product, it would be null; but since I load products of an already loaded category, the category reference in product list is loaded too. Then it throws a cyclic exception for serialization. How can I avoid it in the right way?

**Comment by AndriySvyryd** [comment]
@MasoudShah https://github.com/dotnet/efcore/issues/11564 will address this
