### ISSUE TITLE
Have a model building "mode" where everything must be explicitly specified

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#1414]
This item relates to #908 in which we decided to remove the BasicModelBuilder and instead use the convention ModelBuilder with no conventions for explicitly building the entire model. After further discussion whether this will work how people want depends on what are considered "conventions". Take the FK example. Removing conventions means that an FK property will not be discovered by convention, but we have no way of knowing what the FK will be until it is specified. If it isn't, then the shadow state FK will remain in the model--which could be seen as introducing a shadow state FK by convention.

If the goal is to ensure the entire model is explicitly specified then we could do this by having a mode in which model validation will check if anything in the model was not specified explicitly. If anything is found then model validation will fail. This has the additional advantage the conventions don't need to be removed to use this mode, although removing conventions would still be possible and could be useful for things like removing reachability.

**Comment by breyed** [comment]
Comparing the suggestion in this issue with that item #7561, it's worth clarifying that there are at least three levels of explicitness:

1. **Implicit columns**: Assumed presence of columns in the database even without matching properties in the POCOs. POCO property relationships assumed by convention.
2. **Explicit columns**: Database columns only correspond to POCO properties. POCO property relationships assumed by convention.
3. **Explicit model**: Database columns only correspond to POCO properties. POCO property relationships must be specified explicitly (e.g. `CustomerId` is only the key for `Customer` if a configuration says so).

This item is advocating for option 3 (assuming I understand it correctly). Item #7561 advocates for option 2. All three options are useful. I think 3 is often overkill. I'm not sure how often people would want to do that much configuration, and if they did and forgot to configure a relationship, debugging the omission might still be difficult. I like option 2 because debugging columns that don't exist was so tricky. Option 1 is great for really lean POCOs, although I wonder if it is too automagical for a default.

**Comment by ajcvickers** [comment]
Closing as we haven't seen significant demand for this feature. We could revisit this decision based on feedback and we would also consider a well-written community PR for it.

**Comment by AndriySvyryd** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/214 will allow to remove all non-essential conventions
