### ISSUE TITLE
Don't check for temporary values on non-key properties when deleting an entity

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#14192]
See https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/518#issuecomment-447643646

**Comment by NinoFloris** [comment]
@ajcvickers why did this get pushed into backlog? Postgresql seeding with xmin still doesn't work after 2 years of seeding being introduced. There is a tail of issues slowly fixing parts of the problem, this being the last piece. I'd really appreciate it if 3.0 or a 3.0 patch would finally fix this.

**Comment by ajcvickers** [comment]
@AndriySvyryd @roji Thoughts?

**Comment by roji** [comment]
@NinoFloris this issue isn't actually necessary in order to seed entities that has xmin. The root issue was https://github.com/aspnet/EntityFrameworkCore/issues/14161 which was fixed in EF Core 2.2.2 - this issue was opened as part of a proposed workaround for that, which is no longer necessary to use xmin (but is important for other scenarios).
