### ISSUE TITLE
Modifying an alternate key in a "disconnected" scenario appears to save successfully but actually doesn't

### ISSUE THREAD

**Issue by deslee** [dotnet/efcore#14210]
I spent a few hours debugging an issue where I could not seem to get the ORM to update a `Title` field of my model.

I had an alternate key on the `Title` field because I intended for it to be unique. I know now that alternate keys are not ever supposed to be updated, however the application made it seem like it was successfully updated before I fetched the entity again.

I have a sample project with a single entity. When I try to update a detatched entity's alternate key field and call `update`, it successfully updates and does not throw an error.

However, when I fetch this entity again, the alternate key is back to its original value. 

Here is some code:

```c#
class Program
    {
        public class Blog
        {
            public string Id { get; set; }
            public string Title { get; set; }

        }
        public class BloggingContext : DbContext
        {
            public DbSet<Blog> Blogs { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlite("Data Source=blogging.db");
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Blog>().HasAlternateKey(b => b.Title);
            }
        }

        static void Main(string[] args)
        {
            string blogId = null;

            using (var db = new BloggingContext()) {
                db.Database.EnsureCreated();
                var blog = new Blog {
                    Title = Guid.NewGuid().ToString()
                };
                db.Add(blog);
                db.SaveChanges();
                blogId = blog.Id;
                Console.WriteLine($"Printing blog title for the first time: {blog.Title}");
            }

            using (var db = new BloggingContext()) {
                var blog = new Blog {
                    Id = blogId,
                    Title = Guid.NewGuid().ToString()
                };
                db.Update(blog);
                db.SaveChanges();
                Console.WriteLine($"Printing blog title for the second time: {blog.Title}");
                Console.WriteLine($"Printing original values: {db.Entry(blog).OriginalValues["Title"]}");
            }
            
            using (var db = new BloggingContext()) {
                var blog = db.Blogs.FirstOrDefault(b => b.Id == blogId);
                Console.WriteLine($"Printing blog title for the third time: {blog.Title}");
            }
        }
    }
```

Here's the output:

```
Printing blog title for the first time: 7f4ab263-b9d6-4469-acf5-ddf4df2e7703
Printing blog title for the second time: c1156031-4ea9-47ae-bb17-2371e9a67261
Printing original values: c1156031-4ea9-47ae-bb17-2371e9a67261
Printing blog title for the third time: 7f4ab263-b9d6-4469-acf5-ddf4df2e7703
```

On the other hand, if I try to do the same thing with an "attached" entity, I get an error:

```c#
using (var db = new BloggingContext()) {
                db.Database.EnsureCreated();
                var blog = new Blog {
                    Title = Guid.NewGuid().ToString()
                };
                db.Add(blog);
                db.SaveChanges();
                blog.Title = Guid.NewGuid().ToString();
                db.Update(blog);
                db.SaveChanges();
            }
```

```
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll: 'The property 'Title' on entity type 'Blog' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key first delete the dependent and invoke 'SaveChanges' then associate the dependent with the new principal.'
```

I think the [docs](https://docs.microsoft.com/en-us/ef/core/modeling/relational/unique-constraints) should make it clear that Alternate Keys can not be updated, and the DbContext should throw an exception if it happens.

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 2.2.0
Operating system: Windows 10
IDE: Visual Studio Code (using dotnet)

**Comment by ajcvickers** [comment]
@deslee Thanks for reporting this; it's certainly an interesting case where I agree the behavior is not desirable. 

Note: I haven't run the code, but I'm assuming that what happens is the alternate key doesn't get marked as modified because we treat alternate and primary keys in the same way. But this means it is just ignored by the update pipeline. Treating it as a concurrency token would avoid this, but I'm not sure we want to force that since all updates will pay the cost for the check even if it's not needed because the alternate key value does never change.

Leaving un-triaged to discuss with @divega.

**Comment by ajcvickers** [comment]
We discussed this at length in triage. Notes:
* Allowing mutation of alternate keys is covered by #4073
* Attempting to modify an alternate key property on a tracked entity will throw, so this issue is about the specific case that it is modified before being attached.

Things we considered:
* Treating the alternate key property as a concurrency token. However, this incurs overhead that should not be needed except in corner cases like this. However, this would need to be removed again once #4073 is implemented.
  * Manually configuring an alternate key property as a concurrency token could be done in applications that need protection against this specific case.
* Allowing the key property to be marked as modified and then either writing it or using the modified flag to trigger something else. But this is part way to implementation of #4073 anyway.

Conclusion: we should implement #4073, at which point this case will be covered. So closing this as a duplicate.

**Comment by Jeffery-Glenn** [comment]
Just from my own experience I've often modified an alternate and sometimes the key itself in natural key systems.  Natural key systems rely on the cascade logic to move the dependent tables into sync.  There is a large debate out there about natural vs surrogate key systems and without wading into that I can certainly say that both sides admit that there are always cases in both camps.  As someone who has code that uses natural keys with cascades in regular ADO.Net to not allow me to change the key prevents a key use case (updating the key); this forces me into a delete followed by insert model that is very much complicated with dependent entities.

I know the EF core group is doing great work so if there is any way this can be supported at some point it would be huge win for people with databases that work with natural keys.
