### ISSUE TITLE
varchar not null does not allow empty strings

### ISSUE THREAD

**Issue by dylanthelion** [dotnet/efcore#14279]
Start a DB first project, and run a DbScaffold with the -d flag on a table with a column like:
```
, Foo varchar(50) not null
```
The generated code is:
```
[Required]
[MaxLength(50)]
public string Foo { get; set; }

```
The issue with this, is that the DB can accept an empty string Foo, but if you call

```
if(!ModelState.IsValid) { throw; }

```
the validation will fail.

I understand that this has been raised as an issue and closed in the past, because you can set the AllowEmptyStrings property of the Required attribute, but this doesn't work when you're running frequent migrations, as my team is; those changes will be overwritten. Is there a reason why the generated code does not match the constraints in the DB?

**Comment by ajcvickers** [comment]
Based on our experience, it is much more common to use `[Required]` for non-nullable database columns than it is to use `[Required(AllowEmptyStrings = true)]`, so that's what scaffolding generates.

Running the tool without the `--data-annotations` option will configure the property to allow empty strings since no `Required` attribute will be generated.

Beyond this, #4038 covers customization of the output using templates or similar. Also, @ErikEJ might consider adding an option for this in the Power Tools.

**Comment by dylanthelion** [comment]
@ajcvickers : Thanks!

To your first point: fair. I feel like not adding a character length >0 CHECK is...just kind of lazy, but lazy design is a reality of the industry. I've been guilty of this plenty of times, and the databases my team is working with are prime examples of the same. I respect that you built your tool to be easy to use, instead of strictly intuitive (read: "technically correct" if you like Futurama).

To your second point: a very onerous option for us, but that's fine.

And the last: I'm sorry I couldn't fine the scaffolding override options before wasting your time with this question. Again, thanks: you've given me something to do this weekend.
