### ISSUE TITLE
RelationalDataStoreCreator.EnsureCreated returns false if DB already exists and has schema

### ISSUE THREAD

**Issue by egorpavlikhin** [dotnet/efcore#1427]
https://github.com/aspnet/EntityFramework/blob/48b776f65d97c6589fae1842215ce86119ccdaf7/src/EntityFramework.Relational/RelationalDataStoreCreator.cs#L64

Otherwise the sample MVC app in Identity repo won't work on a relational db.

Currently:

```
public override bool EnsureCreated(IModel model)
    {
        Check.NotNull(model, "model");

        if (!Exists())
        {
            Create();
            CreateTables(model);
            return true;
        }

        if (!HasTables())
        {
            CreateTables(model);
            return true;
        }

        return false;
    }
```

Should be:

```
public override bool EnsureCreated(IModel model)
    {
        Check.NotNull(model, "model");

        if (Exists() && HasTables())
        {
            return true;
        }

        if (!Exists())
        {
            Create();
        }

        if (!HasTables())
        {
            CreateTables(model);
            return true;
        }

        return false;
    }
```

**Comment by ajcvickers** [comment]
@egorpavlikhin The return value indicates whether or not the database and/or its tables were created. In other words, the return value is false if the call was a no-op. This can then be used to determine whether or not the database should be seeded, which can be useful in test code where several tests share a common database that should only be created and seeded once.

**Comment by egorpavlikhin** [comment]
So then it's rather a bug in Identity sample project, which should be calling Exists instead of EnsureCreated.

https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Models/SampleData.cs#L20

**Comment by rowanmiller** [comment]
@egorpavlikhin - The logic in that file is correct. That logic means that if EnsureCreated creates the database then the seed data will get added. If the database already existed then EnsureCreated returns false and the seed data is not needed (since it would have been added when the database was actually created). This is the scenario the return value is intended to be used for.

**Comment by egorpavlikhin** [comment]
@rowanmiller the problem is that it then skips CreateAdminUser(), which it shouldn't. Should I create a different issue in the Identity project?

**Comment by divega** [comment]
@egorpavlikhin feel free to file a bug on the Identity repo if this isn't working for you. 

But as @rowanmiller mentioned the code seems correct, e.g. you are only supposed to create the admin user the first time the code runs and when the database is created. In all subsequent times this code is executed if the database is already created the admin user should already be in the database. 

Incidentally the sample code could be simplified a bit: there shouldn't be a need to special case `SqlServerDatabase`, because we have made `EnsureCreated()` return consistent values for the in-memory provider as well.
