### ISSUE TITLE
ef core not detecting enum in class

### ISSUE THREAD

**Issue by mtad2002** [dotnet/efcore#14450]
EF core not detecting enum in code first 

i have an entity and trying to add enum type as int in it but ef core silently not detecting my enum 
and not adding column and not throwing any errors .

in other entities everything working fine with enums but this class not working properly

```
 public class UserBankAccount : BaseEntity
    {
        [Required]
        [Column(TypeName = "int")]
        [Display(Name = "وضعیت تایید")]
        public UserBankStatus userBankAccountStatus;
}

public enum UserBankStatus
    {
        [Display(Name = "مشخصات ثبت شده")] InfoApplied = 0,
        [Display(Name = "مشخصات رد شده")] InfoRejected = 1,
        [Display(Name = "مشخصات تایید شده")] InfoVerified = 2,
        [Display(Name = "مشخصات بروزرسانی شده")] InfoUpdated = 3
    }

```

### Further technical details
EF Core version:  Entity Framework Core 2.2.1-servicing-10028 initialized
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE:  Visual Studio 2017 15.9.4

**Comment by 4nonym0us** [comment]
You should use property instead of field to store UserBankStatus in your entity. 
Replace `public UserBankStatus userBankAccountStatus;` 
with `public UserBankStatus userBankAccountStatus { get; set; };`

One more reminder: enums are mapped to Int32 by default and using `Column` attribute to define enum type might be a bad idea. If you want to map it to `short` (or to explicitly define that it's integer), for example, I'd suggest you to define that in your enum like this instead of using `Column` attribute):
```csharp
public enum UserBankStatus : short
{
    [Display(Name = "مشخصات ثبت شده")] InfoApplied = 0,
    [Display(Name = "مشخصات رد شده")] InfoRejected = 1,
    [Display(Name = "مشخصات تایید شده")] InfoVerified = 2,
    [Display(Name = "مشخصات بروزرسانی شده")] InfoUpdated = 3
}
```
