### ISSUE TITLE
Self referencing many to many relation problem.

### ISSUE THREAD

**Issue by CuteLeon** [dotnet/efcore#14475]
hi all:
    there is something wrong when I tried to create a self-referencing Many-To-Many relationship between the same Model, I tried the document in MSDN, but the example is about two Models, and it didn't work, so I need your help. Thanks.

##### Model:

```
/// <summary>
/// the Self-referencing model
/// </summary>
public class Version
{
	/// <summary>
    /// ID
    /// </summary>
    [Key]
    public string Id { get; set; }

    /// <summary>
    /// precursor version
    /// </summary>
    public virtual List<HeadVersion> HeadVersions { get; set; }
}

/// <summary>
/// the relationship model
/// </summary>
public class HeadVersion
{
	[Key]
	public string Version_1_ID { get; set; }

	public Version Version_1 { get; set; }

	[Key]
	public string Version_2_ID { get; set; }

	public Version Version_2 { get; set; }
}
```

 	As you see, I have a Model named `Version` , I want to create a relationship between `Version` via the relationship-model named `HeadVersion`，and I have  Fluent API like this :

**ApplicationDbContext.cs**

```
protected override void OnModelCreating(ModelBuilder builder)
{
	builder.Entity<HeadVersion>()
        .HasOne(relation => relation.Version_1)
        .WithMany(version => version.HeadVersions)
        .HasForeignKey(relation => relation.Version_1_ID);

    builder.Entity<HeadVersion>()
        .HasOne(relation => relation.Version_2)
        .WithMany(version => version.HeadVersions)
        .HasForeignKey(relation => relation.Version_2_ID);

    base.OnModelCreating(builder);
}
```

​      but when I execute `add-migration CreateModels`, I got a Exception:

```
System.InvalidOperationException:“Cannot create a relationship between 'Version.HeadVersions' and 'HeadVersion.Version_2', because there already is a relationship between 'Version.HeadVersions' and 'HeadVersion.Version_1'. Navigation properties can only participate in a single relationship.”
```

​     so I am so confused how should I to create a self-referencing Many-To-Many relationship between the same Model, thanks.

##### Development Environment:

- Visual Studio 2017(15.9.5)
- ASP.NET Core 2.2.1
- DataBase : SQLite
- EntityFrameworkCore.Sqlite 2.2.1

Regards,
Leon

**Comment by VinnieThePooh** [comment]
Firstly, you create here one-to-many relationship, and do it twice.
Notes about many-to-many (m-t-m further): 
1.  EF Core does not support many-to-many without join table manual creation. Related [issue](https://github.com/aspnet/EntityFrameworkCore/issues/1368).
2. The only workaround i know for m-t-m for the same table is described [here](https://stackoverflow.com/questions/39771808/entity-framework-core-many-to-many-relationship-with-same-entity).
One relation reserves one collection navigation property, so for m-t-m for the same table
 you need 2 navigation properties - actual and fake navigation property. 
Otherwise, your configuration is not passed by EF Core internal validation.

Probably, you could redesign your domain, HeadVersion => Version (one to many), it would be the best solution.
