### ISSUE TITLE
Reconsider navigations on query type

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#14481]

**Comment by ajcvickers** [comment]
Notes from triage: Issue #14194 is tracking merging query types and entity types. At that point all navigations will be allowed except those that reference an entity type with no key as the principal end.

**Comment by ajcvickers** [comment]
Update to the note above. After further discussion, _all_ navigations to query types will be disallowed. This is because:
* There is a point of view which says references to query types is not needed. That is, in a well-defined model query types should only ever have references to entity types. Query types should never reference other query types, and should never reference entity types, even if the query type has an FK property and there is an entity type with a PK that matches that FK.
* This means that even though query types cannot be tracked, they could be used to pull in entity types that are tracked without ambiguity. (Note that this is not implemented yet.)
