### ISSUE TITLE
Query: Allow providers to influence funcletization on low level

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#14507]
Currently, our funcletization is influenced by providers in 2 ways.
- Indicating that certain expression should not be evaluated on server. (mainly non-deterministic ones)
- `NotParameterizedAttribute` to avoid parameterization of any function's parameter.

Both of above works fine till you encounter a method which is coming from other library. This disallows you from putting the attribute on parameter. And in order to determine that the function parameter should not be converted to query parameter, you need more info on parent expression tree to look at the function.
One such example is 
`string.Compare(string s1, string s2, bool ignoreCase);`

**Comment by pmiddleton** [comment]
@smitpatel - 

Has there been any discussion within the team of my idea to centralize all function registration into a single metadata store?

If we do that then this use case becomes easy to solve because the end user can modify all of the functions via the fluent api.  That also assumes we add a way to mark a parameter as `NotParameterized` which wouldn't be difficult.

**Comment by smitpatel** [comment]
Rather than putting complexity in funcletization it would be better handled in RelationalCommandCache.
