### ISSUE TITLE
Get  EntityEntry<TEntity> from EntityEntry

### ISSUE THREAD

**Issue by REscobar** [dotnet/efcore#14521]
EF6 `DbEntityEntry` provided the `Cast<TEntity>` method to get a typed `DbEntityEntry<TEntity>`, this api is not present in EFCore

EF6 implementation was to create a new instance of `DbEntityEntry<TEntity>` when this method was called using a type check to validate that the type was assignable, an EFCore implementation could be similar to:

```csharp
        public virtual EntityEntry<TEntity> Cast<TEntity>() where TEntity : class
        {
            if (!typeof(TEntity).IsAssignableFrom(InternalEntry.EntityType.ClrType)))
            {
                throw new InvalidCastException();
            }

            return new EntityEntry<TEntity>(InternalEntry);
        }
```

I'm porting a small library that provides trigger like actions to be performed when submiting changes to the database and being unable to convert to `DbEntityEntry<TEntity>` makes the implementation of such actions very error prone.

**Comment by ajcvickers** [comment]
@REscobar Is there something preventing the code creating `EntityEntry<T>` in the first place?

**Comment by REscobar** [comment]
Yes, InternalEntry is protected and not accessible from outside inheriting classes.

**Comment by ajcvickers** [comment]
@REscobar We added these in EF6 because there were two separate type hierarchies for the generic and non-generic types. In EF Core, the generic `EntityEntry<TEntity>` derives from `EntityEntry` which largely makes these conversions not useful. Also, if you must start with the non-generic instance, then it can be converted with a simple extension method. Something like this:

```C#
public static EntityEntry<TEntity> Cast<TEntity>(this EntityEntry entry) where TEntity : class
    => entry.Context.Entry((TEntity)entry.Entity);
```

I'll keep this issue open to discuss adding API surface here, but given the simplicity of doing with the above method it seems unlikely that it is API surface we will want to add.

**Comment by nikita-starostin** [comment]
this not working when need to cast from runtime type, possibly it is about generics casting, jfyi

```C#
            // typeof(withSideEffectEntry) == EntityEntry<IWithSideEffect>
            var entityType = withSideEffectEntry.Entity.GetType();
            var castMethod = GetType().GetMethod(nameof(Cast)).MakeGenericMethod(entityType);
            var entityCastedToConcretedMethod = castMethod.Invoke(null, new object[] { withSideEffectEntry.Entity });
            var entryCastedToConcreteClass = withSideEffectEntry.Context.Entry(entityCastedToConcretedMethod);
            // method - is generic method received via reflection, it should be called with EntityEntry<TEntity>, however currenyl I have exception EntityEntry<IWithSideEffect> can not be casted to my class
            // the type of entryCastedToConcreteClass is EntityEntry, but I need somehow to get EntityEntry<TEntity>, where TEntity - is concrete entity, not one of implemented interfaces
            var task = (Task)method.Invoke(
                sideEffectHandler,
                new object[] { entryCastedToConcreteClass, CancellationToken.None });
            return task;
```

**Comment by MelGrubb** [comment]
Since this is one of the only discussions I can find on this topic, I'm hoping that at least someone is still paying attention to this and might have some insight. The casting solutions above might work great if you know what you're looking for at compile time, but is there any way to get `EntityEntry<TEntity>` from `EntityEntry` at runtime?

I am trying to publish events via an event aggregator / pubsub system when entities are added, updated, or deleted. Calling ChangeTracker.Entries() gets me the full list of entities that are about to be saved, but they are all just the plain `EntityEntry` base class, and I need to publish the closed generic type `EntitySaving<EntityEntry<Person>>` or `EntitySaved<EntityEntry<Person>>` so that the subscribers can subscribe to only the message types they're interested in.

The `EntitySaved<T>` class has a constructor that expects an instance of `EntityEntry<T>`. If I changed it to use the base `EntityEntry` type, then each subscriber would have to check each event to make sure that the entity it contains is the right type.

I can't find a way from here to there.

**Comment by MelGrubb** [comment]
I already have the hooks/triggers taken care of, it's getting hold of the `EntityEntry<Foo>` that's the problem. Maybe I can root around in his source code and see how he's coming up with the typed before and after triggers. I don't see anywhere where he's handling those types, though. I could easily use reflection to spin up a similar type that says "A Foo was just saved", but I need to get to the original and current value collections, which are on the original `EntityEntry` instance. I'm already wrapping that, so maybe I could do _without_ the typed `EntityEntry` as long as my event class is typed. Okay, I have a few different options to try.

**Comment by REscobar** [comment]
You can get a typed `EntityEntry{TEntity}` from a untyped `EntityEntry` doing `entityEntry.Context.Entry((TEntity)entityEntry.Entity)`

**Comment by MelGrubb** [comment]
My problem is that I don't have access to TEntity where I am. I'm in the DbContext, and it's not generic. I need to resolve EntityEntry<T> so that I can pass it as a constructor parameter to a message class EntitySaving<T>. I suppose that from _inside_ that class I would have access to TEntity, but I'd still have to take the plain EntityEntry as the constructor parameter and then cast it inside the constructor... That could work, I suppose. I don't love it, but it could work.

**Comment by REscobar** [comment]
If your use case requires creating a `EntitySaving` class without "pre-registering" the `EntityType` in a `ServiceCollection` or similar, that is, emiting the message even if no one may be listening, then I think reflection could be your next best option, check this sample console app it dynamically creates a factory for each `EntityType` and is able to create a `new EntitySavingMessage(EntityEntry{EntityType})` which you may use for your needs, check the `SavingChangesAsync` function on the `DbContext`.

The last function on the sample is the one responsible for magic stuff



```csharp
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;

Console.WriteLine("Hello, World!");
var contextOptions = new DbContextOptionsBuilder()
    .UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Messaging-Context;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")
    .Options;

var context = new MessagingDbContext(contextOptions);
context.Database.EnsureCreated();

context.Add(new SampleEntity
{
    Field = "Sample value",
});

await context.SaveChangesAsync();


internal class EntitySavingMessage
{
    private readonly EntityEntry entityEntry;

    public EntitySavingMessage(EntityEntry entityEntry)
    {
        this.entityEntry = entityEntry;
    }
}

internal class EntitySavingMessage<TEntity> : EntitySavingMessage
    where TEntity : class
{
    private readonly EntityEntry<TEntity> entry;

    public EntitySavingMessage(EntityEntry<TEntity> entry) :
        base(entry)
    {
        Console.WriteLine("Constructor with generic argument called");
        this.entry = entry;
    }
}

internal class SampleEntity
{
    public int Id { get; set; }

    public string Field { get; set; }
}


internal class MessagingDbContext : DbContext
{
    private Dictionary<Type, Func<EntityEntry, EntitySavingMessage>> messageFactoryCache = new Dictionary<Type, Func<EntityEntry, EntitySavingMessage>>();

    public MessagingDbContext(DbContextOptions options) :
        base(options)
    {        
    }

    public DbSet<SampleEntity> SampleEntities { get; set; }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        var entries = this.ChangeTracker.Entries()
                 .Where(
                     entry =>
                         (entry.State == EntityState.Added) ||
                         (entry.State == EntityState.Modified) ||
                         (entry.State == EntityState.Deleted));

        foreach (var item in entries)
        {
            var message = this.CreateMessage(item);
            // profit
        }

        return base.SaveChangesAsync(cancellationToken);
    }

    private EntitySavingMessage CreateMessage(EntityEntry item)
    {
        if (this.messageFactoryCache.TryGetValue(item.Entity.GetType(), out var factory))
        {
            return factory(item);
        }
        else
        {
            factory = CreateAndRegisterFactory(item.Entity.GetType());
            return factory(item);
        }
    }

    private Func<EntityEntry, EntitySavingMessage> CreateAndRegisterFactory(Type type)
    {
        var messageType = typeof(EntitySavingMessage<>).MakeGenericType(type);
        var messageCtor = messageType.GetConstructors().First();
        var parameter = Expression.Parameter(typeof(EntityEntry), "entityEntry");
        var entityProperty = Expression.Property(parameter, nameof(EntityEntry.Entity));
        var entityPropertyCast = Expression.TypeAs(entityProperty, type);

        var contextProperty = Expression.Property(parameter, nameof(EntityEntry.Context));
        var typedEntryMethod = typeof(DbContext).GetMethod(nameof(DbContext.Entry), genericParameterCount: 1, new Type[] { Type.MakeGenericMethodParameter(0) });
        var typedEntryGenericMethod = typedEntryMethod.MakeGenericMethod(type);

        //entityEntry.Context.Entry(entityEntry.Entity as {TEntity})
        var typedEntryMethodCall = Expression.Call(contextProperty, typedEntryGenericMethod, entityPropertyCast);

        //new EntitySavingMessage(entityEntry.Context.Entry(entityEntry.Entity as {TEntity}));
        var messageCtorCall = Expression.New(messageCtor, typedEntryMethodCall);

        var body = Expression.Block(messageCtorCall);
        var lambda = Expression.Lambda<Func<EntityEntry, EntitySavingMessage>>(body, parameter);

        var compiled = lambda.Compile();

        this.messageFactoryCache[type] = compiled;

        return compiled;
    }
}```
