### ISSUE TITLE
Migrate Data process Disable auto-increment Ids

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/efcore#14597]
Hello,

We use EfCore with multiple database providers. Our app support Mssql,Mysql and PostgreSql. We want to create a tool to migrate data from one Db technology to Other. 

We try a approche that creates 2 DbContexts with different providers configured. Then we try to load the data untracked and insert them with the second DbContext. The problem is that we want to keep the same ids. Is there any solution to tell the entity framework to tell the database to keep the ids we provide?

thank you

**Comment by mohamedmahmoudalemam** [comment]
Firstly, I prefer to select only one database (PostgreSql) is good. I think the best solution for you problem is create in each table a column called DevName (unique column)-(specify its value using a prefix of table name and numbers(std1, std2, std3 for table student), you can use different way to initialize this column), and you query against tables using this column. 
ex: context.Students.Where(x => x.DevName == "std1");

**Comment by ajcvickers** [comment]
@xrkolovos If a key value is explicitly set in the entity, then EF will use send it to the database. The problem comes in whether or not the database itself allows this. SQL Server, for example, requires a special mode enabled (IDENTITY_INSERT) before values can be explicitly set into an identity column.

So, basically, EF should not prevent you from doing this, but the underlying database engine may have limitations that make it hard.
