### ISSUE TITLE
Is it better to use SetValues or update a tracked entity by reference?

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/efcore#14626]
```csharp

// Fetch the item from the database
var itemFromDatabase = await _context.Set<TEntity>().SingleOrDefaultAsync(x => x.Id == updateViewModel.Id);

// Overwrite the values on the EF tracked itemFromDatabase
_mapper.Map(updateViewModel, itemFromDatabase);

// ------------
//       VS
// ------------

// Map VM to an entity and then call SetValues instead of the above approach
var updateEntity = _mapper.Map<TEntity>(updateViewModel);
_context.Entry(itemFromDatabase).CurrentValues.SetValues(updateEntity);
```

How different are these? Which is preferred? I know when you use AutoMapper, your config could be newing up navigation property items. SetValues wont do that right?

Bonus question: Is saying "tracked" the same thing as saying "attached" in EF land?

**Comment by ajcvickers** [comment]
@VictorioBerra I'm not familiar enough with AutoMapper to know for sure. They are both taking values from one object and applying them to another object. SetValues does it in a very simplistic way, so I would be surprised if you can't configure AutoMapper to do the same thing. You are correct that SetValues only works on the non-navigation mapped properties of the entity.

Yes, "tracked" is the same as "attached". However, attached can sometimes imply that the state is `Unchanged` because the `Attach` method does this.

**Comment by VictorioBerra** [comment]
@ajcvickers Thanks for taking the time to answer! One follow up question, does `context.Entry()` attach if an item is detached? Whats the difference betwee:

```csharp
var a = _context.Attach(item);
var b = _context.Entry(item);
```

They both return an EntityEntry. I assume Entry wont work if the entity is not already being tracked?

**Comment by ajcvickers** [comment]
@VictorioBerra See: [Attach](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.attach?view=efcore-2.1) and [Entry](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.entry?view=efcore-2.1).
