### ISSUE TITLE
Converters for collections are not called

### ISSUE THREAD

**Issue by mqudsi** [dotnet/efcore#14660]
It seems that type converters specifying a conversion to a supported collection type are not called/used.

e.g. 

```csharp
public class Email {
    public Email(string email) { EmailAddress = email }
    public string EmailAddress { get; set; }
}

public class Contact {
    public int Id { get; set; }
    public List<Email> Emails { get; set; }
}

public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.Entity<Contact>()
            .Property(c => c.Emails)
            .HasConversion(emails => emails.Select(e => e.EmailAddress).ToList(),
                emails => emails.Select(e => new Models.Email(e)).ToList());
    }
}
```

If `Contact.Emails` were defined as `List<string>` everything would work; so presumably mapping from `List<Email>` to `List<string>` should also work. But in practice it throws the following:

> The property `Contact.Emails` is of type `List<Emails>` which is not supported by current database provider. Either change the property CLR type or ignore the property using the `[NotMapped]` attribute or by using `EntityTypeBuilder.Ignore` in `OnModelCreating`.

(Hopefully it would also work without the `.ToList()` as well)

### Further technical details
EF Core version: 2.2.1
Database Provider: SQLite
Operating system: Windows 10 17763
IDE: Visual Studio 2019 16.0.0 preview 2.2

**Comment by ajcvickers** [comment]
@mqudsi Value converters allow conversion from some type/format that the database provider cannot map to a type/format that the database provider can map. Since the SQLite provider (and most others) doesn't support mapping lists, it means that in your case you're doing a conversion to something that the provider still can't map; hence the error.  You could instead serialize the list into something like a string representation and store that, since the provider can map strings.
