### ISSUE TITLE
Feature Request: Xml Datasource

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#1469]
I'd like to request for a future release, creating an xml data store.  This would be useful for really small almost static websites and very simple applications that have records small sets of data that doesn't really warrant creating an actual database. 

It would also serve as a decent prototyping tool that still maintains state without the overhead of things like sql server, redis, etc.  IMHO, this would make .NET more enticing to entrepreneurs.

**Comment by davidfowl** [comment]
What does this have to do with EntityFramework?

**Comment by michaelherndon** [comment]
The old version of EF weakened the need for creating repository abstractions since DbContext and DbSet seem to function as the unit-of-work and repository.  The newer version of EF 7 takes this a step further with the introduction of nosql databases.  The repositories that developers created end up being a repository repository when its used in conjuction with EF.  

Using xml requires an extra layer of abstraction in order to switch between xml and EF currently, though that may not need to be the case. 

An EF xml/whatever data provider (for lack of a better term at the moment) could be very useful for:
* applications that start small
* prototypes that are developed to show off to users in order to gain feedback quickly.
* applications that ride the line of needing something small to sql depending on the consumer.

Inmemory is only for testing purposes, at least that is my take from it. Maybe the storage doesn't have to be xml, but what I can see is that there is value in having a data provider between inmemory and using sql-server.  

An application would no longer require an extra layer of abstraction just start off with something simple and then move to sql-server without having to manage a custom built data access layer and EF.  

It would give a developer peace of mind that they could  switch their application to using a database later with minimum effort and minimize the loss of work.

**Comment by ErikEJ** [comment]
Sounds like SQL Server Compact and/or SQLite would fit the bill, and offer many advantages over xml

**Comment by michaelherndon** [comment]
The primary two things that I'm looking at are building prototypes or just starting an application.  

These are times where one doesn't want to get too attached to the prototype, application, or schema.  With a sql database, there are extra mental processes and effort/time devoted to getting the schema right and sometimes wrestling with the quirks of the database.  You can also get caught up in fiddling too much with the schema migrations.  The more time you invest into any of the above, the harder it becomes to just throw it all away.  

Also you want the focus of your time to be on building out things that users are more interested in. 

In these cases, dealing with SQL can be more of a hinderance.

**Comment by divega** [comment]
We could allow the contents of the InMemory store to be serialized to and from a file. Although I think @ErikEJ is right that an embeded database would work just fine for prototyping in most cases.

**Comment by michaelherndon** [comment]
That would be sufficient. 

It would fall in line with opting into things as you need them. 

It also would help startups to be more willing to throw away their prototypes in order to pivot. And it would free up those of us that work on side projects to focus more on the creative side of things than dealing with the DAL too much upfront.

**Comment by rowanmiller** [comment]
__EF Team Triage:__ Discussed and concluded that this isn't something our team would do. Between the InMemory data store and a lightweight database (SQLite, SQL Compact etc.) it seems like there are enough options here.
