### ISSUE TITLE
Weak/shared types: Consider adding weakly typed query operators and cast expressions

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#14718]
If `x` is mapped to a weak/shared CLR type, strongly-typed query expressions like `xs.Cast<W>()`, `xs.OfType<W>()`, `(W)x`, `x as W`, `x is W`, won't be enough to express operations for a specific entity type in queries. 

At least for some of these we could create IQueryable extensions or EF class methods that allow passing a specific "conceptual" entity type, for example using the entity type name as a string.

**Comment by smitpatel** [comment]
Even though weak/shared types are not identified by just type, there would always be query root which identify if such type is used. Or if it accessed via a navigation then metadata gives real entityType. At that point, any cast or other queryable operators are going to be identifying the EntityType in hierarchy since we already have which one IEntityType there. So there is no confusion or ambiguity and it works automatically.
