### ISSUE TITLE
LazyLoading and null in navigation property

### ISSUE THREAD

**Issue by Forester-** [dotnet/efcore#14731]
There are two entities. The first entity contains a collection of the second entities. And this collection is lazy loading property as described in "Loading Related Data, Lazy loading without proxies" (https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading).

```C#
    [Table("Entity")]
    class Entity
    {
        private readonly ILazyLoader _lazyLoader;
        internal List<ChildEntity> _children;

        public Entity() { }
        private Entity(ILazyLoader lazyLoader)
        {
            _lazyLoader = lazyLoader ?? throw new ArgumentNullException(nameof(lazyLoader));
        }

        [Key]
        public int Id { get; set; }

        [InverseProperty(nameof(ChildEntity.Parent))]
        public List<ChildEntity> Children
        {
            get => _lazyLoader.Load(this, ref _children);
            set => _children = value;
        }
    }

    [Table("ChildEntity")]
    class ChildEntity
    {
        [Key]
        public int Id { get; set; }

        public int EntityId { get; set; }
        [ForeignKey(nameof(EntityId))]
        public Entity Parent { get; set; }
    }
```

Consider two scenarios of getting the entity from DbContext. DB does not contain any data at scenarios start.
The first scenario:
1. Create DbContext
2. Create new Entity, don't set value of Children property. It is null by default.
3. Add entity in DbContext
4. SaveChanges
5. Get entity from DbContext as `db.Entity` without Include.

The second scenario:
1. Create DbContext
2. Create new Entity, don't set value of Children property. It is null by default.
3. Add entity in DbContext
4. SaveChanges
5. Close DbContext
6. Create DbContext
7. Get entity from DbContext as `db.Entity` without Include.

The difference between the scenarios is that in the first scenario `entity.Children == null`, but in the second `entity.Children != null`.

Usually navigation collections in EFCore is not null. Without lazy loading in both scenarios `entity.Children != null`. So it would be good if EFCore in the first scenario would `set entity.Children = new List<ChildEntity>()`.

Sampe source code is available at https://github.com/Forester-/EFCoreNavPropInit

### Further technical details
EF Core version: 2.2.2
Database Provider: Microsoft.EntityFrameworkCore.InMemory (does not matter)
Operating system: Windows 10
IDE: Visual Studio 2017 15.4.5

**Comment by ajcvickers** [comment]
@Forester- In the first scenario, an entity instance is still being tracked when when the query executes, which means that this instance is returned rather than a new instance created from the database. However, this instance was created without an `ILazyLoader`, which means that it does not attempt to load related entities, and hence the collection navigation property remains uninitialized.

In the second scenario, a new entity instance is created and it gets the `ILazyLoader` injected, which means that reading the collection navigation property to be loaded, which in turn creates the collection since it doesn't already exist.

A couple of ways to change this:
* Create a service property for `ILazyLoader`--for example, `private ILazyLoader LazyLoader { get; set; }`. The context can then inject the `ILazyLoader` when the entity instance is tracked, even if it was originally constructed without one.
* Change the code in in the navigation property getter to always create a collection, even if `ILazyLoader` has not been injected.

**Comment by Forester-** [comment]
Thank you very much for advice with `private ILazyLoader LazyLoader { get; set; }`. It works. I missed this moment in the documentation. My fault...
