### ISSUE TITLE
Possibility of changing Migration2 in EFCore.Relational.Specification.Tests

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#14749]
As I'm trying to integrate `EFCore.Relational.Specification.Tests` into [`FirebirdSql.EntityFrameworkCore.Firebird`](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/tree/master/Provider/src/FirebirdSql.EntityFrameworkCore.Firebird) I'm facing an issue, that the [`Migration2`](https://github.com/aspnet/EntityFrameworkCore/blob/master/test/EFCore.Relational.Specification.Tests/MigrationsFixtureBase.cs#L71) is using `RenameTable` operation, which is [not supported on Firebird](http://www.firebirdfaq.org/faq363/). That makes all the `Can_revert_one_migrations`, etc. tests useless for me, because the `NotSupportedException` is always thrown. Is there a chance of changing this migration (i.e. `RenameColumn` would be fine for me)? Or any other idea how to solve this (without forking the tests and keeping my own copy)?

**Comment by ajcvickers** [comment]
@cincuranet We would be happy to take a PR that makes the specification tests better for external providers--we have taken such changes from Npgsql and SQLite in the past. Just make sure that the tests are still testing what they should.

For cases where this isn't possible because the thing being tested just isn't supported, then override the tests in your code to disable them. All the tests should be virtual, but if they're not we would love a PR for that too.

**Comment by cincuranet** [comment]
OK. Done in #14811.
