### ISSUE TITLE
Anxious for table-per-hierarchy

### ISSUE THREAD

**Issue by heathyates** [dotnet/efcore#1476]
I have seen many users point out that EF does not have support for inheritance. In fact, I have learned this is already well known and being work on by the team, as seen here: https://github.com/aspnet/EntityFramework/issues/247

I have two questions: 
1. When might it be ready for test and evaluation?  Especially tph(table per hierarchy)? We would really like to help evaluate and test this when you are ready. I also realize you may be tempted to answer it like this: http://imdb.to/1H0Ujd8 :)
2. In the meantime, is there anyway we could currently try to mimic tph (database first perhaps)? It seems the current behavior is tpt (table per type)?

**Comment by rowanmiller** [comment]
Hey,

1. Love the quote :smile:... I can be a little more specific. We view inheritance mapping as a 'must have O/RM feature' and we expect to have all those implemented toward the end of the year [insert usual disclaimer that things can change, this is just what we think, etc.].
2. There isn't really a way to mimic it at the moment. If you use inheritance then the types are treated as two completely different types (as if they didn't inherit). We also don't make any guarantees that stuff won't just break since we haven't implemented inheritance at all yet... that just happens to be what occurs with the current logic.

~Rowan

**Comment by heathyates** [comment]
Thanks. Your reply will help us and I feel many others who had this question and propel a lot of folks projects further. If anyone has come across this, I would suggest they design a concrete schema as carefully as possible with an eye towards extending those concrete tables as base classes when the time for tph comes.
