### ISSUE TITLE
Cosmos: Add basic support for collections and dictionaries of primitive types

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#14762]
It should be possible to implement this without a `ValueConverter` because Cosmos supports them natively.

This issue doesn't include server translation of queries with any methods using properties of these types,   essentially they will be treated as atomic units.

**Comment by kierenj** [comment]
Hi, I'm keen to understand the `propose-punt` label please? I understand Backlog means this is vaguely planned for the future. Am keen to see if a project in 3-6 months should go the EF Core / Cosmos route or not - understand you can't give a definitive on this feature but just so I can guess the odds :) Thanks

**Comment by smitpatel** [comment]
@kierenj - We use `propose-punt` label for issues which we had planned for certain release but due to time constraints we ended up removing it from that release. Like this issue was planned for 3.0 but we had more work in 3.0 then what can be done in the time we got. So `propose-punt` label signifies that we consider this should be punted from 3.0 release. We go through such issues and decide if we can punt past 3.0 or we need to do it in 3.0. This issue got cut and `propose-punt` became `punted-for-3.0`.

This issue is currently in backlog milestone so we are not working on it for our next release 3.1. Cosmos being a new provider which is going to be RTM first time in 3.0, we are going to evolve cosmos based on user feedback. We will prioritize adding features which are requested by many customers. When planning a release, we look at how many people have voted for a feature to decide if it is in demand. Please upvote first issue if you need this.

**Comment by svrooij** [comment]
It seems weird to me that the provided documentation [states](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli#embedded-entities) how easy it is to embed entities, that I could believe that embedding a simple string collection is **unsupported**.

@ajcvickers or @smitpatel do you guys maybe have an update for us? Since EF Core 5 is just released and this still isn't supported.

**Comment by kierenj** [comment]
@svrooij Strings aren't entities, of course. I think the documentation is accurate

**Comment by svrooij** [comment]
> @svrooij Strings aren't entities, of course. I think the documentation is accurate

Yes, if you put it that way, sure. But I wasn't talking about the documentation, I was talking about that it's weird you're able to embed entire objects but not a collection of strings. Even more because cosmos supports the [**ARRAY_CONTAINS**](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-array-contains#:~:text=ARRAY_CONTAINS%20(Azure%20Cosmos%20DB)&text=Returns%20a%20Boolean%20indicating%20whether,boolean%20expression%20within%20the%20command.) query function.

So if I stop using the EF core framework and just connect to plain cosmos I can set a property to a string collection and even use ARRAY_CONTAINS to query based on the values.

**Comment by Assassinbeast** [comment]
> It should be possible to implement this without a `ValueConverter` because Cosmos supports them natively.

@AndriySvyryd can you show an example on how to do it with a ValueConverter? I would really appreciate it.

**Comment by Marusyk** [comment]
@Assassinbeast 
something like 

```
modelBuilder.Entity<YourEntity>()
        .Property(e => e.Strings)
        .HasConversion(
            v => string.Join(',', v),
            v => v.Split(',', StringSplitOptions.RemoveEmptyEntries));
```

**Comment by Assassinbeast** [comment]
> ```
> modelBuilder.Entity<YourEntity>()
>         .Property(e => e.Strings)
>         .HasConversion(
>             v => string.Join(',', v),
>             v => v.Split(',', StringSplitOptions.RemoveEmptyEntries));
> ```

@Marusyk Thanks! So this will mean in my C# code, that its a string array, but in CosmosDB, it will become a single string. That means I cant make a query against an array. Is that correct?

**Comment by svrooij** [comment]
> That means I cant make a CosmosDB query against an array. Is that correct?

That is exactly the problem. This way it is saved but you cannot query for it.

**Comment by Drew-E** [comment]
Is there any update on this?  It definitely missed 5.0 as well.

**Comment by AndriySvyryd** [comment]
@Drew-E It's in the Backlog milestone, meaning it's not planned for 6.0 either

**Comment by pcbl** [comment]
Hi Folks,

Facing same issue. Just need to save an double[], but using the  folowing code:
```
location.Property(l => l.Coordinates).HasConversion(t => JsonConvert.SerializeObject(t),
                                             s => JsonConvert.DeserializeObject<double[]>(s)).ToJsonProperty("coordinates");
```

It gets saved as:
"coordinates": "[-44.431451,-16.223516]"

But I expect:
"coordinates": [-44.431451,-16.223516]

This EF Core Cosmos useless on my case as I need to run Spatial Queries against the data. Quite annoying to see that this issue is open for so long, but still not in place.

That way I am forced to use CosmosDB SDK directly, which I wanted to avoid on this specific scenario...

Are there any workaround I could make to overcome this issue until there`s a fix for it? Tried many options, but none worked...

**Comment by AndriySvyryd** [comment]
@pcbl Spatial support is tracked by https://github.com/dotnet/efcore/issues/17317

**Comment by AndriySvyryd** [comment]
For issues in the backlog we don't have any specific plans, they are reprioritized after each release.

**Comment by PaulOst** [comment]
Is first-class support for collections and dictionaries of primitive types anywhere in our future? Why is such a basic capability in the backlog for so long? Not having this capability is a showstopper for my team. Whatever your reprioritization plans are you are giving us the impression that the EF Core provider just isn't important.

**Comment by ericb-blankenburg** [comment]
This is a huge issue for us too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pcbl** [comment]
@ericb-blankenburg , @PaulOst ,
On my Team we end up not using EF Core for the objects we store on Cosmos and relies on stuff like GeoSpatial data and so on. For Collections and Dictionaries we did not notice the issue as on the case in question it was a simple object with coordinates. At the end of the day we implemented a repository using CosmosDB SDK directly... For now our CosmoDB repository is somehow very limited as we hope to switch it to the EF Core version later down the road... But when that will be? Not so sure.. :-)

**Comment by Drew-E** [comment]
Yes, there are workarounds.  We could modify our document structure to use a list of objects with a single property.  We can use the Cosmos SDK instead of EF Core.  But really, this is such a basic feature that it should be supported by EF Core.

Why such a low priority on supporting this?  Are there not enough people that require it?  Is the effort too large?  Is every backlog item ahead of this one really a higher priority?  A little transparency would be great.

**Comment by AndriySvyryd** [comment]
You can read about our [planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning#the-planning-process), based on it we came up with the following [plan](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/plan). It does have **Cosmos database provider** in it, but the details haven't been decided as it depends on the progress of other features in the plan. As soon as the team members that can work on Cosmos finish their assigned committed features we will update the plan.
