### ISSUE TITLE
unit test cases to test methods containing EntryFrameworkCore Attach method 

### ISSUE THREAD

**Issue by NidhiNagarro** [dotnet/efcore#14777]
I have an update method which updates an entity. As my controller already fetched the item from DB, I was attaching my entity with DBContext

```C#
using (var dbContext = _dbProvider())
{
                dbContext.Attach(message);               
                message.IsRead = true;                
                await dbContext.SaveChangesAsync();
}
```

This works fine with the Sqlserver provider.

In my unit test cases, I tried to test this using InMemory Provider.
1. First my InMemoryDBContext fetches entity
2. Then sends an update for that entity.

But I get error

The instance of entity type 'Message' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
 

### Steps to reproduce
1. First my InMemoryDBContext fetches entity
2. Then sends an update for that entity.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

### Further technical details
EF Core version: 2.1.4.0
Microsoft.EntityFrameworkCore.InMemory: 2.1.2.0

**Comment by ajcvickers** [comment]
@NidhiNagarro Almost certainly this is because the same context instance is being used to Add and SaveChanges the entity initially as is being used later for the Attach. Try using a different context instance for each part, which matches how things would be in a typical web application.

If this isn't the root cause, then please comment with a small, runnable project/solution that demonstrates the behavior you are seeing, and we will re-open and investigate.

**Comment by NidhiNagarro** [comment]
[SampleAttachProblem.zip](https://github.com/aspnet/EntityFrameworkCore/files/2896526/SampleAttachProblem.zip)

**Comment by ajcvickers** [comment]
@NidhiNagarro The code posted uses the same context instance in both places.
