### ISSUE TITLE
SQLite shared in memory does not destroy the database when all connections are closed

### ISSUE THREAD

**Issue by norcino** [dotnet/efcore#14784]
I am working to create an integration test framework that allow my to create idempotent tests.
The idea is to create for each test initialization a _WebHostBuilder_ to hose a WebAPI, within using the Environment setting I use the connection string: _DataSource='file::memory:?cache=shared'_, and the same connection string is used on the test to create a context used by multiple "persisters".
Persisters are responsible to create the required base data, and then the tests invoke the API, and using the context I can verify that entities have been created, updated or deleted.

Everything work perfectly if I run all tests individually but I have failures when tests are executed not in parallel, but together.

The reason for the failure is that SQLite is not destroying the database when all connections are closed, and given that I am disposing carefully of every context, it looks like this behavior is not respected.
At least according with https://www.sqlite.org/inmemorydb.html I expect:

> The database is automatically deleted and memory is reclaimed when the last connection to the database closes

I use:
Microsoft.Data.Sqlite v2.2.0
Microsoft.EntityFrameworkCore v2.2.0

Below I show an helper method used to setup the IoC used by both API and Integration tests.
The context is static but this should not be relevant.

```C#
public static void RegisterContext(IServiceCollection services, string connectionString, IHostingEnvironment hostingEnvironment)
{
	if (connectionString == null)
		throw new ArgumentNullException(nameof(connectionString));
	if (services == null)
		throw new ArgumentNullException(nameof(services));

	services.AddDbContextPool<DBContext>(options =>
	{
		// If no hosting environment is provided or is specified testing
		if (hostingEnvironment == null || hostingEnvironment.IsTesting())
		{
			if (string.IsNullOrEmpty(connectionString))
			{
				// When there is no connection string, for testing will be used an in memory SQLite database                        
				//var connection = new SqliteConnection($"DataSource='file:test-db?mode=memory&cache=shared'");
				var connection = new SqliteConnection("DataSource='file::memory:?cache=shared'");
				connection.Open();
				options.UseSqlite(connection);
			}
			else
			{
				// If a connection string is provided, a real testing database is provided
				options.UseSqlServer(connectionString);
			}
		}
		else
		{
			// Production setup using SQL Server
			options.UseSqlServer(connectionString);
			options.UseLoggerFactory(MyLoggerFactory);
		}
	}, poolSize: 5);

	if (hostingEnvironment == null || hostingEnvironment.IsTesting())
	{
		services.AddSingleton<IDBContext>(service =>
		{
			var context = services.BuildServiceProvider().GetService<DBContext>();                    
			context.Database.EnsureCreated();
			return context;
		});  
	}
	else
	{
		services.AddTransient<IDBContext>(service => services.BuildServiceProvider().GetService<DBContext>());
	}
}
```

If this is not a but it means that for some reason when the next test is initialised, some connection is still open since the previous execution, but I disposed every context I used, or application.
Is there anything I can try?

**Comment by norcino** [comment]
I tried to use **Context.Database.EnsureDeleted()** at the end of each test, it returns **true** but the data is never reset and at each test I can see the data generated in the previous tests.

**Comment by ajcvickers** [comment]
@norcino This code leaks an open SQLite connection:
```C#
var connection = new SqliteConnection("DataSource='file::memory:?cache=shared'");
				connection.Open();
				options.UseSqlite(connection);
```
EF will not close it because it was passed in open. EF will also not dispose it because it was not created by EF. 

[The docs on testing with SQLite](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite) have an example of doing SQLite in-memory connection. Notice that opening/closing and disposal are handled to ensure the open connection does not leak.

**Comment by norcino** [comment]
@ajcvickers Thank you for the information, this misplaces me, I read the docs you linked, but in my case, in the Integration Tests (E2E) I create a WebHost to host the WebAPI and I initialize it passing custom settings. The problem is that I cannot control the lifecyle of the SQLite connection(s).
Below the code I use to create server and client, after each test I dispose both, and I was assuming (wrongly) that the shutdown was going to close and dispose the connections.

```
        public TestServerApiClient()
        {            
            var webHostBuilder = new WebHostBuilder();
            webHostBuilder.UseEnvironment("Test");
            webHostBuilder.UseStartup<Startup>();
            
            _server = new TestServer(webHostBuilder);            
            _client = _server.CreateClient();
        }

Do you have any suggestion about how to setup the dependency injection to manage the connection lifecyle? (So open and close the connections when needed, like it is done when using the SQL Server provider)

Now I use: 
```
        public static void RegisterContext(IServiceCollection services, string connectionString, IHostingEnvironment hostingEnvironment)
        {
            services.AddDbContextPool<HouseKeeperContext>(options =>
            {
                // If no hosting environment is provided or is specified testing
                if (hostingEnvironment == null || hostingEnvironment.IsTesting())
                {
                    if (string.IsNullOrEmpty(connectionString))
                    {
                        // When there is no connection string, for testing will be used an in memory SQLite database    
                        options.UseSqlite($"DataSource='file::memory:?cache=shared'");
                    }
                    else
                    {
                        // If a connection string is provided, a real testing database is provided
                        options.UseSqlServer(connectionString);
                    }
                }
                else
                {
                    // Production setup using SQL Server
                    options.UseSqlServer(connectionString);
                    options.UseLoggerFactory(MyLoggerFactory);
                }
            }, poolSize: 5);

            if (hostingEnvironment == null || hostingEnvironment.IsTesting())
            {
                services.AddTransient<IDBContext>(service =>
                {
                    var context = services.BuildServiceProvider().GetService<HouseKeeperContext>();
                    context.Database.OpenConnection();
                    context.Database.EnsureCreated();
                    context.Database.CloseConnection(); // Closing it here the API won't be able to use the connection
                    return context;
                });  
            }
            else
            {
                services.AddTransient<IDBContext>(service => 
                    services.BuildServiceProvider()
                    .GetService<DBContext>());
            }
        }

When I use services.AddTransient<IDBContext>(service => ... after ensuring the creation of the database I close the connection but doin so the api stack when using the context, doesn't open the connection automatically.

**Comment by ajcvickers** [comment]
@norcino There is no difference in behavior here between SQL Server and SQLite, or indeed any other provider. For all providers:
* If the application creates the DbConnection object, then the application is responsible for disposing it
* If the application passes an open connection to EF, then EF won't close the connection. The application must make sure the connection is closed.

Conversely:
* If the application passes a connection string to EF, then EF will create the DbConnection object and ensure it is disposed when the DbContext is disposed.
* If the application passes a closed connection to EF, then EF will open and close the connection as needed.

Now, when SQLite is used for in-memory testing, then it has a restriction that database will only stay around while there is an open connection to it. This means that something special has to be done to use this for testing since it requires a connection remain open in the test application when it does not need to in the real application. There are a few ways to handle this:
* Don't use the in-memory database. Thousands of tests can run in seconds against an on-disk database with modern hardware.
* Create and keep some connection open to the SQLite database purely as part of the test code, and then pass a connection string to EF as normal. As long as the test keeps the connection open while running there should not need to be any special handling in EF.
* Do something in D.I. and in your application to manage the lifetime of the connection. I can show examples of this if you need, but since it involves changing what your DbContext looks like and how its registered in D.I. just to enable SQLite in-memory testing, it doesn't seem like the best way to go.

**Comment by norcino** [comment]
@ajcvickers thank you very much, yes I did not understand how the connections were handled, what was misleading me was the "EnsureCreated" which was failing if I was not opening the connection.
But anyway I was really doing wrong many things, I changed the lifecycle of the connection setting it singleton.
To give you a bit of context (if interested) check https://stackoverflow.com/a/54858071/2482439, there is also the final version of the code I used.
