### ISSUE TITLE
Add-Migration unable to link scripts with UNC path

### ISSUE THREAD

**Issue by JagdCrab** [dotnet/efcore#14781]
When running Add-Migration for the project located on a network folder, migration fails with following error:
```
Add-Migration : Cannot add the link because the source file '\\\\Network Share\Folder\Solution\Project\Migrations\00000000000000_Create.cs' cannot be found.
At line:1 char:1
+ Add-Migration Create
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Add-Migration], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Add-Migration
```
So, it seems that problem is in two extra backslashes in UNC address that Add-Migration is trying to use

> \\\\\\\\Network Share\Folder

 rather then 

> \\\\Network Share\Folder

Files are actually created and can be found in network folder, but not added to project. 
If generated files manually added to Project though Add.. - Existing Item and then Update-Database executed - Migration completes successfully.
If Project is open from same location but with Mapped Network Drive rather then UNC - it works fine.

VisualStudio 2017 15.9.7
.Net 4.6.1
EFC 2.2.2.0

**Comment by Psypher9** [comment]
My cursory look over this seems to suggest that [the calls to the EnvDTE here](https://github.com/aspnet/EntityFrameworkCore/blob/f7758ea6da3f642e9a6ae9b5de8765ed2e5663ea/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L69-L76) would be throwing this exception.

Is this possibly happening because of this:
```csharp
        public static string Literal(string text)
            => text != null
                ? "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\""
                : "null";
```

in [ef/Json.cs#L14-L17](https://github.com/aspnet/EntityFrameworkCore/blob/e337283acd5e709b31730fd9eb7ff9857dcb7366/src/ef/Json.cs#L14-L17)? I can see that we are trying to espcape the backslashes for JSON, so if we need to keep this, perhaps at [this location in the PMC](https://github.com/aspnet/EntityFrameworkCore/blob/f7758ea6da3f642e9a6ae9b5de8765ed2e5663ea/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L69-L76) we could double-check the filename to make sure that it doesn't have double-double backslashes?

Otherwise, I think we can make the check [here](https://github.com/aspnet/EntityFrameworkCore/blob/e337283acd5e709b31730fd9eb7ff9857dcb7366/src/ef/Commands/MigrationsAddCommand.cs#L37-L45). Thoughts?

**Comment by Psypher9** [comment]
I've got an idea that doesn't require most of what I said before. I'm testing it now. @bricelam am I good to open a PR once I've validated the changes?

**Comment by bricelam** [comment]
Always feel free to submit PRs!

**Comment by ajcvickers** [comment]
We can no longer reproduce this and believe that the underlying issue has been fixed. If you are still hitting this issue with EF Core 5.0 or later, then please file a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
