### ISSUE TITLE
Why the Projection_containing_DateTime_subtraction test does not contain the subtraction in SQL?

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#14875]
Looking at the [`Projection_containing_DateTime_subtraction` test](https://github.com/aspnet/EntityFrameworkCore/blob/release/2.2/test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs#L616) and I'm wondering why the subtraction itself is not in the generated SQL?

**Comment by cincuranet** [comment]
Ah, looks like [SqlServerSqlTranslatingExpressionVisitor](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Query/ExpressionVisitors/Internal/SqlServerSqlTranslatingExpressionVisitor.cs#L19) is "handling" that. Am I correct?

**Comment by smitpatel** [comment]
SqlServer explicitly blocks math operations on datetime. While anything other than +/- is not possible, +/- have interesting signatures for `DateTime`
```C#
public static DateTime operator +(DateTime d, TimeSpan t);
public static TimeSpan operator -(DateTime d1, DateTime d2);
public static DateTime operator -(DateTime d, TimeSpan t);
```
In T-Sql, if you do `datetime - datetime` you get datetime back and not the timespan. Hence SqlServer does client eval. For subtraction over 2 datetimes, DateDiff functions can be used instead. (may be provider can implement exact using DateDiff function from clr operator overload but that is future enhancement).

The reason SqlServer blocks it and not relational, because PostgreSQL perfectly handles it. In PostgreSQL `datetime - datetime` gives back interval which maps to `TimeSpan`. cc: @roji

**Comment by cincuranet** [comment]
Thanks. I wasn't sure; maybe some deeper meaning. 

Firebird behaves the same and I'm already handling the TimeSpan, so I'm lucky here.

**Comment by roji** [comment]
@smitpatel yes, I remember us discussing this:

```sql
roji=# select pg_typeof('2018-01-05'::timestamp - '2018-01-04'::timestamp);
 pg_typeof
-----------
 interval
(1 row)
```

So everything works very well in PostgreSQL, no reason to have it blocked.
