### ISSUE TITLE
ModelBuilder question

### ISSUE THREAD

**Issue by aday12345** [dotnet/efcore#14926]
we are using 2.2 and for the time being we scaffolding it  and would like to keep it so we can regenerate it at anytime so we keep any model partial classes the we build in a separate folder.

The question I have is there anyway to add some additional models to the context after/before "protected override void OnModelCreating(ModelBuilder modelBuilder)" is run. We want to add some models for views without changing what was generated.

**Comment by ErikEJ** [comment]
EF Core Power Tools allows you to do that by generating a ModelCreatingPartial method.

**Comment by aday12345** [comment]
thanks, i will take a look

**Comment by ajcvickers** [comment]
@aday12345 For now, recommendation is to use the Power Tools. We're not going to make a change on EF at this time since it would make implementation of "Update from Database" (#831) much harder. However, customization of the scaffolding process (#4038) would make it easier to add such a partial method, although doing so could potentially still break "Update from Database" in a future release.
