### ISSUE TITLE
Ambiguity between Microsoft.Data.Entity.Migrations.DatabaseExtensions.AsMigrationsEnabled and Microsoft.Data.Entity.Infrastructure.Database

### ISSUE THREAD

**Issue by heathyates** [dotnet/efcore#1500]
See the error below: 

![ef7](https://cloud.githubusercontent.com/assets/1896424/5962700/3feb91e6-a7ab-11e4-8cf3-8b1279598231.PNG)

Steps to reproduce: 
0. I created a new ASP.NET template application using VS15CTP. 
1. project.json change  "EntityFramework.SqlServer": "7.0.0-beta2" to  "EntityFramework.SqlServer": "7.0.0-*"

**Comment by rowanmiller** [comment]
@heathyates if you are just changing EntityFramework.SqlServer to * then you are still going to be using the beta2 versions of the other packages. For our pre-release builds, you need to get a complete set of ASP.NET 5/EF7 packages from a single build. Changing everything to * is the easiest way to do this. BTW you would also need to make sure you get the latest version of the KRE as well.

**Comment by heathyates** [comment]
@rowanmiller This is a useful discussion for folks who may be having the same issue as me. You noted we need the complete set of ASP.NET 5/EF7 packages from a single build. You noted that * is the easiest way to do this. Also to make sure our KRE is updated. So I went and got the got the [mvcmusicstore](https://github.com/aspnet/MusicStore.git). I noticed that when I do all the above either for my own application, mvcstore, or the ASP.NET5 starter web it turns into [this](https://github.com/aspnet/MusicStore/issues/374#issuecomment-72529312). 

Honestly @rowanmiller , this is beyond the scope of EF7, but I would appreciate it if you could bring it to the attention of folks who might know what is going on here. This issue and the one at mvcstore are related (I didn't know that when I first posted above). I hope this benefits other folks reading this.

**Comment by rowanmiller** [comment]
Hey,

NuGet.org is where we publish our pre-releases that we have verified work together etc. So if you stick with NuGet.org and the KRE that comes with Visual Studio pre-releases then everything should work. These releases align with the 'release' branch in each of our repos.

If you want to start using nightly builds then you are opting into a world where we do not guarantee everything will always work together. This is the world we work in while developing and changes in various products can break others. We also aren't going to invest a lot of time helping folks out in this world since you are opting into the bleeding edge. It's also very important to understand that this isn't how we expect folks developing application with EF/ASP.NET to get and use our products, so the experience can be complex and you'll be mucking around with changing package sources, etc.

You need KVM from here and will periodically need to run `kvm upgrade` to get the latest KRE - https://github.com/aspnet/home/tree/dev
The package from our CI build are published here - https://www.myget.org/F/aspnetvnext/api/v2/ 

~Rowan

**Comment by heathyates** [comment]
@rowanmiller Thank you for your generous and kind response. I feel I've been a babe when it comes to this new framework and approach by Microsoft, but ready for more solid food. Your team has inspired me to be a better developer, contributor, and learner. I will do my best to find opportunities to pay it forward.
