### ISSUE TITLE
Update handling of non-nullable store-generated properties

### ISSUE THREAD

**Issue by JakePorter05** [dotnet/efcore#15070]
If you make the default value of an enum that is mapped to the database anything other then 0 it always defaults every value saved to the default value. 

Example with code: If I do default sleeping and try to set it to active and save. It will change it back to sleeping in the savechanges. But if you leave the default at 0 aka active then you can change and save as normal.

[EfcoreEnumTester.zip](https://github.com/aspnet/EntityFrameworkCore/files/2980805/EfcoreEnumTester.zip)

``` c#
public partial class Person
{
   [Key, Column(TypeName = "uniqueidentifier")]
   public Guid Id { get; set; }
   [Column(TypeName = "nvarchar(20)")]
   public string FirstName { get; set; }
   [Column(TypeName = "nvarchar(20)")]
   public string LastName { get; set; }
   [Column(TypeName = "int")]
   public State State { get; set; }
 }

public enum State
{
    Active = 0,
    Sleeping = 1,
}

modelBuilder.Entity<Person>(entity =>
{
    entity.HasIndex(e => e.Id);
    entity.Property(e => e.State)
              .HasConversion<int>()
              .HasDefaultValue(State.Sleeping);
 });
```

**Comment by ajcvickers** [comment]
Note for triage: related to #13613

**Comment by ajcvickers** [comment]
Note for triage: should our guidance here be to do this:
```C#
public partial class Person
{
   public State State { get; set; } = State.Sleeping;
}
```
This is basically what we decided to scaffold in #13613--although we don't reverse engineer to enums by default its still the same pattern. This works because a value will always be inserted, but if no value was explicitly set, then `Sleeping` will be inserted.

The property above should not have a call to `HasDefaultValue`, or if this is needed for Migrations, then the following would be needed:

```C#
modelBuilder.Entity<Person>(entity =>
{
    entity.Property(e => e.State)
        .ValueGeneratedNever()
        .HasDefaultValue(State.Sleeping);
});
```
Another option is to break to `HasDefaultValue` (and `HasDefaultValueSql`) such that it doesn't also set store-generated. But that would be a pretty impactful break.

Let's discuss. (Again. 🚎)

**Comment by ajcvickers** [comment]
## Notes for the design meeting

### Current behavior

Calling `HasDefaultValue` or `HasDefaultValueSql` does the following:
* Marks the property as ValueGenerated.OnAdd
* Sets the default value for use by migrations
* Setting both of these makes the property store-generated (as opposed to client-generated)

Making something a store-generated property means:
* If the property value is the CLR default, then don't include the value in the insert, and instead propagate back the store-generated value.
* If the property value is anything else, then include it in the insert.

This mechanism works well except when the CLR default is a valid value that needs to be inserted. For example, if the default for a bool column should be true, then setting the CLR default (false) will result in using the default of true, and so there is no way to end up with a value of false in the database.

In addition, the call to `HasDefaultValue` or `HasDefaultValueSql` might only be intended to set the value for Migrations.

### Options

Patterns that make this better, using as an example a bool with default true.

#### A: Use client-side defaults

We would scaffold:

```C#
public class Blog
{
    public bool IsValid { get; set; } = true;
}

```
and
```C#
    .HasDefaultValue(true)
    .ValueGeneratedNever();
```
(If we introduce a scaffolding mode which does not include all database artifacts, then we can skip this.)

When writing code manually, we would recommend just:
```C#
public class Blog
{
    public bool IsValid { get; set; } = true;
}
```
and no store-generated config unless you need Migrations to create the default in the database.

#### B: Use regular properties backed by nullable field

This approach would preserve all store-generated behavior at the expense of more code. Also, we need to make changes to EF to make this work, but they should not be complex.

Code is the same for both scaffolding and writing manually:
```C#
public class Blog
{
    private bool? _isValid;

    public bool IsValid
    {
        get => _isValid ?? false;
        set => _isValid = value;
    }
}
```
and
```C#
    .HasDefaultValue(true);
```
(There should be no need to set the property access mode since we read/write fields by default in 3.0.)

#### C: Use nullable properties

This preserves store generated behavior, but forces the type in the model to be nullable.

```C#
public class Blog
{
    public bool? IsValid { get; set; };
}
```
and
```C#
    .HasDefaultValue(true);
```

### Proposal

For reverse engineering:
* If the default value can be parsed into a CLR object, then use pattern A
* Otherwise use pattern B (with `HasDefaultValueSql`)

To document/recommend for "Code First":
* Show how to do pattern A for when client-side defaults are the best option
* Show how to do pattern B for when store defaults must be used
* Mention pattern C to simplify code where the model property can be nullable

**Comment by ajcvickers** [comment]
Notes from design meeting:
* Make B (nullable field) work (see #15182)
* Consider expanding warning for bools to also be used for enums (this issue)
* For hand-written code document: (see https://github.com/aspnet/EntityFramework.Docs/issues/1398)
  * Use client side default values. This ensures the defaults are consistent in the domain model.
  * Show how store-generated values work in the "normal" case--e.g. with integers
  * Show how to use option B for when both the normal way and client-side defaults are not appropriate, also mentioning C
  * Show how to get the default value into the migration if it needs to be there
* For scaffolding: (see #13613)
  * We currently only do C for bools with a default of true. We could consider doing B here, but this could be punted to post 3.0.
  * For other cases, just keep doing what we are doing.
* Use of a different sentinel value could be useful here if it is set to the same as the default value. (See #701)
  * This would mean that if the value is set to default, then it would not be inserted, since this value is the same as the sentinel. But it would get the default value from the database as expected.
  * However, this would be a breaking change since it would insert the CLR default rather than using the default from the database
  * We could even consider automatically making the default value the same as the sentinel value if it has been set.
