### ISSUE TITLE
Updating entry with attach approach is not working if new value of property is null

### ISSUE THREAD

**Issue by m-demydiuk** [dotnet/efcore#15117]
To update db entry I want to use attach approach to avoid fetching entry from the db.
Like described here https://gist.github.com/tombowers/6f99eb132cfec185b951#file-update-without-select-cs

All works well besides the case when the new field value is null. See the example below.

### Steps to reproduce
Assume we have a db entity
```c#
public class School
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

In the db, we already have an entry of School with Id = 1 and Name = "School Name"

In next case, update works as expected
```c#
...
var schoolToUpdate = new School {
    Id = 1
};
_dbContext.Attach(schoolToUpdate);
schoolToUpdate.Name = "New School Name";
await _dbContext.SaveChangesAsync();
...
```

But, if new school name is null, it is not updating the db, because original value is also null and IsModified flag is not changed to true. (School.Name in the db is not null)
```c#
...
var schoolToUpdate = new School {
    Id = 1
};
_dbContext.Attach(schoolToUpdate);
schoolToUpdate.Name = null;
await _dbContext.SaveChangesAsync();
...
```

Is it a bug, or is it by design? Do you have any suggestions on how to make it works? 
Mark field manually as modified will not work because we have about 20 fields and it will uglify our code. So now we use AutoMapper null substitute approach and setting string.Empty if the value is null:
```c#
cfg.CreateMap<SchoolEditModel, School>()
                    .ForMember(dest => dest.Name, opts => opts.NullSubstitute(string.Empty));
```

In this case OriginalValue is null but NewValue is "" and IsModified flag is true; But it results to "" in the db instead null.

### Further technical details
EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.7

**Comment by ajcvickers** [comment]
@m-demydiuk Indeed, this approach is a definite anti-pattern and should never be used.

To elaborate. The fundamental decision point here is whether you want to use partial updates (that is, only sending updates for properties where the value has actually changed) or always send updates for all properties in the entity. Of course, partial updates sounds better, but it is predicated on being able to _know what has changed_. Otherwise how can you know what updates to send? This is where the pattern above falls down--it basically makes the assumption that all the original values were null, and any update will be from null to non-null, and never non-null to null. This is clearly a false assumption in general.

So, what to do? The easiest thing is to not do partial updates. That is, have all the correct values in the entity instance and then call `Update` and `SaveChanges`.

To retain partial updates, either:
* If you know statically which properties have changed, then Attach the entity and then explicitly set those properties as modified using something like `context.Entry(foo).Property(e => e.Bar).IsMdified = true`.
* Make sure the original values of the entity are maintained so that it can be attached with all the correct values. This usually means sending them to and from the client.
* Query for the entity (e.g. using `DbSet.Find`) so that it is populated with the values already in the database before making updates to it.
