### ISSUE TITLE
Migrations: Additions to the model should be before removals

### ISSUE THREAD

**Issue by yepeekai** [dotnet/efcore#15179]
When doing model refactoring, we need to translate the old data to the new model.  To achieve that, it is important that new tables and columns are added before the old ones are dropped to give an opportunity window to migrate the data.  EF6 was working that way but EF core is dropping everything before adding the new stuff.  It is possible to move things around in the migration to achieve data correction but I think it would be useful that it is correctly positioned by default.

**Comment by ajcvickers** [comment]
@yepeekai This was specifically changed in EF Core to be more robust since people would frequently run into conflicts between the old and the new when taking the EF6 approach. Therefore we don't plan to change this, even though it can make things more difficult for data motions. Data motions are not super-common and require work in the migration anyway, so having to change the order for this is a better compromise than changing what we do by default and having common cases hit issues.
