### ISSUE TITLE
Lazy loading using proxies does not seem to work (SQLite)

### ISSUE THREAD

**Issue by leaditnet** [dotnet/efcore#15218]
when using lazy loading I expect the child navigation properties not loaded
The current behaviour: I cannot avoid the children being loaded and causing circular reference when serialized

DB Context:

```C#
 public class SampleDbContext : DbContext
    {
        public SampleDbContext(DbContextOptions<SampleDbContext> options)
              : base(options)
        {

        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLazyLoadingProxies();
        }
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Child> Children { get; set; }


    }

```
Models:

```C#
public class Child
    {
        public int Id { get; set; }
        [ForeignKey("Parent")]
        public int ParentId { get; set; }

        public string Name { get; set; }
        public virtual Parent parent { get; set; }
    }


  public class Parent
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public virtual ICollection<Child> children { get; set; }
    }
```

Startup:

```C#
 services.AddDbContext<Models.SampleDbContext>(options =>options.UseLazyLoadingProxies().UseSqlite(Configuration.GetConnectionString("DefaultConnection"));
```            

Controller:
 
 ```C#
 [HttpGet]
        public async Task<List<Models.Parent>> Get()
        {
            var sample = _cont.Parents.ToList();
            return sample;
        }
```

EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 2.2.1
Operating system: Win 10
IDE: Visual Studio 2017

**Comment by divega** [comment]
EF Triage: This is the expected behavior with lazy loading enabled if serialization happens while request is being processed (i.e. while DbContext is still in scope). 

EF Core proxies does not know the difference between user code and serialization code when navigation properties are accessed, so lazy loading is triggered nonetheless. 

There are several alternatives to avoid the extra payload:

- Project the exact data you want in the serialization payload into DTO/ViewModel objects
- Annotate navigation properties with "ignore" attributes to suppress serialization
- Avoid enabling lazy loading in your application
- Disable lazy loading explicitly before returning entities from the controller method
