### ISSUE TITLE
Support EF-specific interfaces for notification change tracking

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#15242]
Suggesting that EF define it's own copies of notification interfaces, say EntityFrameworkCore.INotifyCollectionChanged, EntityFrameworkCore.IPropertyChanged. and EntityFrameworkCore.INotifyPropertyChanging. If an entity implements these then notification change tracking is enabled and EF uses them for notification tracking. This would be a non-breaking change. 

Following are two challenges with notification change tracking that would be nicely solved by this approach.

1. Say we would like to implement a concurrent data structure, such as a tree, that is stored in the database. We want to lock changes to the structure using a normal synchronous signature and a lock such as SemaphoreSlim.Wait. We must notify changes outside of the lock, because running user event code from inside the lock is a recipe for deadlock. But when we notify the changes outside of the lock, EF's relationship fix-up kicks in and EF then makes additional changes to the data structure, such as adding children due to change of a parent pointer. Those EF-initiated collection changes then run outside the lock, even though we need these data structure changes to occur within the lock. With the proposed approach we could notify EF from within the lock and notify users from outside the lock. 

2. Say we have a tree structure that is implemented using entities with notification change tracking, and we are using these entities in the ItemsSource of a UWP TreeView. This means that instances of the entity are stored in TreeViewNode.Content. Now, we drag and drop a node in the TreeView and want to update the entity tree structure accordingly. To do so, we must disable collection change notification. If change notifications were enabled, then since the entities are bound as the ItemsSource, the TreeView would detect the changes and attempt to update itself to match -- causing havoc since at this point we are trying to change the entity tree structure to match the dragged TreeViewNodes structure, not vice versa. However, when we disable collection change notifications in the entity tree structure, it interferes with EF's notification change tracking. Specifically it means that EF cannot detect changes to the collections and fix-up the corresponding principle entity navigations and foreign keys. We then have to be careful to only manipulate the entity tree structure using principal entity navigations, rather than the navigation collections. With the proposed approach we could disable collection changed for the TreeView while leaving collection changed in place for EF.

**Comment by ajcvickers** [comment]
@divega to follow up.

**Comment by divega** [comment]
@sjb-sjb thanks for sharing the details of these scenarios. We discussed your feature request in triage today. Given that we haven't received any similar requests in the past, and that adding EF Core-specific change tracking interfaces would add significant complexity, we currently don't think we should do this, at least until we get more evidence that this is widely required and that there aren't reasonable workarounds. 

Here are a few alternative approaches I believe customers can take to address a scenario similar to yours:

1. Avoid notification-based change tracking: You can still implement the interfaces for the purpose of binding your entity types to your UI, and implement the same logic you described to lock the graph or disable change notifications in its collections. If you don't explicitly enable notification change tracking in EF Core (e.g. you don't call HasChangeTrackingStrategy) then you can rely on automatic snapshot change tracking to discover any changes in the graph of objects any time it is needed, or even explicitly invoke change tracking APIs such as DetectChanges, or setting current values explicitly on entity entries. 

2. Using the [model–view–viewmodel pattern](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel) (or similar) to separate the two layers: You can use notification entities in the EF Core model, but use separate types to binding to the UI. The view model types can either wrap the data classes or there can be an adapter between them.

**Comment by sjb-sjb** [comment]
@divega thanks for your thoughtful comments. 

I agree there's always a way to work around things. All of the workarounds require a similar amount of work to solve the same underlying problem. I think that the examples I gave do identify concrete challenges. Obviously it's up to you whether these should be addressed in EF or not. I am not arguing against the triage decision: based on the great quality of EF it is clear that you're doing a great job on design!

The conflicting demands between multiple uses of collection and property change notifications could be viewed as a system-wide challenge rather than only an EF question. 

Noting I am already using MVVM. I happen to be driving my View Model updates off of the Model notifications; but even if I were not, the same problem (2 in my post) would occur. I would have to suspend my VM collection change notifications for the same reason. The difference would be that this workaround would be more decoupled from EF.

**Comment by sjb-sjb** [comment]
I guess that a work-around to (1) might be to predict all of the changes that EF would make (such as adding children, in the example) and execute them in advance within the lock.

**Comment by divega** [comment]
I am catching up with old issues assigned to me, and I think I am ready to either close this discussion (since we don't have plans to implement the original feature request for now, but we can always revisit this decision in presence of new data) or move it to the backlog with the following idea:

We could abstract a bit more how we bind to the events from the INotifyPropertyChang* interfaces to allow advanced users to provide their own interfaces and their own binding logic. I haven't fully investigated this, but here are a few steps that I believe would be required:

1. The user would need to somehow replace a state management service, IInternalEntityEntrySubscriber (currently internal) to implement subscription an un-subscription for the events in their custom interfaces.

2. Something on the InternalEntityEntry needs to carry the actual event handlers. Currently we have InternalEntityEntry.HandleINotifyPropertyChang* which watch the shape of the event handlers from the INPC interfaces. If the events on the custom interface happen to take the same parameter types (object sender and object sender, PropertyChangingEventArgs eventArgs) then you shouldn't need any changes. These handlers in turn invoke the mehtods on IInternalEntityEntryNotifier, but at this point the code is agnostic of the interfaces.

3. In places like https://github.com/aspnet/EntityFrameworkCore/blob/fc69488be0a725530bd213d41d8b086e8c013018/src/EFCore/Metadata/Internal/EntityType.cs#L2426-L2445, we validate that the actual INotifyPropertyChang* interfaces are implemented by entities. We could allow that to be overridden too. 

All in all, for someone that implements both the standard INotifyPropertyChange* interfaces and custom ones, they can probably get away with just doing (1), but this requires replacing an internal service.

**Comment by sjb-sjb** [comment]
Hi Diego 

I don't think it needs to be so complex. At the places noted in (3) where EF currently tests for INotifyPropertyChang*, it could simply test to see whether a specific alternative interface defined by EF is implemented, say INotifyEfPropertyChang*. If the EF version is implemented then EF would subscribe to that, otherwise it would use the normal interface. 

Steve

**Comment by ajcvickers** [comment]
Note from triage: closing this based on Diego's analysis since this is something we are very unlikely to implement.
