### ISSUE TITLE
[Feature] PropertyBuilder<TProperty> HasDefaultValue<TProperty> should use TProperty as type for parameter value

### ISSUE THREAD

**Issue by Dabbel** [dotnet/efcore#15322]
Why is value an object in method PropertyBuilder<TProperty>.HasDefaultValue<TProperty> and not TProperty? This would make the method typesafe

**Comment by ajcvickers** [comment]
@Dabbel We remember that there was a reason for this when we originally created the API, but we don't 100% remember the reason now. It might have been because we wanted allow null to be set for any property to indicate no default value. Regardless, after some discussion we've decided not to change this at this time. It might have some value, but it would also be a breaking change, and we don't believe any additional value would be worth it.
