### ISSUE TITLE
Query: groupjoin projecting and composing on grouping (not flattening) doesn't get translated

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#15412]
Example:

```
from l1 in ctx.LevelOne
join l2 in ctx.LevelTwo.Where(x => x.OneToOne_Optional_FK2.Name != "Foo") on l1.Id equals l2.Level1_Optional_Id into grouping
from l2 in grouping.DefaultIfEmpty()
select new { l1, l2, grouping };
```

**Comment by divega** [comment]
Note from triage: @smitpatel to write down an explanation of why we don't support this.

**Comment by smitpatel** [comment]
Since a "group" (coming out of `GroupJoin` or `GroupBy`) cannot be represented in SQL. Above query has to do client eval after GroupJoin (which has `SelectMany` with `DefaultIfEmpty`). As we don't support client eval going forward, above query cannot be translated to server fully. We will throw exception. Using `AsEnumerable` will allow the query to generate groupings in EF and then do rest of processing on client side outside of EF.
