### ISSUE TITLE
Getting the original values from a navigation collection property

### ISSUE THREAD

**Issue by alexandrejobin** [dotnet/efcore#15422]
I need to log the diff of my entity before it get updated to the database. To do so, i'm using the CurrentValue and the OriginalValue properties for the EntityEntry and the ReferenceEntry but it doesn't exist for the CollectionEntry.

How can I get the original and the current collection object for my navigation properties? For example, a Book can have many Authors. How can I know what was the authors attached to my collection before the change?

```
var entries = ChangeTracker.Entries<Book>()
                           .Where(x => x.State == EntityState.Modified)
                           .ToList();
				
foreach (var entry in entries)
{	
   // read the entity current & original values	
   var currentTitleValue = entry.Property(x => x.Title).CurrentValue;
   var originalTitleValue = entry.Property(x => x.Title).OriginalValue;
   
   // read the reference object current & original values
   var promotionReferenceEntry = entry.Reference(x => x.Promotion);
   var currentPromotionPriceValue = promotionReferenceEntry.TargetEntry.Property(x => x.Price).CurrentValue;
   var originalPromotionPriceValue = promotionReferenceEntry.TargetEntry.Property(x => x.Price).OriginalValue;
   
   // read the navigation object current & original values
   var authorsCollectionEntry = entry.Collection(x => x.AuthorBooks);
   var currentAuthorIds = authorsCollectionEntry.CurrentValue.Select(x => x.AuthorId).ToList();
   var originalAuthorIds = ?????;
}
```

EF Core version: 2.2.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@alexandrejobin Original values only apply to properties that are directly mapped to columns in the database. Navigation properties are instead a kind of view over the FK properties, for which original values are available. However, detecting changes in navigation properties of entities that are not tracked requires more than this because entities can be added and removed. This is discussed in more detail under [disconnected entities](https://docs.microsoft.com/ef/core/saving/disconnected-entities) in the documentation.
