### ISSUE TITLE
Suboptimal SQL generated on Left Join

### ISSUE THREAD

**Issue by zeeshanzahoor** [dotnet/efcore#15437]
### Left join generates suboptimal query when more then two entities are used in a query.

When I use left join with two entities it works fine but when I include third entity in the query It devides SQL in two portions. The first retrieves the whole table and the second does the left join. It also discard any filter associated with the query. 

### LINQ Query

```c#
void Main()
{
	var rep = new Repository();
	
	var q = from entity in rep.All<Entity>()
		    join attr in rep.All<EntityAttribute>() on entity.Id equals attr.EntityId into et
		    join mod in rep.All<ModuleDefinition>() on entity.ModuleSubmoduleId equals mod.Id
		    where mod.Id  < 20000
		    select new { entity, et , mod};
			  
	var r = q.ToList();

}
```

### Generated SQL
```SQL
SELECT [mod].[ID], [mod].[CONNECTION_DEFINITION_ID], [mod].[DESCRIPTION], [mod].[INSERT_TIME], [mod].[INSERT_USER_ID], [mod].[IS_ACTIVE], [mod].[IS_INTERNAL], [mod].[NAME], [mod].[ROW_VERSION], [mod].[TFS_PATH], [mod].[TYPE_ID], [mod].[UPDATE_TIME], [mod].[UPDATE_USER_ID]
FROM [dbo].[MODULE_DEFINITION] AS [mod]
GO

SELECT [entity].[ID], [entity].[DESCRIPTION], [entity].[INSERT_TIME], [entity].[INSERT_USER_ID], [entity].[IS_AUDITABLE], [entity].[IS_SYSTEM_TABLE], [entity].[MODULE_SUBMODULE_ID], [entity].[NAME], [entity].[ROW_VERSION], [entity].[UPDATE_TIME], [entity].[UPDATE_USER_ID], [attr].[ID], [attr].[DATA_TYPE_ID], [attr].[DESCRIPTION], [attr].[ENTITY_ID], [attr].[HAS_TRANSLATION], [attr].[INSERT_TIME], [attr].[INSERT_USER_ID], [attr].[IS_NULLABLE], [attr].[NAME], [attr].[ROW_VERSION], [attr].[UPDATE_TIME], [attr].[UPDATE_USER_ID]
FROM [dbo].[ENTITY] AS [entity]
LEFT JOIN [dbo].[ENTITY_ATTRIBUTE] AS [attr] ON [entity].[ID] = [attr].[ENTITY_ID]
ORDER BY [entity].[ID]
GO
```

EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows
IDE: e.g. Visual Studio 2017

**Comment by divega** [comment]
Note from triage: This query may not have a translation in SQL. @smitpatel to respond.

**Comment by smitpatel** [comment]
This query contains a non-flattened GroupJoin. Grouping cannot be represented in SQL. Hence we have to do client computation to generate Groups. If you apply any operator after producing group, it will also do client evaluation. Hence you get additional SQL which will get data to perform the join on client side.

The easy work-around would be to do GroupJoin last so that everything before that translates to server. In this case it is possible because your join is not using anything from Grouping (if it was using then there is no way other than client eval). You can move join before groupjoin and make it work on server side like this
```C#
var query = (from b in db.Blogs
                join bd in db.BlogDetails on b.BlogDetailId equals bd.Id
                join p in db.Posts on b.Id equals p.BlogId into ps
                where bd.Id < 2000
                select new { b, ps, bd }).ToList();
```
SQL
```SQL
      SELECT [b].[Id], [b].[BlogDetailId], [bd].[Id], [p].[Id], [p].[BlogId]
      FROM [Blogs] AS [b]
      INNER JOIN [BlogDetails] AS [bd] ON [b].[BlogDetailId] = [bd].[Id]
      LEFT JOIN [Posts] AS [p] ON [b].[Id] = [p].[BlogId]
      WHERE [bd].[Id] < 2000
      ORDER BY [b].[Id]
```

**Comment by cinarab** [comment]
dear smitpapel,
we are using efcore in a very key Project. this problem cannot be a by design problem. we are not talking about groups. I think there is a misunderstanding here.
Our problem is just fecthing related entity datas by using left join. If we use one related entity in our linq, efcore creates left join successfully but when we add one more join relation for another left join related entity in our linq, it starts to generate seperate non-filtered/full-select query for each entity. In our case this query generation approach is unacceptable. Every entity/table will hold millions of records. so fetching all entities without filtering and then joinin these entities in application memory is not acceptable. there should be a way to generate SQL Left join statements when there is more than two entity relations in linq statements.

**Comment by smitpatel** [comment]
When you write this `join mod in rep.All<ModuleDefinition>() on entity.ModuleSubmoduleId equals mod.Id` in your query you have access to `et` group also. That is how LINQ works but that is not something SQL can process. That is the reason you can actually change order of joins to make this work otherwise, your query cannot be translated to server at all. If you are loading related data only then consider using Include instead. While we may generate similar query for Include but we are certain that we are not using groups anywhere other than top level select. But for the query you are writing it is not possible to figure that out in expression tree without doing complex analysis which may still fail if group is being referenced.
Above query will throw in 3.0 pipeline so you will not end up with loading whole table accidently.
