### ISSUE TITLE
String interpolation with FromSql not correctly working

### ISSUE THREAD

**Issue by Bentivimon** [dotnet/efcore#15461]
Hi all.

I have a question about string interpolation with .FromSql method.
When I set string like this :
```
 notifications.FromSql($"SELECT * FROM notifications WHERE endpoint_entity_id = {endpointId} AND data -> 'feedId' = '{request.FeedId}'");
```
I have exception like this: 
```
22P02: invalid input syntax for type json
```
and database got this query:
```
SELECT * FROM notifications WHERE endpoint_entity_id = $1 AND data -> 'feedId' = '@p1'
```

When i set string like this:
```
 var query = $"SELECT * FROM notifications WHERE endpoint_entity_id = {endpointId} AND data -> 'feedId' = '{request.FeedId}'";
 var notificationQuery = notifications.FromSql(query);
```
database got this query:
```
SELECT * FROM notifications WHERE endpoint_entity_id = 1 AND data -> 'feedId' = '1435'
```
Maybe somebody know what a problem and can explain

**Comment by ajcvickers** [comment]
@Bentivimon What are you expectations as to what should happen in each case?

**Comment by Bentivimon** [comment]
@ajcvickers I think when we use string interpolation direct in .FromSql method and through a variable "query" result must be the same.

**Comment by ajcvickers** [comment]
@Bentivimon Unfortunately, the language feature doesn't work like that. See #10996 for a full discussion.

With regard to the parameterization error, this looks like a problem creating parameters for those placeholders. This could be because that SQL is not parameterizable in those places, or it could be because there is a bug trying to use it.  What version of EF Core and which database provider are you using?

**Comment by Bentivimon** [comment]
@ajcvickers Npgsql.EntityFrameworkCore.PostgreSQL version 2.1.1.1

**Comment by ajcvickers** [comment]
@roji Possible Npgsql EF provider issue?

**Comment by roji** [comment]
@Bentivimon can you please try removing the quotes around `{request.FeedId}`? The `{endpointId}` in your query is (correctly) unquoted, and gets properly transformed into a parameter.

**Comment by Bentivimon** [comment]
@roji I try this.

Code example:
```
var notificationQuery = notifications.FromSql($"SELECT * FROM notifications endpoint_entity_id = {endpointId} AND data -> 'feedId' = {request.FeedId}");
```

Postgres got this query:
```
SELECT * FROM notifications WHERE endpoint_entity_id = $1 AND data -> 'feedId' = $2
```

But, after query execution exception was thrown with message
```
42883: operator does not exist: jsonb = integer
```

**Comment by roji** [comment]
@Bentivimon that's better, but [see the PostgreSQL documentation](https://www.postgresql.org/docs/current/functions-json.html) about how to access elements inside a JSON type. The `->` operator returns a jsonb document (keep in mind that `data => 'feedId'` could be a complete sub-document). To extract that as a scalar number, replace `->` with `->>`.

**Comment by Bentivimon** [comment]
@roji 
This query 
```
var notificationQuery = notifications.FromSql($"SELECT * FROM notifications WHERE endpoint_entity_id = {endpointId} AND data => 'feedId' = {request.FeedId}");
```
Return this
```
 42601: syntax error at or near "=>"
```
And this query 
```
var notificationQuery = notifications.FromSql($"SELECT * FROM notifications WHERE endpoint_entity_id = {endpointId} AND data ->> 'feedId' = {request.FeedId}");
```
Return this
```
42883: operator does not exist: text = integer
```

**Comment by roji** [comment]
Sorry, the `=>` as a mistake (corrected above).

It would seem like your `data->>'feedId'` in your JSONB document is of type text, but you're comparing it to an integer (i.e. `request.FeedId`). PostgreSQL is very strict with typing, and it's your responsibility to make sure you providing the right types. First, double check what the types actually are in the database. If `data->>'feedId'` really is always a number, then consider converting your database data to reflect that (i.e. with an integer value instead of a text one). Otherwise you could send a string representation of `request.FeedId` which would probably work, but isn't advisable if the data really is always numeric.

Note that at this point I'm basically helping you write the correct PostgreSQL SQL for your database. This is OK (and you can continue asking questions) but doesn't really have anything to do with EF Core, so I'm going to go ahead and close this issue.
