### ISSUE TITLE
The type initializer for 'Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache' threw an exception

### ISSUE THREAD

**Issue by Coflys** [dotnet/efcore#15511]
windows server 2008 r2

Exception has been thrown by the target of an invocation.
The type initializer for 'Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache' threw an exception.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
 at System.Activator.CreateInstance[T]()

**Comment by jonasnordlund** [comment]
I got here via a web search as we just had the same problem. Ensure that all your NuGet package versions are up-to-date. The first install of Microsoft.EntityFrameworkCore and assorted related providers like Sqlite and PostgreSQL does surprisingly not come with in a functioning state for us, but after downloading the latest versions Visual Studio immediately wants us to update a large number of the dependencies even more. And after a first wave of updates, we have needed to close the NuGet Package Manager tab and re-open it, and even more updates are discovered as needed.

For us, I think the root cause of this particular one was that it needed the System.ValueTuple package (a dependency from Npgsql.EntityframeworkCore.PostgreSQL) to be no less than Version 4.5.0.

**Comment by a-einstein** [comment]
I have also been struggling a long time with errors about the version of System.ValueTuple, in the context of other changes.

I read that particular packages depends of the targeted frameworks.
Check this: [Could not load file or assembly System.ValueTuple](https://stackoverflow.com/questions/42867434/could-not-load-file-or-assembly-system-valuetuple)

For me solving turned out to be related to installed packages, dependencies, and version redirects.
Finding information about regeneration of the redirects finally helped me to sort it out.

Check this topic and my remark there:  [AutoGenerateBindingRedirects doesn't work for class libraries](https://github.com/dotnet/msbuild/issues/1310#issuecomment-926114457)
