### ISSUE TITLE
Add support built in Bulk Insert  

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/efcore#1556]
please add support built in bulk insert to Entity Framework that allow pass IEnumerable  with AddBulk method to easy use and improvement performance

**Comment by rowanmiller** [comment]
@mojtabakaviani - There is already an overload of Add that takes a collection of entities. It was an overload of `Add` but has just been renamed to `AddRange`. The entities are not immediately persisted, they are saved when `SaveChanges` is called, but we now have batching enabled in EF7... so you will get a single command sent to the database to insert all the data (obviously there may be more than one command depending on batch size, etc.).

**Comment by veeravendhans** [comment]
I have used AddRange this has a good performance when compared with EF6 AddorUpdate. At the same time when I add more records its slow down and not working: below is the stat. I have also created batch and tried inserting there was a increases in performance. but more then 50K its not working. In my case I am looking for at least to insert 50K+ one time insert. since the performance is not good I am going back to BulkInsert in EF6
Env	Records	Insert(sec)	Update(sec)	Delete(sec)
LocalDB	5K	7	6	1
LocalDB	10K	22	24	9
LocalDB	20K	48	100	48
LocalDB	30K	60	120	60
LocalDB	50K	180	300	120
LocalDB	0.5K	2	2	0.4
Azure	5K	120	240	54
Azure	10K	300	660	120
