### ISSUE TITLE
Are multiple linq where clauses in EF CORE SQLite supported?

### ISSUE THREAD

**Issue by lugospod** [dotnet/efcore#15742]
I tried to find an issue that references this question, and also tried to google it... it look like it is not supported..
`var x = context.MyEntitites.AsNoTracking().Where(z => z.Id % 2 == 1) ;
 x.Where(z => z.Id == 1);
 var result = x.ToList();`

The previous code doesn't add the ID == 1 to the query...it basically ignores all of the where statements after the first...
tnx!

**Comment by smitpatel** [comment]
When you do `x.Where(z => z.Id == 1)` it creates new expression tree but you are not storing it. You are using the old `x.ToList()` hence you are not seeing predicate because it is not in expression tree.
Whenever you chain anything on queryable you need to save that new queryable object to actually use it.
