### ISSUE TITLE
Supporting TableAttribute on properties

### ISSUE THREAD

**Issue by shravan2x** [dotnet/efcore#15746]
Currently, attempting to use EF's `[Table]` atrribute on a `DbSet` property complains with an error `Attribute 'Table' is not valid on this declaration type. It is only valid on 'class' declarations.`. I created this issue to ask whether it could be updated to work on properties as well, and if not, to understand why the decision was made. I was unable to find a satisfactory answer via a Google search.

I regularly reuse models across databases, tables, JSON serialization/deserialization, and even exposing via libraries. Keeping this in mind, it seems like a limitation to require TableAttributes to be set on the class definition itself, rather than when the model is used in a `DbSet`.

I would like to create a context like:
```cs
private class SomeDbContext : DbContext
{
    [Table("custom_tags")]
    public DbSet<CustomTag> CustomTags { get; set; }

    [Table("custom_props")]
    public DbSet<CustomTag> CustomProps { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite($"Data Source=some.db");
    }
}
```

Apart from this, it also seems ideologically incorrect to me to map a type to a table. Mapping properties in a model to columns makes sense since each property maps to exactly _one table cell_ (given that an instance of the class maps to _one row_). However, mapping types to tables makes less sense than mapping a _collection of a type_ to a table (i.e. a `DbSet`), since that's what a table is anyway.

**Comment by shravan2x** [comment]
It seems other users have also looked for a similar solution in the past:
https://github.com/aspnet/EntityFrameworkCore/issues/7299
https://github.com/aspnet/EntityFrameworkCore/issues/7418
https://github.com/aspnet/EntityFrameworkCore/issues/10272

**Comment by ajcvickers** [comment]
@shravan2x Allowing `[Table]` on a `DbSet` property is certainly an interesting idea. However, it's quite a deviation from how the attribute was intended to be used, and would be an outlier in behavior if this was allowed. Also, `TableAttribute` is not defined by EF Core, but instead comes from the `Microsoft.ComponentModel.Annotations` package. There is a pretty high bar for making changes to those types since they are so widely used.

We regard to your scenario and the other issues you referenced, I don't see those as asking for the same thing. The normal way to not couple a type to a specific mapping is to not use data annotations to configure your model (since these are coupled to the type) but to instead use the fluent API in `OnModelCreating`. For example,
```C#
modelBuilder.Entity<CustomTag>().ToTable("custom_tags");
```
Having the same type mapped to multiple different tables _in the same model_ is currently only supported for owned types. Issue #9914 covers adding support for this in any time.

**Comment by ajcvickers** [comment]
Discussed in triage ans while we decided not to use `TableAttribute` for this, we would consider a new attribute for this.
