### ISSUE TITLE
Different behaviour between Find and FirstOrDefault when raise Exception

### ISSUE THREAD

**Issue by m4ss1m0g** [dotnet/efcore#16213]
### Steps to reproduce
```c#

public class Simple
{
	public int Id { get; set; }

	public string Title { get; set; }

}

public class SimpleContext : DbContext
{
	public virtual DbSet<Simple> Simples { get; set; }

	public SimpleContext(DbContextOptions options) : base(options)
	{

	}
}



public class ReproBugs
{
	public void Run()
	{
		var connection = new SqliteConnection("DataSource=:memory:");

		var options = new DbContextOptionsBuilder<SimpleContext>()
			  .UseSqlite(connection)
			  .Options;

		connection.Open();

		EntityEntry<Simple> simple;
		using (var ctx = new SimpleContext(options))
		{
			ctx.Database.EnsureCreated();


			simple = ctx.Simples.Add(new Simple { Title = "Title 1" });

			ctx.SaveChanges();


			var e = ctx.Simples.Find(simple.Entity.Id);
			ctx.Remove(e);
			ctx.SaveChanges();

		}

		using (var ctx = new SimpleContext(options))
		{
			try
			{
				ctx.Update(simple.Entity);
				ctx.SaveChanges();
			}
			catch (Exception)
			{
				var exist = ctx.Simples.Find(simple.Entity.Id);
				var nonExist = ctx.Simples.FirstOrDefault(p => p.Id == simple.Entity.Id);

				//Assert.Null(nonExist);
				//Assert.NotNull(exist);
			}
		}
	}
}

```

On the exception code block the _exist_ variable CONTAINS the value, on the nonExist return null.
If it work as expected please report on docs.

### Further technical details
EF Core version: 2.2.
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.3

**Comment by ajcvickers** [comment]
@m4ss1m0g The call to `Update` starts tracking the entity. Since [Find](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.find?view=efcore-2.1#Microsoft_EntityFrameworkCore_DbSet_1_Find_System_Object___) looks at tracked entities first, it returns that entity. The query on the other hand [is always run against the database](https://docs.microsoft.com/en-us/ef/core/querying/overview), where the entity has been deleted, and so it is not returned.
