### ISSUE TITLE
Consider moving design-time interfaces to Abstractions packages

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#16248]
Interfaces like IDesignTimeDbContextFactory and IPluralizer are commonly implemented in application code to influence tooling behavior. In 3.0 the Microsoft.EntityFrameworkCore.Design becomes a DevelopmentDependency package, so you cannot use these interfaces in application code without manually editing the project file (see https://github.com/aspnet/EntityFramework.Docs/pull/1536/files). 

This can be avoided if we move this kind of interfaces to abstractions package so that they are always available to the application.

**Comment by ajcvickers** [comment]
Notes from triage: we should look for things that should move. These things should be in abstractions if we expect the proper usage to be that they are part of the deployed, runtime code. So `IDesignTimeDbContextFactory` fits this. On the other hand, implementing `IPluralizer` is more of a workaround. We should consider directing people to other patterns, or implementing #11160.

**Comment by bricelam** [comment]
Notable items:
- `[DesignTimeProviderServices]`
- `[DesignTimeServicesReference]`
- `IDesignTimeServices`
- `IDesignTimeDbContextFactory`
- `[DbContext]`

These are currently in Microsoft.EntityFrameworkCore.dll. They shouldn't move to abstractions because they aren't useful without references to additional EF Core packages.
