### ISSUE TITLE
Consider removing nullable reference types support form EF Core 3.0

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#16250]
We are considering this due to the fact that nullability isn't first class in reflection (see https://github.com/dotnet/corefx/issues/38087, punted post-3.0), and so far we have not been provided any guarantees that the nullability attributes generated by the compiler will be stable after the 3.0 release. 

cc @ajcvickers, @roji

**Comment by roji** [comment]
Here's the newly-updated document describing the metadata structure. It's not as trivial as before, but also doesn't seem to hard to implement. We can of course wait for final confirmation on what to do, but IMHO there's a good reason to drop this just because there's no reflection API.

/cc @rynowak what are your plans on the ASP.NET side? I'm seeing various issues related to C# 8 nullability in the ASP.NET repo, I'm assuming that means you're implementing support for the new metadata? If this is already done, can you point me towards the parsing code?

**Comment by rynowak** [comment]
> Here's the newly-updated document describing the metadata structure.

Is there supposed to be a link?

> what are your plans on the ASP.NET side?

I don't have a decision yet because I haven't been following along with the docs. If it's reasonable to do, then I want to keep the feature.

> I'm seeing various issues related to C# 8 nullability in the ASP.NET repo, I'm assuming that means you're implementing support for the new metadata? If this is already done, can you point me towards the parsing code?

I don't think we've had any issues reported on related to the metadata, those are unrelated 😆

**Comment by roji** [comment]
> Is there supposed to be a link?

Oops, it's a bit late here: https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md

> I don't have a decision yet because I haven't been following along with the docs. If it's reasonable to do, then I want to keep the feature.

OK, let's keep in sync on this - at the very least so that we don't implement a metadata parser twice!

**Comment by divega** [comment]
We are getting some more reassurance that the attributes in practice won't change because changing it after 3.0 would almost certainly be a breaking change where the C#8 compiler would not recognize annotations from assemblies compiled by a later compiler. 

We still need to figure out the feasibility of decoding the new metadata.
