### ISSUE TITLE
In Memory Database Doesn't Use Value Conversion

### ISSUE THREAD

**Issue by Cooksauce** [dotnet/efcore#16270]
When using the in memory database by calling "UseInMemoryDatabase":

It does not use value converter when materializing entities.

Is this a bug or a design decision?

Note: When using the real db provider the value is used.

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.InMemory

**Comment by ajcvickers** [comment]
@Cooksauce There was a time when it didn't, but I'm pretty sure it was fixed before 2.2 was released. Can you post a small, runnable project/solution or complete code listing that demonstrates the behavior.

**Comment by Cooksauce** [comment]
@ajcvickers  Yup here's the link:
[https://github.com/Cooksauce/InMemoryBugReplication](url)

**Comment by Cooksauce** [comment]
@ajcvickers Are you able to run the repo and see the issue?

**Comment by ajcvickers** [comment]
@Cooksauce Thanks for the repro--looks like this wasn't fixed. Issue #14042 is tracking this.

Note for triage: It's interesting that this has never worked, but this is the first externally reported issue. This is because usually the in-memory database can store any value, so conversion is not needed, and the fact that it is not there cannot be observed. However, in this case the conversion is being used to force a UTC DateTime, where it can be observed.

**Comment by cpboyd** [comment]
@ajcvickers I have another case: A list of primitives.

The in-memory database throws an exception without a converter.  (With a converter, it always returns an empty list.)
