### ISSUE TITLE
Flaky test: Union_non_entity

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#16365]
Says
```
            AssertSql(
                @"SELECT [c].[CustomerID]
FROM [Customers] AS [c]
WHERE ([c].[ContactTitle] = N'Owner') AND [c].[ContactTitle] IS NOT NULL
UNION
SELECT [c0].[CustomerID]
FROM [Customers] AS [c0]
WHERE ([c0].[City] = N'México D.F.') AND [c0].[City] IS NOT NULL",
                //
                @"SELECT [o].[OrderID] AS [Id1], [o0].[OrderID] AS [Id2]
FROM [Orders] AS [o]
CROSS JOIN [Orders] AS [o0]
LEFT JOIN [Customers] AS [c] ON [o].[CustomerID] = [c].[CustomerID]
LEFT JOIN [Customers] AS [c0] ON [o0].[CustomerID] = [c0].[CustomerID]
WHERE ([o].[CustomerID] IS NOT NULL AND ([o].[CustomerID] LIKE N'A%')) AND ((([c].[CustomerID] = [c0].[CustomerID]) AND ([c].[CustomerID] IS NOT NULL AND [c0].[CustomerID] IS NOT NULL)) OR ([c].[CustomerID] IS NULL AND [c0].[CustomerID] IS NULL))
ORDER BY [o].[OrderID], [o0].[OrderID]");
```
Though that's not correct SQL. Need to disable the test.

**Comment by smitpatel** [comment]
It caused issue in Join_customers_orders_with_subquery_anonymous_property_method_with_take now.
I am disabling the test which generates that Union SQL.

**Comment by roji** [comment]
FYI we also have tests failing because of `System.InvalidOperationException : There is already an open DataReader associated with this Command which must be closed first.` (e.g. [this build](https://github.com/aspnet/EntityFrameworkCore/pull/16385/checks?check_run_id=160037365)). Interestingly this happened on the same test Comparing_navigations_using_Equals, although I think I saw it happening in other tests too. If this gives anyone any ideas/pointers let me know, otherwise I'll try to investigate very soon.
