### ISSUE TITLE
Update previous migration file

### ISSUE THREAD

**Issue by dennis-8** [dotnet/efcore#16545]
Hello,

I have a question about migrations.

Example: I have created 3 tables using separate migration for each: AddTable1, AddTable2, AddTable3.

After that several days later I decided to change the type of `status` column in `Table1` to be `int` and not `string`.

I drop the database, update the AddTable1 file, execute `update-database` and it doesn't work.
The column `status` in database after running the scripts is still `string`.

What is happening here?

I know I'm supposed to add a new migration to change the type, but I'd like to know why it doesn't work the way I was expecting.

Thank you

### Further technical details
EF Core version: 2.2.6 (installed latest Visual Studio 2019 update)
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows 8.1
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by denis-n** [comment]
Also, what is `Designer.cs` file for?

I removed them and when I executed the migrations, no table was created.
Can you please get rid of them?

**Comment by ajcvickers** [comment]
@denis-n A good place to start for these kinds of questions is one of the [getting-started walk-throughs](https://docs.microsoft.com/en-us/ef/core/get-started/), or the [documentation for Migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/)

Beyond this, if you have additional questions about some aspect of this, then please try to formulate very specific questions, preferably with runnable code that demonstrates the behavior you are seeing so that we can investigate what you are seeing without guessing too much what you mean.
