### ISSUE TITLE
Single query perf regression on linux

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/efcore#16557]
Just noticed **~40%** regression for a single query:
![image](https://user-images.githubusercontent.com/34246760/60994875-3bce0700-a306-11e9-897c-317fe797f228.png)

This is a huge regression:
![image](https://user-images.githubusercontent.com/34246760/60994989-6fa92c80-a306-11e9-98de-28cdb11a749d.png)

![image](https://user-images.githubusercontent.com/34246760/60994899-49838c80-a306-11e9-864f-7a35a4caea41.png)

@ajcvickers, @DamianEdwards, @davidfowl FYI

**Comment by mkArtakMSFT** [comment]
This is still the case with more queries being impacted: 
![image](https://user-images.githubusercontent.com/34246760/61071184-48656480-a3c5-11e9-9460-c2a4022ab04a.png)

**Comment by ajcvickers** [comment]
Looks like one of the regular blips:
![image](https://user-images.githubusercontent.com/1430078/61142109-d43dc600-a483-11e9-9da6-c0c334e4ddc1.png)

Some notes:
* Most of these tests don't use EF, so it's only usually an EF issue if only the EF tests show a regression. In a case like this, it's something else going on outside of EF because all the tests showed a regression.
* The benchmarks are using a version of EF from preview 5. @roji is working on updating the Npgsql provider to preview 7, at which point we will get more realistic numbers.

**Comment by roji** [comment]
Am on vacation but will look a bit more in depth next week.

As Arthur wrote, both EF Core and the Npgsql ADO.NET driver are pinned and do not automatically like other components in the stack - so unfortunately even if we do have a regression that wouldn't show.
We do have the EF Core microbenchmarks which were added recently (and aren't very stable yet) which should start giving us continuous perf data.

One last thought is to rig our TE benchmarks to run on Sqlite instead of Npgsql - like in the microbenchmarks. That would give continuous results tracking the latest EF Core (which is the main point) even if that's not what the ideal overall perf we're taking for TE. This could also be done in a separate dashboard if we want.
