### ISSUE TITLE
Query: Bitwise Ex-Or support

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#16645]
Currently client eval

**Comment by ranma42** [comment]
related to #18795 (which includes also other bitwise operators)

**Comment by roji** [comment]
Interestingly, in PG the caret (^) isn't bitwise XOR, it's exponentiation; hash (#) is used for bitwise XOR. See below for a cross-database list.

@ranma42 given that XOR currently isn't supported in SQLite, can you confirm that we don't have any translations actually relying on that? Since these would fail in SQLite (IIRC you introduced XOR for SQL Server-specific search condition transformations, so seems fine - just confirming).
 
* SQL Server: caret (^) ([docs](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/bitwise-exclusive-or-transact-sql?view=sql-server-ver16))
* SQLite: not supported (https://github.com/dotnet/efcore/pull/34071). Expand in post-processing?
* MySQL: caret (^) ([docs](https://dev.mysql.com/doc/refman/8.4/en/bit-functions.html#operator_bitwise-xor))
* MariaDB: caret (^) ([docs](https://mariadb.com/kb/en/bitwise-xor/))
* PostgreSQL: hash(#) ([docs](https://www.postgresql.org/docs/current/functions-bitstring.html)). The caret (^) is the exponentiation operator.
* Oracle: caret (^) ([docs](https://docs.oracle.com/cd/E19253-01/817-6223/chp-typeopexpr-7/index.html)) 
* Firebird: BIN_XOR() ([docs](https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref30/fblangref30-functions-bitwise.html))

**Comment by ranma42** [comment]
> @ranma42 given that XOR currently isn't supported in SQLite, can you confirm that we don't have any translations actually relying on that? Since these would fail in SQLite (IIRC you introduced XOR for SQL Server-specific search condition transformations, so seems fine - just confirming).

Yes, inside of efcore the XOR is currently only used to avoid some back-and-forth between boolean value and boolean predicate in SqlServer. It would be trivial to support it for boolean values on sqlite, while other values would require plugging something like `ef_xor`.
