### ISSUE TITLE
Seed Data changes should be possible without a migration

### ISSUE THREAD

**Issue by TehWardy** [dotnet/efcore#16690]
In EF6 it was possible to make changes to seed data and simply re-run the project in EF Core that is not longer possible.

I would like an option to seed data as part of my application startup in a way that doesn't involve a migration as managing this data via migrations is creating literally days more work for me at the moment.

**Comment by ajcvickers** [comment]
@TehWardy You can write a method that will seed the database and run it at startup, just like in EF6. The only difference is that you have to make the call to seed the database--it won't happen automatically. This is by design, since running it automatically was both error-prone and limiting in how it works.
