### ISSUE TITLE
Drop Statistics

### ISSUE THREAD

**Issue by MrChriZ** [dotnet/efcore#1690]
In Entity Framework Migrations we have methods for Dropping Indexes however no methods are provided for Dropping Statistics.

I'm trying to alter a column and make it not nullable but it fails because a statistics object is linked to the column.   As a result I will need to do this via SQL.  Could we have a method for dropping statistics please?

**Comment by rowanmiller** [comment]
@MrChriZ am I correct in assuming you have `AUTO_CREATE_STATISTICS` switched on for the database, which is how the statistics were created?

**Comment by MrChriZ** [comment]
Hi Rowan,

That would be correct.  The database was originally created independently of EF and then I used power tools to reverse engineer code first classes.
Thanks,
Chris.

**Comment by rowanmiller** [comment]
Hey,

We experimented with this a bit more and if SQL Server automatically creates the statistics then it will also automatically drop them when the index is dropped. So this means the need to drop the statistics only arises when you have also explicitly created them. For this scenario it is consistent with the migrations design that you would need to add an explicit call to drop them (using `SQL(...)`) given it's something migrations did not create (or in your case, because migrations didn't create the database, something it wouldn't have created). 

~Rowan

**Comment by MrChriZ** [comment]
" For this scenario it is consistent with the migrations design that you would need to add an explicit call to drop them (using SQL(...)) "

Thanks rowan.  However my point was that with indexes for example I could manually add to a migration file
DropIndex("dbo.tbl_cruise", "_dta_index_tbl_cruise_12_181575685__K5_K2_K1_K4");

I can't do the same with statistics - since there's no DropStatistics command available?

**Comment by rowanmiller** [comment]
Hey,

Yeah we typically only provide APIs for common operations when modelling with EF. Give that statistics can't be represented in the model, and are typically transparently created and dropped by the database, this isn't really something we would provide an first class API for. That is why we provide the Sql(...) method though, so you can take care of things there aren't an API for.

If there are things you find you do a lot in your particular projects, then you can write [custom migration operations](http://romiller.com/2013/02/27/ef6-writing-your-own-code-first-migration-operations/).

~Rowan

**Comment by MrChriZ** [comment]
thanks Rowan. That's fair enough.  I'll take a look at the custom migration operations that's interesting.
