### ISSUE TITLE
RevEng: Support for additional SQL Server data types

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#1713]
Currently we support many SQL Server data types, but not the following: cursor, hierarchyid, sql_variant, table, xml, geography, geometry. If RevEng comes across a column with one of these types it just outputs a warning message that it is ignoring that column.

We should decide which of the above we do plan to support and how we plan to do so.

**Comment by popcatalin81** [comment]
Table, xml, geography and geometry would be very welcome.

**Comment by ErikEJ** [comment]
Cursor  and table are not column types, afaik. Do not support sql_variant. And think carefully about how to support the remaining ones. (most likely not in V1)

**Comment by lajones** [comment]
I'm working off https://msdn.microsoft.com/en-us/library/ms187752.aspx which lists all the data types for SQL Server 2014. That said several of these types have not traditionally been supported - this list is just exhaustive so that we can make a deliberate yes/no support decision for each of them.

**Comment by rowanmiller** [comment]
**EF Team Triage:** There is a more general need to support these throughout EF and our SQL Provider. Closing out this issue not because we don't want to support them, but because we will enable support right throughout the stack as we go and don't need a specific item for reverse engineer.

**Comment by vRITHNER** [comment]
Hey Rowan, just to add my 2 ct, hope you'll support HierarchyId asap because it's really a great way to manage hierarchy and other manual ways demand so much effort in code. 
Also, it could be great to support natively the GROUP BY xxxx WITH ROLLUP to allow to calculate par ex. Totals per group/subgroup/etc... witch make a huge save code effort + offcourse performance improvement 
Txs
-Vince
