### ISSUE TITLE
Consider delaying DbCommandInterceptor.CommandCreated until DbCommand properties are intialized

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#17261]
I was hoping I could now log the CommandText from this method without having to override Execut* methods, but the DbCommand exposed as the result of CommandCreated is empty. 

We discussed with @ajcvickers that having the properties populated could be more useful, but it is likely we don't have time to change this for 3.0 RTM, in which case we can add  "CommandInitialized" method later.

**Comment by ajcvickers** [comment]
Compare to #15988

**Comment by simeyla** [comment]
@ajcvickers I was excited to see the following in the [EF Core 5 New Features](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew):

>"In addition, it is now possible to call ToQueryString on any LINQ query, retrieving the SQL that the query would execute"

I've added my own `DBInterceptor` to add `NOEXPAND` hints and it work's great.

However if I run `ToQueryString()` during debugging I won't see my hint in the SQL since I am relying on `ReaderExecutingAsync` and `ReaderExecuting` to perform the modification of the underlying command string.

It seems a shame that `CommandCreating` and `CommandCreated` seem to be intended only for fully [comprehensive]([url]([url](https://docs.epsagon.com/docs/dotnet))) interception, but not for the simpler cases. It would also be nice not to have to consider overloading both `ReaderExecutingAsync` and `ReaderExecuting`.

I know it's sort of an edge case and easy to work around but wanted to add this as part of this conversation.
