### ISSUE TITLE
Cosmos: Optimize `Find` by querying by 'id'

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#17310]
Use ReadItem
Include the partition key if present

**Comment by AndriySvyryd** [comment]
Depends on https://github.com/aspnet/EntityFrameworkCore/issues/7391

**Comment by AndriySvyryd** [comment]
@1iveowl The other option I mentioned in the comment above is to just handle the simple case where the PK consists of `id` and the partition key, so the user would be calling `Find(partitionKey, id)` or `Find(id, partitionKey)` depending on how they’ve configured it.

The next step up from this would be handling PKs that include the partition key, but don’t include the `id` directly. In those cases we usually can calculated the `id` value using the value generator configured on it, which by default is [IdValueGenerator](https://github.com/dotnet/efcore/blob/master/src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs)

The above can be accomplished by detecting the query pattern generated by [EntityFinder](https://github.com/dotnet/efcore/blob/dd843a2db241572395fd1c26ba7fc4e7e1e6ba72/src/EFCore/Internal/EntityFinder.cs) and instead of translating the query based on [SelectExpression](https://github.com/dotnet/efcore/blob/725adf77d3a08d99ce59787354d391176c3844b7/src/EFCore.Cosmos/Query/Internal/SelectExpression.cs) you'd need to create something like `ReadItemExpression`. Thinking about this it's actually a much more difficult change than I originally assumed.

@smitpatel for thoughts or advice

**Comment by AndriySvyryd** [comment]
@1liveowl If the above doesn't fit in the time you can dedicate for this creating the extension you've proposed - `DbSet<>. FindWithPartitionKeyAsync(partitionKey, primaryKey)` would also be an acceptable temporary solution. For the implementation you can create a class derived from EntityFinder that would handle this.

**Comment by smitpatel** [comment]
ShapedQueryExpression does allow having an expression different than SelectExpression. It may require some conditional code in ShapedQueryCompilingExpressionVisitor. Or we can factor it differently to call shaper specific part outside of query pipeline. It would be a difficult change. Shaper compiler on cosmos is more complicated than core.

**Comment by 1iveowl** [comment]
@AndriySvyryd, @smitpatel Let's lock-in on the API first. 

A few questions

> so the user would be calling Find(partitionKey, id) or Find(id, partitionKey) depending on how they’ve configured it

Where and how is configuration of the DbSet determining the order of the two values specified/implied?

> ... this would be handling PKs that include the partition key, but don’t include the `id` directly. In those cases we usually can calculated the `id` value using the value generator configured on it, which by default is [IdValueGenerator] ...

How might the `DbSet<>Find(???);` look for this?

Like this:  `DbSet<>.Find(myPartitionKey);`? If so, how would that work if there're multiple documents with the same entity type in Cosmos and with the same Partition Key? Should `Find` return a list of those documents in that case?

For `Find` to be an effective and generic way to read one specific document - fast and with ReadItem and from a specific partition - I think that it is a prerequisite that the developer provide both the Primary Key (or the cosmos `id`) ***and*** the Partition Key, and in a structured way where it's clear which is what.

### Suggestion: 

Could it be something like this: `DbSet<>.Find("myPartitionKey:myId")`?

In which case, we assume a string and introduce a Cosmos specific syntax for `Find` using `:` (or some other character or string) as the delimiter between the `id` and the `partition key`.

If no delimiter (`:`) is present we assume only **myPartitionKey** and return a list if there're more than one document with the entity type in context, in the partition. 

The reason we don't assume **myId** in the single value scenario, is that this wouldn't work if the access key supplied is a *resource token*, rather than a master key. Alternatively we'd need to also check what type of access key is supplied and thrown a meaningful exception based on that, to guide the developer.

**Comment by AndriySvyryd** [comment]
> Where and how is the configuration of the DbSet determining the order of the two values specified/implied?

@1iveowl The [PK is configured in this way](https://docs.microsoft.com/en-us/ef/core/modeling/keys?tabs=fluent-api):

```C#
    modelBuilder.Entity<Car>().HasKey(c => new { c.State, c.LicensePlate, c.PartitionKey });
```

> How will DbSet<>Find(???) look for this? Would it be like this: DbSet<>.Find(myPartitionKey);? If so, how would that work if there're multiple documents with the same entity type in Cosmos and with the same Partition Key? Should Find return a list of those documents in that case?

User always needs to specify all PK values in `Find`. But the PK doesn't need to be the Cosmos `id`. Like in the configuration above the user would call

```C#
    context.Set<Car>().Find("WA", "999ZZZ", "1234");
```

Currently this would translate into something like
```SQL
SELECT * from c
WHERE c.State = "WA" AND c.Plate = "999ZZZ" AND c.PartitionKey = "1234"
```
But in most cases we know how to generate the `id` value, which in this case would be `"WA|999ZZZ"`.
So ideally we would want to call `container.ReadItemAsync<>("WA|999ZZZ", "1234")` instead

> For Find to be an effective and generic way to read one specific document - fast and with ReadItem and from a specific partition - I think that it is a prerequisite that the developer provide both the Primary Key (or the cosmos id) and the Partition Key, and in a structured way where it's clear which is what.

Yes, so the simple case is where the entity type is configured like this:
```C#
    modelBuilder.Entity<Car>().HasKey(c => new { c.id, c.PartitionKey });
```

So the `id` and partition key values are specified explicitly:

```C#
    context.Set<Car>().Find("WA|999ZZZ", "1234");
```

> Could the API be something like this: DbSet<>.Find("myPartitionKey:myId")?

This doesn't follow current API conventions and would be confusing for existing EF users.

**Comment by 1iveowl** [comment]
Thank you @AndriySvyryd. Good comments. 

One more thing regarding:
> ```cs
> modelBuilder.Entity<Car>().HasKey(c => new { c.State, c.LicensePlate, c.PartitionKey });
> ```

This helps us build the query, but now to extract the partition key explicitly. The example tricks us, because it's so obvious that the third value is the partition key. However it might as well have looked like this:. `modelBuilder.Entity<Car>().HasKey(c => new { c.ValueA, c.ValueB, c.ValueC });` and now we don't know which one is the partition key any longer. 

Thus, I guess for the generic `Find` to work,  we would need to require that the developer also specifies: `modelBuilder.Entity<Person>().HasPartitionKey(o => o.ValueC)`, because then we would know for sure that `ValueC` is the partition key.

**Comment by AndriySvyryd** [comment]
> I guess for the generic Find to work, we would need to require that the developer also specifies: modelBuilder.Entity<Person>().HasPartitionKey(o => o.ValueC), because then we would know for sure that ValueC is the partition key.

Yes

**Comment by 1iveowl** [comment]
Regarding:

> ```cs
>     context.Set<Car>().Find("WA", "999ZZZ", "1234");
> ```
> 
> 
> Currently this would translate into something like
> ```sql
> SELECT * from c
> WHERE c.State = "WA" AND c.Plate = "999ZZZ" AND c.PartitionKey = "1234"
> ```
> 
> 
> But in most cases we know how to generate the id value, which in this case would be "WA|999ZZZ".
> So ideally we would want to call container.ReadItemAsync<>("WA|999ZZZ", "1234") instead

In this example, the assumption is made, that the `id` equals `WA|999ZZZ`, because the EF.Core/Cosmos `IdValueProvider` has been used to generate the `id`.

However, in a scenario were the Cosmos documents were not created by EF.Core/Cosmosthe `id` might look like: `Car-WA-999ZZZ` or something entirely different. This raises a need for an additional feature for overriding the `IdValueGenerator` to adapt to the `id` generation scheme used.

**Comment by AndriySvyryd** [comment]
> However, in a scenario were the Cosmos documents were not created by EF.Core/Cosmosthe id might look like: Car-WA-999ZZZ or something entirely different. This raises a need for an additional feature for overriding the IdValueGenerator to adapt to the id generation scheme used.

It's up to the user to provide the correct value generator, we'd just use whatever is configured on `id`. And if it has no value generator, then we'll fall back to the slow query

**Comment by 1iveowl** [comment]
> It's up to the user to provide the correct value generator, we'd just use whatever is configured on `id`. And if it has no value generator, then we'll fall back to the slow query

Ahh yes, using https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.propertybuilder.hasvaluegenerator?view=efcore-3.1

**Comment by dennis-yemelyanov** [comment]
What's the current story on this? EF Core 5.0.0 still seems to generate queries instead of doing point reads using ReadItem{Async}. Am I missing some setup/doing something wrong?

The code looks like this:
```csharp
    public class User
    {
        public Guid Id { get; set; }

        // other fields
    }

    public class UserContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        public UserContext(DbContextOptions<UserContext> options)
            : base(options)
        {
            Debug.WriteLine($"{ContextId} context created.");            
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.LogTo(x => Debug.WriteLine(x), Microsoft.Extensions.Logging.LogLevel.Debug);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .Property(o => o.Id)
                .HasConversion<string>();

            modelBuilder.Entity<User>()
                .HasPartitionKey(o => o.Id);
        }
    }
```
The entity is queried like this:
```csharp
    using var context = dbContextFactory.CreateDbContext();

    Guid keyValue = Guid.Parse("guid-value");

    var user = await context.Users.FindAsync(keyValue);
```
This generates the following log, which seems to indicate a query is executed and not a point read operation:

```
dbug: 12/11/2020 11:15:55.360 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query) 
      Compiling query expression: 
      'DbSet<User>()
          .FirstOrDefault(e => object.Equals(
              objA: EF.Property<object>(e, "Id"), 
              objB: (object)__get_Item_0))'
dbug: 12/11/2020 11:15:55.552 CoreEventId.QueryExecutionPlanned[10107] (Microsoft.EntityFrameworkCore.Query) 
      Generated query execution expression: 
      'queryContext => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<User>(
          asyncEnumerable: new QueryingEnumerable<User>(
              (CosmosQueryContext)queryContext, 
              SqlExpressionFactory, 
              QuerySqlGeneratorFactory, 
              [Cosmos.Query.Internal.SelectExpression], 
              Func<QueryContext, JObject, User>, 
              ReResponse.UserContext, 
              null, 
              False
          ), 
          cancellationToken: queryContext.CancellationToken)'
```
Passing `keyValue` twice (`FindAsync(keyValue, keyValue)`) generates an exception since the entity is set up with only one primary key:
`ArgumentException: Entity type 'User' is defined with a single key property, but 2 values were passed to the 'DbSet.Find' method.`

**Comment by dennis-yemelyanov** [comment]
What's the current story on this? EF Core 5.0.0 still seems to generate queries instead of doing point reads using ReadItem{Async}. Am I missing some setup/doing something wrong?

The code looks like this:
```csharp
    public class User
    {
        public Guid Id { get; set; }

        // other fields
    }

    public class UserContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        public UserContext(DbContextOptions<UserContext> options)
            : base(options)
        {
            Debug.WriteLine($"{ContextId} context created.");            
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.LogTo(x => Debug.WriteLine(x), Microsoft.Extensions.Logging.LogLevel.Debug);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .Property(o => o.Id)
                .HasConversion<string>();

            modelBuilder.Entity<User>()
                .HasPartitionKey(o => o.Id);
        }
    }
```
The entity is queried like this:
```csharp
    using var context = dbContextFactory.CreateDbContext();

    Guid keyValue = Guid.Parse("guid-value");

    var user = await context.Users.FindAsync(keyValue);
```
This generates the following log, which seems to indicate a query is executed and not a point read operation:

```
dbug: 12/11/2020 11:15:55.360 CoreEventId.QueryCompilationStarting[10111] (Microsoft.EntityFrameworkCore.Query) 
      Compiling query expression: 
      'DbSet<User>()
          .FirstOrDefault(e => object.Equals(
              objA: EF.Property<object>(e, "Id"), 
              objB: (object)__get_Item_0))'
dbug: 12/11/2020 11:15:55.552 CoreEventId.QueryExecutionPlanned[10107] (Microsoft.EntityFrameworkCore.Query) 
      Generated query execution expression: 
      'queryContext => ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<User>(
          asyncEnumerable: new QueryingEnumerable<User>(
              (CosmosQueryContext)queryContext, 
              SqlExpressionFactory, 
              QuerySqlGeneratorFactory, 
              [Cosmos.Query.Internal.SelectExpression], 
              Func<QueryContext, JObject, User>, 
              TestApp.UserContext, 
              null, 
              False
          ), 
          cancellationToken: queryContext.CancellationToken)'
```
Passing `keyValue` twice (`FindAsync(keyValue, keyValue)`) generates an exception since the entity is set up with only one primary key:
`ArgumentException: Entity type 'User' is defined with a single key property, but 2 values were passed to the 'DbSet.Find' method.`
