### ISSUE TITLE
Entity Id Type (generic / dynamic) with Generic Repository

### ISSUE THREAD

**Issue by lixaotec** [dotnet/efcore#17573]
How may I have some kind of 'mix' types for Id property (keys) of an Entity that is inherited?
I have tables that Ids are of bigint autoincrement, and some of them are Guid type. (i wish not to change all to Guid)

Like:

```C#
public abstract class Entity {
  public object id { get; set; }
}

public class Car : Entity {
  public new long id { get; set; } // this generates a second id property at runtime, efcore doenst work well  with that
...
}
```

and in my GenericRepositories I do some Linq operations with id property that aren´t accepatable when having object type for it.

What is the best practices of this scenarios of mixing int/bigint autoincremet ids and guids with generic operations?

thanks

**Comment by ajcvickers** [comment]
@lixaotec Depends exactly what you need. If the base class does not need to be mapped in the EF model, then the hidden `Id` property would not be a problem for EF. If the base class does need to be mapped, then the key type must be defined there, since all types in a mapped hierarchy must share the same key space.

That being said, as the code is written above I'm not sure how the property on the base class would be used at all, since there is no connection between it and the real `Id` probably. In other words, setting the `Id` on `Car` has no impact on the base class property. So I'm kind of assuming that you really mean something like this:

```C#
public abstract class Entity 
{
    public object Id { get; set; }
}

public class Car : Entity 
{
    public new long Id
    {
        get => (long)base.Id;
        set => base.Id = value;
    }
}
```

**Comment by Rudragowda2g** [comment]
public abstract class Entity<T> {
  public T id { get; set; }
}

public class Car : Entity<long> {
//define car class here
}
