### ISSUE TITLE
Set operation Visit() methods not called in all cases

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/efcore#17854]
For "naked" set operations, `QuerySqlGenerator.VisitExcept()` and `QuerySqlGenerator.VisitIntersect()` are never getting called.
Tested with `SimpleQueryTestBase.Intersect()` on `release/3.0:5ee5829`.

https://github.com/aspnet/EntityFrameworkCore/blob/130fe39bed1c9351ba73a829aa14a6112108a6b2/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L110-L118

Shouldn't `QuerySqlGenerator.VisitSelect()` really call `QuerySqlGenerator.VisitIntersect()` etc. instead of calling `QuerySqlGenerator.GenerateSetOperation()` directly?

At the moment it is necessary to override `GenerateSetOperation` as a workaround:

```C#
protected override void GenerateSetOperation(SetOperationBase setOperation)
{
    if (setOperation is UnionExpression)
        base.GenerateSetOperation(setOperation);

    throw new InvalidOperationException(
        CoreStrings.TranslationFailed(setOperation.Print()));
}
```

The current behavior seems unexpected from a provider's point of view and it's a bit odd to override `QuerySqlGenerator.GenerateSetOperation()`.

---

I came across this issue, while looking for the right place to explicitly trigger client eval (if enabled, otherwise throw an exception) for set operations (like `INTERSECT` and `EXCEPT`) without native database support.
As it turns out, `QuerySqlGenerator` is the wrong place for that scenario (too late in the query pipeline) and `RelationalQueryableMethodTranslatingExpressionVisitor` should be used instead.

**Comment by smitpatel** [comment]
Each individual SetOperation is a table source so it appears as `FROM (….)` (or appropriate join syntax). But in case if the set operation is not composed over, that is it is just selecting columns from result of set operation without doing anything else then select from subquery is unnecessary. Hence we need to generate only inside of the parenthesis (without parenthesis of course), hence it uses that method directly.

I believe, that logic should never need to be changed. Of course, feedback welcomed if it is necessary but in that case it would be extended via making `IsNonComposedSetOperation` function public to let provider tell us if we can lift it or not. Also, the current pattern is mixed bag scenario. If you want to print IntersectExpression differently you would need to override GenerateSetOperation function truly. It is a compromise between having to update code at one point and being it bit unintuitive to understand. At the same time since it is open source and providers can view the base class, it is not hard to figure out what to override when. Documentation on these methods in future would help.

As you figured out, if provider does not support the function then translation itself should be blocked rather than playing around with SqlGenerator.
