### ISSUE TITLE
ApplyTypeMapping does still not handle all cases for SqlLikeExpression

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/efcore#17987]
The issue #17605 fixed a couple of problems with `SqlLikeExpression`, but there is one more.

The following 3 queries are all valid SQL, at least in SQL Server and MySQL:

```sql
select o.OrderID
from Northwind.Orders as o
where 3.0 like '3.%';

select o.OrderID
from Northwind.Orders as o
where '3.0' like 3.0;

select o.OrderID
from Northwind.Orders as o
where 3.0 like 3.0;
```

This can be easily triggered by a `DbFunction` extension method like this one:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/a5255dcdc3f2b743cec4cd995da6c4e39f716958/src/EFCore.MySql/MySqlDbFunctionsExtensions.cs#L498-L503

```c#
public static bool Like<T>(
    [CanBeNull] this DbFunctions _,
    [CanBeNull] T matchExpression,
    [CanBeNull] string pattern,
    [CanBeNull] string escapeCharacter)
    => LikeCore(matchExpression, pattern, escapeCharacter);
```

The current `SqlExpressionFactory.ApplyTypeMappingOnLike()` implementation looks like this:

https://github.com/aspnet/EntityFrameworkCore/blob/6cfdd4a9df8fa46ece6894541278b01b6411d273/src/EFCore.Relational/Query/SqlExpressionFactory.cs#L65-L79

Because the match and the pattern can be of different types and can be of non-string types, and are therefore independent of each other, none of the `SqlLikeExpression` parameter types should be inferred by default by the first found type mapping of a preceding parameter.

Instead it should be tried to find each parameter's type mapping by using the parameter's own type first.

The handling should be changed to either:

```c#
return new LikeExpression(
    ApplyDefaultTypeMapping(likeExpression.Match),
    ApplyDefaultTypeMapping(likeExpression.Pattern),
    ApplyDefaultTypeMapping(likeExpression.EscapeChar),
    _boolTypeMapping);
```

Or:

```c#
return new LikeExpression(
    ApplyTypeMapping(ApplyDefaultTypeMapping(likeExpression.Match), inferredTypeMapping), 
    ApplyTypeMapping(ApplyDefaultTypeMapping(likeExpression.Pattern), inferredTypeMapping),
    ApplyTypeMapping(ApplyDefaultTypeMapping(likeExpression.EscapeChar), inferredTypeMapping),
    _boolTypeMapping);
```

to handle all the cases correctly.

**Comment by smitpatel** [comment]
According to T-SQL documentation for Like https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-2017 match, pattern & escape char all are character string data types only. If the documentation is correct then the SQL you posted if working in SqlServer, probably converting non-string to string implicitly. Not sure if there is any value added to support non-string inside SqlLikeExpression. Non-string can always be converted to string by calling ToString method.

I believe first question which should be answered that if we want to support such non-strings in like. If there is no utility (EF.Functions.Like has been around for a while), then it's YAGNI.

If we ever decide to _support_ it, then both the solutions are *incorrect*. If SQL is `a.Column Like 'Sea%'` then the pattern should have same facets as `a.Column` (especially Unicode-ness). By applying default type mapping you lose that. That defeats the purpose of inferring typeMapping. The second alternative still applies default typeMapping only. `ApplyTypeMapping` is no-op if typeMapping is already set which would be done by `ApplyDefaultTypeMapping` already.

A correct fix would potentially infer typeMapping and apply inferred one if same type otherwise apply default if it is a different type and cannot be inferred.

If MySQL wants to support such an overload, you can always apply default (or whatever other typeMapping you want to apply), to the SqlExpression before passing it to `_sqlExpressionFactory.Like` function. If the typeMappings are already set for all the arguments, then it won't be changed by base visitor.

**Comment by lauxjpn** [comment]
> [...] probably converting non-string to string implicitly [...]

> If SQL is a.Column Like 'Sea%' then the pattern should have same facets as a.Column (especially Unicode-ness). By applying default type mapping you lose that. That defeats the purpose of inferring typeMapping.

Good points and insights!
MySQL seems to convert the `LIKE` arguments to string implicitly as well:

> 12.5.1 String Comparison Functions and Operators
> [...]
> A number converted to a string is treated as a binary string. This affects only comparisons.

I will apply the appropriate type mapping manually then.
