### ISSUE TITLE
How to get SQL script before calling DbContext.SaveChanges()

### ISSUE THREAD

**Issue by usender** [dotnet/efcore#18018]
I use EF core 2.2
How to get generated SQL scripts to be applied. I need something like that

```
 private IEnumerable<string> GetSqls<TEntity>(ICollection<TEntity> entities)
        {
            foreach (var entity in entities)
            {
                DbContext.Add(entity);
            }

            // list of the apply sql scripts. something like this DbContext.GetQueries()
            foreach (var query in DbContext.GetQueries())
            {
                yield return query;
            }

          //  DbContext.SaveChanges();
        }
```

**Comment by smitpatel** [comment]
@zsender - Can you describe why you need to get SQL for SaveChanges?

**Comment by zsender** [comment]
I have methods for synchronizing database dictionaries (these methods are also used in code, in services).
Therefore, I use **DbContext**.
My database is created by migration. At the end of the script, I added my own method for inserting data for dictionaries. I did this to create either everything or nothing (in one transaction).
The problem is that when I call **DbContext.SaveChanges()**, I get an error that the object does not exist.
Therefore, I need to get scripts from **DbContext** and pass them to **MigrationBuilder.Sql(...)** so that it sequentially performs all the actions.

**Comment by zsender** [comment]
Is it possible somehow in **MigrationBuilder** to pass executing **DbContext.SaveChanges()**

**Comment by bricelam** [comment]
To modify data in a migration, use `migrationBuilder.Insert()`, `Update()`, and `Delete()`--not the DbContext.

**Comment by zsender** [comment]
How to do it? If when adding an item we have navigation property?

**Comment by bricelam** [comment]
Use foreign key values and insert data in the correct order.

**Comment by zsender** [comment]
This is understandable, I wanted to solve this problem by DbContext. The first reason is to forget about changes of fields of Entity (deleting, renaming columns, or remove or create navigation properties). The second reason, do not to editing SQL, delegate  this for the DbMigration.

**Comment by bricelam** [comment]
Are you looking for [Data Seeding](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)?

**Comment by zsender** [comment]
Not exactly what I wanted, but this solution is working. Thanks for help.
