### ISSUE TITLE
Entity framework Core using Store Procedure - With multiple subsets of results.

### ISSUE THREAD

**Issue by allanisaikumar** [dotnet/efcore#18010]
My current store Procedure return result columns based on my conditions.
 **i.e in one set of my params it gives a b c columns.
     in other set of params it gives a b d columns.**

But the entity is of a b c d column properties...

this gives error for that d is not in query result in first case and c is not in query result in second case

**Need us the way to have map the properties if result have that value otherwise take the default values of the properties...**

**Comment by smitpatel** [comment]
You can also update your sproc to select column which is not generated with default or null value as columnName.

**Comment by allanisaikumar** [comment]
We are having that selection but the same SP is selecting the column based on the condition as per our business logic search params.

**Comment by smitpatel** [comment]
@allanisaikumar - Your SP can return all the columns regardless of condition. Since you have an entity with all the properties, what is your expectation of a property value when SP does not return a column? You can use whatever is your expected value in entityType as a value for the column returned from SP. (It could be default or null or whatever). Based on condition in your SP you can figure out when to put some real value and when to put a default value. Since you are using single entityType your SP's output needs to match the shape of entity.
