### ISSUE TITLE
Internal properties are not included in the model by convention

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#18065]
A query using a filter on an internal string property is causing an exception saying it can’t be translated. 

Using EF.Property works.

Haven’t checked but this could be scooped to the in-memory provider, based on the repro provided.

### Steps to reproduce

The repro Is at https://gist.github.com/mabster/dd0e7cc7041ba42ce26725838a1d1180

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.InMemory

Cc @DamianEdwards, @smitpatel

**Comment by divega** [comment]
Cc @mabster

**Comment by smitpatel** [comment]
Internal properties are not discovered by convention. Hence the property `Tag` is actually not mapped in the model. I verified this is true for 2.2 & 3.0 both. (Since it is modelBuilding, the behavior is same across all providers).
From query perspective, 2.2 also did client eval & since 3.0 does not do client eval it throws. Verified that it throws for member access & EF.Property both when not mapped.
If you map the internal property explicitly using this in `OnModelCreating`
`modelBuilder.Entity<Widget>().Property(e => e.Tag);`
Then it is included in the model & querying using member access and EF.Property both works correctly.

**Comment by divega** [comment]
@mabster I wonder if the simplified repro you provided fails for the same reason you originally hit the exception in your code. For example, on Twitter you mentioned that EF.Property worked for you as a workaround, but as @smitpatel explained, that doesn’t happen in the simplified repro because the property isn’t mapped.

**Comment by divega** [comment]
Ah, @mabster I think I got what you said in Twitter wrong. The workaround wasn’t to call EF.Property in the query, but to explicitly configure the property in OnModelCreating. Then you are saying the same thing as @smitpatel, and this is currently expected.

**Comment by mabster** [comment]
Bingo. :) I was mostly confused because it was working previously. I'm fine with having to explicitly map the property - just wasn't aware that this was necessary for internals.

**Comment by divega** [comment]
@smitpatel, are we keeping this open to discuss mapping internal properties?

**Comment by smitpatel** [comment]
@divega - Yes. Let's see what team says about it. (I also changed title to reflect it)

**Comment by ajcvickers** [comment]
After discussing this again while we agree this might be a better behavior, we don't believe that there is enough value to make the breaking change now.
