### ISSUE TITLE
How to extend SelectExpression

### ISSUE THREAD

**Issue by daniel-white** [dotnet/efcore#18114]
In EF Core 2.1, I was able to extend `SelectExpression` to provide wrapping a column conditionally in a SQL function call.

For instance I would adjust the `SelectExpression` to take a query like this

```
SELECT Column FROM Table
```

and remap it into
```
SELECT myfunc(Column, args...) FROM TABLE
```

I used to override `SelectExpression.BindProperty`.

`SelectExpression` now only has internal/private constructors.

Is there another new layer to the EF Core 3.0 stack that I'm missing?

**Comment by daniel-white** [comment]
From the looks of it, I have to hook in a `ProjectionExpression` to change the column. I'll keep digging if theres any insight, I'd appreciate it.

**Comment by roji** [comment]
@daniel-white can you please provide some more context on exactly what you're trying to achieve?

**Comment by daniel-white** [comment]
So I'm trying to change how the property is bound in the projection part of the `SELECT`. With 2.1, I could detect certain model/entity properties as having a certain annotation and turn it on selectively. 
I'm trying to project the column from a scalar function that takes additional information in - a string parameter from the .net-side query context, the column value and the PK of that row. The end goal of this scalar function is to potentially return a localized string form of the column so its bound to the entity class property.

**Comment by roji** [comment]
I believe the proper way to do this, rather than extending SelectExpression, would be to write a post-processing visitor (see IQueryTranslationPostprocessorFactory and its implementations), which would identify the ColumnExpressions (or ProjectionExpression) you want to modify and replace it accordingly. However, @smitpatel is the authority here.

**Comment by daniel-white** [comment]
thanks @roji and @smitpatel. i'm able to adjust the projection for the column! however, I'm not able to find a "safe" way to get the `IEntityType` and `IProperty`. Is there something I'm missing?

**Comment by daniel-white** [comment]
here's what I have as a POC:

```
Expression expression = base.Process(query);
if (expression is ShapedQueryExpression shapedQueryExpression && shapedQueryExpression.QueryExpression is SelectExpression selectExpression)
{
   List<ProjectionExpression> projections = new List<ProjectionExpression>(selectExpression.Projection);

  for (int i = 0; i < projections.Count; i++)
  {
    ProjectionExpression projectionExpression = projections[i];
    if (projectionExpression.Expression is ColumnExpression columnExpression &&
        columnExpression.Name == "Name" && 
        columnExpression.Table is TableExpression tableExpression)
    {
      projections[i] = projectionExpression.Update(RelationalDependencies.SqlExpressionFactory.Function("upper", new SqlExpression[] { columnExpression }, typeof(string)));
    }
  }

  shapedQueryExpression.QueryExpression = selectExpression.Update(
    projections,
    new List<TableExpressionBase>(selectExpression.Tables),
    selectExpression.Predicate,
    new List<SqlExpression>(selectExpression.GroupBy),
    selectExpression.Having,
    new List<OrderingExpression>(selectExpression.Orderings),
    selectExpression.Limit,
    selectExpression.Offset,
    selectExpression.IsDistinct,
    selectExpression.Alias
  );
}
return expression;
```

I'd like to adjust the condition in the `for` loop

**Comment by daniel-white** [comment]
I've also seen that `EntityProjectionExpression` has all the information I need, but I dont see how I can extend and use that since it appears `SelectExpression` creates it.

**Comment by ajcvickers** [comment]
@smitpatel to respond

**Comment by smitpatel** [comment]
- Extending SelectExpression should be avoided. It contains a lot of metadata and internal logic. At best extending is allowed only if you are adding something additional (like query hint or so).
- If you want to make any changes to ExpressionTree before translation where you can search for metadata too, it is `QueryTranslationPreprocessor`
- Translate phase gives you metadata and requires to generate a SQL tree out of it. You can do some changes by overriding provider specific SqlTranslatingExpressionVisitor
- SqlTree changes happen in `QueryTranslationPostprocessor` since this is SQL tree, it does not contain any metadata about EF Core by design.

So what you have above as work-around is probably, best you could do. If we see enough feedback and demand for modification then we would consider adding extension point. For now, above is what we have.
