### ISSUE TITLE
Code analysis throwing CA1062 on generated migrations

### ISSUE THREAD

**Issue by MattRuwe** [dotnet/efcore#18277]
After generating a new EF migration, I started getting code analysis errors stating:

In externally visible method 'void Initial.Up(MigrationBuilder migrationBuilder)', validate parameter 'migrationBuilder' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.

The generated code is not validating the 'migrationBuilder' parameter for null values which causes my code analysis to throw an error.  I can work around this by adding #pragma warning disable CA1062 to the top of the file, but I don't want to do this every time I add a new migration.  Is there a way I can change the way the code-gen works?

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10.0.15063
IDE: Visual Studio 2019 16.3.2

**Comment by ajcvickers** [comment]
@MattRuwe We don't believe such a check is needed given the design or this class and method when used in any reasonable (i.e. not convoluted) way. Therefore we are reluctant to add additional code to every generated migration for this. If there is some specific reason (other than the analyzer says so) that would make adding this code useful, then please provide more details and we will reconsider.

Since the migration is one-time generated code that is intended to then be edited, it seems not unreasonable that you could add this check yourself along with other changes needed if it seems valuable to you.

**Comment by dferretti** [comment]
Would it be worth having EF Core add a `DiagnosticSuppressor` for this? Similar to how the [uninitialized DbSet suppressor](https://github.com/dotnet/efcore/blob/f9139ada3c8ecfed2c2b5d8aa8c4c267092a0725/src/EFCore.Analyzers/UninitializedDbSetDiagnosticSuppressor.cs) works?

**Comment by roji** [comment]
We've discussed the possibility of having EF drop an .editorconfig with the various suppressions, that's a better (and much simpler) approach than a diagnostics suppressor.

@ajcvickers do we have an issue tracking the editorconfig feature?

**Comment by ajcvickers** [comment]
@roji Not yet; I'm still investigating.

**Comment by dferretti** [comment]
If I already have a rule like this in my globalconfig:
```
dotnet_code_quality.CA1062.excluded_type_names_with_derived_types = T:Microsoft.AspNetCore.Mvc.ControllerBase
```
and EF adds another for `T:Microsoft.EntityFrameworkCore.Migrations.Migration`, will the 2 rules combine so both types are excluded? The [precedence rules](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#precedence) makes me think that one would override the other since they have the same key, but I am not positive.
