### ISSUE TITLE
Two different ways of writing the query conditions, the translation statements are inconsistent

### ISSUE THREAD

**Issue by Varorbc** [dotnet/efcore#18349]
Two different ways of writing the query conditions, the translation statements are inconsistent

### Steps to reproduce

```csharp
var a = dbContext.Test.Where(a => !a.IsDeleted).FirstOrDefault();

SELECT TOP(1) [b].[IsDeleted]
FROM [Test] AS [b]
WHERE ([b].[IsDeleted] <> CAST(1 AS bit))

var b = dbContext.Test.Where(a => a.IsDeleted == false).FirstOrDefault();

SELECT TOP(1) [b].[IsDeleted]
FROM [Test] AS [b]
WHERE ([b].[IsDeleted] = CAST(0 AS bit))

```

### Expected behavior

The translation statement is consistent and uses the second

### Further technical details

EF Core version:3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system:Win10
IDE: Visual Studio 2019 16.3

**Comment by REscobar** [comment]
If `IsDeleted` is nullable, the expected behaviour is those two different queries

**Comment by ajcvickers** [comment]
Agree with @REscobar

**Comment by Varorbc** [comment]
@ajcvickers If an index exists in'IsDelete', the use of it is not equal to a query, which will cause the database to be unable to use the index query. In addition, these two queries express a meaning. Why do we get two different queries? In addition,'IsDelete == false'will be recommended by Vs as'! IsDelete'

**Comment by ajcvickers** [comment]
@Varorbc Is `IsDeleted` a nullable property?

**Comment by Varorbc** [comment]
@ajcvickers not

**Comment by smitpatel** [comment]
`a => !a.IsDeleted` gets translated like follows
- `!a.IsDeleted`
-> `!(a.IsDeleted == true)`
-> `a.IsDeleted != true`

Second query gets translated as is. so `IsDeleted == false`.
We translated the query as it was written. It may be same when reading but they do not come as the same thing in expression tree for sure.

**Comment by Varorbc** [comment]
@smitpatel For users, they may not know about this, but think they get the same results. Is it possible for different expression trees to get the same result

**Comment by smitpatel** [comment]
@Varorbc - My question would be why it matters to a user if both queries are getting the same results. Both queries are equivalent in C# and they are equivalent in SQL. If the performance is important for user then queries need profiling to figure out where things can be improved. You are aware that first query could not use index so you want to optimize it but same can be said for C# also. Implementation of `!` and `== false` may have different performance in C# too. Profiling is way to figure out when to use either of that.
Further the first query would be translated in non-SqlServer providers as `NOT(IsDeleted)`. Does that use index? Should we also convert that kind of thing?
While it is possible to convert one expression tree to another but things start to get really messy when there are null semantics. If `IsDeleted` is nullable then both of them may not be even equivalent.
As a user, you know that equality comparison will be able to use the index hence you should write LINQ in that form. It would be easier to understand if EF Core did less magic during translation.
We will re-discuss this issue in triage if we want to make any changes but keep in mind we are talking about correctness vs performance here. So performance gets slightly lesser priority.

**Comment by Shane32** [comment]
I've run into the same issues with queries in EF -- indexes are not utilized because it's common to write `!obj.Deleted`, and the filtered index was written as `Deleted = 0`.

I do like the fact that EF translates LINQ queries as literally as possible.  It's simply unfortunate that in this unique scenario, a less literal translation would be better (assuming the field was not nullable).

As a developer using SQL, I'd be happy if `!(bit)` was translated to `bit = 0` for non-nullable fields, but if I was in your shoes, I might not want to add special code for every edge case.

**Comment by ajcvickers** [comment]
We discussed this in triage and the general feeling is that, other than for correctness, we should translate what was written as closely as possible, especially where doing otherwise will perform differently on different back ends. However, we could revisit this if we find many people falling into a performance trap because of this.
