### ISSUE TITLE
EF Core 3 - Skip() not working

### ISSUE THREAD

**Issue by jorgesoprani** [dotnet/efcore#18654]
Paging is not working on my queries:

### Steps to reproduce

![image](https://user-images.githubusercontent.com/19509475/67868021-0d20aa00-fb0a-11e9-9e69-4d2a8d6f6897.png)

I'm using the UseRowNumberForPaging option, but seems to be ignored.
I'm using EF Core 3.0.0 with SQL Server 2008 R2. Aand this is how its configured.
![image](https://user-images.githubusercontent.com/19509475/67868039-14e04e80-fb0a-11e9-8ef8-efe6c6265f62.png)

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
SQL Server Version: 2008 R2

**Comment by smitpatel** [comment]
@sfrobous - EF Core 3.0 does not support row number paging. https://github.com/aspnet/EntityFrameworkCore/issues/16400 is tracking to bring back support for it.
In the meantime, I have filed https://github.com/aspnet/EntityFrameworkCore/issues/18667 to obsolete the method so that as a user you get better error message that it is not supported.
