### ISSUE TITLE
Using in memory db when saving a set of objects with foreign keys 

### ISSUE THREAD

**Issue by twDuke** [dotnet/efcore#18698]
When saving a set of objects with keys not under db context control, in memory database throws exception when saving changes thinking that the objects do not exist. 
Worked in version 2.6.

### Steps to reproduce
https://github.com/twDuke/ef-core-in-mem-bug

### Further technical details

EF Core version: 3.0.0
Database provider: InMemory
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2019 16.3.3

**Comment by ajcvickers** [comment]
This is due to an [intentional change made in 3.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dc) that brings DetectChanges into alignment with attaching entities with regard to how generated key values are interpreted.

This discussion may also be helpful: https://github.com/aspnet/EntityFrameworkCore/issues/18055#issuecomment-546068893
