### ISSUE TITLE
Reconsider breaking change policy

### ISSUE THREAD

**Issue by Neme12** [dotnet/efcore#18721]
I was honestly a little surprised by the number and character of breaking changes in .NET Core 3.0

Yes, .NET Framework had a tremendous disadvantage in that almost nothing could be changed, fixed or improved and compatibility was to be taken extremely seriously as any minor bug fix could break millions of existing applications because of a single shared global runtime.

.NET Core was a promise that we could finally get rid of that burden and move forward and expect awesome new features. improvements and fix old warts that couldn't be fixed before. But (out of frustration of course) I'm wondering if it's gone too far. There has to be a middle ground.

The example I want to highlight and where I find it hard to see the benefit of a breakage is this:

We asked for nullable owned entities, but not for that to suddenly become the (*unchangable*) default. Yes, we asked for nullable owned entities but didn't ask to get rid of required owned entities. Now, instead of having owned entities be present like before, I just get `null`. Patching this is definitely not a small or trivial fix and requires updating code all over the project in almost all places that the entity is queried and carefully rethinking how the change will affect this.

I honestly can't see how this is an improvement in behavior at all, let alone it being an improvement that has  **so much benefit** to justify make it a breaking change, as opposed to an opt-in. Or at the very least... adding a way to opt-out.

I especially find it hard to believe that this is now the default and unchangable behavior because it has so many bugs: #17935 #18718. Even the most basic usage like updating an owned entity no longer works. They're completely unusable in 3.0. Has this even been tested? I get the impression that it hasn't, or that nobody uses .NET anymore, because googling these issues didn't give any results and it feels like I'm the only person to be using this, which is frustrating.

**Comment by ajcvickers** [comment]
@Neme12 Thanks for the feedback--I answered a similar question here: https://github.com/aspnet/EntityFrameworkCore/issues/18256#issuecomment-540109273

There is always a balance between breaking for a better experience long-term, and not breaking to keep existing applications running. For 3.0, we may have erred too much on the breaking side, but it will likely take some time before we can really tell, since the breaks support long-term goals.

We have more 50,000 tests that run for each platform on each build, so yes, we do test. Also, the numbers I have seen indicate many developers already using EF Core 3.0. (Nuget package download counts, which are public, also indicate this--this morning we were getting close to half a million downloads of EF Core 3.0.)
