### ISSUE TITLE
AddAsync but no UpdateAsync ?

### ISSUE THREAD

**Issue by Davilink** [dotnet/efcore#18746]
It's more a question than a bug. After reading the difference between DbSet.Add() vs DbSet.AddAsync(), i was wondering why DbSet.UpdateAsync doesn't exists, because : 

Extract of the doc for DbSet.Update()
>  For entity types with generated keys if an entity has its primary key value set
        //     then it will be tracked in the Microsoft.EntityFrameworkCore.EntityState.Modified
        //     state. If the primary key value is not set then it will be tracked in the Microsoft.EntityFrameworkCore.EntityState.Added
        //     state. This helps ensure new entities will be inserted, while existing entities
        //     will be updated

So if a update an entity that has a the default value has the primary key, the EntityState. will be set to Added, will it cause a problem if we use the SqlServerValueGenerationStrategy.SequenceHiLo ?

**Comment by ajcvickers** [comment]
@Davilink In that scenario, the database could occasionally be accessed synchronously.  A few follow-up qustions:
* Are you seeing this cause functional issues in your application?
* If so, have you considered using a bigger interval on the sequence to minimize the database access from Update?
* Related to the previous question, what is your primary motivation for using SequenceHiLo?

**Comment by Davilink** [comment]
To be honest, i don't have this issue at this moment, because i don't use this strategy. I was only wondering why there was not updateAsync, is it something that you forgot or it just a edge case that wasn,t not worth the effort. It was only by curiosity.

**Comment by ajcvickers** [comment]
@Davilink When AddAsync was implemented it wasn't an issue, since Attach/Update would never mark an entity as Added, and therefore never accessed the database. When that change was made, we could have gone back and added AttachAsync and UpdateAsync at that time, but we didn't because, as you alluded to:
* SequenceHiLo is not commonly used, and even less commonly used correctly
* AddAsync (as opposed to just Add) is commonly used when it is not needed
* Parallel async methods create more maintenance and increase the risk of a fix being missed in one path or the other
* There are workarounds (e.g. Making sure Added entities are explicitly Added first.)
* The implications of using the sync version are not very bad anyway

**Comment by Davilink** [comment]
Ok
