### ISSUE TITLE
Separate EF roadmap from .NET Core 

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/efcore#18764]
Next version of .NET Core scheduled for November 2020. this means not add new features to EF Core for one year, while if developing it separated from .NET Core can releasing next version(4,5) very soon before next .NET Core. 
Many request features that very important in real projects remained in the Backlog. please change policy and listen user voices!

**Comment by ajcvickers** [comment]
@mojtabakaviani EF typically has three types of releases:
* Major versions
* Minor versions
* Patches

For the patches, we are planning to be able to release more quickly that .NET Core as a whole is able to. However, we haven't got there yet, and it still might not work out this way.

For major versions, we will likely still be tied to the .NET Core releases, at least for the time being. There are advantages (both technical and business) in doing this.

For minor versions, we don't intend to do a release between 3.1 and 5.0 because the important things we need to work on will take us that length of time to do. Looking further into the future we might consider additional minor versions, but we'll have to see how everything works out after 5.0.

Also, the primary reason for important features being in the backlog is not the release schedule but rather having people available to work on these features.

**Comment by mojtabakaviani** [comment]
I know these. But in major's version just add some features and we must wait one year for next version, if project is open source contributers and issuers must assign next features and roadmap, now is a public source! Anyway i will hope speedup version releasing.
