### ISSUE TITLE
Query: simplify IndexOf translation

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#18773]
Currently query like:

```cs
es.Where(e => e.NullableStringA.IndexOf("oo") == e.NullableIntA).Select(e => e.Id)
```

gets translated to:

```sql
SELECT [e].[Id]
FROM [Entities1] AS [e]
WHERE (CASE
    WHEN N'oo' = N'' THEN 0
    ELSE CHARINDEX(N'oo', [e].[NullableStringA]) - 1
END = [e].[NullableIntA]) OR (CASE
    WHEN N'oo' = N'' THEN 0
    ELSE CHARINDEX(N'oo', [e].[NullableStringA]) - 1
END IS NULL AND [e].[NullableIntA] IS NULL)
```

This seems too complicated. While it's true that **if** argument is and empty string we can short circuit and not compute the result of CHARINDEX function it doesn't seem too common (usually queries are on indexof different than emtpy). 
Another reason might have been that for cases when target is null, and argument is empty string we return 0, rather than null (i.e. any string starts with empty string - which is consistent with out mental model of null meaning unknown value). However this scenario is invalid on c# already (null ref) and seems like sacrificing 99% scenario for the sake of 1%.

Instead, we could simply translate to:

```sql
SELECT [e].[Id]
FROM [Entities1] AS [e]
WHERE CHARINDEX(N'oo', [e].[NullableStringA]) - 1 = [e].[NullableIntA]
OR (CHARINDEX(N'oo', [e].[NullableStringA]) IS NULL AND [e].[NullableIntA] IS NULL)
```

which, once #18555 is done, can be further optimized to:

```sql
SELECT [e].[Id]
FROM [Entities1] AS [e]
WHERE CHARINDEX(N'oo', [e].[NullableStringA]) - 1 = [e].[NullableIntA]
OR ([e].[NullableStringA] IS NULL AND [e].[NullableIntA] IS NULL)
```

**Comment by maumar** [comment]
Also this scenario yields different results between SqlServer and Sqlite, when the argument to IndexOf is empty string, i.e.

```cs
es.Where(e => e.NullableStringA.IndexOf("") == e.NullableIntA)
```

Sqlite produces:

```sql
SELECT "e"."Id"
FROM "Entities1" AS "e"
WHERE ((instr("e"."NullableStringA", '') - 1) = "e"."NullableIntA") OR (instr("e"."NullableStringA", '') IS NULL AND "e"."NullableIntA" IS NULL)
```

**Comment by ajcvickers** [comment]
Theoretically, could do fancy parameter snipping to special case empty string.

**Comment by ranma42** [comment]
Currently the translation for

```csharp
ss.Set<NullSemanticsEntity1>().Where(e => e.NullableStringA.IndexOf("oo") == e.NullableIntA).Select(e => e.Id)
```

(see [here](https://github.com/dotnet/efcore/blob/77097ee99a12b6b87b606d7d8f56f68f91a04f12/test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs#L940)) is

```sql
SELECT [e].[Id]
FROM [Entities1] AS [e]
WHERE CAST(CHARINDEX(N'oo', [e].[NullableStringA]) AS int) - 1 = [e].[NullableIntA]
OR ([e].[NullableStringA] IS NULL AND [e].[NullableIntA] IS NULL)
```

(see [here](https://github.com/dotnet/efcore/blob/main/test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs#L1611-L1613)).

Is there any further improvement that we should look for? (I see that there is a `CAST` in addition to the expected query)

Regarding the mismatch in the results from SQLite and SQL Server, it was apparently caused by the non-propagation of `NULL` when the pattern was the empty string; I tried to fix it in https://github.com/dotnet/efcore/pull/33876.
