### ISSUE TITLE
Database First code generation won't trigger if project can't compile

### ISSUE THREAD

**Issue by Q-Tec90** [dotnet/efcore#18780]
Hello,
I just had an issue with the generation for the entity classes as well as the context class.
Mostly I am working with database first and while testing out the new ef core I had multiple issues.
1) The ef tool is no longer default in the dotnetcore sdk. Took me some time to undestand the fact that it has been moved out and needs to be installed additionally.
2) if you are working on an project which is in a state where it can not be compiled successfully you 
can not generate the entity class or the context because currently a success build seems to be a requirement before he generates those files.
Sometimes I have changes in the database and need to sync it with my code again. I do not see a valid reason why a successful build is required in order to generate code classes out of a database.
![BuildFailed](https://user-images.githubusercontent.com/54884618/68300790-c6e5c080-009e-11ea-9c79-bfd6ea6965ea.jpg)
![BuildFailedDetail](https://user-images.githubusercontent.com/54884618/68300792-c77e5700-009e-11ea-9ca9-5bf22f0d7997.jpg)

Add another parameter for the ef tool which allows to generate the files without the requirement for a successful build. Maybe there is already something similiar and I wasn't able to find it.

**Comment by ErikEJ** [comment]
Just use EF Core Power Tools (disclaimer: I am the author)

**Comment by ajcvickers** [comment]
Related to #9716
/cc @bricelam

**Comment by bricelam** [comment]
We load the provider, design, and plugin assemblies via the project and give you a hook to customize the design-time services (e.g. use a custom pluralizer or code generator).

Without this, we’d need to duplicate a lot of the work of NuGet and MSBuild.

I love that the PowerTools don’t need to build the project, but it comes at a cost—they have to include all the provider and plugin assemblies and there is no hook to customize the services.

**Comment by ErikEJ** [comment]
No hook? You can customize some services via the configuration UI / JSON file

**Comment by bricelam** [comment]
I just mean you can’t, for example use a custom implementation of IPluralizer. All the extensibility has to be implemented in the PowerTools

**Comment by Q-Tec90** [comment]
Thank you all for the responses.
@ErikEJ Thank you. It does look solid.

I really do miss the the edmx designer which is using t4 for generation. It sure had its own issues but overall an awesome utility for Database First Models. One click and he generated everything new regardless of the project he was in.

**Comment by bricelam** [comment]
Re-opening. I want to discuss some possibilities with the team

**Comment by bricelam** [comment]
For example, there is a hidden `—no-build` option that will probably just work most of the time with `dbcontext scaffold`. We could document it for that command explaining the caveats

**Comment by ajcvickers** [comment]
Note from triage: document `--no-build` and it caveats in the `--help` for the command, and also add update the doc page.

**Comment by jeremycook** [comment]
Not sure if this should be a separate issue, so I'm starting here.

I can imagine it being helpful to be able to specify a minimalist project that simply provides custom implementation code like an IPluralizer or an IConfiguration with a connection string to support Name=ConnectionStringName. It would not take a dependency on the project that the database context and models are scaffolded into. This would be to ensure it could build and be used by the scaffolder even when the scaffolded project can't compile.

**Comment by bricelam** [comment]
@jeremycook This should be possible today:
```sh
dotnet ef dbcontext scaffold ... --startup-project ../MinimalistProject/

# or

cd MinimalistProject/
dotnet ef dbcontext scaffold ... --output-dir ../ActualProject/
```

**Comment by jeremycook** [comment]
@bricelam  So close...one side effect is the namespace is the project name, in this case it ends up as "MinimalistProject". I can hack around it by naming the minimalist project ActualProject.Data where my output directory will be ../ActualProject/Data if ran from within the MinimalistProject folder. That definitely feels hacky and would be confusing to someone unfamiliar with why the project got **that** name since it doesn't actually hold the data models and context. I looked through the docs but don't see an option for customizing the namespace.

**Comment by bricelam** [comment]
Ah, we have an issue somewhere to let you specify the namespace in the command

**Comment by ErikEJ** [comment]
@jeremycook EF Core Power Tools solves all the issues you describe...

**Comment by bricelam** [comment]
The Power Tools let you provide your own implementation of IPluralizer and read connection strings from configuration?

**Comment by ErikEJ** [comment]
@bricelam sorry, missed that part. Only solves the namespace part.

**Comment by ErikEJ** [comment]
EF Core Power Tools provides 2 pluralizers, the EF6 one and Humanizer.Core

**Comment by iGanja** [comment]
This no-build switch is not available to me, using EntityFrameworkCore 5.0.4 on Visual Studio Pro 2019.
This seems to be a no-brainer feature. I have a broken DBContext for which I have to re-scaffold to fix. of course because the DBContext itself is the reason the project won't build, I am now in a Catch 22. I need to build my project before I can scaffold, but the scaffolded context is broken and the project won't build.
I can think of work-arounds that require a lot of work, same as literally commenting out every line of code that references the broken dbcontext, OR we could re-establish a feature we database first guys have come to rely on...

**Comment by I4-PJ** [comment]
Hi, from time to time I am solving similar issues. Would be so helpful giving more support to database-first guys. (i can not imagine myself making a high performing database schema with view, triggers and those fancy things with code-first.

**Comment by motohead400** [comment]
I'm trying the --no-build option and keep getting the message of "A positional parameter cannot be found that accepts argument ..." no matter where I put it.  It's ridiculous it requires the project to build in order to generate the context.  In my case, like iGanja mentioned, the reason the project won't build is because I need to recreate the context.  I'm using EF Core 5.0.8 and VS2019 16.11.1.  Now I have to jump through a bunch of hoops of commenting things out so the project will build so that I can just recreate the dbcontext....

**Comment by dsTny** [comment]
[@motohead400]
I have the same issue. Are you also using Oracle (Oracle.EntityFrameworkCore)?

**Comment by motohead400** [comment]
@dsTny 
Nope, SqlServer.

**Comment by ErikEJ** [comment]
@Kurti123 EF Core Power Tools? (does not require anything to be building)
