### ISSUE TITLE
InMemory: Expansion weak entities in OrderBy/ThenBy should happen together

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#18912]
OrderBy_collection_count_ThenBy_reference_navigation

**Comment by RamunasAdamonis** [comment]
I ran into this issue while migrating my project from `.Net Core 2.2` to `.Net 5.`

Following expression was working with `EF Core InMemory` version `2.2.3`, but does not work anymore in `5.0.1` (also checked `3.1.3` not working as well). 

                var products = await context.Products
                    .OrderBy(x => x.ProductType)
                    .ThenByDescending(x => x.Price.Amount)
                    .ToListAsync();

_*Price is Owned entity_

 Same error as in #22732

**Comment by smitpatel** [comment]
new regression test
```C#


        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Owned_navigations_are_expanded_for_OrderBy_ThenBy_together(bool async)
        {
            return AssertQuery(
                async,
                ss => ss.Set<OwnedPerson>()
                    .OrderBy(e => e.PersonAddress.PlaceType)
                    .ThenBy(e => e.PersonAddress.Country.Name),
                assertOrder: true);
        }
```

Old one works correctly now since it is weak type which uses STET.

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.
