### ISSUE TITLE
RelationalTypeMapping in SqlExpressionFactory

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#18978]
What is the logic/reasoning behind sometimes `RelationalTypeMapping` being optional in `SqlExpressionFactory` and sometimes not? I.e. `MakeBinary` vs. `Coalesce`.

**Comment by smitpatel** [comment]
It follows suite from LINQ tree. For specific expression typeMapping is optional. In some cases it is not needed or would be inferred from inner already. In some cases it may be needed to be passed hence optional. For MakeBinary where it can create various different SQL, typeMapping is not optional. You can pass null value if you don't have outer type mapping to propagate but that is intentional decision.

**Comment by cincuranet** [comment]
> It follows suite from LINQ tree. 

Can you elaborate on that?

**Comment by smitpatel** [comment]
Expression.MakeBinary vs Expression.Coalesce. Specific expression only takes facets which are relevant. LINQ uses overloads we used optional parameters.

**Comment by cincuranet** [comment]
Thanks.
