### ISSUE TITLE
SqlExpression.Print purpose

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#19032]
What's the purpose of `SqlExpression.Print` when having custom expressions? The more or less same logic is then in `QuerySqlGenerator` derived class. 

I don't like duplication, so I'd like to know the reasoning behind it, before I start any refactoring on my side.

**Comment by ajcvickers** [comment]
@maumar to respond.

**Comment by maumar** [comment]
Print is the method that ExpressionPrinter uses to render a given custom expression. We use the printer heavily in debugging and for printing expression/query plans when exception happens. Ideally the expression printer to knows how to print every expression it can encounter and IPrintable is our extension mechanisms when providers add their custom nodes.

We don't want to use sql generator because we don't want to inject sqlgenerator to the expression printer (we wan't the print operation to be static).

**Comment by smitpatel** [comment]
Also IPrintable is for core level vs QuerySqlGenerator is relational specific. So any custom expression in core cannot use sqlGen.
