### ISSUE TITLE
Translate to sql at compile time

### ISSUE THREAD

**Issue by AutumnEvans418** [dotnet/efcore#19121]
## EF Core vs Dapper
I often use EF Core and dapper together in projects depending on how certain queries perform and how fast I need them to be.  EF Core is slightly slower due to translating sql at runtime, while dapper does not have to perform this operation.  It would be nice to not have to compromise typed queries and speed.

## Generate Sql at compile time
I think it would be awesome if we could generate our ef core queries into sql queries at compile time.  This would increase the performance of EF Core without sacrificing usability.  
I have been working on a prototype using Microsoft.CodeAnalysis to inject code into assemblies.  The compiled queries could be controlled by having something like ```[CompileQuery]``` on top of the class, method, or for an entire assembly.  I have done some benchmarks and doing something like this performs better than Compiled queries.

I was wondering if this is something that would be practical and if there are some tools in the EF Core codebase that might help with building something like this.  For example, I know that there is tools to generate DbContexts and the needed classes.

**Comment by roji** [comment]
EF Core only generates SQL queries the first time that a LINQ query is executed, and caches that. The second time that the same query is executed (even with different parameter values), the cached SQL is reused without having to regenerate the SQL. There are some important missing details in this description but overall it's correct for the purpose of this discussion. Generating SQL queries could still make sense in order to reduce application *startup time*, but would not affect *stable run time* (which is perf after queries have already been compiled). See #1906 and #16496 about this.

Now, there's still an overhead of getting to the cached SQL. If perf is extremely important to you, you can use [compiled queries](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#explicitly-compiled-queries) to avoid that as well.

Beyond that we're aware that EF Core's runtime performance can be improved, and this is one of areas of focus for the 5.0.0 release.

Hope that explains the situation, if I've misunderstood you suggestion please post back - will leave this open for a bit.

**Comment by aguerrieri82** [comment]
I think in most real-world scenario this would be very complicated, expecially in dynamic query that depends on variables not known at compile time ( i refer mainly to not-static "where" / "order by" condition, that canno't be mapped as parameters)

example:

```c#
var query = (IQueryable<MedicalReportSection>)dataContext.MedicalReportSections;

if (!string.IsNullOrWhiteSpace(command.Filter.Text))
{
	query = query.Where(a => (a.Name).Contains(command.Filter.Text))
		   .OrderBy(a => a.Name.IndexOf(command.Filter.Text));
}
else
	query = query.OrderBy(a => a.Order).ThenBy(a => a.Name);
```
an access to a related entity will cause an additional join in the middle of the query, hard to manage statically.

**Comment by roji** [comment]
> I think in most real-world scenario this would be very complicated

What exactly do you think would be very complicated? Most of what I referred to above is already implemented and working.

In any case, the example you gave above isn't really a dynamic query scenario - it's just a scenario with two query structures. The moment one of these is executed, it is compiled and then cached - just like with any normal query - and will then be reused. EF already handles these in an efficient manner. It's true that this could present some significant challenges to any design-time optimizations (which again, would only help startup performance and not stable query execution times), but we're far from that in any case.

Note that it possible to produce "truly dynamic" query structures, e.g. where the number and/or composition of Where predicates depends on variables which change all the time. This kind of scenario is rare/exotic, and pretty much impossible to handle in an efficient way, since at some point each query structure has to be compiled independently. It also wouldn't be possible to do any sort of design-time optimization here, since nothing is known at design-time.

**Comment by aguerrieri82** [comment]
Don't want to generate a flame, I speak because in one of my projects i had to write something similar :)
In some query you have to filter / order a set based un user-defined criteria. In a simple if/else scenario you have only two cases. In 5 if scenario (each one is an optional criteria), you must take in account all 5 combinations 00001 - 00010 - etc (1/0 = criteria on/off, 2^5 = 32 combinations)
Or dynamic concat the strings in order to add all the pieces in the select /where / from / order by statements.
In EF each criteria is stored in memory once is added, so in the end you can optimize what you have, and easly translate in that unique sql query

**Comment by chrisevans9629** [comment]
After doing some benchmarks, it seems that compiled queries perform better than I thought.  The performance is comparable to Dapper.  
Is there a reason for compiled queries to be static funcs?  It'd be neat to get the benefit of compiled queries while just writing standard linq.

**Comment by roji** [comment]
@aguerrieri82 no worries about starting a flame :) There's nothing inherently wrong with dynamically constructing queries, you just need to be aware of the perf impact of that. 32 combinations isn't that much - EF Core will compile these 32 combinations and cache them internally without any issue, this should already work quite efficiently. On the other hand, if you allow for a totally open dynamicity which can lead to query explosion, you may encounter a severe perf degradation as EF is constantly forced to compile different query structures. I don't really think there's anything we can do about this. Again, none of this is really directly related to this issue ("translate to SQL at compile time").

@chrisevans9629 good to hear that you're seeing good perf with compiled queries. Compiled queries *are* expressed via standard LINQ - but you have to provide that LINQ once and tell EF Core to compile it. In the normal non-compiled case where you just use LINQ inline, EF Core receives a LINQ expression tree and has to look it up in its internal cache; this step can be quite heavy perf-wise, and the whole point of compiled queries is to avoid it.

**Comment by roji** [comment]
I'm not sure this issue currently adds new information beyond what is already present in issues like #1906 and #16496, so I'll go ahead and close it for now. However, we can continue the conversation here and if something new comes up, we can reopen.

**Comment by ajcvickers** [comment]
@roji AOT is the other situation where doing this at compile time is useful because then we can compile the needed materialization delegates rather than generating and compiling them dynamically. If we do something like this, which I hope we will, then I think that will be the primary motivator, even above startup perf. I suspect compiled models is likely to be the biggest win in startup perf.

**Comment by roji** [comment]
Yeah. I admit my thinking about compiled models tends to focus on the negatives (but I haven't been in these conversations):

* We get shapers, but only when the full entity gets projected out; when a query projects out arbitrary columns we lose this. I hope that doesn't mean we can't project out when on AOT.
* Even related entities seem to make this difficult: unless we pregenerate shapers for all possible permutations of related entities (blogs alone, blogs with posts, blogs with posts and comments...), we again lose the advantage.
* Unless I'm mistaken, we'd still need to go through query compilation for SQL generation. I'm not sure how much time goes into shaper generation/compilation vs. the rest of compilation, but if we're doing AOT it would be great if we could also cache the SQL. Ideally, at application startup we'd have everything we need.

So I tend to think more towards an approach that would analyze code, identify queries and somehow generate shapers and SQL from them at design-time (this could hopefully be made possible via the new code generators coming in C# 9). That may be overly ambitious or I may be missing various aspects of the problem.

**Comment by ajcvickers** [comment]
@roji Is your point to distinguish compile-time from design-time?

**Comment by roji** [comment]
Not really... My point is more that if we go into either compile-time or design-time as a way of speeding up startup times and unlocking certain AOT-only scenarios, doing so via the model only (without looking at queries) may simply not be sufficient...

**Comment by roji** [comment]
(hope I'm making sense)

**Comment by ajcvickers** [comment]
@roji I think we will likely have to do both. However, there are two different things in play here:
1. Reducing the amount of work done at startup
2. Fast execution of queries on an AOT-only platform

The first is likely dominated by model building and isn't directly related to AOT. The second is specific to AOT and is likely dominated by interpretation of IL on query execution.

**Comment by roji** [comment]
OK, makes sense. I'm guessing that means that just pure model building (executing conventions etc., unrelated to any query execution) is enough of heavy task that it's worth going into compiled models (or rather, serialized models?). I'm interested in how much of startup time is dominated by model building vs. query compilation though, we should measure at some point on a reasonable scenario.

**Comment by ajcvickers** [comment]
@roji Historically start-up time in EF Core has been dominated by model building. In EF6 view generation was also a big problem. Query compilation could also be a problem but this is probably much less common than model building perf.
