### ISSUE TITLE
OrderBy discarded when followed by Distinct in 3.x but not 2.x

### ISSUE THREAD

**Issue by chrarnoldus** [dotnet/efcore#19130]
OrderBy is discarded when followed by Distinct in EF Core 3.x but not in 2.x. I doubt this change was intentional, since the new behavior is unpleasantly surprising in my opinion, even if it conforms to the specification of Distinct (which says that an unordered sequence is returned).

### Steps to reproduce

```c#
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

internal class Person
{
    [Key] public string Name { get; set; }
}

internal class PersonContext : DbContext
{
    public PersonContext()
        : base(
            new DbContextOptionsBuilder<PersonContext>()
                .UseSqlServer("Server=localhost;Database=Person;Integrated Security=True")
                .UseLoggerFactory(LoggerFactory.Create(builder => builder.AddConsole()))
                .Options
        )
    {
    }

    public DbSet<Person> Person { get; set; }
}

internal class Program
{
    private static void Main(string[] args)
    {
        Console.WriteLine(typeof(DbContext).Assembly);
        using var context = new PersonContext();
        context.Database.EnsureCreated();
        context.Person.OrderBy(p => p.Name).Distinct().Load();
    }
}
```

When executed using 3.1.0-preview3.19554.8, the executed SQL is:

```sql
      SELECT DISTINCT [p].[Name]
      FROM [Person] AS [p]
```

note that OrderBy was discarded altogether. Using 2.2.6, the SQL is:

```sql
      SELECT DISTINCT [p].[Name]
      FROM [Person] AS [p]
      ORDER BY [p].[Name]
```

which is what I would expect. 

### Further technical details

EF Core version: 3.1.0-preview3.19554.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
Notes from triage: while the translation here is technically correct it would be useful to preserve ordering when it is possible. This will be different for different providers--for SQLite we should be able to always preserve. For SQL Server we should be able to preserve when the the ordered columns are also the projected columns.

**Comment by chrarnoldus** [comment]
Closing, I doubt anyone still cares after 5 years.

**Comment by roji** [comment]
@chrarnoldus note the following sentence in [the docs on Queryable.Distinct](https://learn.microsoft.com/en-us/dotnet/api/system.linq.queryable.distinct?view=net-7.0#system-linq-queryable-distinct-1(system-linq-iqueryable((-0)))):

> The expected behavior is that it returns an unordered sequence of the unique items in source.

This is also the actual behavior of [the in-memory implementation of Distinct](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.distinct?view=net-7.0#system-linq-enumerable-distinct-1(system-collections-generic-ienumerable((-0)))). So while I understand that the breaking change from 2.x to 3.x was surprising, EF is translating in line with the documentation, and preserving existing ordering after distinct would actually cause some queries to be considerably slower (since the ordering would have to be reapplied in some cases).

So I'm leaving this closed as by-design.
