### ISSUE TITLE
dotnet ef * commands fail to build with BuildEvents referencing $(SolutionDir)

### ISSUE THREAD

**Issue by panayot-zhi** [dotnet/efcore#19170]
When using pre or post build custom event targets referencing $(Solution*) macro dotnet build fails and the variables appear as *Undefined*. Building from solution dir and from Visual Studio is working fine. Adding --project to command does not resolve the problem.

https://prnt.sc/q6irez

Output from dotnet build

https://prnt.sc/q6isbp

EF Core version: Microsoft.EntityFrameworkCore (2.2.6)
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework: .NET Core 2.2
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.7

**Comment by ajcvickers** [comment]
@panayot-zhi These are specific to Visual Studio; building at the command-line using `dotnet` does not support use of `$(Solution*)`.

However, if you are using Visual Studio, then you can use the [Package Manager Console commands](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell) instead. These should work because they use the VS build.
