### ISSUE TITLE
Multiple in memory databases have overlapping data

### ISSUE THREAD

**Issue by kwebb-bis** [dotnet/efcore#19184]
While using multiple in memory databases, I would expect that each individual database would keep separate data. However, I am seeing that adding data in one database, will add that data to every database.

E.G. Create an in memory database where databaseName = "A". Add 2 rows to database "A" table "items" and the count says that there are 2 entries in items. Create another in memory database where databaseName ="B". Adds 3 rows to database "B" table "items" and the count says that there are 5 items, not the expected 3.

### Steps to reproduce

I have created a small sample project here: https://github.com/kwebb-bis/EFCoreTestFailure

Within the unit tests I am creating an in memory database, using a new guid as the database name, for each test. The tests each add a range of objects to a database table and then perform an assert on the count of objects in the table. The first test passes as expected and the remaining tests fail, with the count containing the sum of objects added by other tests. 

I am both using the test initialization to create the databases, and creating the databases within each test, and both yield the same result. 

### Further technical details

EF Core version: 3.1
Database provider: Microsoft.EntityFrameworkCore.InMemory
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.4

**Comment by ajcvickers** [comment]
@kwebb-bis The first time that `SetUpTestBed` is called it starts tracking `Status` entities. Later the the context is used to track `Task` entities that reference the Status entities. This results in fixup of the navigation property on each Status entity to reference the related Task.

The same Status entities are used the next time the setup is run. Since these now reference the Tasks it results in these also being tracked by the context and saved to the database.
![image](https://user-images.githubusercontent.com/1430078/70357470-d8e88980-182b-11ea-9873-f04d860cf8f0.png)

I would suggest not sharing the same Status instances between tests.

**Comment by kwebb-bis** [comment]
That helped me get it working, thank you. I have posted a new file `UnitTestPassing.cs` to the repo for anyone else having this issue to see how it needs to be done.

It looks like the same object needs to be referenced throughout the single test, but a new object needs to be made for each test.

It still seems very odd to me that the navigation property will allow you to track objects across databases. If I am adding an object that tracks to a different database, that information should likely be sanitized.
