### ISSUE TITLE
Suggestion: add attribute to make type keyless

### ISSUE THREAD

**Issue by LostAsk** [dotnet/efcore#19246]
Now ViewModel（ReonlyModel） It can only be set through the fluent API.
I want to attribute that the entity is read-only through the feature.

To avoid having to call `HasNoKey`.

**Comment by ajcvickers** [comment]
Note for triage: specific case of #10864

**Comment by Joehannus** [comment]
When will this be implemented? Right now we are using DBQuery in our Azure based solution. And as I mentioned in #19509, we use .Net Framework as well as .Net Core - which does not allow us to use the Fluent API. In stead we use data annotations in our entity classes. Because DBQuery is obsolete in EF Core this even has as a consequence that we will not be able upgrade from .Net Core 2.x to 3.x.

**Comment by ajcvickers** [comment]
@Joehannus This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 5.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

We can continue the conversation on #19509 but I still do not understand why you can't just the model building API.

**Comment by smitpatel** [comment]
@AndriySvyryd - Pick a name. 😉

**Comment by AndriySvyryd** [comment]
`[Keyless]`
