### ISSUE TITLE
Why DbContext caching works the way it works?

### ISSUE THREAD

**Issue by webczat** [dotnet/efcore#19378]
Hello,
When looking at EF-core API I became curious about the reasons for some of the design decisions.
The DbContext is like a lightweight session object allowing database access. However there is no higher level object like DbContextFactory maintaining metadata/models/etc, the caching is mostly hidden, and done using caches instantiated as services in a special internal DI container, that is itself cached in a singleton. What is the actual reason for designing it like that instead of having an explicit disposable object that holds model/metadata and would be a source of DbContext instances?
In comparison, things like hibernate in java (I just don't know the NHibernate so can't comment, but probably same) has this distinction. Also other non EF things like the logging extensions, where you have loggers vs logger factories, and logger factory explicitly holds logging configuration. Of course this caching normally means you can never release and reload metadata or just make sure to shut everything down before app exit, at least not by default.
I know about a way to control the caching by providing service provider manually, but although it's nice it is possible and not really difficult, it is also quite non obvious and seems a bit hacky, like touching internals, at least for me.

**Comment by ajcvickers** [comment]
@webczat There are a couple of reasons we went this way:
* Low barrier of entry. Somebody new doesn't need to understand how to setup factories, etc. in order to get started. For common scenarios this is handled for you in a way that avoids common pits-of-failure.
* Continuity from previous EF versions which also used similar patterns. The way it was implemented in previous versions is completely different, but for someone coming from EF6 or earlier it works as expected.

However, EF Core was specifically designed to allow control of these things for those applications that want to to do so. When approaching this it's important to understand that the internal service provider and model caching are two separate things:
* The internal service provider acts as a root for a variety of internal caches. Not using these caches results in a massive performance hit, and most applications will only ever create one internal service provider, so it's usually best to just let EF manage this. It can be useful to control this for cases where explicitly flushing EF caches to free up resources is required.
* The model cache can hold multiple models built using the same EF configuration/service provider. This doesn't have to be used at all--`DbContextOptionsBuilder.UseModel()` can be used to supply a pre-built model. The model can be pre-built by creating a `ModelBuilder`, specifying the conventions to use. This model can then be cached any way the application sees fit.

See also: https://github.com/aspnet/EntityFramework.Docs/issues/1920

**Comment by webczat** [comment]
I was asking about specifically the *why* part, I was aware of the options I have for controlling caching and of the fact that model cache can cache different models, etc. Thanks for answerring my questions.
Not sure if I agree with point #1 as you normally still need to configure the context options, so creating a factory with the options and then DbContext doesn't seem much more difficult to understand, but... that's just my opinion.
Is using the same DI provider as the rest of application considered to be a bad practice? Just curious.

**Comment by ajcvickers** [comment]
> Is using the same DI provider as the rest of application considered to be a bad practice?

Yes.

**Comment by webczat** [comment]
actually, is there any reasoning for this being a bad practice? I mean it is not a default, but I don't see any drawbacks to it... except the fact that scoped EF services means something else than it would normally mean, that is, that scoped services requested by DbContext are not per request... and it is not the same scope as used by aspnet core.

**Comment by ajcvickers** [comment]
@webczat If you ensure that your application respects the services and scopes that it needs, and you're willing to react to changes in these things when a new version is released, then there is nothing stopping this working. However, there is usually very little overlap between the types registered in EFs internal service provider and the services registered by the application, so it's rarely advantageous to do this.

**Comment by webczat** [comment]
okay, thanks for explanation.
