### ISSUE TITLE
Test: InMemory and Value Comparers

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#19465]
https://github.com/aspnet/EntityFrameworkCore/pull/19406 added support and some logic
Though it had bug for EF.Property so no regression test. Also regression test for indexer property.

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.
