### ISSUE TITLE
Data Annotation equivalent of HasConversion

### ISSUE THREAD

**Issue by DrGriff** [dotnet/efcore#19471]
Whilst the Fluent API is great, it does have one limitation in that you code is not always "DRY".  In our application, we have many different Contexts, each small and bespoke to that particular feature.

If a property on an Entity requires a Conversion, then that's specific to the Entity, whatever Context it is used in.  Is there a data-attribute approach for the HasConversion so that we can write this just once in the Entity and not have to repeat it in every Context it's used in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@DrGriff We discussed this, but specifying the value conversion logic as part of the annotation doesn't seem very feasible. It would require specifying multiple expression trees in an annotation.

**Comment by RSadocchi** [comment]
Thanks @ajcvickers

**Comment by ajcvickers** [comment]
@RSadocchi I think you meant to thank @AndriySvyryd. 😄 

I was thinking about this, and you can always inject your own model building delegates. For example:

```C#
public class Program
{
    public static void Main()
    {
        var services = new ServiceCollection()
            .AddDbContext<SomeDbContext>(
                b => b.UseSqlServer(Your.ConnectionString)
                    .LogTo(Console.WriteLine, LogLevel.Information)
                    .EnableSensitiveDataLogging())
            .AddSingleton<Action<ModelBuilder>>(
                b =>
                {
                    b.Entity<Blog>();
                    b.Entity<Post>();
                })
            .BuildServiceProvider();

        using (var scope = services.CreateScope())
        {
            var context = scope.ServiceProvider.GetService<SomeDbContext>();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog());
            context.SaveChanges();
        }
    }
}

public class Blog
{
    public int Id { get; set; }
    public ICollection<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
}

public class SomeDbContext : DbContext
{
    private readonly Action<ModelBuilder> _buildAction;

    public SomeDbContext(DbContextOptions<SomeDbContext> options, Action<ModelBuilder> buildAction) 
        : base(options)
    {
        _buildAction = buildAction;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder) 
        => _buildAction(modelBuilder);
}
```

Which isn't quite what you want, but is perhaps an interesting pattern.

**Comment by vozeldr** [comment]
It drives me crazy that some annotations have been neglected like this "because it would be hard". In my opinion, this is ridiculous. 

The answer shouldn't be to split the entity configuration logic across multiple classes and files. Data annotations are supported for MaxLength, StringLength, Key, Required, etc. For most of my entities, I require no additional configuration outside of what's provided by annotations.

Then there are the outliers that have special cases like needing HasConversion. For those entities, I have part of the entity's configuration done with annotations on the classes' properties and a separate class that does the special HasConversion configuration.

I think this attitude should be revisited. Either obsolete data annotations or fully implement them.

**Comment by roji** [comment]
> It drives me crazy that some annotations have been neglected like this "because it would be hard". 

The problem with annotations is not that they're hard, it's that many things are simply impossible to represent via annotations - .NET attributes support only a very constrained set of things (e.g. literals), making it simply impossible to pass rich, arbitrary configuration. In contrast, the Fluent APIs - being regular .NET code - can support any sort of imaginable configuration.

> Either obsolete data annotations or fully implement them.

Why would we obsolete that's working successfully for many people, and cause all the disruption of forcing them to move away from it? The fact that data annotations would be limited - because .NET attributes are - was known from the very beginning, and there was no intention of making everyone possible with annotations.

**Comment by roji** [comment]
> You're telling me you can't possibly fathom how to implement an attribute that takes a type as a parameter? I know there are other uses of HasConversion that are more complex, but you've chosen to do nothing because you can't do everything?

It's clear that you're posting out of frustration, but please use a more respectful tone. I can absolutely fathom implementing an attribute a type as a parameter, but so far we have chosen not to do so, for two reasons. For one thing, very few people have requested it, so it's very low on our priority list (there are far more important things). For another, yes - since many value converter scenarios are not possible to express via attributes (e.g. because parameters need to be passed). Implementing support only for the very basic scenario would be very partial/inconsistent (some users would consider that "half-assing", as you wrote above).

> Obsoleting something by applying the attribute doesn't force anyone to do anything, it simply informs the developer that it's not the current preferred way of doing something and possibly will be removed in the future. Whole-ass one thing instead of half-assing two.

Nothing is half-assed here just because not all configuration is supported. By your logic, .NET attributes themselves should be obsoleted as a feature, since not everything can be represented with them. Once again, the idea was never to allow doing **everything** via attributes: the covered scenarios are enough for many people, most of the others are impossible to do because of the limitations of attributes, and the rest simply haven't seen any actual user demand.

**Comment by vozeldr** [comment]
First, sorry if I was a bit disrespectful due to frustration. You stated one of the reasons some functionality with attributes hasn't been implemented is due to a lack of user interest... but that's kind of my point and what has me so frustrated.

This issue exists, so there is obviously some user interest. A gatekeeper decided to close the issue (multiple times)... so for the last several years, people looking for this functionality either find this page or some stack overflow article that just says it's not possible, do it the other way. Most people are going to take that at face value and just do what SO says, therefore you can't accurately gauge the current level of user interest.

- `HasDefaultValue` simply takes in an object.
- `HasDefaultValueSql` simply takes a string.
- `HasConversion` at its simplest takes one or two types.

These seem to me like pretty simple things to implement which, for my current code base, would entirely get rid of the need to use the Fluent API and be able to do everything through attributes. Hopefully, you can agree it's not optimal to have some configuration for an entity be done within the entity (where it's "in-your-face" and easy to find when working with the entity) and then have other parts of the configuration for the entity abstracted away in some other class / method.

I'm simply asking that this be reopened so it can foster some discussion.

**Comment by roji** [comment]
> This issue exists, so there is obviously some user interest.

Yes - we have literally thousands of users which exist, and all of them have some user interest. In many/most cases, one - or maybe a handful - users have such interest, and we unfortunately have to prioritize other things which are much, much more important.

> These seem to me like pretty simple things to implement [...]

So are many of the aforementioned multitude of issues. Tons of users have their one thing, which is likely simple to implement, which they'd love to see us implement. But we're a small team and must prioritize.

> [...], for my current code base, would entirely get rid of the need to use the Fluent API and be able to do everything through attributes.

I understand, but importantly that's true of your very specific case, but not of the general case. I understand the frustration of this being the only thing missing for you to exclusively use attributes, but try looking at the more general picture, where we have to deal with a great many users - each of which has their own case - and prioritize accordingly. Tomorrow you may need to use a value converter that needs a constructor parameter, and then you'd be stuck again. I really recommend letting go of the desire to do everything with attributes - it simply doesn't work in the general case.

I'll summarize the situation as I see it:

* Data annotations cannot be used to perform all possible configuration - that can only be done with the Fluent API. The main reason for this has nothing to do with EF - it's simply that .NET attributes are very limited in what they support. There was never any intention of allowing **everything** to be configured this way.
* The scenarios we currently support with data annotations are scenarios which fit well with attributes, and can be fully addressed by them; [Required], [MaxLength] and [Column] do the job fully, not partially. With value converters, in contrast, only a very specific subset would be supported by an attribute (simple value converter with no parameters); yes, this happens to be what you're looking for, but that again doesn't change that fact.
* Over the years we really have seen little interest in this; people generally understand and accept that they can't do everything with .NET attributes anyway, and simply move on. Yes, we can reopen this issue for supporting this simple scenario, but that definitely doesn't mean we'll implement it anytime soon.
