### ISSUE TITLE
Query performance: Client evaluation for tracked queries returning an entity by key

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#1948]
Currently a query like this will always cause a database round trip:

``` C#
var product = context.Products.FirstOrDefault(p => p.Id == pid);
```

As mentioned in the comments of #797 we have been talking for some time about handling such queries differently: we can check first if an entity exists in the context that matches the predicate, and if found we can short-circuit the database query.

In terms of previous versions of EF this would be equivalent or very similar to `DbSet<T>.Find()` and ObjectContext.GetObjectByKey()` (the main difference between these two is that the latter cannot be used to retrieve objects in the added state).

Initially we could support only queries that:
1. Return a tracked entity
2. Do not use `Include()`
3. Are restricted by a simple predicate of the general form `entityKey == value`
4. Have that predicate passed to `First()`, `FirstOrDefault()`, `Single()` or `SingleOrDefault()`

Then (also initially or in the longer term) we can pick other scenarios in which the database query can be unnecessary, e.g.:

``` C#
// Deferred query that return a single entity is compelling as many customers will use it
var product1 = context.Products.Where(p => p.Id == pid).First();
// Composite predicates
var product2 = context.Products.First(p => p.Id == pid && !string.IsNullOrEmpty(p.Name));
// Any() over a predicate by key could sometimes return true without going to the database
var found = context.Products.Any(p => p.Id == pid);
// Contradictions don't need round tripping, but are less common 
var never = context.Products.Where(p => p.Presentation != p.Presentation);
```

The only observable functional change I can think of is with entities that have been deleted in the database after the entity was originally retrieved in the context. Previously the query would not return the entity, although the entity would continue to be present in the context. This change in fact makes the behavior more consistent with the _snapshot semantics_ of the `DbContext`, although only for a (very useful) subset of the queries.

Note also that this is a popular feature in LINQ to SQL.

**Comment by neurospeech** [comment]
Business Logic and Transactions?

In business logic, caching entities locally will be harmful and will not obey transactions. If user has successfully wrapped query in Transaction Scope, returning client cache breaks transaction. 

Ideally I would recommend not using client cache but you can always create repository over DbContext which can cache whatever you wish to. Or create CachedDbContext which supports local caching but gives a warning that you cannot use Transactions.

**Comment by divega** [comment]
@ajcvickers just FYI, I found this issue already in the backlog. I think it is fine to keep it there.

**Comment by gdoron** [comment]
If it will be implemented, it might be a good idea adding an overload that forces these method to do a roundtrip to the DB for the cases where you do not want to get stale data.

**Comment by divega** [comment]
@gdoron this only applies to tracked queries so it would return stale data from the identity map anyway. If you don't want the stale data you use a non-tracking query. The database roundtrip would only really make a difference in cases in which the entity has been deleted from the database, but even in that case it is debatable if the current behavior (you would get a null from a `FirstOrDefault()` query, but you still get the entity if you used `Find()`) is the most correct/excepted/helpful within a unit of work.

**Comment by sjb-sjb** [comment]
A simple approach that would add a lot of value would be to extend Find so that it can use an alternate key (unique secondary key, foreign key). Currently Find can only take key field values for the primary key. However, in many cases the primary key is a meaningless integer; what we really want to do is Find on a unique user-understandable string that is a unique secondary key. 

For example, consider an entity such as: class User { int Id; string UserName; ... }. Here the Id is the primary key while the unique UserName is what we want to see on the user interface. This kind of design comes about because in EF one can't (and shouldn't) change the primary key, but there are often reasons to change the corresponding string shown on the user interface.

When using Find, in this example, one wants to Find on the UserName so that the Id can be obtained and stored in a related record. 

The purpose of doing this with Find instead of a Where clause would be, obviously, to take advantage of the indexes to speed up the operation. 

This feature would go along with #4073 which hopefully will enable changing the value of alternate keys.

**Comment by BalassaMarton** [comment]
IMHO it is a terrible idea to change just a few methods of `IQueryable` to behave this way, while leaving the rest. Consider this: according to `IQueryable` semantics, the following two queries should return the same set:
```
  var list1 = query.Where(x => x.Whatever == x.Whatever).FirstOrDefault(x => x.SomeAltKey == keyValue);
  var list2 = query.FirstOrDefault(x => x.SomeAltKey == keyValue);
```
The great thing about `Find` is precisely that it has different, documented semantics than the rest of the `IQueryable` methods.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
