### ISSUE TITLE
Provide guidance on warming up DbContext

### ISSUE THREAD

**Issue by justhoma-zz** [dotnet/efcore#19675]
We want to provide a consistent user experience when utilizing our application. We are seeing a significant difference around the first execution of a request (>2 seconds) and subsequent calls (<500ms) and from our research the most significant portion of the time is being taken inside EF.

I have attached the code related to a stand-alone console app that you should be able to run locally. Take a look at the code and you will see that it executes 6 requests to add a new blog to the in-memory context and captures the ‘logged’ execution times per EventId.Name. 
e.g.

![FirstRun](https://user-images.githubusercontent.com/17317253/72959182-cc31dd80-3d66-11ea-8e6d-7ba011bb26aa.png)

As you can see, the elapsed time decreases fairly significantly in multiple areas after the first execution.

I found the following https://github.com/dotnet/efcore/issues/15568  and saw the suggestion from ‘ajcvickers’ about adding a call to access the model. I did this inside the ‘ExecuteWarmup’ method prior to executing the test runs and it had a fairly significant impact:
 
![SecondRun](https://user-images.githubusercontent.com/17317253/72959293-1f0b9500-3d67-11ea-8d35-8360831aa0ac.png)

However, there is obviously yet more “magic” that is going on inside EF that is causing the first execution to take longer. 

Would it be possible to provide a ‘generic’ way to mitigate this “warm up” which does not involve actually doing an update to any data in production.

**Sample program file**
```C#
    class Program
    {
        static async Task Main()
        {
            ExecuteWarmup();
            for (var i = 0; i < 6; i++)
            {
                LogMessageCollector.RunNumber = i;
                await ExecuteRun(i);
            }

            LogMessageCollector.CollateResults();

            var resultFormat = "{0,-70} {1,5:N1} {2,5:N1} {3,5:N1} {4,5:N1} {5,5:N1} {6,5:N1}";
            Console.WriteLine(resultFormat, "Event", "Run1", "Run2", "Run3", "Run4", "Run5", "Run6");
            foreach (var result in LogMessageCollector.Results)
            {
                Console.WriteLine(string.Format(resultFormat, result.EventName, result.ElapsedTimes[0], result.ElapsedTimes[1], result.ElapsedTimes[2], result.ElapsedTimes[3], result.ElapsedTimes[4], result.ElapsedTimes[5]));
            }
            Console.WriteLine(string.Format(resultFormat, "Totals", LogMessageCollector.Results.Sum(x => x.ElapsedTimes[0]), LogMessageCollector.Results.Sum(x => x.ElapsedTimes[1]), LogMessageCollector.Results.Sum(x => x.ElapsedTimes[2]), LogMessageCollector.Results.Sum(x => x.ElapsedTimes[3]), LogMessageCollector.Results.Sum(x => x.ElapsedTimes[4]), LogMessageCollector.Results.Sum(x => x.ElapsedTimes[5])));
        }

        private static void ExecuteWarmup()
        {
            using (var db = new BloggingContext())
            {
                // Seen here: https://github.com/dotnet/efcore/issues/15568
                _ = db.Model;
            }
            LogMessageCollector.LogMessages.Clear();
        }

        private static async Task ExecuteRun(int runCounter)
        {
            using (var db = new BloggingContext())
            {
                await db.AddAsync(new Blog { BlogId = runCounter, Url = "http://blogs.msdn.com/adonet" });
                await db.SaveChangesAsync();
            }
        }
    }

    class BloggingContext : DbContext
    {
        public static readonly ILoggerFactory testLoggerFactory
            = new LoggerFactory(new[] { new TestLoggingProvider() });

        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder options) =>
            options
                .UseInMemoryDatabase(Guid.NewGuid().ToString())
                .UseLoggerFactory(testLoggerFactory);
    }

    class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }

    class TestLoggingProvider : ILoggerProvider
    {
        public ILogger CreateLogger(string categoryName) => new TestLogger();

        public void Dispose() { }
    }

    class TestLogger : ILogger
    {
        private DateTime? _datetimeOfLastLog = null;

        public IDisposable BeginScope<TState>(TState state) => null;

        public bool IsEnabled(LogLevel logLevel) => true;

        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
        {
            var elapsedTime =
                _datetimeOfLastLog != null
                ? DateTime.Now.Subtract(_datetimeOfLastLog.Value).TotalMilliseconds
                : 0;
            _datetimeOfLastLog = DateTime.Now;

            LogMessageCollector.Add((elapsedTime, eventId.Name, formatter(state, exception)));
        }
    }

    static class LogMessageCollector
    {
        public static int RunNumber { get; set; }
        public static List<(int runNumber, double elapsedTime, string eventName, string message)> LogMessages { get; } = new List<(int runNumber, double elapsedTime, string eventName, string message)>();
        public static List<LogMessageResult> Results { get; } = new List<LogMessageResult>();

        public static void Add((double elapsedTime, string eventName, string message) logMessage)
        {
            LogMessages.Add((RunNumber, logMessage.elapsedTime, logMessage.eventName, logMessage.message));
        }

        public static void CollateResults()
        {
            foreach (var logMessageRun in LogMessages.GroupBy(lm => lm.runNumber))
            {
                foreach (var logMessage in logMessageRun)
                {
                    var result = Results.SingleOrDefault(x => x.EventName == logMessage.eventName);
                    if (result == null)
                    {
                        result = new LogMessageResult { EventName = logMessage.eventName };
                        Results.Add(result);
                    }
                    result.ElapsedTimes[logMessageRun.Key] = logMessage.elapsedTime;
                }
            }
        }
    }

    class LogMessageResult
    {
        public string EventName { get; set; }
        public double[] ElapsedTimes { get; } = new double[] { 0, 0, 0, 0, 0, 0 };
    }
```

**Comment by ajcvickers** [comment]
Related: #19610 #16496 #1906

**Comment by AndriySvyryd** [comment]
@justhoma As a general note there's nothing special the EF Core does after the first run, so times from Run 2 are the best you'll be able to consistently get even with a warm start, all perf differences afterwards are due to low-level optimizations that take advantage of the tight loop used in the benchmark.

Also if you are maximizing latency instead of throughput I'd strongly suggest using only synchronous methods.

Here are the things that take up time during the first run apart from model building:
- Service initialization. This can be avoided by using context pooling (`AddDbContextPool`), but that's currently only available when using DI. Do you use ServiceProvider in the real app?
- InMemory database initialization. There's no way to fully warm this up without actually accessing the database (you could add an entity and then delete it). Do you actually use InMemory in production?
- Property access delegate compilation. To warm these up you'd need to attach an entity for every entity type and call `db.ChangeTracker.DetectChanges()`. We could add an option to compile these eagerly when we implement https://github.com/dotnet/efcore/issues/8258
- Query compilation. Not present in the benchmark posted above, but is likely to be a significant contributor in production. I assume you are already using compiled queries (`EF.CompileQuery`).

**Comment by ajcvickers** [comment]
We have been in contact with @justhoma through other channels. In this case it was the update pipeline that needed warming up. However, this is quite specific to the model such that it doesn't seem practical to write a generally useful method for this in the product. We also want to focus more on pre-calculation (see linked issues above) for startup time, rather than warming up.
