### ISSUE TITLE
End-to-end soft delete

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#19695]
(Thought we had this on the backlog, but couldn't find it.)

Query filters provide most of the underlying functionality for soft deletes, but they don't allow things like automatically updating an entity to set the flag instead of deleting it. This issue is about making a good end-to-end experience for this.

**Comment by AshkanAbd** [comment]
@ajcvickers  Below link is my proposal for #21524 issue as an implementation for soft deletes. sorry my writing skills for English language is not very good. 
[https://1drv.ms/b/s!AirwjkMOI-BwkAzedA6E6YVkZqjQ?e=vfV2hq](url)

**Comment by roji** [comment]
@AshkanAbd we usually just post design proposals in their relevant github issues, in Markdown - this is easiest to access for everyone and ensures the content never goes away.

I haven't given your document a thorough read, but on principle EF Core generally does not require entities to implement interfaces or inherit from base classes to provide functionality. Any proposal which requires this goes against the current design of the library.

**Comment by AshkanAbd** [comment]
@roji I understand that but this proposal is not just an idea for an implementation, its the best implementation after several projects. I have been tried other implementations in several projects for this feature and because of feedbacks I get from my friends and other developers, I choose this one, other implementations that I have been tried, was really confusing for developers, they were not easy to add or remove from the project. I can implement relations need to delete in "DbContext" but its not clean enough in the project or "OnSoftDelete" for each entity needs to define in the entity's class. Also, soft deletes needs to modify entities because of "DeletedAt" property. Please note that soft deletes is an really useful and important feature that needs to implement in a framework like .Net Core, there is no Nuget package or an implementation that really works. One of the reasons that other developers don't want to use EF Core is that the library doesn't soft deletes. You may need to add some exceptions in the current design of the library.

**Comment by ajcvickers** [comment]
@AshkanAbd I agree with @roji. I don't think this is kind of implementation belongs in the main EF Core codebase. That being said, if you feel that this would be useful to people, then I encourage you to ship it as an extension to EF Core in a NuGet package. It can then be added to https://docs.microsoft.com/en-us/ef/core/extensions/ to help other people find it.
