### ISSUE TITLE
EF Core Sqlite

### ISSUE THREAD

**Issue by jesorian** [dotnet/efcore#19725]
I just want to say that this issue is still happening in the latest version

https://stackoverflow.com/questions/59186616/ef-core-update-database-throws-system-nullreferenceexception

Hoping for the future fix.

**Comment by ajcvickers** [comment]
@xshiiiidev Please attach a small, runnable project or post a complete code listing that demonstrates the behavior you are seeing so that we can investigate.

**Comment by xshiiiidev** [comment]
I just created a new fresh project and installed the nugget package `Microsoft.Data.Sqlite.Core`.

Now after installing it, the error is shown when issuing the command `Update-Database`. Because this package does not include its dependency `Microsoft.Data.Sqlite` by default.

I think the installation should just include the `Microsoft.Data.Sqlite` by default.

**Comment by ajcvickers** [comment]
@xshiiiidev Use Microsoft.Data.Sqlite if you want a package pre-configured with a native SQLite executable. Microsoft.Data.Sqlite.Core is for manual configuration. The "Core" here has nothing to do with .NET Core or EF Core.

**Comment by xshiiiidev** [comment]
Oh I see the SQLite Core has nothing to do with the .Net Core and EF Core. My wrong.

I will close this now.
