### ISSUE TITLE
Backing field is null when lazy loading hasmany collection

### ISSUE THREAD

**Issue by piyushchhapekar** [dotnet/efcore#19809]
Noticed that backing field collection is null if the property is configured to be lazy loaded. Once you access the property then the backing field gets loaded.
```C#
public class Blog
{
    protected Blog() { }

    public int BlogId { get; private set; }
    public string BlogName { get; private set; }

    private IList<Post> _posts;
    public virtual IEnumerable<Post> Posts => _posts;

    public void DeletePost(int postId)
    {
        _posts.Remove(_posts.FirstOrDefault(postId => p.PostId == postId));
    }
}

public class Post
{
    protected Post() { }

    public int PostId { get; private set; }
    public string PostTitle {get; private set; }
    public int BlogId { get; private set; }
}

public class BlogMap : IEntityTypeConfiguration<Blog>
{
    public void Configure(EntityTypeBuilder<Blog> builder)
    {
        builder.HasKey(blog => blog.BlogId);
        builder.HasMany(blog => blog.Posts).WithOne().HasForeignKey(pm => pm.BlogId)
        .Metadata.PrincipalToDependent.SetPropertyAccessMode(PropertyAccessMode.Field);
    }
}
```

In above example, accessing _posts in DeletePost method returns null. If I hit a breakpoint before accesing _posts and tries to lookup Posts (lazy loading) then _posts also gets filled in.

**Comment by ajcvickers** [comment]
@piyushchhapekar This by-design. EF only initializes collection navigations when the relationship is loaded. That is, when Include is used, Load is called, or lazy-loading kicks in. Doing otherwise would result in a perf and memory hit for queries that don't load the relationships, which is the common case.

However, application code is free to initialize collection navigations if needed. It's easiest to do this eagerly:

```C#
private IList<Post> _posts = new List<Post>();
```

But it can also be lazy:

```C#
(_posts ??= new List<Post>()).Remove(_posts.FirstOrDefault(postId => p.PostId == postId));
```

**Comment by TAGC** [comment]
@ajcvickers Initialising the collection doesn't make it actually load the collection, all it does is prevent a `NullReferenceException` being thrown.

For example, given a class like this:

```cs
public class ProductConsultant
{
    private readonly List<Discretionary> _discretionaries = null!;

    protected ProductConsultant()
    {
        // Required by EF
    }

    // Public constructor goes here

    public virtual IReadOnlyCollection<Discretionary> Discretionaries => _discretionaries.AsReadOnly();

    public void RemoveDiscretionaryWithId(int discretionaryId)
    {
        _discretionaries.RemoveAll(x => x.Id == discretionaryId);
    }
}
```

If I change it so that the field gets initialised when the class is constructed:

```cs
private readonly List<Discretionary> _discretionaries = new List<Discretionary>();
```

When I call a method on the entity that accesses that field before the corresponding property is first accessed:

```cs
productConsultant.RemoveDiscretionaryWithId(someDiscretionaryId);
```

Then the `_discretionaries` collection is empty:

![image](https://user-images.githubusercontent.com/1588951/96876405-5501b500-1470-11eb-9a1f-6bf0db573a42.png)

Whereas if I view the corresponding property `Discretionaries` in the debugger, I can see that it should have 26 items:

![image](https://user-images.githubusercontent.com/1588951/96875835-9a71b280-146f-11eb-9723-3e9f106188f0.png)

The way I've "hacked" around this is to add another private property that accesses the lazy-loaded public property before returning the private list:

```cs
private List<Discretionary> PrivateDiscretionaries
{
    get
    {
        Discretionaries.ToList();
        return _discretionaries;
    }
}
```

That then allowed my code to work:

![image](https://user-images.githubusercontent.com/1588951/96877094-1fa99700-1471-11eb-9e9a-05c85b0ca292.png)

Obviously I can't directly reference `Discretionaries` within these methods because it exposes the collection as a read only collection, whereas I need to be able to modify it. I also don't want to allow external code to be able to modify the collection directly.

Is there not a way of maintaining encapsulation using EF Core lazy-loading proxies without having to do this extremely hacky thing where I have to ensure the public properties are accessed before I can safely access their backing fields?

**Comment by TAGC** [comment]
Nevermind, I see that you've addressed this [here](https://github.com/dotnet/efcore/issues/22752#issuecomment-700282063).

Since injecting lazy loaders (even as an `Action<object, string>`) into my entities couples them far too tightly to the underlying persistence tech than I'd be happy with, I'll probably just try to move away from using proxies altogether. I only switched to them in the first place because I encountered huge performance issues when upgrading an ASP.NET Core 2 project to ASP.NET Core 3 (because EF Core 3 doesn't use split queries, and so can generate extremely expensive SQL queries when you've got a lot of `Include`s).

EF Core 5 gives us back the option of using split queries again, so I can probably revert back to the original, explicit way of resolving entity graphs.
