### ISSUE TITLE
IdentityResolution Configuration on AsNoTracking queries

### ISSUE THREAD

**Issue by YZahringer** [dotnet/efcore#19877]
Identity Resolution is no longer performed with no-tracking queries on EF Core 3: [breaking change doc](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#no-tracking-queries-no-longer-perform-identity-resolution)

In some cases, I think that creating several instances of the same object instead of reusing the instance is not optimal in terms of memory usage.

In other cases, such as in recursive objects, you want to be able to enable Identity Resolution to resolve all properties and be able to navigate recursively.

I created a Unit Test that reproduces the recursivity problem in `EF Core 3` with `NoTracking`: https://github.com/MADSENSE/Madsense.EFCore.Tests/tree/no-tracking-recursive

Related issues: https://github.com/dotnet/efcore/issues/19276, https://github.com/dotnet/efcore/issues/18570

**Proposal**
Make `Identity Resolution` configurable when a request is executed with `AsNoTracking`.

**Comment by ajcvickers** [comment]
Team notes: sometimes it is desirable to have full identity resolution in cases where it is not possible to use a tracking query. For example, when diffing the current and database graphs to resolve update resolutions. In these cases the only solution is to spin up a new context for the query. We could instead provide a query mode that automatically spins up a new state manager or similar to do identity resolution. This would leave the default no-tracking case usable as a streaming API without memory issues, while still allowing a different behavior where it is needed.

Related: #11564

**Comment by ole1986** [comment]
This issue is absolutely underrated already!!!

**Comment by JonPSmith** [comment]
This comments might be too late, but here is my take on surfacing this feature. If its a done deal then ignore, but I only found out about this yesterday.

I'm not sure how you are going to control the identity resolution added to a `AsNoTracking` call, but personally I think something like  `...AsNoTracking(true)` for turning on identity resolution, and the original `...AsNoTracking()` where identity resolution is turned off. I like that because most AsNoTracking queries are for the front-end, which doesn't care about identity resolution - I'm only interested in identity resolution in business logic that a) wants a read-only copy but b) needs the class instances map exactly to what the database says - which is a small set of `AsNoTracking` queries.

Also, you could provide a DbContext-wide setting to switch all  `AsNoTracking` queries to include identity resolution. Then optional parameter to `AsNoTracking` allows you to turn off the identity resolution for an individual  `AsNoTracking` query, e.g. `...AsNoTracking(false)`. Not sure that is worth the effort, but some people might find that useful (I wouldn't).

**Comment by smitpatel** [comment]
@JonPSmith - We are going to update the exact API. We discussed about it during API review. Current plan is to add another enum value in `QueryTrackingBehavior` enum, which will enable
- Making it separate from AsNoTracking to avoid confusion.
- Ability to set at context level.
- Possibly As* API to align with AsTracking/AsNoTracking which does not take any parameter.
- Ability to use AsTracking with the enum value.

**Comment by smitpatel** [comment]
New API - AsNoTrackingWithIdentityResolution
Added new enum value in `QueryTrackingBehavior` to control it at context level or use with `AsTracking` API which takes parameter.

**Comment by ole1986** [comment]
Öhm just asking a dumb question: will this be only available on EF Core 5.0 and higher?

**Comment by ajcvickers** [comment]
@ole1986 Yes.
