### ISSUE TITLE
Generate a warning for multiple collection Includes

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#19933]
See this discussion for details: https://github.com/dotnet/efcore/issues/18022

**Comment by ajcvickers** [comment]
Should we also issue a warning when using split Include to warn of the potential consistency issues? Or is it assumed that you understand this when you opt-in?

**Comment by AndriySvyryd** [comment]
@ajcvickers We should add that to the XML docs on `AsSplitQuery`

**Comment by smitpatel** [comment]
Design meeting decisions:
Correlated with #21355 
In the presence of 2 or more collection joins, we will log a warning guiding users to landing page of https://github.com/dotnet/EntityFramework.Docs/issues/2479 which will explains pros/cons of both.
If user configures either scenario on context level using #21355 then we won't log a warning since user has explicitly decided to choose one behavior.
