### ISSUE TITLE
EF Core migrations don't see tables in an EF6 database

### ISSUE THREAD

**Issue by mrmowji** [dotnet/efcore#19950]
I'm trying to migrate from ASP.NET Framework (and EF6) to ASP.NET Core (and EF Core).
Unfortunately I can't provide a repo since I don't have access to ASP.NET Framework anymore.

### Steps to reproduce

- Have an ASP.NET Framework project with a database created by EF 6.
- Create a new ASP.NET Core project.
- Copy one of your isolated models from the old project into the ASP.NET Core one.
- Test a migration.

### Observations

The migration creates the table corresponding to that model, but it already exists on the database.
**Is it by design or there's something wrong?**

### Further technical details

EF Core version: **3.1.1**
Database provider: **Microsoft.EntityFrameworkCore.SqlServer**
Target framework: **.NET Core 3.1**
Operating system: **Ubuntu 18.04.4 LTS**
IDE: **Visual Studio Code 1.42.1**

### Edit
I also tried to get the models from the exisitng database; `dotnet ef dbcontext scaffold`. Models are scaffolded, but the new migration still has `CreateTable`s.

**Comment by ajcvickers** [comment]
@mrmowji EF Core doesn't understand EF6 migrations because there are fundamental improvements to the way migrations work in EF Core. The way forward is to treat the existing database and its already applied migrations as the starting point and to generate new EF Core migrations for future schema changes. We have some docs here, although they need to be better: https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code#existing-migrations See also: https://github.com/aspnet/EntityFramework.Docs/issues/91

**Comment by mrmowji** [comment]
@ajcvickers Thanks. I'm on it.
