### ISSUE TITLE
Support extra methods/properties in SpatialQueryTestBase

### ISSUE THREAD

**Issue by EricStG** [dotnet/efcore#19957]
I'm adding new translations to npgsql/efcore.pg#457 and noticed that support in `SpatialQueryTestBase` was missing for some of them, namely:
- [Geometry.Normalized()](http://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Geometry.html#NetTopologySuite_Geometries_Geometry_Normalized)
- [Geometry.ToGMLFeature()](http://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Geometry.html#NetTopologySuite_Geometries_Geometry_ToGMLFeature)
- [LinearRing.IsCCW](http://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.LinearRing.html?q=IsCCW#NetTopologySuite_Geometries_LinearRing_IsCCW)

I'd like those methods and properties to be supported by the `SpatialQueryTestBase` class.

I can submit a PR if the project is open to those changes.

**Comment by ajcvickers** [comment]
@EricStG Thanks, this would be great!

/cc @bricelam

**Comment by bricelam** [comment]
👍 Adding them to SpatialQueryTestBase is the right thing to do since it'll force other providers to think about whether or not they can be translated.

One question: How are you handling the XmlReader of ToGMLFeature()? Only translating it if it's chained with ReadOuterXml()?

NTS | MSSQL (geometry) | MSSQL (geography) | SpatiaLite
--- | --- | --- | ---
geometry.Normalized() | ❌ | ❌ | ❌
geometry.ToGMLFeature() | ❌ | geometry.AsGml() | AsGml(geometry)
linearRing.IsCCW | ❌ | ❌ | ❌

**Comment by EricStG** [comment]
I'll admit I didn't think this far into my process... I just happened to be starting with the other ones and noticed they were missing, but it seems to make sense to only translate it if it's chained with ReadOuterXml(0.

**Comment by bricelam** [comment]
Another possibility: https://github.com/dotnet/efcore/issues/19991

**Comment by ajcvickers** [comment]
@EricStG We discussed this and concluded that maybe you should try just `Normalized` and `IsCCW` since these don't have the XmlReader complications.

**Comment by EricStG** [comment]
@ajcvickers Works for me, thanks!
