### ISSUE TITLE
Evaluating decimal values in LINQ expressions fails

### ISSUE THREAD

**Issue by germandb** [dotnet/efcore#19982]
How to evaluate linq in the Sqlite and SQLServer when using c# Decimal.

I know that the Decimal Type in Sqlite is a string Type in order to maintain the precision, that prevents the translation of many numeric operations in expressions so the LINQ must be evaluated on the client. But in my use case I need to support Sqlite and SQLServer as Databases. In EFCore 2.2 I used the type of database to modify the optionsBuilder in the AddDbContext to enable the query to evaluate in the client if Sqlite was selected. But with the new changes that prevent the onclient evaluation i don't know where I can hook to modify all the queries and add the AsEnumerable when the db type is Sqlite.
I tried to implement my own QueryCompiler but the excepcion occurrs before the call to the Execute method.

### To Reproduce
Create an Entity with a Decimal field, create a query using that Entity.
```c#
entity.Where(e => e.decimalValue > 100) 
```
Evaluate the linq return:
> The LINQ expression '`DbSet<Entity> .Where(e => EF.Property<DecimalValue>(e, "DecimalValue").BaseValue > 100,0)` could not be translated. Either rewrite the query in a form that can be translated, or swith to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync().' 
### Additional context

Microsoft.Data.Sqlite version:
Target framework: .NET Core 3.1
Operating system: Windows Server 2016 Standard

**Comment by ajcvickers** [comment]
@germandb This is covered by #19635 which is a stretch-goal for 5.0.

For now, one workaround is to use a value converter to tell EF to map to a double:

```C#
if (Database.IsSqlite())
{
    modelBuilder.Entity<Product>().Property(e => e.Price).HasConversion<double>();
}
```
This:
```C#
var results = context.Products.Where(e => e.Price > 1.5m).ToList();
```
will then translate to:
```sql
SELECT "p"."Id", "p"."Price"
FROM "Products" AS "p"
WHERE "p"."Price" > 1.5
```
This works even when the existing data is stored as strings because of the way SQLite handles types at the database level.

(Note that I am assuming you are using EF Core because the exception message which come from EF Core. If you are looking for something at the ADO.NET level then please provide more details.)

**Comment by sebetci** [comment]
While developing a project on [Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/), due to a similar [LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/) query, I got the error shown below by [dotnet](https://docs.microsoft.com/en-us/dotnet/core/tools/):

```
Unhandled exception. System.InvalidOperationException: The LINQ expression 
'DbSet<Product>.Where(p => p.Price >= __price_0)' could not be translated. Either rewrite the
query in a form that can be translated, or switch to client evaluation explicitly by inserting 
a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync().
```

I discovered that this problem is solved using the cast operator. Since the base data type `decimal` is floating point and the use of the `double` cast operator is allowed in the current context, I developed the following solution:

```csharp
///<summary>Entity Class</summary>
public class Product
{
  [Key]
  public int ID { get; set; }
    
  [MaxLength(100)]
  [Required]
  public string Name { get; set; }

  public decimal Price { get; set; }
  ...
}

///<summary>
/// In a scenario where Entity Framework Core is used by the ApplicationLayer class in the application layer ...
///</summary>
public class ApplicationLayer
{
  ///<summary>
  /// Using the "double" cast operator on the line where the "Where" LINQ query is used will work in solving this problem.
  ///</summary>
  public static void PrintProductsByMinimumPrice(decimal price)
  {
    using(var context = ProductContext())
    {
      var products = context.Products
                            .Where(product => ((double)product.Price) => (double)price)
                            .Select(product => new { product.ID, product.Name })
                            .ToList();

      foreach(var product in products)
      {
        Console.WriteLine($"ID: {product.ID}\tName: {product.Name}");
      }
    }
  }
}
```

**Comment by Noushadkanniyan** [comment]
how to select decimal values like 10.23 in linq select query

**Comment by roji** [comment]
@Noushadkanniyan can you please open a new issue with some code showing what you're trying to achieve, and what's not working?
