### ISSUE TITLE
Support updatable views

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#20013]
Split off https://github.com/dotnet/efcore/issues/17270

Would be configured using something like `.ToView(updatable: true)` and would be used instead of the configured table for CUD operations.

**Comment by pfdsilva** [comment]
@AndriySvyryd @ajcvickers 
Please could you confirm if updating of rows is not supported when an entity class is mapped to a view using fluent API.

I have the following code in my OnModelCreating method.
```
 modelBuilder.Entity<BlogsView>(entity =>
            {
                entity.ToView("BLOGS_VIEW");

                entity.Property(e => e.Id)
                    .HasColumnName("ID")
                    .HasColumnType("NUMBER(38)");

                entity.Property(e => e.Sub)
                    .HasColumnName("SUB")
                    .HasColumnType("VARCHAR2(30)");
            });
```
When I execute the following code, I am noticing that the changes are getting successfully reflected on the database. I was expecting that the update will not go through because I thought updating of views from EFCORE is not supported. May be I have not understood the scope of this github issue. Please could you help me understand?

```
var entity = db.BlogsView.FirstOrDefault(item => item.Id == 10);

          // Validate entity is not null
          if (entity != null)
          {
            // Answer for question #2

            // Make changes on entity
            entity.Id = 10;
            entity.Sub = "new sub";
          }
```
I am using an Oracle DB and the view that I have created on the DB has a primary key constraint.

**Comment by AndriySvyryd** [comment]
@pfdsilva In 3.1.5 SaveChanges doesn't differentiate between views and tables, so it will try to update whatever is configured. In 5.0 you'll be able to map an entity type to both a view and a table and SaveChanges will only use the table mapping

**Comment by johnwc** [comment]
@AndriySvyryd When using scaffolding, there is no way to tell it to use `ToTable(...)` instead of `ToView(...)` What do we do in that scenario?

**Comment by ErikEJ** [comment]
@johnwc You may be able to set it ToTable and specify a Key in a partial class that implements the OnModelCreatingPartial method
