### ISSUE TITLE
InMemory: Defining query with shadow props

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20023]
Current we have ToQuery method which has it's own issues in InMemory. Notably, #17158. Further, in current mechanism there is no way to specify shadow properties. But on the other hand, a keyless entity can still have shadow property.

With relational model coming into picture in 5.0 and mapping to view or ToQuerySql, for testing purposes of the views we can add following to InMemory provider,
```C#
modelBuilder.Entity<BlogView>().ToQuery(
e => from b in Blogs.Where(...).Join(...) // any linq
         Select new { .... });
```
The anonymous type construction must have all the properties defined on BlogView. (Even if it is always null does not matter). (Same as what we do for views/tables/FromSql).
We would take this defining query, compile it fully to generate enumerable of ValueBuffers where slots in ValueBuffers are sorted as we expect properties to come and substitute it for following method. 

https://github.com/dotnet/efcore/blob/17009083724c8617dcafb7afbd2809b532e55dd3/src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.cs#L84-L87

The ToQuery method can also take a static list of values and project into anonymous type form we want and we can use that as source too. In a way, it would provide readonly data.

Due to implementation, scope of this should only be InMemory provider. This would make testing keyless entities in cross database scenario a lot simple and make feature more useful.

**Comment by smitpatel** [comment]
Blocked on #21624

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.
