### ISSUE TITLE
context.Update sets IsLoaded to false

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#20022]
@lajones to provide details

**Comment by lajones** [comment]
The problem was that at some stage during test debugging we were seeing [this line](https://github.com/dotnet/efcore/blob/master/test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs#L726) make `context.Entry(owner).Reference(o => o.Address).IsLoaded` change from true to false. But I'm no longer seeing that - so closing.

**Comment by ajcvickers** [comment]
@lajones FYI Issues that can't be reproduced don't get a type label and should be closed with no milestone.
