### ISSUE TITLE
vNext hosted on Ubuntu can't fetch data from SQL database on Azure

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2007]
My vNext app works on both, Windows and Ubuntu. The difference is when I host it on Ubuntu, it doesn't get any data from SQL database in Azure, actually when database is clean, migration does nothing, no table gets created. 

Can this actually be done at the moment or  am I trying to do (currently) impossible thing? 
I think it's SQL server 2012 on Azure, Ubuntu 14.10 and I installed mono and nginx.  

So, I thought if it works on Windows, it'll work on Ubuntu too. If this is not possible at the moment, will it be in the future? Also, what could be an obstacle for this to work?

**Comment by Junsui** [comment]
I solved this by setting Encrypt=False and added Trusted_Connection=False in my connectionString. But beside Reading from database, it's not possible to Update, Create or Delete in database while hosting on Ubuntu. Again, same code works while hosting with IIS. I allowed access to all IPs so that's not the problem, also Ubuntu firewall also doesn't make a difference wether it's on or off. 

Any idea if there is a workaround for this?
