### ISSUE TITLE
Provide a hook for identity resolution

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#20124]
In general, identity resolution is a difficult problem. See https://github.com/dotnet/efcore/issues/20116#issuecomment-593499871 and many other similar comments over the years.

However, maybe we could provide a hook that applications can do to implement their own identity resolution when EF starts tracking a graph. This likely wouldn't cover difficult were merging needs to happen, but simple cases where duplicates can be essentially ignored could become much easier.

**Comment by ajcvickers** [comment]
Related: identity resolution for no-tracking queries #19877

**Comment by cdaragorn** [comment]
I just ran into this problem and would like to promote this proposed solution. In my case I have to take a slower route in order to prevent hitting the same entity multiple times. It would be extremely nice for my case if I could somehow just say "don't worry about conflicts. I know they're ok".

To give some context, I was using FindAsync() to take advantage of already tracked entities but was then using RemoveRange() on a foreign keyed entity which triggers adding the parent entity to tracking. Since I have no control over that it has become impossible for me to use FindAsync() and I now will have to take the slow route to the database for each of those calls.
