### ISSUE TITLE
ASP.NET 5 on Ubuntu: can't create,alter or delete rows in SQL db in Azure

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2018]
In my other question, I asked how to connect to Azure SQL db and someone helped me out by suggesting I should set Encrypt =false in my connection string. That worked out. So I closed that issue.

Now, my vNext website is showing list of rows in the table, but I can't do create, update or delete in my table while hosting on Ubuntu. I can do it while hosting on Windows normally. Same code.

If someone had similar situation, how do you solve this? What can I do about this? If you  need more info, ask away.

**Comment by divega** [comment]
@Junsui That said, this is a scenario that we haven't tested exhaustively, that said we recently became aware of some limitations in the SqlClient implementation included in Mono and we added workarounds that should help things work: https://github.com/aspnet/EntityFramework/commit/71980107ab0e3707f9ce1f9855960055303c46b0 https://github.com/aspnet/EntityFramework/commit/71980107ab0e3707f9ce1f9855960055303c46b0

It would be great if you could try recent builds from our dev branch or the upcoming beta 4 bits. Both include the workarounds. Otherwise please provide more information about the failure, e.g. any exceptions you are seeing with stack traces.

**Comment by rowanmiller** [comment]
Closing as we haven't heard back with details. Feel free to reactivate if you can test on latest builds and provide error details.

We will be doing testing in this area at a later date too.
