### ISSUE TITLE
Query: revisit extensibility of null semantics visitor

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#20204]
Currently null semantics visitor has extensibility point to handle provider specific nodes (via VisitInternal), but we don't have good way to custom handling of existing sql expression nodes (e.g. some specific SqlFunctions in postgresql. We should consider if nullable property should be protected rather than public etc.

**Comment by smitpatel** [comment]
From API review to keep in mind
- Rename to *NullabilityProcessingSqlExpressionVisitor*
  - Use a method (DoNotCache) instead of a setter on CanCache 
  - Hide NonNullableColumns, add an Add method
  - Just return SelectExpression from Process (no bool)
  - Just return TResult from VisitInternal and use an output parameter for the bool
