### ISSUE TITLE
A second operation started on this context before a previous operation completed in EF 3.1

### ISSUE THREAD

**Issue by JuanIrigoyen** [dotnet/efcore#20252]
We are upgrading from EF 2.2 to 3.1 using .net Framework 4.8. One of the problems arises when executing different queries with the same context and that worked until version 2.2

The error shows: **a second operation started in this context before a previous operation was completed.**

I understand that opening and closing the context is the most appropriate in this case. However, this would force me to change hundreds of methods in my application. We try not repeat same code to open and close the context in every method. For this, we shared the context in every business manager class and dispose this when dispose the class. 

Something similar to this:

``` C#

public sealed class InformesDA : MasterDA<Informes>
{
     private readonly MaldivasBaseContext _ctx;
     public InformesDA()
     {
         _ctx = CurrentCtx as MaldivasBaseContext; 
     }

    void Dispose(bool disposing)
    {
        if (disposing && _ctx != null) _ctx.Dipose()
    }
```
 
### Steps to reproduce

I have read the possibility of mitigate this set the **ServiceLifetime.Transient**

In my program I configure the context dependent of a connection, we use .net framework 4.8 in windows forms app. How can we establish ServiceLifetime.Transient in this code?

``` C#
var optionsBuilderBase = new DbContextOptionsBuilder<MaldivasBaseContext>();
optionsBuilderBase.UseSqlServer(connectionString);
ActivateLogger(logger, optionsBuilderBase);
return new MaldivasBaseContext(optionsBuilderBase.Options);
```

Or is there another alternative to mitigate this problem?

### Further technical details

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Core 3.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@JuanIrigoyen DbContext is not safe to use from multiple threads concurrently, and this has not changed between EF Core 2.2 and 3.1. So this means either:
* The detection of this in 2.2 was failing, but it is now being correctly detected in 3.1. (Likely, since the way we detect was made more robust in 3.x.)
* There is a bug in the 3.1 detection.
* The application wasn't doing this before and now is after updating.

We can dig into the root cause if you think it would be useful, but ultimately it's never going to be safe to use the same instance from multiple threads.

D.I. is only relevant here if you're using D.I. to create your DbContext instances. Unless you need to use D.I., just use `new MaldivasBaseContext()` to create a new instance.

**Comment by JuanIrigoyen** [comment]
Thank you @ajcvikers!!. I understand that the only solution is to open and close the context as recommended.
