### ISSUE TITLE
InvalidOperationException is not thrown using InMemory Database

### ISSUE THREAD

**Issue by VILLAN3LL3** [dotnet/efcore#20257]
Since EF Core 3.0 database queries that cannot be executed on the server run into an InvalidOperationException ("The LINQ expression xxx could not be translated"). That's fine. Unfortunately these exceptions are not thrown in my integration tests where I use an InMemory Database:

```
 services.AddDbContext<MyDbContext>(options =>
            {
                options.UseInMemoryDatabase("DefaultConnection");
                options.EnableDetailedErrors();
                options.EnableSensitiveDataLogging();
            });
```
So although all my tests are green, I run into exceptions in production mode with my code.
How can I make my integration tests detect the invalid operation queries?

### Further technical details

EF Core version: 3.1.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer and InMemory database
Target framework: netcoreapp3.1
Operating system: Windows 10
IDE: Microsoft Visual Studio Enterprise 2019 Version 16.4.4

**Comment by ajcvickers** [comment]
@JulidaRocks Fundamentally, you'll need to run your tests against the same database engine that your production code uses. This because there are differences in the sets of queries that can be translated against each type of database. See https://github.com/dotnet/EntityFramework.Docs/issues/430 and https://github.com/dotnet/EntityFramework.Docs/issues/1304, and also the discussion on https://github.com/dotnet/efcore/issues/18457
