### ISSUE TITLE
Build NuGet from source

### ISSUE THREAD

**Issue by michaelmualem** [dotnet/efcore#20289]
Hello

I have a running .Net Core project referencing the following packages:
- Microsoft.EntityFrameworkCore
- Microsoft.EntityFrameworkCore.Design
- Microsoft.EntityFrameworkCore.Tools
- Microsoft.EntityFrameworkCore.Sqlite

I have built these from source but after replacing the outputs in my .Net Core project there is a runtime exception: "Could not load file or assembly 'Microsoft.EntityFrameworkCore.Abstractions, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference."

What should resolve this ?

**Comment by smitpatel** [comment]
You would need to build and replace all the binaries which would be appearing in dependencies of EF projects you built. `Microsoft.EntityFrameworkCore` depends on EFCore.Abstractions/EFCore.Analyzers.

Since you did not replace those, there is assembly version mismatch. To resolve it copy those dll to your project output.

**Comment by ajcvickers** [comment]
@micahbresette I'm curious why you are building from source. (Not saying it's wrong, just interested. :-))

**Comment by micahbresette** [comment]
Hey @ajcvickers, FYI Your previous comment tagged me; likely by accident as I am not a participant on this topic.

**Comment by ajcvickers** [comment]
@micahbresette Sorry about that--thanks for pointing it out.
 
@michaelmualem  I'm curious why you are building from source. (Not saying it's wrong, just interested. :-))
