### ISSUE TITLE
Is there any way to run the ./build script offline?

### ISSUE THREAD

**Issue by IAmJustAQuestion** [dotnet/efcore#20290]
I am trying to run the ./Build script offline, after running it online and downloading + installing all the required components.
but the script still fails, because it is trying to download everything again, even when i already run it once.

I would like to have some kind of parameter in the script that i can toggle, that will use the resources previously downloaded without downloading them again.

thank you.

**Comment by smitpatel** [comment]
@dotnet/aspnet-build

**Comment by dougbu** [comment]
The top-level scripts pass the `-restore` / `--restore` command-line argument to eng/common/build.ps1 and eng/common/build.sh. Best option is to execute those scripts directly but without `-restore` / `--restore` e.g. `./eng/common/build.sh --build`.

Please close the issue if this works for you. Follow up here otherwise.
