### ISSUE TITLE
Event store persistence using EF core 

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/efcore#20306]
Hi,
One of the pattern that has evolved with cloud is Even store persistence. EF core has almost become the de-facto for .NEt core. This feature request is to add event store capability to EF core.

The feature I'm requesting is like what we get with Marten ORM for postgres(https://github.com/JasperFx/marten). But then I wanted this capability to be available to all EF core supported database. There are some open source packages that are available like https://github.com/jacqueskang/EventSourcing/blob/develop/doc/EfCoreSetup.md. It would be of immense help if this added into EF core as it is more a design pattern that needs to be implemented and lots of design best practices needs to be kept in mind and lots of normal usecases and edge usecases needs to be considered

**Comment by ajcvickers** [comment]
Note from team triage: @JeremyLikness to do some investigation into what might make sense for event stores and EF in general.

**Comment by JeremyLikness** [comment]
Event sourcing is not something that EF Core should have a built-in opinion about. There are different approaches (such as the two examples provided: a document-based approach like Marten ORM, and a DDD approach like the EventSourcing project referenced), different ways to store/replay events and even different capabilities built into different databases. If there is something in EF Core that prevents the successful implementation of an event store, please file an issue and we will address. Otherwise recommendation is to use or implement an external package.

**Comment by VenkateshSrini** [comment]
One of the key functionality of the Event source is to have aggregate to arrive at a current state. I think an opinionated approach on Document based one or the DDD can be considered as first level. Based on further asks, some other flavors can be implemented.
