### ISSUE TITLE
After modifying entity, query result could not match predicate.

### ISSUE THREAD

**Issue by motz-art** [dotnet/efcore#20333]
### Steps to reproduce
1. Fetch some entity from DB (with tracking query). And update some property.
2. Run query, that do not matches new property value.
Result:
Modified entity is included into query results even it doesn't match a predicate.
Expected result:
Ideally: Modified entity is excluded from query result as it doesn't match the predicate.
Or just return value from Db, at least it will match predicate.

Here is minimal reproduction: https://github.com/motz-art/EFQueryModifiedEntities.git

``` C#
            using (var context = new BlogContext())
            {
                {
                    var modifiedItem = context.Blogs.First(x => x.Name == "Blog 2");
                    modifiedItem.Name = "Other 2";
                }

                // Later in code.
                {
                    var items = context.Blogs.Where(x => x.Name.StartsWith("Blog")).ToList();

                    foreach (var item in items)
                    {
                        Debug.Assert(item.Name.StartsWith("Blog")); // Not all Names starts with "Blog"!
                    }
                }
            }
```

### Further technical details

EF Core version: 3.1.2
Database provider: Microsoft.EntityFrameworkCore.InMemory 3.1.2
Target framework: .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.4

**Comment by smitpatel** [comment]
Forgot to save changes to database? 😉

**Comment by ajcvickers** [comment]
@motz-art EF always executes queries against the database, so the query will return entity instances based on the value in the database, not the value in the tracked entity. So if the database has been updated since the entity was tracked, then the predicate is still evaluated against the database, but the results may contain stale data that don't match what the predicate tested for in the database.

Issue #2982 tracks combining local and database queries in a way that might give you the results you are expecting, but that change is big and complex and would probably never work well anyway, so I don't think we'll ever do it.
