### ISSUE TITLE
Enable throwing better exceptions for specific cases of failed translation

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#20344]
If it cannot rewrite it should just return original tree. Let client eval deal with it.

**Comment by smitpatel** [comment]
Related #20164

**Comment by ajcvickers** [comment]
From an experience perspective, the more specific we can get about why something can't be translated the better. However, some of the expression visitors are designed not to throw. Therefore, we should look at how to propagate the more detailed information to the place that will throw.

**Comment by roji** [comment]
One main point is to also avoid duplicating logic from the concerned visitor in order to identify specific patterns and throw the informative exception. If we end up doing this, it may be better to simply expose knobs in the expression visitor, telling it whether to throw or let the tree through. The visitor would throw by default, unless a provider has explicitly disabled that in order to handle things in translation.

**Comment by smitpatel** [comment]
All exception messages from scenarios Entity Equality was throwing has been migrated to new entity equality implementation.

**Comment by ajcvickers** [comment]
@smitpatel What are examples of better exception messages that we now throw? Are they included in preview 4?

**Comment by smitpatel** [comment]
This issue tracked only migrating existing exception messages of EntityEquality rewrite to translation pipeline. No new exception message were added.

**Comment by ajcvickers** [comment]
@smitpatel Where are we tracking new exception messages?

**Comment by smitpatel** [comment]
https://github.com/dotnet/efcore/issues/20612
