### ISSUE TITLE
Default order of returned entities

### ISSUE THREAD

**Issue by TonyTroeff** [dotnet/efcore#20460]
This is rather a question than an issue... In some of my projects there is always one entity for which the returned results are not ordered by id.  would like to know if this is expected or not? I can provide with some code samples if this is not something usual.

### Further technical details

EF Core version: The most recent project uses 3.1.3
Database provider: I have noticed that problem with tests that use Microsoft.EntityFrameworkCore.Sqlite
Target framework: Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 Enterprise 16.5.1

**Comment by ErikEJ** [comment]
Never expect an order.

**Comment by ajcvickers** [comment]
@TonyTroeff To expand on what @ErikEJ said, EF Core will return the entities in the order that they come from the database. For most databases, that order is undefined unless an explicit ordering is applied. (Note that adding an ordering often has perf implications.) Sometimes, because of the way the database is storing values, the rows may appear to come back in PK order, but often that can change as the internal data structures are expanded.

**Comment by SimonCropp** [comment]
this is my attempt at a solution https://github.com/SimonCropp/EntityFramework.OrderBy

**Comment by ErikEJ** [comment]
@SimonCropp Maybe add this to the extension list in docs?

**Comment by roji** [comment]
Just noting that asking the database to order results has a performance price, as opposed to not doing so; a solution such as the above may have the effect of having the database always perform the extra ordering even for queries the order isn't actually important. This is why, for perf-conscient application, I'd recommend explicitly specifying OrderBy() in the query **only** when the ordering is actually needed, and not doing so for queries where it isn't.

Of course, it's always good to have options, and it's great that an extension can help people who prefer to always have a default ordering, even if that might have a performance cost.

**Comment by SimonCropp** [comment]
@roji do u think Automatic Index Creation mitigates the performance impact enough? https://github.com/SimonCropp/EntityFramework.OrderBy?tab=readme-ov-file#automatic-index-creation

**Comment by roji** [comment]
@SimonCropp it might for very simple cases, but not for other cases. For example, if you Include an additional collection navigation, you're now ordering by e.g. two Id columns (the principal's and the dependent's); at that point you need a composite index over both things (the two separate indexes you've created don't work together).

In fact, EF currently does exactly that when you do Include over collection navigations: it adds orderings by each included entity's key properties, for its own purposes (so that dependents are grouped together in the resultset, for reading them). #29171 is precisely about removing that behavior, since the orderings are expensive (and if you add many Includes, **very** expensive). I really hope to do #29171 by EF 12 at the latest - your proposal here goes in the other direction.

I'm generally a believer in embracing the database and the way it works, rather than trying to impose foreign, external practices on it. SQL databases really do work in this way - they contain logically unordered sets, and if you want ordering, you need to make that explicit. What this does is taper over that, and forces an external idea of an ordered list where the database works differently. It slightly reminds me of when people want EF to impose case-sensitive/insensitive string comparisons via UPPER/LOWER; that's just not how the database works - the proper way to do things is to define the column collation etc.

So if you ask me, I'd recommend against doing something like this, and considering on a query-per-query basis whether ordering is important, and if it is, **which** ordering. But that's the beauty of extensions - if this fits some people's needs, they can absolutely use this (and it might not even really affect them that much if they're doing simple things). But I'd maybe at least warn against the possible perf implications.

**Comment by SimonCropp** [comment]
@roji given this performs the same as doing an order at the ef query level. can u point me to the official EF docs on the performance implications of that. and i will add similar docs to my project

**Comment by roji** [comment]
> given this performs the same as doing an order at the ef query level.

Just noting that this is a pretty major performance problem in EF itself - one that we want to fix.

> can u point me to the official EF docs on the performance implications of that. and i will add similar docs to my project

There aren't any at the moment, since it wouldn't be actionable - that's just how EF (currently) works. But you can see the details in #29171.

**Comment by SimonCropp** [comment]
@roji you are suggesting "But I'd maybe at least warn against the possible perf implications." so i would like to duplicate the existing warning from the EF docs about the performance implications of ordering

**Comment by roji** [comment]
As I wrote, there is no warning currently.
