### ISSUE TITLE
Convert constrained list to enum in EF DataBase-First approach

### ISSUE THREAD

**Issue by RredCat** [dotnet/efcore#20596]
I have a table with a status column. This column was created in the following way:
`[Status] VARCHAR(10) NOT NULL CHECK ([Status] IN ('New', 'InProgress', 'Done', 'Error')),`

I know that I could use the `int` type for this column and easily convert it to an enum. But I see some advantages in string type. It is self-described, and it is easier to work directly with the database.

I am looking for a possibility to scaffold enum for a column restricted by string-list.

**Comment by ajcvickers** [comment]
@RredCat We discussed this and while it is an interesting idea, we don't think that we should scaffold this by default because:
* It would require SQL parsing of the check constraint which is a can of worms and something we try to avoid
* This pattern might represent other constructs, such as discriminator columns.

Better customization of the code generated by scaffolding could support this--see #4038. Also, pinging @ErikEJ in case he has ideas for the EF Core Power Tools.

You can, of course, modify the scaffolded code to do this. For example:

```C#
public enum Status
{
    New,
    InProgress,
    Done,
    Error
}
```
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder
        .Entity<Blog>()
        .Property(e => e.Status)
        .HasConversion<string>();
}
```

Implementation of #831 would also allow this change to be retained, although this feature is not scheduled for any time soon.
