### ISSUE TITLE
Add ability to explicitly force query part evaluation during query generation

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/efcore#20610]
I believe that something like the following would be helpful in many scenarios:

```c#
var result1 = context.Customers
    .Where(c => c.Name == EF.Constant(GetMySearchCriteria()))
    .ToList();

var comparisonMode = StringComparison.OrdinalIgnoreCase;
var result2 = context.Customers
    .Where(c => string.Equals(c.Name, "Foo", EF.Constant(comparisonMode)))
    .ToList();
```

A method `EF.Constant()` is used here, to preevaluate part of the query at query build time and returns a `SqlConstantExpression`.

Of course this preevaluated part cannot depend on any database columns etc.

It should be communicated clearly, that whatever is in the body of this method call will be evaluated *only once and at query generation time*. If a clear method description is enough here, the method name could be kept relatively short, which would aid query readability, instead of giving it a long and overly descriptive name.

Some decisions would need to be made, how this affects/is affected by query caching.

---

This might also be useful (either explicitly for calls by users, or implicitly in providers) in conjunction with `EF.Functions.Foo()` methods, that take arguments that changes the behavior of the method. 

Currently, if anything but a constant value is used (e.g. with `string.Equals()` and its comparison parameter as in the example above), then the method needs to throw or, in case the user supplied the argument using a variable, the whole method call needs to generate a `CASE` that evaluates the variable when the SQL is run.

See the following (intentionally simplified) SQL as an example:

```sql
@__comparison_0='2'

SELECT `c`.`CustomerID`
FROM `Customers` AS `c`
WHERE CASE
    WHEN @__comparison_0 IN (4, 0, 2) THEN `c`.`CustomerID` = 'anton'
    ELSE LCASE(`c`.`CustomerID`) = LCASE('anton')
END
```

After implementing and using `EF.Constant()`, it would just look like this:

```sql
SELECT `c`.`CustomerID`
FROM `Customers` AS `c`
WHERE `c`.`CustomerID` = 'anton'
```

**Comment by roji** [comment]
Re the collation/case-sensitivity aspects specifically, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/996#issuecomment-616475003.

Re the general proposal to have EF.Constant, @smitpatel is the more qualified person here. 

* This reminds me of #17598, where we would allow translators to cause specific values of parameters to cache to different versions of the query. For example, today, different queries are already generated when a parameter is null and when it is non-null (this is important for perf); #17598 extends that to aspects other than nullability (e.g. different values of an enum such as StringComparison).
* I think the approach in #17598 would provide the same benefit as EF.Constant, but in a better way: rather than requiring the user to be aware of an advanced API, the translator for StringComparison would be deciding that the StringComparison parameter is worth "literalization"; the user would implicitly get the benefit without needing to know or do anything. It's hard for me to imagine a case where the user has special knowledge about the specific query that the translator doesn't, and which would warrant this.
* Note that there's also [NotParameterized]. This allows a provider to ensure that a specific parameter will never be parameterized (the proposed EF.Functions.Collate has it, for instance, since no database I've seen supports parameterizing the collation string in the expression). However, this only works for methods we own (e.g. EF.Functions), and cannot be applied to built-in methods like string.Equals.

**Comment by ajcvickers** [comment]
Ping @roji

**Comment by roji** [comment]
To summarize:

* Instead of a user-facing EF.Constant, we think that #17598 is a better provider-facing alternative that would allow generating different SQL for different enum values when translating (or indeed, for anything else).
* Specifically for StringComparison, see the discussion in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/996#issuecomment-616475003. I think we agree that in future versions, translating basic .NET string functions accepting String.Comparison in ways that prevent index use should probably be avoided - and the exception should lead to a clear explanation of what to do.

So I'll go ahead and close this for now. @lauxjpn if you think there's anything more to discuss here please post back and we'll reopen.
