### ISSUE TITLE
Move SequentialGuidValueGenerator to SQL Server

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#20627]
This value generator is tailored to the specific needs of SQL Server's clustered keys/indexes, but is the class is in EF Core and is used by StringGuidConverter and GuidToBytesConverter.

**Comment by ajcvickers** [comment]
@roji See #1627

**Comment by roji** [comment]
Ha, that's interesting... Do you remember in which sense this is supposed to be "generally useful functionality" for non-SQL Server providers? The specific byte shuffling performed here seems fairly specific to SQL Server (though I could be wrong). I supposed I could look into sequential GUIDs and other providers.

**Comment by ajcvickers** [comment]
@ anpete? @ divega? ;-)

**Comment by Fazali-Illahi** [comment]
@roji I think it makes more sense to move the guid generation logic to providers. The byte order difference in SQL Server as mentioned in discussed in #20643. And possibly provide COMB GUID implementation as the default.

**Comment by roji** [comment]
That is more or less what this issue proposes. I think it does make sense to keep the non-sequential (i.e. random) GUID generator as common functionality, for those providers that choose to use it, since there's nothing provider-specific about it.

**Comment by ajcvickers** [comment]
While I agree technically, the value doesn't seem high compared to the cost of making a breaking change.

**Comment by roji** [comment]
It's definitely a breaking change, but do you think this class is actually used anywhere? It's not used by the Sqlite or Npgsql providers, and the Pomelo MySQL providerhas its own [MySqlSequentialGuidValueGenerator](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/ValueGeneration/Internal/MySqlSequentialGuidValueGenerator.cs).

**Comment by ajcvickers** [comment]
Not enough value to make a break.

**Comment by dmlarionov** [comment]
I see the value in keeping SequentialGuidValueGenerator considered as generally useful functionality, really.

Using of GUIDs / UUIDs as a keys is usually higher level architecture decision than one of using SQL Server as the database engine in a project. But, if it's ability of being sequential (which is important for performance) is limited to SQL Server two levels of decision become tightly coupled. That's not good.

I want to choose the features of my keys before choosing the database engine. Having SequentialGuidValueGenerator at EF Core level keeps this time-proved algorithm for sequential GUIDs open to reuse by varios DB providers in the form of well tested EF core class. This makes me feel able to change DB engine in the future if I decide to do so (when SequentialGuidValueGenerator be used by Npgsql or others). That's good.

I disagree with the phrase  'byte shuffling performed here seems fairly specific to SQL Server' because what it does is just making it sequential. If the key would be generated by the same algorithm for an entity in PostgreSQL it whould be also benefitial, because it is sequential (this is just the feature of the key). Isn't it?

**Comment by roji** [comment]
> I disagree with the phrase 'byte shuffling performed here seems fairly specific to SQL Server' because what it does is just making it sequential.

@dmlarionov the point is exactly what sequential here means (which specific part of the GUID), and that seems to be an SQL Server-specific thing. 

> If the key would be generated by the same algorithm for an entity in PostgreSQL it whould be also benefitial, because it is sequential (this is just the feature of the key). Isn't it?

Most probably not - do you have anything to back that up?
