### ISSUE TITLE
I use the EF Core official tutorial to create tables and insert data, the time used is more than 100ms

### ISSUE THREAD

**Issue by 19920716** [dotnet/efcore#20728]
The official case https://docs.microsoft.com/zh-cn/ef/core/get-started/?tabs=netcore-cli

DataBase PostgreSQL 12.1

The attachment file：
[demo.txt](https://github.com/dotnet/efcore/files/4521690/demo.txt)
![1](https://user-images.githubusercontent.com/19903385/80086678-a3e79400-858c-11ea-89e9-656c4adc5ea8.jpg)

**Comment by roji** [comment]
@qwe5788319 you seem to be executing every operation only once - there are some significant warm-up costs which probably explain this. For example, the first time you run a query, EF Core needs to compile it (and the .NET JIT needs to also JIT parts of EF Core itself). To measure actual performance, you need to run the same thing many times, and disregard the first few iterations (because of warmup costs).

Rather than trying to measure performance yourself in this way, you should use the [BenchmarkDotNet project](https://benchmarkdotnet.org/) - it allows you to write a simple method, which it will then run in the correct way and extract meaningful statistics. We run benchmarks regularly and are seeing far lower numbers.

Am going to close this for now, but if you write a proper benchmark and see unsatisfactory performance, please post back with the benchmark code and we'll reopen.

**Comment by qwe5788319** [comment]
@roji 
Thank you for answering my doubts.
