### ISSUE TITLE
Allow prefix length to be specified with IndexBuilder.HasIndex()

### ISSUE THREAD

**Issue by olicooper** [dotnet/efcore#20751]
When I use `IndexBuilder.HasIndex()`, EF Core creates a migration which converts the `TEXT` column to a `varchar(255)` before adding the index.

I would like to call `HasIndex` using the FluentAPI and specify a prefix length so that the column doesn't need to be converted. I can manually run this in MariaDB and specify a prefix length of 16 on a `LONGTEXT` column and I'd like EFCore provide the same functionality if possible.
```sql
CREATE INDEX IF NOT EXISTS IX_MailAccountLogs_MessageId ON MailAccountLogs(MessageId(16));
```

**Comment by roji** [comment]
@olicooper we don't maintain any MySQL/Maria providers. If you're using Pomelo.EntityFrameworkCore.MySql, please open this issue in [their repo](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) (otherwise you can see the different providers [on this doc page](https://docs.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli)).

**Comment by olicooper** [comment]
Yep okay, sorry about that. For reference, I have found an open PR for Pomelo: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1069

**Comment by roji** [comment]
Great that it's being taken care of!
