### ISSUE TITLE
ValueConverter only works when a second ValueConverter is configured

### ISSUE THREAD

**Issue by majbo** [dotnet/efcore#20769]
I created a ValueConverter to set the DateTimeKind to UTC on read, but it remains unchainged.

``` 
var dateTimeConverter =
                new ValueConverter<DateTime, DateTime>(v => v, v => DateTime.SpecifyKind(v, DateTimeKind.Utc));
``` 

### Steps to reproduce
I created a simple app here: (https://github.com/majbo/ValueConverterTest)
Run the unit test ConvertDateTimeKindTest, it will fail.
Run the unit test ConvertDateTimeKindAndPkTest, it will succeed. Only difference between the two tests is the additional ValueConverter for the primary key.

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.Sqlite 3.1.3
Target framework:  .NET Core 3.1
Operating system: Window 10
IDE: Rider 2020.1

**Comment by ajcvickers** [comment]
@majbo In the test that does not pass, this is because the entity instance that is saved is still being tracked by the context when you query for it. This means EF doesn't create a new entity instance and the UTC kind will be the same thing it was set to when it was created earlier in the test.

In the test that does pass, the PK value converter is incrementing the PK value before saving it to the database, while leaving the value unchanged in the entity. (This is a _very_ strange thing to do, btw.) This means the query to the database brings back a different entity instance, since the PK is different in the database than it is in the entity that was saved. Since this entity instance is created by EF it runs the value converter on the DateTime read from the database and sets the Kind appropriately.

**Comment by majbo** [comment]
@ajcvickers Of course, its still the same instance! Thanks you, I'll close the issue.
