### ISSUE TITLE
Relational.Specification.Tests Requires .NET Core 3.1, instead of .NET Standard 2.0

### ISSUE THREAD

**Issue by Gwindalmir** [dotnet/efcore#20788]
Even though the .NET requirements for EF Core 3.1 were reverted back to support .NET Standard 2.0, the Microsoft.EntityFrameworkCore.Relational.Specification.Tests package still requires .NETCoreApp,Version=v3.1.

I'm not sure if that was intentional, but it seems odd I can make a provider using, and targeting .NET Standard 2.0, but I can't actually test it.

NU1202: Package Microsoft.EntityFrameworkCore.Relational.Specification.Tests 3.1.3 is not compatible with net472 (.NETFramework,Version=v4.7.2). Package Microsoft.EntityFrameworkCore.Relational.Specification.Tests 3.1.3 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)
Package restore failed. Rolling back package changes for '<project>'.

### Further technical details

EF Core version: 3.1.3
Target framework: .NET Standard 2.0/.NET Framework 4.7.2
Operating system: Windows 10 1909
IDE: Visual Studio 2017 15.9.22

**Comment by ajcvickers** [comment]
@Gwindalmir .NET Standard 2.0 is not something that can be tested against because code can't run against just the standard--it instead needs one of the actual runtime platforms that supports the standard. So you should test against at least one platform that implements the standard--in this case we're using .NET Core 3.1. In the current master branch for EF Core 5.0, we're testing against .NET Core 3.1 and .NET 5.

**Comment by roji** [comment]
It's true that [Microsoft.EntityFrameworkCore.Relational.Specification.Tests](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/3.1.3) targets netcoreapp3.1, where it should probably target netstandard2.0.

@Gwindalmir, assuming your provider also supports .NET Core, as a workaround you can still have a test project targeting netcoreapp3.1 and use that to ensure the provider works well.

**Comment by Gwindalmir** [comment]
Unfortunately I still use VS 2017, and I don't have go ahead yet to move to 2019.
I am, however installing 2019 locally for this purpose, just to move forward for the time being.

**Comment by ajcvickers** [comment]
@Gwindalmir It may be worth mentioning here that EF Core 5.0 (scheduled for November) will require .NET Standard 2.1 and will not run on .NET Framework. See [the EF Core 5 plan](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan) for more details. So .NET Standard 2.0 support in a provider created now will have somewhat limited usefulness.

**Comment by Gwindalmir** [comment]
EF is such a fast moving target, it doesn't really seem to make much difference to me. We already support 2.0 in our product, so ideally everything would be on the same standard.

It's like asking the question "Should I buy a new GPU now, or wait for the next gen?"
If you keep waiting for the next one, you are always waiting.
😆

**Comment by ajcvickers** [comment]
@Gwindalmir I here you. Although things are converging in the .NET world around Core. So going the Core route now will set things up for the future, whereas .NET Framework support will not.

**Comment by ajcvickers** [comment]
@Gwindalmir We discussed this, but we don't think that going back and changing the testing for 3.1 now that it's shipped and in servicing is something that we want to, especially given that it has no value past 3.1. Suggest you test with .NET Core 3.1, if you can. Otherwise it should be possible to fork the repo and make the changes needed for your own testing.
