### ISSUE TITLE
Failed to create migration

### ISSUE THREAD

**Issue by koeltp** [dotnet/efcore#20800]
![image](https://user-images.githubusercontent.com/2775276/80784575-0f92b800-8bb0-11ea-9b72-7bc79f90bf84.png)
项目结果如上图所示。
ef core模型在一个类库中，当我Main方法调用的名称为BuildHost方法时，我在包管理器中执行
 `Add-Migration initcreated`时，报如下错误：
![image](https://user-images.githubusercontent.com/2775276/80784734-98a9ef00-8bb0-11ea-9285-66fcaad5da1c.png)
而当我在Main方法中将BuildHost的名字改为CreateHostBuilder时，就可以成功了。
![image](https://user-images.githubusercontent.com/2775276/80784820-dad33080-8bb0-11ea-8d4b-6fcdd5e46e6e.png)

是因为有这样的约定，还是是一个bug。
### Further technical details

EF Core version:3.1.3
Database provider: Pomelo.EntityFrameworkCore.MySql
Target framework:  .NET Core 3.1
Operating system:win10 1903
IDE:  Visual Studio 2019 16.5.4

谢谢

**Comment by ajcvickers** [comment]
Machine translation:

## Failed to create migration 

![image](https://user-images.githubusercontent.com/2775276/80784575-0f92b800-8bb0-11ea-9b72-7bc79f90bf84.png)

The project results are shown in the figure above.
The ef core model is in a class library, and when my Main method calls the BuildHost method, I execute it in the package manager
When Add-Migration initcreated, the following error was reported:

![image](https://user-images.githubusercontent.com/2775276/80784734-98a9ef00-8bb0-11ea-9285-66fcaad5da1c.png)

And when I changed the name BuildHost to CreateHost Builder in the Main approach, It worked.

![image](https://user-images.githubusercontent.com/2775276/80784820-dad33080-8bb0-11ea-8d4b-6fcdd5e46e6e.png)

It's because there's such a convention, or is it a bug.

**Comment by ajcvickers** [comment]
@koeltp The method must be called `CreateHostBuilder` for it to be found by EF. See also https://docs.microsoft.com/ef/core/miscellaneous/cli/dbcontext-creation

**Comment by koeltp** [comment]
thank you very much.
