### ISSUE TITLE
Accessing DI when use AddDbContextPool

### ISSUE THREAD

**Issue by mabouchalkha** [dotnet/efcore#21085]
in our startup we add AddDbContextPool
```csharp
 services.AddDbContextPool<CPDbContext>(options => options.UseSqlServer("Connectionstring"));
```
and in our CPDbContext we cannot inject any service because of AddDbContextPool accept only DbContextOptions in the constructor.
Is there any way to get IHttpContextAccessor in the OnModelCreating to get claims from it?.

```csharp
 public class CPDbContext : DbContext
{
        public CPDbContext(DbContextOptions<CPDbContext> options) : base(options)
        {
        }

       //code omitted

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        //we need IHttpContextAccessor here to get claims we need 
      // var email = _context.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "emails")?.Value;
            modelBuilder.Entity<Job>().HasQueryFilter(j => j.Agreement.UserAgreements.Any(ua => ua.Email == email ));
        }
}
```
Thank you

**Comment by dominiclapointe** [comment]
@ajcvickers So there is no way to use the AddDbContextPool and having a global filter? Would work for softDelete but its impossible to use the performance enhancement of the pooling as soon as we need injection in the Context?

Thank you

**Comment by dominiclapointe** [comment]
@ajcvickers As you says it does limit DI, what is the limitation? it seem to me like it completely prevent DI more than soft limitation?

Thank you

**Comment by ajcvickers** [comment]
@mabouchalkha Yes, if you need to inject other services into your context, then you can't use context pooling. This should be fine; pooling is unlikely to have any real benefit in this kind of application. If you're seeing a case where not using pooling is significantly impacting your perf, then we would like to hear about that and investigate it.

Beyond that, you should not attempt to build a new model just to change the value in the query filter. This won't work out of the box because OnModelCreating is only going to be called once and the resulting model is then cached. This is important because model building is slow.

Instead, reference a property on the context instance inside the query filter, and then set that property appropriately for each context created. For example:

```C#
modelBuilder.Entity<Job>()
    .HasQueryFilter(j => j.Agreement.UserAgreements.Any(ua => ua.Email == this.Email ));
```
