### ISSUE TITLE
Query with CTE not working

### ISSUE THREAD

**Issue by lvmajor** [dotnet/efcore#21134]
Related issue reported (see [here](https://github.com/npgsql/efcore.pg/issues/1153), but I have been advised to open a new one on the efcore repo so here it is. 

I am trying to run a query containing a CTE but it is not working due to the fact that EF tries to include it in a subquery (as of my limited understanding about this) but it seems like in this case, it shouldn't have to be put within a subquery as no composition is done (correct me if I'm wrong here @roji)

### Steps to reproduce

These are not actual steps as I don't have a repro project as it's only a single query that is faulty, and here is a slightly shortened version of the query (but the real one is exactly the same, just a little longer as there are more rows retrieved in the `relatedRowNumbers` CTE)

```C#
var queryResult = await _dbContext.EquipmentResultsTable.FromSqlRaw($@"
    WITH equipmentResults AS
    (
        SELECT ROW_NUMBER() OVER (Order BY EquipmentId, TestDate) AS rn
        , *
        FROM dbo.EquipmentResultsTable
        WHERE EquipmentId IN (1,2)                            
    ),
    relatedRowNumbers AS 
    (
        SELECT
        rn AS currentResultRN,
        rn+1 AS nextResultRN
        from equipmentResults
        WHERE Id IN (3,4)
    )
    SELECT * from equipmentResults
    WHERE rn IN (select currentResultRN from relatedRowNumbers) OR rn IN (select nextResultRN from relatedRowNumbers)")
.ToListAsync();
```

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system:
IDE: Visual Studio 2019 16.6.1

**Comment by roji** [comment]
One way to deal with this would be for EF Core to not embed the raw SQL in a subquery if it is not composed over.

**Comment by sdanyliv** [comment]
I have implemented CTE support for linq2db more than three years ago and you can use this feature via extension [linq2db.EntityFrameworkCore](https://github.com/linq2db/linq2db.EntityFrameworkCore)

Something like this, no magic strings:
```cs
var ids = new int[] {1, 2};
var relatedIs = new int[] {3, 4};

var equipmentResults = 
	from e in _dbContext.Equipment
	where ids.Contains(e.EquipmentId)
	select new 
	{
		RN = Sql.Ext.RowNumber().Over().OrderBy(e.EquipmentId).ToValue(),
		Equipment = e
	};

equipmentResults = equipmentResults.AsCte("equipmentResults");

var relatedRowNumbers = 
	from er in equipmentResults
	where relatedIs.Contains(er.Equipment.EquipmentId) 
	select new 
	{
		currentResultRN = er.RN,
		nextResultRN    = er.RN + 1
	};

relatedRowNumbers = relatedRowNumbers.AsCte("relatedRowNumbers");

var finalQuery = from er in equipmentResults
	where er.RN.In(relatedRowNumbers.Select(r => r.currentResultRN)) ||
	      er.RN.In(relatedRowNumbers.Select(r => r.nextResultRN))
	select er.Equipment;

var result = await finalQuery.ToArrayAsync();
```
Here we go:
```sql
WITH [equipmentResults] ([Equipment_EquipmentId], [RN], [Id])
AS
(
	SELECT
		[e].[EquipmentId],
		ROW_NUMBER() OVER(ORDER BY [e].[EquipmentId]),
		[e].[Id]
	FROM
		[Equipment] [e]
	WHERE
		[e].[EquipmentId] IN (1, 2)
),
[relatedRowNumbers] ([currentResultRN], [nextResultRN])
AS
(
	SELECT
		[er].[RN],
		[er].[RN] + 1
	FROM
		[equipmentResults] [er]
	WHERE
		[er].[Equipment_EquipmentId] IN (3, 4)
)
SELECT
	[er_1].[Id],
	[er_1].[Equipment_EquipmentId]
FROM
	[equipmentResults] [er_1]
WHERE
	(EXISTS(
		SELECT
			*
		FROM
			[relatedRowNumbers] [r]
		WHERE
			[r].[currentResultRN] = [er_1].[RN]
	) OR EXISTS(
		SELECT
			*
		FROM
			[relatedRowNumbers] [r_1]
		WHERE
			[r_1].[nextResultRN] = [er_1].[RN]
	))
```
Strange query by the way. You are trying to do something which may do not need CTE usage at all but only Window Functions.

**Comment by os1r1s110** [comment]
@sdanyliv Thanks for the pointer, I will look at your extension! As for the query, I am really not a SQL expert so the query might effectively be a bit overkill/not exactly optimal.

IIRC I had looked at window functions but it was not giving me the expected results. As for the "magic strings", these are only used in the example above, they are hydrated from variables in the actual code. 

I will take another look to see if a window function could be used in my scenario because last time I tried, I failed. Here is the goal of this query and why I am using CTE. 

When test results are updated for a given equipment, I need to reprocess them with previous results on the same equipment to compute rates of changes between results (also need to check if there are more recent results for the same equipment as their respective rates of change will also be affected by changing the "current" results). 

To accomplish this I do the following:
1. First create a list of all the equipment for which results have been updated since last rate compute task has run. This list is used as a parameter to the 1st CTE, which returns me a list containing all the test results of all the specified equipment (in the example equipment with id 1 and 2).

2. Once I have this list, I then need to find the specific rows for which results have been updated, and then go on to find their adjacent rows (results are also sorted by date in 1st CTE). This is what the 2nd CTE is used for (attributing row numbers (here the window function could be beneficial I guess)

Here is an example result table after running 1st `CTE`, in which I identifier the rows that I need to retrieve in the final result (and for which I used the 2nd `CTE` and final `SELECT` clause)


Rn | EquipmentId | ResultsRowId | Date Updated | Note
-- | -- | -- | -- | --
1 | 1 | 1 | 2020-06-05 |  
2 | 1 | 2 | 2020-06-06 |  
3 | 1 | 3 | 2020-06-07 | Previous relative to 1st
**4** | **1** | **4** | **2020-06-08** | **1st results row updated**
5 | 1 | 5 | 2020-06-09 | Next (relative to 1st)
6 | 2 | 28 | 2020-06-10 |  
7 | 2 | 29 | 2020-06-11 |  
8 | 2 | 31 | 2020-06-12 |  
9 | 2 | 54 | 2020-06-13 | Previous
**10** | **2** | **108** | **2020-06-14** | **2nd results row updated**
11 | 2 | 109 | 2020-06-15 | Next
12 | 2 | 111 | 2020-06-16 |  
13 | 2 | 112 | 2020-06-17 |  

Where I have specified which rows were updated since last rates of change computing has been done and where we see the adjacent rows that need to be retrieved (potentially with window function?)

**Comment by sdanyliv** [comment]
@os1r1s110, please make an issue in linq2db repository to do not flood big community.
Previous value is
```cs
PrevValue = Sql.Ext.Lag(e => e.InterestingValue).Over()
   .PartitionBy(e.EquipmentId).OrderBy(e.DateUpdate).ToValue(),
```

**Comment by os1r1s110** [comment]
@sdanyliv ok, I will create an issue on your repo to continue discussion even though it's not really an issue at this point (the impossibility to perform CTE with EF Core is though) so I'll let this one open too.

**Comment by smitpatel** [comment]
There is no actual repro in this issue. 
Since the issue filed so far
- We detect non-composed raw SQL and don't generate subquery.
- We detect and throw better message for raw SQL in subquery which cannot be composed.
- We made the detection stronger and allowed providers to override it.
- We fixed bug in detection for identifying non-composed raw SQL.
- We added a way to configure discriminator mapping complete so raw SQL is not put in subquery so we don't force subquery with hierarchy.

With all other improvements the first query posted should be working. Closing this issue as no repro. If OP provides a runnable code which repro issue, we can reopen.
