### ISSUE TITLE
InMemory: Enable joins between sources which have client eval

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#21200]
Spun off from #17763 & #19247 
Part of broader issue #20291

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.
