### ISSUE TITLE
InMemoryDatabase Memory Leak

### ISSUE THREAD

**Issue by chrisajohn** [dotnet/efcore#21314]
For our tests we use the in memory database.  I am trying to run our tests in parallel because we have many of them and we would like to speed up the time it takes.

When I create a context like this it does not leak memory and is pretty performant, but the tests cannot be run in parallel due to the static InMemoryDatabaseRoot (same goes if I leave off the "InMemoryDatabaseRoot" part of the "UseInMemoryDatabase").

```C#
        public static readonly InMemoryDatabaseRoot InMemoryDatabaseRoot = new InMemoryDatabaseRoot();
        
  ...
            var options = new DbContextOptionsBuilder<SContext>()
                .UseInMemoryDatabase(Guid.NewGuid().ToString(), InMemoryDatabaseRoot)
                .ConfigureWarnings(w => w.Ignore(InMemoryEventId.TransactionIgnoredWarning))
                .Options;

            var sContext = new SContext(options);
```

When we write it like the following, I can run them in parallel, but the tests run slowly and I can see a memory leak happening as I run each test.  No matter if I dispose of the context or "EnsureDeleted", the memory keeps going up and up and up as each test runs which causes an out of memory exception.

```C#
var options = new DbContextOptionsBuilder<SContext>()
                .UseInMemoryDatabase( Guid.NewGuid().ToString(), new InMemoryDatabaseRoot())
                .ConfigureWarnings(w => w.Ignore(InMemoryEventId.TransactionIgnoredWarning))
                .Options;

            var sContext = new SContext(options);
```

Is it possible there is a bug that is not disposing of the passed in In Memory Database Root?

### Further technical details

EF Core version: 2.2.6
Database provider: InMemory
Target framework: .NET Framework 4.7

**Comment by ajcvickers** [comment]
@chrisajohn Consider reading through the guidance documentation on testing: https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/

Also note that EF Core 2.2 is [out-of-support](https://docs.microsoft.com/en-us/ef/core/what-is-new/).

With regard to the database root, it is not disposable and so cannot be disposed. Once it is no longer referenced and the GC has had a chance to run, then it should no longer be in memory. If this isn't the case, then please update to EF Core 3.1 and then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by chrisajohn** [comment]
@ajcvickers  Thanks for your response.  Is there a way to upgrade to 3.1 that won't blow up on certain queries?  (Basically make it run like 2.2?)  We have hundreds of queries that I know break with 3.1 and I can't try to update all at once.

FYI - In 2.2 it does not release even after I see GC running.  I will try to get a 3.1 setup running to see.

**Comment by ajcvickers** [comment]
@chrisajohn There is no way to make 3.1 queries work like 2.2 because the query pipeline was changed extensively for the 3.0 release.
