### ISSUE TITLE
AsNoTracking in subquery is making original query no tracking

### ISSUE THREAD

**Issue by tomasbruckner** [dotnet/efcore#21368]
### Steps to reproduce
If I have AsNoTracking on subquery, EF Core does not start tracking entities. If I remove AsNoTracking from subquery, it works correctly. I would expect to not start tracking only if I call AsNoTracking on the main query.

``` C#
public class Foo {
  public int Id { get; set; }
  public string Data { get; set; }
}

public class FooRecursion {
  public int Id { get; set; }
  public int ParentId { get; set; }
}


var subQuery = _db.FooRecursion.Where(o => o.ParentId == 1).Select(o => o.Id).AsNoTracking();
var entites = await _db.Foo.Where(o => subQuery.Contains(o.Id)).ToListAsync();

foreach (var entity in entities) {
  entity.Data = "new value";
}

await _db.SaveChangesAsync();
```

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Rider

**Comment by ajcvickers** [comment]
@tomasbruckner `AsNoTracking` always applies to the entire query. We know that this can sometimes be confusing because it looks like a query operator. We did try making it behave as you suggested, but the interactions between the tracking and no-tracking queries became complicates, and it was also a break from EF6 behavior, so we didn't end up going that way.

**Comment by tomasbruckner** [comment]
Ok, thanks for the explanation.
