### ISSUE TITLE
Transaction - EnableRetryonFailure exception in .net core 3.0 

### ISSUE THREAD

**Issue by mymatrixpixel** [dotnet/efcore#21530]
Hi Team,

We are migrating Entity Framework to EF core 3.1.

Wherever we have transaction code , getting below exception.

"An exception has been raised that is likely due to a transient failure.consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseSqlServer' call."

I added enableretryonfailure() in onconfigure event. 

And then do we need to add Execution startegy whereever we have transactions code?.

Please give a solution.

Thanks.

**Comment by roji** [comment]
@mymatrixpixel you probably want to read [the docs on connection resiliency](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency).

In simple cases, once you configure an execution strategy at the context level (via EnableRetryOnFailure or ExecutionStrategy), you don't need to do anything in specific in code doing updates - the strategy will automatically retry several times when you do SaveChanges.

However, if you're managing your own transactions, then you indeed need to manually invoke the execution strategy, since SaveChanges can no longer start transactions on its own (this is detailed in [this doc section](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#execution-strategies-and-transactions)).

Is there any other aspect here that is unclear?

**Comment by mymatrixpixel** [comment]
@roji  I have few doubts - do we need to add resiliency= true in connection string?. Also provide name  = Microsoft.Data.SqlClient. if I do these changes it won't create any issues?.
Migrating from ef to efcore 3.1 , we have code along with manually handled transactions. Initially we add enableretryonfailure but we ran into an issue. So we added startegy evrywhere. Then we removed enableretryonfailure and startegy too. But still we have old transactions code. So from ur point ( do we need to enable resiliency=true and remove transaction (old code)) will it work?

**Comment by roji** [comment]
@mymatrixpixel SqlClient has [some built-in resiliency features](https://docs.microsoft.com/en-us/sql/connect/ado-net/step-4-connect-resiliently-sql-ado-net?view=sql-server-ver15), but unless I'm mistaken these apply only to connecting, and not to executing commands. The EnableRetryOnFailure/ExecutionStrategy feature is implemented in EF Core level (so at a higher level than the database driver), and encompasses command execution, not just opening connections. So the two are unrelated features working at different levels, and are unrelated - both can be enabled, or just one.

**Comment by AndriySvyryd** [comment]
@mymatrixpixel It's better to disable the SqlClient connection resiliency as it can cause additional delays for non-transient errors. EF implementation is a superset unless you are also using the same ADO.NET connection outside of EF.

**Comment by mymatrixpixel** [comment]
Ok thank you @AndriySvyryd
