### ISSUE TITLE
No data stores are configured exception

### ISSUE THREAD

**Issue by guardrex** [dotnet/efcore#2156]
Win7 x64
DNX: dnx-coreclr-win-x64.1.0.0-beta5-11744
EF: 7.0.0-beta5-13161

```
No data stores are configured. Configure a data store by overriding OnConfiguring in your
DbContext class or in the AddDbContext method when setting up services.
```

... so what have I done wrong here ...

```
services.AddEntityFramework()
    .AddSqlServer()
    .AddDbContext<FirstDBContext>(options => options.UseSqlServer(@"my_conn_string"))
    .AddDbContext<SecondDBContext>(options => options.UseSqlServer(@"my_conn_string"));
```

**Comment by Keraxel** [comment]
You should try to add UseSqlServer to OnConfiguring() in your DB Context. It works for me.
However, it's still a bug.

**Comment by GuardRex** [comment]
@Keraxel Yes, thanks for confirming that. I did move it to `OnConfiguring()` when that wasn't working. This doesn't seem to be a dup issue ... but I'll (or someone at MS can) close it if it is.

**Comment by divega** [comment]
How are you creating the context instances? By default services are wired up at application startup so that you will get a fully configured DBContext instance but __you need to use dependency injection to obtain it__.

**Comment by divega** [comment]
See #2191.

**Comment by GuardRex** [comment]
@divega I don't understand ...
> you need to use dependency injection to obtain it.

I was trying to follow the pattern in MusicStore. Let's start with what I have and if you supply the missing logic/change, then I'm sure that will make more sense to me. I'm more of a visual learner, so a visual pattern should clear it up for me. This works ...
In Startup.cs:
```
public IConfiguration config { get; private set; }
```
In Startup.cs `ConfigureServices` ...
```
config = new Configuration().AddEnvironmentVariables();
config.Set("Database", @"...my_connection_string");
```
Db.cs (don't sweat the goofy naming ... just playing/learning):
```
namespace MyApp.Models {
    public class DbDbContext : DbContext {

        private readonly IConfiguration _config;
        public DbSet<Test> Tests { get; set; }

        public DbDbContext(IConfiguration config) {
            _config = config;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            optionsBuilder.UseSqlServer(_config.Get("Database"));
        }

        protected override void OnModelCreating(ModelBuilder builder) {
            builder.Entity<Test>().Property(typeof(int), "id").ForSqlServer().UseIdentity();
            base.OnModelCreating(builder);
        }

    }

    public class Test {
        [Key]
        public int id { get; set; }
        [Required, StringLength(50), RegularExpression(@"^[A-Za-z]{0,50}$", ErrorMessage = "Field1 contains invalid characters"), Display(Name = "Field1")]
        public string field1 { get; set; }
        [Required, Range(0, int.MaxValue, ErrorMessage = "Field2 is not a valid integer"), Display(Name = "Field2")]
        public int field2 { get; set; }

    }
}
```
Then, it gets used like this (there is a ViewModel for this that holds a few other things) ...
```
namespace paccharter {
    public class DbController : Controller {

        private readonly IConfiguration _config;

        public DbController(IConfiguration config) {
            _config = config;
        }

        [HttpGet]
        [Route("/db")]
        public IActionResult Index() {
            var viewModel = new DbViewModel();
            using(var db = new DbDbContext(_config)) {
                viewModel.Tests = db.Tests.Where(p => p.id > 0).OrderBy(q => q.field1).ToList();
            }
            return View(viewModel);
        }
    }
}
```
That all works. But what I want to do is this ...
```
services.AddEntityFramework()
    .AddSqlServer()
    .AddDbContext<DbDbContext>(options => options.UseSqlServer(@"...my_conn_string..."));
```
... so that I can move the connection string to `Startup.cs` and get it out of `OnConfiguring`.

I tried using ...
```
public IActionResult Index(DbDbContext db) {
    var viewModel = new DbViewModel();
    viewModel.Tests = db.Tests.Where(p => p.id > 0).OrderBy(q => q.field1).ToList();
    return View(viewModel);
}
```
... which resulted in `MissingMethodException: Cannot create an abstract class`, so that's clearly not what you meant when you said to use DI instead of the `new` keyword.

Also, it would great if you could explain ...
> Besides, I am not sure what you are trying to achieve, but it is generally not a great pattern to have the entity types depend on the context.

Pretend like you're talk'in to someone educated in the Mississippi public school system ... In fact, don't pretend.

**Comment by GuardRex** [comment]
@divega Nevermind ... I got it. I see what you mean. I just needed to handle the database context DI the same way that I was handling my configuration DI. It makes sense to me now and my code is working.

**Comment by divega** [comment]
Glad to hear it is working for you. Just for completeness, here are all the basic patterns from the top of my mind that you can get a DbContext with the right services injected:

``` C#

public class MyController
{
  private readonly IServiceProvider _serviceProvider;
  private readonly MyDbContext _context1;
  
  // Constructor injection
  MyController(MyDbContext context, IServiceProvider serviceProvider)
  {
    _context1 = context;    
    _serviceProvider = serviceProvider;
      ...
  }
  // MVC6 property activation
  [Activate]
  public MyDbContext Context2 { get; set; }

  public void SomeMethod()
  {
    // passing service provider on constructor
    var context3 = new MyDbContext(_serviceProvider);
    ...
   // using DbContextActivator
    var context4 = DbContexctActivator.CreateInstance<MyDbContext>(_serviceProvider);
    ...
  } 

}

**Comment by GuardRex** [comment]
@divega That's helpful (as my slow brain is finally getting the DI pattern). Yes, just in case anyone finds this, for completeness. My update was truly simple (sorry about the goofy naming of my context).
```C#
namespace MyApp{
    public class DbController : Controller {

        private readonly IConfiguration _config;
        private readonly DbDbContext _db;

        public DbController(IConfiguration config, DbDbContext db) {
            _config = config;
            _db = db;
        }

        [HttpGet]
        [Route("/db")]
        public IActionResult Index() {
            var viewModel = new DbViewModel();
            viewModel.Tests = _db.Tests.Where(p => p.id > 0).OrderBy(q => q.field1).ToList();
            return View(viewModel);
        }
    }
}
```

You said in #2191:
> Besides, I am not sure what you are trying to achieve, but it is generally not a great pattern to have the entity types depend on the context.

Does my pattern fall into the that's-not-a-good-idea pattern? What I was trying to achieve was getting the config out of my DbContext class. Specifically, I want to get the connection string out of the context class `OnConfiguring` and getting it set up the `AddDbContext` in Startup.cs, because I have some connection string selection logic in Startup.cs. That's where I preferred to handle my `SqlServerDbContextOptionsBuilder`. Am I being bad?

**Comment by divega** [comment]
> Does my pattern fall into the that's-not-a-good-idea pattern?

From the perspective of EF usage what you had in the most recent snippets seems fine to me.

> I want to get the connection string out of the context class OnConfiguring and getting it set up the AddDbContext in Startup.cs, because I have some connection string selection logic in Startup.cs.

The code below takes care of setting up DI sot that the context will receive the connection string filled out from configuration when it is instantiated: 

``` C#
services.AddEntityFramework()
    .AddSqlServer()
    .AddDbContext<DbDbContext>(options => options.UseSqlServer(@"...my_conn_string..."));
``` 

So you shouldn't need to flow the full configuration into the context or use the 'OnConfiguring()' method if you have it a call to AddDbContext<TContext>() in 'ConfigureServices()' for your context type. 

You need to make sure that you instantiate the context using one of the patterns supported the DI system your application is using. 

E.g. the pattern that you showed in one of your snippets in which the DbContext is one of the constructor parameters for the controller should work with the basic built-in DI system. If on the other hand you want to have the controller injected as a parameter of the controller actions, I am not sure you will be able to make that work, especially because MVC will invoke those methods.

**Comment by divega** [comment]
Feel free to reopen if after using DI and the `AddDbContext<TContexT>()` as explained it still doesn't work for you. And please add a full repro.

**Comment by GuardRex** [comment]
It's all good. Your last snippet for the `AddDbContext` is what I ended up with and is working great. Thanks for your help.

**Comment by lovemory** [comment]
I want to try Constructor injection as divega said:

 // Constructor injection
  MyController(MyDbContext context, IServiceProvider serviceProvider)
  {
    _context1 = context;    
    _serviceProvider = serviceProvider;
      ...
  }

tthis is my code:
    public class ImageStoreController : Controller
    {
        private static bool _databaseChecked;


        //public MyDBContextcs context { get; set; }
        private readonly IServiceProvider _serviceProvider;
        private readonly MyDBContextcs _context1;

        // Constructor injection
        ImageStoreController(MyDBContextcs context, IServiceProvider serviceProvider)
        {
            _context1 = context;
            _serviceProvider = serviceProvider;
        }
.............................



InvalidOperationException: Unable to locate suitable constructor for type 'WebApplication3.Controllers.ImageStoreController'. Ensure the type is concrete and all parameters are accepted by a constructor.
