### ISSUE TITLE
Write a DiagnosticSuppressor for CS8618 for DbSet properties

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/efcore#21608]
See https://github.com/dotnet/roslyn/issues/45912

**Comment by Youssef1313** [comment]
If you wish, I may try to give a PR that implements it.

**Comment by roji** [comment]
Makes sense to me... We already have Microsoft.EntityFrameworkCore.Analyzers, this could go in there. Please feel free to submit a PR for this.

**Comment by davidroth** [comment]
IMO it would also make sense to document how simple expression bodied db-sets are an alternative way to define DbSet properties.

So instead of using mutable auto properties like this:

```csharp
public class NullableReferenceTypesContext : DbContext
{
    public DbSet<Customer> Customers { get; set; } = null!;
    public DbSet<Order> Orders { get; set; } = null!;
}
```

Using expression bodied get-only properties can be a more natural way to define them.

```csharp
public class NullableReferenceTypesContext : DbContext
{
    public DbSet<Customer> Customers => Set<Customer>();
    public DbSet<Order> Orders => Set<Order>();
}
```

Pros:
 - Immutable DBSet properties. It makes no sense to have mutable db-sets so why even declare them.
 - "Natural" fix for CS8618 because Set<>() has a none-nullable return value.
 - No property initialization cost because when constructing a new context EF does not have to initialize all set properties. (Although this is highly optimized anyway, so no real measurable benefit).

Note that I am not arguing against the suppressor. I am just wondering why the auto-properties "way" of defining DBSets, is still the default one? Probably just because of historical reasons? Thoughts @ajcvickers @roji

**Comment by roji** [comment]
Hmm, I think this might require a bit of change in EF Core, i.e. when the DbContext constructor is doing its thing. I suspect that will especially be necessary to support read-only properties here.

However, assuming the required changes aren't huge and it yields the same perf, I like it a lot - it definitely looks much better than the current guidance with null - and anything not requiring a suppressor is obviously better.

@ajcvickers thoughts?

**Comment by ajcvickers** [comment]
@roji What exactly is the question? Is the suggestion to change the guidance for if you're using NRT, or to change what we reverse engineer when NRTs are being used? Or something else?

**Comment by roji** [comment]
Yeah - @davidroth's suggestion above is clean, resolves the NRT warning and even makes the DbSet properties read-only, which is a bit more correct. I've submitted https://github.com/dotnet/EntityFramework.Docs/pull/2520 to integrate this into our NRT guidance.

**Comment by Neme12** [comment]
@roji I still think the diagnostic suppressor would be a good addition because defining `DbSet` as auto-properties is still supported.

**Comment by roji** [comment]
As suggested, reopening to consider doing this so that the following doesn't generate an NRT warning:

```c#
public class SomeContextContext : DbContext
{
    public DbSet<Customer> Customers { get; set; }
}
```
