### ISSUE TITLE
No errors report when using readonly navigation properties in many-to-many relationship tables

### ISSUE THREAD

**Issue by pendenaor** [dotnet/efcore#22057]
This type of navigation properties
```cs
public ICollection<PostTag> PostTags => new List<PostTag>();
```
does not work. 
But efcore does not emit any errors or warning message.

### Steps to reproduce
see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1139

### Further technical details

EF Core version: 3.1.7
Database provider: Pomelo.EntityFrameworkCore.MySql 3.1.2
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.7.1

**Comment by ajcvickers** [comment]
@pendenaor EF Core supports read-only properties. However, defining a property like you do above results in very strange behavior, regardless of being used with EF or not. It says, every time I access this property, give me a new list. So the property will never actually store anything.

Instead, this is the normal way to define a read-only collection navigation:

```C#
public ICollection<PostTag> PostTags { get; } = new List<PostTag>();
```

This means initialize the property to a new list when the object containing the property is created, and then keep returning that list so that items can be added or removed.
