### ISSUE TITLE
How to participate in Logging as provider?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2205]
```
 internal static class RelationalLoggerExtensions
```
- do each provider roll their own, or can we take advantage of above?

**Comment by divega** [comment]
Our general approach to logging is a bit in flux at the moment. My recommendation would be to try to stay close to the patterns we use in our providers and file bugs on any code you find we could be doing a better job of sharing, but don't invest a lot of time up front on it since many of the details are very likely going to change before RTM.

**Comment by ErikEJ** [comment]
Thanks, Will leave a TODO for now
