### ISSUE TITLE
Beta5 2032: DbSet.Add, DbContext.Add & Entry.State=Added setting key value of entity

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#2210]
This is new behavior and I can't imagine it's intended. It did not work like this in Beta3. And in Beta4, the Add method started doing this but Entry.State=Added didn't.

When you call any of these methods on a new object (who's key property is an integer), the Id is gettinig populated.

I tried this with InMemory and SQLServer providers.

Simple as can be:

My class:

```
 public class LambsonType
  {
    public int Id { get; set; }
    public string Description { get; set; }
  }
```

My context: (note that you can't pass in dboptions with preset provider so I have a workaround)

```
 public class LambsonContext : DbContext
  {
    bool _isInMemory = false;
    public DbSet<LambsonType> Lambsies { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
      if (_isInMemory)
        optionsBuilder.UseInMemoryStore();
      else
        optionsBuilder.UseSqlServer
          ("Server = (localdb)\\mssqllocaldb; Database=EF7Bryce; Trusted_Connection=True; MultipleActiveResultSets = True;");
      base.OnConfiguring(optionsBuilder);

    }
    public LambsonContext(bool isInMemory) : base() {
      _isInMemory = isInMemory;
    }
  }
```

A set of tests. The first three use the inmemory provider and are just adding the new object to the context. The second three use SqlServer provider and just add (no saving).

WIth the inmemory, if you run them all together, the Id gets changed to 1, 2 and 3 in each subsequent test.

With Sqlserver it's wierd because if I run the three tests, I first got 1, 11 and 21. ran them again and got 31, 41 and 51.

With these getting applied you will have a conflict if there are already objects being tracked by teh context with those key values ...this happened to me which is how I backed up to this problem.

hope it's useful.

Also there is another problem I noticed re using DbContextOptionsBuilder. DbContext still takes DbContextOptions as an overload. I will look for a related issue and add if necesary then come back here and add a pointer.

```
  [TestMethod]
    public void InMemoryAddNewEntityViaDbSetAddMethod() {
      var lamb = new LambsonType { Description = "a type" };
      var lambidbeforeadd = lamb.Id;
     // Console.WriteLine("before adding to context, new lamb ID is {0}", lamb.ID);
      using (var ctx = new LambsonContext(true)) {
        ctx.Lambsies.Add(lamb);
        Assert.AreEqual(lambidbeforeadd,lamb.Id);
         Console.WriteLine("InMemory: After DbSet.Add, new lamb ID is {0}", lamb.Id);
      }

    }
    [TestMethod]
    public void InMemoryAddNewEntityViaDbContextAddMethod() {
      var lamb = new LambsonType { Description = "a type" };
      var lambidbeforeadd = lamb.Id;
      // Console.WriteLine("before adding to context, new lamb ID is {0}", lamb.ID);
      using (var ctx = new LambsonContext(true)) {
        ctx.Add(lamb);
        Assert.AreEqual(lambidbeforeadd, lamb.Id);
        Console.WriteLine("InMemory: After DbContext.Add, new lamb ID is {0}", lamb.Id);
      }

    }
    [TestMethod]
    public void InMemoryAddNewEntityViaEntryState() {
      var lamb = new LambsonType { Description = "a type" };
      var lambidbeforeadd = lamb.Id;
       using (var ctx = new LambsonContext(true)) {
        ctx.Entry(lamb).State = Microsoft.Data.Entity.EntityState.Added;
        Assert.AreEqual(lambidbeforeadd, lamb.Id);
        Console.WriteLine("InMemory: After DbContext.Entry.State, new lamb ID is {0}", lamb.Id);

      }

    }

    [TestMethod]
    public void SqlServerAddNewEntityViaDbSetAddMethod() {
      var lamb = new LambsonType { Description = "a type" };
      var lambidbeforeadd = lamb.Id;
      using (var ctx = new LambsonContext(false)) {
        ctx.Database.EnsureCreated();
        ctx.Lambsies.Add(lamb);
        Assert.AreEqual(lambidbeforeadd, lamb.Id);
        Console.WriteLine("SqlServer: After DbSet.Add, new lamb ID is {0}", lamb.Id);

      }

    }
    [TestMethod]
    public void SqlServerAddNewEntityViaDbContextAddMethod() {
      var lamb = new LambsonType { Description = "a type" };
      var lambidbeforeadd = lamb.Id;
      using (var ctx = new LambsonContext(false)) {
        ctx.Database.EnsureCreated();

        ctx.Add(lamb);
        Assert.AreEqual(lambidbeforeadd, lamb.Id);
        Console.WriteLine("SqlServer: After DbContext.Add, new lamb ID is {0}", lamb.Id);
      }

    }
    [TestMethod]
    public void SqlServerAddNewEntityViaEntryState() {
      var lamb = new LambsonType { Description = "a type" };
      var lambidbeforeadd = lamb.Id;
      using (var ctx = new LambsonContext(false)) {
        ctx.Database.EnsureCreated();

        ctx.Entry(lamb).State = EntityState.Added;
        Assert.AreEqual(lambidbeforeadd, lamb.Id);
        Console.WriteLine("SqlServer: After DbContext.Entry.State, new lamb ID is {0}", lamb.Id);
      }

    }
```

**Comment by julielerman** [comment]
cc @bricelam

**Comment by julielerman** [comment]
Here is the issue re DbContext overload for DbContextOptionsBuilder: https://github.com/aspnet/EntityFramework/issues/2211

**Comment by ajcvickers** [comment]
@julielerman EF7 doesn't have the old "temporary key objects" that were used in the old stack. Instead EF7 has value generators which generate values for keys as needed when new entities are added to the context. This means that when an entity is Added the values of its key properties are checked. If  the values have been set, then these values are just used. If the values are null or the default value, then EF generates a value.

How the value is generated depends on the store being used. It may be the actual final key value, or it may be a temporary value that which will be updated when the entity is saved. Prior to Beta 4, SQL Server used temporary values for integers, which were then updated on SaveChanges using the value from an Identity column. In Beta 4, the SQL Server provider now gets the real key value from a database Sequence object immediately when Add is called. This means that you no longer have temporary keys that can change when the entity is saved. (Note that it uses a pool of blocks obtained from the database to avoid round-tripping on every Add call. This is one reason you don't just see 1, 2, 3, 4, etc.)

There are advantages and disadvantages to this use of Sequences, and we may end up changing back to using temporary values and Identity columns again. If you want to switch back now you can do so with `modelBuilder.ForSqlServer().UseIdentity;`. Regardless, EF7 will continue to generate key values for new entities on Add--this has been baked in from the beginning and is very unlikely to change.

Note that you should not get key conflicts using these patterns when doing anything normal. Obviously, if you delete and recreate or otherwise manipulate the Sequence object, then you might, or if you sometimes set key values explicitly while letting other keys be generated. But for normal code you should never get conflicts.

**Comment by julielerman** [comment]
oh my...so many things I didn't realize. I was performing a test. which I had built with beta 3. With beta4, it went awry. 

Here is the actual test (actually a method in a console app)

in ctor, I set up a few new objects:
   static Samurai Samurai_KK = new Samurai { Name = "Kikuchiyo" };
    static Samurai Samurai_KS = new Samurai { Name = "Kambei Shimada" };
    static Samurai Samurai_GK = new Samurai { Name = "Gorōbei Katayama" };

In the method I added those and saved them to the database. (no problem)
Then I retreivedthem into a new context. edited one. Deleted one. and ...here was the problem, added another new one. When I used the Add method, I got the error "can't track this because there's already an entity being tracked with the same key". When I changed it to Entry.State, it worked. (this was with beta4). Maybe I'll do *this* one with beta5 to see if it works out, but the fact that it was using a sequence value for the id that already existed in the tracked entities seems really like trouble ...though I couldnt imagine this leaking through your tests so figured I'm soing soemting wrong. I don't have time to test right now (have to get on the road for a 6 hour drive) so could you tell me a few things....
1) are you saying that if I call add (etc), a RT is made to the database? (say no say no say no)
2) do you think the conflict happened in the below code because I deleted something before I added? 
3) will this work better if I use it in beta5?

I have to figure out what "normal code" is becuse I'm really worried about having to wade through "watch out for this this and that when you use EF". I'm sorry I missed this in all the time you have been working on EF7. It's really hard to keep up with (or remembering) the details even reading meeting notes etc. And with beta3, nothing out of the norm happened with this code so it didn't catch my attention.

So here's the code that triggered this:

I was using sqlserver provider here.

 private static void Batch_CUD() {

      Console.WriteLine("If you want to see the effect of this method, switch the context builder options to the UseSqlServer code and also start your db profiler. Press any key to continue...");

      using (var context = new SamuraiContext(true)) {
        context.Samurais.AddRange(Samurai_KK, Samurai_KS, Samurai_GK);
        context.SaveChanges();
      }

      using (var context = new SamuraiContext(true)) {
        var samurais = context.Samurais.ToList();
        samurais[0].Name += "The Glorious";
        var ks = samurais.FirstOrDefault(n => n.Name.Contains("Shimada"));
        ks.Quotes.Add(
            new Quote
            {
              Text =
                        @"This is the nature of war. By protecting others,
                          you save yourself. If you only think of yourself, 
                          you’ll only destroy yourself."
            });
        context.Remove(samurais.Where(n => n.Name.Contains("Gor")).FirstOrDefault());
        var newSamurai = new Samurai { Name = "Julizuro" };
        context.Entry(newSamurai).State=EntityState.Added;
        context.SaveChanges();

     }
      Console.WriteLine("Check profiler to see the batched up SQL sent to db.");

    }

**Comment by julielerman** [comment]
p.s. thanks for the quick and detailed reply above :)

**Comment by ajcvickers** [comment]
@julielerman I don't see anything immediately and obviously wrong with the test code--can you post your model so that I can try to repro the issue.

To answer your questions:

1. It may result in a database round trip if a new block of values from the database sequence is needed. This is a trade off for having stable keys. You will always be able to use temporary values instead and have them updated on SaveChanges, which was what happened on the old stack. We will likely make this the default again for RTM for a number of reasons (e.g. Azure support and key space aesthetics), although the database round trip isn't one of those reasons.

2. I don't know why the conflict happened--I will try to reproduce if you send me your model. F.Y.I. there should not have been any difference between calling Add and changing the state to Added.

3. Everything works better in the current bits. :-)

In EF7 you should have less to watch out for than in the old stack. However, there are lots of places where if you have an expectation of what will happen based on the old stack then things might be different on the new stack. Think of it as a different framework rather than a new version of an existing framework. When using EF7 your knowledge of the intricacies of the old stack may not help much. We tend to get used to the way the old stack works and think of it as the "right way" when really it was only that way because it was implemented that way in v1 and was too hard to change--temporary key objects in the old stack is one example of that.

**Comment by julielerman** [comment]
Thank you so much Arthur.

I'm currently without WiFi but can upload my code later.

I really appreciate your perspective and explanation.
Julie

-----Original Message-----
