### ISSUE TITLE
wiki modification

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#2216]
I'd to this as a PR but I have to  go drive in the car for 6 hours. :)

 update https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext#config-inline-in-code-but-overridden-from-external-code to fix it so uses a ctor that takes builder and uses options property to pass into base ... ala

``` c#
   public BlogContext(DbContextOptionsBuilder optionsbuilder) : base(optionsbuilder.Options) { }
```

**Comment by rowanmiller** [comment]
Hey Julie, we don't go back and keep our design documents updated (that would be one huge job between design meetings notes, design docs, etc.).

Once we get closer to RTM we will produce proper docs outside of design documentation. We do keep the walkthrus on this wiki up to date since they are the only real getting started docs we have at the moment.
