### ISSUE TITLE
SQL Count results with IIncludableQueryable

### ISSUE THREAD

**Issue by Lazyhms** [dotnet/efcore#22459]
I have a question. Why does Include not generate join statistical queries when I use count()?

### Steps to reproduce

I have a query like this with IQueryable:
var result = context.User.Include(s => s.Role).Count();

The actual generated sql:
select count(*) 
from user as t

Hope to generate sql:
selcet count(*) 
from user  as t 
inner join role as t0 on t.roleId=t0.Id

### Further technical details
EF Core version: 3.1.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1.401
Operating system: Windows 10 version 2004
IDE: Visual Studio 2019 16.7.3

**Comment by smitpatel** [comment]
Since number of users in the database should be the same with or without including Roles.

**Comment by HUMAOSHUAI** [comment]
> Since number of users in the database should be the same with or without including Roles.

I am not using FK. If I want to query the number of valid users, it will not be correct.
For example, if I delete role A, the user of role A will be invalid.
At this time I want to use pagination query, it will not be correct.
because
**var total = context.User.Include(s => s.Role).Count()**
There is no join table query Role, but
**var page=context.User.Include(s => s.Role).Skip(1).Take(10).ToList()**
Do a join table query Role

**Comment by smitpatel** [comment]
> I am not using FK. If I want to query the number of valid users, it will not be correct.

Can you elaborate what is valid users? The number of users in the "Users" table should remain same regardless of there is associated role or not. If something is invalid user then it should not be in "Users" table.
