### ISSUE TITLE
Remove(entity) vs State=EntityState.Deleted behavior

### ISSUE THREAD

**Issue by jmzagorski** [dotnet/efcore#22465]
Below you will find my entity & event setup. I have one entity that can generate many events to an event table. A user will save an entity and that entity plus an event will get saved to the database at the same time. However, downstream events can run a compensating command that will delete the entity and event from that database. My "revert" logic disconnects all existing entities and reattaches the entity and event by using 

```C#
Entry(entity).State = EntityState.Deleted;
Entry(event).State = EntityState.Deleted;
```

However, when the event is attached in the deleted state i receive the exception: "Database operation expected to affect 1 row(s) but actually affected 0 row(s)" because cascade deletes are setup in migrations and sql server has a foreign key that deletes the event. However, if I use 

```C#
Remove(entity);
Remove(event); // not needed, but my revert logic goes over every prior saved entity, so this does happen
```

everything works fine. **Is this the expected behavior?** I read over the comments for the `Remove` method and the `State` setter, but could not find why EF was expecting to delete rows setting the `State` vs not expecting to delete rows with `Remove`

### Steps to reproduce
1. Configure the entity & event relationship (see below)
2. Add them to the database
3. SaveChanges
4. Disconnect them
5. Revert SaveChanges, by setting the state to deleted and SaveChanges again
6. Should get the exception

``` C#
    public class EventDescriptor
    {
        public int Id { get; private set; }
        public Entity Entity { get; private set; }
    }

    public class Entity
    {
        public long Id { get; private set; }
   }

    public class EventDescriptionEntityConfiguration :  IEntityTypeConfiguration<EventDescriptor>
    {
        public void Configure(EntityTypeBuilder<EventDescriptor> builder)
        {
            builder.ToTable("Events", "evt");

            builder.Property<long>("EntityId");

            builder.HasOne(e => e.Entity)
                .WithMany()
                .HasForeignKey("EntityId")
                .IsRequired();
        }
  }

    public class EntityEntityConfiguration :  IEntityTypeConfiguration<Entity>
    {
        public void Configure(EntityTypeBuilder<Entity> builder)
        {
            builder.ToTable("Entity", "dbo");
        }
  }
```

### Further technical details

EF Core version: 3.1.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .net core 3.1.302
Operating system: Windows 10
IDE: Visual Studio 2019 16.6

**Comment by jmzagorski** [comment]
Hit [ENTER] by mistake, please disregard until this is updated. Sorry!

**Comment by ajcvickers** [comment]
@jmzagorski When calling Remove on an un-tracked entity it is first tracked (as if Attach was called) and then marked as Deleted. When setting the state, it simply changes the state to Deleted. It's unusual to detach and entity and then set it to Deleted, and this can be especially problematic when the entity types are using shadow properties for the FK, since detaching the entity will result in the FK value being lost.

That being said, we may be able to do better here--we'll discuss.

@AndriySvyryd 

The difference in outcome is due to incorrect original value for the FK in the case that fails:

```
Entity {Id: 1} Deleted
  Id: 1 PK
EventDescriptor {Id: 1} Deleted
  Id: 1 PK
  EntityId: 1 FK Originally 0
  Entity: {Id: 1}
```
Because the original value here is zero, then it seems like the update pipeline doesn't order deletion of the dependent before deleting the principal, and hence there we get a constraint exception.

When it works the state manager is like this before SaveChanges:

```
Entity {Id: 1} Deleted
  Id: 1 PK
EventDescriptor {Id: 1} Deleted
  Id: 1 PK
  EntityId: 1 FK
  Entity: {Id: 1}
```

It may be that this is not fixable if the state manager has an incorrect original value, but I think it's worth discussing, as is whether or not this can be fixed in the state manager.

```C#
public class EventDescriptor
{
    public int Id { get; set; }
    public Entity Entity { get; set; }
}

public class Entity
{
    public long Id { get; set; }
}

public class EventDescriptionEntityConfiguration :  IEntityTypeConfiguration<EventDescriptor>
{
    public void Configure(EntityTypeBuilder<EventDescriptor> builder)
    {
        builder.ToTable("Events", "evt");

        builder.Property<long>("EntityId");

        builder.HasOne(e => e.Entity).WithMany().HasForeignKey("EntityId").IsRequired();
    }
}

public class EntityEntityConfiguration :  IEntityTypeConfiguration<Entity>
{
    public void Configure(EntityTypeBuilder<Entity> builder)
    {
        builder.ToTable("Entity", "dbo");
    }
}

public static class Program
{
    public static void Main()
    {
        using (var context = new SomeDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var entity = new Entity();
            var @event = new EventDescriptor {Entity = entity};
            context.Add(entity);
            context.Add(@event);
            context.SaveChanges();

            context.Entry(entity).State = EntityState.Detached;
            context.Entry(@event).State = EntityState.Detached;
            
            //context.Remove(entity);
            //context.Remove(@event);
            context.Entry(entity).State = EntityState.Deleted;
            context.Entry(@event).State = EntityState.Deleted;

            context.SaveChanges();
        }
    }
}

public class SomeDbContext : DbContext
{
    private static readonly ILoggerFactory
        Logger = LoggerFactory.Create(x => x.AddConsole().SetMinimumLevel(LogLevel.Debug));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new EntityEntityConfiguration());
        modelBuilder.ApplyConfiguration(new EventDescriptionEntityConfiguration());
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .EnableSensitiveDataLogging()
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TestX;ConnectRetryCount=0");
}
```

**Comment by jmzagorski** [comment]
Thank you for extending my example for others and providing great feedback.

> It's unusual to detach and entity and then set it to Deleted

The reason for detaching is just a sanity check in my code to make sure I do not attach an Entity that is already tracked. I save snapshots of the entities and the EntityState before changes are applied and that is how I can revert "modified" data. I could probably search the change tracker and change the state to deleted, but since I am iterating over my snapshots it was easier to detach all existing and then reattach the snapshots. Not sure if that makes sense. Just thought I'd give a little more background.

**Comment by ajcvickers** [comment]
@jmzagorski I think if you are going to detach and re-attach, then it would be advisable not to use shadow FK properties so that you preserve FK values on the detached entity.

Notes from triage:
* This is by-design in the update pipeline; if the original value is set then it must be used for ordering
* However, it's possible that we could avoid setting the original value when re-attaching an FK with an unknown shadow value.
* Another idea is to see if the entity entry can live long enough to be re-used when re-attached.

Putting this in the backlog to see if these things can be done.

**Comment by jmzagorski** [comment]
Thanks, that is what i did when i created another event-entity relationship.
