### ISSUE TITLE
Add ability to skip the top level model snapshot

### ISSUE THREAD

**Issue by pawelpabich** [dotnet/efcore#2268]
First of all great job with EF7. Now it can be used in team environment :).

If I understand correctly the top lelve CONTEXTNAMEModelSnapshot is not used by EF. Could you add an option to disable its generation? I'm happy for it to be disabled out of the box. I know why it is there but I would like to have fewer than more merge conflicts :).

**Comment by rowanmiller** [comment]
Hey,

We actually always use the snapshot, that is how we detect what changed since the last migration. Merging the file is actually the whole point of having it there. In situations where you get a merge conflict is where you would have got incorrect behavior out of migrations in the past. Now you merge the conflicting changes to the model and migrations will work correctly.

~Rowan

**Comment by bricelam** [comment]
See also the Model Snapshots section of [EF7 Migrations: Design-time](http://www.bricelam.net/2014/12/16/ef7-migrations-designtime.html)

**Comment by pawelpabich** [comment]
@rowanmiller ok so my understanding was not correct. thanks for clarifying. 

If you build a piece of infrastructure that makes conflicts more likely to happen than not then you are not following the "pit of success" mantra. 

DbUp simplicity + automated migration generation is where EF could shine. Why can't this be done? If you optimize your process for devs who have no CI and tests then you are going to exclude quite a few people. I will repeat, I'm happy with your default safety nets, just let me get rid of them if I don't need them. Otherwise they simply slow me down.

**Comment by bricelam** [comment]
If we implemented #1298, you could just add the file to your scm's ignore list.

**Comment by rowanmiller** [comment]
Just to be clear though... any time you need to merge this file because another developer changed it is a scenario where migrations will not work correctly if we didn't have a central model snapshot. If developers make unrelated changes in the model then they should auto-merge just fine. This means scenarios were migrations would have behaved incorrectly on EF6 (because we used the snapshot from the last migration) now work correctly. However if there is a real merge conflict in the file that requires manual merging then you can merge it and migrations will continue to work.

Implementing #1298 and ignoring the snapshot from SCM would basically give you the same behavior as EF6... which would work fine for a single developer but would have all the same issues as EF6 for teams.

**Comment by pawelpabich** [comment]
@rowanmiller I did a quick test with 2 branches. One added Property1 and the other one added Property2 and I ended up with a merge conflict in that file. Shared state has a tendency to cause problems like that. 

DbUp(and most of other platforms) works just by relying on the order of migrations. Scary :)? In theory yes, but I've never seen this being a problem for a team that has half decent CI and tests. 

The article, that @bricelam linked to, mentions that you embed a snapshot of the model in every migration. Could build the global snapshot of the model from them and store it a temp file so it doesn't clutter the source code? Migrations are immutable so having snapshot there does not cause any trouble.

**Comment by rowanmiller** [comment]
@pawelpabich deriving the model based on the latest migration(s) suffers a lot of problems (only in team environments). This article goes over the technical details of that https://msdn.microsoft.com/en-us/data/dn481501.

**Comment by pawelpabich** [comment]
@rowanmiller if we can not use snapshots then can we simply have a mode where we rely on the order of migrations and their content?  

In short, what stops us from having DbUp like experience with Entity Framework ?

**Comment by popcatalin81** [comment]
Have you considered dropping snapshots altogether? 

Instead of using snapshot maybe rebuild the model in memory from all the migrations found and then generate the new migration.

This would be the most friendly method for distributed teams and branch per feature flows.

**Comment by rowanmiller** [comment]
We use snapshots because we do a diff based on the EF model, not just the shape of the schema. The simplest example of this is if you change the column that a property maps to. If you just do a schema diff then all you see if a add/remove but if you diff at the model layer then you can see it's just a renamed property.

Running the up method of migrations would likely introduce performance issues, it also prevents the scenario where you modify the migration after it is generated (add a column that is transparent to EF, change a data type, etc.). Since we would be effectively diffing the current db schema migrations would always try and change back anything you modified. With the snapshot you just get what has changed since the last migration was generated.

Running up methods also begins to suffer the same issue with conflicts. If you Developer 1 deletes a property and Developer 2 modifies it, then this isn't immediately obvious when you merge and the behavior you get happens to depend on the order things are run.

@pawelpabich your scenario of adding two new properties to the same class is one of the few examples where you will get a merge conflict when there isn't really a conflict... but I'm assuming you also got a merge conflict on the entity class that you added the properties too. So it should be pretty obvious that you merge the snapshot in the same way you merge the entity class.

For non-team scenarios the snapshot should be completely transparent and you can just consider it an implementation detail. In team environments, for the most part you will only get a conflict if you get a conflict in your actual entity classes (or the DbContext code). And that will often be a legitimate issue that needs to be merged.

**Comment by pawelpabich** [comment]
@rowanmiller I think I'm lost here a bit. Correct me if I'm wrong. From what you are saying it looks like the snapshots that are embedded in each migration can *not* be used to generate the global snapshot? If that's not true and the only concern is perf then can you generate it only when it does not exist? In this way only people that want this feature will pay the additional tax.

**Comment by pawelpabich** [comment]
@rowanmiller regarding the merge conflict. You are 100% right. But what I've been trying to communicate here is that it adds friction. Every dev process has some level of friction and I would like to see it decrease not increase. And I really hope you don't optimize for non-team scenario. How many 1 person teams do you have at Microsoft :) ?

I did the experiment again and I ended up with 2 conflicts. One in the entity and one in the model snapshot. Have a look at the one in the entity. All I had to is to click right and left which means include changes from both and I was done. Now have a look at the merge conflict in the snapshot file. It's scary, isn't it?. And what is more when I simply clicked left and right I ended up with a file that does not compile. This is unnecessary friction in its purest form.

What would be your response If every time you wanted a cup of tea someone asked you to do 5 pushups. Would you just do them or maybe you would ask why? What value does it bring? This is how I feel about this forced safety net.

Entity:
![image](https://cloud.githubusercontent.com/assets/347637/8096958/30b50c10-1020-11e5-830f-6854fd30861f.png)

Snaphost:
![image](https://cloud.githubusercontent.com/assets/347637/8096965/3e3358f6-1020-11e5-8024-c24efe9b7dca.png)

**Comment by rowanmiller** [comment]
> From what you are saying it looks like the snapshots that are embedded in each migration can not be used to generate the global snapshot? If that's not true and the only concern is perf then can you generate it only when it does not exist? In this way only people that want this feature will pay the additional tax.

The snapshots in the migration can not be used for the reasons covered in the article I linked to. They work fine for single developer scenarios but do not work in teams. 

> And I really hope you don't optimize for non-team scenario. How many 1 person teams do you have at Microsoft :) ?

The global model snapshot is only being introduced because of teams. In a single developer scenario it would be fine to remove it and rely on the snapshot from the last migration.

> I did the experiment again and I ended up with 2 conflicts. One in the entity and one in the model snapshot. Have a look at the one in the entity. All I had to is to click right and left which means include changes from both and I was done. Now have a look at the merge conflict in the snapshot file. It's scary, isn't it?. And what is more when I simply clicked left and right I ended up with a file that does not compile. This is unnecessary friction in its purest form.

This is really good feedback and just means there is an issue with the layout we are using in the snapshot as it needs to be tweaked to work better with merging. We need to use something that yields a change/merge that is more consistent wit the corresponding change in the entity class. I've opened https://github.com/aspnet/EntityFramework/issues/2377 to address this.

**Comment by pawelpabich** [comment]
It's a pity that this can't be fixed but it is what it is. 

Thanks
