### ISSUE TITLE
Add a dry-run option for `migrations add` 

### ISSUE THREAD

**Issue by zcarson** [dotnet/efcore#22761]
When making changes to entities in the code base, sometimes its hard to tell if anything has changed that would require a new migration to be created. Especially when working in a new area, we create the entities, create a migration, then develop features. Occasionally we'll make changes to the entities due to features. When it comes time to check everything in, its hard to remember if all changes have been wrapped into migrations

Within the cli, a new flag similar to `dotnet ef migrations add --dry-run` which would output what changes would be made in a new migration

**Comment by ajcvickers** [comment]
@zcarson The typical flow for this is to run `dotnet ef migrations add` and if you don't want to keep the migration for any reason, then run `dotnet ef migrations remove`. This is typically more useful than a "dry-run" because it places the generated migrations into the project where they can be compiled and examined in the context of the rest of the code. `dotnet ef migrations remove` is then intended to be a quick, easy way to go back to where you were before.

**Comment by bricelam** [comment]
I think you're looking for #22105
