### ISSUE TITLE
i have some problem in use efcore in wpf

### ISSUE THREAD

**Issue by pengqi1991** [dotnet/efcore#22794]
## I have a question use efcore in wpf.

Scene

* sql: sqlserver
i have two page in my wpf application.
page1: it work for tte face of a contrast,if acquaintance degree reaches 80,i will use efcore change the status property form 1 to 2 in one computer.
page2:another computer connection to the page1 computer use same database.i find then status but the status still is 1.
this  often can appear in  page 1 change something but page 2 is not changed.
How to solve it?

### page 1

```C#
Inscription.QueueStatusId = 2;
 ctx.Entry<Inscription>(Inscription).Property("QueueStatusId").IsModified = true;
 ctx.SaveChanges();
```
### page 2
```C#
var Inscription = ctx.Inscriptions
                 .Include(r => r.SecondWeightStatus)
                .Include(r => r.FirstWeightStatus)
                 .Include(r => r.Event)
                  .ThenInclude(r => r.WeightLevel)
                .Where(r => r.IDNumber == IDNumber)
                .FirstOrDefault();
```
because of page 2 i want to change the Inscription's anthor property,
i dont want to use ctx.Inscriptions.AsNotracking()

 ### Include provider and version information

EF Core version:
Database provider: ( Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (.NET core 3.1 )
Operating system: win 10
IDE: (Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
