### ISSUE TITLE
Documentation: Comprehensive list of methods that take SQL

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#22815]
Moved from discussion #22053.

### Question

From @zspitz

As the author of the [Entity Framework](https://bobby-tables.com/adodotnet_ef) page at [bobby-tables.com](https://bobby-tables.com/), I want to update it for EF Core 3.1. To do that, I need a list of the EF Core methods that can accept SQL (raw or interpolated). Currently, I have the following:

* FromSql (deprecated)
* ExecuteSqlCommand (deprecated)
* ExecuteSqlCommandAsync (deprecated)
* FromSqlRaw
* FromSqlInterpolated
* ExecuteSqlRaw
* ExecuteSqlRawAsync
* ExecuteSqlInterpolated
* ExecuteSqlInterpolatedAsync

Am I missing anything?

In addition, I understand the non-`*Interpolated` methods can take simple strings that use named parameter placeholders and `DbParameter`-derived instances:
```
// https://docs.microsoft.com/en-us/ef/core/querying/raw-sql/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlcommand
var user = new SqlParameter("user", "johndoe");
var blogs = context.Blogs
    .FromSqlRaw("EXECUTE dbo.GetMostPopularBlogsForUser @user", user)
    .ToList();
```
Can the `*Interpolated` methods do this as well?
```
var user = new SqlParameter("user", "johndoe");
var blogs = context.Blogs
    .FromSqlInterpolated("EXECUTE dbo.GetMostPopularBlogsForUser @user", user)
    .ToList();
```

---

### Replies

From @ajcvickers 

@zspitz Are you suggesting that this should be in the docs?

---

From @zspitz

I think it's a valid idea. It provides real value to developers to have a checklist of methods, and be able to say, "I'm using this method somewhere, let me make sure I'm using it properly."

However, my immediate need is because I want to revamp the aforementioned page, which only covers until EF 2.1.

---

From @ajcvickers

We discussed again, but the general consensus on the team is that there is very little value in documenting this as a separate list.

**Comment by zspitz** [comment]
> there is very little value in documenting this as a separate list.

In other words, if I want to harden my application against SQL injection, I have no straightforward way of determining the methods where concatenated SQL might have been passed in. Is there no value in helping people prevent SQL injection?

Is there "very little value" in making it straightforward to avoid SQL injection with EF Core?

Is the argument that direct SQL shouldn't be used at all? These methods exist; they're not marked as deprecated.

**Comment by roji** [comment]
@zspitz methods which accept SQL strings and which could result in SQL injection attacks certainly aren't deprecated; they are sometimes necessary, e.g. in dynamic SQL scenarios where table/column names need to come from some external source. When using such methods, it's the developer's responsibility to make sure they're using properly sanitized values and preventing SQL injection attacks.

Any methods accepting FormattableString (e.g. FromSqlInteroplated or FromSql in EF Core 7.0) is also safe against SQL injection, since any interpolation results in a DbParameter which is safe. This is why why recommend these methods as the default SQL query mechanism, unless the user specifically needs dynamic SQL generation where DbParameter can't work.

The documentation around all of this has been updated recently, check out the [SQL queries page](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries).
