### ISSUE TITLE
entry.OriginalValues.SetValues swallows error

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/efcore#22968]
`SetValues` has a signature of `Dictionary<string, object>`

its perfectly fine to send in `new Dictionary<string, TProperty>` but it will not update the original value correctly.  So no concurrency error will trigger when saving. Since compiler does not complain you should throw some kind of runtime here to save on debugging for developers. 

Thanks

**Comment by stevendarby** [comment]
Rather than throw, could the method signature be updated to take `IDictionary<string, T>` so it just works? I’m not sure there are likely to be many use cases where you want to pass in a string dictionary to the `SetValues(object)` overload. The workaround for the would be to cast it as an object. The current workaround for the opposite problem is having to recreate the dictionary casting each value as object.

Is this possibly a good first issue?

**Comment by ajcvickers** [comment]
@stevendarby After investigating this, I think you were right. Sorry for not getting back to you.
