### ISSUE TITLE
Loading large datasets with minimal internal array allocations (List<T> Capacity)

### ISSUE THREAD

**Issue by MartinJSoles** [dotnet/efcore#22997]
When retrieving datasets that are mostly read-only and possibly large number of entities, it would be nice to prevent the underlying framework from having to reallocate temporary arrays while fetching data from the backing store.

SQL Server has a way to return the number of records being fetched using windowing. The query sent to the database could include the COUNT(*) OVER () AS Extent_x phrase to give the context a hint of how large to set the initial capacity of the underlying storage object (array or List<T>) at instantiation. This should be an opt-in optimization and used by default. An attribute could be placed on the DbSet properties of the DbContext or done in the model builder.

Alternatively, provide a method for an application developer to provide a hint to EF for the default capacity to use when constructing its internal List object to hold results of a loading operation.

**Comment by MartinJSoles** [comment]
SQL Server does support getting the count of records at the same time as the results are streamed. For instance:

```
SELECT COUNT(*) OVER () CT, DgnID, DgnSort, DgnCode, DgnDescription
FROM dbo.DiagnosisCodes
```

You can have a blank window clause with the COUNT function.

**Comment by roji** [comment]
Check out the query plan for that query, compared to just a normal query - I highly suspect this will degrade performance in a very significant way... Or am I missing something?

**Comment by roji** [comment]
(in addition, this duplicates the count across all rows, adding potentially network traffic that's otherwise useless...)

**Comment by MartinJSoles** [comment]
You're worried about duplicates when the default behavior of EF when bringing back related records has a boatload of duplicated entities? Doesn't every parent entity get included in each returned row? That's a lot more network traffic than a single integer per row. :)

Yes, performance is degraded. The windowed field does double the cost when looking at the execution plan. This becomes something that the SQL engine can optimize for in the future.

An alternative that doesn't use windowing would be a query with a small group of statements while allowing for the possibility that the returned row count might not be accurate (the window functions make that guarantee at the statement level). If you want to really incur the wrath of the DBA, wrap these in a transaction and lock the whole table.

```
DECLARE @CT INT;

SET @CT = (SELECT COUNT(*) FROM dbo.DiagnosisCodes);

SELECT @CT CT, DgnID, DgnSort, DgnCode, DgnDescription
FROM dbo.DiagnosisCodes;
```

If we're really worried about query performance, the row count of a table is stored as metadata, [see link](https://blog.sqlauthority.com/2020/08/07/fastest-way-to-retrieve-rowcount-for-a-table-sql-in-sixty-seconds-096/). If we can make sure that we are really trying to retrieve all rows, the linked method would be the most performant. It avoids an extra index (or table) scan. Again, we run the risk of returning a row count that is changed between statements.

I only do this once per application cold start since I'm only wanting to do this on static data. This penalty is paid once. When I hit an out of memory exception in my application because the internal List object grows capacity exponentially while streaming in rows. For an example dataset of 80k rows, the list will grow 16 times with the last one needing enough memory for 192k records (throwing away an array of 64k rows after copying to another of 128k). Even considering that the arrays only contain references to the actual entities, that's a lot of memory thrashing.

While a server-side application (I'm looking at you ASP.Net) usually has enough memory to handle this thrashing, a client-side app doesn't necessarily have enough room in the playground. I also don't want to keep calling back to the server and getting a screen's worth of codes for a data entry screen.

I understand that this would be bad behavior to use on every DbSet. That was why I was hoping to apply a hint via attribute or model builder. Unless there is an existing way to hook into the framework and take over the materializing of a DbSet itself. If I had a few extra weeks to dig into it, I might see how to surface this or extend the framework for myself.

**Comment by roji** [comment]
> You're worried about duplicates when the default behavior of EF when bringing back related records has a boatload of duplicated entities? Doesn't every parent entity get included in each returned row? That's a lot more network traffic than a single integer per row. :)

That's exactly why EF Core 5.0 has [split queries](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#split-queries-for-related-collections) - we do take data duplication pretty seriously :wink: 

> Yes, performance is degraded. The windowed field does double the cost when looking at the execution plan. This becomes something that the SQL engine can optimize for in the future.

Is there any reason to suppose this will (or even can) be optimized in the future? Once again, coming from PostgreSQL, the query engine really has no way of knowing - at the point when it starts to process the query - how many total rows will be returned. You're in effect asking the database server to perform the entire query - buffering all rows - before sending out the first one, which is very considerable in terms of perf/memory at the database.

> An alternative that doesn't use windowing would be a query with a small group of statements while allowing for the possibility that the returned row count might not be accurate (the window functions make that guarantee at the statement level). If you want to really incur the wrath of the DBA, wrap these in a transaction and lock the whole table.

In addition to the consistency issue (and the potentially very adverse effects of locking the whole table just for this), this performs two queries instead of just one. Batching the two would at least avoid the two roundtrips, but this is still not really acceptable as a general querying strategy.

> the row count of a table is stored as metadata

This is relevant only for the total table count. Anything relevant here would need to handle arbitrary queries (e.g. with WHERE clauses)...

I'll try to summarize... There are fundamental reasons why what you want can't be done in a safe, performant, systematic, and database-agnostic way. There may be some edge cases where that's possible (e.g. for entire tables), but I don't see anything here that would fit in a general way in EF Core.

More importantly, there's nothing stopping you from doing all of the above. Instead of doing ToList on the query, you can preallocate your own List (with a given capacity), and stream the query results (via foreach), adding them to the List. This allows you to execute your own query to e.g. find out the table's row count, allocate the List accordingly and then populate it. You could easily wrap all this in an extension over IQueryable, e.g. a ToList which accepts the initial capacity.

**Comment by ajcvickers** [comment]
We discussed this in triage and agreed with @roji that this isn't a direction we plan to go.
