### ISSUE TITLE
Error: Cannot translate 'Contains'

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#23022]
## File a bug

I'm getting this type of error after upgrading from EF Core 3.1.8 to EF Core 5.0 RC2: EntityEqualityOnKeylessEntityNotSupported. Nothing changed in the code after upgrading.

I didn't find anything on the [What's New](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#rc1) or [Breaking Changes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes) pages.

Here is the error:

> "Cannot translate the 'Contains' on an expression of entity type 'MyType' because it is a keyless entity. Consider using entity properties instead."

Here is the code:

```c#
// myTypes is a List<MyType>
var ids = _engageContext.MyType.Where(a => myTypes.Contains(a)).Select(a => a.Id).ToList();
```

Here is what's in the Application Output:

> Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.Relational.dll

### Include provider and version information

EF Core version: 5.0.0-rc.2.20475.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: macOS 10.15.7
IDE: Visual Studio for Mac Preview 8.8 build 2811

**Comment by smitpatel** [comment]
cc: @roji

**Comment by roji** [comment]
Contains wasn't supported on keyless entities in 3.1 as far as I can tell (see code sample below). The reason is that when you use Contains over entity instances (as opposed to one of their properties, we translate this to compare their keys, which represent their identity (entity equality). However, keyless entities don't have keys, and so don't have an identity we can use.

You can still use Contains with specific properties (`.Where(b => blogNames.Contains(b.Name)`).

Here's the code sample, if I've misunderstood can you please correct the below to show your issue?

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var blogs = new List<Blog> { new Blog() };

_ = await ctx.Blogs
    .Where(b => blogs.Contains(b))
    .ToListAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(...)
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().HasNoKey();
    }
}

public class Blog
{
    public string Name { get; set; }
}
```

**Comment by mrlife** [comment]
@roji Thanks, the code sample looks like what I'm doing. In 3.1, I definitely was doing this without issue. Since it was not intended to be supported, I'll change it to compare with the table's primary key property instead of the whole entity. Thanks!

**Comment by roji** [comment]
>  I'll change it to compare with the table's primary key property instead of the whole entity.

There's some confusion here somewhere, because the error you've reported above reports that there is no primary key, because the entity is keyless (note the HasNoKey call in my code sample). If your entity isn't actually keyless, than that error shouldn't be appearing, and if it *is* keyless, then there is no primary key for you to run Contains over.

A runnable repro from you could help clarify what's going on.

**Comment by mrlife** [comment]
@roji Thanks for getting back to me. I'm unable to reproduce this and consider this an error on my part. I appreciate your time on this and all the efforts Microsoft makes with its developer customers to create a modern and open software development framework.
