### ISSUE TITLE
Drop foreign key based on column and table names

### ISSUE THREAD

**Issue by kanadaj** [dotnet/efcore#23106]
The `migrationBuilder.DropForeignKey` step assumes the foreign key is either directly named in the constraint or follows the naming convention; in some cases like when tables have been renamed this assumption may fail.

It would be good to have the option (or maybe even default to?) run a query to fetch the name of the foreign key based on the linked tables and columns and delete based on that.

**Comment by ajcvickers** [comment]
@kanadaj EF Core migrations should rename constraints when tables are renamed. So these should not get out of sync unless the table is being renamed outside of migrations. In that case, either the constraints should be updated at the same time, or constraint names should be added to the EF model.

If you're running into cases where migrations is renaming a table and not renaming constraints, or if you think there is some other issue, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
