### ISSUE TITLE
When lazy-loading fails the property flag in LazyLoader is still marked as loaded

### ISSUE THREAD

**Issue by Alksar** [dotnet/efcore#23165]
The question is at the junction of ef and Rider, but this is good place to start.

Rider debugger works with one thread, so when we try to evaluate any ef queries from debugger we get an timeout error. (`System.TimeoutException: Timeout during reading attempt`).

This happens automatically for variables with lazy loading if `property evaluations` enabled in debugger settings:
![image](https://user-images.githubusercontent.com/8016963/97807862-6454df80-1c74-11eb-979a-c51ae4974ef1.png)

LazyLoader sets the loaded mark before making a query: [here](https://github.com/dotnet/efcore/blob/319db8b25e72741540a3461b10431088bc064bfd/src/EFCore/Infrastructure/Internal/LazyLoader.cs#L142).
 
This way we get the situation when a lazy query failed, but the loaded mark had been setted, the navigation property is not actually loaded, but ef thinks it has been loaded. We have a dangerous inconsistency.

What are the workarounds?

**Comment by ajcvickers** [comment]
Note from triage: if lazy-loading fails, then the property should not end up marked as loaded; this seems like a bug.

With regard to debuggers and lazy-loading, I tend to see this as being one of the problems with using lazy-loading, and one of the reasons many people consider lazy-loading to be an anti-pattern. Usually, the problem manifests differently--i.e. that, something that would not be loaded during normal execution ends up loaded because the debugger caused it to load. Debugging the app then becomes very confusing. Either way, it illustrates the conceptual mismatch with the .NET concept of a property; having a property access do something complex and with blocking I/O goes against best practices.
