### ISSUE TITLE
EF Core 3.1.x and EF Core 5.0 in the same package, is this possible?

### ISSUE THREAD

**Issue by danielValdezR** [dotnet/efcore#23223]
Hi, 

I have a EF Core provider currenty with support for v3.1.x, so with EF Core 5.0 at the door, I would like to add the support for it in the same package but it doesn't seem to be working. The goal is that the end-user add the reference to my package and automatically download the correct version depending of what EF Core is using. Here's what I have in the main **.csproj:**

**Note:** _I've also made proper changes in the source code to handle the differences between both versions. Executed tests individually for each of them._

```
...
<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
....
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.9" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <Compile Remove="Framework/EFCore3.1/*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0-rc.2.20475.6" />
  </ItemGroup>
```

So the end-user coudl have something like:

```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.9" />
    <PackageReference Include="MyPackage" Version="X.X.X" />
  </ItemGroup>
```

And it could automatically pull the _dll_ built using **netstandard2.0** and **EFCore3.1.**

I'm receiving this error at build time:
```
Error NU1605 Detected package downgrade: Microsoft.EntityFrameworkCore from 5.0.0-rc.2.20475.6 to 3.1.9. Reference the package directly from the project to select a different version.
``` 

So is there something I could do at my side (EF Core provider) to handle this efficiently, or is it pretty much impossible to have the support for two EF Core versions in the same package/project?

Thanks,
Daniel

**Comment by roji** [comment]
If I understand the above correctly, you want to have a single provider package which automatically brings in EF Core 3.1 when netstandard2.0 is targeted, and EF Core 5.0 when netstandard2.1 is targeted.

Regardless of any msbuild/nuget issues around this, this is generally not a good idea - EF Core versions and .NET versions (or .NET Standard versions) aren't the same thing, and do not necessarily correspond. That is, it is completely reasonable for an application using netstandard2.1 to want to use EF Core 3.1, simply because they haven't yet ported and tested their application for EF Core 5.0. This is why it's important for the user to make an explicit choice of which EF Core version they want, and not to assume it automatically from the project TFM.

There also seems to be an expectation that the user's PackageReference for Microsoft.EntityFrameworkCore somehow influence what version of EF gets select inside MyPackage. The problem is that the same EF provider *assembly* cannot work with both EF 3.1 and 5.0, since there have been provider-facing API changes - you can't simply switch around versions of EF Core and expect the same provider DLL to work. And the DLL selected by nuget within your nuget package depends *only* on your project's TFM (netcoreapp3.1 above). So the above will not work.

The recommended way for this to work, is for the user to simply reference your provider, and for your provider to bring in Microsoft.EntityFrameworkCore via transitive dependency. Your provider should have the same version scheme as the EF Core it supports - MyPackage 3.1.x should work with Microsoft.EntityFrameworkCore 3.1.x, 5.0.x should work with 5.0.x (since again, there are incompatibilities between major versions). That means that a simple reference to MyPackage 3.1.x is all the user needs - no need for a separate Microsoft.EntityFrameworkCore reference.

One exception to the above is patch versions. Since patches never break backwards compatibility, it is indeed possible for MyPackage 3.1.7 to work with Microsoft.EntityFrameworkCore 3.1.3, for example. The user can explicitly specify that via a reference to Microsoft.EntityFrameworkCore in their csproj.

**Comment by danielValdezR** [comment]
I get it now. We were trying to handle it in one single package but it looks like it's not the right way to do it, actually that was my initial bet. Guess we have to restructure our project and make some decisions regarding this. 

Thank you so much for your clear and concrete answer, I really appreciate it and helps me alot.
