### ISSUE TITLE
Add model validation for nested dependents

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#23229]
If there are no non-PK required properties.

See `GraphUpdatesSqlServerTest.Owned.Required_one_to_one_are_cascade_deleted`

### Model:

`Root.RequiredSingle` is an optional dependent

1. Add `r.Navigation(e => e.Single).IsRequired();` to mark `Root.RequiredSingle.Single` as required

1. Remove `RequiredSingle1.Bool`

**Comment by AndriySvyryd** [comment]
Related: #21488

**Comment by smitpatel** [comment]
I updated model according to above. Test still fails in assert after loading required graph.

When we load root, root->RequiredSingle materializes always because there is no differentiating property. root->RequiredSingle->Single is not materialized because the values are null in the bool column inside RequiredSingle2 class. Test seems like making wrong assertion. @AndriySvyryd ?

**Comment by smitpatel** [comment]
Investigating more - The model falls into a kind of invalid model.
RequiredSingle is optional but nested Single is required.
Due to lack of properties in RequiredSingle it acts as required hence we materialize the instance but we cannot materialize Single since it was deleted along with RequiredSingle (due to it being required).

**Comment by ajcvickers** [comment]
Based on current design, we should add model validation to detect when there is an optional dependent that doesn't have any required properties that are not shared.

**Comment by smitpatel** [comment]
Design meeting N notes:
- We will add a `IModelFinalizingConvention` which would log and convert the dependent to required dependent so that metadata can be read that way at runtime.
- We will also remove the code from SQL which tries to add rows for nested dependents.

**Comment by smitpatel** [comment]
Design meeting N+ M notes:
- We will add validation in model.
- If optional dependent doesn't have a required identifying property,
  - If there are no nested dependents then warn
  - If there are nested dependents then throw.

**Comment by smitpatel** [comment]
Older snapshots which are already having this kind of faulty model would start throwing exception (tests are failing in source rn).

What direction are we taking on it? @dotnet/efteam

**Comment by AndriySvyryd** [comment]
We don't run model validation on snapshots

**Comment by smitpatel** [comment]
Looks like test in model snapshot processor is failing because the runtime model is faulty. I will debug more.
