### ISSUE TITLE
Change Tracker fails to recognize Added items

### ISSUE THREAD

**Issue by PatrikBak** [dotnet/efcore#23224]
Model:

```CSharp
public class Event
{
    public int EventId { get; set; }

    public int MatchId { get; set; }

    public Match Match { get; set; }

    public int? PlayerId { get; set; }

    public PlayerInMatch Player { get; set; }
}

public class PlayerInMatch
{
    public int PlayerId { get; set; }

    public Match Match { get; set; }

    public int MatchId { get; set; }

    public ICollection<Event> Events { get; } = new List<Event>();
}

public class Match
{
    public int MatchId { get; set; }

    public ICollection<Event> Events { get; } = new List<Event>();

    public ICollection<PlayerInMatch> Players { get; } = new List<PlayerInMatch>();
}
```

Configuration:

```CSharp
modelBuilder.Entity<PlayerInMatch>()
	.HasKey(e => new { e.MatchId, e.PlayerId });

modelBuilder.Entity<Event>()
    .HasOne(e => e.Match)
    .WithMany(e => e.Events)
    .IsRequired();

modelBuilder.Entity<Event>()
    .HasOne(e => e.Player)
    .WithMany(e => e.Events)
    .HasForeignKey(e => new { e.MatchId, e.PlayerId })
    .IsRequired(false)
    .OnDelete(DeleteBehavior.Cascade);

modelBuilder.Entity<PlayerInMatch>()
    .HasMany(e => e.Events)
    .WithOne(e => e.Player)
    .HasForeignKey(e => new { e.MatchId, e.PlayerId })
    .IsRequired(false)
    .OnDelete(DeleteBehavior.Cascade);
```

Code:

```CSharp
var context = new TestDbContext();

context.Database.EnsureDeleted();
context.Database.EnsureCreated();

context.Add(new Match
{
    MatchId = 42,
    Players =
    {
        new PlayerInMatch
        {
            PlayerId = 42
        }
    },
    Events =
    {
        new Event
        {
            PlayerId = 42
        }
    }
});

context.SaveChanges();

context = new TestDbContext();

context.Database.ExecuteSqlRaw("truncate \"Events\"");

var match = context.Matches.Include(e => e.Events).ThenInclude(e => e.Player)
    .Include(e => e.Players).ThenInclude(e => e.Events)
    .First();

match.Players.Clear();

match.Players.Add(new PlayerInMatch
{
    Match = match,
    PlayerId = 42
});

match.Events.Add(new Event
{
    Match = match,
    PlayerId = 42,
});

context.SaveChanges();
```

Table `Events` contains no entries, even if there should be one event.

**Database provider:** Npgsql.EntityFrameworkCore.PostgreSQL 3.1.4
**Target framework:** NET Core 3.1

**Comment by ajcvickers** [comment]
Note for triage: requires Npgsql to attempt the repro--the code uses concepts that don't work on SQL Server (delete cycles, explicitly inserting into Identity columns) and SQLite ("truncate").

/cc @roji

**Comment by PatrikBak** [comment]
@roji

The issue is there even for .NET 5.0 and Npgsql.EntityFrameworkCore.PostgreSQL 5.0.0

**Comment by roji** [comment]
Sorry for taking so long to answer this - the 5.0 release created a lot of work.

To understand what's going on in this kind of scenario, it's best to [turn on logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#filtering) for the `Microsoft.EntityFrameworkCore.ChangeTracking` category. Running your code shows the following messages (showing only the interesting ones):

> DetectChanges starting for 'TestDbContext'.
> 1 entities were added and 0 entities were removed from navigation 'Match.Events' on entity with key '{MatchId: 42}'.
> 1 entities were added and 1 entities were removed from navigation 'Match.Players' on entity with key '{MatchId: 42}'.
> The 'PlayerInMatch' entity with key '{MatchId: 42, PlayerId: 42}' tracked by 'TestDbContext' changed state from 'Unchanged' to 'Deleted'.

In other words, the problem is that you're trying to swap an existing tracked Player (with ID 42) with another instance, and the event is getting identified as belonging to the older instance - it's referencing the player by ID rather than by an instance reference.

To get around this, let the change tracker know that you're removing the old player instance early via e.g.:

```c#
context.PlayersInMatch.Remove(match.Players.Single());
```

Then, reference the new player instance from your event instead of using the foreign key:

```c#
match.Events.Add(new Event
{
    Match = match,
    Player = player // Notice reference to the new player, instead of a foreign key value
});
```

Hope that makes sense.

(@ajcvickers or any other team member, PostgreSQL TRUNCATE simply clears a table, same as `DELETE * FROM Events` on any other database).

**Comment by PatrikBak** [comment]
@roji 

Thanks, it does make sense. However, I still find it a bit sad. This occurred in a real scenario and it took me a few hours to track down the issue. And my production solution was to remove the problematic foreign key. The class that does these manipulations does not have access to the db context directly.

**Comment by roji** [comment]
Understood. FWIW I think it's generally safer to wire up relationships via instance references rather than with foreign keys, at least in cases where you're changing tracked CLR instances of the same thing. That last bit in itself - the swapping - can be somewhat tricky and requires special care.
