### ISSUE TITLE
Should CommentAttribute be in System.ComponentModel.DataAnnotations

### ISSUE THREAD

**Issue by Maple512** [dotnet/efcore#23247]
I found that CommentAttribute was added in Version 5.0, but things like TableAttribute, StringLengthAttribute, etc. will be in this System.ComponentModel.DataAnnotations, Do you consider centralizing them under the System.ComponentModel.DataAnnotations?

In fact, i don't refer to the EfCore package in the project where the Entity is located, so i can't use CommentAttribute, which is not recommented by the framework of 'abp'

thaks:)

**Comment by roji** [comment]
System.ComponentModel.DataAnnotations is part of the .NET base class library - that means that only attributes with a general function (beyond EF Core) logically belong there. It is also a relatively old namespace that isn't being evolved any more, and in order to add attributes in there we would have to convincingly show that there's actual, concrete use and utility outside the scope of EF Core.

Microsoft.EntityFrameworkCore.Abstractions, on the other hand, is part of EF Core and can be easily evolved according to the project needs.

**Comment by Maple512** [comment]
ok, thanks for reply

**Comment by ajcvickers** [comment]
@Maple512 In addition to what @roji said, I just wanted to mention that if you want a pure separation EF-specific code with no references to any other assemblies from your entity types, then the `modelBuilder` API in `OnModelCreating` is designed for this.

**Comment by Maple512** [comment]
@ajcvickers thanks you for your reply, i understand wath you mean, i think i will use Microsoft.EntityFrameworkCore.Abstractions as @roji said, thanks again, enjoy:)
