### ISSUE TITLE
Question: why `GetColumnName` extension method is obsolete

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/efcore#23301]
## Ask a question

In ef core 3.1, I use `propertyEntry.Metadata.GetColumnName` extension method to get the mapped column name,

while upgrade to ef core 5.0, I get a warning like `Use the overload that takes a StoreObjectIdentifier`.

I'd tried to add an extension method like follow:

``` csharp
public static string GetColumnName(this PropertyEntry propertyEntry)
{
    var storeObjectId =
                StoreObjectIdentifier.Create(propertyEntry.Metadata.DeclaringEntityType, StoreObjectType.Table);
    return propertyEntry.Metadata.GetColumnName(storeObjectId.GetValueOrDefault());
}
```

Seemed it works for my scene, but not sure whether it's the best practice or not

Could anyone please help on this, thanks in advance

### Include provider and version information

EF Core version: 5.0.0
Database provider: (`Microsoft.EntityFrameworkCore.SqlServer`)
Target framework: (.NET 5.0)
IDE: (Visual Studio 2019 16.8)

**Comment by ajcvickers** [comment]
@WeihanLi The method is obsolete because it will not always give the correct answer for newer models. For EF Core 5.0, this only means models that have TPT inheritance mapping, but as we add more features there will be more cases where the method will give the wrong answer.

If you have a model for 3.1 and you haven't changed it to use TPT, then you should be okay calling the implementation above in 5.0.

**Comment by WeihanLi** [comment]
Thanks @ajcvickers

**Comment by Neme12** [comment]
@ajcvickers I feel like this should be added to the list of breaking changes or somewhere else with a migration guide. I couldn't figure out that I had to use `StoreObjectIdentifier.Create`, at first I was just  trying to find this in properties of methods of various metadata. I only found out how to create a `StoreObjectIdentifier` when browsing this repository to see how `GetColumnName` is now used.

**Comment by ajcvickers** [comment]
@Neme12 The PR documenting this as a breaking change is here: https://github.com/dotnet/EntityFramework.Docs/pull/2938. This update has not yet been propagated to the live site.

**Comment by JonPSmith** [comment]
I have a question on the `StoreObjectIdentifier.Table(table.Name, table.Schema)` method. I need to equate the schema value provided by the context's `Model` to the schema value in the `DatabaseModel` provided by the scaffolder. The retuned values for a default database schema are different, i.e.

1. The context Model code `context.Model.GetDefaultSchema()` returns `null` 
2. The scaffolder `databaseModel.DefaultSchema` returns "dbo"

I need to detect that the "dto" returned by the scaffolder is the default setting for the context's `Model` code so that I can return `null` in the second parameter in the `StoreObjectIdentifier.Table` method.


### Include provider and version information

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET 3.1)
Operating system: Windows
IDE: (e.g. Visual Studio 2019 16.8)

**Comment by JonPSmith** [comment]
@ajcvickers, Sorry, I should have started my question as as a new issue. Let me know if you want this as a new issue let me know.

**Comment by stijnherreman** [comment]
Is this the intended way of getting a column name from a specific `DbSet<T>` or am I missing something? It seems convoluted, having to use `DbSet<T>.IEntityType` to get the `StoreObjectIdentifier` for said `DbSet<T>`.

```c#
var colorColumnName = dbContext.Widgets.EntityType
    .GetProperty(nameof(Widget.Color))
    .GetColumnName(StoreObjectIdentifier.Table(
        dbContext.Widgets.EntityType.GetTableName()!,
        dbContext.Widgets.EntityType.GetSchema()!
    ));
```

**Comment by AndriySvyryd** [comment]
You can also call `.GetColumnBaseName()`, but this will have a different behavior in the future, when column name can be overriden per table
