### ISSUE TITLE
EF Core 5.0, TPT inheritance, How to specify DeleteBehavior for inherited class/tables?

### ISSUE THREAD

**Issue by olegkap** [dotnet/efcore#23335]
Hi,

I was trying to take advantage of TPT feature in new EF Core 5.0 and found out that by default inherited classes created with ReferentialAction.Restrict.

How do I change this behavior for TPT scenario and change it default ReferentialAction behavior to Delete for example?

What happens now that I would need to issue to different delete if I want to delete lets say Person and PersonEmployee.

Thanks,
Oleg

**Comment by ajcvickers** [comment]
@olegkap When the entity is marked as Deleted, then EF Core will send delete statements for both tables. While theoretically this can be optimized in some cases by having using a database cascade, such behavior is not something that EF Core relies on, since database cascades have significant limitations on some platforms, including SQL Server.
