### ISSUE TITLE
Normalization of SqlExpressionFactory::ApplyDefaultTypeMapping

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#23404]
Hello,

Current implementation of SqlExpressionFactory::ApplyDefaultTypeMapping removes "Convert to object".
https://github.com/dotnet/efcore/blob/e45256e6166c548c7db6c54e3e8996b33996659a/src/EFCore.Relational/Query/SqlExpressionFactory.cs#L47-L50

For me - it is very strange behaviour of this method :)

I suggest move this operation into RelationalSqlTranslatingExpressionVisitor::VisitUnary.

Just for improving of code :)

Although it may improve perfomance also.

What do you think about this?

``` c#
 public override SqlExpression ApplyDefaultTypeMapping(SqlExpression sqlExpression)
 {
  if(Object.ReferenceEquals(sqlExpression,null))
   return sqlExpression;
 
  if(!Object.ReferenceEquals(sqlExpression.TypeMapping,null))
   return sqlExpression;
 
  var tm=m_TypeMappingSource.FindMapping(sqlExpression.Type);
 
  if(Object.ReferenceEquals(tm,null))
   return sqlExpression;
 
  var r=this.ApplyTypeMapping(sqlExpression, tm);
 
  return r;
 }//ApplyDefaultTypeMapping

```

``` c#
 protected override Expression VisitUnary(UnaryExpression unaryExpression)
 {
  Debug.Assert(!Object.ReferenceEquals(unaryExpression,null));

  const string c_bugcheck_src
   ="LcpiOleDb__SqlTranslatingExpressionVisitor::VisitUnary";

  var r1_e=base.VisitUnary(unaryExpression);

  var r1
   =Check.BugCheck_Value_NotNullAndInstanceOf<SqlExpression,Expression>
     (c_ErrSrcID,
      c_bugcheck_src,
      "#001",
      nameof(r1_e),
      r1_e);

  Debug.Assert(!Object.ReferenceEquals(r1,null));

  if(r1 is SqlUnaryExpression sqlUnaryExpression)
  {
   if(sqlUnaryExpression.OperatorType==ExpressionType.Convert)
   {
    Debug.Assert(!Object.ReferenceEquals(sqlUnaryExpression.Type,null));
    Debug.Assert(!Object.ReferenceEquals(sqlUnaryExpression.Operand,null));
  
    if(sqlUnaryExpression.Type==Structure.Structure_TypeCache.TypeOf__System_Object)
    {
     //Remove convert to object
  
     r1=sqlUnaryExpression.Operand;
    }//if
   }//if
  }//if

  Debug.Assert(!Object.ReferenceEquals(r1,null));

  Debug.Assert(!Object.ReferenceEquals(this.Dependencies,null));
  Debug.Assert(!Object.ReferenceEquals(this.Dependencies.SqlExpressionFactory,null));

  var r2
   =this.Dependencies.SqlExpressionFactory.ApplyDefaultTypeMapping
     (r1);

  Debug.Assert(!Object.ReferenceEquals(r2,null));

  return r2;
 }//VisitUnary

```

**Comment by smitpatel** [comment]
Actually that would be an incorrect thing.
Compiler adds convert to object node to match types in various case. Now that would be visited via VisitUnary but when we are visiting UnaryExpression, we don't know if we need to preserve the convert node or to remove it. 
Example.
`stringColumn.Concat((obj)intColumn)` because most matching overload for concatenation to int will match the object overload, there will be convert node. In this case we cannot remove the convert node. Instead we have to preserve convert node and assign type mapping to string column to conversion. And this would not call ApplyDefaultTypeMapping.
Now if a user request default type mapping for it then no specific type is required so the conversion to object was just to satisfy client contract and has no effect on server side hence it can be removed. So we remove it in ApplyDefaultTypeMapping. Further when we create convert node, we apply default type mapping to operand of it since type mapping from outside cannot influence it inside conversion so in this method we simply return the operand.
