### ISSUE TITLE
[Question] Migrations workflow and There is already an object in the database error.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/efcore#2343]
I'm trying to understand how the migration workflow is supposed to be used/work.

I have my local db created using migrations.
updated code, added migrations, apply, everything worked fine.

now let's say I publish this application to azure, where there is an empty db.

1) Should I have this code so migrations are applied on azure server? or there's another way to manage this?

```
        public ApplicationDbContext()
        {
            if (!_created)
            {
                Database.AsRelational().ApplyMigrations();
                _created = true;
            }
        }
```

then after that I updated code, apply migration (local), etc. and publish to azure.

right now I'm not sure how, I ended up in a state where the application runs (both local and azure) but if I try to do anything with ef commands I get:

```
System.Data.SqlClient.SqlException: 
There is already an object named 'IdentityRoles' in the database.
```

How can this be resolved without deleting the database/tables? What can make me get into this state (so I can avoid it in the future) ? Any help and guidance are very welcome. I didn't used migrations before.

I'm sorry I don't know the exact steps on how I get into this, but I using/trying as a I'm learning so I may very well screwed that up without even noticing.

**Comment by rowanmiller** [comment]
@Bartmax is it possible that a different context (i.e. different fully qualified type name) created the same tables in the database? Migrations are keyed off the type name, so if the Identity tables are created with a  different type name then it will try and apply the migration to create tables that are already there.

Regarding deploying migrations... we are working to have proper deployment support during publish but in the meantime you do need to use code to apply them. I would actually recommend adding the code during Configure in Startup.cs (rather than in a static constructor on the context). The only reason we don't do this for ApplicationDbContext in the project template is for local startup time during development.
