### ISSUE TITLE
Migration creates constraint before altering efcore 3.1.x

### ISSUE THREAD

**Issue by deereeed** [dotnet/efcore#23443]
## Ask a question
There was a problem with operations order in migrations, https://github.com/dotnet/efcore/issues/21037.
Issue is closed, changes were merged in  5.0.0-preview6 milestone.
But in ef core 3.1.x the problem is still exis.
Is it possible to merge pach from https://github.com/dotnet/efcore/issues/21037 to 3.1.x ?

**Comment by ajcvickers** [comment]
@deereeed At this time we don't believe this issue meets the bar for patch. In particular, this is only the second report we have on this issue since release, it's fixed in 5.0, and the workaround (reorder the migration) is reasonable. See [the planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more information on how we determine which issues to patch.
