### ISSUE TITLE
Include() on abstract entity results in InvalidIncludeExpression

### ISSUE THREAD

**Issue by vflame** [dotnet/efcore#23547]
Including a property of an abstract type results in an InvalidOperationException stating the include expression is invalid. Works fine if casted to concrete type. Removing the EF migration eliminates the error; however, results in an incorrect migration. May be related to: https://github.com/dotnet/efcore/issues/18325

There should be consistency in the Include behaviors. Using the string overload for include works fine, but using the Linq expression results in an error. This was working in EF core 2.1/2.2 but is no longer working in 5.0 (did not test with 3.0/3.1).

Configuration:

```c#
public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {

        }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<StV>().HasBaseType<VBase>();

            builder.Entity<Inbound>().HasOne(p => p.VBase);

            builder.Entity<VBase>().HasOne(p => p.User).WithMany().IsRequired().HasForeignKey(p => p.UserId);

            //commenting out this line results in invalid migration (extra FK of 'UserId1') but eliminates the Invalid Include Expression issue.
            builder.Entity<User>().HasMany(p => p.StVs).WithOne(p => p.User).HasForeignKey(p => p.UserId);

        }
    }
```

Models
```c#
public class Inbound
    {
        public string Id { get; private set; }

        public VBase VBase { get; set; }
    }


    public class User
    {
        public string Id { get; private set; }

        public IEnumerable<StV> StVs { get; set; }
    }


    public abstract class VBase
    {
        public string Id { get; private set; }
        public User User { get; set; }
        public string UserId { get; set; }
    }

    public class StV : VBase
    {
    }
```

Test Harness
```c#
 var ctx = host.Services.CreateScope().ServiceProvider.GetRequiredService<ApplicationDbContext>();
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();

            //valid
            var valid0 = ctx.Set<Inbound>()
                .Include(p => (p.VBase as StV).User)
                .ToList();

            //valid
            var valid1 = ctx.Set<StV>()
               .Include(p => p.User)
               .ToList();

            //valid, not consistent with invalid0
            var valid2 = ctx.Set<VBase>()
               .Include(nameof(VBase.User))
               .ToList();

            //invalid include expression, not consistent with valid2
            var invalid0 = ctx.Set<VBase>()
               .Include(p => p.User)
               .ToList();

            //invalid include expression
            var invalid1 = ctx.Set<Inbound>()
              .Include(p => p.VBase)
              .ThenInclude(p => p.User)
              .ToList();

            //invalid include expression
            var invalid2 = ctx.Set<Inbound>()
               .Include(p => p.VBase.User)
               .ToList();
```

Reproduction:
[EFCoreLocalTests.zip](https://github.com/dotnet/efcore/files/5625215/EFCoreLocalTests.zip)

EF Core version: 5.0
Database provider: SqlServer
Target framework: .NET 5
Operating system: Win 10
IDE: VS 2019 Preview

**Comment by smitpatel** [comment]
You are trying to configure 2 relationships with same reference navigation and same foreign key property in 2 types in same hierarchy. The later one will override the former one. 

First you are configuring one-to-many relationship between VBase and User without any inverse collection navigation using "UserId" as FK.
Then you are configuring one-to-many relatioship between Stv and User with an inverse collection navigation and using same FK as before. This removes the previous configuration as they are conflicting. Further you are getting error without this line of "UserId1" since you did not use "Users" navigation anywhere so that causing another relationship with "UserId1" as a property.

With above model you have User navigation only declared on Stv and there is no such navigation on VBase.

With that Include behaviors are as expected.
If you include "User" navigation on Stv, it will always work. String/expression either overload.
If you include "User" navigation on VBase,
- For expression based overload you need to cast it to derived type. We look for navigation on casted type.
- If you don't cast then we look for it on VBase where it is not defined in the model and the error is thrown.
- The casting for navigations in derived type is useful for getting code completion and string type checking in IDE. For string based overload none of those is needed. So when you specify a navigation as a string, EF will try to find the navigation in base type first and if not found look into derived types for such navigation. The navigation specified in Include via string must existing in at least one derived type fully else that is also an error.

@AndriySvyryd - Is this valid model? There is a clr type defined on VBase but not added to model yet no error.

**Comment by ajcvickers** [comment]
We discussed this in triage and don't believe there is anything actionable here. Closing as by-design.

**Comment by vflame** [comment]
> You are trying to configure 2 relationships with same reference navigation and same foreign key property in 2 types in same hierarchy. The later one will override the former one.
> 
> First you are configuring one-to-many relationship between VBase and User without any inverse collection navigation using "UserId" as FK.
> Then you are configuring one-to-many relatioship between Stv and User with an inverse collection navigation and using same FK as before. This removes the previous configuration as they are conflicting. Further you are getting error without this line of "UserId1" since you did not use "Users" navigation anywhere so that causing another relationship with "UserId1" as a property.
> 
> With above model you have User navigation only declared on Stv and there is no such navigation on VBase.
> 
> With that Include behaviors are as expected.
> If you include "User" navigation on Stv, it will always work. String/expression either overload.
> If you include "User" navigation on VBase,
> 
> * For expression based overload you need to cast it to derived type. We look for navigation on casted type.
> * If you don't cast then we look for it on VBase where it is not defined in the model and the error is thrown.
> * The casting for navigations in derived type is useful for getting code completion and string type checking in IDE. For string based overload none of those is needed. So when you specify a navigation as a string, EF will try to find the navigation in base type first and if not found look into derived types for such navigation. The navigation specified in Include via string must existing in at least one derived type fully else that is also an error.
> 
> @AndriySvyryd - Is this valid model? There is a clr type defined on VBase but not added to model yet no error.

Thanks for the clarification. We can use the string or just cast one of the derived types and it appears to materialize the includes properly for any objects in the hierarchy.
