### ISSUE TITLE
Cannot group by object

### ISSUE THREAD

**Issue by offirpeer** [dotnet/efcore#23592]
I upgraded efcore 2.2 to 5 and simple group by and object is not working:

`List<IGrouping<Categories, Businesses>> businessesByCategory = location.Businesses.GroupBy(x => x.Category.Parent ?? x.Category).ToList();`

In Ef Core 2.2 it worked fine, the businesses were grouped by their category, now it does nothing.

If I try to group by **id** it works:

    List<IGrouping<int, Businesses>> businessesByCategory = location.Businesses.GroupBy(x => x.Category.ParentId ?? x.CategoryId).ToList();

But I need the Category entity and this way I get only the category id.

**Comment by smitpatel** [comment]
GroupBy entity type is non-trivial and does not translate to SQL GROUP BY always.
In 2.2 release, we did client evaluation. Since 3.x release query stopped doing client evaluation exception in top level projection. See [breaking change](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client) hence it does not work.

Add this translation to server is being tracked by #17653
