### ISSUE TITLE
Automatically recreate computed column on migration changes

### ISSUE THREAD

**Issue by Mizuwokiru** [dotnet/efcore#23619]
I found some disadvantage when faced with computed column changing on **SQL Server** using **EF Core 5.0**.
So, for example, we have an entity:
```csharp
public class Some {
    public Guid Id { get; set; }

    public decimal Value { get; set; }

    public decimal SquaredValue { get; set; }
}
```

Let's pretend that **SquaredValue** is _already calculated_ column in some **IEntityTypeConfiguration** implementation with following code:
```csharp
builder
    .Property(x => x.SquaredValue)
    .HasComputedColumnSql($"{nameof(Some.Value)} * 2");
```

Next, I want to add some precision settings to this column. I added it and it's looks like that:
```csharp
builder
    .Property(x => x.SquaredValue)
    .HasComputedColumnSql($"{nameof(Some.Value)} * 2")
    .HasPrecision(18, 5);
```
I create migration and open generated class. EF Core generated migration with **AlterColumn** call, so when I try to update database using this migration an error "ALTER TABLE ALTER COLUMN failed because one or more objects access this column." occurs.

How about generate drop and add column calls instead of alter column?

**Comment by roji** [comment]
@Mizuwokiru EF already drops and creates computed columns in migrations - I've recreated your exact scenario and everything seems to work, the runnable code sample below produces the following when applying migrations:

```sql
ALTER TABLE [Blogs] DROP COLUMN [SquaredValue];
ALTER TABLE [Blogs] ADD [SquaredValue] AS Value * 2;
```

Note that SQL Server computed columns don't really have their own precision/scale defined on them - as you can see from the DDL above; the precise type is inferred from the SQL expression you give.

Now, I suspect you really want to ask about changing the precision/scale of the underlying, non-computed column (i.e. Value rather than SquaredValue) - SQL Server indeed doesn't allow altering that column since the computed SquaredValue depends on it. EF could indeed drop all known computed columns which reference the column, and then recreate them afterwards.

<details>
<summary>Working code sample</summary>

```c#
public class BlogContext : DbContext
{
    public DbSet<Some> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Some>()
            .Property(x => x.SquaredValue)
            .HasComputedColumnSql($"{nameof(Some.Value)} * 2")
            .HasPrecision(18, 5);
    }
}

public class Some
{
    public Guid Id { get; set; }
    public decimal Value { get; set; }
    public decimal SquaredValue { get; set; }
}
```

**Comment by natelaff** [comment]
+1 on this

**Comment by ajcvickers** [comment]
@Mizuwokiru We discussed this and a couple of things came up. First, as @roji said, the type of a computed in SQL Server is the type of the SQL expression. You can use a `CAST` in that expression to get specific facets on the type. For example:

```C#
         modelBuilder
             .Entity<Some>()
             .Property(x => x.SquaredValue)
             .HasComputedColumnSql($"CAST({nameof(Some.Value)} * 2 AS decimal(18,5))")
             .HasPrecision(18, 5);
```

You should leave the `.HasPrecision(18, 5)` configuration as well, since this ensures that EF and SqlClient are aligned with the server for parameter types, etc.

Second, with regards to dropping and creating (rebuilding) columns, we do that when we can. However, in this case EF does not know which columns the SQL expression refers to--it's opaque to EF. Therefore in this case we don't know when the drop/create will be needed.
