### ISSUE TITLE
Converting EF Core to SQL for performance investigations

### ISSUE THREAD

**Issue by jaredpar** [dotnet/efcore#23610]
## Ask a question

I'm hitting an issue where several EF Core queries to a SQL DB are timing out when I run them in my web application. This is not unexpected, I'm a bit new to SQL DBs of the scale I'm dealing with and it's been a teaching experience for me to get my indexes and queries in the right shape. But I'm having real trouble finding a way to profile the SQL query that EF Core is running so I can understand what is going wrong here. 

My process is that when I see this I go to my App Insights log, find the SQL exception and grab the SQL query which timed out and it looks roughly like the following:

```sql
SELECT COUNT(*)
FROM [ModelTimelineIssues] AS [m]
LEFT JOIN [ModelBuilds] AS [m0] ON [m].[ModelBuildId] = [m0].[Id]
WHERE (([m0].[StartTime] >= @__started_DateTime_0) AND ([m0].[DefinitionId] = @__definitionId_1)) AND CONTAINS([m].[Message], @__text_3)
```

My process is then to essentially replace the `@` values with real values, run the SQL in SSMS studio (or anywhere where an execution plan tracker is available) and see where the query is stalling out. The actual query I execute ends up looking like this:

```sql
SELECT COUNT(*)
FROM [ModelTimelineIssues] AS [m]
LEFT JOIN [ModelBuilds] AS [m0] ON [m].[ModelBuildId] = [m0].[Id]
WHERE (([m0].[StartTime] >= '2020-12-01 03:00:42') AND ([m0].[DefinitionId] = 686)) AND CONTAINS([m].[Message], 'Error')
```

This query though executes instantaneously and the execution plan shows it hitting all the indexes I would expect. Then I execute the same query in my web app and it immediately times out. To me this indicates that there is a subtle difference in how EF Core is executing this query and what I'm doing locally to profile the problem. I'm unable to figure out what this difference is here and am hoping someone can point me in the rigth direction here. 

Or if there is generally a better way to profile EF Core queries against a SQL DB I'm very interested in learning that as well. 

The accompanying model for the query can be seen [here](https://github.com/jaredpar/runfo/blob/master/DevOps.Util.DotNet/Triage/Model.cs#L270). Can provide more info here if needed but given this is around the raw SQL I didn't expect this to be terribly relevant. 

**Note:** I'm fairly new to EF Core hence I fit looks like I'm doing some thing very basic wrong please assume I am and point it out to me :smile:

### Include provider and version information

EF Core version: 3.1
Database provider:Microsoft.EntityFrameworkCore.SqlServer
Target framework: netcoreapp3.1

**Comment by ErikEJ** [comment]
This may be a good start: http://www.sommarskog.se/query-plan-mysteries.html 

In addition, you can get better parameterized SQL by using ToQueryString: https://github.com/dotnet/efcore/issues/19549#issuecomment-572823246

**Comment by roji** [comment]
As @ErikEJ mentioned, queries can sometimes execute (quite) differently depending on whether they contain constants or parameters (not unlike compilers :rofl:). So a more accurate way of testing your query in SSMS would use the same parameter placeholders that EF Core emits:

```sql
DECLARE @__started_DateTime_0 datetime2 = '2020-12-01 03:00:42';
DECLARE @__definitionId_1 integer = 686;
DECLARE @__text_3 varchar2 = 'Error';

SELECT COUNT(*)
FROM [ModelTimelineIssues] AS [m]
LEFT JOIN [ModelBuilds] AS [m0] ON [m].[ModelBuildId] = [m0].[Id]
WHERE (([m0].[StartTime] >= @__started_DateTime_0) AND ([m0].[DefinitionId] = @__definitionId_1)) AND CONTAINS([m].[Message], @__text_3)
```

Make sure that your parameter types are exactly what EF sends too (datetime2, varchar2), otherwise that could be a source of discrepancy. You can see the type by turning on [EF's logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/). As @ErikEJ mentioned, [the new ToQueryString feature](https://github.com/dotnet/efcore/issues/19549#issuecomment-572823246) is an easy way to get the SQL of a LINQ query out, along with all its parameter declarations.

If you've made everything exactly the same, and your SSMS query (consistently) works fine while the EF one (consistently) does not, things start to get interesting. One thought is that SSMS may limits the number of result rows (database UIs usually do), while EF fetches everything in the query - this could be significant if the query returns a large number of rows (and limiting them in the query may be a good idea).

Let us know how it goes!

**Comment by ajcvickers** [comment]
@jaredpar Did the guidance from @roji help? Anything more we can do here?
