### ISSUE TITLE
Guidance on value generation for SQLCE provider

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#2363]
As I understand it, much of the EF7 value generation centers around use of sequences. Unfortunately, the SQLCE engine does not support sequences, not does it support a way of retreiving new value of NEWID, so the only "value generation" is use of IDENTITY on int and bigint columns. This works well in my current implementation. I have added a .UseIdentity() model level extension, and all is fine.

BUT: I would like the "default" behaviour for int and bigint keys to be to use IDENTITY, and currently it is the other way around (so you must always speficy "UseIdentity" for that to work). I had a modelconvention working that made useidentity the default, but it broke a number of tests.

What would be the best approach to implement this? I was thinking about adding a model level extension: UseNoValueGeneration, and make UseIdentity the default then? Thoughts?

**Comment by divega** [comment]
We are going to make `UseIdentity()` the default soon, so the problem should go away.

**Comment by ErikEJ** [comment]
@divega  Great, that means the tests will have to respect that. But I assume I will still need a global switch to turn if off, a la UseNoValueGeneration or?

**Comment by ajcvickers** [comment]
@ErikEJ In the EF7 KeyConvention, integer keys are set to StoreGeneratedPattern.Identity by default. This means that if no explicit value has been set for the key, then it should have a value generated when SaveChanges is called--just like in EF6. It is up to the provider to choose how to honor this--again, this is basically the same as in EF6. (The major difference from EF6 is that if an application sets a specific value for a key, then that value will be used by the update pipeline rather than being ignored. If the provider cannot handle having an explicit value set in this situation then it may choose to throw--which is what SQL Server does.)

EF7 also uses value generators for new entities, which are usually used to assign temporary key values. These are then replaced in SaveChanges by the real values returned from the provider. However, EF7 value generators don't have to generate temporary values; they can generate the actual real key values instead. The obvious example is for guids where the actual guid is generated client side and then saved.

So what about sequences? Well, for SQL Server we have a client-side value generator that uses a server sequence to get real values immediately so that temp values are never used. This means that the update pipeline will just save these values and Identity columns are not needed. But this is a SQL Server-specific behavior; we don't expect all providers to support this. It is entirely fine to not support this in SQL CE just as it is not supported in SQLite. We had made this behavior the default for SQL Server, but that didn't mean we expected other providers to have to do so as well. And as Diego points out we have decided to change the default back anyway.

**Comment by ErikEJ** [comment]
So for the update pipeline, I probably do not need the Identity annotation. As I recall, I needed it for migration/table creation statements, but maybe I am doing something wrong? I think I needed it to generate the IDENTITY property in the table create statement!?

**Comment by ajcvickers** [comment]
@ErikEJ That is an interesting question. :-) I think the CE provider should rely entirely on StoreGeneratedPattern.Identity. If it is there, then create an Identity column, if not, don't. Having no Identity columns by default for the whole model is something that should be handled by the core--I created #2369 for this.

For SQL Server, the UseIdentity or UseSequence methods (which will be renamed) will not change that conceptually something like an Identity column is being used--i.e. the app doesn't have to specify key values. They just change how the provider will implement that pattern. We will remove the NoValueGeneration setting from SQL Server since this should be switched off at the core model level instead, either on individual properties or through #2369.

**Comment by ErikEJ** [comment]
@ajcvickers the sqlce provider now uses identity unless switched off via StortGeneratedPattern setting on a property
