### ISSUE TITLE
Application Level Data Encryption Support

### ISSUE THREAD

**Issue by SPEMoorthy** [dotnet/efcore#23653]
Data to be stored in the database will be kept always encrypted format for all DB vendors.

If an entity/property is annotated with Encryption flag. Migration should be created the columns with String column to store the encrypted form of data. Saving context Should be the place to encrypt the data. Querying part should be the part of decryption. Raw SQL will return Encrypted Entity.. That can be passed to conversion utility to decrypted.

Any other better way to handle this solution....? Like Interceptors?

My intention is We are going to Build business model with required Types. If I introduce Colum / Table is Encrypted with my Encryption method. EF will take care of 

1) Creation of DB Schema to store Encrypted Data.
2) Storing and Retrieving data will be as usual. (All Cryptic operations will be taken care by EF Core)

Pros:-
This will boost use of EF Core.

Cons:-
Performance...  Can be compromised by the value of data security during this cloud-driven application Era.

Thanks & Regards,
@spemoorthy

**Comment by ajcvickers** [comment]
@SPEMoorthy This is not something we plan to implement in EF Core for many reasons. From a purely pragmatic perspective, there isn't a lot of commonality in what different database systems support, and we're certainly not going to roll-our-own encryption.

If you've having issues with using the encryption features of a given database system with EF Core, then please let us know so that we can understand what you are trying to do and why it doesn't work.

**Comment by SPEMoorthy** [comment]
@ajcvickers thanks for the answer.
