### ISSUE TITLE
The Generated migrations for Identity Property is nullable with an entity

### ISSUE THREAD

**Issue by AhmedKhalil777** [dotnet/efcore#23673]
This issue with my AppUser that inherit from the IdentityUser like DocNo

![image](https://user-images.githubusercontent.com/38745087/102011574-af6f1180-3d4d-11eb-8ccc-6602825b1a1c.png)
![image](https://user-images.githubusercontent.com/38745087/102011610-f52bda00-3d4d-11eb-8de5-97f78aa7445f.png)
 
but when work with other entities it works like AppointmentNo

![image](https://user-images.githubusercontent.com/38745087/102011525-615a0e00-3d4d-11eb-95b9-24571188bf70.png)
![image](https://user-images.githubusercontent.com/38745087/102011652-3fad5680-3d4e-11eb-8a35-a69e1860becf.png)

**Comment by roji** [comment]
I wasn't able to reproduce your issue with the following steps, please share a project where the issue occurs.

* Create a new project with dotnet new aspnet --auth Individual
* Create a MyUser type extending IdentityUser, with a DocNo int property, and specify that in the ApplicationDbContext's generic parameters
* Delete existing migrations and create a new initial migration.

**Comment by ajcvickers** [comment]
@AhmedKhalil777 This is likely because the `Patient` is a sub-type of `AppUser` and this hierarchy is mapped to a single table--otherwise known as a TPH mapping. In this mapping, all database columns mapped from properties in the sub type must be nullable, since rows from the parent type will have no value for that column.
