### ISSUE TITLE
EF Core 5 support in netcoreapp3.1?

### ISSUE THREAD

**Issue by Simonl9l** [dotnet/efcore#23735]
EF Core version:
Database provider: (Pomelo.EntityFrameworkCore.MySql
Target framework: netcoreapp3.1

Seems that Microsoft.EntityFrameworkCore 5.0.x has a dependency of other packaged such as:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/66816457/102679095-e5533200-4161-11eb-86d3-64bde872d5ae.png">

But it was [pitched](https://devblogs.microsoft.com/dotnet/announcing-the-release-of-ef-core-5-0/#how-to-get-ef-core-5-0) to be able to work with 3.1.x ? Whist we all love to up great to .Net 5 tomorrow...

Integrating with other 5.0.x libraries it's then not really 3.1.x compatible, if one depends not other version of these libraries beyond a simple hello world app or you get into horrid package dependency issues?

**Comment by roji** [comment]
@Simonl9l all the dependency packages you're seeing do support netcoreapp3.1 - you don't have to use .NET 5.0 to use any of them. The .NET version (3.1, 5.0) is unrelated to the library versions you're seeing above.

Regardless, if your application needs to depend on one of these libraries, then yes, you'll have to make sure that versions are aligned with what EF Core requires - nuget helps do that.

**Comment by Simonl9l** [comment]
@roji To be clear, your suggesting that one crosses over SDK versions of libraries such that EF Core 5 “can” be used in in a dotnet core 3.1 project? This would appear a non standard approach. 

Your replay also alludes to a way one can perhaps one can force NuGet package dependence’s to perhaps have say both a 3.1.10 and 5.0.1 version of day the `Microsoft.Extensions.Options` package so ones existing code leverages the 3.1.x package as implemented and only EF Core 5 uses its 5.0.1 dependency.

To be honest the page linked above (or elsewhere) should really have a “how to” use EF Core with 3.1 SDK section, that allows one to continue to use the 3.1.x packages our other existing code is dependent upon?

It might perhaps be considered, by those that can’t just jump to DotNet 5, a better experience that having to force developers to punt on this reported upgrade “capability” if they have to, each one, work out how to “fight” with NuGet to achieve what is being suggested?

This otherwise comes across as a hack than a supportable deployment scenario?

**Comment by roji** [comment]
> To be clear, your suggesting that one crosses over SDK versions of libraries such that EF Core 5 “can” be used in in a dotnet core 3.1 project? This would appear a non standard approach.

SDK versions (e.g. 5.0.101), .NET TFMs (e.g. netcoreapp3.1, net5.0) and nuget library versions are completely different things. 

It's true that EF and .NET versions increment at the same time (e.g. EF Core 5.0 was released at the same time as .NET 5.0), but that's all it is. EF Core 5.0 targets .NET Standard 2.1, so you can use it - and all of its dependencies libraries - in an application targeting .NET Core 3.1. There's nothing non-standard or hacky about this, and no need to upgrade to .NET 5.0 just in order to use EF Core 5.0.

**Comment by ajcvickers** [comment]
@Simonl9l This is easy to test. For example, this project targets .NET Core 3.1, even though it uses EF Core 5.0 and brings in all the 5.0 dependent packages.

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
            <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.1" />
        </ItemGroup>
</Project>

```

**Comment by Simonl9l** [comment]
@ajcvickers thanks, yes that easy...if only it were that simple.

There, for a whole development community out there that have 1000’s of lines of code across multiple projects, seems to be an indication based on the announcement that EF Core 5 “would” work with 3.0.x package dependencies.

For packages such as `Windows.Extenstions.Options` what is so needed from the 5.0.x version for EF Core 5 that is not implemented in the 3.1.x version such that it could not have been to minimum version needed, that force package upgraded to don’t perhaps change the functionality?

I get that it’s cool to have 5.0.x packages everywhere but is kind of flies in the face of the 3.1 compatibility.

Many development projects don’t have the luxury to make such radical changes to there dependencies without a whole host of downstream (mostly testing) implications.

unfortunately the ship has sailed here...it is now what it is, and we’ll get to jump to 5.0.x at some future date when we can support a full regression test.

**Comment by ajcvickers** [comment]
@Simonl9l If there is some package that EF Core depends on, even transitively, that doesn't work with .NET Core 3.1, then please let us know. As @roji stated, the 5.0 package versions is orthogonal to whether or not these packages work on .NET Core 3.1 or not. Also, if you run into any breaking change updating one of the dependent packages from 3.1 to 5.0, then please let us know about that. All these packages should be fully backward compatible.

**Comment by Simonl9l** [comment]
@ajcvickers it's not like the likely won't work..as a software develops with 1000's of lines of code across multiple micro services, no doubt like others, we'd prefer (as many other would agree) to not bump library versions as that would otherwise need a full regression of each.

If the functionality to say the 3.1.10 version of a EF core dependent package is **_"exactly"_** the same implementation as the 5.0.x version why not have just made the the EF Core dependency have a **_minimum_** of that 3.1.10 version.

We don't what to have to test all that backwards compatibility with our other code...we'd prefer that the EF core developers just supported those 3.1.10 packages and make the **3.1 Compatibility** Claim more real. 

An approach there would ease our path to adoption. As it stands we'll now wait till do a full DotNet 5 adoption...

**Comment by roji** [comment]
> We don't what to have to test all that backwards compatibility with our other code...we'd prefer that the EF core developers just supported those 3.1.10 packages and make the 3.1 Compatibility Claim more real.

EF Core 5.0 claims to be compatible with the .NET Core 3.1 *platform* (by targeting .NET Standard 2.1, [see this page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms)), but makes no specific guarantees or claims about the versions of its nuget dependencies. If you see a place where we make any such claim, please point it out so we can fix it. You should get more familiar

> As it stands we'll now wait till do a full DotNet 5 adoption

Once again, .NET 5 is different from EF Core 5 and version 5.0 of other nuget libraries. You don't have to adopt .NET 5 in order to adopt EF Core 5.0.

> If the functionality to say the 3.1.10 version of a EF core dependent package is "exactly" the same implementation as the 5.0.x version why not have just made the the EF Core dependency have a minimum of that 3.1.10 version.

Nobody made that claim. My expectation is for dependent packages to be fixing bugs and possibly adding valuable features. It is standard practice for libraries and software projects in general to depend on latest versions of dependencies, because we cannot always know exactly which bugs are being fixed in dependencies, or which features are being added that could be useful to our users; holding versions back would potentially expose users to various issues with older versions that have been fixed since. Making EF Core depend on latest dependency versions also ensures we are properly compatible with those latest versions, since that's how we run all our testing.

**Comment by Simonl9l** [comment]
@roji 7 @ajcvickers thanks both for your explanations, and responses in general, both your positions make sense from you perspectives as do ours and possibly other product development teams position associated with migrating to newer version. It's tough and thee are trade-off's either way.

We'll defer for now...to a time when we can fully embrace the full 5.0.x stack and be in a position to carry out the full regression with other concurrent changes.

 Happy Holidays! Cheers!
