### ISSUE TITLE
I'm want to writing  a database provider,but i can't know how to write to it.

### ISSUE THREAD

**Issue by Vision-Zhang** [dotnet/efcore#23750]
Hi, 
I‘m Chinese，Recently, I would like to write a provider for the domestic database, but I do not know how to write, can I give some advice?
I have read  this article [https://blog.oneunicorn.com/2016/11/11/so-you-want-to-write-an-ef-core-provider] ,but I'm still wondering.

**Comment by roji** [comment]
Writing an EF Core provider is quite a big task. If your database is a relational one (SQL), then your best bet is to start off with one of the existing relational providers; [the PostgreSQL provider](https://github.com/npgsql/efcore.pg) can be a good starting point since it's an external project and not inside the EF Core repo, but the [SQL Server](https://github.com/dotnet/efcore/tree/main/src/EFCore.SqlServer) or [Sqlite](https://github.com/dotnet/efcore/tree/main/src/EFCore.Sqlite.Core) ones are also possible.

If you have a non-relational database, there will be more work to do, and the [Cosmos](https://github.com/dotnet/efcore/tree/main/src/EFCore.Cosmos) provider may provide some direction in where to start.

**Comment by Vision-Zhang** [comment]
@roji Tanks,I also think it's a very difficult job for me who's just started for half a year.but,I'll try

**Comment by roji** [comment]
Good luck @Vision-Zhang, I'm going to close this issue for now, but don't hesitate to post back or file new issues for specific questions.
