### ISSUE TITLE
UseSqlServerIdentityColumn optional arguments break code

### ISSUE THREAD

**Issue by Coder3333** [dotnet/efcore#23805]
My custom library was complied against the 1.0 version of UseSqlServerIdentityColumn(PropertyBuilder) and is shared with many other projects.  EF Core 3.0 changed the signature to UseSqlServerIdentityColumn(PropertyBuilder, Int32, Int32) with optional arguments.  This caused every piece of code that references my library to break once they updated to EF Core 3.0, because the runtime does not accept UseSqlServerIdentityColumn(PropertyBuilder) as a substitution for UseSqlServerIdentityColumn(PropertyBuilder, Int32, Int32), even though you would think that it might because of the optional arguments.  If the EF Core team had created overloads for UseSqlServerIdentityColumn with the additional parameters, but left the original signature in place, I wouldn't have this issue.  As it stands, I have to re-publish my library with a reference to EF Core 3.0, even though I am not making any changes to my code.

I realize that at this point there is nothing that can be done about this issue and that UseSqlServerIdentityColumn has been entirely deprecated now, but I am just so surprised that this change made it out the door.  I wish that the .Net Runtime would recognize two signatures as the same if the only difference was that some optional arguments were added, but that is just not the case.  I did not see any other mentions of this issue online, and wanted to point it out so that this is not done again in the future.  Thank you very much to the hard work of the EF Core team.

**Comment by roji** [comment]
@Coder3333 EF Core does introduce some breaking changes in major versions in some cases (after all, that's why they're major versions); as a result, applications and libraries using EF Core aren't generally expected to work out-of-the-box across major versions (especially when jumping from 1.0 to 3.0!). Note that earlier versions of EF Core did introduce more breaking changes (which were also more severe), and at the point where the product is, it's likely that we'll be doing less in the future (and more minor ones). We also take more care to obsolete overloads rather than remove them.
