### ISSUE TITLE
Filtered SQL query returns modified entities that don't match the filter criteria

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/efcore#23887]
## Steps to reproduce
1) Use FindAsync to get an entity from the database and modify a field on it
2) Query the database with a filter on that field that does not match the value you set it to
3) Notice that it is still returned even though it doesnt match the filter criteria

### Include your code

```C#
async Task Main() {
    var services = new ServiceCollection();

    services.AddLogging(logging => logging.AddConsole());
    services.AddDbContext<ApplicationContext>(db => {
        db.UseSqlServer(@"Server=(localdb)\mssqllocaldb; Database=test; Trusted_Connection=True; MultipleActiveResultSets=true")
            .EnableDetailedErrors()
            .EnableSensitiveDataLogging();
    });

    using var root = services.BuildServiceProvider();

    using (var scope = root.CreateScope()) {
        var db = scope.ServiceProvider.GetRequiredService<ApplicationContext>();
        await db.Database.EnsureDeletedAsync();
        await db.Database.EnsureCreatedAsync();

        db.Blogs.Add(new Blog {
            Name = "Blog 1",
            IsActive = true
        });

        await db.SaveChangesAsync();
    }

    using (var scope = root.CreateScope()) {
        var db = scope.ServiceProvider.GetRequiredService<ApplicationContext>();
        var blog = await db.Blogs.FindAsync(1);
        blog.IsActive = false;
        
        // Dont save changes
        
        // This will return the blog that we just marked as inactive because IsActive is still true in the database
        // and we haven't called SaveChanges
        var blogs = await db.Blogs.Where(x => x.IsActive).ToArrayAsync();
    }
}

// Define other methods and classes here
public class ApplicationContext : DbContext {
    public ApplicationContext(DbContextOptions<ApplicationContext> options)
        : base(options) {
    }

    public DbSet<Blog> Blogs { get; set; } = default!;

    protected override void OnModelCreating(ModelBuilder model) {
        model.ApplyConfigurationsFromAssembly(this.GetType().Assembly);
    }
}

public sealed class Blog {
    public int BlogId { get; set; }
    public string Name { get; set; } = default!;
    public bool IsActive { get; set; } = default!;

    internal class EntityConfiguration : IEntityTypeConfiguration<Blog> {
        public void Configure(EntityTypeBuilder<Blog> entity) {
            entity.ToTable(nameof(Blog));
            entity.HasKey(x => x.BlogId).IsClustered();
            
        }
    }
}
```

![image](https://user-images.githubusercontent.com/5934505/104666962-f1abab80-5689-11eb-90e6-3c80ce2653e0.png)

## Expected Outcome
It seems like the entity should be filtered locally as well as on the SQL Server so that local changes apply.

### Include provider and version information
EF Core version: 5.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.3

**Comment by ajcvickers** [comment]
@ChristopherHaws Two important points here:

* Query filters are just what they say--filters applied to queries
* Queries are always executed against the database, which means they always operate on the data in the database, not the data tracked by the context

Doing otherwise in each of these cases would require combining query results with tracking data, which is not something we plan to do since it would be very complicated and even then there are likely to be many places where combining the data runs into issues.

**Comment by ChristopherHaws** [comment]
Thanks for the response @ajcvickers!

So what would you recommend as a workaround for this issue? If EF is not the code to execute the filter against tracked entities then it seems like I will never be confident in any query and will always have to run my where criteria twice. For code that says `.Where(x => x.IsActive)` to return entities that are not active is not very logical and can easily cause bugs all throughout the code base. For this specific issue, I could `(await db.Blogs.Where(x => x.IsActive).ToArrayAsync(ct)).Where(x => x.IsActive).ToArray()` but I will need to do this with every single query in the app in order to be confident I am getting the results I asked for and looks very strange to anyone looking at the code.

**Comment by ajcvickers** [comment]
The intention is the following:

- Create a context instance
- Have query filters setup appropriate for the unit-of-work.
- Run queries so that the context only contains entities that match those filters
- Make updates as appropriate and SaveChanges
- Dispose the context instance

Note that the issue you are describing is not limited to query filters. Any query that askes if IsActive is true in the database while tracking objects that may have been mutated that value will have the same issue. Ideally, this is avoided by not reading the same data twice in a single unit of work. If the same data must be queried multiple times while it is also being mutated, then the application will need to make sure that this all happens correctly, which is often not trivial.

**Comment by ChristopherHaws** [comment]
Hmm, that is quite unfortunate. We are using the pattern described [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation#the-deferred-approach-to-raise-and-dispatch-events) where we queue domain events and then right before SaveChanges we dispatch those events so that the side effects are tracked in the same transaction as the entity modification. It seems like there isn't really a way around this then. =/
