### ISSUE TITLE
Filtered include don't give expected results

### ISSUE THREAD

**Issue by MSchioldan** [dotnet/efcore#23959]
I'm not sure if this is 'an issue' or 'a feature', but I have this query, that returns unexpected results:

var attendees = await _dbContext.Attendees.Include(x => x.CourseAttends.Where(y => y.Status == "attended")).Where(x => x.CourseAttends.Count == 1).ToListAsync();

In my database I have an `Attendee` with two `CourseAttends`. The first attend with status `attended`, the second `cancelled`.

Now, I would expect the query above to return this attendee, but it doesn't. If I set the `.Count` equals 2, the attendee is in the query result.

So, is it by design, that I have to do the `.Where(y => y.Status == 'attended')` on the `.Count` in the final Where-clause?
I would expect the filtering to be reflected in the condition.

*I'm aware I could build the query better, but this is just an example. The real query is more complex and needs a better understand of the data.*

**Comment by anranruye** [comment]
I think this is by design.

Notice that `.Include()` is different from projection.

When you use `.Where(x => x.CourseAttends.Count == 1)`, you tell ef core, "ef core, i want to get some attendees which have one courseAttend". When you use `.Include(x => x.CourseAttends.Where(y => y.Status == "attended"))`, you tell ef core, "ef core, please also give me the courseAttends of the returned attendees, i dont want all of them, only these with an attended status".

`.Where()` and `.Include()` don't affect each other and can both work independently. So 
`_dbContext.Attendees.Include(x => x.CourseAttends.Where(y => y.Status == "attended")).Where(x => x.CourseAttends.Count == 1)` and `_dbContext.Attendees.Where(x => x.CourseAttends.Count == 1).Include(x => x.CourseAttends.Where(y => y.Status == "attended"))` should give the same result.
