### ISSUE TITLE
How can I configure data annotation to realize insert records when using guid

### ISSUE THREAD

**Issue by decie** [dotnet/efcore#23978]
I have configured the guid on primary key and added 
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
When migrate it, I have added  `defaultValueSql: "newsequentialid()"`, so it can generate the id automatically when I insert some records. I can insert data successfully. But here I want to use Fluent API or data annotations to realize this, how can I do it?

**Comment by roji** [comment]
@decie the SQL Server provider automatically generates sequential Guid values for for key properties - but this is done client-side (by EF Core) rather than by specifying `newsequentialid` as the column's default value. So if you have a simple entity type as follows:

```c#
public class Blog
{
    public Guid Id { get; set; }
    public string Name { get; set; }
}
```

... inserting new instances will automatically take care of Guid generation for you.

[This doc page contains some details](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties), though https://github.com/dotnet/EntityFramework.Docs/pull/2998 (which isn't yet live) improves on that.
