### ISSUE TITLE
How can I insert records with sql when using guid as primary key

### ISSUE THREAD

**Issue by decie** [dotnet/efcore#23991]
I have set  [DatabaseGenerated(DatabaseGeneratedOption.Identity)] on entity, and add the newsequentialid() when migrate in ef core. In this case, I can insert some records, but I want to realize this through Fluent API or data annotations, how can I do?

**Comment by anranruye** [comment]
see https://docs.microsoft.com/en-us/ef/core/modeling/sequences

**Comment by roji** [comment]
To add to @anranruye response... 

If you're looking to have an auto-generated Guid key, you don't need to do anything - EF Core will automatically generated sequential values for you as long as the property has been identified as a key (i.e. if it's named Id or BlogId for Blog, or if you explicitly configure it as a key). Note that this is done client-side and not server-side with `newsequentialid()`, since that can be more efficient.

Otherwise, if you want to use `newsequentialid()`, simply specify that with HasDefaultValueSql - no need for any additional Fluent API call or data annotation:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Blog>()
        .Property(b => b.SomeGuid)
        .HasDefaultValueSql("newsequentialid()");
}
```
