### ISSUE TITLE
Why DbContext.Remove() deletes dependant entities even when a new entity is provided?

### ISSUE THREAD

**Issue by kejdajar** [dotnet/efcore#24000]
Hello,
I have attached a small runnable project demonstrating my question. I have an entity of type User. Every User always has a Speciality specified. This is a very simplified example, but basically, I need to delete the Speciality from the database and insert a new Speciality (with a new Id) instead. The User entity has a property User.SpecialityId which can never be set to null. 

What I tried was:

 ```C#
// get the User with a pre-seeded speciality
 var firstUser = _dbContext.Users.Include(u => u.Speciality).FirstOrDefault();
// remove their Speciality from database
  _dbContext.Specialities.Remove(firstUser.Speciality);
// assign a completely new Speciality instead of the previous one
  firstUser.Speciality = new Speciality("This should replace the previous Speciality.");           
  _dbContext.SaveChanges(); 
```
When I run this code, the User is deleted from the database together with the old speciality. Only the newly inserted
speciality remains in the database. I need the User to stay in the database.

The User:

```C#
 public class User {
        public User( string name ) {
            Name = name;
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        // navigation property
        public int SpecialityId { get; set; }
        public Speciality Speciality { get; set; } = null!;
    }
```

The Speciality:

```C#
 public class Speciality {
        public Speciality( string name ) {
            Name = name;
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        // navigation property
        public ICollection<User> Users { get; set; }
    }
```

## My solution

So far I have managed to come up with a following solution:

```C#
  modelBuilder.Entity<User>()
                        .HasOne<Speciality>(u => u.Speciality)
                        .WithMany(s => s.Users)
                        .IsRequired(true)
                        // other DeleteBehaviour members throw "association between entity types has been severed" exception
                        .OnDelete(DeleteBehavior.ClientNoAction);
```

Also, I need to perform this whole delete and insert operation within a single transaction. The previous `DeleteBehavior.ClientNoAction ` works fine. 

Yet I am still concerned this is not a best practice or side-effect-free solution. Is this the way to go, or is there any better way of handling this?

### My environment (Postgre SQL)

EF Core version: 3.1.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: .NET Core 3.1
Operating system: Windows 10 Pro 64bit
IDE: Microsoft Visual Studio Enterprise 2019, Version 16.8.4
[npgsqlcore.zip](https://github.com/dotnet/efcore/files/5882523/npgsqlcore.zip)

**Comment by ajcvickers** [comment]
@kejdajar This relationship is configured for cascade delete by default because the dependent (User) cannot exist without a principal (Specialty) since the FK is not nullable. Changing this behavior makes sense in your case, although it would be more normal to use `Restrict`. See https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete for more information on cascade deletes.

Alternately, you could leave the cascade delete in place if it is useful, but change the timing of cascades with `context.ChangeTracker.CascadeDeleteTiming = CascadeTiming.OnSaveChanges;` This means that the User will not be marked as deleted as soon as the required Specialty is deleted. Instead that will only happen if a different Specialty has not been assigned before SaveChanges is called. (I suspect setting the DeleteBehavior matches what you want more than changing the timing, but I mention it for completeness.)

**Comment by groege** [comment]
Is there a reason not to just update the existing with the new entity?

**Comment by kejdajar** [comment]
@groege Updating works fine as long as the `Specialities.Remove(firstUser.Speciality)` is left out from the code. Updating is also fine when the .Remove() method is called within a new database transaction. Our business requirement is that all related database operations must happen within a single transaction scope, so two transactions was never an option for me. Also, it is important for us to remove all "dangling" Specialities after they have been un-assigned from the User. I have also reworked the relationship to be one-to-one to better reflect how things work within our app, but this does not change anything.

**Comment by ajcvickers** [comment]
@kejdajar It's interesting that Restrict behaves that way; I will investigate.

**Comment by ajcvickers** [comment]
Investigated this, and it a consequence of cascade timing. With the default value (cascade changes immediately), the violation of graph integrity is reported immediately, because `Restrict` prevents EF from conceptually setting the FK to null. This can be changed by either not using `Restrict`, or by changing the cascade timing--see https://docs.microsoft.com/en-us/ef/core/change-tracking/relationship-changes#cascade-delete-timing-and-re-parenting.

For example,

```C#
context.ChangeTracker.CascadeDeleteTiming = CascadeTiming.OnSaveChanges;
```
