### ISSUE TITLE
How can I limit the size between two property when migrating

### ISSUE THREAD

**Issue by decie** [dotnet/efcore#24042]
There is one model, it contains two int type property.
I want to add data annotations on the two properties to limit the size. propertyA should larger than propertyB.
<pre>public class MyModel
    {
        
        [?]
        public int propertyA{ get; set; }
        //
        [Compare("MinDayRate", ErrorMessage ="zv")]
        public int propertyB{ get; set; }
    }</pre>

**Comment by anranruye** [comment]
for what? seems not related to ef core.

**Comment by roji** [comment]
You seem to be asking EF Core to create a database check constraint which enforces [Compare]. However, [Compare] checks that the two properties are *equal*, not that one is larger than the other. You can define any check constraint yourself with the exact SQL you want; for your case, put something like the following in your OnModelCreating:

```c#
modelBuilder.Entity<MyModel>()
    .HasCheckConstraint("CK_Properties_A_B", "[propertyB] > [propertyA]");
```

Note: there does exist [EFCore.CheckConstraints](https://github.com/efcore/EFCore.CheckConstraints) which applies various .NET validation attributes as database check constraints (need to update docs), but it does not support [Compare] since that seems quite useless in a database.
