### ISSUE TITLE
AsQueryable vs AsNoTracking

### ISSUE THREAD

**Issue by changhuixu** [dotnet/efcore#24142]
What is the differences between `AsQueryable` and `AsNoTracking`?
Which one is better?

```C#
_dbContext.Blogs.AsNoTracking().ToList();

// vs
_dbContext.Blogs.AsQueryable().ToList();
```

https://github.com/dotnet/efcore/blob/3b0a18b4717c288917dabf8c6bb9d005f1c50bfa/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2430-L2444

Thank you.

**Comment by roji** [comment]
AsQueryable and AsNoTracking are completely unrelated.

AsNoTracking makes your query execute as a no-tracking query - [here are the docs on tracking and no-tracking queries](https://docs.microsoft.com/en-us/ef/core/querying/tracking).

AsQueryable in your example above is superfluous: since _dbContext.Blogs is already an IQueryable, it does nothing. AsQueryable is only needed in some cases where you need to treat an IEnumerable as an IQueryable.

**Comment by changhuixu** [comment]
I see. Thank you very much.
