### ISSUE TITLE
Why isn't the Activity API used to track diagnostic events?

### ISSUE THREAD

**Issue by eduard-bystrov** [dotnet/efcore#24171]
like for example in [HttpHandlerDiagnosticListener](https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/HttpHandlerDiagnosticListener.cs#L594).

**Comment by roji** [comment]
Related: https://github.com/dotnet/runtime/issues/22336
Posted for SqlClient as well: https://github.com/dotnet/SqlClient/issues/917

**Comment by ajcvickers** [comment]
@eduard-bystrov We looked at Activity IDs when we first did this work. At the time they were of limited value for correlation since they cannot handle multiple, interleaved activities, which are not uncommon when doing database access against multiple databases. Therefore, we have correlation IDs that are associated with the database objects and do not interfere with each other when using interleaved actions across multiple objects.
