### ISSUE TITLE
Using included filtered query in same linq statement again

### ISSUE THREAD

**Issue by Der-Kraken** [dotnet/efcore#24183]
## My Question

I'm using the new feature "Filtered Include" and it is working well. I found a situation (which I want to use in production) where the filtered query works unexpected.

I have an Entity "Blog" which references N "Posts". So I want to load each Blog and include their Posts but only if the name of the Post is equal "ExampleName".

The query should only return Blogs if the filtered include is 1 or greater. Blogs without matching Posts can be ignored.

If found two ways which works. 
1. Load each Blog with `ToList()` into memory and then call `.Where(o => o.Posts.Any())`. Without `ToList()` the statement `.Where(o => o.Posts.Any())` will target each referenced Post (ignoring the filtered include).
2. The second way would be to copy the `Where()` into `Any()`. But then the sql will check it twice.

_By the way. If I would code pure SQL I would have used InnerSelect. Maybee it would make sense to add that option to the Filtered Include feature?_

My question is if the first solution will be fixed? For me it seems as unexpected behavior. For the moment I will use the workaround by loading all blogs into memory.

### My Query

```C#
var blogWithPosts = _dbContext.Set<Blog>()
   .Include(b => b.Posts.Where(p => p.Name == "ExampleName")) 
   .Where(b => b.IsDeleted == false)
   .ToList() // This line is required because on database ".Where(o => o.Posts.Any())" will target all Posts of the Blog.
   .Where(b => b.Posts.Any())
   .ToList()
   ;
```

### Include provider and version information

EF Core version: 5.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0.3
Operating system: Windows 10
IDE: e.g. Visual Studio 2019 16.8.5

**Comment by maumar** [comment]
@Der-Kraken this behavior is by design. The include "filter" only applies to the elements in the collection that is being included (Posts) - all Blogs will always be returned, regardless of the filter. Basically, the query with include will never return fewer elements than query without the include. 
If you want to return fewer Blogs you need to apply the filter on the blogs separately, like you suggested either copy the predicate into Any, or filter them on the client.

**Comment by Der-Kraken** [comment]
Away from the "Inner Join" example above I have here another scenario which behaves unexpected.
Again I wrote a linq blog-query and filter their posts. But know I want so select the filtered collection.

For me it feels wrong that the Posts are unfiltered.

```C#
var blogWithPosts = _dbContext.Set<Blog>()
   .Include(b => b.Posts.Where(p => p.Name == "ExampleName")) 
   .Where(o => o.IsDeleted == false)
   .Select(o => new 
   {
      BlogId = o.Id,
      FilteredPosts = o.Posts, // All posts are returend, but I expected the filtered one's.
   }
   .ToList()
   ;
```

Loading all blogs into memory with `ToList()` works.

```C#
var blogWithPosts = _dbContext.Set<Blog>()
   .Include(b => b.Posts.Where(p => p.Name == "ExampleName")) 
   .Where(o => o.IsDeleted == false)
   .ToList() // This line is required in order to access filtered posts.
   .Select(o => new 
   {
      BlogId = o.Id,
      FilteredPosts = o.Posts, // Now it works but with bad db performance.
   }
   .ToList()
   ;
```

By the way. I think a developers expectation is that ToList should not make any difference. If a difference in result happens it should not be "by design" but only for technical limitations.

**Comment by smitpatel** [comment]
`Include` operator applies loading of a collection on `Blog` instance. Hence filtered `Include` doesn't change anything with how navigations are used inside a query, it only changes elements in the collection "iff" parent instance is in final result. In your query you are not loading blogs (include is fully ignored), you are selecting `Posts` collection in anonymous type. This is disjoint from `Posts` collection in blog instance if you were having it in result and EF loading data in it with filtered include. Hence `Posts` will be fully loaded from database. If you need to filter posts then you need to write a where after `b.Posts` in your projection.

**Comment by Der-Kraken** [comment]
Thank you for your answer. For me (and colleagues) the expectation was that once a navigation property has been filtered that we work on that filtered one again. The current behavior of EF-Core feels like a bug. I think the most intuitive way for a developer is that the middle `ToList()` don't change the result. That should be the aimed way for the ef-api.

As a workaround I could of course write the same "Where"-clause multiple times. But for maintenance reasons we avoid redundant code. So we would use the middle `ToList()` instead double Where's.

What I want to know is, is this behavior really "by-design" or will be changed in future?
If it is "by-design" than I'm excited to hear the reasons for it.

**Comment by roji** [comment]
@Der-Kraken one way to look at it, is that if an earlier Include affects what is later seen in filters, then the absence of an Include should also mean no related entities are seen at all. In other words, the following query would never return anything, since the Posts aren't included at all:

```c#
var blogWithPosts = _dbContext.Set<Blog>()
   .Where(b => b.Posts.Any())
   .ToList();
```

If you do add Include to the above, you end up actually fetching all Posts (expensive), although the intention was only to get Blogs which have Posts. This is one one reason why filtering and including are two separate, disjoint concepts in the way query works, and the Include itself doesn't participate in the ordering of LINQ operators (whether it's before or after a filter has no bearing).

Having said that, we briefly discussed this internally, and we do think that the current design could be to a certain extent a result of adding the filtered include feature later, after the original Include was already in place; had we designed things from scratch today, we may have ended up in a different place. But it is what it is now.
