### ISSUE TITLE
[Question] Can we improve the performance of EF 7

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#2424]
Reading this article looks like EF 7 in some case is lower almost 6x compare to dapper.
http://ppanyukov.github.io/2015/05/20/entity-framework-7-performance.html
Github: https://github.com/ppanyukov/EntityFrameworkBenchmarks

What is the status of EF 7 performance benchmark, can we put in the ReadMe.md

**Comment by rowanmiller** [comment]
Hey,

We have benchmarks for the basic scenarios in EF7 and we have some scenarios that are greatly improved over EF6 and others that are still quite slow. We have these on a list to address but we haven't optimized the code paths yet because the code paths are still changing quite rapidly. If we'd optimized things before now then we'd likely have wasted a lot of time as things have changed so much and we'd end up hitting different bottlenecks.

The code base is starting to churn less now, so we are starting to look at these. We still have plenty of time to get things tidied up before we need to RTM. ASP.NET 5 is the main driving force behind the dates for our initial RTM of EF7 and they have announced that they will still be pre-release when Visual Studio 2015 reaches RTM (so EF7 still has a while before it reaches RTM). I can't comment on specific dates since they are up to the Visual Studio and ASP.NET 5 teams to make public.

BTW we are also working on some things now that will eventually end up with the results of our automated performance runs being public.

~Rowan
