### ISSUE TITLE
IndexAttribute in Microsoft.EntityFrameworkCore - causing dependency

### ISSUE THREAD

**Issue by SetTrend** [dotnet/efcore#24246]
The `IndexAttribute`, newly introduced with EF Core 5.0, is defined in the `Microsoft.EntityFrameworkCore` namespace.

This way, using it with POCOs, stored in a separate assembly, loses the advantage of being independant of Entity Framework in unit tests or middle tiers which may also want to take advantage of an index's uniqueness feature.

Wouldn't this attribute have better been added to the standard `System.ComponentModel.DataAnnotations` namespace and assembly instead?

**Comment by anranruye** [comment]
+1
However, notice that these new attributes is from `Microsoft.EntityFrameworkCore.Abstractions` assembly which is a really small package.

**Comment by smitpatel** [comment]
While the namespace is same as EFCore, the assembly is different as pointed out by @anranruye. That assembly is designed to be lightweight and independent of everything EF brings in for this kind separation only.

**Comment by roji** [comment]
Note also that System.ComponentModel.DataAnnotations is a BCL .NET assembly that doesn't belong to EF Core. That makes it inappropriate for EF-specific things, since changes there could affect other products too; for that reason, it hasn't been updated in quite a while and can be considered archived.

If you truly want your POCOs to be independent of Entity Framework, uses the Fluent API (in OnModelCreating).

**Comment by SetTrend** [comment]
Thank you for all your enlightening questions.

@roji: Fluent API won't do, because I expect the middle tier/front-end to be able to validate uniqueness, too (e.g. MVC [`ModelState.IsValid`](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelstatedictionary.isvalid#Microsoft_AspNetCore_Mvc_ModelBinding_ModelStateDictionary_IsValid).

Only for the sake of design, I'd like to pose this final question:

Is it wise to use the product name `Microsoft.EntityFrameworkCore` as namespace for something that's supposed to be uncoupled from the product? Wouldn't it have been advisable to rather use a generic namespace for that package, like, e.g. `Microsoft.Validation.Constraints`?

**Comment by roji** [comment]
> Fluent API won't do, because I expect the middle tier/front-end to be able to validate uniqueness, too (e.g. MVC ModelState.IsValid).

In general, I don't think uniqueness can be validated by the middle tier/front-end, since uniqueness can only be checked in the database (looking at all rows). Or am I misunderstanding what you're looking for?

> Is it wise to use the product name Microsoft.EntityFrameworkCore as namespace for something that's supposed to be uncoupled from the product?

The things inside Microsoft.EntityFrameworkCore.Abstractions aren't intended to be generic validation features, but very much EF-specific features only. Some of them aren't about validation - [Index] is first and foremost about creating a database index, which has nothing to do with validation as a concept (remember indexes don't have to be unique). Another example is [Comment], which specifies some comment on a database column or table. We don't believe these should be uncoupled from the product - quite to the contrary (even if they're in a separate package).

Even for validation, it's true that System.ComponentModel.DataAnnotations was originally conceived (among other things) to contain generic validation attributes that would be enforced/applied by various products/tiers. That approach has largely been abandoned; different products invariably support different types of validations, different validations make sense depending on which tier you're in (the uniqueness validation above is a great example), and making common validation attributes means it's very hard to evolve them, since many products depend on them. The whole model is basically not very scalable/sustainable.

**Comment by ErikEJ** [comment]
FluentValidation FTW @jeremyskinner

**Comment by SetTrend** [comment]
I see ... Thank you for elaborating on the reasoning! ❤️ 👍 

Regarding uniqueness in upper tiers we're certainly on the same page. Upper tiers would only be able to perform preliminary checks, based on the sub set they have access to, of course.

However, such attribute could be valuable in providing hints to the user. A generic front-end, dynamically created from POCOs alone (e.g. by means of [T4](https://docs.microsoft.com/visualstudio/modeling/code-generation-and-t4-text-templates) or at runtime) could automatically provide helpful hints to the user. Similar to the `RequiredAttribte` which usually is indicated by an asterisk in front-ends, a Unique attribute could generate a tooltip message like "must be unique".

**Comment by roji** [comment]
> Similar to the RequiredAttribte which usually is indicated by an asterisk in front-ends, a Unique attribute could generate a tooltip message like "must be unique".

It's hard to understand, though, what "unique" would mean in this context; in the database context, unique means "globally unique across all rows", but I'm having a hard time seeing how something like that could be useful on a user-facing UI. Sure, the username/email must be globally-unique, but the user can't do anything to ensure that beyond trying a username and being told it's already taken.

I'm pressing the point because it's a good example of something that superficially seems like it could work across different tiers, but in reality does not... [Required] is indeed an example of something that's abstract and useful enough, that makes sense to have a general attribute not coming from any specific framework - and that indeed works both in EF Core and elsewhere. But that really seems to be the exception rather than the rule.
