### ISSUE TITLE
Setting a general [Column(TypeName="")] for strings and datetime for the migrations when using efcore and sqlite

### ISSUE THREAD

**Issue by johanknape** [dotnet/efcore#24269]
**MY PROBLEM:**
Right now when using efcore with sqlite, strings are case sensitive and datetime gets the type TEXT in the migration file. 

string:
`Origin = table.Column<string>(type: "TEXT", nullable: false)`

DateTime:
`DateTo = table.Column<DateTime>(type: "TEXT", nullable: false)`

My workaround for this is that I set all strings with the following annotation:
`[Column(TypeName = "TEXT COLLATE NOCASE")]`

And all DateTime gets the following annotation:
`[Column(TypeName = "DATE")]`

But I have to remember that for every class I make and if I want to change database in the future, that is a lot of files I need to change for a new migration file for that database.

**SOLUTION:**
If I could do a general setting for the migrations that tells it that all strings and DateTime should look a certain way, unless of course I made a manual setting on that property in the class would make my life so much easier.

Of course it should not be limited to just strings and DateTime, but since those are the ones I'm having trouble with, that's the ones I'm focusing on.

**Comment by roji** [comment]
Unfortunately Sqlite doesn't seem to allow defining a collation at the database level like SQL Server.

The PostgreSQL provider has a feature where you can specify the default collation at the database level, and that flows through as the collation for each property (if one isn't set explicitly). We could add something similar to Sqlite.

>  [Column(TypeName = "TEXT COLLATE NOCASE")]

Note that instead of this you should be able to configure the collation via the Fluent API, which is slightly better:

```c#
modelBuilder.Entity<Blog>().Property(b => b.Name).UseCollation("NOCASE");
```

>  [Column(TypeName = "DATE")]

Not a Sqlite specialist, but doesn't this create a NUMERIC type as opposed to a TEXT one, [as per the docs](https://www.sqlite.org/datatype3.html)?

**Comment by roji** [comment]
One addition comment: it's easy to loop over your EF model, and to programmatically set properies' column type to whatever you want. For example, you could use the following to set the column type for all string properties to `TEXT COLLATE NOCASE`:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    foreach (var entity in modelBuilder.Model.GetEntityTypes())
    {
        foreach (var property in entity.GetProperties().Where(p => p.ClrType == typeof(string)))
        {
            property.SetColumnType("TEXT COLLATE NOCASE");
        }
    }
}
```

**Comment by johanknape** [comment]
@roji Thank you, that looks exactly what I was looking for. Much appreciated.
