### ISSUE TITLE
Can IsSparse be included in a forthcoming EF Core 5 update

### ISSUE THREAD

**Issue by henrikdahl8240** [dotnet/efcore#24280]
Can IsSparse be included in a forthcoming EF Core 5 update so we don't need to wait for November 2021 for this very valuable feature?

**Comment by roji** [comment]
We only release important bug fixes in patches to existing versions, such as 5.0. Since sparse columns are a new feature, we won't be porting that back.

Note that you can pretty easily define sparse columns yourself via [raw SQL in migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql). The 6.0 feature only makes it easier/nicer, but it's not something you can't already do with 5.0.

Finally, you may want to consider trying the preview for EF Core 6.0 - they are generally considered very stable.

**Comment by henrikdahl8240** [comment]
OK.
Do you already know, if doing it now using raw SQL in migrations will cause some difficulties when upgrading to EF Core 6, e.g. that migrations do not work because the model will tell, that the column is not sparse, which it actually is, due to the raw SQL?
It it OK to use the EF Core 6.0 in production or it's not advisable?

**Comment by roji** [comment]
Defining sparse columns today with raw SQL shouldn't create serious issues down the road. When EF Core 6.0 comes along, if you want to switch to the nice new APIs, then the first time you generate a migration after that, that migration will alter that column to make it sparse. Since you already made it sparse via raw SQL, that operation is unneeded but most probably harmless; at worse you can delete those operations from the migrations. After that point everything is in sync and there won't be further issues.

EF Core 6.0 previews go through the same test verification as normal releases, and so are considered quite stable; we are also very reactive to bugs introduced in previews (regressions), so there's a very good chance that the fix would be available in the next preview (we release one every month). Of course, always deploy new versions with care.

Having said all that, previews aren't officially supported releases in the technical sense.

**Comment by henrikdahl8240** [comment]
@roji Thank you, as always, for your quick response!
