### ISSUE TITLE
Problem with UWP and 5.xxx versions?

### ISSUE THREAD

**Issue by Dedecekhribecek** [dotnet/efcore#24294]
I have UWP project with 3. 1.12 of EntityFrameworkCore and EntityFrameworkCore.Sqlite. every update to 5.xxx leads to problem. Please see attachments.

Before update packages
![project](https://user-images.githubusercontent.com/13888026/109384662-ab837200-78ee-11eb-9f6e-f01becef6060.png)

Result
![problems](https://user-images.githubusercontent.com/13888026/109384685-c8b84080-78ee-11eb-943b-63498ae5bcec.png)

**Comment by hez2010** [comment]
Neither UWP framework nor .NET Native compiler supports .net standard 2.1 (which is the target framework of efcore 5), you cannot use it in a UWP app.

**Comment by ajcvickers** [comment]
In general EF Core doesn't work with UWP. We are watching with interest how the various U.I. platforms develop. Given all the issues we have had trying to create a good experience for UWP together with internal usage data, we have currently put UWP work on the backburner. However, closing this as external, since these errors are specifically about UWP not supporting .NET Standard 2.1, which is out of the scope of EF Core.
