### ISSUE TITLE
EF7 Child entities are not inserted

### ISSUE THREAD

**Issue by AwsomeCode** [dotnet/efcore#2434]
Hi Team,
I am using EF7 in ASP.NET5 Console project. I am adding child entities to parent entity via Add() method and saving that parent entity only, via SaveChanges() method. But on my SQLServer database I am only seeing parent data is inserted to the parent table but in child table no data is inserted.

Is this implemented? or I am doing something wrong, pls guide me.

Edit: Just verified, Same code is working in EF6.
More Info: I have revEng Sqlserver database in EF7.

Thanks & Regards.
Kalpesh

**Comment by makcakaya** [comment]
It would be better if you showed some of your code.

**Comment by MaximBalaganskiy** [comment]
I think it's related to #2387

**Comment by rowanmiller** [comment]
Hey,

This is by design. `Add` now only adds the single object (consistent with other `Add` methods on collections in .NET). There is a new `TrackGraph` method you can use to add the root entity and everything reachable from it (you supply a delegate to work out the state for each entity).

We are discussing changing the name of `Add` to something like `AddSingleObject` just because `Add` behaved differently in previous versions.

~Rowan
