### ISSUE TITLE
Question: How to map to different schemas with MySql.EntityFrameworkCore v5?

### ISSUE THREAD

**Issue by DefinitelyADev** [dotnet/efcore#24342]
Hello,

I'm trying to map a class using the `System.ComponentModel.DataAnnotations.Schema.Table` attribute.
MySql uses the Database setting in the connection string to specify the schema name.
The issue is that I have associations across multiple schemas for example an entity in schema_a.table_a might have an one-to-one relationship with an entity in schema_b.table_a.
Unfortunately, the obvious answer to change the Schema property of the table attribute didn't work.
Is there any way to support this?

![image](https://user-images.githubusercontent.com/20267678/110331436-ca3ce380-8027-11eb-9e2e-cdafe61b11cc.png)

Thank you in advance!

EF Core version: 3.1.9
Database provider: MySql.EntityFrameworkCore
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: Visual Studio 2019 16.8.6

**Comment by roji** [comment]
@TsakiDev can you please post a more complete description of your problem, preferably including a runnable code sample? How does the [Table] attribute not meet your needs exactly?

/cc @lauxjpn

**Comment by ErikEJ** [comment]
@roji The OP uses the Oracle supplied provider

**Comment by roji** [comment]
Thanks @ErikEJ.

You may need to turn to Oracle for support on using the [Table] attribute. In general, you should be able to specify [Table] on any entity CLR type, but I'm not sure how that interacts with any Oracle-specific connection string parameter managing the schema.

**Comment by TsakiDev** [comment]
@ErikEJ You are correct the issue is that I want in the near future to update this project to .Net 5 and Pomelo implementation is at 5.0.0-alpha.3.

**Comment by lauxjpn** [comment]
@TsakiDev While there is no official support in Pomelo for multi-database support, it can be achieved quite easily. See https://github.com/dotnet/efcore/issues/22971#issuecomment-707768344 for a code sample.

**Comment by TsakiDev** [comment]
@lauxjpn Thank you for you help but I'm looking for a way to implement this using MySql.EntityFrameworkCore v5 since it's the only stable release currently for mysql and .Net 5.
There is a MySQLSqlGenerationHelper in MySql.EntityFrameworkCore but the API has differences and the MySql documentation is nonexistent.

**Comment by lauxjpn** [comment]
> Thank you for you help but I'm looking for a way to implement this using MySql.EntityFrameworkCore v5 since it's the only stable release currently for mysql and .Net 5.

@TsakiDev You did open https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1342 on our Pomelo repo.

The Pomelo 5.0.0 prereleases are stable (and have been from the beginning). We just haven't released the GA version, because there will be breaking changes introduced, that can impact a very small minority of people in a way, that could lead to a compile time error (easy to fix). It is being used in production by the community for months.

The GA release will be published over the next few weeks. See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088 for more information.

**Comment by TsakiDev** [comment]
Hm ok, I preferred to use pomelo anyway, since I had a pleasant experience with it in the past. I will start working with it now and merge it when the GA becomes available.
Thanks!
