### ISSUE TITLE
Changing a column type

### ISSUE THREAD

**Issue by f0rt** [dotnet/efcore#2435]
Is changing column type currently supported?
As far as I can see from my test `[Column(TypeName = "")]` is not respected. Also the fluent API doesn't have the `HasColumnType`.

Thanks,
Nedko

**Comment by bricelam** [comment]
Per #107, Data Annotations aren't supported yet. The Fluent API has changed a bit:
```C#
modelBuilder.Entity<Person>().Property(p => p.Name).ColumnType("char(30)");
```

**Comment by f0rt** [comment]
Oh.. I see. Sorry, I'm new to MVC/EF world. :)

 Actually it is even one lever deeper behind "forsqlserver()", right?
`builder.Entity<ApplicationUser>().Property(x => x.FirstName).ForSqlServer().ColumnType("varchar(50)")`

Unfortunately I still can't get it to work:
I'm using:
- VS2015 rc
- ef 7.0.0-beta4
- standart MVC 6 preview template with local login


There is something strange to me.
- When I click the Login button `OnModelCreating()` is called. No DB is created.
- When I submit a registration request the DB is created but the `OnModelCreating` is not executed.
Is this normal?

**Comment by bricelam** [comment]
Oh sorry, I forget beta4 is the latest release. :smile: The code changes so fast! The API will be changed in beta5. Type mapping will actually work in the release after that. If you need these features now, you should consider using the [nightly builds](https://github.com/aspnet/EntityFramework/wiki/Getting-Started-with-Nightly-Builds).

**Comment by bricelam** [comment]
> When I click the Login button OnModelCreating() is called. No DB is created.

The templates should include a call to `ApplyMigraitons` that creates the database. Otherwise, run `dnx . ef migration apply` before running the application to create the database.

> When I submit a registration request the DB is created but the OnModelCreating is not executed. Is this normal?

Yes, the result of OnModelCreating is cached in the service provider, so it should only ever run the first time the context is used.

**Comment by f0rt** [comment]
Thanks! :)

**Comment by f0rt** [comment]
Is there something like samples project or docs synced with the nightly builds? In other words: How to figure out how to use the latest code?

**Comment by ErikEJ** [comment]
@f0rt The best place for documentation of nightly builds is the related test code!

**Comment by rowanmiller** [comment]
@f0rt we don't do docs for nightly builds since that would waste a lot of time as things change all the time. If you decide to "live on the bleeding edge" then you are opting into the undocumented world where you need to figure things out. As @ErikEJ mentioned, looking at the test code is a good place to start.
