### ISSUE TITLE
Pull in data from another DbSet

### ISSUE THREAD

**Issue by mrlife** [dotnet/efcore#24439]
## Ask a question

I would like to pull audit information into unmapped properties from another `DbSet`. Can `Join()` or similar be called on a navigation property such as `StreetAddress` below? I have not been able to find a way.

If not, is there a supported way to accomplish this concept?

### Include your code

**Model**
```c#
public class Order
{
    public int Id { get; set; }
    public StreetAddress ShippingAddress { get; set; }

    [NotMapped]
    public DateTime CreateDate { get; set; }

    [NotMapped]
    public DateTime UpdateDate { get; set; }
}

public class Order_Audit
{
    [Key]
    public int AuditId { get; set; }
    public int Id { get; set; }
    public StreetAddress ShippingAddress { get; set; }

    public string AuditAction { get; set; } // Insert, Update, or Delete
    public DateTime AuditDate { get; set; }
}

// StreetAddress and StreetAddress_Audit not shown but are similar to above
```

**Query**
```c#
// pull in audit data for orders
context.Orders.Join(Order_Audit, ...);

// pull in audit data for street addresses -- workaround for the following possible in EF Core?
context.Orders.Include(o => o.StreetAddress.Join(...));
```

### Include provider and version information

EF Core version: 5.0.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0

**Comment by ajcvickers** [comment]
@mrlife I'm not really sure what you are trying to achieve here. If you can write the LINQ query, then it should work, but it's not clear what actual query you want. Have you tried writing the code? If so, then please post a runnable code example that you expect to work but does not, and include the exception generated.

**Comment by mrlife** [comment]
@ajcvickers Yes, I started with the code, and I apologize for not getting a clear explanation into this issue.

An entity in an `Include()` is not a `DbSet`, so it doesn't have access to `Join()`. 

For example, `StreetAddress` in the following:

```c#
context.Orders.Include(o => o.StreetAddress);
```

I would like to join `StreetAddress` to another entity, to pull in its `CreateDate` and `UpdateDate`, but there doesn't appear to be a way when using `Include()`. Is there another way?

**Comment by smitpatel** [comment]
- When EF Core generates entity instance (materializes an entity), it will assign values of all the properties which are mapped in the model. That means that any unmapped properties will have their default values. Also EF Core will only start tracking entity instances we generate if it is a tracking query.
- The way you are doing a `Join` in your first query for `Order`, it will fetch additional data but you would need to construct an `Order` object in `Select` to assign that data. This is specifically diverges from first point as EF Core is no longer creating entity instance. As a user you are creating an object which happens to be a same class as mapped entity.
- `Include` is specific API to assign navigation properties in EF Core queries, where the entity instance holding the navigation property and entity instance(s), targeted by the navigation both are creating by EF Core. If you are constructing any object yourself (no matter them being mapped entity types), `Include` won't do anything. If you performed a join of Order & Order_Audit and constructed new Order in projection & your Order has include specified on it, it will be ignored since there is no EF Core created order object in the result.

Overall, you can populate unmapped properties & navigation properties using Include at the same time in query without writing a client side post-processing step after the query. You have 2 option for this specific scenario
1. You basically query for Order join to it's audit and do same for StreetAddress and manually assign navigations after both queries has run in their results. This is splitting out Task of include outside the query since you want to assign values inside query by using `new Order` syntax.
2. You change the projection of the query to basically do an anonymous type construction which select actual entity and unmapped property values so `context.Orders.Join(...).Select(e => new { Order = e.Order, e.OrderAuditCreateDate, e.OrderAuditUpdateDate}` kind query. Here you are still asking EF Core to generate Order entity instance. In such query you can add include for `StreetAddress` and join with similar kind of query for `StreetAddress` (outside of Include API), to fetch additional data of CreateDate/UpdateDate for StreetAddress in your final result. Once the query has run, you iterate over result and assign relevant dates to their entity instances which are created by EF. This is splitting out assigning values of unmapped properties outside of the query.

As for `Include` API, the result of Include is always an entity instance which is generated by EF Core. Further, it has to create a consistent object graph which matches model definition. So if a navigation is required because FK is non-nullable then after Include the navigation must be populated to non-null instance and must not be filtered out. Because of this, there is very little value for reference navigation to be applied any operator on top it. Collection navigations are principal to dependent so they can always have 0 to n dependents so they do allow filtering and few other limited operations on the collection inside Include API. Supported APIs are restricted so that the final result is entity instance generated by EF Core only and it doesn't violate the graph consistency.
