### ISSUE TITLE
Why is EF Core 5.0 data retrieval at least 4x slower than using SQLClient?

### ISSUE THREAD

**Issue by ayushguptacoder** [dotnet/efcore#24494]
I have an issue where merely querying the data via EF Core is 6x slower than using SQLClient.
I have attached the benchmarks for local and remote DB. 

I have explained the issue here: https://stackoverflow.com/questions/66775415/ef-core-5-data-retrieval-is-4x-slower-than-using-sqlclient-for-a-simple-select-q

Benchmark results on remote database:

![image](https://user-images.githubusercontent.com/47259520/112262850-8bb04700-8c2b-11eb-93d8-803693441cd0.png)
![image](https://user-images.githubusercontent.com/47259520/112262863-9074fb00-8c2b-11eb-8201-5c2071ae37b2.png)

Benchmark result on the local database:
![image](https://user-images.githubusercontent.com/47259520/112262898-9d91ea00-8c2b-11eb-8b55-ef913cba5790.png)
Sample project showing 3x+ slowness when compared to SQLClient. This gets exaggerated when running against a remote database.
The project contains the migration which creates a single table and fills it with 36000 rows. The benchmark code is also in there.
[EFCoreBenchmarking.zip](https://github.com/dotnet/efcore/files/6194743/EFCoreBenchmarking.zip)

**Comment by roji** [comment]
@ayushguptacoder thanks for the full benchmark, that's exactly what we need in order to investigate issues/performance.

* Any particular reason to use RunStrategy.ColdStart, and to limit the target count to 5? EF definitely imposes a startup overhead (e.g. query compilation), which we typically don't want to take into account when measuring; since ColdStart disables pilot and warmup, it could be including various startup actions in the measurements, skewing results.
* "This gets exaggerated when running against a remote database." - this doesn't make much sense to me, if anything, latency should make the proportional gap *less* significant. Can you please try rerunning without ColdStart/targets?
* Your GetData_NoTracking_AsList includes a Console.WriteLine, which is sure to skew results.

After removing ColdStart and the Console.WriteLine, and adding an async SQL test, I get the following results running locally:

```
|                         Method |      Mean |    Error |    StdDev |    Median |       Min |       Max |
|------------------------------- |----------:|---------:|----------:|----------:|----------:|----------:|
| GetData_NoTracking_AsAsyncList | 178.21 ms | 3.537 ms |  5.712 ms | 179.19 ms | 164.06 ms | 185.83 ms |
|      GetData_NoTracking_AsList | 129.74 ms | 9.373 ms | 26.893 ms | 112.52 ms | 108.72 ms | 197.52 ms |
|          RetreiveingDataViaSql |  50.46 ms | 0.374 ms |  0.331 ms |  50.44 ms |  50.04 ms |  50.94 ms |
|     RetreiveingDataViaSqlAsync | 131.31 ms | 2.615 ms |  6.163 ms | 131.62 ms | 118.30 ms | 146.32 ms |
```

This shows a x2.5 difference between EF Core and raw SQL in the sync scenario, and a x1.3 difference in the async scenario. The slowness of the async scenario here is most probably SqlClient's async implementation, which could be optimized.

Beyond this, there are some other EF high-perf features which are likely to considerably close the remaining gap; for example, EF's compiled queries remove the overhead of finding the cached SQL (and materializer/shaper). In addition, I'm currently working on improving EF Core's runtime performance, so 6.0 should improve these results further; I suggest following #23611 to see this work, and also to see how to write the EF benchmark code more efficiently.

**Comment by ayushguptacoder** [comment]
Thanks for the quick reply. I updated the codebase to update all the properties when fetching data via SqlClient. I also disabled ColdStart and ran it for the default iterations. The results came back skewed. 

![image](https://user-images.githubusercontent.com/47259520/112269713-f6668000-8c35-11eb-8246-1efa385c63d7.png)

The results from remote execution are confusing too. I will check the #23611 to see if it helps. 

Remote DB: 
![image](https://user-images.githubusercontent.com/47259520/112270493-fadf6880-8c36-11eb-8905-ce8d0d0fc714.png)


[EFCoreBenchmarkingV2.zip](https://github.com/dotnet/efcore/files/6195074/EFCoreBenchmarkingV2.zip)

**Comment by roji** [comment]
@ayushguptacoder any progress in producing stable, meaningful benchmark results?

**Comment by ayushguptacoder** [comment]
@roji Not really, the latest release of Microsoft.EntityFrameworkCore.SqlServer (5.0.4 -> 5.0.5) did bring in some improvement. 
Here are the latest benchmarks against the local DB. 

Version: 5.0.4
![image](https://user-images.githubusercontent.com/47259520/113924727-02f2e880-979f-11eb-8ea9-197e93d0e37f.png)

Version 5.0.5
![image](https://user-images.githubusercontent.com/47259520/113924773-0dad7d80-979f-11eb-9b80-3ddd6097ba34.png)

Prerelease versions:
![image](https://user-images.githubusercontent.com/47259520/113925019-62e98f00-979f-11eb-857a-0e03912e664d.png)

The local DB results are acceptable and EF actually performs better ( when we include creating the entire result object) but I am still trying to figure out what changes when I make calls against DBaaS. 

I am fine with closing this issue and will wait for new releases.

Thanks for the help.

**Comment by roji** [comment]
@ayushguptacoder AFAIK EF Core 5.0.5 doesn't include anything that should change performance in any way ([see the issue list](https://github.com/dotnet/efcore/milestone/108?closed=1)). I suspect something is wrong with you benchmarks (or the way you're running them, e.g. parallel processes running at the same time?), giving you varying results regardless of EF Core version.
