### ISSUE TITLE
Questions about converting to int in Sqlite

### ISSUE THREAD

**Issue by stevendarby** [dotnet/efcore#24526]
For SQL Server, a number of Convert.ToX(value) functions are [translated](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/functions) to `CONVERT(X, @value)` which is great. I'm particularly interested in Convert.ToInt32.

Like many I use Sqlite for unit testing and found that it's [not translated](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/functions) for Sqlite. I do see a slew of new function mappings for 6.0 which is cool.

My question are:
1. Is Convert.ToInt32 (and similar) on the cards for Sqlite?
2. The translation for Convert.ToInt32 in SQL Server uses CONVERT, which is semantically the closest, but my understanding is that CAST functions very similarly- and because CAST is an ANSI-SQL standard, could a general relational translation be provided instead of a SQL Server specific one? I'm genuinely interested to learn about the subtle differences and the decision making process behind function mapping choices.
3. I don't think I can add CAST using `DbContext.HasDbFunction` (for either SQL Server or Sqlite) due to its unusual syntax, i.e. not just taking a parameter but also `as int/integer` - is this correct or are there any workarounds?

EF Core version: Tried 3.1.13 / 5.0.4 / 6.0 preview 2
Database provider: Microsoft.EntityFrameworkCore.Sqlite

**Comment by snappyfoo** [comment]
Regarding 3, I found I could use `HasDbFunction(...).HasTranslation(...)` to convert the single ColumnExpression argument into a SqlFragmentExpression using the table alias and appropriate delimiting/escaping etc, and supply that as the argument for "CAST"

**Comment by ajcvickers** [comment]
@snappyfoo What types of value are you attempting to convert and why?

**Comment by snappyfoo** [comment]
@ajcvickers

This is for varchar columns that in 99% of cases hold consistently zero-padded integers, but it’s possible for legacy data to use unpadded or variable length padded numbers. We need to get the max number. As we can’t reliably do a MAX() directly on the column in SQL (“1” would win over “00999”) previously we brought all back to a List and did the max on that using int.Parse. This could result in a few thousand strings returned so was hoping to shift this calculation to the database, which would require a cast in the query (or possibly padding them consistently in the query).

Cleaning up legacy data and improving the schema would be ideal, but is complicated by these sometimes being used in keys, migrated/synced from external systems, 30 years in the making etc. These questions are part of investigating temporary solutions.

TBH, since discovering the ability to provide my own translation for CAST I’m less interest in my initial questions, but I suppose they might still be of interest to others. I can post an outline of my solution too in case it’s useful.

**Comment by snappyfoo** [comment]
Against 3.1:

```C#
public class DatabaseFunctions
{
    public static int? CastAsInt(string value) =>
        throw new NotImplementedException("Used for Expression translation only.");
}
```

```C#
modelBuilder
    .HasDbFunction(typeof(DatabaseFunctions).GetMethod(nameof(DatabaseFunctions.CastAsInt))!)
    .HasTranslation(arguments =>
    {
        var columnExpression = (ColumnExpression) arguments.First();
        var argumentSql =
            $"{Delimit(columnExpression.Table.Alias)}.{Delimit(columnExpression.Name)} AS int";
        var argumentExpression = new SqlFragmentExpression(argumentSql);

        return SqlFunctionExpression.Create("CAST", new[] {argumentExpression}, typeof(int?), null);

        static string Delimit(string identifier) => $"[{identifier.Replace("]]", "]")}]";
    });
```

In reality I have a helper for the delimiting/escaping so I can adjust for Sqlite contexts, you might also want to protect against the first argument not being a column, but this shows the basic idea.

**Comment by bricelam** [comment]
SQLite provides [an extension for a UINT collation](https://github.com/sqlite/sqlite/blob/master/ext/misc/uint.c) that ignores leading zeros. You could also re-implement it in C#:

```csharp
sqliteConnection.CreateCollation(
    "UINT",
    // NB: This isn't a true re-implementation of SQLite's UINT collation, but should work for you
    (x, y) => long.Parse(x).CompareTo(long.Parse(y)));
```

```csharp
var max = context.Entities.Max(e => EF.Functions.Collate(e.PaddedProperty, "UINT"));
```

**Comment by snappyfoo** [comment]
Thank you @bricelam, that’s a good tip. I probably wasn’t clear enough that I’m writing primarily against SQL Server, and was hoping to find something that worked against SQLite in unit tests too. That’s why I sought a function mapping for CAST which works for both
