### ISSUE TITLE
Custom value converters

### ISSUE THREAD

**Issue by pikausp** [dotnet/efcore#24524]
## Ask a question

I wanted to add `CultureInfo` as a property to one of my entities. Since the type does not have a default conversion I created a `ValueConverter`. I used the following snippet to apply the conversion to all properties of the given type

```C#
var cultureConverter = new ValueConverter<CultureInfo, string>(c => c.Name, c => new CultureInfo(c));

foreach( var entityType in modelBuilder.Model.GetEntityTypes() ) {
    foreach( var property in entityType.GetProperties() ) {
        if( property.ClrType == typeof(CultureInfo) ) {
            modelBuilder.Entity(entityType.Name).Property(property.Name).HasConversion(cultureConverter);
        }
    }
}
```
this works fine, however, using the same method when dealing with my custom class does not work. The system creates a foreign key between the entities etc. What works when working with custom classes is the following

```C#
var classConverter = new ValueConverter<RandomClass, string>(v => JsonConvert.SerializeObject(v), v => JsonConvert.DeserializeObject<RandomClass>(v));

foreach( var entityType in modelBuilder.Model.GetEntityTypes() ) {
    foreach( var property in entityType.ClrType.GetProperties() ) {
        if( property.PropertyType == typeof(RandomClass) ) {
            modelBuilder.Entity(entityType.Name).Property(property.Name).HasConversion(classConverter);
        }
    }
}
```
sadly, this does not work for `CultureInfo`. The model is following
```C#
public class LocalizationItem : ILocalizationItem {
    public LocalizationItem( string key, CultureInfo culture, string value ) {
        Key = key;
        Culture = culture;
        Value = value;
    }

    public string Key { get; set; }
    public CultureInfo Culture { get; set; }
    public string Value { get; set; }
    public RandomClass? Class { get; set; }
}
```

When do I need to use which?  The answer [here](https://stackoverflow.com/a/52184765/3620174) seems to suggest the second method should work for all types, but that doesn't seem to be the case.

### Include provider and version information

EF Core version: 5.0.4
Database provider: Npgsql
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.9

**Comment by pikausp** [comment]
I'd like to add that I just noticed EF seems to have troubles when composite PK is created on the `Culture` property if the `HasKey` method was invoked after the converter was assigned.

```
modelBuilder.Entity<LocalizationItem>().HasKey(e => new { e.Key, e.Culture }); // works

var cultureConverter = new ValueConverter<CultureInfo, string>(v => v.Name, v => new CultureInfo(v));
foreach( var entityType in modelBuilder.Model.GetEntityTypes() ) {
    foreach( var property in entityType.GetProperties() ) {
        if( property.ClrType == typeof(CultureInfo) ) {
            modelBuilder.Entity(entityType.Name).Property(property.Name).HasConversion(cultureConverter);
        }
    }
}

modelBuilder.Entity<LocalizationItem>().HasKey(e => new { e.Key, e.Culture }); // throws System.InvalidOperationException: The property 'LocalizationItem.Culture' is of type 'CultureInfo' which is not supported by the current database provider. Either change the property CLR type, or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

**Comment by ajcvickers** [comment]
@pikausp When you say "sadly, this does not work for CultureInfo," can you be more specific what "does not work" means? I don't see anything obviously wrong. Ideally, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by pikausp** [comment]
Here is the sample [project ](https://github.com/dotnet/efcore/files/6235181/MappingRepo.zip). It contains three DbContext implementations. One fails for the Culture property with the following error
```
The property 'CurrentCulture' cannot be added to the type 'CultureInfo' because no property type was specified and there is no corresponding CLR property or field. To add a shadow state property, the property type must be specified.
```
second one fails for the custom class with 
```
The entity type 'RandomClass' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
```

and the last one works. Let me know if you need anything else.

**Comment by ajcvickers** [comment]
@pikausp Asking for entity types on the model (`modelBuilder.Model.GetEntityTypes()`) returns all the types that EF Core has configured by-convention as an entity type. So in this case, the following types are returned:
![image](https://user-images.githubusercontent.com/1430078/113202312-78027300-921f-11eb-8330-3490746aba0e.png)

Notice that RandomClass, CultureInfo, and some other reachable types are included in the model. This is because EF does not recognize these as primitive types and so maps them as entity types by default. This is a temporary state while the model is still being built.

Next, this `entityType.ClrType.GetProperties()` returns all public properties of the type. This included a static `CultureInfo` property, which cannot be mapped, and hence the exception is thrown.

To avoid this you need to be more explicit about which types/properties should get the converter. Specifically, I would avoid using `Model.GetEntityTypes()` as a starting point for further explicit configuration, since it will end up trying to bring too many types into the model.

**Comment by pikausp** [comment]
@ajcvickers thank you! What would be the correct way to add a custom converter to all properties of a certain type? (whether it's CultureInfo, some custom class etc.). I think having a global conversion for culture is fairly common and reasonable thing.

**Comment by ajcvickers** [comment]
@pikausp #10784 is tracking support for this, and has some discussion on workarounds. Unfortunately, I don't think there is a foolproof way to do this right now. You might want to use an interface or an attribute to mark your entity types so that you can filter to only the types you want to process.

Unless you have a very large number of entity types I would probably just do explicit configuration on each property. It's cumbersome, but easy to get right.

**Comment by pikausp** [comment]
@ajcvickers The most upvoted [workaround](https://github.com/dotnet/efcore/issues/10784#issuecomment-415769754) in the comments uses `Model.GetEntityTypes()` as well. Did I miss something? I guess right now it comes down to the "I would probably just do explicit configuration on each property"?

**Comment by ajcvickers** [comment]
@pikausp In many cases using GetEntityTypes or some other dynamic way will work, but it requires being careful about what is actually being found and configured.
