### ISSUE TITLE
EF Attributes for database roles and permissions

### ISSUE THREAD

**Issue by albinsunnanbo** [dotnet/efcore#24531]
### Problem
When trying to build an application with high security one of the aspects is to give applications minimal permissions to the database. For example a web application would have INSERT and SELECT, but not UPDATE nor DELETE permissions on an AuditLog table.
One way to make the security model quite comprehensible is to create database roles for different applications and scenarios and assign to the service accounts for the different services.

I would like to keep the security model tied to and visible in the object model to make it easy to visualize and maintain. Possibly also writing unit tests for it.  
This way security would be deployed with EF migrations together with the rest of my data model.  

### Solution idea
You could of course create a migration where you create your roles and assign permissions.
However, that hides the security settings scattered over different migrations, making it hard to get an overview.
One solution could be to annotate entity classes with attributes, like 

    [DbRole(Name="MyWebAppRole")]
    public class MyDbContext : DbContext
    {
       ...
    }

and

    [DbPermission(Principal="MyWebAppRole", Grant = DbPermissions.Insert | DbPermissions.Select)]
    public class Order
    {
        ...
    }

**Comment by roji** [comment]
The exact permission/authorization model varies from database to database, so anything like the above would most probably be very provider-specific (i.e. SQL Server-only). It's also unlikely that we could actually cover it with C# attributes, which are very limited in what they allow using; a Fluent API would be more comprehensive, but defeat your stated purpose of keeping authorization info with the types.

I personally don't believe it's a great idea to have EF model complex database features which don't affect any runtime behavior, and only affect schema creation in migrations... Value is generally limited as users can already achieve the same by including raw SQL in migrations, so it's basically about using .NET APIs rather than SQL for expressing the same thing.

**Comment by ajcvickers** [comment]
We discussed this and decided that this is not something we plan to add to EF Core. If you want this kind of information to be applied at the same time as migrations, then you could create an extension that pulls the info from somewhere in your model and puts it in the migrations.
