### ISSUE TITLE
Deepclone of the entity

### ISSUE THREAD

**Issue by risogolo** [dotnet/efcore#24696]
I would like to ask you wheter and how it is possible to clone entity loaded from DB containing entire graph of child properties and set that as new enity

or to load 2 diferrent entities of the same type from DB, and set (update) entity 1 with values from entity 2 including all subproperties (something like deep clone)

scenario I have
ID 1 ParentID = null
ID 2 ParendID =1 

I want to set (update) entity ID1 with values from entity ID2 (it contains huge hirerarchy graph - so including that)

how can I achieve that easily?

**Comment by ajcvickers** [comment]
@risogolo Generally if you query for the graph using `AsNoTracking()`, then you will get a non-tracked copy of the entities. You can then go through those entities changing primary keys as appropriate and then `Add` the graph.

**Comment by risogolo** [comment]
Yes, but I would appreciade to have a method out of the box which will do this for me, I have very large deep graph, so I dont want to do it manualy, is it possible to identify at least these propoerties somehow and then I can recursively iterate over the graph resetting these properties?

**Comment by roji** [comment]
@risogolo if you're looking to identify the primary key properties for entities, you can do this by consulting the EF Core model as follows:

```c#
var keyProperties = ctx.Model.FindEntityType(typeof(MyType)).FindPrimaryKey().Properties;
```

At that point you have a .NET PropertyInfo for each key property, and can easily reset it on an entity instance.

**Comment by koenbeuk** [comment]
@ajcvickers 

We're struggling with this issue today. Our scenario is related to Orleans. When a grain Activates, We grab a fresh copy of the entity graph. We then deep clone this entity graph so that we have 2 separate (but otherwise equal) graphs in memory. 

Over time, one of the graphs gets patched and a commit gets deferred. Finally when it's time to commit, We use the delta between the 2 graphs to know what needs to be patched in the database.

We're currently in the process of implementing a reliable deep clone. This is not trivial and it would be great if EF can do it for us.

**Comment by HenkKin** [comment]
Maybe this package will help you: https://github.com/HenkKin/EntityCloner.Microsoft.EntityFrameworkCore
