### ISSUE TITLE
RelationalConnection.BeginTransaction() passes level Unspecified

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#2469]
When [`RelationalConnection.BeginTransaction()`](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/RelationalConnection.cs#L93) is called without an isolation level, `Unspecified` is used. At the ADO.NET level, however,  [`DbConnection.BeginTransaction()`](https://msdn.microsoft.com/en-us/library/xfh66ye8%28v=vs.110%29.aspx), specifies that "the default isolation level for the specific type of connection is used".

`Unspecified` seems to mean something very different from "default": "A different isolation level than the one specified is being used, but the level cannot be determined.".

A more correct behavior seems to be for `RelationalConnection.BeginTransaction()` to end up calling `DbConnection.BeginTransaction()`, letting the ADO.NET provider choose the default.

I can submit a PR if you agree with this.

**Comment by roji** [comment]
Another possibility here is to decide that EF attempts to provide consistent behavior across databases, and to pass a specific isolation level down to the ADO.NET provider (e.g. `ReadUncommitted`).

**Comment by divega** [comment]
It has been our assumption on EF for a long time that `IsolationLevel.Unspecified` option meant "do whatever your provider or database would do by default".  In fact, for SqlClient and all the other ADO.NET providers included in the .NET framework the `BeginTransaction()` overload that takes no parameters is implemented as a call to another overload with `IsolationLevel.Unspecified`. 

That said, I find that particular part of the documentation confusing, so I can see how different providers may have chosen to give it different semantics and I think it wouldn't be hard for us to call the overload with no arguments instead of passing `IsolationLevel.Unspecified`. 

@AndriySvyryd any thoughts?

**Comment by roji** [comment]
My understanding was that `Unspecified` would be used for some custom isolation level specific to some provider, which doesn't get captured by any of the other standard enum values and is somehow expressed in a different provider-specific API.

Regardless, it's possible for Npgsql to also interpret `Unspecified` as default if that's what everyone does (we're very close to releasing the 3.0.0 major version, so it's a good time to make this kind of change).

**Comment by divega** [comment]
Yes, I believe you are right and `Unspecified` means that too. However if such provider specific API isn't used and just `BeginTransaction(IsolationLevel.Unspecified)` is called, it should use whatever the default isolation level is for that particular database and provider.

I do believe it would be very good if Npgsql 3.0.0 implemented this behavior if it doesn't already.

**Comment by rowanmiller** [comment]
Discussed and agreed that providers can choose what Unspecified means

**Comment by roji** [comment]
OK, will modify Npgsql for this.
