### ISSUE TITLE
Automatic query splitting behaviour

### ISSUE THREAD

**Issue by stevendarby** [dotnet/efcore#24719]
EF Core generates a warning when it detects that a query may load multiple collections and split query has not been enabled. I would be very interested in seeing a new QuerySplittingBehavior option which would use the same collection detection to instead automatically switch to split query behaviour (‘Auto’?)

This would be on the understanding that it may not always make the absolute best choice, as ideally the decision around single vs. split should be made on a case-by-case basis so details such as the likely cardinality of collections can be factored in, but that it’s a pretty good heuristic— hence why the warning uses it.

This would be a good ‘smart’ feature of EF Core, similar to other carefully considered automatic optimisations that happen behind the scenes, e.g. command batching behaviour. 

One case where it might be especially useful is when a tool like AutoMapper is used for projections. If I’ve been following correctly, split query will soon work for such projections (i.e non-Include scenarios) in 6.0. When using AutoMapper, the number of collections in the projection is not obvious at the point of querying (at least not as obvious as with a manually crafted Select) and the DTO/mapping is easier to change independently of the query code. In some architecture the query code could just be taking generic type arguments for the entity set and projected DTO, making it harder to determine the appropriate split query behaviour without further parameters from the caller. Some - like me! - would be more than happy to let a new ‘Auto’ behaviour make the decision in such cases.

**Comment by roji** [comment]
@snappyfoo it sounds like you're asking for the option to enable split queries globally, which EF Core already supports ([see these docs](https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries#enabling-split-queries-globally)). This means that whenever a query perform e.g. a collection include, split query will be used rather than single query (with joins).

**Comment by snappyfoo** [comment]
> @snappyfoo it sounds like you're asking for the option to enable split queries globally, which EF Core already supports ([see these docs](https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries#enabling-split-queries-globally)). This means that whenever a query perform e.g. a collection include, split query will be used rather than single query (with joins).

From my reading of the documentation, using the SplitQuery option would mean a projection with **one** collection or more would be split into multiple SQL queries.

Meanwhile using the SingleQuery option only logs a warning if a projection has **two** collections or more. 

The proposed Auto option would only split the query when there were **two** collections.

The exact number which is the tipping point could theoretically change, the idea would be it uses the same number of collections as the tipping point as the current warning does under SingleQuery mode. (EF Core team could later decide two collections are ok, three is the tipping point, etc.)

**Comment by roji** [comment]
@snappyfoo the decision to log when two collections joins happen was somewhat arbitrary - there are many cases where a single collection join could lead to severe perf problems, and other where three collection joins are perfectly fine; it all depends on the actual cardinality of the data and the number and size of principal columns being duplicated.

So although I get your argument from a consistency/purity point of view, I'm not sure I see the actual value of another option to only use split query when two collection includes are present. Always-single and always-split seem quite sufficient as global defaults, and then the user can specify the behavior on a query-by-query basis; more options mean more complexity for maintenance and for users.

**Comment by snappyfoo** [comment]
> @snappyfoo the decision to log when two collections joins happen was somewhat arbitrary - there are many cases where a single collection join could lead to severe perf problems, and other where three collection joins are perfectly fine; it all depends on the actual cardinality of the data and the number and size of principal columns being duplicated.

Maybe it's worth highlighting my take on this again, as I know my first post wasn't understood initially:
> This would be on the understanding that it may not always make the absolute best choice, as ideally the decision around single vs. split should be made on a case-by-case basis so details such as the likely cardinality of collections can be factored in, but that it’s a pretty good heuristic— hence why the warning uses it.

I agree it's somewhat arbitrary, but I still think it's a decent rule of thumb.

> Always-single and always-split seem quite sufficient as global defaults, and then the user can specify the behavior on a query-by-query basis; more options mean more complexity for maintenance and for users.

I described a scenario where an additional global default would take away some complexity for users, so I still think this would be a good feature, but fair enough if can't convince you! Thanks for taking the time to read my suggestion.

**Comment by smitpatel** [comment]
Any query (regardless of single/split), for a collection needs to repeat the columns from outer which are used to identify collection (to add element to existing or create new one). So a query with just one collection
- can either do single query where all records of parents are repeated (not just identifying columns) but 1 DbCommand
- can do split query where parent records are not repeated but fetched in separate DbCommand

Which of above is faster depends on many factor including the size of columns on outer (which are repeated in single query but won't be in split query) & time cost to execute a separate DbCommand. We don't make that determination and let users decide whatever they want.

We show warning for 2 or more collections - that is not _arbitrary_ The actual impact depends on data and cardinality but the effect of so-called "cartesian product" starts at 2 collections. As mentioned above for 1 collection you inevitably have to repeat identifying columns of parents.

We cannot change current split query option because splitting even for 1 collection is what EF Core 2.x did and users wanted that back. So another option of splitting where first - parent query will have at least 1 collection loaded alongside (like how single query does) but other collections are loaded in split query. Though you also have very odd choices at that point, which 1 collection loaded together is best one to be added to parent (which depends on cardinality). I am not opposed to option, but it may be hard to understand for user and may not always give best results. We should collect more feedback from users.

**Comment by stevendarby** [comment]
@ajcvickers :( impression I got from last comment was to leave for feedback, but, if closing, that’s ok, but it was an enhancement proposal and not than a question.

**Comment by ajcvickers** [comment]
@stevendarby We discussed in triage and agreed that there was nothing new here that had not been discussed before. As always, we are always happy to get additional feedback, regardless of whether or not an issue is open.

`closed-question` is just a catch-all which means, "closed with no action to take."

**Comment by stevendarby** [comment]
Thanks for clarifying!

**Comment by stevendarby** [comment]
> [with one collection] We don't make that determination [between single or split] and let users decide whatever they want.

You kinda do make the determination. You do single query by default, and made big changes 3.0 to switch to that behaviour without an opt out. Yes, in 5.0 you allow the user to change this, but I still think a determination was made by EF Core that single is generally preferred hence the default. If you cannot defend single query as _generally preferred_ even for only one collection then one wonders why the change to single query was made at all. 

> So another option of splitting where first - parent query will have at least 1 collection loaded alongside (like how single query does) but other collections are loaded in split query. Though you also have very odd choices at that point, which 1 collection loaded together is best one to be added to parent (which depends on cardinality). 

Fwiw my proposal was not this, it was that under a new third option, query with 1 collection would be single query but a query with 2+ collections would be full split query behaviour- no complexity around loading one collection as single query and others separately.

**Comment by smitpatel** [comment]
If the point is that we make a decision, then yes, we do in order to provide users a workable query rather than putting them in decision making even with a starting query. The default behavior we went with is single query because of correctness of result in all scenario. We have whole discussion captured in the issue which decided to change default behavior to single query. So I don't think we are making any incorrect determination here or we are lacking some decision we should be making more than what we do.
