### ISSUE TITLE
Update ApplyConfigurationsFromAssembly to call non-public constructors

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#24748]
See https://github.com/dotnet/EntityFramework.Docs/issues/3207

It would be useful for `ApplyConfigurationsFromAssembly` to still use a parameterless constructor if there is one, even if it is not public.

Also, `ApplyConfigurationsFromAssembly` should warn if it finds a configuration that would be instantiated except that there is no parameterless constructor.

**Comment by Dr-Ogden-Wernstrom** [comment]
Hi @ajcvickers, I'm a noob interested in working on this.

I'm thinking pass binding flags into the `type.GetConstructor` call and instead of `continue` if a parameterless contructor isn't found, assign a bool.

Then, if `if (@interface.GetGenericTypeDefinition() == typeof(IEntityTypeConfiguration<>))` evaluates to true, if the aforementioned bool is true, log the warning and break out of the `foreach`.

Else, active a new instance with an additional parameters to include non-public constructor `Activator.CreateInstance(type, true)` and invoke target.

Looks like there's a nullable logger passed into the constructor's `modelDependencies` parameter. Maybe add a new logger extension method to perform the logging.

Does it sound like I'm thinking about things in approximately the right way?
