### ISSUE TITLE
Best Practice for Database per Customer and Blazor

### ISSUE THREAD

**Issue by wjvii** [dotnet/efcore#24759]
I am working on a Blazor application that uses a different database per customer, so I need to change the connection string per customer. For non-Blazor based applications I have successfully been using the technique discussed here: https://gunnarpeipman.com/aspnet-core-database-per-tenant/. The problem with Blazor is that I run into "System.InvalidOperationException: A second operation was started on this context before a previous operation completed." So, I tried using what I believe is the recommend method of using DbContextFactory and creating the new DbContext each time. However, when I did that, I ran into InvalidOperationException: Cannot resolve scoped service ‘Tenant.ITenantProvider' from root provider which is used to supply the Connection String for each customers database.

I have read on some ways to resolve the “cannot resolve scoped service from root provider” but most sound like or even recommend you do not use scoped services inside of singletons/transients.

So, my question is, for Blazor and Entity Framework Core, what is the recommended practice for handling per customer databases? 

Thank you in advance for any advice or recommendations.

**Comment by JeremyLikness** [comment]
Hi @wjvii,

The database factory default of `Singleton` works for most scenarios, but you can configure a different scope based on need. For example, if your users are in a specific tenant with its own connection, the options/settings must change per user or per scope. So, it's perfectly valid to register the factory as `Scoped` instead of the default `Singleton`:

```csharp
services.AddDbContextFactory<MultipleDbContext>((sp, opts) =>
{
   var tenantProvider = sp.GetRequiredService<TenantProvider>();
   opts.UseSqlServer(tenantProvider.GetTenantSpecificConnectionString());
}, 
   ServiceLifetime.Scoped);
```

If the user can switch tenants, you can make the factory `Transient` to re-evaluate the connection string each time.

I made an example app to reference: [Blazor EF Core Multi-tenant examples](https://github.com/jeremylikness/BlazorEFCoreMultitenant) that shows two strategies (one database and multiple databases).

Let me know if you still have questions or problems after reviewing this reply!

Regards,

Jeremy

**Comment by wjvii** [comment]
@JeremyLikness thank you for the quick reply. This is an awesome response and I believe it has put me on the right path. Thank you so much for the effort not only to reply but also to create the great examples.

I am working with the example now and adapting what you have shown me for my application. If I have any more questions, I will let you know.

Thank you again.
