### ISSUE TITLE
Ef Core default behaviour in replicated mode

### ISSUE THREAD

**Issue by kirinnee** [dotnet/efcore#24764]
Generic question since I am.not familiar with EF Core implementation:

If I have multiple instance of the same .netcore application connecting to the same database via ef Core, are there any pitfalls or gotchas I need to take note or configure?

Does EF Core cache the database? How is entity tracking affected? What's the recommended practice for running EF Core application in replicated mode?

**Comment by roji** [comment]
@kirinnee entity tracking is performed for each individual DbContext instance, of which there can be many at any given point in an application. So whether there are multiple instances of your application doesn't seem particularly important or relevant.

EF Core definitely does not cache the database. When you load entity instances with tracking queries, they are snapshotted as part of change tracking (to know what changes need to be saved when calling SaveChanges); but otherwise EF Core does not cache any data implicitly.

I can't think of anything else in particular, but can answer specific questions if you have any.
