### ISSUE TITLE
Query GraphQL with LINQ

### ISSUE THREAD

**Issue by Giorgi** [dotnet/efcore#24776]
I'm not sure whether this feature belongs to this project or not but I wanted to share my suggestion and a prototype I built.

## Problem:

Querying a GraphQL endpoint requires writing a string query that is neither strongly typed, nor checked by the compiler. As LINQ solved the same problem it would be cool to do use LINQ for GraphQL queries too.

## Solution

I have built a prototype called [GraphQLinq](https://github.com/Giorgi/GraphQLinq/) that generates strongly typed client from GraphQL API and allows writing graphQL queries like this:

```cs
var spaceXContext = new QueryContext();
var companySummary = spaceXContext.Company().Select(c => new CompanySummary
{
    Ceo = c.Ceo,
    Name = c.Name,
    Headquarters = c.Headquarters
}).ToItem();
```

This will generate a GraphQL query, run it and deserialize response in the corresponding class.

It supports quering nested properties and you can find more examples in the Readme of the project.

**Comment by roji** [comment]
@Giorgi we've had quite a few discussions around this internally - it's a fascinating subject and your project looks very interesting! Here are a few points that came up on this...

* Strawberry Shake (the client-side component of Chilli Cream/Hot Chocolate) uses code generation to produce a strongly-typed API from a GraphQL query. This is of course not the same as LINQ, but does solve the problem of compile-time checking and strongly-typed GraphQL client access. In general, with the advent of Roslyn source generators, the compile-time code generation approach seems to be gaining momentum in various scenarios (type-safe, zero runtime overhead, etc.)
* User surveys seemed to show that most users actually prefer to express queries in the GraphQL language, rather than having the LINQ abstraction over it. This would naturally include users who are already familiar with GraphQL (in other languages/platforms) and simply want to move to .NET; this also corresponds to the fact that most interested users seem to come from frontend programming, and are looking to do that rather than a backend service querying another backend service with GraphQL.
* A LINQ provider for GraphQL still could make sense, but there are a few "mismatches" between LINQ and GraphQL:
    * Since it's first and foremost a frontend-backend querying language, GraphQL is concerned with reducing over-fetching (transferring unneeded properties over the wire). LINQ's design by default makes it fetch entire objects, so in a way tends to nudge users into an over-fetching pit of failure; over-fetching can be prevented by projecting results out and selecting the desired properties, but this is an additional operation that has to be expressed on every query. FWIW I think this problem also exists to an extent when using LINQ to query databases.
    * One place where GraphQL really shines is **directives**: `@defer`, `@stream`, `@live` and similar allow fetching data beyond the single request-response paradigm, with specific bits of the response being delivered later in various ways. This isn't totally incompatible with LINQ, but once again requires a very specific kind of projection, e.g. to an anonymous type where the deferred bit would be represented as a `ValueTask<T>` (`@stream` could be an `IAsyncEnumerable<T>`). This again leads to always projecting out of your basic LINQ query (similar to the over-fetching problem above).
    * The constant projecting-out described above isn't an absolute blocker or anything, but imagine what things look like when you start to fetch nested types - this is quite an unwieldy way to express queries, compared to writing out GraphQL syntax.
    * LINQ is only about querying, but GraphQL also has the concept of mutations and subscriptions. Mutations could be implemented well in an EF Core provider (with change tracking and SaveChanges).

Although the above points seem somewhat "negative" on using LINQ for GraphQL, I do think a GraphQL LINQ provider is a very interesting direction and definitely worth exploring! Regarding EF Core, such a LINQ provider could be a standalone provider (unrelated to EF Core), or it could be an EF provider, in which case it would be able to leverage features such as change tracking and other additional functionality EF provides. 

/cc @JeremyLikness @michaelstaib

**Comment by Giorgi** [comment]
@roji Thanks for your insightful comments!

I'm familiar with Strawberry Shake and it does most of the problems that LINQ solves but I think both of these approaches will be useful for developers. The biggest LINQ advantage in my opinion is the LINQ syntax that most (if not all) .Net are familiar with. Also, with LINQ you have intellisense/discoverability but I'm not sure if Strawberry Shake has it.

Regarding mismatches, yes, I encountered those mismatches too when working on that project. The strategy that I use for fetching fields is to by default fetch only scalar/primitive properties and skip fields with nested properties or fields that are arrays. For those fields, you need to specify them either in `Select` or call `Include`:

```cs
var companyWithHeadquartersAndLinks = spaceXContext.Company()
                                            .Include(info => info.Headquarters)
                                            .Include(info => info.Links).ToItem();
```
But I agree that it fetching all fields by default may not be the best idea.

**Comment by roji** [comment]
> The biggest LINQ advantage in my opinion is the LINQ syntax that most (if not all) .Net are familiar with.

I agree - it's a matter of whether we're discussing .NET developers new to GraphQL and already familiar with LINQ, or developers coming from other ecosystems and already familiar with GraphQL. We seem to see more of the 2nd case, but there's definitely room for both approaches!

> Also, with LINQ you have intellisense/discoverability but I'm not sure if Strawberry Shake has it.

I know ChilliCream are working on VS integration, which would possibly add language support for the GraphQL syntax. Since Strawberry Shake code-generates types from GraphQL queries at compile-time, user code interacting with them should have Intellisense/discoverability; but of course the fine details are important here.

> The strategy that I use for fetching fields is to by default fetch only scalar/primitive properties and skip fields with nested properties or fields that are arrays.

Yeah, that's not a bad compromise and is what EF Core does as well for relational databases - by default all columns of a table row are fetched, whereas relationships need to be explicitly specified (with Include as well). I know GraphQL explicitly aims to reduce overfetching even at the property level (so the 1st one), which requires an explicit projection out; this doesn't kill LINQ to GraphQL in any way - just something to consider.

I'd also recommend looking at the different GraphQL directives, which are a very important part of the language (`@defer`, `@stream`...). As I wrote above, I think there are potential nice solutions for making these work in a LINQ provider, e.g.:

```c#
var companySummary = spaceXContext.Company().Select(c => new
{
    Ceo = c.Ceo,
    Name = GQL.Defer(c.Name),
    Headquarters = c.Headquarters
}).ToItem();
```

In the above snippet, we're projecting out name with a special `Defer` operator. It would return a `ValueTask<string>` (since the point of `@defer` is that the value may be returned later - but doesn't have to). Since the type of Name is now different, we can no longer project out to CompanySummary and must use an anonymous type instead; that seems somewhat awkward (especially in nested projection scenarios), but not a blocker.

As I wrote above - I'm personally pretty excited to see a .NET GraphQL LINQ provider! I wonder how far the approach can be pushed, and how many GraphQL features can be covered in a nice, idiomatic way. I'd be happy to continue discussing possibilities on this, do you want to move the discussion to your repo, or are you thinking specifically of an EF Core angle around this?

**Comment by Giorgi** [comment]
We can move to the project repo for more details. I opened it here because EF 6 plans mentioned GraphQL and wanted to bring the project to the ef team's attention.

**Comment by roji** [comment]
We're definitely interesting in anything GraphQL and .NET, thanks for opening this and for the discussion. Please don't hesitate to ping me or the rest of the team for anything.

**Comment by Giorgi** [comment]
@roji I opened a new issue to track `@defer` directive: https://github.com/Giorgi/GraphQLinq/issues/14
