### ISSUE TITLE
Optional relationship is not being tracking

### ISSUE THREAD

**Issue by ldsenow** [dotnet/efcore#24809]
Hi there,

I set the optional relationship property from null to a new object, however, the tracking status for the entity is still Unchanged.
Then when I save it, exception occured.

### Include your code

```
public class Contact : IEntityTypeConfiguration<Contact>
{
    public int Id { get; set; }
    public int? AddressId { get; set; }
    public Address Address { get; set; }

    public void Configure(EntityTypeBuilder<Contact> builder)
    {
        builder.ToTable("Contact");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.Id).UseIdentityColumn();
        builder.HasOne(x => x.Address);
    }
}

public class Address
{
    public int Id { get; set; }
    public string Location { get; set; }
}

var contact = context.Set<Contact>().First(x => x.Id == 123);

var address = new Address { Location = "...." };

context.Add(address);
context.SaveChanges();

contact.AddressId = address.Id;
contact.Address = address;

context.SaveChanges();
```

The AddressId is a nullable Foreign key (optional relationship).

The Addess is created without any issue. However the Contact's state is Unchanged for some reason. 

Then I see the exception bellow, 

Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: 'Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.'

### Include provider and version information

EF Core version: v3.1.9
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET Standard 2.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.9)

**Comment by ajcvickers** [comment]
There isn't enough information here for us to be able to understand the issue. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
