### ISSUE TITLE
Include with a view, some navigation properties are null

### ISSUE THREAD

**Issue by tovich37** [dotnet/efcore#24802]
Hello,

I have a problem when I include a view to my entity (the code is attached, with SQL script), some navigation properties are null.
The code: [EfCoreViewNull.zip](https://github.com/dotnet/efcore/files/6397250/EfCoreViewNull.zip)

## The schema (I use SQL Server)
**Table EfSub1**
- Id (int)
- Name (varchar(30))

**Table EfSub2**
- Id (uniqueidentifier)
- Name (varchar(30))

**View VI_EfView** (this view joins EfSub1 and EfSub2)
- Id (ex.: SUB1_10, SUB2_061CA753-CE1D-49AD-B23A-11102A071D80)
- OriginalId (ex.: 10, 061CA753-CE1D-49AD-B23A-11102A071D80)
- Name

Table EfTable
- Id (uniqueidentifier)
- ViewId (varchar(60))

## The code
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<EfView>(entity =>
    {
        entity.ToView("VI_EfView");

        entity.HasKey(e => e.Id)
            .IsClustered(false);
    });

    modelBuilder.Entity<EfTable>(entity =>
    {
        entity.ToTable("EfTable");

        entity.HasKey(e => e.Id)
            .IsClustered(false);

        entity.HasOne(e => e.View)
            .WithOne();
    });
}
```
```C#
// Use queryable to check the query
var queryable = _context.EfTable
    .Include(e => e.View)
    .AsQueryable();

var t = await queryable
    .ToListAsync();
```

**Generated query (is correct, and all records is joined, no null)**
```
SELECT [e].[Id], [e].[ViewId], [v].[Id], [v].[Name], [v].[OriginalId]
FROM [EfTable] AS [e]
LEFT JOIN [VI_EfView] AS [v] ON [e].[ViewId] = [v].[Id]
```
But if I check the navigation properties, some e.View are null:
```C#
var viewNull = t.Where(e => e.View == null); // Count = 14998
```
And, very strange, if I check the "ViewId" property, the same records are null:
```C#
var viewIdNull = t.Where(e => e.ViewId == null); // Count = 14998
```
### Provider and version information

EF Core version: 5.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer 5.0.5
Target framework: .NET 5.0
Operating system: Windows 8.1
IDE: Visual Studio 2019 16.8.2

Thank you!

**Comment by ajcvickers** [comment]
@tovich37 The `ViewId` FK column is used in a 1:1 relationship:

```C#
entity.HasOne(e => e.View)
            .WithOne();
```

However, examining the data shows that this column contains duplicate values:

![image](https://user-images.githubusercontent.com/1430078/117070542-b8538600-ace2-11eb-9bdf-c3c096e80ccd.png)

This means it's not appropriate for a one-to-one relationship since many table entities are related to each view. Try instead mapping as a one-to-many relationship:

```C#
entity.HasOne(e => e.View)
    .WithMany();
```

See [Relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key) in the documentation for more info.
