### ISSUE TITLE
Entity object not found in dbContext immediately after Add or AddAsync

### ISSUE THREAD

**Issue by changhuixu** [dotnet/efcore#24800]
### Ask a question

I have not found any related questions, which worries me. 
I guess most of you must have already had an answer or best practice.
Please help me understanding it. Thank you.

Note: 
Make a query before `SaveChanges()` does not return the just added entity object....

```C#
var student = new Student { Name = "a" };
await _dbContext.Students.AddAsync(student);
_logger.LogInformation($"{_dbContext.Entry<Student>(student).State}");    // Added
var a = await _dbContext.Students.FirstOrDefault(x => x.Name == "a");   // a == null
await _dbContext.SaveChangesAsync();
```

**Why `a` is NULL? How to make sure the just added entity is in dbContext?**

This happens when I do the `SaveChanges()` in the end of two services call.

EF Core version: 3.1.13
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET Core 3.1
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by ajcvickers** [comment]
@changhuixu EF Core always executes queries against the database and results returned reflect the entities stored in the database. Since the Added entity does not yet exist in the database it is not returned. See [Accessing Tracked Entities](https://docs.microsoft.com/en-us/ef/core/change-tracking/entity-entries) for more information.
