### ISSUE TITLE
Error when using ExecuteSqlRaw for DELETE with parameter passing the value

### ISSUE THREAD

**Issue by alexandre-trapp** [dotnet/efcore#24810]
Hello, following error when passing the parameter with value to delete a table, with Microsoft.EntityFrameworkCore 5.0.2.

![image](https://user-images.githubusercontent.com/42077703/116691494-3fc29180-a991-11eb-9aac-66d1d7a3326c.png)
![image](https://user-images.githubusercontent.com/42077703/116691522-46510900-a991-11eb-9cb9-ce2b6fc6ce56.png)

By placing the parameter name with the same column name, is executing WHERE mestre_mapa_id = mestre_mapa_id under the table, excluding all data from the table, as if it were WHERE `mestre_mapa_id = mestre_mapa_id`:
![image](https://user-images.githubusercontent.com/42077703/116691600-67b1f500-a991-11eb-9497-0fbc5590ece5.png)

It only works by passing the parameter as NpgsqlParameter, but I believe that the above scenario gives rise to many errors:
![image](https://user-images.githubusercontent.com/42077703/116691909-e5760080-a991-11eb-934f-f4983ce5a574.png)

**Comment by ArminShoeibi** [comment]
Hello, if you want to pass parameters to your SQL statement please use ExecuteSqlInterpolated or ExecuteSqlInterpolatedAsync

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlinterpolated?view=efcore-5.0

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlinterpolatedasync?view=efcore-5.0

**Comment by alexandre-trapp** [comment]
I understand the answer, but I wonder how is the database cache that uses parameters bindings, since the interpolated sql will always vary;
And I am also concerned that ExecuteSqlRaw does not throw an exception at least when trying to use @field_name and the value of the field in the parameter, causing this delete from table where field_name = field_name.

**Comment by roji** [comment]
> I understand the answer, but I wonder how is the database cache that uses parameters bindings, since the interpolated sql will always changes;

The SQL does not change. When properly using parameters, your SQL always contains a fixed placeholder (e.g. `@mapaId`), and a DbParameter is sent outside of the SQL with the parameter value; only the DbParameter changes.

>  And I am also concerned that ExecuteSqlRaw does not throw an exception at least when trying to use @field_name and the value of the field in the parameter, causing this delete from table where field_name = field_name.

This is an Npgsql behavior. When you specify a parameter placeholder that doesn't match to an actual parameter, Npgsql will leave the placeholder as-is in the SQL (since there may be a chance it falsely identifies something as a placeholder in its SQL parsing). Unfortunately, PostgreSQL interprets `@x` as `x` (e.g. `select * from foo where id = @id`).

Note that you don't have to use ExecuteSqlInterpolated to properly parameterize your raw queries. ExecuteSqlRaw can also do that, but not with named parameters. It's recommended to carefully read [the documentation on this](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters).

**Comment by alexandre-trapp** [comment]
Nice, thanks for answer.
