### ISSUE TITLE
[Bug] - [Required] attribute ignored when creating column named Id

### ISSUE THREAD

**Issue by omnilogix** [dotnet/efcore#24821]
When creating a new database using EnsureCreated(), a column with the name Id is created as nullable even though the required attribute is placed on the property.  I believe this is due to it being in a derived class with the Primary Key annotated in the base class.  Perhaps the order of property evaluation affects the outcome.

```
  public class MyBaseClass
    {
        [Key]
        public int MyKey { get; set; }
    }

    [Table("Test")]
    public class MyDerivedClass : MyBaseClass, IEntityTypeConfiguration<MyDerivedClass>
    {
        [Required]
        public string Id { get; set; }

        
        void IEntityTypeConfiguration<MyDerivedClass>.Configure(EntityTypeBuilder<MyDerivedClass> builder)
        {
            _ = builder.HasKey(x => x.MyKey);
            _ = builder.HasIndex(x => x.Id).IsUnique();
        }
    }
```
![image](https://user-images.githubusercontent.com/9586533/116820157-60711f80-ab28-11eb-8e52-be1f78233813.png)

With the above definition, a table is created with an auto-generated primary key "MyKey" and a nullable column "Id"

**Comment by roji** [comment]
Since you're using the Table-Per-Hierarchy (TPH) inheritance mapping strategy, both MyBaseClass and MyDerivedClass are mapped to the same table. And since Id only exists in MyDerivedClass, the column must be nullable for rows, since it must contain null for rows mapped to MyBaseClass.

[See the docs on inheritance mapping](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#entity-type-hierarchy-mapping) and specifically the note on column nullability.

**Comment by omnilogix** [comment]
@roji - Thanks for the clarification.  I find the convention rather counter-intuitive since the base class will never represent a table in my schema.  Perhaps the convention could be modified so that if the base class is marked abstract, the derived class would be treated as a single concrete class?

For others facing this issue, the nullable column behavior can be overridden as follows:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            foreach (var property in modelBuilder.Model.GetEntityTypes()
                                                       .SelectMany(t => t.GetProperties())
                                                       .Where(p => p.Name == "Id"))
            {
                property.IsNullable = false;
            }

            base.OnModelCreating(modelBuilder);
        }
```

**Comment by roji** [comment]
We could in theory not make the column nullable in the scenario of a single concrete type, inheriting from a single abstract type; the moment there's a second concrete type in the hierarchy, the column would again (most likely) need to be nullable. So this seems to be quite the edge case for not making the column nullable.

**Comment by omnilogix** [comment]
@roji - So I changed the the test case as follows and still get the same result.  The intended column definitions are quite clear using attributes, also the base class is not part of the schema, so why does this not work?  Thanks

```
  public class MyBaseClass
    {
    }

    [Table("Test")]
    public class MyDerivedClass : MyBaseClass, IEntityTypeConfiguration<MyDerivedClass>
    {
        [Key]
        public int MyKey { get; set; }

        [Required]
        public string Id { get; set; }
        
        void IEntityTypeConfiguration<MyDerivedClass>.Configure(EntityTypeBuilder<MyDerivedClass> builder)
        {
            _ = builder.HasKey(x => x.MyKey);
            _ = builder.HasIndex(x => x.Id).IsUnique();
        }
    }
```

 `       public DbSet<MyDerivedClass> Test { get; set; }`

**Comment by omnilogix** [comment]
@roji - For context, I am porting a rather large project From EF 6 via edmx.    Without the magic of T4 templates, the amount of code to copy into each POCO is not reasonable to maintain without inheritance from a base class.  As long as the base class does not have EF mapped properties, I think it would be a great benefit to myself and others to be able to inherit without unexpected side effects.  Maybe introduce a class attribute [EFInherit]?  Not really sure how to best solve this, but there will surely be a lot of devs moving to EF core in the years to come...

**Comment by roji** [comment]
@omnilogix the fact that MyBaseClass doesn't have any properties doesn't really change anything - it is still part of your model (as the base type for MyDerivedClass), and so at least in theory there may be rows in the table mapped to it.

You're probably looking to not map MyBaseClass at all; this can be done by specifying `modelBuilder.Entity<Subblog>().HasBaseType((Type)null)` in your OnModelCreating (see the tip under [this section in the inheritance docs](https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#entity-type-hierarchy-mapping)). You can also write code in OnModelCreating that automatically locates all subtypes of MyBaseClass and configures them in this way.

**Comment by ajcvickers** [comment]
`HasBaseType` should not be needed in this case. Just don't include the base type in the model. Typical ways the base type is included in the model:

* Having a `DbSet` property for the type
* Having a call to `ModelBuilder.Entity` for the type
* Having an `IEntityTypeConfiguration` for the type
* Referencing it from another type in the model

Since there isn't full repro code here I can't tell which of these is being used. If you are not doing any of these things and the type is still included, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by omnilogix** [comment]
@ajcvickers - I have attached a demo project.  The specific issue I am experiencing turns out to be related to the order in which the properties are defined in the derived class.   Id then Key = Id Nullable.   Key then Id = Id not nullable.
[EF_Demo1.zip](https://github.com/dotnet/efcore/files/6419241/EF_Demo1.zip)

**Comment by roji** [comment]
This indeed looks like a bug, and has nothing to do with inheritance - see the minimal repro code below.

The problem seems to be that Id is initially discovered as the primary key by convention, and then later, when another property is configured as the key, Id is removed as the key (InternalEntityTypeBuilder.HasNoKey), at which point its requiredness is also set to null, and so the attribute gets ignored.

Seems to be a dup (or part) of #15898, /cc @AndriySvyryd.

<details>
<summary>Minimal repro</summary>

```c#
using var ctx = new BloggingContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer("Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .EnableSensitiveDataLogging()
            .UseLoggerFactory(ContextLoggerFactory);
}

public class Blog
{
    //**** Leave the order of these properties (Id, RecKey) and Id will NULLABLE
    //**** Change the order of these properties (RecKey, Id) and Id will be NOT nullable

    [Required]
    public string Id { get; set; }

    [Key]
    public int RecKey { get; set; }
}
```
</details>

**Comment by roji** [comment]
@omnilogix as a workaround, you can either change the order of the properties as you've done, or change the name of the Id property, this way EF doesn't initially configure it as the key by convention.
