### ISSUE TITLE
property marked as modified but value is same due to precision

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#24865]
I've an Entity with a Property that is decimal and has a precision set e.g. 

    builder.Property(x => x.MyProperty).HasPrecision(9, 3);

    decimal myValue = 1.2345678M;

Then the following:

            using (var db = new MyDatabaseContext())
            {
                var entity = db.Entities.Add(new Entity { Id = id });
                entity.MyProperty = myValue;
                db.SaveChanges();
            }

            using (var db = new MyDatabaseContext())
            {
                var entity = db.Entities.Single(x => x.Id == id);
                entity.MyProperty = myValue;
                var entry = db.Entry(entity);
                var estate = entry.State; // also modified but ok maybe something else changed?
                var pstate = entry.Property(x => x.MyProperty).IsModified; // why true?
                db.SaveChanges();
            }

I need to detect that because of the precision it didn't change. I know it changed because 1.235 != 1.2345678. But it doesn't update the value in the database because of the precision. How to check on the entry.Property(x=>x.MyProperty) that it's not actually changing the data when precision is included?

**Comment by ajcvickers** [comment]
@qsdfplkj By default, EF Core compares primitive types using the normal comparisons for those types in .NET. This means that a truncated decimal will be detected as different from an non-truncated decimal. Rather than change this, I would suggest that the application truncate data as part of business rules, rather than allowing the database to truncate values when being written. However, if you don't want to do that, then you could use a [value comparer](https://docs.microsoft.com/en-us/ef/core/modeling/value-comparers?tabs=ef5) to change the comparison so that truncation is taken into account.

**Comment by qsdfplkj** [comment]
the value comparer looks promising
