### ISSUE TITLE
Generate compiled relational model

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#24896]
- Override methods that throw for a runtime model
- Add tests that assert the relational model, view, query mapping and default mappings in the compiled model.

Related to https://github.com/dotnet/efcore/issues/20284

**Comment by ZvonimirMatic** [comment]
Hi, would it be possible to add an optional parameter in the `Optimize-DbContext` that signals not to generate relational model? Currently the process of generating compiled model takes a lot of time (I guess because the program needs to write a huge file). It takes a long time even without this, but now it takes me like 20 minutes to generate a compiled model. I also need to open up the *ModelBuilder.cs file in another program and delete the method every time.

**Comment by AndriySvyryd** [comment]
@ZvonimirMatic Yes, that is tracked in https://github.com/dotnet/efcore/issues/33483#issuecomment-2071137500
