### ISSUE TITLE
Lazy Loading Proxies and DbContextFactory look incompatible for blazor server

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/efcore#24916]
1. Consider a SPA
2. There is a root object "ROOT" and it has multiple related entities "RELATE1", "RELATE2" etc, which in turn have related entities. "GRANDRELATE1" "GRANDRELATE2" etc.  Think of it as a tree. 
3. The page shows certain properties of ROOT and then properties of RELATE1 etc. On the selection of "RELATE1", depending on the selected value, it shows "GRANDRELATE1" values. (Think of a master-detail view). This is achieved by having a corresponding view/edit component: ROOTCOMP/RELATE1COMP/GRANDRELATE1COMP  
4. Earlier, one could fetch the ROOT object and pass on its related entities and then let the entities further down filter out the entities it wanted to show, *without* the root component knowing exactly which entities would be required/modified by the child components. This meant that the corresponding DbContext was kept 'alive'. This is fine because the updates are few and the users can live with concurrency exceptions. 
5. Now, with DbContextFactory, the context is disposed of as soon as ROOT is fetched. Any child component trying to fetch related entities of ROOT get an exception because the context has been disposed of. _(An error was generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.LazyLoadOnDisposedContextWarning': An attempt was made to lazy-load navigation *ROOT* after the associated DbContext was disposed. This exception can be suppressed or logged by passing event ID 'CoreEventId.LazyLoadOnDisposedContextWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.)_
6. There are two workarounds: 
    a. Use eager loading, which entails loading the entire graph starting with ROOT
    b. Not use eager loading and let each component load the related entities upon initialization. (Preferable)
7. In either case, lazy loading cannot be used.

Ideally, lazy loading proxies should create their own context from the context factory to lazy load further data.

**Comment by ajcvickers** [comment]
In general, we consider it an anti-pattern to capture a service reference in an entity. This is particularly true when that entity then survives the scope of that service. This means that lazy-loading is in-effect, an anti-patterns because of this. (There are also other reasons to consider it an anti-pattern.)

If you do want to use lazy-loading, then you will need to manage the scope of the DbContext instance appropriately. How to do this is really dependent on the architecture of your application. I don't think we can provide any good guidance on this without it suggesting things we would consider bad practice, such as a long-lived ambient DbContext instance.

/cc @JeremyLikness who has done a lot of work on EF Core use in Blazor.

**Comment by JeremyLikness** [comment]
@mayur-ekbote the intended purpose of the factory is to create transient instances with your desired configuration managed by DI (otherwise you could just use new and configure the options builder yourself). If you want to manage a context for longer, I recommend not using the factory but registering a context with the appropriate scope. With Blazor Server you have to be careful because you can lose server state, and the context is not thread safe so if the user opens multiple tabs and you are sharing the same context it will create conflicts. I would either create a service to manage your context as a wrapper or consider a disconnected entity approach. 

Here is more information on:

- [EF Core and Blazor Server](https://docs.microsoft.com/aspnet/core/blazor/blazor-server-ef-core)
- [Disconnected entities](https://docs.microsoft.com/ef/core/saving/disconnected-entities)
- [Managing the lifetime of your DbContext](https://docs.microsoft.com/ef/core/dbcontext-configuration/) 

Thanks!

**Comment by mayur-ekbote** [comment]
Thanks, @JeremyLikness ! That clears up things. Safe to conclude that the use of LazyLoadingProxies is avoidable with the Blazor server?
