### ISSUE TITLE
AddAsync vs. Add in async methods

### ISSUE THREAD

**Issue by matthiaslischka** [dotnet/efcore#24921]
The [official documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.addasync?view=efcore-5.0) on `AddAsync` says:

> This method is async only to allow special value generators, such as the one used by 'Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy.SequenceHiLo', to access the database asynchronously. For all other cases the non async method should be used.

So we should use `Add` instead of `AddAsync` when no "special value generators" are used? To me [and others](https://stackoverflow.com/questions/47135262/addasync-vs-add-in-ef-core) this is a bit confusing. It feels wired to not use `AddAsync` in an `async` method.
What falls under "special value generators" and what would happen when you use the synchronous `Add` in those scenarios?
I would tend to just always use `AddAsync` and be on the save side, but the documentation clearly advises to use `Add`.

Could you maybe elaborate on the background a bit and help me/us understand this better?
Many thanks!

**Comment by roji** [comment]
Unless you use a value generator which performs I/O - such as SequenceHiLo as documented above - adding an entity won't ever perform any I/O operation. As such, there's no advantage in calling AddAsync over Add, only a slight performance overhead due to the async state machines involved.

If you feel more comfortable using AddAsync, that shouldn't be a problem, but it isn't needed either.

**Comment by roji** [comment]
The perf overhead of a synchronously-returning async method (over the analogous synchronous one) is very likely negligible in the vast majority of cases, so I wouldn't go into it in the docs. The current wording may be a strong, but I think the guidance is still correct...
