### ISSUE TITLE
Repository and uow in ef core

### ISSUE THREAD

**Issue by asgharb** [dotnet/efcore#24920]
Hi.
Is Repository and UoW an anti-pattern in Ef Core ?

**Comment by roji** [comment]
@asgharb that is a very general question without a single answer - you'd have to go into concrete details of what specific usages you're thinking of, etc.

EF Core's DbContext itself implements the unit-of-work pattern; you typically use a single DbContext instance to load data from the database, modify it, and then save changes back to the database. An additional layer implementing UoW is typically not needed when working with EF Core (although again, this is just a general statements).

Wrapping a DbContext in a repository layer is sometimes useful, e.g. to separate business logic from database code, and so to mock the latter in order to test the former. Once again, it's not necessarily recommended to add a repository layer as a matter of principle - make sure you know why you're doing it. In many cases, just coding against DbContext - and possibly adding methods to it - is quite sufficient.
