### ISSUE TITLE
How to avoid  entity framework  generate  sub query's T-SQL

### ISSUE THREAD

**Issue by weiwangda2014** [dotnet/efcore#2501]
in my project，i found entity framework is not necessary that sometimes generate T-SQL contain  sub query, but generate T-SQL contain many  sub query. so,i want to know that  how to avoid  entity framework  generate  sub query?

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._


Could you share your model and the LINQ query in question along with the SQL being generated and what you would like to see improved in the SQL.
