### ISSUE TITLE
Simplify calls to date nested in strftime

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#25027]
For example, `strftime('%Y', date($date, '2 years'))` can be simplifed to `strftime('%Y', $date, '2 years')`.

(originally https://github.com/dotnet/efcore/pull/24989#discussion_r643326391)

**Comment by bricelam** [comment]
**Note to implementor:** This requires updating the logic inside SqliteExpression.Strftime to handle `date` in addition to `strftime`:

https://github.com/dotnet/efcore/blob/e7c0b9de29904a8bc0b59aba3458c75d05d6f9fb/src/EFCore.Sqlite.Core/Query/Internal/SqliteExpression.cs#L44-L55

We should also think about whether it's possible to get nested `date` functions.

**Comment by jhowlett-scottlogic** [comment]
Is anyone working on this?

**Comment by jhowlett-scottlogic** [comment]
Sorry @bricelam but i have looked into this task more deeply and have found it to be above my experience level with efcore. Because of this i don't feel like i should take on this issue as i do not fully understand the repository and may not take everything required into account when designing a solution.

 I hope you find someone to take on this task soon!

**Comment by bricelam** [comment]
@jhowlett-scottlogic No worries. But also feel free to ask us questions; we're always eager to help contributors get started. We have a few docs like [How to contribute](https://github.com/dotnet/efcore/blob/main/.github/CONTRIBUTING.md) and [Getting and Building the Code](https://github.com/dotnet/efcore/blob/main/docs/getting-and-building-the-code.md), but I'm sure we could use more.
