### ISSUE TITLE
Query: Translate Math.PI

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#25049]
See https://github.com/dotnet/efcore/pull/24829#issuecomment-832134743

**Comment by Marusyk** [comment]
I will try to prepare a PR for this

**Comment by smitpatel** [comment]
In the associated PR, we came to know that `Math.PI` is inlined as a constant value inside expression by C# compiler directly. This makes us never see `Math.PI` member expression in tree itself so this is not something we can interpret and translate. The constant value will always be sent to server as constant, as we receive it from C# compiler.

**Comment by bricelam** [comment]
Crazy idea: Replace `Expression.Constant(Math.PI)` with `Expression.MakeMemberAccess(null, typeof(Math).GetField("PI"))` in the preprocessor. Obviously, this would catch any constant that happens to equal .NET's approximation of PI, but is that really an issue?

If we do this, we should also do it for `E` and `Tau`.

**Comment by roji** [comment]
Technically the complication is even before ParameterExtractingEV (funcletization) - [as above](https://github.com/dotnet/efcore/issues/25049#issuecomment-876887234) since Math.PI is a constant, the incoming expression tree doesn't even contain it, only the inlined constant value. So I think there's really nothing we can do here, even in theory.
