### ISSUE TITLE
Add source index build step

### ISSUE THREAD

**Issue by davidfowl** [dotnet/efcore#25096]
See https://github.com/dotnet/runtime/pull/46823 for more details. This allows EF core to show up in https://source.dot.net/

cc @alexperovich 
cc @bricelam

**Comment by dougbu** [comment]
@bricelam this change looks straightforward and is something we should do together w/ dotnet/aspnetcore#33534. @dotnet/aspnet-build should make short work of it.

**Comment by bricelam** [comment]
`enableRichCodeNavigation` *and* `source-index-stage1.yml`?? Doesn't seem very DRY... :trollface:

**Comment by alexperovich** [comment]
To simplify this change, if the repo uses eng/common/templates/jobs/jobs.yml, you can just set the "enableSourceIndex" parameter there. If the code to be indexed gets built by default with eng/common/build.ps1, then you can stop there. Otherwise the sourceIndexBuildCommand value in the sourceIndexParams parameter will need to be set to the command that will produce a binlog containing builds of all the projects to be indexed.

**Comment by AndriySvyryd** [comment]
This is done from the EF side. Opened https://github.com/dotnet/source-indexer/issues/116 to track the remaining work.
