### ISSUE TITLE
[dotnet counters] Query Cache Hit Rate (%) is NaN

### ISSUE THREAD

**Issue by iam-black** [dotnet/efcore#25142]
Hi,
after service start I am getting Query Cache Hit Rate (%) : NaN.
![Screenshot 2021-06-24 020752](https://user-images.githubusercontent.com/8601553/123180713-7d74ff80-d494-11eb-9d6e-2e7745fd1ebf.png)

It's not a problem by itself by it makes impossible to build dashboards in Kibana without additional logstash processing.
![Screenshot 2021-06-24 020828](https://user-images.githubusercontent.com/8601553/123180880-d6dd2e80-d494-11eb-8811-aff7093cf7a4.png)

The problem is with _EntityFrameworkEventSource.CalculateAndReset()_ calculation formula when _clone.Hits + clone.Misses = 0_ which results in division by zero.
![Screenshot 2021-06-24 020904](https://user-images.githubusercontent.com/8601553/123181045-2ae81300-d495-11eb-9ce6-60116e750c95.png)

EF Core version: 5.0.4
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL 5.0.2
Target framework: .NET 5.0
Operating system: aspnet:5.0-alpine
IDE: Rider 2021.1.3

**Comment by stevendarby** [comment]
Hi, I'm using event counters for the first time in EF Core 5.0 and getting this issue. I understand this bug was fixed for 6.0 but the circumstances in which it appears in 5.0 aren't clear to me from this issue. The PR comment suggests "NaN" shows when there is "no data in query cache event counter." Why is there no data, what does this suggest about the app? Does it suggest no queries are being cached? Any more info would be greatly appreciated.

**Comment by stevendarby** [comment]
@roji using latest daily build I get -1 instead of NaN in a minimal repo, but I'm still not sure why it's -1. Let me know if I should raise a new issue if this is distinct.

Minimal repo:
```C#
using System;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Linq;

Console.WriteLine(Process.GetCurrentProcess().Id);
Console.ReadKey();

using var db = new MyDbContext();
db.Database.EnsureCreated();
_ = db.Tests.FirstOrDefault();
_ = db.Tests.FirstOrDefault();
_ = db.Tests.FirstOrDefault();

Console.ReadKey();

public class MyDbContext : DbContext
{
    public DbSet<Test> Tests { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=.;Database=Counters;Integrated Security=True");
    }
}

public class Test
{
    public int Id { get; set; }
}
```
Values when waiting for the final key read:
![image](https://user-images.githubusercontent.com/41150696/132211899-6d37a213-d963-431b-8410-6729f2e85501.png)

**Comment by ajcvickers** [comment]
@roji I'm also curious why the output is -1 in the case above.

**Comment by stevendarby** [comment]
Bit of extra info to add which I didn’t notice at first, but you can actually see “66.67%” (the expected value) flash up briefly before it goes back to -1.

I did try to delve into the code and it looks like it resets the counts every time it reads it. I didn’t spend long enough to get my head around it fully and suspect there could be reasoning behind resetting occasionally otherwise you would never see the “100%” you hope to see, as the first use of any query will always be a “miss”. But perhaps it resets too frequently. I am just speculating.

I was going to raise a new issue following a few more days grace as not sure if notifications work on closed items :D

**Comment by roji** [comment]
Sorry for taking a while to look at this.

The "query cache hit rate" counter is calculated for each sampling interval, much like "Queries per second", so if no queries have been executed in the interval (1 second by default), -1 should be the right result. This is why you briefly saw 66.67%, before the counter got reset again to -1 (because presumably no further queries were executed).

We could consider adding a counter that provides the percentage from process start, which is probably what you were expecting. However, note that this counter is specifically useful for detecting ongoing query compilation, which is a perf problem which frequently occurs as a result of bad dynamic query generation ([see the docs](https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-constant#dynamically-constructed-queries)). In other words, I'm not too sure if a statistic of "query cache hit rate from process start" is actually interesting/actionable.

Hope that's clear - would be good to have any feedback on the above to know what your needs are.

**Comment by stevendarby** [comment]
Thanks for taking a look at this @roji.

I think there might be a documentation issue here at least. The sample interval you mentioned isn’t in the current documentation or label, so even if it wouldn’t be interesting/actionable to be measured from process start, I think that would be most people’s reasonable interpretation, especially when it’s compared to the example you gave - “Queries per second” - which is explicit about the interval. 

FWIW the way I planned to use it was to call one of my application’s APIs with different params, which would generate dynamic LINQ queries with those params, and then check the hit rate was as expected. I expected to have to adjust for initial misses (e.g. in the simple repro above, 66.67% is the outcome I’d hope for). 

I can definitely see that having these stats reset at certain intervals would be useful, but I can’t see how doing this every second is usable, and would be interested to know how you expected this to be used. If you’re thinking about it being plugged into a live system with high traffic, I can see how that might provide a constant cache hit rate, but would also fi Often it might take that long to switch between applications / tools, I don’t think having to race to view them before they disappear is a good UX. Therefore my suggestion would
be make the default interval is a larger value and/or ensure the documentation makes it clear how to adjust the default.

**Comment by roji** [comment]
> I can definitely see that having these stats reset at certain intervals would be useful, but I can’t see how doing this every second is usable [...]

The 1-second interval is determined externally by the tool you use to poll for the counter data. For example, if you're using [`dotnet counters monitor`](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters#dotnet-counters-monitor), you should be able to control that via the --refresh-interval switch.

> [...] and would be interested to know how you expected this to be used. If you’re thinking about it being plugged into a live system with high traffic, I can see how that might provide a constant stream of cache hit rates, but it would also be hard to locate the source of any issues without a more careful approach of the type I described above.

Yes, the general expectation for event counters is for them to be used on live systems with generally high traffic; the data is meant to be continuously monitored/charted, providing an insight into production system health. In a sense, the cache hit rate isn't very different from queries-per-second or any of the other non-cumulative counters: they go up and down based on your system's state at that approximate moment. In general, the counters aren't really meant to help you pinpoint exactly which query is producing the problem, since they provide a quantitative, aggregate snapshot; but they help you understand that you do have a problem, and at that point you're supposed to use other means (e.g. tracing/logging) to pinpoint the exact source.

I do agree [the docs](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/event-counters?tabs=windows#counters-and-their-meaning) can be improved on this, opened https://github.com/dotnet/EntityFramework.Docs/issues/3428 to track that.

**Comment by stevendarby** [comment]
Thanks @roji, that answers most of my questions and concerns. I’m mainly interested in finding potential cache issues with complex/dynamic queries at development time; sounds like event counters are not the best tool for that, but your tip for tweaking the refresh interval could help. Otherwise I’ll look into other ways to find that out in logs/traces.

**Comment by roji** [comment]
@stevendarby you can listen for the LogQueryExecutionPlanned event, which EF emits every time it compiles a query (you can do this via logging, or a DiagnosticSource). This should allow you to get a clear, simple event every time query 
compilation occurs.

**Comment by mu88** [comment]
Just FYI: this `-1` was a little bit nasty as you can read [here](https://mu88.github.io/2023/03/13/EF-Core-query-cache.html) 🙂

**Comment by roji** [comment]
@mu88 thanks for that feedback (and for the writeup in general). It would maybe make sense to just default to 100% instead of -1 of NaN...
