### ISSUE TITLE
Suggestion. Use a stable sorting algorithm

### ISSUE THREAD

**Issue by mikhail-khalizev** [dotnet/efcore#25228]
Suggestion. Use a stable sorting algorithm when forming the sequence of command for insert and updating entities.

https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs#L81

```diff
- independentCommandSet.Sort(_modificationCommandComparer);
-
- var batch = _modificationCommandBatchFactory.Create();
- foreach (var modificationCommand in independentCommandSet)
+ var independentCommandSetSorted = independentCommandSet.OrderBy(x => x, _modificationCommandComparer);
+
+ var batch = _modificationCommandBatchFactory.Create();
+ foreach (var modificationCommand in independentCommandSetSorted)
```

**Comment by mikhail-khalizev** [comment]
This change allows to solve https://github.com/dotnet/efcore/issues/11686

**Comment by AndriySvyryd** [comment]
Did you perform any testing that would show that this change would make any difference?

However, even if it would, we shouldn't depend on the implementation of a given method if it's not part of the contract, since it could change in the future.

Instead https://github.com/dotnet/efcore/blob/ac2bb48b10ecf1289b568a94b7a35e8075c6d787/src/EFCore.Relational/Update/Internal/ModificationCommandComparer.cs should be changed to compare keys on inserted entities too. This will reflect the order in which they were added to the change tracker.

**Comment by mikhail-khalizev** [comment]
Yes, I did some testing, this change works.

But your approach (change ModificationCommandComparer) will be better.
