### ISSUE TITLE
Two Letter Acronyms naming convention vs DbContext

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/efcore#25235]
According to the convention below, DbContext should be called DBContext instead. Or is it based on a newer naming convention?

> Do capitalize both characters of two-character acronyms, except the first word of a camel-cased identifier.

https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229043(v=vs.100)#capitalization-rules-for-acronyms

EF Core version: All

**Comment by ajcvickers** [comment]
@PingPongSet 

1. Db is not an acronym, since Database is one word.
2. The Db types in EF were chosen to align with the existing Db types in ADO.NET--for example, DbConnection.
3. The convention referenced above is dumb. (My opinion)
4. Db is actually short for Don Box. (Long-running internal joke.)
5. All of this was discussed at length in 2010 or thereabouts and there is no point discussing it anymore since, whatever anyone's opinion is, it won't change.

**Comment by PingPongSet** [comment]
The intention of the OP is not to change, but to understand why, so I can decide what to use in my project.

Do you have a link to the summary of the discussion below?
`All of this was discussed at length in 2010 or thereabouts and there is no point discussing it anymore since, whatever anyone's opinion is, it won't change.`

**Comment by ajcvickers** [comment]
@PingPongSet The discussion is summarized in points 1 through 5 above.
