### ISSUE TITLE
Are you using (and how do you use) the Entity Framework Designer/EDMX?

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/efcore#25248]
Do you and/or your team use the Entity Framework designer on a regular basis? The designer is the editor for EDMX files that is built right into Visual Studio. The EF Core team would like to understand:

- How you are using the designer today, i.e. just viewing models vs. customizing each release.
- If you have plans to migrate to EF Core and how we can help.
- What obstacles you may be facing.
- If you are aware of visualization alternatives like EF Core Power Tools or Entity Framework Visual Designer.

Please feel free to leave details in the comments for this issue, or reach out to me to set up time for a quick chat. 

Thank you!

**Comment by a11smiles** [comment]
@JeremyLikness for me, because I prefer code-first, but I'm a _visual designer_, I will typically create a side project (most of the time in the same solution, but sometimes in another solution) that contains the EDMX. I can then draw/design the model and visually collaborate with the team.  Once there's consensus, I'll return to my code-first project and implement the design changes.

Unfortunately, since I now use VSCode more than VSEnt (and I _very seldom_ use Windows for development), I use [NaviCat Data Modeler](https://navicat.com/en/products/navicat-data-modeler) and just save the model in an `/assets`-type folder within my project's repo.

I wish VSCode had a modeler extension. :(

**Comment by JeremyLikness** [comment]
Closing as further feedback can come through the [porting guide](https://docs.microsoft.com/ef/efcore-and-ef6/porting/).
