### ISSUE TITLE
AsSplitQuery + paging with ordering containing duplicates

### ISSUE THREAD

**Issue by eh-torkaman** [dotnet/efcore#25260]
## File a bug

when using .Include to load some child table with  .skip(n).take(n) and .AsSplitQuery()  the translated query for fetching rows 
of child table has a subquery  which is  **assumed** to return  correct set of result (same set as before) BUT imagine condition where there  are more than one plausible sub set for the main query base on the exact same query (after sorting base on some fields and take top 10 rows there might be more than one possible outcome - all of the rows have same rank ) then the subquery in the .Include might return different set of results ( which happened to me - may be because of sql query optimizations ... )
of course its always possible to add order by some unique field to fix the problem but its not obvious

## Possible fixes

EF by default adds sort/order by base on primary key of main table 
or 
 may be the subquery in ".Include"  uses foreign key of returned set

**Comment by smitpatel** [comment]
EF by default cannot add sorting since adding any additional ordering increases the perf. See https://github.com/dotnet/efcore/issues/19828 The additional term will only be useful **iff** the ordering + paging combination has duplicates crossing the paging boundary. It is not possible for EF Core to figure out it is the case without looking at data, so we cannot add ordering optionally only when needed either.

Since this is purely manifest due to the query & data combination, user should make sure that their ordering terms at least has one unique term when applying paging or not use split-query.
