### ISSUE TITLE
Skip database schema migration step based on condition

### ISSUE THREAD

**Issue by AnFa1978** [dotnet/efcore#25276]
During executing of database schema migration in Azure DevOps pipeline I want skip for one environment one auto generated migration step. Usually calling Microsoft.EntityFrameworkCore.Migrate() will take all migration Up and Down methods and execute. But I am looking for mechanism to exclude one migration step based on environment. Please share your ideas how I can solve this? Thanks

**Comment by roji** [comment]
@AnFa1978 you can always [edit your scaffolded migration code](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#customize-migration-code) and add whatever check you want, e.g. do nothing if a certain environment variable is defined. However, note that EF Core will still record that the migration has been applied in the database (so that it doesn't attempt to reapply it in the future).
