### ISSUE TITLE
EntityFrameworkCore 5.0.8

### ISSUE THREAD

**Issue by annetcore7** [dotnet/efcore#25277]
Team , 

How to execute the oracle stored procedure which resides in the package through EF Core 5 .

please find the below error while trying to run SP from the oracle package.
Error:-  "ORA-00900: invalid SQL statement"

let me know if any inputs .

**Comment by ErikEJ** [comment]
Please share a code sample

**Comment by annetcore7** [comment]
Hello Erik,

we trying to execute the SP which resides in the package of oracle 11g. As of now we don't have any issues by querying the tables directly but we are facing issues while executing the SP from the package.

1. Get connection string :
services.AddDbContext<ModelContext>(options=>options.UseOracle(Configuration.GetConnectionString("DefaultConnection")));

2. callingSP from package .
Var list  = _context.GetResultdetails.FromSqlRaw
                    ("BEGIN Package.uspGetdetailsSP(:vrAccessID,:results); END;", parameters).ToList();

3.Fetching data from table
 var a = _context.species.FromSqlRaw("select * from DetailDB.table;").ToList();

**Comment by roji** [comment]
@annetcore7 the error above, "invalid SQL statement", seems to be Oracle telling you that your raw SQL is invalid in some way - since EF Core didn't generate the SQL (you're specifying raw SQL), this seems to be a problem in your code. I'd suggest looking at Oracle resources and possibly reaching out to the maintainers of the Oracle EF provider.

One thing does come to mind - are you sure that that BEGIN/END are correct here? These seem to be to start a PL/SQL block, which may not be needed in this context. You may also need to specify CALL before the name of the SP (but again, consult Oracle-specific resources to be sure).
