### ISSUE TITLE
memory 

### ISSUE THREAD

**Issue by naruto1227** [dotnet/efcore#25349]
When I used EFcore5 in AspNetCore5.0, I called SaveChangesAsync when I saved a field that was too long, and EFcore didn't throw an error, but the memory kept soaring

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by roji** [comment]
Could be related to https://github.com/dotnet/SqlClient/issues/593 / https://github.com/dotnet/SqlClient/issues/716.

@zhanghaiboshiwo can you please try using sync I/O (SaveChanges instead of SaveChangesAsync) to check this? If it doesn't help, can you submit a minimal code sample, so we know what exactly you're doing (e.g. what is the field type, how long...)?

**Comment by zhanghaiboshiwo** [comment]
![1](https://user-images.githubusercontent.com/43592384/127292997-baba4976-7a68-43b1-80e0-9410609cf52b.png)

**Comment by zhanghaiboshiwo** [comment]
When I was debugging the source code, I found that the problem appeared here. When I reported an error, debugging here, the memory would soar and could not be finished

**Comment by ajcvickers** [comment]
@zhanghaiboshiwo Almost certainly a duplicate of #15214.
