### ISSUE TITLE
Use EF8-style primitive collections in the Cosmos provider

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#25364]
These could be useful for other providers, not just Cosmos: `ListComparer`, `NullableListComparer`, `SingleDimensionalArrayComparer`, `NullableSingleDimensionalArrayComparer`, `StringDictionaryComparer`, `NullableStringDictionaryComparer`

**Comment by roji** [comment]
When doing this, decide on how to deal with readonly collections (see https://github.com/dotnet/efcore/pull/25344#issuecomment-890343654).

**Comment by AndriySvyryd** [comment]
> When doing this, decide on how to deal with readonly collections

Consider read-only collections of mutable types (nested collections)

**Comment by roji** [comment]
Another provider that seems to support arrays which could benefit from this: https://github.com/cloudspannerecosystem/dotnet-spanner-entity-framework

**Comment by AndriySvyryd** [comment]
Related to #17471

**Comment by roji** [comment]
Design decision: we need to as part of the relational primitive collections work (#30731). Collection properties will use the value converter by default; where not appropriate (because the collection is huge), users can disable it.

Note: special-case .NET immutable collections such as [ImmutableList](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablelist-1?view=net-7.0); for these we don't need to snapshot, and the collection only changed if the reference changed (these types are particularly well-suited for change tracking).

**Comment by roji** [comment]
Note: see the [new implementation](https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs#L351) of the collection comparers in 8.0.0-preview4. Note that this restricts to IList only, and not to ISet as discussed in the design meeting, because of the difficulty to (efficiently) compare two sets using (EF's) element comparer.

**Comment by ajcvickers** [comment]
Note for triage: https://github.com/dotnet/efcore/pull/31480 added comparers for primitive collections, but these don't yet support nested collections. We should re-work them to do so, and then the Cosmos comparers can be removed.

**Comment by AndriySvyryd** [comment]
Related to #4179
