### ISSUE TITLE
[Question] Help implementing sequence in Npgsql

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#2537]
I'm working on identity/sequence and I could use a little bit of hand-holding...

PostgreSQL supports simple SQL sequences, there is no special SqlServer-like identity column. As a shorthand for creating the sequence and assigning it as the default value of a column, a column's type can be serial (or smallserial or bigserial), which does the same thing (see [docs](http://www.postgresql.org/docs/9.4/static/datatype-numeric.html), section 8.1.4).
- If I understand correctly, a user should be able to get a sequence simply by saying `.StoreGeneratedPattern(StoreGeneratedPattern.Identity)` on the property while building the model, right?
- I can see that the SqlServer provider has the property extension methods `UseSqlServerIdentityColumn` and `UseSqlServerSequenceHiLo` to select a specific identity generation strategy. This concept seems meaningless on PostgreSQL, where there is only one strategy (i.e. SQL sequence).
- The trouble I have, is that when generating the migration SQL for a column, property annotations are present but the `StoreGeneratedPattern` doesn't seem to be; `StoreGeneratedPattern` seems to be a flag on Property, but since the property instance isn't passed to the migration SQL generator. SqlServer doesn't run into this issue because it looks at the identity generation annotation rather than at the `StoreGeneratedPattern`.

Thanks for your help...

As a side-note, what purpose does `PropertyFlags.IsValueGeneratedOnAdd` serve and how does it interact with `PropertyFlags.IsIdentity`?

**Comment by ErikEJ** [comment]
Have a look here, you need to implement an annotationprovider

**Comment by roji** [comment]
Thanks @ErikEJ, that looks like the piece I was missing :)

**Comment by ajcvickers** [comment]
@roji To answer your side note, the IsValueGeneratedOnAdd has now been renamed in the PR I mentioned on the other issue. It is now RequiresValueGenerator, which may still not help much. The point is that EF7 requires some form of value generator for almost all key properties, and also in some other cases. Quite often this is only used to generate a temporary key that is then replaced later, but sometimes it will generate a real key. So this piece of metadata just tells EF internals to use a ValueGenerator of some form. Application code will pretty much never want to change this flag from the value automatically calculated. This is why we removed access to this from the fluent API. It is still possible to change it on core metadata because in some advanced scenarios it might make sense to change it, but we do not expect this to be common.

**Comment by roji** [comment]
Thanks for the clarification @ajcvickers.

Just to make sure I understand everything... To provide basic support for sequence fields the EF7 provider doesn't actually have to implement (or subclass) a value generator (e.g. HiLoValueGenerator), right? In PG a serial column can be created simply by giving it the type `serial` (shorthand for creating the sequence and assigning a value from it to the column by default). So right now my MigrationSqlGenerator simply emits `serial` as the column type when the sequence annotation exists - and everything seems to work fine. (It won't take care of columns with specific, i.e. named, sequences, but I'll be doing that soon).

I'm guessing that providing hilo as an option to users can be a useful optimization (less database roundtrips), but as a basic implementation what I've done should be sufficient?

**Comment by ajcvickers** [comment]
@roji That is correct, yes.
