### ISSUE TITLE
Strange identity/default management in tests

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#2539]
The StoreGenerated tests use a test model which has three string Identity columns - they are [configured with `StoreGeneratedPattern.Identity`](https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.Core.FunctionalTests/StoreGeneratedTestBase.cs#L439).

Unless I'm misunderstanding the meaning of Identity that shouldn't make much sense - identity works only for integers... As of now [the Identity setting is ignored in the SqlServer migration annotation provider](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.SqlServer/Migrations/SqlServerMigrationAnnotationProvider.cs#L39) since the same fields also happen to be configured with default values.

It seems that mixing Identity with default values shouldn't be possible, i.e. exception rather than silently ignoring the identity. And in that case the tests would need to change as well...

**Comment by ajcvickers** [comment]
@roji We discussed the naming and API for these methods in the [design meeting last week](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-July-2,-2015) and I just sent out a PR that implements some of these renames. We were previously trying to stick with the "Identity" and "Computed" terminology from earlier versions of EF but we decided that this was causing too much confusion because "Identity" in this context is not the same as using a SQL Server Identity column.

Once the PR is merged StoreGeneratedPattern.Identity becomes ValueGenerated.OnAdd. Both before and after the rename its meaning is that an application does not need to provide a value for this property on new entities because one can be generated automatically. It is up to the provider to determine how such a value will be generated using either a client-side ValueGenerator or some pattern on the store that will generate a value--e.g. an Identity column or a column configured to generate a default value.

For example, for integer properties on SQL Server that are marked as ValueGenerated.OnAdd the provider will do the following:
- By default, an Identity column is created by Migrations and a temporary value generator is used for keys. The temporary value is replaced using the value from the Identity column when SaveChanges is called.
- If DefaultValue or DefaultValueSql has been specified for the property, then Migrations will not create an Identity column. A temporary value generator is used for keys and the value is replaced on SaveChanges by the value from the database.
- If the SequenceHiLo generator has been configured, then Migrations will again not create an Identity column and the HiLo value generator will be used so that true, non-temporary keys will be used immediately. In this case SaveChanges just sends the value in the insert.

If the application tries to do something that cannot be handled then it is expected that the provider will generate an error at some point. So for example, two properties both interpreted as an Identity column will cause SQL Server to throw when the migration is applied.

Hope that makes things a bit clearer.

**Comment by roji** [comment]
Thanks @ajcvickers, that helps a lot.

One thing I'm still unclear on: StoreGeneratedPattern currently contains Computed in additition to Identity, are you planning to remove that when Identity is renamed to OnAdd? Otherwise it seems odd for the two to coexist (and default values/expressions definitely seem to be computed).

I'm guessing that the temporary key value is purely an EF internal requirement, to keep track of the object while its true, permanent key hasn't yet been retrieved from the database, right?

**Comment by ajcvickers** [comment]
@roji Computed becomes OnAddOrUpdate. This means that the column value is read from the database and propagated into the entity instance when the entity is first saved, but also when it is updated. This is often used with rowversion/timestamp optimistic concurrency, but can also be used in other ways. For example, see Insert_and_update_with_computed_column in SqlServerValueGenerationScenariosTest. There are FirstName and LastName properties and a FullName property that is marked with OnAddOrUpdate and set to be computed on the store. When FirstName or LastName are changed and the entity is saved the value of FullName is computed in the store and the value is automatically propagated back into the entity instance.

With regard to temp keys, you are correct.

**Comment by rowanmiller** [comment]
@roji feel free to reactivate if this isn't fully answered

**Comment by roji** [comment]
@ajcvickers thanks for the patient explanations, everything is clearer now!

**Comment by julielerman** [comment]
just looping back to make sure that you decided against the "valuegenerated" data annotation ? It's still databasegenerated in RC1. I can't find any indication in current src that it will be any different. Thanks

**Comment by rowanmiller** [comment]
Yep, that attribute is actually defined in System.ComponentModel.DataAnnotations.dll... so we couldn't really change it

**Comment by julielerman** [comment]
thx
