### ISSUE TITLE
Allow scaffolding to generate attributes that are only supported by `System.ComponentModel.Annotations` upon Fluent API usage

### ISSUE THREAD

**Issue by cilerler** [dotnet/efcore#25514]
It would be nice to have `--data-annotations` parameter of [`dotnet ef dbcontext scaffold`](https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-dbcontext-scaffold) to allow to generate the attributes that exist in `System.ComponentModel.Annotations` upon Fluent API usage.

Those attributes are valuable upon Model library sharing.  However, right now, if we don't add that parameter, it strips all the attributes; if we add it, we have to have a `Microsoft.EntityFrameworkCore.SqlServer` dependency in the model project.

e.g.
```powershell
dotnet ef dbcontext scaffold "<connection-string>" Microsoft.EntityFrameworkCore.SqlServer `
--force  --no-onconfiguring --data-annotations `
--context-namespace "MyApp.Data" --context-dir "..\MyApp.Data" --context "MyCompanyDbContext" `
--namespace "MyApp.Models.MyCompany" --output-dir ".\MyCompany"  `
--schema dbo --schema mySchema;
```

So far I have only identified the attributes below as missing ones from [dataannotations](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations?view=net-5.0) or [dataannotations.schema](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.schema?view=net-5.0)
- `Keyless`
- `Index`, `Name`, `IsUnique`

**Comment by ajcvickers** [comment]
@cilerler You should not need to add a reference to `Microsoft.EntityFrameworkCore.SqlServer`. All the mapping attributes are contained in [Microsoft.EntityFrameworkCore.Abstractions](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Abstractions/). This is a small package (currently 44K) that doesn't depend on any other packages and is intended for those who want to continue to use mapping by attribute without referencing all of EF Core.

We do not intend to make any changes to `System.ComponentModel.DataAnnotations` or add any new types there, because this creates a semantic coupling across code that uses the annotations that then makes it pretty much impossible to evolve these things. However, people like to use mapping attributes and we want to allow that experience to get better, hence new attributes are added to `Microsoft.EntityFrameworkCore.Abstractions` where they are specific to EF Core and don't suffer from the coupling issues.

For people who don't want to depend on `Microsoft.EntityFrameworkCore.Abstractions`, we recommend using the fluent API, which supports all configuration and can be used with fully-POCO models.

**Comment by cilerler** [comment]
@ajcvickers, it is exactly what I was looking for actually, thank you very much 🤗
