### ISSUE TITLE
ArgumentException with Complex Delegation of Compiled Query

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/efcore#25679]
## File a bug

I am kicking the tires on Compiled Queries, and I appear to have run into a potential bug.  Reporting it here for your review.

In essence, I am delegating the resolution of the `IQueryable<T>` used for the compiled query expression to other components.  This works, but there does appear to be a limit to how far this can go currently.

When this condition happens, the wrong type appears to be evaluated, leading to the exception.

I have actually seen this type of exception before in my usage with EfCore, but the scenarios were far too complex to report at the time.  Luckily I have been able to capture it here in a much more simpler format to investigate.

### Include your code

I've created a sample project with a passing test and a failing test here:
https://github.com/Mike-E-angelo/Stash/tree/master/EfCore.CompiledQuery.ArgumentException

### Include stack traces

```

System.ArgumentException
Expression of type 'Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor+QueryingEnumerable`1[EfCore.CompiledQuery.ArgumentException.Subject]' cannot be used for parameter of type 'System.Linq.IQueryable`1[EfCore.CompiledQuery.ArgumentException.Subject]' (Parameter 'arg2')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Invoke(Expression expression, Expression arg0, Expression arg1, Expression arg2)
   at System.Linq.Expressions.InvocationExpression3.Rewrite(Expression lambda, Expression[] arguments)
   at System.Linq.Expressions.ExpressionVisitor.VisitInvocation(InvocationExpression node)
   at System.Linq.Expressions.InvocationExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CreateCompiledAsyncQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledAsyncEnumerableQuery`2.CreateCompiledQuery(IQueryCompiler queryCompiler, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.<>c.<EnsureExecutor>b__6_0(CompiledQueryBase`2 t, TContext c, LambdaExpression q)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam1,TParam2,TParam3,TValue](TValue& target, TParam1 param1, TParam2 param2, TParam3 param3, Func`4 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.EnsureExecutor(TContext context)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, CancellationToken cancellationToken, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledAsyncEnumerableQuery`2.Execute[TParam1](TContext context, TParam1 param1)
   at EfCore.CompiledQuery.ArgumentException.Form`2.Get(In`1 parameter) in ...\EfCore.CompiledQuery.ArgumentException\EfCore.CompiledQuery.ArgumentException\Class1.cs:line 249
   at EfCore.CompiledQuery.ArgumentException.Invoke`3.Get(TIn parameter) in ...\EfCore.CompiledQuery.ArgumentException\EfCore.CompiledQuery.ArgumentException\Class1.cs:line 231
   at EfCore.CompiledQuery.ArgumentException.Evaluate`3.Get(TIn parameter)
   at EfCore.CompiledQuery.ArgumentException.CompiledQueryTests.DoesNotWork() in ...\EfCore.CompiledQuery.ArgumentException\EfCore.CompiledQuery.ArgumentException\CompiledQueryTests.cs:line 46
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

```

### Include verbose output

NA

### Include provider and version information

EF Core version: `6.0.0-rc.1.21416.1`
Database provider: `Microsoft.EntityFrameworkCore.InMemory`
Target framework: `net6.0`
Operating system: Windows 10
IDE: Visual Studio 2022 Preview 3.1

**Comment by Mike-E-angelo** [comment]
Thank you for looking into this, @smitpatel.  However, there may be some confusion here either on your side or mine.  Both tests are calling `EF.CompileAsyncQuery` which takes an `Expression<Func<DbContext, TIn, IQueryable<T>>>`:

https://github.com/Mike-E-angelo/Stash/blob/master/EfCore.CompiledQuery.ArgumentException/EfCore.CompiledQuery.ArgumentException/Model/Form.cs#L16

Meaning each expression ultimately evaluates to an `IQueryable`.  The resulting delegate of this compilation is a `Func<DbContext, TIn, IAsyncEnumerable<T>>` which of course is not an `IQueryable` so I am trying to understand what you mean by your statement.

Please also note that each test use a `Expression<Func<DbContext, TIn, IQueryable<T>>>` but one passes and one does not.

**Comment by smitpatel** [comment]
> Expression of type 'Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor+QueryingEnumerable`1[EfCore.CompiledQuery.ArgumentException.Subject]' cannot be used for parameter of type 'System.Linq.IQueryable`1[EfCore.CompiledQuery.ArgumentException.Subject]' (Parameter 'arg2')

This exception message says  that you have some function invocation which has 3rd parameter which takes result of EF.CompiledQuery but it is typed as `IQueryable<Subject>` rather than `IAsyncEnumerable<Subject>`. So result types are not matching the way you believe. Since the code is using whole set of different classes to generate & execute the query, I am not able to easily point-out where the type mismatch is happening. If you can provide a simplified repro which doesn't additional classes to generate query, I may be able to help out.

**Comment by Mike-E-angelo** [comment]
If the types aren't matching up @smitpatel shouldn't that result in a compile exception?

**Comment by smitpatel** [comment]
In ideal world, yes it should throw compile exception but in real world things are bit different. When you write a complex expression tree and pass it to EF.CompiledQuery the delegate returned from it would take correct type, so this doesn't cause compilation error. But in the complex expression tree written if you have a queryable subquery which would terminate (for whatever reason like applying a terminating result operator or ToList or passing it as argument to a function which EF doesn't understand), EF will convert the queryable to IAsyncEnumerable after query translation. Now the tree you had earlier which was compile fine is incorrect since you don't have queryable anymore. If you are using such method inside the expression passed to CompiledQuery the method needs to take type which can accommodate this change. Since queryable derives from IEnumerable, you need to make sure that parts of query which will get converted from queryable to EF Core's enumerable are used as enumerable inside expression.

**Comment by Mike-E-angelo** [comment]
OK thank you for that explainer and taking the time to write that, @smitpatel it is appreciated.

I did make more direct tests for you to view here:
https://github.com/Mike-E-angelo/Stash/blob/master/EfCore.CompiledQuery.ArgumentException/EfCore.CompiledQuery.ArgumentException/CompiledQueryTests.cs#L54-L77

I checked and doublechecked and it seems like it's "Queryable all the way down" 😆  It further seems it is being passed directly from the `DbContext`.  However, one test fails and one passes.  The only difference is the extra delegate.

You've got me jumpy now that I have overlooked something fundamental and plainly obvious.  The frustration here for me is that it's nearly impossible to debug expressions as you know.  So it's useless to put a breakpoint in those delegates to check values, etc.  Otherwise those sorts of things could be done before adding to your issue list here.  That stated if you are aware of any neat tricks to debug expressions I would be grateful. 🙏

**Comment by smitpatel** [comment]
the variable `next` lambda returns IQueryable according to signature but the 3rd argument is DbSet there which will be converted to IAsyncEnumerable and that method call throws exception. Not sure why the other one works.
The "Queryable all the way down" doesn't work with EF.CompileQuery.

**Comment by Mike-E-angelo** [comment]
Right it would seem that if the hidden casting to `IAsyncEnumerable` was the problem, it would fail with both.

**Comment by Mike-E-angelo** [comment]
The plot thickens.  Picking at this some more, removing the `TIn` parameter also works and results in no exception thrown:

https://github.com/Mike-E-angelo/Stash/blob/d6f48b05181ce446831b0ab3b3209b7d358e9abd/EfCore.CompiledQuery.ArgumentException/EfCore.CompiledQuery.ArgumentException/CompiledQueryTests.cs#L82-L97

So it would appear the issue here lies in the introduction of the `TParam1` parameter on `CompileAsyncQuery`.

**Comment by smitpatel** [comment]
Sadly there is no documentation on CompiledQuery yet because API has been bit complicated in terms of use.
This class serves as current compiled query feature in EF Core https://github.com/dotnet/efcore/blob/release/6.0/test/EFCore.Specification.Tests/Query/NorthwindCompiledQueryTestBase.cs

Regarding attempt to convert to queryable, the tree itself is fine to have Queryable calls but the return type of the delegate cannot utilize Queryable since anything which is converted to a server correlated query by EF Core will become a custom enumerable. If you are using Async query then the custom enumerable will be of IAsyncEnumerable. IAsyncEnumerable doesn't derive from IEnumerable since they are different kind. The real issue lies in using a expression + invocation in tree construction. When you invoke a delegate/lambda with parameters in normal world it will just evaluate it. The same is not true when it is used inside a lambda expression, since lambda will try to preserve the structure.

Looking at the code again the core issue in the code is `Func<>` which are opaque structure in expression tree, they causes client evaluation. Once the query has evaluated for EF Core (the part which can be) it will become the custom enumerable. Also all the funcs are using either IQueryable/IEnumerable. CompileAsyncQuery returns IAsyncEnumerable which cannot be cast from either of those. 

I recommend stop using Func in this way for composition of expression tree. There are easier and better way to compose expression tree to arrive at tree you need.

**Comment by Mike-E-angelo** [comment]
Thank you for confirming my understanding with regards to documentation, @smitpatel.  I appreciate that link as well as the discussion here.

>  real issue lies in using a expression + invocation in tree construction

I agree with this.  However, I am not sure we are on the same page as far as the impact of this issue.  Here is another test that really highlights it:

https://github.com/Mike-E-angelo/Stash/blob/master/EfCore.CompiledQuery.ArgumentException/EfCore.CompiledQuery.ArgumentException/CompiledQueryTests.cs#L99-L111

Notice line `106`, bypassing the provided parameter from the argument list and using a direct value in its place works.  This seems very broken to me.

> they causes client evaluation

Is there a way to confirm this?  In the case of creating and defining a `IQueryable<T>` (and not evaluating it, that is ToArray, etc) I am OK with this.

> Also all the funcs are using either IQueryable/IEnumerable

Not to be a stickler here but I never use `IEnumerable`.  `IQueryable`s all the way down, after all. :)

> CompileAsyncQuery returns IAsyncEnumerable which cannot be cast from either of those.

Nodding along here.

> I recommend stop using Func in this way for composition of expression tree. There are easier and better way to compose expression tree to arrive at tree you need.

I would tend to agree with you here, but as demonstrated the `Func<>`'s work just fine when parameters are not a part of the picture.

Additionally, this goes against the preferred way I would like to design compiled queries.  The idea is to have query definitions that can build upon one another and subsequently stored as strongly-typed instances in the application domain that are used as building blocks to defining compiled queries.

So you can imagine something like:

```
sealed class EnabledUsers : QueryDefinition<ApplicationDbContext, User>
{
	public static EnabledUsers Default { get; } = new EnabledUsers();

	EnabledUsers() : base(x => x.Where(y => y.Enabled)) {}
}
```

Then `EnabledUsers` can be used as a starting point to build the body of the compiled query, with other `QueryDefinition` taking that and selecting/adding their own modifications and adjustments to build the final form.  The aggregated result of this would then go into the compiled query for the `Func<DbContext, TIn, IAsyncEnumerable<T>>`.

Again, the critical part here is that this works as desired when no `TParam1` is used.  It's only when a parameter is introduced and subsequently used does this exception occur.

Thank you again for your time and discussion. 👍

**Comment by smitpatel** [comment]
Just certain func working doesn't imply it is right pattern. It is fundamentally broken pattern to use funcs inside expression tree which gives no ability to translate. To highlight the issue, the expression passed to EF.CompileQuery in the test WorksWithProvidedParameter looks like following
```C#
(context, @in) => next(context, None.Default, context.Set<Subject>())
```

Which means that we don't know what `next` is so we evaluate `context.Set<Subject>()` effectively getting whole table back and calling the function `next` to generate results.
If you write the expression properly then it should look like this
```C#
(context, @in) => context.Set<Subject>().Where(x => x.Name != "Two");
```
In which we will evaluate `Where` on server side and only fetch records from database where `Name` doesn't equal to `Two`. So using func to compose a tree here is fundamentally bad for perf and a design which must not be used.

Now this doesn't mean that you cannot have composition the way you want but rather than using func, you need to create proper expression tree. Some of them can be done easily by calling appropriate code on Queryable directly albeit conditionally. Sometimes you may also need to build expression tree manually. Both of the variants are very advanced scenario (since normal users just write query directly, only libraries try to do thing dynamically), and outside the scope of EF Core. Perhaps a web search would be a good place to get understanding of building expression tree dynamically.

Since the pattern being used is bad (due to client evaluation/opaque structure of func), we don't have plan to make them working or investigate why some work and why others don't. I am closing this issue as nothing actionable on EF Core side.

**Comment by Mike-E-angelo** [comment]
On the contrary @smitpatel I would ask that you reconsider, as you appear to be mistaken in your understanding with regards to client evaluation.  Please see the following project, which makes use of a compiled query here:
https://github.com/Mike-E-angelo/Stash/tree/master/EfCore.CompiledQueries.ClientEvaluation

In it, I run a `DbSet<T>` through a delegate here:
https://github.com/Mike-E-angelo/Stash/blob/master/EfCore.CompiledQueries.ClientEvaluation/EfCore.CompiledQueries.ClientEvaluation/Query.cs#L13

The following is emitted at runtime:


```
Microsoft.EntityFrameworkCore.Model.Validation: Warning: Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 6.0.0-rc.1.21416.1 initialized 'Context' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
IF SERVERPROPERTY('EngineEdition') <> 5
BEGIN
    ALTER DATABASE [efcore.clientevaluation] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
END;
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
DROP DATABASE [efcore.clientevaluation];
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (147ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
CREATE DATABASE [efcore.clientevaluation];
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (51ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
IF SERVERPROPERTY('EngineEdition') <> 5
BEGIN
    ALTER DATABASE [efcore.clientevaluation] SET READ_COMMITTED_SNAPSHOT ON;
END;
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [Subjects] (
    [Id] uniqueidentifier NOT NULL,
    [Name] nvarchar(max) NOT NULL,
    CONSTRAINT [PK_Subjects] PRIMARY KEY ([Id])
);
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (33ms) [Parameters=[@p0='b56837c8-25a2-405c-cb01-08d9673bb66d', @p1='One' (Nullable = false) (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Subjects] ([Id], [Name])
VALUES (@p0, @p1);
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (1ms) [Parameters=[@p0='a14b3a5d-4df1-494c-cb02-08d9673bb66d', @p1='Two' (Nullable = false) (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Subjects] ([Id], [Name])
VALUES (@p0, @p1);
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (1ms) [Parameters=[@p0='bde04ef6-020c-4f4a-cb03-08d9673bb66d', @p1='Three' (Nullable = false) (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Subjects] ([Id], [Name])
VALUES (@p0, @p1);
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 6.0.0-rc.1.21416.1 initialized 'Context' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: SensitiveDataLoggingEnabled 
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [s].[Id], [s].[Name]
FROM [Subjects] AS [s]
WHERE [s].[Name] <> N'Two'
EfCore.CompiledQueries.ClientEvaluation.Worker: Information: There are 2 Subjects.
EfCore.CompiledQueries.ClientEvaluation.Worker: Information: Subject Name: One
EfCore.CompiledQueries.ClientEvaluation.Worker: Information: Subject Name: Three
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Production
```

As you can hopefully see, there is no query to pull all of `Subject`s as you suggest, and the requested items are pulled exactly defined in the delegated function.  As such, there appears to be no client evaluation in this regard.

Thank you for any further consideration towards this matter. 🙏

**Comment by smitpatel** [comment]
EF Core has certain visitor for certain patterns to remove invocation expression. See https://github.com/dotnet/efcore/blob/release/6.0/src/EFCore/Query/Internal/InvocationExpressionRemovingExpressionVisitor.cs

The invocation pattern is only useful when a custom selector needs to be applied on a reference navigation which is not composable in LINQ any longer. For other patterns when a simpler and better expression tree can be generated using invocation expression is unsupported scenario. The specific reason you are running into type mismatch for parameter "arg2" is that the method is being evaluated on client side. I hope this explains why some of the queries worked for you.
The way expression trees are being created above is not same as tree created by compiler from a LINQ query, it is not the way trees are created dynamically (there are many libraries which integrate on top of EF and generate queries dynamically, eg. OData/AutoMapper). We don't intend to spend time in supporting the pattern represented above since we consider it bad design.

As suggested above, if you really want to construct dynamic trees then more understanding in how to create expression tree will be useful. The current design of passing around func is _not_ supported.

**Comment by Mike-E-angelo** [comment]
OK @smitpatel I greatly appreciate the knowledge transfer here and the time taken to educate me.  My concern was that there was a misunderstanding with client-side evaluation and wanted to be sure.

I am OK with this being an unsupported scenario and accept that.  It would be nicer to have that in an exception message so I don't have to spend an afternoon taking your time with such nagging questions. 😆

But I think you're correct with constructing dynamic queries.  Unfortunately, I do not consider that an elegant solution, unless there is some way to directly compile an expression tree from an existing Func, which doesn't seem possible and is in fact the opposite process.  If you have any suggestions in this regard I would be more than happy to check them out.

Besides all this, much respect and appreciation for all your work on this product out there.  It's positively wonderful. 👍

**Comment by Mike-E-angelo** [comment]
@smitpatel another gotcha here that I uncovered after a bit more testing.  While the invocation calls appear to work with non-parameter delegates, the invocations are indeed client-evaluated, and more importantly _stored_ for subsequent calls.  So while the first call may appear to work as expected, subsequent calls may not, as they are based on the state of the call of the first invocation.  I know you probably tried to convey this to me but it didn't stick to me the way a failed test can. :)  I happened upon this on further testing to see if there was a way around the `TParam1` problem.

So, expression building it is.  In case anyone else also happens upon this problem, here are a few links to help get you started:

https://stackoverflow.com/questions/457316/combining-two-expressions-expressionfunct-bool
https://stackoverflow.com/questions/1717444/combining-two-lambda-expressions-in-c-sharp/1720642#1720642
https://stackoverflow.com/questions/6736505/how-to-combine-two-lambdas/6736589#6736589

FWIW this looks much more usable/reasonable the last time I looked at expression building, which according to the answers in the given links above must have been pre-4.0.  :S  Hope that helps explain my apprehension towards investigating this from the outset.
