### ISSUE TITLE
MigrationsAssembly path not working

### ISSUE THREAD

**Issue by EduardRotaru** [dotnet/efcore#25725]
I am trying to add a new migration in another project and I think I don't understand how it works.

```
       services.AddDbContext<ApplicationDbContext>(
                c => c.UseSqlServer(_config.GetConnectionString("ApplicationDbContext"), 
                opt => opt.MigrationsAssembly("DatabaseContext.Migrations")));
```

First I tried to add the migration from the API project, not the class library with database context, and migration folder. Then I tried from the other project.. None working and its telling me the following:

If I try to add migration in the class Library via Package Manager console where I select the default project the DatabaseContext
`System.IO.FileLoadException: The given assembly name or codebase was invalid. (0x80131047)`

If I try to add from the API project I get:
`Could not load file or assembly 'DatabaseContext.Migrations, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

At this point I am confused.. by my logic it should be working from both right?

The structure in Solution Explorer is the following
Shop (former empty solution)
      1. DatabaseSchema (folder with empty spaces)
              DatabaseContext (project with the migrations folder inside)
      ..
     bunch of other stuff
     ..
    ShopApi (here I have that code above in Startup.cs)

I tried many different paths and I looked at namespaces and nothing seems to work. 
"../DatabaseContext.Migrations"
"DatabaseContext.Migrations"
"../1. DatabaseSchema/DatabaseContext.Migrations"

**Comment by wingi11** [comment]
The sample project works for me but my implementation does not. The only thing that differs from the sample project is that my projects are in an src folder. Is there somewhere a real world project that does this?

**Comment by titobf** [comment]
The approach suggested in [Using a Separate Migrations Project](https://docs.microsoft.com/ef/core/managing-schemas/migrations/projects) didn't work for me either. The web host project would not pick up the migrations dll even if it was there on the bin folder.
What worked for me was using OutputPath instead of BaseOutputPath in the migrations class library:
<OutputPath>..\MigrationsDlls\</OutputPath>
And then from the Web Host project reference the generated dll (right click -> Add Project Reference -> Browse -> select dll).
Additionally, this approach allows moving the migrations class library into a separate solution.
Hope this helps somebody else.

**Comment by david-szabo97** [comment]
I'm using the `MigrationsAssembly()` to avoid circular dependency between my projects. I have two projects:
- `App`
- `Migrations`

The dependencies are:
- `Migrations` references `App` as a dependency

In the `Migrations` project we added the following to the `.csproj`'s `PropertyGroup`:
```xml
<BaseOutputPath>..\App\bin\</BaseOutputPath>
```

To access the migrations from the `App` project, we need to use `MigrationsAssembly("Migrations")`. This will throw an exception because it cannot load an assembly which isn't referenced by the `App` project. To fix it, you can either load it into the `AssemblyLoadContext`, or load the assembly via absolute path. An example for the latter:

```cs
var migrationsAssembly = Assembly.LoadFile(Path.Join(AppContext.BaseDirectory, "Collabri.Migrations.dll"));
optionsBuilder.UseNpgsql("", x => x.MigrationsAssembly(migrationsAssembly));
```
