### ISSUE TITLE
Expose method DbContext.Set(Type entityType)

### ISSUE THREAD

**Issue by ilmax** [dotnet/efcore#2586]
Hi, poking around with EF7 I've found this method missing, and since EF7 provide in almost all cases a strongly typed and loosely typed way of doing things, this is api is missing IMHO.

What about you?

Regards, Max

**Comment by ilmax** [comment]
I would like to submit a PR for this, so IO would like to discuss with the team/community how to implement this since whe only have DbSet<T> in EF7.

Option 1 is to mimic what ```IDbSetSource``` is doing and return an object.
Option 2 is to create a non generic DbSet.

I personally didn't like option 1 because IMHO returning object from a Set method in DbContext leads to a poor user experience, I didn't like option 2 either because we need to create another empty class (like DbSet<T>) just for this scenario and keep it in sync with DbSet<T>, this options IMHO provides a way better user experience but comes with an extra class costs.

Let me know if there are others options, or which one you prefer.

Regards, Max

**Comment by laskoviymishka** [comment]
Hi,
I also look at this issue :confounded: . 
My opinion same - its need to create non generic DbSet, but there is a little API difference from <code>DbSet(T)</code>  -> <code>DbSet</code>.

If you look at <code>DbSet(T)</code> api you will see that it support for both <code>params T[]</code> and <code>IEnumerable(T)</code> input for <code>Range</code> operations (<a href="https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.Core.Tests/DbSetTest.cs#L98">like in this test </a> and <a href="https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.Core.Tests/DbSetTest.cs#L187">like in this test </a>).

In case of <code>DbSet(T)</code> it works since it has more specific <code>IEnumerable(T)</code> input for these methods. 

But in case of <code>DbSet</code> we need to choose which overload we should expose <code>param object[]</code> or <code>IEnumerable</code>. We cannot have same functionality in both <code>DbSet(T)</code> and <code>DbSet</code>.

In my opinion we should leave the same api as in EF and skip params input feature (like it was in <a href="https://msdn.microsoft.com/en-US/library/system.data.entity.dbset.removerange(v=vs.113).aspx">old EF</a>).

Best regards,
Andrei Tserakhau

**Comment by ChangedHourly** [comment]
I would like to see this in EF7 if possible.

**Comment by ajcvickers** [comment]
@ilmax @ChangedHourly Could you give some examples of scenarios in which you would use the non-generic context.Set method? This will help drive an appropriate implementation and return type. Keep in mind that in EF7 you never need the DbSet to add, attach, or otherwise manipulate entities because the methods for this are on the context.

Thanks,
Arthur

**Comment by ilmax** [comment]
@ajcvickers Thanks for your info, in fact those methods on ```DbContext``` does satisfy all my actual needs. 

For me this issue could be closed!

**Comment by ChangedHourly** [comment]
Hi,

 

I am using the DbContext.Set(Type entityType) to iterate through sets in a context in an export function:

 

        public async Task ExportDbSetsAsync(DbContext oldDatabase, DbContext newDatabase, List<DbSetExportInfo> dbSets)

        {

            foreach (DbSetExportInfo setData in dbSets)

            {

                if (setData.Export == true)

                {

                    var oldSet = oldDatabase.Set(setData.DbSetType);

                    var newSet = newDatabase.Set(setData.DbSetType);

                    var progress = new Progress<int>(count =>

                    {

                        setData.ExportedCount = count;

                    });

 

                    try

                    {

                        await ExportDbSetAsync(oldSet, newSet, progress);

                        await newDatabase.SaveChangesAsync();

                    }

                    /* PCVB: Need to send exceptions back to user. More work needed here. */

                    catch (Exception ex)

                    {

                        throw new Exception("Error exporting data: " + setData.DbSetName + "\r\n"

                            + ex.Message + "\r\n" + ex.InnerException.Message);

                    }

                }

            }

        }

 

        public async Task ExportDbSetAsync(DbSet oldSet, DbSet newSet, IProgress<int> progress)

        {

            if (oldSet.ElementType.Equals(newSet.ElementType))

            {

                var i = 0;

 

                await oldSet.AsNoTracking().ForEachAsync(entity =>

                {

                    newSet.Add(entity);

                    if (progress != null)

                    {

                        progress.Report(++i);

                    }

                });

            }

        }

 

I have some lengthy code to create the List<DbSetExportInfo> from the context type using objectcontext and metadata.

 

I confess that I haven’t considered yet how else this might be achieved, it may be very straightforward!

 

 

FYI I was originally using SqlServerCe, I am using localdb for testing with EF7.

 

 

 

Patrick

**Comment by rowanmiller** [comment]
Clearing back up for triage based on discussion.

**Comment by divega** [comment]
@ChangedHourly would something like this work for you?:

``` C#
var oldSet = (IQueryable<object>)oldDatabase.GetType().GetMethod("Set").MakeGenericMethod(setData.DbSetType).Invoke(oldDatabase, null);
```

We think of DbSet mainly as:
1. The starting point for LINQ queries
2. A place where you can issue typed CUD operations for the unit of work

LINQ queries have always been hard to write with non-generic DbSets and as @ajcvickers explained, `Add()`, `Remove()`, etc. can now be called on the DbContext directly. 

In my view, the way you are using non-generic DbSet to programmatically bring all the entities from the database into memory is valid but not super common. It is possibly the only scenario left for which the non-generic `Set()` can be nicer to use and so I am not sure it is a good idea to have the extra API just for it.

**Comment by ChangedHourly** [comment]
Hi divega,

Thanks for the idea. I think that I may be able to replace the DbSet(Type entityType). I will have a go at testing this shortly.

I understand that you would want to clear out what you consider to be unnecessary code. I have been using EF6 for some time but have been tempted into testing EF7, mainly by the TrackGraph feature.

Patrick

**Comment by rowanmiller** [comment]
Discussed and concluded that for most scenarios the `Add`/`Remove` methods on `DbContext` are a better option than the non-generic set. 

If there are more scenarios like the one @ChangedHourly mentioned then we will reconsider adding it in the future. But we suspect those scenarios are pretty rare and using `MakeGenericMethod` is acceptable for those.

**Comment by ctonger** [comment]
I find this decision a serious blow to anyone trying to use ef7 in advances scenarios.
I always used the non generic Set Method in scenarios where I do generic querying on interfaces implemented on the entities and where I only know the entity type at run time. The assumption that you know all your query types at design time is too limiting in my view. I think that this is restricting things on the wrong end.

**Comment by atesoglu** [comment]
Any update on this?

**Comment by ajcvickers** [comment]
@atesoglu @ctonger Can you show some example code of how you are doing the queries after starting with a a non-generic set?

**Comment by codinesh** [comment]
@rowanmiller 

We have a scenario where we need to dynamically identify the DbSet to insert data into. 

This is for conflict scenarios, where we are storing all the possible conflicts into a different table and later be presented to the user for resolution with an original record against conflicting records.
Is there any alternate way other than a non-generic Set method to do this?

**Comment by ajcvickers** [comment]
@codinesh For inserts, call Add on the DbContext directly.

**Comment by MeikelLP** [comment]
Here is my code (works at least for me).

``` csharp
        [HttpPost]
        public async Task<IActionResult> List(string entityType)
        {
            var type = typeof(ApplicationUser).Assembly.GetType(entityType);
            if (type == null) return NotFound("Unkown entity");
            var dbSetMethodInfo = typeof(DbContext).GetMethod("Set");
            var dbSet = dbSetMethodInfo.MakeGenericMethod(type).Invoke(_db, null);

            var toListMethodInfo = typeof(EntityFrameworkQueryableExtensions).GetMethod("ToListAsync").MakeGenericMethod(type);
            var toListMethod = (dynamic)toListMethodInfo.Invoke(dbSet, new []{dbSet, default(CancellationToken)});
            var results = await toListMethod;

            return Json(results);
        }
```

**Comment by novikov-alexander** [comment]
In my project I should often find entities by some predicate. 
I do it this way:

>                 MethodInfo method = typeof(EGeoContext).GetMethod("Set");
>                 MethodInfo generic = method.MakeGenericMethod(type);
>                 IEnumerable<IDescription> dbSet = ((IEnumerable)generic.Invoke(context, null)).Cast<IDescription>();
>                 return dbSet.Where(predicate)
>                        .Select(o => (String)o.GetType().GetProperty(propName).GetValue(o));

Is there shorter way to do it without non-generic "Set"?

**Comment by ajcvickers** [comment]
@novikov-alexander That's actually giving you an `IEnumerable<IDescription>`, not a `DbSet`. The issue is again not how to get the DbSet in a non-generic way, but what you then do with it. There's no way that you can end up with a `DbSet<IDescription>`, but you could get to an `IQueryable<IDescription>()` by doing this instead:
```C#
MethodInfo method = typeof(DbContext).GetMethod("Set");
MethodInfo generic = method.MakeGenericMethod(typeof(Description));
IQueryable<IDescription> queryable = ((IQueryable)generic.Invoke(context, null)).Cast<IDescription>();
```

**Comment by novikov-alexander** [comment]
@ajcvickers Of course you are right. IQueryable is much better than IEnumerable in this context.
But is this way of getting IQueryable (MakeGenericMethod, Invoke etc) shortest and right?

**Comment by ajcvickers** [comment]
@novikov-alexander It's a reasonable way to do it.

**Comment by marcwittke** [comment]
In case someone is stumbling on this, too:

```
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers) in /_/src/coreclr/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 2758
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers) in /_/src/coreclr/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 2743
   at System.Type.GetMethod(String name, BindingFlags bindingAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Type.cs:line 219
   at System.Type.GetMethod(String name) in /_/src/libraries/System.Private.CoreLib/src/System/Type.cs:line 213
```

In Ef Core 5.0 `DbContext` has a second overload for `Set<T>()`, therefore the reflection call suggested by @divega [here](https://github.com/aspnet/EntityFrameworkCore/issues/2586#issuecomment-121407363) needs some tuning. I ended up with a brute force enumeration of all possibilities, since I was unable to figure out how to achieve it with the more detailed overloads of `Type.GetMethod()` and it is just test code in my case...

```csharp
MethodInfo setterMethodInfo = ctx.GetType()
    .GetMethods()
    .Single(mi => mi.Name == "Set" && !mi.GetParameters()
    .Any());
```

**Comment by xellans** [comment]
This option works great for me, an example of an implementation

```
 public class Command<T> : IRepository<T>
 {
     public Context Context; 

     private IQueryable<T>? Reflection()
     {
         MethodInfo method = typeof(DbContext).GetMethod("Set", new Type[] { });
         MethodInfo generic = method.MakeGenericMethod(typeof(T));
         IQueryable<T>? queryable = ((IQueryable<T>)generic.Invoke(Context, null));
         return queryable;
     }
     public IEnumerable<T> Where(Func<T, bool> Expression) => Reflection()?.Where(Expression);
     public bool Any(Func<T, bool> Expression) => Reflection().Any(Expression);
     public T? FirstOrDefault(Func<T, bool> Expression) => Reflection().FirstOrDefault(Expression);
 }
```

**Comment by stevendarby** [comment]
@xellans why not use `Context.Set<T>()`?

**Comment by xellans** [comment]
@stevendarby I use Ef6, it is impossible to do this to methods that are not universal, and since I have a universal class, I would like to expand the possibility of its methods, and without limiting the methods
For example, if you make a restriction for universal methods, the use is
` if(user.Any<User>(x => x.Name == _user.Name));`
But if you use reflection, now you don't need to specify the type
` if(user.Any(x => x.Name == _user.Name));`

**Comment by stevendarby** [comment]
@xellans I don’t follow. You can stop use your Command<T> but within that you have the Context and T, so your Reflection() method could simply return context.Set<T>() without the reflection

**Comment by xellans** [comment]
@stevendarby 
But then I will be forced to do so
`public T? FirstOrDefault<T>(Func<T, bool> Expression) where T : class => Context.Set<T>().FirstOrDefault(Expression);`
Use
```
Command<People> people = new Command<People>();
people.FirstOrDefault<People>(x => x.Name == "");
```
And I can't use such a construction
` public T? FirstOrDefault(Func<T, bool> Expression) => Context.Set<T>().FirstOrDefault(Expression);
`
The type "T" must be a reference type in order to use it as the "TEntity" parameter in the generic type or the "DbContext.Set<TEntity>()" method.

**Comment by xellans** [comment]
```
Command<People> people = new Command<People>();
people.FirstOrDefault<People>(x => x.Name == "");
```
Specifying a class for a method each time loses all versatility for the Set method

**Comment by stevendarby** [comment]
You wouldn’t need to make the method a generic, you already have the generic on the class. Yes, you need to constraint T to classes, but that can’t be an issue, as your existing Reflection method would surely fail if it wasn’t a class anyway.

**Comment by xellans** [comment]
@stevendarby 
While I was writing, you gave an example and I erased everything, I did not think about limiting the class itself, but stopped only at the T class definitions for the method. Your example perfectly replaces mine, and reveals the potential of the Set method. Thanks for the example

**Comment by stevendarby** [comment]
@xellans glad I could help. Btw, perhaps your examples aren’t exact copies of your real code, but I think passing in `Func<T, bool>` will cause EF6 to do client evaluation, which means it’ll load the whole set first. You need to pass in `Expression<Func<T, bool>>` to have a chance of evaluating it on the database server (in SQL)

**Comment by xellans** [comment]
@stevendarby I tested this approach earlier and it works well, it got even better with your example) Thanks again)
