### ISSUE TITLE
QuerySqlGenerator.VisitOrdering does not use GeneratePseudoFromClause

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/efcore#25908]
Firebird DBMS does not support SELECT-statement without FROM-section.

(SELECT 1) - incorrect SQL

(SELECT 1 FROM TableWithOneRow) - correct SQL

QuerySqlGenerator for avoid this problem provides GeneratePseudoFromClause method, which allows to provider generate correct SQL:

https://github.com/dotnet/efcore/blob/3a0defcdb61c6832b705b45fac590024bf447107/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L240-L245

**Question/Problem 1**

Why QuerySqlGenerator.VisitOrdering does not use GeneratePseudoFromClause  for generation of SELECT statement?

https://github.com/dotnet/efcore/blob/3a0defcdb61c6832b705b45fac590024bf447107/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L601-L609

**Question/Problem 2**

Own EFCore-provider for Firebird overrides VisitOrdering and provides correct generation:

https://github.com/FirebirdSQL/NETProvider/blob/94128e044e3ec7bdd19cb84c16cb216bb74932f6/Provider/src/FirebirdSql.EntityFrameworkCore.Firebird/Query/Internal/FbQuerySqlGenerator.cs#L226-L235

Plus, it processes SqlFragmentExpression with "(SELECT 1)" text.

As I undestood, this fragment generated in SqlExpression.AddJoin:

https://github.com/dotnet/efcore/blob/3a0defcdb61c6832b705b45fac590024bf447107/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs#L1984

Why SelectExpression generates/defines SQL without information about target DBMS?

May be better use special/signal SqlExpression-class for "(SELECT 1)" statement (SqlSelectOneExpression?) and process it instance at QuerySqlGeneration layer?

---
Yes, of course. I will override VisitOrdering and write code like FB-provider.

But I hope, future version of EFCore allow exclude this work.

**Comment by dmitry-lipetsk** [comment]
About point 2.

If I right about SqlExpression.AddJoin, may be better generate OrderingExpression with SqlConstantExpression(1) ???

**Comment by roji** [comment]
> may be better generate OrderingExpression with SqlConstantExpression(1) ???

`ORDER BY 1` refers to the first column in the projection, rather than the constant 1.

> Why SelectExpression generates/defines SQL without information about target DBMS?

We do our best to not build in assumptions, but unfortunately we don't know about all the restrictions of all databases in the world... But we can definitely make this better for Firebird in EF 7.

**Comment by smitpatel** [comment]
For `SELECT 1` in VisitOrdering, override the method and inject whatever is suitable for the database. We have done what is suitable for most database providers. The method is not really complicated. Providers which intend to do anything different should override that method only. We don't think that GeneratePseduoFromClause fits in design there since the intention is not to inject a select expression there but print out something valid which would have been invalid otherwise.

For AddJoin method, we cannot inject anything else due to service dependencies and lack of having service there. I have thought about that in detail and the reason ordering is needed for deterministic behavior and we don't really have alternative without bringing huge perf penalty. That is also place where we cannot consult providers to give us what is valid. Providers which doesn't work with that construct are required to write a QueryTranslationPostProcessor visitor to capture it and replace it with whatever is suitable for them. It only appears inside RowNumberExpression. For most database it requires ordering to be specified always (hence we have to inject `SELECT 1`). Providers should replace it with whatever is suitable for their database.
