### ISSUE TITLE
What is the recommended way to do DDD Value Objects in EF Core?

### ISSUE THREAD

**Issue by rantri** [dotnet/efcore#26065]
Hi,

In @JeremyLikness blog post: "[The Plan for Entity Framework Core 6.0](https://devblogs.microsoft.com/dotnet/the-plan-for-entity-framework-core-6-0/)" there is a section about Domain-Driven Design Value Objects:

![image](https://user-images.githubusercontent.com/705616/133593750-8839c3fb-443f-4103-81ca-6b77d23c4e02.png)

In EF6 I used Complex Types for value objects.  I thought that owned entities is the way to do ValueObjects in EF Core.
Owned entities is the approach recommended in: "[.NET microservices - Architecture e-book](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects)".

Why owned entities are not a good fit?
What is the recommended way to implement Value Objects?

Thank you all for a great product.

**Comment by ajcvickers** [comment]
@rantri See [value object examples](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations#examples). Unfortunately, issues to make this better (#9906 and #13947) had to be punted out of 6.0.

Owned types are not a good fit because they have keys, even though the key might be hidden. This results in non-obvious behaviors when value objects are used as if they did not have keys. See [this comment](https://github.com/dotnet/efcore/issues/18007#issuecomment-590008098) and the linked issues for some more discussion.

**Comment by Javid-underwater** [comment]
@ajcvickers https://chunkypng-magical.github.io/MMwj7gkbo7/
