### ISSUE TITLE
InMemory: Owned navigation for required dependent can generate join

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#26214]
In #26213 we are making it always generate left join since inner join would dependent on owner's nullability which is not available right now in the method which determines join vs left join. We can pass owner nullability from caller which has entity shaper expression. This would pubternal API break so deferring to next release.

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.
