### ISSUE TITLE
Table splitting: Make HasColumnName optional

### ISSUE THREAD

**Issue by TrymBeast** [dotnet/efcore#26345]
Hello!

When configuring table splitting I would like not to need to specify the name of the column in the database if the property name of the entity matches the name of the column.

As per the [documentation](https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting) this is needed, and after trying it I know it is, but I don't understand why if normally we don't need this.

For example, this configuration:

```
modelBuilder.Entity<DetailedOrder>(
    dob =>
    {
        dob.ToTable("Orders");
        dob.Property(o => o.Status).HasColumnName("Status");
    });
```

should be:

```
modelBuilder.Entity<DetailedOrder>(
    dob =>
    {
        dob.ToTable("Orders");
        dob.Property(o => o.Status);
    });
```

Without the need to use the HasColumnName.

Thanks!

**Comment by ajcvickers** [comment]
@TrymBeast The default behavior is to map properties with the same name but from different classes to different columns in the database. This is because the properties are not necessarily conceptually the same, and may map to columns with different store types or facets. This behavior is overridden by explicitly mapping both the properties to the same column.

In retrospect, it would probably have been better to map compatible properties (i.e. same type and facets) to the same column. However, it is not worth breaking the mapping of existing applications in order to do this now.
