### ISSUE TITLE
Provide event that can be used to get notifications when all property changes have been detected

### ISSUE THREAD

**Issue by samuelpsfung** [dotnet/efcore#26506]
Please see attached program. I use a shadow property for one-to-many relationship, and wish to capture changes in ChangeTracker.StateChanged event. When the parent relationship changed, the current value in the event is still the same as the original one.

![image](https://user-images.githubusercontent.com/56810423/139781128-85de878a-3852-4ce2-bf75-1f1961a5614a.png)
[EFEvents.zip](https://github.com/dotnet/EntityFramework.Docs/files/7457600/EFEvents.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329736f5-8463-ec7f-ead6-9ded03dd6f6b
* Version Independent ID: 89098121-5603-26ba-da4d-331aea51f237
* Content: [.NET events - EF Core](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/events)
* Content Source: [entity-framework/core/logging-events-diagnostics/events.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/logging-events-diagnostics/events.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Note for triage: The state changed event happens as soon as an entity is detected as modified, which in this case happens when the Name property is detected as changed. At this time the FK property has not yet been detected as changed. We should consider delaying this event until all properties of the entity have gone through change detection.

@samuelpsfung To answer your second question, cast the `INavigationBase` to an `INavigation`.

**Comment by ajcvickers** [comment]
On further investigation, delaying the event is not appropriate since the state must change when the first property change is detected. However, the new `DetectChanges` events can be used to achieve the desired notification here--see https://github.com/dotnet/efcore/pull/28356
