### ISSUE TITLE
Consider exposing DatabaseFacade.Clean

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#26550]
For using doing integration tests, it may be useful to have an API to delete all the contents of a database (including schema); at that point EnsureCreated can be invoked to create the up-to-date schema. This would typically be faster then doing EnsureDeleted, since database drop/create are typically heavy/slow operations (see discussion in #26541).

(the name `Clean` probably isn't appropriate)

**Comment by ajcvickers** [comment]
@roji Problem with this is doing it reliably when we don't know everything about the database. The DatabaseCleaner we have only needs to cover the things we do in our tests. In the past we have always resisted making it generally available because it's hard to make it always work in the general case.

**Comment by roji** [comment]
@ajcvickers are you referring to stuff like non-table/sequence stuff in the database which we don't manage, and/or various global database tweaks/settings?

Maybe it's reasonable to provide this API with clear documentation on what's covered, and a clear warning that it does not guarantee bringing the database back to the exact same state as after EnsureCreated... After all, for the vast majority of actual users (integration tests), these limitations shouldn't be a concern (as long as tables and sequences are dropped etc.).

**Comment by roji** [comment]
FWIW [in Npgsql](https://github.com/npgsql/efcore.pg/blob/main/test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlDatabaseCleaner.cs#L41) I did make an effort to also clean other stuff: functions, types, extensions, collations... But obviously that also doesn't pretend to be 100% exhaustive.

**Comment by ajcvickers** [comment]
I think we should consider it. It has certainly proved very useful.

**Comment by JonPSmith** [comment]
I copied the SQL Server Clean code into my EfCore.TestSupport library in Version 5 and it has been SO useful. I used it all the time because its really quick (for SQL Server my tests say it 1/2 the time of EnsureDeleted + EnsureCreated) and it picks up EF Core Model changes. I think people would really find these EnsureClean features, but I understand that it means you would need to support it.

One feature I added to my version of EnsureClean is an bool parameter called `setUpSchema` which default to true. This causes the `creator.CreateTables();` to run. By setting `setUpSchema` to false the tables are added, which allows me to test a migration. I don't use this much but when I'm building a migration with SQL in it I find it useful (NOTE: the SQL Server Clean doesn't delete the default named migration history table, but it does delete any differently named migration history tables.

**Comment by roji** [comment]
Thinking about this a bit more.. The actual database schema generally isn't expected to change within a single test run; so there shouldn't be a reason to drop tables; just clearing them out should be perfectly fine (and possibly somewhat faster). So a solution based on PG [TRUNCATE](https://www.postgresql.org/docs/current/sql-truncate.html) or [respawn](https://github.com/jbogard/respawn) seems more appropriate for most cases.

Clean could still be a more efficient way for 1st-time setup of the database, as an alternative to EnsuredDelete/EnsureCreated, since the same database could be reused from a previous test run while rebuilding the table schema.

@JonPSmith what are your thoughts on this? Where do you see Clean as being useful?

**Comment by roji** [comment]
Triage discussion: even if between tests in the same run we just clean data (and not the schema), this is still useful for making the entire test run start up quicker (especially on PostgreSQL) and also more reliably (e.g. on SQL Server, where creating a database sometimes can have an asynchronous component). In other words, we reuse the database from the previous test run, only recreating the schema.

The problem is still that this would handle all types of database objects/settings (e.g. sprocs), and there's a danger we'd have to maintain it and add support for lots of stuff. This may also make sense as a community extension of some sort.

**Comment by JonPSmith** [comment]
Hi @roji,

> The actual database schema generally isn't expected to change within a single test run; so there shouldn't be a reason to drop tables.

It's a balance between of ease of use and the quickest way to create an empty database, with my focus on the second - time to empty the database. Here is my feedback from two approaches

1. **Respawn / truncate + delete all test databases on Model change:**  I original EfCore.TestSupport library was created when I worked on the first book, which based on 2.0, and used this approach. This was fast and because the EF Core Model changed rarely the time it took to delete all test databases (which is quick) and the time to have each test to recreate (took long time) didn't matter.
2. **EF Core Database cleaner:** When I started on the updated book I asked lots of questions and [in one from @ajcvickers ](https://github.com/dotnet/efcore/issues/19635#issuecomment-611006882) he mentioned the SQL Server database cleaner. I added that to EfCore.TestSupport version 5 and used it in the tests in the second book and on other projects. This is nicer because I don't have to delete old test databases, and its QUICK! Also the cleaner also gets rid of other things, like user defined functions etc.

Overall the SQL Server database cleaner approach wins hand-down.

- Its quicker than EnsureDeleted / EnsureCreated
- Its so quick that its not worth trying a Respawn approach
- I handles EF Core Model changes
- It also clean out other stuff, like user defined functions

I haven't implemented the PostgreSQL database cleaner yet, but if that is close to the Respawn approach I already have then using the PostgreSQL database cleaner is the way to go.

**Comment by roji** [comment]
@JonPSmith makes sense, I think we're all aligned here. The main question is whether this belongs as a public API as part of EF Core, or some 3rd-party extension.

**Comment by roji** [comment]
After thinking about this some more, it indeed doesn't seem like this belongs in EF Core:

1. Resetting a database could be just as useful to non-EF applications.
2. There are probably (considerably) more efficient ways to reset a database than to reverse engineer it and then drop tables/sequences one by one.

**Comment by ajcvickers** [comment]
Closing; better done outside of EF.
