### ISSUE TITLE
Null semantics compensation missing for LIKE negation

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#26735]
When negating `EF.Functions.Like`, we don't add null compensation, so `EF.Functions.Like || !EF.Functions.Like` does not yield the full set of rows.

```c#
var blog = await ctx.Blogs.Where(b => EF.Functions.Like(b.Name, "f%")).SingleAsync();
Console.WriteLine($"Blog {blog.Id}: {blog.Name}");

var blogs = await ctx.Blogs.Where(b => !EF.Functions.Like(b.Name, "f%")).ToListAsync();
Console.WriteLine($"Blogs: {blogs.Count}");

blog = await ctx.Blogs.Where(b => b.Name == null || !EF.Functions.Like(b.Name, "f%")).SingleAsync();
Console.WriteLine($"Blog {blog.Id}: {blog.Name}");
```

**Comment by joakimriedel** [comment]
Isn't this quite expected, since a "Name not like 'f%'" SQL statement will not returns rows where `Name` is null?

However, if I want the null rows to be returned the only workaround from C# world I've found is to do `Where(b => !EF.Functions.Like(b.Name ?? '', "f%"))` to translate to `not (COALESCE(Name, '') like 'f%')`  (in MS SQL I believe `ISNULL` would be better since it has stricter nullability but it's not in `EF.Functions`)

**Comment by smitpatel** [comment]
Looking at current processing, when `!` is applied to any term we try to push it inside if the term is non-nullable (2-value logic). If the inner term is nullable then we leave the not operator as is. With that implementation, `something OR !something` may not give all results if something is nullable.
@maumar should know reason behind why we don't try to convert something to 2-value logic to apply `!` operator over it.
