### ISSUE TITLE
Query performance decrease when updating from 2.1 to 5.0

### ISSUE THREAD

**Issue by mtomberger2** [dotnet/efcore#26747]
### Problem description

I have a .NET Core 2.1 application I would like to upgrade to .NET 5.0. Behind this application there is a database accessed with EntityFramework Core 2.1. Within this database there are manually encrypted columns with strings. There are some queries for these columns with operations like .StartsWith(), .Contains etc. These operations are case insensitive.

In EntityFramework Core 2.1 queries like this
```
IQueryable<Employee> query = context.Employee;
var emp = query.FirstOrDefault(q => string.Compare(EncryptionService.Decrypt(q.Name).ToLower(), searchEmpName) == 0);
```
were solved with client evaluation which means, every row of the Employee table will be loaded and the condition will be applied afterwards. 
For 10000 values (see: minimal reproducible example below) this took approx. 40 ms on my machine and only the found entry was attached to the ChangeTracker. 

After the upgrade to .NET EF 5.0 this query throws a InvalidOperationException.
When I try to regain the old functionality by loading all entries from the db it will take approx. 80ms on my machine and all 10000 values will be attached to the ChangeTracker.
```
Employee e = null;
try {
    e = query.FirstOrDefault(q => string.Compare(EncryptionService.Decrypt(q.Name).ToLower(), searchEmpName) == 0);
} catch (InvalidOperationException ex) {
    e = query.ToList().FirstOrDefault(q => string.Compare(EncryptionService.Decrypt(q.Name).ToLower(), searchEmpName) == 0);
 }
```

Because there are encrypted values in the database and queries accessing only part of the decrypted values, such as .StartsWith(), exist and the comparison is case insensitive comparing the encrypted given string with the value in the database is not possible. Additionally the queries executed in my real world application come from varying different sources, some of which are out of my reach.  

Edit: The real world application uses the repository pattern to access the database, so sometimes the returned entities are changed and persisted. Therefore its not possible to use .AsNoTracking()

**How can I regain the old functionality without doubling the query execution time and overcrowding the ChangeTracker?**

### Additional info
EF Core version: 2.1 / 5.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  NET Core 2.1 / .NET 5.0
Operating system: Windows 10 Home
IDE: Visual Studio 2019 16.10.3

### Minimal reproducible example

[EfCoreUpgradeExample.zip](https://github.com/dotnet/efcore/files/7562956/EfCoreUpgradeExample.zip)

**Comment by ErikEJ** [comment]
Use AsNoTracking ?

**Comment by mtomberger2** [comment]
@ErikEJ The found entity will sometimes be changed and saved in the real world application. I forgot to mention that in the issue

**Comment by ErikEJ** [comment]
Raw SQL / stored proc?

**Comment by OpenSpacesAndPlaces** [comment]
Have you tried creating an indexed column with a salted hash and then just do direct DB lookups?
string searchEmpNameHash = Hash(searchEmpName);
query.FirstOrDefault(q => q.NameHash == searchEmpNameHash).ToList();

As long as you don't need partials and this doesn't invalidate any security requirements you have, should work better.

**Comment by mtomberger2** [comment]
In my application some queries search for parts of the encrypted values, only the minimal example does not. The application uses .StartsWith(), .Contains() etc. inside the queries

**Comment by OpenSpacesAndPlaces** [comment]
Other question would be - have you looked at using ValueConverters for encryption instead of layering into the business logic?

e.g. in your model setup
entity.Property(p => p.Name).HasConversion(new EncryptionValueConverter());

Wondering if that would help performance.

**Comment by roji** [comment]
@mtomberger2 to make EF Core 6.0 do the same thing you were doing with client evaluation on EF Core 2.1, use AsEnumerable, not ToList:

```c#
e = query.AsEnumerable().FirstOrDefault(q => string.Compare(EncryptionService.Decrypt(q.Name).ToLower(), searchEmpName) == 0);
```

ToList buffers all results (taking up lots of memory client-side, while AsEnumerable streams them ([see docs on this](https://docs.microsoft.com/en-us/ef/core/performance/efficient-querying#buffering-and-streaming), I'd advise giving the section a good read in general). BTW I'm not sure what the try/catch are doing there - the first invocation inside the try is guarantee to throw because of untranslatability.

Aside from that, this will still track a potentially huge number of entities in change tracking - just as in EF Core 2.1. One possible  idea would be to first do a non-tracking query to find your specific row, and then load that again via a change-tracking query. This would still download the entire table to the client, but would at least do change tracking only on a single row.

However, the general approach of downloading the entire table is obviously not great. I'd recommend looking at [SQL Server Encrypted Columns](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine?view=sql-server-ver15#feature-details), which at least in some configurations allow indexing and efficient filtering over encrypted columns (see secure enclaves).

**Comment by smitpatel** [comment]
In order to get exact same change tracking behavior from 2.1 era, you would need to query using `AsNoTracking` explicitly and then attach the entities to change tracker manually. See how to attach docs here https://docs.microsoft.com/en-us/ef/core/change-tracking/explicit-tracking#attaching-existing-entities

While the ability to track only after applying client filter worked in this case, it didn't work in all case causing entities to be not tracked properly after client eval hence along with client eval we removed the whole logic of it. Also in the absence of client eval, there is no 2 different points where the entities differ in query causing question which point we should add tracking.

Beyond above, specifically for perf, EF Core when doing client eval didn't materialize the entity fully unless needed to so it passed off the column value to client function and if the filter returned true then only materialized the entity instance. Doing manual client eval that won't be the case since it will materialize the entity (since you are asking for it in the query) before running the filter on client side. This kind of differences are expected. As @roji mentioned `AsEnumerable` will help in this case. Nothing else we can do here.
