### ISSUE TITLE
Improve experience for data binding and graphical interfaces

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#26799]
EF Core is designed to work well with data binding scenarios, such as when used with Windows Forms or .NET MAUI. However, connecting the dots between these technologies is not always easy. For EF7, we plan to improve the experience with both work in EF Core and in Visual Studio to make it easier to connect the dots.

**Comment by bricelam** [comment]
The primary work for this issue is to re-enable the Visual Studio tooling to work in more-or-less the same way it used to work on .NET Framework.

Our [WPF tutorial](https://docs.microsoft.com/en-us/ef/core/get-started/wpf) provides good guidance for databinding in XAML-based frameworks. We'll probably use that as the foundation for thinking about data binding in MAUI and WinUI. See also https://github.com/dotnet/EntityFramework.Docs/issues/2541

**Comment by ajcvickers** [comment]
Update: verified that WinForms and MAUI work well now. Walkthrough for WinForms has been completed. MAUI demo created and presented; convert to walkthrough tracked by https://github.com/dotnet/EntityFramework.Docs/issues/3984

**Comment by janseris** [comment]
Hi, there is an important issue to this and that is that EF Core cannot be used in .NET MAUI on Android 8.1 and lower due to their SSL error and noone seems to do anything about it even if I reported it on MAUI, SqlClient etc.

**Comment by roji** [comment]
@janseris we're well aware of this issue, but there's nothing we can do about it in EF Core - it's a problem in SqlClient (and not related to data binding or graphical interfaces).
