### ISSUE TITLE
Where_TimeOnly_subtract_TimeOnly using TimeOnlyTypeMapping for TimeSpan constant

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#26864]
For some reason when running `Where_TimeOnly_subtract_TimeOnly` the `GenerateNonNullSqlLiteral` for `new TimeSpan(0, 0, 15, 50, 500)` is called on `TimeOnlyTypeMapping` instance instead of `TimeSpanTypeMapping`. And I'm kind of lost why. Any pointers?

**Comment by cincuranet** [comment]
Hmm, when I change the test to this (extracted the `TimeSpan` out as a variable):
```csharp
public override Task Where_TimeOnly_subtract_TimeOnly(bool async)
{
	var timeSpan = new TimeSpan(0, 0, 15, 50, 500);
	return AssertQuery(async, (ISetSource ss) => (from m in ss.Set<Mission>()
													where m.Time - new TimeOnly(10, 0, 0) == timeSpan
													select m).AsTracking(), null, null, assertOrder: false, 1, "Where_TimeOnly_subtract_TimeOnly");
}
```

The type mapping is properly `TimeSpanTypeMapping`. 

Looks like for `SqlConstantExpression` the type mapping is incorrect. Where am I doing something wrong? 🤔

**Comment by roji** [comment]
Yeah, EF Core's default handling of the subtraction (and addition) operator assumes that the result type of the binary expression is the same as the operands (e.g. int - int = int), so at least in Npgsql I have [special logic](https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs#L345) to to recognize date/time subtraction. At least for the time being, you can duplicate that.

@smitpatel I think we discussed bringing this into relational a long time ago, any thoughts?

**Comment by cincuranet** [comment]
I understand what you are saying about subtraction. But my problem is the right side of equality operator. 

Or are you saying that the type of right side of equality here is inferred from the left side? That seems weird, given the right side is constant (in terms of SQL).

**Comment by roji** [comment]
> Or are you saying that the type of right side of equality here is inferred from the left side? That seems weird, given the right side is constant (in terms of SQL).

Yep, that's precisely why we're inferring from left to right. Constants and parameters have no type mapping - only a CLR type. So to know what database type needs to be represented we infer from the other side, where there's a column with a definite type mapping.

Concretely, in this case the type mapping comes from m.Time, bubbles up through the subtraction (where in your case the wrong return type gets inferred - TimeOnlyTypeMapping instead of TimeSpanTypeMapping), and gets applied to the other side of the comparison, i.e. to the TimeSpan constant.

**Comment by cincuranet** [comment]
OK. Thanks. At least it's not a bug somewhere in my code. 

I'll implement some extra logic later as Firebird has few quite weird rules/limitations for direct DATE/TIME computations. For now I want to finish support for EF Core 6 and I'm sweeping couple of failing tests.

**Comment by roji** [comment]
Reopening to see if we want to bring in date/time inference logic (subtraction/addition) into relational.

**Comment by roji** [comment]
So PostgreSQL and Firebird support datetime subtraction, SQL Server and SQLite do not. MySQL/MariaDB do support it, but return an int result whose meaning isn't completely clear.

So I guess I'm on the fence... It could still make sense to introduce this inference logic as the sane default, to be overridden in the case of MySQL where something "special" occurs. But I guess we can also let each provider handle it.

**Comment by cincuranet** [comment]
@roji In case you want to check the Firebird sub/add rules, it's [here](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-datatypes-datetimeops).

**Comment by roji** [comment]
@cincuranet thanks... though I'm now seeing that `TIMESTAMP - TIMESTAMP` returns a number ("Number of days and part-day, within the range DECIMAL(18, 9)") rather than some sort of interval type that could map to .NET TimeSpan (like on PostgreSQL). In that sense Firebird may resemble MySQL/MariaDB more than PG.

Keep this in mind when copying the code from PG, since things aren't the same...
