### ISSUE TITLE
How to make a database able to use migrations, in code, after it was created using EnsureCreate

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/efcore#26870]
We are using EF Core 5.

We have a databases for a product that were created using **EnsureCreated**. We have added migrations to the
product. We need to migrate in code, so we use the Migrate, which is great. I did the migrate and nothing happened. Come to find our databases created using **EnsureCreated** cannot be migrated. How can we update databases in the field, in code, so that we can call **Migrate**?

**Comment by ajcvickers** [comment]
@dgxhubbard This is essentially the same as having an existing database that you then want to start using migrations with. We are tracking #2167 to make this better, and also https://github.com/dotnet/EntityFramework.Docs/issues/91 to document it.

The general approach for this is to create an initial migration, and then to edit that migration and remove all the code from the `Up` method. (You can optionally also remove the code from the `Down` method.) For example:

```C#
public partial class StartingPoint : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}
```

When this migration is applied, it won't change the database (since the database is already in the correct state anyway) but it will create the `__EFMigrationsHistory` table. Also, the model snapshot in code is in the correct state to track new changes. This means additional migrations can then be added in the normal way.

**Comment by santosh-jallapuram** [comment]
@ajcvickers this helped me. thanks for this tip One quick question. Should we remove the content of the `BuildTargetModel` as well in the partial class same like `Up`  and `Down`?

**Comment by ajcvickers** [comment]
@santosh-jallapuram Not sure; @bricelam?

**Comment by dgxhubbard** [comment]
@ajcvickers 
I am not looking for "having an existing database that you then want to start using migrations with". What I am looking for is generating and applying migrations using a namespace and assembly. I finally understand the multiple provider case in a single assembly. The user has to generate and apply migrations using a separate context for each provider. What I would like as a feature is the user specifies a connection string to generate migrations, and connection string, namespace and assembly to apply a migration. This would remove DbContext from migrations and I feel simplify generating and applying migrations.

**Comment by dgxhubbard** [comment]
@ajcvickers 
It would be great if migrations could start being used with databases created from EnsureCreated.

**Comment by bricelam** [comment]
> Should we remove the content of the BuildTargetModel as well in the partial class same like Up and Down?

That code will only be used if you try to `dotnet ef migrations remove` the second migration, so yeah, probably safe to delete.
