### ISSUE TITLE
Ask EF Core to provide a method of replacing parameterization in generating SQL statements

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#26880]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/请EF-Core最新版本提供生成SQL语句中替换参数化的方法/1538315)._

---
[regression]
Please provide EF Core to generate a parametric method in the SQL statement to replace, directly to the SQL statement assignment query, rather than generating a parametric SQL statement query. Similar to: select from A where A.Id=@id, you can get the real statement directly: select s from A where A.Id=2, assigned statement.

---
#### Feedback Bot on 9/24/2021, 01:51 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.</p>

**Comment by roji** [comment]
We're going to need a bit more details and context on this. It seems like you're asking to be able to tell EF Core to send constants embedded in the SQL (`SELECT ... WHERE x=2`), instead of parameters (`SELECT ... WHERE x=@id`).

If this is what you're looking for, then you can already control this by how you write your EF LINQ queries.

Values which are inlined into the LINQ query get generated as constants in the SQL:

```c#
var blogs = context.Blogs.Where(b => b.Id == 2).ToList();
```

... whereas C# variables get generated as parameters:

```c#
var id = 2;
var blogs = context.Blogs.Where(b => b.Id == id).ToList();
```

It's important to note that parameterization can be crucial for performance, as multiple queries with different parameter values can share the same query plan, prepared statement, etc. When constants are embedded into the SQL, this is not possible.

**Comment by gallop1** [comment]
@roji It's not like this. I think you don't need parameterized parameters in the SQL statement generated by LINQ with parameters. You can directly replace them with values, similar to = @ ID, which can be replaced with = 2. In this way, you don't need to replace the generated SQL statement values manually, which is convenient for query in database tools

**Comment by roji** [comment]
@gallop1 see my note above about performance. If we replace `= @ID` with `= 2`, query performance would be decreased very significantly, as each SQL would be different and have its own query plan. Please take a look at articles such as [this one](https://www.mssqltips.com/sqlservertip/2981/using-parameters-for-sql-server-queries-and-stored-procedures/) which explain the importance of parameterization.

You'd probably be interested in [ToQueryString](https://blog.oneunicorn.com/2020/01/12/toquerystring/), which generates runnable SQL for a LINQ query.

**Comment by gallop1** [comment]
@roji OK ,thanks. yes,I want you introduce.

**Comment by gallop1** [comment]
@roji Does EF6 also provide a ToQueryString method? I hope that EF6.0 of the.NET Framework also adds this method.  So I can use it on different platforms.

**Comment by roji** [comment]
I'm not an expert on EF6, but it has [ToTraceString](https://stackoverflow.com/questions/1412863/how-do-i-view-the-sql-generated-by-the-entity-framework) which is similar.
