### ISSUE TITLE
Is there a good reason why support for cascading updates has not been added?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#26894]
I'm developing an application with a database schema that really calls for a string primary key with a couple of related tables that use that same value as a foreign key.

But, because Entity Framework doesn't support cascading updates, this means my application wouldn't be able to update that primary key.

This column must be editable and so I'm unable to proceed because I'm using Entity Framework.

It seems like it would be straight forward enough to implement cascading updates.

    builder.HasMany(c => c.ClmImportRules)
        .WithOne(ir => ir.Company)
        .OnUpdate(UpdateBehavior.Cascase);

I suspect this has been discussed before. If there are links to some discussions about this that explain why it can't be done, I would appreciate seeing those.

*Note: For my design, I realize I could add an integer primary key and use that as the foreign key in related tables. But without going into too many details, I need to quickly get the same value from those related tables. In some cases, the FK is nullable. After playing with this a while, it really would be much better to have the string value as the foreign key.*

**Comment by ajcvickers** [comment]
Specifying cascade updates is tracked by #21563. It hasn't been implemented yet because, as with all software development, we have limited resources and so must prioritize what we work on. Currently, #21563 has only four votes; make sure to add your vote. The [release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) in our documentation provides some insight into how we decide what to work on.
