### ISSUE TITLE
Applying type mappings in translators

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#26891]
Is there some rule of thumb when/where the `ApplyDefaultTypeMapping` (and related) should be called in _translators_? I don't seem to have a firm grasp on the rules and sometimes end up with `Expression 'XXX' in the SQL tree does not have a type mapping assigned.`.

**Comment by smitpatel** [comment]
So the `SqlExpressionFactory` has default rules regarding how to apply type mappings. e.g. Most binary operations copy it over from the other side. Sql function arguments would take default type mapping if not assigned (since there is no inference). A translator would need to apply type mapping (default or inferred one) when it doesn't match the default rules.

Flip side it is never harmful to assign type mappings in translators. The default inference logic short-circuits if type mapping is already set. It is just a short hand to not assign in translator if default code is going to do the same.

Few reasons you may be running into the error like that
- New-ing up the SqlExpression rather than using SqlExpressionFactory.
- Provider derived SqlExpressionFactory not assigning type mappings recursively and correctly for custom nodes
- Assigning type mapping on outer level when inner subtree doesn't have type mappings assigned. Due to short circuit logic, if a node has type mapping we don't evaluate its children.

**Comment by cincuranet** [comment]
Is there some extra logic after [this](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/SqlExpressionFactory.cs#L444) that would apply the mappings? I see the defaults applied to arguments, but not the function itself (and some of these functions are failing for me now - that said, I can apply the mappings on my side, just curious).

**Comment by smitpatel** [comment]
If a function being compared to another column/value then function would take type mapping from other side (just like normal type mapping inference in binary) so function itself doesn't apply type mapping on itself unless passed as argument in the method. Any expression which comes for transltion in SqlTranslatingExpressionVisitor will be applied a default type mapping at top level since there is nothing else to infer that. In between those it is all about inferences.

**Comment by cincuranet** [comment]
Thanks.
