### ISSUE TITLE
In memory provider does not throw when navigation property is null

### ISSUE THREAD

**Issue by rajmondburgaj** [dotnet/efcore#26987]
Maybe this is answered somewhere else or maybe it is by design but was kind of hard to find out what was the issue:

So, I am using entity framework core 6.0.0 + Asp.Net Core 6 + In memory provider to run my unit tests.

Here are my models.

```c#
class A
{
   //properties
  public virtual ClassB MyClassBInstance { get;set; }
}

class B 
{
   //properties
   public virtual ICollection<ClassA> ClassAInstances { get; set; }
}
```

If I add some mock values in the db context for type class `A` and add none for type class `B` and run this query it does not throw but returns 0 values.

```c#
var result = await _dbContext.MyAClassInstances.Where(x => x.Id == request.Id).Select(x =>
                    new MyModel
                    {
                        //property mappings here    
                        CreatedBY = x.MyClassBInstance.CreatedBy
                    })
                .OrderByDescending(x => x.Created)
                .ToListAsync(cancellationToken)

```

but if I run this now:

```c#
var result = await _dbContext.MyAClassInstances.Where(x => x.Id == request.Id)
                    .AsEnumerable()
                    .Select(x =>
                    new MyModel
                    {
                        //property mappings here    
                        CreatedBY = x.MyClassBInstance.CreatedBy
                    })
                .OrderByDescending(x => x.Created)
                .ToList()
```

it throws as expected complaining that class `MyClassBInstance` instance is null therefore you can not access `CreatedBy` from it.

Would it make sense to check and throw exception in the first case as well, considering I am trying to access a `MyClassBInstance` instance which should be null ?

I know that somehow it was my mistake in the first place for not seeding the data in the right way but this may happen by mistake and then the unit test might run successfully without knowing some exception is thrown-caught(maybe!) internally without letting the user know about it.

**Comment by ajcvickers** [comment]
@rajmondburgaj In the first case, EF is not executing your code directly. It is instead taking the expression tree generated by the C# compiler and translating it into an appropriate query to run against the database.  For real databases, checking for nulls in the way .NET does makes no sense (and isn't even really possible) in the generated SQL. So EF instead does "null compensation", such that simple queries can be written in LINQ and executed in SQL without excessive null checks in the LINQ code or very weird and non-optimal SQL generation. EF does the same thing for the in-memory provider so that the same kinds of queries work against all database providers.

In the second case, the `AsEnumerable` call turns this into a LINQ-to-Objects query, which is not translated by EF Core and is instead directly executed by the CLR.

**Comment by rajmondburgaj** [comment]
Hi @ajcvickers , thanks a lot for the reply. I guess this:

>> EF does the same thing for the in-memory provider so that the same kinds of queries work against all database providers

answers my question and it makes sense actually.
