### ISSUE TITLE
Fluent API : property.HasMinLength()

### ISSUE THREAD

**Issue by russia** [dotnet/efcore#27052]
We already have .HasMaxLength(), but it is impossible to define a minimum length of a given property without using an attribute.
Maybe there is a good reason for it? (if so I wonder what could it be)

I haven't seen anyone suggest the HasMinLength() : https://github.com/dotnet/efcore/search?q=HasMinLength

So simply allow us to do : 
```cs
myEntityTypeBuilder.Property(myEntity => myEntity.myProperty)
            .HasMaxLength(50)
            .HasMinLength(10);
```
or :
```cs
myEntityTypeBuilder.Property(myEntity => myEntity.myProperty)
            .HasLength(10, 50);
```

**Comment by ajcvickers** [comment]
@russia `HasMaxLength` is used to set the maximum size of the database column, and to configure parameters appropriately so that they behave efficiently. There isn't an equivalent thing for `HasMinLength` to do, except possibly set a `CHECK` constraint in the database, which is discussed in #22180 and implemented here for the attribute: https://github.com/efcore/EFCore.CheckConstraints/issues/19.

Is there something else that `HasMinLength` would be used for?

**Comment by russia** [comment]
> @russia `HasMaxLength` is used to set the maximum size of the database column, and to configure parameters appropriately so that they behave efficiently. There isn't an equivalent thing for `HasMinLength` to do, except possibly set a `CHECK` constraint in the database, which is discussed in #22180 and implemented here for the attribute: [efcore/EFCore.CheckConstraints#19](https://github.com/efcore/EFCore.CheckConstraints/issues/19).
> 
> Is there something else that `HasMinLength` would be used for?

You are right, there is no minimum length constraint for strings.
I should have done more research on this topic, I'm closing thank you.
