### ISSUE TITLE
How to Unit-Test provider specific functions

### ISSUE THREAD

**Issue by bw-flagship** [dotnet/efcore#27085]
## How to Unit-Test provider-specific functions?

I use efcore to query an SQL-Server. For some cases it is required to use functions which are only available in SQL Server, e.g. DateDiffMinute() or Contains().
If I use such a function, I cannot test the code in SQLite or InMemory, because the functions dont work there.
How do I write tests for that code?

```C#
query.where(b => EF.Functions.DateDiffMinute(
                    b.OpeningAt,
                    b.ClosingAt
                )
```

### Provider and version information
EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: MacOs (Arm)
IDE: (e.g. Rider for Mac)

**Comment by roji** [comment]
@bw-flagship there is indeed no way to test provider-specific functions when using InMemory or SQLite. Your two options are to either run tests against a SQL Server instance (which may be easier/better than it sounds!), or to introduce a repository layer above EF Core which you can stub out in your unit tests.

We have some documentation improvements on this subject, you may be interested in them: #3539

**Comment by bw-flagship** [comment]
@roji Thanks for the response, it makes sense and you can mark this as closed.

I still think that it would be a great feature to allow provider-specific-functinos to be mocked - in case this is the right place, we could transform this question issue into a feature-request.

**Comment by roji** [comment]
> I still think that it would be a great feature to allow provider-specific-functinos to be mocked - in case this is the right place, we could transform this question issue into a feature-request.

The question is what exactly this would mean.

One way to interpret this, is that it should be possible to invoke "fake" implementations of SQL Server functions, i.e. have EF.Functions.DateDiffMinute somehow work as expected when executing queries against SQLite or InMemory. That's not feasible for many reasons: SQLite is a full-fledged EF Core provider, with its own support and specific translation for functions (InMemory too, in a way); we cannot start to have SQLite magically start to behave like SQL Server, recognizing functions which are specific to SQL Server. InMemory is similar - making SQL Server functions work on InMemory means replicating the entire functionality set of the SQL Server provider as a mode in InMemory, which we'd therefore also need to do for other providers (PostgreSQL, MySQL...); we'd also have to guarantee that the SQLite/InMemory implementations conform to the SQL Server implementation that they're faking; this simply isn't practical (thing of functionality like full-text search).

Another way to interpret it, is to give some sort of hook for users to "stub" out these functions, i.e. users would provide the result to be returned by EF.Functions.DateDiffMinute, when it's encountered in a query. This is theoretically possible - some sort of hook could make EF Core place a simple user-provided constant in the query tree where it sees an invocation to EF.Functions.DateDiffMinute. But as with mocking frameworks, we'd need to provide some sort of API to express which result to provide given which parameters, etc. - this get complex very fast.

Finally, even if we did this, InMemory would still be unusable for cases where transactions or raw SQL is used, and SQLite would still be unusable where raw SQL is used that's not quite the same across SQL Server and SQLite (there are other examples of incompatibilities). At that point one must ask why not simply test on SQL Server, rather than trying to force SQLite to behave like SQL Server...

**Comment by bw-flagship** [comment]
This makes lots of sense!
I found a (not so great) workaround now.

I create an interface like
``` csharp

public interface ISqlFunctionService
{
    public Expression<Func<Domain.Models.Availability.DayBusinessHours, int>> MinutesOpened { get;  }
}

```

And a class like

``` csharp

public class SqlServerFunctionService : ISqlFunctionService
{
    public Expression<Func<Domain.Models.Availability.DayBusinessHours, int>> MinutesOpened =>
        b => b.ClosingAt == null
            ? 1440 - EF.Functions.DateDiffMinute(new TimeSpan(0, 0, 0, 0)
                , b.OpeningAt
            )
            : EF.Functions.DateDiffMinute(
                b.OpeningAt,
                b.ClosingAt
            )!.Value;
}

```

Inside other methods I can use the expression like that:

``` csharp
return query.SelectMany(x =>
            x.Office.BusinessHours.Where(
                b => b.DayOfWeek == dateTime.DayOfWeek
            ).AsQueryable().
                Select(_sqlFunctionService.MinutesOpened)
        );
```
I can write mocks for that class and use the mocked version in UnitTests via dependency injection.

However, there remains untested logic inside the SqlServerFunctionService.
I did not find a way to mock an expression which takes not the model-class but two TimeSpans as parameters, so I can put more logic inside the tested code.

**Comment by roji** [comment]
@bw-flagship the above works since the thing being mocked is the entire lambda being passed into Select. However, frequently what you want to stub out/mock is just a single function invocation inside that lambda. Consider a more complex case like this:

```c#
var blogs = ctx.Blogs.Where(b => EF.Functions.DateTimeMinute(...) && .Functions.DateTimeMinute(...) && somethingElse)...
```

You want to be able to stub out each invocation of DateTimeMinute - possibly with different results, e.g. based on the parameters they get (as is standard with regular mocking frameworks). You also *don't* want to stub out `somethingElse` - this is just regular query code which should be executed as-is (on SQLite or InMemory).

In addition, your approach above forces you to change product code in a significant way so that the mocking can take place. This isn't a problem in the general sense (for examples, programs frequently use DI so that mocking becomes possible), but IMHO that this specific degree of invasiveness is too much.

Finally, if you're set on doing unit testing here (i.e. not involving SQL Server), another way to approach this is to not try to stub out/mock bits and pieces inside the query (i.e. the DateTimeMinute calls), but rather the entire query. This is what the repository pattern would do - you'd have an abstraction over the entire query, where the production implementation calls the EF query (with DateTimeMinute), and the test implementation stubs out the entire query. This allows you to take EF Core out of the story altogether and provide the desired test results directly to your program code.

**Comment by bw-flagship** [comment]
The repository pattern is not an option, since 90% of my logic is about building a very complex query.
Yes, I see there is no perfect solution as long as I don't take a real SQL Server for my tests.

Thanks a lot for the explanations!
