### ISSUE TITLE
Migrations should go under a root folder called Data

### ISSUE THREAD

**Issue by rustd** [dotnet/efcore#2709]

**Comment by bricelam** [comment]
Not sure if it qualifies as a *breaking* change, but it's been the way it is since Entity Framework 4.3...

**Comment by divega** [comment]
This would only be for MVC apps (based on the default template), and it is just an idea based on feedback that called for the creation of a Data folder for things like the application's DbContext. We could otherwise:

1. Keep Migrations as a top level folder side by side with the new Data folder
2. Not create the Data folder at all and leave the application's DbContext under the Models folder.

**Comment by rowanmiller** [comment]
We want to stay consistent with what we have done in the past. It's also not clear that Data is the right pattern. Even discussing within our team there are various opinions on where things should go:
* Everything under Models
* Just CLR classes under Models and then Migrations and DbContext under Data
* etc.

Developers are free to move the migrations to wherever they want and then any subsequent migrations will be added in the same location.

**Comment by rowanmiller** [comment]
Also worth noting that we haven't heard any significant feedback in the past that folks didn't like where we have been putting them

**Comment by rustd** [comment]
Reopening this issue per the templates review. In RC2 we will update the layout to move migrations to data folder. https://github.com/aspnet/Templates/issues/290

**Comment by rowanmiller** [comment]
We're not going to change this in EF. We have been using Migrations folder for several releases now and haven't had negative feedback. Migrations will still work with the template since we just follow wherever your existing migrations are.
