### ISSUE TITLE
Ef Core update 3.x to 5.x Connection String not working when using localhost ip instead of "localhost"

### ISSUE THREAD

**Issue by JanTrichter** [dotnet/efcore#27112]
## Connection String for 3.x not working after update to 5.x

Hello,
I just encountered a weird issue yesterday. I have a project (.Net core 3.1 Webapi) where I tried to update from EF Core 3.x to 5.x because I wanted to use Filtered Include. The Database Connection wasn't working after the update. I tried to identify with local windows auth. I didn't work probably because I used the localhost ip address (`127.0.0.1`) instead of the `localhost` string. I have EF Core design/tools/sqlserver installed (all the same version).

Here is my Connection string that worked for the 3.1.22 version:
`server=127.0.0.1;user id=user;password=password;database=db;trusted_connection=true;`
_sensitive data has been replaced_

When I try the same connection string in version 5.0.13 I get the following error:
`Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'`

When I replace the ip address of localhost with the string "localhost" it works in version 5.0.13:
`server=localhost;user id=user;password=password;database=db;trusted_connection=true;`
or alternatively:
`Data Source=localhost; Initial Catalog=db; Integrated Security=true`
_sensitive data has been replaced_

Can anyone confirm this? I couldn't find anything related when I searched for it on the internet and I found the solution by chance.

### Versions and Setup

EF Core version: 3.1.22 / 5.0.13
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Core 3.1
Operating system: Windows 10 21H2
IDE: Rider 2021.2.1

**Comment by roji** [comment]
@JanTrichter connection, authentication and SQL Server driver functionality is in general handled by Microsoft.Data.SqlClient - EF Core is built on top of that. Now, EF Core 3.1.22 [uses Microsoft.Data.SqlClient 1.1.3](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/3.1.22), whereas EF Core 5.0.13 uses [5.0.13](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/5.0.13); it's entirely possible that some change there caused this - to confirm this I'd check the release SqlClient release notes over at [their repo](https://github.com/dotnet/SqlClient) and possibly post a question there.

Regardless, I'd strongly recommend upgrading to EF Core 6.0 rather than 5.0 at this point, since 5.0 goes out of support in May, whereas 6.0 is a long-term support release that will be supported until November 2024 ([see here for version and support information](https://docs.microsoft.com/en-us/ef/core/what-is-new/)).

**Comment by JanTrichter** [comment]
@roji thanks for the info. I cannot use EF Core 6.0 though as it would require an update from .Net Core 3.1 to .Net 6.0 which would probably mean a lot of refactoring.
