### ISSUE TITLE
InMemory Database should apply TableNameFromDbSetConvention

### ISSUE THREAD

**Issue by matt-psaltis** [dotnet/efcore#27164]
When using InMemory configuration for Testing vs Relational at Runtime, the EntityType.GetTableName method produces inconsistent results. This inconsistency leads to bugs when developers test against InMemory and then deploy to Relational. I realise there could be further considerations with other Document/NoSql providers.

The TableNameFromDbSetConvention is applied by default on the InMemory provider to produce consistent Table Naming when compared to Relational Providers.

**Comment by roji** [comment]
@matt-psaltis by design, InMemory behaves differently from relational providers - it is not meant (and cannot) provide the same features or behavior as whatever other database system you're using. Consider that EF Core also has non-relational providers (e.g. Cosmos), so making InMemory behave like Relational would be problematic for them. Note also that EntityType.GetTableName is quite a small detail compared to various other relational features which aren't and cannot be supported (transactions, raw SQL, provider-specific methods on EF.Functions...).

This is why we [explicitly discourage](https://docs.microsoft.com/en-us/ef/core/testing/#approach-3-the-ef-core-in-memory-database) using InMemory for testing applications which use EF Core. You may consider using [SQLite in-memory](https://docs.microsoft.com/en-us/ef/core/testing/#approach-2-sqlite) instead, which would be closer as it's relational; but for full fidelity, you must test against your production database system (e.g. SQL Server). An alternative is to introduce a repository layer, which would allow abstracting EF Core altogether and mocking your data access directly.

Note that some documentation is in the works to explain all the above in more detail.
