### ISSUE TITLE
What are the rules that determine which tables gets pluralized and what doesn't?

### ISSUE THREAD

**Issue by reinux** [dotnet/efcore#27171]
Some things in my project are getting pluralized and some aren't:

- AssetBillingRule -> asset_billing_rule
- EquipmentKiosk -> equipment_kiosk
- Facility -> facilities
- Asset -> assets
- MembershipAssets -> membership_asset

I can annotate everything, of course, but I don't understand what's going on or when I can expect it to pluralize and when I can't.

All of these entities are just classes without any additional configuration in the data context.

Edit: Just realized EquipmentKiosk is a joining table, which makes sense. The rest, I don't understand.

EF Core version: 6
Database provider: npgsql
Target framework: .NET 6
Operating system: Windows 11
IDE: VS 2022

**Comment by reinux** [comment]
So it seems to take the name that's given as a DbSet in the data context.

Still not quite sure why it wouldn't pluralize automatically, since not everything is going to have a DbSet and the expected behavior is for table names to be pluralized, but oh well.

**Comment by ajcvickers** [comment]
@reinux 

> Still not quite sure why it wouldn't pluralize automatically

Because pluralizers are frequently updated to correct errors and add new special cases. Each time this is done it creates a breaking change at runtime where existing tables can no longer be found. This is why the EF6 pluralizer was never updated, and hence does a pretty poor job.

Pluralizers are also culture/language-specific, and create a poor experience when on by default for non-US-English developers.
