### ISSUE TITLE
Generated Migration Class Partial Class Division & Name

### ISSUE THREAD

**Issue by brent-russell** [dotnet/efcore#2724]
I have some minor gripes about the generated migration partial classes.

I think the Id property should be part of the main class and not in the 2nd partial. By not putting it in the main partial class, it makes it seem like it's a "second class" member not worthy of being seen by developers. I think it's important enough that it should not be relegated to a partial class. This will also facilitate easier renaming.

I'm not sure what the ProductVersion property is used for or if it is permanent. It seems like a temporary field during the development phase? If permanent, could it be renamed to better reflect that it refers to the EntityFramework product version, and not the end-developer's product version?

It seems like the main purpose of the partial class file is to separate the migration-level target model from the actual migration code. If this is so, it would be nice if the generated file name reflected that better by using a file name like *.TargetModel.cs or *.MetaData.cs instead of *.Designer.cs. The new project structure in VS 2015 supports file nesting in the explorer for any "partial" name variation, not just "designer". "Designer" has a bad connotation due to its association with WebForms, and might imply that it is automatically maintained by VS, which it is not.

I might suggest not using a secondary partial class file at all, and just putting all members in a single class and file. However, I understand that the migration-level target model is an odd case, because it doesn't have relevance for every repository type. If I were to write a migration class on my own from scratch, I wouldn't see the need to divide these elements into a separate file. Although unless I needed true multiple-repository compatibility, I probably wouldn't bother with the migration-level target model at all. And with the migration syntax and model building being as cumbersome as it is compared to something like FluentMigrator, I would much rather use the migration scaffolding.

**Comment by rowanmiller** [comment]
Hey,

Generally speaking we split things up based on "this is your code, you are free to edit it" and then the "you shouldn't really mess with this unless you really know what you are doing" stuff goes in the designer file.

The Id of the migration is also included in the filename, so that is where most people see it. You have to be very careful changing it... it's similar to rewriting history in Git... ok if you *really* know what you are doing... disastrous if you don't :smile:.

We use `.designer.cs` because we don't just work with Visual Studio 2015 but also with 2012 and 2013. Also, from Package Manager Console we can control the nesting, but when running from a command line (such as `dnx . ef ...` in ASP.NET 5) we are just writing files to disk and VS will automatically nest them when named `*.designer.cs`.

> And with the migration syntax and model building being as cumbersome as it is compared to something like FluentMigrator, I would much rather use the migration scaffolding.

Do you have specific examples of what you would like to see improved. We can be quite smart when we scaffold. But in EF7 we are also enabling writing things by hand, in which case you don't need to specify and of the target/source model stuff at all. Those are just things that EF can use smartly when it is responsible for generating migrations.

~Rowan
