### ISSUE TITLE
`scaffold --data-annotations` no longer emits [Required] attributes.  This causes issues running `ef dbcontext script` as required columns are emitted as NULLable

### ISSUE THREAD

**Issue by gatapia** [dotnet/efcore#27270]
EF Core version: 6.0.1
Database provider:  Source: Microsoft.EntityFrameworkCore.SqlServer / Target: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Command Line

Upgrading from .Net Core 3.1 so not sure when this was introduced.

Running: `dotnet ef dbcontext scaffold "connection string" Microsoft.EntityFrameworkCore.SqlServer --data-annotations --no-onconfiguring --no-build --no-build --no-pluralize --project ...` now creates POCOs without the `[Required]` attributes.  It is instead generating nullable types to indicate nullability. 

This is fine.  However, I then use my model to generate SQLite SQL script that I use to initialise my testing database.  This script is now generated with all columns marked as 'NULL' (nullable) even when required.  I generate this script with:
`dotnet ef dbcontext script --context SqLiteContext --no-build --project "<project>" -o "<output file>"`

Is anyone aware of workaround in the meantime, documentation does not mention nullability/required attributes, ideally an option to turn these back on?

**Comment by ajcvickers** [comment]
@gatapia 

> This script is now generated with all columns marked as 'NULL' (nullable) even when required.

Do you have nullable reference types enable for this project?

**Comment by gatapia** [comment]
As part of my migration from 3.1 I am enabling nullable reference types slowly across the projects in my solution.  Since I opened this ticket I had not realised that this was now working.  So you are correct.  At the time of creating this ticket I did not have nullable reference types enabled on some projects.  

Please note that my data model is actually generated across two c# projects so that could play a role in this also.  

I will close this as it appears that the issue was just due to my inconsistent 'nullable' state.

Thanks for the guidance.

**Comment by MikeMcWilliams** [comment]
I just love EF Core.  Been using it for several years and love marrying database projects and the power of scaffolding which offers a huge advantage to kick out models (.cs) files very quickly.  But today I noticed something -- a missing `[Required]` (data annotations attribute) on one of my scaffolded classes.

Below is the scaffolded table `IdentityProfile` table which defines the `TenantId` as a required (not null) column.  As pointed out in earlier in posts above, the scaffolded version of TenantId does not have the `[Required]` attribute;

![image](https://github.com/dotnet/efcore/assets/90723734/f1fce460-df65-4d80-8121-1636e83f7ac6)

Conversely, notice the `EmailAddress` does show the  `[Required]` attribute.
I also noticed that `#nullable` is no longer applied to the output of a scaffolded class definition -- I'm happy that it's gone.

**Quick setup notes**
1. I'm using .Net6, ASP.Net Core, package updates and projects are up to date -- the is new/modern development.
2. A database project defines the schema, deployed to local host (SQL Developer Edition), then...
3. All models in my DbContext are scaffolded using `dotnet ef dbcontext scaffold Name=ConnectionStrings:MyContext Microsoft.EntityFrameworkCore.SqlServer --data-annotations ...`
4. All C# code is generated as the database schema is the source of truth for most rules; meaning no models  are maintained manually.

This is something I would expect from the scaffolding.
![image](https://github.com/dotnet/efcore/assets/90723734/5b9216ba-8d35-47a6-9942-e323ffe8d64d)

However, now that I think about it, I'm thinking that the model probably should look like this:
![image](https://github.com/dotnet/efcore/assets/90723734/cc83f4f7-1217-475f-9410-ea44a617cda3)
In the image above, I edited the code for  `TenantId` is defined as `int?` to prevent `TenantId` from ever being `0' (the default value in C#) but use the '[Required]' annotation during validation. I don't ever remember this being a problem before, but if a client passes a JSON without the `TenantId` defined, the model will have `0` instead of null which is incorrect because business logic would then need to trap it and fail the request outright.    

Is there something I'm doing wrong?  Why the inconsistency with the `[Required]` attribute?  For code readability consistency, the `[Required]` should be wherever the NOT NULL appears on the table definition (.sql file).

Please advise.

**Comment by ajcvickers** [comment]
Please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
