### ISSUE TITLE
ValueConverterAttribute for Smart Enums and simple Value Objects

### ISSUE THREAD

**Issue by PawelGerr** [dotnet/efcore#27313]
I work with Smart Enums and Value Objects quite a lot, which have to be persisted in a database. To do so the classes have to provide a `ValueConverter`. Currently, the ValueConverters can be registered 
* manually via `HasConversion` or in `ConfigureConventions`. Both options require some typing if the model is using dozens of different Smart Enums and Value Objects.
* "automatically" in `OnModelCreating` by iterating over all entities and all properties
* "automatically" by passing some conventions (like PropertyAddedConventions and NavigationAddedConventions) to `DbContextOptionsBuilder`

An ideal solution would be if the developer doesn't have to do anything besides implementing the Smart Enum or Value Object - similar as with `JsonConverterAttribute` or `MessagePackFormatterAttribute`.

The current work flow for JSON is as following:

* The developer installs a [nuget package](https://github.com/PawelGerr/Thinktecture.Runtime.Extensions/wiki/Smart-Enums#getting-started) and implements a Smart Enum or a Value Object.

```csharp
public partial class ProductType : IEnum<string>
{
   public static readonly ProductType Groceries = new("Groceries");
   public static readonly ProductType Housewares = new("Housewares");
}
```

A roslyn source generator kicks in and generates a lot of boilerplate code.

* The developer installs [a JSON-specific nuget package](https://github.com/PawelGerr/Thinktecture.Runtime.Extensions/wiki/Smart-Enums#json-serialization), which comes with another roslyn source generator. The source generator applies the `JsonConverterAttribute` to the Smart Enum/Value Object - the type is *json-serializable* without further configuration.

```csharp
[JsonConverterAttribute(typeof(ValueObjectJsonConverterFactory))]
partial class ProductType
{
}
```

With a `ValueConverterAttribute` it would be the same as with JSON. A source generator could render a few lines of code making the type *convertable*.

```csharp
[ValueConverterAttribute(typeof(MyProductTypeValueConverter))]
partial class ProductType
{
}
```

A more powerfull solution could be an attribute, which provides not just the `ValueConverter` but some other configuration settings as well, like max-length, is-unicode and precision.

```csharp
[ScalarValueAttribute(ValueConverter = typeof(MyProductTypeValueConverter), MaxLength = 20)]
partial class ProductType
{
}
```

**Comment by roji** [comment]
@PawelGerr if you're simply looking for a way to easily bulk-configure a value converter for all properties of a given type, then you'd probably be interested in the new [pre-convention model configuration](https://docs.microsoft.com/en-us/ef/core/modeling/bulk-configuration#pre-convention-configuration) in EF Core 6.0.

Aside from this, you seem to be asking to configure value converters via an attribute (Data Annotation). This approach would be generally limited, since attributes are very constrained in the parameters they allow (essentially only constants); we tend to provide Data Annotations for the simple/restricted cases (e.g. specifying a string column name), but value converters are quite an open case which may not be a good fit.

Given the new pre-convention model configuration which can be used to do the same thing, do you still think an attribute-based approach is important, especially given the added complexity of the source generator to augment the type with it?

As an aside, I'm curious about the pattern of defining a "smart enum" in this way... I understand the desire to pack additional state with the enum (not possible with built-in .NET enum), but this precludes using the enum in standard C# constructs (e.g. switches, pattern matching) and is quite inefficient (heap allocation for each enum instance, could be mitigated by making it a struct).

**Comment by PawelGerr** [comment]
@roji Last topic first :)
* _precludes .. standard C# constructs (e.g. switches, pattern matching)_: one of the reasons the smart enums exist is to **not** needing (error-prone) switch-cases and if-elses - if done right
* _is quite inefficient (heap allocation ...)_: there are no extra memory allocations. if you have 5 enum items, then you have 5 instances altogether. I've [committed a few benchmarks](https://github.com/PawelGerr/Thinktecture.Runtime.Extensions/commit/2cdb8a1792b52585c93135adc43b5e1b4cafe45e) which load 10k entities from the database (SQL Server). The tests are executed for 6 different entities
  * with real C# enum inside, which is persisted as an int
  * with real C# enum having the string-enum-converter
  * with string-based smart enum which is a class (*string-based* means the underlying type is a string)
  * with string-based smart enum which is a struct
  * with int-based smart enum which is a class
  * with int-based smart enum which is a struct

The differences are not worth meantioning
![image](https://user-images.githubusercontent.com/7135790/151883076-96975d2c-e260-4eaf-8e55-ce3594d578d3.png)

Back to the actual feature request.

The idea behind the `ValueConverterAttribute` or even something like `ScalarValueAttribute` is the same as with [EntityTypeConfigurationAttribute](https://github.com/dotnet/efcore/blob/0d1d602d72fefe14f12a86410ec70394ec8151e0/src/EFCore.Abstractions/EntityTypeConfigurationAttribute.cs). We've got this new (cool) attribute, although we had (not that cool) `modelBuilder.ApplyConfigurationsFromAssembly` - the first approach is a solid statement, the 2nd one is poking around in the assembly.
With an attribute, you could implement and use smart enums and simple value objects as if they were primitive types - no extra configuration required. You can even make a nuget package with smart enums and provide them to someone else.
And whether this attribute is placed manualy or by a source generator doesn't matter. Although, if I have a source generator already then I will use it because (1) I know how to convert to and from provider and (2) if the underlying type is a `string` then I can even determine the max-length or in case of a `decimal` the precision.


You're right, the approach with attributes is in general quite limited, so we have (at least) 2 options:

(1) Include settings which can be passed as attribute arguments only, i.e.: ValueConverterType, ValueComparerType, MaxLength, Precision/Scale, IsUnicode, ColumnType. These are virtually all settings provided by the pre-convention `PropertiesConfigurationBuilder`, i.e. this approach is not that limited.

(2) If we want full power then the approach will be identical to `EntityTypeConfigurationAttribute`. We need a new attribute like `ScalarTypeConfigurationAttribute` which requires the implementation type of a new interface 
```csharp
public interface IScalarTypeConfiguration<T>
{
     // we could even use the builder for the pre-conventions, 
     // i.e. PropertiesConfigurationBuilder<T> or TypeMappingConfigurationBuilder<T>
      void Configure(ScalarTypeBuilder<T> builder)
}
```

The usage will be something like

```csharp
[ScalarTypeConfiguration( typeof(MyScalarTypeConfiguration) )]
public class MySmartEnum
{
}

----

public class MyScalarTypeConfiguration : IScalarTypeConfiguration<MySmartEnum>
{
   public void Configure(ScalarTypeBuilder<MySmartEnum> builder)
   {
       builder.HasConversion(...)
                  .HasMaxLength(42);
   }
}
```

With the 2nd approach there are virtually no limits.

PS: the issue should probably be renamed from `ValueConverterAttribute` to something like `ScalarValue/Property/TypeMapping-Attribute`

**Comment by roji** [comment]
> (2) If we want full power then the approach will be identical to EntityTypeConfigurationAttribute. We need a new attribute like ScalarTypeConfigurationAttribute which requires the implementation type of a new interface

First, IMHO from a design/complexity standpoint that's really starting to get over-engineered for what's being done - an attribute pointing an interface that's implemented by a type that accepts a builder, all to configure a value converter.

More importantly, I'm not convinced by the idea that a shared smart enum - in a reusable package - should carry its own instructions for how it should be mapped by EF Core. For one thing, different databases need different mappings. For another, different applications have different needs in terms of how they want to map their enums (as an int to save space? as text for readability?). And once the application starts tweaking the conversion (in its own model configuration, with the Fluent API), it may as well just do the whole mapping itself - it really is just a single config line using pre-convention model configuration.

Having said all that, EF Core makes it possible to write your own plugin, which would add a model-building convention to do exactly what you describe above; we're big believers in community extensions, and don't think everything should be built into EF itself. So you can write this and publish a nuget package for others to use.

On smart enums in general:

> precludes .. standard C# constructs (e.g. switches, pattern matching): one of the reasons the smart enums exist is to not needing (error-prone) switch-cases and if-elses - if done right

Labeling a fundamental language construct as error-prone is a bit much :) Switch *expressions* (as opposed to switch/case statements) are safe in that they require handling all cases; I suspect writing the following with "smart enums" would be considerably more verbose and inelegant, without providing any specific value (but would be happy to be proven wrong):

```c#
public bool IsFoo(SomeEnum value)
    => value switch
    {
        SomeEnum.A => true,
        SomeEnum.B => false,
        // other values...
        _ => throw ...
    };
```

With switch/case you can indeed forget the default case, but how do "smart enums" mitigate this?

In addition, recent versions of C# have been improving pattern matching - which doesn't have any unsafe aspects as far as I'm aware - and "smart enums" aren't compatible with that AFAICT. So there has to be some considerable value here to justify dropping these modern (and useful) language features, and for now I don't see it.

> is quite inefficient (heap allocation ...)

You're right - I misunderstood above.

**Comment by PawelGerr** [comment]
> from a design/complexity standpoint that's really starting to get over-engineered

I'm not sure whether there was an issue on GitHub or an internal discussion, but what was the reason to implement `EntityTypeConfigurationAttribute`? (it is not a rhetorical question and by no means irony or sarcasm)

**Off-topic**
Regarding `IsFoo`: the smart enum *knows* whether it is a *Foo* or not.

```csharp
// instead of calling Foo, which can throw an exception in "_ =>"
// because I extended the enum by another item "C" and forgot again to update all occurrences in my project
var isFoo = IsFoo( someEnum );

// you call the method/property/field on the smart enum - depending on the design, no exception is possible
// because the new item "C" will get the required information during implementation
var isFoo = someSmartEnum.IsFoo;


public class SomeSmartEnum
{
   public static readonly SomeSmartEnum C = new(true);

   public bool IsFoo { get; }

   private SomeSmartEnum(bool isFoo)
   {
      IsFoo = isFoo;
   }
}
```

I propose we are not going to deep into domain driven design (DDD) :)
Maybe I will write a few articles how smart enums achieved more with less code (in real projects) by replacing dozens of lines of code, glued together by magic strings, numbers, C# enums, switch-cases and if-elses, with 1 line.

**Comment by roji** [comment]
>> from a design/complexity standpoint that's really starting to get over-engineered
>
> I'm not sure whether there was an issue on GitHub or an internal discussion, but what was the reason to implement EntityTypeConfigurationAttribute? (it is not a rhetorical question and by no means irony or sarcasm)

That's a very valid question.. This was specifically added to address the size of OnModelCreating, which can get very big when there are many entities. Some people also prefer to keep model configuration for an entity type near that entity, rather than in OnModelCreating. Note also that the EntityTypeBuilder type that gets passed there already exists - it's the same thing you use in OnModelCreating to configure an entity type (so there's no additional builder type).

Now, we could theoretically do a similar thing for properties, i.e. an IPropertyConfiguration interface, referenced by an attribute on a property and containing model configuration for that property; that would also allow configuring value converters. But the need to bulk-configure properties in the model is already met by pre-configuration model configuration - at least we haven't had any requests for such a thing.

> Regarding IsFoo: the smart enum knows whether it is a Foo or not.

That wasn't really my point above - my scenario was about when I need to write some method that accepts some enum (which is out of my control), and I want to pattern-match on it, returning true for some values, and false for others (or any other mapping from the enum's values to some other set of values).

My general point is, you're giving up a lot of language constructs/power, and I'm still not sure exactly what problem is being solved here to justify for that. If it's just about switch/case not requiring you to handle all cases, an analyzer could easily do that.

**Comment by PawelGerr** [comment]
> Some people also prefer to keep model configuration for an entity type near that entity

That's exactly what I want to do with smart enums and value objects.

> the EntityTypeBuilder ... already exist

With EF Core 7 you want to [add support for value objects](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#value-objects). If the support for value types is implemented then there will be a new means for configuration of these, i.e. a new builder. Depending on how the builder will look like, this builder can be used for smart enums as well. This issues could be considered a sub-task of [Use C# structs or classes as value objects](https://github.com/dotnet/efcore/issues/9906).
Otherwise we have `TypeMappingConfigurationBuilder<T>` and `PropertiesConfigurationBuilder<T>` which should work splendidly for providing some "default settings" - what's missing is the attribute.

**Comment by roji** [comment]
> That's exactly what I want to do with smart enums and value objects.

Sure, though it simply doesn't seem that valuable, and AFAIK you're the first one to request it.

If what you want is to put a piece of model configuration code next to your smart enum, you can have a small static class next to it, and call that method from the pre-convention configuration API. You can even put the static method with the model configuration *in* your smart enum type, if that's what you want. Sure, you still have a piece of code on your context that calls it, but designing a thing just to make that go away seems like too much.

Keep in mind that again, IMHO this doesn't make sense as something shared as a nuget across applications, again because mappings differ across applications.

> [...] Depending on how the builder will look like, this builder can be used for smart enums as well. [...]

Maybe. I still don't think it makes much sense to introduce this kind of functionality in EF Core itself.

**Comment by roji** [comment]
Just to clarify... It may indeed make sense to revisit this idea once value objects are implemented, though we try to avoid too much complexity in Data Annotations in general.

**Comment by PawelGerr** [comment]
> It may indeed make sense to revisit this idea once value objects are implemented

Ok, let's wait for the value objects.
