### ISSUE TITLE
Why do IQueryables produced by methods other than OrderBy(Descending) satisfy the `is IOrderedQueryable` condition?

### ISSUE THREAD

**Issue by ivanbiljan** [dotnet/efcore#27330]
## Why do IQueryables produced by methods other than OrderBy(Descending) satisfy the `is IOrderedQueryable` condition?

I have a generic ordering method as part of a pagination/sorting system written for an ASP.NET Core app.
The general idea is: 
1. The request handler fires
2. I select data from the appropriate DbSet using `.Select`
3. The result of that operation is passed to a method that applies the appropriate ordering method based on the `obj is IOrderedQueryable<T>` condition (i.e., if obj has been ordered it invokes `OrderBy`, otherwise it calls `ThenBy` and returns an `IOrderedQueryable`). Essentially, the implementation is a mixture of https://stackoverflow.com/questions/53557376/how-to-build-a-generic-order-by-function-for-ef-core and https://github.com/dotnet/efcore/issues/7233#issuecomment-266438651

The issue is that invoking methods such as `.Select`, `.Take`, `.Where` return `IQueryable`s that are also `IOrderedQueryable`s despite the fact that no actual ordering had happened (i.e., no prior `OrderBy` calls). Given that my sorting mechanism relies on the aforementioned `obj is IOrderedQueryable` condition such behaviour disrupts proper execution.

### Code
I've created a rudimentary repro project to demonstrate this: 
https://github.com/ivanbiljan/efcore-select/blob/master/EFOrderedQueryableRepro/Program.cs

Here's a screenshot of what happens once this is executed:
![image](https://user-images.githubusercontent.com/7541476/151980401-567fed83-cf4b-42f2-944e-86aa214f1b70.png)

Naturally, I'd expect all of these to return false. Is this documented somewhere or can be considered an actual issue?

### Include provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by smitpatel** [comment]
`IQueryable<T>` is an interface not a type. In order to construct one, there needs to a concrete type at runtime. The concrete type generally inject a query provider, implementing a way to iterate over `IQueryable<T>`. In case of EF Core that would mean getting results from database. In order to inject our own query provider we have `EntityQueryable<T>` class (which is not for public use). Since all expression tree constructed from query are wrapped by it, a ThenBy operator needs to be applied to it too if earlier operator was OrderBy. Hence it implements `IOrderedQueryable<T>`. If we want to have a clear boundary then we would have to define 2 different concrete classes. Further, the `OrderBy` LINQ method doesn't differentiate so we would need to intercept the CreateQuery method and evaluate if we want need to change underlying Queryable.

Following piece of code can identify if the Queryable is indeed OrderedQueryable
```C#
static bool Check(IQueryable source) => source.Expression.Type.IsGenericType
    && source.Expression.Type.GetGenericTypeDefinition().IsAssignableTo(typeof(IOrderedQueryable<>));
```
