### ISSUE TITLE
Add Entity Framework to the project from local disk

### ISSUE THREAD

**Issue by i1221** [dotnet/efcore#27381]
How do I make Entity Framework stored on my computer's local disk and I can add Entity Framework to my projects without internet access?
And so that it can be done for any versions of the project and EF. 
 
I plan to work on a computer without internet access.
I plan to work with .NET Framework, .NET Core of different versions for this I need EF of different versions.
 I plan to work with WPF, ASP.NET, WinForms, Xamarin.

**Comment by roji** [comment]
@i1221 EF is used via nuget, which is the standard .NET package management technology. If you have a project that references EF Core - or any other dependency - you can restore all dependencies (`dotnet restore`). At that point they have all been downloaded to your machine (into your home directory), and you should be able to develop without Internet access.

For more information, I'd suggest getting familiar with nuget and how it works - that isn't an EF Core-specific question, but rather a general .NET one.

**Comment by i1221** [comment]
@roji 
Sorry, I didn't understand....

I have 1 computer without internet access.
I created a project.
I want to connect EF.

Where can I get EF in order to connect to the project?

If I understand correctly, Nugget receives packets from the internet...
In other words, I need to switch to computer 2 with internet access. 
Download EF.
Transfer EF to computer 1.

Where to place EF on computer 1 so that Nugget can use it?

**Comment by ajcvickers** [comment]
@i1221 There are a few options, but they all involve setting up the solution/projects on a machine with Internet connection in order to find/download all the packages/assemblies required. This includes all the dependencies of the packages you reference, and all the dependencies of those dependencies, and so on. You could try to manually figure this out, but it would be very time consuming and error-prone, hence it is best to set up it all up with the Internet available and let NuGet restore everything needed.

Once you have done this, you can either:

* Set up a [local package source](https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds#:~:text=Local%20NuGet%20package%20feeds%20are%20simply%20hierarchical%20folder,Package%20Manager%20UI%2C%20and%20the%20Package%20Manager%20Console.) on the isolated machine and copy all the packages into it. This would be my preferred choice, since it preserves the development experience on the isolated machine.
* Or Just copy the entire solution/projects to the isolated computer, including all referenced assemblies. Make sure never to clean the solution or you will lose everything!
* Exact all the assemblies from the NuGet packages and reference them directly.

**Comment by roji** [comment]
To add to @ajcvickers answer above, note that your question isn't related to EF Core in any way - looking at general nuget resources in the web should provide guidance.
