### ISSUE TITLE
Support for "Named Arguments"

### ISSUE THREAD

**Issue by Der-Kraken** [dotnet/efcore#27413]
# My Problem

I have a class (MyAggregate) which I want to load from database. I do not want use auto mapping-feature from efcore (the reasons is listed at end of this issue). So I create a special constructor which my repository should use for loading. The amount of arguments of that special constructor can be a lot. So I want to use "[Named Arguments](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments)"-Feature in repository  in order I see directly what is what.

## MyAggregate:

``` csharp
public class MyAggregate
{
    /// <summary>
    /// Common constructor used for new MyAggregates.
    /// </summary>
    public MyAggregate(string primaryName)
    {
        PrimaryName = primaryName;
        SecondaryName = string.Empty;
        CreatedAt = DateTime.Now;
    }

    /// <summary>
    /// Special constructor which only should be called from repository and unit tests.
    /// </summary>
    public MyAggregate(int id, string primaryName, string secondaryName, DateTime createdAt, string createdBy, string description)
    {
        Id = id;
        PrimaryName = primaryName;
        SecondaryName = secondaryName;
        CreatedAt = createdAt;
        CreatedBy = createdBy;
        Description = description;
    }

    public int Id { get; private set; }
    public string PrimaryName { get; private set; }
    public string SecondaryName { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public string CreatedBy { get; private set; }
    public string Description { get; private set; }
}
```

## MyRepository

``` csharp
public class MyRepository
{
    private readonly MyDbContext _dbContext;

    public MyRepository(MyDbContext dbContext)
    {
        _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
    }

    public MyAggregate GetByKey(int id)
    {
        return _dbContext.MeterUnit
            .Where(o => o.Id == id)
            .Select(o => new MyAggregate(
                o.Id, // Id
                o.Name, // PrimaryName
                o.Alias, // SecondaryName
                o.Logs.Min(o => o.LogDate), // CreatedAt
                o.Logs.MinBy(o => o.LogDate).UserName, // CreatedBy
                o.Remarks // Description
            ))
            .FirstOrDefault
            ;
    }
}
```

# My Wished Feature

I want to code my repository with "Named Arguments" as below:

``` csharp
public class MyRepository
{
    private readonly MyDbContext _dbContext;

    public MyRepository(MyDbContext dbContext)
    {
        _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
    }

    public MyAggregate GetByKey(int id)
    {
        return _dbContext.MeterUnit
            .Where(o => o.Id == id)
            .Select(o => new MyAggregate(
                id: o.Id,
                primaryName: o.Name, 
                secondaryName: o.Alias,
                createdAt: o.Logs.Min(o => o.LogDate),
                createdBy: o.Logs.MinBy(o => o.LogDate).UserName,
                description: o.Remarks 
            ))
            .FirstOrDefault
            ;
    }
}
```
## Why I want this?
The source and target naming differs. Eg. 
- `Alias => SecondaryName`
- or `LogDate (from first log) => CreatedAt`

1. I write the target naming at the end of line as a comment. But renaming of members is a common thing. Update the comment mostly not happens. If I would use the "Named Arguments" feature then I do not need write comments. The code itself would be self documenting.

2. Another advantage is. If the developer of MyAggregate would change the order of "primaryName" and "secondaryName" then the compiler would see no problem but the repository would map the wrong values. If I used "Named Arguments" then no problem will be occur.

## Why not use mapping feature of Ef-Core?

I know that Ef-Core can map to backing fields. But we do not want that our aggregate is deserialized directly from efcore. We have an existing database with a schema which cannot be mapped to a well modeled aggregate. Additionally I want to avoid backing fields because we do not need them.

On the other side, our unit tests need mocks of MyAggregate. That mock is created by that special constructor too. So the special constructor is required anyway (for unit tests we can use "Named Arguments" of course).

**Comment by roji** [comment]
Named arguments are currently unsupported in expression trees - that's a C# limitation rather than anything we can control in EF Core. Apart from that your above code should work just fine - EF Core supports constructor binding for non-navigation properties ([see the docs](https://docs.microsoft.com/en-us/ef/core/modeling/constructors)).

**Comment by Der-Kraken** [comment]
@roji Thank you for sharing the constructor binding. I didn't know that. But still. I think for me and my team a more explicit writing style, with compile time checks is more better than dynamic magic binding (I think that only unit tests will recognize if the constructor binding was wrong or the end user at runtime).

I will try link this ticket to the dotnet 6 team. Thank you.

**Comment by roji** [comment]
> I think for me and my team a more explicit writing style, with compile time checks is more better than dynamic magic binding [...]

So it's worth distinguishing between two things here:

1. Using named argument syntax in C# expression trees (as in your Select above). This is about how you write your queries, and has nothing to do with [constructor binding](https://docs.microsoft.com/en-us/ef/core/modeling/constructors). If you don't use it, you're simply using plain old positional parguments - there's also nothing magical or dynamic about that. For named argument syntax to work in expression trees, the C# team needs to add support for it.
2. Having EF Core itself materialize instances of your entity types (when it loads rows from the database). This is what constructor binding is about, and that doesn't have anything to do with named argument syntax. This is a purely EF-related thing, and the C#/.NET teams have nothing to do with it. You may consider this dynamic or magical, though the same is conceptually done when doing Dependency Injection, and there's no way around it really (unless you're OK with EF Core injecting properties instead of calling the non-default constructor).
