### ISSUE TITLE
FindAsync not return latest data

### ISSUE THREAD

**Issue by xiaodongcool** [dotnet/efcore#27432]
version:
vs2022
efcore 6.0.2

step 1
// entity id is 123
await Db.Set<T>().AddAsync(entity);
await Db.SaveChangesAsync();

// step 2
Db.Database.ExecuteSqlRawAsync("update table1 set filed = 1 where id = 123");

// setp3
var item = await Db.Set<T>().FindAsync(id);
item.Field not update.

**Comment by ErikEJ** [comment]
ExecuteSqlRaw does not interact with the change tracker.

**Comment by ErikEJ** [comment]
Run a LINQ query for the data,  or instantiate a new DbContext

**Comment by ajcvickers** [comment]
@jyller To elaborate on what @ErikEJ said, the entity with ID 123 is already being tracked (cached) by the DbContext instance, and hence the tracked instance is used. It's hard to suggest what you should do in this case without knowing more generally what you are trying to achieve. Generally this happens when a DbContext is being used for more than a single unit-of-work. See [Change tracking](https://docs.microsoft.com/en-us/ef/core/change-tracking/) and [DbContext lifetime](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/) for more information.
