### ISSUE TITLE
sporadically EF Core returning incorrect data and throwing InvalidCastException

### ISSUE THREAD

**Issue by PANKAJKUMARKADU** [dotnet/efcore#27442]
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

_**Please find attached repro project (Repro.zip) and check readMe.txt to run it. More details about the issue is available in readMe.txt. Let me know if you need any input from my side. Thanks**_

<img width="934" alt="Repro" src="https://user-images.githubusercontent.com/29298832/154048334-53ba614f-3e5e-4211-85e2-05844135094e.PNG">
<img width="938" alt="Repro1" src="https://user-images.githubusercontent.com/29298832/154048345-3930d4f9-0518-4371-aabc-c3105eb46877.PNG">

[Repro.zip](https://github.com/dotnet/efcore/files/8068449/Repro.zip)

### Include provider and version information

EF Core version: 5.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer 5.0.9
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.10.2

**Comment by AndriySvyryd** [comment]
The issue in the repro project is that the `Task` that reads the value is not awaited. Use `Parallel.ForEachAsync` instead of `Parallel.ForEach` or replace
`var tidFromTableA = await dataService.GetTidFromTableA(td.Asn).ConfigureAwait(false);`
with
`var tidFromTableA = dataService.GetTidFromTableA(td.Asn).GetAwaiter().GetResult();`

Also don't silently catch exceptions as this can hide the real issue.
