### ISSUE TITLE
error converting datetime in ef core

### ISSUE THREAD

**Issue by brux88** [dotnet/efcore#27464]
Hi, with ef core (net 6) I have a problem in converting dates, before everything worked with the old .net framework.

this is my code for reply the error:
`var query = ((SednaContext)Context).Set<TestataDocumento>().Where(x => x.DataDocumento == new DateTime(2021, 2, 17));
var result = query.Take(1);`

and this is result of error:
![Clipboard-File-1](https://user-images.githubusercontent.com/3495339/154451845-3f5a8332-baad-4f48-9f30-1ad2c59072cb.png)

this is a workaround:
`public class SednaContext : DbContext
{
    ...
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        ...
        modelBuilder.Entity<TestataDocumento>().Property(p => p.DataDocumento).HasColumnType("datetime");
    }
}`

but I have a context with more than 400 tables and each table has different dates, I can't manually set one by one on the OnModelCreating

**Comment by roji** [comment]
@brux88 your code should work without having to do `HasColumnType("datetime")`, unless there's some extra configuration somewhere that you're not showing (see my code sample below). Can you please submit a runnable code sample showing the error happening? This would allow us to investigate and help you further.

<details>
<summary>Working code sample</summary>

```c#
await using var ctx = new SednaContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var query = ctx.Set<TestataDocumento>().Where(x => x.DataDocumento == new DateTime(2021, 2, 17));
var result = query.Take(1);
_ = await result.ToListAsync();

public class SednaContext : DbContext
{
    public DbSet<TestataDocumento> TestataDocumento { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class TestataDocumento
{
    public int Id { get; set; }
    public DateTime DataDocumento { get; set; }
}
```

</details>

**Comment by brux88** [comment]
my scenario is a bit more complex, I am attaching an example where the error comes out:

 I also added a bac file with data and the connection string you have to insert RicercaServerViewModel.cs -> RitornaNuovoContesto(); in infoLoginTest

[ExmapleErrorDtaaGrid_giuthub.zip](https://github.com/dotnet/efcore/files/8088000/ExmapleErrorDtaaGrid_giuthub.zip)


this is screencats:
[https://www.screencast.com/t/jwFIgWH77a8i](url)

**Comment by roji** [comment]
@brux88 there is not bac file in your RAR file. I added a dummy line to the database with the right date, and I can see the query properly loading it without any errors. I'm not sure if your pre-existing database has a different schema or some sort of corrupt data - can you please try running you code on a new, blank database and seeing what happens?

Note that you need to call ToList() or similar on your query for it to actually execute against the database.

**Comment by brux88** [comment]
sorry i forgot to upload the bac. attached the bac.
first the app was written in net framework then i migrated to net
[Sedna.Test.zip](https://github.com/dotnet/efcore/files/8088237/Sedna.Test.zip)
6

**Comment by roji** [comment]
Thanks. The is happening because your database column is `datetime`, and not `datetime2`. In SQL Server, `datetime` is obsolete, and `datetime2` is recommended instead ([see docs](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15)).

Because of this, when EF Core sees a DateTime property, it assumes by default that it needs to be mapped as `datetime2` unless told otherwise. The DateTime value you're sending in the query (`new DateTime(2021, 2, 17)`) gets generated as `2021-02-17T00:00:00.0000000` in the SQL, which is a `datetime2` literal representation that isn't compatible with `datetime` (too much precision). If you explicitly tell EF Core that the property should be mapped to `datetime2 instead (as you did above), it generates '2021-02-17T00:00:00.000' instead, which works.

If your entire database uses `datetime` instead of `datetime2`, you can use [bulk configuration](https://docs.microsoft.com/en-us/ef/core/modeling/bulk-configuration#pre-convention-configuration) to configure all DateTime properties as `datetime`, by including the following on your context:

```c#
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    configurationBuilder.Properties<DateTime>().HaveColumnType("datetime");
}
```

However, it's recommended to plan for migrating the data to `datetime2` at some point.

**Comment by ErikEJ** [comment]
Or migrate to date ?

**Comment by brux88** [comment]
correct, then I know that I will try to migrate to datetime2 but it is possible to do it via script with ef code first

**Comment by ajcvickers** [comment]
> but it is possible to do it via script with ef code first

EF Core is not designed to do this kind of scripting.

**Comment by NetMage** [comment]
Given that this is still causing issues today with users just expecting EF Core to work for them with legacy databases (and I wonder how many databases use datetime versus datetime2), it is unfortunate that some consideration wasn't taken to e.g. trim off any unneeded zeros from the string sent as the SQL parameter?

**Comment by roji** [comment]
@NetMage that kind of thing doesn't work in the general case, e.g. when the parameter has non-zero digits beyond the range of `datetime`.

In any case, we've received very little users complaints about this specifically... At the end of the day EF needs to know the types of columns it's going to interact with, and we have bulk configuration APIs specifically for this kind of thing.

**Comment by NetMage** [comment]
Here is a recent example: https://stackoverflow.com/q/76303482/2557128
I'm pretty sure this is resulting from this issue.

I think to me the problem is that EF defaults to the wrong choice for many databases, doesn't verify it has the right choice, and doesn't give a reasonable error message or have any discovery for the root cause of the issue when getting the error. It feels like a pit of failure to me, but perhaps it isn't a large one.

**Comment by roji** [comment]
> Also, I don't think the digits beyond range of datetime matters. If the database column is datetime, and it is being compared to a C# value that has extra digits, that is an error in any case, and getting the SQL error is at least a sign of that.

The point is that if there are extra digits beyond the `datetime` range, we can't truncate them, since that would return incorrect results from the database. So that means some values (with zeros) will work since they get truncated, and others won't (since they don't have zeros). IMHO that's a worse situation than what we have today - it's preferable to always fail quickly and force the user to configure their column correctly, rather than for the user to discover the problem only much later, when suddenly they need to use a value that can't be truncated (fail-fast is always better for early discovery etc.).
