### ISSUE TITLE
Source Generator for EFCore for DB First users.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/efcore#27553]
Currently those who prefer to make their DB first (and generate code from that) are forced to use EF6 with .NET Framework, however I am working on a means of using Analyzer ``AdditionalFiles`` option on an item to where a source generator can look at the data and generate the same type of code the legacy db-first designer file used to generate with EF6 and .NET Framework. Needed for those people who want to migrate can migrate more easily. However it comes with some changes:
- the edmx file format cannot be used (I am making an efcmx file to be EFCore specific)
  - the efcmx file needs a designer that only changes that file.
  - a source generator reads the efcmx file and from there generates code from a database (the designer is responsible for reading from database and obtain any updates to tables the person selected to update the efcmx file)
  - can also be easier to edit: it's not xml based so easier to read and more compact.
  - the generated code does not need to be committed to the codebase (only the efcmx file).
  - the generated code uses file-scoped, assumes global usings are already added, and uses the project's configured root namespace for the namespace.

The solution is a source generator that reads from a new file format (efcmx) which can be named under VS as ``Entity Framework Core Entity Data Model`` (the template would need to be created as well). Of course it would need some integration similar to the ``ADO.NET Entity Data Model`` template but with differences where the code generation is from a source generator and is separate from an designer and so *should* be more performant than the old EF6 option mentioned above.

I mentioned this issue on the .NET Evolution Discord to @jnm2 back on the 28th of last month about this and he understood that currently EFCore is not all to great for users who prefer to start with DB and not with code. As such the fix to this should be trivial with a source generator.

**Comment by ErikEJ** [comment]
EF Core has fully functional reverse engineering and EF Core Power Tools adds additional features and options on top.

**Comment by jnm2** [comment]
@AraHaan I don't think I made that statement about EF Core.

**Comment by ajcvickers** [comment]
@AraHaan 

> Currently those who prefer to make their DB first (and generate code from that) are forced to use EF6 with .NET Framework

Can you explain what you mean by this? This approach is fully supported by EF Core on .NET, so why are those people forced to use EF6 with .NET Framework?

**Comment by AraHaan** [comment]
> 

That I know of so far, the only way to do DB first is to manually write the code side as well and hope that it matches the db side. With an source generator that reads a file that how the tables/procedures/functions/etc from the db is designed as that could be accomplished better as then people like me would not have to manually write that code (and get it wrong).

**Comment by roji** [comment]
@AraHaan you're maybe unaware of [reverse engineering](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli)? And as @ErikEJ wrote above, additional functionality is provided by his EF Core Power Tools?

**Comment by AraHaan** [comment]
That does work, but it lacks a few things I would definitely want it to check:

- if the project uses an version of C# that supports file-scoped namespaces.
  - if so, it should use file scoped namespaces.
- if the project enabled global usings
  - if so, check and see if the usings the generated code uses are in the global usings, if some of them are not then place only the ones not in the global usings in each generated file.
- cannot tell the generator to generate the types/members as internal.

**Comment by roji** [comment]
@AraHaan as in #25223, most of your points above are complaints about the specific C# being generated, and so don't seem to be related to your more general proposal above (edmx/efcmx). Users are currently using reverse-engineering successfully, even if the C# generated isn't always the most modern. For EF Core 7.0, https://github.com/dotnet/efcore/issues/4038 will add templating, which should give you total control over the C# being generated.

I'm also not sure exactly how your last bullet point (`Name=`) is related to introducing an efcmx file format.

**Comment by reecebradley** [comment]
IMO, having a source generator would be the next step up from scaffolding via CLI. Having real-time access to whether or not your code is correct to the DB keeps me in the "inner loop" longer. 

Perhaps both models can be supported? I could see the CLI approach adopt source generator to prove this out and also ship the library for those who want that library in the project. Obviously there are probably cases where different approaches make more sense, but I just wanted to put a few of my thoughts here since I saw this issue closed.

Context: After watching this dotnetconf video on source generators
https://www.youtube.com/watch?v=4DVV7FXukC8 
It got me excited to see there is possibility for it to work with databases, similar to maybe F# type providers. After doing some bingling, this issue popped up.

**Comment by jnm2** [comment]
You would have to answer some questions like, how frequently does the source generator attempt to connect to the database? A slow source generator means that light bulb options found, previewed, and applied in the IDE slow down.

**Comment by AraHaan** [comment]
Not if there is a cache file be used from the generator (is generated by the ``dotnet ef tool`` or an msbuild task that runs before the generator runs (aka before/after the ``BeforeBuild`` task).

**Comment by roji** [comment]
Guys, while I generally love Roslyn source generators and use them for various things, I don't believe they make sense for doing database scaffolding in EF. Source generators are generally about generating code as part of the compilation process from other source files (or other files in the project). As @jnm2 wrote above, since source generators in principle execute with every compilation, doing database scaffolding this way would expose the compilation process to e.g. connectivity issues with the database, slowdowns, etc.

If you start caching (i.e. not really scaffold on each compilation), then it's no longer clear why you'd do this as a source generator. Not everything needs to be done in compilation - it should be easy to just call `dotnet ef context scaffold` via msbuild, either every time, or every X seconds, if that's what you want (as @AraHaan hinted to above). I'm still pretty skeptical about integrating something like this - which is relatively heavy and depends on an external resource - directly into the build, but it's possible.

**Comment by reecebradley** [comment]
Thank you for adding your thoughts @jnm2 @roji @AraHaan 

I understand the caching discussion from other similar topical discussions. I also realize what we are discussing are approaches to achieving the same thing (or very close). So while I do agree we _could_ do CLI approach as mentioned every X seconds or on build, I tend to think if you didn't have to do that, rather, it be done for you while taking account all the perf/etc concerns, that IMO would be a level up - and that really is where it started for me, 1) is it possible and 2) would more the community see value in it - say compared to what type providers did for F# - [there probably are other better examples but this one is what caught me first](https://fsprojects.github.io/SQLProvider/#Example) 

If this feature doesn't make parity sense with the C# source generators, I can get behind that and perhaps what we need is something else built-in first before we can entertain such an idea. Like I mentioned, it was the dotnetconf session that lead me here to just piggy back off a prior discussion. I can't imagine I would be the only one thinking this.... but who knows.

Thanks for the discussion

**Comment by AraHaan** [comment]
I think source generators would be ok for locally hosted sql server dbs or sqlite dbs.
