### ISSUE TITLE
Applying configurations for entities in DataContext

### ISSUE THREAD

**Issue by kentkost** [dotnet/efcore#27568]
**Preface**
I found a solution for my problem that solves my issue. This is only a suggestion that I am airing in order to see if other would find it neat.

### Problem

**Problem in one line: ef migration with multiple datacontext where all datacontexts use ApplyConfigurationsFromAssembly()**

The problem I'm facing is that I have a lot of datacontexts in the same project(.csproj). All datacontexts use ApplyConfigurationsFromAssembly(). Some contexts share the same entities. I've now tried to migrate multiple contexts and it fails because ef migration tries to make a table that already exists.

The solution would be as simple as just having the modelbuilder exclude certain tables - but that is not possible since the DbSet<someEntity> is not accessible in the modelbuilder. All the configurations just gets added irregardless of whether there exists a DbSet for the configuration. And I have no interest in adding every configuration individually.

### Workaround

Currently I have a workaround that uses reflection to only add the IEntityTypeConfigurations where the generic type exists in the current modelbuilders list of EntityTypes. This works just fine and it has the added benefit of only using Configurations that are relevant to the DataContext.

```Csharp
public static class ModelBuilderExtensions
{
	//Only add the IEntityTypeConfigurations that are in the DataContext
	public static void ApplyConfigurationsForEntitiesInContext(this ModelBuilder modelBuilder)
	{
		var types = modelBuilder.Model.GetEntityTypes().Select(t => t.ClrType).ToHashSet();

		modelBuilder.ApplyConfigurationsFromAssembly(
			Assembly.GetExecutingAssembly(),
			t => t.GetInterfaces()
				.Any(i => i.IsGenericType
					&& i.GetGenericTypeDefinition() == typeof(IEntityTypeConfiguration<>)
					&& types.Contains(i.GenericTypeArguments[0]))
			);
	}
}
```

Another possible workaround would be to separate the DataContexts into each their own project.

### Solutions

**Solution A**
It could be useful if I had an extra argument for including or excluding tables when using "dotnet ef migrations add". Similarly to how "dotnet ef dbcontext scaffold" has an argument for including tables.

**Solution B**
In [ModelBuilder.cs](https://github.com/dotnet/efcore/blob/main/src/EFCore/ModelBuilder.cs) add a method that would do what my current workaround does. Something like this(not tested):

```csharp
public virtual ModelBuilder ApplyConfigurationsFromEntities(Assembly assembly)
{
    var types = modelBuilder.Model.GetEntityTypes().Select(t => t.ClrType).ToHashSet();

    this.ApplyConfigurationsFromAssembly(
        assembly,
        t => t.GetInterfaces()
            .Any(i => i.IsGenericType
                && i.GetGenericTypeDefinition() == typeof(IEntityTypeConfiguration<>)
                && types.Contains(i.GenericTypeArguments[0]))
        );

    return this;
}
```

**Comment by ajcvickers** [comment]
@kentkost A few things. First, creating DbSet properties on a context is not intended to be the way to define the closed set of entity types that make up an EF model. Rather DbSet properties should typically be used only for those entity types that form the roots that will be accessed directly by the application.

Also, ApplyConfigurationsFromAssembly is most commonly used so that the DbContext type does not need to have a direct reference to the entity types in the model. (Also, the team does not like this approach--too much can go silently wrong, and assembly scanning is both not very performant and historically has caused many problems with error handling.) It is easy for people to add their own assembly scanning code that works for their specific cases, as you have done, but we are very unlikely to change the code that is shipped in-the-box. If I were you, I would drop it entirely and explicitly invoke the configurations you want from the DbContexts that need those configurations.

Finally, types can already be [excluded from migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#excluding-parts-of-your-model). However, this is very different from not configuring the type in the model, so I'm not sure if it is really what you want.

**Comment by kentkost** [comment]
Completely understandable. 
I do use "ExcludeFromMigrations()"
The problem was that based on the "standard" assembly scan I get more configurations than are relevant to the Datacontext - which is why I filtered it the way I did, such that I can actually exlude DbSets. At the time I thought it was impossible to exclude a specific DbSets that isn't in the Datacontext (but their configurations had been added via assembly scanning). But I figure you can do it by like this but I haven't tested it:

```csharp
modelBuilder.Entity<SomeEntity>().Metadata.SetIsTableExcludedFromMigrations(true);
```

Just not a fan of writing a lot of code that just looks the same.
