### ISSUE TITLE
Concurrency detection/exceptions and delete

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#27562]
While thinking about optimizing deletion, I started wondering: does it make sense to apply our concurrency logic for deletions, in the same way as we do for updates?

First, let's assume there's no concurrency token defined. The only reason a delete could throw a concurrency exception, is if someone else deleted the row first. But if that happened, our delete is idempotent - we don't really care if our delete actually deleted, we only care that the row is gone.

Even if there's a concurrency token defined, is the user's reasonable intent really to delete the row only if it hasn't been updated since loading? With updates, concurrency tokens protect against "split" updates, where two concurrent updates on the same row can make it inconsistent. But with deletions there's no such danger, since the entire row is deleted.

This has a perf aspect, since if we don't need to do concurrency checking for deletions, we can do bulk deletion (#27550).

<details>
<summary>Repro without concurrency token</summary>

```c#
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var blog = await ctx.Blogs.SingleAsync();
ctx.Blogs.Remove(blog);

using (var ctx2 = new BlogContext())
{
    var blog2 = await ctx2.Blogs.SingleAsync();
    ctx2.Blogs.Remove(blog2);
    await ctx2.SaveChangesAsync();
}

await ctx.SaveChangesAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Connect Timeout=60;ConnectRetryCount=0")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<Blog>().HasData(new Blog { Id = 1, Name = "first" });
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>

**Comment by pinkfloydx33** [comment]
I'm actually hitting an issue because of this (or at least, I believe related to it). I have an interceptor that prepends to every command a Postgres `SET` command that we use for RLS. Essentially turning every command into a batch of two statements. 

```csharp
cmd.CommandText = "SET LOCAL \"some.var\" to \"tenant-identifier\";" + cmd.CommandText;
```

It works great for updates/selects (with and without concurrency tokens enabled) but I'm hitting an issue on deletes. The database throws a concurrency exception indicating no rows were deleted. If I copy the sql and run it manually it works fine. On a hunch I removed the interceptor and things started working. What I believe is happening is that the first (sub) command returns 0 rows affected and that is being read by EF, despite the second half actually deleting the rows. 

I'm probably abusing things here, but if this restriction wasn't in place my deletes would work just fine. Ideally I'd set the variable at the session level (execute a single `SET` command on connection opened) instead of on each command but due to session pooling/pgbouncer that's not really an option. 

Of course, I also agree that if the record is already deleted, then it's deleted and shouldn't throw an error. Similar to how an API might return a 204 for a delete even if the record didn't exist to begin with.

**Comment by roji** [comment]
@pinkfloydx33 a SET command in PostgreSQL should definitely not be producing any results, so that's unlikely to be related. I'd propose putting together a minimal, runnable code sample and posting it in a new issue.

**Comment by stevendarby** [comment]
Something to consider is that an application might have some business rules around deletion. For example, only allowing deletion when a column such as AllowDeletion is true. A concurrency token on such a column might be pretty useful for preventing the deletion of a record which has just recently had AllowDeletion switched to false.

Another use case for it might be if there is an auditing process on delete which audits the last values of the record being deleted. A concurrency token on a row version column could ensure the record is only deleted with an accurate audit of the last values.

**Comment by roji** [comment]
@stevendarby thanks for your input - those scenarios indeed make sense and we discussed some variations of them offline.

On the other side of the argument, it's worth noting that the current behavior is also problematic for various scenarios, where the user just wants to delete a record regardless of the current value of the concurrency token; a concurrency exception needlessly complicated by requiring retries. In other words, it seems like there are valid scenarios for both having the concurrency check and not having it. A manual opt-in/opt-out could be the way to go here (#10443).

**Comment by roji** [comment]
I just realized that a bulk delete can be performed while keeping a (limited) form of concurrency checking:

```sql
DELETE FROM Foo WHERE id IN (1, 2, 3) RETURNING 1;
```

This returns a row with 1 for each row deleted. This allows us to detect when a concurrency issue, but does not allow us to know exactly which entry was the problematic one.

If we'd be OK with the limited concurrency exception details, that means that perf wouldn't be a consideration for this issue any more.

**Comment by roji** [comment]
Design discussion: 

* It turns out that the concurrency checks aren't blocking for implementing bulk deletes (#27550).
* Regardless of perf, we agree that doing concurrency checks isn't ideal as the default behavior, but at this point we don't think it's worth making the breaking change.

#10443 tracks a general mechanism for opting out of concurrency checking.
