### ISSUE TITLE
Including a related entity B inside query for A results in unpredictable state of collection of B in entity C

### ISSUE THREAD

**Issue by ErroneousFatality** [dotnet/efcore#27678]
We have entities A and B which have a many-to-many relationship between them, and both belong to a C entity.
```
class A
{
  public Guid Id { get; private set; }

  public ICollection<B>? Bs { get; private set;}

  public Guid CId { get; private set; }
  public C? C { get; private set; }
}

class B
{
  public Guid Id { get; private set; }

  public ICollection<A>? As { get; private set; }
  
  public Guid CId { get; private set; } 
  public C? C { get; private set; }
}

class C
{
  public Guid Id { get; private set; }
  
  public ICollection<A>? As { get; private set; }
  public ICollection<B>? Bs { get; private set; }
}
```

I want to delete an A entity.
That will cascade delete all AB relationships.
But I also want to delete all B entities which belong only to the A entity being deleted.
So I perform this query:
```
  public async Task<A?> GetWithCAndExclusivelyOwnedBsAsync(Guid id)
    => await DbSet
      .Where((A a) => a.Id == id)
      .Include((A a) => a.C!)
      .Include((A a) => a.Bs!
          .Where((B b)=> b.As!.Count == 1)
      )
      .SingleOrDefaultAsync();
```
Now the issue is this:
The A returned by this, will always contain a non-null collection of Bs, which may be empty or non-empty.
The C inside the returned A, will also contain a non-null collection of Bs if A does so too.
**But if A is returned with an empty (non-null) collection of Bs, then the C will have a null value for it's Bs (collection) property.**

Is this by design?

Can I somehow make the query always instantiate the C.Bs property?

**Comment by ErroneousFatality** [comment]
@smitpatel Could you explain to me how this is closed by design please?

**Comment by smitpatel** [comment]
When performing tracking queries in EF Core, EF Core will fix up navigations between related entities which are being tracked by change tracker. In above case if the `Include` loads entity `B` which is also related to entity `C` being loaded via include then the navigations between those entities will also be populated due to fix-up. This will cause the collection navigation to be initialized and populated. Hence the behavior you are seeing is by design.

If you want to always instantiate the `c.Bs` property then you can initialize the collection in the model class itself. If model class doesn't initialize the collection then EF Core only initialize the collection when there is a need to add an element to the collection when fixing up navigations. By initializing yourself you can remove the differing behaviors. And EF Core will use the collection you initialized to add elements automatically.

**Comment by ErroneousFatality** [comment]
I like to leave my collections unitialized because then when they're null that means that they were not loaded from the storage, and when they're empty that means that the data loaded from the DB was actually empty.

**Comment by ajcvickers** [comment]
Collections explicitly referenced in the `Include` are always initialized. Other collections are initialized when the first item is added.

**Comment by ErroneousFatality** [comment]
Can you see the value of my proposition? 
If someone writes a query which could populate a collection, it makes sense to me that that collection always be initialized after the query's execution.
Could this be expanded upon, or is it a design choice that the tracker doesn't care what the query was about, but only looks at the data received?

**Comment by ajcvickers** [comment]
@ErroneousFatality I think its reasonable to explicitly reference the collection in the Include if you want it loaded. The design choice is that the collections are loaded if they are referenced in the Include. Other collections may be initialized if entities are added via fixup, but these collections are not considered loaded.
