### ISSUE TITLE
Allow using retry policies on explicit transactions using savepoints?

### ISSUE THREAD

**Issue by mattbrailsford** [dotnet/efcore#27716]
Currently if you define your own transaction whilst using retry policies you will encounter the exception

> InvalidOperationException: The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit. 

I understand the reasoning for this, and the use of execution strategies to deal with this, but I wonder if there is a simplified solution that could be implemented using Savepoints.

Given EF Core creates a save point before a call to `SaveChanges` could these be created around every command and then the retry policy rolls back to these points each time if it fails. So for a transaction to commit all the previous queries and calls to save changes must have succeeded?

I'm sure there are possibly errors that would mean this isn't possible, but in that case you could throw an exception and just abort the whole transaction without a retry, but for common transient errors that can be retried in this scenario, it could simplify the implementation.

**Comment by mattbrailsford** [comment]
In this scenario I'm also not interested in read operations, I'm just wanting to ensure my write operations occur.

**Comment by roji** [comment]
We discussed this in triage. While this is possible, as @AndriySvyryd pointed out, may transient exceptions (which are precisely the errors you want to retry) also happen to terminate the connection (e.g. network issue); in this case, we cannot retry at all. The current situation is better in that it informs users up-front about this compatibility, and points them towards the right pattern for dealing with any kind of transient exception (i.e. [manual execution of the retry strategy with a block](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#execution-strategies-and-transactions)). 

So allowing user-initiated transactions with retrying strategies would allow retrying for a certain class of transient exceptions (e.g. deadlocks), but it would actually make the situation worse for exceptions which break the connections, since users would no longer be aware of the problem and be guided to manual execution.
