### ISSUE TITLE
Remote provider with a proper API controller as endpoint

### ISSUE THREAD

**Issue by GioviQ** [dotnet/efcore#27793]
As suggested here https://github.com/unoplatform/uno/issues/2405 it would an useful feature using ef both server side and client side sharing the same entities types.

**Comment by roji** [comment]
It's generally a bad idea to expose an unrestricted database endpoint over HTTP on the web: this raises very problematic security concerns. The generally recommended practice is to expose a GraphQL/OData endpoint backed by EF Core - those two technologies already address the security concerns in various ways. Note also that GraphQL (and possibly OData) also provide advanced  techniques for fetching data efficiently between clients and servers, e.g. fetching some results immediately and others as they become available. A simple EF Core proxy provider wouldn't do any of that.

**Comment by GioviQ** [comment]
@roji have you read the title of the issue? I am talking of something like http://breeze.github.io/doc-cs/.
What you say though bad practice it is already possible and I am talking of an endpoint like Odata or similar but seen as EF provider.

**Comment by roji** [comment]
@GioviQ there are various ways to interpret what's being asked here.

According to its [docs](http://breeze.github.io/doc-cs/introduction.html), Breeze.Sharp basically provides a .NET LINQ provider which translates the query to OData. If this is what you want, then you simply use that package: your server-side OData endpoint would be backed by EF Core, which would do the SQL translation and execution on the database. In other words, Breeze.Sharp would translate LINQ to OData client-side, and server-side OData would translate that back to a LINQ expression tree, which EF Core would execute. You can share CLR types between your client and server in this scenario, and the server-side OData endpoint takes care of security. In any case, I'm not sure what additional component/capability EF Core would provide here - the above is already possible.

(note that the above addresses querying - I'm not sure how updating would work, but hopefully there's a similar story).

I know there are also GraphQL possibilities for using LINQ to query, rather than a GraphQL query; this would provide a similar model as the OData one above. However, as I wrote above, GraphQL really shines with capabilities beyond the simple query-response model, with things like incremental responses to the same query and result streaming, which LINQ doesn't necessarily capture well (at least not without some special API care). So using client-side LINQ with GraphQL is something that should be considered carefully.

If the above answer isn't satisfactory, then it would be good to get a clear description of what it is you're looking for (and why).

**Comment by roji** [comment]
@GioviQ Breeze.Sharp definitely does not replicate EF - according to its own documentation it provides a LINQ provider that translates queries to OData; that's something very different from what EF does.

To understand the complexity/details involved here, ask yourself what you expect to be sent over the wire between the client and the server; in other words, what's the actual network representation of the query. There are already two major standards for this kind of thing - GraphQL and OData. Given that we would not be inventing a 3rd standard for representing a query (why would we), this largely boils down to having a LINQ-to-GraphQL or LINQ-to-OData provider. There are already various implementations for both out there (you may want to take a look at e.g. [GraphQL.EntityFramework](https://github.com/SimonCropp/GraphQL.EntityFramework)), and EF Core isn't directly connected to this area.

Now, it's true that there's a difference between a LINQ provider and an EF Core provider; the former only supports querying with LINQ, whereas the latter provides the full set of EF features (change tracking, saving changes...). So someone could write an EF Core provider for GraphQL or OData, exposing that functionality; I'm not sure if something like this already exists out there.

**Comment by GioviQ** [comment]
@roji 
First of all Breeze.Sharp does not support OData http://breeze.github.io/doc-cs/odata.html
Second: forget a moment Breeze.Sharp
Third:  OData, GraphQL and other protocols are designed to make different systems communicate
Fourth: can you see the left side and the right side of the above diagram? We have EF on both side, no protocols needed, just serialized on the left what it is expected deserialized on the right. E.g. serialize IUpdateEntry entries on the left and deserialize on the right side for SaveChanges.

**Comment by roji** [comment]
> First of all Breeze.Sharp does not support OData http://breeze.github.io/doc-cs/odata.html

See this from the [introduction](http://breeze.github.io/doc-cs/introduction.html):

> Query your object model via LINQ with where clauses, ordering, and paging and Breeze translates these queries into the Open Data Protocol (OData) query standard so you can “expand” the result with related entities or “project” over the data to cherry pick columns and flatten object graphs. Web API, OData, and many other service providers can implement the OData query spec.

> We have EF on both side, no protocols needed, just serialized on the left what it is expected deserialized on the right. E.g. serialize IUpdateEntry entries on the left and deserialize on the right side for SaveChanges.

What do you propose would be the serialization format over the wire, exactly? How would you handle security to make sure that a user can only send IUpdateEntry for database rows which they own?

You seem to be thinking that having "EF Core on both sides", on the client and server, is a trivial matter and data just needs to be passed back and forth. The reality is much more complicated (and security-sensitive across the network boundary!), and that's why GraphQL and OData were created.

**Comment by GioviQ** [comment]
http://breeze.github.io/doc-net/odata.html

"We will not be supporting OData for .NET Core"

The connection would be authenticated and based on current user you can decide which operation is accepted.

**Comment by roji** [comment]
I suggest you carefully read the [Breeze introduction](http://breeze.github.io/doc-cs/introduction.html), paying attention to OData there. There's a distinction between OData as a query spec and the implementation, but as far as I can tell, Breeze is basically an OData client.

> The connection would be authenticated and based on current user you can decide which operation is accepted.

That is a very vague statement which doesn't go into the heart of the matter. I suggest reading up on security in GraphQL and OData to understand the full complexity of the problem; that should help understand why it's very unlikely we'll be developing a new client/server querying system.

And once again, security is only one aspect of the problem - there are many others. It's easy enough to say "just make everything work", but the fact is that OData and GraphQL already exist to solve roughly the same problem.

**Comment by GioviQ** [comment]
in fact with .NET Core this is used http://breeze.github.io/doc-js/query-using-json.html (Breeze.Sharp is dead, only js client is updated)

Despite concerns I think it could be done without OData more easily, etc., but I am not young enough to develop by myself.

**Comment by GioviQ** [comment]
I found https://github.com/6bee/Remote.Linq

**Comment by GioviQ** [comment]
https://github.com/azabluda/InfoCarrier.Core
