### ISSUE TITLE
Building my own scaffolding 

### ISSUE THREAD

**Issue by dmitry-a-morozov** [dotnet/efcore#2782]
I want to build my own scaffolding (classes generation based on database schema).
My understanding it can be done in provider independent way in EF7 because each provider supports set of meta-data interfaces/methods. 
For starters explaining how to do it for Sql Server is good enough.

Thanks.

**Comment by rowanmiller** [comment]
Here is how we do it for SQL Server :smile:  https://github.com/aspnet/EntityFramework/tree/dev/src/EntityFramework.SqlServer.Design/ReverseEngineering

In all seriousness, we haven't documented any of this yet since things are very much influx and anything we write will be out of date in a matter of days (or hours). We will have docs when things stabilize, which they are starting to now, but in the meantime we have several provider writers making good progress just by looking at our code base.

**Comment by dmitry-a-morozov** [comment]
Thanks !
If you're curios I'm trying to build F# type provider for EF7. 
Kinda vNext of https://msdn.microsoft.com/en-us/library/Hh361035.aspx
I understand very well how to build scaffolding using ADO.NET but
to make it work on CoreCLR in provider independent completely diff story.

P.S.
very nice set of videos on C9 !

**Comment by dmitry-a-morozov** [comment]
@rowanmiller Is there alternative in EF7 to EF6 System.Data.Entity.Design.PluralizationService class?

**Comment by natemcmaster** [comment]
We removed the pluralizing service (see https://github.com/aspnet/EntityFramework/issues/2506). There is always [PluralizationService in full .NET](https://github.com/Microsoft/referencesource/tree/master/System.Data.Entity.Design/System/Data/Entity/Design/PluralizationService), but I don't think there is a .NET Core port.
