### ISSUE TITLE
How do you configure a one-to-one/many relationship for future entities?

### ISSUE THREAD

**Issue by Dazfl** [dotnet/efcore#27821]
I have a microservice scenario where my service is receiving data (via events) from two separate services.  The two pieces of data are related but because of the architecture, one piece might arrive before the other.  I'm trying to configure EF Core to allow for a foreign key relationship with navigation, but also allow for a relationship that may not exist yet.

For example:

```csharp
public class FirstEntity
{
   public long Id { get; set; }
   public long SecondEntityId { get; set; }
   public SecondEntity SecondEntity { get; set; }
}
public class SecondEntity
{
   public long Id { get; set; }
}
```
The FirstEntity might arrive first with the property `SecondEntityId=5`, but SecondEntity with Id 5 has not arrived yet.

When I try to save the FirstEntity, I get a foreign key violation error, since the SecondEntity doesn't exist yet.

I had it partially working when I ignored the mapping ...
```csharp
builder.Ignore(first => first.SecondEntity);
```
With this configuration, I was able to save the entity without any problems.  But when I tried to retrieve FirstEntity and use `.Include(first => first.SecondEntity)`, I then received another error saying...
```
The expression 'first.Second' is invalid inside an 'Include' operation, since it does not represent a property access: 't => t.MyProperty'
```
I believe this is because the Navigation property has been removed.  I'm not sure how to solve this.

Is what I'm trying to do even possible?  If `.Ignore()` is the way to go, how do I solve the Include issue?

EF Core version: 6.0.3
Database provider: Npgsql for Postgress - 6.0.3
Target framework: .NET 6.0

**Comment by roji** [comment]
@Dazfl you probably want to insert a blank version of SecondEntityId (with the correct ID 5, but all other fields set to default), and then overwrite all its fields when you get the actual data for it. Be careful, since code querying the database in the interval before SecondEntity is inserted will see the default/blank copy, which may or may not be problematic.

Another option would be to remove the foreign key constraint between the two tables; this would allow you to insert FirstEntity widh SecondEntityId=5 even though no corresponding SecondEntity exists yet. However, this means that your database is sometimes in an inconsistent state: EF queries querying the database in the interval before SecondEntity is inserted will throw. Removing the foreign key constraint should be doable via raw SQL in your migrations.

Finally, you could mark the SecondEntity navigation as optional, so you can save FirstEntity without a SecondEntity; when SecondEntity arrives, you would insert it and also update FirstEntity to point to it. This models the situation in the most accurate way: EF Core is aware that some FirstEntities have no SecondEntities (yet), and will return null for that navigation. However, this would force you to remember the relationship between FirstEntity and SecondEntity (i.e. that this FirstEntity refers to SecondEntity with ID=5), adding program state and possible complexity.

`Ignore` is about excluding a property (SecondEntity) entirely from EF Core's model, so it's not appropriate here.

**Comment by ajcvickers** [comment]
See also #15854.

**Comment by Dazfl** [comment]
Thanks @roji and @ajcvickers for your responses (sorry, have been busy to get back to this).  

What I ended up doing (rightly or wrongly) was in my generated migration script, I added the command to drop the foreign key that was created.  I left everything else as is.  For example:
```csharp
migrationBuilder.DropForeignKey(
    schema: schemaName,
    name: "fk_first_entity_second_entity",
    table: "first_entity");
```

This worked.  I was able to save without a foreign key violation, plus the navigation still worked.

Ultimately I suspect that I have a fundamental design flaw, but this was the situation I was faced with (as I'm sure you all can relate to).
