### ISSUE TITLE
DbUpdateException is handled but exception is sent to Azure Application Insight

### ISSUE THREAD

**Issue by iqb-dawn** [dotnet/efcore#27885]
I was checking one issue with Application Insight team at https://github.com/microsoft/ApplicationInsights-dotnet/issues/2545

As per my code,

```
            try
            {
                await context.AddAsync(new Model
                {
                    UserId = 1,
                    Id = 1,
                });
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException dbEx)
            {
                return Ok("Error Caught");
            }

            return Ok("Error Not Caught");
```
There should not be in any exceptions in Azure exceptions portal but I am seeing exceptions in Azure AppInsights even though the code handled the exception.

**Comment by ajcvickers** [comment]
@iqb-dawn This is by-design. EF Core logs the failure regardless of what your application code does.

**Comment by iqb-dawn** [comment]
This means all EF Core logs regardless whether handled or not. 

As you know all unhandled exception are already logged by Azure AppInsight library, so duplicate exception will be logged if not handled.

**Comment by ajcvickers** [comment]
@iqb-dawn EF Core logging happens at a lower-level than application code. EF Core has no way of knowing what is going to be done with the exception. You can always choose to [disable EF Core logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/) if you choose.

**Comment by stevendarby** [comment]
> EF Core has no way of knowing what is going to be done with the exception.

Isn't that a reason not to log the exception? In the example given, the exception is handled and the app doesn't want to log the exception. If it did, it could do that itself. But the choice is taken away if EF Core is always doing it.

Logging an exception then throwing seems to be considered an anti-pattern due to the likelihood of either duplicate or undesired stack traces in the log. 

I don't think disabling EF core logging is the answer. EF Core could be logging a lot of useful things, including at exception time. It is specifically the logging of the exception itself that may be undesirable. In application insights, these are tracked and can raise concern. But if they're actually coming from scenarios that the app considers benign (and so catches it and doesn't want to log it), this makes it harder to use application insights to monitor genuine issues.

**Comment by stevendarby** [comment]
@ajcvickers do your or your team have any thoughts on the above?

**Comment by ajcvickers** [comment]
@stevendarby This is an area where people want different things, which are quite often opposites. See #26417.

**Comment by swaroopshivanna** [comment]
@stevendarby how did you get around it? We are facing something similar and this is bloating our logs
