### ISSUE TITLE
Improve SQL Server query performance by always specifying the schema in table names

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#27922]
If the schema of a table is not specified SQL Server will have to spend CPU cycles to resolve the schema of the object. 

And worse, not specifying the schema can lead to plan cache pollution and CPU resource waste.

See [this](https://solutioncenter.apexsql.com/improve-sql-query-performance-by-qualifying-object-names/)

More about [the plan cache issue](https://www.red-gate.com/simple-talk/blogs/why-you-should-always-use-schema-name-in-queries/)

To fix this, all query interaction should specify the schema.

- [ ] For reverse engineered models, the schema should always be explitly set, also see #9318
- [ ] For code first models - improve docs / tooling?

**Comment by ErikEJ** [comment]
@roji  FYI

**Comment by roji** [comment]
@ErikEJ if I understand correctly, this would help reuse query plans when the same SQL query is used by different database users, right? If so, I don't think we're seeing a lot of usage where multiple users are used (especially not with the same queries). Of course, there's the multitenancy scenario, but there you typically *want* different tables to be referenced for the different tenants. Note also that users who are in this scenario and want the plan reuse already have the option of explicitly specifying the schemas in their model to get the explicit SQL.

But if we do want to do this... Unless I'm mistaken, we could "default schema" concept as it is today, and simply always emit the schema in SQL, even when it's the default one. This would immediately apply to all users (no need for them to do anything), and would also not require a change in reverse engineering as in #9318.

**Comment by ErikEJ** [comment]
>> this would help reuse query plans when the same SQL query is used by different database users, right?

Correct, it would apply to that, for example multiple desktop users / POS devices connecting directly to a database or multiple microservices with different AAD identities connecting to a shared database resource.  

But also (probably less impactful) to the ongoing resolution of object owner in each query.

>> we could "default schema" concept as it is today,

I do not understand what you mean by this - do you mean resolving the default schema for each user?

**Comment by roji** [comment]
> I do not understand what you mean by this - do you mean resolving the default schema for each user?

I just meant the following... In #9318, I think you're proposing to always reverse-engineer explicit schemas (instead of the default schema), so that the new, efficient model would always include explicit schemas on each and every table. Instead of doing that, we could continue to have the default schema and avoid explicitly specifying it on every entity in the model, but still always generate it in SQL. That means that in terms of model building and conventions, nothing changes, but in our SQL generation we make a change to always generate a schema.

Note that I'm still not sure that we necessarily want to do this... For example, non-qualified table names can be important for some types of multi-tenant scenarios. For example, some users have a schema per user, and actually do want the query to automatically resolve to the current user's table; so the same EF model is used across users, but with a different user in the connection string (a similar thing is done in PostgreSQL by changing the searc_path in the connection string). Fully-qualifying everything would prevent that.

My gut feeling is telling me that there are few scenarios where this will actually improve perf (i.e. where multiple db users send the same queries); and importantly, users can already achieve this if they want by explicitly setting the schema everywhere themselves. But we should definitely discuss.

> But also (probably less impactful) to the ongoing resolution of object owner in each query.

This part I'm less sure about - if there's already a cached query plan for the current user, then that plan should get used even without an explicit schema, and table lookup should be the same, no? It would be good to have actual numbers.

**Comment by ErikEJ** [comment]
>> For example, some users have a schema per user, and actually do want the query to automatically resolve to the current user's table

That not an approach I would recommend anyone...

In addition this will be resolved by the change to scaffolding: https://github.com/ErikEJ/EFCorePowerTools/issues/1353

**Comment by AndriySvyryd** [comment]
Calling `modelBuilder.HasDefaultSchema("dbo");` would add the schema to all entity types that don't have it set.

**Comment by ErikEJ** [comment]
@AndriySvyryd Also in scaffolding? https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs#L517

**Comment by AndriySvyryd** [comment]
Why would you need to scaffold it? I thought it only matters in queries

**Comment by ErikEJ** [comment]
@AndriySvyryd think I finally got the point.
