### ISSUE TITLE
EF Core returns null for some navigation properties

### ISSUE THREAD

**Issue by Danbeac** [dotnet/efcore#27952]
I have a big problem here. Im working with EF core Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.10". All was working good until realize some navigation properties are null even when the data is register in DB. The most weird is meanwhile I insert more data in db, the navigation properties of data that before wasnt loading now is loading and the new ones data are registered don't load these navigation properties.
In few words sometimes the navigation properties are loaded and sometimes not. most often the new information and the previos information begin filling automatically. I cant understand why this happen but Im getting crazy . Please some help !!

**Comment by ajcvickers** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
