### ISSUE TITLE
Cosmos Db First query always shows very slow performance compared to subsequent queries.

### ISSUE THREAD

**Issue by RengarLee** [dotnet/efcore#28027]
## Question
Cosmos Db First query always shows very slow performance compared to subsequent queries.

Set up Cosmos DB (SQL core) with a container.
I ran the same query twice , The first time was very slow.

## Code
![image](https://user-images.githubusercontent.com/23287334/168466264-74bbe9ce-2fa9-48d6-9bbc-7d654a2f23fa.png)

![image](https://user-images.githubusercontent.com/23287334/168466268-284c7243-5f65-4cdf-ab22-dc99fb6f7093.png)

![image](https://user-images.githubusercontent.com/23287334/168466284-1bcc99d5-948a-48ff-b90b-3e747b18214e.png)

### version information
Microsoft.EntityFrameworkCore 6.0.5
Microsoft.EntityFrameworkCore.Cosmos 6.0.5

**Comment by roji** [comment]
@RengarLee this is generally expected - there are various things that need to happen the very first time something is done.

EF Core itself has to compile your query the first time, and internally caches compilation outputs to make subsequent executions much faster. Cosmos itself may involve warmup on its side, and depending on how/where you're running your .NET application, there may be startup costs as well (especially if you're using something like Azure Functions).

It's quite common to do a "warmup query" when your application start before starting to accept users queries, in order to avoid exposing these startup delays to users.

**Comment by RengarLee** [comment]
@roji Thank you for your answer

**Comment by John-HLC** [comment]
@roji - Can something like this be used on the Cosmos EF (SQLAPI) side?


https://entityframework.net/why-first-query-slow
Using a Cached DbModelStore


Our Setup:  Blazor WASM + Cosmos DB (SQL API) + EF Core 6

We timed the different areas
====================
0.2 sec - Azure Functions takes 0.2 sec (getting back security token)
0.009 sec - Cosmos DB is very fast.. 
8 to 9 seconds - but we believe the DBCotnext Building for first query, is now taking **8 to 9 seconds, and growing**.

**Comment by John-HLC** [comment]
Updated the above link just in case -- it was a diff article
