### ISSUE TITLE
Simple projection "cannot be translated"

### ISSUE THREAD

**Issue by janseris** [dotnet/efcore#28038]
## File a bug

Doing a simple projection fails on a query.
The problem is that this query cannot be further processed in my code (e.g. I want to do client-side groupby etc.) directly in the object initialization.

![image](https://user-images.githubusercontent.com/64279914/168684760-f4bf9749-1997-4520-8132-7758f260c340.png)

### Include your code

[Data.zip](https://github.com/dotnet/efcore/files/8703523/Data.zip)

### Include stack traces

```
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.Relational.dll
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.Relational.dll
The LINQ expression 'item => item' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

### Include provider and version information

EF Core version: 6.0.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 6.0
Operating system: Windows 10 Home 21H1
IDE: Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 1.0

![image](https://user-images.githubusercontent.com/64279914/168688178-15297f63-943b-448c-ad23-8e1a289fdcc0.png)

**Comment by smitpatel** [comment]
We don't support doing client evaluation by calling `ToList` or `AsEnumerable` inside a projection which is going to be run by EF Core. You need to select results into an anonymous type then call `AsEnumerable` on top level and then apply any client transformation you want.

**Comment by janseris** [comment]
@smitpatel Wait then how to force the evaluation in the second example? I cannot achieve evaluation by using any combination of .ToList() or AsEnumerable(). This however works in the first example where .ToList() evaluates the query.

**Comment by smitpatel** [comment]
Essentially, you cannot write this in projection
```C#
UserProjektRoles = (from item in GetUserProjektRoles(u, projektMapper, roleMapper).ToList()
                                 select item).ToList()
```
By putting ToList in the middle you are causing enumeration. Above statement is effectively this
`GetUserProjektRoles(u, projektMapper, roleMapper).ToList().Select(item => item).ToList()`
EF Core specifically do not process lambda expressions in client eval. In above query since the projection is identity (selecting the enumeration element), it is not uneccessary to and Just calling `GetUserProjektRoles` method would be sufficient. 
The above exception message refers to `item => item` appearing in above expression tree. You need to remove it.

There is no example since every client evaluation error is different. Please post actual query which is throwing error and the error it generates.

**Comment by janseris** [comment]
The identity projection replaces an advanced projection from the original code for simplification.

> Please post actual query which is throwing error and the error it generates.

```
var query =
                    from u in view
                    select new UserEntity
                    {
                        ID = u.ID,
                        Jmeno = u.Jmeno,
                        Prijmeni = u.Prijmeni,
                        Role = (from item in 
                                            (from userProjectRole in u.V_KONFIGURACE_PROJEKTU__USER__ROLE
                                             select new UserProjektRoleEntity
                                             {
                                                 Projekt = projektMapper.Map(userProjectRole.KonfiguraceProjektu.Projekt),
                                                 Role = roleMapper.Map(userProjectRole.Role)
                                             })
                                group item.Role by item.Projekt into groupByProjekt
                                select new UserProjektRolesEntity
                                {
                                    Projekt = groupByProjekt.Key,
                                    SeznamRoli = groupByProjekt.ToList()
                                }).ToDictionary(x => x.Projekt, x => x.SeznamRoli),

                    };
                return query.ToList();

```


```
System.InvalidOperationException: 'The LINQ expression 'DbSet<V_KONFIGURACE_PROJEKTU__USER__ROLE>()
    .Where(v => EF.Property<int?>(EntityShaperExpression: 
        Tempus.Vystavba.Data.Models.USER
        ValueBufferExpression: 
            ProjectionBindingExpression: EmptyProjectionMember
        IsNullable: False
    , "ID") != null && object.Equals(
        objA: (object)EF.Property<int?>(EntityShaperExpression: 
            Tempus.Vystavba.Data.Models.USER
            ValueBufferExpression: 
                ProjectionBindingExpression: EmptyProjectionMember
            IsNullable: False
        , "ID"), 
        objB: (object)EF.Property<int?>(v, "UserID")))
    .Join(
        inner: DbSet<KONFIGURACE_PROJEKTU>(), 
        outerKeySelector: v => EF.Property<int?>(v, "KonfiguraceProjektuID"), 
        innerKeySelector: k => EF.Property<int?>(k, "ID"), 
        resultSelector: (o, i) => new TransparentIdentifier<V_KONFIGURACE_PROJEKTU__USER__ROLE, KONFIGURACE_PROJEKTU>(
            Outer = o, 
            Inner = i
        ))
    .Join(
        inner: DbSet<PROJEKT>(), 
        outerKeySelector: v => EF.Property<int?>(v.Inner, "ProjektID"), 
        innerKeySelector: p => EF.Property<int?>(p, "ID"), 
        resultSelector: (o, i) => new TransparentIdentifier<TransparentIdentifier<V_KONFIGURACE_PROJEKTU__USER__ROLE, KONFIGURACE_PROJEKTU>, PROJEKT>(
            Outer = o, 
            Inner = i
        ))
    .GroupBy(v => __projektMapper_0.Map(v.Inner))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

**Comment by smitpatel** [comment]
There are 2 issues, 
- ToDictionary method uses lambda. We don't evaluate lambdas in top-level projection. As you know, you would need to put evaluation of dictionary outside of projection. Another alternative is to call client method on it which essentially calls ToDictionary in the body. We will just call into method and lambdas are hidden from EF Core.
- While client eval is supported in top-level projection, we don't evaluate any queryable operation in top-level projection (other than select) if it cannot be translated. It would be same as suppose you applied some filter on a collection and filter couldn't be translated. We would need to fetch additional rows from server and discard it which is no different than client eval in other cases. So if you make your grouping key using mapper then it is opaque to us and cannot be translated to server. Hence we cannot translate group by if you are using a client function in the grouping key. That is what the other exception you are hitting. For this one, you would need to remove the client method call in the property which is being used as grouping key. Given your group by operation doesn't really reduce any data coming back from server (since you are selecting all the element into a list/dictionary anyway), you can just get collection before group by from server and call into client method which applies GroupBy/Select/ToDictionary calls.
