### ISSUE TITLE
Why Ef Core MinLength constraint has no effect on database configuration?

### ISSUE THREAD

**Issue by mamaly12** [dotnet/efcore#28076]
Hi,
I just have a question which is why ef core "MinLength" constraint has no effect on database configuration?

is there a particular reason for it? and what is the best approach to do that after making changes and creating a migration, my approach is to write a code  at the end lines of migration to set constraints:

```
ALTER TABLE my_table 
ADD CONSTRAINT MY_TABLE_PASSWORD_CK CHECK (DATALENGTH(password) >=4)
```
I would be more than happy if you could give me some advice.

thank you.

**Comment by SimonCropp** [comment]
duplicate of https://github.com/dotnet/efcore/issues/22180

seems to be implemented as part of EFCore.CheckConstraints https://github.com/efcore/EFCore.CheckConstraints/issues/5

**Comment by roji** [comment]
Yep, see @SimonCropp's answer above. For context, by default EF Core doesn't add various check constraints since that can have an impact on performance (additional checks), and not everyone wants them. The [EFCore.CheckConstraints](https://github.com/efcore/EFCore.CheckConstraints) plugin does support this, for those who want to opt into that.

**Comment by mamaly12** [comment]
Thank you @SimonCropp and @roji. I will use EFCore.CheckConstraints plugin.
