### ISSUE TITLE
Allow tagging migrations when applying them to database, and let unapplying them by tag.

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#28245]
I would like to apply a sequence of migrations tagging them with release version, so when I rollback I can ask ef core to roll back database state back to the last migration prior the tagged sequence of migrations.

```
1. Migration 1, Tag: Release 1.0
2. Migration 2, Tag: Release 1.0
```
After deploying new release and applying migrations with the tag: 
```
1. Migration 1, Tag: 1.0
2. Migration 2, Tag: 1.0
3. Migration 3, Tag: 2.0
4. Migration 4, Tag: 2.0
5. Migration 5. Tag: 2.0
```

And then I need to rollback, either  `dotnet ef update database --before-tag 2.0` or `dotnet ef update --up-to-tag 1.0`
and it becomes again:
```
1. Migration 1, Tag: Release 1.0
2. Migration 2, Tag: Release 1.0
```

**Comment by ajcvickers** [comment]
This is not something we plan to implement. General changes to the migration history table are expensive to implement, and the value here does not seem high.

**Comment by voroninp** [comment]
ok, but is there a guide on how to rollback a bunch of ef migrations associated with a particular release?

**Comment by ajcvickers** [comment]
@voroninp You will need to know the last migration for the given release. There is no "guide" on how to do that--maybe put it in your release notes? Then run update-database or equivalent targeting that migration.

**Comment by voroninp** [comment]
yes, those are possible options, yet they require manual action, which means error prone.

P.S. Do `RelationalDatabaseFacadeExtensions.GetMigrations` and `RelationalDatabaseFacadeExtensions.GetPendingMigrations` return the list of migrations in the order they were created in code?

**Comment by roji** [comment]
@voroninp note that this would raise some non-trivial questions: how to handle migrations which aren't tagged, what happens if the ordering of the versions of the tags doesn't correspond to the ordering of the migrations themselves, and various others. This kind of thing is trickier when you start thinking about the details, and as @ajcvickers wrote, there's little value in it.

If you want to include version info in your migrations, an easy way would simply be to prefix or suffix the migration name with the version (e.g. 1_0_AddSomeColumn, 1_1_DoSomeOtherChange). This way you can see which migration belongs to which version when listing migrations.
