### ISSUE TITLE
"SELECT COUNT(*) FROM sqlite_schema;" always returns null

### ISSUE THREAD

**Issue by levicki** [dotnet/efcore#28321]
In the attached project, the `ExecuteScalar()` result is always `null` for me.

To create a test database and verify what value should be returned use [sqlite3.exe](https://www.sqlite.org/2022/sqlite-tools-win32-x86-3390000.zip) as follows:

![image](https://user-images.githubusercontent.com/16415478/175926490-3239e89c-e9b4-47fa-b0b2-30667466d9cc.png)
```
Microsoft.Data.SQLite version: 6.0.622.26602
Windows version: 10.0.19044.1766
Visual Studio version: 17.2.5
```
[Bug.zip](https://github.com/dotnet/efcore/files/8991302/Bug.zip)

_**Note:** In the attached Bug.zip the query contains `COUNT()` instead of `COUNT(*)` but in SQLite both seem to be acceptable and the result is `null` in both cases._

**Comment by bricelam** [comment]
```cs
var Row = cmd.ExecuteScalar() as int?;
```

This will always result in `null`. `ExecuteScalar` only ever returns `long`, `double`, `string` and `byte[]` values. See [Data types in Microsoft.Data.Sqlite](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/types) for more information.

**Comment by levicki** [comment]
@bricelam 
> ```cs
> var Row = cmd.ExecuteScalar() as int?;
> ```
> 
> This will always result in `null`.
> 
> `ExecuteScalar` only ever returns `long`, `double`, `string` and `byte[]` values. See [Data types in Microsoft.Data.Sqlite](https://docs.microsoft.com/dotnet/standard/data/sqlite/types) for more information.

I see... I shouldn't have expected Microsoft to keep the API orthogonal.

1. [SqlCommand.ExecuteScalar](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.executescalar?view=dotnet-plat-ext-6.0)
2. [SqliteCommand.ExecuteScalar](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlite.sqlitecommand.executescalar?view=msdata-sqlite-6.0.0)

`SqlCommand.ExecuteScalar` even gives two examples with `Int32` cast right there in the documentation (I am reposting only shorter one here):
```
cmd.CommandText = "SELECT COUNT(*) FROM dbo.region";  
Int32 count = (Int32) cmd.ExecuteScalar();
```

`SqliteCommand.ExecuteScalar` on the other hand doesn't even mention any restrictions on types the resulting object can be coerced into, nor does it throw `InvalidCastException` like the `SqlCommand.ExecuteScalar` method.

One cannot but wonder what was the rationale for making both the method return value and exception behavior different, not to mention how poorly it is documented compared to the other one.

**Comment by roji** [comment]
@levicki database providers are different, so it's not a flaw in Sqlite that it doesn't behave exactly like SqlClient. At the end of the day, if you're casting the results of ExecuteScalar to some type, it's your responsibility to know what type that should be. On PostgreSQL, for example, the COUNT function returns `bigint` (although unlike SQLite regular 32-bit ints are supported), so your code wouldn't work there either.

> SqliteCommand.ExecuteScalar on the other hand doesn't even mention any restrictions on types the resulting object can be coerced into, nor does it throw InvalidCastException like the SqlCommand.ExecuteScalar method (or if it does it is not documented).

ExecuteScalar cannot throw anything here, since it doesn't know about your cast - you're doing that outside of SQLite via the C# `as` operator; the semantics of that operator is precisely to not throw when the type is incompatible. If you simply cast as the SqlClient code does above (instead of using `as`), you should indeed see an InvalidCastException. In other words, this has nothing to do with SQLite or SqlClient.

> Moreover, returning null should have been the behavior reserved for when the result set is empty like it is with SqlClient.

Again, the null here is a result of your usage of the C# `as` operator, and has nothing to do with the database driver.

**Comment by roji** [comment]
> I understand the providers are different but I thought that purpose of ADO.NET and especially [.Net Framework Data Providers](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers) was to provide generic abstraction which behaves the same way regardless of the underlying database engine?

Only up to a point. At the end of the day, the COUNT function returns different data types across different databases - sometimes it's `int` (.NET int), sometimes it's `bigint` (.NET long); this isn't something ADO.NET can magically disappear, at least not without reducing databases to their lowest-common denominator, which would severely restrict things. ADO.NET also cannot parse the SQL dialects of all databases in the world in order to find out that you're calling the COUNT function, so that some general conversion could be applied.

> Also, as far as I know SQLite internally stores INTEGER as 1, 2, 4, or 8 bytes depending on the value magnitude so it can certainly return Int8, Int16, Int32, and Int64.

While that's true, that's just for internal storage. See the following statements just a few lines down below in the [SQLite docs](https://www.sqlite.org/datatype3.html):

> A storage class is more general than a datatype. The INTEGER storage class, for example, includes 7 different integer datatypes of different lengths. [This makes a difference on disk.](https://www.sqlite.org/fileformat2.html#record_format) But as soon as INTEGER values are read off of disk and into memory for processing, they are converted to the most general datatype (8-byte signed integer).

This is why you always get a long out.

> You are correct that I have unintentionally masked an exception here by using as, however I am confused as to how SqlCommand.ExecuteScalar has InvalidCastException documented and SqliteCommand.ExecuteScalar doesn't if ExecuteScalar isn't aware of it?

Looking at the [SqlClient docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlcommand.executescalar?view=sqlclient-dotnet-standard-4.1#exceptions), the conditions where ExecuteScalar there throws InvalidCastOperation are about various conditions where a command **parameter** is mis-configured; in other words, that has nothing to do with the return value which we're discussing here.

> Also, why I cannot cast to int when as you say it is my responsibility to know what data will be returned and SQLite native DLL has sqlite3_column_int() API and I personally checked that calling it from C++ returns value without error?

You can cast to int; the issue is that ExecuteScalar is a non-generic API which returns an object, and C# doesn't allow directly casting a boxed long to an int:

```c#
var x = (int)cmd.ExecuteScalar(); // Unable to cast object of type 'System.Int64' to type 'System.Int32'
var x = (int)(long)cmd.ExecuteScalar(); // works
```

I agree that this is an unfortunate state of affairs, ultimately a result of ADO.NET being a very old API (since before generics even existed in .NET). We do have plans to make this better by introducing a generic `ExecuteScalar<T>` though.

An alternative to all this is to use ExecuteReader instead of ExecuteScalar, and then call the generic `GetFieldValue<T>` on the returned reader. Dapper can also make it easier to work with ADO.NET.

**Comment by levicki** [comment]
@roji Thanks for considering the documentation change.

As for the InvalidCastException behavior I am not seeing the message you are describing.

If I change the sample code to this:
```C#
int Count = (int)cmd.ExecuteScalar();
```
All I am getting when I try to execute it is `Specified cast is not valid.` -- I see no mention of source or destination object type. Because of that at first I suspected that I am not casting `object?` returned from `ExecuteScalar` correctly, which misled me to try using `as` instead of a cast, and shooting myself in the foot with the resulting `null`.

Here are the exception details I am getting:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=Bug
  StackTrace:
   at Bug.Program.DatabaseExists() in C:\WORK\Projects\Bug\Program.cs:line 21
   at Bug.Program.Main(String[] args) in C:\WORK\Projects\Bug\Program.cs:line 34
```
The `HResult` value is `OLE_E_ENUM_NOMORE` (`Can't enumerate any more, because the associated data is missing`) which I assume is related to `Data` and the `Results View` within which is showing `Enumeration yielded no results` which again isn't very helpful.

I have noticed that `_xcode` as well as `_COMPlusExceptionCode` in the exception object are set to `0xe0434352`, which if I am not mistaken comes from CLR possibly implying that the exception was thrown from native code, which in turn might explain the lack of usual details on why the cast failed.

If the exception thrown cannot be fixed to include the types involved in casting in the error message, then in my opinion the documentation should definitely be clarified to include the list of allowed type casts.

**Comment by roji** [comment]
> All I get during runtime is Specified cast is not valid. -- I see no mention of source or destination object type in the exception object.

Are you using an old version of .NET, e.g. .NET Framework? With the following minimal code I get a very clear exception:

```c#
var conn = new SqliteConnection("Data Source=/tmp/foo.sqlite");
conn.Open();

using var cmd = new SqliteCommand("SELECT 8", conn);
_ = (int)cmd.ExecuteScalar()!;
```

This throws `Unable to cast object of type 'System.Int64' to type 'System.Int32'.`.

> The HResult value is OLE_E_ENUM_NOMORE [...]

This is a COM interop-related value that doesn't have anything to do with what we're discussing.

**Comment by levicki** [comment]
@roji 
>Are you using an old version of .NET, e.g. .NET Framework?

The project I attached here is targetting .Net Framework 4.8. I wasn't aware that's considered old given that it is preinstalled in every Windows 10 version since 1903.

**Comment by roji** [comment]
Although .NET Framework continues to ship with Windows for backwards compatibility and is supported, it is no longer being actively developed, and it's no longer recommended to use it for new applications etc.

I highly recommend looking and .NET 6.0, which is the modern version of .NET - it's cross-platform, has substantially better perf, and is being actively evolved (.NET 7.0 will be released in November). See [dot.net](https://dotnet.microsoft.com/en-us/) and various other resources for more details.

**Comment by levicki** [comment]
@roji 
> and it's no longer recommended to use it for new applications etc.

I see.

Instead of continuing off-topic discussion here, I have sent you an email to the address listed on your profile.

Hopefully you will have some spare time to respond.
