### ISSUE TITLE
How to remove orphans from the db context?

### ISSUE THREAD

**Issue by bdongus** [dotnet/efcore#28345]
## My orphan entity is removed from the database, but is still in the db context

The code snippet below is simple test showing the problem. In my real application the row is deleted from the database but not from the db context.

If a user adds a child with the same name after (s)he removed it, an exception occurs as ef core thinks the child is already/still existing.

According to your documentation "Changing Foreign Keys and Navigations" this should work. What am I missing/doing wrong?

```C#
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace tests;
public class Parent{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Child> Children { get; set; } = new List<Child>();
}
[Index(nameof(Name), IsUnique = true)]
public class Child{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class TestDbContext : DbContext {
    public TestDbContext(DbContextOptions<TestDbContext> options) : base(options) {
    }

    public DbSet<Parent> Parents {get; set;}
    public DbSet<Child> Children {get; set;}
    protected override void OnModelCreating(ModelBuilder modelBuilder) {
        modelBuilder.Entity<Parent>().Navigation(p => p.Children).AutoInclude();
    }
}
public class UnitTest1 {
    [Fact]
    public void Test1() {
        // Arrange
        var contextOptions = new DbContextOptionsBuilder<TestDbContext>();
        var connection = new SqliteConnection("DataSource=:memory:");
        connection.Open();
        contextOptions.UseSqlite(connection);
        var dbContext = new TestDbContext(contextOptions.Options);
        dbContext.Database.EnsureDeleted();
        dbContext.Database.EnsureCreated();
        var p = new Parent {
            Name = "lsmf"
        };
        p.Children.Add(new Child { Name = "chld"});
        dbContext.Add(p);
        dbContext.SaveChanges();

        // Act
        var p2 = dbContext.Parents.SingleOrDefault(p => p.Name == "lsmf");
        var c = p2.Children.FirstOrDefault();
        p2.Children.Remove(c);
        dbContext.SaveChanges();

        // Assert
        Assert.Empty(p2.Children);
        Assert.Empty(dbContext.Children);
    }
}
```

EF Core version: 6.06
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 6.0
Operating system: macOS 12.4
IDE: VS4MAC 2022 / VS Code

**Comment by ajcvickers** [comment]
@bdongus In the code above, the child is not deleted from the database. Using [logging](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging) can help show what is going on:

```C#
contextOptions
    .UseSqlite(connection)
    .LogTo(Console.WriteLine, LogLevel.Information)
    .EnableSensitiveDataLogging();;
```

This code severs the relationship between the Child and Parent entities:

```C#
p2.Children.Remove(c);
dbContext.SaveChanges();
```

It does not mark the child as `Deleted`. This means that the child's FK is set to null in the database:

```
info: 6/30/2022 10:16:06.696 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (0ms) [Parameters=[@p1='1', @p0=NULL (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      UPDATE "Children" SET "ParentId" = @p0
      WHERE "Id" = @p1;
      SELECT changes();
```

Then in this line of code a new database query is executed to bring back the Child entities from the database:

```C#
Assert.Empty(dbContext.Children);
```

```
info: 6/30/2022 10:16:06.707 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*)
      FROM "Children" AS "c"
```

The query returns an entity (rather than no entities) because the child is still in the database, since it was never deleted.

If you want the child to be deleted when it is no longer associated with any parent, then typically the [relationship should be made required}(https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#required-and-optional-relationships). This will automatically result in cascade deletes being configured for the relationship.

**Comment by bdongus** [comment]
@ajcvickers Thanks a lot for the explanation and code snippets. Very good and helpful answer. Making the relationship required solved my issue.
