### ISSUE TITLE
When I run dotnet ef update database I get this error: A connection was successfully established with the server, but then an error occurred during the login process.

### ISSUE THREAD

**Issue by abbasymot** [dotnet/efcore#28388]
When I run dotnet ef update database I get this error: 
```
A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
```
here is my csproj
```
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0-preview.5.22302.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.0-preview.5.22302.2">
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.0-preview.5.22302.2" />
  </ItemGroup>
```

and this is my Connection String
```
"DefaultConnectionString": "Server=.;Database=ShopCore;Trusted_Connection=True;"
```

Can you please help me?

**Comment by abbasymot** [comment]
So I figured out that I should use EntityFrameworkCore.SqlServer version 6.0.6 instead of 7.0.0

**Comment by roji** [comment]
@abbasymot the error above isn't related to the EF Core version you're using, but rather to the SqlClient one (the EF Core 7.0 preview brings in a new version of SqlClient).

Specifically, the error above occurs because of [this change](https://github.com/dotnet/SqlClient/blob/main/release-notes/4.0/4.0.0.md#encrypt-default-value-set-to-true) in SqlClient 4.0. You can make sure to use a properly-signed certificate, or pass Encrypt=false.

**Comment by abbasymot** [comment]
Thank you for your explanation

**Comment by abbasymot** [comment]
@roji Thank you for your explanation
