### ISSUE TITLE
Support C# 11 Required

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#28391]
`System.Runtime.CompilerServices.RequiredMemberAttribute` could mark a property or navigation as required.

**Comment by 333fred** [comment]
The spec for how required members are emitted is [here](https://github.com/dotnet/csharplang/blob/main/proposals/required-members.md#metadata-representation). The quick summary:

* If a type defines required members, the `RequiredMemberAttribute` is emitted on the type.
* Every member in that type that is required also is attributed with `RequiredMemberAttribute`.

**Comment by roji** [comment]
@AndriySvyryd am not very familiar with the proposal, but AFAIK it's perfectly valid for required properties to be nullable (and therefore also null). All they do is require that the property be initialized at instantiation-time (and therefore allow non-nullable properties which aren't initialized in the constructor, but rather by the user in an initializer).

Isn't our concept of required properties/navigations already covered with C# NRTs?

**Comment by 333fred** [comment]
> Isn't our concept of required properties/navigations already covered with C# NRTs?

The goal is specifically to ensure that users don't have to do this:

```cs
[Required] public required string Prop { get; set; }
```

**Comment by roji** [comment]
@333fred in the EF context, [Required] just means that a property is non-nullable in the database; that's already conveyed by the nullability of the property type (`string` or `string?`). So since NRTs people already don't have to use the `[Required]` attribute - they just use NRTs.

Now, users may choose to make their EF properties C#-required, to make sure they're properly initialized when the type is instantiated; but I'm not sure why EF itself would care about C#-requiredness - like what additional information would it provide us... Or am I misunderstanding this in some way?

**Comment by 333fred** [comment]
What about models that haven't turned on nullable reference types?

**Comment by roji** [comment]
Well, they have the `[Required]` attribute (or the EF Fluent API), as before.

Also, when nullability is disabled, isn't it perfectly fine to assign null to C# 11 required properties? In other words, aren't C# required properties about making sure the property is assigned, without saying anything about *what* can be assigned (null or otherwise)?

**Comment by 333fred** [comment]
When nullability is disabled, it's perfectly fine to assign `null` to a C# 10 property marked with `[Required]` as well, so I'm not certain what difference that really brings.

**Comment by roji** [comment]
> When nullability is disabled, it's perfectly fine to assign null to a C# 10 property marked with [Required] as well, so I'm not certain what difference that really brings.

The point here is that C# 11 required just means something completely different from how EF treats nullability, so I'm not sure why we'd do anything here.

To summarize, in the EF world, the [Required] attribute means very specifically that the column mapped to the property should be non-nullable. That's covered very well by NRT, and for projects with NRT disabled, there's both [Required] and an EF Fluent API for expressing that. I'm not sure why we'd want to start recognizing C# 11 required as meaning non-nullable, when that's not what it means in C#.

**Comment by roji** [comment]
Note: opened an issue for EF to *scaffold* non-nullable columns as required properties, instead of the current bang null (suggested by @AndriySvyryd).

**Comment by AndriySvyryd** [comment]
With NRTs enabled we don't need to do anything extra to make this work as expected:
```C#
public required string Prop { get; set; }
```

And in the nullable case `required` doesn't seem very useful, so it would be rare for users to need to do this:
```C#
[Required] public required string? Prop { get; set; }
```
