### ISSUE TITLE
I am trying to build Error RS2003 Rule 'EF1001' was shipped in analyzer release '3.0.0', but is no longer a supported diagnostic for any analyzer. Add an entry for this rule in a 'Removed Rules' table to unshipped file.	EFCore.Analyzers

### ISSUE THREAD

**Issue by hounddog22030** [dotnet/efcore#28408]
I have pulled the lastest 6.0 main into Visual Studio but get the compilation error:

Severity	Code	Description	Project	File	Line
Error	RS2003	Rule 'EF1001' was shipped in analyzer release '3.0.0', but is no longer a supported diagnostic for any analyzer. Add an entry for this rule in a 'Removed Rules' table to unshipped file.	EFCore.Analyzers	C:\Users\17034\source\repos\hounddog22030\efcore\src\EFCore.Analyzers\CSC	1

How do I "resolve" this, get around this?

**Comment by roji** [comment]
Which exact branch did you check out, and which commit are you trying to build (please provide the SHA1)? This happens because of https://github.com/dotnet/roslyn-analyzers/issues/5828, but we already [hacked around it](https://github.com/dotnet/efcore/blob/main/src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs#L19) (in 6.0 it was never present).

My guess is that you're on some old 7.0 commit.

**Comment by hounddog22030** [comment]
Your question made me investigate.  I merged 6.0 down in and the issue went away.  Thanks.
