### ISSUE TITLE
Consecutive WHERE-statements are ignored after coalesced nullable bool withouth using paranthesis

### ISSUE THREAD

**Issue by SireMartin** [dotnet/efcore#28474]
## File a bug

x.Active is a nullable boolean

when i compose the following statement :
`.Where(x => x.Active ?? false && (identification.Role == Shared.Enums.Roles.Skylux || x.Customer == identification.Customer))`
the generated sql is :
`WHERE COALESCE([i].[Active], CAST(0 AS bit)) = CAST(1 AS bit)`
So the consecutive statement gets ignored!!

when i add paranthesis around the first statement (x.Active ?? false), the generated sql is as expected:
`.Where(x => (x.Active ?? false) && (identification.Role == Shared.Enums.Roles.Skylux || x.Customer == identification.Customer))`
is translated to
`WHERE (COALESCE([i].[Active], CAST(0 AS bit)) = CAST(1 AS bit)) AND ([c].[Id] = @__entity_equality_identification_Customer_0_Id)`

### Include provider and version information

EF Core version:
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0.6
Operating system:
IDE: Microsoft Visual Studio Community 2022 (64-bit) - Preview / Version 17.3.0 Preview 2.0

**Comment by roji** [comment]
@SireMartin the precedence of the `&&` operator is higher than that of the `??` operator ([see the C# operator precedence table](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/)). That means that in `x ?? false && y`, `y` can be dropped since `false && y` will never be true. This is just how the C# language works and has nothing to do with EF Core; you need to enclose the null-coalescing expression in parentheses as you do above.
