### ISSUE TITLE
Json: add support for collection of primitive types inside JSON columns

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#28688]

**Comment by ajcvickers** [comment]
Note from triage: also consider other issues related to primitive collections--see label `area-primitive-collections`.

**Comment by alrz** [comment]
For the time being, value converter doesn't seem to work even though the the docs claim `Browsers` in the example is configured this way.

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew


How we can accomplish that?

**Comment by PsychoBoy11** [comment]
If current implementation of JSON on List<string> converts it to comma-separated text field what happens if any of string contains comma?

**Comment by roji** [comment]
@PsychoBoy11 which "current implementation of JSON" are you referring to?

**Comment by PsychoBoy11** [comment]
> @PsychoBoy11 which "current implementation of JSON" are you referring to?

EF CORE 7.0.0

Having property like:
`
public class TestEntity
{
     ...
     public List<string> MyProperty;
}`
and setting in `OnModelCreating`:
`modelBuilder.Entity<TestEntity>().OwnsMany(t => t.MyProperty).ToJson();`

First of all it fails when trying to create migration:
`No suitable constructor was found for entity type 'string'. The following constructors had parameters that could not be bound to properties of the entity type:
    Cannot bind 'value' in 'string(char[] value)'
    Cannot bind 'value', 'startIndex', 'length' in 'string(char[] value, int startIndex, int length)'       
    Cannot bind 'value' in 'string(Char* value)'
    Cannot bind 'value', 'startIndex', 'length' in 'string(Char* value, int startIndex, int length)'        
    Cannot bind 'value' in 'string(SByte* value)'
    Cannot bind 'value', 'startIndex', 'length' in 'string(SByte* value, int startIndex, int length)'       
    Cannot bind 'value', 'startIndex', 'length', 'enc' in 'string(SByte* value, int startIndex, int length, Encoding enc)'
    Cannot bind 'c', 'count' in 'string(char c, int count)'
    Cannot bind 'value' in 'string(ReadOnlySpan<char> value)'
Note that only mapped properties can be bound to constructor parameters. Navigations to related entities, including references to owned types, cannot be bound.`

Second, according to 7.0.0 implementation List<string> gets mapped to comma-separated text field, if that's true, what happens if any of the strings contain comma? 

Thanks for your help.

**Comment by roji** [comment]
@PsychoBoy11 string is a primitive type, in the sense that it's not an entity type; EF doesn't yet support collection of primitives types (e.g. `List<string>`), which is why the above code fails. Making that work is what this issue tracks.

> Second, according to 7.0.0 implementation List gets mapped to comma-separated text field, if that's true, what happens if any of the strings contain comma?

I'm still not understanding which scenario you're talking about here - EF doesn't do that. If you map an object graph to a JSON column ([as shown in the docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#json-columns)), everything is properly escaped.

**Comment by PsychoBoy11** [comment]
@roji 
Och, I must have misinterpreted what says on this site:
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew

> Mapping collections of primitive types to JSON is not yet supported. The document above uses a value converter to transform the collection into a comma-separated string.

I understood it in the way that EF Core does that internally.

By the way, what happens if I do the following:
```
public class TestEntity
{
     ...
     public List<Company> CompanyNames;
}

public class Company
{
     public string Name { get; set; }
};
```

**Comment by roji** [comment]
I'm not sure whether we support a List of entity types as the top-level JSON property; #29677 is asking the same question. The scenario that's definitely supported is having a non-collection entity type as the top-level JSON property, and inside that you can put arrays of entity types.

**Comment by roji** [comment]
Note: similar to this, we could allow weakly-typed mapping via Dictionary as well (see #29825).

**Comment by Soundman32** [comment]
I have a working prototype for this from a few years back for .EF5 - should I see if I can resurrect it for EF7 ?

**Comment by roji** [comment]
@Soundman32 this tracks support specifically inside the new EF 7 JSON columns feature, so I'm guessing any work on EF 5 would need serious adjustment in order to be relevant. But you can always take a look.

**Comment by Soundman32** [comment]
@roji My prototype was purely for the Cosmos driver, so it might not be quite as simple as I first thought, but I'll have a go :-)

**Comment by Eirenarch** [comment]
Is this why `Dictionary<string, string>` with items in it ends up in the database as `{ }`?

**Comment by roji** [comment]
@Elrenarch that sounds like a bug - can you please open a separate issue with a minimal, runnable code sample?

**Comment by Eirenarch** [comment]
> @Elrenarch that sounds like a bug - can you please open a separate issue with a minimal, runnable code sample?

Done - https://github.com/dotnet/efcore/issues/30707

**Comment by roji** [comment]
@maumar this was also done as part of #30738... We have some basic testing there specifically for when the primitive collection is inside an owned JSON entity (calling Count, indexing), though at least in principle it shouldn't matter whether the collection is inside or not (see conversation https://github.com/dotnet/efcore/pull/30738#discussion_r1176108012). If we do decide to add more coverage, better to add a JSON owned entity to PrimitiveCollectionsTestBase with some tests on that, and remove Column_collection_inside_json_owned_entity from NonSharedPrimitiveCollectionsQueryRelationalTestBase.

Am leaving this issue open for a bit - let me know what you think, the basic testing we already have may be enough.

**Comment by roji** [comment]
Ah no, there's a problem with the way things currently are: the primitive collection is integrated as a string inside the larger owned entity JSON document, instead of as an in-line JSON array. For example, looking at the `[TestOwner]` table created by the Column_collection_inside_json_owned_entity test, I see:

```
{"Strings":"[\u0022foo\u0022,\u0022bar\u0022]"}`
```

i.e. the document contains a string value, which itself encodes an array inside. Instead, it should be:

```
{"Strings":["foo","bar"]}
```

So we still have a bit of work here.
