### ISSUE TITLE
How to avoid COMMIT and SAVE TRANSACTION queries?

### ISSUE THREAD

**Issue by verdysh** [dotnet/efcore#28724]
.NET 6
ASP .NET Core
EF 6.0.5

I have some code which processes some list, goes through this list and check whereas each element exists in the table. If element doesn't exist - create it.

Here is a simplified example of what is actually happening. The meaning of the real code is just that.
```
var _set = _db.Set<Folder>();
foreach (var subPath in subPaths)
{
	var entityId = await _dbSet
		.Where(...)
		.Select(f => new EntityId<int>{Id = f.Id})
		.FirstOrDefaultAsync();

	if (entityId is null)
	{
		var folder = new Folder
		{
			...
		};
		await _dbSet.AddAsync(folder);
		await _db.SaveChangesAsync();
	}                          
}
```

I host my app in Azure and use ApplicationInsights for collection of telemetry. I noticed, after each INSERT query there is COMMIT query which takes time too. Just **COMMIT** word and that's it.

I thought COMMIT query somehow related to transactions. I don't need transaction in this case, so I don't declare any transactions explicitly.

**Question 1 is**: can I avoid these COMMIT queries?

"Okay", - I thought. If it related to transactions, what if I explicitly create transaction and do all queries inside it?
I did it.

```
var _set = _db.Set<Folder>();
using var transaction = await _fileRepository.BeginTransaction();
foreach (var subPath in subPaths)
{
	var entityId = await _dbSet
		.Where(...)
		.Select(f => new EntityId<int>{Id = f.Id})
		.FirstOrDefaultAsync();

	if (entityId is null)
	{
		var folder = new Folder
		{
			...
		};
		await _dbSet.AddAsync(folder);
		await _db.SaveChangesAsync();
	}                          
}
transaction.Commit();
```

COMMIT queries disappeared. But instead I got `SAVE TRANSACTION [__EFSavePoint];` queries. They don't appear after each insert but relatively often and they also take time.

**Question 2 is**: can I avoid these SAVE TRANSACTION queries?

**Comment by roji** [comment]
Every time you execute SaveChangesAsync, EF Core does a database round trip to apply your changes. Consider moving your SaveChangesAsync to outside of your foreach; this will make all the accumulated AddAsync be sent in a single roundtrip, instead of doing a round trip for each element in subPaths.

The transaction (or savepoint) is necessary in order to make sure that if a failure occurs in the middle of the SaveChanges, rows which have already been modified will be rolled back. This is very unlikely to be a real source of slowdown (database need to commit even if you don't explicitly manage a transaction), so in principle you shouldn't be trying to get rid of the commit.

**Comment by verdysh** [comment]
Thanks!
