### ISSUE TITLE
Collection initilization with EF Core 7

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#28847]
This used to be HashSet, but is now List - why?

`public virtual ICollection<Order> Orders { get; } = new List<Order>();`

**Comment by ajcvickers** [comment]
`HashSet` is a good choice when navigations contain a lot of entities. Over the years, experience has shown that `List` is probably better in the code for majority of uses since it preserves ordering, allows indexing, etc., and it's actually faster for a small number of items. Since these are templates, it's easy to change the template to get back to `HashSet` if desired.

**Comment by ErikEJ** [comment]
I am doing some research for this: https://github.com/ErikEJ/EFCorePowerTools/issues/1499
