### ISSUE TITLE
Consider migrating all of the msbuild files from the current nuget packages to an msbuild sdk.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/efcore#28882]
I would like it if all the msbuild files that are currently a part of the current nuget packages to efcore were instead moved to an msbuild sdk that people can import better.

Why?

Let's say so one can for example pack all of the nuget packages (except the msbuild sdk) into an locally maintained shared framework (using arcade tooling). I have an example of such thing where I might want to trick the efcore tools to use the efcore.design code from the shared framework).
https://github.com/Elskom/EFCore-Installer (Don't get mad at the name, the repo's files is just a proof of concept to what some users might actually do to try to avoid the nuget packages and share the same efcore binaries with all projects in a way that will roll forward for them and prevents the efcore binaries from getting copied to their output directory which is what shared frameworks are for).

**Comment by roji** [comment]
@AraHaan it's generally really not a good idea to "avoid the nuget packages" - nuget is the way EF is meant to be consumed, like all standard .NET libraries. EF Core's msbuild files are a build concern of EF Core itself, and should not be exposed to users; among other things, this may cause breaking changes as we change our build and users somehow depend on it.

Note that there are ways to use nuget references and still control what is getting copied to the output directory, etc. That should be the right way to do things, rather than avoid nuget altogether.

**Comment by AraHaan** [comment]
While that is an option, shared frameworks is also the only option to share the same binaries with all programs that use efcore as ``dotnet store`` does not work in .NET 5 and newer (the apphost seems to have removed it).

**Comment by roji** [comment]
@AraHaan I'm not aware of that being a supported deployment option in .NET. If you want to roll your own solution for doing that, I'd highly advise extracting the assemblies from the nugets and putting them in your central location, rather than doing anything that interacts with the build system of specific projects like EF Core.
