### ISSUE TITLE
Translation of method 'string.Format' failed - EF error.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#28894]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Translation-of-method-stringFormat-fa/10131971)._

---
In Visual Studio 2022 when I am trying to do string Interpolation in EF Function with Like method I am facing the error " Translation of method 'string.Format' failed '. Below is the code I am trying to write:
Basically I am trying to implement a Search filter in a dashboard where we want to allow user to search on the full name where Last Name comes first followed by First Name and Middle Name . The Last Name and First Name are separated by ',' .
 EF.Functions.Like((string.Format(CultureInfo.InvariantCulture, "{0}, {1} {2}", "Last Name", "First Name", "Middle Initial").Trim()),$"{request.KeywordFilter}%")

---
#### Feedback Bot on 8/26/2022, 07:57 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by roji** [comment]
EF doesn't translate string.Format because you can use various advanced features in string.Format which aren't translatable to SQL (e.g. int/date formatting). In the above, it seems like you simply want to concatenate some strings; if that's the case, just use the C# concatenation operator (`+`) instead of string.Format.
