### ISSUE TITLE
Test: Azure SQL Database

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#2898]
Our functional tests run every time against LocalDB. In the recent past we have found issues when running against Azure SQL Database only through manual testing. We should figure out a way (through automation or not) to improve our coverage of this scenario.

**Comment by natemcmaster** [comment]
Getting successful runs of SqlServer.FunctionalTests against SQL Azure will require infrastructure changes to our testing. 

On my most recent attempt, 1624 of 1649 tests fail, mostly due to connection timeouts, replication issues, and throttling. Most issues appear to stem from our use of >75 separate databases and our limited options. 

Tests using scratch databases will always fail until we add something to fix #2969 that because Azure immediately begins geo-replication on all standard 'S0' databases.

**Comment by natemcmaster** [comment]
Status update: running *all*  functional tests against SQL Azure is not likely to work. I can get a very small subset passing, but anything that tests that uses database creation/deletion fails (which is basically all right now).

**Comment by natemcmaster** [comment]
I've investigated further. I would not recommend running our full suite of SQL Server functional tests against Azure as I believe they will frequently fail without providing useful information about actual problems with SQL Azure. Instead, I would favor automated a subset of tests that focus primarily on the aspects of Azure that are different. These include:

1. Remote connectivity. Our SQL Server testing runs on the same machine or in the same subnet. SQL Azure tests will ensure SQL Client /EF are resilient enough to handle WAN connections
1. Throughput and stress. Related to 1.
1. Eventual database creation and deletion. `EnsureCreated()` and `EnsureDeleted()` fail because database creation operations on SQL Azure are subject to heavy delay. Also would allow functional testing for #2969
1. Slight differences in DDL support

I think it is also worth noting that SQL Azure v12 improves parity with SQL Server 2014 but still has [some differences.](https://azure.microsoft.com/en-us/documentation/articles/sql-database-transact-sql-information/) These differences may affect EF and should be investigated further. For instance, we need to ensure migrations creates *clustered* indexes.

> Because Azure SQL Database does not support heap tables, a table must have a clustered index. If a table is created without a clustered constraint, a clustered index must be created before an insert operation is allowed on the table.

**Comment by divega** [comment]
@natemcmaster thanks a lot for investigating further. Am I understanding correctly that besides the lack of automatic retries on transient failures EF7 generally works with Azure SQL DB?

BTW, clustered indexes are created on the PK by default, so that shouldn't be a big concern.

Also, I remember long time ago you observed some failures in `SaveChanges()` against Azure for batch sizes greater than 3 but we were not sure if it would apply to the actual SqlClient implementation (you were testing it with Mono). Have you had a chance to test batching in particular with Azure SQL DB?

**Comment by natemcmaster** [comment]
@divega there still appear to be batching issues on SQL Azure. I've been debugging this and can't figure out why. See https://github.com/aspnet/EntityFramework/issues/4228

**Comment by natemcmaster** [comment]
Also, x-plat testing has revealed more issues in SqlClient on coreclr. See https://github.com/dotnet/corefx/issues/5173. I have not been testing Mono as it's implementation of SqlClient continues to be very broken.

**Comment by natemcmaster** [comment]
SQL Azure testing is now running for all builds on our CI. Testing infrastructure done. Coverage is very poor, however.

Important areas to add for more coverage:
 - creation/deletion of SQL Azure databases
 - batching issues (see #4228) (test in place, but currently disabled)
 - stress test on connection resiliency

@divega Should we use this issue to track adding more coverage? Or track separately?

**Comment by divega** [comment]
@natemcmaster Thanks for the update, this is great! I will clear up milestone so that we can decide how to track further work in triage.

**Comment by rowanmiller** [comment]
@natemcmaster this can just be ad-hoc testing against SQL Azure for RTM (mostly around DDL). We don't have to sort out the issues with our test infra for RTM.

**Comment by natemcmaster** [comment]
See also https://github.com/aspnet/EntityFramework/pull/5016#issuecomment-207577125. Need to cleanup how our functional tests are categorized.
