### ISSUE TITLE
Add API for building raw sql queries with dynamic number of parameters

### ISSUE THREAD

**Issue by mariusz96** [dotnet/efcore#29195]
When using `FromSqlRaw` / `FromSqlInterpolated` / `ExecuteSqlRaw` / `ExecuteSqlInterpolated` it takes quite a bit of code to parameterize even fairly simple inputs:
```cs
public enum Company
{
    C01,
    C02,
    C03
}
```
```cs
public Task<IEnumerable<Specification>> GetSpecifications(List<Company> companies, DateTime date)
{
    string companiesSql = string.Join(", ", companies.Select((x, index) => $"{{{index}}}"));
    string dateSql = $"{{{companies.Count}}}";

    string sql = $@"WITH MyCte AS
(SELECT ...)
SELECT ...
WHERE Company IN ({companiesSql})
AND Date = {dateSql}";

    var parameters = new List<object>();
    parameters.AddRange(companies.Cast<object>());
    parameters.Add(date);

    return _dataWarehouseContext.Specifications
        .FromSqlRaw(sql, parameters.ToArray())
        .ToListAsync();
}
```
(sql is just an example, could be anything and could be very long and ugly).

It would be nice to have some built-in helper that would allow concatenating sql strings in EF-acceptable format, parametrizing inputs along the way.

Currently I use this but it's non-standard and I would like to have something with similar functionality built-in:
```cs
public sealed class FormattableStringBuilder
{
    private readonly StringBuilder _format = new();
    private readonly List<object?> _arguments = new();

    public FormattableStringBuilder AppendInterpolated([InterpolatedStringHandlerArgument("")] Handler handler) => this;

    public FormattableStringBuilder Append(string value)
    {
        _format.Append(value.Replace("{", "{{").Replace("}", "}}"));
        return this;
    }

    public FormattableStringBuilder AppendLine()
    {
        _format.AppendLine();
        return this;
    }

    public FormattableString ToFormattableString() => FormattableStringFactory.Create(_format.ToString(), _arguments.ToArray());

    [InterpolatedStringHandler]
    public struct Handler
    {
        private readonly FormattableStringBuilder _builder;

        public Handler(int literalLength, int formattedCount, FormattableStringBuilder builder)
        {
            _builder = builder;
        }

        public void AppendLiteral(string value) => _builder._format.Append(value.Replace("{", "{{").Replace("}", "}}"));

        public void AppendFormatted(object? value, int alignment = 0, string? format = null)
        {
            _builder._format.Append('{').Append(_builder._arguments.Count);
            if (alignment != 0) _builder._format.Append(CultureInfo.InvariantCulture, $",{alignment}");
            if (format is not null) _builder._format.Append(':').Append(format);
            _builder._format.Append('}');

            _builder._arguments.Add(value);
        }
    }
}
```
```cs
public Task<IEnumerable<Specification>> GetSpecifications(List<Company> companies, DateTime date)
{
    var sql = new FormattableStringBuilder()
        .Append(@"WITH MyCte AS
(SELECT ...)
SELECT ...
WHERE Company IN (");

    for (int i = 0; i < companies.Count; i++)
    {
        sql.AppendInterpolated($"{companies[i]}");
        if (i != companies.Count - 1)
        {
            sql.Append(", ");
        }
        else
        {
            sql.Append(")");
        }
    }

    sql
        .AppendLine()
        .AppendInterpolated($"AND Date = {date}");

    return _dataWarehouseContext.Specifications
        .FromSqlInterpolated(sql.ToFormattableString())
        .ToListAsync();
}
```
Is that an option?

**Comment by roji** [comment]
@mariusz96 a few thoughts on the above...

First, I'm not sure there's anything in your proposed FormattableStringBuilder that's specific to EF or to SQL; it seems like a general-purpose mechanism for generated dynamic FormattableStrings. If so, then that probably doesn't belong in EF.

Second, it's true that your original sample with FromSqlRaw is somewhat cumbersome, but that's because it's a scenario where the number of parameters itself is dynamic. That's not a common scenario in our experience - one notable case is using the `WHERE x IN (...)` construct with a variable number of elements inside the parentheses, which is a problematic construct even regardless of SQL queries (see #13617). In the majority of user cases we've seen, the number of parameters is fixed, and invoking that raw SQL is easy. In other words, I'm not convinced a whole new non-trivial API for piecing together SQL for queries with dynamic parameter counts is justified.

Finally, in SQL it's very important to distinguish between regular string interpolation and integration of a value via a DbParameter (both for protection against SQL injection attacks and for query plan efficiency through parameterization). I think the above API blurs that line somewhat. I'm not saying your proposal isn't safe, but it makes it more difficult to fully understand where a value is being safely integrated via a DbParameter and where not.

**Comment by mariusz96** [comment]
> @mariusz96 a few thoughts on the above...
> 
> First, I'm not sure there's anything in your proposed FormattableStringBuilder that's specific to EF or to SQL; it seems like a general-purpose mechanism for generated dynamic FormattableStrings. If so, then that probably doesn't belong in EF.

To be clear: I do not propose that this exact class be added here - this is just to better illustrate the functionality I want. I do not care what such method/utility would use internally - I would just like to handle cases like the above more gracefully and in the same manner throughout the whole application (I mean using `FromSqlInterpolated` instead of `FromSqlRaw`).

Currently, using `FromSqlRaw` is quite tricky - casting to object array and seems more of a workaround than a proper solution but the client's use case still exists and needs to be fulfilled somehow. What's more, if developers cannot figure out quickly how `FromSqlRaw` exactly works and need to use raw SQL in cases like the above it can lead them to very extreme solutions.

> Second, it's true that your original sample with FromSqlRaw is somewhat cumbersome, but that's because it's a scenario where the number of parameters itself is dynamic. That's not a common scenario in our experience - one notable case is using the `WHERE x IN (...)` construct with a variable number of elements inside the parentheses, which is a problematic construct even regardless of SQL queries (see #13617). In the majority of user cases we've seen, the number of parameters is fixed, and invoking that raw SQL is easy. In other words, I'm not convinced a whole new non-trivial API for piecing together SQL for queries with dynamic parameter counts is justified.

I do not agree that using raw SQL or nullable parameters or arrays of parameters in an ORM is not a common scenario - I would imagine even https://github.com itself uses filters with nullable parameters and arrays of parameters somewhere. In my experience it's very common and both are a great way to make C# classes more general-purpose (especially when one starts to "get" SQL and "thinking in sets").

And about the linked issue - I'm not sure if it applies here. It seems to be about parametrizing `.Contains` method's arguments when translating it to SQL - but with `FromSqlInterpolated` parametrization appears to work OK (just checked with EF Core 6).

That's to me also where the value proposition is - when EF translation does not work as expected (ie too slow, not possible, not implemented yet*) but the use case still needs to be fulfilled somehow. Besides that, other Microsoft products already offer similar tools and utilities - for example, aspnetcore (`QueryHelpers` in `Microsoft.AspNetCore.WebUtilities` namespace, `LinkParser` or `LinkGenerator`), net runtime (`StringBuilder`, `UriBuilder`, `HttpClient`, `Microsoft.Extensions` namespace) and those are greatly useful and can be used as building blocks inside the application.

_*kudos for the new bulk operation APIs_

I think in case of raw SQL, builder would be the most flexible and allow all vendor-specific strings to be used always, without switching back and forth between `FromSqlInterpoled` and `FromSqlRaw` or without bringing in other tools for this simple and common use case.

> Finally, in SQL it's very important to distinguish between regular string interpolation and integration of a value via a DbParameter (both for protection against SQL injection attacks and for query plan efficiency through parameterization). I think the above API blurs that line somewhat. I'm not saying your proposal isn't safe, but it makes it more difficult to fully understand where a value is being safely integrated via a DbParameter and where not.

Absolutely, I thought about it and would be very happy if such a tool would work akin to `FromSqlInterpolated` - accepting only `FormattableString`s and parametrizing everything in placeholders. Then I could just hard-code all the values in the query building method (which would be just strings, anyway). It limits the functionality somehow but in my view would be fully justified because of security.

I would be very happy also if the solution would be designed and implemented completely differently as long as it would allow `Append` operation and would do `auto-parametrization` thing, allowing me to use the same syntax for all my raw SQLs and perhaps even making `FormattableString` more explicit and accessible than it currently is.

**Comment by roji** [comment]
> I do not agree that using raw SQL or nullable parameters or arrays of parameters in an ORM is not a common scenario [...]

To be clear, I'm not saying that raw SQL or nullable parameters is uncommon; the current EF APIs support this quite well via FromSqlInterpolated (note that in 8.0 we're adding a shorter-named FromSql overload which also accepts FormattableString). Where things are slightly more complicated is when the number of parameters is variable; that's indeed the case with the IN construct (unfortunately), and in some highly-dynamic situations where the SQL clauses themselves are dynamically pieced together (e.g. construct multiple conditions in the WHERE clause dynamically). I generally don't think we see that much of advanced dynamic SQL generation being done with EF, and having to construct an array doesn't seem too bad for these.

But we'll discuss this and see what the other team members think.

> And about the linked issue - I'm not sure if it applies here. It seems to be about parametrizing .Contains method's arguments during SQL translation - but with FromSqlInterpolated parametrization appears to work OK (just checked with EF Core 6).

The reason I mentioned is #13617 was only to highlight that the IN construct is a bit unique, in that it's difficult to parameterize it in a simple way (because of the variable number of parameters required). Once again, that's a pretty rare situation for us when generating SQL. I'm just recommending not getting stuck on IN here; most other SQL query cases simply have a fixed number of parameters, and so don't need this feature.

> That's to me also where part of the value proposition is - when EF translation does not work as expected (ie too slow, not possible, not implemented yet*) but the use case still needs to be fulfilled somehow.

I fully agree, and as I wrote above, this is a major reason why we have SQL querying as an EF feature. But special advanced APIs for SQL queries with a variable number of parameters is a step beyond just having SQL querying.

One last thought: as I wrote before, I don't really see anything specific to EF/SQL here; so it could be a 3rd-party package that can be used to build FormattableStrings, which can than be passed to FromSqlInterpolated.

**Comment by ajcvickers** [comment]
Thanks for the suggestion, but after discussion with the team, this is not something we plan to add to EF Core.

**Comment by mariusz96** [comment]
Thanks.

PS FormattableStringBuilder is now a [Nuget Package](https://www.nuget.org/packages/FormattableSb), thanks @roji for refining the API.

**Comment by roji** [comment]
Great, If others run into difficulties here we can point them to this package.
