### ISSUE TITLE
Add a way to delete seed made with HasData without removing data in the database

### ISSUE THREAD

**Issue by rsescalante** [dotnet/efcore#29273]
I need to remove the seed data using HasData in my app, but this removes the rows in the database

An option to let decide if seeded data should be deleted or kept.

**Comment by roji** [comment]
@rsescalante yeah, EF's seeding feature definitely was not meant to be used in this way - it's intended that the seeded data is only every managed via migrations, and not changed via external means afterwards (otherwise the database state goes out of sync with the migrations' model snapshot). I'd recommend simply removing the seeding data entirely from your migrations, and managing them with regular EF SaveChanges going forward.

In any case, yeah, you're always free to edit a scaffolded migration and remove (or add) lines. Just keep in mind that once again, your migration snapshot would no longer be in sync with the database, which can cause lots of confusion down the road.

**Comment by rsescalante** [comment]
Hello @roji, 

I deleted the lines, then created the migration that deletes the rows in the database.  Before applying the migration I removed the fluent lines that addded the data, updated the data and deleted the data.  I can confirm that in a new database, no data is seeded and in the old database the data is still there.  It would be nice though if this option could be more straight forward.

Thank you again for your help.

**Comment by roji** [comment]
> It would be nice though if this option could be more straight forward.

This is something we explicitly discourage doing - the migrations snapshot should be kept in sync with the actual databases, and a divergence (such as what you're doing) can lead to trouble in the future. So I don't think this is something we'd want to make easier/more straightforward.
