### ISSUE TITLE
DateTime.Now  not consistent with client and server with different time zone

### ISSUE THREAD

**Issue by elvince** [dotnet/efcore#29284]
## File a bug

Remember:

* Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
* Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.

### Include your code

Create a request: 
Select * from mytable where DateTime.UTCNow >= MyDateColumn

### Result

 DateTime.UTCNow is translated to SISTIMESTAMP.

SISTIMESTAMP is the server OS date.
So if my client and server are not on the same timezone, the query is wrong.

I check on SQL and we have the same issue.
https://github.com/dotnet/efcore/blob/098785af82c52edeee8ff5c262a8c7e53b9655c5/src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMemberTranslator.cs#L59-L64

I think it is a bug as it has side effect depanding on client/server configuration.
If not, could you please give us more insights?
thanks,

### Include provider and version information

EF Core version: 6.x
Database provider: Microsoft.EntityFrameworkCore.Oracle
Target framework:  .NET 6.0
Operating system: Linux
IDE: Visual Studio 2022

**Comment by roji** [comment]
@elvince it's not clear whether you're using Oracle or SQL Server: the code snippet above points to SQL Server, but SYSTIMESTAMP is an Oracle function (note that there's no Microsoft.EntityFrameworkCore.Oracle, the official Oracle EF provider is [Oracle.EntityFrameworkCore](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/).

If you're using Oracle, then you'll need to report the issue to the maintainers of that provider.

**Comment by elvince** [comment]
@roji 
Sorry for the confusion.
Let keep the discussion on SQL Server side.

Why do you translate Datetime.UtcNow to GETUTCDATE ?
The first one should be the client UTC time and the translation is the Server UTC time.
If server and client are not in the same time zone we don't have the expected behavior.

Could you please help me to understand the rationals behind this?

Thanks

**Comment by roji** [comment]
> If server and client are not in the same time zone we don't have the expected behavior.

By definition, time zones have no relevance here since we're talking about **UTC** timestamps both on the client and on the server (i.e. the time zone of the timestamp is always the same - UTC). So the client or server machine time zone should be irrelevant. So what kind of unexpected behavior are you seeing?

**Comment by elvince** [comment]
I agree you are right. My bad, I didn't put the full picture, sorry for that

My issue is that I used a value converter for my datetime column on EF Core side.
The value has been setup so datetime property convert the value from "UTC" are converted to "CET" and reverse.
Our database have datetime without timezone. We know that they are "CET" only date. As a consequence, we are force to convert any value to CET so our request are working.

All the datetime we are using are converted properly in the resquest to CET, except Datetime.UtcNow.
I suspect that the converter is not applyed due to the fact that it is translated to GETUTCDATE function and not as ISO date string.

As a fix, we made a custom "datetime" class that return Datetime.UtcNow and our query are working properly.

Thanks for your input on how to manage this.

**Comment by roji** [comment]
If I understand correctly, your actual data in the database is timestamp in the CET time zone, and you're having issues in queries comparing them to DateTime.UtcNow in EF queries (because of the time zone mismatch).

One way around this would be to use DateTime.Now instead of DateTime.UtcNow. For SQL Server, this is translated to [GETDATE](https://learn.microsoft.com/en-us/sql/t-sql/functions/getdate-transact-sql?view=sql-server-ver16) instead of [GETUTCDATE](https://learn.microsoft.com/en-us/sql/t-sql/functions/getutcdate-transact-sql?view=sql-server-ver16). If you set the machine time zone of your SQL Server to CET, GETDATE should return the current time in CET, which should then be comparable to your data.

However, this creates a dependency on the machine time zone, which isn't ideal. EF 7 also introduces support for [AT TIME ZONE](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#support-for-at-time-zone), which you can use to convert the DateTime.UtcNow to a CET timestamp in your queries.

But at the end of the day, I'd consider converting your actual data in the database to UTC timestamps. This is a one-time data migration operation that would allow you to remove your value converters and all this complexity.
