### ISSUE TITLE
Status of the dbo schema for other providers

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#2939]
I just wanted to make sure about the status of the "dbo" schema vis-à-vis other databases. The Npgsql EF6 provider used dbo as its default schema, which is definitely not idiomatic in PostgreSQL (which uses the "public" schema instead).

What are the guidelines for EF7? Is this totally a provider-specific question (in which case Npgsql will use "public" as its default schema)?

Sorry if this has been discussed and answered.

**Comment by rowanmiller** [comment]
I'll let @brice and @anpete chime in on technical details that may be relevant to you... but yes that is completely up to the provider now. For SQL Server we actually don't specify any schema by default because SQL Server has the notion of a default schema for the current user (typically dbo, but can be changed).

We are in the process of adding the ability to specify a single default schema at the model level too.

**Comment by roji** [comment]
Great, that's what I hoped to hear. Will leave this for you guys to close in case there are any other relevant details.

**Comment by bricelam** [comment]
The only place `dbo` should even be mentioned under the `src` directory is in SQL Server's Reverse Engineer implementation to strip it out.

Some of our Relational tests use it explicitly just because it's a familiar string, but I was sure to throw in [a nod or two](https://github.com/aspnet/EntityFramework/blob/dev/test/EntityFramework.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs#L199) your way. :wink:

**Comment by roji** [comment]
Ah, nice!

You guys are definitely Doing It Right :)
