### ISSUE TITLE
SaveChanges Perf Improvements through detecting opportunity to bulk update/delete.

### ISSUE THREAD

**Issue by batesm** [dotnet/efcore#29397]
Hi. 

Let’s say I would like the performance improvements of bulk updates and bulk deletes and at the same the benefits of ChangeTracker since I’m using the typical SaveChanges method for persisting changes to the database. 

Imagine, through query, I retrieve 3 Blog entities with a rating of 1 and set IsActive to false on all three. 

In the same unit of work I do a bunch of other arbitrary changes to other entities. 

When SaveChanges is called the CREATE, UPDATE and DELETE statements are generated and executed. 

There will be 3 separate UPDATE statements for those Blogs where I flagged IsActive to false. 

But couldn’t the 3 blogs be condensed into a single UPDATE statement automatically because ChangeTracker knows that all three Blogs were affected by the same update and it’s safe to do so. 

I guess this doesn’t exist already and know it sounds like it could get complicated. Just an idea and wondered what folks thought.

**Comment by roji** [comment]
> But couldn’t the 3 blogs be condensed into a single UPDATE statement automatically because ChangeTracker knows that all three Blogs were affected by the same update and it’s safe to do so.

This maybe works if you happen to do the same change on **all** the entities retrieved via your query (that's indeed the scenario I showed in the community standup today). But it breaks down the moment you don't do it on all entities (e.g. because you're checking some additional thing), or if you don't do the same change on all entities.

Even more importantly, this would require the change tracker to somehow "reverse-engineer" the changes you're making across all entities, somehow working back to a single rule. For example, instead of setting IsActive to false on all entities, assume you're increasing some column - like the Counter++ done in the benchmark I showed. The change tracker would only see the old and the new Counter values across all the tracked entities, and would have to somehow understand that the new value is the old value plus one. That's just not possible - the change being applied could be any operation (mathematical or otherwise), or even worsse - the result of some .NET function which cannot be executed in the server. In short, if you want to apply the same change across multiple rows - which is what SQL UPDATE and EF ExecuteUpdate do - you have to express that change to EF (via LINQ operators); it cannot be reverse-engineered by it.

Finally, this would maybe condense the multiple UPDATE statements into one, but it wouldn't do anything to help with the immense and needless fetching of data from the database, its materialization into entities and the change tracking machinery involved. That's quite a significant part of the overhead, e.g. the considerable memory requirements we saw in the benchmark.

**Comment by batesm** [comment]
I was aware that there are plenty of complexities around change tracking which would warrant EFCore quickly stepping outside the proposed optimisation should it exist. And in computing the optimised UPDATE, if it could, it would probably put a lot of perf back on the table. 

I forgot to say that my suggestion would be based on bulk updates but the condensed WHERE clause could only ever be on the primary keys of the entities concerned. 

I’m aware of the overhead of fully materialising the entities and the problem ExecuteUpdate/ExecuteDelete is solving. This idea was more about optimising the SaveChanges while stealing a few concepts from the new bulk updates feature. 

Even if EFCore knew, in a rare circumstance, it was clear and safe to condense the 3 updates into one (because conditions meant it didn’t have to ‘escape’ the optimisation for any of the myriad reasons) is it really worth even trying to optimise for this in the grand scheme of things?

Very probably not. 

I was just exploring the space 😊. 

Thanks for the quick response @roji and again a great presentation on the stand up today.

**Comment by roji** [comment]
Thanks for your suggestion and feedback - it's always good to hear people's thoughts on this kind of thing! I'll go ahead and close this for now as unfeasible/not worth it, but if you feel like this is worth pursuing please post back.
