### ISSUE TITLE
Table splitting problem 

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/efcore#29423]
I'm trying to implement table splitting where I want to split a single table into 3 entities.
The table comes from a legacy system and I can't change the db schema.

The simplified table layout is something as this

`Id | ReportName | Prop1 | Prop2 | BlobData | BlobResult`

Now what I need is to split this into 3 entities:

- ReportRequest (uses columns `Id | ReportName | Prop1 | Prop2`)
- ReportData (uses columns `Id | ReportName | BlobData`)
- ReportResult (uses columns `Id | ReportName | BlobResult`)

this is needed to map the db to the DDD domain entities.
Note that the Id field is the table Key and it's declared as an **autoincremental** bigint

some of our constraints are:
- we don't want to have navigation properties between these entities (they are aggregate roots)
- ReportRequest is referenced from ReportData and ReportResult just by a ReportRequestId property that should map to the ID columns of the shared table (this would allow us in the future to create a proper DB schema)

I've read the documentation about table split and I come across several problem implementing it.
I want to create my ReportRequest as the main entity (principal) and let other 2 define a relation on that, this way:

the 3 entity configurations are similar to this:

```
class ReportRequestEntityTypeConfiguration : IEntityTypeConfiguration<ReportRequest>
{
   private const string TABLE_NAME = "ScheduledReports";

   public void Configure(EntityTypeBuilder<ReportRequest> config)
   {
      config.ToTable(TABLE_NAME, ReportsContext.DEFAULT_SCHEMA);

      config
         .HasKey(b => b.Id);

      config.Property(b => b.Id)
         .UseIdentityColumn(1, 1);
   }
}


class ReportDataEntityTypeConfiguration : IEntityTypeConfiguration<ReportData>
{
   private const string TABLE_NAME = "ScheduledReports";

   public void Configure(EntityTypeBuilder<ReportData> config)
   {
      config.ToTable(TABLE_NAME, ReportsContext.DEFAULT_SCHEMA);

      config
         .Property(b => b.ReportRequestId)
         .HasComputedColumnSql("ID");

      config
         .HasOne<ReportRequest>().WithOne()
         .HasForeignKey<ReportRequest>(o => o.Id);
   }
}

class ReportResultEntityTypeConfiguration : IEntityTypeConfiguration<ReportResult>
{
   private const string TABLE_NAME = "ScheduledReports";

   public void Configure(EntityTypeBuilder<ReportResult> config)
   {
      config.ToTable(TABLE_NAME, ReportsContext.DEFAULT_SCHEMA);

      config
         .Property(b => b.ReportRequestId)
         .HasComputedColumnSql("Id");

      config
         .HasOne<ReportRequest>().WithOne()
         .HasForeignKey<ReportRequest>(o => o.Id);
   }
}
```

If I try to create an instance of ReportRequest and save it, I get this error:
System.InvalidOperationException: The value of 'ReportRequest.Id' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.

It doesn't make sense to me, what's wrong with this?
Is this related to the fact that I don't have a navigation property? (we DON'T want it)

**Comment by MithrilMan** [comment]
nevermind, I ended up inverting the dependent type used on HasForeingKey, I had to set the ReportData and ReportRequest, I'll leave this discussion in case someone will stumble with similar problems

**Comment by wdhenrik** [comment]
You state:
“ReportRequest is referenced from ReportData and ReportResult just by a ReportRequestId property”

But your configuration puts the FK constraint on the ReportRequest table

      config

         .HasOne<ReportRequest>().WithOne()

         .HasForeignKey<ReportRequest>(o => o.Id);



Assuming this is part of ReportDataConfiguration, this is telling EFC:

ReportRequest references ReportData and the FK column containing the PK value is ReportRequest.Id.  No column on ReportData is mentioned or involved in the constraint.



This means that ReportRequest.Id is the PK of ReportRequest, but is also a FK pointing to the PK of ReportData.
Based on the error message, ReportRequest cannot be saved because there is no related PK in ReportData for ReportRequest to use as a key reference.

.HasForeignKey<T> instructs EF which entity has the FK constraint and which column contains the referenced PK.  Based on what you describe, I would expect that configuration to be:

      config

         .HasOne<ReportRequest>().WithOne()

         .HasForeignKey<ReportData>(o => o. ReportRequestId);

This should make a FK constraint on ReportData.ReportRequestId, pointing to ReportRequest.Id.

From: MithrilMan ***@***.***>
Sent: Tuesday, October 25, 2022 7:45 AM
To: dotnet/efcore ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/efcore] Table splitting problem (Issue #29423)

CAUTION: This email originated from outside the organization
Beware of suspicious links, files, or requests. When in doubt report as phishing.


I'm trying to implement table splitting where I want to split a single table into 3 entities.
The table comes from a legacy system and I can't change the db schema.

The simplified table layout is something as this

Id | ReportName | Prop1 | Prop2 | BlobData | BlobResult

Now what I need is to split this into 3 entities:

  *   ReportRequest (uses columns Id | ReportName | Prop1 | Prop2)
  *   ReportData (uses columns Id | ReportName | BlobData)
  *   ReportResult (uses columns Id | ReportName | BlobResult)

this is needed to map the db to the DDD domain entities.
Note that the Id field is the table Key and it's declared as an autoincremental bigint

some of our constraints are:

  *   we don't want to have navigation properties between these entities (they are aggregate roots)
  *   ReportRequest is referenced from ReportData and ReportResult just by a ReportRequestId property that should maps to the ID columns of the shared table (this would allow us in the future to create a proper DB schema)

I've read the documentation about table split and I come across several problem implementing it.
I want to create my ReportRequest as the main entity and let other 2 define a relation on that, this way:

the 3 entity configurations are similar to this:

class ReportRequestEntityTypeConfiguration : IEntityTypeConfiguration<ReportRequest>

{

   private const string TABLE_NAME = "ScheduledReports";



   public void Configure(EntityTypeBuilder<ReportRequest> config)

   {

      config.ToTable(TABLE_NAME, ReportsContext.DEFAULT_SCHEMA);



      config

         .HasKey(b => b.Id);



      config.Property(b => b.Id)

         .UseIdentityColumn(1, 1);

   }

}





class ReportDataEntityTypeConfiguration : IEntityTypeConfiguration<ReportData>

{

   private const string TABLE_NAME = "ScheduledReports";



   public void Configure(EntityTypeBuilder<ReportData> config)

   {

      config.ToTable(TABLE_NAME, ReportsContext.DEFAULT_SCHEMA);



      config

         .Property(b => b.ReportRequestId)

         .HasComputedColumnSql("ID");



      config

         .HasOne<ReportRequest>().WithOne()

         .HasForeignKey<ReportRequest>(o => o.Id);

   }

}



class ReportResultEntityTypeConfiguration : IEntityTypeConfiguration<ReportResult>

{

   private const string TABLE_NAME = "ScheduledReports";



   public void Configure(EntityTypeBuilder<ReportResult> config)

   {

      config.ToTable(TABLE_NAME, ReportsContext.DEFAULT_SCHEMA);



      config

         .Property(b => b.ReportRequestId)

         .HasComputedColumnSql("Id");



      config

         .HasOne<ReportRequest>().WithOne()

         .HasForeignKey<ReportRequest>(o => o.Id);

   }

}

If I try to create an instance of ReportRequest and save it, I get this error:
System.InvalidOperationException: The value of 'ReportRequest.Id' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.

It doesn't make sense to me, what's wrong with this?
