### ISSUE TITLE
MinAsync and MaxAsync on an empty sequence.

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/efcore#29447]
Having a query that returns no results and using MinAsync or MaxAsync throws  "Sequence contains no elements."
but Sum e.g. does return zero.  So why do min and max not return the corresponding unit values (e.g. For min the int.maxvalue and for max the int.minvalue).

There also isn't any OrDefault counterpart?

**Comment by ajcvickers** [comment]
@qsdfplkj Because [sum is commonly defined such that the sum of the empty set is zero](https://en.wikipedia.org/wiki/Empty_sum).

On the other hand, finding the max and min over the empty set is invalid. There is no correct answer.

Or, in a more pragmatic sense, these are the behaviors of LINQ-to-Objects.

**Comment by qsdfplkj** [comment]
I learned that 0 is unity for plus. True is unity for and. False for or. Where infinity is unity for min. And min infinity for max. As any operation with unity value doesn't change the answer. (unity opp x == x) it would be really helpful to have such an operator now I need to depend on an exception.

**Comment by qsdfplkj** [comment]
i will work around this:

   OrderBy(x => x.Value).Select(x => x.Value).Cast<Nullable<ValueType>>().FirstOrDefaultAsync()

which will get me a null.
