### ISSUE TITLE
Will the new JSON columns be compatible with existing string columns that contain JSON?

### ISSUE THREAD

**Issue by ManuelHaas** [dotnet/efcore#29451]
With EF Core 7 JSON columns will be supported.
Will the new JSON columns be compatible with existing string columns that contain JSON?

Example: I have columns of type string in which JSON content is stored using `JsonConvert.SerializeObject(myObject)` and loaded using `JsonConvert.DeserializeObject<MyObjectType>(...)`.
Can such columns be used as JSON columns in EF Core 7 without changing the content of the columns or do they need to be migrated in a specific way?

**Comment by maumar** [comment]
you will have to provide the structure of the json document, mapping it to an owned entity (`MyObjectType`). When it comes to the data itself, EF Core 7 stores it pretty much in the same form as the default JSON serializer does. The only difference is that enums are stored as string rather than int. So you will have to manually add a converter for your enums, so that they are stored as ints. Otherwise all *should* work out of the box.
