### ISSUE TITLE
Add API for modifying value on row update

### ISSUE THREAD

**Issue by AdisonCavani** [dotnet/efcore#29464]
## Issue
I would like to have two columns:
- createdAt
- updatedAt

I'm configuring ``CreatedAt`` like this:
```cs
// database-side
builder.Entity<UserEntity>()
            .Property(x => x.CreatedAt)
            .HasDefaultValueSql("current_timestamp at time zone 'utc'");
```

or: (working on server-side)
```cs
// server-side
builder.Entity<UserEntity>()
            .Property(x => x.CreatedAt)
            .HasDefaultValue(DateTime.UtcNow);
```

However, currently there is no first class API to configure ``UpdatedAt``.  
The workaround is to override ``SaveChanges`` method or using raw SQL in migrations - add triggers.

See:
- [Npgsql docs](https://www.npgsql.org/efcore/modeling/generated-properties.html#timestamp-generation)
- [efcore docs](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#update-timestamp)

## Proposed solution
New FluentAPI in ``OnModelCreating``:
- server-side
- database-side

Example.:
```cs
builder.Entity<MyEntity>()
            .Property(x => x.UpdatedAt)
            .HasDefaultValueSql("now()'")
            .ValueGeneratedOnAddOrUpdate();
```

```cs
builder.Entity<MyEntity>()
            .Property(x => x.UpdatedAt)
            .HasDefaultValue(DateTime.UtcNow)
            .ValueGeneratedOnAddOrUpdate();
```

## Similar APIs in another ORMs
Mikro-orm [docs](https://mikro-orm.io/docs/decorators#property):
```
onUpdate() - Automatically update the property value every time entity gets updated.
```

## Similar/related issues
- #3955

**Comment by roji** [comment]
@AdisonCavani [the doc page](https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations) you linked to provides some context on this. While databases usually provide an easy way to set a default value which is set on insert, having a computed column which automatically changes when the row is updated is unfortunately more complex/limited, e.g. non-deterministic functions such as `now()` typically aren't supported. This is why the more complex trigger setup is needed.

Above, it seems that you're suggesting for the "on update" value to be calculated client-side, by EF, rather than in the database. We may be able to provide this via a value generator, but IIRC these only work for adding, not updating (/cc @ajcvickers).

**Comment by ajcvickers** [comment]
@roji #6999 tracks value generation on update.
