### ISSUE TITLE
efcore 7 - json mapping to non-efcore updated column

### ISSUE THREAD

**Issue by vigouredelaruse** [dotnet/efcore#29591]
## Ask a question
my understanding of json support in efcore 7
* materialize entities in the database with mapped properties stored as  db provider specific json

what i'd like to do is 
* ingest arbitrary json and store it in a column without using necessarily efcore, in dbprovider native json column
* use efcore to map pocos to entities in db provider native json column

in other words the use case calls for some non-efcore process to acquire and persist json, presumably in a manner amenable to subsequent consumption by a efcore 7 dbcontext

in the scenario, the 'json ingestion, persist to db' workflow is assumed not to have access to poco clr types, and an asssociated dbcontext

please advise

**Comment by maumar** [comment]
You can store JSON in a column in a database column using whatever means you like, doesn't have to be thru EF. EF expects it to be in a certain format - we store it very close to how `System.Text.Json.JsonSerializer` does it with it's default settings - the only difference is that EF stores enum values as strings, rather than ints. 

We plan to add customizable serialization options in the future (tracked here: https://github.com/dotnet/efcore/issues/28043)

But even currently you should be able to serialize an object using JsonSerializer (or manually craft the JSON string, or whatever), store it a JSON column in SQL Server using your preferred method, then configure EF model to map a POCO structure to that JSON column and proceed from there as if you've done everything using EF from the start.

**Comment by vigouredelaruse** [comment]
thanks for the clarification. also i prefer to reason over string enums in debugging scenarios
