### ISSUE TITLE
AddOrUpdate leads to incorrect foreign key update

### ISSUE THREAD

**Issue by hermesramos** [dotnet/efcore#2960]
I am having the same error as the one reported at Stack Overflow: http://stackoverflow.com/questions/20300035/entityframeworks-addorupdate-leads-to-incorrect-foreign-key-update/32281544#32281544

Example:

var state = new State { Name = "NY" }
Context.States.AddOrUpdate(p => p.Name, state);
Context.SaveChanges();

var city = new City { Name = "NYC", Location = "1", State = state }
Context.Cities.AddOrUpdate(p => p.Name, city);
Context.SaveChanges();

var city = new City { Name = "NYC", Location = "2", State = state }
Context.Cities.AddOrUpdate(p => p.Name, city);
Context.SaveChanges();

Exception is thrown, saying Foreign Key StateId = 0

Thanks

**Comment by ajcvickers** [comment]
@hermesramos This is because of the behavior described in this bug: http://entityframework.codeplex.com/workitem/2128 The workarounds described there should also work here for ensuring that the correct entity instance is used. FYI, we track EF6 issues on the CodePlex site, so that would be the best place to file EF6 issues in the future.
