### ISSUE TITLE
EfCore: How to use override Equals Model Compare

### ISSUE THREAD

**Issue by karimz1** [dotnet/efcore#29625]
Hello Everyone, I have a question please, that I could not find in the MS Docs.

I want to override the default comparer in EF Core to use the override Equals of a Model.

```csharp
// Example Model
public class Customer{
      public int Id { get; set; }
      public string FirstName { get; set; }
      public string LastName { get; set; }
      public string Email { get; set; }
    
     public override bool Equals(object? obj)
      {
          var other = obj as Customer;
          return this.FirstName == other.FirstName &&
              this.LastName == other.LastName &&
              this.Email == other.Email;
      }
    
      public override int GetHashCode()
      {
          unchecked
          {
              int hash = GetType().GetHashCode();
              hash = (hash*31) ^ FirstName.GetHashCode();
              hash = (hash*31) ^ LastName.GetHashCode();
              hash = (hash*31) ^ Email.GetHashCode();
              return hash;
          }
      }
}
```

When I perform an entity compare using Linq, I want to use my overridden Equals Logic from the Model. 

```csharp
bool isCustomerInDb = DbContext.Set<Customer>().Any(c => c == customer);
```

Expected SQL Output, should be like this: 
``` sql
SELECT c.Id, c.Email, c.FirstName, c.GenderId, c.LastName
FROM Customer AS c
WHERE ((c.FirstName == @__customer_FirstName) && (c.LastName == @__customer_LastName)) && (c.Email == @__customer_Email))
```

I hope someone here can lead me to the right direction.

Sincerely
Karim

___
Setup:
EF Core version: 6.0.3
Database provider: (Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (NET 6.0)
Operating system:
IDE: (Visual Studio 2022 17.4)

**Comment by roji** [comment]
@karimz1 EF Core has no idea about the implementation of your Equals method, and cannot translate it to SQL. The SQL translation for equality - when the thing being compared is an entity type rather than a scalar - is to compare the primary keys; this approximates a reference identity check in C# (i.e. [object.ReferenceEquals](https://learn.microsoft.com/en-us/dotnet/api/system.object.referenceequals?view=net-7.0#system-object-referenceequals(system-object-system-object))).

If you want to compare in a different way, you'll have to spell it out inside your LINQ query, e.g.:

```c#
bool isCustomerInDb = DbContext.Set<Customer>().Where(c => c.FirstName == customer.FirstName && c.LastName == customer.LastName /* and so on */);
```
