### ISSUE TITLE
Nullable object must have a value within Entity Framework Core 6.0

### ISSUE THREAD

**Issue by AndreiBalan7** [dotnet/efcore#29691]
Hi,

I am working on a team that we are using EF with .NET Core 3.1 from a long time and we decide to upgrade to .NET Core 6. We have a very huge application with over 600 queries.

Looks like I found a situation when going through FK's, something like this: Property = x.Table1.Table2.Table3.Table4.Id and one of this table could be null, so the result of Id will be int?, but the property is int. I found a fix, cast to (int?) before, but this will be a pain to do this change to over 600 queries. I know that 3.1 replaced the value with default value of the type. Is something like this possible with only one line of code, somehow to configure EF to replace null with default value, not throw an error ?

Thanks.

**Comment by maumar** [comment]
As far as I know there is no good/easy way to do this in EF6. In EF7 we added query interceptors (https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#linq-expression-tree-interception) an advanced feature that allows you to customize query expressions before EF query engines consumes them. 

You would need to recognize the pattern you want (e.g. member access that results in non-nullable int or other primitive) and change it to convert to nullable and then add coalesce default value on top. Simply adding conversion won't work in Expression tree world because types would all be wrong. But coalesce guarantees the correct types so all should work. Note your might need to also be smart about not making changes inside predicates.

**Comment by roji** [comment]
@AndreiBalan7 what @maumar wrote is definitely a possibility. At the same time, I'd personally advise against trying to solve this via such automatic rewriting of the queries - it's a hard task to get right, and such implementations are frequently brittle. In addition, you end up with LINQ C# code that's essentially wrong, since the returned type really is an `int?` (but that wouldn't be visible when looking at the query source).

I'd advise investing in comprehensive test coverage that would tell you which queries are failing, and fixing up the actual queries. I know it's likely not the answer you'd like to hear and it could take a lot of work, but ultimately that's the way to ensure that your code works correctly across upgrades etc.

**Comment by AndreiBalan7** [comment]
Thanks @maumar and @roji for your answers. I decided to validate each query and add cast where needed. 

I have another big problem with some generic code using Expression that can't be computed anymore. I will post this in a different issue.

**Comment by 11220287** [comment]
@AndreiBalan7 

How was it resolved in the end, but the editor did not tell me which parts needed to be modified. Can you tell me how it was handled

Thanks.
