### ISSUE TITLE
[7.0, SQL Server]: No option to override auto-generated Index filter for nullable columns

### ISSUE THREAD

**Issue by schuettecarsten** [dotnet/efcore#29739]
I have an entity like this:

```
[Index(nameof(SubscriptionGuid), nameof(EntitlementGuid), IsUnique = true)]
public class AzureSubscription
{
	public Guid SubscriptionGuid { get; set; }

	public Nullable<Guid> EntitlementGuid { get; set; }
```

The migration for the index is

```
            migrationBuilder.CreateIndex(
                name: "UQ_AzureSubscription_SubscriptionGuid_EntitlementGuid",
                table: "AzureSubscription",
                columns: new[] { "SubscriptionGuid", "EntitlementGuid" },
                unique: true,
                filter: "[EntitlementGuid] IS NOT NULL");
```

The problem is that the index filter removes all rows where EntitlementGuid is null from the index. This might be by design. But there is no (easy) solution to override this auto-generated filter and set the filter to "null".

**Comment by roji** [comment]
IIRC SQL Server treats two nulls as non-distinct, meaning that if the unique index doesn't have that filter, you can't have more than one row with null. Is this your intention? Note that you can set up a second, non-unique index to speed up the null lookup, if that's what you're looking for.

Otherwise, you can manually remove the filter from the generated migration code. If you want to get rid of it globally in your application, you can also remove SqlServerIndexConvention, which is what adds the filter:

```c#
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    configurationBuilder.Conventions.Remove(typeof(SqlServerIndexConvention));
}
```

**Comment by schuettecarsten** [comment]
@roji Okay, if understand correctly, SQL treats the whole index entry as null if one value is null and that's why EF code has to exclude null values from the index?

**Comment by roji** [comment]
> SQL treats the whole index entry as null if one value is null

I'm not sure what that means, but if you remove that filter, then you can no longer insert more than one entry which has NULL in EntitlementGuid.

**Comment by schuettecarsten** [comment]
Thank you for explanation.

**Comment by schuettecarsten** [comment]
@roji I took a look into SqlServerIndexConvention and unfortunately, any custom index filter gets removed by that convention. Is that expected?

**Comment by roji** [comment]
Can you post some code that shows this happening?
