### ISSUE TITLE
EF Migrations requires full path of web.config file

### ISSUE THREAD

**Issue by thepaulpage** [dotnet/efcore#2974]
Running migrate tool from the command line throws a weird error when not using the full path to the web.config file: 
Works:
migrate CodeFirst.dll /startUpConfigurationFile:"D:\app\ProPharmOnePlus\web.config"

Doesn't work:
migrate CodeFirst.dll /startUpConfigurationFile:"web.config"

It would be nice if the error mentioned that it couldn't find the file instead of just saying that it can't find the connection string name

**Comment by rowanmiller** [comment]
This is an EF6 issue with migrate.exe (EF6 issues are tracked at http://entityframework.codeplex.com). That said, before I send you over to open an issue there... `migrate.exe` has a bunch of issues and we are going to build a much more robust CLI in EF7. This isn't something our team is planning to spend time addressing in `migrate.exe` (mostly because it is minor compared to the all up issues the tool has) but we would accept a contribution if it was something you wanted to look at.

**Comment by thepaulpage** [comment]
I'll be glad for a better CLI in EF7.  I can live with what I have till then, thanks a lot.

**Comment by hminaya** [comment]
Uffff, I just spent a couple of hours battling this. Thanks for the tip.

**Comment by rangelier** [comment]
I'm moving from one exception into another with the EF6 migratie.exe CLI. This tool should make live easier, not harder.

**Comment by thepaulpage** [comment]
there might be some help in this SO question: http://stackoverflow.com/questions/28724546/cant-run-code-first-migrations-using-migrate-exe/29853289#29853289.  We got ours working

**Comment by rowanmiller** [comment]
Also worth looking at the docs for migrate.exe if you haven't already https://msdn.microsoft.com/en-us/library/jj618307(v=vs.113).aspx. We know it has a bunch of issues.
