### ISSUE TITLE
Is CommandCreating/Created/Initialized interceptor guaranteed to be invoked?

### ISSUE THREAD

**Issue by rayao** [dotnet/efcore#29813]
Because I see this in the RelationalCommand
https://github.com/dotnet/efcore/blob/767bc93c6e6fca19868f486c7df8f4235bcf53cd/src/EFCore.Relational/Storage/RelationalCommand.cs#L779
and seems there's an expiration time in the RelationalDiagnosticsLogger, so if I want to alter command text in CommandInitialized interceptor, is it possible the call is bypassed for cache not expired?

**Comment by roji** [comment]
Whether any sort of logging/interception is needed is cached within that method, so that we don't have to check every time (is there an interceptor, is a diagnostics listener registered...). When the cache period expires, we simply check again. This speeds up the case where no logging/interception is set up, which is very common. Since interceptors are set up when the context is initialized, they should always be invoked.

Are you asking because you're seeing a different behavior?

**Comment by rayao** [comment]
Thanks @roji 
I'm asking because I want to utilize it to alter command text, being afraid of that it might not fulfill my purpose.
BTW, I saw many samples override Execute*(Async) methods to alter command, but I guess CommandInitialized can cover all SQL commands, equivalent to overriding all Execute*(Async) methods, right?

**Comment by roji** [comment]
@rayao yes, using the command interceptor is a reliable way to modify SQL in any EF-generated database command.

**Comment by rayao** [comment]
Thanks, got what I want to know.
