### ISSUE TITLE
Linq query is throwing exception "could not be translated. Either rewrite the query in a form that can be translated...

### ISSUE THREAD

**Issue by tahaAttique** [dotnet/efcore#29829]
Hi, I am building a platform on the blazer server, Dotnet core. I am using the code-first approach in EF core using repository patterns. The problem is there are messages in the database. I have an array of strings. I have to get those messages from the database in which all the strings in the array are present.

To accomplish this, I have created the LINQ expression to send it as a filter in the EF core to get all those messages.

```c#
public Expression<Func<EmailHistory, bool>> WithSearch(string searchTerm)
{
    // Here it is converting a string to a list of words by separating it on the basis of " ". 
    // Trim() is used to remove extra spaces
    string[] listOfWords= (searchTerm.Trim()).Split(' ');
    return emailHistory =>
        listOfWords.All(x => emailHistory.Message.Contains(x));
}
```

The above expression expectedly should have returned all the messages containing all the strings in the "listOfWords" array but instead, it is throwing the following exception

![image](https://user-images.githubusercontent.com/47359465/207023546-8b64cc08-8176-41ca-9ad2-03f62a02ad5c.png)

I am unable to understand the reason why it can't be translated and how to make this possible.

Can you help? Thanks in Advance

**Comment by roji** [comment]
@tahaAttique the above code is very fragmentary - it's difficult to understand what you're actually doing, and how the returned expression is integrated in the larger query tree. In general, when creating an issue, please post a runnable, minimal code sample. You're also not specifying which database you're using (SQL Server?).

But in general, EF doesn't translate the pattern `arrayVariable.All(x => x.StringColumn.Contains(x))`, since there's no analogous SQL construct for that. You could implement this by dynamically generating the predicate as follows:

```c#
var listOrWords = new[] { "a", "b" };

var parameter = Expression.Parameter(typeof(Blog), "b");
var column = Expression.Property(parameter, nameof(Blog.Name));

var predicate = listOrWords.Aggregate(
    (Expression?)null, (prevExpression, word) => prevExpression is null
        ? Expression.Equal(column, Expression.Constant(word))
        : Expression.AndAlso(prevExpression, Expression.Equal(column, Expression.Constant(word))));

var lambda = Expression.Lambda<Func<Blog, bool>>(predicate ?? Expression.Constant(true), parameter);
```

This generates the following SQL:

```sql
SELECT [b].[Id], [b].[Name]
FROM [Blogs] AS [b]
WHERE [b].[Name] = N'a' AND [b].[Name] = N'b'
```

Note that the actual values are embedded in the SQL as constants, which means that every word list needs to get recompiled by EF and has its own query plan in SQL Server (causing plan pollution). This isn't good for performance; I'd suggest trying to think of another way to design your query.

**Comment by tahaAttique** [comment]
Hi @roji, thanks a lot for ur response.  

Considering the same example u gave, what I feel is that the above code is solving the case where there is a list of words and we need to find out all the blogs from the database whose name is equal to all the words in the listOrWords. 

Actually, I want to solve the use case in which I want to get those blogs whose name will **contain** all the words in the listOrWords.

I am sorry for the missing information. I am using MS SQL. Implemented the Repository and Unit of Work Patterns with Entity Framework code first approach. 

![image](https://user-images.githubusercontent.com/47359465/207515116-36b5b8a4-2a07-438f-a690-f53063d6e58b.png)

The above code is the expression that I send to the where clause to get specific data from the database. Please check out the code below to understand. 

`context.EmailHistories.where(expression)` 

I hope I am clear now. Thanks again

**Comment by roji** [comment]
> Actually, I want to solve the use case in which I want to get those blogs whose name will contain all the words in the listOrWords.

Right, I missed that, sorry. But the solution I gave is basically the same: simply replace the Expression.Equal there with an Expression.Call that references the string.Contains method. Since using Aggregate requires duplicating that (once for the first expression, once for all subsequent ones (composition with AndAlso), you may want to switch to a loop instead.

**Comment by tahaAttique** [comment]
Thanks a lot @roji

**Comment by tahaAttique** [comment]
Problem Resolved with the following 

![image](https://user-images.githubusercontent.com/47359465/207786390-f0b71b01-b711-43c3-8512-411f0fa7a301.png)

**Comment by stevendarby** [comment]
@tahaAttique @roji 
FWIW you can avoid constants by changing the line generating an enumerable of ConstantExpression to this:
```C#
var values = listOfWords.Select(x =>
{
    Expression<Func<string>> valueExpression = () => x;
    return valueExpression.Body;
});
```

Note though that you'll hit the parameter limit if there are more than 2100 words.
