### ISSUE TITLE
Why Collection navigations should never be null ?

### ISSUE THREAD

**Issue by Socolin** [dotnet/efcore#29892]
Hello

Why Collection navigations should never be null ?  as the note specify here https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#required-navigation-properties

If I did not do a `.Include()` on a collection, and the collection is not null, how can I know if I forget to load it or if there is no entity yet (0:n relation)

So far it seems to work so I'm wondering why should I not have this `null` when not loaded like this ?

```cs
private ICollection<Child>? _children;
public ICollection<Child> Children
{
    get => _children.ThrowIfNotLoaded();
    set => _children = value;
}
```

**Comment by roji** [comment]
> If I did not do a .Include() on a collection, and the collection is not null, how can I know if I forget to load it or if there is no entity yet (0:n relation)

If there's no entity, the collection navigation should be empty, not null (as per the doc note::

> Collection navigations, which contain references to multiple related entities, should always be non-nullable. An empty collection means that no related entities exist, but the list itself should never be null.

Forgetting to load a collection and then accessing it is a programming bug. You can choose to be defensive about it and have a wrapping property that throws on null (as above), that's seldom necessary or even very helpful; since actually accessing the unloaded collection would throw NullReferenceException, all this does is replace that exception with another exception.

The important point is that the publicly-exposed navigation shouldn't be nullable, since a loaded collection navigation is never null - only possibly empty. So you should not be imposing null checks on all code accessing the collection just because of a possible programmer bug where the navigation wasn't loaded.

**Comment by Socolin** [comment]
Thanks for the clarification.

In my case I prefer throwing an exception saying `"The entity Xxxx was not loaded on Yyyyy"` instead of a `NullReferenceException`  it's the same at the end, but it's easier to debug.

Adding this I found few bugs in our code, so not always init those collection is helpful in my scenario.

Since this was in a doc I was just curious to understand why and I wanted to make sure this would not break in the future.

**Comment by MamboJoel** [comment]
Wouldn't forbiding null collections cause an ambiguity?

As a consumer of a class that has been instanciated by EF (through the repository pattern for instance) I find it quite useful to be able to tell if the collection is empty because items where not included (`Include()` in EF) or because the collection is really empty in the DB.

Example.

``` c#
public class Order {

    public List<Item> Items { get; set; }

}

public class Item
{

}

public interface IOrdersRepository
{
    Order Get(int id);

    Order[] Search(string args);

}
```

When an `Order` has been instanciate through `IOrdersRepository.Get()` we can likely assume that `Order.Items` was binded from the data source. But perhaps it was not in `IOrdersRepository.Search()`. And as a consumer of an instance of `Order` I don't have to know the implementation behind these methods.

- Having `Order.Items == null` tells me that `Items` was not binded.
- Having `Order.Items.Count == 0` garantees me they were binded and that the `Order` has no items.

But if `Order.Items` are always instanciated wether they were binded or not, a consumer can wrongly assume the order has no items in the database when actually it could have.

Forbiding this behaviour could propagate this ambiguity up the stack to the UI developper.

**Comment by roji** [comment]
@MamboJoel the main issue with that is that it forces each and every access of the navigation property to check for null, which is very rarely what users want. The usual pattern is to know whether you've loaded the navigation or not, and either access it or not based on that: a repository wrapping would have a different API which loads the navigation, and a call-site using that API would know they can always access it (and vice versa). Having different APIs is important also in order to ensure that the navigation is never loaded when it isn't needed, which would be bad for perf.

But if you're transferring around the results of a query, with the eventual consumer not knowing where they come from or whether the navigation was loaded, then it may make sense for the navigation to be nullable in order to express that.

**Comment by MamboJoel** [comment]
@roji thanks a lot for your response. I'm probably mistaking but I have the feeling that this non null collection design implies the consumer of a class has to know what API was used to instanciate it. In my example knowing an `Order` was instanciated through `IOrdersRepository.Search()` the consumer wont mess with the `Items` property. Well, at the end of the day, we are all grownups.

But the risk, in my opinion, is for dependencies of this collection. Say you have a method of `Order` (or any other type for that matter) that relies on the `Order.Items` to compute a total for instance; a method that the consumer of the class might not even be aware of. It could seen as safer for this method to handle `NullReferenceException` (or even throw it) instead of leting a wrong computation go along.

**Comment by ajcvickers** [comment]
@MamboJoel Are you suggesting we change something here, or do you just have a different opinion?

**Comment by roji** [comment]
We could change the doc warning wording to be a bit softer on this - I do agree there are some patterns where a nullable collection navigation might make sense; it's just that it's definitely not the standard thing.

**Comment by MamboJoel** [comment]
Thanks for your reply @roji. Please do not change anything. We can just disable the warning on these projects.

**Comment by alexanderchr** [comment]
If best practice is to initialize collection navigations to an empty collection instead of null, maybe this should be reflected in other places in the documentation, for example [here](https://learn.microsoft.com/en-gb/ef/core/querying/related-data/eager) and [here](https://learn.microsoft.com/en-gb/ef/core/querying/related-data/lazy)?

**Comment by ajcvickers** [comment]
@alexanderchr There are pros of lazy-initialization (no allocations if the navigation isn't used) and eager-initialization (no null checks).

**Comment by alexanderchr** [comment]
@ajcvickers Agreed, I'm just pointing what I think is an inconsistency in the docs.

To clarify: [here](https://learn.microsoft.com/en-gb/ef/core/miscellaneous/nullable-reference-types#required-navigation-properties) is it explicitly stated

> Collection navigations, which contain references to multiple related entities, should always be non-nullable. An empty collection means that no related entities exist, but the list itself should never be null.

and for example [here](https://learn.microsoft.com/en-gb/ef/core/modeling/relationships/one-to-many) the collections are initialized to empty lists. However not so on the pages I linked above.

I think that either the pages on eager and lazy loading should be updated to also initialize the collections to empty lists, or the note on the nullable reference types page should be rewritten to be less absolute.

**Comment by ajcvickers** [comment]
@alexanderchr Declaring the collection as non-nullable or not is different from eagerly initializing it or not.
