### ISSUE TITLE
Issue/PR 30,000! Let's celebrate!

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#30000]
We have reached 30,000 combined issues and PRs in this repo. Let's celebrate by posting words of thanks to the team and community!

![image](https://user-images.githubusercontent.com/1430078/211017615-afbab986-6fac-4f5c-b34b-39e7e38b8202.png)

**Comment by ajcvickers** [comment]
I'll start by saying thank you to the amazing team I work with. I've been working with most of you for many years now, and I'm so grateful for that. It has been and continues to be a pleasure. ❤️ ❤️ ❤️ 

And of course, also thank you to all the past team members from the last 14 years. We wouldn't be where we are now without you all! ❤️ ❤️ ❤️

**Comment by flensrocker** [comment]
Thank you for giving me "compile-time-safe-SQL"! 🦄

**Comment by ErikEJ** [comment]
Thanks for the great interaction with the team both in person and virtually over the years. 

It has been an amazing journey to see EF Core mature to the competent EF6 Classic replacment it is today.

**Comment by inlineHamed** [comment]
🎉🥳🎆🎉🥳🎆🎉🥳🎆🎉🥳🎆

**Comment by JeremyLikness** [comment]
Congratulations! There are so many thinks to give thanks for, but I'd specifically like to raise a toast to open source. I believe the teams commitment to doing everything in the open, both with and for the community, has created a model of what success looks like for an OSS project with corporate backing.

**Comment by MohadKamil** [comment]
Oh that's great, I've been a consumer of your great work, you did a great job over the last year's, each EF core release was better and added more performance improvement, congrats to you from a small .NET developer 🎉

**Comment by rasmusfjord** [comment]
Love your amazing work 🥂🍻🍾🍰

**Comment by joelmandell** [comment]
I have been following Entity Framework since its birth. Loved the idea behind ORM from the start and having it for the .NET ecosystem IMO is essential.

It amazes me how you keep improving the software and its performance.
Thank you guys for your hard work! 👏👏🍾

If there ever will be an in-person meetup in Europe (i.e. Berlin). I hope I would have the opportunity to meet such a nice them like you.

**Comment by fschlaef** [comment]
Thank you EF team ! You guys are awesome 🍾

**Comment by davidroth** [comment]
I am actively using EF since 2013, starting with EF 6.0.0 so its almost a 10 year journy now 😅
Thanks for your amazing work and the expectional communication + transparancy with the community. 
Love the direction of EF (Core). It was a wild ride from EF Core 1.0 to where we are now, but the EF Team is truely amazing. Nice people and exceptional technical skills!
Keep rocking!

**Comment by roji** [comment]
Thank you all for all the kind words!! It's really heart-warming to read ❤️

**Comment by TonyValenti** [comment]
... back in my day we had to write stored procedures, DB migration scripts, and full blown DALs by hand.

I am sure glad those days are over. 

I love you EFCore! ❤️

**Comment by vslee** [comment]
Amazing product from an amazing team! EF is the killer app of .net
