### ISSUE TITLE
Optional columns

### ISSUE THREAD

**Issue by arnoldtaal** [dotnet/efcore#30015]
My question is, if there's an option in Entity Framework which makes it possible to have optional columns? Or maybe there's another solution for the following problem.

My application uses EF to communicate with several Oracle databases. This database has different versions. So one version could miss one column towards another version. I know that there is de option tot Ignore a column but than this column will always be ignored. I only want to ignore this column if it isn't available.
Is there a solution for this or maybe a workaround?
Thanks in advance!

**Comment by roji** [comment]
@arnoldtaal I'm not sure what exactly you're asking for.

Your database table may contain more columns than EF knows about - this in itself isn't a problem. EF only queries for the columns it knows about, and only similar only inserts/updates values for columns it's aware of.

However, if you want EF to be configured with a column that may or may not be there, then that's not possible. EF generates SQL to e.g. query table and fetch back its columns; if the database is missing a column that's supposed to be there, the SQL query will fail at the database, since that column is missing.

**Comment by ErikEJ** [comment]
Multiple DbContexts?

**Comment by ajcvickers** [comment]
As @ErikEJ said, or more generally, there will be a different EF model each different database. This could be done with multiple DbContexts, or by having multiple models with the same context--see [Alternating between multiple models with the same DbContext type](https://learn.microsoft.com/en-us/ef/core/modeling/dynamic-model).
