### ISSUE TITLE
Add ToHashSetAsync() to IQueryable<T>

### ISSUE THREAD

**Issue by wertzui** [dotnet/efcore#30033]
In current EF Core code, most queries are written like this
```
List<Blog> blogs = await context.Blogs.Where(b => something).ToListAsync(cancellationToken);
```

The problem I see with this approach is that `List<T>` implies an order of the elements, although the database does not guarantee an order as long as there is no `OrderBy()` in the query.

I know that this pattern is well established and it might be impossible to change it.
However to allow to better express that there is no order, I would like to see another extension method `ToHashSetAsync()`. 
Then one could write a query like this
```
HashSet<Blog> blogs = await context.Blogs.Where(b => something).ToHashSetAsync(cancellationToken);
```

This would better express that there is no ordering to all consumers of the `blogs` collection.

**Comment by roji** [comment]
I think it's generally fine to use a list/array for unordered data; it's most probably more efficient to enumerate over it, for example (memory locality).

But since .NET has [ToHashSet](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tohashset?view=net-7.0#system-linq-enumerable-tohashset-1(system-collections-generic-ienumerable((-0)))), I think it makes sense for us to have ToHashSetAsync just like we have ToListAsync/ToArrayAsync etc.

**Comment by qsdfplkj** [comment]
I looked at ToListAsync and it's pretty straight forward you can write your own extension:

    public static async Task<HashSet<TSource>> ToHashSetAsync<TSource>(this IQueryable<TSource> source, CancellationToken cancellationToken = default)
    {
        var hashSet = new HashSet<TSource>();
        await foreach (var element in source.AsAsyncEnumerable().WithCancellation(cancellationToken))
        {
            hashSet.Add(element);
        }

        return hashSet;
    }

**Comment by wertzui** [comment]
I've created a PR to add the missing methods.
Would be nice if someone could review it.
