### ISSUE TITLE
EF Core ChangeTracker entities snapshot and reset to that snapshot

### ISSUE THREAD

**Issue by vzarskus** [dotnet/efcore#30097]
## Ask a question

Is it possible to take a snapshot of the current state of EF Core's `ChangeTracker` and then reset later to that snapshot if needed? Let's say I want to make the following code into reality:
```
public async Task ExecuteTransactionAsync(DbContext context)
{
    var executionStrategy = new SqlServerRetryingExecutionStrategy(context);
    var retries = 0;
    var snapshot = null;

    await executionStrategy.ExecuteAsync(async () =>
    {
        var txOptions = new TransactionOptions
        {
            IsolationLevel = IsolationLevel.ReadCommitted
        };
        using var transaction = new TransactionScope(TransactionScopeOption.RequiresNew, txOptions, TransactionScopeAsyncFlowOption.Enabled)

        if (retries > 0 && snapshot != null)
        {
            // This method in reality doesn't exist.
            context.ChangeTracker.ResetToSnapshot(snapshot);
        }
        // This method in reality doesn't exist.
        var snapshot = context.ChangeTracker.TakeSnapshot();

        retries += 1;
        
        // Let's imagine that we are doing an insert operation on the context.
        context.DoInsert();

        await context.SaveChangesAsync(false);

        // Let's imagine that we are doing an update operation on the context.
        context.DoUpdate();

        // Let's say this SaveChanges fails the first time and the transaction will retry.
        await context.SaveChangesAsync(false);

        transaction.Complete();
    }
}
```
**Why would this be useful?**
I have found it hard to work with `ChangeTracker` and retrying transactions. The transaction itself of course works fine, the changes will be rollbacked database side between retries. However, `ChangeTracker` doesn't seem to have a similar rollback functionality.
There is `SaveChanges(false)` option which is supposed to be used with transactions in order to preserve the state of `ChangeTracker` between retries. However, if I had an insert on the first run of the transaction, on the second run (first retry) another entity would be added to the `ChangeTracker` and then on successful `SaveChanges`, two entities would get inserted to database, but my expectation from the code was to have one entity inserted.
```
public async Task ExecuteTransactionAsync(DbContext context)
{
    var executionStrategy = new SqlServerRetryingExecutionStrategy(context);

    await executionStrategy.ExecuteAsync(async () =>
    {
        var txOptions = new TransactionOptions
        {
            IsolationLevel = IsolationLevel.ReadCommitted
        };
        using var transaction = new TransactionScope(TransactionScopeOption.RequiresNew, txOptions, TransactionScopeAsyncFlowOption.Enabled)

        // On the first retry, the ChangeTracker will already have a new entity added.
        // DoInsert will add another one and now I will have two new entities
        // when my expectation was just one.
        context.DoInsert();

        await context.SaveChangesAsync(false);

        context.DoUpdate();

        // Let's say this SaveChanges fails the first time and the transaction will retry.
        await context.SaveChangesAsync(false);

        transaction.Complete();
    }
}
```
A similar problem would occur when updating an entity with `+=` or `-=` operators. If, for example, an entity had `Price = 10` and `.DoUpdate` would do `Price -= 2` - after the first retry (so after the code wrapped in the transaction would run twice) I would have `Price = 6` because it was subtracted twice, when my expectation at the end of the transaction was to have `Price = 8`.

So it got me thinking that a total reset to some `ChangeTracker` state in some point of time or something similar along these lines would be extremely useful.

### Include provider and version information

EF Core version: 6.0.9
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Windows 10
IDE: VS Code

**Comment by ajcvickers** [comment]
@vzarskus Typically this would form a single unit of work, and that whole unit-of-work would be redone on a clean context instance if the transaction could not be committed.

Note for triage: this could be useful in cases where the application is performing multiple changes that impact context state in a transaction, but the context does not start in a clean state.

**Comment by vzarskus** [comment]
Thank you for the reply!
Just to clarify: 
- There is currently no common approach for transactions where contexts do not start in clear state.
- You will perhaps be investigating an approach that would cover this case?

**Comment by ajcvickers** [comment]
@vzarskus I discussed this with the team and we came to the conclusion that being able to reset the context state to some arbitrary point is very difficult because it would require rolling back of changes made to graphs of entities, including the relationships between them. So this is something we are very unlikely to do. I think this means the options are:

- Start with clean context and repeat everything
- Make sure that the code that interacts with the context is idempotent. For example, check whether a new entity should be tracked and only track it if needed.
- Implement the rollback in application code. This is significantly easier than doing a general rollback, since the application is aware of the graph of entities and their states, and understands what can and cannot be done.

**Comment by molinch** [comment]
When people use Azure SQL dbs or managed instances, then they are forced to use the Retry strategy.
Hence, users need to think about the ChangeTracker having stale data when the delegate will re-run.
I checked lot of samples on internet, and also code from our company and past company, honestly everybody does it wrong since no one expects this behavior.

@ajcvickers @roji While it is clear that this would be a massive change, don't you think that EF should abstract this ?
I truly think that the default should be easy and safe.
Right now, the default for Azure, mostly kills you: if you add an entity, and it retries, you'll have it N times in the DB.

If the retry strategy could reset the ChangeTracker to its state *before* the delegate was initially invoked, I'm sure this would solve massive bugs, a lot of enterprise code currently has.
