### ISSUE TITLE
When did we get support for extension functions(mehods) inside IQueriable.Select ?

### ISSUE THREAD

**Issue by Uraharadono** [dotnet/efcore#30148]
Basically my title: When did we get support to use extension or class functions inside `IQueriable.Select `?

## Demo setup

Let say I have following classes:
```
public partial class Contactpersoon : IEntity
{
    public Contactpersoon()
    {
        OrderContactpersoons = new HashSet<Order>();
    }

    public long Oid { get; set; }
    public string FirstName { get; set; }
    public string Preposition { get; set; }
    public string LastName { get; set; }

    [InverseProperty("ContactpersoonNavigation")]
    public virtual ICollection<Order> OrderContactpersoons { get; set; }

    [NotMapped]
    public string FullName => $"{$"{FirstName} {Preposition}".Trim()} {LastName}";
}
```

```
public partial class Order : IEntity
{
    public long Oid { get; set; }
    public DateTime OrderDate { get; set; }
    public DateTime? DeliveryDate { get; set; }
    public EOrderStatus Status { get; set; }
	
    [ForeignKey("ContactpersoonNavigation")]
    public long? Contactpersoon { get; set; }
    public Contactpersoon ContactpersoonNavigation { get; set; }
}
```

And following extension functions (methods):

```
public static class DateTimeExtensions
{
    public static string ToDutchDateFormat(this DateTime dt)
    {
        DateTimeFormatInfo nlDtfi = new CultureInfo("nl-NL", false).DateTimeFormat;
        string result = dt.ToString(nlDtfi.ShortDatePattern);
        return result;
    }
}
```

```
public static string GetDisplayName(this Enum value)
{
    var field = value.GetType().GetField(value.ToString());
    if (field == null)
        return "";

    var dna = Attribute.GetCustomAttribute(field, typeof(DisplayNameAttribute)) as DisplayNameAttribute;
    if (dna != null)
        return dna.DisplayName;
}
```

And my query finally looks like so:

```
IQueryable<Order> query = _uow.Query<Order>()
    .Where(s => s...)
    .Include(s => s...)
    .AsNoTracking();

if(filter.condition1)
	query = query.Where(s => s...)
if(filter.condition2)	
	query = query.Where(s => s...)
	  
var data = query
            .Skip(filter.Skip)
            .Take(filter.Take);

return data.Select(order => new SalesOrdersOverviewItemDto
{
    Id = order.Oid,
    OrderDate = order.OrderDate .ToDutchDateFormat(),
    DeliveryDate = order.DeliveryDate != null ? order.DeliveryDate .Value.ToDutchDateFormat() : "",
    Contact = order.ContactpersoonNavigation != null ? order.ContactpersoonNavigation.FullName : "",
    Status = order.Status.GetDisplayName(),    
}).ToList();
```
			

## My question and digression

I know for a fact that just until recently that using extension methods or methods from class itself in `IQueryable.Select() ` like in query above, would not work. Actually I am 100% sure that if I have mapped any of the properties above (except from Id) that it would fail. 

I love this, don't get me wrong. I love the fact that I can finally use more of LINQ in future, but where is the release note for this functionality? I cannot find it anywhere.

## Provider and version information

EF Core version: 7.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 10 Version	10.0.19045 Build 19045
IDE: Visual Studio 2022 17.4.4

**Comment by roji** [comment]
@Uraharadono you're asking about the use of ToDutchDateFormat() in the Select, right?

If so, then EF Core has always allowed client-side evaluation (which includes arbitrary .NET method invocations) - but only in the *last* Select. The logic is that the method is simply applied to database results that are queried, and so being able to translate it to SQL isn't important; it doesn't really matter whether the logic is executed in the database before sending the data, or at the client after receiving it.

Calling such a method anywhere else - e.g. in a Where clause - is not allowed and causes an exception. This is because evaluating the method at the client could cause a lot more data to be transferred.

All this is detailed in our [Client vs. Server Evaluation](https://learn.microsoft.com/en-us/ef/core/querying/client-eval) doc page.

**Comment by Uraharadono** [comment]
Hey @roji , 

I asked about 3 things in my example which (if my memory serves me correctly) caused issues before:
- `ToDutchDateFormat() `
- `order.ContactpersoonNavigation.FullName `
- `Status.GetDisplayName() `- which is extension method on the `Enum`, but otherwise same as  `ToDutchDateFormat() `

Keep in mind I kind of skipped couple of years of .Net development, and jumped straight from .Net Framework 4.6.2 to .Net Core 5. Maybe I have missed these release notes in development of EF Core versions. 

Sorry it is always you who has to answer my questions and (at the same time) thank you immensely for being one who answers them.

**Comment by roji** [comment]
@Uraharadono all three examples are instances of the same thing - something in the query tree that cannot be translated into SQL, but is evaluated client-side instead, since it's in the last Select.

I'm honestly not sure whether the old non-Core EF allows client evaluation in this way (@ajcvickers would know), but EF Core has always allowed it.

**Comment by ajcvickers** [comment]
I don't believe EF6 allows it.

**Comment by Uraharadono** [comment]
Wow, I knew something was up! Thanks both (@ajcvickers and @roji) of you guys. This is great news for me!
