### ISSUE TITLE
How to disable plan caching

### ISSUE THREAD

**Issue by martore** [dotnet/efcore#30152]
[https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/query-plan-caching-entity-sql](https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/query-plan-caching-entity-sql)

The article above refers to the property `EnablePlanCaching` in .NET Framework 4.8.1.

I would like to disable query plan caching. Where can I find equivalent to this property in EF Core 7.0?

**Comment by ajcvickers** [comment]
@martore EF Core does not use Entity SQL and so does not have the concept of a "plan cache". What goal is it that you are trying to achieve where you think disabling query plan caching might be helpful?

**Comment by martore** [comment]
@ajcvickers I am facing the same issue as described in [#10535](https://github.com/dotnet/efcore/issues/10535) Microsoft.Extensions.Caching.Memory.CacheEntry has a significant amount of cached data (> 500MB). Rewriting queries is not an option due to the nature of our application. Most queries will be compiled and cached per tenant, every query for each tenant. The number could grow to well over tens of thousands of queries. Application does not have much use of query cache but on the other hand produces high memory use.

**Comment by ajcvickers** [comment]
@martore I don't believe there is a way to disable the query cache, but @roji may know. It would be devastating in terms of performance.

**Comment by roji** [comment]
@martore EF's internal query cache has an upper bound; it is a MemoryCache initialized with MemoryCacheOptions that has a SizeLimit of 10240 ([here](https://github.com/dotnet/efcore/blob/main/src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs#L298)). Each query's entry takes up a size of 10 ([here](https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/Internal/CompiledQueryCache.cs#L67)), so only 1024 queries are ever cached. (in reality, SQLs are cached separately, so the actual number of queries is less). Once the size limit is reached, old entries should get evicted to make space for the new ones.

So I'd be interested in knowing exactly how the memory cache gets to > 500MB; if you're seeing that in a memory profiler, and you're convinced the entries come from EF, it's possible that the GC simply hasn't reclaimed the evicted data yet. If that's not the case, then I'd definitely want to see a minimal repro demonstrating this.

Having written all that, we can consider a per-query operator which instructs us to not cache. Users would put this on totally dynamic queries, and that would prevent eviction of static queries because of dynamic queries which will likely never repeat etc.

**Comment by martore** [comment]
@roji Found an issue in my code. Memory leak did not come from EF. Thanks for the help.

**Comment by roji** [comment]
Reopening to consider tracking an operator to instruct EF to not cache.

**Comment by roji** [comment]
Opened #30158 instead.
