### ISSUE TITLE
Relational: Implement Key table HiLo generator

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#302]
i.e. mimic a sequence using a key table

**Comment by phillip-haydon** [comment]
@rowanmiller I saw your video on c9, it's great to see this is finally coming to EF.

Is there any discussion or draft about the implementation? Is it configurable like NHibernate in regards to Column or Row per key. Or Table per Key. Etc.

Can it be assigned at model level rather than global EF level, if some things are generated in the DB while others are not?

**Comment by rowanmiller** [comment]
@phillip-haydon this issue is particularly about using a table for key values. The functionality that is available already in EF7 uses a sequence for key values. It is full configurable, you can switch it on globally or for individual types, you can uses different sequences for different types, set the start/increment/etc.

**Comment by ajcvickers** [comment]
Closing as we haven't seen significant demand for this feature. We could revisit this decision based on feedback and we would also consider a well-written community PR for it.

**Comment by douglasg14b** [comment]
Well, that's a shame...

**Comment by danielwagstaff** [comment]
Please can this be re-opened and implemented? EF encourages integration testing, rather than mocking the database, but in-memory testing is impossible when using `UseHiLo()`.

**Comment by roji** [comment]
@danielwagstaff are you requesting that UseHiLo be somehow implemented for InMemory? Because this issue was about implementation at relational (and InMemory is not a relational database).

In any case, we discourage using InMemory for testing - InMemory is definitely not a form of integration testing, but rather a test double of your database (similar to a mock).

**Comment by danielwagstaff** [comment]
@roji I was hoping that it would be implemented in SQLite, as that's the recommended in-memory database (https://docs.microsoft.com/en-us/ef/core/testing/sqlite) for testing.

I guess it depends on your definition of Integration/Component/etc, but using an in-memory database would allow me to exercise my business logic, quickly and without the need for additional components, i.e. a database. Maybe my comment would have been better placed here https://github.com/dotnet/efcore/issues/20750, but the issues are linked.

**Comment by roji** [comment]
@danielwagstaff indeed, HiLo support for SQLite is tracked by #20750. Be sure to up-vote it, though as you can, not many people are interested in that (only 8 votes currently).
