### ISSUE TITLE
RelationalDatabaseCreator.CreateTables execute all table create even a table already exists

### ISSUE THREAD

**Issue by barruka** [dotnet/efcore#30424]
When executing the CreateTables() for the first time it works fine, but on future calls, if there is a new table set in the AppDbContext DbSet, the CreateTables() throw an exception that the table already exits.
So, if we have defined entity A and B in AppDbContext, CreateTables() works fine on the first time and it creates table A and table B, but in the next executions, throws exception "table A already exits" and table C is never created.

It would be nice if the CreateTables try to create each table and if it fails keep executing the loop to trying the create the other table ones, to avoid using migrations and other methods.

If you don't consider changing the CreateTables behaviour, maybe you could implement a new method to achieve this goal.

**Comment by roji** [comment]
@barruka CreateTables by design just creates the tables, without checking whether they already exist. Are you maybe looking for [EnsureCreated](https://learn.microsoft.com/en-us/ef/core/managing-schemas/ensure-created#ensurecreated)?

Also, consider using migrations to manage your database schema instead - [see these docs for more details](https://learn.microsoft.com/en-us/ef/core/managing-schemas/). CreateTables/EnsureCreated really are suitable mostly for testing and prototyping, and less for a production application.

**Comment by barruka** [comment]
I ended up addind this method to my AppDbContext.cs (I know it's not the best solution ever, but for the moment it works):

```
    public async Task EnsureTablesCreated()
    {
        try
        {
            var databaseCreator = this.Database.GetService<IDatabaseCreator>() as RelationalDatabaseCreator;
            await databaseCreator.EnsureCreatedAsync();
        }
        catch { }

        try
        {
            var createScript = this.Database.GenerateCreateScript();
            var createScriptStatements = createScript.Split(";");

            foreach (var statement in createScriptStatements)
                try
                {
                    if (!string.IsNullOrWhiteSpace(statement)) 
                        await this.Database.ExecuteSqlRawAsync(statement);
                }
                catch { }
        }
        catch { }
    }
```

**Comment by roji** [comment]
@barruka why are you calling GenerateCreateScript? EnsureCreated (or EnsureCreatedAsync) already creates your database as well as all tables (unless tables already exist).

Also, any reason not to just call Database.EnsureCreated, as per the docs I linked to?

FWIW it's a pretty bad idea to have all those `catch { }` - I'm sure you want to know if the database creation (or script execution) failed.

**Comment by barruka** [comment]
I tried to cover this use case: After adding a new XXX entity to the DbSet collection, auto-create the table XXX when the app starts.
I'm using this procedure to local-cache data of the app, so the db is going to be created in "Environment.SpecialFolder.LocalApplicationData".

So when an user upgrades the app, if their database has not the new "XXX" table, this EnsureTablesCreated will create the table.

I know the empty catch are not suitable for production level, so now I'm working testing the exceptions they can catch and refactoring them.

Thanks!

**Comment by roji** [comment]
@barruka none of these APIs are suitable for managing the incremental creation of additional tables when a new entity type is added; they really are there only in order to create the database and its tables from scratch when it (or the tables) don't exist at all. Trying to make these APIs evolve an additional tables is very unlikely to succeed.

This scenario is exactly what migrations are for - I highly recommend considering that instead; is there any specific reason you're not using them?

**Comment by barruka** [comment]
Ok, I'll consider using migrations.
