### ISSUE TITLE
Question about a Migrations test

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3043]
The Can_generate_up_scripts() test for both SQL Server and SQLite seem to rely on the ability to check if the __EFMigrations table already exists. Will this be an issue for the SQL CE provider, as it does not support this feature?

**Comment by bricelam** [comment]
Hmm, it should be OK to not check and just have a `CREATE TABLE` statement. It's just there as a convenience in case you have two contexts targeting the same database and you want to generate and apply scripts for both. Worst case scenario, they just have to remove it from the second script they apply.

**Comment by bricelam** [comment]
At runtime (i.e. during `Update-Database` and `context.Database.Migrate()`), we check if the table exists and only send the `CREATE` statement if it doesn't.

**Comment by ErikEJ** [comment]
Thanks!

**Comment by roji** [comment]
I just ran into difficulties because of this check for reasons similar to the schema existence check mentioned in #2928. In PostgreSQL you can easily check for the existence of a table, but you can't simply send IF statements to the database. A workaround is to use PL/pgSQL, which is PostgreSQL's procedure server-side language, but that's definitely an ugly hack.

So it should be OK to override `HistoryRepository.GetBeginIfExistsScript` and friends and do nothing?

**Comment by ErikEJ** [comment]
You should throw a Not supported exeception (with explanation) - like the SQLite and SQLCE providers do.

**Comment by roji** [comment]
OK thanks @ErikEJ, I understand things a little better now. Will throw not supported for now, and maybe implement later with PL/pgSQL.
