### ISSUE TITLE
Problem: Scaffolding not taking in consideration the project default namespace

### ISSUE THREAD

**Issue by abelepereira** [dotnet/efcore#3050]
If a project (class lib) is named `Company.Product.Data.xproj` but has configured a different namespace under `SolutionExplorer (right click) | Properties | Application | Default Namespace` text box (for instance something like `Company.Product.DataModel`), `dnx ef scaffold...` operation simply ignores the default namespace producing the RevEng classes with the project file namespace.

**Comment by bricelam** [comment]
This might be tricky. That information isn't stored in the `project.json`, but instead a VS-specific artifact. Thus far, the DNX commands don't know anything about VS.

**Comment by bricelam** [comment]
@davidfowl Any plans to have default namespace configured in the `project.json`?

**Comment by abelepereira** [comment]
I think the ideal solution would be to have only one metadata file containing the root/default namespace: VS could look for the default namespace in project.config or `ef` command (EntityFramework.Commands) assembly should look for a .xproj file in the working directory and if nothing is found, fallback to what's implemented at the moment.

**Comment by rowanmiller** [comment]
Discussed and we aren't going to do anything special in our command line tools to look at xproj (xproj is a VS specific thing and dnx commands are designed to be independent of VS). If it gets promoted to a project.json concept then our command line tools could make use of it. 

We will also look at this when we do the Package Manager Console PowerShell commands, since those are VS specific and making use of xproj info makes more sense.
