### ISSUE TITLE
Unable to use ExecuteUpdate(Async) when  having owned entity

### ISSUE THREAD

**Issue by mgrosperrin** [dotnet/efcore#30521]
An exception is thrown when calling `ExecuteUpdate` when the entity have an owned entity (even if the owned property is not updated).

You can find a small repro here: https://github.com/mgrosperrin/repro_issues/tree/efcore-executeupdate-owned-entity

Just run the program and the exception will be thrown.

### Include stack traces

```
System.InvalidOperationException: 'The LINQ expression 'DbSet<Entity>()
    .Select(e => IncludeExpression(
        EntityExpression:
        e, 
        NavigationExpression:
        EF.Property<SubEntity>(e, "Owned"), Owned)
    )
    .ExecuteUpdate(updates => updates.SetProperty<string>(
        propertyExpression: e => e.Name, 
        valueExpression: "Test"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

```
### Include provider and version information

EF Core version: 7.0.4
Database provider: Microsoft.EntityFrameworkCore.InMemory (but I have the same issue with Microsoft.EntityFrameworkCore.SqlServer)
Target framework: .NET 7.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.5.2

**Comment by ajcvickers** [comment]
@mgrosperrin I am not able to reproduce this with 7.0.4 when using SQL Server--which is what I would expect, since this issue was fixed in #28727.

`ExecuteUpdate` is not supported for the in-memory provider, and we have no plans to add support.

**Comment by mgrosperrin** [comment]
Hello @ajcvickers,
I can confirm this is indeed working on SQL Server with version 7.0.4.

**Comment by roji** [comment]
Duplicate of #28727

**Comment by julealgon** [comment]
> `ExecuteUpdate` is not supported for the in-memory provider, and we have no plans to add support.

@ajcvickers this should be more well documented. Can't you throw a more specific exception saying that instead of just throwing "The LINQ expression {whatever} could not be translated"?

If that's not possible, there should at least have a note in the main documentation page about this limitation. There are zero mentions right now:
- [ExecuteUpdate and ExecuteDelete](https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete)

I spent some time here trying to change my query because I thought I was doing something wrong, but in the end it was just because I was using the inmemory provider 😢

**Comment by roji** [comment]
@julealgon InMemory's limitations are well-documented in https://learn.microsoft.com/en-us/ef/core/testing; we may have not specified ExecuteUpdate specifically as an unsupported feature, but we repeat loud and clear across our docs that the provider generally does not support the features which real databases support, and even when it does, may behave differently. I don't think we'd want to go over every page describing a feature not supported by InMemory and add a warning there.

**Comment by julealgon** [comment]
@roji , fair enough, but wouldn't it be possible to at least provide more specific exception messages when things are not supposed to be used?

"Query cannot be translated" is extremely generic in the context of EF and will almost always cause people to just double/triple check their actual queries instead of suspecting the thing is not supposed to work.

**Comment by roji** [comment]
I agree that we should generally try to throw more specific exceptions, though that's unfortunately often much harder than it sounds... Specifically in this case, we could indeed identify ExecuteUpdate/Delete by their names in InMemory and through a specific question. Can you please open a separate issue for that?

**Comment by Paula2001** [comment]
> @julealgon InMemory's limitations are well-documented in https://learn.microsoft.com/en-us/ef/core/testing; we may have not specified ExecuteUpdate specifically as an unsupported feature, but we repeat loud and clear across our docs that the provider generally does not support the features which real databases support, and even when it does, may behave differently. I don't think we'd want to go over every page describing a feature not supported by InMemory and add a warning there.

I am not using inmemory database I am using test containers which is basically a functional MSSQL db so what can be my problem

**Comment by ErikEJ** [comment]
@Paula2001 This issue is closed, please crate a new issue with exact error message and reproduction details.
