### ISSUE TITLE
Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping..ctor(System.String, System.Type, System.Nullable`1<System.Data.DbType>, Boolean, System.Nullable`1<Int32>)'

### ISSUE THREAD

**Issue by singhdilip1007** [dotnet/efcore#30523]
## Config Details:
```C#
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySql.Data" Version="8.0.32.1" />
    <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="5.0.17" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DBModel\" />
  </ItemGroup>

</Project>
```
## Scaffold Command:

Scaffold-DbContext "server=localhost;port=3306;user=root;password=xxxxxx;database=xxxx" MySql.Data.EntityFrameworkCore -OutputDir DBModel

## Error
Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping..ctor(System.String, System.Type, System.Nullable`1<System.Data.DbType>, Boolean, System.Nullable`1<Int32>)'.

Trying to connect MySQL db to .Net core web app. Please help me

**Comment by roji** [comment]
@singhdilip1007 the Pomelo.EntityFrameworkCore.MySql.Design should no longer be needed - this was removed many releases ago, and that's why there's no newer version. This depends on Pomelo.EntityFrameworkCore.MySql 1.1.2, which is ancient and causes the problem.

In addition, note that .NET 5.0 and EF Core 5.0 are now out of support. Also, it's unclear whether you're intentionally using both MySql.Data.EntityFrameworkCore and Pomelo.EntityFrameworkCore.MySql in the same project; these are two different EF providers for MySQL, you typically should choose one and use only that.
