### ISSUE TITLE
SQLNullValueException not raised on assignment of nullable column to value-type property

### ISSUE THREAD

**Issue by terribad** [dotnet/efcore#30583]
With EF Core 6.x and SQL Server databases, I have encountered inconsistent behavior when assigning a NULL value to a non-nullable property (int, DateTime, etc), when data is loaded including child records of a relationship.

For example, suppose you have the following tables and the corresponding entity model:

``` sql
CREATE TABLE [dbo].[Genres](
	[GenreId] INT IDENTITY,
	[Name] NVARCHAR(120) NOT NULL,
	CONSTRAINT [PK_Genre] PRIMARY KEY ([GenreId])
)

CREATE TABLE [dbo].[Books](
	[BookId] INT IDENTITY,
	[Title] NVARCHAR(160) NOT NULL,
	[PublicationDate] DATETIME NULL,
	[GenreId] INT NOT NULL,
	CONSTRAINT [PK_Book] PRIMARY KEY ([BookId])
)
```

``` cs

public class Genre
{
    public int GenreId { get; set; }
    public string Name { get; set; }
    public List<Book> Books { get; set; }
}

public class Book
{
    public int BookId { get; set; }
    public string Title { get; set; }
    public DateTime PublicationDate { get; set; }
    public int GenreId { get; set; }
    public Genre Genre { get; set; }
}

class Library : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb; database=Library;Integrated Security=true; MultipleActiveResultSets=True");
    }

    public DbSet<Book> Books { get; set; }
    public DbSet<Genre> Genres { get; set; }
}


```
(Note: the PublicationDate property is not nullable value type.)

In the Books table there is a row containing NULL in the PublicationDate column:
``` sql
INSERT INTO [dbo].[Books] ([Title],[PublicationDate], [GenreId]) VALUES 
('Foundation','2003/03/01',1),
('Ender''s Game',NULL,1);
```
When loading books, expect SQLNullValueException, and it goes like this:
``` cs
var db = new Library();
foreach (var b in db.Books)  //-> SQLNullValueException
{
    Console.WriteLine(b.Title);
}
```
But when loading books across genres, the exception is not raised:
``` cs
foreach (var g in db.Genres.Include(g => g.Books))
{
    foreach (var b in g.Books)
    {
        Console.WriteLine(b.Title);
    }
}
```
The default value is stored in the PublicationDate property: 0001/01/01

(In Entity Framework 6.x .NET Framework the exception is always raised.)

I ask: is this an expected behavior, or is it a bug?

**Comment by cihatsolak** [comment]
I think this is expected behavior. because when loading books via `Genres.Include(g => g.Books),` ef core performs a left outer join that returns a null value for the PublicationDate column, which cannot be null when there are no matching records in the Books table. So ef sets the PublicationDate property to its default value instead of throwing a SqlNullValueException. When loading books directly from the Books table, it creates an inner join that excludes the book with a NULL PublicationDate value and throws a SqlNullValueException. i hope i could help.

**Comment by ajcvickers** [comment]
@cihatsolak is correct about the SQL generated when the foreign key is required (non-nullable) rather than optional (nullable). However, for the actual data you posted, the result would be the same either way because the FK value is always 1. (Unless there really isn't a `GenreId` of 1, which would violate the FK constraint.) In this case, the change in behavior is interesting and I will discuss with the team. However, in general if the model doesn't match the actual data in the database (for example, a non-nullable property mapped to a column that contains nulls) then all bets are off in terms of not crashing and returning correct data.

Note for triage:

This query ignores an inappropriate null in `PublicationDate`:

```sql
SELECT [g].[GenreId], [g].[Name], [b].[BookId], [b].[GenreId], [b].[PublicationDate], [b].[Title]
FROM [Genres] AS [g]
LEFT JOIN [Books] AS [b] ON [g].[GenreId] = [b].[GenreId]
ORDER BY [g].[GenreId]
```

Whereas this query throws for the same data:

```sql
SELECT [b].[BookId], [b].[GenreId], [b].[PublicationDate], [b].[Title]
FROM [Books] AS [b]
```

```
fail: 3/27/2023 20:30:50.481 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query)
      An exception occurred while iterating over the results of a query for context type 'Library'.
      System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
         at Microsoft.Data.SqlClient.SqlBuffer.ThrowIfNull()
         at Microsoft.Data.SqlClient.SqlBuffer.get_DateTime()
         at Microsoft.Data.SqlClient.SqlDataReader.GetDateTime(Int32 i)
         at lambda_method5(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
```

**Comment by ajcvickers** [comment]
> If the entity model doesn't match the database data, I expect an exception to be raised

EF Core doesn't do this (EF6 didn't always either) because we use the model to generate the most efficient query and code to read the results that we can, which means either an arbitrary exception can be thrown or the results returned can be incorrect if the data does not match the model.

**Comment by ajcvickers** [comment]
Notes from triage: we would expect the first case to also throw unless there is code to check if the column is null (i.e. IsDBNull), in which case that code should be removed since it is not needed when the model states that the property is non-nullable. However, we should only do this if we do not have to do additional work (e.g. additional checks when materializing) or add too much complexity.

**Comment by maumar** [comment]
this is the shaper we generate for Book entity in the include scenario:

```
(queryContext, dataReader, resultContext, resultCoordinator) => 
{
    Book namelessParameter{0};
    namelessParameter{0} = 
    {
        MaterializationContext materializationContext2;
        IEntityType entityType2;
        Book instance2;
        InternalEntityEntry entry2;
        bool hasNullKey2;
        materializationContext2 = new MaterializationContext(
            ValueBuffer, 
            queryContext.Context
        );
        instance2 = null;
        entry2 = queryContext.TryGetEntry(
            key: Key: Book.BookId PK, 
            keyValues: new object[]{ dataReader.IsDBNull(2) ? default(object) : (object)dataReader.GetInt32(2) }, 
            throwOnNullKey: False, 
            hasNullKey: hasNullKey2);
        !(hasNullKey2) ? entry2 != default(InternalEntityEntry) ? 
        {
            entityType2 = entry2.EntityType;
            return instance2 = (Book)entry2.Entity;
        } : 
        {
            ValueBuffer shadowValueBuffer2;
            shadowValueBuffer2 = ValueBuffer;
            entityType2 = EntityType: Book;
            instance2 = switch (entityType2)
            {
                case EntityType: Book: 
                    {
                        return 
                        {
                            Book instance;
                            instance = new Book();
                            instance.<BookId>k__BackingField = dataReader.IsDBNull(2) ? default(int) : dataReader.GetInt32(2);
                            instance.<GenreId>k__BackingField = dataReader.IsDBNull(3) ? default(int) : dataReader.GetInt32(3);
                            instance.<PublicationDate>k__BackingField = dataReader.IsDBNull(4) ? default(DateTime) : dataReader.GetDateTime(4);
                            instance.<Title>k__BackingField = dataReader.IsDBNull(5) ? default(string) : dataReader.GetString(5);
                            (instance is IInjectableService) ? ((IInjectableService)instance).Injected(
                                context: materializationContext2.Context, 
                                entity: instance, 
                                bindingInfo: ParameterBindingInfo) : default(void);
                            return instance;
                        };
                    }
                default: 
                    null
            }
            ;
            entry2 = entityType2 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(
                entityType: entityType2, 
                entity: instance2, 
                valueBuffer: shadowValueBuffer2);
            return instance2;
        } : default(void);
        return instance2;
    };
    return namelessParameter{0};
}
```

we indeed add the null check for all the properties.

The decision is made in `CreateGetValueExpression` in the `ShaperProcessingExpressionVisitor`. This method takes IProperty (which is non-nullable) but also takes a bool "nullable" parameter, which we derive from the nullability of column in the SelectExpression projection that corresponds to this property. That column is nullable because LeftJoin.

**Comment by roji** [comment]
I'm probably missing something here, but aren't we confusing the case where there's no dependent (Book) and so all its columns are null (because of the LEFT JOIN), and the case where there is indeed a Book but with an unexpected null for a non-nullable property? In other words, should we consider removing the null check for PublicationDate in the shaper above?

**Comment by ajcvickers** [comment]
Discussed in triage and agreed with @maumar's assertions.
