### ISSUE TITLE
Cosmos DB null handling bug

### ISSUE THREAD

**Issue by HEBOS** [dotnet/efcore#30586]
I'm not sure if this is by design, but it is clearly different when compared to relational database query.

**Given the following model:**

```
public class Order
{
    public Guid OrderId { get; set; }
    public Address Address { get; set; }
    public bool? Checked { get; set; }
    public string DistributionPointId { get; set; }
}
```

**and incoming request:**

```
request = {
  DistributionPointId = null
}
```

**When we execute the following query**

```
var query = context.Orders
            .Where(order => order.DistributionPointId == request.DistributionPointId &&  order.Checked == true);
```

**We get it translated to**

```
SELECT c FROM root c  WHERE ((c["Discriminator"] = "Order") AND (c["Checked"] = true))
```

It seems that DistributionPoint is left out of the equation, if the scalar value that we use to compare with, isn't provided.

Is that by design?

-------------------------------------------------------------------------
EF Core version:
Database provider: Microsoft.EntityFrameworkCore.Cosmos, 7.0.3
Target framework: .NET 7.0
Operating system: Windows 11
Visual Studio 2022 17.4.3

**Comment by ajcvickers** [comment]
We recommend against using the in-memory provider for testing--see [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/). While we have [no plans to remove the in-memory provider](https://github.com/dotnet/efcore/issues/18457), we will not be adding any new features to this provider because we believe valuable development time is better spent in other areas. When feasible, we plan to still fix regressions in existing behavior.
