### ISSUE TITLE
Reading is extremely slow if there's a value with a large amount of text

### ISSUE THREAD

**Issue by mikalai-sauchanka** [dotnet/efcore#30644]
I've got records (~20) that have one column with large amount of text. Reading them takes ~20 seconds. The numbers don't matter, it's just slow. In SQL directly it performs < 1 second.

**Comment by roji** [comment]
Are you using async I/O? If so, you're probably hitting https://github.com/dotnet/SqlClient/issues/593 (this is called out in [our docs](https://learn.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli)); switch to using async APIs when interacting with large text/binary data.

Otherwise, we're going to need to see a minimal, runnable code sample in order to help.
