### ISSUE TITLE
Crash in libsqlite3-0 related to topology suite

### ISSUE THREAD

**Issue by gokhangumul** [dotnet/efcore#30805]
Hi,

My project is a .Net Core 6 web api solution and project published ubuntu server.

After the first request I made, I am getting the following error.

```
.NET ThreadPool[1504463]: segfault at 0 ip 0000000000000000 sp 00007fddff7f97f8 error 14` `in dotnet[55f2dc013000+c000]
Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
```

My operating system;
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
```

.NET Info;
```
Host:
  Version:      6.0.16
  Architecture: x64
  Commit:       1e620a42e7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Thanks...

**Comment by bricelam** [comment]
This looks like a known issue with using mod_spatialite v4 with PROJ v6. There are some details about how to work around it in the [Installing SpatiaLite](https://learn.microsoft.com/en-us/ef/core/providers/sqlite/spatial#installing-spatialite) section of our docs. We've been waiting for a new release of SpatiaLite for a long time now.

**Comment by bricelam** [comment]
Hmm, any more info about the exception? You might need to install the SQLite development package:

```sh
apt install libsqlite3-dev
```

If it still doesn't work, try using this version instead:

```xml
<PackageReference Include="SQLitePCLRaw.bundle_sqlite3" Version="2.1.2" />
```

**Comment by gokhangumul** [comment]
`<PackageReference Include="SQLitePCLRaw.bundle_sqlite3" Version="2.1.2" /> `

I updated the package but got the same error for both windows and ubuntu.

```
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load DLL 'sqlite3' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SQLitePCL.SQLite3Provider_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
```

**Comment by ajcvickers** [comment]
@ericsink Any ideas on this? Any way to get more details about why the library can't be found?

**Comment by ericsink** [comment]
Hmmm.  That (most recent) error is coming from the provider I would expect.  That one has no actual logic.  It simply does a straight DllImport of "sqlite3", so there aren't that many ways for the library to not be found.

The most obvious way the library can't be found is that it's not actually there.  :-)  Or it has a name which causes the pinvoke logic to not be able to find it.  Or one of it's dependencies can't be found.

The stack trace from the crash further above does mention a system SQLite, so there's one installed, but I can't be sure that the dotnet runtime is actually finding it, perhaps either due to name or path issues.  I think there's an environment variable that can be set on Linux to dump out diagnostic info about dynamic loading, but I can't remember it, and at the moment I can't find it.

FWIW, that stack trace is tragic.  The crash is happening because both e_sqlite3 and the system sqlite3 are involved.  It looks like EFCore loaded e_sqlite3, and then mod_spatialite, which loaded the system sqlite3, so a busy handler from one sqlite instance got passed to the other one.

Which reminds me, @bricelam ,  I think we've talked about this before, but what would be needed for mod_spatialite to work with e_sqlite3?  Is it basically that we would need to do a custom mod_spatialite build?

**Comment by bricelam** [comment]
[Last I heard](https://groups.google.com/g/spatialite-users/c/pCiZnGEXvHg/m/ikjDEi3XAQAJ), they had a fix in SpatiaLite to play better with custom builds of SQLite. We're just waiting for them to release it. (An have been for nearly two years now...)

**Comment by gokhangumul** [comment]
According to the last posts, Sqlite is not the right choice for spatial operations. :)

Thanks everyone...
