### ISSUE TITLE
How can i disable the new "OPENJSON" feature when using primitive collections?

### ISSUE THREAD

**Issue by Kokujou** [dotnet/efcore#30946]
Apparently with EFCore 8 preview 4 a new feature was introduced that tries mapping "Contains" queries to OPENJSON SQL commands.

i think the reasoning behind this is that we should be able to also map in-memory collections of complex objects.

but if my research is coorect, then OPENJSON is less efficient than a simple IN query for primitive collections. so i'd like to know what i can do either:
- to map only primitive collections to IN statement
- to disable OPENJSON completely

i know there's the way of setting the compatibility level, but this more like seems as a work around and i'm worried that this might then skip some performance improvements on other aspects.

EF Core version: 8.0.0-preview.4.23259.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by roji** [comment]
@Kokujou this question was touched upon in [the blog post](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4), and is also being discussed in-depth in #13617.

We are aware that switching from IN to OPENJSON implies a slight performance decrease for that particular query; but it solves the query plan cache eviction problem, meaning that it stops the eviction of all other queries. The current thinking is that this trade-off is worth it, since query plan cache eviction affects your overall application speed in a significant way. That being said, I'm actively investigating this and looking into possible optimizations.

More concretely, have you actually benchmarked to measure the exact performance impact of switching to OPENJSON? If so, I'm interested in seeing the actual (minimal) benchmark and the results. If you just have a general concern here and haven't actually benchmarked, I'd urge doing so rather than assuming and switching back to the older behavior without hard data.

If you do want to switch back, then the compatibility level is a good way to do so **at the moment** - it does not currently affect any other behavior. This will indeed probably change in the future though.

**Comment by Kokujou** [comment]
thanks for having the time of explaining it to me :) i didn't run any benchmarks yet, especially because right now we can't just increase our compatibility level, so before changing this we wanted to discuss whether this might actually be dangerous as we're also dealing with mass data at various points. 

Sadly non of us is really an expert in SQL and we have no access to such experts, I got confronted with our issue as our DB has a compatibility level of 110 (we're trying to raise it but sadly in our project this is not something easy to do) so when updating it suddenly failed. this is how i got to know that the generated query significantly changed so i was afraid, since writing and parsing a JSON string out of the data and then executing SQL on top of it might actually be a performance problem, hence asking this question.

i'm already reassured when you tell me that this approach is solving a caching-related issue resulting, that is a worthy trade-in and that the compatibility level is currently only affecting this particular feature, so thanks for taking the time to explain this matter to me!

**Comment by roji** [comment]
Compatibility level 110 corresponds to SQL Server 2012, which really is very old by now - I do hope you're able to increase it at some point.

However, if that's the case, then OPENJSON simply isn't supported by your database. That means that you *must* configure EF Core with your compatibility level ([as detailed here](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/#older-versions-of-sql-server)), otherwise your queries will start failing. So for you, the issue isn't really about what performs better - it's that OPENJSON isn't supported at all, which is a scenario we've already taken care of via the compatibility level.

**Comment by dpoornabi29088** [comment]
Hi guys, I just want to disable openjson in ef core without use 'UseCompatibilityLevel(110))' because of performance issues, Is there any way?

**Comment by roji** [comment]
@dpoornabi29088 EF9 introduced TranslateParameterizedCollectionsToConstants specifically to disable OPENJSON, [see docs](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/whatsnew#parameterized-primitive-collections).

Though `UseCompatibilityLevel(110)` shouldn't cause you any performance issues as far as I'm aware (in case you need to stay on EF 8.0).

**Comment by rbsis** [comment]
> We are aware that switching from IN to OPENJSON implies a slight performance decrease for that particular query; but it solves the query plan cache eviction problem, meaning that it stops the eviction of all other queries. The current thinking is that this trade-off is worth it, since query plan cache eviction affects your overall application speed in a significant way. That being said, I'm actively investigating this and looking into possible optimizations.
> 
When analysing a query timeout exception I discovered the generated OPENJSON in the SQL query. With normal usage of WHERE ... IN (...) the query returns data instantaneously. With OPENJSON a timeout occurs after 30 seconds. In my case "a slight performance decrease" is a huge understatement...

**Comment by roji** [comment]
@rbsis see the comment just above about disabling the OPENJSON translation; note also that for the upcoming EF 10 release we're changing the default away from OPENJSON because of these performance issues, [see this release note](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-10.0/whatsnew#improved-translation-for-parameterized-collection)).
