### ISSUE TITLE
MsgPack for Json Serialization 

### ISSUE THREAD

**Issue by khalilsheikh** [dotnet/efcore#30980]
saving all the property names for all the entities will take up lot of table space

ef core should have a option to use MsgPack (MessagePack) json serialization so that it saves the list as array and with key index instead of property names

**Comment by roji** [comment]
@khalilsheikh what exactly are you referring to, saving all the property names where exactly?

**Comment by khalilsheikh** [comment]
Hi @roji , Thanks for the reply.
request you to mention latest standard JSON representation ?
 MsgPack example mentioned to store the json without properties names etc. as it would save bytes.
Having properties names in json field for example: { Contact:[{Phone:123, Extention:123},{Phone:456, Extention: 456}]}
here properties names **Contact**, **Phone**, **Extention** is being repeated for every row which is unnecessary

**Comment by roji** [comment]
@khalilsheikh yes, property name repetition is a well-known inefficiency of the JSON format. However, note that some databases have special JSON representation on-disk: PostgreSQL has jsonb, SQL Server has a planned JSON type as well; these mitigate the size issue with plain JSON by having an efficient, binary representation that may even resemble MsgPack. However, that's an internal storage detail that's never exposed to users.

In any case, as I wrote above, there's nothing stopping you from using value converters to store MsgPack (or anything else) in your column. Since the database doesn't understand MsgPack, you wouldn't be able to do anything with it except read and write it, which is exactly what value converters are good for. For example, you wouldn't be able to write a query that extracts only rows where some field within the MsgPack documentation has some value. This **can** be done with JSON, which is why that's the default format for e.g. primitive collections.

**Comment by khalilsheikh** [comment]
Hi @roji , that's very right. 

the only issue with converter is that we cannot use in where clause and joins.

one of the favorite feature of EF 8 is JSON columns, which translates to OPENJSON when used in where clause and joins

is there a way to make use MsgPack & translate to openjson when the property is used in where clause of join?

if EF core can translate to openjson with the key index instead of property names that would be dream come true.

**Comment by roji** [comment]
> the only issue with converter is that we cannot use in where clause and joins.

That's always going to be the case, including if EF adds built-in support for MsgPack - that's what I've been trying to say above. At the end of the day, the database doesn't know MsgPack - there's no OPENJSON for MsgPack - so you can't do JOIN or WHERE on it. Whatever we do in EF, it won't be more than what a value converter can already do today.

**Comment by ajcvickers** [comment]
Note from triage: this is not something we plan to work on.
