### ISSUE TITLE
IDbContextFactory and AsNoTracking

### ISSUE THREAD

**Issue by jakubmaguza** [dotnet/efcore#30985]
Good day!

I read somewhere, that with Blazor Server it's a [good practice](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#using-a-dbcontext-factory-eg-for-blazor) to use `IDbContextFactory` (Please correct me if I'm wrong).

I'm having bunch of services in my Blazor Server application, all working fine with `IDbContextFactory`. It's known fact, that when reading data from DB, one would like to use `AsNoTracking()` for better performance.

1. I'm wondering if this applies to `IDbContextFactory`. After each use I'm disposing context anyway, and no tracking applies. In that case, using  `AsNoTracking()` will do any good, or it doesn't matter becasue context is disposed?
2. Is there a way of using `LazyLoading` (f.e. with `Microsoft.EntityFrameworkCore.Proxies`) and `IDbContextFactory`?

**Comment by roji** [comment]
> It's known fact, that when reading data from DB, one would like to use AsNoTracking() for better performance.

I'd strongly suggest benchmarking to see whether it actually makes sense in your application. The overhead of tracking queries is typically negigible for real-world applications, and if you're writing an application that needs unit-of-work patterns (e.g. query some entities, change them and then persist the changes back to the database), then it's highly recommended to use tracked queries rather than avoiding them for some theoretical performance gain.

> I'm wondering if this applies to IDbContextFactory. After each use I'm disposing context anyway, and no tracking applies. In that case, using AsNoTracking() will do any good, or it doesn't matter becasue context is disposed?

IDbContextFactory and AsNoTracking are completely orthogonal. AsNoTracking determines whether you queries track the entities they return - this is regardless of whether you dispose your DbContext right afterwards or not. So if you're seeing a performance improvement from using AsNoTracking, you should see the same improvement regardless of whether you use IDbContextFactory or not.

> Is there a way of using LazyLoading (f.e. with Microsoft.EntityFrameworkCore.Proxies) and IDbContextFactory?

Here as well, these two things should be completely orthogonal. Microsoft.EntityFrameworkCore.Proxies is configured by adding UseLazyLoadingProxies() when configuring EF ([see docs](https://learn.microsoft.com/en-us/ef/core/querying/related-data/lazy)), this can be done regardless of whether you use IDbContextFactory or not.

**Comment by jakubmaguza** [comment]
Thanks for an answer Shay,

I made small repo to reproduce my issue. [Here it is](https://github.com/jakubmaguza/IDBContextFactoryAndLazyLoading).

It's Blazor Server project with auth. I changed `SQLServer` to `SQLite` and added `Microsoft.EntityFrameworkCore.Proxies`.
I changed `WeatherForecast` so it contains navigation property.
I also put `WeatherForecast` to database, and change `WeatherForecastService` to read data from database.

Here is what I found:
When using `builder.Services.AddDbContext<ApplicationDbContext>(...)` and then injecting `builder.Services.AddDbContext<ApplicationDbContext>` I can use navigation property with lazy loading without a problem.

However, if I switch to `builder.Services.AddDbContextFactory<ApplicationDbContext>(...)`, inject `private readonly IDbContextFactory<ApplicationDbContext> _dbContextFactory;` and get forecast like this:

```C#
public Task<WeatherForecast> GetForecastAsync()
{
	using (var _context = _dbContextFactory.CreateDbContext())
	{
		return _context.WeatherForecasts.FirstAsync();
	}
}
```
It throws an error:
```
'Microsoft.EntityFrameworkCore.Infrastructure.LazyLoadOnDisposedContextWarning': An attempt was made to lazy-load navigation 'WeatherForecastProxy.Summary' after the associated DbContext was disposed. This exception can be suppressed or logged by passing event ID 'CoreEventId.LazyLoadOnDisposedContextWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.'
```

So either I'm doing something wrong, or using `IDbContextFactory` is in fact making difference to lazy loading.

I also think this make difference to tracking objects. I was trying to load navigation proprety (after context was disposed) with query:
```C#
_context.Entry(forecast)
    .Reference(b => b.Summary)
    .Load();
```
and this also gives an error:
```
Unhandled exception rendering component: The navigation 'WeatherForecast.Summary' cannot be loaded because the entity is not being tracked. Navigations can only be loaded for tracked entities.
```

That's where both my questions came from.
If I'm doing something wrong please let me know.

**Comment by roji** [comment]
Lazy loading means that database calls are made later, as properties as accessed. In your code sample above, you dispose the DbContext and then return the queried WeatherForecast; any access of a lazy-loading navigation on that WeatherForecast will automatically trigger the exception, since the instance has already been disposed.

Carefully think about your DbContext lifecycle and how it interacts with your Blazor component. One way to make this work would be to forego lazy loading, use eager laoding and return a fully loaded graph from GetForecastAsync above; that ensures that the DbContext will no longer be needed. Another strategy would be to keep the DbContext alive for the lifespan of the Blazor component, in which case it wouldn't be disposed when the lazy navigation is accessed.

I recommending reading [the EF+Blazor tutorial](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-7.0#scope-to-the-component-lifetime) to learn more about how to make the two work together well.

**Comment by jakubmaguza** [comment]
Thanks for an answer.
Before posting this question I came to similar conclusions about Lazy Loading.

Still I'm not sure about using `AsNoTracking()` with very short lived context like above service.

Assume that I only need to get data and return it to customer.
In short lived `dbcontext`, adding `AsNoTracking()` will make any difference?

**Comment by roji** [comment]
Re AsNoTracking, the question is whether you need to track or not, i.e. will changes be done to the entities you query? If so, you generally need to use tracking queries, which mean that the context needs to live from the time you query to the time you call SaveChanges to persist the changes. That's why it frequently makes sense to scope the context lifetime to the form responsible for loading and saving the entity, as per the tutorial I linked to above.

Note that the new ExecuteUpdate can be an alternative to the unit-of-work SaveChanges model, see [the docs](https://learn.microsoft.com/en-us/ef/core/saving/) for more info (but I wouldn't necessarily recommend using ExecuteUpdate over SaveChanges in this scenario as a default).

**Comment by jakubmaguza** [comment]
No, as I mentioned I don't need to track it. Just return to data f.e. from API call.
Looking at 2 examples:
```C#
using (var db = _contextFactory.CreateDbContext())
{
   return db.SomeEntity.ToListAsync();
}
```
and 
```C#
using (var db = _contextFactory.CreateDbContext())
{
   return db.SomeEntity.AsNoTracking().ToListAsync();
}
```

My question is which one will perform better? My understanding is that doesn't matter, because context is disposed right after returning data, but maybe I'm wrong?

**Comment by roji** [comment]
@jakubmaguza as I wrote [above](https://github.com/dotnet/efcore/issues/30985#issuecomment-1566853859), you pay the perf overhead of tracking regardless of how quickly you dispose the context afterwards; tracking involves some extra processing during the query, and that happens in any case whether you dispose right afterwards or not.

AsNoTracking can indeed improve performance in some cases. But as with all perf questions, I highly recommend simply setting up a small, quick benchmark with BenchmarkDotNet and measuring the two options - this will give you an answer specific to your scenario.

**Comment by jakubmaguza** [comment]
> tracking involves some extra processing during the query, and that happens in any case whether you dispose right afterwards or not.

And that's all i wanted to hear. Thank you very much and have a good day!
