### ISSUE TITLE
EntityFramework Core 7.0 GIN search accuracy

### ISSUE THREAD

**Issue by khteh** [dotnet/efcore#30994]
I use postgresql with EntityFramework Core 7.0 and build search vector with the default GIN method:
```
        builder.HasGeneratedTsVectorColumn(
                   p => p.SearchVector,
                   "english",  // Text search config
                   p => new { p.Title, p.Description })  // Included properties
               .HasIndex(p => p.SearchVector)
               .HasMethod("GIN"); // Index method on the search vector (GIN or GIST)
```
The search vector column contains partial word of the `Title` and/or `Description` columns. For example, the word `glucose` would only have `glucos` in the search vector column. So, search using `.Where(record => record.p.SearchVector.Matches(EF.Functions.ToTsQuery(keywords)))` would end up with empty result set. This is disappointing or what do I miss?
### Include provider and version information

EF Core version: 7.0.5
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL
Target framework: (e.g. .NET 6.0) .Net 7.0.105
Operating system: Ubuntu 23.04
IDE: (e.g. Visual Studio 2022 17.4) VS Code

**Comment by roji** [comment]
@khteh this seems like a PostgreSQL full-text search more than anything related to EF; and in any case, this belongs in the PostgreSQL EF provider repo (https://github.com/npgsql/efcore.pg) rather than here (the general EF repo).

I suggest reading up on how PostgreSQL full-text search works, and understanding what SQL you're looking to use exactly; from there you should be able to use the EF PG provider to generate it. If you're still having trouble, please open a new issue in https://github.com/npgsql/efcore.pg, but please include a minimal, runnable code sample so I can fully understand what you're trying to do.
