### ISSUE TITLE
How to use ChangeTracker.Entries to audit database updates/deletes/inserts

### ISSUE THREAD

**Issue by andyb70** [dotnet/efcore#31087]
I’m trying to use the ChangeTracker.Entries() collection to maintain an audit log of updates/inserts/deletes whereby the Table, Primary Key and operation type are logged. However, the entries are not listed in the correct sequence they appear to have added state type entries at the beginning of the collection regardless of when it was added in the business logic.

The sequence of these events is critical to our solution as we use this information to synchronise a data warehouse and currently we get SQL foreign key errors because the log is out of sequence.

We have overridden the SaveChangesAsync method on the database context to allow us to hook this feature in.

**Comment by roji** [comment]
> However, the entries are not listed in the correct sequence they appear to have added state type entries at the beginning of the collection regardless of when it was added in the business logic.

When calling SaveChanges, EF orders all the different changes based on dependencies between them (e.g. satisfying foreign constraints); however, this is part of SaveChanges, and is not reflected before that, when looking at the tracked entries.

I'd recommend looking for a different strategy for synchronizing your data warehouse. You may want to have a change data stream directly out of your database (e.g. [like CDC for SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/track-changes/about-change-data-capture-sql-server?view=sql-server-ver16), or otherwise set up something that automatically syncs between the two databases.

You could in theory use a [command interceptor](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#database-interception) to get the actual command SQL as it's sent to the database; everything is properly ordered there, but you'd have to parse the SQL to reconstruct what's actually happening, which is brittle and discouraged.

**Comment by andyb70** [comment]
Hi @roji

Thank you for your response it's very much appreciated.

I've tried the Command Interceptor stuff and it is an absolute minefield of complexity! 

The golden nugget here is the CDC feature, I didn't know it existed so a huge thank you for pointing me in the right direction. I've investigated the Change Tracking option as well but you can't get all of the information using that. However, the Change Data Capture feature as you suggested gives me everything I need.

Many thanks again, knowledge is power!
