### ISSUE TITLE
Why does the connection close after executing a query or savechanges. DbConnection. State is closed

### ISSUE THREAD

**Issue by Sc7-git** [dotnet/efcore#31151]
Why does the connection close after executing a query or savechanges. DbConnection. State is closed

```
                var users = await _dbContext.Set<Personnel>().ToArrayAsync();
                var dbc = _dbContext.Database.GetDbConnection() as MySqlConnection;

                if (dbc.State == System.Data.ConnectionState.Closed)
                    dbc.Open();
                dbc.ChangeDatabase("test_2");
```
In the above code, it is necessary to first open before changing the Database

Is this a performance optimization strategy

**Comment by Sc7-git** [comment]
View[ado.net docs]( https://learn.microsoft.com/zh-cn/dotnet/framework/data/adonet/sql-server-connection-pooling ), close will return the connection to the Connection pool. Is the purpose of doing this to avoid blocking and creating more connections? Optimize program throughput

**Comment by roji** [comment]
@Sc7-git EF only keeps DbConnections open for the duration of the database operation (e.g. query or SaveChanges), closing it directly afterwards. Since database providers implement pooling, the overhead of opening and closing is negligible, and this prevents keeping connections open without them actually being used, e.g. as user code is off doing something else. If EF didn't do this, the connection pool could get exhausted.
