### ISSUE TITLE
Db first with Columns that may exist in dev but not prod

### ISSUE THREAD

**Issue by wizebaseLLC** [dotnet/efcore#31173]
Hello all,

how does one go about dealing with using The db first solution, and scaffolding a database that has multiple environments (dev, prod), but dev may have different “newer” columns than prod. 

If I scaffold dev, prod will crash due to not having those columns.  

This is with sql server.

**Comment by roji** [comment]
@wizebaseLLC your databse schema should in principle be the same across dev and prod, otherwise an application that works on dev may fail when deploying to prod etc. The typical flow is to make schema changes to dev/testing while developing, and then to sync prod's schema to be the same when deploying the new version of the application.

In any case, an EF model - the thing you scaffold from a database - generally represents a single database schema; so you'll have to scaffold either dev or prod. If you want to actually be able to work against two different database schemas (which really shouldn't ever happen for dev/prod), you'll have to have two models, e.g. scaffold two different DbContexts.

**Comment by wizebaseLLC** [comment]
> @wizebaseLLC your databse schema should in principle be the same across dev and prod, otherwise an application that works on dev may fail when deploying to prod etc. The typical flow is to make schema changes to dev/testing while developing, and then to sync prod's schema to be the same when deploying the new version of the application.
> 
> In any case, an EF model - the thing you scaffold from a database - generally represents a single database schema; so you'll have to scaffold either dev or prod. If you want to actually be able to work against two different database schemas (which really shouldn't ever happen for dev/prod), you'll have to have two models, e.g. scaffold two different DbContexts.

Thank you for your prompt response. I may have to scaffold two different context, as I am not in charge of new fields being generated in dev. 

I appreciate your help.

**Comment by roji** [comment]
@wizebaseLLC the point is that you're not support to have two contexts in your application code base at the same time for dev and prod; these represent two phases of your application (i.e. before a change is deployed to production and after). I don't know anything about the work flow in your organization, but I'd advise thinking about this more and not actually scaffolding two contexts here.

In any case, I'll go ahead and close this issue - but feel free to continue posting if you have further questions.
