### ISSUE TITLE
Add `Exists` and `ExistsAsync` like `Find` and `FindAsync`

### ISSUE THREAD

**Issue by nrhoffmann** [dotnet/efcore#31203]
I am trying to check if an entity exists given a `Type` and key.

I'd like to have a method `Exists` and `ExistsAsync` that return a boolean. Currently, I use `Find` and `FindAsync`, but since I don't need the object returned from the database, its a waste, especially for big objects.

**Comment by roji** [comment]
That should be trivial to implement in your project as an extension method over DbSet, which just does a LINQ query (e.g. `context.Blogs.Any(b => b.Id == someId)`.

The reason Find/FindAsync exist as special methods is because they look inside EF's change tracker before actually contacting the database, so they save a database roundtrip if the entity instance is already tracked.

**Comment by nrhoffmann** [comment]
How would you recommend getting a DbSet from `typeof(TEntity)`? I am using `Find` because I don't need to know the type or the key property name/s.

**Comment by ajcvickers** [comment]
Note from triage: we will not make this change. Options are:

* Implement specific, typed `Exists` methods for the entity types you have
* Continue to use `Find` for this, and discard the allocated instances
* Implement a non-type-specific Exists method by copying the code for Find. This could be made easier by #7391.
