### ISSUE TITLE
Clarification needed on computed properties

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3120]
I have a question regarding the expected behavior of computed properties (i.e. marked with `ValueGeneratedOnAddOrUpdate`), before implementing in Npgsql. The way I thought it should work, when I save a modified entity (without having having modified the computed property), the computed property should always be "recomputed", e.g. like a modification timestamp.

The SqlServer implementation of the StoreGeneratedSqlServerTest suite sets up the computed properties with `HasDefaultValue`, and not with `HasComputedColumnSql`, is this intentional? I've tested recomputation with the test below and it fails (i.e. not recomputed on update). Trying to change to `HasComputedColumnSql` causes some tests to fail with `The column "Computed" cannot be modified because it is either a computed column or is the result of a UNION operator.`, which I assume is an SqlServer-specific restriction.

So:
- Unless I'm misunderstanding correctly, the function tests aren't really testing recomputation on update?
- Regardless of the tests, am I understanding the expected behavior? i.e. should properties marked with `ValueGeneratedOnAddOrUpdate` and `HasComputedColumnSql` be recomputed on all entity updates (or at least those in which the property in question isn't explicitly modified)? And this shouldn't happen with `HasDefaultValue?

Here's the test I use to check whether recomputation actually happens:

``` c#
[Fact]
public virtual void Computed_property_on_Modified_entity_is_recomputed_when_not_explicitly_modified()
{
    int id;

    using (var context = CreateContext())
    {
        var entity = context.Add(new Gumball()).Entity;
        entity.Computed = "Masami";
        context.SaveChanges();
        id = entity.Id;
    }

    using (var context = CreateContext())
    {
        var gumball = context.Gumballs.Single(e => e.Id == id);
        Assert.Equal("Masami", gumball.Computed);
        gumball.NotStoreGenerated = "Larry Needlemeye";
        context.SaveChanges();
        Assert.Equal("Alan", gumball.Computed);
    }

    using (var context = CreateContext())
    {
        Assert.Equal("Alan", context.Gumballs.Single(e => e.Id == id).Computed);
    }
}
```

**Comment by ajcvickers** [comment]
@roji There is perhaps some lack of coverage in the provider-agnostic functional tests when it comes to computed columns. The SqlServerValueGenerationScenariosTest tests cover many scenarios from a SQL Server perspective, but these were not made provider-agnostic because most of the tests cover very SQL Server specific scenarios. The StoreGeneratedSqlServerTest tests are more provider-agnostic but in being so they don't attempt to actually use computed columns, but rather to test that the update pipeline is doing the appropriate thing when round-tripping. The columns have default values so that the tests that insert new entities will get some value back, but are otherwise normal columns so that they can be updated in some of the tests when needed. For modification tests, the state of the entity is manipulated to check that the update pipeline is doing the correct thing. For example, see "Computed_property_on_Modified_entity_is_read_from_store_when_not_modified". In this test the property is set to a new value, but then the original value and modified flags are reset so that it looks to the state manager like the property hasn't been modified. SaveChanges is then called and because the property is marked as computed but is not modified the update pipeline correctly gets the value of the column from the database and sets it into the entity. The test then asserts that that has happened by checking that the property has the value from the database. Technically the value that came from the database was not "computed", but this does not matter to the test.

Feel free to add some more tests to this suite that use really computed values, but keep in mind that these properties cannot, at least on SQL Server, be updated explicitly (as the exception you reference above says) and so can only be used for the tests that don't attempt to update the property. Also, the setup is likely to be different for different providers, and some may not support this at all, so it might be better just to create the equivalent of the SqlServerValueGenerationScenariosTest for your provider with scenarios tailored to what can be supported.

**Comment by roji** [comment]
Understood @ajcvickers, thanks (as always) for the patient explanation.

I can definitely whip up some tests which actually make use of computed columns. IMHO it seems right to add them to StoreGeneratedTests - after all EF7 does support computed columns if the provider does. Providers which don't support computed columns (or which don't support certain scenarios with computed columns) can then override these tests and skip them. The model would then need to be extended with a few more fields that have `HasComputedColumnSql` (what do we call them, TrulyComputed? :)).

Or if you prefer to keep computed tests out of there I can just add tests in my provider-specific suite as you suggested. Let me know what seems best.

**Comment by ajcvickers** [comment]
@roji Provider agnostic tests are preferred if possible unless the scenarios are very specific to a single provider.
