### ISSUE TITLE
Performance hit creating scoped context instance

### ISSUE THREAD

**Issue by jerry2007** [dotnet/efcore#3146]
I had a problem with performance. One query to DB with simple select with where condition in ASP.NET 5 MVC6 with EF7 in Beta 7 take more then 500ms. After some research and found out that DbContext LifeTime in services is Scoped. And that is a problém, because in each request new DbContext is created and every request doing "First" query what obviosly spend lot of time. When I changed DbContext lifetime from Scoped to Singleton, first request takes 500+ms again, but after that every request take less than 100ms what is much better...

Can you consider change lifetime from scope to singleton? Or put there option to set this on adding context?

**Comment by ilmax** [comment]
@jerry2007 generally it's up to you how to register services/components (singleton/scoped/transient) and lifetime management is not a dbcontext responsibility.

Note that is an anti pattern to use a shared context across multiple request. If you need further help, please share your configuration code.

**Comment by davidroth** [comment]
@jerry2007 Using a shared dbcontext for the application does just not work. Don't do it.

You will run into various problems:
 - Cross-threading issues because DbContext is not Thread-Safe => If there are multiple queries(requests) at the same time, you will get weird cross-threading related exceptions.

 - Memory usage: DbContext tracks all entities which are loaded from the db. But these entities are not released if the context lives "forever". This can lead to high memory usage and finally to an OutOfMemoryException.

-  Stale data: This is also due to the fact that DbContext tracks all entities => It is likely that you will get stale data.

So for a web application, it is generally a good idea to use a *scoped* context.
Your performance problem (400ms), sounds weird though.I would recommend attaching a profiler to figure out what causes the this performance drop.

**Comment by matthewDDennis** [comment]
If you are measuring performance, make sure you have a Release build and running Non-Debug.
There are some caching of views and queries that may not run in debug, basically so they can be debugged.  This is from observation, not looking at the code.

**Comment by rowanmiller** [comment]
Context per request is the correct pattern to use (for the reasons discussed in this thread).

@jerry2007 can you share your project so that we can investigate the performance issue?

**Comment by rowanmiller** [comment]
Closing since we have not heard back, feel free to re-open if you can provide more details
