### ISSUE TITLE
Issue Connecting to Postgres Pgpool Server with Entity Framework Core

### ISSUE THREAD

**Issue by erdisonberisha** [dotnet/efcore#31545]
I am encountering an issue while attempting to connect to a PostgreSQL Pgpool server using Entity Framework Core. The setup involves the utilization of the Postgresql HA Helm Chart by Bitnami, which sets up a high-availability PostgreSQL cluster. The intended behavior is for EF Core to create the database if it doesn't already exist and subsequently migrate data. However, upon initiating the connection and migration process, I am immediately confronted with the following error:

Npgsql.PostgresException (0x80004005): XX000: unable to get session context.

My architecture comprises a PostgreSQL Pgpool server orchestrated via the Bitnami Postgresql HA Helm Chart. The primary goal is to establish a connection using Entity Framework Core and perform migrations to set up the initial data structure. Regrettably, the encountered error is impeding progress.

Ideally, when EF Core connects to the PostgreSQL Pgpool server, it should be able to acquire the necessary session context to proceed with database operations, including database creation and data migration.

Steps Taken:

Configured the PostgreSQL Pgpool server using the Bitnami Postgresql HA Helm Chart.
Attempted to connect to the database and initiate data migration using Entity Framework Core.
Encountered the Npgsql.PostgresException with the error message indicating a failure to obtain the session context (XX000: unable to get session context).
Request:
I kindly request assistance in diagnosing the root cause of this issue and finding a potential solution or workaround. If possible, please provide guidance on how to correctly configure Entity Framework Core to work seamlessly with a PostgreSQL Pgpool server, considering the observed error.

Additional Information:

EF Core Version: 6.0

**Comment by roji** [comment]
@erdisonberisha the error - `XX000: unable to get session context` - isn't familiar to me, and looks like it might be a pgpool-specific error. I'm not sure what specifically EF is doing to trigger this error (if at all) - are you able to connect with EF outside of migrations, to an already-existing database?

**Comment by erdisonberisha** [comment]
@roji No I'm not being able to connect even if I try an already existing database. I'm getting the same error. I found this issue in the bitnami pgpool repo https://github.com/bitnami/charts/issues/18807 but it said the issue possibly relies on the .NET library (referring to EF core)

**Comment by roji** [comment]
When you instruct EF to create a new database, it connects to an "administrative" database in order to issue the CREATE DATABASE command (in PostgreSQL you're always connected to **some** database). The default database is `postgres`, which is the right choice for regular PostgreSQL.

With various hosted PG options, you must create the database via a web UI or similar, and cannot connect to `postgres` and issue CREATE DATABASE; you'll have to check what the right process with bitnami is. Otherwise, if bitnami has a different administrative database (not `postgres`), you can configure the EF PG for that [as per these docs](https://www.npgsql.org/efcore/misc/database-creation.html#specifying-the-administrative-db).

I'm going to go ahead and close this as Npgsql/EF is connecting fine and the only problem is the administrative database. But feel free to post back here with further questions etc.

**Comment by lubishtanid** [comment]
Hello @roji. Thank you for answering about the issue, but is it possible for you to explain this following part in more detail:
"With various hosted PG options, you must create the database via a web UI or similar, and cannot connect to postgres and issue CREATE DATABASE".
What do you mean that some hosted PG options cannot connect to the administrative db (postgres) in this case. Is this a feature of Postgresql or something like this. Because, the administrative db of the helm chart that we deployed is postgres, and it still gives that unable to get session context error. Otherwise, if we first create the db manually (in pgAdmin for example), then it works without problem.

**Comment by roji** [comment]
@lubishtanid I don't know bitnami, and I don't know how you're expected to create the database there. All I know is that by default, when the EF Core PostgreSQL provider needs to create a new database (i.e. issue the CREATE DATABASE statement), it connects to a database called `postgres` on the server; while this database exists on regular PG installations, it might not on bitnami.

You need to figure out how you're supposed to create a new database with bitnami.

**Comment by lubishtanid** [comment]
@roji As I previously mentioned, the administrative database 'postgres' exists on our deployed PG server, so if the only condition to create a db from the .NET app is to connect to the administrative database 'postgres', then this condition should've been met already.

About the part on figuring out how to create a new database, that is the sole reason why we are asking for help. We can create the database manually via PgAdmin, and then connect our app using PgPool II's connection string and it works perfectly to migrate the data, but when the database doesn't exist then the app says it is unable to get session context.

**Comment by roji** [comment]
@lubishtanid I'm not sure don't understand... [Above](https://github.com/dotnet/efcore/issues/31545#issuecomment-1691470129) you indicated that you can connect to existing databases just fine with EF. Asking EF to create a database just means that it connects to an existing database called `postgres` and sends CREATE DATABASE there. So it really sounds like there's some issue connecting to `postgres` in your case - can you confirm whether this works or not, regardless of whether you do CREATE DATABASE there or not?

**Comment by lubishtanid** [comment]
@roji Yes, it is working. It connects to 'postgres' db and it can migrate data there.

**Comment by roji** [comment]
Then I honestly don't know how to help... If I understand you correctly, you're saying you can connect to the `postgres` DB from EF, but not when this is done to create another database - it's hard to imagine why that would be the case. I'd recommend double-checking everything and maybe trying to do the same thing EF is doing (i.e. connect to `postgres` and do the same CREATE DATABASE it's trying to do.
