### ISSUE TITLE
Navigation Name is incorrect.

### ISSUE THREAD

**Issue by dpwzone** [dotnet/efcore#31836]
Using the fluent api, HasOne method, I supply it the related type name and the navigation name, yet after the model is built, the navigation says "Item" and NOT the supplied navigation name from above.

Before the inevitable we need code to reproduce, take a step back and determine where in YOUR code you're setting that name.

As a note, you might want to add an interceptor for when that value is assigned, just in case EF fails like it has.

**Comment by roji** [comment]
@dpwzone this seems identical to #31813. Note that many, many EF users are using HasOne successfully and are not hitting this issue, so it's very likely there's something specific you're doing that's causing this. That's why we need a code sample from you.

**Comment by dpwzone** [comment]
Yep, the expected we need code  smh

Do you, yes or no, how navigation property names are set?

**Comment by roji** [comment]
Are you asking me whether we know how navigation property names are set? If so, the answer is yes.

**Comment by dpwzone** [comment]
Cool, do you want to share?  Seems like it would be the most useful route.

**Comment by roji** [comment]
@dpwzone no, sorry. You've indicated that you're seeing unexpected behavior which points to a bug either in your code or in EF's. Going into EF's internal design and architecture isn't a good way to make progress here, and won't make a good use of both your time and ours.

Please provide a minimal repro, otherwise we can't help you.

**Comment by dpwzone** [comment]
What's the matter, you afraid to show you don't know how these navigation names are set?  How about leaving this issue open for someone who does?

**Comment by roji** [comment]
@dpwzone I'm closing this issue now, as you're refusing to provide the minimal repro we've requested several times, and your comments are entering the domain of personal attacks, in breach of our [code of conduct](https://dotnetfoundation.org/about/policies/code-of-conduct).

If you decide to provide the requested repro and to communicate more respectfully, we'll be here and will be happy to assist.

**Comment by vslee** [comment]
@dpwzone, I think what @roji is saying is that yes, of course they know how their internal code works. But going this direction means:
1. It would take a long time to explain not only how the code works, but all of the caveats associated with it. Also, the code is open source, so if you wanted to take the time, you could always look yourself. 
2. Even after they explain, you would then have to dive into the EFCore code yourself to figure out where the bug lies. This is a very time-consuming process, and most people give up. Thus, all of the time spent by both sides up to this point would have been wasted. 

Instead, what roji is offering to do is to handle the work in #2 for you (which would also eliminate the need for #1). They would just need a small repro from you to do so. This would eliminate a lot of work on both sides, and also be far more likely to produce results.
