### ISSUE TITLE
Referencing a third table in `JOIN` clauses

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#31894]
Let's assume the following schema:

```

# Greens
---
Id
TenantId
RedId
NativeId
---

# Blues
---
Id
RedId
NativeId
---

# Reds
---
Id
TenantId
---
```

![image](https://github.com/dotnet/efcore/assets/115199/fe6ffcf2-e943-4576-9229-f7775b8db02b)

```csharp

modelBuilder.Entity<Greens>()
    .HasMany((g) => g.Blues)
    .WithOne((b) => B.Green)
    .HasForeignKey((b) => new { b.NativeId, ??? })
    .HasPrincipalKey((g) => new { g.NativeId, ??? });
```

My dilemma is that when I'm fetching my `Greens` and all their related `Reds` and `Blues`, I need a way to clamp the `TenantId` between them in the joins that EF generates.  My initial thought with the code snippet above was that I could do this somehow in the relationship definition.  But I'm not sure how I could get a reference to the `Reds` table.

**Comment by pbanerji17** [comment]
If we want to ensure that when fetching Greens and their related Reds and Blues, the **TenantId** is clamped between them in the joins generated by EF Core, we can achieve this by configuring the relationship between Green and Red in a way that includes the **TenantId** in the join condition.

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Green>()
        .HasOne(g => g.Red)
        .WithMany(r => r.Greens)
        .HasForeignKey(g => new { g.RedId, g.TenantId }) // Include TenantId in the join
        .HasPrincipalKey(r => new { r.Id, r.TenantId }); // Include TenantId in the join

    modelBuilder.Entity<Green>()
        .HasMany(g => g.Blues)
        .WithOne(b => b.Green)
        .HasForeignKey(b => new { b.NativeId, b.RedId }) // Include RedId in the join
        .HasPrincipalKey(g => new { g.NativeId, g.RedId }); // Include RedId in the join
}

```

In this configuration:
1.	The relationship between Green and Red includes the **TenantId** in both the foreign key and the principal key, ensuring that the **TenantId** is clamped in the join condition.
2.	The relationship between Green and Blue includes the **RedId** in both the foreign key and the principal key to link them based on **RedId**.
With this setup, when we fetch Greens and their related Reds and Blues, EF will generate SQL queries that include the necessary joins with the **TenantId** clamped between them in the join conditions.

**Comment by roji** [comment]
@atrauzzi I'm probably mis-reading your question, but assuming you always fetch Blues as dependents of their Red/Green (i.e. via a JOIN), then an inner join already ensures that you never get Blues that aren't related to a Green/red with the right TenantId. The same holds for ensuring you get Greens and Reds with the same TenantId.

In other words, assuming you inserted the correct data into your database tables, and e.g. Greens and Reds are only related (via the RedId foreign key) if they also share the same tenant, then there's no reason to enforce the TenantId equality in any actual query.

You **can** get that enforced by including TenantId in the foreign key - and you may want to to define an *alternate* composite key on the principal so that the dependent's foreign key can be composite and point to it to. But of course, if the Blue table doesn't have the TenantId at all, there's nothing you can do there except rely on your data being correct.
