### ISSUE TITLE
Combination of split queries and limit/order leads to inconsistent inclusions

### ISSUE THREAD

**Issue by cus-dbc-laika** [dotnet/efcore#31975]
### Description

In some LINQ queries, we got inconsistent `.Include`-results when using `.Take` and `.Order` in split queries. This happens because in the first SQL query (that provides the "main" objects), the `LIMIT` and `ORDER` are set correctly. The following SQL queries (to include the related objects) use sub-selects that are similar to the first query to determine which entries to load, but don't contain the `ORDER` while keeping the `LIMIT`. So it's up to the DBMS to decide in which order the results are returned. The two sets won't necessarily match and so there's a chance of non-included properties. 

We can mitigate this problem by using `.AsSingleQuery()` but those bugs are really hard to find though.

### Include your code, stack traces and verbose output

For data protection reasons, I can't provide the code that leads to this bug. :(
I can try to write a small demo if you want me to.

### Include provider and version information

EF Core version: 7.0.10
Database provider: Pomelo.EntityFrameworkCore.MySql 7.0.0
Target framework: .NET 7.0
Operating system: macOS Sonoma 14.0
IDE: JetBrains Rider 2023.2.1

**Comment by roji** [comment]
This sounds very similar to #26808, which covers any case where the results are non-deterministic (either because an OrderBy is missing or because it's on a non-unique column).

It sounds from your above description that you do have OrderBy, so this might be a different issue. If so, we really do need a repro to see this happening. We don't need to see the code from your project, but can you please put together a minimal, runnable console program with a small model and query that shows the problematic SQL being generated?

**Comment by roji** [comment]
Thanks, that indeed looks like a dup - please follow #26808 for tracking this.

**Comment by roji** [comment]
Duplciate of #26808
