### ISSUE TITLE
no exception when model is different to database schema:

### ISSUE THREAD

**Issue by kennywangjin** [dotnet/efcore#3200]
when the code first model is different to database schema (maybe some changes to only model or only database schema, no sync), if I try to add some entity to database, savechanges throws no exception or gives any notification, and no record is inserted into database.
Is this behavior intended or something wrong?

**Comment by leus** [comment]
I've observed this but since I'm in a rapid prototyping phase I don't add migration-generated files to my project. I'm curious about this too.

**Comment by kennywangjin** [comment]
Exactly, me too, no migration-generated files added.
But, it should throw some exception or return some notification indicating the invalid operation, right?

**Comment by rowanmiller** [comment]
Not giving an exception just because the model/database don't match is by-design - in EF7 we no longer have initialization logic that runs against the database. You should get an exception from `SaveChanges` though if something fails. Can you add some code that demonstrates where the save fails but no exception is thrown.

**Comment by roji** [comment]
@rowanmiller would you consider adding an opt-in model/database sync check? Although it makes sense not to impose this on the user, in many applications it's a good idea to make sure the model is synchronized at initialization time (early fail-fast rather than receiving a late exception).

**Comment by rowanmiller** [comment]
@roji you can already check if there are any changes to the model since your last migration, which can tell you if you forgot to push changes to the database. You could add some app start logic that uses that. We actually use this as part of the Database Error Page in ASP.NET 5 to provide some database centric help when things fail.
