### ISSUE TITLE
Include ConnectionCreatingAsync & ConnectionCreatedAsync in IDbConnectionInterceptor

### ISSUE THREAD

**Issue by jamezamm** [dotnet/efcore#32042]
No async counterparts for ConnectionCreating & ConnectionCreated in IDbConnectionInterceptor are available.

Is it possible for ConnectionCreatingAsync & ConnectionCreatedAsync to be included in IDbConnectionInterceptor?

**Comment by roji** [comment]
@jamezamm there are no async counterparts for connection creation events since creating a connection is not supposed to involve any sort of I/O. In ADO.NET, creating the connection is just a matter of instantiating the object (at which point nothing has happened yet); the connection is then **opened**, at which point actual I/O may occur to the database. You're probably looking for the ConnectionOpening/Opened pair instead.

Otherwise, can you please provide more context on why you think you need async counterparts for ConnectionCreating/Created?

**Comment by jamezamm** [comment]
I was hoping to asynchronously open the connection the moment the DbConnection has been created, thus preventing EFCore from managing the dbconnection (Open/Close connection with every query).

**Comment by roji** [comment]
@jamezamm can you provide context on why it is you're trying to do that? Holding the connection open (as opposed to letting EF manage it) would mean that you hold connections open for far longer than needed, putting lots of needless pressure on the connection pool etc. It would be good to understand the root cause leading you to try this.

If you really do need to do this (again, I'd recommend against it), then you can simply intercept the open/close events instead, keeping the connection open instead of closing it.

**Comment by jamezamm** [comment]
I am using Oracle and I normally open the connection at the beginning of a request and close it at the end of the request. As far as I can tell, Oracle closes or deactivates the connection immediately after querying is performed and never had any issues with it.  

Would have been great to have ConnectionCreatingAsync & ConnectionCreatedAsync, but I have used ClosingConnectionAsync event to suppress and it seems to work.

One small issue I noticed that ClosedConnectionAsync is still called once even tough ClosingConnectionAsync has been suppressed.

**Comment by roji** [comment]
> I am using Oracle and I normally open the connection at the beginning of a request and close it at the end of the request. As far as I can tell, Oracle closes or deactivates the connection immediately after querying is performed and never had any issues with it.

I don't understand...

EF's behavior is to keep the connection open (i.e. keep it out of the connection pool) only when needed; that means it opens it (gets it from the pool) just before e.g. a query is executed, and closes it (returns it to the pool) right afterwards. This strategy minimizes the time connections are kept out of the pool, using connections more efficiently and lower the total number used (thereby reduces resource usage).

This strategy generally works well - I'm not clear why you're trying to change that.

**Comment by jamezamm** [comment]
I have discussed this subject with my team, and you are correct. Thanks for your persistence in bringing this to my attention.

I will be closing this issue.
