### ISSUE TITLE
Check if Table exists

### ISSUE THREAD

**Issue by rghayazi** [dotnet/efcore#32071]
Hi,

Is there a way to customize migration generation in order to check if table exists before its creation?

thank you

**Comment by ajcvickers** [comment]
Generally speaking, only creating a table when it does not exist results in tables that are out-of-date, so there isn't any built-in way to do this. You can write raw SQL to do it, but then you pretty much need to use raw SQL for all the migrations. Also, generated idempotent scripts will check if changes have already been made before applying those changes.

**Comment by roji** [comment]
To give more context, the way migrations are designed to work is that we don't check whether a table (or column exists); instead, EF checks whether a **migration** has already been applied (by examining the migrations history table in the database, `__EFMigrationsHistory`). In other words, if a migration has been applied, any tables that it adds are assumed to have been added.

I recommend carefully considering why you think you need to manually check whether a table exists - some more context on what you're trying to achieve may help us help you better.

**Comment by rghayazi** [comment]
for some reasons, we sometimes run into issues when running migration. to fix this we usually need to remove all the added tables and rerun again. but I actually want to just truncate __EFMigrationsHistory to force running the migration again without recreating the tables and to make sure all changes are applied

**Comment by roji** [comment]
@rghayazi that approach is unlikely to work - migrations perform various things beyond just creating tables, e.g. adding/removing/renaming columns, manipulating sequences, and so on. It's not possible for migrations to "make sure everything is applied".

Can you open an issue reproducing the issues you have when running migrations? Trying to fix the source of the problem here would be a better approach here.
