### ISSUE TITLE
Custom query translation 

### ISSUE THREAD

**Issue by Helius01** [dotnet/efcore#32117]
Hey. How can i customize the query translation?

Imagine i have  a query like this : 

```
var totalCustomers = context.Customers.Count();
```
In this case the code translates into something like this : 

```
SELECT Count(*) FROM dbo.Customers
```

But i prefer to customize the translated query to this : 

```
Select Count(Id) From dbo.Customers
```

**Comment by roji** [comment]
@Helius01 what exactly is the intent of this particular customization? `COUNT(Id)` counts the number of rows where `Id` is non-null, as opposed to `COUNT(*)` which counts the number of rows (regardless of what any specific column contains); because of this, `COUNT(*)` is the correct translation for the LINQ query above (since it behaves the same way as when executed in-memory).

If you really want to count the number of rows where Id is not null, you can write the following query:

```c#
var totalCustomers = ctx.Blogs.Count(b => b.Id != null);
```

However, assuming Id is non-nullable (which Id usually are), EF will optimize this away and you'll get `COUNT(*)` again. If you do this on a nullable column you'll get a query that indeed checks for rows where the column is not null (though IIRC we don't currently generate `COUNT(Column)` for that, but rather just add a WHERE clause).

**Comment by ErikEJ** [comment]
@RaminMT That is not correct, what are your sources for that claim?

**Comment by roji** [comment]
> I've heard from many DBAs & also read many articles claiming that COUNT(*) is not that much performant & suggesting to change it to COUNT(COLUMN_NAME). I guess this can be the reason for such a requirement

Like @ErikEJ I'm curious to see some of those articles - can you please provide some links?

However, regardless of performance, `COUNT(*)` and `COUNT(COLUMN_NAME)` are two completely different things with differently results (all rows vs. all rows with non-null column). Your LINQ query above - `context.Customers.Count()` - has the semantics of the 1st: it counts all customers, not just those with a non-null ID. So it would be incorrect to translate this to `COUNT(COLUMN_NAME)` regardless of performance.

**Comment by Helius01** [comment]
I think i found my answer.
