### ISSUE TITLE
Generate SQL scripts to create the entire DB (not only tables)

### ISSUE THREAD

**Issue by piskov** [dotnet/efcore#32122]
Form the [docs](https://learn.microsoft.com/en-us/ef/core/managing-schemas/ensure-created#ensurecreated):

> EnsureCreated will create the database if it doesn't exist and initialize the database schema.

…and below that:

> To get the SQL used by EnsureCreated, you can use the `GenerateCreateScript` method.

One would think that `GenerateCreateScript` will get you the SQL to create the entire DB but it’s not — only SQL for tables. If `EnsureCreated` generates some `CREATE DATABASE %your db name%` SQL under the hood, it would be nice to have it as well.

## Use case
When migrating between the DB engines (e.g. SQL Server → PostreSQL) one would appreciate to have a DB creation SQL as well (as a separate script or same like SQL Management Studio generates in Tasks → Generate Scripts… → Script entire database and all database objects)

**Comment by roji** [comment]
As I wrote in https://github.com/dotnet/efcore/issues/10551#issuecomment-1773413322, at least for PostgreSQL that's not technically possible, since creating the database must occur when connected to some administrative database, the script itself (table creation) must run on the database (and switch the database for a connection is impossible).

In addition, there are various cloud database systems where the database cannot be created in this way, but rather must be created via the UI or a separate API call.

Finally, this really affects only migration SQL scripts. If you use e.g. EF's migration bundle feature, it can do everything for you without any issue. I highly recommend looking at that.

**Comment by piskov** [comment]
> EF's migration bundle feature, it can do everything for you without any issue. I highly recommend looking at that

Will do, thank you
