### ISSUE TITLE
UseLazyLoadingProxies is not effect on AddPooledDbContextFactory

### ISSUE THREAD

**Issue by binhnguyent-MediaBrands** [dotnet/efcore#32130]
Hello everyone, 

While we use UseLazyLoadingProxies within AddPooledDbContextFactory, the UseLazyLoadingProxies does not work.

```
services.AddPooledDbContextFactory<T>(options => options
    .UseLazyLoadingProxies()
    .UseNpgsql(configuration["ConnectionStrings:Default"])
);
```

Please help on this.

**Comment by roji** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate. Just posting "does not work" with no description of what happens and no full code sample isn't sufficient.
