### ISSUE TITLE
EFCore 8 daily label - Converter getting called for writing value to JSON data

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#32169]
Following GitHib issue suggests that if JsonValueReaderWriter is used as part of type mapping, then converters are not used to convert the value while writing to JSON column.
https://github.com/dotnet/efcore/issues/32073#issuecomment-1770489553

However In the GIT test `Can_read_write_collection_of_uint_enum_JSON_values`
Converter gets called from below place in `JsonConvertedValueReaderWriter.cs` (https://github.com/dotnet/efcore/blob/main/src/EFCore/Storage/Json/JsonConvertedValueReaderWriter.cs)

```C#
public override void ToJsonTyped(Utf8JsonWriter writer, TModel value)
    => _providerReaderWriter.ToJson(writer, (TProvider)_converter.ConvertToProvider(value)!);
```

I am using this test to test Oracle provider. 
I have created a type mapping for UInt32 type for Oracle Provider.
This type mapping uses a converter `OracleUInt32Converter()` also which converts the value to Int64 while writing it to the database.

```C#
public OracleUint32TypeMapping(string storeType,
  DbType? dbType = System.Data.DbType.UInt32
  )
  : this(
	new RelationalTypeMappingParameters(
	  new CoreTypeMappingParameters(
		typeof(UInt32), new OracleUInt32Converter(), jsonValueReaderWriter: JsonUInt32ReaderWriter.Instance),
	  storeType,
	  StoreTypePostfix.PrecisionAndScale,
	  dbType))
{
}
```

As per above link the converter shouldn't be called for writing the value to JSON column. But I could see the converters ToStore() method gets called which converts the value to Int64 type. 
After that JsonValueReaderWriter.ToJson() gets called where it accepts the value to be UInt32 and hence following exception is thrown.
`System.InvalidCastException: 'Unable to cast object of type 'System.Int64' to type 'System.UInt32'.'`

Please could someone clarify why is the converter getting called.

**Comment by shvmgpt116** [comment]
@ajcvickers @roji

**Comment by ajcvickers** [comment]
@shvmgpt116 When running with SQL Server, the type mapping has the following reader/writer configured

<img width="1049" alt="image" src="https://github.com/dotnet/efcore/assets/1430078/1c5d994f-c16c-4c53-ad78-de2fab558f87">

The `JsonCollectionReaderWriter` is generated internally, since this is a primitive collection mapping. The provider type mapper should not be returning this. Inside the collection read/writer is an element reader/writer for the elements of the collection. Since the elements are enums, this is a `JsonConvertedValueReaderWriter<Enum32, long>`. This again should not be created by the provider, since it is an enum conversion. So at no place in this test should the provider's reader/writer be needed.

Are you seeing differently?

**Comment by shvmgpt116** [comment]
@ajcvickers Yes, I am seeing different reader/writer.
![image (1)](https://github.com/dotnet/efcore/assets/17099824/dc373b8a-2a72-4046-83a9-5d21ee982bb1)

**Comment by ajcvickers** [comment]
@shvmgpt116 Your element type mapping is incorrect, since it isn't in terms of the element of the collection. I don't know what could be causing this. If you would like us to investigate, then we're going to need to reproduce this.
