### ISSUE TITLE
Support CRUD operations for updatable views

### ISSUE THREAD

**Issue by harmhorstman** [dotnet/efcore#32216]
It seems like that Create, Update and Delete operations are not supported.

I wish to have an option to treat updatable views like tables, in case triggers are detected in the view, during the reverse engineering process.

I understand that key column(s) must exist for this, this is something that should be maintained in a config file. Or create easy to find placeholders in the generated code for this.

**Comment by roji** [comment]
@harmhorstman if your updatable view exposes a primary key, you can simply map it as a regular table - EF doesn't actually need to know that it's an updatable view (you can exclude it from migrations if that's an issue).

Otherwise, if there's no key, then EF can't perform (tracking) updates, since that relies on tracking loaded data by its key.
