### ISSUE TITLE
I suggest a better way to work with Stored Procedure migrations

### ISSUE THREAD

**Issue by HolyOne** [dotnet/efcore#32316]
I am using Entityframework with .net 8

Everything is great except working with stored procedures. I want to add a stored procedure to my database (code first).
The documents suggest that I write a custom migration ( Up, down methods).
Adding the SP from a string is not a good development experience, no syntax highlighting etc...

Also if I add it by executing some strings, I am no longer able to auto create migrations from database. I will have to write every migration by hand because everything is in Migrations folder. and it will be deleted if I clear migrations.

What I suggest is there should be a SP folder with spname.sql files inside, each containing an SP file.
When I do an Update-Database , the SP folder should be scanned and they should be included to Migrations folder.

**Comment by roji** [comment]
> Adding the SP from a string is not a good development experience, no syntax highlighting etc...

If you're really concerned about syntax highlighting, you can always integrate code into your migration which reads the sproc SQL from an external SQL file; the IDE should then provide syntax highlighting for that. Some modern IDEs also recognize SQL in strings and provide syntax highlighting there as well (I'm pretty sure there's something in the works for VS), so that doesn't seem like a big concern.

> I will have to write every migration by hand because everything is in Migrations folder. and it will be deleted if I clear migrations.

There are many situations in which customizations are required in migrations, far beyond sproc management. Deleting your migration folder isn't something that's supported in that sense, and it wouldn't make sense to introduce a solution specifically for sprocs when other customizations are possible. We do have [migration squashing](https://github.com/dotnet/efcore/issues/2174) on the backlog, which will allow you to reduce your entire migrations folder to a single migration; ideally, customizations would be preserved by that.

> What I suggest is there should be a SP folder with spname.sql files inside, each containing an SP file. When I do an Update-Database , the SP folder should be scanned and they should be included to Migrations folder.

This isn't as simple as it looks, and is incompatible with the way migrations work. For example, how would EF know which stored procedures have already been added to the database (in a previous migration)? That seems like it would require EF to scan the database to know what sprocs are already there - that's not how migrations (currently) work. The same goes for modifying the definition of an already-existing database.

**Comment by HolyOne** [comment]
The main reason it is needed is, lets say I write my db in code first.
I have like 10 migrations.
Then I need to add an SP with a custom migration. I then wont be able to generate migrations by add-migration. I will have to add all the other migrations by hand.

how would EF know which stored procedures have already been added to the database ?
It doesnt need to know, you can just do create or alter. and for the down method, delete if exists.

Im sure its not that simple but SP is still a big part of applications.

**Comment by roji** [comment]
@HolyOne I don't follow what you're saying. You can add a sproc by adding a migration and manually inserting the sproc creation as SQL inside it. EF knows which migrations have been applied (via the migration history table stored in the database); there's no problem with adding further migrations (with manually-written SQL or not) afterwards. If you need to alter a sproc, once again add another migration with SQL to alter it; EF will again know to apply it only if the migration hasn't already been executed (as per the migration history table).

If that doesn't make sense, please trying explaining where you see the problem exactly.
