### ISSUE TITLE
Query: primitive collection parameters values should reflect the type they are representing

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#32515]
See: Where_contains_DateTime_literals

each parameter represents primitive collection of a different sql type, but the values are the same across the board

**Comment by roji** [comment]
@maumar thanks for filing - I looked into this and I think everything is actually fine. I can see the correct different type mappings inferred all the way to SQL generation. When we generate the JSON, the textual DateTime representation within the JSON doesn't take the store type/precision/scale into account - it simply writes the canonical JSON DateTime representation (ISO9601), which is why all parameters look the same.

So AFAICT the TODO comment can be removed from the test and we can close this.

**Comment by ajcvickers** [comment]
Note from triage: expected behavior is as Shay says. @maumar to validate that there is nothing to do here.
