### ISSUE TITLE
Is there any way to check whether provider supports transactions and certain isolation levels?

### ISSUE THREAD

**Issue by voroninp** [dotnet/efcore#32524]
Is there a programmatic way to get the information about data provider capabilities?

**Comment by voroninp** [comment]
There's InMemory provider which does not support transactions, for example. Not sure about Cosmos DB or MongoDb provider. 

I have a wrapper which implements the semantics of auto commited transaction, but I want it to throw when it detects that it's applied to the DbContext configured with the provider which does not support transactions.

**Comment by voroninp** [comment]
>  In any case, EF doesn't provide any sort of discovery API or similar (I don't think that would make sense). 

IMO, the more data provider could tell about its capabilities, the better it would be. But ok.

**Comment by ErikEJ** [comment]
@voroninp The providers you mention are not Relational providers. Maybe there is a way of discovering that?

**Comment by ajcvickers** [comment]
@voroninp It's unlikely we are going to implement this because it goes against the design philosophy that you should use any database _intentionally_ because it has the right characteristics for what you need to do. It would be wrong to assume that because any database has a given capability, then that means the capability will work in the same way and be "interchangeable". We really discourage the idea that EF can be used with any database interchangeably.

**Comment by voroninp** [comment]
> We really discourage the idea that EF can be used with any database interchangeably.

That's fine, but if we speak about extensions, what should be the approach? Explicitly check the underlying provider and decide whether it's supported or not?

**Comment by ErikEJ** [comment]
@voroninp Target the extension to each provider?
