### ISSUE TITLE
Detect Many to Many Relation Not Configured as Such

### ISSUE THREAD

**Issue by markolbert** [dotnet/efcore#32677]
It is possible to configure a one-to-many relationship in a Sql Server (localdb) schema but access it as a one-to-one relationship in C# code using EF Core. Neither a compile time nor run time error is generated, and the net result is only the first relationship value is stored in the database, regardless of how many records are added to the many-to-many linking table.

This occurred while I was using a database-first approach for the first time, designing and modifying the schema on the server and then updating the C# code to reflect it. I'm sure this problem would not occur with a code-first approach because the schema generator would set up the relationship as one-to-one.

If there's a way to detect this kind of mismatch it would be helpful. It's a subtle bug that spans two very different realms (C# and T-SQL) that I spent well over a day resolving :).

**Comment by ajcvickers** [comment]
@markolbert We use the model to make the most efficient use of the database that we can. This means not validating that the model is correct when using it, since this is only useful for bad code, but all good code pays the price. Having a single source of truth for the model helps a lot here. That is, the database is the source of truth and the EF model is derived from that, or vice versa.

**Comment by markolbert** [comment]
Fair point. OTOH, offering the opportunity, when needed/desired, to validate the model would be helpful.

-          Mark
