### ISSUE TITLE
Code cleanup: Standarize how we detect EF.Property<T>() in expression visitors

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#3269]
Investigating bug #3119 I saw in the code that we are using several dissimilar patterns to check for `EF.Property<T>()` in several expression visitors (by checking for reference equality against `EntityQueryModelVisitor.PropertyMethodInfo`). Looks like this could be moved into a utility method. In a lot of cases we use this to special case `EF.Property<T>()` in `VisitMethodCall()`, so wondering if we could reduce the number of copies we have of that code by lifting that logic into a base expression visitor.

**Comment by whyi** [comment]
:+1: We should DRY the code up whenever possible.

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/8751675ddad5f8caa07fc188ecac14ac24dc55da/src/EFCore/Extensions/Internal/EFPropertyExtensions.cs#L34-L41

We have `IsEFProperty` extension method and that is what we are using almost everywhere now. We can do another pass to see if anything missing otherwise this has been fixed.
