### ISSUE TITLE
Queries with `Take` are not cached properly by SQL Server provider

### ISSUE THREAD

**Issue by erdalsivri** [dotnet/efcore#32712]
An expression that has `Take(N)` is parameterized correctly but the generated query is never cached by EF when executing against SqlServer (`Microsoft.EntityFrameworkCore.SqlServer`).

I create a very simple repro on EF 8x:  [EF_Take_Test.tar.gz](https://github.com/dotnet/efcore/files/13823624/EF_Take_Test.tar.gz)

Basically it replaces  `IRelationalCommandBuilder` with a `LoggingRelationalCommandBuilder`, which keeps track of number of times a query is built by EF:

```c#
public class LoggingRelationalCommandBuilder : IRelationalCommandBuilder
{
    private static int _queryCounter;
    private readonly IRelationalCommandBuilder _inner;
    private bool _isAppendCalled;
    
    public LoggingRelationalCommandBuilder(IRelationalCommandBuilder inner) => _inner = inner;
    
    public static int QueryCounter => _queryCounter;
    public static void ResetQueryCounter() => _queryCounter = 0;

    public IRelationalCommand Build() => _inner.Build();

    public IRelationalCommandBuilder Append(string value)
    {
        if (!_isAppendCalled)
        {
            // Increment only once when the first time Append is called, which means EF is building a SQL query.
            Interlocked.Increment(ref _queryCounter);
            _isAppendCalled = true;
        }
        return _inner.Append(value);
    }
}
```

Then runs a simple query several times and logs the counter in `LoggingRelationalCommandBuilder`:

```c#
for (int i = 0; i < 100; i++) {
  _ = await context.Users.Take(take).ToListAsync();
}
Console.WriteLine("EF built {0} queries", LoggingRelationalCommandBuilder.QueryCounter);
```

This prints 100 but it should ideally print 1 as the query should be built/compiled once and reused. The following query prints 2 as expected:

```c#
for (int i = 0; i < 100; i++) {
  _ = await context.Users.Skip(take).ToListAsync();
  _ = await context.Users.ToListAsync();
}
Console.WriteLine("EF built {0} queries", LoggingRelationalCommandBuilder.QueryCounter);
```

So there is something wrong with caching for queries that include `Take`. The issue reproduces even with a compiled query:

```c#
private static readonly Func<SampleDbContext, int, Task<SampleUser>> s_compiledQuery = EF.CompileAsyncQuery(
  (SampleDbContext context, int count) => context.Users.Take(count).ToList());

for (int i = 0; i < 100; i++) {
  _ = await s_compiledQuery(context, take);
}
```

This doesn't reproduce on Sqlite so it must be a bug specific to the SqlServer provider.

You can run the attached test program after creating a SqlServer database with a table called `Users` that contains a single column called `Id`. Then you need to set the `SQL_CONN_STRING` env var. The program first runs a simple benchmark and then the custom code that keeps track of query compilation using the `LoggingRelationalCommandBuilder` class:

```
$ export SQL_CONN_STRING=....
$ cd EFTest
$ dotnet run -c Release

| Method | Mean     | Error    | StdDev   |
|------- |---------:|---------:|---------:|
| Take   | 33.23 us | 0.641 us | 0.811 us |
| NoTake | 13.31 us | 0.221 us | 0.185 us |

SqlServer
EF built 1 queries
EF built 100 queries
EF built 100 queries
EF built 100 queries
Sqlite
EF built 1 queries
EF built 1 queries
```

As  you can see from the output `Take` version is slower and always rebuilds the query even though the query is properly parameterized:

```sql
SELECT TOP(@__p_0) [u].[Id]
FROM [Users] AS [u]
```

**Comment by roji** [comment]
Yes, this is (currently) by design, because of #22525. SQL Server errors when you give it FETCH 0, so we sniff the Take parameter for 0 and rewrite to a false predicate for that case; but parameter sniffing means we can't cache the SQL.

However, our check is a bit too wide - we should only be preventing caching if both Skip *and* Take are specified; I also found a bug while looking at this. Opened #32767 to track both things.

**Comment by dster2** [comment]
Thank you @roji, that is unfortunate but understandable.

I am ignorant of many deep internals but is there a way to improve this case with Compiled Queries?  Not just as a workaround to the performance issues we're facing in this particular circumstance, but more broadly it feels wrong for any Compiled Query to (IIUC) not actually pre-compile and instead silently run the compilation pipeline on every invocation.  I might even prefer for CQs to `throw` in such cases so we don't incorrectly assume we're getting the pre-compilation benefits when we're not.

**Comment by roji** [comment]
The (relational) query pipeline has two parts:
1. The 1st part is the big, heavy compilation part - it goes from the incoming LINQ expression tree to a near-finalized SQL expression, and also, importantly, a compiled code-generated materializer which reads the results back and materializes them as entity instances, etc. Note that the SQL is nearly finalized, but not quite - it's still in tree form rather than a baked string, so we can still make changes to it.
2. The 2nd part is where we make final adjustments to the SQL tree based on parameter values, which change across invocations of the same basic tree. This is **usually** about nullability-related adjustments - and indeed there's a cache for not doing this processing every time, but rather getting the final SQL string immediately. But in cases where we need to produce different SQLs **other** than based on parameter nullability (exactly like this one), we must disable the cache.

The real heavy lifting happens in step 1 - step two is really quite light. Are you really saying that the 20us difference is in some way actually significant to you, for a database query that presumably gets sent over the network and also causes I/O on the database side? If so, could you provide a bit of context?

Finally, compiled queries are orthogonal to all of the above; even without compiled queries, the 1st part above is only performed the first time we see a given query tree shape - the outputs (materializer, near-finalized SQL tree) are cached. So the 2nd invocation of a given query doesn't need to go through this. What compiled queries do, is allow you to skip a bit of preprocessing that happens **before** the 1st part above, e.g. the cache lookup itself, and parameter extraction in the incoming LINQ query tree which must happens before that cache lookup.

**Comment by roji** [comment]
> We do have a self-inflicted performance hit in our custom IRelationalCommandBuilder [...]

Ah... Yeah, that's not a great idea... FYI there are various other (edge-case) scenarios where SQL can't get cached - Take() with 0 is only one specific case. I'd definitely advise against doing this kind of stack walking, but I indeed don't have a great answer for you...

> Again I'm ignorant and just brainstorming but I wonder if you could cache the step 2 happy path result (where all Take params > 0) and only bypass the cache in cases where a 0 was actually provided?

Unfortunately not, not with the current caching infrastructure in any case... different SQLs can only (currently) be cached based on the nullability of the query's parameters. Any sort of observation of any parameter value beyond that (e.g. is it zero or not) means we can't cache.

**Comment by dster2** [comment]
Sounds good, thanks so much Shay!
