### ISSUE TITLE
Advice on implementing change management on ef core entities

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/efcore#32818]
I am currently working on implementing a change management system using EF Core where modifications to entities, especially in many-to-many relationships, need approval before being persisted to the database. I am seeking advice or best practices on how to efficiently handle this scenario.

The system I am thinking of would intercept changes to entities and, instead of directly updating the database, it would create a change request object. This change request should include detailed information about the proposed changes, such as what properties are being modified, added, or deleted, including changes in navigation properties, especially in many-to-many relationships.

The critical requirement is that these changes should only be applied to the database after they have been reviewed and approved. This implies a need for a mechanism to:

- Intercept and serialize entity changes.
- Store these changes as pending approvals.
- Reapply the changes to the actual entities once approved.

A particular area of interest is handling many-to-many relationships. The challenge lies in effectively tracking and representing changes in the association tables that EF Core manages implicitly for many-to-many relationships (especially if the navigation properties are colelctions).

**Questions**

- Are there existing patterns or features in EF Core that facilitate this kind of change tracking and approval mechanism?
- How can changes in many-to-many relationships be efficiently tracked and represented in a change request model?
- Any guidance on handling scenarios where the navigation properties themselves have nested navigation properties?
- Any insights, suggestions, or references to relevant documentation would be greatly appreciated. This feature is crucial for maintaining data integrity and audit trails in our application.

Best regards.

**Comment by roji** [comment]
@mihaimyh what should happen to an executing SaveChanges while it's waiting for approval? Is the program supposed to hang (for minutes, for hours?) until the change is approved? Or is it supposed to complete as if the change was applied, even though it wasn't? If it's the latter, things may be more complex than you think; for example, EF retrieves the database-generated IDs of inserted entities, e.g. so that they can be updated later (or so that IDs can be sent to clients). This won't be possible here, since nothing actually gets inserted.

Also, just to make sure you're aware - you can indeed cause SaveChanges to wait or to return even though nothing happened; however, that's not a security mechanism - the developer can easily drop down to raw SQL and/or ADO.NET, and do whatever they want to the database directly. If you're looking to implement an actual security feature here, then this isn't the way - you'll need to apply security at an earlier phase.

**Comment by mihaimyh** [comment]
> @mihaimyh what should happen to an executing SaveChanges while it's waiting for approval? Is the program supposed to hang (for minutes, for hours?) until the change is approved? Or is it supposed to complete as if the change was applied, even though it wasn't? If it's the latter, things may be more complex than you think; for example, EF retrieves the database-generated IDs of inserted entities, e.g. so that they can be updated later (or so that IDs can be sent to clients). This won't be possible here, since nothing actually gets inserted.
> 
> Also, just to make sure you're aware - you can indeed cause SaveChanges to wait or to return even though nothing happened; however, that's not a security mechanism - the developer can easily drop down to raw SQL and/or ADO.NET, and do whatever they want to the database directly. If you're looking to implement an actual security feature here, then this isn't the way - you'll need to apply security at an earlier phase.

I am marking the entity being changed as detached so it does not get persisted and serialize the current values and original values as json strings and attach them to the change request object, as properties, for review.

After the change request gets approved I am deserializing the values back and perform the change on the database.

**Comment by roji** [comment]
I understand that, but that doesn't answer my questions above - is your intention for the actual SaveChanges to block while waiting for approval, or return a fake success? Also please take more of my comment against relying on this as an actual security measure, as it can be easily bypassed.
