### ISSUE TITLE
Unable to create a 'DbContext' of type '' when running Add-Migration in PMC

### ISSUE THREAD

**Issue by iKingNinja** [dotnet/efcore#32837]
I was trying to add a migration using `Pomelo.EntityFrameworkCore.Mysql`, but whenever I run `Add-Migration` in PMC, I get the following error: `Unable to create a 'DbContext' of type ''. The exception 'Access denied for user 'studio'@'localhost' (using password: YES)' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728`

```cs
using Microsoft.EntityFrameworkCore;
using Studio.Models.DatabaseModels;

namespace Studio.Services
{
    public class DatabaseService : DbContext
    {
        private string connectionString = "Server=localhost; Port=3306; Database=studio; User=studio; Password=mypwd";

        public DbSet<UserModel> Users { get; set; }
        public DbSet<RoleModel> Roles { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserModel>()
                .HasMany(u => u.Roles)
                .WithMany(u => u.Users);
        }
    }
}
``

EF Core version: 8.0.1
Database provider: Pomelo.EntityFrameworkCore.Mysql
Target framework: .NET 8.0.100
Operating system: Windows 10 Home
IDE: Visual Studio 2022 17.8.3

**Comment by 8703303** [comment]
Yes, Exactly I'm facing this issue. I've been forced to switch to .Net and EF core 7 to make everything work again.

**Comment by iKingNinja** [comment]
Right now that seems to be the only workaround

**Comment by 8703303** [comment]
To further details, It isn't related to which provider ( SQLite, SQL server, etc ) is being used.
I've tried and make the context class and models very simple, but the issue persists.

**Comment by ajcvickers** [comment]
@iKingNinja This is caused by an exception being thrown when the MySQL provider is attempting to connect to the database. Either specify the MySQL version explicitly, or fix the error causing the connection to fail ("Access denied for user 'studio'@'localhost' (using password: YES)"). If you think there is a bug here, then please report it on the Pomelo MySQL repo.

@8703303 The issue posted above is MySQL-specific. I was not able to reproduce it with other providers, since other providers don't attempt to connect to the database here. If this is not working in some other way, then please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by iKingNinja** [comment]
You are correct, it turned out the provider's version for .NET 6 is in beta hence it wasn't being shown in visual studio's versions list and there was a mismatch between .NET and the provider.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1831#issuecomment-1905071940

**Comment by intisor** [comment]
i am seeing this also
The exception 'Unable to connect to any of the specified MySQL hosts.' was thrown while attempting to find 'DbContext' types. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
