### ISSUE TITLE
Why is a static constructor added to the SqlServerTypeMappingSource class?

### ISSUE THREAD

**Issue by indrajitjadeja** [dotnet/efcore#32861]
## Why is a static constructor added to the SqlServerTypeMappingSource class?
Does this change affect a specific feature? 
Is there any test coverage for same?

Below pull request changes are present in EF core 8.0.0
https://github.com/dotnet/efcore/pull/31390

I want to understand the rationale behind switching the variable initialization from normal constructor to static constructor.

### provider and version information

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0

**Comment by indrajitjadeja** [comment]
@ajcvickers

**Comment by indrajitjadeja** [comment]
@roji @AndriySvyryd

**Comment by AndriySvyryd** [comment]
The reason is that we didn't need to create new instances of the standard mappings for every instance of `SqlServerTypeMappingSource`. While it's uncommon to have more than a single instance of `SqlServerTypeMappingSource` during normal execution it would decrease memory usage a bit for more complex usages, like some multi-tenant scenarios. There is no functional difference from this particular change, so the tests didn't change.
