### ISSUE TITLE
How to make `Include` method work in custom `IQueryable` collection ?

### ISSUE THREAD

**Issue by sulton-max** [dotnet/efcore#32964]
## Description

I created custom queryable and custom query provider to be able integrate caching directly into `IQueryable`. But when executing query, it's not considering `Include` operation inside expression, I assume EF Core preprocessors for expression visiting must be failing, but I'm not sure

### Expected behavior

- querying using custom queryable which uses custom query provider that wraps ef core's query provider
- when querying using custom querable, it should result exactly as querying from `DbSet` directly

### Reproducing 

 Bug example repo - https://github.com/WoW-2-0-Core/EFCore.Issues, CachingIssues -> IncludeIssue project

- Clone and run the above project
- Send request for endpoint `/api/users/a` - which uses custom queryable returns following result
```json
[  
  { 
      "id": "727bf16f-5c3a-41cc-bf80-acf630f37f07",     
      "firstName": "Bill",     
      "lastName": "Goyette",     
      "emailAddress": "Hugh.Larson@yahoo.com",     
      "userSettings": null   
   }
]
``` 

- Sending request for endpoint `api/users/b` - which doesn't use custom queryable returns different and expected result
```json
[
  {
    "id": "727bf16f-5c3a-41cc-bf80-acf630f37f07",
    "firstName": "Bill",
    "lastName": "Goyette",
    "emailAddress": "Hugh.Larson@yahoo.com",
    "userSettings": {
      "userId": "727bf16f-5c3a-41cc-bf80-acf630f37f07",
      "language": "English",
      "theme": "Light"
    }
  }
]
``` 
- although queries are the same, results are different, when querying from `DbSet` directly user settings is included in query result
    
### Environment

EF Core version: 8.0
Database provider: Npgsql.EntityFrameworkCore.PostgreSQL Version="8.0.0
Target framework: .NET 8
Operating system: mac OS Sonoma 14.2.1
IDE: JetBrains Rider 2023.3.2

**Comment by ajcvickers** [comment]
@roji @maumar `Include` is a no-op by default. Any way to change that?

**Comment by sulton-max** [comment]
@ajcvickers Hey! Any updates on this ?

**Comment by roji** [comment]
I think the logic here was to allow queries with Include() to execute over non-EntityQueryable; for example, in mocking scenarios where an in-memory list is used (with AsQueryable()), composing the Include() operator would make the query fail.

Stepping back, I don't think that integrating caching logic via a custom IQueryable is the right way to go - EF has a variety of extensibility hooks and interceptors which would probably be a better fit for this kind of thing. Otherwise, the Include() implementation checks if the queryable source's provider is an EntityQueryProvider ([code](https://github.com/dotnet/efcore/blob/main/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2628)); you may be able to make this work if you use that as your provider implementation (or a subclass thereof).
