### ISSUE TITLE
Entity materialization using StringPool

### ISSUE THREAD

**Issue by rouen-sk** [dotnet/efcore#32986]
Problem: I think there are many use cases, when user needs read-only object graph containing lots of strings that repeat a lot. Things like first names, country/postal codes, category codes, etc. AFAIK, right now every entity has its own copy of the string, resulting in unnecessary memory footprint in this scenario.

I imagine something like:

```
var products = dbContext.Products.AsNoTracking().UseStringPool().ToList()
```
or even
```
var products = dbContext.Products.AsNoTracking().UseStringPool(existingPrepopulatedStringPool).ToList()
```
could be nice opt-in trade-off, little bit more materialization time for memory saving. 

I assume this could be first implemented completely as extension, without change to EF Core code, using `IMaterializationInterceptor`, and I would gladly try it, if someone could give me any pointers, where to start (regarding how to "mark" the query in similar fashion as `AsNoTracking` does, so it can be used per-query; and maybe if it is possible to prevent allocating the strings would be used to check/insert into StringPool).

**Comment by roji** [comment]
EF sits on top of the low-level database driver (e.g. SqlClient, Npgsql...), and that's where raw database results - such as all string results - get read. In other words, the reading of strings from the wire happens in a layer underneath EF, and there's nothing you can do at the EF layer to prevent that. So if you implement string pooling (or "interning") at the EF level, that wouldn't reduce the memory footprint as the multiple copies have already been created.

See https://github.com/npgsql/npgsql/pull/3458 for a bit of discussion and prototyping of string interning inside Npgsql, the PG driver. A lot of that was about some SQL string that Npgsql does internally - since then we've introduced a raw mode where that no longer happens (so not relevant). One could still think about interning actual strings coming back from the database, but it's very unclear whether that works in the general case: the pool itself adds overhead (and contention), a caching policy needs to be done that wouldn't cause excessive memory (how do you decide which strings to keep in the cache and which to purge), and reducing cardinality by making the cache per-column makes things even more complex.

I'll go ahead and close this as something that isn't relevant for the EF layer in any case, as above - but if you'd like to continue discussing it here, please feel free to post back.

**Comment by rouen-sk** [comment]
Thank you @roji 
Let's forget allocation preventing then, and focus on pooling strings. Allocations will happen, but in case the created objects will be long lived (cached), it is still better to quickly swap strings for their pooled versions (in IMaterializationInterceptor) so that they are collected (ideally in gen0), than keeping thousands of duplicates for a long time, right? 

I understand this is probably too niche for EF codebase, but if I wanted to implement it as extension, could you please give me any hints, how to implement the per-query opt-in mechanism, so I can recognize queries requesting this behavior inside the interceptor?

**Comment by roji** [comment]
> Allocations will happen, but in case the created objects will be long lived (cached), it is still better to quickly swap strings for their pooled versions (in IMaterializationInterceptor) so that they are collected (ideally in gen0), than keeping thousands of duplicates for a long time, right?

That *may* be right in the case where the entities being materialized actually all live for a long time. Once again, remember that there's a cost to this, which you'd be paying for all cases, probably causing a performance degradation for typical case where entities *aren't* kept around for long. I'd advise against trying something like this unless you have a clear, specific scenario where you know this will actually improve performance.

**Comment by rouen-sk** [comment]
> I'd advise against trying something like this unless you have a clear, specific scenario where you know this will actually improve performance.

I do have clear and specific scenario, exactly as I described in original post - tens of thousands of cached objects with repeated string values. I could do something like `var products = dbContext.Products.AsNoTracking().Select(p => new StringPooledProduct(p)).ToList()` and do pooling in this DTO constructor, I was just wondering about making it reusable and more elegant via EF extensibility points. 

>Once again, remember that there's a cost to this

Yep, time-memory trade-off, increasing immediate allocations, but reducing overall long-lived cache size

>probably causing a performance degradation for typical case where entities aren't kept around for long

That's why I want it to be opt-in, per-query, like `AsNoTracking`

**Comment by roji** [comment]
So I'm still dubious this is something that will actually help you out - it feels more like a premature micro-optimization. But if you'd like to try, the materialization exception is probably the way to go ([some docs/samples here](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#simple-actions-on-entity-creation)). I'm not sure if there's a way to trigger that via a query operator like AsNoTracking(); with interceptors that can usually be done via tags, but I'm not sure the materialization interceptor specifically works well with that. Hoewver, it seems to make sense for this to be per-entity type rather than per-query; if so, then you can simply check the entity type on the MaterializationInterceptionData argument.

**Comment by rouen-sk** [comment]
Your gut feeling turned out to be right, @roji 

I just simulated my typical use case in debug mode and took some snapshots, cached object graph of about 30k objects, containing 194k strings, of which 167k are duplicates (according to Insights -> Duplicate strings feature in Visual Studio), but since they are fairly small (as I said, country codes, postal codes, category codes), the waste is "whooping" 3 MB :)

So lesson here is, unless you have BIG duplicate strings, this is not worth the hassle. I hope this will save some souls googling Entity Framework Core string pooling.

**Comment by roji** [comment]
Thank you for measuring and for sharing the results - that's always very valuable.

FWIW there **may** be a useful story for doing string interning/pooling at the lower-level ADO.NET layer (i.e. not instantiate String instances at all, but rather reuse the same pooled instance), but I think it would be hard to come up with a general strategy that's actually beneficial and helps the right cases without regressing others, etc.
