### ISSUE TITLE
`Select` projection with an (uncorrelated) subquery produces two separate SQL queries

### ISSUE THREAD

**Issue by InspiringCode** [dotnet/efcore#33012]
A `Select` projection with an (uncorrelated) subquery seems to produce two separate SQL queries, which is not what I expect as a developer. For example:

```csharp
IQueryable<Employee> allEmployees = context
	.Employees
	.Where(x => x.Department == "Engineering");

Employee[] result = allEmployees
	.Where(x => x.Salary > 1000)
	.Select(e => new {
		Employee = e,
		TotalCount = allEmployees.Count()
	})
	.Skip(2).Take(10)
	.ToArray();
```

produces:

```sql
info: Executed DbCommand (16ms) [...]
      SELECT COUNT(*)
      FROM [Employees] AS [e]
      WHERE [e].[Department] = N'Engineering'

info: Executed DbCommand (26ms) [...]
      SELECT [e].[Id], [e].[Department], [e].[Manager], [e].[Name], [e].[Salary], @__Count_0 AS [TotalCount]
      FROM [Employees] AS [e]
      WHERE [e].[Department] = N'Engineering' AND [e].[Salary] > 1000.0
      ORDER BY (SELECT 1)
      OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
```

Can I somehow force EF to combine these two queries into one (which is what I expect as a developer when I write the above query):

```sql
      SELECT [e].[Id], [e].[Department], [e].[Manager], [e].[Name], [e].[Salary], (
             SELECT COUNT(*)
             FROM [Employees] AS [e]
             WHERE [e].[Department] = N'Engineering') AS [TotalCount]
      FROM [Employees] AS [e]
      WHERE [e].[Department] = N'Engineering' AND [e].[Salary] > 1000.0
      ORDER BY (SELECT 1)
      OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY
```

In my real application the query is quite complex (with filters and DISTINCTs) and it is measurable faster to combine the two (I guess because SQL Server can reuse quite some intermediate query results). But there might also be other reasons, why developers want to combine the two queries, for example if there are hard consistency requirements.

Here is a [.NET Fiddle](https://dotnetfiddle.net/rVnLzy) with full repro.

**Comment by roji** [comment]
I agree that EF should be folding the referenced IQueryable into the larger query, rather than executing it as a separate query (with an additional roundtrip). This may connect with some work I'm currently doing on the new funcletizer (#32999) - I'll possibly take a look.

**Comment by roji** [comment]
Note the similarity/relationship with #29918, which is to translate to SQL CTEs when the same IQueryable variable is referenced multiple times. This issue here is only about inlining with CTEs (so if the same variable is referenced multiple times, we'll get subquery duplication), but it does prepare things a bit.

**Comment by roji** [comment]
Note that there's a small downside to this; in the current way things work, integrating e.g. `nestedSubquery.Count()` evaluates that expression and sticks the result in as a parameter. This means you can execute the same containing query with different nested subqueries, and they'll all use the same query cache entry.

After this change, since `nestedSubquery` gets inlined into the query tree, having different nested subqueries would cause a cache miss, as well as different SQLs getting sent out to the database.

The change still feels right though; if users wanted to have two queries, they can just execute two queries instead of integrating a queryable into another; composing queryables really means that a single LINQ query is being constructed.
