### ISSUE TITLE
Performance implications of Projections which result in unnecessary casts 

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [dotnet/efcore#33036]
Consider an ef core linq query like this,

```csharp
string prefix = 'blg';
var blogs = context.Blogs.Select(x => new { Name = prefix + x.Id }).ToList();
```
This results in a SQL query,
```sql
SELECT _variable_ + CAST(id AS VARCHAR(MAX)) as 'Name' FROM blog
```
Here SQL must cast it to a `varchar(max)` because it doesn't know the length limit, which is understandable. 

However, does this have any performance implications? Consider doing this for 10,000 rows or more. From SQL standpoint, the query plan would be almost identical without cast, but maybe some additional storage needs to be allocated due to casting as VARCHAR(max) on the SQL side?

I'm trying to understand if this can cause any performance degradation or additional memory consumption as application scales. 

An alternative to this is to make the query precise and perform the string concatenation on the app server side. Something like,
```csharp
string prefix = 'blg';
var blogsDbResult = context.Blogs.Select(x => new { x.Id }).ToList();
var blogs = blogsDbResult.Select(x => new { Name = prefix + x.Id })
```
which generates a rather simple SQL query,
```sql
SELECT id FROM blog
```

But the question is, is this over-optimization warranted?

Any additional insights would be much appreciated. 

----------------------------------------------------------------------------------------------------------------

Framework: net core + ef core
DB: MSFT SQL Server

**Comment by roji** [comment]
CASTs can indeed have a significant impact on performance, but this is usually the case when they prevent index usage e.g. in WHERE clauses; their effect in pure projections isn't likely to be very significant.

But my general advice would be, whenever the performance impact of something isn't clear, simply writing a benchmark is the best way to find out the answer, rather than asking a question. Putting together a BenchmarkDotNet scenario is trivial, and would ensure that your specific scenario is measured, rather than a more general observation (such as the one I made above) which may not actually apply to your scenario for whatever reason.

Specifically on the string concatenation issue, we actually have plans to make this better - not so much for direct performance gains but more for query correctness; see #32491 and #32333.
