### ISSUE TITLE
Which .slnf to use for development?

### ISSUE THREAD

**Issue by clement911** [dotnet/efcore#33156]
I've cracked open the EF core repo for the first time.
I'm seeing a few different solution files and I'm wondering which one I should use?

It seems that they are using a slightly different set of projects.

![image](https://github.com/dotnet/efcore/assets/3426504/532770ed-a898-485b-b485-6b07b682c9d8)

In my case, I'm mostly interested in the sql server provider.

Does it imply that I should use `EFCore.Relational.slnf`

**Comment by roji** [comment]
You can always just open EFCore.sln, the solution filters are for not loading unnecessar projects (e.g. use less memory). EFCore.Relational.slnf is a good option if you're focusing on SQL Server.

But why not just examine the slnf to see which projects they reference, rather than posting a question? That seems easier and causes less noise.

**Comment by clement911** [comment]
I could but that doesn't tell me why these filters exist in the first place.
Is this not the right place to ask questions?
I want to make a contribution but the repo is overwhelming and I found very little details on how to get started. I guess I'll try to figure things out on my own..

**Comment by roji** [comment]
@clement911 you're absolutely welcome to ask questions on this repo - it's just that solution filters in general aren't an EF thing (a quick Google search brings up [this page](https://learn.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2022) which explains the concept).

So I'd just suggest doing a bit of research before posting a question - but otherwise please feel free to do that if you need any assistance. EF is indeed a big and complicated project, and not easy to get into.

I'll go ahead and close this issue as the question has been answered.

**Comment by clement911** [comment]
Thanks @roji 
I am familiar with .slnf files.
I was not asking what they are but rather  which one I should use.

**Comment by roji** [comment]
> I was not asking what they are but rather which one I should use.

Right, so then that's where I was suggesting to just open them up and see what they refer to.
