### ISSUE TITLE
Does nullable reference types enable affect the runtime null checks?

### ISSUE THREAD

**Issue by maxcherednik** [dotnet/efcore#33245]
I am trying to enable the nullable reference types for the project. 
Since it is pretty old project, I am following the migration process described here: https://learn.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies

1. I enabled the nullable types on the project level
2. I added #nullable disable warnings to every single file

This way I was hoping to enable all the new classes and retrospectively refactor old files.

### What I expect

Based on the documentation enabling the nullable reference types should not affect the runtime execution: 
```
The compiler doesn't add any runtime checking for non-nullable reference types
```
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types#nullable-references-and-static-analysis

### What I get

Half of my tests are failing with the following message:
```
An error occurred while saving the entity changes. See the inner exception for details.) (Data is Null. This method or property cannot be called on Null values.
```

Even though I understand that there might be real null-cases, I was hoping to solve those issue later one by one.

### Include provider and version information

EF Core version: 8.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET 8.0)
Operating system: Windows

**Comment by roji** [comment]
@maxcherednik the compiler doesn't add any runtime checking, but code (EF in this case) can still use reflection to look at properties and react differently based on whether they're nullable or not. When you turn on the feature, EF treats properties with nullable reference types as required, and so creates a non-nullable column in the database - that's why you're seeing these exceptions.

For more details, [see these docs](https://learn.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types).

**Comment by maxcherednik** [comment]
@roji I understand. What I am looking at is a migration path. Is there one where I can do this step by step retrospectively?

**Comment by maxcherednik** [comment]
>  but code (EF in this case) can still use reflection to look at properties and react differently based on whether they're nullable or not. When you turn on the feature, EF treats properties with nullable reference types as required, and so creates a non-nullable column in the database - that's why you're seeing these exceptions.

Logically it is kinda the same as if compiler would add extra null checks and started to throw. 
Ideally, ef core should have taken the same non-invasive approach. 

By default, it is on and throwing(like it is now). 
To have an option to keep the old behaviour. Like this setting for example(userelationalnulls). Maybe this is exactly the setting I need?

**Comment by roji** [comment]
Unless I'm mistaken, `#nullable disable warning` only disables warnings, but does not otherwise disable the nullability feature (or contex) itself. In other words, it sounds like your EF properties are still getting annotated as non-nullable - try to opt out with `#nullable disables` instead of `#nullable disable warnings`.

**Comment by maxcherednik** [comment]
@roji It worked with `#nullable disable`. 

Thank you.
