### ISSUE TITLE
Performance decrease (10 second delay) in database migration 8.0.0 vs 8.0.3 

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [dotnet/efcore#33399]
Hi,

After upgrading from 8.0.0 to 8.0.3, get a large performance decrease during database creation.

https://github.com/EvgenyMuryshkin/EF8PPerf

![image](https://github.com/dotnet/efcore/assets/11254187/a070471a-5ff2-4a7d-8208-e57870bc2246)

EF 9 also has the same issue

![image](https://github.com/dotnet/efcore/assets/11254187/09e66541-9679-4200-bbeb-fa0558df7b6f)

### Include provider and version information
.NET 8/.NET 9
EF 8.0.0 => 8.0.3, 9.0.0-preview.2.24128.4
Windows 11 Pro
VS 2022 17.9.4/17.10.0 Preview 2.0

Thank you

**Comment by roji** [comment]
@EvgenyMuryshkin looks like a duplicate of #33176, which has already been fixed for 8.0.4. Can you please try the workaround in [this comment](https://github.com/dotnet/efcore/issues/33176#issuecomment-1969668284) and confirm?

**Comment by EvgenyMuryshkin** [comment]
@roji nope, I think my issue is not model creation, but database creation.
Model is already created

![image](https://github.com/dotnet/efcore/assets/11254187/5ed88216-546c-40c8-b9f2-aab7bf2a0ed3)

**Comment by roji** [comment]
This doesn't repro for me (MacOS Sonoma):

![image](https://github.com/dotnet/efcore/assets/1862641/9257a23a-3818-4d40-939c-a343abcc0150)

I'm noticing that EF upgraded patch versions of SqlClient between [8.0.0](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/8.0.0#dependencies-body-tab) (SqlClient 5.1.1) and [8.0.3](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/8.0.3#dependencies-body-tab) (SqlClient 5.1.5). Can you try to take a dependency on SqlClient 5.1.1 when using EF Core 8.0.0 to see if the problem comes form there? I'm thinking possibly of #7283 or similar.

**Comment by EvgenyMuryshkin** [comment]
@roji 8.0.1 fast, 8.0.2 slow.

with 8.0.0
5.1.1 - fast
5.1.2 - slow

**Comment by roji** [comment]
Thanks for confirming!

The 5.1.2 release notes are [here](https://github.com/dotnet/SqlClient/blob/main/release-notes/5.1/5.1.2.md), the culprit may be https://github.com/dotnet/SqlClient/pull/1983. This may very well be a dup of #7283.

/cc @David-Engel @cheenamalhotra

**Comment by cheenamalhotra** [comment]
Have you tried setting [ConnectRetryCount](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.connectretrycount?view=sqlclient-dotnet-standard-5.1)=0 on the connection string to disable transient fault handling?

**Comment by ajcvickers** [comment]
@cheenamalhotra This should not be needed. Issue https://github.com/dotnet/efcore/issues/7283 goes into this in detail.

**Comment by roji** [comment]
@cheenamalhotra in addition to #7283, see https://github.com/dotnet/SqlClient/issues/29 and https://github.com/dotnet/SqlClient/pull/463 on the SqlClient side where this was discussed at length (especially why the connection string-based approach is insufficient here).

**Comment by EvgenyMuryshkin** [comment]
> Have you tried setting [ConnectRetryCount](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.connectretrycount?view=sqlclient-dotnet-standard-5.1)=0 on the connection string to disable transient fault handling?


it actually worked, thanks :)

![image](https://github.com/dotnet/efcore/assets/11254187/19f794de-b796-4c62-99f9-880b3290ece3)

**Comment by ErikEJ** [comment]
Interestingly, this test is not failing: https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs#L364

**Comment by roji** [comment]
> it actually worked, thanks :)

The problem with setting ConnectRetryCount=0 in your actual connection string is that is disables connection retrying everywhere, not just in the database existence check.

**Comment by cheenamalhotra** [comment]
> @cheenamalhotra in addition to #7283, see [dotnet/SqlClient#29](https://github.com/dotnet/SqlClient/issues/29) and [dotnet/SqlClient#463](https://github.com/dotnet/SqlClient/pull/463) on the SqlClient side where this was discussed at length (especially why the connection string-based approach is insufficient here).

Thanks for the context, I think we should also make sure FailFast is supported for `OpenAsync()` as well, now that Transient fault handling is enabled.. This probably skipped our minds and we didn't realize before.

For you and @ajcvickers 
Can you confirm the reason why [dotnet/SqlClient#29](https://github.com/dotnet/SqlClient/issues/29) regressed was due to the change we made on `OpenAsync()` API to enable Transient Fault Handling? And that `Open()` API works as expected with Fail fast option defined?

> The problem with setting ConnectRetryCount=0 in your actual connection string is that is disables connection retrying everywhere, not just in the database existence check.

Yes, that is true.

**Comment by cheenamalhotra** [comment]
> Interestingly, this test is not failing: https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs#L364

Note that it's only testing `Open()` and not `OpenAsync()`..

**Comment by ErikEJ** [comment]
But does OpenAsync support the new overload?

**Comment by ErikEJ** [comment]
Ah, I found: https://github.com/dotnet/SqlClient/issues/615

**Comment by ajcvickers** [comment]
Confirmed the regression is for async only.

**Comment by EvgenyMuryshkin** [comment]
Hi all,

8.0.4 looks good, will run our full test suite to confirm shortly.

![image](https://github.com/dotnet/efcore/assets/11254187/79e3f46b-679e-4abc-8a7b-4e64a81ffd05)

Thanks,

**Comment by roji** [comment]
@EvgenyMuryshkin I don't think we've done anything on the EF side (unless I've missed something) - we're still waiting for support to be added to SqlClient to programmatically opt-out of the retrying behavior (that's https://github.com/dotnet/SqlClient/pull/2433).

**Comment by EvgenyMuryshkin** [comment]
@roji this is weird. I restarted visual studio and now it is back to 10 second delay... false alarm, sorry about.

**Comment by roji** [comment]
Note: the plan on the SqlClient side is to revert the retrying behavior for OpenAsync for 5.0 ([comment](https://github.com/dotnet/SqlClient/issues/2481#issuecomment-2108103984)), and re-introduce it in SqlClient 6.0.

Opened #33741 to track eventually using the opt-out when we switch to SqlClient 6.0. We can keep this issue open just to track SqlClient's reverting of the async retry logic in 5, so that people can find it.

**Comment by ErikEJ** [comment]
In other words, this will be fixed in 5.2.1

**Comment by ajcvickers** [comment]
Verified this is fixed with SqlClient 5.2.1.

**Comment by EvgenyMuryshkin** [comment]
@ajcvickers which version of EF will get this fix? 8.0.7?

**Comment by ErikEJ** [comment]
@EvgenyMuryshkin You can just add an explicit PackageReference to 5.2.1

**Comment by EvgenyMuryshkin** [comment]
@ErikEJ I tried but I got lots of failed tests due to transient connection failures, will try to create repro soon

**Comment by ajcvickers** [comment]
Re-opening to consider updating the 8.0 dependency, which is currently at 5.1.5.

**Comment by roji** [comment]
@ajcvickers isn't SqlClient planning to revert their change in the 5.1 branch? I haven't been following closely...

**Comment by ajcvickers** [comment]
@roji Not sure. Will try to pull together the relevant info for the team to discuss.

**Comment by ErikEJ** [comment]
@ajcvickers @roji This will be fixed in 5.1.6 https://github.com/dotnet/SqlClient/projects/20

**Comment by EvgenyMuryshkin** [comment]
@ErikEJ looks like my transient connectivity errors were something random and gone after PC restart (Windows update forced me to do that). 
EF 8.0.6 + direct reference 5.2.1 seems to be working fine.
Thanks.

**Comment by MichaCo** [comment]
Our unit test performance for some apps degraded like crazy after updating from .NET 6 to .NET 8. 

After trying many things for hours I finally found this issue and the connection string workaround... 
At least this time it wasn't the huge performance issue with OPENJSON in EF 8.

Build and test duration jumped from 5 to 20minutes on average for some CI builds (which runs integration tests and create a lot of databases)

![image](https://github.com/dotnet/efcore/assets/5837539/35375ebe-75df-4906-977b-5a57e00445ac)

This problem still exists today when using EF Core 8.0.6.

Changing the connection string to include `;ConnectRetryCount=0` fixed all the problems... For us this problem only affects unit tests where its fine to disable retry (at least as long as we do not actually use certain features I guess).
But it would be really great if that could be fixed in EF 8.0.x soon

**Comment by AndriySvyryd** [comment]
Fixed in https://github.com/dotnet/efcore/commit/576f0d009f9d63fc36fa3d4a4a6c40b8e9d9d93b
