### ISSUE TITLE
Problem with annotations "ForeignKey" & "InverseProperty" on One-to-One relation.

### ISSUE THREAD

**Issue by topguss** [dotnet/efcore#3341]
We have problem with annotations "ForeignKey" & "InverseProperty"  on one-to-one relation with EF 7 beta-7.

We tried several cases, here are our examples and results:

Case 1:

```
public class Person {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long? PersonId { get; set; }

    [InverseProperty("Person")]
    public virtual PersonPhoto PersonPhoto { get; set; }
}

public class PersonPhoto {
    [Key]
    [Required]
    public long? PersontId { get; set; }

    [ForeignKey("PersontId")]
    public virtual Person Person{ get; set; }
}

public class Test {
    Person newPerson = new Person();
    _dbContext.Add(newPerson);

    PersonPhoto newPersonPhoto = PersonPhoto();
    newPersonPhoto.Person = newPerson;
    _dbContext.Add(newPersonPhoto)

    _dbContext.SaveChanges();
}
```

When we tried to add two related object to DbContext, EF couldn't recognize annotation "DatabaseGenerated" and it tried to add PersonId value into Person table.

Here is exception: 
"An error occurred while updating the entries. See the inner exception for details.
Cannot insert explicit value for identity column in table 'Person' when IDENTITY_INSERT is set to OFF."

MS SQL profiler catch only one insert statement (for Person table) .

Case 2:
Same as case 1, but we commented "InverseProperty" annotation on Person.
Here is exception: 
"An error occurred while updating the entries. See the inner exception for details.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PatientHasPhoto". The conflict occurred in database "Test", table "Person", column 'PersonId'."

MS SQL profiler catch two insert statements. The first for PersonPhoto and the second for Person.

Case 3:
Same as case 1, but we commented "ForeignKey" annotation at PersonPhoto.
Everything Work fine.

Case 4:
Same as case 1, but we placed "ForeignKey" annotation on PersontId insted of Person at PersonPhoto.
Everything Work fine.

Case 5:
Same as case 1, but we commented all annotations.
Everything Work fine.

---

We cannot understand why case 1 failed? 
According with MSDN documentation (https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.schema.foreignkeyattribute(v=vs.110).aspx) this two cases should be similar.

Are we missing something?

**Comment by smitpatel** [comment]
@topguss - I tried running above code with beta7, everything is working fine for me.
By looking at exception message for case 1, following could have happened
- DatabaseGeneratedAttribute worked correctly and made column PersonId identity for table Person
- The relationship between Person and PersonPhoto got configured in a way that made Person as dependent side and PersonId became the foreign key property. EF will insert the foreign key property value when inserting new record which conflicts with identity.

Since either side can be principal in one-to-one relationship, if the principal end is not specified by user then it can be configured in opposite way then expected.

`InverseProperty` has no effect in determining principal end. It helps in assigning navigations to relationships when 2 entities have more than one relationship between them.
`ForeignKey` has effect on determining principal end based on how it is used. It can be specified on navigation property indicating name of the foreign key property. This can appear on either side of the relationship. But when it is used on property indicating name of the navigation, it appears on dependent side only.

Can you share your modelsnapshot file? That would tell us exactly what is the relationship configured.

**Comment by topguss** [comment]
Hi again, 

This example we were from our commercial project. And it represent simplified use case. 

Now, we make test solution and find out that problem occurs when we have two dependent classes (as is in commercial project) PersonPhoto and PersonData.

As you said, everything is working fine with one dependent class.

Here is additional dependent class:

    public class PersonData
    {
        [Key]
        [Required]
        public long? PersonId { get; set; }

        [ForeignKey("PersonId")]
        public virtual Person Person { get; set; }
    }

and updated test class:

    public class Test {
        Person newPerson = new Person();
        _dbContext.Add(newPerson);

        PersonPhoto newPersonPhoto = PersonPhoto();
        newPersonPhoto.Person = newPerson;
        _dbContext.Add(newPersonPhoto);

        PersonData newPersonData = PersonData();
        newPersonData.Person = newPerson;
        _dbContext.Add(newPersonData);

        _dbContext.SaveChanges();
    }

Testing cases 3, 4 and 5 are same (and give same results), but during test we were making changes on both dependent classes.

Now, test case 1 and 2 give same result as previous test case 2:

"An error occurred while updating the entries. See the inner exception for details.
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Person". The conflict occurred in database "TestPerson", table "dbo.Person", column 'PersonId'.
The statement has been terminated."

MS Profiler catch this statement.
exec sp_executesql N'SET NOCOUNT OFF;
INSERT INTO [PersonPhoto] ([PersonId]) VALUES (@p0);
SELECT @@ROWCOUNT;
',N'@p0 bigint',@p0=-2

Here is link to full testing solution (Visual Studio project and SQL script for database):
https://drive.google.com/open?id=0B5bsSH-06GTYLWY5XzdCc05OQUE

**Comment by smitpatel** [comment]
@topguss - Thanks for the code. It explained all the strange thing happening here.
In your model, `Person` has one-to-one relationship with `PersonData` & `PersonPhoto`. For both relationships, `Person` is the principal table.
Since relationships discovered by conventions and not being specified explicitly, EF has to determine the principal end of each relationship by conventions.

**Case 5:** No Data annotations
In the absence of annotations, relationships will be configured by conventions fully. Since the entity `Person` is participating in multiple relationships and can be principal type for both of them, EF selects it to be principal type in both relationship. Your model matches with the model EF generates and everything works fine.

**Case 4:** `ForeignKey` annotation on foreign key property instead of the navigations
When `ForeignKey` attribute is used on property, that property is foreign key property hence the entity containing that property is dependent type and the referenced entity is principal type. Since you set `ForeignKey` on property in `PersonPhoto` & `PersonData`, EF made those entities dependent type and entity `Person` principal type. EF generated model matches expected model and everything works.

**Case 3:** No `ForeignKey` annotations
`ForeignKey` attribute is the only attribute which can influence the principal/dependent side of relationship and `InverseProperty` has no effect in it. So in the absence of `ForeignKey` annotations EF worked the same way as case 5 and made `Person` principal type for both relationship therefore everything works.

**Case 2:** No `InverseProperty` annotations
Since `InverseProperty` has no effect in determining the principal/dependent side, case 2 will generate exactly same model as case 1 and will give same error.

**Case 1:** `ForeignKey` annotations on navigations
`ForeignKey` annotation on navigation specifies foreign key property and this annotation can be placed on either navigation. EF add entities to the model as it finds them. In this particular case, EF started with `Person` then explored `PersonData`. Due to this EF tried to create relationship from `PersonData` side which made `Person` dependent end. Since this is one-to-one relationship, EF does not know which side is principal type. EF tries to determine it while setting foreign key property for relationship in conventions. Since `ForeignKey` attribute on navigation tells `PersonId` as foreign key property and it exists on dependent side `Person` if configured `Person` to be dependent type determined through data annotations. Conventions does not override configurations made by data annotations. Therefore what conventions did in case 5 will not happen here and `PersonId` column in `Person` table will take value from `PersonId` column in `PersonData` table. Therefore while saving entities EF will try to insert value in `PersonId` of `Person` table. Since `PersonId` in `Person` is marked to be identity column, it throws exception - `System.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Person' when IDENTITY_INSERT is set to OFF.`


**What is the source of other exception:**
In the domain model you have marked `Person` table to use identity. Therefore if EF creates model and generates database for you then you will get exception `System.Data.SqlClient.SqlException (0x80131904): Cannot insert explicit value for identity column in table 'Person' when IDENTITY_INSERT is set to OFF.`

The SQL script you provided to generate database has foreign key constraint checks. Therefore if you create database using the script instead of EF then you will get exception `System.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Patient". The conflict occurred in database "TestPerson", table "dbo.Person", column 
'PersonId'.`

**How to use `ForeignKey` and `InverseProperty` correctly**
`ForeignKey` and `InverseProperty` are attributes to specify how you want the relationship to be configured if you want to specify or to remove ambiguity which stops conventions to build relationships. It is essential that attributes to be used in correct way. If they specify invalid model then EF will throw exception. If they have some ambiguity then the model created can be different from what is expected.

`InverseProperty` - When 2 related entities have multiple navigations pointing at each other such that there can be multiple pairs of navigations, it is ambiguous to determine the correct pairs for relationship building. In such case `InverseProperty` attribute helps determine the correct inverse navigation for given navigation and those 2 navigation will participate in relationship. When there is unique pairs of navigations then `InverseProperty` just provide readability and conventions will determine the same pairs if no annotations provided.

`ForeignKey` - This attribute tells EF the foreign key properties to use when the names of properties are different from the ones which convention can recognize. (If the navigation name is `Person` and if `PersonId` property exists on depending entity type then convention will use it as foreign key property without annotation also). Since `ForeignKey` attribute can determine dependent side, its placement is important in case of one-to-one relationship (dependent side is pretty clear when its one-to-many relationship). `ForeignKey` attribute's placement affects determinism of dependent side in following ways:
- If the attribute appears on a property then entity type containing property is dependent side.
- If the attribute appears on navigation then property(-ies) can appear on either entity type. The entity type containing those properties will be made dependent type.

In the cases like above where the foreign key property specified on navigation appears on both entity types then EF will maintain the sides determined at that time which can be different than user intention.

Hope this helps!

**Comment by rowanmiller** [comment]
@smitpatel is there any action needed on our side from your investigation?

**Comment by smitpatel** [comment]
@rowanmiller - No, everything working fine as expected.
