### ISSUE TITLE
Query optimization issue when using interceptors that filter Nullable<> fields

### ISSUE THREAD

**Issue by BlaineM-SeriouslyRAD** [dotnet/efcore#33599]
Situation:

- Entities have a nullable GUID field "DeletedGuid" which stores a value if the entity is deleted and is ```null``` for active entities
- Interceptor added to automatically filter deleted entities ```item => item.DeletedGuid == null```

Problem:

- When applying the same deleted filter to the DbSet, EF incorrectly applies "WHERE 0 = 1" in the generated SQL

To reproduce:

- Open the attached project
- In Package Manager Console, run ```Update-Database```
- Run the project

This performs the following actions:

- Adds 10 blogs to the database (all active / not deleted)
- Queries the number of blogs without any additional filter (only the one applied by the interceptor) (```db.Blogs.Count()```). This correctly returns 10 records
- Queries the number of blogs with the soft delete filter applied a second time manually (```db.Blogs.Where(item => item.DeletedGuid == null).Count()```). This incorrectly returns 0 records (it should still return 10).

_(Note that the sample program outputs the expressions transformed and SQL generated to the console)_

The problem appears to be that the expression:
 ```
[Microsoft.EntityFrameworkCore.Query.EntityQueryRootExpression]
    .Where(Param_0 => (Param_0.DeletedGuid == null))
    .Where(item => (item.DeletedGuid == null))
```

Is being translated to:
```
WHERE 0 = 1
```

It's worth noting that

- this behaviour does not occur if using a boolean flag to determine entity deleted state
- this is not an issue in EF6

EF Core version: 8.0.4
Database provider: Microsoft.EntityFrameworkCore.Sqlite / Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.9.6

[Interceptors.zip](https://github.com/dotnet/efcore/files/15081516/Interceptors.zip)

**Comment by FenikkusuKoneko** [comment]
I had a similar case with "WHERE 0 = 1" when filtering included entities in the query plus a global filter.
I solved the issue by explicitly telling EFCore that the property is of `DateTime?` in OnModelCreating method where I apply the filter.
If you apply the same filter twice, one can be true and the other one false because EFCore thinks that field or property is not null and will return false. Hence the 0 = 1.

This didn't happen in .NET 7. So my theory is that they added more checks on the query optimization part about nullability.
What's funny though is that using `!x.DeletedAt.HasValue` works. But I didn't want to rely on this method and I fixed it where I construct the filter.
I will provide what I had to change:

Before:
`var filter = Expression.Lambda(Expression.Equal(Expression.Property(param, property), Expression.Constant(value)), param);`

After:
`var filter = Expression.Lambda(Expression.Equal(Expression.Property(param, property), Expression.Constant(value, typeof(DateTime?))), param);`

What changed? I explicitly told Expression.Constant that I work with a nullable DateTime. You could try the same with your nullable Guid if it applies.
