### ISSUE TITLE
Strange behavior when doing a Select (client side) after results are loaded

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [dotnet/efcore#33666]
Consider the below code,

```C#
// let's say Project is a navigation property (another table)
var query = context.Student.Where(x => x.id == 123).Include(x => x.Project);
var data = await query.ToListAsync()

// if i inspect "data" at this point. I do see `Student` as well as the details of the `Project` collection loaded. 
// however, the next line fails when accessing `.Project`. It shows null. 
var filteredModelData = data.Select(x => x.Project.Any(y => y.Active == true)); // Error right here. `.Project` is coming as null
```

Can someone please explain this behavior? When I have eagerly pulled down that data via `ToListAsync`, and I do see the data when inspecting, the moment i do `.Select`, the navigation property is `NULL` but the top level primitive properties of `Student` are still present. 

Im wondering if im doing something wrong or is there an explanation for this behavior. 

Any help would be much appreciated. 

EF Core version: 5
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows
IDE: Visual Studio 2022

**Comment by roji** [comment]
@EmmanuelPonnudurai there's not enough up there for us to help you. In general, the moment you do ToListAsync(), EF is no longer responsible or involved - you've executed the query and loaded the data to the client (.NET), and from here on you're just doing .NET operations on in-memory objects.

Double-check whether your student's project actually is null or not - you may be looking at the wrong object. Otherwise, if you think EF is somehow misbehaving, please put together a minimal, runnable code sample which shows the problem occuring.

**Comment by EmmanuelPonnudurai** [comment]
@roji My bad. Pls disregard. I found out the issue and it's my mistake. 

There was a method down the lane which was removing the navigation property. The fact that I did a `.Select` resulted in it being evaluated _after_ the property was removed. 

False alarm. Closing the issue. Thanks you.
