### ISSUE TITLE
Testing: How is AssertQuery supposed to work

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#33742]
I'm troubleshooting some tests where it seems like I'm having problems with this custom driver and how it pulls double/decimal precision from the db. I've got some of the northwind include tests reporting
```
Expected: 0.0500000007
Actual:   0
```

When I drill into the method and what its doing, it seems like it takes the linq query, and runs/evaluates it two different ways... and then compares the results.  

This is one of the overloads I'm calling when I run into this. `expectedQuery`, and `actualQuery` just get set as the same value.
```
public Task AssertQuery<TResult>(
    bool async,
    Func<ISetSource, IQueryable<TResult>> query,
    Func<TResult, object> elementSorter = null,
    Action<TResult, TResult> elementAsserter = null,
    bool assertOrder = false,
    int entryCount = 0,
    [CallerMemberName] string testMethodName = null)
    where TResult : class
    => AssertQuery(async, query, query, elementSorter, elementAsserter, assertOrder, entryCount, testMethodName);
```

I've got query logging enabled, and the exact same query gets spat out twice, but somehow run into these cases where it looks like it gets the actual precision of a double, and in the fetched set, no precision... not even rounding (just truncated precision).

**Comment by ronnyek** [comment]
Is it basically generating the query, executing it as results into a DataTable or something, and then comparing that data to fetched entities?

**Comment by roji** [comment]
@ronnyek tests with AssertQuery execute the same LINQ query twice - once against the database (via your provider), and once against an in-memory (Enumerable) collection; it then compares the results, and throws if they do not match. This tests that your provider returns the same results as the query would have returned, had it been executed in-memory.

In the above, it seems that the in-memory evaluation returned 0.0500000007, but your provider returned 0; of course I can't say what that is without knowing what your provider is doing, what test is being discussed, etc.

**Comment by ronnyek** [comment]
Interesting, that makes a lot more sense. Where is the initialization of that in memory provider source done (specifically where it gets populated with the "expected" values)?

**Comment by roji** [comment]
When a test suite extends QueryTestBase, it gets access to the AssertQuery machinery, and must implement various requirements to enable that. One of these requirements is to provide the data contents, which get both seeded into the database (for the "actual" results when the query is executed against the database), and used to run the in-memory queries (for the "actual" results, aka the "oracle").

In the Northwind case, you can take a look at NorthwindData.cs in the EF repo - it contains the in-memory .NET data for the Northwind model. The Northwind tests are a bit special in that this data doesn't seeded, but instead we use a SQL script instead, so for Northwind specifically the database and in-memory data sets are disjoint; but for all other test suites, the in-memory data also gets used to seed the database.

BTW as a general recommendation when developing a provider: it's probably worth setting things up so that you directly reference the EF projects as `<ProjectReference>` from your provider projects and solution, so that you can easily debug into EF code and even tweak it to see what happens. I do this regularly when debugging e.g. the PG provider.

I'll go ahead and close this issue as the question seems to be answered, but don't hesitate to post more questions here if needed.

**Comment by ronnyek** [comment]
Thanks again @roji!
