### ISSUE TITLE
New Provider - Why is Avg aggregate projection truncating precision?

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#33807]
Working again on custom provider and finding tests that run avg aggregations. The tests themselves fail because its taking the resulting double is what the database returns, except without precision.

This test: `Average_on_nav_subquery_in_projection` has a query that looks like:
``` cs
s => ss.Set<Customer>()
                    .OrderBy(c => c.CustomerID)
                    .Select(c => new { Ave = (double?)c.Orders.Average(o => o.OrderID) });
```

I can look at what `GetSchemaTable` call returns from the ado driver... and it looks like it returns `decimal` for type for the avg column.  To  me it would make sense that casting to double from decimal (which technically has more precision) would result in some precision loss, but it seems like its truncating all precision, like it was casting to int.

Executing the db query against the db engine itself results in a value like:
`10805.833333333332`
but by the time I get the list of values from the above query, I get:
`10805` (no rounding or anything)

So I guess I'm unsure how to progress. I'd like to pass as many of the specification tests as possible. Is this likely a type mapping problem? Should I be overriding this test and providing an alternative implementation?

As a side note, I've got most tests for decimal, float, etc... and they appear to be working... If I change the query to be `(decimal?)c.Orders.Average` it comes back with some precision (though potentially not the correct precision because of loss of precision)

### Include provider and version information
EF Core version:
Database provider: (e.g. Custom)
Target framework: (.NET 6.0)
Operating system: Windows 11
IDE: (e.g. Visual Studio 2022 17.4)

**Comment by cincuranet** [comment]
The `double` is being used there because that's what the `Average` function returns `double Average<TSource>(this IEnumerable<TSource> source, Func<TSource, int> selector)` (given the `OrderId` is `int`). 

And i.e. for SQL Server we explicitly cast to `float` to get correct result for `AVG` function.

https://github.com/dotnet/efcore/blob/de2e17ee3cf04cd5ec376d00f684b1907c8b0c1c/test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs#L2859

I would first validate that the translation is correct from the types POV (i.e., as you mentioned, part of that is also the type mappings) and then the processing from the driver. It is absolutely possible that your database has different rules around returns types for aggregate functions and in that case I would do what's best (or expected) for user and adjust test(s) accordingly. It's fine that some tests are changed (or even skipped, if the database has very different rules).
