### ISSUE TITLE
Issue in documentation

### ISSUE THREAD

**Issue by Adriann-07** [dotnet/efcore#33818]
As far as I know and experienced, it is not possible to add two .ThenInclude(x => x.<Model>) after each other. In the documentation this is stated but doesn't work in VS.

**Comment by maumar** [comment]
Chaining multiple ThenIncludes should work - we have tests in our repo that do that and they work fine in VS. Which version of VS are you using? There used be a problem with compiler not correctly reasoning about ThenIncludes some time ago (https://github.com/dotnet/roslyn/issues/8237) , but those issues should have been fixed by now. Can you provide a repro code that is causing you problems?
