### ISSUE TITLE
Is it possible to add arbitrary queries to run within the same transaction as SaveChanges?

### ISSUE THREAD

**Issue by tyler-boyd** [dotnet/efcore#33845]
## Ask a question

I apologize if this question sounds dumb...consider I have a table `orders` which has an `updated_at` field, as well as a `[ConcurrencyCheck] public int Version` field for optimistic concurrency.

The app also has a few other endpoints which modify an entity that is _related to_ `orders`. Whenever a related entity is modified, I want to update the related order's `updated_at` field.

The naive approach is to use a `SaveChangesInterceptor` which loads and modifies the associated order, but this has 2 problems:
1. I don't necessarily want to load the order, I just want to update its `updated_at`
2. Since the changes happen through the change tracker, the optimistic concurrency check will happen even though I don't want it  to, leading to unnecessary exceptions

The next thing I tried was to use a `SaveChangesInterceptor` which performs an `.ExecuteUpdateAsync` call instead of using the change tracker, eg. `update orders set updated_at = ? where id = ?`. This is good, but I'm not able to easily run my `ExecuteUpdateAsync` call within the same transaction/savepoint as `SaveChanges`. I was able to work around this by manually wrapping my entire operation in a transaction/savepoint, but this leads to unnecessary/redundant savepoints being created and released.

I'd like to think that my original objective here makes sense, so am I missing a better way of approaching this problem? My current implementation has extra round trips and database load for unnecessary savepoints, which I'd love to get rid of. 

### Include provider and version information

EF Core version: 8.0.3
Database provider: Npgsql
Target framework: net8

**Comment by maumar** [comment]
@roji @ajcvickers

**Comment by bevanweiss** [comment]
Have you looked at the Events available on the DBContext?  It seems that by hooking the SavingChanges you could potentially modify the state of your desired context elements
https://learn.microsoft.com/en-au/ef/core/logging-events-diagnostics/events#events-raised-by-ef-core

Alternatively you could have this as part of your C# object model.  So that whenever you do a 'set' on the properties in question, it would also update the 'updated_at' property for the related object.  The timestamping would then be 'as viewed by the application' rather than 'as viewed by the database', but this might be of negligible consequence (or even more desirable) in many situations.

You could always manually update the ChangeTracker if you needed fine grained handling of the related record updates (i.e. to ONLY set the updated_at not other fields).

In regards to ConcurrencyCheck.. the entire SaveChanges should be either committed or not.  So as long as you follow the standard EF core context usage (and don't go doing your own side operations, i.e. Interceptor miss-use), then it should be fine, and you'd just need to handle the change conflicts..

**Comment by ajcvickers** [comment]
@tyler-boyd If you want multiple operations to happen in the same transaction as `SaveChanges`, then you'll need to at least tell EF when to start using the transaction and when to commit. See [Controlling transactions](https://learn.microsoft.com/en-us/ef/core/saving/transactions#controlling-transactions). in the docs. I wouldn't call this a workaround; this is the way control of transactions is done with EF Core.

**Comment by tyler-boyd** [comment]
Thanks for the inputs!

@bevanweiss I'm specifically trying to avoid the change tracker and ConcurrencyCheck in these scenarios because they aren't necessary and only increase load on my DB and application. I am handling the DbUpdateConcurrencyExceptions and retrying, so things do work, but I am trying to avoid these unnecessary checks and retries in the first place

@ajcvickers this also worked, but since EF core creates a savepoint if a transaction already exists, I haven't managed to find a way to avoid 2 extra round-trips (creating a savepoint and releasing it) that really aren't necessary in my case.

It sounds like at the moment there's probably no way around this, and that's fine, a couple extra round trips isn't a big deal. But perhaps it could be considered in the future to add a bit more flexibility into the SaveChanges transaction behaviour 🙂 

I'll close this issue for now, thanks again for your comments!

**Comment by roji** [comment]
@tyler-boyd with Npgsql, creating a new savepoint doesn't do a roundtrip - it just sets some state internally, and the savepoint creation goes out prepended to the next actual execution (the same thing happens when starting a transaction). If you're interesting in these lower-level performance things, I suggest taking a look with Wireshark to see when exactly a roundtrip occurs.
