### ISSUE TITLE
Columns with HasMaxLength is not respected when SQL is generated

### ISSUE THREAD

**Issue by Tasteful** [dotnet/efcore#3390]
When trying to add record to database that contains field that has HasMaxLength attributes will throw exceptions.

```
An error occurred while updating the entries. See the inner exception for details.
String or binary data would be truncated.
The statement has been terminated.

Result StackTrace:  
at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection, ILogger logger)
   at Microsoft.Data.Entity.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.Data.Entity.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

The generated SQL command is the following where we can see that the first 3 parameters (p2-p4) not respect the `HasMaxLength` attribute.

```
exec sp_executesql N'SET NOCOUNT OFF;
INSERT INTO [Products].[ProductFieldData] ([OwnerId], [Id], [Culture], [DateTimeValue], [DoubleValue], [GuidValue], [IndexedTextValue], [IntValue], [JsonData], [TextValue])
VALUES (@p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11);
SELECT @@ROWCOUNT;
',N'@p2 nvarchar(4000),@p3 nvarchar(4000),@p4 nvarchar(4000),@p5 datetime2(7),@p6 nvarchar(4000),@p7 nvarchar(4000),@p8 nvarchar(max) ,@p9 bigint,@p10 nvarchar(max) ,@p11 nvarchar(4000)',
@p2=N'5a5df787215d453da9d79b0e7300ad1a',
@p3=N'myfield:',
@p4=N'4dbc58b1-0b93-4054-943f-654e07995d2c',
@p5=NULL,
@p6=NULL,
@p7=NULL,
@p8=NULL,
@p9=NULL,
@p10=NULL,
@p11=N'test'
go
```

Model

```
    public class ProductFieldDataDto
    {
        public string OwnerId { get; set; }
        public string JsonData { get; set; }
        public string Culture { get; set; }
        public object BinaryValue { get; set; }
        public DateTime? DateTimeValue { get; set; }
        public double? DoubleValue { get; set; }
        public Guid? GuidValue { get; set; }
        public string Id { get; set; }
        public string IndexedTextValue { get; set; }
        public long? IntValue { get; set; }
        public string TextValue { get; set; }
    }
```

And mapping in the DbContext

```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProductFieldDataDto>(builder =>
            {
                builder.ToTable("ProductFieldData", "Products");
                builder.HasKey(p => new {p.OwnerId, p.Id, p.Culture});

                builder.Property(p => p.OwnerId).HasMaxLength(100);

                builder.Property(p => p.Id).HasMaxLength(100);
                builder.Property(p => p.Culture).HasMaxLength(10);

                builder.Property(p => p.IndexedTextValue).HasMaxLength(250);

                builder.Ignore(p => p.BinaryValue);

                builder.Index(p => p.Id).Unique();
                builder.Index(p => p.OwnerId);
                builder.Index(p => p.IndexedTextValue);
            });
        }
```

The script that was generated to create the table will respect the length limit

```
    CREATE TABLE [Products].[ProductFieldData] (
        [OwnerId] nvarchar(100) NOT NULL,
        [Id] nvarchar(100) NOT NULL,
        [Culture] nvarchar(10) NOT NULL,
        [DateTimeValue] datetime2,
        [DoubleValue] float,
        [GuidValue] uniqueidentifier,
        [IndexedTextValue] nvarchar(250),
        [IntValue] bigint,
        [JsonData] nvarchar(max),
        [TextValue] nvarchar(max),
        CONSTRAINT [PK_ProductFieldDataDto] PRIMARY KEY ([OwnerId], [Id], [Culture])
```

Tested with 7.0.0-beta8-15930

**Comment by rowanmiller** [comment]
This is by-design, `Culture` is setup with a max length of `10` (`nvarchar(10)`) but you are trying to insert the value `4dbc58b1-0b93-4054-943f-654e07995d2c` (which would result in truncation). EF doesn't do any validation of this, since it would just be duplicating the check that is also going to be performed by the database.

BTW you may notice that EF is generating parameters with a `nvarchar(4000)` data type, this is also by design as it helps with plan cache performance.

**Comment by Tasteful** [comment]
In my test the `Culture` was set to `null` and because of that `Culture` is part of the composite primary key the value for `Culture` was generated by EF. I'd did not see that when I inspected the SQL. Maybe it should be better to not generate values on the composite primary keys, in that case will the error message be more clear and says that `Culture` not can be `null`.

**Comment by rowanmiller** [comment]
Ah, reopening as I believe we should not be generating values for composite keys (e.g. https://github.com/aspnet/EntityFramework/issues/1126). @ajcvickers @divega do you agree?

**Comment by divega** [comment]
I agree. I thought that is what we had decided anyway. @smitpatel @AndriySvyryd do you know if that is supposed to be implemented?

**Comment by AndriySvyryd** [comment]
@divega Currently we should not generate values for composite primary keys by default. We should investigate why it's still happening in this case.

**Comment by smitpatel** [comment]
I tried running a test app with composite PK. We mark `RequiresValueGenerator` as true for all the properties in composite PK (`KeyConvention`). When saving changes we throw an exception - ` System.InvalidOperationException: The property 'Id' on entity type 'Blog' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly or 
ensure that the database is configured to generate values for this property.`
And regardless of exception, temporary values are stored in database. And for string/Guid properties we are generating some new value as temporary values and sending it to database.

The above exception came due to database constraint of length and it threw before the exception of temporary value.

**Comment by rowanmiller** [comment]
It feel like we have an issue in the how the pieces interact here. If the property is not setup to be generated (because it's part of a composite key) and we successfully insert the assigned value it seems we shouldn't throw trying accept changes. Maybe this has changed already though with @ajcvickers work to remove sentinel values?

**Comment by ajcvickers** [comment]
There are several things going on here. 
- We are generating temporary values in this case because currently we do that for all keys. This enables graph tracking to happen with any entity order--dependents can be found in the graph before principals and they can still be added without key violations. However, we are changing this such that if the property is not setup for "real" value generation, then it will never get a value generated, meaning that in some cases if key values are not set, then you will get either bad data inserted or a constraint exception--depending on whether or not multiple entities have default key values.
- Currently, when we try to save entities with temp values, the check for this doesn't happen until after the update pipeline has run, meaning the temp values are saved and then an exception is thrown. (This is because the update pipeline overwrites most temp values and we check for any that are not overwritten at the end.) This is a bug--we should figure out which values will remain temporary at the end before having the update pipeline run, and then throw early.
- Because the temp values don't fit in the columns, saving them causes an exception.

Unwinding this, we have:
- The exception from saving temp values will go away, because we will do the temp values check before saving.
- Even having temp values will go away, because we will not generate temporary keys for these properties
- An exception will be thrown indicating that the item has a null primary key,

**Comment by rowanmiller** [comment]
Per @ajcvickers analysis this situation will be pretty hard to get into with his recent set of changes, but we did open up https://github.com/aspnet/EntityFramework/issues/3425 to make sure we throw before saving if you ever do get into it.
