### ISSUE TITLE
Nested transactions throw an exception

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/efcore#33954]
I have a class that imports a waybill into our database. Since multiple tables are updated, a transaction is used.

    using var trans = await DbContext.Database.BeginTransactionAsync();

    // Import data...

    await trans.CommitAsync();

Now, I've been asked to modify the class so that the waybill is split up into multiple waybills, and then call the original import function to import each of those waybills.

It's important that I either import all of the multiple waybills, or I don't import any of them. And so I also tried wrapping the code that calls the import function for each waybill in another transaction.

However, this creates a nested transaction, which throws an exception.

> System.InvalidOperationException: 'The connection is already in a transaction and cannot participate in another transaction.'

I thought nested transactions were a thing. Is this considered bad practice? Is there a way to make this work? Or is there a better approach?

*Note 1: I know that one option is to remove the transactions from the import function, so I just have the one "outer" transaction. However, I still need the option to run it without splitting up the waybill, as it worked originally. So I really need to leave the import function alone.*

*Note 2: It doesn't matter to me if the database doesn't treat this as an actual nested transaction. I just want to be able to call `BeginTransaction()` twice, and have the database not update until I then call `Commit()` twice.*

I'm using Microsoft.EntityFrameworkCore.SqlServer version 8.0.2.

**Comment by roji** [comment]
> It doesn't matter to me if the database doesn't treat this as an actual nested transaction. I just want to be able to call BeginTransaction() twice, and have the database not update until I then call Commit() twice.

Can you provide a bit more context? Like more databases, SQL Server indeed doesn't support actual nested transactions; so why is it important for you call BeginTransaction() twice?

**Comment by SoftCircuits** [comment]
@roji It isn't so much that I want to call `BeginTransaction()` twice. It's that I want to call a method multiple times, and that method calls `BeginTransaction()`.

But I want my multiple calls to this method to all complete, or none of them complete. So I want to wrap my code in a transaction. But then when I call this method, it leads to a nested transaction.

Ultimately, my goal is to call a method that uses transactions multiple times. But if there's an error, I don't want any of them to complete.

**Comment by SoftCircuits** [comment]
@roji Thanks. FWIW, I think it would be advantageous if `BeginTransaction()` could be nested using a counter. Calling it multiple times would require calling `Commit()` multiple times before the changes were committed. I think EF used to do this at some point in the past--not sure now. It seems like this would require very little new functionality, but would allow code like mine to run without issue.

**Comment by roji** [comment]
@SoftCircuits stuff like DbContext.Database.BeginTransaction() generally tries to be a thin wrapper over the corresponding ADO.NET method. Put another way, the problem you're running into doesn't seem specific to EF in any way - someone using ADO.NET directly (or Dapper) could run into the exact same problem (wanting to call, within a transaction, a function that starts a transaction internally) - so it seems problematic to "fix" this at the EF level.

Ultimately I still think the problem here is on the user side. In other words, if a function somewhere does BeginTransaction() and then Commit(), it's written with the assumption that changes will actually be committed when Commit() is called. But here you're requesting to change that, making it so that Commit() is a no-op if the transaction is "nested" (nested in the .NET sense, not in the database sense). It feels more correct for the function to be changed instead, to accept a flag determining whether it should use a transaction at all. I get that this can be hard in an existing codebase and it would be nicer if EF just magically "made it work", but I'm not convinced that's right at this point.

(and just for completeness, as I mentioned above, TransactionScope was explicitly designed to address this sort of scenario via ambient state)

**Comment by roji** [comment]
We discussed this in design, and decided this is not something we want to implement in EF; specifically, the fact that this would make Commit() sometimes not commit - and in ways which are non-obvious (impossible to tell from the immediate context) - seems quite risky.
