### ISSUE TITLE
SQL Server: what is the maximum supported compatibility level for EF6 (Azure SQL)?

### ISSUE THREAD

**Issue by Saibamen** [dotnet/efcore#33980]
I'm in the process of migrating old .NET Framework & EF6 WebAPI to .NET 8 and EF8.

Yesterday because of [this breaking change](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/breaking-changes#contains-in-linq-queries-may-stop-working-on-older-sql-server-versions), I changed `compatibility_level` to `130` for our EF6 (Azure SQL) databases.

My question is:
What is the recommended `compatibility_level` for EF6 and for EF8?

We want to have the same database working for both EF6 and EF8 because of migration testing.

**Comment by roji** [comment]
There is no recommended compability level really as far as EF is concerned. Certain features - like JSON querying - require newer compatibility levels, and EF will generally assume the newest compatibility level and make use of those features. But you can always tell EF that it's targeting a lower compatibility level (in UseSqlServer()), at which point it will refrain from using those features. Of course, that would mean that some EF capabilities would be limited (e.g. no full JSON querying capabilities).

At the same time, I'm not aware why you **wouldn't** use a newer compatibility level, just because you need to be EF6-compatible; in itself, raising the compatibility level shouldn't cause EF6 applications to break. Are you encountering something like this?

**Comment by Saibamen** [comment]
Thank you, Shay, for quick response!

>Are you encountering something like this?

I have not updated to `160` yet. I will do this today for our Dev and Staging and let you know tomorrow.

**Comment by roji** [comment]
@Saibamen I'll go ahead and close this for now as there's nothing actionable on our side, but definitely post back here with your findings (or any additional questions/discussion).

**Comment by Saibamen** [comment]
No problems noticed since yesterday
