### ISSUE TITLE
Why does FindAsync see an entry that was deleted by ExecuteDeleteAsync?

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/efcore#33986]
## Ask a question

Why does FindAsync see an entry that was deleted by ExecuteDeleteAsync?

Use triple-tick code fences for any posted code. For example:

```C#
            string _id = Guid.NewGuid().ToString();
            dbcontext.Roles.Add(new() { Id = _id, Name = "Test" });
            dbcontext.SaveChanges();
            await dbcontext.Roles.ExecuteDeleteAsync();
            var tmp1 = await dbcontext.Roles.FindAsync(_id);
```

![image](https://github.com/dotnet/efcore/assets/25795145/3461a87e-1ce6-4910-bf6e-7fe06e662a7b)

**Comment by ajcvickers** [comment]
@EvgenyPrikhodko Because `Find` looks in the context cache and returns that entry. `ExecuteUpdate` and `ExecuteDelete` operate outside of change tracking. See [ExecuteUpdate and ExecuteDelete](https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete) for more info.

**Comment by EvgenyPrikhodko** [comment]
> @EvgenyPrikhodko Because `Find` looks in the context cache and returns that entry. `ExecuteUpdate` and `ExecuteDelete` operate outside of change tracking. See [ExecuteUpdate and ExecuteDelete](https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete) for more info.


Thank you for your reply, do you think this behavior is correct? In what situation is there such a need for such a result?  Or are we saying that Find is not recommended for use?

**Comment by ajcvickers** [comment]
@EvgenyPrikhodko Yes, this is by-design. Best practice would be to not combine `ExecuteUpdate` or `ExecuteDelete` in the same unit-of-work as doing change tracking changes. See [Change Tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/) for more info.

**Comment by EvgenyPrikhodko** [comment]
> @EvgenyPrikhodko Yes, this is by-design. Best practice would be to not combine `ExecuteUpdate` or `ExecuteDelete` in the same unit-of-work as doing change tracking changes. See [Change Tracking](https://learn.microsoft.com/en-us/ef/core/change-tracking/) for more info.


Thanks for your answer, in which scenarios is it necessary to use Execute Delete without ChangeTracker?

**Comment by EvgenyPrikhodko** [comment]
> @EvgenyPrikhodko Because `Find` looks in the context cache and returns that entry. `ExecuteUpdate` and `ExecuteDelete` operate outside of change tracking. See [ExecuteUpdate and ExecuteDelete](https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete) for more info.




I'm trying to figure out what EF is using Find for now, are there any advantages?

**Comment by roji** [comment]
Simply put, ExecuteDelete/Update bypass the change tracker and are completely oblivious to it. Keep in mind that regardless of ExecuteDelete/Update, someone else may delete a row from the database after you've loaded it with your DbContext; in that scenario, doing FindAsync will return the locally-cached entry in exactly the same way.

To avoid confusion, as @ajcvickers wrote above you can simply avoid using both ExecuteUpdate/Delete and change-tracking queries with the same context. Otherwise, you can mix them, but need to be aware that changes done via ExecuteUpdate/Delete are not reflected in the change tracker, and so FindAsync may return out-of-date data (again, as could happen in any case with external modifications.
