### ISSUE TITLE
Introduction of onDelete with Foreign Key's breaks migrations

### ISSUE THREAD

**Issue by jruckert** [dotnet/efcore#3400]
Hi,

 I've just tried generating Migrations using the standard command lines of the latest RC1 - 15945, and found with the introduction of the new property (we generated a couple of days ago without any issues, but this property was not present)

onDelete: ReferentialAction.Restrict

when i try to apply the migrations to the database

Introducing FOREIGN KEY constraint 'FK_RepresentingMinistry_Ministry_Representin
gMinistryId' on table 'RepresentingMinistry' may cause cycles or multiple cascad
e paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOR
EIGN KEY constraints.
Could not create constraint or index. See previous errors.

Any ideas?

Cheers,
Jonathan

**Comment by jruckert** [comment]
Seems like the default behavior has changed to be Cascade, not Restrict.

**Comment by rowanmiller** [comment]
This has recently changed to be in-line with the EF6 behavior - cascade delete is enabled for required relationships. We think this is the most expected behavior, but it is unfortunate that SQL Server is so aggressive in its detection of cycles (at the schema level rather than just failing when you attempt to delete cyclic data).

You ca switch off one of the cascades to break the cycle as follows:

```c#
modelBuilder.Entity<RepresentingMinistry >()
    .HasOne(r => r.Ministry)
    .WithMany(m => m.RepresentingMinistries)
    .OnDelete(DeleteBehavior.Restrict)
```
