### ISSUE TITLE
Remove Migrate lock timeout

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#34196]
Also, log when `Migrate` is waiting for a lock

**Comment by roji** [comment]
A thought I had since our discussion on this: it may still make sense to have a lock timeout, but implemented client-side - exactly like cancellation; in other words, we'd just check the timeout/cancellation token from time to time, in between migrations or whatever. Since the timeout and lock would be fully controlled by the .NET client, we don't have the problem we discussed where the lock expires autonomously while we're still applying migrations. This would at least allow termination in the case of a network partition, and if users want it, maybe also terminate long migration batches (whether we want it on by default is another question).

**Comment by AndriySvyryd** [comment]
We have a cancellation token on MigrateAsync. Are you suggesting that we add it to Migrate as well? In case of a network partition it would still not stop execution before some other exception is thrown

**Comment by roji** [comment]
@AndriySvyryd good point. I guess this is more about making sure we have a command-line mechanism for setting client-side timeout when applying migrations (e.g. via bundle). Having that set CommandTimeout (as opposed to anything via the cancellation token) is probably sufficient - and this would take care of sync I/O scenarios as well.

**Comment by AndriySvyryd** [comment]
The command-line tools use the same infrastructure, so the `CommandTimeout` DbContext option would be used.

**Comment by roji** [comment]
OK, sounds good then, thanks.
