### ISSUE TITLE
New Provider: Specification tests Projection with datetime subtraction

### ISSUE THREAD

**Issue by ronnyek** [dotnet/efcore#34296]
Plugging away on new provider still, and running into a problem that it seems like we should be able to handle...

I am running into a problem with implementation of a test `NorthwindSelectQueryTestBase.Projection_containing_DateTime_subtraction`

Test is basically as simple as this
``` cs
return AssertQueryScalar(
    async,
    ss => ss.Set<Order>().Where(o => o.OrderID < 10300)
        .Select(o => o.OrderDate.Value - new DateTime(1997, 1, 1)));
```

And I think that should essentially produce something along the lines of: (this engine has no concept of a timespan, but datediff could be used to bring back ms or seconds or whatever)
``` sql
SELECT
DateDiff(MILLISECOND, o."OrderDate", <otherdate>)
FROM "Orders" o
where o.OrderId < 10300
```
And presumably somewhere just know that when executing a date diff, the result will be a long, and we should be able to turn that into timespan.

Right now I get an exception:
``` cs
System.InvalidOperationException
No coercion operator is defined between types 'System.DateTime' and 'System.Nullable`1[System.TimeSpan]'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.CreateGetValueExpression(ParameterExpression dbDataReader, Int32 index, Boolean nullable, RelationalTypeMapping typeMapping, Type type, IPropertyBase property)
```

As a side note, I've looked at implementations of SqlLite and SqlServer implementations, and they both seem to have the test there, and presumably both pass, but I'm not sure if this is because I dont have a type mapping for timespan in the `TypeMappingSource` (have properties that are timespan somehow apparently assume value should come back from db as a long, and use `TimeSpan.FromMilliseconds()` or something)

Anyone have any ideas or input here? I understand what its saying (I think). I'm not exactly sure why its wanting to coerce a timespan from a datetime, and I'm not sure if I should try to make a timespan mapping that essentially creates timespan from milliseconds, or if I should just not try to accommodate this.

EF Core version:
Database provider: custom
Target framework: (e.g. .NET 8.0)
Operating system:
IDE: Visual Studio 2022 17.4

**Comment by roji** [comment]
It would seem like you're attempting to implement DateTime subtraction in your custom provider, but you probably have a bug in that implementation. The translation node returned as the translation must have type TimeSpan, since that's what DateTime subtraction returns in .NET.

Note that the SQL Server and Sqlite providers don't implement DateTime subtraction at all, so the subtraction gets evaluated on the client-side (this is a top-level Select). The PG provider does translate this - PG itself supports direct subtraction of timestamps in SQL, returning a PG `interval` which is mapped back to TimeSpan, so everything aligns well. Either your provider has a similar thing, or it doesn't and can't translate DateTime subtraction. If you provide more context I may be able to help further.

**Comment by ChrisJollyAU** [comment]
I'll chime in since I have a very similar error (but in a different place - more on that later).

First of all, you're going to want a type mapping for TimeSpan. As part of that you are going to want to figure out what data type your database supports that is best to use to save the TimeSpan to.

Next, as @roji says, you're going to need to check how you're setting up your translation of the Subtract.. The return type and type mapping need to be correct for the TimeSpan.

You can see in SqlServer at https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs#L99 in the `VisitBinary` function that it returns a `.NotTranslatedExpression` for the expression. In this case, by default given it is a top-level select you get a client-side evaulation. I do the same with EFCore.Jet.

It would help to have a code snippet so we can try help.

Now we come to the next issue you will have - reading the value from the returned dataset. I don't know what technology you are using to actually connect to the database, send the query and read the returning results.

Here's the scenario, lets say all the above is working and the query is executed. When reading the resulting dataset, as your database doesn't have any timespan, its data type is going to be one of its native types (probably a DateTime or a long depending on what works best for you). Now if EFCore has a class with properties that directly coincide with the table in the database, efcore knows to specifically request the type from the class (e.g. TimeSpan). Your data reader then knows that TimeSpan is requested and knows to convert whatever value is in that column to a TimeSpan. The problem comes in is if it is a calculated column (e.g in test `Select_datetime_TimeOfDay_component`), for that column when it asks for the value of that column it doesn't ask for any specific data type. You just have a DateTime or a long database native type and no knowledge of whether the type that efcore really wants. It gets the returned value and then later tries to cast it to the type it needs (TimeSpan). At this point you are likely to get an `unable to cast` error.

I've still got to solve this problem for EFCore.Jet

**Comment by ronnyek** [comment]
I was pulled away from this for some time. So basically this db engine has no native timespan equivalent. It supports datediff, and date subtraction could be translated to return ms representing a timespan, and timespan could be parsed from that total ms, but that's all just theory, and not sure how easy that could be translated over.

I've overridden `TranslatingExpressionVisitor` to handle date stuff in `VisitBinary` such that it returns `NotTranslatedExpression`. With or without that change I still get the same error in `UnaryExpression.cs` suggesting it cant find a user defined coercion between `DateTime` and `Nullable<TimeSpan>`

I'm just unsure what all is happening in this query to understand what's missing, or maybe if there is something I've got in code that I shouldn't. I know it for some reason is trying to get a datetime from a Timespan? but I'm honestly not sure what its trying to do to get that far.

**Comment by roji** [comment]
> So basically this db engine has no native timespan equivalent. It supports datediff, and date subtraction could be translated to return ms representing a timespan, and timespan could be parsed from that total ms, but that's all just theory, and not sure how easy that could be translated over.

If your database has no native TimeSpan equivalent (like SQL Server), then in principle you cannot support **translation** of date/time subtraction; since the subtraction needs to return a a TimeSpan in .NET, projecting out that subtraction would mean that EF needs to read out a TimeSpan from the DbDataReader of your ADO.NET, which simply isn't supported.

The test above specifically performs DateTIme subtraction in the final select, which means that the subtraction **can** be client-evaluated; this is exactly what happens in SQL Server - if you look at the test implementation for SQL Server, you can see the following SQL:

```sql
SELECT [o].[OrderDate]
FROM [Orders] AS [o]
WHERE [o].[OrderID] < 10300
```

Note that there's no trace of any subtraction here - that happens client-side in .NET (the PostgreSQl implementation would show the subtraction in SQL, since that database does support a TimeSpan equivalent (interval) and timestamp subtraction).

So it seems like your provider is somehow attempting to translate the subtraction although it shouldn't - I'd debug this test to see where that's happening.

I'm going to go ahead and close this as there's nothing actionable on the EF side, but if you need more guidance feel free to continue posting here.

**Comment by ronnyek** [comment]
For anyone running into anything similar to this, I was very confused as to why it was trying to do a convert. This was as simple to fix as simply making sure my type mapping source had correct mappings, and where there were unsupported types, dont be afraid to return null for those TypeMappings. Also there was a problem where the underlying ado database component was mapping native db type to the wrong .net type.

I'm good to go, and always @roji and others.. .thanks so much for assistance. 

I find it someone difficult to understand what is happening under the scenes in this case. I kind of wish there was some way to trace an expression tree evaluation through the typical steps... to better understand what the flow is since it seems undocumented.

**Comment by roji** [comment]
> I find it someone difficult to understand what is happening under the scenes in this case. I kind of wish there was some way to trace an expression tree evaluation through the typical steps... to better understand what the flow is since it seems undocumented.

What I usually do here is set a breakpoint in QueryCompilationContext ([here](https://github.com/dotnet/efcore/blob/main/src/EFCore/Query/QueryCompilationContext.cs#L256)) - that's a very early point in the query pipeline, where the tree really resembles the raw input that EF sees (there's one step before this but it's usually not important). At that point you can step in/over the various processing visitors, and see what happens with each one.

**Comment by ChrisJollyAU** [comment]
Although as a third party provider you don't necessarily have it within your solution. You can manage to open it and set a break point although I will say I often end up trying to look at a variable and VS just shows that the value is unavailable due to it being optimized out or something like that.

My favourite points for queries are normally the start of the `Process` in the relevant `QueryTranslationPostprocessor`, the `Optimize` in the `ParameterBasedSqlProcessor`, `VisitSelect` in the `QuerySqlGenerator`. And then our own `JetCommand` where we actually execute the `DbCommand` so I can see the final command and its parameters. Thereafter you just work towards whichever translation file you need

**Comment by roji** [comment]
Yeah, for provider writers, i highly recommend having a branch where the relevant EF projects are referenced in your solutions (and via `<ProjectReferences>`); this allows you to debug into EF code effortlessly. I do this routinely when investigating issues on the PostgreSQL providers, etc.
