### ISSUE TITLE
Have you considered supporting DuckDB?

### ISSUE THREAD

**Issue by netnr** [dotnet/efcore#34336]
DuckDB v1 has been released for a while now, and it has been announced that the storage format is stable and compatible.

Because DuckDB and SQLite are both embedded databases, they have many similarities, and DuckDB is faster, especially for analytical queries.

Related links
https://github.com/duckdb/duckdb
https://github.com/Giorgi/DuckDB.NET
https://github.com/Giorgi/DuckDB.NET/discussions/109

**Comment by roji** [comment]
@netnr the team doesn't generally implement new providers beyond the ones it already owns (SQL Server, SQLite, Cosmos) - we're a team with limited resources, and it's much better for providers to be owned and maintained by community members or the database vendors. But we're very happy to support and help out external provider writers and do so regularly.

Specifically re DuckDB, SQLite is still - by far - the most popular embedded database in the world, as far as I'm aware, which is another reason why it's important for it to be supported etc.

**Comment by skuirrels** [comment]
Adding another one to the list: (MIT, on NuGet as DuckDB.EFCoreProvider).
https://github.com/skuirrels/DuckDB.EFCoreProvider 

Main difference from the read-only options above is that it's a full read/write provider — LINQ and SaveChanges both work, plus migrations, transactions, optimistic concurrency, and scaffolding. It targets EF Core 10 / .NET 10.

A few things that were the reason I built it rather than using what already existed:

- Appender-backed BulkInsert and primary-key Upsert, plus opt-in insert/update/delete batching in SaveChanges
- Querying Parquet/CSV/JSON directly, and typed Parquet export
- A DuckLake profile (UseDuckLake(...)) with tracked writes, transactions, and MERGE upsert
- Tiered storage — keep recent rows in the .duckdb file, archive older ones to hive-partitioned Parquet (local or S3/GCS/Azure), and uniion query across both with LINQ

Worth being clear about scope: DuckDB is single-writer and embedded, so this is aimed at analytics, reporting, and embedded/edge stores — it's not a drop-in for a high-concurrency OLTP database. Happy to answer questions if anyone tries it.
