### ISSUE TITLE
How to handle "The entry point exited without ever building an IHost"

### ISSUE THREAD

**Issue by lonix1** [dotnet/efcore#34715]
I have a console project which manages my EF migrations (amongst other things). For simplicity, it doesn't use an `IHost`.

For years, whenever running that app, it shows a warning:
> An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: The entry point exited without ever building an IHost.

Everything works regardless of the warning. I've simply ignored it. It's annoying though, and every once in a while I forget what it's referring to and waste time trying to diagnose the non-issue. This has come up many times in many variations on StackOverflow, without any real solution.

Now, on a whim, I added this hack to the app's `Main` method:
```cs
using var host = Host.CreateDefaultBuilder(args).Build();
```

It does nothing, but it silences the warning!

Can someone please give us official guidance about the nature of this warning, and what is the recommended way to address it? (There is my hack above, but... it's a hack.)

**Comment by AndriySvyryd** [comment]
Basically, EF is just prodding the app in case it does use an `IHost` that contains configuration for the context. It probably should have been a debug-level message instead of a warning, but that logic doesn't have a way to specify the logging level.

Starting with EF 9.0 another workaround is to implement [`IDesignTimeDbContextFactory`](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-a-design-time-factory) in your app. Then EF won't try to look for an `IHost`
