### ISSUE TITLE
Support ExecuteDelete and ExecuetUpdate for sqllite

### ISSUE THREAD

**Issue by mahdiyar021** [dotnet/efcore#34741]
Unhandled exception rendering component: The LINQ expression 'DbSet<UserClaim>()
          .ExecuteDelete()' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to

**Comment by roji** [comment]
ExecuteDelete and ExecuteUpdate are supported on SQLite. You're doing something specific that isn't supported, but there's no way to know what because you haven't included any details.

**Comment by mahdiyar021** [comment]
i run SQLite on WebAssembly  , that is  interesting sometime its work and sometime throw exception !! 
command is simple DbSet.ExecuteDelete(); 
i am working on it.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by mahdiyar021** [comment]
i still have that issue . may anyone give me some advice ?

**Comment by roji** [comment]
@mahdiyar021 you need to post a minimal, runnable repro, so that we can see what you're doing and what's not working - you simply haven't given us the information that's needed to understand the problem.

**Comment by GebekovAS** [comment]
EF Core 8, SQLite: My Solution

I encountered an issue where ExecuteDeleteAsync() could not be translated in EF Core 8 with SQLite. The solution that worked for me was replacing it with ExecuteSqlRawAsync().

Error code:
```csharp
return _context.Set<TEntity>().ExecuteDeleteAsync(cancellationToken);
```
Solution:
```csharp
var tableName = _context.Model.FindEntityType(typeof(TEntity))!.GetTableName();
return _context.Database.ExecuteSqlRawAsync($"DELETE FROM {tableName}", cancellationToken);
This approach directly executes a raw SQL DELETE statement, bypassing EF Core's translation limitations in SQLite.
```

**Comment by roji** [comment]
@GebekovAS ExecuteDeleteAsync works just fine on SQLite, see below for a minimal console program that works correctly. As I posted above, please post a similar, minimal console program that shows what's not working for you.

<details>
<summary>Attempted repro</summary>

```c#
await using var context = new BlogContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

await context.Set<Blog>().ExecuteDeleteAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlite("Data Source=/tmp/test.sqlite")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

</details>
