### ISSUE TITLE
Handling DbUpdateConcurrencyException inside TransactionScope

### ISSUE THREAD

**Issue by unpub777** [dotnet/efcore#34873]
I have the following code that has TransactionScope and some changes are commited with SaveChangesAsync.

```C#

public class Test
{
    public int Id { get; set; }

    public int Status { get; set; }

    [ConcurrencyCheck]
    public Guid RowVersion { get; set; }

    public List<SubTest> SubTests { get; set; }
}

public class SubTest
{
    public int Id { get; set; }

    public int TestId { get; set; }

    public int Status { get; set; }

    public Test Test { get; set; }
}
....

using var transactionScope = new TransactionScope();

await Foo(2);

transactionScope.Complete();


public async Task Foo(int statusId)
{
    var saved = false;
    while (!saved)
    {
         var test = await _context.Set<Test>()
            .Include(st => st.SubTests)
            .FirstAsync(cancellationToken);

        var subTest = test.SubTests.First();

        if (subTest.Status == statusId) //after DbUpdateConcurrencyException subTest.Status has changed to statusId(2) and we will return from the method.
            return;

        subTest.Status = statusId;

        test.RowVersion = Guid.NewGuid();
        test.Status = 3;

        try
        {
            saved = await _context.SaveChangesAsync(false, cancellationToken) > 0;
        }
        catch (DbUpdateConcurrencyException)
        {
            DetachEntries();
        }
    }
}
```

https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Update/Internal/BatchExecutor.cs#L72

As I see from the codebase SaveChangesAsync doesn't create a transaction if there is an ambient transaction and on the other hand it doesn't create a savepoint because there isn't a current transaction. In this case it looks like unexpected behavior for SaveChange when a part of commands can be applied and other no.
What is the correct way to do a rollback when we have an ambient transaction? Is it possible to do the rollback of all commands from the batch of SaveChangesAsync without doing a rollback of the outer transaction?

EF Core version:
Database provider: (Npgsql.EntityFrameworkCore.PostgreSQL)
Target framework: (.NET 6.0)

**Comment by roji** [comment]
When a TransactionScope is disposed, it automatically rolls back the transaction **unless** Complete() was called, in which case it commits. So all you have to do is write code as follows:

```c#
using (var transactionScope = new TransactionScope())
{
    // Code that does stuff in the database

    transactionScope.Complete();
}
```

... and an exception will automatically cause a rollback.

Otherwise, TransactionScope indeed doesn't support the concept of savepoints - although that doesn't really seem related to your question above. EF's use of savepoints is to allow retrying a SaveChangesAsync operation - and only that SaveChangesAsync opewration - when it's inside a larger transaction and an exception occurs. When using TransactionScope, you can still have EF retry an entire retriable block, within which you'd create the TransactionScope on each retry.

Finally, note that it's discouraged to keep a DbContext as a member (`_context`) and to clear it/detach entries - consider creating a new DbContext every time you need to use the database, and disposing it when done instead.

**Comment by roji** [comment]
> Because according code that I see SaveChangesAsync doesn't create transaction if there is an ambient transaction and if something goes wrong with one command in a batch of SaveChangesAsync, the other commands of the batch will remain in the database.

If something goes wrong within SaveChangesAsync, an exception is thrown and the entire work done within the TransactionScope should egt rolled back - no changed that were part of that TransactionScope should remain in the database.

Otherwise, as I wrote above, TransactionScope doesn't support the concept of savepoints, so it's not possible to roll back only some changes made within a TransactionScope.
