### ISSUE TITLE
EFCore 9 RC2 - Issue with translation of DbFunction when EF.Constant is used as an argument

### ISSUE THREAD

**Issue by shvmgpt116** [dotnet/efcore#34962]
## Ask a question
In EFCore 8 following is the behavior for translating DbFunctions-
During translation of provider specific `DbFunctions`, if a variable is passed as an argument inside EF.Constant then it is treated as SqlConstantExpression in the Translate method DbFunction.
For Ex:- For the following LINQ
```C#
string abcd = "abcd";
await AssertCount(
    async,
    ss => ss.Set<Order>(),
    ss => ss.Set<Order>(),
    c => EF.Functions.IsNumeric(EF.Constant(abcd)),
```

The argument[1] would be a SqlConstantExpression

![Image](https://github.com/user-attachments/assets/379cfdc8-a26b-4185-b9f0-02cd481fe4a1)

This is useful for the database specific DbFunctions where using parameters is not an options and also if the database providers would want to change the ConstantExpression value. ForEx:- is a database db function just accepts an expression/matric value instead of a string value (lets just say For Ex:- ISNUMERIC(abcd) where the argument is not a string instead it is a metric)

However in the EFCore 9 RC2 provider, below is the behavior for translating DBFunctions
During translation of provider specific `DbFunctions`, if a variable is passed as an argument inside EF.Constant then it is treated as SqlParameterExpression in the Translate method DbFunction.

For Ex:- For the same LINQ as above the argument[1] would be a SqlParameterExpression.
![Image](https://github.com/user-attachments/assets/4f81b10c-3359-48da-9d58-102fa9bbb652)

It seems the evaluation of the parameter expression to its constant value happens at a later stage in EFCore 9 while it used to happen in earlier stage in EFCore 8.

Evaluation at a later stage is a limiting factor. SInce the value of the parameter isn't immediate available during translation, database providers cannot use it as they could use it earlier in EFCore 8 where they could accept a string value from the customer and generate a corresponding matric for the DB function.

I wanted to ask why EFCore 9 does evaluation of parameter expression to constant value at later stage.
Can Database providers enforce to do the evaluations earlier like it used to happen in EFCore 8.

### Include provider and version information

EF Core version: EFCore 9 RC2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.4

**Comment by cincuranet** [comment]
This issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by shvmgpt116** [comment]
@cincuranet Sorry I posted the incomplete issue by mistake. Now I have put the complete info.

**Comment by shvmgpt116** [comment]
@ajcvickers @roji

**Comment by cincuranet** [comment]
This is an intentional change and it is a result of our continuous query pipeline improvements. 

In this case, originally the node for `EF.Constant` was created early in the pipeline. That had negative effect on our cache, because the node was always different (although the end result was always the same) and the cache hit was poor (and bloating the cache unnecessarily). For EF Core 9 this was improved. 

Now, the node is introduced late in the pipeline. Before that step it is represented as a parameter (hence playing nicely with the cache because it's always the same node) and the fact that it will become constant later on is carried throughout the translation. Only in very last stages of the translation the node is replaced with the constant.

Providers cannot force the previous behavior.

> accept a string value from the customer and generate a corresponding matric for the DB function

This is still possible, when the string value is constant part of the query. If it is a variable wrapped in `EF.Constant`, the above behavior will take place.

**Comment by roji** [comment]
Just to add a tiny note to @cincuranet's answer, you still have the option of building an expression tree and integrating a constant node (with Expression.Constant); that should produce the pre-9.0 behavior for EF.Constant. As @cincuranet wrote, in the vast majority of cases, such extremely early integration of the constant is a very bad idea, causing the entire query to be compiled needlessly.
