### ISSUE TITLE
Not using updated ConnectionString

### ISSUE THREAD

**Issue by AydinBiber-Dekker** [dotnet/efcore#34961]
The ConnectionString in both the appsettings.json and DBContext have been changed, but error messages still indicate that a connection to the old database cannot be made (I am at no point attempting to make this connection).

There seems to be some cached data. Either enable us to easily clear this cache or remove the cache entirely.

**Comment by cincuranet** [comment]
EF is not caching connection strings. So it is probably something else. But this issue is lacking enough information for us to be able to fully understand what is happening. Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by cincuranet** [comment]
As I said, EF is not caching the connection string. Probably you're changing connection string in different file, or the application is not fully rebuilt/restarted, or something similar. But unless proven otherwise, this does not look unrelated to EF.

**Comment by roji** [comment]
> Providing code is impossible. I cannot give you the entire Blazor, EntityFramework and SQL code.

This is never what we ask for - we ask you to start a new project and try to reproduce the problem there; this is generally the effort expected when submitting a bug report. In most cases, as part of working on such a project, users discover the problem in their own code, and resolve it themselves. Otherwise, they have a repro they can post here, so that we can reproduce the problem to investigate.
