### ISSUE TITLE
EFCore 9 RC2 - AsNoTracking doens't work at the Context Level (.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking))

### ISSUE THREAD

**Issue by c5racing** [dotnet/efcore#34970]
We are moving from EFCore7 to EFCore 9 RC2 now that JSON is at a place that we need.  We use read only contexts throughout the platform and have our OptionsBuilder setup like the following:

        options
            .UseNpgsql(dataSource, pgsqlOptions =>
            {
                pgsqlOptions
                .EnableRetryOnFailure()
                .UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)
            })
            .EnableSensitiveDataLogging()
            .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking)
            .EnableDetailedErrors();

When running a query that is projected, we get the following error:  JSON entity or collection can't be projected directly in a tracked query. Either disable tracking by using 'AsNoTracking' method or project the owner entity instead.

Everything works as it should if I add .AsNoTracking() to the actual query.  Shouldn't the default take effect?

**Comment by roji** [comment]
> When running a query that is projected

Can you please include the actual query, or better yet, a minimal, runnable code sample?

**Comment by roji** [comment]
You haven't included your actual query, so it's impossible to be sure what exactly you're doing (please always include a minimal, runnable sample).

However, if you're trying to project part of a JSON document in a tracked query, then that fails by design - EF does not track fragments of a document. We discussed this quite extensively, and decided that EF shouldn't implicitly turn your query into a no-tracking query in this case, since that would be non-obvious to the user, who wouldn't be aware of what's going on and may be surprised that nothing is being tracked. In other words, it's better for the user to have to explicitly specify that the query is untracked.

**Comment by c5racing** [comment]
Thank you.  I put a sample project together to replicate and couldn't so my issue lies in my code and not otherwise.  I should have done this previously.
