### ISSUE TITLE
Property not being ignored by EntityTypeBuilder

### ISSUE THREAD

**Issue by niubomian** [dotnet/efcore#35017]
"AuditType"  cant been ignored!

```C#
public abstract class BaseEntityTypeConfiguration<T> : IEntityTypeConfiguration<T> where T : class, IEntity
{
    public virtual void Configure(EntityTypeBuilder<T> builder)
    {
        //设置主键 或者 无主键
        if (typeof(IHasKeyEntity).IsAssignableFrom(typeof(T)))
        {
            builder.HasKey(nameof(IHasKeyEntity.Id));
            builder
                .Property(nameof(IHasKeyEntity.Id))
                .IsRequired()
                .ValueGeneratedNever();
        }
        else
        {
            builder.HasNoKey();
        }

        //配置 逻辑删除
        if (typeof(ILogicDeletable).IsAssignableFrom(typeof(T)))
        {
            builder.HasQueryFilter((Expression<Func<T, bool>>)(x => !((ILogicDeletable)x).IsDeleted));
        }

        //设置忽略 AuditType
        if (typeof(IAutoAudit).IsAssignableFrom(typeof(T)))
        {
            builder.Ignore(x => ((IAutoAudit)x).AuditType);
        }

        //扫描ULID 然后配置转换器
        var ulids = typeof(T).GetProperties().Where(x => x.PropertyType == typeof(Ulid) || x.PropertyType == typeof(Ulid?)).ToList();

        foreach (var ulid in ulids)
        {
            builder.Property(ulid.Name)
                .HasConversion<UlidToStringConverter>()
                .HasConversion<UlidToBytesConverter>();
        }

        //扫描BaseEnumeration 然后配置转换器
        var enumerations = typeof(T).GetProperties().Where(x => x.PropertyType.BaseType == typeof(BaseEnumeration)).ToList();

        foreach (var enumeration in enumerations)
        {
            var converterType = typeof(EnumerationConverter<>).MakeGenericType(enumeration.PropertyType);
            var converterInstance = Activator.CreateInstance(converterType) as ValueConverter;
            builder.Property(enumeration.Name).HasConversion(converterInstance);
        }
    }
}
```

**Comment by niubomian** [comment]
when "AuditType" is enum type , this property will be ignored successfully. when "AuditType" is custom class type , this property will  not be ignored.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
