### ISSUE TITLE
Analyzer: Warn about missing indexes on queries

### ISSUE THREAD

**Issue by alrz** [dotnet/efcore#35026]
### Background and motivation

SQL tooling supports this sort of warnings but on efcore's generated SQL there's no visibility into the query patterns and existing indexes.

### Proposal

Warn if properties used in conditions are not indexed.

```cs
var result = q.Where(e => e.SomeProperty == value); // warn 'missing index on SomeProperty'
var result = q.GroupBy(e => e.SomeProperty); // warn 'missing index on SomeProperty'
```

**Comment by roji** [comment]
@alrz not every Where() or GroupBy() needs to necessarily use an index (e.g. with small tables), so it definitely wouldn't make sense to warn on every such case. EF is also generally limited in its ability to reliably perform static analysis on LINQ queries, in order to know which .NET property corresponds to which column (and whether that column has an index attached to it).

**Comment by roji** [comment]
Am going to go ahead and close this, as I don't believe EF should be issuing warnings of this sort - in many cases it's completely legitimate to query on columns which don't have indexes defined over them.

@AndriySvyryd if you feel like we should consider this, feel free to reopen!
