### ISSUE TITLE
No coercion operator is defined between nullable and not nullable type after upgrade from EFCore8 to EFCore9

### ISSUE THREAD

**Issue by dario-l** [dotnet/efcore#35117]
We have are extensively use typed identifiers.

For Example:
``` c#
public readonly record struct AreaLocationId(int Value);
```

Which can be mapped as not required nullable foreign key like this:
``` c#

builder.Property(e => e.LocationId)
    .HasConversion(
        id => id == null ? (int?)null : id.Value.Value,
        value => value == null ? null : new AreaLocationId(value.Value));
```

and in where linq clause I can write like this:
``` c#
...
var result = await db
    ...
    .Where(x => x.LocationId != null && availableLocations.Contains(x.LocationId.Value))
    .ToListAsync(ct);
```

With EF Core8 everything works fine. After switching to EFCore9 in the line above we have exception:
```
Unhandled exception: "Exception has been thrown by the target of an invocation."
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
System.InvalidOperationException: No coercion operator is defined between types 'Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer1[System.Nullable1[TimeHarmony.Shared.Areas.AreaLocationId]]' and 'Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer1[TimeHarmony.Shared.Areas.AreaLocationId]
```

Only downgrading to EF Core 8.0.11 solves the issue.

EF Core version: 9.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 9.0

**Comment by dario-l** [comment]
Wow... serious issue as I can see. 😞 

![Image](https://github.com/user-attachments/assets/ce9d9c50-5f0a-4c4e-9335-def83cc08f93)

**Comment by dario-l** [comment]
@roji Thanks for explanation. That's a relief. 👍🏻

**Comment by rabberbock** [comment]
I also ran into a similar issue.

```
 int? number = 10;
 var t = await _applicationContext.Projects
    .Select(p => new
    {
        IntValue = Math.Min(p.MaxTimes, number ?? 10)
    })
    .FirstAsync(); 
```

Because `number` is nullable this no longer works in EF Core 9 with the following error,

```
Expression of type 'System.Nullable`1[System.Int32]' cannot be used for parameter of type 'System.Int32' 
```

Let me know if you think I should open a separate issue. Thanks!

**Comment by roji** [comment]
@rabberbock if you could post a minimal, runnable console program for your case that would be ideal, this way we can check it as we fix this.

**Comment by rabberbock** [comment]
@roji Sure thing!
Here it is https://github.com/rabberbock/EfCore9RegressionNullable.

**Comment by ajcvickers** [comment]
@dario-l A workaround here is to use a parameter type that matches the property type. So in this case a nullable int rather than a normal int:

```C#
var availableLocations = new List<AreaLocationId?> { new(1), new(2) };
```

Note for team: the root cause here is that we get a `List<AreaLocationId>` as the parameter type, which cannot be used with the property type  which is `AreaLocationId?`. We either need better inference, or more forgiving collections.

**Comment by ajcvickers** [comment]
@rabberbock I moved your issue to #35227 since it is not the same as the issue reported here.

**Comment by dario-l** [comment]
> [@dario-l](https://github.com/dario-l) A workaround here is to use a parameter type that matches the property type. So in this case a nullable int rather than a normal int

Thanks for quick solution but this kind of code we use a lot. For now we need to stay at NET8. 😃

**Comment by ajcvickers** [comment]
Note for team: the root cause of the mismatch is the value comparer defined for a nullable value type. This is not recommended (we may want better docs) unless the converter must handle nulls, which is rare. We may want to wait for more feedback before backporting.

@dario-l I recommend you change your value converter to work with the non-nullable value type. For example:

```C#
protected class AreaLocationIdConverter() : ValueConverter<AreaLocationId, int>(v => v.Value, v => new(v));
```

And then used like this:

```C#
b.Property(e => e.LocationId).HasConversion<AreaLocationIdConverter>();
```

**Comment by ajcvickers** [comment]
Re-open to consider patching.

**Comment by ossendorf-at-hoelscher** [comment]
We are experiencing the same exception but not with a collection.
```
Message: No coercion operator is defined between types 'Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1[System.Nullable`1[System.Int32]]' and 'Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1[System.Int32]'.

Stacktrace:
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at Microsoft.EntityFrameworkCore.ChangeTracking.ListOfValueTypesComparer`2.CompareLambda(ValueComparer elementComparer) in /_/src/EFCore/ChangeTracking/ListOfValueTypesComparer.cs:line 68
   at Microsoft.EntityFrameworkCore.ChangeTracking.ListOfValueTypesComparer`2..ctor(ValueComparer elementComparer) in /_/src/EFCore/ChangeTracking/ListOfValueTypesComparer.cs:line 52
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

We have a simple query:
```csharp
if(cirteria.Foo.HasValue)
{
    from item in ourQuery where !item.Foo.HasValue || item.Foo == criteria.Foo.Value select item;
}
```

This also prevents us from updating from .Net8 to .Net9.

**Comment by ajcvickers** [comment]
Note from team meeting: we will not patch this now, since following best practices as shown in [the comment above](https://github.com/dotnet/efcore/issues/35117#issuecomment-2506546699) should fix this issue.

@ossendorf-at-hoelscher If you are still seeing an issue after defining non-nullable value type converters, then please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
