### ISSUE TITLE
`Entity type 'Entity.Addresses#Address' is mapped to JSON and has a navigation to a regular entity which is not the owner`

### ISSUE THREAD

**Issue by ZzZombo** [dotnet/efcore#35115]
## Ask a question

```csharp
	internal class Address
	{
		public string? City { get; set; }
		public string? Street { get; set; }
		public string? Building { get; set; }
		public string? Flat { get; set; }
		public string? PostalCode { get; set; }
		public virtual AddressUseKind UseEntry { get; set; } = null!; // <-- here.
	}
```
`Entity.Addresses` is `ICollection<Address>` and is mapped as an owned type to a JSON column.

Is there a technical reason this is not currently supported? Doesn't it just store FKs? Why can't it map that to JSON?

### Include provider and version information

EF Core version: 8.0.11.
Database provider: (e.g. Npgsql.EntityFrameworkCore.PostgreSQL).
Target framework: (e.g. .NET 8.0-windows).
Operating system: Windows 10.
IDE: (e.g. Visual Studio 2022 17.11.5).

**Comment by ZzZombo** [comment]
> Duplicate of [#31245](https://github.com/dotnet/efcore/issues/31245)

Are you sure about that? That issue title reads "Allow navigations and FK properties on **non**-collection **complex** types".

**Comment by ZzZombo** [comment]
> You're correct. However, it's unlikely that we will make any significant changes to owned types going forward, so this is tracking the scenario for complex types.

I'm going to dispute this decision to close the issue on the grounds that it was a duplicate: 1) it is not a duplicate at all and 2) it was NOT a request for change in the first place. It was a question, fueled by my professional curiosity.

**Comment by roji** [comment]
@ZzZombo the fact that the issue was closed only means that we don't have an actionable work item here (i.e. a bug to fix or a feature to implement), at least not at this stage; we can absolutely continue to discuss things, and that could maybe lead to the issue getting reopened, or another issue getting filed etc.

In any case, whether the navigation is a collection or a reference navigation is (IMHO) not important here; it's true that #31245 talks about non-collection complex types, but I strongly believe that we should support navigations within complex type collections as well.

Other than that, as @ajcvickers wrote above, we're shifting towards complex types being the preferred/standard way to map JSON columns, which is why this issue is conceptually a duplicate of #31245 (even though that issue is about complex types and this one is about owned entities, so technically it isn't). Complex types are simply a better fit for (most cases of) JSON modeling, and we hope to make a major push on this for EF 10.

But in any way, as I said, we're happy to continue discussing here regardless of whether the issue is open or closed.
