### ISSUE TITLE
Microsoft.EntityFrameworkCore.Database.Command: Taking time to execute the queries because of new DateOnly datatype in .NET 8

### ISSUE THREAD

**Issue by santosh20-debug** [dotnet/efcore#35248]
Good Evening,

While using the .NET 8 notice the new change in EFCore 8.0 that, fields having "date" datatype in SQL Server is now showing "DateOnly" in entity class which is generated using dotnet ef scaffold command.

**IMP ISSUE TO NOTE:**
_Due to this "DateOnly" datatype, EFCore Database command execution in .NET 8 is very slow and taking 15 to 20 seconds to get the result._
**IMP ISSUE TO NOTE:**

While in .NET 6, the query runs very faster and took only 80-90 milli-seconds.
In .NET 6, we don't have "DateOnly" datatype and in context class it specified the field having date dataType with property "HasColumnType".

For your reference I have attached the 2 screenshots for query executions in .NET 8  and .NET 6.

Can you please provide the solution for this or else please update the scaffolding, so it would not convert date field to "DateOnly" in entity class?

Because of this I have to update the date datatype to datetime datatype in DB and do the scaffolding again, re-generate the class and update the logic.

**EFCORE .NET 6 DB Command Execution:** - Tooks 86 ms
![Image](https://github.com/user-attachments/assets/a0b21514-76aa-4373-9a4c-6642a8230be6)

**EFCORE .NET 8 DB Command Execution:** - Tooks 11 second
![Image](https://github.com/user-attachments/assets/ef3ae6b9-622e-4794-b1cb-fcdaf9b8defe)

**EF Core version:** 8.0.10

**Below Packages Used:** 

a) Microsoft.EntityFrameworkCore -v 8.0.10
b) Microsoft.EntityFrameworkCore.Design -v 8.0.10
c) Microsoft.EntityFrameworkCore.SqlServer -v 8.0.10
d) Microsoft.EntityFrameworkCore.Tools -v 8.0.10

Target framework: .NET 8.0 , SDK Version: 8.0.403
Operating system: Windows 11 - 64 Bit
IDE: Visual Studio Code

**Comment by roji** [comment]
@santosh20-debug we're going to need to see a minimal repro for the slowdown - a couple of redacted screenshots is not enough when submitting an issue. There's nothing fundamentally slower about DateOnly, in EF or elsewhere; the SQL in the queries seems to have changed based on the screenshots above, and that may be the source of a slowdown, but we need to see some code to actually know.

**Comment by santosh20-debug** [comment]
> > > [@santosh20-debug](https://github.com/santosh20-debug) sorry, but issue filing doesn't work this way - we need at the very least to see an actual LINQ query, along with the SQL; you can rename/redact whatever you want, but you have to provide some code, otherwise we have nothing to go on. You'll have to do the minimal amount of work to get your issue looked at, otherwise quick textual descriptions such as what you've posted above simply aren't sufficient.
> > 
> > 
> > [@roji](https://github.com/roji) , ok thanks for sharing, I will get back to you on this by tomorrow.
> 
> [@roji](https://github.com/roji) , And what about the SQL server for DB, do you have or we need to provide you the DB Connectivity for running and compiling the code?

@roji If you have localdb set up with you, then I can provide the repository for .NET 6 and .NET 8 by tomorrow, please confirm?

**Comment by roji** [comment]
@santosh20-debug we have SQL Server running locally; what we need is a minimal code sample which, when executed, shows the problem happening. Please do not send your entire repository or similar, but rather a minimal, runnable code sample.

**Comment by AndriySvyryd** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.

Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
