### ISSUE TITLE
Rename EntityTypeBuilder<TEntity>.HasData(params object[] data) overload

### ISSUE THREAD

**Issue by nlriverty** [dotnet/efcore#35261]
I would have expected the following code to produce an error at compile time:
```csharp
    public void Configure(EntityTypeBuilder<EntityType> builder)
    {
        builder.HasData(new CompletelyDifferentEntityType { });
    }
```
It works because the overload accepts an array of type `object`. 
We had code like this for a while without realizing, probably because they share common a set of fields with the same names and types, which created correct (hopefully) migrations.

I'd like to rename that overload to something different to force the developer to recognize they're supplying anonymous objects rather than the incorrect entity type.

**Comment by roji** [comment]
What would you rename it to, and how would the APIs actually look like?

**Comment by nlriverty** [comment]
I'm terrible at naming 😬
I think I would keep the existing strongly typed overloads as they are and rename 
`HasData(params object[] data)` to `HasDataFromAnonymousTypes(params object[] data)`

**Comment by roji** [comment]
So are you only proposing that we rename HasData to HasDataFromAnonymousTypes, without introducing an alternative API that works differently?

In any case, HasDataFromAnonymousTypes doesn't seem right, since it does allow using the entity's (non-anonymous) CLR type ([as per the docs](https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding#model-managed-data)). That's how most people use it, I think you're the first person to try another, arbitrary CLR type.

**Comment by nlriverty** [comment]
> In any case, HasDataFromAnonymousTypes doesn't seem right, since it does allow using the entity's (non-anonymous) CLR type

If they wanted to do that they would call `HasData`, i.e. do exactly what they're doing now.

**Comment by roji** [comment]
I'll got ahead and close this as some time has passed without any specific response - see my comment above for reasoning. If you have further comments/arguments, feel free to post them here - we can reopen if needed.
