### ISSUE TITLE
Inconsistencies in the Ignore() method

### ISSUE THREAD

**Issue by sebastienros** [dotnet/efcore#3546]
_Minor issue._

This code ignores a property

`modelBuilder.Entity("Foo").Ignore(...);`

Adding a lambda as the argument will make it ignore the type only. At least from the inline documentation.

`modelBuilder.Entity("", p => { }).Ignore();` 

I would have expected the same options for `Ignore`.

**Comment by rowanmiller** [comment]
Hey,

This is by design...

There are two patterns on the Fluent API. The first one drills down on each method call, so you end up with multiple lines of code to configure each entity.

```
modelBuilder.Entity<Blog>().Property(b => b.Name).HasMaxLength(200);

modelBuilder.Entity<Blog>().Ignore(b => b.DisplayName); 
```

The lambda overload of Entity that you mentioned is designed so that you do all the config for the entity in the lambda:

```
modelBuilder.Entity<Blog>(blog =>
{
    blog.Property(b => b.Name).HasMaxLength(200);

    blog.Ignore(b => b.DisplayName);
});
```

The return type of this is the top level ModelBuilder, so you can keep chaining things together. Therefore Ignore after this overload is an Ignore at the ModelBuilder level (i.e. ignoring a type) rather than an ignore at the entity level (which you would do inside the lambda):

```
modelBuilder
    .Entity<Blog>(blog =>
    {
        blog.Property(b => b.Name).HasMaxLength(200);

        blog.Ignore(b => b.DisplayName);
    })
    .Entity<Post>(post=>
    {
        post.Property(b => b.Title).HasMaxLength(500);
    })
    .Ignore<Tag>();
```
