### ISSUE TITLE
Error selecting over inherited entities

### ISSUE THREAD

**Issue by IonRobu** [dotnet/efcore#3584]
Hello, 

I have a submodel of parent-child entities, like described here: https://github.com/aspnet/EntityFramework/issues/3445.
When I make a simple select:

```
public class Context : DbContext
{
        public new IQueryable<TEntity> Set<TEntity>() where TEntity : class, IEntity, new()
        {
            var result = base.Set<TEntity>()
                .AsNoTracking()
                .AsQueryable();
            return result;
        }
}
```

I receive error: 
System.ArgumentNullException: Value cannot be null.
Parameter name: navigation

"Value cannot be null.\r\nParameter name: navigation"

This seems to be related somehow to https://github.com/aspnet/EntityFramework/issues/3445, since the select works for simple (non-inherited) entities.

Thanks,
Ion

**Comment by IonRobu** [comment]
Hello,

Any progress on this?

Thanks,
Ion

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing? Be sure to include the code for you model, context, and the application code that fails.
