### ISSUE TITLE
Plea for code review of SQL CE provider

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#3611]
About 1/3 of the code in the SQLCE provider is now residing in a single class. I would be very grateful if someone from the team could take time to review it, to find if there is potential for a different implementation with less code (and any other improvements). Thanks in advance!

https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/src/Provider40/Update/Internal/SqlCeModificationCommandBatch.cs
One of the reasons that this class has grown is the recent changes to command execution, combined with the fact, that the sqlce engine only can execute a single statement per command execution, and I need to get the @@identity value on the same open connection in order to return an identity value

**Comment by rowanmiller** [comment]
@mikary can you help out here

**Comment by bricelam** [comment]
I noticed similar connection lifetime issues on SQLite in-memory. Migrations can no longer be applied because the connection is closed during the migration so the database goes away after creating the history table.

**Comment by mikary** [comment]
It looks like you've been forced to override a large amount of behavior in `ReaderModificationCommand` and `AffectedCountModificationCommand` due to the batching and indexing of commands assumed in the factoring.
@AndriySvyryd do you think we should revisit the factoring on these classes to better accommodate command batch size limitations (including no batching)?

I'm a little concerned about the `SplitCommandText` method because it seems to only accommodate the case where the command text represents two commands, while I don't think there is a restriction like that in place.

Something else to note in the Execute methods is that calling `ExecuteReader` calls 'Open' on the `IRelationalCommand` and when the RelationalDataReader is disposed the accompanying `Close` call is made. It is possible to opt out of this behavior by passing 'false' for the optional "manageConnection" parameter, and instead wrap the sequence of commands in try/finally with 'Open' and 'Close'

**Comment by ErikEJ** [comment]
@mikary  Thanks for your comments - do not worry to much about the amount of code, SQL CE has some very specific limitations. 

Re SplitCommandText: I have a fixed MaxbatchSize of 1, and the only case where I add another statement is to return the @@IDENTITY value.

Not sure I understand the comments re Open/Close...
