### ISSUE TITLE
ColumnType annotation ignored for Where clause?

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#3617]
I'm implementing some type mapping scenarios for Npgsql and have run into an issue.

PostgreSQL supports some types which don't have a natural corresponding CLR type; for example, the PostgreSQL jsonb type has no natural/universal JSON CLR type. It makes sense to map it to CLR string. This should work well as long as the user explicitly sets the ColumnType on the property to "jsonb"; this should make the type mapper to look up the JSON mapping (as opposed to string) and set up the DbParameter correctly.

I've written some Npgsql testing around this in the BuiltInDataTypes testsuite (similar to SqlServer's) and am running into trouble. Specifically, in the `Can_query_using_any_mapped_data_type` test, the jsonb property is being used in a Where() clauses. It seems that when the parameter is constructed, the `GetMapping(Type)` overload is called on IRelationalTypeMapper, rather than the `GetMapping(IProperty)` overload. The overload that accepts a type sees only the property's type, which is a string, and creates a string DbParameter instead of a jsonb one. In other words, the user-configured ColumnType seems to be ignored in this scenario.

**Comment by mikary** [comment]
This appears to be a part of a larger issue (#4608) that the query pipeline does not infer column/property facets. the `DefaultQuerySqlGenerator` does not use the `IProperty` based mapping because it is absent in the query expression.

Adding a note to that issue to ensure this is resolved as a part of that work and closing this issue.
