### ISSUE TITLE
Information Logging in Beta 8 seems to be gone

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/efcore#3624]
In Beta 7 I could turn on Information logging (to the console or debug) and I would get detailed output from EF7, but in Beta 8 it's missing. Is this expected? I couldn't see anything in the release notes.

**Comment by ErikEJ** [comment]
I have some helper classes here, that work(ed) with beta8: https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/tree/master/src/Provider40/Extensions/Logging and https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/blob/master/src/Provider40/Extensions/SqlCeDbContextExtensions.cs

**Comment by poke** [comment]
The log level was corrected to be *debug* instead of *information*, since it’s really not information but just very detailed debug stuff. This was actually done shortly after the release of beta 7 IIRC, see #3081.

So if you want to see that information, change the console’s log level to debug, so you see the output.

**Comment by shawnwildermuth** [comment]
I didn't see it under debug either. I'll attach my repro later today

**Comment by rowanmiller** [comment]
@shawnwildermuth we haven't been able to reproduce this, feel free to attach a repro. Could it be that you need to pass the LogLevel to the AddConsole method?

**Comment by shawnwildermuth** [comment]
Looks like it is working, changes to logging hid it from me. Please close it.
