### ISSUE TITLE
(Question) Can be Aspnet Identity (Code First) with EF edmx model together?

### ISSUE THREAD

**Issue by danicomas** [dotnet/efcore#3661]

**Comment by rowanmiller** [comment]
Identity always uses Code First, so you cannot use EDMX with Identity. You can have a separate EDMX model in the same project as a CodeFirst one.

**Comment by danicomas** [comment]
Yes @rowanmiller, but it causes a performance problem because you need to do Enumerable queries. Linq + EF can not work with separtely context I don't know why because will be easy to do dbo.db1.table1.id = dbo.db2.table2.id.

**Comment by rowanmiller** [comment]
You can extend the existing Identity model to include other entities... you just need to keep using code-based modelling since that is how the model is defined.

BTW having the option to use EDMX for the identity model does not seem unreasonable to me, the work to do this would be in Identity and their issue tracker is at http://aspnetwebstack.codeplex.com/. That said, I don't think they will do the work since EDMX is no longer around in EF7 so they would only be doing the work for past versions of Identity.
