### ISSUE TITLE
Suggestion: Class name for Migrations to match filename as closely as possible

### ISSUE THREAD

**Issue by ChristineBoersen** [dotnet/efcore#3673]
Currently, When making a new migrations, example "Initial",
It names the migrations file in the format "yyyyMMddhhmmss_Initial.cs", but names the partial class generated "Initial".

My suggestion (given the above scenario) is to have the partial class named "_yyyyMMddhhmmss_Initial" instead. This way you don't have to think up unique names for all of your Migrations since the date/time part already makes it unique. Also then your class name "matches" (albeit with an underscore in front of the name) the file name, which is more consistent.

Just trying to envision once a system has been in production for a year or two and having lots of Migrations possibly, as it stands, a developer could easily get some naming collisions, say they do two data inserts and call them "Data" not realizing that the partial classes aren't matching the filename.

**Comment by rowanmiller** [comment]
We discussed this as a team and decided to leave the naming as it is. We've been generating class names without the timestamp since EF4.1 and in general we've seen it work well. We discourage folks from having duplicate simple names since most of the migration commands allow you to specify the name without the timestamp.
