### ISSUE TITLE
Why cannot use circular reference with foreignkey

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#3678]

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing? Can you provide details of the error you are seeing (message and stack trace) or the unexpected behavior? If it is unexpected behavior rather than an error, please also include the expected behavior.
