### ISSUE TITLE
Changetracking in disconnected Scenarios for client?

### ISSUE THREAD

**Issue by ThomasGugler** [dotnet/efcore#3707]
i'm looking for a disconnected "real world" (.net wcf) sample,
1) Read Entity from Server
2.) Update disconnected Entity on Client
Q1) How to detect a modified entity on Client?
Q2) How to detect a modified entity on Server?

**Comment by batesm** [comment]
This issue is not strictly within the scope of EntityFramework and is a more generalised problem.

1. When dealing with entities both client- and server-side communication is done with the aid of serialization. WCF by default does this with DataContract serialization (there are other ways - binary, json etc) This is how you would "read an entity from the server".
2. To update the entity on the server you would typically have to use serialization again to pass the changes from client to server. The changes (ChangeSet) established by your service method (e.g Create/Update) would necessarily have to be re-applied service-side to reflect exactly what happened on the client.

Q1). Use EF change tracker to see what changed client-side. The change tracker is not new to EF and indeed EF7 is concept compatible with that.
Q2). Ditto for detecting changes server-side (but only only after you have re-applied your changes on the server to reflect client activity properly).

A couple of times I have referred to re-applying changes on the server-side after receiving data from the client. There are plenty of samples on the web to show how you to do this with EF. For instance, in Visual Studio when adding a Controller to an ASP.NET MVC app you can choose an item template that scaffolds all the code needed to receive entities from the client and create, update or delete them on the server.

For WCF I expect to the code to basically look just the same in your service/operation contracts when dealing with EF (same use of DbContext, DbSet etc).

This is not an official MS answer but wanted to contribute. Hope it helps.
