### ISSUE TITLE
Crash when applying include after projection

### ISSUE THREAD

**Issue by davidroth** [dotnet/efcore#3721]
If I apply _Include(..)_ on the root expression, everything is fine:

``` csharp
(from pos in Context.Set<OrderPosition>().Include(x => x.Order)
select new
{
    Position = pos,
})
.ToList();
```

However when applied after the projection, the query crashes:

``` csharp
(from pos in Context.Set<OrderPosition>()
select new
{
    Position = pos,
})
.Include(x => x.Position.Order)
.ToList();
```

Exception:

```
Exception thrown: 'System.InvalidCastException' in EntityFramework.Core.dll
Additional information: Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MemberExpression'.
```

This is obviously a simplified version where it would be easy to include at the top of the expression.
However, there are scenarios, where it is nice to include later when not having access tho the root expression.For example one might pass the projected query to another method which then decides to include based on some conditions.

**Comment by rowanmiller** [comment]
This is by-design because you can only call the Include method on an entity type. Before the call to `select new` the type of your query is `IQueryable<OrderPosition>`, after it is `IQuerable<AnonymousTypeWithPostitionProperty> `. Since the anonymous type you projected to is not an entity type, EF is not able to include related data.

**Comment by davidroth** [comment]
@rowanmiller 

But this could be supported in a future EF version right? The expression has the link to the original entity type/root expression. Shouldn't this be marked for backlog / up4grabs instead?

Furthermore the exception `System.InvalidCastException` does not look *as design* and does not indicate that this feature is not supported by EF. I think it would be better to throw an explicit `System.NotSupportedException` with the remark, that including via a projection is not supported.

**Comment by rowanmiller** [comment]
@davidroth we aren't planning to support it. LINQ is one of those things where anything could be supported but we need to chose where we focus and this doesn't seem like it adds enough value as you can always just write the include in terms of the entity being queried.

The same is true for exception messages, we could spend endless time adding pretty exception messages for negative cases. But we typically only fix ones where you get a NullReferenceException etc.

This does exclude someone deciding to contribute support for this (or a better exception message). We just aren't planning to work on it and we try not to keep issues around that we don't ever plan to tackle (otherwise we'd have thousands of work items on our backlog :smile:)

**Comment by davidroth** [comment]
@rowanmiller I understand, thanks for the reply.
