### ISSUE TITLE
InvalidOperationException when adding Migration. Can't resolve service for type IHttpContextAccessor

### ISSUE THREAD

**Issue by MaxxDelusional** [dotnet/efcore#3814]
I am getting the following error when I am trying to add a migration.

Unable to resolve service for type 'Microsoft.AspNet.Http.IHttpContextAccessor' while attempting to activate 'Microsoft.AspNet.ViewFeatures.TempDataDictionary'

I did a quick test and both of these types are available through Dependency Injection.

EF7 ASP.Net 5 RC1

**Comment by MaxxDelusional** [comment]
It seems that this problem occurs because IHttpContextAccessor is not an available service when running from the command line. My DbContext class had a constructor that took a parameter that relied on DI providing an IHttpContextAccessor. 

In beta8 I believe it just passed null, but in RC1 it throws an exception.

**Comment by davidfowl** [comment]
Why are you filing this on EF?

**Comment by MaxxDelusional** [comment]
Are database migrations not part of EF?

**Comment by davidfowl** [comment]
Ah I missed it, I thought you were using RC2

**Comment by rowanmiller** [comment]
So migrations needs to create an instance of you context to be able to build the model etc. At design time there is no `IHttpContextAccessor`... since there is no request :smile:. There are a few options here, such as registering a dummy implementation of that for design time, or you could just implement `IDbContextFactory` to tell EF how to create design time instances of you context.

Out of interest... what are you using `IHttpContextAccessor` for in the context?

**Comment by MaxxDelusional** [comment]
I was actually using `TempDataDictionary` in the context to store some error information, but `TempDataDictionary`'s constructor requires the `IHttpContextAccessor`.

It's fairly easy to workaround, but because it worked in beta8, I thought something had broke.

**Comment by rowanmiller** [comment]
BTW one other idea is to take IEnumerable<IHttpContextAccessor> and you will either get one or zero elements (that way you can emulate the behavior from Beta 8)
