### ISSUE TITLE
strange sql generation when configuring incorrectly the enity

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#3838]
Hi, this is not a bug, I just found a strange behavior in the generation of sql when I do mistakes configuring relationship using fluent api

I have this entity class

```
    public class Attivita
    {
        public int AttivitaNo { get; set; }
        public string Descrizione { get; set; }
...
        public int? ProgettoNo { get; set; }
        public int? PagamentoNo { get; set; }

        public Progetto Progetto { get; set; }
        public Pagamento Pagamento { get; set; }
    }
```

the correct configuration of the relationship using fluent api is:

```
            builder.Entity<Attivita>().HasOne(loc => loc.Progetto)
                .WithMany(cli => cli.Attivita).HasForeignKey(loc => loc.ProgettoNo)
                .IsRequired(false);
            builder.Entity<Attivita>().HasOne(loc => loc.Pagamento)
                .WithMany(cli => cli.Attivita).HasForeignKey(loc => loc.PagamentoNo)
                .IsRequired(false);

```

I have done a mistake writing the second one this way:

```
            builder.Entity<Attivita>().HasOne(loc => loc.Pagamento)
                .WithMany(cli => cli.Attivita).HasForeignKey(loc => **loc.ProgettoNo**)
                .IsRequired(false);
```

Adding an incorrect foreignKey:
The strange result is that in the generated script

```
Execute Reader "SELECT TOP(30) [a].[AttivitaNo], [a].[ClienteNo], [a].[CommessaNo], [a].[DaFatturare], [a].[Data], [a].[Descrizione], [a].[FatturaNo], [a].[Fatturato], [a].[LocazioneNo], [a].[NonPrevisto], [a].[Note], [a].[NumOre], [a].[PagamentoNo], [a].[ProgettoNo], **[a].[ProgettoProgettoNo]**, [a].[TipoAttivitaNo], [a].[Urgente] FROM [Attivita] AS [a]"  
```

adds the [a].[ProgettoProgettoNo] that does not exists, finxing the foreign key corrects the problem

**Comment by rowanmiller** [comment]
It looks like we are introducing a shadow state foreign key, I think this is because your second mistyped configuration call is re-assigning `ProgettoNo` to be the FK for a different relationship, which means the first relationship is left without an FK and therefore we introduce a shadow state one.

@smitpatel @AndriySvyryd is my reasoning correct?

**Comment by AndriySvyryd** [comment]
@rowanmiller Yes, that's what happened. The name for the generated FK property is navigation+PK name

**Comment by lucamorelli** [comment]
thanks for the answer. I read about shadow properties in the docs site but honestly I don't understand the scenario where to use this feature. I'll look for more info.

**Comment by rowanmiller** [comment]
@smitpatel @AndriySvyryd I think we decided we already had an issue to allow multiple relationships to share an FK property (provided they point to different types) - which would mean this case would end up with a shared FK rather than a shadow state FK. Was that correct? And if so, can you point to the issue (or PR) for that change?

**Comment by AndriySvyryd** [comment]
https://github.com/aspnet/EntityFramework/issues/3551
