### ISSUE TITLE
InMemory provider increments row id property even when saving throws an exception

### ISSUE THREAD

**Issue by philippecp** [dotnet/efcore#3855]
If an entity has a primary and a property mapped to use UseSqlServerIdentityColumn(), adding two instances with same key using different dbContext instances will result in an exception being thrown (as expected). However,calling context.Add() pre-emptively increments the id so that after both calls the entity has an id of 2 instead of 1.

**Comment by rowanmiller** [comment]
This is by design. It's similar to if you use the Hi-Lo generator on SQL Server, we don't make any attempt to return keys that are not ultimately saved.

BTW calling `UseSqlServerIdentityColumn()` has no impact when running against InMemory, that metadata is only processed by the SQL Server provider.
