### ISSUE TITLE
Timestamp doesn't work on types with inheritance

### ISSUE THREAD

**Issue by philippecp** [dotnet/efcore#3912]
When using SQL localdb and code first, the row version byte array doesn't get updated in db when the type has a parent.

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing?

**Comment by Eneuman** [comment]
I'm also having problem with this.
My setup is like this:

public class BaseEntity
{
    public int Id { get; set; }
}

public class Adress : BaseEntity
{
    public string Street { get; set; }
    public byte[] RowVersion { get; set; }
}

builder.Entity<Adress>(b =>
{
        b.ToTable("Addresses");
        b.Property(u => u.Street).IsRequired().HasMaxLength(400);
        b.Property(u => u.RowVersion).IsConcurrencyToken();
});

ef migrations generates this:

     migrationBuilder.CreateTable(
                name: "Adresser",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Street = table.Column<string>(nullable: false),
                    RowVersion = table.Column<byte[]>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Adress", x => x.Id);
        });

Whenever I insert a address, RowVersion gets NULL as it's value in the database.

**Comment by rowanmiller** [comment]
@smitpatel @AndriySvyryd is configuring a `byte[]` property as a concurrency token enough to make it a rowversion... or do you need to mark it as store generated too?

**Comment by Eneuman** [comment]
Yeah, reading the documentation about Concurrency Tokens a second time I noticed that only the [TimeStamp] data annotation actually creates a timestamp columns in sql server.
But it cannot be done in Fluent API.
I think this is going to be a problem. More and more are using DI and hexagon/onion architecture now a days and separating any Data logic from the core entities is in my opinion a good thing. I havn't seen any new projects using Data Annotations over Fluent API.

Since there already is a UseSqlServerIdentityColumn, wouldn't it be nice with a UseSqlServerTimeStampColumn :)

**Comment by AndriySvyryd** [comment]
@Eneuman It is already possible to do with Fluent API that's not SqlServer-specific:
```
modelBuilder.Entity<Product>().Property(e => e.Version)
    .ValueGeneratedOnAddOrUpdate()
    .IsConcurrencyToken();
```

**Comment by Eneuman** [comment]
Nice :)

The ef7 [TimeStamp] doc section could use this information. ValueGeneratedOnAddOrUpdate part is missing.

Thanks for the info!
//Per

**Comment by rowanmiller** [comment]
@Eneuman good point, just drafted up a change to add this info https://github.com/aspnet/EntityFramework.Docs/pull/85

**Comment by philippecp** [comment]
You're right, I must have done a mistake because I can't seem to reproduce anymore.
