### ISSUE TITLE
SQL Client Writing Wrong Sql?

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#3917]
I heard in the recent community stand up video that there was an RC1 Update 1 coming to help address some issues in RC 1. In specific I am seeing the SQL Client ("EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final") incorrectly write SQL to be executed against MS SQL Server. For example I am seeing an error that says PartyPartyId is not a valid column name. The issue it looks like is there is no "dot" between Party (table) and PartyId(column). Does anyone know if Update 1 will address this?

Thanks in advance for any help!

**Comment by srollinet** [comment]
Probably not a missing dot. I Have the same exception here #3889 (second query)
the column name is correct, but it is not on the correct table. In my example, t should be a team and not a player.

**Comment by rowanmiller** [comment]
> For example I am seeing an error that says PartyPartyId is not a valid column name.

This is probably because EF is not picking up the foreign key property in your class and so it is introducing its own (the convention is <navigation property name><primary key name>). Take a look at http://docs.efproject.net/en/latest/modeling/relationships.html and then feel free to share the code listing of you model if you need additional help.

**Comment by chassq** [comment]
Thanks for the input. When I rechecked my model code the FK was set improperly. Beta 8 did not catch this mistake but apparently RC1 did. Thanks again for the help!
