### ISSUE TITLE
Baseclass-Fields only inserted, not updated

### ISSUE THREAD

**Issue by KarlAndenmatten** [dotnet/efcore#3929]
We have an abstract entity-base-class with 3 properties:
.  Id
. CreatedAt
. ModifiedAt
from which all our real entity-classe are derived.

This seemed to work fine but then we discovered that this base-class-fields are only saved on insert but not when we update the record:  ‚ModifiedAt‘ is never written back to the database.
We have logged the SQL-Statements: the ModifiedAt-Field is missing in the update-Statement.
We have installed 'EntityFramework.Sqlite '7.0.0-rc1-final'.

Is our approach not correct? 
Or do we have specially to configure the update-behaviour of the baseclass-fields?

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing?

**Comment by KarlAndenmatten** [comment]
I will try to prepare this week a project to reproduce the issue.

**Comment by KarlAndenmatten** [comment]
Hi @rowanmiller 
i have now added a visual-studio solution (EF7BugBaseFieldsNotUpdated.zip) on my github-account. This solution reproduces the bug.
I hope that with this solution it should be possible to fix the bug or to tell us if we have to configure our model other way.

**Comment by rowanmiller** [comment]
@KarlAndenmatten this one took me a minute to spot :smile: ...

You `ModelBase` base class implements `INotifyPropertyChanged` which means EF expects to receive notification when a property changes (and therefore stops capturing values when it loads the entities and scanning for changes before saving).

The issue is that you don't raise a notification for the `ModifiedDate` property... so EF is never notified that the new value is assigned. I've confirmed that updating the `EntityBase` implementation as follows rectifies the issue.

```c#
        private DateTime _modifiedAt;
        public DateTime ModifiedAt
        {
            get { return _modifiedAt; }
            set
            {
                _modifiedAt = value;
                OnPropertyChanged("ModifiedAt");
            }
        }
```

**Comment by KarlAndenmatten** [comment]
@rowanmiller Thanks a lot for your help: this solved the 'bug'.
For me it seems a bit curious that EF expects to receive notification from the model because it's not obvious that the model must then implement notification on ALL properties. I think this should later be good documented - when then a documentation exists ;-)
