### ISSUE TITLE
Migrations is ignoring my maxlength when columntype was specified

### ISSUE THREAD

**Issue by pedroivobraga** [dotnet/efcore#3985]
I'm generating my database using migrations, when I specific the column type as varchar and maxlength the result is varchar(1)

```
        modelBuilder.Entity<Area>(entity =>
        {
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("varchar");
        });
```

I had to remove the column type to generate right.

**Comment by rowanmiller** [comment]
This is by-design, if you specify an explicit type then you are overriding all the other hints that EF would give the provider to work out a data type to use. You would typically put "varchar(50)" as the data type if that is what you want.

Leaving open for triage, as it seems a little strange that we are converting "varchar" to "varchar(1)"

**Comment by justdmitry** [comment]
As soon as MaxLength attribute (as source for HasMaxLength) is used not only for db schema, but also by GUI generators/validators - it's desirable for HasColumnType() also honor it.

**Comment by rowanmiller** [comment]
You are fine to put the max length attribute on, but if you use `HasColumnType()` then you are explicitly telling EF what type to use for the column. EF is not doing anything to convert this to `varchar(1)`, it is just sending exactly what you supplied to the database (and SQL Server decides that `varchar` means `varchar(1)`).

BTW if you just want to swap to a non-Unicode data type then we have a work item to bring back `IsUnicode` so that you don't have to drop down to a hard-coded data type (https://github.com/aspnet/EntityFramework/issues/3420).
