### ISSUE TITLE
Error adding EntityFramework.MicrosoftSqlServer.Design to project.json

### ISSUE THREAD

**Issue by ww-sandra** [dotnet/efcore#4013]
Unable to add EntityFramework.MicrosoftSqlServer.Design to the project.json file.  I am receiving the following error output: 

"Unable to locate Dependency EntityFramework.MicrosoftSqlServer.Design >= 7.0.0-rc1-final"

*Also, nuget is bust as well w/ the following: 

"Unable to find package 'EntityFramework.MicrosoftSqlServer.Design'"

**Comment by rowanmiller** [comment]
Hey,

Have you verified that you have nuget.org in your package sources?

~Rowan

**Comment by jalalmostafa** [comment]
`EntityFramework.MicrosoftSqlServer.Design ` is still a release candidate (RC1) no stable packages are ready yet. (That's why nuget was unable to find the package)
Just run:
`Install-Package EntityFramework.MicrosoftSqlServer.Design -Pre`
instead of `Install-Package EntityFramework.MicrosoftSqlServer.Design`
