### ISSUE TITLE
Introduce Index on TPH Discriminator

### ISSUE THREAD

**Issue by matthewDDennis** [dotnet/efcore#4030]
I've just created my first TPH EF Core DbContext and discovered that the Discriminator column is not indexed.  Won't this result in a table scan for any queries that use the Discriminator to determine the derived type?

**Comment by LonDat** [comment]
It's depends...when you have milion rows and 2 derived classes...index is not useful.

**Comment by matthewDDennis** [comment]
Why not.  Lets say the two derived classes are A and B, and the table is 25% A and 75% B.
If you need to get only the As, then with an Index you would only Index scan 25%.  Without the Index you would Table Scan the entire table.

**Comment by LonDat** [comment]
Yes...when you select only by type, index really help...I have experience with there 3 scenarios:
1. sql use another index, because where contains more conditions (almost never run select with discriminator fitter only on big table)
2. select over base table...so discriminator index not useful
3. select by discriminator only...but table is small, that index not helping :)

I mean, that index for discriminator is good for some situations...but I don't know, if "default ON" is best way...and if yes, than please some way, how this index disable.

I'm not sure, but maybe you can add index over `EntityTypeBuilder<>.HasIndex("Discriminator")`?

Milan

**Comment by rowanmiller** [comment]
We'll dig into this more post-7.0.0 release. In the meantime you can add them manually via the Fluent API

**Comment by caleblloyd** [comment]
@matthewDDennis is correct, if derived classes are being queried, the Discriminator should get an Index to prevent a Full Table Scan.  Here's an example of how to adjust the length and add an index with the Fluent API:

	modelBuilder.Entity<YourType>(entity =>
	{
		entity.Property("Discriminator")
			.HasMaxLength(63);
		entity.HasIndex("Discriminator");
	}

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
