### ISSUE TITLE
Multiple parents with the same 1:1 child doesn't work well

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/efcore#4035]
I've got the following model:

``` csharp
public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class ParentA
{
    public int Id { get; set; }
    [Required]
    public Child Child { get; set; }
}

public class ParentB
{
    public int Id { get; set; }
    [Required]
    public Child Child { get; set; }
}

public class Context : DbContext
{
    public DbSet<ParentA> ParentA { get; set; }
    public DbSet<ParentB> ParentB { get; set; }
}
```

When I `Add` a fully constructed ParentA (with child) and `SaveChanges()` I get a "NOT NULL constraint failed: ParentA.ChildId" exception from SQLite.

I have read #3724, but I don't think the resolution applies here.

In the model snapshot, I can see that the parent/child connections are correctly set up with foreign keys set up on both `ParentA` and `ParentB`. However, these are set up as `HasOne().WithMany()`, while I would have expected `HasOne().WithOne()`.

For now, I have extended my Context with a `DbSet<Child>` and `Add()` the child from the parent manually, but I would have expected the `GraphBehavior.IncludeDependents` to do The Right Thing.

**Comment by smitpatel** [comment]
The way relationships are configured would be `Child` being the principal and `ParentA` & `ParentB` are dependent ends. There will be foreign key property named `ChildId` in both `ParentA` & `ParentB`. With the naming of parent/child, it looks like relationships are not configured as you want since `Child` is parent and `ParentA` & `ParentB` are children. If that is the case then solution of #3724 would be applicable here. The relationships are generated with `HasOne().WithMany()` because in the absence of principal to dependent navigation, conventions assume the relationship to be one to many unless set explicitly otherwise.

If above is not the case and your relationships are configured correctly as you want them then, `Add()` is working as expected. When you add principal entity then all dependent entity referencing it will be added. In your example when you add `ParentA` with child, `ParentA` is dependent entity, so `Add()` won't traverse towards principal to add the `Child` entity used there. You have to add child entity separately.

**Comment by rowanmiller** [comment]
Hey,

As @smitpatel already covered, you are ending up with one-to-many relationships with ParentA/ParentB being the principals/parents. Below is one way to setup your classes so that EF will discover a one-to-one relationship by convention.

More info at http://docs.efproject.net/en/latest/modeling/relationships.html#one-to-one

```
public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }

    public int ParentAId { get; set; }
    public ParentA ParentA { get; set; }

    public int ParentABd { get; set; }
    public ParentB ParentB { get; set; }
}

public class ParentA
{
    public int Id { get; set; }
    public Child Child { get; set; }
}

public class ParentB
{
    public int Id { get; set; }
    public Child Child { get; set; }
}

public class Context : DbContext
{
    public DbSet<ParentA> ParentA { get; set; }
    public DbSet<ParentB> ParentB { get; set; }
}
```

~Rowan

**Comment by Tragetaschen** [comment]
I haven't been able to get it working by convention with your example (with the obvious typo fixed :) ). No matter what I tried, I ended up with Child-HasOne-Parent-WithOne in the Model Snapshot. Sometimes even with an additional Child-HasOne-Parent-WithMany.
Only with the fluent API, I was able to create the model I wanted.
```csharp
modelBuilder.Entity<ParentA>()
    .HasOne(x => x.Child)
    .WithOne()
;
modelBuilder.Entity<ParentB>()
    .HasOne(x => x.Child)
    .WithOne()
;
```

**Comment by Tragetaschen** [comment]
However, in this constellation, I'm back to the NOT NULL constraint failed exception when I do
```csharp
var entry = new ParentA
{
    Child = new Child { Name = "Foo" },
};
db.ParentA.Add(entry);
db.SaveChanges();
```

When I start adding explicit `HasForeignKey<Child>(x=>x.Id)` in model builder to both parents, the Model Snapshot starts becoming outright weird:
Child-HasOne-ParentB-WithOne and ParentA-HasOne-Child-WithMany

**Comment by smitpatel** [comment]
Model classes:
````c#
public class Child
{
	public int Id { get; set; }
	public string Name { get; set; }

	public int ParentAId { get; set; }  // Navigation name + "Id"
	public ParentA ParentA { get; set; }

	public int ParentBId { get; set; }  // Navigation name + "Id"
	public ParentB ParentB { get; set; }
}

public class ParentA
{
	public int Id { get; set; }
	public Child Child { get; set; }
}

public class ParentB
{
	public int Id { get; set; }
	public Child Child { get; set; }
}
public class MyContext : DbContext
{
	public DbSet<ParentA> ParentA { get; set; }
	public DbSet<ParentB> ParentB { get; set; }
}
````
Above classes generate following in `MyContextModelSnapshot.cs`
````c#
modelBuilder.Entity("TestApp.Child", b =>
	{
		b.HasOne("TestApp.ParentA")
			.WithOne()
			.HasForeignKey("TestApp.Child", "ParentAId");

		b.HasOne("TestApp.ParentB")
			.WithOne()
			.HasForeignKey("TestApp.Child", "ParentBId");
	});
````
As snapshot suggests both foreign key has been defined on `Child` class. That is because there are properties in `Child` class which match navigation + "Id" (primary key of Parent). Also notice `HasOne().WithOne()`, this is due to the fact that reference navigations have been specified in both directions. I suppose this is the model you want to have.

Based on the navigation property from Principal to Dependent, multiplicity of the relationship is decided. For one-to-many relationship it is collection navigation, for one-to-one it is reference navigation. Dependent to Principal navigation is always reference navigation (till many-to-many support is added in EF7).
When you provide only one navigation property, then
- If it is collection type then there is no ambiguity. It is principal to dependent navigation for a one-to-many relationship.
- If it is reference type then there are 2 things possible:
  1. It is principal to dependent navigation - This means it is one-to-one relationship.
  2. It is dependent to principal navigation - In this case since we don't have Principal to Dependent navigation available and we assume it to one-to-many relationship.

When there is only one navigation is provided for relationship building, we use it as dependent to principal navigation hence making it one-to-many relationship. That is what happening in the model you provided in very first post. Parent classes become dependent.

When both the navigation are specified then multiplicity can be easily decided. But for one-to-one relationship, principal-dependent sides are still ambiguous. The user can specify dependent side by either putting `ForeignKeyAttribute` on a property on dependent side or using fluent API to configure foreign key properties. If nothing is specified by the user then following rules are followed by EF to determine principal/dependent side in the specific case of one-to-one relationship.
(ref: https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs#L69)
1. If there is matching property(-ies) present in entity type then it is dependent type. Matching property(-ies) should be in form of (NavigationName/PrincipalEntityName/"" + CorrespondingPrincipalPropertyName). If there is only one property then it also checks with "Id" in place of principal property name. 
2. If matchies properties are not found either side, then existence of navigations is checked. If there is only one navigation is specified then we try to use the navigation as PrincipalToDependent navigation.
3. If sides are still not clear then we try to find the entity type which is being referenced by other entity types. If an entity is principal for one relationship then chances are higher for it to be principal for other relationships.
4. If none of above works then we just use string comparison on class names so that choice of side is deterministic.

In the example provided by Rowan,
`Child` has property named `ParentAId` which matches NavigationName+PrincipalKeyPropertyName (since `Id` is primary key of `ParentA` and principal key for relationship). Due to this `Child` will be dependent side for the relationship with `ParentA`. If there was a property named `ParentBId` in `Child` then `ParentB` will also be principal using `ParentBId` as foreign key property. Since there is a typo as `ParentABd`, for relationship between `Child` & `ParentB`, rule 1 fails. Since both navigations are present  rule 2 fails. Due to the ordering of the discovery of entity types, `ParentB` forms relationship before `ParentA` therefore rule 3 also fails. Hence due to alphabetical order `Child` is determined to be principal side of relationship with `ParentB`.
Following is the relationship configuration in model snapshopt in the presence of typo
````c#
modelBuilder.Entity("TestApp.Child", b =>
	{
		b.HasOne("TestApp.ParentA")
			.WithOne()
			.HasForeignKey("TestApp.Child", "ParentAId");
	});

modelBuilder.Entity("TestApp.ParentB", b =>
	{
		b.HasOne("TestApp.Child")
			.WithOne()
			.HasForeignKey("TestApp.ParentB", "Id");
	});
````
The only time one-to-many relationship is configured if there is only 1 navigation available. In the presence of both direction reference navigations in same relationship, it is always shown as `HasOne().WithOne()` in snapshot.

The Fluent API configuration:
````C#
modelBuilder.Entity<ParentA>()
    .HasOne(x => x.Child)
    .WithOne();

modelBuilder.Entity<ParentB>()
    .HasOne(x => x.Child)
    .WithOne();
````
Above specifies 2 one-to-one relationships in the model both of them having only one navigation. If you have not removed the opposite navigations in `Child` class as provided in Rowan's example, then you will end up having 2 more one-to-many relationships for those navigations. Now the configuration above states that both relationships are one-to-one but still it is not telling which side the foreign key properties reside. Hence there is ambiguity which conventions have to resolve. If you take model as initial post then all fails and rule 4 will determine `Child` to be principal side for both of the relationship.

When you try to use `HasForeignKey<Child>(x => x.Id)` to both relationship configuration then first it will set `Id` as foreign key for `ParentA` relationship but when you use the same foreign key property for relationship with `ParentB` it will change foreign key property for `ParentA`. At present EF7 does not support using same set of properties for multiple relationships. (see #3551). Since there is only one navigation specified for ParentA-Child relationship, it is converted to one-to-many relationship while replacing the fk property. It should have preserved the uniqueness (bug? @AndriySvyryd) though there will be shadow property created for fk. Following is the model snapshot
````c#
modelBuilder.Entity("TestApp.Child", b =>
	{
		b.HasOne("TestApp.ParentB")
			.WithOne()
			.HasForeignKey("TestApp.Child", "Id");
	});

modelBuilder.Entity("TestApp.ParentA", b =>
	{
		b.HasOne("TestApp.Child")
			.WithMany()
			.HasForeignKey("ChildId");
	});
````

The scenario:
````c#
var entry = new ParentA
{
    Child = new Child { Name = "Foo" },
};
db.ParentA.Add(entry);
db.SaveChanges();
````
Above will only work when `ParentA` is principal and `Child` is dependent. i.e. relationship configured in snapshot as  follows: 
````
b.HasOne("TestApp.ParentA")
	.WithOne()
	.HasForeignKey("TestApp.Child", "ParentAId"); /* 2nd argument - the name of property can be different based on how it is configured */
````
If above is not how the relationship is configured in model snapshot then it will throw exception stating NOT NULL constraint failed since the `Child` will not be stored to the database.

**Comment by Tragetaschen** [comment]
@smitpatel Thank you for that explanation. That's really awesome!

However, I cannot wrap my head around this.

When I take my initial model and look at how it is baked into a schema by the SQLite provider, I'm seeing what I actually want. A `Child` table, two parent tables and those parent tables contain a `ChildId` field with a foreign key constraint. That's what I want to model with my classes. However, in that scenario, adding just a parent won't add the Child, it has to be added explicitly. I'm doing this in my own application.

When I start adding the navigation properties to `Child`, the database schema becomes much more convoluted and moves away from what I would expect (no more `ChildId` in the parents) and when I add a parent using the SQLite provider, I end up with a Foreign Key exception.

**Comment by smitpatel** [comment]
Initial model makes Child table principal and Parent tables dependent. Adding Child will add relevant parents but adding parent won't add the Child and it has to be done explicitly.

When you add navigation properties to `Child`, EF will have more information to build relationship. With this new model, since there are navigation in both directions, EF can determine one-to-one & one-to-many accurately without making assumption of it being one-to-many. In case of one-to-one, EF will try to determine the principal/dependent side which can be different than initial model. It all depends on the kind of information provided but above rules will govern the relationship building.

In case of ambiguity, the best thing to do is configure relationship explicitly.

**Comment by Tragetaschen** [comment]
Ok, I think I got it (after reading the provided information every other day :) ).

Given my initial example, it's an explicit design decision by EF to configure the `Child` as principal and both `Parent`s as dependents. This decision is necessary because the model as it is shown doesn't offer enough information given the current set of rules. I tend to disagree, due to the `[Required]` attribute, but I can see the problem.

This decision, however, results in the `Add()` method to fail, because with the default for `GraphBehavior`, only dependents would be added automatically, which `Child` isn't.

Here is why I had (and still have) such hard time getting this:
In my application, I have different types of measurement data and some common side-channel data for all measurement types. If I envision the IMO most natural database schema for that, I would have a table for the side-channel data and for each type of measurement another table with a foreign key to the side-channel data. With POCO objects, I would have a class holding the side-channel data and a member ("has-a") of that type in each of the measurement data types. This is where EF and I agree, because my POCO objects map exactly to the database schema I expect. That's great!

When I now take all that and look at what `Add` does, it's super, super surprising to see it fail and once I start digging into solutions, everything falls apart.
1) If i gave my `ParentA` POCO object and the database schema to someone and ask her to "put the object in the database", I'd like to think there is a completely natural way to do this and every human programmer would probably get it right without any additional information.
2) I cannot make it work in EF without losing the most natural representation I outlined above. There is no way of telling the modelBuilder that my measurement data types (`Parent*`) are the principals. For example doing 
```csharp
modelBuilder.Entity<ParentA>()
    .HasOne(x => x.Child)
    .WithOne()
    .HasForeignKey<Child>(x => x.Id)
;
modelBuilder.Entity<ParentB>()
    .HasOne(x => x.Child)
    .WithOne()
    .HasForeignKey<Child>(x => x.Id)
;
```
results in the weirdest thing.
3) The only working solution entirely "taints" the side-channel data (`Child`) so it now references *all possible* measurement data types (`Parent*`). Not only is that unnatural (to say the least), but it's also a lot more to type and scales really badly: When I add another measurement type, I have to change the side-channel data and as a result change the database schema. Something that's not necessary at all in the natural schema outlined above.

Remember: all that is only necessary to "fix" the principal/dependent that breaks `Add()`. That's a really high cost!

**Comment by ajcvickers** [comment]
In number 2 above you are doing the correct thing, but this doesn't work because of #3551. Once #3551 is fixed, then you will be able to correctly tell EF that Child.Id is the FK for both relationships, and hence Child will be the dependent in both relationships.

**Comment by Tragetaschen** [comment]
Thanks! I was losing my mind over what I saw as database schema :)

But then an additional attribute could make this entirely discoverable by EF:
```csharp
[Dependent, Required]
public Child Child { get; set; }
```
And would have the same semantics as the modelBuilder construct.

**Comment by soroshsabz** [comment]
> Thanks! I was losing my mind over what I saw as database schema :)
> 
> But then an additional attribute could make this entirely discoverable by EF:
> 
> ```cs
> [Dependent, Required]
> public Child Child { get; set; }
> ```
> 
> And would have the same semantics as the modelBuilder construct.

What is the equivalent in EF Core 7?
