### ISSUE TITLE
Issue about One-to-One by Single Navigation Property

### ISSUE THREAD

**Issue by vincedan** [dotnet/efcore#4046]
Hi,
right now my sourcecode is based on EF6 and can implement one to one with single navigation property. but I could not achieve the same result on EF7. below is the details:
1) requirements:
 table Object1 has one to one relationship with Table DisplayNames(no foreignkey constrant)
table Object2 also has one to one with Table DisplayNames.  Id(Guid) is PK for Object1,Ojbect2 and DisplayNames.  the Id of DisplayNames also should be logically  foreignkey..

2) Based on EF6 everything is perfect.

``` c#
   public partial class Object1
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public DisplayName DisplayName { get; set; }
    }

    public partial class Object2
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public DisplayName DisplayName { get; set; }
    }

    [Table("DisplayNames")]
    public partial class DisplayName
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }

        [Required]
        public string ChineseName { get; set; }
    }

    public partial class Model1 : DbContext
    {
        public Model1()
            : base("name=Model1")
        {
        }

        //public virtual DbSet<DisplayName> DisplayName { get; set; }
        public virtual DbSet<Object1> Object1 { get; set; }
        public virtual DbSet<Object2> Object2 { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<Model1>(null);
            modelBuilder.Entity<Object1>().HasOptional(e => e.DisplayName).WithRequired();
            modelBuilder.Entity<Object2>().HasOptional(e => e.DisplayName).WithRequired();

        }
    }
           using (var db = new Model1())
            {
                Object1 o1 = new Object1
                {
                    Name = "Object1",
                    DisplayName = new DisplayName
                    {
                        ChineseName = "ChineseName Object1"
                    }
                };
                // add one record  in Object1, add onre record in DisplayNames
                db.Object1.Add(o1); db.SaveChanges();

                Object2 o2 = new Object2
                {
                    Name = "Object1",
                    DisplayName = new DisplayName
                    {
                        ChineseName = "ChineseName Object2"
                    }
                };
                // add one record  in Object2, add onre record in DisplayNames
                db.Object2.Add(o2); db.SaveChanges();

            }
```

3) on EF7, issue ourred.... although I replace the above code with new API like the following sample
`modelBuilder.Entity<Object1>().HasOne<DisplayName>(b => b.DisplayName).WithOne();`  

my problem is: I can not add navigation property on DisplayName side because it is used by many tables such as Object1 Object2~ ObjectN. When I add [foreignkey] on DisplayName property of  Object1, only one record add in Object1 and no  related record can be inserted in DisplayName.
How to implement these One-to-One by Single Navigation Property on EF7?

**Comment by rowanmiller** [comment]
@vincedan single navigation properties are supported on EF7 and the syntax you have is correct. Perhaps you can elaborate on the error you are seeing?

**Comment by vincedan** [comment]
@rowanmiller  sorry for missing info.  When I move source code of step 2) above from EF6 to EF7 (of course use HasOne&WithOne fluentAPI), after running, EF7 wanna execute the following sql mdl.

exec sp_executesql N'SET NOCOUNT OFF;
INSERT INTO [Object1] ([Id], [DisplayNameId], [Name])
VALUES (@p0, @p1, @p2);
SELECT @@ROWCOUNT;
',N'@p0 uniqueidentifier,@p1 nvarchar(4000),@p2 nvarchar(4000)',@p0='B4EC6026-B688-4636-CB7B-08D302685F9B',@p1=NULL,@p2=N'Object1'
field 'DisplayNameId' is not existing in DB and return related exception..

I try to add [ForeignKey("Id")] on DisplayName property of Object1, then no error return, but the result is not correct: only insert a record in Table Object1, no record added in Table DisplayNames.and in memory, the inserted record successfully in Object1 has a DisplayName object with ID is Guid.Empty.

**Comment by smitpatel** [comment]
The relationships are one to one relationship and the explicit configuration does not specify which one is dependent end. Therefore the conventions will determine the dependent end and that's where EF6 & EF7 have different behavior. Hence the relationships generated are different.
In EF6, the `DisplayName` is dependent end for both the relationships.
In EF7, by conventions, `DisplayName` is configured to be principal end since it is being referenced by multiple relationships. This creates shadow foreign key property on `Object1` side named `DisplayNameId` which is the cause of the exception in generated SQL since database does not have that column.
When you try to add `[ForeignKey("Id")]` on `DisplayName` navigation of `Object1`, since `ForeignKeyAttribute` can be used in either navigations, it does not determine the principal end. But it enforces `Object1` to use `Id` as foreign key property instead of creating shadow property `DisplayNameId`. Due to this the generated SQL does not throw exception. The incorrect result is due to the Add behavior with IncludeDependents.

**Comment by smitpatel** [comment]
Resolution of #3724 would be applicable here also.
For incorrect result, https://github.com/aspnet/EntityFramework/issues/4035#issuecomment-164060567

**Comment by vincedan** [comment]
@smitpatel  that's it. different depand and principal default behivour. I also config the wrong end by foreignkey attribute(It should be on displaynames side.)
1) right now it does work after I adopt fluent API. modelBuilder.Entity<Object1>().HasOne<DisplayName>(b => b.DisplayName).WithOne().HasForeignKey<DisplayName>(c=>c.Id);

2) in addition, understand it more clearly that ForeignKeyAttribute can not decide depand or principal.. even add this attribute on Id property of table DisplayNames.
Thanks @smitpatel & @rowanmiller 's answer.

**Comment by vincedan** [comment]
@smitpatel that's it. different default behivour for setting depand and principal . I also config the wrong end by foreignkey attribute(It should be on displaynames side.)
 1) right now it does work after I adopt fluent API. modelBuilder.Entity().HasOne(b => b.DisplayName).WithOne().HasForeignKey(c=>c.Id);

2) in addition, understand it more clearly that ForeignKeyAttribute can not decide depand or principal.. even add this attribute on Id property of table DisplayNames.
 
3) FluentAPI-> HasForeignKey()  is not the same as ForeignKeyAttribute (If my understanding is wrong, please correct me : )

**Comment by smitpatel** [comment]
2) `ForeignKeyAttribute` can determine dependent end only when it is used on the foreign key property. Since we know where is the property, we know that is the dependent end. Though to use it that way, you require dependent to principal navigation which ForeignKey refers to and it cannot be used with composite foreign key this way. In your case since `DisplayName` does not have navigation to principal, `ForeignKey` cannot help.

3) FluentAPI-> HasForeignKey is more explicit way to define the foreign keys. It takes all the required components so that there is no ambiguity. Hence using it makes you to specify the dependent end for one-to-one foreign key on which the properties reside.

`ForeignKeyAttribute` has various limitation in expressing the relationship fully
- Since it refers to navigation or fk property, it requires them to be defined. Hence to have it on property, you must have dependent to principal navigation.
- Using it on navigation it doesn't specify the principal end. It gives only property name for which EF has to search on both the side to see where it exists and determine the principal-dependent ends with conventional rules. 
- To define composite FK, you must write it on navigation only.

Therefore, when annotations are used, there can be some missing pieces which convention tries to fills in based on the information available. Which may not always matches with the user expectations.

**Comment by vincedan** [comment]
@smitpatel , thanks for your deep elaboration for foreignKeyAttribute and related EF implmentation mechnism. 
I repen this issue because I found, if I configure both Object1 and Object2 like the below,

            modelBuilder.Entity<Object1>().HasOptional(e => e.DisplayName).WithRequired();
            modelBuilder.Entity<Object2>().HasOptional(e => e.DisplayName).WithRequired();

when I want to add object1 with child displayname,  the same error happened again --> {ColumnName DisplayName_Id is invalid}

**Comment by vincedan** [comment]
@smitpatel , thanks for your deep elaboration for foreignKeyAttribute and related EF implmentation mechnism. 
I repen this issue because I found, if I configure both Object1 and Object2 like the below,

            modelBuilder.Entity<Object1>().HasOne<DisplayName>(b => b.DisplayName).WithOne().HasForeignKey<DisplayName>(c => c.Id);
            modelBuilder.Entity<Object2>().HasOne<DisplayName>(b => b.DisplayName).WithOne().HasForeignKey<DisplayName>(c => c.Id);

when I try to add Object1 with child Displayname,  the same error happened again --> {ColumnName DisplayName_Id is invalid}  

if only one configure, no error.
            modelBuilder.Entity<Object1>().HasOne<DisplayName>(b => b.DisplayName).WithOne().HasForeignKey<DisplayName>(c => c.Id);

**Comment by smitpatel** [comment]
You are trying to use the same property `Id` as foreign key for 2 different relationships, that scenario is blocked by #3551. Therefore when you configure second relationship to use `Id` property, it will remove the foreign key property for the first one and create shadow property named `DisplayNameId` for it. If you specify only one configuration then the other relationship will have shadow property `DisplayNameId`.

**Comment by vincedan** [comment]
@smitpatel  thanks.. I close this one  and waiting new release to solve it
