### ISSUE TITLE
Cannot execute .Where(x => SomeArray.Contains(x.SomeVirtualEntity.SomeProperty))

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#4118]
```
        var Areas = new string[] { "A1", "A2" };
        var tmp = DB.Houses
            .Include(x => x.Building)
            .ThenInclude(x => x.Estate)
            .Where(x => Areas.Contains(x.Building.Estate.Area))
            .Select(x => x.Account)
            .Distinct()
            .ToList();
```

![image](https://cloud.githubusercontent.com/assets/2216750/11871266/61053e20-a509-11e5-82aa-4db936bd0762.png)

**Comment by divega** [comment]
@Kagamine it would help if you could provide the full stack trace in text and also a full repro.

Besides that I can see several things that I think could go wrong this this query:

1. I don't think we will support using `Include()`/`ThenInclude()` and then changing the shape of the results of the query as you do in the `Select()`. Include is really about telling EF to materialize additional entities along side the result.
2. The `Include()` and `ThenInclude()` calls shouldn't actually be necessary in this query because we should be capable of translating the navigation properties used in the `Where() operator`.
3. I am not sure what `Account` is in your model. If it is another navigation property (i.e. if it points to another entity) then I am not sure `Distinct()` will work.
