### ISSUE TITLE
Take then Skip not work.

### ISSUE THREAD

**Issue by mikeandersun** [dotnet/efcore#4127]
This code work and return next page.

```
 int offset = (pageSize * pageNumber) - pageSize;
            var query = _dbContext.Customer
                  .Select(b =>  new Customer
                  {
                      Title = b.Title
                  })
          .Skip(offset)
           .Take(pageSize);
```

But this code don't work and don't return next page.

```
 int offset = (pageSize * pageNumber) - pageSize;
            var query = _dbContext.Customer
                  .Select(b =>  new Customer
                  {
                      Title = b.Title
                  })
           .Take(pageSize)
            .Skip(offset);
```

This is a bug?!

**Comment by qujck** [comment]
what values are you using for `pageSize` and `offset`? If you take 50 and then skip 50 logically there's nothing left ....

**Comment by mikeandersun** [comment]
`offset is` 10 and `pageZise` is 10 and `pageNumber` is 2 . The problem is usage order of `Skip` and `Take` when pageNumber is grater than 1.
The first code work fine.

**Comment by buraktamturk** [comment]
isn't it supposed to do that? since when pageNumber is 2 and pageSize is 10 the offset becomes 10 ((2 * 10) - 10). You take 10 items from database then you call skip(10) on the data you got from there, no data left after you do that. I think you want to do the first approach because you actually want to skip offset rows from the database then get the top pageSize data from it.

**Comment by qujck** [comment]
@buraktamturk Exactly!

**Comment by mikeandersun** [comment]
thanks
