### ISSUE TITLE
Perf: EF's usage of DI possibly causing significant overhead on context per request scenarios

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#4133]
@DamianEdwards detected significant overhead on `GetService<T>()` calls while profiling controllers that use EF in [ASP.NET Benchmarks](https://github.com/aspnet/benchmarks). 

Initial investigation seems to indicate that one of the patterns we use in our service collection builder extensions with scoped services may prevent DI from leveraging its caching, e.g.:

``` C#
builder.GetInfrastructure() 
    .TryAdd(new ServiceCollection() 
...
    .AddScoped(p => GetProviderServices(p).ParameterNameGeneratorFactory)
```

cc @halter73 @ajcvickers @lodejard

**Comment by halter73** [comment]
I ran both tracing and sampling profiles using dotTrace against the [SingleQueryEfMiddleware in the Benchmarks repo](https://github.com/aspnet/benchmarks/blob/4e51e962578d91e2b78b6ba0707ceebaea92a8c7/src/Benchmarks/SingleQueryEfMiddleware.cs). A quick overview of dotTrace's "Hot Spots" shows that a lot of time is being spent in GetService:

![image](https://cloud.githubusercontent.com/assets/54385/12369091/60f36236-bba7-11e5-8b9a-f7dd5bb370f5.png)

![image](https://cloud.githubusercontent.com/assets/54385/12369220/d68672c6-bba8-11e5-97c0-c0b2ed82555a.png)

    Running 2m test @ http://10.0.0.100:5001/db/ef
      32 threads and 256 connections
      Thread Stats Avg      Stdev Max   +/- Stdev
    Latency   171.55ms  107.55ms 913.55ms   65.28%
        Req/Sec   470.98    117.20     1.41k    73.15%
      1499277 requests in 1.67m, 221.48MB read
      Socket errors: connect 0, read 0, write 298, timeout 0
    Requests/sec:  14977.91
    Transfer/sec:      2.21MB

(Sampling results above)

It also shows 24% of the time spent in GetService is spent calling methods in the System.Collections(.Generic) namespace. For example 6.5% of time in GetService is spent in Resize, 4.5% is spent in FindEntry, etc... There might be some small changes in the DI project to improve performance (like a larger default size for some of our dictionaries), but the primary problem in my eyes is that there are simply too many recursive calls to GetService.

![image](https://cloud.githubusercontent.com/assets/54385/12369306/f65b94c2-bba9-11e5-981e-c265d79225f4.png)

![image](https://cloud.githubusercontent.com/assets/54385/12369349/7d234f54-bbaa-11e5-8afb-a4ad97e64338.png)

    Running 2m test @ http://10.0.0.100:5001/db/ef
      32 threads and 256 connections
      Thread Stats Avg      Stdev Max   +/- Stdev
    Latency   205.26ms  565.28ms   2.00s     0.00%
        Req/Sec    41.92     15.48   131.00     66.94%
      132712 requests in 1.67m, 19.72MB read
      Socket errors: connect 0, read 0, write 413, timeout 8181
    Requests/sec:   1326.02
    Transfer/sec:    201.73KB

(Tracing results above)

The first screenshot of the tracing results show the callers to GetService, but don't trust the call count that is given (934,007) because recursive calls are "unfolded" by dotTrace. When I "fold" the recursive calls you see the true number of calls to GetService which is: 9,072,935 or about 68 calls to GetService per request.

When services are injected into another service by DI via the constructor, the are no additional calls to GetService. All of the recursive calls to `GetService` are made by anonymous methods in [EntityFrameworkServiceCollectionExtensions](https://github.com/aspnet/EntityFramework/blob/abbadc904a623cbd2fa576125e5c06c47c3709b2/src/EntityFramework.Core/EntityFrameworkServiceCollectionExtensions.cs).

The reason this is so bad is because this causes an [additional lookup](https://github.com/aspnet/DependencyInjection/blob/e1fcc739fc8e5602caacd761901222f22b777fc1/src/Microsoft.Extensions.DependencyInjection/ServiceProvider.cs#L56) in a `ConcurrentDictionary` for a compiled expression tree that is used to resolve the service. If the services were defined as a type instead of a factory that calls GetService, the expression trees would be merged and compiled together which would remove the calls to `RealizedServices.GetOrAdd`.

Oh, the last screenshot shows that despite being called "only" once per request, 25% of the total time spent in GetService is spent in the `SqlConnectionStringBluilder` constructor, so you can probably get a nice perf boost by just optimizing that.

**Comment by divega** [comment]
@halter73 thanks for the analysis! 

@anpete should this be assigned to you for now since I see you have been addressing some of the findings?

**Comment by ajcvickers** [comment]
@divega I have some ideas to look into, but doing perf work is such a pain right now.

**Comment by anpete** [comment]
@divega I've addressed the low-hanging fruit :-)

**Comment by divega** [comment]
Thanks. Assigned to @ajcvickers hoping things can be less painful soon.

BTW from @halter73's analysis above I suspect this benchmark must have improved already with https://github.com/aspnet/EntityFramework/pull/4139.

**Comment by ajcvickers** [comment]
Marking for re-triage.

I have not been able to come up with any way to change the way EF uses the service provider while still maintaining the functionality and experience we need.

These services are fundamentally dynamic in that different implementations are returned depending on how the current instance of the context is configured. This is why there is a delegate registered in D.I. Coupled with the scope created for the context instance, the delegate handles returning the correct implelemtation of the service for that context instance. This is done transparently to other services which just need to depend on the service contract in the normal way.

**Comment by bricelam** [comment]
**Triage:** Closing. We've made improvements where possible. Further changes would require a fundamental change to EF's architecture.
