### ISSUE TITLE
Implement Repository & UnitOfWork pattern with Entity Framework is implement itselft

### ISSUE THREAD

**Issue by rustd** [dotnet/efcore#4160]
Porting from ASP.NET UserVoice site
https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/8173092-implement-repository-unitofwork-pattern-with-ent

DbContext is a combine of UnitOfWork an Repository pattern. Why we should implement itself when dev mvc app?

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This isn't a bug report or feature request. For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). Questions about how to use Entity Framework are best asked on [StackOverflow](http://stackoverflow.com/).

That said... here is a quick answer... There is no need to implement them. Some people chose to because they want absolute control over the surface of the repositories and/or because they want to abstract away the fact that EF is being used as the data access technology. But this is by no means a requirement.
