### ISSUE TITLE
Attached: "translated" Add-Migration to VB

### ISSUE THREAD

**Issue by marcioqmaciel** [dotnet/efcore#4210]
Hi bricelam

Follow the VB version of Migrations in zip file:
[EF-Migrations-VB.zip](https://github.com/aspnet/EntityFramework/files/76902/EF-Migrations-VB.zip)

4 files: VBHelper, VBMigrationOperationGenerator, VBMigrationsGenerator and VBSnapshotGenerator.

Some doubts in VBHelper = CSharpHelper
Any "____keyword" in VB like "__arglist" in C#? I dont remember.

In "public virtual string Lambda([NotNull] IReadOnlyList<string> properties)" you are wanting to create a lambda, and if properties.Count > 1 then "new ??? { .... }". I am lost here. Please, can you write the generated lambda code, in C#? My translation:

x => x.prop    /    Function(x) x.prop
x => new {x.prop1, x.prop2}    /   Function(x) New From {x.prop1, x.prop2}

Its correct?

In "public virtual string Literal([NotNull] string value)" you are replacing \r\n? I'm lost again.
In VB dont need @"" \ and etc... In what situation would expect to find a NewLine in a VB String?

In "public virtual string Literal([NotNull] IReadOnlyList<string> values)" you use "new[]". ????? =)
New String()? New From {...}?

Questions:
- can you help me to finish VBHelper?
- need "translate" others files? maybe "...Commands/Scaffolding/Internal/CSharpUtilites.cs"?
- how compile and try this "Install-Package CommandsWithVBMigration"? Compile and send to Nuget?
- how tell to Add-Migration use VB version?

Hugs from Brasil

**Comment by rowanmiller** [comment]
Hey @midnait,

Just to set expectations... one of the reasons that we scoped features (such as VB.NET support) out of our first release is due to time constraints and the need to focus on finishing and stabilizing the features we have. To that end, we aren't going to be able to spend too much time helping others implement these feature either. Don't get me wrong, we're happy to answer a question here and there.

If this is something that you want to contribute to the code base, then contributions are handled via pull requests (rather than attaching code). 

~Rowan

**Comment by midnait** [comment]
Hi @rowanmiller, @bricelam 

I can contribute via PR, but first I need understand the code. =)  And this is not "code", but "pieces of generated code". I can spend very time trying understand why AppendLine("new ") or he just say "hey, the generated code will be 'x => x.prop1;', mount in VB now. =)

See, my doubts about "code" are only in 3 lines in Helper. 99% is done. Open PR with 99% done?

Still in my others questions: open PR without test before? missing necessary files?

Hugs

**Comment by rowanmiller** [comment]
Hey @midnait,

Sorry for any misunderstanding... I wasn't suggesting that you open a Pull Request with your work so far. I was just saying that when you have something working then that is when we would take a detailed look at the code via a PR.

We discussed this today and we aren't really ready to start taking VB.NET support contributions because there is work needed in various other places too in order to have proper support. The biggest area is query, where the VB.NET and C# compilers can result in different expressions and we will need to additional logic to handle LINQ queries from VB.NET. We don't want to start taking migrations contributions and then have a half-finished VB.NET implementation in an RTM release.

Like you also mentioned, there are some sizable design questions around this feature (such as "how does Add-Migration work out which code generator to use").

Given all of this, and the need to focus on critical bugs at this stage in the release, we aren't really going to invest any cycles into the feature (or helping to implement it) at this stage. If you want to keep plugging away at it and coming up with proposals on how to solve some of the design questions, then we'd be happy to look at taking it post-7.0.0.

Sorry that isn't really the response you were after. We are just really having to focus our efforts at the moment to make 7.0.0 as stable as we can.

~Rowan

**Comment by HClausing** [comment]
How can I use these translated migration on my projects? If not possible, Can I create a class lib. on my Project (in C#) just for store migrations? (keeping model and dbcontext on main vb.net Project).

Thanks

**Comment by bricelam** [comment]
@HClausing The C# class library should work just fine. You may need to generate the C# files into your project with the `DbContext` first, then move them into the class library.

**Comment by HClausing** [comment]
Thanks!

**Comment by cwesterlund** [comment]
Been trying to do what @HClausing is doing but the migration is not working. A database is created but not with any of my tables in it, just the migrationhistory table.

I got it to work a couple of months ago, but that time I translated the migrations classes to vb.net. Since there was other issues I used another SQLite provider at the time but thought to give it another shot now since it isn't preview anymore.

**Comment by HClausing** [comment]
@cwesterlund , I just call dbContext.Database.Migrate() **instead of** dbContext.Database.EnsureCreated().

During translation stage, I have used this site to do the jog, and it create sub lambas with Function(b). I have replaced this by Sub(b), and fixed some composite PK's.

Please try again, good luck.

If does not work, let me know, that'll help.

**Comment by cwesterlund** [comment]
Hi @HClausing, So if I understand you correctly you converted the generated C# classes to VB.NET and stored them in the same project as the DBContext?
That is not the issue, I got that working a couple of months ago. The thing I want to do is use the generated C# classes without converting them to VB.NET. I thought @bricelam suggested that it be put in a separete C# project? But they are not used during the migrate call.

This is my class structure:
App.proj  (main UWP project)
Model.proj (Main vb.net model project with dc and DBContext)
Model_CS.proj (The new C# project where I store the generated migration classes in a sub-folder "Migrations")

Then during start up I call a function in the Model_CS project that calls DBContext.Database.Migrate on the DBContext class in Model.proj.

**Comment by HClausing** [comment]
Hi @cwesterlund.

I'm sorry for misunderstood.

Have you ever tried to move your DbContext for C# Project? I believe this way will work.

Translating your dbcontext to c# is easier than translate the migrations to vb.net.

**Comment by bricelam** [comment]
@cwesterlund Are you missing the following?
```VB
contextOptions.UseSqlServer(...)
    .MigrationsAssembly("MyCSharpClassLibrary")
```

**Comment by cwesterlund** [comment]
Hi @HClausing and @bricelam 

No, i missed that option but it makes no difference, the C# assembly is CASTS_MODEL_CS:

    Protected Overrides Sub OnConfiguring(optionsBuilder As DbContextOptionsBuilder)
            optionsBuilder.UseSqlite($"Filename=" & DBManager.DatabaseRelativePath, 
                 Sub(ob As Infrastructure.SqliteDbContextOptionsBuilder)
                    ob.MigrationsAssembly("CASTS_MODEL_CS")
                 End Sub)
    End Sub

**Comment by cwesterlund** [comment]
Ok, now it suddenly works. Don't know what I did. I tried to move the DBContext to the C# project but realized that if I did that I would have to move the DAL classes also so I reverted and then it suddenly worked and the migration classes was in use.

Thanks @HClausing and @bricelam
