### ISSUE TITLE
InMemoryDatabase testing results are unexpected

### ISSUE THREAD

**Issue by bastienJS** [dotnet/efcore#4216]
Hello EF team,

I tried EF 7 testing with InMemoryDatabase today and I compared it to a real integration test with sqlexpress database.

Either I do not understand the concept of InMemoryDatabase or this feature is somehow not working correctly.

When you have 3 entities: Schoolclass 1 to N Pupil to M Subject and run this query:

await context.Schoolclasses.Include(s => s.Pupils).ToListAsync();

On the REAL database => then I get all schoolclasses including pupils 

On the INMEMORY database => then I get all schoolclasses including pupils AND subjects

Both databases got seed data of course.

How can the .Include logic work, for InMemoryDatabase when the context is seeded with data already?

Would you please shed some light on this topic? :-)

**Comment by rowanmiller** [comment]
@bastienJS are you using a different context that the one you used to seed the in memory database? One possible explanation would be that you are using the same context that you used to seed... and therefore regardless of the Include call you already have that data in the context. But that may not be the issue... because you would get the same behavior against any database.

**Comment by bastienJS** [comment]
ah stupid me I passed the same context...now I created a method for the context creation ;-)
