### ISSUE TITLE
ExecuteSqlCommand when using InMemoryDatabase

### ISSUE THREAD

**Issue by Aleksanderis** [dotnet/efcore#4270]
I'm trying to execute some raw SQL Update queries. It works with SqlServer, but not with InMemoryDatabase. Is there any way to workaround it with InMemoryDatabase?

Currently it throws following exception:

> Result StackTrace:
> at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
> at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
> at Microsoft.Data.Entity.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
> at Microsoft.Data.Entity.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, String sql, Object[] parameters)
> Result Message:
> No service for type 'Microsoft.Data.Entity.Infrastructure.RelationalSqlExecutor' has been registered.

Looks like it's obviously not supported - is it by design, or is it planned to be supported a bit later? Might be there is something that should be configured additionally to make it work?
I'm kind of suspecting there is almost no sense to execute raw SQL for in-memory data, but it would be good to have at least some way to mock it.

Or should I use SqlServer provider for such tests with some rollbacking (it would be more like integration tests)? Such raw SQL execution is indeed not will be used everywhere, just in 1-2 places, but these places might be quite critical.

**Comment by divega** [comment]
InMemory is a rather simple store designed for simple testing scenarios. There is no SQL query processor and therefore raw SQL APIs are by design out of the scope of what is supported. 

We can discuss the priority of improving the exception in triage. 

We can also discuss if there is anything we should do differently to help improve testability of these APIs, but my first reaction is that using a real in-memory relational database such as SQLite in-memory mode or creating your own repository abstraction you can easily mock are better patterns tho adopt if your data access code is complex and/or includes provider specific code.

**Comment by rowanmiller** [comment]
As mentioned, `ExecuteSqlCommand` is specific to relational database providers (which InMemory is not). If you only install the InMemory provider then this extension method is not available).
