### ISSUE TITLE
EF7 Redis Joins Not Supported.

### ISSUE THREAD

**Issue by zoeysaurusrex** [dotnet/efcore#4316]
Reading through the Redis documentation here:

https://github.com/aspnet/EntityFramework/wiki/Entity-Framework-Design-Meeting-Notes---July-17,-2014

Are joins going to be supported in the final release of the Redis code for EF7. It sounds like the approach might be to store one set per entity, and if this is done, it sounds like joins would be a natural fit for this model. Can you provide clarity?

**Comment by rowanmiller** [comment]
@wmccullough we don't really have any details on the Redis provider at this stage. We did a rough prototype to make sure that our core framework was useable with various non-relational databases, but it was a long way from a shippable product. We do plan to pick back up our non-relational prototypes after 7.0.0 RTM and turn them into proper providers - but that is a little ways off yet.

**Comment by wmccullough** [comment]
Is our company welcome to contrib here?

**Comment by rowanmiller** [comment]
Yes absolutely. We won't be able to dedicate much time helping you out while we get 7.0.0 RTM wrapped up, but if you are ok with that then we'd love to see the implementation move forwards. We probably won't want to pull it into the master branch just yet, but we can always work on it elsewhere and merge when we are ready.

@lajones I think we have our semi-working prototype in a branch somewhere right? The core code base has evolved a lot since it was moved out, so it would take some work to get it working again - but it may be useful.

Here is the high level item tracking Redis suppor - https://github.com/aspnet/EntityFramework/issues/327.

**Comment by rowanmiller** [comment]
@bricelam to point to last version of the Redis provider

**Comment by bricelam** [comment]
The parent of the commit that removed them is c2e636234d6468f4b6681dffe6386986e38a5f16

**Comment by rowanmiller** [comment]
Closing this one out as we have #327 to track the all up work of brining back the Redis provider
