### ISSUE TITLE
Parent-child insert, not insert childs 

### ISSUE THREAD

**Issue by valdirviana** [dotnet/efcore#4329]
```
public class ConfiguracaoPrazo : EntidadeBase
{
    public virtual Vigencia Vigencia { get; set; }
}

public class Vigencia : EntidadeBase
{
    public int PrazoDesativacaoAAM { get; set; }
    public int NumeroAvisos { get; set; }
    public int IntervaloEntreAvisos { get; set; }
}

    public void InsertConfGeral()
    {
          confGeral.ConfiguracaoPrazo = new Geral.ConfiguracaoPrazo();
          confGeral.ConfiguracaoPrazo.Financeiro = new Geral.Financeiro {
            IntervaloEntreAvisos = 10,
            NumeroAvisos = 12,
            PrazoDesativacaoAAM = 14
        };
        confGeral.ConfiguracaoPrazo.Licenca = new Geral.Licenca {
            IntervaloEntreAvisos = 12,
            NumeroAvisos = 12,
            PrazoDesativacaoAAM = 12,
            NumeroLicencas = 12,
            PeriodicidadeValidacao = 12
        };
        confGeral.ConfiguracaoPrazo.Vigencia = new Geral.Vigencia {
            IntervaloEntreAvisos = 23,
            PrazoDesativacaoAAM = 12,
            NumeroAvisos = 234
        };
    }


    public void Adicionar(T entidade)
    {
        _contexto.Set<T>().Add(entidade, behavior: GraphBehavior.IncludeDependents);

        _contexto.SaveChanges();
    }
```

**Comment by valdirviana** [comment]
The process _contexto.SaveChanges(); only save parent entity, not save/create child entities.

**Comment by Tarig0** [comment]
I don't see any children entities, or where the adicionar function is being called

**Comment by valdirviana** [comment]
I use:

var configuracaoPrazo = new ConfiguracaoPrazo (); // and initialize parent and chield with new data....

after

Adicionar(configuracaoPrazo );

**Comment by rowanmiller** [comment]
@valdirviana there isn't really enough code provided to work out what is happening. But here is a guess based on what is provided...

In the relationship between `ConfiguracaoPrazo` and `Vigencia`, `ConfiguracaoPrazo` is the child and `Vigencia` is the parent. This is because `ConfiguracaoPrazo` can have a single `Vigencia` (based on the `ConfiguracaoPrazo.Vigencia` navigation property). There is no navigation property on the other side, so EF assumes it is a one-to-many. Therefore, if you are adding instances of `ConfiguracaoPrazo` to the context, the related `Vigencia` will not get added automatically (because it is the parent, not a child).

If this is supposed to be a one-one-relationship with `Vigencia` being the child, then you would need to add some configuration to your context:

```c#
modelBuilder.Entity<ConfiguracaoPrazo>()
    .HasOne(c => c.Vigencia)
    .WithOne()
    .HasForeignKey<Vigencia>(v => v.<the foreign key that points to the parent>);
```

If that doesn't answer your question, can you provide a complete code listing that we can run to demonstrate the issue that you are seeing.

**Comment by valdirviana** [comment]
My class's are:

    public class ConfiguracaoPrazo: Entidade
    {
        public Vigencia Vigencia { get; set; }
    }

    public class Vigencia : Entidade
    {
        public int IntervaloEntreAvisos { get; set; }

        public int NumeroAvisos { get; set; }

        public int PrazoDesativacaoAAM { get; set; }
    }

 ///MAPPING
     public class ConfiguracaoGeralMapeamento : MapeamentoBase<ConfiguracaoGeral>
     {
         public ConfiguracaoGeralMapeamento(ModelBuilder builder) : base(builder)
         {
         }

        public void Configure()
        {
            Builder.HasKey(u => u.Id);

            Builder.HasOne(x => x.Vigencia);
        }
    }

I have to forcing the parent class ID in the child class, such as foreign key ?

**Comment by rowanmiller** [comment]
If you don't want to include a foreign key property in your class, then you can use a shadow state property...

```c#
modelBuilder.Entity<Vigencia>()
    .Property<int>("ConfiguracaoPrazoId");

modelBuilder.Entity<ConfiguracaoPrazo>()
    .HasOne(c => c.Vigencia)
    .WithOne()
    .HasForeignKey(typeof(Vigencia), "ConfiguracaoPrazoId");
```

Note that this is actually what is happening with the one-to-many relationship too. Because you don't have a foreign key property on your `ConfiguracaoPrazo` class - EF is introducing a shadow state one for you (but you want to override all that because you want a one-to-one with `ConfiguracaoPrazo` as the parent/principal).
