### ISSUE TITLE
EF Core 1.0 !!!

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#4340]
Now that EF7 has become EF Core 1.0, what will happen with package versions/names? And how will this affect NuGet versioning and providers? http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx

**Comment by divega** [comment]
@ErikEJ we are still discussing some options for the packing naming scheme of EF Core 1.0 components. Certainly, how it wpuld work for provider writers is one of the important aspects we are looking at. We should have a proposal very soon.

**Comment by OlegKi** [comment]
@ErikEJ I agree with you, that it could be real problem for developers who started development with ASP.NET 5. I posted [the issue](https://github.com/aspnet/Home/issues/1222) which described the issue with many renaming of packages. The issue was closed, because Microsoft don't take seriously the consequence of renaming the packages and the difficulties of finding the new names.

Renaming of "official names" follows renaming of assemblies, which are the names of packages. As the result the projects created before will not resolve to the new packages. One find a lot of examples on the stackoiverflow or in the documentation, which uses *old package names*. Thus it's really difficult to locale the correct name of some internal assembly after its renaming.

**Comment by ErikEJ** [comment]
@OlegKi Sure, but keep in mind, that ASP.NET Core 1.0 has not been released yet, but is "beta" software

**Comment by OlegKi** [comment]
@ErikEJ What I mean is: it's no problem with changing the names of assemblies

 `Microsoft.AspNet.Mvc.Xml` to `Microsoft.AspNet.Mvc.Formatters.Xml`
`EntityFramework.SqlServer` to `EntityFramework.MicrosoftSqlServer`
...

and so on, but the names will be used as the NuGet package name or **id** of the package. Thus the projects, which used `"EntityFramework.SqlServer": "7.0.0-beta8"` will get no advice that the Update to renamed package `"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final"` exist. You will still find a lot of code examples in Google where old name `EntityFramework.SqlServer` are used and a lot of developers will not update his `project.json` to new versions because or renaming of **ids** used for referencing. Many parts of official ASP.NET documentation will be corrected to new names weeks later.

It's clear for me that the ASP.NET is not final, but the most release candidates was more friendly to projects created using beta versions. One didn't renamed DLLs, registry keys and other internal information, which could be used by developers.

I expect a lot of **renaming of packages** after renaming of the product name. It will punish the developers, who already started migration his large projects to ASP.NET 5. It's really easy to extend the requests to NuGet server for the newest version so that the renamed packages would be used too.

**Comment by rowanmiller** [comment]
@OlegKi totally hear what you are saying. For us it's a matter of "do we cause some pain now for folks who have adopted pre-release software or do we forevermore stick with a naming/versioning story that causes confusion". I'm not diminishing the impact that it has now... but in the long term I think adopting a strategy that correctly reflects what we are building is the clear winner.

**Comment by rowanmiller** [comment]
Opened https://github.com/aspnet/EntityFramework/issues/4376 to track everything that needs to be done around this (and discuss naming etc. with provider writers).
