### ISSUE TITLE
Bug in EF7 with DI and two different DBContext

### ISSUE THREAD

**Issue by SharpNoiZy** [dotnet/efcore#4360]
Hi,

I try to use EF 7 RC1 with two different DBContext and resolve this two with DI.

```
services.AddEntityFramework().AddSqlite().AddDbContext<ReadModelContext>(options => options.UseInMemoryDatabase());
services.AddEntityFramework().AddSqlite().AddDbContext<EventStoreContext>(options => { options.UseInMemoryDatabase(); });

services.AddSingleton<IReadModelContext>(provider => provider.GetService<ReadModelContext>());
services.AddSingleton<IEventStore>(provider => provider.GetService<EventStoreContext>());
```

But in my ReadModelContext constructor an instance of:

```
Microsoft.Data.Entity.Infrastructure.DbContextOptions<EventStoreContext>
```

arrives.
So my quick and dirty thoughts are, that the second "services.AddEntityFramework()..." overrides the first one.
For me that is clearly a bug, because I can and I do specify the type I want to configure with:

```
AddDbContext<TContextType>
```

Kind regards

**Comment by rowanmiller** [comment]
@SharpNoiZy one problem I see with your code is that you are registering the context interface as a singleton... which would mean the same instance of the context is shared by all web requests (not supported since DbContext is not thread safe).

If you swap them to be scoped does everything work?

```
services.AddScoped<IReadModelContext>(provider => provider.GetService<ReadModelContext>());
services.AddScoped<IEventStore>(provider => provider.GetService<EventStoreContext>());
```

If that doesn't work, can you share the exception/error you are getting

**Comment by rowanmiller** [comment]
Closing as we have not heard back
