### ISSUE TITLE
[Question] Multiple In Memory Databases of same context

### ISSUE THREAD

**Issue by Abrissirba** [dotnet/efcore#4373]
I'm trying to use EF7 In Memory Database for my unit/integration tests written with xUnit. At the moment the tests are executed in parallel. All tests uses the same DbContext class.

The tests are written so that the db should be "clean" for each test suit.This is working as long as I only have one test suite. As soon as I add one more suite I get problems. There is no way to guarantee that the db is "clean" in each test since the two test suites run in parallel. 

One solution to this is of course to run each test sequentially but I would prefer if it was possible to run them in parallel. One solution to this would be that each test suite gets its own isolated in memory database, even though the same DbContext class is used. Is this possible today?

**Comment by bryanjhogan** [comment]
I wrote tests in xunit using the in memory database but found that even running sequentially that the context was not clean. 

See https://github.com/aspnet/EntityFramework/issues/4345

**Comment by rowanmiller** [comment]
By default, the InMemory database is shared between context instances (so that it behaves similar to other databases). See https://github.com/aspnet/EntityFramework.Docs/issues/95 for details on how to control the scope of the database (this will eventually turn into proper documentation).

BTW we do also plan to have something like named in-memory instances in the future... which would give you a simpler way to control the scope of data sharing.

**Comment by bryanjhogan** [comment]
I think many people will use the in memory database for unit testing. Could a option be added disable this sharing?

**Comment by rowanmiller** [comment]
I think what you really want is the ability to control the scope of the database. There are some tests where a clean database each time you create a context would work... but when writing real tests you quickly run into the need to inert seed data in one context and then create a second context to run the actual test against. Using the same context that you setup the test data in doesn't give you a real test because all the data is loaded already and you wouldn't hit issues where the component you are testing assumes that some data is loaded, but there is no logic to load it.

There is sample code in https://github.com/aspnet/EntityFramework.Docs/issues/95 that shows how to control this scoping, but I agree that we need an easier way to do this (which is where the named database feature comes in).

**Comment by bryanjhogan** [comment]
How does this work if I'm using ninject? 

            var serviceCollection = new ServiceCollection();
            serviceCollection
                .AddEntityFramework()
                .AddInMemoryDatabase()
                .AddDbContext<SampleContext>(c => c.UseInMemoryDatabase());

**Comment by Abrissirba** [comment]
I acctually have another question regarding this but this time I want to share the same instance of the in memory Database instead! ;) I have integration tests for my Web API written in ASP.NET 5. In these tests I would like to access my DbContext to seed the database with data before the tests. However, when I did this I noticed that the DbContext used in my test project wasn't the same being used by my Web Api so I can't seed test data from my test project. Would be great with some more documentation about In Memory Databases and especially how to use it in unit and integration tests in ASP.NET 5.

**Comment by rowanmiller** [comment]
@Abrissirba we will absolutely document this. In the meantime, there is code in https://github.com/aspnet/EntityFramework.Docs/issues/95 that shows how to control the scope of the InMemory database (to share, or not share, data between instances of the context).

**Comment by bryanjhogan** [comment]
Any suggestion on how to use EF 7 with ninject? 

I need to use a real db for the application and the inmemory option for testing.

**Comment by mgallig** [comment]
I'm still having this issue and have resorted to a bunch of workarounds to get my contexts to not share. I'm running xunit with a class fixture and separate dbcontext per class, no parallelization, and I still get the same context amongst all of my testserver instances.

**Comment by wleader** [comment]
I'm aware this item is closed, but its a top result for searching about In-Memory databases being shared between contexts in unit tests, so I'll add what I've learned.

I have a fake context that I use in my unit tests, and inside that class I've done roughly this:

`
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    base.OnConfiguring(optionsBuilder);
    optionsBuilder.UseInMemoryDatabase("MemDB-"+ GetSomeUniqueString());
}
`

The result is that every time I create an instance of the fake context used in my tests, it uses a different database name. 

Like the OP, my tests are written to expect an 'clean' (empty database) that gets populated in the Arrange step of Arrange Act Assert.

If you look at the doc at https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory the code block under the heading writing tests does pretty much the same thing: specifying a different database name for each test.
