### ISSUE TITLE
[Question] Roadmap

### ISSUE THREAD

**Issue by Suchiman** [dotnet/efcore#4390]
What is the current plan for EntityFramework? https://github.com/aspnet/EntityFramework/wiki/Roadmap hasn't been updated in some time.

I'm currently concerned about the really slow pace at which EF is moving forwards and the amount of prio0 bugs. I can't even get my IRC bot upgraded from EF6 to EF7 RC2 nightlies, which isn't the primary scenario for EF7, i know, but it is only using pretty basic EF features. Still he is mostly blocked by severe SQL gen bugs.

Estimating from the pace at which bugs are fixed i don't see how it will be considered useable for any projects by March (i guess ASP.NET 5 goes live at build 2016...)

**Comment by rowanmiller** [comment]
The roadmap hasn't been updated because it hasn't really changed :smile:. Our team is basically just focusing on stabilization at this point. Per your point about stability, we've renamed EF7 to EF Core (and ASP.NET 5 to ASP.NET Core) to help reinforce that these are both v1 technologies and are not as stable and mature as their EF7/ASP.NET 4 counterparts that have existed for many years.

The release dates for both ASP.NET Core and EF Core are "TBD" at this stage ([see our shared schedule](https://github.com/aspnet/Home/wiki/Roadmap#schedule)) as we are working to move to .NET CLI (which did not exist when we planned the initial schedule).

**Comment by Suchiman** [comment]
Alright, thanks. I will have to exert myself more in patience :grin:
