### ISSUE TITLE
Dependency issues when installing RC1-final packages

### ISSUE THREAD

**Issue by danielwertheim** [dotnet/efcore#4395]
Visual Studio 2015 pro (updated with all latest magical stuff)
NuGet v3.3.0
Project with .Net 4.5.2

When installing `RC1-final` packages, `EntityFramework.Core` or `EntityFramework.MicrosoftSqlServer` you get:

_"Failed to add reference to 'System.Collections.Concurrent'. Please make sure that it is in the Global Assembly Cache."_

What is the preferred way of handling this?

**Comment by ErikEJ** [comment]
Remove all references to the NuGet packages, clear/remove packages.config, start over.

**Comment by danielwertheim** [comment]
That "works" in a single project. But if you have two, it sometimes fails
at the second. Is this an issue with NuGet in itself, or does the EF
packages have wrongly configured packages or magical Powershell scripts?

**Comment by mehrt** [comment]
This one is a bit of a pain really. I'm playing with the nightly builds, and I see this every time I try to update the packages to a new release. As this occurs in multiple projects, it makes something that should be a plug and play excercise a pretty cumbersome process.

**Comment by ErikEJ** [comment]
@mehrt @danielwertheim Agree with both of you, it is a pain, but I think it is very low on the list of things to be done.

**Comment by mehrt** [comment]
@ErikEJ Is it actually an issue with the EF7 builds, or more of a NuGet problem? Because that's what @rowanmiller 's comment in #3891 seems to suggest ...

**Comment by ErikEJ** [comment]
Yes, it is most likely a NuGet issue. But I am waiting for the dust to settle.

**Comment by davidroth** [comment]
I feel your pain. Had the same issue multiple times. Its really annoying if you are playing with the nightly bits.

**Comment by ErikEJ** [comment]
Maybe the EF team could raise/file as issue in the correct repo, as they are better equipped to provide the correct background informstiom?

**Comment by benoit-bernard** [comment]
Hello,
Same issues (and more like that with RC2). It's so so painfull that i have to stop using EF7. I don't understand how it could not be a high priority as it is a blocking issue in real life (not a single test project)

**Comment by danielwertheim** [comment]
I don't see how "making something consumable" can be "low" prio, especially since it's RC and golive licensed... It's a major PITA as it is now. Hope the restore will work in the CI build once I get there...

**Comment by mikes-gh** [comment]
Is it because packages are resolved using packages directory first then nugget.
Basically if you clone one of the repos you'll get nightly aspnetcidev nugget package because of the nugget.config.  After this happens you will need to delete all the packages in the packages cache directory and reload your project so it uses the aspvnext packages.  It's been discussed whether packages should store info about where they came from so this behaviour can be fixed but as said it doesn't seem high priority.  It's a real pain though.

**Comment by rowanmiller** [comment]
Absolutely hear folks pain on this one... trust me I feel it myself working on demo applications etc. Unfortunately this is just a side effect of all the churn in package structures, TFMs etc. The fixes to most of these issues would be in NuGet, but because this is upgrades between pre-release versions we're not going to put aside features and bug fixes to sort these out.

You could argue that if things are changing so much and stability is an issue then this stuff shouldn't all be listed as RC... and you would be right. Unfortunately with the move to .NET CLI, it looks like things could be pretty messy in terms of upgrade for the next release too. Hopefully we are through the pain at that point though.

I realize that's not what folks want to hear... just trying to be transparent and realistic :smile:
