### ISSUE TITLE
How to select one in include expression?

### ISSUE THREAD

**Issue by AlexeyTipunin** [dotnet/efcore#4476]
I Have query like this:

return db.Tanks
        .Include(i => i.FluedLevelSensor)
        .Include(i => i.WaterLevelSensor)
        .Include(i => i.GasPressureSensor)
        .Include(i => i.HudrostaticPressureSensor)
        .Include(i => i.TechnologicalMaps)
        .Include(i => i.TechnologicalGroup)
        .Include(i => i.TemperatureSensor).ThenInclude(t => t.TemperatureSensorPoints)
        .Include(i => i.Material)
        .Include(i => i.TankType)
        .Include(i => i.QualityPassports).ThenInclude(i1 => i1.ContentType)
        .Include(i=>i.CalibrationTableNew)
        .Include(i => i.TankOperations)
        .Include(i => i.TankStates).ThenInclude(i => i.State);
How can I write it like this:

return db.Tanks
     .Include(i => i.FluedLevelSensor)
     .Include(i => i.WaterLevelSensor)
     .Include(i => i.GasPressureSensor)
     .Include(i => i.HudrostaticPressureSensor)
     .Include(i => i.TechnologicalMaps.OrderByDescending(o=>o.InsertTime).FirstOrDefault())
     .Include(i => i.TechnologicalGroup)
     .Include(i => i.TemperatureSensor).ThenInclude(t => t.TemperatureSensorPoints)
     .Include(i => i.Material)
     .Include(i => i.TankType)
     .Include(i => i.QualityPassports.OrderByDescending(o => o.SamplingDate).FirstOrDefault()).ThenInclude(i1 => i1.ContentType)
     .Include(i=>i.CalibrationTableNew)
     .Include(i => i.TankOperations.OrderByDescending(o => o.OperationStartTime).FirstOrDefault())
     .Include(i => i.TankStates.OrderByDescending(o => o.Time).FirstOrDefault()).ThenInclude(i => i.State); 
and whether there are any other ways to optimize the query? Thank you.

**Comment by divega** [comment]
You can't use 'Include()' for that, but you can include subqueries like that in the projection of the query, e.g. `.Select(i => new { Tank = I, LastOperation = i.TankOperations.OrderByDescending(o => o.OperationStartTime).FirstOrDefault()})'.

A couple of caveats:

1. There are bugs and limitations in EF Core of that can affect whether those queries execute correctly or how efficiently they work.
2. Even if LINQ has the expressivness needed to write very complex queries, in general I would recommend writing multiple simpler queries instead of a large query like this. It can be better because it leads to easier to maintain code, gives you more control of the queries that get sent to the database. allows you to defer loading of specific data until it is really needed, etc.

**Comment by divega** [comment]
Closing because I think I have answered your question, but if you hit issues while working on this, please open new issues.
