### ISSUE TITLE
Logging: DbCommandLogData should expose DbCommand object

### ISSUE THREAD

**Issue by albahari** [dotnet/efcore#4514]
DbCommandLogData should have a property to expose the DbCommand object that's about to be executed, or at a minimum, a property to expose the native DbParameter objects (rather than just a Dictionary<string,object>). Without this, it's impossible to use EF7's logging infrastructure to capture the SQL that's being executed with full fidelity, and you cannot format the output such that it can be pasted directly into SSMS for execution plan analysis.

This feature is necessary for full LINQPad support. At the moment, LINQPad offers an EF7 driver, but it's limited in its ability to analyse the SQL generated from LINQ queries.

(Furthermore, in the current EF7 release, the object-based parameter values all return "?". Presumably this will be fixed in RTM?)

**Comment by rowanmiller** [comment]
I'm pretty sure this is by design since we don't want to expose anything to logging that could cause the SQL command to be manipulated (logging should be read-only). 

Coming up in the next release we have an `EnableSensitiveDataLogging` switch that can be used to allow parameter values to be logged.

cc @anpete I think we already have a mechanism (other than logging) that lets you get hold of things like the DbCommand??

**Comment by divega** [comment]
@albahari The feature @rowanmiller is referring to is our support for System.Diagnostics.DiagnosticSource. I couldn't find documentation about it so probably that isn't ready but you can look it up in our code, in MVC and in Glimpse. We expose a couple of events that hopefully will help at https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalDiagnostics.cs
