### ISSUE TITLE
CLI Commands: honor default namespace from project

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#4524]
Apparently, this is a thing in `project.json`.

``` JSON
{
  "tooling": {
    "defaultNamespace": "Not.Project.Name"
  }
}
```

We should honor that in our commands instead of just using the project name.

**Comment by natemcmaster** [comment]
Not sure where this "tooling" node came from, but it is not in the project model for CLI projects.

**Comment by divega** [comment]
cc @rowanmiller since I know we had resolved a few bugs as dupes of this one. We may want to have something (maybe repurpose this issue?) to make sure we handle the equivalent scenario for tooling RTM.

**Comment by rowanmiller** [comment]
Agreed, reopening and removing milestone so that we can discuss in triage

**Comment by divega** [comment]
Edited title to make it non project.json specific.

**Comment by rowanmiller** [comment]
This will go away as we consolidate with MSBuild

**Comment by NightOwl888** [comment]
Where is the "tooling" element supposed to go in project.json? I can't seem to find any documentation on this.

Also, what version of the CLI was it first supported in?

**Comment by ajcvickers** [comment]
@NightOwl888  The  [.NET Core SDK 1.0.0](https://www.microsoft.com/net/download/core) no longer supports project.json or Visual Studio 2015. Everyone doing .NET Core development is encouraged to [migrate from project.json to csproj](https://docs.microsoft.com/dotnet/articles/core/migration/) and [Visual Studio 2017](https://www.visualstudio.com/downloads/).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by NightOwl888** [comment]
I've been told (but have not confirmed) that VS 2017 and the unified .csproj file for .NET Framework/.NET Core is not fully functional yet. And I really don't have the time to migrate my 35 projects (105 different build configurations) to .csproj just to jump over a lot of other hurdles trying to develop again. So for the time being, we are sticking with the project.json file (since that is the way your Microsoft contributor set it up a few months ago).

That said, my question still applies and is not yet answered.
