### ISSUE TITLE
cannot apply migrations in sql azure

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#4562]
Hi,
  I have a a dbcontext with 3 tables in a library project, that is used by an application:in my web app I created without problems the migration (the initial migration), the migration class and the snapshot source files are in the project.
  If I try to run the command **dnx ef migrations list** I have received the messag 
`No migrations were found, 
`and if I try to update the db via dnx command I see that the the migration history table is created but the migration is not applied.
  running in verbose I see

```
dnx ef database update -v
Finding DbContext classes...
Using context 'LibraryContext'.
Using database 'xxx' on server 'tcp:yyydatabase.windows.net,1433'.
Done.

```

If I try to specify the migration name I obtain
`The migration ... was not found.`

Am I missing something?

**Comment by rowanmiller** [comment]
This is really messy in RC1 and we've made some improvements to help you get it right in RC2. What you probably need to do is add a call to `MigrationsAssembly` in `OnConfiguring` to let EF know where to find the migrations. The issue is that the tooling knows where to drop new migrations (the project you are executing the command on), but it isn't as smart about where to find them when applying migrations.

```c#
protected override void OnConfiguring(DbContextOptionsBuilder options)
{
    options.UseSqlServer(...).MigrationsAssembly("<assembly name>");
}
```

Like I said, this all gets a lot better in RC2, but let me know if this solves the issue for you for the moment.

**Comment by rowanmiller** [comment]
Feel free to reopen if this doesn't solve your problem.
