### ISSUE TITLE
Advice regarding failing test 

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#4565]
I have ported the following test for the SQL CE provider. All other tests in the ported class pass.

This one fails:

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.Tests/Extensions/Metadata/SqlCeBuilderExtensionsTest.cs#L80

I am running against build 1.0.0-rc2-16811 

It fails on the following Assert:

```
Assert.Equal(ValueGenerated.Never, property.ValueGenerated);
```

The property value is:  ValueGenerated.OnAdd, not .Never

Hoping you could point me to what I have done wrong, and thanks in advance.

**Comment by smitpatel** [comment]
`ValueGeneratedNever()` call should be setting ValueGenerated.Never with Explicit CS. When `ForSqlCeHasDefaultValueSql("VanillaCoke")` is called it will try to set ValueGenerated.Add by Convention CS which won't happen since Explicit overrides Convention. Looks like somewhere configuration sources are not being handled correctly.

**Comment by ErikEJ** [comment]
I realize I was very unclear, it is the assert in line 103 that fails, NOT the one on line 94... @smitpatel

**Comment by smitpatel** [comment]
The EF build you will need is rc2-16834 :smile:

**Comment by ErikEJ** [comment]
So you are saying it is a bug fixed in a later build? :thumbsup:

**Comment by smitpatel** [comment]
Yes. 2948069534c9a99aecba796f3a4697c5ca7d75a9 corresponds to 16834
