### ISSUE TITLE
Are .Include/.ThenInclude supposed to work with Select in RC1-final?

### ISSUE THREAD

**Issue by bragma** [dotnet/efcore#4641]
Quick question: I can't populate navigation properties (they stay null), even using include (and theninclude) whenever I use select(). I can provide sample code if required. Are they supposed to work in RC1-final?

Sample query:

`db.CarParts.Include(cp => cp.Car).ThenInclude(c => c.Drivers).Where(cp => cp.ProductionBatchExternalCode == "PB001" && cp.Car.Drivers.Any(d => d.UserId == 1)).Select(cp => cp.Car)
`

Thanks!

**Comment by maumar** [comment]
There is a know issue of Include not working with navigations for some cases. Workaround could be to split your filter into two calls, perform first one on the server a d the second one on the client. This is not ideal, because you will get unnecessary rows to the client, but should work.

 db.CarParts.Include(cp => cp.Car).ThenInclude(c => c.Drivers).Where(cp => cp.ProductionBatchExternalCode == "PB001").ToList().Where(cp => cp.Car.Drivers.Any(d => d.UserId == 1)).Select(cp => cp.Car)

**Comment by csaloio** [comment]
I'm having a problem with include as well. Not sure if it's the same problem:
```
_ctx.UserLogins.Where(l => l.auth_server_id == authServerId && l.login_id == userId)
                    .Select(l => l.Person)
                    .Include(p => p.Person2Roles).ThenInclude(p2r => p2r.Role)
                    .SingleOrDefault();
```
The generated SQL seems way off:
```
SELECT TOP(2) [l.Person].[id], [l.Person].[email], [l.Person].[handle], [l.Person].[name]
FROM [com].[user_login] AS [l]
INNER JOIN [com].[person] AS [l.Person] ON [l].[person_id] = [l.Person].[id]
WHERE ([l].[auth_server_id] = @__authServerId_0) AND ([l].[login_id] = @__userId_1)
```

It doesn't do the sub query and for some strange reason it is doing a TOP(2) ?!?!

**Comment by maumar** [comment]
Try applying includes first and then filter and projection. Including out of projection makes more query and EF can't handle it currently. Top (2) is due to SingleOrDefault. No need to pull more rows because it will throw if there is more than one anyway.

**Comment by csaloio** [comment]
@maumar Thanks for the advice and explanation of TOP(2). I altered the query as you suggested but the generated SQL is still not grabbing the roles:
```
SELECT TOP(2) [l.Person].[id], [l.Person].[email], [l.Person].[handle], [l.Person].[name]
      FROM [com].[user_login] AS [l]
      INNER JOIN [com].[person] AS [l.Person] ON [l].[person_id] = [l.Person].[id]
      WHERE ([l].[auth_server_id] = @__authServerId_0) AND ([l].[login_id] = @__userId_1)
```

**Comment by maumar** [comment]
In that case try:

_ctx.UserLogins
  .Include(l => l.Person)
  .ThenInclude(p => p.Person2Roles)
  .ThenInclude(p2r => p2r.Role)
  .Where(l => l.auth_server_id == authServerId && l.login_id == userId)
  .SingleOrDefault().Person;

It seem that EF can't deal with navigation projection in conjunction with include at all. This way, the projection will happen on the client so it should further simplify the query plan.

**Comment by csaloio** [comment]
@maumar Yes, that does work. It produces 2 DbCommands and gets all the needed data. I wouldn't have thought to skip the projection. Thank you.

I wonder if this way of writing the query works out a bit faster w/o the `select()` even once EF is able to handle it correctly.

**Comment by maumar** [comment]
The drawback of doing projection on the client is that EF needs to pull entire UserLogin entity to the client, even though you don't necessarily need it for your query. If UserLogin has a big binary column, that could impact performance. In general, the more you can do on the server the better, but the difference should be fairly small for most queries like these

**Comment by csaloio** [comment]
Makes sense. Thanks again!

**Comment by rowanmiller** [comment]
We discussed in triage and concluded this isn't something we plan to support. Taking the original query as an example, the Include/ThenInclude operators here are saying "when you return `CarPart`s in the query, include the relates `Car`s and their related `Driver`s". Because the query is then changed to return `Car`s rather than `CarPart`s, this is ignored.

```c#
db.CarParts
    .Include(cp => cp.Car).ThenInclude(c => c.Drivers)
    .Where(cp => cp.ProductionBatchExternalCode == "PB001" && cp.Car.Drivers.Any(d => d.UserId == 1))
    .Select(cp => cp.Car);
```

We do eventually want to make the following work, where you can specify includes on the query after you have changed the result type. But this does not work yet.

```c#
db.CarParts
    .Where(cp => cp.ProductionBatchExternalCode == "PB001" && cp.Car.Drivers.Any(d => d.UserId == 1))
    .Select(cp => cp.Car)  
    .Include(c => c.Drivers);
```

Until we enable the above scenario, the best option, is to swap the query around to be rooted on the type you intent to return (`Car`).

```c#
db.Cars
    .Include(c => c.Drivers)
    .Where(c => c.Parts.Any(cp => cp.ProductionBatchExternalCode == "PB001") && c.Drivers.Any(d => d.UserId == 1));
```

**Comment by rowanmiller** [comment]
Opened https://github.com/aspnet/EntityFramework/issues/5332 to warn when we ignore includes like this

**Comment by timotei** [comment]
FYI, this issue is worse and cannot be solved nicely AFAICT, if we want to do partial properties selection from an entity, for example: `Select(x => new { x.Property1 }`

However, it's very important (application-wise) to take just some specific property(ies), because other column(s) will contain binary data/unwanted on the client
