### ISSUE TITLE
Create database views in Migrations using SQL generated from a LINQ projection

### ISSUE THREAD

**Issue by ilmax** [dotnet/efcore#465]
Note: This issue is tracking a specific aspect of using EF Core with database views. See #827 for an overview of the areas where EF Core interacts with database views. The completion of this feature does not mean that every aspect of database view support has been implemented.

---

Hi, 
I'm wondering if is possible to create view from migrations in a C# fashion. Since a view is essentially a projection of one or more tables, it could be easily created by parsing a C# linq projection, so we can write once and execute everywhere (no more db dependent sql script).

Since all the pieces of this functionality are already there, I think it should be at least possible to do this.

Let me know what you think about it.
Cheers Max

**Comment by skynode** [comment]
Has this left the backlog? Can we expect to have this feature in EF Core 2.1? Thank you!

**Comment by ajcvickers** [comment]
This issue is in the Backlog milestone. This means that it is not going to happen for the 2.1 release. We will re-assess the backlog following the 2.1 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.
