### ISSUE TITLE
FromSql() with Table Value Constructor throws "Input string was not in a correct format."

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#4651]
When running the following query in FromSql(), EF throws. The query runs fine in SQL Management Studio.

```
SELECT
    a.*
FROM
    aTable a
    INNER JOIN (
        SELECT
            c.Target,
            MAX(d.Started) Started
        FROM
            (VALUES ({ts '2016-02-11 23:00:00'}),({ts '2016-02-12 23:00:00'}),({ts '2016-02-13 23:00:00'}),({ts '2016-02-14 23:00:00'}),({ts '2016-02-15 23:00:00'}),({ts '2016-02-16 23:00:00'}),({ts '2016-02-17 23:00:00'}),({ts '2016-02-18 23:00:00'}),({ts '2016-02-19 23:00:00'}),({ts '2016-02-20 23:00:00'}),({ts '2016-02-21 23:00:00'}),({ts '2016-02-22 23:00:00'}),({ts '2016-02-23 23:00:00'}),({ts '2016-02-24 23:00:00'}),({ts '2016-02-25 23:00:00'})) AS c(Target),
            aTable d
        WHERE
            d.Started < c.Target
        GROUP BY
            c.Target
    ) b ON a.Started = b.Started
```

I tried to parameterize the values TVC (https://msdn.microsoft.com/en-us/library/dd776382.aspx) from a list of DateTime, but that does not work, so I had to manually make the query as a string and input it to FromSql().
Running on rc1-final

**Comment by rmja** [comment]
Debugging with the EF source, and the exception is thrown here:
https://github.com/aspnet/EntityFramework/blob/7.0.0-rc1/src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs#L304

The reason is of cause that I use the curly braces in the sql to specify a safe date (https://msdn.microsoft.com/en-gb/library/windows/desktop/ms712360(v=vs.85).aspx), but this is used for parameter substitution in string.Format(). I can easily fix this on my side by inserting {{ and }} instead, but I think this probably should be handled inside EF.

**Comment by rowanmiller** [comment]
This is by design, we use the `{xyz}` syntax to represent parameters - for example `context.Blogs.SqlQuery("SELECT * FROM dbo.SearchBlogs {0}", searchTerm)` (note that we don't `string.Format` the actual value inline, we use parameterization and put the parameter name where the placeholder is - just so no one reading this freaks out about SQL injection :smile:)

Escaping as you did is the correct thing to do.

**Comment by sriramarunachalam** [comment]
Hi. I am trying to insert this into a table through FromSqlRaw. 
INSERT INTO dbo.MockAPIData (ServiceId) VALUES  ('1fa550f2-1f82-48a6-ad71-4df8319032b8')

Its throwing an "Input string was not in correct format" error. Is there an issue with inserting Guid values as string through fromsqlraw? 

Thanks.

**Comment by ErikEJ** [comment]
FromSql is for SELECT, not INSERT. Use ExecuteSqlCommand

**Comment by sriramarunachalam** [comment]
sorry, my mistake. I am using executesqlcommand, but i think the issue is not with the guid value. I am passing json and i am using additonal curlys to escape the curlys in the json. But the weird this is that one json gets inserted, but another json throws "input string was not in correct format" error.

INSERT INTO dbo.MockAPIData (JsonData) VALUES ('{{"Name":"SAM D1 - Workpapers (CTP D1)","Description":"Test Project","ProcessDetails":"CTP DEV1 Test Project","InstructionDocumentUri":"","ServiceLocalisation":[],"ServiceRequestDeliveryMethod":"WebRequest","EngagementAPIAccessRequired":false,"EngagementAPIs":[],"NoOfInputFiles":0,"ServiceEndPoint":{"Type":"REST","Address":"","AudienceUri":"","UserName":null,"Password":null},"EmailTemplate":null,"InputFiles":[],"NoOfOutputFiles":1,"OutputFiles":[{"GroupId":"","GroupName":"Evidence file","FileSequence":1,"TemplateUri":null,"Description":"Evidence","FileExtensions":"xlsx","MaxFileSize":40816,"IsRequired":true,"FileMetadataLocalisation":[],"Id":""}],"AssociatedCountries":[{"Name":"US","ServiceEndPoint":null,"DataCenterId":0},{"Name":"Germany","ServiceEndPoint":null,"DataCenterId":0}],"AuthorizedUsers":[],"SubscriptionId":"","IsActive":true,"CreatedById":1,"CreatedAt":"2020-09-01T15:07:35.8167551","LastUpdatedAt":"0001-01-01T00:00:00","LastUpdatedById":0,"Id":""}}')

INSERT INTO dbo.MockAPIData (JsonData) VALUES ('{{"EngagementId":11994,"WorkspaceCountryId":218,"EngagementDesc":"Tag Regression -South","EngagementUserStatus":1,"EngagementStatus":1,"EngagementIsProfileComplete":true,"EngagementUserInvitationMessage":null,"UserInitials":"AGN","UserFirstName":"","InCountryUri":"","UserLastName":"","EngagementCodeIsPrimary":false,"EngagementCodeIsClientEngIdValidated":true,"EngagementArchivalDate":"2018-03-24T19:59:59-04:00","CanAcceptDeletion":false,"ActiveUserAccount":7,"EngagementUserCount":9,"IsGroupAudit":false,"IsLinked":false,"EngagementVersion2":"2.8.0","IsInterimReviewEngagement":false,"ExpectedReportedReleaseDate":"2018-02-22T18:59:59-05:00","HasGamxOption":false,"HasEngagementNotification":false,"HasEngagementUserNotification":false,"NotifyUserName":"","HasIndependenceCompleted":true,"IndependenceStatusId":6,"WorkspaceId":"5824","Workspacedesc":"South Region","WorkspaceShowExpanded":"False","ShowDeleteExpanded":"False","IsNewWorkspace":"False","CountryId":"0","IsCurrent":"True","EngagementVersion":"2.8.0","ClientId":"","ClientName":"Dummy Client for Canvas Testing","ClientShowExpanded":"False","SortOrder":"0","IsClientCodeValid":"True"}}')

The first query fails, but the second one succeeds.

**Comment by NotFound404Forbidden** [comment]
use double "{{}}" , look like : xxx.FromSqlRaw("select * from ttt where ttt.jsonvalue @> '[{{\"id\":2}}]'")
