### ISSUE TITLE
Move the code to read the connectionstring in DbContext rather than Startup

### ISSUE THREAD

**Issue by rustd** [dotnet/efcore#4764]
From the ASP.NET templates review.
What is required to move the code for reading connectionstring from Startup to DbContext

I am opening this in the EF repo but someone will have to follow up with the runtime folks. 
/cc @rowanmiller

**Comment by ajcvickers** [comment]
Clearing this for re-triage. The fundamental problem is that there is no way to access configuration outside of Startup.cs unless:
* Configuration is made statically available to the application
* Something is done in Startup.cs to make configuration available elsewhere

It seems that the first of these will not happen due to fundamental objections from the wider team.

The second would require code in Startup in addition to code in OnConfiguring, which doesn't seem to be an improvement over just having code in Startup.

Therefore, I don't think we can make this happen within the current constraints of the ASP.NET templates.
