### ISSUE TITLE
Entity 5 Connection Issue 

### ISSUE THREAD

**Issue by cassellwang** [dotnet/efcore#4798]
I used ef5 to connect Oracle
Now DBA told me have a connection session issues
Do I have to manual closing DbContext connection when Disposed ?

this my code

``` c#
public class GenericRepository<TEntity> : IRepository<TEntity>
        where TEntity : class
    {

private DbContext _context
        {
            get;
            set;
        }
        public GenericRepository()
            : this(new DBEntities())
        {
        }

        public GenericRepository(DbContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }
            this._context = context;
        }

public void Create(TEntity instance)
        {
            if (instance == null)
            {
                throw new ArgumentNullException("instance");
            }
            else
            {
                this._context.Set<TEntity>().Add(instance);
                this.SaveChanges();
            }

        }

protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this._context != null)
                {
                    this._context.Dispose();
                    this._context = null;
                }
            }
        }

}
```

**Comment by rowanmiller** [comment]
You don't need to manually close the connection if you are letting EF manage the connection for you. If you are manually passing a connection to EF, or manually opening it etc., then you would need to close it.

This issue probably needs to be directed toward Oracle (https://community.oracle.com/welcome), who implement the EF provider for Oracle. When you open an issue, be sure to provide some more detail on what you mean by "Now DBA told me have a connection session issues" so that they can better help you.

**Comment by cassellwang** [comment]
thank you, i will try it again

2016-03-23 8:07 GMT+08:00 Rowan Miller <notifications@github.com>:
