### ISSUE TITLE
OriginalValue and CurrentValue having the same value when using .Update()

### ISSUE THREAD

**Issue by gfrSE** [dotnet/efcore#4801]
The .Update() function is usefull, but dont work as expected.
I am overriding the SaveChanges() function to get modified properties, but if i use the .Update function the OriginalValue and CurrentValue are both the "newValue" !!

Not working code:

``` c#
public PersonModel Add(PersonModel person /* , some more stuff .. */)
{
    if (person == null) return null;

    using (var transaction = _dbc.Database.BeginTransaction())
    {
        if (person.Id == 0)
        {
            _dbc.Persons.Add(person);
            _dbc.SaveChanges();
        }
        else
        {
            _dbc.Update(person); // can't track changed properties ?!
        }

        // .. some more stuff ..

        _dbc.SaveChanges();
        transaction.Commit();
    }
}
```

working code:

``` c#
public PersonModel Add(PersonModel person /* , some more stuff .. */)
{
    if (person == null) return null;

    using (var transaction = _dbc.Database.BeginTransaction())
    {
        var curPerson = _dbc.Persons.FirstOrDefault(p => p.Id == person.Id);

        if (person.Id != 0 && curPerson == null)
        {
            person.Id = 0;
        }

        if (person.Id == 0)
        {
            _dbc.Persons.Add(person);
            _dbc.SaveChanges();
        }
        else
        {
            //_dbc.Update(person); // can't track changed properties ?!

            var t = typeof(PersonModel);

            foreach (var prop in t.GetTypeInfo().DeclaredProperties)
            {
                prop.SetValue(curPerson, prop.GetValue(person));
            }
        }

        // .. some more stuff ..

        _dbc.SaveChanges();
        transaction.Commit();
    }
}
```

**Comment by gfrSE** [comment]
sorry, cant get the "code" to be displayed correct.. !?

**Comment by rowanmiller** [comment]
@gfrSE if you just pass in a disconnected entity instance to Update then EF has no info on what the original values were. The purpose of this API is just to tell EF to update to whatever the supplied values are. We did discuss having them return null in this situation, but ultimately decided it wasn't really worth the complexity in the stack.

If you want more fine grained control, then you can follow the query-update-save approach that you have in your second code snippet. This will result in a more concise `UPDATE` statement going to the database (only the changed properties getting set). However it has the same end result as just using the `Update` method and is likely slower since it requires the additional query.

BTW we do have https://github.com/aspnet/EntityFramework/issues/2295 tracking some APIs to be added to ChangeTracker to make this easier.

**Comment by gfrSE** [comment]
big thanks for your comment @rowanmiller .

During reading your comment i realized the WHY it works like it work.
How should "you" know the old values without reading them from database..
So if I want to know them, I HAVE TO read the corresponding entry first..

Thanks for opening my eyes. :)

**Comment by rowanmiller** [comment]
@gfrSE glad it makes sense :smile:

**Comment by SPEmoorthy** [comment]
If we attach an entity to Context... Will it get the Current value from DB Automatically? Any Possible Solutions?

**Comment by ajcvickers** [comment]
@SPEmoorthy No. Depending on what you are doing, consider context.Entry(foo).GetDatabaseValues.
