### ISSUE TITLE
Can we avoid needing Commands installed in startup project for Full .NET apps?

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#4833]
Currently we require commands to be installed in the startup project, this is nasty from an architecture perspective though. I'm guessing we only introduced this requirement for xproj?

```
PM> Add-Migration NextMigration
Cannot execute this command because Microsoft.EntityFrameworkCore.Commands is not installed in the startup project 'src\RocketProfiler.UI'.
```

**Comment by bricelam** [comment]
It think this may have always been the case. If I remember right, VS wouldn't copy `M.EFC.Commands.dll` to the output directory if it was only transitively referenced.

**Comment by natemcmaster** [comment]
Remarking for triage: this can wait until after RTM.

**Comment by natemcmaster** [comment]
Scope question: are we trying to do this just for csproj/packages.config projects?

**Comment by rowanmiller** [comment]
Any progress we can make would be good, if csproj is easier then that would still be a win. BTW I think it would be really good to relax this restriction... but I also don't think it's a ship stopper for tooling RTM. So I think the decision can take into account how messy the implementation is 😄

**Comment by natemcmaster** [comment]
Here is my thinking. After #5334, here is the tooling in layers of dependency: 

- `.Tools.VisualStudio`/ `.Tools.DotNet`  = `init.ps1` and `dotnet-ef`
- `.Design` = `OperationExecutor`, the version-resilient design-time "entry-point" into the app
- `.Relational.Design` = other design-timey stuff.
- `.Relational` and below = the runtime stuff

The tools layer is the funny bit. `.Tools.VisualStudio` "floats" across all projects in a solution because PMC cmdlets are solution-global, and the `.Tools.DotNet` is disconnected from the app's "dependencies". But both still need the next layer down is why our tools require installing (what used to be .Commands) .Design.

To ease the restrictions, we could:
 - Squash design layers down. We could squash the code in .Design down into .Relational.Design. I'm not sure the separation is as important post #5334.  (I like this idea most)
 - Make the tools layer carry the next layer down with it. Tools copy the design dll's to the right place before running and cleans up after
 - Squash design into runtime. We could be even more aggressive and push it all into .Relational. Downsides: violates our pay-for-play ideals, increases binary size. Upsides: tools will basically work anywhere EF runtime is installed. (I like this idea least)

**Comment by bricelam** [comment]
I still don't think there's anything we can do here. NuGet/MSBuild won't copy transitive dependencies to the output directory, and the best workaround is to install them directly into the startup project.

**Comment by rowanmiller** [comment]
Should we just close this one then? I don't think we need to spend a lot of time trying to work around it, I just raised it as something that would be good to make easier if we could.

**Comment by bricelam** [comment]
I vote to close, yes.

**Comment by rowanmiller** [comment]
Sold! 🔨
