### ISSUE TITLE
Eager load all navigation properties

### ISSUE THREAD

**Issue by deenairn** [dotnet/efcore#4851]
Is there a mechanism to eager load all navigation properties (and any navigation properties they have) without having to do repeated calls to Include().IncludeThen(), etc. This is pretty labourious in our circumstances and error prone if new properties must be added then they must be added to this sequence of Include().IncludeThen().

Previously this worked via lazy loading - I know issue #3797 is there to resolve how to support this.

**Comment by rowanmiller** [comment]
We probably don't want a "just Include everything" switch, since then you would quickly end up with the entire database loaded into memory. But we do have a couple of existing features that we want to implement that would help here. Rule based eager loading would require setup, but avoids having to explicitly include stuff all the time (https://github.com/aspnet/EntityFramework/issues/2953). We also want to support some for of defining aggregates, where it probably does make sense to allow automatically loading a complete aggregate when you are for one of the entities within it (https://github.com/aspnet/EntityFramework/issues/1985).

**Comment by baratgabor** [comment]
Where I ran into this need (or let's call it a desire) is actually integration testing. Specifically when I want to do asserts on the completeness of added or modified entities. Would be great to have assurance that everything related to the given entity is loaded automatically, and the amount of data or the performance in this use case is never gonna be a concern.
