### ISSUE TITLE
Cannot update alternate key entity framework core 1.0 rc-1

### ISSUE THREAD

**Issue by ar27111994** [dotnet/efcore#4914]
I'm using entity framework 7 or core 1.0 for my new project. In the products table, ProductName column is set as an alternate key (unique constraint). The problem is that I'm unable to update this column in the database. Here are the details:
[stackoverflow question](http://stackoverflow.com/questions/36200436/cannot-update-alternate-key-entity-framework-core-1-0?noredirect=1#comment60157013_36200436)
 More details are in the commnts of the stackoverflow post.

**Comment by ar27111994** [comment]
The update query is working fine in SQL server so it really is an Entity Framework issue.

**Comment by rowanmiller** [comment]
@ar27111994 EF Core currently does not support changing the value of alternate keys. We do have https://github.com/aspnet/EntityFramework/issues/4073 tracking removing this restriction though.

BTW it only needs to be an alternate key if you want it to be used as the target key of a relationship. If you just want a unique index, then use the `HasIndex()` method, rather than `AlternateKey()`. Unique index values can be changed.

**Comment by ar27111994** [comment]
Thank You so much. @rowanmiller

**Comment by johnkwaters** [comment]
I have a model where an object has a key that I set manually (SQL Server, not an identity column)
In my code, I fetch one of these objects, then copy it using AutoMapper, and then I set a new value for the key and save it. This gives me an error "The property 'Id' on entity type 'DbProject' is part of a key and so cannot be modified or marked as modified.".
What do I do to basically modify they key value of this new object?
