### ISSUE TITLE
Wrong SQL request with EF

### ISSUE THREAD

**Issue by tango-charly** [dotnet/efcore#4956]
Hi,

I forgot to declare my ID as Identity in my SQL Server and i used_ CodeFirst From Database _to generate my entities. 

So EF wrote :
`[DatabaseGenerated(DatabaseGeneratedOption.None)]`
`public int Id;`

I corrected my mistake with :
`[DatabaseGenerated(DatabaseGeneratedOption.None)]`
`public int Id;`
Or (never mind) 
`public int Id;`

EF generated a good migration   :
`Id = c.Int(nullable: false, identity: true),`

But the SQL request wich alter the column doesn't add the property Identity.

EF'll consider my ID as Identity, but it's not define as it in my SQL Server.

I had no problem with create or add column requests.

**Comment by divega** [comment]
@tango-charly thanks for reporting this. In summary, it is not as easy as it looks: in order to add or remove an IDENTITY spec on a column in SQL Server you need to rebuild such table and that is a more complicated feature we are considering to do in the future. That is tracked by #329. For RTM we are planning to issue a warning when this situation occurs, which is tracked in #4783.
