### ISSUE TITLE
Query: Flatten unnecessary SQL subqueries, e.g. when Take() before projection

### ISSUE THREAD

**Issue by bragma** [dotnet/efcore#4957]
Hi,
1. I'm aware that the position of take may correctly change the resulting query command because it changes the semantic.
2. I'm aware there are already many issues regarding take, but I've not found mine. Please forgive me if it's a duplicate.

Still I don't understand why the relative position of take() and select() change the query.

```
db.Users.Where(u => u.Name == "user1").Take(1).Select(u => new UserDTO
{
    UserId = u.UserId,
    Name = u.Name,
    LastName = u.LastName
}).ToList();
```

Produces the query:

```
SELECT [t0].[UserId], [t0].[Name], [t0].[LastName]
FROM (
    SELECT TOP(1) [u].*
    FROM [User] AS [u]
    WHERE [u].[Name] = 'user1'
) AS [t0]
```

While moving the take() after the select():

```
db.Users.Where(u => u.Name == "user1").Select(u => new UserDTO
{
    UserId = u.UserId,
    Name = u.Name,
    LastName = u.LastName
}).Take(1).ToList()
```

Generates the simpler query:

```
SELECT TOP(1) [u].[UserId], [u].[Name], [u].[LastName]
FROM [User] AS [u]
WHERE [u].[Name] = 'user1'
```

Is there space for optimization or am I missing something?

Thanks.

**Comment by divega** [comment]
@bragma thanks for creating this issue. Yes, I believe the reason the two queries generated are different is that we just haven't built the intelligence into our query pipeline to figure out that for the first query it could be possible to flatten the `Take()` operation and the projection together (or from a different perspective, lift the `Take()` operation over the projection to get the same query) instead of just taking the order in which you did things in your LINQ literally. 

Depending on the database engine this kind of "optimization" may or may not have an impact on the execution of the SQL, but it can certainly make it look nicer.

**Comment by bragma** [comment]
Thank you all for the answers!

**Comment by smitpatel** [comment]
Take is a result operator. It causes a subquery to generate. So when you put take there are outer & inner query model generated. Putting Take at the end means single flat query model hence no nesting in SQL.

At present, we lift subquery at query model level but the way joins are handled, if Select Expression is anything more than basic shape, we push it down to be safe. Which is causing nesting in this case.

#8094 is improving join translation pipeline which allows us to move away from always causing pushdown to only on required basis. Which would mitigate this issue totally.

I have added note in #8094 to consider this scenario.
