### ISSUE TITLE
When will EF7 for SQLite be Updated?  RC1 has Build Issue. 

### ISSUE THREAD

**Issue by maxmin88** [dotnet/efcore#4981]
On my old inactive post #4331 there is an issue with building release versions using EF7 RC1 for SQLite.  When the project is built for release any calls to the SQLite DB fail .  I tried the suggestions but they did not help.

I have several apps I am ready to release to Windows store but cannot because if I build the projects for release the apps crash when run.  Building the apps for Debug make them run crazy slow on the phone. I was hoping I wasn't going to have to redo my entire DB approach and leave SQLite.

**Comment by rowanmiller** [comment]
RC2 will be coming out as soon as everything is stabilized on the new .NET CLI. We don't have an exact date on that yet because the work is still ongoing. RC2 takes a vastly different approach to running under .NET Native - thanks to some improvements the .NET Native team made - so things should be a lot smoother in terms of release/,NET Native/publishing to store.
