### ISSUE TITLE
EF7 - UnitOfWork

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#4982]
Does anyone have any advice on implementing EF 7 in a library using the UnitOfWork pattern? See below an rough example. We want to be able to "wrap" separate calls to operations (methods) in our code base with a UnitOfWork in order to commit all the work as a unit. I know using EF 7 currently is demonstrated as using DI to inject the DBContext by the initializing project but that really does not feel natural to us. We want to better encapsulate the DB Access layer. For example we do not need access to it in the web site controllers.

Hope this question makes sense. Any thoughts on this matter are most appreciated.

Thanks!

EXAMPLE:

``` C#
public class UnitOfWork : IUnitOfWork
    {
        //[FromServices]
        public AppDBContext DbContext { get; private set; }

        public string Name { get; set; }

        public UnitOfWork()
        {
            DbContext = new AppDBContext();
        }

        public async Task CommitChangesAsync()
        {
            await DbContext.SaveChangesAsync();
        }

        #region IDisposable Support
        private bool disposedValue = false; // To detect redundant calls

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    DbContext.Dispose();
                }

                // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                // TODO: set large fields to null.

                disposedValue = true;
            }
        }

        // TODO: override a finalizer only if Dispose(bool disposing) above has code to free unmanaged resources. 
        // ~FactoryUnitOfWork() {
        //   // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
        //   Dispose(false);
        // }

        // This code added to correctly implement the disposable pattern.
        public void Dispose()
        {
            // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
            Dispose(true);
            // TODO: uncomment the following line if the finalizer is overridden above.
            // GC.SuppressFinalize(this);
        }
        #endregion
    }
```

**Comment by ajcvickers** [comment]
@chassq You can just new up a class derived from DbContext and dispose of it when done. EF will take care of creating a service provider for it to use internally. You will need to override OnConfiguring on the context or use a constructor that takes a DbContextOptions object in order to configure the connection string, etc.

If you need to both do this and also integrate with services from the application's D.I. container, then that's a bit tricky with RC1, but has been much improved for the RC2 release where there are methods on DbContextOptionsBuilder that can be used to pass in things like the LoggerFactory, or even tell EF to use the application's D.I. container as its own internal container.

**Comment by chassq** [comment]
Much Thanks!!! I will give that a try...

**Comment by gdoron** [comment]
@ajcvickers I would love to know how you recommend handling transactions with EF and ASP.NET core.
Would you use filter (which?) and in that filter you use `context.SaveChanges`.
(This question might be more suitable on the ASP.NET Home/MVC repro)
