### ISSUE TITLE
Using ef 7 in class library

### ISSUE THREAD

**Issue by AlexKulbako** [dotnet/efcore#5053]
I want to make the work with data in a class library with asp.net core 1. My problem http://stackoverflow.com/questions/36604855/how-to-use-entity-framework-7-in-class-library?noredirect=1#comment60807751_36604855 

Using the migration, I get the   InvalidOperationException in command line

**Comment by rowanmiller** [comment]
From the error displayed it seems like SQL Client is unable to connect to your database. I see you posted the screen shot, any chance you could give us the text from the error so that I can translate it?

**Comment by divega** [comment]
@rowanmiller the exception message was actually already there: "Exception instance". Doesn't sound familiar.

**Comment by divega** [comment]
I responded on the StackOverflow thread:

I think the instance failure is occurring because the connection string is incorrect:

``` C#
    @"Data Source=DESKTOP-R3AP4AT\\SQLEXPRESS;..."
```

Should actually be

``` C#
    @"Data Source=DESKTOP-R3AP4AT\SQLEXPRESS;..."
```

Or 

``` C#
    "Data Source=DESKTOP-R3AP4AT\\SQLEXPRESS;..."
```

I.e. don't use both a verbatim string (prefixed with @) and double backslash. 

I am not sure this answer your main question though.

@rowanmiller reminded me that the guidance is to leave the connection string in the `AddDbContext<TContext>()` call in the application's Startup.cs call and to use `MigrationsAssembly()` to tell migrations where to have the migrations, which should probably alongside the DbContext. E.g.:

``` C#
services.AddEntityFramework().AddDbContext<MyDbContext>(options => 
    options.UseSqlServer(connectionString).MigrationsAssembly(assemblyName));
```

From there one, you are still use the application startup to configure the right context and the connection string but your migrations can be located in your library.

**Comment by divega** [comment]
Closing as I believe I have answered your questions, but feel free to reply here or reactivate.

**Comment by AlexKulbako** [comment]
Thank you guys for your help)
