### ISSUE TITLE
dbcontext scaffold ignores project namespace

### ISSUE THREAD

**Issue by mi4t23** [dotnet/efcore#5170]
performing dbcontext scaffold, the project directory name is taken as root namespace and not configured project default namespace.

For example if a Project **XCompany.YProject** lives in subdirectory **YProject** of a solution and the default namespace for the project is configured as **XCompany.YStuff** scaffold ignores both the configuration and even the project name and takes directory name as root namespace for generated class which is wrong.

**Comment by rowanmiller** [comment]
@lajones I vaguely remember us fixing this issue already... is that correct?

**Comment by natemcmaster** [comment]
Potential the same issue as https://github.com/aspnet/EntityFramework/issues/4524?

**Comment by lajones** [comment]
Within RevEng we are passed a `RootNamespace` and an output path. If the output path is a _relative_ output directory within that project, then the generated namespace will be the concatenation of the two. If the directory is not relative the output namespace will just be the RootNamespace - see https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Tools.Core/Scaffolding/Internal/ReverseEngineeringGenerator.cs#L145.

However the code that passes in the `RootNamespace` has changed quite a bit since I last looked at it. If you invoke from Powershell on a project for which we can get `EnvDTE` (i.e. a `.csproj` or `.vbproj` project) we should use the `RootNamespace` property of that `EnvDTE.Project`. Outside of that @natemcmaster should comment.

**Comment by rowanmiller** [comment]
Ah, yep #4524 was the one I was thinking of... didn't realize we hadn't implemented that yet.
