### ISSUE TITLE
Better diagnostics for exceptions

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#5221]
We see a lot of issues filed that are lacking in specifics. E.g. No details about product version etc.

I think we could add more detail to logging/exceptions to improve this:
- Product version
- Configured providers
- Configuration values (change tracking enabled etc.)
- Model snapshot?

**Comment by ajcvickers** [comment]
Marking for re-triage. I think we should postpone this until post RTM for a few reasons:
* We should decide how much additional information to put into exception messages.
 * At one end of the spectrum, adding the product version seems pretty safe everywhere. At the other end, adding the full model could be problematic for large models.
 * We should probably make a guess for each exception as to what kind of additional informaton is useful.
* For cases where some information is not available at the place we throw--for example, because the code is metadata independent or a provider agnostic singleton, we need to decide whether it is worth changing the design of out services to make the information available.
 * Or maybe we don't put the information in the exception at that point but instead catch, wrap, and throw again higher in the stack--see next point.
* A lot of times with bugs we get generic exceptions like null refs or wrong number of items in the enumeration instead of exceptions we are explicitly throwing. In such cases should we find some places to catch, wrap, and throw, such as SaveChanges and query execution?
  * If so, what kind of exception should we throw as the wrapping exception?
  * Should we special case things like DbUpdateConcurrencyException?
  * Should we only do this and not do anything at the lower levels?
  * We're already logging at these places--would it be better to make it easier for people to get the logs rather than catching, wrapping, and throwing?

**Comment by ajcvickers** [comment]
Discussed in planning and decided to move this to backlog for now. New Issue template seems to be doing a good job of getting info on bugs.

**Comment by ajcvickers** [comment]
After further discussion, we think that the changes already made to logging are sufficient here.
