### ISSUE TITLE
Perf against Azure database...

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#5240]
Running @rowanmiller  build demo against latest RC2 release bits, and  using a SQL Azure DB, I get these results (notice the results come out in favor of EF Core when running against LocalDB.)
Test: 

```
 db.Customers.ToList();
```

 Iteration 0
- EF6.x:        59ms
- EF Core:     126ms
- Improvement: -114 %
  
  Iteration 1
- EF6.x:        53ms
- EF Core:     140ms
- Improvement: -164 %
  
  Iteration 2
- EF6.x:        64ms
- EF Core:     102ms
- Improvement: -59 %

**Comment by rowanmiller** [comment]
This is pretty interesting, I guess I never ran the whole set of tests against SQL Azure before (just the SaveChanges one to show the effect of batching).

The numbers I see aren't quite as bad, but they do show EF Core performing the same or worse for a simple SELECT against SQL Azure.

```
Query ToList
 Iteration 0
  - EF6.x:        24ms
  - EF Core:      35ms
  - Improvement: -46 %

 Iteration 1
  - EF6.x:        26ms
  - EF Core:      26ms
  - Improvement: 0 %

 Iteration 2
  - EF6.x:        22ms
  - EF Core:      21ms
  - Improvement: 5 %
```

The improvement is still there on more complex queries, but much less pronounced.

```
Query Complex
 Iteration 0
  - EF6.x:       151ms
  - EF Core:      89ms
  - Improvement: 41 %

 Iteration 1
  - EF6.x:        32ms
  - EF Core:      26ms
  - Improvement: 19 %

 Iteration 2
  - EF6.x:        24ms
  - EF Core:      23ms
  - Improvement: 4 %
```

This is actually consistent with what we have seen in the benchmarks. We just split the app and database server for those test runs and we now see SimpleQueryTests.ToList() running slower than EF6 - at least for the `tracking on, sync` variation, `tracking off` is on par with EF6 and `async` is faster. So this seems to be about a database with some latency rather than SQL Azure specifically.

**Comment by rowanmiller** [comment]
Hold on my comment about the benchmarks... looks like we have some anomaly results in there and the benchmarks haven't been running long enough on the new hardware for those outliers to come out in the wash.

**Comment by rowanmiller** [comment]
@ErikEJ I'm guessing you just ran this against the SQL Azure database you created using the script from the demo repo? If so, that was only ever setup for the SaveChanges demo to show the effect of batching. The customers table is empty, so the query isn't returning any data 😊. I overlooked this too, until I realized the SQL Azure queries were running a lot quicker than the LocalDb ones... which didn't seem right 😄.

Here are the results when I populate the SQL Azure table with the same data:

```
Query ToList
 Iteration 0
  - EF6.x:      1193ms
  - EF Core:     940ms
  - Improvement: 21 %

 Iteration 1
  - EF6.x:      1091ms
  - EF Core:     939ms
  - Improvement: 14 %

 Iteration 2
  - EF6.x:      1102ms
  - EF Core:     904ms
  - Improvement: 18 %
```

Interestingly, the much bigger improvement (~70%) when running against LocalDb actually seems to be that EF6 is doing something that causes the queries to be slow... I'm still digging into this one.

**Comment by rowanmiller** [comment]
Ignore my previous comment (removed) about the lower % improvement on Azure vs. LocalDb... this makes total sense since the majority of the test is spent round tripping, so the time spent in EF code is a much smaller % overall.

**Comment by ErikEJ** [comment]
Doh! Of course!
