### ISSUE TITLE
__EFMigrationsHistory table not populated on database create

### ISSUE THREAD

**Issue by Sohra** [dotnet/efcore#5249]
I'm using Microsoft.EntityFrameworkCore.Sqlite 1.0.0-rc3-20637, in Windows 10, in a .NET 4.6.1 application.

On startup I call `dbContext.Database.EnsureCreated()` and this creates the database with the full schema, however the __EFMigrationsHistory table is empty, and it should contain the name of the initial migration.

This problem prevents me from using code such as the following:

```
if (!dbContext.Database.EnsureCreated())
  dbContext.Database.Migrate();
```

When the database already exists, I want to execute any new migrations to bring it up to date, but with the current situation it'll throw because it'll try to reapply the initial migration over the database (can't create a table that already exists, for example).

If I manually insert the version information into this table then Migrate() works as expected without throwing.

**Comment by rowanmiller** [comment]
This is by design. `EnsureCreated()` just brute force creates the schema without paying any attention to migrations etc. It is mostly designed for testing, or scenarios where you don't care about upgrading the database.

I think you just want to call `Migrate()` - it will take care of creating the physical database if it doesn't already exist.

**Comment by ErikEJ** [comment]
@rowanmiller Maybe an update to the xml docs for EnsureCreated stating just that would be helpful?

**Comment by Sohra** [comment]
Good to know then, thanks

**Comment by rowanmiller** [comment]
Opened https://github.com/aspnet/EntityFramework/issues/5306 to update the docs
