### ISSUE TITLE
SaveChangesAsync() sometimes throws erros if in a method that is not awaited

### ISSUE THREAD

**Issue by f0rt** [dotnet/efcore#5257]
Hi team,
**I have:**
- VS2015U2
- MVC 6 website
- that targets DNX 1.0.0-rc1-update2
- reference to EF 1.0.0-rc1-final

I've implemented 2 classes similar to these below:

```
public class MyService
  {
    private readonly ApplicationDbContext _dbContext;

    public MyService(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task SaveAsync(int myInt)
    {
        _dbContext.ObjectDataSet.Add(myInt);
        await _dbContext.SaveChangesAsync(); //<< THIS IS THE FAULTY LINE
    }
}
```

and 

```
public class MyService2
{
  private readonly ApplicationDbContext _dbContext;

  public MyService2(ApplicationDbContext dbContext)
  {
     _dbContext = dbContext;
  }

  public async Task<string> GetAsync()
  {
     MyService s1= new MyService(_dbContext);
     s1.SaveAsync(123); // Intentionally not await-ed
     return "123";
  }
}
```

and a MVC controller:

```
public class MyController : Controller
{
  [FromServices]
  public MyService2 s2{ get; set; }

  [HttpGet()]
  public async Task<IActionResult> Get() {
     return
        Json(
           await s2.GetAsync());
  }
}
```

When I load the page in the browser I get behavior that varies:
- Sometimes it runs without errors
- Sometimes I get InvalidOperation exception: The requested operation cannot be completed because the connection has been broken.
- Sometimes I get TaskCancelledException: A task was canceled.

When I write "await" in front of the line
    s1.SaveAcync(123);  // Intentionally not await-ed
I get no errors.

P.S. Sorry for the long example but I couldn't isolate it more.

**Comment by khionu** [comment]
Async... without awaiting, your async methods will not hold up your threads, meaning the next portions of your code will execute without pausing... when your code is executing portions that depend on other portions  that that haven't finished executing yet, you get a Race Condition. Race Conditions are one of the reasons people not used to async should be wary.

**Comment by divega** [comment]
@f0rt TL;DR: You will have to await.

You may need to change your expectations on what async support on EF Core (or EF6 for that matter)is about: for applications executing on a server is actually about improving scalability by freeing up threads when they would otherwise have to wait idle for database operations to complete. It doesn't mean that you can "fire and forget" async operations so that they can complete in any order independent of the lifetime of the `DbContext` and the underlying database connection. In general you have to await for any individual task that you initiate on a `DbContext` so that all operations occur in the same sequence that they would normally occur if you were not using async. 

In the particular case of this code:

``` C#
  public async Task<string> GetAsync()
  {
     MyService s1= new MyService(_dbContext);
     s1.SaveAsync(123); // Intentionally not await-ed
     return "123";
  }
```
What I would expect is that `SaveAsync()` would initiate and maintain control of the thread until the first I/O operation occurs that returns a Task that is not already completed. When the latter happens control will be yield to the next line `return "123" (you made the `GetAsync()` async but didn't put any await in it. Next the controller operation will finish and the controller instance be freed up and the DI scope of the request will get disposed, at which point any `IDisposable` scoped services you used in the controller, including the `DbContext` will get disposed. The latter will cause the underlying `DbConnection` to be disposed as well, very likely before the async operations originally initiated by `SaveChangesAsync()` can be completed. 

You are getting different results because you have introduced a race condition. I.e. depending on how fast the async operations get completed you may be in different stages of finishing the request.

**Comment by f0rt** [comment]
Thank you very much for the fast response. I suspected something like this but wanted to check that with you. It sound very clear now when you explain but I couldn't find anything in the net for that. Maybe it will be a good idea to mention that "Always await for awaitable DB operations" in the documentation. I've actually spent a a couple of hours debugging this on a azure website. You know debugging experience on azure website is not very fun (yet). :)

**Comment by khionu** [comment]
Or better yet, you can learn how to properly utilize Async
https://msdn.microsoft.com/en-us/library/hh873177(v=vs.110).aspx

**Comment by divega** [comment]
Triage: I agree with @f0rt that thus is a topic we should add in the documentation if we don't have it already.

**Comment by rowanmiller** [comment]
Added note to https://github.com/aspnet/EntityFramework.Docs/issues/158 to ensure we doc this when we do query docs
