### ISSUE TITLE
How to generate custom IDs?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5303]
EF7 does all the usual stuff about auto-generating auto-incrementing IDs. Now, I have some tables that require custom key generation on insert.
1. COMB Guids. i.e. Guids that get inserted (close to) sequentially so they don't wreak havoc with the clustered index.
2. One table has a custom GUID generated from the hash of some other values on the table, to ensure that the ID is consistent over all our environments.

I saw your video [here](https://channel9.msdn.com/Blogs/Seth-Juarez/Key-Generation-Strategies-in-Entity-Framework-7), but it doesn't deal with the cases I mentioned.

How do you generate custom IDs?

**Comment by rowanmiller** [comment]
Are values generated in the database, or in memory prior to insert? Also, it this an existing database, or are you using migrations to create the database from the model?

**Comment by shaulbehr** [comment]
We *could* generate the COMB GUIDs in the database, but a good part of the reason why we chose to have GUID keys is so that we can generate them in memory and have the values available before we insert.

This is an existing database; we're migrating to EF7 from NHibernate.

**Comment by rowanmiller** [comment]
@ajcvickers can you point in the right direction for using a value generator to do this.

**Comment by shaulbehr** [comment]
@ajcvickers I will be most grateful for any assistance you can offer!

**Comment by shaulbehr** [comment]
Bump.  @rowanmiller , @ajcvickers could you please point me in the right direction for this?

**Comment by ajcvickers** [comment]
This is not very easy to do with the current bits. We need to add some sugar that will do most of the heavy lifting for you, but until we do that here are the steps to get custom value generators to work.

1) Implement a custom value generator. Something like:
```C#
public class CustomGuidValueGenerator : ValueGenerator<Guid>
{
    public override Guid Next() => // Logic for generating values

    public override bool GeneratesTemporaryValues => false;
}
```
Note that there is already an implementation to generate sequential GUID values on SQL Server (SequentialGuidValueGenerator) and this is actually the default value generator we use for GUIDs when using SQL Server.)

2) Extend the ValueGeneratorSelector for your provider to let EF know which properties need to use the new value generator. Using InMemory as an example:
```C#
public class CustomInMemoryValueGeneratorSelector : InMemoryValueGeneratorSelector
{
    public CustomInMemoryValueGeneratorSelector(IValueGeneratorCache cache)
        : base(cache)
    {
    }

    public override ValueGenerator Create(IProperty property, IEntityType entityType)
    {
        if (property["SpecialGuid"] != null)
        {
            return new CustomGuidValueGenerator();
        }

        if (property.ClrType == typeof(Guid))
        {
            return new SequentialGuidValueGenerator();
        }

        return base.Create(property, entityType);
    }
}
```
In this example the code looks for an annotation on the property (see below) and if present it will use the special value generator, otherwise it uses the sequential generator, otherwise it falls back to whatever the provider's default is.You don't have to use an annotation here; you can use whatever information makes sense (property type, name, etc.) to determine which generator to use.

3) Create a service provider that will use the new selector. The service provider should be created once and cached somewhere in your application. Normally EF does this for you, but when adding in a custom service you have to control it yourself.
```C#
private static readonly IServiceProvider _serviceProvider
    = new ServiceCollection()
        .AddEntityFrameworkInMemoryDatabase()
        .AddScoped<InMemoryValueGeneratorSelector, CustomInMemoryValueGeneratorSelector>()
        .BuildServiceProvider();
```

4) In your DbContext class (or in AddDbContext for an ASP.NET application) tell EF to use the service provider that you created:
```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder
        .UseInternalServiceProvider(_serviceProvider)
        .UseInMemoryDatabase();
```

5) Provide some metadata to tell EF that you want a value generated and how to generate it. For example:
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder
        .Entity<SomeEntity>()
        .Property(e => e.SpecialId)
        .HasAnnotation("SpecialGuid", true)
        .Metadata.RequiresValueGenerator = true;
}
```
In this case the code adds the "SpecialGuid" annotation to the property that is then used by the selector code above. Also, for a non-key property, the RequiresValueGenerator flag should be set to true to tell EF that the property needs to have a value generated. Key properties already have this set.

Obviously, doing all this for a simple value generator is not very practical. I will assign this bug for re-triage to add some simple sugar to avoid all the selector and service provider stuff for simple cases.

**Comment by shaulbehr** [comment]
@ajcvickers Thanks for that info!  Very happy to hear that COMB Guids are the default behavior for Guid keys; that will save me (and others) a lot of time and effort!
Meanwhile, I followed your example for a custom generator, but I'm missing one trick, and that is how to make the Id a function of other fields on the record.  The generator is basically operating from a static context, with no information about the object for which it is generating an Id.  Is there some way to get a reference to that object passed through to the generator, or at least to the values that it will need in order to generate the id?

**Comment by ajcvickers** [comment]
@shaulbehr Is it that you want to use both some data from the entity and some static state? Or is it simply a property whose value is computed from other state in the entity? If it is the latter, then I don't think you need a value generator to do that. If it is the former, then I don't think that is possible at the moment but I am looking into how to enable it.

**Comment by shaulbehr** [comment]
@ajcvickers It is generated purely from a hash of some data values on the record, nothing else.
How would you recommend we do this?

**Comment by ajcvickers** [comment]
@shaulbehr Can it just be a computed property of the entity? Regardless, I have sent out PR #5423 that would allow this to work.

**Comment by shaulbehr** [comment]
Thanks, I got it working using the ValueGenerator.  OOI, how would I have written a computed property?

**Comment by rowanmiller** [comment]
@shaulbehr I think @ajcvickers just meant a getter-only property, that EF would ignore:

public string Hash
{
    get { return <logic to compute hash>; }
}

**Comment by rowanmiller** [comment]
Closing as I think we have done all the work needed here, but feel free to ask any follow up questions.

**Comment by ajcvickers** [comment]
@rowanmiller I couldn't find any item on the backlog to track making it easy to set a simple value generator for a property. I was hoping we would triage this bug into that.

**Comment by rowanmiller** [comment]
@ajcvickers good point, I thought we had one already on the backlog... but I couldn't find it 😄. Opened https://github.com/aspnet/EntityFramework/issues/5537.
