### ISSUE TITLE
In PM Command line input “Update-Database newbook” when My models are Modified but result is error 

### ISSUE THREAD

**Issue by applenele** [dotnet/efcore#5437]
In PM Command line input “Update-Database newbook” in order to modify db when My models are Modified but result is error 
and Chinese garbled。
![611961-20160519002012529-789919599](https://cloud.githubusercontent.com/assets/5456023/15413880/5a13327a-1e67-11e6-9733-df5d2c726035.png)

**Comment by applenele** [comment]
And If I remove the db ,it worked.i want modify the field only and  retain the original data

**Comment by Kagamine** [comment]
Here is EF Core, you'd better open an issue on Codeplex (EF repo).

**Comment by gdoron** [comment]
Are you using entity framework core?

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing?

cc @roji

**Comment by Kagamine** [comment]
I suppose he has used DbContext.Database.EnsureCreated(). Migration cannot be used in this scene.

**Comment by applenele** [comment]
This is a article that records my problem in Chinese but Code is clear.You can have a look,Later I will provide a detailed Code.
think you.
@rowanmiller

**Comment by applenele** [comment]
Yes,I am using  entity framework core
@gdoron

**Comment by applenele** [comment]
I find a same issue [__EFMigrationsHistory table not populated on database create](https://github.com/aspnet/EntityFramework/issues/5249) ,i get it.
