### ISSUE TITLE
Where did InternalEntityEntry.GetPrimaryKeyValue() go?

### ISSUE THREAD

**Issue by ninety7** [dotnet/efcore#5438]
I have 2 DbContexts and want to see if an entity from context 1 is loaded on context 2. On RC1, there was the method `GetPrimaryKeyValue()` that I would call on the `InternalEntityEntry` class on context 1, and then just call the `TryGetEntry()` method on context 2's infrastructure; but it's gone on RC1. I've gone back and forth on the new API but cannot find something similar.

Does anybody know how I can achieve this on RC2?

**Comment by ajcvickers** [comment]
@ninety7 The APIs for our internal code were changed because the state manager no longer stores entities in the same way and doesn't ever calculate keys in this way.

To do this using the public surface you would want to query the state manager using context.ChangeTracker.Entries. This is probably not going to be very fast and I think it would be worth us adding an API to look up in the state manager by key values, probably as part of the implementation of Find, which is tracked by #797.

If you want to keep using internal APIs (which may change without notice in any release, but if you are okay with that then we're okay with them being used), then you could try using IStateManager.TryGetEntry, passing in the IKey and a ValueBuffer with key values in it. You have to make sure the key values are in the correct place in the ValueBuffer. See the test Exception_in_SaveChanges_causes_store_values_to_be_reverted for an example of this.

**Comment by ninety7** [comment]
Thanks for your help @ajcvickers. I'm trying to sync entities between contexts but cannot easily create a `ValueBuffer` from a boxed entity (`object` type). I'll stick to querying the `context.ChangeTracker.Entries` collection. I'll subscribe to #797 and hope that you add a way to retrieve/search key values from the state manager.
