### ISSUE TITLE
How can I update a range of unique values?

### ISSUE THREAD

**Issue by flagbug** [dotnet/efcore#5452]
Let's say I have the following class:

``` csharp
public class Foo
{
    public int Id { get; set; }

    [Unique]
    public int Position { get; set; }
}
```

The `Position` property is for ordering purposes and is unique.
In my database, I have a list of Foos, something like this:

`{ Id: 100, Position: 0 }, { Id: 101, Position: 1 }, { Id: 102, Position: 2 }`

Now I want to insert a new `Foo` at the beginning of the "list", so I read all foos, increment their position by 1 and assign the new `Foo" the`Position = 0`.

The problem is, that the underlying SQL database now throws `An error occurred while updating the entries. See the inner exception for details.Cannot insert duplicate key row in object 'dbo.Foos' with unique index 'IX_Foos_Position_Index'. The duplicate key value is 0.`. 
This exception happens for every other position value too.

Is this something Entity Framework should/could handle, and is there a workaround for now?

**Comment by smitpatel** [comment]
Basically exceptions are thrown because values are added/updated before the previous record holding same value is updated. i.e. New record with position 0 is added but the old record with position 0 has not changed its value therefore duplicate value. Same will happen at the update time. For this case the update/insert statements needs to be sent in decreasing order of Position. So that Position 2 is moved to 3 making space for 2 so lower records can move.

As for work-around for now,
You can update records one by one and call `SaveChanges()` in the decreasing order of position so that duplicate values do not arise.

**Comment by rowanmiller** [comment]
This would also be a scenario where dropping down to raw SQL would be a good option...

```c#
context.Database.ExecuteSqlCommand("UPDATE dbo.Foo SET Position = Position + 1 WHERE ...");
```
