### ISSUE TITLE
RC2 and migrations on Azure website

### ISSUE THREAD

**Issue by bragma** [dotnet/efcore#5486]
Hi,
while porting from RC1 to RC2 I've stumbled on this ancient piece of code doing migrations on ASP NET Core app configuration:

```
if (Configuration.GetValue<bool>("Data:DBConnection:Migrate"))
{
    using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
    {
        using (var context = serviceScope.ServiceProvider.GetService<EfContext>())
        {
            context.Database.Migrate();
        }
    }
}
```

It did the trick, but it's not nice to scaled out web apps. Not that RC2 is out, what's the suggested way of migrating an azure web app with an azure sqlserver?

When deploying with VS I've noticed a new "Entity framework Migrations" tab under "settings". Is it working? Is there some docs explaining how it works?

Thanks a lot!

**Comment by rowanmiller** [comment]
> When deploying with VS I've noticed a new "Entity framework Migrations" tab under "settings". Is it working? 

Yes, you should use that new functionality. It performs the migration during deployment, rather than post-deployment during app startup. 

> Is there some docs explaining how it works?

cc @danroth27 @sayedihashimi to see if the feature is documented anywhere. It uses the dbFullSql WebDeploy provider to execute the migration script against the target database.
