### ISSUE TITLE
RC2 migrations wrong table names (using class names with namespace)

### ISSUE THREAD

**Issue by oyvindvol** [dotnet/efcore#5488]
Hi. I migrated from RC1 to RC2, and am having trouble getting my database to update pending migrations (`Database.Migrate()`). 

I have no changes in my model, and the first migration I created with RC2 is removing and adding all foreign keys, primary keys, indexes, and renaming tables. One problem seems to be that the table names in the generated migration is the full namespace path to my model classes representing the database tables. Since that is not the correct table names in the database, the migration call fails:

```
migrationBuilder.DropForeignKey(
    name: "FK_LIS.Web.Models.Lis.Comment_LIS.Web.Models.Lis.Delegation_DelegationId",
    table: "LIS.Web.Models.Lis.Comment");
```

The actual table name in the database is `Comment`, so the migration throws an exception at `Database.Migrate()`.

I have added this one to my `OnModelCreating()` method:

```
foreach (var entity in builder.Model.GetEntityTypes())
{
    entity.Relational().TableName = entity.DisplayName();
}
```

Does anyone know how to avoid the generated migrations using the full namespace path to the model classes?

**Comment by matthewjcooper** [comment]
I had the exact same issue. Since i'm not in production yet, I just blew away all my migrations and created a new initial one, but if anyone is running in prod this is a major bummer.

**Comment by oyvindvol** [comment]
Ahh, luckily I am not in production either, so I deleted all the migrations and created one large new one, and it worked..

**Comment by ShikiGami** [comment]
I'm using it in production, what the hell can I do?

**Comment by oyvindvol** [comment]
@ShikiGami is the foreign keys getting a "1"-number added at the end?

**Comment by ShikiGami** [comment]
No, the names are completely wrong, specially all of the keys that have to do with identity and roles.

As a simple example, I'm getting `FK_AspNetUserRoles_AspNetRoles_RoleId` instead of the real FK `FK_IdentityUserRole<string>_IdentityRole_RoleId`

Also, all the FK that have to deal with tables with discriminators, have in the middle the name of the actual table instead of the name of the discriminator.

The migrations I'm getting are completely unusable.

**Comment by ShikiGami** [comment]
Also I'm getting another bug, when every time I try to create a Migration, it makes the ApplicationDbContextModelSnapshot unusable.
It replaces all `.HasDefaultValue(false)` with `.HasDefaultValue("False")`, and then it crashes because `"False"` is of type string.

**Comment by smitpatel** [comment]
> As a simple example, I'm getting  FK_AspNetUserRoles_AspNetRoles_RoleId  instead of the real FK  FK_IdentityUserRole<string>_IdentityRole_RoleId 

That is what we have changed in RC2. Instead of using display name of entitytype's clr type, we changed it to use the actual table name. And it makes more sense that way since the FK `FK_AspNetUserRoles_AspNetRoles_RoleId` is FK on table `AspNetUserRoles` which references `AspNetRoles` table and uses `RoleId` as foreign key property. See #3545 for more info.

FK with tables with discriminator is also facing the same change. So previously where middle name referred to the appropriate entity (it was name of entity and not the discriminator), it now refers to the table, which would be same for all entities in hierarchy.

I will look into `HasDefaultValue("false")` issue.

**Comment by nmilosev** [comment]
This is affecting me as well. Table names are full class names with namespaces. I had to manually modify my migration class by removing all the rename statements and dropping and remaking keys.

Any fix available for the next time?

**Comment by bricelam** [comment]
This is caused by using Migration classes that were generated using a pre-release version. It is advised to start clean with Migrations on 1.0.0

**Comment by nmilosev** [comment]
Hello, thanks for replying. My database is in production so starting clean is a bit difficult... For now I'm good, but the main issue I find here is that even when specifying the table name with Table attribute, the Migration generator doesn't respect it. Is that a bug or the table names are now always fully classified class names?

Cheers.
