### ISSUE TITLE
RC2: "Unable to find provider assembly with name EntityFramework.MicrosoftSqlServer" error

### ISSUE THREAD

**Issue by tdjastrzebski** [dotnet/efcore#5498]
An attempt to scaffold database as described here:
https://docs.efproject.net/en/latest/platforms/full-dotnet/existing-db.html
results in error:
"Unable to find provider assembly with name EntityFramework.MicrosoftSqlServer. Ensure the specified name is correct and is referenced by the project."
All three required packages have been successfully installed. It worked for RC1

**Comment by rowanmiller** [comment]
Your scaffold command has a provider package name in it, you need to swap to the RC2 provider name - which is `Microsoft.EntityFrameworkCore.SqlServer` (the error suggests you are still specifying the RC1 package name of `EntityFramework.MicrosoftSqlServer`).

**Comment by lajones** [comment]
That's the error you would see if you executed `Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" EntityFramework.MicrosoftSqlServer`. 

For RC2 you need to do `Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer`. Note the change to the provider name.

**Comment by scottz1** [comment]
I have a WPF 4.61 app using EF6. When I try to follow this article and scaffold in my repository project, I get this error:

PM> Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=MyDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer

Unable to find provider assembly with name Microsoft.EntityFrameworkCore.SqlServer. Ensure the specified name is correct and is referenced by the project.

The reference to the assembly is definitely in the project. Is it a problem because the project is also still using EF6? I can't compile without that and EF Core 2 requires it to build.
I was able to convert a separate console app from EF6 to EF Core 2.0.
