### ISSUE TITLE
Migrations: Data motion APIs

### ISSUE THREAD

**Issue by ansydor** [dotnet/efcore#5642]
There is nothing that can help to manipulate with data with migrations:
basically it can be implemented like 
`migrationBuilder.Sql("Insert ...");`
but would be grate to implement it like:
`migrationBuilder.Insert.IntoTable("Users").Row(new { FirstName = "John", LastName = "Smith" });`

there is a case why really need it this way:
there is a table `Posts` with string content column, but if I want a table `Contents`, so i want to add a table, select data, insert data and then delete column

**Comment by divega** [comment]
@bricelam in triage we discusses that this was probably a dupe of an existing issue to support data motion functionality. Can you please help me find that issue? :smile:

**Comment by bricelam** [comment]
Well, there's [Work Item 16](http://entityframework.codeplex.com/workitem/16) on EF6 :smirk: Looks like it never made it to our EF Core backlog. We'll use this issue.

**Comment by bricelam** [comment]
In addition to inserting, updating, and deleting data. This issue also covers transferring or moving data between tables.

**Comment by grahamehorner** [comment]
please consider sharding/partitioning data

**Comment by bricelam** [comment]
Note, in version 2.0.0, we added `InsertData()`, `UpdateData()`, and `DeleteData()` migration operations.

**Comment by ajcvickers** [comment]
Note from triage: Migrations code cannot reference application types since changes in those types will break existing migrations. This means there is little value in any API here over just writing SQL directly using `migrationBuilder.Sql("...")`.

**Comment by pmoleri** [comment]
> Note from triage: Migrations code cannot reference application types since changes in those types will break existing migrations. This means there is little value in any API here over just writing SQL directly using `migrationBuilder.Sql("...")`.

I think it still adds quite some value.
E.g.
 - If you write migrations for different DBs you need to make subtle syntax changes.
 - For MS SQL using `migrationBuilder.Sql("...")` will generate a valid script only while the table columns still exist, otherwise the script will fail to parse and you need to wrap your SQL in a an `exec("")` and escape strings inside. See: https://github.com/dotnet/efcore/issues/17826

So, it helps with the correctness of the migration scripts and portability to different DBs.
