### ISSUE TITLE
Attempt to build following wiki instructions fails

### ISSUE THREAD

**Issue by rendmath** [dotnet/efcore#5740]
### Steps to reproduce

Attemps to clone and build the source code following the instructions in the [wiki](https://github.com/aspnet/EntityFramework/wiki/Getting-and-Building-the-Code) fails during the "build initialize" phase.
### The issue

Many packages are deemed "`not compatible with netcoreapp1.0 (.NETCoreAPP,Version=v1.0)`"
### Comments

Clone done  using --depth=1 to reduce the amount of content to download.
### Further technical details

EF Core version: dev branch (commit 18a110e581b1a81325f1dee6e756f3681d768f7c)
Operating system: Windows 8 64-bits
Visual Studio version: n/a

**Comment by divega** [comment]
Most of our RTM runtime packages (currently versioned as `rc3-*`) have been recently rebuilt to target a newly introduced TFM `netstandard1.6` instead of the `netstandard1.5` Tom they targeted for RC2. The new TFM is compatible with `netcoreapp1.0` (the TFM targeted by most of our applications), but the Preview1 version of the tooling (and the NuGet components that come with it) is not aware of that. So if you try to use RC3 packages with the Preview1 version of the tooling, package restore will complain that these packages are not compatible with `netcoreapp1.0`.
 
As far as I am aware, you have three options:
 
1. Stick to the rc2 versions of the packages: the dependencies are all in NuGet.org and the code is currently in the master branch. These are compatible with the public Preview1 version of the tooling. 
2. Upgrade to a Preview2 version of the tooling (e.g. nightly CLI builds, or wait until we ship Preview2 for VS) so you can use RC3 code and packages directly
3.      As a temporary hack, add `netstandard1.6` to the list of imports for any project.json file that targets `netcoreapp1.0` e.g.:
 
``` JSON
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "netstandard1.6" ]
    }
  }
```
 
The latter hack may not work if other things changed that require newer tooling.

**Comment by divega** [comment]
The hack of adding `netstandard1.6` to the imports I mentioned above may help building project.json based apps, but I am not sure will help with building EF following the instructions in the wiki (which use `build initialize`). 

cc @bricelam @natemcmaster

**Comment by rowanmiller** [comment]
If there isn't a semi-easy way to build the source using public bits then we should probably just replace the instructions with a "not currently possible" notice. It will only be for a short period.

**Comment by divega** [comment]
@rowanmiller I believe the instructions should still apply to the master branch, which may still be a useful thing to do depending on the user's motivation to build the code. Maybe we should update the instructions to add a step to pick a branch and also a disclaimer that the dev branch may not be buildable at all times?

**Comment by natemcmaster** [comment]
Our CI builds on AppVeyor run "build.cmd" without anything special and has been passing. (See https://ci.appveyor.com/project/aspnetci/entityframework/branch/dev and https://github.com/aspnet/EntityFramework/blob/dev/appveyor.yml). Most build errors are caching or point-in-time errors. I'm guessing this one is due to a stale version of .NET Core CLI.  This occurs because KoreBuild caches the version of build tools in `(repo root)/.build/` on local machines. Deleting this an re-running the build script ensures the latest versions of .NET Core CLI will be installed. Cref https://github.com/aspnet/KoreBuild/issues/72

**Comment by divega** [comment]
@natemcmaster ah, good point! I was having this issue with other apps using the Preview1 tools, but since the build in our projects will download the CLI you just need to make sure it is up to date.

Closing since I believe this answer the question.

**Comment by rendmath** [comment]
Deleting the .build folder (or recloning the entire repository for that matter) did not change anything here.
* Both NuGet feeds are accessible.
* The NuGet packages and caches have been cleared (lauched nuget.exe from the .build folder).

Here is the build output:
[failed.txt](https://github.com/aspnet/EntityFramework/files/313242/failed.txt)

**Comment by rendmath** [comment]
We finally got it to work after manually deleting the AppData\Local\Microsoft\dotnet folder.
I suggest adding it in the "Solving common build initialize errors" steps in the wiki.

**Comment by natemcmaster** [comment]
@rendmath thanks for the feedback. I've updated the wiki page.
