### ISSUE TITLE
Some table that got two properties on same reference type

### ISSUE THREAD

**Issue by LstpierreMaximum** [dotnet/efcore#5792]
### Steps to reproduce

I'm passing a project ef 6.1.3 that was using database first moving to ef 6.1.3 code first
and now passing to ef core code first

the generated code was ajusted to help the migration
the ef core code was lightly adjusted to need my need (added a IMaxEntity.cs)

THE PROBLEM is when I got a cross reference class that got 2 properties 

class A
class got a collection of class B

class B got 2 properties of type A

see code, you can run the "testsmall" project  (in testcomple.zip)
cannot attach the files, son you can get it from this link

https://1drv.ms/f/s!Aph9oU2dEjC8qkeu9L_VUANU39G2
(2 files : Word documents and the complete source file including EF ready to build)

I cannot exclude the property

**Comment by ajcvickers** [comment]
@LstpierreMaximum The problem is that there are two navigation properties pointing from CashingDepositAmounts to CashingDeposit. The first is DepositTransaction and the second is Transaction. There is only one navigation property on CashingDeposit that points back to CashingDepositAmounts. This is a situation where you need to tell EF how these navigation properties are related. For example:
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<CashingDepositAmounts>()
        .HasOne(e => e.Transaction)
        .WithMany(e => e.DepositAmounts)
        .HasForeignKey(e => e.TransactionId);

    modelBuilder.Entity<CashingDepositAmounts>()
        .HasOne(e => e.DepositTransaction)
        .WithMany()
        .HasForeignKey(e => e.DepositTransactionId);
}
```
The actual relationships may be different from this--this is just my guess based on looking at the code.
