### ISSUE TITLE
Reverse Engineer: Visual Studio Item Template Wizard

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#5837]
We've talked about this, but I couldn't find an issue for it...

We should have a workflow similar to EF6:
1. **Project** > **Add New Item...** > **ADO.NET Entity Data Model**
2. Choose **Code First from database**
3. Specify a provider and connection string
4. Select database objects and specify additional options

**Comment by ErikEJ** [comment]
In the meantime, I have added a simple GUI Tool to my SQLite / SQL CE Toolbox for VS 2010 and later, that allows you to generate a EF Core Model for SQL Server, SQLite and SQL Server Compact https://github.com/ErikEJ/SqlCeToolbox (currently included in the "daily" build)

**Comment by rowanmiller** [comment]
@ErikEJ nice, just tried it out. Not sure if you have these planned... but it would be good to be able to put the output files into a folder. Also would be cool to install the EF Core runtime packages if they aren't already in the project 😄.

**Comment by ErikEJ** [comment]
Thanks, Rowan. 
Re folder: Yes, it is planned.
Re runtime: yes, thought about at least adding a check for that, but first I would like to wait for VS 2017 RTM to test with the new project system. And what if the user wants to drop the poco classes in one project and the DbContext in another... then I would avoid requiring EF Core runtime..

Actually I think I will make an option to specify what to drop (poco, dbcontext or both)

**Comment by ErikEJ** [comment]
@rowanmiller  Thanks for taking your time to provide feedback!
The latest daily build supports OutputPath, and warns if the provider package is missing. (In addition to some UI fixes re Window location, control layout and tab order)

**Comment by mguinness** [comment]
Have MSFT considered working w/ a 3rd party to achieve this?  There is an excellent product by Devart called [Entity Developer](https://www.devart.com/entitydeveloper/editions.html) which has EF Core support.

They've done this in the past with Dotfuscator Community Edition and Devart has a similiar Entity Developer Express Edition (which is limited to 10 tables).  Seems like this could be advantageous for both companies if a licensing deal could be agreed upon.

**Comment by ErikEJ** [comment]
@mguinness The sqlite toolbox does this already for sqlite, sql server and sqlce

**Comment by mguinness** [comment]
@ErikEJ Although you have a great tool, it isn't a full replacement for the old EDMX designer yet.  Maybe I'm missing something (I saw the DGML export), but there is no GUI to view the database entities.

I could be wrong, but I think a lot of EF6 users are looking for the EDMX designer experience (using database first) which Entity Developer provides (see below).  If you have plans to add that functionality that would be awesome.

![image](https://user-images.githubusercontent.com/14002844/29324877-80a1a952-819a-11e7-97dd-3b11ce87ffbf.png)

**Comment by bricelam** [comment]
@mguinness You're looking for issue #1027

**Comment by mguinness** [comment]
@bricelam Ah yes, you're correct.  Apologies for muddying the waters here.

**Comment by ErikEJ** [comment]
I have implemented this in my "EF Core Power Tools" - try it out and let me know what you think! https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools

**Comment by ErikEJ** [comment]
@syndicatedshannon Just publish your VS Database Project to a new LocalDB database, and refresh schema form that

**Comment by syndicatedshannon** [comment]
No thank you ErikEJ. That's specifically the type of deployment-hard-linked toolchain I'm looking to avoid.

**Comment by bricelam** [comment]
Looking for #4321?

**Comment by syndicatedshannon** [comment]
@bricelam : Yes, that would match, thank you for the reference.

Although, I had hoped it wouldn't require writing to a separate API, for example if there was a neutral way to approach both external DB and VS SSDT database projects. I see, looking at the DACFX API Rowan linked, where that would be an excellent toolset, but without the correct abstractions in this issue here, I probably wouldn't really have any shortcuts to produce the tooling myself.

Ultimately, I have a broader concern that EF may still have regressed in supporting multidisciplinary teams (data separate from code), even when reaching the target "ready to replace EF6" status. I see so many tools built to avoid working with DDL, and demoting DDL to secondary concerns, or wrapping it in lambdas, or fluent syntax, or requirements to first be an OO developer. While I have those OO skills, I'm very expensive.

I also feel those techniques really aren't a good low-impedance vehicle to convey or store authoritative schema, in many relational data scenarios. I appreciate the capabilities provided by EF, but I worry its changes are backing us into a corner.

Anyway, I'll promote #4321 where I can. Thanks again.

**Comment by ajcvickers** [comment]
Closing this for now because we are not planning on implementing this at this time. (Also, @ErikEJ has already implemented something like this in the EF Core Power Tools.)

We may reconsider putting something in the box for this based on feedback/telemetry, since that would be useful for a different class of user, but the cost of shipping in VS is very high, so at least for now we're not planning on doing this.

**Comment by MarcoLoetscher** [comment]
It's a very bad decision to close this issue. This is a [critical O/RM feature](https://github.com/aspnet/EntityFrameworkCore/wiki/roadmap#critical-orm-features) on  your roadmap. If the costs are too high to ship the function with Visual Studio, it can be provided as an extension. I don't understand why the world's largest software company (Microsoft) cannot recruit enough staff for this project (EF Core). I hope that as many developers as possible will protest against it.

**Comment by ErikEJ** [comment]
@MarcoLoetscher Have you tried my free Visual Studio extension (EF Core Power Tools)? 
I would be happy to work with you on anything that you miss.

**Comment by ajcvickers** [comment]
@MarcoLoetscher Can you explain why you think this is so important?

**Comment by MarcoLoetscher** [comment]
It makes life easier for us developers. You could also ask what an IDE like Visual Studio needs. Most people get along better with visual tools than with a command-line.
