### ISSUE TITLE
C# 6.0 string format does not work on Required DataAnnotation

### ISSUE THREAD

**Issue by Ponant** [dotnet/efcore#5857]
### Steps to reproduce

Console App .Net Core
### The issue

`using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;`

```
public class B
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = nameof(Works) + "cannot be empty")]
        public string Works { get; set; }

```

```
    [Required(AllowEmptyStrings = false, ErrorMessage = $"{nameof(DoesNotWork)} cannot be empty")] //Not working
    public string DoesNotWork { get; set; }

}
```

Will not compile with error owing to property DoesNotWork.
Error Message:
_An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type_

While I have seen this kind of error message on Stackoverflow, it is still not clear why this does not work because the first property works ok.
### Further technical details

EF Core version: RC2 preview 1
Operating system: W10 Pro 64
Visual Studio version: VS 2015 Community Update 2

**Comment by natemcmaster** [comment]
This doesn't appear to be related to Entity Framework. This is the expected behavior of the C# compiler. This error occurs because [interpolated strings](https://msdn.microsoft.com/en-us/library/dn961160.aspx) (e.g. `$""`) are not constant. Interpolate strings behave similar to a method call to `string.Format()`.
