### ISSUE TITLE
Discussion for Announcement 195: RC2 => RTM maxLength needs to be added to existing migrations

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#5872]
Discussion for https://github.com/aspnet/Announcements/issues/195

**Comment by Bartmax** [comment]
so, what's the suggestion here? I run dotnet ef migrations add but I don't see anything about maxLength. should I re-create the whole database, again?

**Comment by gdoron** [comment]
@Bartmax I really hope not, we are not in a phase where we can simply drop and recreate the DB.

**Comment by rowanmiller** [comment]
You should just need to edit your existing migrations and add the `maxLength` specification to columns that need it. No need to drop database or delete migrations.

Any issues would only show up when applying those existing migrations to a new database. The problem is that the absence of the `maxLength` in the migration would result in `varchar(max)` in the database, which would then fail when the index is created (since you can't index a `varchar(max)` column).

**Comment by gdoron** [comment]
@rowanmiller Changing the `HasMaxLength` value (let's say add one) in the `OnModelCreating` and add a new migration after upgrading to 1.0.0 should do the trick too, right?

**Comment by rowanmiller** [comment]
@gdoron you shouldn't need to change anything in your model, this is just about updating the code in existing migrations so that they produce the same schema when they are applied with the RTM runtime. Any new migrations that you scaffold will correctly include the `maxLength` specification where needed.

You also may not need to do this anywhere. You can always try running the existing migrations against a new database to see if they successfully apply.

**Comment by Bartmax** [comment]
ok. To get rid of the error for creating the tables, I only need to update the migration for max length on columns that have indexes.

On the identity config, https://github.com/aspnet/Identity/blob/ed1d8cfbd001676c7b187881934d207577cf8a24/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityDbContext.cs

I can see that more properties have a `MaxLength` specified, but since they don't have indexes it won't throw an error. (but it will create the column with `varchar(max)` on new database).

So in reality, all columns that had a `MaxLength` before defined somewhere (like metadata or fluent) must be checked and updated the migration. am I right ?

Is there a *safe* way to **recreate migrations from scratch without affecting database** ?

Will this work?:
 1. Change connection string to new database.
 2. Delete migrations/snapshot
 3. Add migration.
 4. Update database.
 5. Revert configuration file to old database.

I prefer to deal with a new *correct* big migration than to update manually all migration I already have. Sorry, but I have too many tables/migrations already.

**Comment by Bartmax** [comment]
Ok I did that and worked. Way better for my scenario. Seeing the new migration file I had 40 maxlength entries. thanks.

**Comment by gdoron** [comment]
@Bartmax Not really.

1. Add a migration
2. Update database

You'll probably get an error because the migrations which were already applied to the old DB don't match the new one.

You probably need to change the migration history table.

(Didn't test it since I'm waiting for Azure to support 1.0.0 before migrating to 1.0.0)

**Comment by Bartmax** [comment]
@gdoron that's weird, because it does make sense what you said, but it actually worked (?)

**Comment by gdoron** [comment]
@Bartmax maybe because the migration was empty?
Did it had something?

**Comment by gdoron** [comment]
@Bartmax How do you update the DB?
Maybe you run it in a safe script?

	IF (EXISTS ...

**Comment by Bartmax** [comment]
migration wasn't empty.
I didn't updated the DB. Created a new one and then discarded it.

**Comment by rowanmiller** [comment]
Did the migration you generated have the same name as the previous one? We match based on names stored in the migration history table to work out whether a migration is already applied or not.

**Comment by gdoron** [comment]
@rowanmiller so that seems to be the easiest solution.

1. Delete the migrations folder
2. add a migration.
3.Delete the `__EFMigrationsHistory` table in the DB
4. Insert the new migration to `__EFMigrationsHistory`.

BTW, isn't the `ProductVersion` in `__EFMigrationsHistory` there so there'll be backward compatibility?

**Comment by rowanmiller** [comment]
@gdoron yep that works. You can ignore product version, it's fine for it to be the RC2 or RTM number.

It may be used in the future if we make changes between RTM releases. For example, if we made a change like this one between RTM releases we would compensate for it internally by looking at product versions. Though for this particular change it would be the version number in the migration code-behind rather than the one that applied the migration to the database.

**Comment by gdoron** [comment]
Might be a good idea adding to the announcement this solution as an alternative one.

**Comment by Bartmax** [comment]
I confirm that next migration failed miserably with weird (but  expected) errors.

Updating the migrations table by hand did the trick.

So the steps I get to make it working were:

 1. Delete the migrations folder.
 2. Add a new migration
 3. Changes the connection string to another DB (tempDB)
 4. Update database (this creates tempDB)
 5. Revert connection string to initial DB
 6. Update migration history table of initial DB from data of tempDB

One can skip the new db creation (steps 3 to 5) by deleting all entries on migrationHistory table and add an entry that matches the new migration. Being the MigrationId the same as the file created without the `cs` extension in the Migration folder, and for the version you can keep what you have or update to `1.0.0-rtm-21431`
in my case:
```
MigrationId: 20160628154458_InitialMigration
ProductVersion: 1.0.0-rtm-21431
```

Hope this helps others in a similar situation.

**Comment by rowanmiller** [comment]
Updated known issue (https://github.com/aspnet/Home/releases/tag/1.0.0#issue141) and announcement (https://github.com/aspnet/Announcements/issues/195) with the recommendation to rescaffold migrations rather than editing them (including detailed steps on how to do it).

**Comment by stephtr** [comment]
Just a small typo: in both documents it should be `dotnet ef migration**s** add InitialSchema`.

**Comment by rowanmiller** [comment]
@stephtr thanks, I've fixed it
