### ISSUE TITLE
[Question] How to specify foreign key column names using fluent API?

### ISSUE THREAD

**Issue by alaatm** [dotnet/efcore#5893]
In EF 6.x, we could specify foreign key column names in relations using fluent API as follows:
`HasRequired(p => p.x).WithMany().Map(m => m.MapKey("fk"));`
`HasMany(p => p.x).WithRequired().Map(m => m.MapKey("fk"));`
etc...

I am not sure how can this be done in EF Core 1.0. I prefer not to use ForeignKey attribute.

**Comment by rowanmiller** [comment]
Here are the docs that show how to do it https://docs.efproject.net/en/latest/modeling/relationships.html#foreign-key

**Comment by alaatm** [comment]
@rowanmiller Maybe the question was not clear. I know how to create relations and foreign keys but my question was about giving a custom name for the foreign key column.

For example, the sample code below:

    modelBuilder.Entity<Post>()
                .HasOne(p => p.Blog)
                .WithMany(b => b.Posts)
                .HasForeignKey(p => p.BlogForeignKey);

will generate a column named `BlogForeignKey`. My question was how to give it a different name. In EF 6.x we had the `Map` method: `.Map(m => m.MapKey("foreign_key_column_name"));`

**Comment by gdoron** [comment]
@alaatm 
Though I admit I never tried it as I'm good with the defaults, this looks like they way of doing it:

	.Property(x=> x.BlogForeignKey).HasColumnName("foreign_key_column_name")

**Comment by rowanmiller** [comment]
@alaatm sorry about that, here is the doc for what you are after - https://docs.efproject.net/en/latest/modeling/relational/fk-constraints.html

**Comment by rowanmiller** [comment]
@alaatm if the property is in your entity classes, then as @gdoron pointed out, you can just change the column it maps to.

If it's not in your class, then EF creates a "Shadow Property" for you. You can still change the column that this property is mapped to, you just need to use the string overload of `Property` to address it.

```
modelBuilder.Entity<Post>().Property<int>("BlogId").HasColumnName("foreign_key_column_name")
```

**Comment by rowanmiller** [comment]
@gdoron they are just useful if you have stuff you want in the database that is not in you CLR class. The most common case is not wanting foreign key properties in the class. I wouldn't go out of my way to use them unless you have a need.

BTW they shouldn't have any impact on queries, they only make a difference when it's time to read/write to the entity class, aside from that they are the same as any other property.

**Comment by gdoron** [comment]
@rowanmiller I still don't understand why one wouldn't want the foreign key properties in the CLR class. But I'll leave it.

They do have impact on queries.

Consider

	Product product = Context.Products.Include(x=> x.Store).First();
	Foo(product, product.Store.StoreId)
Vs

	Product product = Context.Products.First();
	Foo(product, product.StoreId)

**Comment by rowanmiller** [comment]
Oh right, the queries you have to write, yes. I thought you meant the SQL EF will generate for the same LINQ query 😄.

**Comment by alaatm** [comment]
@gdoron @rowanmiller Thanks for the info.

**Comment by a-h** [comment]
I tested this out on some code I'm working on, and while (surprisingly to me) @gdoron's suggestion didn't work:

```c#
            modelBuilder.Entity<Branch>()
                .Property(p => p.Region).HasColumnName("Region_Id");
```

and produced the error...

```
Unhandled Exception: System.InvalidOperationException: Cannot call Property for the property 'Region' on entity type 'Branch' because it is configured as a navigation property. Property can only be used to configure scalar properties.
```

@rowanmiller's suggestion of:

```
            modelBuilder.Entity<Branch>()
                .Property<int>("RegionId")
                .HasColumnName("Region_Id");
```

Worked well for me.

I don't think it's as neat as having the `MapKey` function though because:

   - It's unclear to someone reading the code because there isn't actually a RegionId property on the model.
   - It requires a bare string which won't survive a property rename refactor.

**Comment by fullsailor** [comment]
@a-h I've found this works.

Given a relationship like the original:
```
modelBuilder.Entity<Post>()
            .HasOne(p => p.Blog)
            .WithMany(b => b.Posts)
            .HasForeignKey(p => p.BlogForeignKey);
```
Then this will update the column name to the underscored name
```
modelBuilder.Entity<Post>()
            .Property(p => p.BlogForeignKey)
            .HasColumnName("Blog_Foreign_Key");
```

I think the reason your example raised the exception is because the property you want to change the column name of is `p.RegionId`, and not `p.Region`.

Hope it helps.

**Comment by IngemarNilsson** [comment]
@fullsailor thank you!
https://github.com/aspnet/EntityFrameworkCore/issues/5893#issuecomment-362106342

**Comment by CubeSpark** [comment]
As I am reading the Fluent API builders from scratch, I noticed there are some TSQL ambiguities that appear to be following this discussion.   First, note that as a TSQL developer, I can tell you there is a major difference between a referencing column and a referenced column. The constraint binds them, links them, on one singular mission to be rapidly JOINED.  **One Constraint to Bind them Together.**   We constrain foreign key column **relationships** with **Foreign Key Constraints**. 

Columns by themselves DO NOT constrain, but a constraint  will, namely, the **Foreign Key Constraint**.  That thing CONSTRAINS, so, unlike me, who is never constrained, two columns MIGHT be in a constraining relationship, and their underlying relationship is CONSTRAINED by a **Foreign Key Constraint**.   You can be confused if you look at any GUI (graphical user interface) and not the formal or SQL.   Any GUI can be confusing because GUI does not speak about Foreign Keys in the correct way, due to the fact that GUI does not read the code.  GUI represents things, and the GUI map is NOT the territory.  

Please, let me **tell** you what the semantics of TSQL are in this context. When you create a Foreign Key Constraint in TSQL, for example, you don't create any columns, but rather you can assume the columns already exist because you create them first.  What you want is to BIND the columns together so the rows that MATCH do so and are CONSTRAINED to do so. 

What you want is to think of the LINKAGE between columns, the equation, the link that equates and constrains one column to another at the level of the row data.  The digital bit-level data needs to have at least the same TSQL Datatype, say INTEGER, so the hardware can line-them-up.   You create a linkage, a relationship between one column and another, whether the columns are in the same table or not. The relationship is CONSTRAINED by a NAMED constraint that happens to have functional attributes known as "constraint properties" on the constraining relationship.  There can be multiple INCOMING links.  So, NEVER think of a Foreign Key as a Column, but rather think of it as a CONSTRAINT, a **Foreign Key Constraint**.   Again, **DO NOT THINK OF A FOREIGN KEY AS A COLUMN - IT AIN'T** !

The first poster expressed a need for the Fluent API to have complete control over the NAME of the Foreign Key Constraint, and since we all need a good F.K.C. name (if ya feel me), you can take a look at my way of declaring columns and the constraints in totally valid TSQL.   You will see there that I like to organize all of it on the same object, instead of having separate code for the constraints.  

The PRIMARY Key constraint declarations, and the FOREIGN KEY constraint declarations are listed right there by their respectively constrained columns.   Also, I NEVER use Hungarian commas, because commas are little-endian, not big-endian.  Keep your commas on the tail of the lines, all you young fellas out there, and your F.K.C. constraints will be UNFETTERED and free!

```
CREATE TABLE [Security].[TenantClaimTypes](
	TenantClaimType_PSK INTEGER IDENTITY (-2147483648,1) NOT NULL ,
	CONSTRAINT TenantClaimType_PKC 
	PRIMARY KEY CLUSTERED (TenantClaimType_PSK ASC ) 
	WITH (IGNORE_DUP_KEY = OFF) ON [Security] ,
	-------------------
	Tenant_FSK INTEGER NOT NULL, 
	-------------------
	CONSTRAINT TenantClaimTypes_1_M_Tenants 
		FOREIGN KEY(Tenant_FSK) 
		REFERENCES [Security].Tenants (Tenant_PSK),
	-------------------
	TenantClaimType VARCHAR(35) NOT NULL,
	TenantClaimValue VARCHAR(35) NULL,

	) ON [Security];
GO
PRINT 'Table Security.TenantClaimTypes was recreated'
-- That's all she wrote
GO
```
And, here is code to probe ALL the Foreign Key Constraints.  

```
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Use this to check foreign key constraints.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

USE [YourOwnDatabase];
GO

SELECT 
'Referencing Table' = RFNGT.name,
'Referencing Object ID' = RFNGT.object_id,
'Referenced Table Name' = RFCDT.name,
'Referenced Table ID' = RFCDC.object_id,
'Referenced Column Name' = RFCDC.name,
'Foreign Key Name' = FKC.name,
'Key ID Value' = FKC.object_id,
'Key Type' = FKC.type_desc

FROM

sys.tables AS RFNGT
JOIN
sys.foreign_keys AS FKC
ON
FKC.parent_object_id = RFNGT.object_id
JOIN
sys.tables AS RFCDT
ON
RFCDT.object_id = FKC.referenced_object_id
JOIN
sys.columns AS RFNGC
ON
RFNGC.object_id = RFNGT.object_id
JOIN
sys.columns AS RFCDC
ON
RFCDT.object_id = RFCDC.object_id
JOIN
sys.foreign_key_columns AS FKCC
ON
FKCC.constraint_object_id = FKC.object_id
AND
RFNGT.object_id = FKCC.parent_object_id
AND
RFNGC.column_id = FKCC.parent_column_id
AND
RFCDT.object_id = FKCC.referenced_object_id
AND
RFCDC.column_id = FKCC.referenced_column_id
JOIN
sys.schemas AS RFNGS
ON
RFNGS.schema_id = RFNGT.schema_id
JOIN
sys.schemas AS RFCDS
ON
RFCDS.schema_id = RFCDT.schema_id
ORDER BY RFCDT.name

```
