### ISSUE TITLE
DbSet is empty after adding entity.

### ISSUE THREAD

**Issue by oshulaev** [dotnet/efcore#6015]
### Steps to reproduce

```
    static void Main(string[] args)
    {
        using (var db = new BloggingContext())
        {
            db.Blogs.Add(new Blog { Url = "http://sample.com/blog_one" });
            db.Blogs.Add(new Blog { Url = "http://sample.com/blog_two" });

            var firstBlog = db.Blogs.First(); //db.Blogs is empty - System.InvalidOperationException: Sequence contains no elements
            firstBlog.Url = "";

            var lastBlog = db.Blogs.Last();
            db.Blogs.Remove(lastBlog);

            db.SaveChanges();
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase();
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

    }
```
### The issue

After i added entities to db.Blogs, it is still empty.
Entities become visible in DbSet after call SaveChanges. Why?
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 7
Visual Studio version: VS 2015

**Comment by ajcvickers** [comment]
@oshulaev I realize this can seem confusing at first, but when you do db.Blogs.First() the First call is actually a query to the database. Because the added objects have not yet been saved to the database they are not returned in the results.

You can get all the blogs that are being tracked by the context using something like this:
```C#
var trackedBlogs = context.ChangeTracker.Entries<Blog>().Select(e => e.Entity).ToList();
```
In your example that call should return the two blogs that you added.
