### ISSUE TITLE
MaxLength missing - better error message

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#6057]
### Steps to reproduce

Have a string property on your entity, but don;t configure a `maxlength`.
### The issue

To be helpful, the exception message should inform you of the entity name, and the property name, but it doesn't:

```
Data type 'varchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'varchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type.
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerTypeMapper.ValidateTypeName(String storeType)
   at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.EnsureDataTypes(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)

### Further technical details

EF Core version: RTM
Operating system: Windows 8
Visual Studio version: 2015
```

**Comment by ajcvickers** [comment]
We decided not to do this for a combination of two reasons:
* While it might be useful in general to provide entity type/property name information for bad type mappings, it doesn't in this case provide much additional value since it should be easy to search code for occurrences of "varchar" or similar. 
* It would require breaking the IRelationalTypeMapper interface to do this in the obvious way. We don't want to break this interface for something that is not compelling. We could add some exception wrapping in the RelationalModelValidator, but when considered with the first point it doesn't seem worth it right now.
