### ISSUE TITLE
Why Don't Run This Releases 1.0 Source Code

### ISSUE THREAD

**Issue by strivelearns** [dotnet/efcore#6063]
Compile Has 720 Error

**Comment by smitpatel** [comment]
Do you have visual studio update 3 + .NET core 1.0 installed? Are your nuget feeds configured to point to nuget.org ?

**Comment by stalker2016** [comment]
Thank you  .I installed Visual Studuio 2015 by Update 3 And DotNet Core 1.0 ,I Open EntityFramework.sln Before, Compile Has 720 Error.Now I Open EntityFramework-xproj.sln Has Zero Error.
What's the difference between EntityFramework.sln and EntityFramework-xproj.sln ???

**Comment by smitpatel** [comment]
Before you open solution in VS, you need to run `./build.cmd initialize` in command line, which will restore the packages for all projects. That could be reason for compilation error. xproj solution would work since VS restores packages for them by reading `project.json` file.
EntityFramework.sln uses csproj based projects. EntityFramework-xproj.sln uses xproj-based projects. They use the same set of files so source code is same. Project configurations are also kept in sync in both the system. The only difference would be the functionality they provide in VS (like restoring packages automatically)

**Comment by stalker2016** [comment]
after day this xproj little by little replace csproj?

**Comment by ajcvickers** [comment]
@stalker2016 We will evaluate changing the build as things progress with project systems. As of right now, I think most or all of the development team use csproj.

Closing this issue as I think @smitpatel answered your questions.
