### ISSUE TITLE
Migrations Scaffolding Directory Inconsistency

### ISSUE THREAD

**Issue by rondefreitas** [dotnet/efcore#6108]
### Steps to reproduce

Create a new Asp.Net Core project from the templates using EntityFramework.
Create a second, empty project, a basic model, and data context, then scaffold a migration.
### The issue

The first project, the template, starts out with migration scaffolding in Data/Migrations.
The second project uses the established default, ./Migrations.

This causes confusion for users, as seen in aspnet/Home#1675
EF default should either become Data/Migrations to match the templates, or the templates should be changed back to /Migrations
### Further technical details

EF Core version: 1.0.0
Operating system: N/A
Visual Studio version: 2015

**Comment by rowanmiller** [comment]
EF has always used a `Migrations` directory (since EF4.3 when migrations was introduced), so it's not something we were planning to change. The deviation from this in the ASP.NET templates was an intentional choice (cc @rustd). You could file an issue on the templates https://github.com/aspnet/Templates/, but I think that will be resolved as "by design".
