### ISSUE TITLE
use of the Update-Database command

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#6265]
I would like to ask how works the update-Database command with asp.net core.
I have an asp.net rtm project project: if I start visual studio and open the project, if I try to run the Update-Database command I obtain this error message

`Update-Database : The term 'Update-Database' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

If I open an asp.net 4 project, with ef 6.1.3 installed, reopen then asp.net core project and I run the Update-Database command I obtain this message

`Both Entity Framework Core and Entity Framework 6.x commands are installed. The Entity Framework Core version is executing. You can fully qualify the command to select which one to execute, 'EntityFramework\Update-Database' for EF6.x and 'EntityFrameworkCore\Update-Database' for EF Core.`

Can I use these commands with asp.net core?

**Comment by divega** [comment]
@natemcmaster I think you have some context on how this might fail, workarounds, etc. Can you respond?

**Comment by natemcmaster** [comment]
@lucamorelli Which version of EF Core tools are you trying to use? We added PMC support to EF Core commands in preview1. The latest is 1.0.0-preview2-final. 

You're issue appears to contain a few questions. Let's tease these apart.

1. "`The term 'Update-Database' is not recognized as the name of a cmdlet`"

  NuGet should be automagically installing EF Core commands into the Package Manager Console when you open a ASP.NET Core project or when you install Microsoft.EntityFrameworkCore.Tools. This may not happen for a few reasons. 

  (1) You have "Microsoft.EntityFrameworkCore.Tools" in "tools" not "dependencies" in your project.json file. (A known, "wont-fix" issue on NuGet https://github.com/NuGet/Home/issues/3023). 
  (2) NuGet restore failed. (Did restore split out any errors or warnings? etc).
  (3) You have PowerShell 2.0. We require at least v3. The latest is v5.

  Do any of these apply to you?

2. Warning message about EF 6.x commands. This is not an error, just a warning. So if the command is working, keep calm and code on.

  Explanation of the warning:  PMC cmdlets are solution-global which means it is common to have a solution that has both EF 6.x and EF Core commands installed. To distinguish between the version, the warning message is suggesting using [module-qualified cmdlet names](https://www.sapien.com/blog/2015/10/23/using-module-qualified-cmdlet-names/) when invoking commands that exist in both EF 6 and EF Core.

**Comment by Xipooo** [comment]
FYI, I have encountered the same issue twice with two separate resolutions.  The first one was simple.  I just closed VS and re-opened it.  Seems after you install the EF tools, you should restart VS as a matter of best practice.  The second time I resolved it by changing on my project.json file tools object:

`"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"`

To:

`"Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type":  "build"
    }`

**Comment by natemcmaster** [comment]
> FYI, I have encountered the same issue twice with two separate resolutions. The first one was simple. I just closed VS and re-opened it. 

@Xipooo this is likely a bug in NuGet and/or the ASP.NET tooling. We should confirm exact repro steps and hand this off to the right team. Can you confirm exactly how this reproduces? e.g. is this only when using NuGet GUI, Package Manager Console, a new ASP.NET template, etc?

`"type": "build"` doesn't have any effect on the way the package is installed. However, editing/saving project.json automatically triggers a NuGet restore in ASP.NET Core/.NET Core projects in VS. It's possible that adding "type": "build" appears to fix the issue when really the fix was to just run a package restore a second time.

**Comment by Xipooo** [comment]
@natemcmaster In both cases I followed the steps lined out [here](https://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html#install-entity-framework) in the online docs.  I ran the import-package for both EF Core and tooling.  One time on a project I've been working on since RC1 (that one required the project.json modification) while the other was a new ASP.NET Core RTM project with only 2 model classes and a single DbContext.

I believe you are right about adding the "type":"build".  I saw this as a suggested solution elsewhere in the EF issues tracker though I don't have a link to it off hand.

**Comment by natemcmaster** [comment]
Ping @lucamorelli on https://github.com/aspnet/EntityFramework/issues/6265#issuecomment-238347869. Can you share more details about your project/solution setup? I don't have enough details to reproduce or isolate the issues you've asked about.

**Comment by lucamorelli** [comment]
looks like calling dotnet restore from command line solved the problem. that's strange because I created the project with the latest version of tools in this computer, so the initial restore should be this the good one. Could be in some situations there is a problem detecting if this kind of installation is broken

**Comment by natemcmaster** [comment]
Thanks for the details. I've seen a few other similar issues with the ASP.NET Core web tooling. I've opened aspnet/Tooling#737 to see if we can have the VS team look at this.
