### ISSUE TITLE
Feature request: Option to validate query against provider

### ISSUE THREAD

**Issue by kierenj** [dotnet/efcore#6296]
For unit testing, we have the in-memory provider, which is a great step.

However there will be some queries not supported by the SQL Server provider, or other providers, which are handled easily by the in-memory provider.

I'm hoping that whether or not a provider supports a given query is largely deterministic based on the IQueryable operation chain produced and passed to them.  Or perhaps some are deterministic, others can be "data-dependent" (which could also be flagged up).  What I'd love is a way to determine whether a query is supported without having to connect to a data source and execute the query.

Putting providers into a "what-if" mode, with no live DB accesses but indicating if the expression cannot be translated is one option.  The providers could proxy everything to an in-memory provider, shadowing each DB access with an attempt to build the appropriate query and flagging up (via exception) any issues.

Other options could include a separate per-provider query validator class, which accepts an Expression which could be analysed for instance:

``` c#
sqlQueryValidator.IsValid<MyEntity>(q => q.Where(e => e.IsOk).Select(e => new { e.Date.Kind }));
```

(I prefer the first thought rather than this one, but this is more explicit I suppose, "test my query!")

I realise this could be a big impact issue - just seeing if this is an option for the big issue of testing queries!

**Comment by divega** [comment]
@kierenj Thanks for the suggestion. We discussed in triage and our current take on the enhancement you describe is that its potential benefits don't seem compelling enough to justify its cost. It also seems that executing tests periodically against an actual database should be easy enough, generally more useful (as you are testing more of the real infrastructure that the application will use), and a reasonable "click stop" for testing after using the in-memory provider.

We may change our position in the future on this if we get enough feedback and if someone planned to make a contribution, but since we don't currently think we would build it, I will go ahead and close the issue.
