### ISSUE TITLE
Improve error message when calling context.Database.OpenConnection but the database not exist 

### ISSUE THREAD

**Issue by 303248153** [dotnet/efcore#6308]
### Steps to reproduce

When I call "context.Database.OpenConnection", I get an error from sqlserver, the message is "A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.)".
Reproduce code

```
using (var context = new MyDbContext ())
{
    context.Database.OpenConnection();
}

class MyDbContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Data Source=.\\sqlexpress;Initial Catalog=xxx;User Id=sa;Password=123456");
    }
}
```

The reason is the database ain't created.
After I execute a empty sql command before calling `OpenConnection`, the error message become
 "Cannot open database "xxx" requested by the login. The login failed.".
Maybe it's better to improve the error message.
### Further technical details

EF Core version: 1.0.0
Operating system: windows 8.1
Visual Studio version: 2015

**Comment by divega** [comment]
@303248153 these are both exceptions coming from the ADO.NET provider for SQL Server, i.e. SqlClient. 

I have personally seen these occur more frequently when working against SQL Server LocalDB, especially when LocalDB is not running and it needs to start to handle the first database request.

We don't have any plans to wrap these exceptions into a different exception at the EF layer, mainly because we don't have a better exception message that could contribute to help users understand what went wrong and that they can do to address it, but it is possible that these will be handled automatically by retrying logic as part of the connection resiliency feature (#237) that we will start working on soon. 

BTW, if you are able to consistently repro this issue it may help to report the bug to the SqlClient folks at https://github.com/dotnet/corefx/. It is very likely easy to produce a repro that doesn't have EF in the picture.
