### ISSUE TITLE
generate classes in pascal case

### ISSUE THREAD

**Issue by mauriliommachado** [dotnet/efcore#6315]
I would like to generate the classes in pascal casing, how do i do it?

**Comment by divega** [comment]
@mauriliommachado this issue is lacking enough information for us to be able to answer. 

In case you are talking about how to get EF Core to generate classes with Pascal case when reverse engineering objects from the schema of a database: it already has the ability to create names with Pascal case but it needs to somehow find how words are delimited in the names of the objects in the database, e.g. those objects can be themselves in Pascal case, have underscores (a.k.a. snake case) or spaces between words.
