### ISSUE TITLE
Implement custom SqlServerConnection

### ISSUE THREAD

**Issue by jhermsen** [dotnet/efcore#6320]
I tried adding custom ISqlServerConnection service in the startup class like so:
`// Add framework services.
            services.AddScoped<ISqlServerConnection, SqlServerConnectionRLS>()
                .AddEntityFramework()
                .AddDbContext<AuthDbContext>(options =>
                    options
                    .UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));`

The problem is that entity framework isn't using my custom connection.
I also did some copying and overriding other methods.
I did get it working, but had to implement a custom UseSqlServer extension so I can override the SqlServerOptionsExtension and use a custom method to ApplyServices and add all required services without the default SqlServerConnection class.

EF Core version: 1.0.0

**Comment by ajcvickers** [comment]
@jhermsen This is probably because you're not letting EF know to use the service provider to which you have added the custom service. We're making this easier in 1,1 (see #6306). Until then, I'm going to assume you are using ASP.NET and that its OK for your app to share a service provider with EF. You then need to make your AddDbContext look something like this:
```C#
services
    .AddEntityFrameworkSqlServer()
    .AddDbContext<AuthDbContext>(
        (serviceProvider, options) => options
            .UseInternalServiceProvider(serviceProvider)
            .UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```
If this doesn't solve the issue, then please post more complete code to help us reproduce the issue.

**Comment by jhermsen** [comment]
@ajcvickers Thanks for the answer managed to achieve it that way.
One more thing if I don't use the shared ServiceProvider.
Can I then still access the app services from a custom service within the EF service provider?

**Comment by ajcvickers** [comment]
@jhermsen If you use a shared service provider, then all services for EF and your application are registered in the same container. If you use separate service providers, then each provider will not resolve services from the other provider. This usually means that a custom service in the EF provider will not have access to application services.
