### ISSUE TITLE
Preventing database/table/model creation

### ISSUE THREAD

**Issue by SergeySagan** [dotnet/efcore#6346]
I have a solution with a Data project that creates my database tables (model). I have an API and Web project which both consume that DbContext . The problem is that I have the tables dropped and recreated on each App Pool Recycle. Well each of those apps is doing the drop and recreated and they are stepping on top of each other, causing some of the tables to not be there. I can kind of get around it by using a conditional exception, a simplified example:

`
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    if (!isAPIApp)
        throw new Exception("This app shouldn't be creating the database.");
`

However this seems extremely crude... is there some way to tell modelBuilder to not create the tables in this app only? By the way, I also asked this question here: http://stackoverflow.com/questions/38986437/prevent-ef-model-creation-in-secondary-apps but haven't gotten any response.

**Comment by divega** [comment]
@Serjster We discussed this in triage and assuming we understand what you are trying to do, we cannot think of anything that EF Core can do help. If your application is in development and changing at a rapid pace perhaps the easiest approach would be for each developer to debug it on a separate local database. If for some reason you cannot do that then may be you should avoid programmatically dropping and recreating the database as part of the application code and have developers only do it manually as needed instead. Last, if no other solution applies to your scenario, you could create a custom mechanism based on a shared lock. Since presumably all instances of the application share the same database server you could use a row on a table on some database that instances of the application need to acquire a lock on before they can start dropping and recreating the tables.  

In any case, `ModelBuilder` does not create tables or databases. The code in `OnModelCreating()` only builds a model that EF Core uses to reason about the objects and how the map to tables, but this code has to be run at least once for each instance of the application.
