### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by felipepessoto** [dotnet/efcore#6351]
VS can't discover tests. The Tests Output says:

------ Load Playlist started ------
========== Load Playlist finished (0:00:00.0156261) ==========
------ Discover test started ------
Dependency '"Microsoft.EntityFrameworkCore.Design.FunctionalTests": {
  "target": "project"
}' has invalid version specification.
========== Discover test finished: 0 found (0:00:01.3950501) ==========

**Comment by ajcvickers** [comment]
@fujiy A quick survey of the team shows that we tend to use TestDriven.NET and/or the ReSharper test runner. Also using build to run all the tests on the command line should work.

We've always had issues getting the VS test runner to work, but we don't spend much time on it because nobody really likes to use it. If there are simple changes that could be made to get it working and you feel like submitting those in a PR, then we would certainly consider taking that PR, but as of now we don't plan to do any work to get the VS runner to work.

**Comment by fujiy** [comment]
Sad to hear :(
I will try TestDriven.Net

**Comment by fujiy** [comment]
Do you know if we have licenses?

**Comment by bricelam** [comment]
I looked into enabling the Visual Studio runner, but because of our custom project.json-to-csproj solution it is not easy to do.

The Personal Version of TestDriven.NET is for open source developers. I'm not a lawyer, but for the purposes of submitting a PR to the open source EF Core project, it seems legit to me...

**Comment by fujiy** [comment]
I'll try that. Thanks
