### ISSUE TITLE
Recursive Entities behave different when calling ToList or FirstOrDefault.

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/efcore#6545]
### Steps to reproduce

Open project at https://github.com/shawnwildermuth/RecusiveEFQueryBug and go to /api/employees and /api/employees/1 and see the different behaviors. 
### The issue

I have a self-referencing entity:

```
  public class Employee
  {
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmployeeNumber { get; set; }
    public bool Active { get; set; }
    public DateTime HireDate { get; set; }
    public DateTime ExitDate { get; set; }

    public ICollection<Address> Addresses { get; set; }

    public Department Department { get; set; }  

    public Employee Manager { get; set; }
    public ICollection<Employee> Reports { get; set; }

  }
```

When I query it with .ToList() and include the self-references field (e.g. Reports) it works find down the hierarchy (hurrah!), but if I do the identical query with _.FirstOrDefault()_ it stops at one level of recursion. For example:

This gets the entire hierarchy:

```
      var emp = _ctx.Employees
        .Include(e => e.Reports)
        .ToList();

```

This get's only one level of hierarchy:

```
      var emp = _ctx.Employees
        .Include(e => e.Reports)
        .Where(e => e.Id == id)
        .FirstOrDefault();
```

I can work around it for now by:

```
      var emp = _ctx.Employees
        .Include(e => e.Reports)
        .ToList()
        .Where(e => e.Id == id)
        .FirstOrDefault();
```

But obviously that is going to load a _lot_ of employees and filter down to the specific one so it's going to be very inefficient.  Is this expected behavior?
### Further technical details

EF Core version: (found in project.json or packages.config) 1.0.0
Operating system: Windows 10 Ent
Visual Studio version: (e.g. VS 2013 or n/a) VS 2015

Other details about my project setup:

**Comment by smitpatel** [comment]
@shawnwildermuth - This behavior is due to tracking nature of query. In the first query, you are querying for all the employees. Since it is self-referencing relationship and results are being tracked, all the navigations will be fixed up. Hence you see `Reports` populated down the hierarchy. That query should give same results even without `Include`.
In the second query, since you are querying for only first record, EF will fetch only 1 employee & associated `Reports` due to include. But since data down the hierarchy is not loaded from database to memory, the navigations will be null. You need to use `ThenInclude` for subsequent levels.
