### ISSUE TITLE
TPH does not enforce unique discriminator types

### ISSUE THREAD

**Issue by colltoaction** [dotnet/efcore#6617]
Product Info: EF Core 1.0.1, SQL Server.

I have an entity that is a `ProductLicense`. The license might have different types, such as `StandardProductLicense`, `ExpandedProductLicense`, and `ExclusiveProductLicense`. Also, an `ExclusiveProductLicense` might be of different types (exclusive for 1 month, for 2 months, etc). This might not be the best architecture, but it's our current design and I need to map it.

I assumed that mapping different `GUID`s to the same type would work, but I just noticed the behavior is that only the last value for the type is being mapped.

Example:

``` cs
entity.HasDiscriminator(e => e.LicenseId)
    .HasValue<StandardProductLicense>(Guid.Parse("AAAAAAAAAAAAAAAAAAAAAAAA"))
    .HasValue<ExpandedProductLicense>(Guid.Parse("BBBBBBBBBBBBBBBBBBBBBBBBBBB"))
    .HasValue<ExclusiveProductLicense>(Guid.Parse("CCCCCCCCCCCCCCCCCCCCCCCCCCCC")) // 6m
    .HasValue<ExclusiveProductLicense>(Guid.Parse("DDDDDDDDDDDDDDDDDDDDDDDD")) // 3m
    .HasValue<ExclusiveProductLicense>(Guid.Parse("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE")); // 1y
```

Ideally, I'd want to be able to map multiple values to one type. If it's difficult or can't be done, I'd expect an error as in [this PR](https://github.com/aspnet/EntityFramework/pull/4958).

Thanks!

**Comment by tinchou** [comment]
I just tested the following and it allows me to filter using `ctx.ProductLicenses.OfType<ExpandedProductLicense>()`, so probably we only want the error if mapping multiple times the same type (and maybe a suggestion to use this solution):

```cs
public partial class ExpandedProductLicense : ProductLicense
{
}

public partial class Exclusive3ProductLicense : ExclusiveProductLicense
{
}

public partial class Exclusive6ProductLicense : ExclusiveProductLicense
{
}

public partial class Exclusive12ProductLicense : ExclusiveProductLicense
{
}

//....

entity.HasDiscriminator(e => e.LicenseId)
    .HasValue<StandardProductLicense>(Guid.Parse("AAAAAAAAAAAAAAAAAAAAAAAA"))
    .HasValue<ExpandedProductLicense>(Guid.Parse("BBBBBBBBBBBBBBBBBBBBBBBBBBB"))
    .HasValue<Exclusive6ProductLicense>(Guid.Parse("CCCCCCCCCCCCCCCCCCCCCCCCCCCC")) // 6m
    .HasValue<Exclusive3ProductLicense>(Guid.Parse("DDDDDDDDDDDDDDDDDDDDDDDD")) // 3m
    .HasValue<Exclusive12ProductLicense>(Guid.Parse("EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE")); // 1y
```

**Comment by smitpatel** [comment]
> Ideally, I'd want to be able to map multiple values to one type. If it's difficult or can't be done, I'd expect an error as in this PR.

The code you posted is modifying discriminator value for `ExclusiveProductLicense`  multiple times. Most of fluent APIs allow to re-define things. That is useful when using derived context in which you want to override base configuration of the model. Therefore it will not throw any error. Instead it will change to new value.

> I'd want to be able to map multiple values to one type.

TPH is just a strategy to make 1 table for whole hierarchy. In the absence of TPH, you would get 1 table for each type. In that world, how would you want your tables to be created?
Would you want single table for all `ExclusiveProductLicense` type?
If yes, then you would need a column in that table (probably duration) to actually tell difference between each of them and use it in your queries appropriately. Since there is only 1 CLR type and you are using it to store different kinds of licenses in it.
If no, then there will be 1 table for each type. Hence 3 different types for each duration. (similar to what you have proposed as solution)

**Comment by tinchou** [comment]
As I mentioned, I'm able to make this work with a base class (`ExclusiveProductLicense`) that doesn't have a discriminator. This is perfect and I don't really need more. As you said there are more things to consider and we don't need to change this.

On the other hand, I was surprised with this behavior because it led me to a very subtle bug. You say *most of fluent APIs allow to re-define things*, and that seems good to me, but maybe we can think of another way to prevent people falling in this issue? Maybe we could be more explicit (e.g. pass a flag) when we want to override an existing value?

**Comment by rowanmiller** [comment]
> On the other hand, I was surprised with this behavior because it led me to a very subtle bug. You say most of fluent APIs allow to re-define things, and that seems good to me, but maybe we can think of another way to prevent people falling in this issue? Maybe we could be more explicit (e.g. pass a flag) when we want to override an existing value?

We discussed this, but decided that it would complicate the API a lot and would be a significant breaking change to start throwing in places that would not have thrown previously.

**Comment by tinchou** [comment]
Sounds reasonable. Hopefully this discussion will aid anyone looking for
explanations.

Also, did you consider expanding the docs section on this topic?

Thanks!

**Comment by rowanmiller** [comment]
@tinchou yes, I'm about to do a pass on the docs to start adding in some of the more advanced topics.
