### ISSUE TITLE
Database.EnsureDeleted() much slower if database does not exist

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#6673]
On my machine `EnsureDeleted()` takes ~50ms to run if the database is present, and ~10100ms if the database does not exist. Seems like we should be able to optimize the no-op path a little.

``` c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Diagnostics;

namespace EFCore101
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                db.Database.EnsureCreated();

                var sw = new Stopwatch();

                sw.Start();
                db.Database.EnsureDeleted();
                sw.Stop();
                Console.WriteLine($"Database exists: {sw.ElapsedMilliseconds}ms");

                sw.Restart();
                db.Database.EnsureDeleted();
                sw.Stop();
                Console.WriteLine($"Database doesn't exist: {sw.ElapsedMilliseconds}ms");
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Demo;Trusted_Connection=True;");
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    }
}
```

**Comment by ajcvickers** [comment]
@rowanmiller Do you see the same results if the second EnsureDeleted is not immediately after the first? It could be hitting exists check issues and re-trying.

**Comment by rowanmiller** [comment]
Yep, I was seeing this in demos where the database hadn't existed for hours. I tried inverting the calls in the repro code too, and get the same results. It seems to be a pretty consistent 10sec overhead (at least on my machine)

**Comment by ajcvickers** [comment]
Investigated this and found it is due to a new feature introduced to SqlClient that does retries on connection failures. By default, the ConnectRetryCount is set 1 and the ConnectRetryInterval is set to 10 seconds. This is transparent to us and cannot be changed publicly without creating a new connection string, which has its own issues such as losing credentials. Therefore, discussed with @rowanmiller, @divega, and @AndriySvyryd and decided that we will not make any changes to EF code.

The workaround for this issue is to add "ConnectRetryCount=0" to the SQL Server connection string. The original, faster behavior for exists should then be restored, with the understanding that there is also a greater chance that the database will not be deleted because the connection to it failed to open.
