### ISSUE TITLE
Add sugar for DiscardStoreGeneratedValues

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#6719]
When calling `.SaveChanges(acceptAllChangesOnSuccess: false)` we provide `.ChangeTracker.AcceptAllChanges()` to handle success in your code, but there's no `.ChangeTracker.DiscardStoreGeneratedValues()` to handle failure

**Comment by ajcvickers** [comment]
Talked with @AndriySvyryd and decided that after the fix for #6720 this is no longer needed. This is because even if DiscardStoreGeneratedValues is not called, the next call to SaveChanges will discard the values. Even if it didn't, the temporary flag will still be set, so another value will be generated anyway.
