### ISSUE TITLE
Is it Possible to Call a Db Function in EF Core?

### ISSUE THREAD

**Issue by mgolois** [dotnet/efcore#6795]
Is it possible to call a Sql Db function in EF Core?

**Comment by rowanmiller** [comment]
You can use a raw SQL command as the starting point for a query - https://docs.efproject.net/en/latest/querying/raw-sql.html.

Proper support for something like `DbFunctions` from EF6 is tracked by https://github.com/aspnet/EntityFramework/issues/2850 but currently not implemented.

**Comment by mgolois** [comment]
Thanks @rowanmiller

**Comment by weitzhandler** [comment]
@rowanmiller 
Can I call a db function such as [`sys.sp_cdc_enable_db`](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sys-sp-cdc-enable-db-transact-sql?view=sql-server-2017) from EF Core? Otherwise what should be the right method to call non-data db functions when working with EF Core?
