### ISSUE TITLE
EF7 removal of EDMX questions

### ISSUE THREAD

**Issue by chekm8** [dotnet/efcore#697]
I have been following some discussions about the removal of EDMX files from EF7 and had a few questions and I thought it best to present what I use in todays EDMX and ask how this may work with the new EF7.  I'm going to prefix this that I haven't had the time to play with EF7 yet so if this has been answered elsewhere I'm sorry.

First, I would like to address the "if you want to use EDMX don't upgrade to EF7" comments I have seen.  This isn't really an option.  First, I like to stay with the latest technologies and keep my skill set in demand. Second, we all know EF6 will become unsupported by Microsoft and vendors such as Oracle will push newer versions of EF making it impossible not to upgrade. 

Ok so here is my scenario:
Let say I have a creative DBA that has this DB structure in place.  The DBA has his db standards so Plurialization and case is intentional, Table names are uppercased (yes it is this way on the actual database).  He's grown over time and learned that pluralization on tables is bad (tisk, tisk) and his field naming standards have changed over time as well but, he hasn't gone back and fixed everything.  

PRODUCTS
Product_ID
NameTxt
DescTxt
Price

ORDER
Id
Customer_Id
SalesRep_Id
OrderDate

PRODUCT_ORDER
Product_Id
OrderId
Quantity

ACCOUNTS
Id
First_Name
Last_Name

In today’s world, without third party add-ons,  we can:
- Generate an EDMX from my existing database, relationships are generated.  This wacky XML is the main vehicle to generate the POCOs.
- Rename fields in a central place.  In the above tables I can make Product_ID = Id, NameTxt can be renamed to Name, DescTxt to Description.  
- Correct the casing and pluralization on my Table names (PRODUCTS becomes Product, PRODUCT_ORDER becomes ProductOrder, ORDER => Order) so I get my clean class names following my Microsoft standards
- Fix relationship names so that "Product" can have a "Orders" Property, etc. 
- Correct relationship names for multiple mappings to the same table.  In the above example both the Customer_id and SalesRep_Id map to a record in the ACCOUNTS table.  When EF generates the EDMX you get something like Account and Account1 for the relationship.  I can rename these to Customer and SalesRep.
- Use the T4 template to generate my POCO objects from the EDMX without having to be connected to my database.  
- Move the generation of my POCO's out into a separate assembly by moving the T4 template to that assembly and pointing it back to the EDMX.  
- When my database changes I can simply refresh my EDMX from the database and rerun my T4 template to generate my POCOs.
- Have a nice visual diagram allowing me as the developer a picture of my database without having to look at the classes or dig around in the database relationships directly

What in the above will be missing?  As I understand it the visual diagram will be gone.  A loss for sure but I can live without it if there are other ways to perform the above operations.

I also heard that "complex mappings" may not work until later release of EF7.  Can you give an example of what is "complex"?  Is renaming a db table to a better class name and creating an "Orders" relationship or multiple mapping to the same table such as Customer/SalesRep in the above examples considered complex?

**Comment by rowanmiller** [comment]
Hey,

Sorry to take *so* long to reply to this, it feel off my radar. Here are some thoughts...

> First, I would like to address the "if you want to use EDMX don't upgrade to EF7" comments I have seen. This isn't really an option. First, I like to stay with the latest technologies and keep my skill set in demand. Second, we all know EF6 will become unsupported by Microsoft and vendors such as Oracle will push newer versions of EF making it impossible not to upgrade. 

We as a team are going to keep working on EF6 for some time to come because we know that upgrading to EF7 is a bigger step that past major versions. Of course, you aren't going to get big new shiny features on EF6 (for example we won't be adding unique constraints and batching to EF6... you'll need to use EF7 to get those). The same will be true for providers, the existing providers will be there and still work, but if you want new shiny features most provider writers will probably just add those to the latest version.

Our encouragement to folks is to consider that upgrading an existing app to EF7 is likely not the right thing to do in a number of cases. For new development, we'll definitely encourage folks to use EF7 (**once it is ready**).

> What in the above will be missing? As I understand it the visual diagram will be gone. A loss for sure but I can live without it if there are other ways to perform the above operations.

Reverse engineering a code based model is template based, so you can modify the templates to take care of how things are reverse engineered. For things such as fixing case, this is actually better because you don't have to hand edit the model after it is generated... you can adjust the template so that the right thing is generated to start with.

Once code is generated you can also do any hand tweaks you want (changing property names etc.). These are just done by editing the code, rather than thru a designer.

"Update model from database" isn't as good for code based models yet, the only option you really have is to regenerate the entire model. This is fine if you do you customization in the templates... but doesn't work well if you have hand edited the code. We'll get this sorted out, but this may be a reason to hold off on adopting EF7 for a while.

BTW the naming of navigation properties generated from a database will be a whole lot better in EF7.

> I also heard that "complex mappings" may not work until later release of EF7. Can you give an example of what is "complex"? Is renaming a db table to a better class name and creating an "Orders" relationship or multiple mapping to the same table such as Customer/SalesRep in the above examples considered complex?

No that is all bread-and-butter basic stuff (we're adding inheritance support for the Customer/SalesRep scenario at the moment). Complex is mixing TPH/TPC/TPT inheritance mapping patterns in the same hierarchy.


Hope that helps :smile: 

~Rowan

**Comment by rowanmiller** [comment]
Closing as I think I answered all your questions... but feel free to re-open if there is anything I missed or my response spurs further questions :smile:
