### ISSUE TITLE
Add IsRelational(), IsSqlServer(), IsInMemory(), etc. (or GetProviderName()) on DatabaseFacade

### ISSUE THREAD

**Issue by danpantry** [dotnet/efcore#6983]
### Steps to reproduce

Given the following class:

```csharp
class DummyContext : DbContext
{
     protected override void OnConfiguring(DbContextOptionsBuilder builder)
     {
            builder.UseInMemoryDatabase();
     }
}
```

When used in the following manner:

````csharp
public class WittyClassName
{
    DbContext ctx;

    public WittyClassName(DbContext ctx)
    {
        this.ctx = ctx;
    }

    public async Task DoWorkAsync()
    {
        await ctx.Database.MigrateAsync();
    }
}
````

### The issue
The above code will grant the following error on the line of `MigrateAsync` when executing `DoWorkAsync`:

````
System.InvalidOperationException : Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
  Stack Trace:
       at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
       at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.MigrateAsync(DatabaseFacade databaseFacade, CancellationToken cancellationToken)
````

This only occurs with the in memory database from my experience and works just fine with the others I've used (which is just sqlite). I would have expected this to have just "worked"; if an in memory schema cannot be created, then make the migration be a no-op.

I can resolve this by providing my own service provider but this involves having to mock not only IMigrator but any other service that the database uses, like `IServiceScopeFactory`. This is a lot of work to have an integration test in an in memory database that utilises migrations. The other option would be to leave this section of the code untested.

### Further technical details

EF Core version: `1.0.1`, `Microsoft.EntityFrameworkCore.InMemory` is also `1.0.1`.
Operating system: OSX Sierra 10.12.1
Visual Studio version: using VS Code 1.5.3

**Comment by danpantry** [comment]
Another alternative is to use `Microsoft.EntityFrameworkCore.Sqlite` with the connection string set to `Data Source=:memory:`.

**Comment by ErikEJ** [comment]
InMemory is not a relational provider, and therefore does not support migrations

**Comment by rowanmiller** [comment]
SQLite in in-memory mode is definitely the way to go if you want to do things like migrations. As @ErikEJ mentioned, InMemory is not intended to be a relational database. The Migrations feature is only contained in the relational libraries since it doesn't really make sense for all types of databases. So InMemory doesn't even depend on it. We're going to update the docs to point folks more heavily towards SQLite rather than InMemory.

Leaving open so that we can discuss making migrations not-throw (and just no-op) when the provider doesn't have migrations. This should probably be a "throw but allow a flag that stops it throwing" approach because there could be relational providers that just haven't implemented migrations yet.

**Comment by danpantry** [comment]
Cool, good to hear. Totally understand that InMemory is not relational, but the error doesn't really convey that very well. :(

**Comment by divega** [comment]
**EF Team Triage:** we want to improve the exception message to explain that migrations is not supported by the provider and add sugar to ask if the database supports this functionality (e.g. `IsRelational()`, provider-specific `IsSqlServer()` and `IsInMemory()` or `GetProviderName()`) to make it easier to write conditional code in tests.

**Comment by AndriySvyryd** [comment]
Merge with https://github.com/aspnet/EntityFrameworkCore/issues/8566 ?

**Comment by onionhammer** [comment]
> InMemory is not a relational provider, and therefore does not support migrations

And therefore does not support seed data? this does not follow for me.

**Comment by AndriySvyryd** [comment]
Already fixed by https://github.com/aspnet/EntityFrameworkCore/pull/8545?

**Comment by ajcvickers** [comment]
Ping @roji

**Comment by ajcvickers** [comment]
Checked and all are implemented except `IsRelational`.

**Comment by WeihanLi** [comment]
> Checked and all are implemented except `IsRelational`.

any plan for `IsRelational` ?

**Comment by ajcvickers** [comment]
@WeihanLi This issue is in the Backlog milestone with the `consider-for-next-release` tag. This means it's not currently planned for the 5.0 release, but it's something we may implement in 5.0 as a stretch goal--in this case because it's a small change.

This issue is also marked with `good first issue` which indicates it is a good candidate for a community pull request.

**Comment by WeihanLi** [comment]
thanks for the info @ajcvickers
