### ISSUE TITLE
When adding a new value type or numeric field a default value is added to the migration

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#7101]
From @YandyZaldivar Nov 16th (PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#115)

Let´s try this for second time. See original issue here PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#39 

I am back to development and I have a pending (closed issue) with you.

When I add a new value field (int) to a table in plain SQL I can mark this field as NULL or NOT NULL, and independently of that I can set or not set a default value. However when using this EF provider whenever I add a new value field I get a default value for that field in the database which I didn´t explicitly specify. And remember that by EF specification you can only define a default value if using the fluent API, so you must not assume any conventions or data annotations for generating default values. Basically I want that when I add a new field independently if it is a nullable type or not that you don´t add a default value into the database which I didn´t explicitly specify, because this is the normal behavior I achieve when not using your provider or not using any provider at all, just using the database engine command line tools.

I would want to write this as part of the discussion of my original issue and expect to receive a convinced answer but instead you closed the issue with no further discussion. Sorry if I am missing something, I hope you help me to clarify this.

**Comment by Kagamine** [comment]
from @caleblloyd

If your field is defined as an `int`, then this library will automatically assign a default value of `0` to it.  That's because the CLR type `int` cannot be null. [Model Deceleration](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/DataTypes.cs#L15), [Empty Value Test Case](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Tests/Models/DataTypesTest.cs#L23)

If your field is defined as `int?`, then this library will automatically assign a default value of `null` to it, since the CLR type `int?` is nullable. [Model Deceleration](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/DataTypes.cs#L22), [Empty Value Test Case](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Tests/Models/DataTypesTest.cs#L30)

Can you post these 4 things:
- Post your model
- `CREATE TABLE` dump for the table that was created
- explanation of the problem
- expected result:

**Comment by Kagamine** [comment]
From @YandyZaldivar

In MySQL `NULL` is not a default value, it just specify if a field must have a value. Besides in MySQL default values are optional, so independently if I mark a field as `NULL` or `NOT NULL` I can chose to set or not set a default value. So the problem with your provider is that you are always assigning a default value when I set an `int` or any other value type which is not a reference or nullable (`xxx?`).

So, in my opinion:

> If your field is defined as int?, then this library will automatically assign a default value of null to it, since the CLR type int? is nullable.

That is right, except maybe that a in MySQL language is not appropriate to refer to null as a default value.

> If your field is defined as an int, then this library will automatically assign a default value of 0 to it. That's because the CLR type int cannot be null.

That is wrong. If my field is an `int` then this library should set the field in the database as `NOT NULL` but without a default value, unless I explicitly set a default value using the fluent API.

> Can you post these 4 things: [...]

I think it is no needed to understand my concern. It happens with all value types distint than nullable or reference types.

**Comment by Kagamine** [comment]
From @caleblloyd

In MySQL, a `NULL` field with no default value implicitly has a default value of `NULL`

A `NOT NULL` int with no default value implicitly has a default value of `0`

We just happen to explicitly set the default value to the implicit value. There's no difference in operation.

**Comment by Kagamine** [comment]
From @YandyZaldivar

@Kagamine 
> If your field is an int, c# will set 0 as its default value. We cannot detect the diffs between public int SomeField{get;set;} and public int SomeField{get;set; }=0

You must not insert value! If you read EF documentation you will find it clearly says:

> Conventions
> By convention, a default value is not con?gured.
>
> Data Annotations
> You can not set a default value using Data Annotations.
> 
> Fluent API
> You can use the Fluent API to specify the default value for a property.

So, if I want to set a default value of `0` for an `int` the only way is using the fluent API:

`modelBuilder.Entity<MyEntity>().Property(p => p.MyProperty).HasDefaultValue(0);`

Supose I want to create a table in MySQL with the following definition, as you can verify this is a correct MySQL SQL script definition:

CREATE TABLE `Pomelo` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Pomelo` int(11) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

The `Pomelo` property is a value type (`NOT NULL`) and doesn't have a default value. 

However if the `Pomelo` field is added to the existent table using your provider instead of:
``Pomelo` int(11) NOT NULL` which is what I expect to achieve, I am ending with:
``Pomelo` int(11) NOT NULL DEFAULT '0'` which is incorrect because I haven't set any default value.

In other words, this definition:
``Pomelo` int(11) NOT NULL`
is equivalent to:
`public int Pomelo { get; set; }`

And this definition:
``Pomelo` int(11) NOT NULL DEFAULT '0'`
is equivalent to
`public int Pomelo { get; set; }`
plus
`modelBuilder.Entity<MyEntity>().Property(p => p.Pomelo).HasDefaultValue(0);`

@caleblloyd 
> In MySQL, a NULL field with no default value implicitly has a default value of NULL

That is correct.

> A NOT NULL int with no default value implicitly has a default value of 0

That is wrong. In MySQL a NOT NULL int with no default value has not a default value. For an int value to have a default value of 0 you need to explicitly write the DEFAULT clause as in
``Pomelo` int(11) NOT NULL DEFAULT '0'`
and to achieve this in Entity Framework the only way is to use the fluent API as in 
`modelBuilder.Entity<MyEntity>().Property(p => p.Pomelo).HasDefaultValue(0);`

If you don't use the fluent API to set a default value it doesn't matter how you define your properties, you should always get
``Pomelo` int(11) NOT NULL`
whitout the DEFAULT clause.

Note: In MySQL when not using strict mode there is the concept of implicit default values, but this is not related to the point we are discussing. What we are discussing is what is the valid C# code that will produce a default clause in MySQL.

For more information please also read the MySQL manual, mainly the section
12.7 Data Type Default Values

> If a column definition includes no explicit DEFAULT value, MySQL determines the default value as follows:
> If the column can take NULL as a value, the column is defined with an explicit DEFAULT NULL clause.
> If the column cannot take NULL as the value, MySQL defines the column with no explicit DEFAULT clause.

**Comment by Kagamine** [comment]
From @caleblloyd

> > A NOT NULL int with no default value implicitly has a default value of 0

> That is wrong.

It is correct.  See the following:

```
mysql> DROP TABLE IF EXISTS `test`;
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE `test` (
    ->   `id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ->   `name` text COLLATE utf8_unicode_ci NOT NULL,
    ->   `num` int(11) NOT NULL
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
Query OK, 0 rows affected (0.03 sec)

mysql> INSERT INTO `test` (`name`) VALUES
    -> ('hi'),
    -> ('whats'),
    -> ('up');
Query OK, 3 rows affected, 1 warning (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 1

mysql> SELECT * FROM `test`;
+----+-------+-----+
| id | name  | num |
+----+-------+-----+
|  1 | hi    |   0 |
|  2 | whats |   0 |
|  3 | up    |   0 |
+----+-------+-----+
3 rows in set (0.00 sec)
```

You're correct in that MySQL does not explicitly say that the default value of the field is 0.  But it's default value _is_ implicitly 0.  That's how the 0's got into the `num` column.  MySQL set them to the implicit default of 0.

This behavior also makes sense, because the default value of the CLR type `int` _is_ 0.

Is this causing a bug in code for you?

**Comment by Kagamine** [comment]
From @YandyZaldivar

What version of MySQL server are you using? Mine is in the original post #39.

> As of MySQL 5.7.5, the default SQL mode includes STRICT_TRANS_TABLES.
> 
> When this manual refers to “strict mode,” it means a mode with either or both STRICT_TRANS_TABLES or STRICT_ALL_TABLES enabled.

```
CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `num` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

-------------------------------------------------------

insert into `test` (`name`) values ('hi'), ('whats'), ('up')

-------------------------------------------------------

1 queries executed, 0 success, 1 errors, 0 warnings

Query: INSERT INTO `test` (`name`) VALUES ('hi'), ('whats'), ('up')

Error Code: 1364
Field 'num' doesn't have a default value

Execution Time : 0 sec
Transfer Time  : 0 sec
Total Time     : 0.038 sec

-------------------------------------------------------

Here is the whole configuration I am using in my database server:

[mysqld]

ssl = false
port = 12484
log-syslog = false
bind-address = "::1"
pid-file = process.pid
secure-file-priv = null
log-error = process.log
log-error-verbosity = 3
lower-case-table-names = 2
character-set-server = utf8
max-allowed-packet = 4194304
explicit_defaults_for_timestamp
innodb-buffer-pool-size = 536870912
collation-server = utf8_general_ci

```

> Is this causing a bug in code for you?

It is causing the following inconsistence, consider this C# entity:

```
    public class Charge
    {
        public int Id { get; set; }
        public int Num { get; set; }
    }
```

When this is first run to create the table it generates the following script:

```
CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `num` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

Then when I add more fields to my C# entity and I apply subsequent migrations:

```
    public class Charge
    {
        public int Id { get; set; }
        public int Num { get; set; }
        public int Num1 { get; set; }
    }
```

```
CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `num` int(11) NOT NULL,
  `num1` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

As you can see my final scripts are populated differently by your provider with some value types having the `DEFAULT` clause and others don't. This behavior is better explained in my original post #39. Through this discussion I have tried to explain you what is the correct behavior to follow, but I will be happy if you just make my code consistent.

**Comment by Kagamine** [comment]
@rowanmiller I've tried other providers, they occurred same issue. So I think it is not a Pomelo issue, it caused by upstream EF Core.

**Comment by divega** [comment]
What would happen in MySQL if the table already contains data (i.e. existing rows) and you add a new non-nullable column with no default value? With other databases that would fail. That is the reason for this behavior.

**Comment by Kagamine** [comment]
@divega In MySQL if the table already contains data, and add a new non-nullable column without default value, like `int`, it will be `0` auto. But in my opinion I don't want to fix this. 

Keep the result which generated by migration differ equal is better for migrate MySQL to other providers.

**Comment by divega** [comment]
BTW, this is about the default migration that gets scaffolded. As a user you are free to change it if you want something else.

**Comment by YandyZaldivar** [comment]
I haven't tested other providers. It would be interesting to see the opinion of someone in the EF team. In the EF documentation it says that by convention, a default value is not configured. In the end I want to be able to migrate from one database engine to other in a reliable manner, so I can accept a behavior that is consistent among the main providers.
