### ISSUE TITLE
Migrations is now specifying the db type in 1.1, whereas in 1.0.1 it didn't

### ISSUE THREAD

**Issue by denisz1** [dotnet/efcore#7108]
I've upgraded my EF Core to the recent 1.1 release. My system uses different databases, including SQLite and SQL Server, so I'm using very generic code everywhere, and I've never had portability problems.

I have some entity with the following config:

    builder.HasKey(b => b.Id);
    builder.Property(b => b.Id).IsRequired().ValueGeneratedOnAdd();

I needed to regenerate my context. The 1.0.1 migration had this:

    .Annotation("Autoincrement", true)

And the 1.1 migration suddenly generated this:

    .Annotation("Sqlite:Autoincrement", true)

Does this mean that now the context can only run on SQLite?

That would be disappointing, as it is less functional than the old version. Maybe there's a config option buried somewhere that controls this behavior?

**Comment by mvermef** [comment]
I believe it was a bug 1.01 where it didn't emit the type before

**Comment by ajcvickers** [comment]
@denisz1 That annotation was always SQLite-specific; it just wasn't following the naming convention for provider-specific annotations in the previous release.

While the overall approach for migrations is to keep them as database provider-agnostic as possible it is still the case that when a migration is scaffolded it is done so for a specific database provider and may contain both model elements and annotations that are intended to work with only that provider. Generally annotations for a different provider are ignored, which means if two providers need different annotations, then you can have all annotations present. You will need to do some hand-editing for this to work. You can also add conditional code in the migration using the ActiveProvider property so that you can do different things on different providers. Again, you will have to hand-edit if you need to use this.

**Comment by denisz1** [comment]
@ajcvickers Thanks for the clarification.

At some point it would be great if the docs mention this in the "advanced" section, or something like that.
