### ISSUE TITLE
Include parent and child in query?

### ISSUE THREAD

**Issue by asadsahi** [dotnet/efcore#7154]
> Customer 1......* Booking

 ```
public class Customer
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Booking> Bookings { get; set; }
    }


  public class Booking
    {
        [Key]
        public int Id { get; set; }
        public string Title{ get; set; }
        public DateTime BookingDate { get; set; }
        public int? CustomerId { get; set; }
        public Customer Customer { get; set; };

    }
```
If _context being DbContext, following two queries ended up in circular dependency.

`_context.Customers.Include(x=> x.Bookings).ToList();
`OR

`_context.Bookings.Include(x=> x.Customer).ToList();
`

Question is how can we query these interdependent relationships if we have to include entity A in B's query and vice versa?

The query returns result from web api, but in browser I get,  net::ERR_INCOMPLETE_CHUNKED_ENCODING. While inspecting the result in api, the only thing I suspect is that circular dependency can be the only reason. Don't get any error in .net side which is confusing.

**Comment by rowanmiller** [comment]
@divega  to find info we posted to a similar issue recently

**Comment by asadsahi** [comment]
@rowanmiller @divega 

Get at the bottom of this after struggling for couple of day. The issue doesn't seem to be with EF Core. When I was querying related entities, and see in debug window, related intities were just going indefinitely. e.g open customer property in booking shows customer, and when opening booking property in customer it shows booking and keeps on going in debug window. I was under the impression that the error I am receiving in browser as a failed asp.net api request (net::ERR_INCOMPLETE_CHUNKED_ENCODING) was because of this circular reference, even entity framework wasn't throwing any exception.

One Solution:

```
 services.AddMvc()
                .AddJsonOptions(options =>
                {
                    // options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                    options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                });

But question remains, that is this something entity framework can handle so that it doesn't created circular references back to parent property.
```

**Comment by divega** [comment]
@asadsahi thanks for your patience. This is not really an issue in EF Core because it would happen if you try to serialize any regular graph of objects with circular references.

There isn't (at least until know, as far as I know) a standard way to represent cyclic references in JSON. 

A common workaround is to omit back-references in objects or to at least annotate them with "ignore" attributes that the serializer recognizes. Another option, as you have found, is to enable a non-standard representation of cycles, a capability present in Json.NET. Beware that once enable this feature, you'll  depend on being able to use Json.NET in any tier of the application in which you need to deserialize the graph.

Although I don't understand all the details, I remember last time this issue was raised there was a discussion about other problems around how ASP.NET Core currently handles this error. See https://github.com/aspnet/IISIntegration/issues/285 for more details.

**Comment by asadsahi** [comment]
@divega Thanks for explaining. Makes sense now. :)

**Comment by tiagocrizanto** [comment]
I ended up in this post due to a google search. The answer here works for older dotnet versions. If you are working with dotnet 6 or greather there are some options:

Add this code on Program.cs:

```
builder.Services.AddControllers()
            .AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
                options.JsonSerializerOptions.MaxDepth = 0;
            });
```

If you are trying serialize an object with System.Text.Json you can use the JsonSerializerOptions to serialize the object:

```
System.Text.Json.JsonSerializerOptions jsonOptions = new() {  ReferenceHandler = ReferenceHandler.IgnoreCycles };
System.Text.Json.JsonSerializer.Serialize(myObject, jsonOptions)
```
