### ISSUE TITLE
Migrations not created correctly

### ISSUE THREAD

**Issue by joacar** [dotnet/efcore#7196]
### Steps to reproduce
1. Create a db context with a model
2. Run `dotnet ef migrations add initial && dotnet ef database update`
3. Add a column to the model that is not required
4. Run `dotnet ef migrations add new_column`
5. Run `dotnet ef database update && dotnet ef database update`

### The issue
Get error message **table '&lt;model&gt;' already exists**. Inspecting the file `<datetime>_new_column.cs` reveals the answer - it tries to create the table again instead of just creating the correct alter command.

**Side note**: It would be better the have the 'migration name' pre-pended to the generated migration file since it would make it easier to work using the command line.

### Further technical details

EF Core version: 1.1.0
Operating system: macOS Sierra 10.12.1
Visual Studio version: Visual Studio preview for Mac
MySQL version: 5.6.10
MySQL adapter: [Sapient](https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql)

Other details about my project setup:

**Comment by Allann** [comment]
I can reproduce something similar.  I have 3 DBContext classes in my project.  when i perform (via PMC scaffold) `add-migration MigrationName -context HistoryContext` it adds the entities from the other contexts too.  It therefore duplicates the CreateTable etc in this migration that are already performed in migrations from the other contexts.
[HistoryContext.zip](https://github.com/aspnet/EntityFramework/files/638330/HistoryContext.zip)
[20161208031200_AddFeeValueId.zip](https://github.com/aspnet/EntityFramework/files/638331/20161208031200_AddFeeValueId.zip)

**Comment by joacar** [comment]
Creating a second migration and then calling `dotnet ef migrations script 1 2` (where 1 and 2 are migrations that I created) doesn't yield the right result. It seem to ignore that there is a current value in the `__EFMigrationHistory`

**Note** Running Sapient MySQL and not sure how much of this logic is maintained in the core repo and what reside in Sapient.

**Comment by rowanmiller** [comment]
@joacar could you share the model classes (or project) so that we can try to reproduce this. Migrations should use the ModelSnapshot.cs file that it generates to work out what changes since the last migration (rather than recreating the whole schema). I guess also just check that you didn't delete/move the snapshot file 😄.

And to answer a couple of your questions...

> Creating a second migration and then calling dotnet ef migrations script 1 2 (where 1 and 2 are migrations that I created) doesn't yield the right result. It seem to ignore that there is a current value in the __EFMigrationHistory

Scripting doesn't pay any attention to the database. It creates a script based on the migrations you specify. This is because scripting is generally used to get a script to apply to a production database.

> Side note: It would be better the have the 'migration name' pre-pended to the generated migration file since it would make it easier to work using the command line.

You can just use the short name (without the timestamp) when you run commands.

**Comment by rowanmiller** [comment]
@Allann your issue seems to be different from the one being discussed here, so probably best to open a new issue. That said, I'm guessing types in one context have references to types in the other contexts? If so, they will get included in the model, and therefore in the migrations too. Take a look at https://github.com/aspnet/EntityFramework/issues/2725 for some discussion - and a feature we are planning that will help with this scenario.

**Comment by Ellinn** [comment]
Same issue @joacar reported.

**Tech details **:
EF Core version: 3.0.0-preview8.19405.11
Operating system: MacOS Mojave 10.14.6
Visual Studio version: Visual Studio preview for Mac
SQL Server: Microsoft SQL Azure (RTM) - 12.0.2000.8

**Comment by ajcvickers** [comment]
@Ellinn This is a closed issue from a long time ago. Please open a _new_ issue and include a _small, runnable_ project/solution or _complete_ code listing that demonstrates the behavior you are seeing.
