### ISSUE TITLE
Same project.json error tolerance as ASP.Net Core / VS

### ISSUE THREAD

**Issue by tedd** [dotnet/efcore#7197]
### Steps to reproduce
Change project.json with either one of these:

- Add a coma before a }.
- Add // in front of a line to comment it out
- Surround a line with /* */ to comment it out.

For example, adding "// test" just before buildOptions:
 },
  // test
  "buildOptions": {

Results in this:
PM> Add-Migration ProsjektInnholdHistory
Both Entity Framework Core and Entity Framework 6 are installed. The Entity Framework Core tools are running. Use 'EntityFramework\Add-Migration' for Entity Framework 6.
Invalid JSON primitive: .

### The issue
EF Core is more sensitive to invalid JSON than ASP.Net Core. While pressing comment-button (CTRL+K, CTRL+C) Visual Studio will comment out lines by adding // or /* */. It also allows ending a list item or key-value block with a coma. This compiles and runs just fine. EF Core however fails to run Add-Migration command due to invalid JSON. It also does not provide any details of where the file is invalid, though it is possible to find out by understanding JSON.

EF Core is not wrong in reacting to invalid JSON, but it does cause problems when VS and ASP.Net Core both allow people to do this.

### Further technical details

EF Core version: 1.1.0
Operating system: Windows 10
Visual Studio version: VS 2015
Other details about my project setup: ASP.Net Core project that has followed upgrade path since RC1,

**Comment by rowanmiller** [comment]
**EF Team Triage:** We are not planning to fix this issue because the pre-release `project.json`/`xproj` project system is being replaced by an MSBuild based system for .NET Core projects. Our approach with `project.json`/`xproj` issues is to find workarounds, rather than spending time fixing issues for a tooling system that will never reach RTM. This allows us to focus our efforts on stabilizing for MSBuild based tooling.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
