### ISSUE TITLE
Can use "IsRowVersion" on InMemory provider?

### ISSUE THREAD

**Issue by hqywork** [dotnet/efcore#7210]
Such as the title?

**Comment by kierenj** [comment]
(Did you try it?)

**Comment by hqywork** [comment]
I try use it! But can not auto generate value, value is null. So I want get help?

**Comment by ErikEJ** [comment]
InMemory is not a relational provider

**Comment by ajcvickers** [comment]
@hqywork The in-memory provider has no support for store-generated values and consequentially no built-in support for optimistic concurrency, so IsRowVersion will have no effect when using the in-memory provider.

**Comment by rowanmiller** [comment]
BTW we updated our docs recently to promote SQLite in-memory mode as much as (if not more than) the InMemory provider. We did this because we were seeing a lot of folks eventually want relational database behaviors in the provider they use for testing. https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/

**Comment by ajcvickers** [comment]
See also #10157
