### ISSUE TITLE
Guidance for unit testing when FromSql<> is used.

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#7212]
We have unit tests that use the `InMemory` provider.

However, a few of our objects under test are calling the `FromSql()` method to materialise objects from stroed procedures.

When using the InMemoryProvider this obviously doesn't work.

One solution i can think of is for the object under test to use the Repository pattern - so we can swap EF7 out entirely at test time, for an InMemory repository. However I think it would be good if the InMemory provider had a way to handle FromSql at test time, so you could map an abitrary set of results when needed?

**Comment by ErikEJ** [comment]
The InMemory Provider is not a relational provider, use SQLite InMemory or localdb

**Comment by dazinator** [comment]
SqlLite sounds like a good shout - thanks 👍

**Comment by dazinator** [comment]
Although worth mentioning, the reason we use InMemoryProvider during testing, is because we want to eliminate the need for having an external database asset to manage. This means we can run tests on any machine quite easily, with minimal setup. 

Using sqllite provider isn't an option if you call an SP, or use a different variant of SQL language. (i.e postgres)

In the situation where you are executing raw sql, you are basically bypassing the ORM's language translation capabilities, and just using it as a mapper that can execute via ADO and

**Comment by rowanmiller** [comment]
@dazinator yep using InMemory or SQLite in-memory mode are all an approximation for running against a real database. In general, SQLite in-memory is a decent approximation for another relational database, but it's never going to be identical. Even if it supports the same features, there is no guarantee it will behave exactly the same as the database provider your application ultimately runs against.

Where you are using something like raw sql to stored procedures, you'll need to either run against the database that supports them, or introduce a layer of abstraction so that you can create a test double for testing.

**Comment by dazinator** [comment]
> or introduce a layer of abstraction so that you can create a test double for testing.
Yup thats what we did. Have made a note: don't call FromSql<> directly!

**Comment by camainc** [comment]
> Yup thats what we did. Have made a note: don't call FromSql<> directly!

@dazinator would you mind elaborating a bit on how you did that? I'm in the same boat, and I'd rather steal from you than reinvent the wheel :-)

**Comment by camainc** [comment]
Thanks for responding. I deleted my comment because I realized it was a stupid question. I did just what you suggested as soon as I deleted the comment.

Thanks again!
