### ISSUE TITLE
IQueryable dbEntity for other where condition

### ISSUE THREAD

**Issue by qianthinkover** [dotnet/efcore#7274]
Hi，all:
       I get a problem for using IQueryable object as return value of linq where operation by querying data 
，when I append other condition for my IQueryable object, this condition will be recognized as and condition but I need to make it as or condition. Is there a code solution to resolve it that condition is appened as and but exactly or.

**Comment by divega** [comment]
@qianthinkover yes, calling `Where()` repeatedly will result in a query that accumulates the effects of all the filter conditions you specified, which is semantically equivalent to chaining the conditions with AND. 

To get OR semantics:
- Chain all the conditions into a single condition using the OR operator (i.e. `||` in C#) and call `Where()` only once
- If you need to do this dynamically at runtime you may better off using a helper, such as [PredicateBuilder](http://www.albahari.com/nutshell/predicatebuilder.aspx)
- For completeness, if there aren't to many different conditions you may get similar results by performing an `Union()` on individual queries, e.g.:

``` C#
var query = source.Where(condition1).Union(source.Where(condition2));
```

In the future, you may be better off asking this kind of questions in a place like http://stackoverflow.com, since it is not specific to EF Core.

**Comment by qianthinkover** [comment]
Thanks a lot!
