### ISSUE TITLE
How to get IDbConnection in TypeMapper

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#7275]
```c#
	    // DateTime
	    private readonly RelationalTypeMapping _datetime         = new RelationalTypeMapping("datetime", typeof(DateTime), DbType.DateTime);
	    private readonly RelationalTypeMapping _datetimeoffset   = new RelationalTypeMapping("datetime", typeof(DateTimeOffset), DbType.DateTime);
	    private readonly RelationalTypeMapping _time             = new RelationalTypeMapping("time", typeof(TimeSpan), DbType.Time);
        private readonly RelationalTypeMapping _datetime6        = new RelationalTypeMapping("datetime(6)", typeof(DateTime), DbType.DateTime);
        private readonly RelationalTypeMapping _datetimeoffse6t  = new RelationalTypeMapping("datetime(6)", typeof(DateTimeOffset), DbType.DateTime);
        private readonly RelationalTypeMapping _time6            = new RelationalTypeMapping("time(6)", typeof(TimeSpan), DbType.Time);
```

```c#
                    { "time", UseDateTime6 ? _time6 : _time },
                    { "timestamp", UseDateTime6 ? _datetime6 :_datetime },
                    { "tinyint", TreatTinyAsBoolean ? _tinyintboolean : _tinyint },
```

I'm the author of `Pomelo.EntityFrameworkCore.MySql`.

We want to detect the `TreatTinyAsBoolean` in connection string to decide treat tinyint as bool or sbyte when scaffolding. And get mysql version, for mysql >= 5.6 we will map `DateTime`(CLR type) to `datetime(6)`(DB Type), mysql < 5.6 map `DateTime`(CLR type) to `datetime`(DB Type).

@rowanmiller any suggestions?

**Comment by ajcvickers** [comment]
@Kagamine Because the connection can change each session you will need your type mapper to be a scoped service. It can then depend on IRelationalConnection. However, the type mapper is designed to cache type mappings across sessions for performance, which is why type mappers should be registered as singletons. You'll probably want to split your type mapper into two services--one singleton containing cached mappings, and one scoped service that handles the mappings that can change. The scoped service would be the one implementing IRelationalTypeMapper and would depend on the singleton service and on IRelationalConnection. You might want the singleton service to extend RelationalTypeMapper so you can use the implementation in that base class, but don't register it as an IRelationalTypeMapper since it should only be accessed through your scoped service.

So something like:
```C#
public class MySqlTypeMapper : RelationalTypeMapper
{
}

public class MySqlScopedTypeMapper : IRelationalTypeMapper
{
    public MySqlScopedTypeMapper(
        MySqlTypeMapper singletonMapper,
        IRelationalConnection connection)
    {
    }
}
````

**Comment by Kagamine** [comment]
Than you, I will try this.

**Comment by caleblloyd** [comment]
I am trying to implement this approach, but my Scoped type mapper is not getting picked up.  It is only using the singleton:

```csharp
public class MySqlTypeMapper : RelationalTypeMapper
{
}

public class MySqlScopedTypeMapper : IRelationalTypeMapper
{
    public MySqlScopedTypeMapper(
        MySqlTypeMapper singletonMapper,
        IRelationalConnection connection)
    {
    }
}

public static class MySqlEntityFrameworkServicesBuilderExtensions
{
    public static IServiceCollection AddEntityFrameworkMySql([NotNull] this IServiceCollection services)
    {
        services.TryAdd(new ServiceCollection()
            .AddSingleton<MySqlTypeMapper, MySqlTypeMapper>()
            .AddScoped<IRelationalTypeMapper, MySqlScopedTypeMapper>()
            ...
```

**Comment by caleblloyd** [comment]
Turns out I needed an override in `MySqlDatabaseProviderServices : RelationalDatabaseProviderServices`
