### ISSUE TITLE
Unit tests failing during build due to wrong dotnet runtime version

### ISSUE THREAD

**Issue by pmiddleton** [dotnet/efcore#7326]
The latest code in the dev branch is failing when running unit tests during the build process.

I am running on windows 10 and receiving the following error.

<code>
info:   program: dotnet
info:   commandline: test --no-build --configuration Debug
info:   workingdir: test\Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests
The specified framework 'Microsoft.NETCore.App', version '1.2.0-beta-001251-00' was not found.
</code>

The build script KoreBuild.ps1 is set to download 1.2.0-beta-001202-00.  I bumped this up to 
1.2.0-beta-001251-00 locally and everything is now working.

I'm not sure if this is just my machine having an issue or not, because the appveyor build on the dev branch is passing and its logs indicate it is using 1.2.0-beta-001202-00.

**Comment by divega** [comment]
cc @pranavkm does this look like something we need to fix on dev?

**Comment by pranavkm** [comment]
@pmiddleton - unfortunately the only time we update our build scripts is if the script directory ('.build directory) in the root of the repository is missing. To get new shared runtime versions, the only way to do this is to remove the directory and run `build initialize` to redownload it. That should in general sort this out. We're looking in to improving this experience since we run in to this all the time too.

**Comment by divega** [comment]
Closing as answered but feel free to respond if this doesn't address the issue or create a new issue if you run into something new with the build.
