### ISSUE TITLE
Access to database in migration

### ISSUE THREAD

**Issue by Materix** [dotnet/efcore#7360]
In our project we used migrations in environment with data which we don't want to lose. Actually we are forced to use some compression directly on model. I created migration where I connect to database and, using SqlClient etc., get, transform and save data. 

Connection string is saved in config.json file. We also used another config file depend on environment. 
Is it any possibility to access to connection string from migration or just to environment specified by `-e` switch in dotnet ef cli?

EF Core version: 1.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by bricelam** [comment]
This isn't really how Migrations are designed to work. The `Migration` classes are merely a way of generating SQL scripts. Connecting to the database during this process would cause strange side effects since the script it's producing in the `Up` method wouldn't actually be executed until *after* the method has completed. You also don't want the database to be altered when it's generating the scripts for `Script-Migration` or while packaging up the app for publishing.

The correct way to do this is inline with the rest of the SQL script it's generating. To do this, use the `Sql` method.

```csharp
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.Sql("-- TODO: Transform and save data using Transact-SQL here");
}
```

**Comment by Materix** [comment]
Some of transformation required by migration cannot be done in T-SQL. We have to pack part of data into json and then compress it by GZIP algorithm. As far as I know there is no build-in method to use GZIP in T-SQL until SQL Server 2016. Actually we use 2014.

We create 3 migrations to do that model transformation. In first we add new column, in second move data and in last remove old columns. All of this operations are done by raw sql (excluding compressing).

**Comment by rowanmiller** [comment]
Discussed at length and concluded that we don't want to do this. As @bricelam mentioned, the code in a migration is run to create a script, which is then run against the database. If you did write code that interacted with the database, it would break scripting (which isn't a blocker on it's own, we could just throw if you tried to access the database during scripting - because there is no database). The bigger issue is that the code would run while the SQL was being created... so it doesn't matter where you put the code, it would always be run before any of the operations in the migration are run. In addition, if you are applying multiple migrations, previous migrations may not even have been applied to the database when your code runs.

**Comment by bricelam** [comment]
One alternative would be to do this while the migrations are applying in your application:
```C#
using (var db = new MyDbContext())
{
    var migrator = db.GetService<IMigrator>();
    db.Database.OpenConnection();
    try
    {
        foreach (var migration in db.Database.GetPendingMigrations())
        {
            // TODO: Do things before each migration.
            // TODO: Access database using db.Database.GetDbConnection()
            migrator.Migrate(migration);
            // TODO: Do things after each migration.
        }
    }
    finally
    {
        db.Database.CloseConnection();
    }
}
```

**Comment by yserious** [comment]
Actually you can access your `dbContext` in a migration, see:
https://stackoverflow.com/questions/42644253/can-i-inject-dependency-into-migration-using-ef-core-code-first-migrations
Once you have your dbContext, you can probably access the connection-string through:
    
            var a = _dbContext.Database.GetDbConnection().ConnectionString;

(I actually use this to add new (non-seeding) data in a separate migration.  However, be _very careful_ when changing data this way.  Your `_dbContext.Save` is executed before any (other) migrations are run.)
