### ISSUE TITLE
Add-migration failed after change platform x64 to x86

### ISSUE THREAD

**Issue by trinvh** [dotnet/efcore#7521]
Add-migration command not working

Exception message:
`Could not find assembly '{project-path}\.\bin\Debug\net452\win7-x64\App.exe'.`

### Steps to reproduce
I need to built x86 assembly instead of x64. So I removed x64 SDK and reinstall x86 version, update project dependencies to latest version too.

project.json:
```
 "buildOptions": {
    "platform": "x86",
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "runtimes": {
    "win7-x86": {}
  }
```

I tried to add new migration with command:
`add-migration Updates -c DbContext`

Not works because there isn't compiled assembly in win7-x64 folder, correct is win7-x86 folder.

### Further technical details
EF Core version: 1.1 x86
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 x64
IDE: VS2015

**Comment by bricelam** [comment]
Standalone (a.k.a. non-portable) apps aren't supported by the `project.json` tools. Please see #7358 for information on trying out the latest MSBuild-based EF Core tools.

**Comment by rowanmiller** [comment]
**EF Team Triage:** We are not planning to fix this issue because the pre-release `project.json`/`xproj` project system is being replaced by an MSBuild based system for .NET Core projects. Our approach with `project.json`/`xproj` issues is to find workarounds, rather than spending time fixing issues for a tooling system that will never reach RTM. This allows us to focus our efforts on stabilizing for MSBuild based tooling.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by bricelam** [comment]
As a workaround, you could try using `dotnet ef migrations add` instead. The CLI commands tend to work better with `project.json`.
