### ISSUE TITLE
Migration files include unnecessary using statements

### ISSUE THREAD

**Issue by jcramer** [dotnet/efcore#7541]
I am using a module based pattern similar to the [SimplCommerce project](https://github.com/simplcommerce).  Myself and the maintainer of the SimplCommerce project have both noticed that migrations generate files with unnecessary `using` statements.  In the case of a project like SimplCommerce, which uses a module loading pattern at runtime and therefore does not have references at compile time, errors occur because of these extraneous `using` statements.  This requires us to remove the unreferenced/unnecessary `using` statements after each migration, a somewhat minor but annoying inconvenience for this use case.  Just wondering if we should expect this to be addressed in future releases.

I am currently using the 1.1.0-preview4-final ef tooling.

**Comment by rowanmiller** [comment]
This is by design, there are some we could remove, but others that we intentionally include even when we know they aren't used. This is because migrations are treated as scaffolded code and can be edited etc.

This has been an ongoing discussion all the way back to EF4.1, with opinions on both sides. We've ultimately just decided to stick with how we do it.
