### ISSUE TITLE
Dictinct not working for custom select

### ISSUE THREAD

**Issue by KANekT** [dotnet/efcore#7549]
Dictinct not add in SQL

For query: 
```
            var queryable = this.dbSet.Where(
                    x =>
                        x.Translation.StartsWith(model.Word) &&
                        (x.Localization == model.From || x.Localization == model.Dest)).Distinct()
                .Select(x => new DictionaryWordCompleterApiModel
                {
                    Word = x.Translation,
                    Localization = x.Localization
                }).Take(10).Distinct();
```
I have DISTINCT in SQL:
```
SELECT TOP(10) [t].[Translation], [t].[Localization]
FROM (
    SELECT DISTINCT [x0].*
    FROM [GameDictionaryWords] AS [x0]
    WHERE ([x0].[Translation] LIKE N'guide' + N'%' AND (CHARINDEX(N'guide', [x0].[Translation]) = 1)) AND [x0].[Localization] IN (N'en', N'es')
) AS [t]
```
BUT for query
```
            var queryable = this.dbSet.Where(
                    x =>
                        x.Translation.StartsWith(model.Word) &&
                        (x.Localization == model.From || x.Localization == model.Dest))
                .Select(x => new DictionaryWordCompleterApiModel
                {
                    Word = x.Translation,
                    Localization = x.Localization
                }).Take(10).Distinct();
```
not DISTINCT in SQL:
```
SELECT TOP(10) [x].[Translation], [x].[Localization]
FROM [GameDictionaryWords] AS [x]
WHERE ([x].[Translation] LIKE N'guid' + N'%' AND (CHARINDEX(N'guid', [x].[Translation]) = 1)) AND [x].[Localization] IN (N'en', N'es')
```
Why not add Distinct?

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by tuespetre** [comment]
Your second query is asking for the distinct entries out of the first ten entries. For some reason EF executes this last `Distinct()` at the client.

Your first query is asking for the distinct entries out of the first ten **distinct** entries. Notice that EF *does* apply the *first* `Distinct()` in SQL but the *last* `Distinct()` is still evaluated client-side. So just because you see the `DISTINCT` keyword in the SQL doesn't mean the second query is wrong.

I guess in theory, EF should be able to push down both of those queries and apply `DISTINCT` to them instead of doing it client-side.

**Comment by smitpatel** [comment]
The first query is having 2 `Distinct()`. The first `Distinct()` happens after where clause (and before select) which means you want distinct of all columns and it is translated to server. Since projection is different and is applied after Distinct, EF causes it to have a subquery containing Distinct. Since in the second query there is no Distinct before projection, it doesn't require subquery.
In both the cases, you want Distinct to happen after taking first 10 elements (which can have duplicates) therefore needing another subquery. Which we can translate to SQL but currently we don't do it for custom projections. See issue #7234

**Comment by KANekT** [comment]
@smitpatel ok! Wait 2.0.0 version...
