### ISSUE TITLE
Scaffolding: Consider generating classes that are JSON serialization-friendly

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#7564]
This matter seems confusing to many customers and has come up as EF Core issues multiple times, e.g. in #3818, #6684, #5429, #4646 and #1854 as well as in VS feedback. 

It is clearly a bug in the application code (as opposed to an issue with EF Core) if the user provides entity types that contain cycles and then attempts operations that require serialize them. 

However in scenarios in which EF Core scaffolding generates the classes, we could do something to help, e.g. generate only some of the navigation properties following some convention to avoid cycles or decorate some navigation properties with a well-know "ignore" attribute that popular JSON serializers recognize. 

Note that users can relatively easy avoid exceptions by configuring the serializer to ignore cycles, but this can lead to missing data if done blindly.

**Comment by rowanmiller** [comment]
@divega to do initial investigation into how other stacks have solved this (i.e. L2S)

**Comment by ajcvickers** [comment]
@divega Punt for 2.0?

**Comment by ajcvickers** [comment]
We discussed this again in triage and decided that for now we aren't going to do anything, partly because the confusion seems to be less now due to more community information, and partly because there is no clear idea on what would be the best thing to do. We would still consider taking a community PR for this if a good proposal can be made--please make sure to comment here (or open a new issue ) with a proposal before submitting a PR.
