### ISSUE TITLE
EF Core cause problems by concurrency

### ISSUE THREAD

**Issue by wangpengxpy** [dotnet/efcore#7570]
NO Description

**Comment by ajcvickers** [comment]
@wangpengxpy The first save inserts all the ReserveInformation entities into the database and they get primary key values assigned. The second save then attempts to save these same entities, but they already have a primary key value assigned, which is why the exception is thrown. The problem is probably in the line `_dbContext.Reservations.Add(reserRecord);` which will mark the graph as Added, implying these are all new entities that need to be inserted, rather than existing entities that need to be updated. Instead, the existing entities need to be set to Unchanged/Modified. Since you are using store-generated keys, you can probably use the Attach or Update methods to do this, or for finer control use TrackGraph.

**Comment by wangpengxpy** [comment]
get it,thanks!
