### ISSUE TITLE
Eager loading not working as expected.

### ISSUE THREAD

**Issue by Lonefish** [dotnet/efcore#7680]
I'm having strange issues with eagerloading when I select a part of a table:

> var x = (from cb in context.CouplingTable.Include(b => b.Blob.Project) select cb.Blob).ToList();
> var x = (from cb in context.CouplingTable select cb.Blob).Include(b => b.Blob.Project).ToList();

Both commands don't load Project, they just show it as null. This code however does work, but gives me a CouplingTable object back, while I don't need that at all, I just need Blob and Blob.Project:

> var x = (from cb in context.CouplingTable select cb).Include(b => b.Blob).Include(b => b.Blob.Project).ToList();

If I then use a second query to get only the blobs, Project is linked:

> var xblobs = x.Select(b => b.Blob).ToList();

But combining them in one big query fails again and leaves project as null:
> var x = (from cb in context.CouplingTable select cb).Include(b => b.Blob).Include(b => b.Blob.Project).Select(b=> b.Blob).ToList();

Which leads me to believe it's a bug when you refer to a linked object combined with eager loading.

### Further technical details
EF Core version: "1.1.0"
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by rowanmiller** [comment]
The issue is that `context.CouplingTable.Include(b => b.Blob.Project)` is telling EF Core "when you return a CouplingTable, include it's related Blob and then the Blobs Project". But then you change the query result so that it no longer returns any CouplingTable instances, so the include is ignored. Take a look at https://docs.microsoft.com/en-us/ef/core/querying/related-data#ignored-includes for more info.

What you want to do is perform the include after you've changed the return type of the query, like this. I tested that this code works.

```c#
var x = (from cb in context.CouplingTable select cb.Blob).Include(b => b.Project).ToList();
```
