### ISSUE TITLE
Simple Select not working

### ISSUE THREAD

**Issue by jasonhjohnson** [dotnet/efcore#7706]
I'm trying to select a list of integers and it's raising an exception.

```
Exception message: System.ArgumentException: Expression of type 'System.Collections.Generic.IAsyncEnumerable`1[System.Int32]' cannot be used for parameter of type 'System.Collections.Generic.IAsyncEnumerable`1[System.Object]' of method 'System.Collections.Generic.IAsyncEnumerable`1[MyProject.Model.Entities.MyTable] Cast[MyTable](System.Collections.Generic.IAsyncEnumerable`1[System.Object])'
Parameter name: arg0
Stack trace:
```

### Steps to reproduce
1. Run the query below (or one like it).

```c#
var ids = await context.MyTable.AsNoTracking()
                .Where(x => x.SomeKey.Equals(keyId))
                .Select(x => x.MyFieldIntegerIWant)
                .ToListAsync();
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: Visual Studio 2015

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
BTW here was my quick attempt to reproduce the issue (which executes successfully). Perhaps you could adjust this code listing to demonstrate the problem.

```c#
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApplication8
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new BloggingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                context.MyTable.Add(new MyTable { SomeKey = 5, MyFieldIntegerIWant = 6 });
                context.MyTable.Add(new MyTable { SomeKey = 5, MyFieldIntegerIWant = 7 });
                context.SaveChanges();
            }

            Test().Wait();
        }

        public static async Task Test()
        {
            var keyId = 5;

            using (var context = new BloggingContext())
            {
                var ids = await context.MyTable.AsNoTracking()
                    .Where(x => x.SomeKey.Equals(keyId))
                    .Select(x => x.MyFieldIntegerIWant)
                    .ToListAsync();
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<MyTable> MyTable { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;");
        }
    }

    public class MyTable
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public int SomeKey { get; set; }
        public int MyFieldIntegerIWant { get; set; }
    }
}
```

**Comment by jasonhjohnson** [comment]
@rowanmiller The issue was caused by a QueryFilter (via Z.EntityFramework.Plus) being applied to my query.
