### ISSUE TITLE
In-Memory and Sql Server behave differently when attaching entities

### ISSUE THREAD

**Issue by wertzui** [dotnet/efcore#7729]
I have a Model that consists of an Order and a Detail.
The relationship between them is 1..*

Entity Order is already attached.
When adding a Detail entity to the Order, the new Detail entity get's different Ids assigned.

In-Memory assigns the Id 1.
Sql assigns some negative Id.

After that, calling context.Attach(detail) does not throw an exception In-Memory while Sql does throw an exception.

I expect both providers to behave the same as this hinders testing.

### Steps to reproduce
```c#
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var order = new Order();
                context.Attach(order);

                var detail = new Detail();
                order.Details.Add(detail);
                detail.Order = order;

                var orderEntry = context.Entry(detail);
                Console.WriteLine("Order Id: " + order.Id);
                Console.WriteLine("Order IsKeySet: " + orderEntry.IsKeySet);
                Console.WriteLine("Order State: " + orderEntry.State);

                Console.WriteLine();

                var detailEntry = context.Entry(detail);
                Console.WriteLine("Detail Id: " + detail.Id);
                Console.WriteLine("Detail IsKeySet: " + detailEntry.IsKeySet);
                Console.WriteLine("Detail State: " + detailEntry.State);

                try
                {
                    context.Attach(detail);
                }
                catch (Exception e)
                {
                    Console.WriteLine();
                    Console.WriteLine("Exception thrown: " + e.Message);
                }
```

This is the output:

> In Memory
> Order Id: 0
> Order IsKeySet: True
> Order State: Added
> 
> Detail Id: 1
> Detail IsKeySet: True
> Detail State: Added
> 
> 
> Sql
> Order Id: 0
> Order IsKeySet: True
> Order State: Added
> 

> Detail Id: -2147482647
> Detail IsKeySet: True
> Detail State: Added
> 
> Exception thrown: The property 'Id' on entity type 'Detail' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.

Here is a minimum example 
[Id Bug.zip](https://github.com/aspnet/EntityFramework/files/804063/Id.Bug.zip)

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Visual Studio 2017 RC 4

**Comment by ajcvickers** [comment]
@wertzui Generation of key values behaves differently between in-memory and relational providers, and even sometimes between different relational providers. If you want an in-memory relational database, then try using SQLite with in-memory mode, as described here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/

Also, there is a bug in the code above such that the state information printed out for order is actually that for detail. I'm not sure exactly what the code is supposed to do, but if the intention is to attach a graph of existing entities, then their key values should be set before you attach the entities. If the intention is to start tracking new entities that will be saved to the database, then look into using Add instead of Attach.

**Comment by wertzui** [comment]
@ajcvickers my Problem is not so much about different Ids, but more about the Sql provider throwing an exception when an already added entity is attached while the In-Memory provider does not.
I think, this behavior should be consistent so the either both throw an exception or they both don't.

**Comment by ajcvickers** [comment]
@wertzui When an entity is Attached (setting state to Unchanged), that is asserting that this entity already exists in the database. This implies that its key value has already been set. When an entity is Added (setting state to Added), that is asserting that this entity is new and has not yet been persisted to the database. For the in-memory database, a key can be generated immediately on Add, which means if the code later says that that entity is Unchanged, we will trust your code and set the state to Unchanged. With the SQL Server provider, it doesn't get a key value immediately on Add, which means that if you later set the state to Unchanged we have to throw because the entity does not have a key value--it has a temp value instead.

Beyond this, there is in general no guarantee that specific behaviors will be exactly the same from one provider to another. EF does not attempt to entirely abstract data access, but rather provide a common set of patterns and mechanisms for working with data. There are lots of things that are supported by one provider and not by another. You could consider this Attach after Add to be something supported by in-memory but not by SQL Server, although that would only really be a valid conclusion if the code was doing something valid, which it really isn't.
