### ISSUE TITLE
DbSet.Add changes Id Property with -2147482647 on new Entities (State Added)

### ISSUE THREAD

**Issue by marcels2204** [dotnet/efcore#7743]
Creating new Entity. Property Id (type: int) is 0.
After calling DbSet.Add() the Id is -2147482647

Exception is thrown after calling SaveChanges()

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Ein expliziter Wert für die Identitätsspalte kann nicht in der Nummernkreis-Tabelle eingefügt werden, wenn IDENTITY_INSERT auf OFF festgelegt ist. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows) at System.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults) at System.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more) at System.Data.SqlClient.SqlDataReader.NextResult() at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader) --- End of inner exception stack trace --- at TSClean.DataAccess.Infrastructure.DataContext.SaveChanges() in C:\git\TSCleanNeu\src\TSClean.DataAccess\Infrastructure\DataContext.cs:line 99 at TSClean.BusinessLogic.Infrastructure.CommitBehavior`2.<Handle>d__3.MoveNext() in C:\git\TSCleanNeu\src\TSClean.BusinessLogic\Infrastructure\CommitBehavior.cs:line 31 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at BusinessLogic.Infrastructure.ValidationBehavior`2.<Handle>d__3.MoveNext() in C:\git\TSCleanNeu\src\TSClean.BusinessLogic\Infrastructure\ValidationBehavior.cs:line 38 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at BusinessLogic.Infrastructure.ExceptionBehavior`2.<Handle>d__2.MoveNext() in C:\git\TSCleanNeu\src\TSClean.BusinessLogic\Infrastructure\ExceptionBehavior.cs:line 29

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).
