### ISSUE TITLE
wrong maxlength when use MigrationBuilder to add column

### ISSUE THREAD

**Issue by hi-xiaoxin** [dotnet/efcore#7749]
hi:

i tried below code in my program ,it's worked . but the column's length is not 200 in database, it's nvarchar(1), am i doing wrong way ?

thank you 

xiaoxin

```
        public static void UpdateDatabase(string connectionString)
        {
            var builder = new DbContextOptionsBuilder<DynamicModelDbContext>();
            builder.UseSqlServer(connectionString);
            var ctx = new DynamicModelDbContext(builder.Options);

            MigrationBuilder builder1 = new MigrationBuilder("SqlServer");
            builder1.AddColumn<string>(
                name: "Description",
                table: "MyTable",
                type: "nvarchar",
                maxLength: 200);

            var generator = ctx.GetService<IMigrationsSqlGenerator>();
            var connection = ctx.GetService<IRelationalConnection>();
            var commands = generator.Generate(builder1.Operations);

            foreach (var cmd in commands)
                cmd.ExecuteNonQuery(connection);
        }

```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2015

**Comment by ajcvickers** [comment]
@xiaoxin1983 When the store type is explicitly specified, then that store type is used rather than generating a store type from other information. In this case, the store type is specified as "ncarchar", which is a synonym for "nvarchar(1)", and hence this is the store type that is used. 

Note that when using EF to scaffold migrations--which is much more common than writing them manually as you are doing above--the above call would not be generated because it is an error to specify "nvarchar" as the column type in an EF model since this can be misinterpreted to mean something other than "nvarchar(1)".
