### ISSUE TITLE
Installing EF tools on WPF 4.5.2 project add references to AspNetCore.Hosting & AspNetCore.Http

### ISSUE THREAD

**Issue by cdie** [dotnet/efcore#7835]
I've installed EF Core tools 1.1.0 on a WPF application, and after installation, I've 4 references to AspNetCore.

Is that mandatory ? It looks like installing some Asp thing within a WPF app, feels bad...
![image](https://cloud.githubusercontent.com/assets/10974241/23794168/192de434-058f-11e7-89de-21a6d4345fc3.png)

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: VS 2017

**Comment by ErikEJ** [comment]
I think it is a well known issue, workaround it by installing the Tools in a separate (scratch) project.

**Comment by bricelam** [comment]
This is by design since we can't differentiate between an ASP.NET Core project targeting .NET Framework and all other .NET Framework projects at the NuGet package level.

This is mitigated by us marking our package as a `developmentDependency`. This tells NuGet that these dependencies aren't part of the app and shouldn't be published/deployed with it.

**Comment by cdie** [comment]
@bricelam  Hum, in my packages.config, this dependency are not marked as developmentDependency. See here :
![image](https://cloud.githubusercontent.com/assets/10974241/23810133/9f50e340-05d0-11e7-9fb4-83ae1cbb4726.png)


Can I mark them by myslef directly with no incidence ?

**Comment by ErikEJ** [comment]
@cdie NuGet version?

**Comment by bricelam** [comment]
That's a limitation of `packages.config`; it doesn't transitively apply the attribute. Also, `project.json` and MSBuild `<PackageReference>` don't handle it on install. (See NuGet/Home#4125)

But, from an EF perspective, we've done everything we can so that NuGet clients *could* do the right thing...

**Comment by bricelam** [comment]
FYI, these may be going away in 2.0.0. (See #8326)
