### ISSUE TITLE
Consider the next change in Microsoft.EntityFrameworkCore.Relational\Query\Sql\DefaultQuerySqlGenerator.cs

### ISSUE THREAD

**Issue by herreraluisr** [dotnet/efcore#7841]
Line 378

                foreach (var xItem in ((dynamic)orderingExpression).Value)
                {
                    aliasExpression = xItem as AliasExpression;
                    if (aliasExpression != null)
                    {
                        if (aliasExpression.Alias != null)
                        {
                            var columnExpression = aliasExpression.TryGetColumnExpression();

                            if (columnExpression != null)
                            {
                                _relationalCommandBuilder
                                    .Append(SqlGenerator.DelimitIdentifier(columnExpression.TableAlias))
                                    .Append(".");
                            }

                            _relationalCommandBuilder.Append(SqlGenerator.DelimitIdentifier(aliasExpression.Alias));
                        }
                        else
                        {
                            Visit(aliasExpression.Expression);
                        }
                    }
                }
                //_relationalCommandBuilder.Append("(SELECT 1)");

**Comment by divega** [comment]
@herreraluisr please provide more details about what your suggested change addresses. 

Also consider sending this as a PR.

**Comment by herreraluisr** [comment]
In the following Query
(From a in Db.tabla select a.campo1, a.campo2) .OrderBy (x => new {x.campo1, x.campo2})

It produces a result:

SELECT field1, field2 ORDER BY (SELECT 1)

And not what should be

SELECT field1, field2 ORDER BY field1, field2

As in version 6.1

**Comment by ajcvickers** [comment]
@divega To investigate what works in L2O and other Linq implementations, and to add a note about ThenBy.

**Comment by ajcvickers** [comment]
We discussed this again in triage and observed that:
* The LINQ ThenBy syntax is the correct way to express this in LINQ queries, and that will work with EF Core
* The interpretation of the ordering for `new {x.campo1, x.campo2}` is ambiguous. EF6 chose to interpret it in a certain way, but this is different from how Linq-to-Objects interprets it, which is to throw because there is no unambiguous way to order the anonymous type

Given this, we are not going to change the behavior in EF Core--it will continue to throw like L2O does. The query should instead be written using ThenBy syntax with is unambiguous.
