### ISSUE TITLE
Not possible to use Temporal tables with entity framework?

### ISSUE THREAD

**Issue by slubowsky** [dotnet/efcore#7883]
Temporal tables have several restrictions [https://msdn.microsoft.com/en-us/library/mt604468.aspx](url) including no cascading deletes or "instead of" triggers.

Does this mean that either you cant use entity framework for deletes (and instead need to write custom procedures that delete related entities) or you cant use temporal tables? (I suppose you could also write entity framework code to delete the related items from the bottom up as well but I don't want dozens of little calls from my API app back to my database)

**Comment by ajcvickers** [comment]
@slubowsky I believe temporal tables should be usable with EF, with a couple of limitations as described here: #4693.

With regard to cascade deletes, EF does not require cascade deletes on the database in order to function correctly. However, if the database does not have cascade deletes, then all related entities must be loaded into the context before the delete happens to ensure that everything is deleted that should be.
