### ISSUE TITLE
DbSet.AddRange not preserving order of list in sql database

### ISSUE THREAD

**Issue by ksmithRenweb** [dotnet/efcore#7894]
What we are seeing is that the order is not preserved when we add a range of values.

### Steps to reproduce
1) Insert an list with a specific order. using an dbset addrange call.
2) Check database table to review order.

pseudo code:
```C#
static void TestAddRange()
{
  List<TestTable> list = new List<TestTable>(5);
  
  for(int i=4; i >= 0; i--)
     list.Add(new TestTable{Name = "test", OrderBy = i+1};

  List<TestTable> orderedlist = list.OrderBy(t => t.OrderBy);

  context.TestTable.AddRange(orderedlist);
  context.SaveChanges();

  // alternate that fails as well
  //foreach(var temp in orderedlist)
  //  context.TestTable.Add(temp);
  //
  //context.SaveChanges()

  // alternate code that succeeds but results in 5 round trips to database.
  //foreach(var temp in orderedlist)
  //{
  //  context.TestTable.Add(temp);
  //  context.SaveChanges()
  //}
}
```
Result in database
Id , OrderBy
1, 3
2 , 1
3, 4
4, 2
5, 5 

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Azure Service Fabric (.net 4.5.2)
IDE: (e.g. Visual Studio 2015)

**Comment by ajcvickers** [comment]
@ksmithRenweb There is no guarantee that entities will be inserted in the order that they are tracked. There are actually many reasons for this, both around efficiency of internal data structures and the need to re-order where dependencies exist. Also, many stores will not preserve order once inserted, and hence trying to preserve order while inserting doesn't help.

If you are looking for specific key values to be assigned to specific entities, then you might want to look into not using store-generated keys, or perhaps introducing a surrogate key that can be used to preserve the ordering you need.

**Comment by ismailkocacan** [comment]
> 

@ajcvickers Why didn't you do ordering is optional or add flag ?  
Is that so hard ?

**Comment by roji** [comment]
@ismailkocacan with relational database, the ordering of inserts simply doesn't matter at all. You can insert rows in a certain order, but the database will send them to you in another order when you select them out.

If you want rows to be selected in a particular order, you must specify an ORDER BY clause in any case. That's why adding rows in a particular order doesn't really have any meaning.

**Comment by IvanShymanouski** [comment]
> If you want rows to be selected in a particular order, you must specify an ORDER BY clause in any case. That's why adding rows in a particular order doesn't really have any meaning.

It has meaning for autoincremented indexes, in my opinion, when you are relying on an order. I understand that getting all the things we need either add items one by one with calling `SaveChanges` or create additional field to monitor order.
However, if I would like simply use autoincrement property to track order, I can't do it with `AddRange` method group, I'm forced to use mentioned options.

So, I tend to think that it still makes sense, but probably it's hard to implement within current EF architecture, that's why it's not implemented.
P.S, .net `List` type itself assumes some order that you can rely on. And it's logically that when you are providing the ordered object set, you are expecting that function would preserve it.
P.P.S. It's just some thoughts, after some debugging time. Hopefully, if it's not so difficult, it would be implemented one day :)

**Comment by roji** [comment]
@IvanShymanouski it's true that if you're relying on autoincremented IDs to express some sort of order, insertion order can be important. However, there are good reasons why EF Core sometimes reorders insertions - see https://github.com/dotnet/efcore/issues/7894#issuecomment-286864644 (there are other reasons).
