### ISSUE TITLE
FromSql Issue - Incorrect values returned

### ISSUE THREAD

**Issue by redowl3** [dotnet/efcore#7917]
I'm not sure if I'm doing something wrong but when I try to use FromSql the data returned is not the same as when running the SQL directly.

When running the following query 

SELECT i.Id, irt.RegionId, t.Code, s.Code AS SupplierCode FROM Item i
                    INNER JOIN ItemRegionTariff irt ON i.Id = irt.ItemId
                    INNER JOIN Tariff t ON t.TariffId = irt.TariffId
                    INNER JOIN Supplier s ON i.LastOrderSupplierId = s.Id
		   ORDER BY i.Id, irt.RegionId

In SQL I get

918	1	4419001000	ALP001
918	2	4419008000	ALP001
918	3	0000000000	ALP001
919	1	4202918090	CEN006
919	2	4419008000	CEN006
919	3	0000000000	CEN006

When I run the same query using FromSQL I get

918	1	4419001000	ALP001
918	1	4419008000	ALP001
918	1	0000000000	ALP001
919	1	4202918090	CEN006
919	1	4419008000	CEN006
919	1	0000000000	CEN006

(The Region Id is repeated) 

Any ideas?

### Further technical details
EF Core version: (found in project.json or packages.config) 1.0.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017)

**Comment by ErikEJ** [comment]
Could you share your code/model?

**Comment by redowl3** [comment]
Sure, 
  
 (In Context) 
public DbSet<ItemUploadExport2> ItemUploadExports { get; set; }

(In Repo)
   var itemUploadExports= _context.ItemUploadExports
                    .FromSql(@"SELECT i.Id, irt.RegionId, t.Code, s.Code AS SupplierCode FROM Item i
                    INNER JOIN Tariff t ON t.TariffId = irt.TariffId
                    INNER JOIN Supplier s ON i.LastOrderSupplierId = s.Id
                    INNER JOIN ItemRegionTariff irt ON i.Id = irt.ItemId
					ORDER BY i.Id, irt.RegionId").ToList();

(Model)
    public class ItemUploadExport
    {
        public int Id { get; set; }
        public string SupplierCode { get; set; }
        public int RegionId { get; set; }
        public string Code { get; set; }
      }

**Comment by ajcvickers** [comment]
@redowl3 We suspect that this is due to identity resolution on the returned entities, although this doesn't quite match the data provided. More specifically, when EF encounters a row with the same key value as an entity that has previously been created, then it will not create a new entity but instead return the entity that was already created. So, in the data provided, EF will create an entity for key 918 and return it three times, then create one for 919 and return it three times.

There are a couple of things you can try to workaround this issue:
* You could try doing a no-tracking query using AsNoTracking(), but there is some level of identity resolution here as well, so it might not work.
* You could try changing the key definition for ItemUploadExport so that it contains more properties. This could then make the rows returned each have a unique key so that identity resolution will not find repeated entities.

Issue #1862 is tracking support for raw SQL queries of non-entity types, which would not have this problem.
