### ISSUE TITLE
Many to Many Query Problem

### ISSUE THREAD

**Issue by tylerlrhodes** [dotnet/efcore#7991]
I'm having to write an additional query to get access to categories below.  This is a many-to-many relationship and even though I've included them in the first query, when I go to retrieve them via the method I have with the variable `categories2` I'm returned a null list.  So I have to query for the Ids and then do another query directly from my Categories table in order to get the actual data back.

This doesn't seem right to me.

Looking at it in the debugger I can see that the Id's are returned from the many-to-many query but the actual object is not.

I can post more of the code if needed, or create a gist.

Thanks in advance for any help.

```      
var posts = await _context.BlogPostFeature
                              .Where(bpf => bpf.FeatureId == feature.Id && bpf.BlogPost.Public == true && bpf.BlogPost.PublishOn < DateTime.Now)
                              .Include(bpf => bpf.BlogPost)
                                .ThenInclude(bpf => bpf.Author)
                              .Include(bpf => bpf.BlogPost)
                                .ThenInclude(bp => bp.Categories)                                 
                              .ToListAsync();

      List<ViewBlogPostViewModel> viewPosts = new List<ViewBlogPostViewModel>();

      foreach (var p in posts)
      {
        var categories2 = p.BlogPost.Categories.ToList();

        var categoryIds = p.BlogPost.Categories.Select(c => c.CategoryId);

        var categories = await (from cat in _context.Categories
                                where categoryIds.Contains(cat.Id)
                                select cat).ToListAsync();
```

I have noticed that if I explicitely do something like:

     ` var Categories = await _context.Categories.ToListAsync();`

Before running my query for posts then I don't have to make the extra query below, but it doesn't seem like I should
have to do this.

**Comment by ajcvickers** [comment]
@tylerlrhodes We're probably going to need a full project to reproduce this. In particular, we will need to know what the entity types look like, and also any configuration in OnModelCreating.

**Comment by tylerlrhodes** [comment]
@ajcvickers thanks for your reply.  You can see the database context class with the OnModelCreating at the link below.

https://github.com/tylerlrhodes/bagombo/blob/master/src/blog/Data/BlogDbContext.cs

The entity types can be found under the models folder:

https://github.com/tylerlrhodes/bagombo/tree/master/src/blog/Models

The whole project on Github is at:

https://github.com/tylerlrhodes/bagombo

Thanks again

**Comment by smitpatel** [comment]
@tylerlrhodes - Thanks for providing full project code.

The problem in the query is, you are not eager loading the navigation you need.
Following are the queries being used,
```C#
var posts = await _context.BlogPostFeature
    .Where(bpf => bpf.FeatureId == feature.Id && bpf.BlogPost.Public == true && bpf.BlogPost.PublishOn < DateTime.Now)
    .Include(bpf => bpf.BlogPost)
        .ThenInclude(bpf => bpf.Author)
    .Include(bpf => bpf.BlogPost)
        .ThenInclude(bp => bp.Categories)
    .ToListAsync();

var categories = p.BlogPost.Categories.Select(c => c.Category).ToList();
```

While querying for `BlogPostFeature` you are loading related `BlogPost` & further loading related `BlogPostCategory` (using navigation `Categories`). So in your final query you will have collection of BlogPostCategory populated but no navigation property in `BlogPostCategory` will be loaded since there was no further `Include`. Therefore when you try to get value of `categories` variable, all `BlogPostCategory.Category` is null and you will get a list of nulls.
You need to update your original query like this
```C#
var posts = await _context.BlogPostFeature
    .Where(bpf => bpf.FeatureId == feature.Id && bpf.BlogPost.Public == true && bpf.BlogPost.PublishOn < DateTime.Now)
    .Include(bpf => bpf.BlogPost)
        .ThenInclude(bpf => bpf.Author)
    .Include(bpf => bpf.BlogPost)
        .ThenInclude(bp => bp.Categories)
        .ThenInclude(bpc => bpc.Category)
    .ToListAsync();
```
This will populate `Category` navigation and categories variable will have correct value.

You have many to many relationship between `BlogPost` & `Category` table using `BlogPostCategory` as join table. When you want to get all the related data from one side of many-to-many, you need Include followed by ThenInclude. In above query, your starting point is another join table so first `Include` will be used just to load `BlogPost` and 2 more include required. Probably confusion here is the navigation name `Categories`. While writing the query, it feels like you are including `Categories` but in reality you are including `BlogPostCategory` and `Category` is still not loaded.

Explicitly loading all categories in the context helps because that will load all the categories in the context and navigation fix up will connect the categories to `BlogPostCategory` objects.

**Comment by tylerlrhodes** [comment]
Perfect.  Thank you.

I think I need to rely less on Intellisense too.  The auto complete for
that last ThenInclude didn't include Category on bpc, one of the rare spots
where Intellisense didn't come up with a possible suggestion.

Thanks for your help.

Tyler

**Comment by smitpatel** [comment]
You were hitting issue https://github.com/dotnet/roslyn/issues/8237 there.
Intelliense does not provide much help after getting into `ThenInclude`. Regardless, if you write the full query, it will compile.

**Comment by tylerlrhodes** [comment]
Yep, tested it out and it works great.  Thanks again for all your help.
