### ISSUE TITLE
Navigation Issue: subquery is using outquery alias, which is out of scope

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#8032]
Hi,
We are running below Navigation test scenario via IBM EF Core provider against DB2 LUW server:

``` C#
var navTest = 
    from p in context.OrderDetails
    from q in context.Product
    where q.OrderDetails.Contains(context.OrderDetails.FirstOrDefault())
    select q;
Console.WriteLine("navigation count: " + navTest.Count());
``` 

Generated Query:

``` SQL
      SELECT COUNT(*)
      FROM OrderDetails AS p
      CROSS JOIN Products AS q
      WHERE EXISTS (
          SELECT 1
          FROM (
              SELECT o.OrderID, o.ProductID
              FROM OrderDetails AS o
              WHERE q.ProductID = o.ProductID
          ) AS t00
          INNER JOIN (
              SELECT o0.OrderID, o0.ProductID
              FROM OrderDetails AS o0 FETCH FIRST 1 ROWS ONLY
          ) AS t1 ON (t00.OrderID = t1.OrderID) AND (t00.ProductID = t1.ProductID))
``` 
Exception:
------------

> fail: Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler[1]
      An exception occurred in the database while iterating the results of a que
ry.
      IBM.Data.DB2.Core.DB2Exception: ERROR [42704] [IBM][DB2/NT64] SQL0204N  "Q
.PRODUCTID" is an undefined name.[IBM][DB2/NT64] SQL0204N  "Q.PRODUCTID" is an u
ndefined name.

Sub query where clause contains:

``` SQL
WHERE q.ProductID = o.ProductID
``` 

here q.ProductID is out of scope and hence throws error.

We could see same SQL query against SQL server as well, but SQL server supports it.

How could we control it ?  

/Archana

**Comment by divega** [comment]
@archanasoni Sorry for the late answer. I am catching up with issues assigned to me. 

> here q.ProductID is out of scope and hence throws error.

I believe DB2 supports the general feature of correlating values from the outer query's in expressions in a subquery, e.g. among some examples I found in the Internet:

``` SQL
  SELECT EMPNO
    FROM DSN8A10.EMP X
    WHERE EXISTS (SELECT * FROM DSN8A10.EMP
                   WHERE X.WORKDEPT=WORKDEPT AND SALARY<20000);
``` 

Can you point out what the exact limitation is that prevents `q`  from being in scope? E.g. is `q` is defined two levels up?

**Comment by archanasoni** [comment]
@divega , Yes problem seems to be with 2 level up:
as in your example if I modify something like:
select * from orderdetails as x
where exists ( select 1 from ( 
select productid from products as y
 where x.productid=y.productid 
) as t)

again we can see the same error.
Invalid SQL statement
ERROR [42704] [IBM][DB2/NT64] SQL0204N  "X.PRODUCTID" is an undefined name.


For original query, if we change like:
 SELECT COUNT(*)
      FROM OrderDetails AS p
      CROSS JOIN Products AS q
      WHERE EXISTS (
          SELECT 1
          FROM (
              SELECT o.OrderID, o.ProductID
              FROM OrderDetails AS o
             
          ) AS t00  
		   INNER JOIN (
              SELECT o0.OrderID, o0.ProductID
              FROM OrderDetails AS o0 FETCH FIRST 1 ROWS ONLY
          ) AS t1 ON (t00.OrderID = t1.OrderID) AND (t00.ProductID = t1.ProductID) **AND (q.ProductID = t00.ProductID))**
         
it works for us. But question is how could we do it ?

**Comment by divega** [comment]
@archanasoni thanks for the additional information. 

@anpete @smitpatel @maumar In summary, The original query does not work because DB2 does not support correlating a subquery to a value that comes from more than one level up in the outer query. Rewriting the query as in the comment above (moving the predicate from the WHERE clause of the most nested subquery into the ON clause of the JOIN) would work. 

A few questions:
- Is there a simple way a provider can change how the query gets generated in a provider so that it uses the second form?
- Is this something we should consider doing ourselves in the default SQL we generate by default?
- Do you think the limitation in DB2 break an assumption that is widespread in the EF Core that could affect other query patterns?

**Comment by divega** [comment]
Just to reflect some of the conversation we had today in triage about this:

- We don't think this would be a good change for base provider since moving filters away from the source table can affect performance if the query engine of the database isn't sophisticated enough 
- We could suggest a change that forces the subquery would be evaluated separately.
- @smitpatel suggested it would be cleaner to if the predicate could be lifted to the WHERE clause of the first subquery, since this condition is not correlating the participants of the JOIN, e.g.:
  ``` SQL
  SELECT COUNT(*)
  FROM OrderDetails AS p
  CROSS JOIN Products AS q
  WHERE EXISTS (
      SELECT 1
      FROM (
          SELECT o.OrderID, o.ProductID
          FROM OrderDetails AS o
          ) AS t00  
      INNER JOIN (
          SELECT o0.OrderID, o0.ProductID
          FROM OrderDetails AS o0 FETCH FIRST 1 ROWS ONLY
      ) AS t1 ON (t00.OrderID = t1.OrderID) AND (t00.ProductID = t1.ProductID) 
      WHERE q.ProductID = t00.ProductID)
  ```
  This may still be complicated for providers for database that have this limitation but at least it is starting to look like a general pattern of lifting expressions over JOINs.

**Comment by ajcvickers** [comment]
Closing this for now as there hasn't been any movement. We can re-open if this is still an issue and there is more to discuss/decide from the DB2 side.

**Comment by ShamsulAmry** [comment]
I found [this page for IBM Informix](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.sqlt.doc/ids_sqt_181.htm) which stated that correlated subqueries are only supported in projection or where clause only.

And also found [this page for IBM DB2 iSeries](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/sqlp/rbafycorrs.htm) which indirectly hinted that correlated subqueries are only supported in projection, where or having clause only.
