### ISSUE TITLE
[SQLite] Filtering by string fields is case sensitive

### ISSUE THREAD

**Issue by darkurse** [dotnet/efcore#8033]
I still cannot apply a case insensitive filter to my SQLite queries. Looking at the source, `instr()` is still used as the expression translator for `.Contains()`. Why not use the SQLite `like()` function to do the job (if mapping the LIKE operator is an issue) ?

Note that the same exact use of `.Contains()` filter with **sqlserver** provider results in the use of a case insensitive filter.

This is not an edge case so I don't understand why this is still an issue. Am I missing something obvious ?

### Steps to reproduce

A quick project to reproduce the issue : [WebApplication1.zip](https://github.com/aspnet/EntityFramework/files/881604/WebApplication1.zip)

Code of interest :
```c#
using (ZooContext context = serviceProvider.GetService<ZooContext>())
{
    if (!context.Animals.Any())
    {
        context.AddRange(
            new Animal() { Id = 1, Name = "Mr Giraffe" },
            new Animal() { Id = 2, Name = "Ms Lion" }
        );
        context.SaveChanges();
    }

    // Different case --> Filter is not working
    var result = context.Animals.FirstOrDefault(o => o.Name.Contains("GIRAFFE"));
    Console.WriteLine(result?.Name ?? "Not found");

    // Exact same case --> Filter is working
    var result2 = context.Animals.FirstOrDefault(o => o.Name.Contains("Giraffe"));
    Console.WriteLine(result2?.Name ?? "Not found");
}

public class Animal
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

**ps:** Issue was originally posted in issue #6397

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: windows 10 pro
IDE: Visual Studio 2017 enterprise

**Comment by ajcvickers** [comment]
@darkurse There are several things at play here and a few ways to get the behavior you want:
* Different database engines treat casing differently in comparisons. We have brainstormed many times whether we should try to force all engines to do the same thing, but doing so has perf costs and makes queries ugly, so as of now we are not intending to try to influence the native database behavior here. Even if we did, it would likely be to make all databases do case sensitive, since that most closely matches C#/LINQ to Objects semantics.
* We are adding explicit support for using LIKE. It has issues in general translations from normal .NET methods, so we are making it an opt-in translation. See #7611. This may then give you want you want, at least for latin characters.
* You could set the collation on the column if you want all comparisons to be done in a certain way.
* You can use FromSQL to write some raw SQL to do whatever query you want.
* You could look at replacing the IMethodCallTranslator to do a different translation.

Hope some of this helps!

**Comment by darkurse** [comment]
@ajcvickers, thank you for your answer.

Regarding : 
 - Adding a collation on the column on sqlite doesn't seem to change anything if you keep using `instr()` in EF
 - FromSQL option, I was **really** hoping to avoid this option.
 - Once you'll have EF.Functions feature released, I will definitely use it ! **Any ETA ?** 
 - And finally regarding IMethodCallTranslator, I didn't know we could do that. Can I actually add a translation rather than replacing one ? What if I add an extension method `string.ContainsNoCase()` and map it to a Like Expression ? I just spent a couple of hours attempting to make this work from [this gist](https://gist.github.com/Antaris/ca0f271311fdb84ef3a8db95b149a307) to no avail.

What I want to do
```C#
var animal = context.Animals.FirstOrDefault(o => o.Name.ContainsNoCase("GIRAFFE"));
Console.WriteLine(result?.Name ?? "Not found");
```

How I try to do it.

**1. Register my new IMethodCallTranslator service :**
```C#
services.AddScoped<
    Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal.SqliteCompositeMethodCallTranslator, 
    CustomSqliteCompositeMethodCallTranslator>();
```
**2. The registered IMethodCallTranslator service :**
```C#
internal class CustomSqliteCompositeMethodCallTranslator : SqliteCompositeMethodCallTranslator
{
    private static readonly IMethodCallTranslator[] _methodCallTranslators =
    {
            new SqliteLikeTranslator()
    };

    public CustomSqliteCompositeMethodCallTranslator(ILogger<SqliteCompositeMethodCallTranslator> logger) : base(logger)
    {
        AddTranslators(_methodCallTranslators);
    }
}
```
**3. My Like translator class :**
```C#
public class SqliteLikeTranslator : IMethodCallTranslator
{
    private static readonly MethodInfo _methodInfo
        = typeof(StringExtensions).GetRuntimeMethod(nameof(StringExtensions.ContainsNoCase), new[] { typeof(string) });

    private static readonly MethodInfo _concat
        = typeof(string).GetRuntimeMethod(nameof(string.Concat), new[] { typeof(string), typeof(string) });

    public Expression Translate(MethodCallExpression methodCallExpression)
    {
        return ReferenceEquals(methodCallExpression.Method, _methodInfo)
            ? new LikeExpression(
                methodCallExpression.Object,
                Expression.Add(
                    Expression.Add(
                        Expression.Constant("%", typeof(string)), methodCallExpression.Arguments[0], _concat),
                        Expression.Constant("%", typeof(string)),
                    _concat))
                : null;
    }
}
```
**4. Quick string method extension to be mapped :**
```C#
public static class StringExtensions
{
    public static bool ContainsNoCase(this string self, string match)
    {
        return self.IndexOf(match, StringComparison.CurrentCultureIgnoreCase) >= 0;
    }
}
```

Any pointers ?

**Comment by ajcvickers** [comment]
@anpete Can you give @darkurse some guidance on this?

**Comment by anpete** [comment]
@darkurse The translator looks OK. Do you get into Translate if you set a breakpoint there?

**Comment by darkurse** [comment]
@ajcvickers and @anpete, thanks for reaching out to help. 

To answer to you question : No, I don't. And I don't even get a breakpoint on CustomSqliteCompositeMethodCallTranslator ctor.

Is there an additional step missing to associate ContainsNoCase to my translator at a higher level ?

**Comment by anpete** [comment]
@darkurse I wonder if it is to do with service registration. Have you seen [this post](https://blog.oneunicorn.com/2016/10/27/dependency-injection-in-ef-core-1-1/) on how to replace services?

**Comment by darkurse** [comment]
Hi @anpete, sorry for late reply as I've been down with nasty flu :(

Spot on ! Your intuition was correct, it was the service registration.  And also I made a mistake with the second string parameter in my `ContainsNoCase` signature when defining internally the `MethodInfo` :

```C#
public class SqliteLikeTranslator : IMethodCallTranslator
{
    private static readonly MethodInfo _methodInfo
        = typeof(StringExtensions).GetRuntimeMethod(
            nameof(StringExtensions.ContainsNoCase), 
            new[] { typeof(string), typeof(string) }); <-- I forgot the 'this string' parameter
   ...
```

However, it still doesn't work .. The method `Translate(MethodCallExpression methodCallExpression)` is called with a `methodCallExpression.Object = null` when processing the ContainsNoCase expression. Any clues ?

**Comment by anpete** [comment]
@darkurse Looks like ContainsNoCase is a static extension method so the target will be the first argument, not .Object.

**Comment by darkurse** [comment]
Oups :S Sorry about that. Thank you so much, it all works like a charm. 👍

**Comment by fellsoft** [comment]
I'm having this issue with EFCore 6 & SQLite currently. This seems fairly fundamental, so I'm surprised it's hard to track down information on it - this thread is the best one I've found that covers the issue, but it's 5 years old now.

Anyway - is implementing IMethodCallTranslator still the best solution?

**Comment by fellsoft** [comment]
Using the NOCASE collation would have been my preferred option. I was able to create the column with NOCASE collation through EFCore 6, but when querying with EFCore 6 it was still case sensitive. That was rather puzzling to me, because the column did then work as expected (i.e. not case sensitive) when I queried it natively using DBBrowser for SQLite.

But as @darkurse noted above:
"Adding a collation on the column on sqlite doesn't seem to change anything if you keep using instr() in EF"

I thought that might have changed, but apparently not.

Thanks.

**Comment by roji** [comment]
@fellsoft that would mean EF Core is generating different SQL from what you're using in DBBrowser. Can you please open a separate issue with the full information, including the full EF Core query and model, and the raw SQL you're trying out in DBBrowser?

**Comment by fellsoft** [comment]
So, this was interesting. I went back to my 'real' project and tried this out again and it definitely wasn't working (i.e. I couldn't get the NOCASE collation on the column honoured in code). I then built a new minimum project to reproduce and that DID work as advertised. Huh.

Turns out the key difference was that in the real (not working) project I was doing the equivalent of this (for some reason unknown):
`var result = context.Animals.AsEnumerable().Where(a => a.Name == "GIRAFFE").FirstOrDefault()`

But in the minimum (working) project I was doing this:
`var result = context.Animals.FirstOrDefault(a => a.Name == "GIRAFFE");`

On the face of it these don't seem that different, but I believe the first example pulls all the data from the database down to the 'client' and then the comparison is done there (i.e. just a normal C# string comparison); whereas in the second example the comparison is done on the database (which does then honour the NOCASE collation).

There's obvious performance implications with large data sets, but I hadn't appreciated how it also affected where the comparison gets done and that might mean different behaviour.

**Comment by roji** [comment]
> On the face of it these don't seem that different, but I believe the first example pulls all the data from the database down to the 'client' and then the comparison is done there (i.e. just a normal C# string comparison); whereas in the second example the comparison is done on the database (which does then honour the NOCASE collation).

That's correct, and client-evaluation (via AsEnumerable above) notably doesn't allow SQLite to use any indexes, which is very important. This topic is covered in [this doc page](https://docs.microsoft.com/en-us/ef/core/querying/client-eval).
