### ISSUE TITLE
Separation of Concerns: Tool makers vs tool users

### ISSUE THREAD

**Issue by ImageQC** [dotnet/efcore#8080]
**What isn't working: issue relating to tool makers are jumbled with issues relating to tool users.**

I am a tool user - i.e. someone who uses EF but has no interest in maintaining it (sorry, I'm much too busy with my cancer research work). I found an issue with Scaffold-DbContext and found the issue Reverse-Engineer in RC2: Scaffold-DbContext not working on ASP.NET Core project #5376. This issue contains lots of posts from tool users complaining about it not working and lots of posts from tool makers suggesting workarounds. I spent about an hour trying the various workarounds, but none of them was particularly effective. The issue is closed, but there's no clear resolution or advice. It seems that this is a common story for many issues here.

Why not create a list of know issues each containing 'latest status':

1. clear description of the issue - in my case using Scaffold-DbContext with LocalDb  
2. the latest workaround advice - in my case putting the connection string inside "'{string}'" (which doesn't work, by the way)
3. target release for a fix

A link to the this 'latest status' could be put at the top of each issue. In this way tool users do not have to trawl though large number of posts by the tool makers suggesting what might be wrong, what to try next, etc.

I know this isn't a code issue, but sometime we need to look at the way we work too.

**Comment by ajcvickers** [comment]
@ImageQC Thanks for providing this feedback. We strive to be helpful to both people using EF and those wanting to contribute. For any bug we always try to provide:
- Information about the status of any fix. This is contained in the panel on the right. Specifically:
 - The release (milestone) in which we plan to release a fix (for open issues), or where the fix has been/will be released (for fixed issues)
 - The status of the issue if it has been closed--for example "closed-fixed" for fixed issues. (This was missing on the bug you referenced so I added it.)
- Workarounds that users of EF can use until the issue is fixed/released
- References to other useful resources

When we ship releases, we also include known issues in the release notes, including workarounds for those issues.

All of this information is aimed at users of EF rather than contributors.

It's also worth mentioning that for using EF, as opposed to reporting bugs, we have documentation (https://docs.microsoft.com/en-us/ef/) and we recommend that questions be asked on Stack Overflow (http://stackoverflow.com/questions/tagged/entity-framework-core) where the community can help with answers.

All that being said, this is an open source project with a freely available issue tracker and as such it is hard to control the discussion threads on issues. We try to keep things clean, but sometimes discussions do go off-topic. I guess that's a downside of having the issue tracker open and accessible to all, but I don't think it outweighs the upside.

To address your points specifically:
- The title should be a clear description of the issue
- Workarounds are included in the comments
- The release where the issue was fixed or is planned to be fixed is in the panel on the right
- The latest status is covered by the issue being open or closed, and, if closed, by the "closed-xxx" label indicating the resolution
