### ISSUE TITLE
Unable to Add migrations EF core V1.0.2 Code first Migrations for .Net core V1.0.3

### ISSUE THREAD

**Issue by omkarachary** [dotnet/efcore#8116]
Hi Team,

I'm unable to create Migrations with EF Core 1.0.2 my dot net Core version is 1.0,3.

We recently migrated our project from .net core 1 to .Net core 1.0.3 as a part of this we also migrated EF Core Version.

The new upgradation from entity framework 1.0.1 to 1.0.2 is blocking us from creating the migrations.

Project.JSOn as attached

Figure 1: running migration command
 
![migrations](https://cloud.githubusercontent.com/assets/13204068/24874342/ead7e9e2-1e41-11e7-9234-0e5722065294.png)

Figure 2: Error.

![error](https://cloud.githubusercontent.com/assets/13204068/24874346/eedcc508-1e41-11e7-8ce8-f7d779fa6b43.png)

Tried upgrading the Tools version from “1.0.0-preview2-final" to all available versions. But no Luck. Received **command dotnet ef not found** error for versions after preview3final. And same error of other versions.

Even tried all the tool versions with EFcore 1.0.3 to all the possible tool versions Again no Luck

We want to use EF core 1.02 or newer version with .net core 1.0.3(Cannot Upgrade ).Please help.
Your help is most appreciated

**Comment by ajcvickers** [comment]
**EF Team Triage:** We are not planning to fix this issue because the  [.NET Core SDK 1.0.0](https://www.microsoft.com/net/download/core) no longer supports project.json or Visual Studio 2015. Everyone doing .NET Core development is encouraged to [migrate from project.json to csproj](https://docs.microsoft.com/dotnet/articles/core/migration/) and [Visual Studio 2017](https://www.visualstudio.com/downloads/).

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
