### ISSUE TITLE
Connection state is coming as closed in First itteration for MVC application, when selecting table data

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#8125]
Originally this issue was reported as #7129 . Opening here to discuss further:
----------------------------------
Excerpt from #7129 
Our IBM EntityFramework Core Provider is based MS EF Core 1.0.1 . We have written MVC EF Application using IBM EntityFramework Core provider by following below link:
https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db

It just selects data from table. When we run application we are getting error:
 AggregateException: An error occurred while writing to logger(s). (Invalid operation. The connection is closed.)
----------------------------------

Further analysis :
When we create MVC App log is enabled By Default:
```C#
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
....
...
}
```
If log is enabled, we have a call for :

```C#
   TryPrintConstant(object value, IndentedStringBuilder stringBuilder)
            {
              ....
                   **var querySqlGenerator = shaperCommandContext.QuerySqlGeneratorFactory();**
             ....
            }
```
In this call, ref for Db2QuerySqlGenerator gets created. where we have a code to fetch server info.

```C#
   Db2QuerySqlGenerator(......) 
            : base(.....)
        { 
           ......
            **Db2GetConnInfo.GetConnInfo((DB2Connection)_connection.DbConnection); 
        }
```
where actually exception occurs as Connection is not opened in MS layer.

When we compared SQLServer EF core provider we observed call for TryPrintConstant(...) is not happening. Bcoz of appsettings.jason configuration:
```json
 "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
```
If the similar entry we add for IBM, this issue is not reproducible:
```json
 "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information",
      "IBM": "Information"
    }
```
Adding LogLevel for IBM is not good, as end user can modify it any time. And application will start crashing.  

Our queries are:
- We generate query based on server flavor, hence we must require to have open connection to get server version info.  Is there a better way to have call for shaperCommandContext.QuerySqlGeneratorFactory() in TryPrintConstant(object value, IndentedStringBuilder stringBuilder) method ?
Our Intention is just to avoid opening connection in our layer. Bcoz this may end up performance hit. 

- What do we try to achieve from TryPrintConstant()..  we could see it does not form exactly same query which we run onto server to fetch result.

- What should be better approach to deal with these kind of scenario ?

**Comment by ajcvickers** [comment]
@archanasoni Here are several observations based on the information above:
* If some code is going to use a connection, then it must ensure that connection is opened and closed appropriately. You should have a class that inherits from RelationalConnection in your code. Use this to open and close the connection. It uses reference counting to handle the situation where the connection has already been opened, so your code should not need to worry about this.
* Don't call methods or read properties from classes in namespaces that end in `.Internal`. These are made available for application developers to use at their own risk. As a provider writer it would be very bad practice to use these since a simple point update in EF Core could cause your provider, and all your customer's applications, to stop working.
* I think you will run into many issues if you try to query the database to determine which "flavor" of SQL to generate. The approach taken by other providers and the approach we recommend is to have the application tell you the flavor when using OnConfiguring or AddDbContext. For example, in the SQL Server provider we have `UseRowNumberForPaging` which allows the application developer to configure EF to do paging in a way that is compatible with earlier versions of SQL Server.
* Consider targeting EF Core 1.1.1 with your provider, or, at this point even EF Core 2. If you target a 1.0 release, then please ensure that your provider works with the latest 1.1 release, since many more developers are using 1.1 releases than are using 1.0 releases.

**Comment by ajcvickers** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
