### ISSUE TITLE
Unable to cast object of type 'System.Func`2 using entity framework core. v1.1.1

### ISSUE THREAD

**Issue by irowbin** [dotnet/efcore#8182]
```javascript
var entry = _context.Entry(obj);
 foreach (var property in entry.OriginalValues.Properties)
{
var current = entry.CurrentValues.GetValue<object>( property.Name );  //error occurring this line
entry.Property(property.Name).IsModified = current != null;
}
```
![capture](https://cloud.githubusercontent.com/assets/13050078/25063090/720c0252-21fa-11e7-84eb-dc174b4e2024.PNG)

**Comment by ajcvickers** [comment]
@irowbin Not sure why the exception is being thrown when using `GetValue<object>`, but if you want to get the value in a non-generic way use `var current = entry.CurrentValues[property.Name];` instead.

**Comment by irowbin** [comment]
@ajcvickers it worked. Thanks

**Comment by bdebaere** [comment]
@ajcvickers The InvalidCastException is being thrown because `propertyBase.GetPropertyAccessors().CurrentValueGetter` in `InternalEntityEntry.cs` is a delegate representing a `Func<InternalEntityEntry, T>` where T is the type of the property being accessed. Since in most cases T will not be an object, an exception will be thrown.

You could replace 
```csharp
        public virtual TProperty GetCurrentValue<TProperty>(IPropertyBase propertyBase)
            => ((Func<InternalEntityEntry, TProperty>)propertyBase.GetPropertyAccessors().CurrentValueGetter)(this);
```

with

```csharp
        public virtual TProperty GetCurrentValue<TProperty>(IPropertyBase propertyBase)
            => (TProperty)propertyBase.GetPropertyAccessors().CurrentValueGetter.DynamicInvoke(this);
```

But I'm not sure this is worth doing, since as you already suggested you can use the non-generic method.
