### ISSUE TITLE
.Include() .Count() not using inner join for count

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#8201]
I'm using  Sqlserver 2008( old database, **without foreight key relation** )， and recently I try to using EntityFramework Core to access the database . 

```C#
public class A
{
    public int Id { get; set; } 
    public string Name { get; set; }
}

public class B
{
    public int Id { get; set; }
    public string Title { get; set; }
    public int AId{ get; set; } //  database may have a int value but may not actually exists
    public A A{ get; set; } 
}
```

`.Count()` and `.Select()' or 'Take()`  produce  very different sql when using `Include(x=>x.property)` .
`.Select()' or 'Take()`   will use `Inner Join` for navigation property, but `.Count()` will just igone them.
And that mean when I paging the data , I will get wrong `pagecount`

Does this be a bug, Or I had to use `int?` for  the model and force to use .Join() to produce Inner Join opration

### Further technical details
EF Core version:  1.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  windows 7 x64
IDE: Visual Studio 2015

**Comment by maumar** [comment]
Regardless of the database version, EF Core treats ```AId``` as a foreign key. The fact that its ```int``` and not ```int?``` makes it a required relationship and causes the INNER JOINs to be generated. If you want LEFT JOINs then you should use ```int?```

**Comment by John0King** [comment]
@maumar   I do want to use INNER JOIN but It not work with `.Count()` Method.
```C#
var query = db.Set<B>().Include(b=>b.A);
var list  = query.ToList(); // 2 row  : SELECT * FROM B INNER JOIN A on B.AId = A.Id 
var count = query.Count(); // 5 row : SELECT count(*) FROM B
···

**Comment by smitpatel** [comment]
@John0King - What you are seeing is optimized query specifically ignored include. When you do `Select` or `Skip` or `Take` then you are projecting out the `B` in final results. Due to eagerly loading via include, The navigation property `B.A` needs to be populated. When you do `Count` you are not projecting out `B` therefore there are no navigation property to load hence Inner Join is not required. More on ignored include here https://docs.microsoft.com/en-us/ef/core/querying/related-data#ignored-includes

>  I do want to use INNER JOIN but It not work with .Count() Method
Based on your model definition, there is a relationship between B & A. Due to existence of `B.AId` which matches convention rules of FK property name, EF will create a relationship with `B.AId` as a FK which points to `A.Id`. Since the type of `B.AId` is int (non-nullable) that means that every B will have FK set. Further since it is dependent end (containing FK property), it also imply that every value of `B.AId` will be present in `A.Id`. It implies that for every row in B there is 1 matching row in A. So count of rows in B is same is count of rows after inner join with A. Hence the optimized query will just count number of rows in B. (If for some reason the query needed Left outer join then we still need to perform the join to find the count because it may not be same as table row count).

In EF, (even with previous versions) existence of navigation property implied relationship between table. In you case, if database doesn't have foreign key constraint then you may need to remove navigation and work with FK property manually. More details on relationships in EF here https://docs.microsoft.com/en-us/ef/core/modeling/relationships

Hope that answers all your questions.

**Comment by John0King** [comment]
@smitpatel  That make sense for a strong relation database .
And my personal opinion is :   `optimized query ` should detect is the `.Include()` perform a INNER JOIN , if not then it's safe to ignore them ,  if true  then do not  ignore ,  even when use `.Select` but not take a value in navigation property.

**Comment by John0King** [comment]
:(   Current  I manually do a join like you mentioned 。
I had to say `Include` is the most easy way  to do  a Join  (and most stable api for doing a join in database today) 

> If you define a nullable FK property, but your database does not allow null in the column, then from database perspective you need Inner Join but EF will still generate a left outer join.

`nullable` tell EF to use LEFT OUTER JOIN  and     `ValueType` or  `required` tell  EF to use INNER JOIN .
That's the reason I use `int` instead of `int?` .  

> And my personal opinion is : optimized query should detect is the .Include() perform a INNER JOIN , if not then it's safe to ignore them , if true then do not ignore , even when use .Select but not take a value in navigation property.

I don't know how EF process those thing. And I think it will be better   if  it can detect  the FK  is  non-nullable and not to ignore them . 


I will close this issue,  but  may be you should  confirm that does it have same problem  when you use NO-SQL database like mongodb

**Comment by ajcvickers** [comment]
@John0King EF relies on a well-formed and consistent mapping from EF model to database model when using a relational database, as was explained by @smitpatel Any non-relational provider will have different requirements based on the semantics of that back-end.

**Comment by John0King** [comment]
@ajcvickers   there many developers argument about the `Foreign Key constraints` in https://stackoverflow.com/questions/83147/whats-wrong-with-foreign-keys

and I think  if we already config the relation in our code first model ,  let EF dealing with it should be possible ( delete, update , validate ).

**Comment by kevinding0218** [comment]
Instead of using like previous:
var query = db.Set<B>().Include(b=>b.A);
var list  = query.ToList(); // 2 row  : SELECT * FROM B INNER JOIN A on B.AId = A.Id 
var count = query.Count(); // return 5 : SELECT count(*) FROM B
----------------------------------------------------------------
here is what I found might work:
var Current_B = this._context.B.Single(b => b.Id == Id);
return await this._context.Entry(Current_B )
                .Collection(b=> b.A)
                .Query()
                .CountAsync(); 
----------------------------------------------------------------
But I am really looking forward that the B.Include.Count() should work in counting items in joined query and not do another tricky count from only table B in EF Core....

Hope that helps!

**Comment by John0King** [comment]
@kevinding0218  that does not work for my case. Previously I do not want use join is because EF 1.x.x is not stable for complex query. and 2.x is much better now .

and thanks anyway .

**Comment by ppcar007** [comment]
In E.F 2.2 there is a problem when using a EF Core GlobalFilter like softdelete.
If the table joined has a softdelete filter, the count does not generates the inner and only counts the primary table so the count returns a wrong result as is not taking into account the filtered records on the inner.
Sample : A -> 5 records, B -> 5 records matching (but one with isDeleted set by a global filter) Count returns 5 instead of 4 because Count only returns a query over A.
But the wuery itself correctly returns the records joinin with B where isdeleted=false

**Comment by lopesrichard** [comment]
Did you find any solution for this? I'm using ef core 3.1 and I'm having the same problem here

**Comment by K38104011** [comment]
This is my solution:
var count = query.Skip(0).Count();

**Comment by GadHao** [comment]
I found a solution, if:
1. You don’t want to write the `join` explicitly
2. Your database table has no real foreign keys 
2. You want to calculate the count after the `inner join`

```c#
var joinedCount = b.where(x => x.A.Id > 0).Count();
```

By accessing the navigation properties through a condition that will definitely be satisfied , you can get the correct count. But at the same time, you have to pay attention to possible performance issues. 

By the way, if it’s just to avoid handwriting `join`, I don’t think it is worth doing this. The reason I did this is because I used `EF + Automapper`, and can’t  get the correct count by `Include` , so I wrote `join` by hand, but Automapper’s ProjectTo raises the problem of repeated Join statements
