### ISSUE TITLE
How to Create a Migration for a Table Name Spelling Mistake?

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#8224]
I misspelled a table, let's call it ProductCat**ge**ories.  I've fixed the spelling mistake but I'm not sure how to create the migration.

1. I would like all data in ProductCatgeories to be inserted into ProductCategories
2. Or call my seeder class on migration up to load the values again.

### FK Failure
Currently my migration fails b/c my Products table has a FK on the ProductCategories table and there is no data in this new table.

### Documenation?
What's the general approach to this problem?  Is there documentation on this I can read about?

### Migration Up
In migration up, how can I get access to the current context?  If I can, this will allow we to instantiate my seeder class and seed my ProductCategories therefore allowing the FK to be created successfully.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: VS 2017

**Comment by ajcvickers** [comment]
@spottedmahn You should be able to do AddMigration for this. (See one of the [walk-throughs](https://docs.microsoft.com/en-us/ef/core/get-started/) for basic instructions on Migrations.) 

If the migration generated does not generate a rename (because both store and model names changed) then you should be able to edit the migration to make it a rename, which should mean that you don't need to move any data.
