### ISSUE TITLE
Check that reverse engineering index and column type are correct

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#8371]
* Create a database based on the DDL statements posted in a comment of #8322 and use it to create a database
* Reverse engineer the database to an EF model
* Check whether or not the index described in the original post is added to the model
* Check what the column type is for the Value column,

**Comment by lajones** [comment]
Using the [eav-db.sql.txt](https://github.com/aspnet/EntityFramework/files/972515/eav-db.sql.txt) file the DB tables etc can be created. 

There are a few ways of reverse engineering a code first model (note the bug refers to DBFirst, but also refers to OnModelCreating() and HasIndex() calls?). You can either use the "Add New Item|New ADO.Net Entity Data Model followed by selecting Code First from Database" i.e. the EF6.1.3 route; or you can install EFCore 1.1.1 and use `Scaffold-DbContext` in the PMC; or the latest EFCore, 1.1.2, and use `Scaffold-DbContext` in the PMC.

I mention EF6.1.3 because it is the only one which generates anything that looks like `ToSIC_EAV_Values2`. There are 3 foreign keys from `ToSIC_EAV_Values` with different dependent ends but each with the same principal end: `ChangeID` on `ToSIC_EAV_ChangeLog`. Because of the naming convention we used to use, the navigation properties for these (on `ToSIC_EAV_ChangeLog`) end up being called `ToSIC_EAV_Values`, `ToSIC_EAV_Values1` and `ToSIC_EAV_Values2`. But in EFCore these are now called `ToSicEavValuesChangeLogCreatedNavigation`, `ToSicEavValuesChangeLogDeletedNavigation` and `ToSicEavValuesChangeLogModifiedNavigation`.

Using the EF6 CodeFirst approach I do _not_ see any `HasIndex()` calls at all.  As mentioned `ToSIC_EAV_Values2` does exist, but the only uses of `ToSIC_EAV_Values2` are a) to define the HashSet which will represent the collection in the constructor of the generated entity class, `ToSIC_EAV_ChangeLog`, and b) to define the foreign key in the OnModelCreating() method of the generated DbContext class. But note that is just creating the FK - it is not a `HasIndex()` call.

For the other two EFCore approaches there is just 1 HasIndex() call on a completely different table; none that match the problem one from #8322.

I do not see anything that looks like the problem index from #8322 using any approach.

The column type of `Value` on the `ToSIC_EAV_Values` table in the DB is `nvarchar(max)`. The data type of the generated `Value` property on the `ToSIC_EAV_Values` class is always `string` (with no `StringLength` or other attribute which would indicate that it's length is limited).
