### ISSUE TITLE
[Question] - background threads resolving dbcontext

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#8450]
In the startup.cs for my ASP.NET Core 1.0 application, I Add my `DbContext` services in the usual mannor:    

```
 services.AddDbContext<GcDbContext>(options => options.UseSqlServer(connectionString));
```

I then start a `Hangfire` job server running within the same process, which runs scheduled jobs on thread pool threads.

These jobs, are classes, that are activated via the ApplicationServices `IServiceProvider`.

I am noticing that when injecting my `DbContext` into these jobs, where there are two jobs running concurrently, they seem to be raising exceptions, because they are attempting to use the same DbContext instance.

My question.. Is this expected behaviour for injecting from `ApplicationServices`, or should I be seeing a new instance (transient) of a DbContext being injected each time?

### Further technical details
EF Core version: 1.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by ajcvickers** [comment]
@dazinator That call to AddDbContext will add your context as a scoped service. This means that:
* You must ensure that a scope has been created before resolving the context. The context will be disposed when the scope is disposed.
* Since the same context instance will be returned anywhere in the scope and the context is not thread-safe, you must ensure that only one thread is running for a given scope at a given time.

You might want to look into registering your context as transient instead--there is an overload of AddDbContext for that.

**Comment by dazinator** [comment]
Thank you @ajcvickers - that's cleared things up for me.
