### ISSUE TITLE
Diagnostics: Consider porting DataReader disposing event to 1.x patch

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#8563]
Original issue: https://github.com/aspnet/EntityFramework/issues/7105
Original PR: https://github.com/aspnet/EntityFramework/pull/7106

Per comment at https://github.com/aspnet/EntityFramework/issues/7105#issuecomment-303387436, EF Profiler could take advantage of this functionality being incorporated in a 1.x release.

**Comment by divega** [comment]
cc @fitzchak

**Comment by ajcvickers** [comment]
There is a major overhaul to diagnostics in the 2.0 release which breaks from the 1.0/1.1 patterns. This means that the event names and payloads have all changed. Given this, we don't think there is a lot of value patching (or rather re-implementing) this in older versions. Instead, after 2.0 goes RTM we expect to encourage people to update to 2.0 if they need functionality that is based on diagnostics. While tools may continue to support 1.0/1.1 diagnostics, we don't expect that to continue for a long time because of the limited functionality in those releases and because the overhaul will make it difficult to support both 1.0/1.1 and 2.0. We recognize this is painful for now, but we're aiming to be setup for the long term by approaching it in this way.
