### ISSUE TITLE
Can't build latest in Visual Studio

### ISSUE THREAD

**Issue by pmiddleton** [dotnet/efcore#8589]
I rebased on top of the latest code and the upgrade to .Net Standard 1.4 & 2.0 has broken the build in Visual Studio for me.  I am receiving the following error

The version of Microsoft.NET.Sdk used by this project is insufficient to support this package.

I followed the advice in the error message and installed Visual Studio 15.3 preview, but using that did not fix the issue.  

KoreBuild has installed 2.0.0-preview2-006127 into my .dotnet directory, and everything builds from the command line.

Any help will be most appreciated.

Thanks

**Comment by smitpatel** [comment]
Try setting env var to preview2 SDK path
$env:MSBuildSdksPath="%userprofile%\.dotnet\x64\sdk\2.0.0-preview2-006127\Sdks"

**Comment by pmiddleton** [comment]
Thanks @smitpatel - I just tried this and I'm now looking at a bunch of different errors :)  

VS now seems to not be able to find all of System.ComponentModel in netstandard 2.0.  I'm getting erros like the type IListSource could not be found.

I am also seeing things like Attribute is defined in an assembly that is not referenced.  Add a reference to netstandard, version 2.0

Have you ever seen anything like this?  

I'm not seeing any issues reproted in the netstandard repo.  I might have just hit a VS bug.

**Comment by smitpatel** [comment]
Since a lot of pre-release components are involved it would be hard to find the root cause of issue (hence the solution too).

I am using VS 2017 RTM community edition so I am not exactly sure if following would work with newer version of VS but you can give it a shot.
1. Disable automatic package restore in VS. nuget is having some issues restoring packages recently.
2. Clear all nuget caches using VS.
3. Delete your %userprofile%\.dotnet folder.
4. git clean -xdf to clean your repo (commit your changes before this)
5. run `.\build.cmd /t:Compile` to restore packages and compile the solution on command line.
6. Set SDK path as above to point to the latest SDK downloaded in %userprofile%\.dotnet folder.
7. Open EFCore.sln

Let us know if you try this and if it works. 🤞

**Comment by pmiddleton** [comment]
@smitpatel Ignore my last post - I was missing a \ in the path.  Those errors I mentioned are gone. 

One one of my VMs I now am building correctly.  The other is complaining with 

error : Unexpected dependency 'Microsoft.NETCore.App' with no version number.  I'm going to blow that VM away and go with the one that is working.  

Yea bleeding edge :)

Thanks again for the help.

**Comment by divega** [comment]
@smitpatel FYI, I fixed your instructions above to make the `\` between `%userprofile%` and `.dotnet` visible :smile:
