### ISSUE TITLE
Query Filters - better (?) implementation

### ISSUE THREAD

**Issue by joshcomley** [dotnet/efcore#8663]
I don't want to do a pull request as I don't believe the code is necessarily up to the bar, but also this isn't a bug.

In your latest release you have query filters, but I encourage you to look at my own implementation from last year at query filters (although updated to a recent version):
https://github.com/joshcomley/EntityFramework

Specific commit:
https://github.com/joshcomley/EntityFramework/commit/0a770921a7eb3a6a41d1a800870425ea47d14ade

The implementation is much more flexible in that it allows cached, per-request filters.

There is an `IQueryFilter` that you can implement:

	using System;
	using System.Linq.Expressions;
	using JetBrains.Annotations;

	namespace Microsoft.EntityFrameworkCore.Query
	{
		/// <summary>
		///     An entity filter
		/// </summary>
		/// <typeparam name="T"></typeparam>
		public interface IQueryFilter<T>
		{
			/// <summary>
			/// The filter expression
			/// </summary>
			/// <returns></returns>
			Expression<Func<T, bool>> Filter([NotNull]EntityFilterContext context);
		}
	}

The `EntityFilterContext` is as follows:

	using System;
	using JetBrains.Annotations;

	namespace Microsoft.EntityFrameworkCore.Query
	{
		/// <summary>
		///     The context of an entity filter
		/// </summary>
		public class EntityFilterContext
		{
			/// <summary>
			///     The service provider to use for this filter
			/// </summary>
			public virtual IServiceProvider ServiceProvider { get; }

			/// <summary>
			/// Initializes a new instance of the entity filter context
			/// </summary>
			/// <param name="serviceProvider"></param>
			public EntityFilterContext([NotNull]IServiceProvider serviceProvider)
			{
				ServiceProvider = serviceProvider;
			}
		}
	}

In your `DbContext`:

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder
                .UseServiceProviderForFilters(_serviceProvider);

            builder
                .Entity<ApplicationUser>()
                .HasFilter<ApplicationUserFilter>();
        }

It is also possible to provide lambda expressions etc. instead of a class, but with the class I can inject whatever I like into the constructor per-request, resolved using the service provider specified above.

In my implementation, the filter part of the query is cached separately and correctly parameterised, which means that although the filters are generated per-request and context driven, identical queries can still use the query cache.

Any thoughts, EF team?

**Comment by joshcomley** [comment]
I should add my implementation only works for SQL Server, so it was limited in its scope but flexible in its approach to contexts etc.

**Comment by ajcvickers** [comment]
@joshcomley Thanks for providing this information/feedback. We discussed this and decided:
- We are fully behind the idea of an ecosystem of packages that add functionality to EF Core. If there are different implementations of query filters available that have different characteristics, that's a good thing for the developer community.
- We welcome good pull requests that help make EF Core better. Along those lines, you might consider two different types of PRs for this kind of thing:
  - We really appreciate PRs that add hooks/extensibility points, so that external code can better implement additions like this. It's often hard to come up with all the right hooks without building the things that need them, so people doing add-on packages are a great source of information as to which hooks to add.
  - We would also consider PRs that add more functionality to the built-in feature.
