### ISSUE TITLE
Sqlite: dbContext.Update() and dbContext.Attact() get information from database, not from POCO entity

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#9040]
I have a parent and a child class.

```
Parent
{
    long IDParent;
    long IdType;
}

Child
{
    long IDParent;
    long IdType;
}
```

The primary key of the parent is an autonumeric and the primary key of the child is not an autonumeric, it is set the same key than the parent.

The initial values in the database, are: myParent.IdType = 1; myCHild.IdType = 2 and I wanted to update the data in the database, I am trying this code:

```
Child myChildUpdated = new Child();
myChild.IDParent = 4;
myChild.dType = 3;

Parent myParentUpdate = new Parent();
myParent.IDParent = 4;
myParent.IDType = 6;

myParent.Child = myChild;
myChild.Parent = myParent;

Entities myDbContext = new Entities();
myDbContext.Update(myParent);
```

At this time, myParent.IdType = 1 and myChild.IdType = 3. So myParent get the data from database but the child not, so the data is not consistent.
The state of both entities are "modified".

I have also try myDbContext.Attach(myParent) but it has the same behavior, the myParent get the information of the database and the child not. In this case the state of both are unchanged.

At the end I have tried myDbContext.Entry(myParent).State = State.Modified. In this case myParent has the expected value, 6, not the value from database. But in this case the child is not add to the dbContext, I have to add it manually.

I guess that the expected behavior of dbContext.Update() and dbContext.Attached() it is to add entities to the context keeping the information of the entities, not going to the database to get the data, because I want to save a trip to the database, if not, I would send a query to the database and I would need these methods.

Anyway, as I commented, the data is not consistent because the parent has the data from database and the child keeps its data.

What I want to do is to add the parent and the child to the dbContext keeping their data in modified state to update the data that there are in the database.

Thanks.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a **complete code listing** that we can run to reproduce the issue.
Alternatively, you can provide a **project/solution** that we can run.
Also, please provider the **product and provider versions** you are using.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ComptonAlvaro** [comment]
At the end the problem was mine, I had a navigation propierty that isn't consistent with the ID, so in the update() EF set the ID with the ID that there is in the navigation property.

So the behavior is correct and it was my problem.

Thanks.
