### ISSUE TITLE
EF Core 1.1.2 Foreign Key Annotation for String Type doesn't generate Cascade delete

### ISSUE THREAD

**Issue by robinkedia** [dotnet/efcore#9043]
Describe what is not working as expected.

The following code doesn't produce cascade delete syntax during migration.
**

> Missing for String type. Works for Int
> .OnDelete(DeleteBehavior.Cascade);

**

### Steps to reproduce
Create following model classes and perform migrations

```c#

public class CodeTerminationFlag 
    {
        [Key]
        [Required]
        [StringLength(2)]
        public string TerminationFlagId { get; set; }
        
        [Required]
        [StringLength(25)]
        public string Name { get; set; }

        [StringLength(200)]
        public string Notes { get; set; }
    }
public class Activity
    {
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ActivityId { get; set; 

        public CodeTerminationFlag CodeTerminationFlag { get; set; }
       
        [ForeignKey("CodeTerminationFlag")]
        public string TerminationFlagId { get; set; }

        [StringLength(250)]
        public string Notes { get; set; }

    }

**Output**

  b.HasOne("API.Data.Models.CodeTerminationFlag", "CodeTerminationFlag")
                        .WithMany()
                        .HasForeignKey("TerminationFlagId");
```

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
MAC (VS Code)

**Comment by ajcvickers** [comment]
Since string is a nullable type, it means the TerminationFlagId is nullable, which makes the relationship optional by default. Cascade delete is only on by convention for required relationships. To get cascade delete in this case, either make the relationship/FK required, or explicitly configure the cascade delete. See the docs here for more details: https://docs.microsoft.com/en-us/ef/core/modeling/relationships
