### ISSUE TITLE
Where is OriginalValue from ReferenceEntry?

### ISSUE THREAD

**Issue by goenning** [dotnet/efcore#9050]
Hi,

I can see that `PropertyEntry` has both `OriginalValue` and `CurrentValue`, but what about `ReferenceEntry`? It seems it's missing the `OriginalValue`. I'm trying to audit all changes from EF, but I need the full reference to the `OriginalValue`, not just the Id that is provided by `PropertyEntry.OriginalValue`. 

Is this property missing or it's like this by design?

I'm using these methods:

- `entry.Property("CurrencyId") to return PropertyEntry`
- `entry.Reference("Currency") to return ReferenceEntry`

Thanks.

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE:. Visual Studio 2017

**Comment by ajcvickers** [comment]
@goenning Original values are the values that were present in the database when the entity was queried. So for a relationship, the FK property will have an original value. Navigation properties are synthesized from the FK value rather than being directly mapped to anything in the database. This means that navigation properties (both reference and collections) do not have original values.
