### ISSUE TITLE
Updating from EF Core 2 Preview 1 to EF Core 2 Preview 2 issue

### ISSUE THREAD

**Issue by jmjcoelho** [dotnet/efcore#9060]
Hi

  I'm trying to update my project from EF Core 2 Preview 1 to  EF Core 2 Preview 2 but when I do so I get the following exception:

Exception message: Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.EntityFrameworkCore.SqlServer 2.0.0-preview2-final'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	

Can anyone please tell me what do I need to do to make it work?

Best Regards
JC

**Comment by divega** [comment]
@jmjcoelho I saw the same issue on one of my machines before I installed the .NET Core 2.0 Preview 2 SDK from https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview2-download.md and the latest preview of Visual Studio 2017 (15.3 Preview 3) from https://www.visualstudio.com/vs/preview/.

There are other workarounds mentioned at https://stackoverflow.com/questions/44394243/entity-framework-core-2-0-on-net-4-6-1, but those were not necessary for me, I assume because I got a very recent version of NuGet as part of either the SDK or Visual Studio.

cc @bricelam

**Comment by jmjcoelho** [comment]
I tried all the mentioned workarounds and none worked for me, the only one I haven't tried was to install the latest latest preview of Visual Studio 2017 (15.3 Preview 3), I'm going to do that and try again.

 Many thanks
JC

**Comment by ajcvickers** [comment]
@jmjcoelho While there may other workarounds/hacks, the only version of Visual Studio that is intended to work is 15.3 Preview 3. Also, the .NET Core 2.0 Preview 2 SDK will need to be installed regardless of using command line or VS.
