### ISSUE TITLE
EF Core 2.0.0-preview3-26077 Scaffolding with error exception

### ISSUE THREAD

**Issue by sonphnt** [dotnet/efcore#9065]
Hi Everyone,

Do you know why scaffolding raises error exception following:

Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I am using VS 2017 Preview 3

Thanks

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
Also, which type of scaffolding are you using? Controller scaffolding for MVC or reverse engineering from a database?
Also, can you post versions of .NET Core, etc.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by sonphnt** [comment]
Hi @ajcvickers 

I am using Visual Studio 2017 15.3 26510 Preview. 
Create a empty project with .Net core 2.0. Microsoft.AspNetCore.All (2.0.0-preview1-final) installed by default.

Trying to Install these following packages:
- Microsoft.EntityFrameworkCore 2.0.0-preview3-26077
- Microsoft.EntityFrameworkCore.Design 2.0.0-preview3-26077
- Microsoft.EntityFrameworkCore.Relational 2.0.0-preview3-26077
- Microsoft.EntityFrameworkCore.SqlServer 2.0.0-preview3-26077
- Microsoft.EntityFrameworkCore.Tools 2.0.0-preview3-26077

And then trying to scaffold with this command:
Scaffold-DbContext "MySQLConnectionString" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Entities -Force

Then got this in PackageManagerConsole:
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Thanks

**Comment by smitpatel** [comment]
You cannot mix version of ASP.NET packages. It is not supported scenario. If you are upgrading EFCore packages to 2.0.0-preview3-* then also upgrade `Microsoft.AspNetCore.All` to same version number. In this case, `System.Diagnostics.DiagnosticSource` is dependency for various packages and due to version mismatch you are ending up with different versions of same assembly required.

**Comment by ajcvickers** [comment]
Also, to use the nightly builds on .NET Core you need to install the latest .NET CLI from https://github.com/dotnet/cli/tree/release/2.0.0#installers-and-binaries.
