### ISSUE TITLE
Query: GTE AND LTE not translated to BETWEEN

### ISSUE THREAD

**Issue by HClausing** [dotnet/efcore#9081]
Good Afternoon for all.

I'm working on generate expressions to .Where() method dynamically. It Works fine, but the SQL Generated string is a bit more complex than expected.

Example: filtering between two dates and some string field:

Generated SQL by EfCore:

```
    WHERE ((CASE
        WHEN [f].[DataEscrituracao] >= '2014-01-01T00:00:00.000'
        THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
    END & CASE
        WHEN [f].[DataEscrituracao] <= '2017-12-31T23:59:59.000'
        THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
    END) & CASE
        WHEN EXISTS (
            SELECT 1
            FROM [EfFiscal].[DocumentosFiscaisAnaliticos] AS [s1]
            WHERE ([s1].[CFOP_FK] = N'1556') AND ([f].[ID] = [s1].[Documento_FK]))
        THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
    END) = 1
```
Is there any way do generate a more common SQL like this? 👍 
`
WHERE CAST (DOC.DataEscrituracao AS DATE) BETWEEN '2014-01-01T00:00:00.000' AND '2017-12-31T23:59:59.000' AND AN.CFOP_FK = '1556'`

I see that EFCore Always comparing expressions as binary 0 or 1.

What I'm doing wrong?

P.S.: On a large amount of rows, it's slower.

Thanks

### Further technical details
EF Core version: **1.2.0-preview1-23326**
Database Provider: **Microsoft.EntityFrameworkCore.SqlServer**
Operating system: **Microsoft Windows 10**
IDE: **Visual Studio 2015**

**Comment by HClausing** [comment]
Hi!

The between operator I didn't see as a problem, but "CASE WHEN" appears to be more complex has the query could be.

Our dynamic expression tree (datagrid control) builds functions converting Between (on view / viewmodel) to ((BiggerThan) AND (LowerThan)) automatically.

The expressions is something like this:

Me.Repository.DbContext.Set(of T).Include(optional).Where(generated from data grid expression constructor).OrderBy(optional).ToListAsync  (vb.net)

In this case, my really doubt is about "CASE WHEN" generated on WHERE clause, comparing argument on binary form (0 or 1) instead of normal way "Column" = "value".

I believe we could disconsider "BETWEEN" on this example. 

Thanks

**Comment by smitpatel** [comment]
> Our dynamic expression tree (datagrid control) builds functions converting Between (on view / viewmodel) to ((BiggerThan) AND (LowerThan)) automatically.

`BiggerThan AND LowerThan` will be converted in above way only unless EFCore explicitly tries to look for such pattern and convert it to Between.

Also, since you are using very old version, I tried query `db.Blogs.Where(b => b.Id >= 1 && b.Id <= 3).ToList();`
Generated SQL
```SQL
SELECT [b].[Id]
FROM [Blogs] AS [b]
WHERE ([b].[Id] >= 1) AND ([b].[Id] <= 3)
```
So we no longer generate CASE WHEN.

A quick search on the topic brought me on this blog http://www.sqlservercentral.com/blogs/technobabble-by-klee-from-kleegeek/2013/03/29/is-between-faster-than-gte-and-lte/

Looks like Between is just short hand for GTE/LTE & there is not much perf differences.

Feel free to re-open the issue if you are seeing major perf benefit by using BETWEEN over `<= && >=`

**Comment by HClausing** [comment]
Ok, Thanks.

PS: 'BETWEEN' was not the problem of this thread. We will update EFCore version right now.
