### ISSUE TITLE
EF Core 2: One to One  Required Not Being Enforced (also Navigation no longer needed?)

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#9152]
This is a two part issue because the first part is just a quesiton and the second is a possible issue (unless its a question called "what did I do wrong this time?" )

Project.assets says I have 2.0.0-rtm-26209

I'm seeing that with EF Core 2.0, I can define a one to one relationship without having a navigation property in the dependent entity. (I like that but it's different than 1.0 and I can't find any reference to this change).

Here are two entity types and a context
```
public class Samurai {
    public int Id { get; set; }
    public string Name { get; set; }
    public Entrance Entrance { get; set; }
  }

public class Entrance {
    public int Id { get; set; }
    public string SceneName { get; set; }
    public int SamuraiId { get; set; }
  }
 public class SamuraiContext : DbContext {
    public SamuraiContext (DbContextOptions<SamuraiContext> options) : base (options) {}
    public DbSet<Samurai> Samurais { get; set; }
  }
```
Note there is no navigation from Entrance to Samurai and no mapping. 

DbSchema shows that it groks the PK/FK relationship between Samurai and Entrance. Entrance.SamuraiId is unique so it's not a one to many in the DB.

![image](https://user-images.githubusercontent.com/5007120/28084665-517a4256-6647-11e7-98d9-e6ec72334e70.png)

**Describe what is not working as expected.**
In EF Core 1.0 a navigation property was required. Now it doesn't seem to be. It's using the FK happily to figure it out.

I prefer it this way and will cheer the change, but want to be sure that this is expected behavior with  2.0. 

**### PART 2**

If I modify Samurai to make Entrance required
```
public class Samurai {
    public int Id { get; set; }
    public string Name { get; set; }
    [Required]public Entrance Entrance { get; set; }
  }
```

Required is _not_ honored with inmemory or sql server. 

I can simply create a new samurai, add to context, and call save changes. No errors. I expect it to throw. Instead,  assertion that savechanges returns 1 (or others that can requiry the data) passes and with the sqldb test, it's there in the database.

I then added the navigation property into the dependent class:

```
public class Entrance {
    public int Id { get; set; }
    public string SceneName { get; set; }
    public int SamuraiId { get; set; }
    public Samurai Samurai {get;set;}
  }
```

And explicitly configured the relationship with IsRequired:

```
modelBuilder.Entity<Entrance>().HasOne(e=>e.Samurai)
  .WithOne(s=>s.Entrance).IsRequired();
```
 But the insert (inmemory and with database) continues to work when I don't create an entrance on samurai.

Here are my inmemory and db tests in case you see something I have been overlooking all this time:
```
 public void CanInsertSamuraiWithNoEntrance_SqlDB () {
        var optionsBuilder = new DbContextOptionsBuilder<SamuraiContext> ();
        optionsBuilder.UseSqlServer (
          "Server=localhost;Database=SamuraiTest;User ID=sa;Password=Passw0rd;MultipleActiveResultSets=true;Connect Timeout=30;");

        var context = new SamuraiContext (optionsBuilder.Options);
        context.Database.EnsureDeleted ();
        context.Database.EnsureCreated ();
        context.Samurais.Add (new Samurai { Name = "JulieSan" });
        Assert.Equal (1, context.SaveChanges ());
      }
public void CanInsertSamuraiWithNoEntrance_InMemory()
    {
      var optionsBuilder = new DbContextOptionsBuilder<SamuraiContext>();
      optionsBuilder.UseInMemoryDatabase("CanInsertSamuraiWithNoEntrance");

      var context = new SamuraiContext(optionsBuilder.Options);

      context.Samurais.Add(new Samurai { Name = "JulieSan" });
      context.SaveChanges();
      Assert.Equal("JulieSan", context.Samurais.FirstOrDefaultAsync().Result.Name);
    }
```
Finally, I set EF Core to preview3-* and preview2-final with the final state of these tests (navigation property in Entrance and fluent config) but the results were the same.

### Further technical details
EF Core version: 2.0.0-rtm-26209 AND 2.0.0-preview3-* AND preview2-final
Database Provider: InMemory and Microsoft.EntityFrameworkCore.SqlServer
Operating system: macOS
IDE: Visual Studio Code

**Comment by ajcvickers** [comment]
Per part 1, I don't think this behavior has changed and I just ran the code on 1.1.2 to confirm. The relationship is 1:1 instead of 1:* because a foreign key property is found by convention and this lets EF know the dependent end. Once the dependent end is known, it can also be inferred that this is 1:1 because the navigation property on the principal side is a reference not a collection.

However, there was an issue in earlier versions where Migrations would not create the FK as unique even though it was a 1:1 relationship, so that's probably what has changed in 2.0. The EF behavior for that model should not have changed between 1.1 and 2.0.

Per part 2, when a relationship is made "Required" it means that a dependent entity cannot exist without an associated principal entity. This is done my making the FK non-nullable--i.e. the FK value must reference some principal entity. 

However, it says nothing about the principal entity existing without the dependent. This is always possible because there isn't really any way to restrict it when working with partially loaded graphs. (This was the same with the old stack, although there were some situations where the state manager would, almost arbitrarily, stop certain things happening.) With stronger semantics applied to aggregates that limit partially loading of graphs it may be possible to enforce such a restriction in the future, but that isn't done yet.

**Comment by smitpatel** [comment]
To extend bit more on part1 #4498 which allowed 1-to-1 with single ref navigation. Though it was done in 1.0-rc2 release so nothing should have changed from 1.0 to 2.0. I saw same behavior as @ajcvickers  in 1.1.1 release. I couldn't verify 1.0 behavior due to legacy tooling & VS it used.

**Comment by julielerman** [comment]
thanks guys. I started out thinking that the FK behavior was normal (FK is there so that's it) then nothing I read (i read a lot) seemed to confirm that.  I also hadn't tested this since 1.0. But then I double checked against the docs  (https://docs.microsoft.com/en-us/ef/core/modeling/relationships) and they also show an FK property with a navigation prop and still say "navigation on both ends". That now clears up that I wasnt really going crazy. Maybe my task is to do a PR on the docs. :) (Happy to)

Re required: as you inferred, my goal was to have it be a pure 1:1 where the navigation is required on both ends.  1:1 required on both ends was definitely a mapping in EF.Old. I don't trust my memory but I do trust the book that Rowan & I wrote. ;)

![image](https://user-images.githubusercontent.com/5007120/28088359-6e1f82ca-6653-11e7-8e28-dd51f28df76a.png)

For now I'm ok with "that's just not how it works in EF Core, it's up to you to write the logic" and that's what I will relay But I think that type of mapping should work (that principal is required ..i.e. no ophans .. is clear, but adding in a mapping and EF validation that dependent is required) and will be happy to create a more focused issue to get it in the queue. Otherwise, I can change the title of this one to something more focused on that request.

**Comment by julielerman** [comment]
p.s. re relaying this, I think you two may get stuck with tech reviewing my article if I can ever get it finished! :)

**Comment by ajcvickers** [comment]
@julielerman That text seems to be referring to the EF _validation_ feature, which EF Core doesn't have, mainly because it is usually better handled by other layers/libraries. If you configure something else to do validation and put the Required attribute on a navigation property, then you'll probably get the same behavior as the old stack.

**Comment by julielerman** [comment]
Ahh ok. Very fair. This is a continual case of "ef core is not ef 6"  Thanks for your patience. I am a canary in the coal mine. So bottom line is maybe some clarification in the docs will stop others from going own this same rabbit hole and trying to drag you down it with me.
