### ISSUE TITLE
Might have overlooked this but...

### ISSUE THREAD

**Issue by nteague22** [dotnet/efcore#9160]
I can no longer simply build a query and call ToString() to get prepared SQL.

I tried in the console dump, the debugger, using breakpoints in VS Code (I do not run using the Preview of 2017 right now)

just something as simple as :
```C#
using(var db = new ContextInstance()) {

  IQueryable<Product> query = db.Products;
  
  Console.WriteLine(query.ToString());

}
```

it only gives the [Microsoft.EntityFrameworkCore.Query.Internal.EntityQuery[Product]] now

**Comment by ajcvickers** [comment]
@nteague22 In EF Core, calling ToString on the query has never returned the query string. There are a couple of problems with doing this:
* The architecture of EF Core makes it problematic because of the way queries are built and cached
* It can be expensive to generate the query string and since ToString is called automatically by the VS debugger (and other tools) it can cause performance issues in the debugger. This has been a real issue for VS with EF6 and earlier.

In EF Core, the recommended way to get SQL is to use logging--see https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging

**Comment by nteague22** [comment]
Sorry on the late reply, I had not noticed this -- but thanks for the help!
