### ISSUE TITLE
Async Queryable Extension methods should fallback to Synchronous methods, Again

### ISSUE THREAD

**Issue by 303248153** [dotnet/efcore#9179]
Refer to https://github.com/aspnet/EntityFramework/pull/6189
I think it's a serious bug, consider this code

``` csharp
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleAppCore
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = new List<int>();
            var b = a.AsQueryable().ToListAsync().Result;
        }
    }
}
```

It should just work but actually it throws:

``` text
Unhandled Exception: System.InvalidOperationException: The source IQueryable doe
sn't implement IAsyncEnumerable<System.Int32>. Only sources that implement IAsyn
cEnumerable can be used for Entity Framework asynchronous operations.
   at Microsoft.EntityFrameworkCore.Extensions.Internal.QueryableExtensions.AsAs
yncEnumerable[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsy
nc[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ConsoleAppCore.Program.Main(String[] args) in C:\Users\admin\Documents\Vis
ual Studio 2017\Projects\ConsoleAppCore\ConsoleAppCore\Program.cs:line 13
```

That mean any code use ToListAsync is strongly coupled with Entity Framework, which is very not good.
My EFCore version is 2.0.0-preview2-final.

**Comment by ajcvickers** [comment]
Note for triage: see #6085

**Comment by divega** [comment]
*EF Triage*: We are torn about this one. On one hand we understand it may be better to not throw and fall back to sync (similar to System.Data.Common), but on the other hand we are concerned that the fall back would happen without making the user aware that it happened. There is no good way to hook up our warning system into these async methods (precisely if the source is not an EF Core query).

We will keep this in the backlog and monitor for user feedback and we might also consider a PR.

A couple of alternative to this:

- The user can write their own version of the method that falls back to our implementation or to sync
- The user can create fake query objects that implement some of the EF Core interfaces so that the method actually succeeds (we could consider something to make this easier).

**Comment by nfaugout** [comment]
I just wanted to add a personal experience related to this Issue, using EF standard and now migrating to EF Core.

We have a home made framework that simplifies the construction of a Linq query, based on the querystring in the URL. Basically we transform something like "&name=like,nico&orderby=lastName,asc&paging=0,10&..." into a (big) predicate on an IQueryable<T>

What we liked when we were synchronous (ie using .ToList( )), is that against a SQL database or against a C# in memory store, we could use the same predicates.

In production (SQL database), it was executed by EF. In our unit tests, it was executed by, I would say "pure C#", and it worked well.

Now that we want to go async and use .ToListAsync( ), we face the same error in our tests, because the all query is not handled by EF.

Yesterday we found a workaround that I want to share : instead of using plain C# in-memory store, we switched to EF InMemoryDatabase, and the error disapeared.

So we now have a solution if we want to use EF as an async enumerator for queries.

And I would suggest that if you want to enumerate plain C# collection, you should not use EF anymore. It was practical by the past, but at that time already a wrong approach.

**Comment by 303248153** [comment]
IMO, `ToListAsync` should be a part of standard library, and EFCore provide an implementation.
But for now `ToListAsync` is a part of EFCore, and can be used only with EFCore, I think that's a design mistake.
Using EFCore 's InMemoryDatabase may resolve this problem but I just want to keep my unit tests slim. :(

**Comment by popcatalin81** [comment]
This issue is preventing me to implement async in my Localization query rewriter without tight coupling with EF core. [Issue](https://github.com/iQuarc/DataLocalization/issues/4)

**Comment by maurei** [comment]
Running into this too.

**Comment by ajcvickers** [comment]
Closing as external since `IAsyncEnumerable` is now part of the BCL.
