### ISSUE TITLE
 about Modify and add EntityFramework

### ISSUE THREAD

**Issue by hjj5258** [dotnet/efcore#9208]
How do you change the structure of the table? Is it new or modified?

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the information requested in the new issue template. Can you please provide this information?

```
Exception message:
Stack trace:
```

> ### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

> ### Further technical details
EF Core version: (found in project.json or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2015)


BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by bricelam** [comment]
@hjj5258 You may want to read the [tutorial on Migrations](https://docs.microsoft.com/aspnet/core/data/ef-mvc/migrations).

**Comment by hjj5258** [comment]
@bricelam Thank you for your help.

**Comment by hjj5258** [comment]
@bricelam But the principle of migration is not clear

**Comment by hjj5258** [comment]
@ajcvickers Thank you for your offer and help,This question is about the principle of database migration, but I don't know where the code is and how it works.
Thank you for your reply!

**Comment by hjj5258** [comment]
@ajcvickers @bricelam How does the EF compare the old and the new two models to determine whether it is new or modified?

**Comment by ajcvickers** [comment]
@hjj5258 The [MigrationsModelDiffer](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs) is responsible for doing that. If this doesn't answer your question, then can you be more specific about you are asking? You might also try asking questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/entity-framework-core).
