### ISSUE TITLE
Sqlite: DatabaseGenerated.Identity is ignored when on non-PK

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#9218]
```C#
    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTime Inserted { get; set; }
    }
```
Creates migration
```
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateTable(
        name: "Blogs",
        columns: table => new
        {
            BlogId = table.Column<int>(type: "INTEGER", nullable: false)
                .Annotation("Sqlite:Autoincrement", true),
            Inserted = table.Column<DateTime>(type: "TEXT", nullable: false),
            Url = table.Column<string>(type: "TEXT", nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_Blogs", x => x.BlogId);
        });
}
```
https://github.com/aspnet/Release/issues/189

**Comment by smitpatel** [comment]
Same for DatabaseGenerated.Computed

**Comment by smitpatel** [comment]
Fluent API configuration has no effect either.

**Comment by smitpatel** [comment]
This seems like issue overall and not just SQLite
Using SQL server
```
public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime Inserted { get; set; }
}
```
Still assigns identity to BlogId and no value generation to Inserted in migrations. 
cc: @AndriySvyryd  @ajcvickers

**Comment by ajcvickers** [comment]
@smitpatel Are the properties marked as ValueGenerated.OnAdd in the model?

**Comment by smitpatel** [comment]
@ajcvickers - Yes they are.

**Comment by ajcvickers** [comment]
That's really all those attributes mean. (Yes, the name is confusing, but it always has been--for example, even in EF 4.1 you could put "Identity" on a GUID property and it would work, but it would not be an "Identity" column. And for other providers there really isn't "Identity" columns at all.

Normally you would also do DefaultValueSql or ComputedColumnSql as well--but you don't have to because if you're mapping to an existing database all you need to tell the runtime is that the database will generate values somehow, not how.

**Comment by smitpatel** [comment]
Docs bug then 😀

**Comment by ajcvickers** [comment]
Closing this but will track the doc issue as part of https://github.com/aspnet/Release/issues/189
