### ISSUE TITLE
RevEng: Redundant ValueGeneratedNever for non-integer PK property

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#9221]
Reproes for SqlServer and SQLite

**Comment by bricelam** [comment]
This is turning into a can of worms. In order to know if we need to `.ValueGeneratedNever()`, we need to know [here](https://github.com/aspnet/EntityFrameworkCore/blob/2.1.0-preview2-final/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L489) if the generated values are temporary. To do that, we need the provider's `IValueGeneratorSelector`, and SQL Server's requires an `ISqlServerConnection` for sequences. 😬

Let's revisit this in a later release. \*punt\* 🏈

**Comment by ajcvickers** [comment]
Plan for 3.0: Never scaffold ValueGeneratedNever for non-integer types since, even if a value generator exists, as long as application always specifies key values, then it will never be used.
