### ISSUE TITLE
Recent change in Microsoft.SqlServer.Types install.ps1 requires committing DLLs to source control

### ISSUE THREAD

**Issue by stijnherreman** [dotnet/efcore#9272]
The Microsoft.SqlServer.Types packages released earlier this year have a change in the install.ps1 script compared to older versions. `$cppLinkx86 = $folderx86.ProjectItems.AddFromFile($cppBinaryPathx86)` and its variations became `$sqlLinkx86 = $folderx86.ProjectItems.AddFromFileCopy($sqlBinaryPathx86)`.

Previously, the .csproj file contained this:

```xml
    <Content Include="..\packages\Microsoft.SqlServer.Types.11.0.2\nativeBinaries\x64\msvcr100.dll">
      <Link>SqlServerTypes\x64\msvcr100.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\packages\Microsoft.SqlServer.Types.11.0.2\nativeBinaries\x64\SqlServerSpatial110.dll">
      <Link>SqlServerTypes\x64\SqlServerSpatial110.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\packages\Microsoft.SqlServer.Types.11.0.2\nativeBinaries\x86\msvcr100.dll">
      <Link>SqlServerTypes\x86\msvcr100.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\packages\Microsoft.SqlServer.Types.11.0.2\nativeBinaries\x86\SqlServerSpatial110.dll">
      <Link>SqlServerTypes\x86\SqlServerSpatial110.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

After the change, the .csproj file contains this:

```xml
    <Content Include="SqlServerTypes\x64\msvcr100.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x64\SqlServerSpatial120.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x86\msvcr100.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x86\SqlServerSpatial120.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

Due to this change, you either need to manually fix the .csproj file to refer to the packages directory, or you need to commit these DLLs to source control. Not doing so results in a non-building project for new clones, because the DLLs are missing.

Why was this change made? Is it possible to do new releases for each of these versions, with the change to install.ps1 reverted?

*Note: I'm reporting this here because EntityFramework is listed as one of the package owners.*

**Comment by divega** [comment]
@stijnherreman the EF team no longer maintains this package. It is now maintained by a SQL Server team. 

I have forwarded the link to this issue to the owners of the package, but I would suggest that you do the same so that they can have your contact information and follow up with you.

You can do this by going to https://www.nuget.org/packages/Microsoft.SqlServer.Types and clicking 
on the Contact Owners link on the left of the page.

**Comment by stijnherreman** [comment]
For the record, I've used the Contact Owners link before creating a ticket here, and again after the suggestion in https://github.com/aspnet/EntityFrameworkCore/issues/9272#issuecomment-321759257 to do so. I've yet to receive a response.

**Comment by dmitryshunkov** [comment]
@stijnherreman as a workaround, you can use for new clones following command in Package manager console to force run Install.ps1:
`Update-Package -Reinstall -Id Microsoft.SqlServer.Types`

Problem still persist for non Visual Studio build though (for example with MSBuild, as nuget CLI doesn't call Install.ps1 scripts because this feature is deprecated for nuget.exe).
