### ISSUE TITLE
Discriminator column is created not indexable in SQL Server

### ISSUE THREAD

**Issue by SergeyBarskiy** [dotnet/efcore#9298]
Describe what is not working as expected.
Discriminator column is created as varchar(max) when inheritance is used

### Steps to reproduce
Create two classes that where one extends to anotehr as models for DbContext.  Create a database.  Discriminator column is created as varchar(max), which makes it non-indexable in SQL Server.  Should really be varchar(511) where 511 is max value for class name supported by c# compiler.
https://stackoverflow.com/questions/186523/what-is-the-maximum-length-of-a-c-cli-identifier

This will enable us to use indexes with discriminator columns.

public class Person
    {

        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

    public class Student: Person
    {
        public string College { get; set; }
    }

### Further technical details
EF Core version: 2.0 preview 2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017)

**Comment by smitpatel** [comment]
Looking at stackoverflow question, there seem to be no limit on the length of the name.

**Comment by SergeyBarskiy** [comment]
Correct, the post implies that the limit is imposed by compiler.  If you do not want to put a limit, how about adding configuration for discriminator columns to allow to specify the type and length?  Without doing something it will not be possible to add an index on them in SQL Server.

**Comment by smitpatel** [comment]
After reading all answers & comments on stackoverflow
- There is no limit written in specs. Virtually any name length of class should work.
- There seem to be some limit imposed by compiler but with ever new version the limit is expanding.
> how about adding configuration for discriminator columns to allow to specify the type and length?

You can already do that.
`modelBuilder.Entity<Person>().Property("Discriminator").HasMaxLength(511);`

**Comment by SergeyBarskiy** [comment]
I did not realize you could configure a column that is nowhere in the model.  Do you want to close the issue, Smit?
Thanks for your help.

**Comment by smitpatel** [comment]
When you don't configure a discriminator property, EF adds a shadow property in the model. Shadow properties are not present on CLR type but they exist in EF model so that it can be mapped to appropriate column in database and you can perform operations just like normal properties using EF APIs.
If you pass string name to `.Property()` on entityTypeBuilder then it will find & configure shadow property if one exist or create a shadow property for you. By convention if no discriminator property is defined then EF creates shadow property named `Discriminator`

**Comment by divega** [comment]
We should verify that configuring the index also limits the size of the column. Otherwise we will create a new issue for that.

We are not going to add a index by convention. We don't know that the index is necessarily going to help if it the discriminator only have a few different values. But the user can configure the index if they know it helps.

**Comment by smitpatel** [comment]
Defining index on the discriminator property in EF model changes type to `nvarchar(450)` and defines an index. 
Side note: Configuring an index also requires the knowledge of property name if its shadow. (same as above)
`modelBuilder.Entity<Blog>().HasIndex("Discriminator");`

**Comment by divega** [comment]
@smitpatel thanks for the investigation. As per decision above, we are not going to create an index by convention. I have also created https://github.com/aspnet/EntityFramework/issues/9384 to track having a sugar method to configure the discriminator property without knowing its name.
