### ISSUE TITLE
Allow multiple IModelCustomizer

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#9330]
This would allow users to add an IModelCustomizer without having to override the provider one

**Comment by divega** [comment]
@AndriySvyryd do you think we need to do this in 2.1 or is ok to have it in the backlog?

**Comment by AndriySvyryd** [comment]
@divega Backlog is fine

**Comment by ajcvickers** [comment]
Moving this to 2.1 based on feedback in #9225.

**Comment by AndriySvyryd** [comment]
This will be covered by https://github.com/aspnet/EntityFrameworkCore/issues/626

**Comment by lauxjpn** [comment]
> This will be covered by #626

Is that really the case? What is the intended procedure for providers to implement their own model customization without disturbing other extensions or custom user code that implements `IModelCustomizer` (especially in later releases like now)?

We currently implemented JSON support in Pomelo for both, `System.Text.Json` and `Newtonsoft.Json`, based on the work done by @roji for Npgsql.

`Newtonsoft.Json` uses a couple of DOM classes with properties that would normally be discovered as navigation properties by EF Core. It seems that the intended way to solve this problem is to implement `IModelCustomizer` and ignore the types.

Doing so at this point in time could however break other extensions that users might already be using and existing user code that depends on their own `IModelCustomizer` implementation.

We would also need different `IModelCustomizer` implementations, a `MySqlJsonMicrosoftModelCustomizer` and a `MySqlJsonNewtonsoftModelCustomizer`, of which one would be registered with DI for `IModelCustomizer`, depending on the JSON library actual used.

That means that users and extension would potentially not only need to override just one provider specific implementation in our case, but both if they would want to support both JSON libraries.

---

There seem to be some solutions to this issue for us:

* Just override `IModelSource` instead, let the provider specific model customizers implement a provider specific interface like 'IMySqlModelCustomizer' that allows for multiple registrations, and then explicitly call all those provider specific model customizers in `IModelSource.GetModel()` in addition to the official `IModelCustomizer` implementation.

* Allow multiple registrations for `IModelCustomizer` itself.

---

Shouldn't `IModelCustomizer` allow multiple registrations in the first place?

**Comment by AndriySvyryd** [comment]
@lauxjpn You can do it in an IModelInitiliazed convention. IModelCustomizer should only be implemented if you need access to the context instance when creating the model.

**Comment by lauxjpn** [comment]
@AndriySvyryd Thanks, I totally missed that option! This works much better than the first approach I outlined, because then we also would have wanted to use our own `MySqlTestModelSource` class when testing, which is simple to do for individual test fixtures, but hard to do an a global level for all test fixtures.
