### ISSUE TITLE
DbContext.Set<T>().FromSql() not updated

### ISSUE THREAD

**Issue by JeanCollas** [dotnet/efcore#9331]
In a Razor page on ASP.NET Core (internal stats/testing), I had some calls to stored procedures:

    @inject AppDbContext DbContext
    @{
    var stats1 = DbContext.Set<Stats_ViewsPerHourLine>().FromSql("Stats_ViewsLastHours_1");
    var stats2 = DbContext.Set<Stats_ViewsPerHourLine>().FromSql("Stats_ViewsLastHours_2");
    }

    <table>
    @foreach(var s in stats1)
    { 
        <tr><td>@s.Time</td><td>@s.Count</td></tr>
    }
    </table>
    <table>
    @foreach(var s in stats2)
    { 
        <tr><td>@s.Time</td><td>@s.Count</td></tr>
    }
    </table>

These two tables were identical when the two outputs should be different. Defining the stats2 variable after the first ``foreach`` did not change anything.

I had to do the following to avoid this issue: (probably one of the ``Tracking``/``ToList`` is not necessary)

    var stats1 = DbContext.Set<Stats_ViewsPerHourLine>().FromSql("Stats_ViewsLastHours_1").AsNoTracking().ToList();
    var stats2 = DbContext.Set<Stats_ViewsPerHourLine>().FromSql("Stats_ViewsLastHours_2").AsNoTracking().ToList();

**Comment by anpete** [comment]
@JeanCollas Which version of EF Core?

**Comment by divega** [comment]
@JeanCollas without seeing the contents of the stored procedures out best guess is that they return rows with the same values for the key property of `Stats_ViewsPerHourLine`. 

That would cause the execution of the second query to resolve all the instances from the `DbContext`'s [identity map](https://www.martinfowler.com/eaaCatalog/identityMap.html) instead of materializing new objects with the new data. 

These are possible solutions:

1. Bypass the identity map by adding `AsNoTracking()` to the queries, as you already found out.
2. Make sure the stored procedures return distinct or unique key values.
3. Use separate `DbContext` instances to execute the two queries.
4. When we finish implemented the feature, map `Stats_ViewsPerHourLine` as a [view type](https://github.com/aspnet/EntityFramework/issues/9290).

Feel free to reactivate if this doesn't answer your question.
