### ISSUE TITLE
EF fails to SQL-ize a cast in a checked function

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/efcore#9356]
Entity Framework Core fails to transform an expression containing a cast into equivalent SQL when that cast is inside a checked function.

### Steps to reproduce
Run the following repro case with SQL Server Profiler attached.

```c#
using System;
using System.Data.SqlClient;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace EFCoreChecking
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine("Creating database...");

			using (var connection = new SqlConnection(GetConnectionString("master")))
			{
				connection.Open();

				Execute(connection, "IF EXISTS(select * from sys.databases where name='EFCoreRepro') DROP DATABASE EFCoreRepro");
				Execute(connection, "CREATE DATABASE EFCoreRepro");
				connection.ChangeDatabase("EFCoreRepro");
				Execute(connection, "CREATE TABLE Records (Id int, RecordType int, Created DateTime, Data varchar(256))");
			}

			Console.WriteLine("Finding oldest record...");

			using (var context = CreateContext())
			{
				var checkedResult = FindOldestRecordChecked(context, DummyRecordType.Foo);
				Console.WriteLine("Checked: {0}", checkedResult?.ToString() ?? "<no data>");
			}

			using (var context = CreateContext())
			{
				var uncheckedResult = FindOldestRecordUnchecked(context, DummyRecordType.Foo);
				Console.WriteLine("Unchecked: {0}", uncheckedResult?.ToString() ?? "<no data>");
			}
		}

		static DateTime? FindOldestRecordChecked(DummyContext context, DummyRecordType type)
		{
			checked
			{
				var matchingRecords = context.Set<DummyRecord>()
					.Where(r => r.RecordType == (byte)type);

				return matchingRecords
					.Select(r => r.Created)
					.OrderBy(d => d)
					.Take(1)
					.ToArray()
					.Cast<DateTime?>()
					.FirstOrDefault();
			}
		}

		static DateTime? FindOldestRecordUnchecked(DummyContext context, DummyRecordType type)
		{
			unchecked
			{
				var matchingRecords = context.Set<DummyRecord>()
					.Where(r => r.RecordType == (byte)type);

				return matchingRecords
					.Select(r => r.Created)
					.OrderBy(d => d)
					.Take(1)
					.ToArray()
					.Cast<DateTime?>()
					.FirstOrDefault();
			}
		}

		static DummyContext CreateContext()
		{
			var context = new DummyContext(GetConnectionString("EFCoreRepro"));
			return context;
		}

		static string GetConnectionString(string databaseName)
		{
			var csb = new SqlConnectionStringBuilder
			{
				DataSource = ".",
				InitialCatalog = databaseName,
				IntegratedSecurity = true,
				ApplicationName = "EFCoreRepro"
			};
			return csb.ToString();
		}

		static void Execute(SqlConnection connection, string command)
		{
			using (var cmd = connection.CreateCommand())
			{
				cmd.CommandText = command;
				cmd.ExecuteNonQuery();
			}
		}
	}

	class DummyContext : DbContext
	{
		public DummyContext(string connectionString)
			: base()
		{
			this.connectionString = connectionString ?? throw new ArgumentNullException(nameof(connectionString));
		}

		readonly string connectionString;

		public DbSet<DummyRecord> Records { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(connectionString);
		}
	}

	enum DummyRecordType
	{
		Foo,
		Bar,
		Baz
	}

	class DummyRecord
	{
		public int Id { get; set; }
		public int RecordType { get; set; }
		public DateTime Created { get; set; }
		public string Data { get; set; }
	}
}

```

I expect the following query, or equivalent to be generated from both functions:

```
SELECT TOP 1 Created
FROM Records
WHERE RecordType = 0
ORDER BY Created
```

The query generated by the unchecked function is:
```
exec sp_executesql N'SELECT TOP(@__p_1) [r].[Created]
FROM [Records] AS [r]
WHERE [r].[RecordType] = @__type_0
ORDER BY [r].[Created]',N'@__p_1 int,@__type_0 int',@__p_1=1,@__type_0=0
```

The query generated by the checked function is:
```
SELECT [r].[RecordType], [r].[Created]
FROM [Records] AS [r]
ORDER BY [r].[Created]
```

The query generated by the checked function loads all records, not just the most recent one. In my case, this unneccesarily loads all five million records from a table.

### Further technical details
EF Core version: 1.1.1, 1.1.2, 2.0.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 v1703
IDE: Visual Studio 2017 15.3 Preview 7.0

**Comment by smitpatel** [comment]
`checked` keyword introduces the overflow checking. Therefore when you use create query insider `checked` block all the cast will create `ConvertCheckedExpression` whereas in `unchecked` block it will cause `ConvertExpression`. The `ConvertCheckedExpression` needs to check for overflow in C# which cannot be translated to server hence we cannot translate the `Where` predicate to SQL. This causes all data to be loaded in memory so that filter can be applied & appropriate overflow exception will be thrown at runtime.
Since `ConvertExpression` does not need exception throwing behavior, we translate it to server (with implicit or explicit cast as needed) hence the whole query is translated in `unchecked` case.

**Comment by smitpatel** [comment]
QueryModels just for info:
`checked`
```C#
Optimized query model:
      '(from DummyRecord r in DbSet<DummyRecord>
      where r.RecordType == ConvertChecked(ConvertChecked(__type_0))

      order by r.Created asc
      select r.Created)
      .Take(__p_1)'
```
`unchecked` case
```c#
Optimized query model:
      '(from DummyRecord r in DbSet<DummyRecord>
      where r.RecordType == (int) (byte) __type_0
      order by r.Created asc
      select r.Created)
      .Take(__p_1)'

**Comment by yaakov-h** [comment]
Is this intended to be a breaking change when compared with EF6?

Most of my assemblies are fully checked with the “Enable arithmetic overflow/underflow checking” project propert. I’d now have to find every query with a similar cast and convert those expressions to unchecked.

**Comment by smitpatel** [comment]
@yaakov-h - In EF6,
- either this query did not work since it fails to translate (EF did not have client eval feature)
- or if it did work then it ignored the checked node.

Effectively, there is no way to translate `ConvertChecked` to SQL and still give the same exception as you would except from C# at run-time. Hence EF Core evaluates it on client to throw exception. In this special case of query since your cast is around a closure variable only, it could be improved a bit (filed #9361). Though if the casting is around any range variable coming from database then EF Core cannot translate it.

As a work-around, you need to use unchecked around all queries. This is what compiler brings in and nothing specific EF can do about.

**Comment by yaakov-h** [comment]
EF6 does translate this query, so it probably just ignores the checked-ness.

Thanks.
