### ISSUE TITLE
Microsoft.EntityFrameworkCore.DbUpdateException when saving with ForeignKey attribute

### ISSUE THREAD

**Issue by bilal-fazlani** [dotnet/efcore#9413]
SaveChanges() throws exception when `ForeignKey` attribute is used.

```
Microsoft.EntityFrameworkCore.DbUpdateException occurred
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EFPOC.Program.Main(String[] args) in C:\Documents\Visual Studio 2017\Projects\EFPOC\EFPOC\Program.cs:line 25

Inner Exception 1:
SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Comments_Blogs_BlogId". The conflict occurred in database "Blogs", table "dbo.Blogs", column 'Id'.
The statement has been terminated.

```

### Steps to reproduce

```c#
    public class BlogContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer(@"Data Source=.\SQLEXPRESS;Initial Catalog=Blogs;" +
                                        "Integrated Security=True;Connect Timeout=30;Encrypt=False;" +
                                        "TrustServerCertificate=True;ApplicationIntent=ReadWrite;" +
                                        "MultiSubnetFailover=False");
        }

        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Comment> Comments { get; set; }
    }


    public class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();
    }

   public class Comment
    {
        public int Id { get; set; }

        public string Text { get; set; }

        public virtual int BlogId { get; set; }

        [ForeignKey("BlogId")]
        public virtual Blog Blog { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (BlogContext context = new BlogContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                Blog blog = new Blog();
                Comment comment = new Comment();

                comment.Blog = blog;

                context.Entry(comment).State = EntityState.Added;

                context.SaveChanges();
            }

            Console.ReadLine();
        }
    }

```

### Notes:

1. This only breaks when I use the foreign Key attribute. If I remove the property `BlogId` from `Comment` class (& also remove the `ForeignKey` attribute), EF doesn't throw exception.
2. This only breaks in EF Core. In EF 6.x, EF doesn't throw exception.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 v 15.3.0

**Comment by smitpatel** [comment]
This is working as expected.

When you use `context.Entry(comment).State = EntityState.Added;` to add comment to context, EF sets state for that entity only. Hence comment will be in `Added` state but blog will be in `Detached` state. When you call `SaveChanges` on this, it will assume that blog already exist in database and will just insert new comment. Since `comment.BlogId` is not initialized it will have default value of 0 which EF will try to insert in database. Since blog table does not have record with Id=0 FK constraint is violated and exception is thrown.

What you need to do is use `context.Add(comment)` method which also adds all reachable entities in added state. Which would put both blog & comment in added state and insert them correctly during `SaveChanges()`.

The exception does not occur when you remove the `Comment.BlogId` because, BlogId is `int` type which is non-nullable hence SaveChanges tries to insert 0 default value of int in the column. In the absence of CLR property, EF Core will generate a shadow property for FK and by default it is made nullable. Therefore the insert statement will insert null value in the column while saving which will not violate FK constraint.

Leaving open to discuss the differences between EF Core & EF6 in triage.

**Comment by ajcvickers** [comment]
In EF6, changing the entity state Added worked the same as calling Add--that is, it operated on the whole graph. This was because EF6 couldn't handle partially tracked graph. With EF Core, changing the state is an intentionally lower-level method that operates on a single entity. This is needed to make APIs like TrackGraph usable. So closing this as by-design because the EF Core/EF6 difference here is intentional.

**Comment by happyEveryDayBoy** [comment]
great
