### ISSUE TITLE
DbContextPool what happens after pool size is reached

### ISSUE THREAD

**Issue by Dave3of5** [dotnet/efcore#9426]
It's not described anywhere what happens with DbContextPool when the pool size is reached and another DBContext is created.

If I am reading [this](https://github.com/aspnet/EntityFramework/blob/69f870ab1f32b3185c3599887fbe020c0f70c445/src/EFCore/Internal/DbContextPool.cs
) correctly it just creates a brand new DBContext rather than take one out of the pool ?

Is this correct ?

**Comment by divega** [comment]
@Dave3of5 that sounds correct. The size argument can be used to limit the number of instances that EF Core will keep in the pool (e.g. even when the application becomes idle), but it won’t limit the total number of instances that can be created. I.e. if you are using “size” instances and a new one is needed, it won’t block.

Cc @anpete

**Comment by Dave3of5** [comment]
@divega What's the point of this then ?

I would assume most people would use this to limit the number of DBContext objects that are created but it doesn't really do that.

Clearly this doesn't work in a similar fashion to the connection pooling in ADO.Net which was implied in the documentation.

I just can't see a good use case for this.

**Comment by ajcvickers** [comment]
@Dave3of5 The point of DbContext pooling is to allow reuse of DbContext instances from a pool, which for certain scenarios can result in a performance boost over creating a new instance each time. This is also the primary reason for connection pooling in ADO.NET, although the performance boost for connections will be more since connections are generally a more heavyweight resource.

This is actually the first time I have heard the limited pool size for ADO.NET connections be described as a feature, although I can kind of see that since maybe you want your application to fail in a more controlled way if you run out of connections, especially given that connections tend to be native resources. For EF the situation is slightly different--the context is not a native resource and there seems to be little value in putting an upper bound on the number of context instances. In retrospect, maybe the size argument could have been clearer, which is something we will think about going forward.

**Comment by Dave3of5** [comment]
So I take from this there is no intention to allow this functionality? If so, how would you limit the number of connections EFCore would be allowed to make to the Db? So the reason I ask is to stop a Db from being overloaded with connections from a server.

If I set a max connections in the connection string is this overall for the server or for each context?

**Comment by Simonl9l** [comment]
I have a use case for you, your cloud DB or other db has a max connection limit!

**Comment by roji** [comment]
> This is actually the first time I have heard the limited pool size for ADO.NET connections be described as a feature

I think this has to do with not overwhelming the database server by opening two many connections, especially with multiple application servers connecting to it. Since physical connections take up non-negligible resources, ensuring that the database driver never surpasses the prescribed maximum provides valuable server-side resource predictability.

Having said that, I do agree that none of that is holds for DbContext pooling, where only client-side resources are in use (memory) and going over the maximum creates no significant problems.
