### ISSUE TITLE
Why Scaffold-DbContext must build the project?

### ISSUE THREAD

**Issue by jimerino** [dotnet/efcore#9484]
Hi!

I'm newbie and I'm trying to understand EF core. I've notice if you have an error in the project, Scaffold-DbContext returns "Build failed". Only if your project is clean and can build without errors, then Scaffold-DbContext can generate the Entities from DB.

In my sample proyects, it's very common to destroy the Entities deleting the clases and regenerating them frequently with Scaffold-DbContext.

Due I've deleted all entity clases, I must comment all lines where my DBContext and Entities appears, build without error, generate the Entities with Scaffold-DbContext and uncomment again. I think if my project was bigger, regenerating all Entities will be a tedious work.

Could it be possible that Scaffold-DbContext doesn't need to get a build project to generate the Entities?

**Comment by bricelam** [comment]
Primarily to allow you to register (or override) design-time services:

```csharp
class MyDesignTimeServices : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection services)
        => services.AddSingleton<IPluralizer, MyCustomPluralizer>();
}
```

There are also other pragmatic reasons, but they could (in theory) be avoided.

**Comment by ajcvickers** [comment]
@jimerino While this is not an unreasonable request it would actually take quite a lot of effort to make work and would also likely result in more fragile code since EF would have to be figuring out things like assembly locations independently. Also, hopefully an improved flow including "update model from database" (issue #831) will make this overall experience better. Closing this issue for these reasons.

**Comment by mathewsun** [comment]
Usually i delete old model and can't generate new. Wrong functional! Generator shouldn't build project!

**Comment by mathewsun** [comment]
Only -f (force flag) help.

**Comment by bricelam** [comment]
See #18780, there's a hidden --no-build flag that we should document for situations like this

**Comment by filmico** [comment]
As @bricelam has stated there is a --no-build flag that actually is not hidden anymore in Core 5/6

You can check all flags using the following command: 
```
dotnet ef dbcontext scaffold --help
```
The following two flags made the trick of overwriting your clases by also avoiding the need to delete things by hand while skipping the build process as a previous step to the scaffold mechanism.

--no-build --force

If you have customized things in the dbContext Class, bare in mind to create a copy of it as it will be overwritten.

MS has a pretty good explanation on many of the tricky flags in here https://docs.microsoft.com/en-us/ef/core/cli/powershell
Those are valid for PMC inside Visual Studio or the CLI if your are using VsCode

**Comment by aeslinger0** [comment]
As a work-around, what I do is make sure the entities are in their own project and reference `Microsoft.EntityFramework.Core.Design` directly from there. That way, I can unload any other projects that have references to these entities temporarily in order to regenerate. This also helps if you have other build errors in your projects not related to EF.
