### ISSUE TITLE
Fails with System.NotSupportedException when cast entity Foo to IFoo and then include navigation property

### ISSUE THREAD

**Issue by zilloy** [dotnet/efcore#9508]
Fails with System.NotSupportedException when cast entity Foo to IFoo and then include navigation property
```
Exception message:

System.NotSupportedException: 'The Include operation 'Include("Bars")' is not supported. 'Bars' must be a navigation property defined on an entity type.'

```

### Steps to reproduce
```c#
public interface IFoo
    {
        int Id { get; set; }
        ICollection<Bar> Bars { get; set; }
    }

    public class Foo: IFoo
    {
        public int Id { get; set; }
        public ICollection<Bar> Bars { get; set; }
    }

    public class Bar
    {
        public int Id { get; set; }
    }

//works fine when: 
_dbContext.Set<Foo>().Include(x => x.Bars).FirstOrDefaultAsync()

//and fails when:
_dbContext.Set<Foo>().Cast<IFoo>().Include(x => x.Bars).FirstOrDefaultAsync()
   
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by smitpatel** [comment]
Include indicates a navigation property to be loaded on an entity type in the model. Once you cast to `IFoo` the query source no longer correspond to any entity type in the model. Hence EF Core fails to find the navigation `Bars` to be included.
Further casting won't be translatable to Server. The best way is to do casting after getting the result on client manually.

**Comment by ajcvickers** [comment]
@smitpatel Any way we can figure out that the actual entity type is Foo and Foo.Bars is the same thing as IFoo.Bars?

**Comment by smitpatel** [comment]
We can map in simple case. For same interface being implemented by multiple types we can fall back to last known entity type. It may create some inconsistency & ambiguity on how & where is include is applied. Easiest way to write that would be to apply include before the cast.

Reopening so that we can discuss in triage.

**Comment by zilloy** [comment]
It worked fine in v 1.1.2 btw, so it's probably a regression

**Comment by ajcvickers** [comment]
@zilloy In general, anything after a cast to an interface like that, nothing following the cast will be translated, because the query is no longer in terms of mapped types. This used to work incidentally for Include in 1.1.2 because of the special way Include was handled. Include is now handled differently and is more in line with the rest of query implementation. 

The use of interfaces in a model is primarily covered by #757, which would allow polymorphic mappings and the use of interfaces in queries. We will address this issue as part of doing that work. However, at this time we don't think we will address it before then specifically for Include.

As a workaround, add the Include before the Cast call.

**Comment by ajcvickers** [comment]
Hi @zilloy. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.
