### ISSUE TITLE
Can not create the database table by the Fluent API way  

### ISSUE THREAD

**Issue by TomWangliming** [dotnet/efcore#9548]
I create the model, but Table cannot be generated automatically in SQLServer. I try create the table by myselft, the Database operation success.
 

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win 10
IDE: Visual Studio 2017 15.3.1

**Comment by tomwangliming** [comment]
i use Database.EnsureCreated, the table is created.
Can the ef core generated  itself, not by useEnsureCreated?

**Comment by ajcvickers** [comment]
@tomwangliming EF Core does not have any mechanism to automatically create the database in the way that EF6 and earlier did. This was changed for several reasons, one of which was that it is generally better for an application to control when a database gets created rather than having it happen automatically and potentially unexpectedly. Along the same lines, EnsureCreated should usually only really be used for quick prototyping and testing. For other situations, we recommend using Migrations with an appropriate deployment strategy to properly create and manage the database.

**Comment by tomwangliming** [comment]
thank you !
