### ISSUE TITLE
System.Data.SqlClient.SqlException (0x80131904): The datepart hour is not supported by date function dateadd for data type date.

### ISSUE THREAD

**Issue by doublnt** [dotnet/efcore#9566]
Using .NET-Core 2.0 and EF-Core 2.0 
When I run this code in ubuntu16.04 in Linux , then log show the error, but it is fine when I use in windows

```c#
public async Task<int> GetTodayQuestionCount()
{
    return await Entities
               .Where(q => q.IsActive && q.DateAdded >= DateTime.Now.Date && q.DateAdded < DateTime.Now.Date.AddHours(8))
               .Select(q => q.QID).CountAsync();
}

```

**Comment by smitpatel** [comment]
Can you post debug log output for query in both machines? Ideally, EF Core should generate same query. Also are you connecting to same server from both machines?

**Comment by doublnt** [comment]
The SQL Query is below:
```sql
exec sp_executesql N'SELECT COUNT(*)
FROM [query] AS [q]
WHERE ((([q].[UserID] = @__spaceUserId_0) AND ([q].[IsActive] = 1)) AND ([q].[DateAdded] >= @__startTime_1)) AND ([q].[DateAdded] < @__endTime_2)',N'@__spaceUserId_0 int,@__startTime_1 datetime2(7),@__endTime_2 datetime2(7)',@__spaceUserId_0=2,@__startTime_1='2017-08-29 00:00:00',@__endTime_2='2017-08-29 16:53:21.3550137'
```
SQL Version is  SQL Server 2014

**Comment by ErikEJ** [comment]
@doublnt Pls share why this was closed!?

**Comment by doublnt** [comment]
@ErikEJ   Sorry, I forgot.Following: I try to separate  the query conditions like that

```c#
public async Task<int> GetTodayQuestionCount()
{
    var startTime = DateTime.Now.Date;
    var endTime = startTime.addHours(8);
    return await Entities
               .Where(q => q.IsActive && q.DateAdded >= startTime && q.DateAdded < endTime)
               .Select(q => q.QID).CountAsync();
}
```
But I didn't test in my production Environment. I will show the result after it is work in my Production Environment.

**Comment by doublnt** [comment]
@ErikEJ  It's work when I use in my production environment

**Comment by v-zubritsky** [comment]
I encounter the same error with `date_value.Date.AddHours(hours_value)`

It fails since `date_value.Date` is converted to sql as `CONVERT(date, date_value)` and then `.AddHours` which is `DATEADD(hour, date_value)` obviously fails as resulting expression is `DATEADD(hour, CONVERT(date, date_value))` and you can't add hours to value of type `date`.

**Comment by uladz-zubrycki** [comment]
@ajcvickers Could you please elaborate on why it's not planned? Developers are forced to use quite a hacky and dirty approach to deal with this issue, which isn't that obvious without additional investigation.

**Comment by ajcvickers** [comment]
@uladz-zubrycki It was closed by the original poster. If you think there is a bug here, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by uladz-zubrycki** [comment]
@ajcvickers Indeed. This change confused me 
![выява](https://user-images.githubusercontent.com/5411526/196040517-fccd2f51-d5e6-4cc6-823b-a992c4ae514d.png)

As to the reproduction, original snippet is enough. And here described a reason of such behavior https://github.com/dotnet/efcore/issues/9566#issuecomment-819563459

It's applicable for EF 3.1.12, haven't tried that with the latest EF version since project, where I faced this problem, is locked to EF 3.
It's the best I could do here, the rest is up to you.
