### ISSUE TITLE
Setting a navigation property to null doesn't set the FK to null

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#9673]
The relationship is configured like this:
`modelBuilder.Entity<Post>().HasOne(t => t.Blog).WithMany("PostBlogCollection").HasForeignKey("Blog_Seqnr").OnDelete(DeleteBehavior.Restrict);`
The following code:
```
var post = ctx.Posts.First();
var blog = ctx.Blogs.Where(z => z != post.Blog).First();
Console.WriteLine(post.Blog_Seqnr);
post.Blog = blog;
Console.WriteLine(post.Blog_Seqnr);
post.Blog = null;
Console.WriteLine(post.Blog_Seqnr);
```
Outputs "1 2 2". I expected the output to be "1 2 ".

It was working as expected in EFCore 1.1.2, the bug only appears in EFCore 2.1.

**Comment by ajcvickers** [comment]
@Wain123 This is a breaking change we made in 2.0. Previously, "Restrict" meant validate the constraint (rather than setting null or cascading) in the database, but the EF change tracking behavior was still SetNull. Now there is a new behavior--ClientSetNull--for this, and Restrict means never null out FKs. ClientSetNull is the new default for optional relationships, while Restrict used to be the default, which means the behavior is the same unless Restrict is set explicitly for an optional relationship--your case above.

Full details here: https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete
