### ISSUE TITLE
Adding DotNetCliToolReference to the csproj file should happen automatically

### ISSUE THREAD

**Issue by roptaty** [dotnet/efcore#9679]
When adding packages from EntityFrameworkCore, the line <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" /> should be added automatically to improve the user experience. If this is currently not possible, it should be displayed during installation of the package.

**Comment by bricelam** [comment]
We'll need features in NuGet to support either of those.

**Comment by ajcvickers** [comment]
@bricelam Can you find issues on NuGet to reference.

**Comment by bricelam** [comment]
We're waiting for NuGet/Home#4190. After that, we're considering adding packages like `Microsoft.EntityFrameworkCore.SqlServer.All` that bring in the runtime and tools for a given provider.

README files simply aren't supported with `project.json` and `PackageReference` NuGet by design. The reasoning I heard was that there is no discrete install step where these would be opened.
