### ISSUE TITLE
[Entity Framework Core 1.0] Group by date

### ISSUE THREAD

**Issue by helderboone** [dotnet/efcore#9701]
Hi!
I have an entity called events which is responsible for storing information such as id, httpmethod (enum), RequestDate, StatusCode (enum).

I want to get the counting of the events between 2017-08-27 to 2017-09-02 (which means last week) grouping them by day ( from sunday to saturday)

I tried something like this:
```
var firstDayLastWeek = DateTime.Now.FirstDayOfWeek().AddDays(-7);
var lastDayLastWeek = DateTime.Now.LastDayOfWeek().AddDays(-7);

var lastWeekValues = db.Events.AsNoTracking()
 .Where(e => e.RequestDate >= firstDayLastWeek &&
e.RequestDate <= lastDayLastWeek)
.GroupBy(e => e.RequestDate)
.Select(g => g.Count())
.ToArray();
```
2017-08-28 - 2 rows 
2017-08-29 - 2 rows 
2017-08-30 - 2 rows 
2017-08-31 - 2 rows 
2017-09-01 - 2 rows 
2017-09-02 - 2 rows 

Second option;
```
var lastWeekValues = db.Events.AsNoTracking()
.Where(e => e.RequestDate >= firstDayLastWeek &&
e.RequestDate <= lastDayLastWeek)
.GroupBy(x => new { DayOfWeek.Sunday, DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday, DayOfWeek.Friday, DayOfWeek.Saturday })
.Select(g => g.Count())
.ToArray();

Result [0] = 12
```

The problem is if there are events almost all days except on 2017-27-08 (sunday) id did not show as 0 in the first position and also the array size is 6 instead of 7.

Any help?

**Comment by smitpatel** [comment]
GroupBy would work that way only. (in linq & in SQL both). The grouping is only created for keys which exists. If there is no row associated with an expected key there will not be any group. Hence Sunday would not show as 0 instead the whole row won't be in results.
For the second option you tried, you are grouping by constant key hence all the records will be in same group. So group size will be total count which is 12.

No direct groupby query could achieve this. Possible alternatives are write a join after grouping with dynamically generated all the dates so that you can insert records with 0 count for missing dates.

**Comment by helderboone** [comment]
@smitpatel I understandood. How could i create this join with dynamically generated dates so that fill the aproppriate values? Could you give me an example according this context i described above?
Thank you!

**Comment by smitpatel** [comment]
```C#
var datesToConsider = new [] { }; //Generate array of dates for which you are printing results.
var lastWeekValues  = var lastWeekValues = db.Events.AsNoTracking()
 .Where(e => e.RequestDate >= firstDayLastWeek &&
e.RequestDate <= lastDayLastWeek)
.GroupBy(e => e.RequestDate)
.Select(g => new { g.Key, Count = g.Count() }) // all small change here from first option
.ToArray();
var result2 = datesToConsider.GroupJoin(lastWeekValues, a => a, l => l.Id, (id, g) => new { Id = id, Count = g.FirstOrDefault()?.Count ?? 0 }).ToList();
```
