### ISSUE TITLE
Sum of a constant is evaluated on client

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#9719]
`ctx.Posts.Sum(z => 1m)`
This code evaluates the sum client-side.

**Comment by smitpatel** [comment]
This arises because we are not translating select of constant into projection of select expression. So we would generate select 1 only where there are no projections. So `Sum()` fails since we apply sum to the Single projection in the list. We need to translate constant and put it into Projection for Sum to work.
```
dbug: Microsoft.EntityFrameworkCore.Query[100104]
      Optimized query model:
      'from Blog b in DbSet<Blog>
      select 3'
dbug: Microsoft.EntityFrameworkCore.Query[100107]
      (QueryContext queryContext) => IEnumerable<decimal> _InterceptExceptions(
          source: IEnumerable<decimal> _ShapedQuery(
              queryContext: queryContext,
              shaperCommandContext: SelectExpression:
                  SELECT 1
                  FROM [Blogs] AS [b],
              shaper: TypedProjectionShaper<ValueBufferShaper, ValueBuffer, decimal>),
          contextType: EFSampleApp.MyContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: queryContext)
```

As a work-around you can do this.
`ctx.Posts.Count() * 1m`

**Comment by ajcvickers** [comment]
@Wain123 Can you provide some more details on why you want to execute that query in that way? (It could be that there is value in changing the way expressions are evaluated when they are not correlated with the query, but from just the example above it's hard to find compelling cases to make a change to the existing behavior. That's not to say we won't, but if the case can be made more compelling, then there is more chance it becomes high enough priority to work on.)

**Comment by ajcvickers** [comment]
@Wain123 Thanks for the feedback. With regard to server evaluation of sum, this:
```C#
var result = context.Foos.Sum(e => e.Id);
```
is evaluated on SQL Server as
```sql
SELECT SUM([e].[Id])
FROM [Foos] AS [e]
```
and when the table is empty the result returned from EF is zero. This shows that having an idea as to whether or not something is executed on the client or on the server is not a reliable way of knowing exactly what the result will be. The only way to be sure is testing.

With regard to the other comments, it has always been hard when using any ORM to determine what queries can be translated just from having a mental model of how the ORM works. With enough experience it's probably possible to know most of the time. EF Core is no different in this respect. The only difference for EF Core is that it can do client evaluation rather than just giving up. But of course, client evaluation can be switched off, in which case EF Core will give up like other ORMs.

Closing this issue since at present the value of implementing it does not seem worth the cost to do so. As always, we would reconsider this with more information.
