### ISSUE TITLE
`dotnet ef migrations` with VSTS feed fails

### ISSUE THREAD

**Issue by Mardoxx** [dotnet/efcore#9762]
`dotnet ef migrations` requires a successful build to run, which in turn needs a successful package restore.

This is not possible if you are not using a VSTS feed as, I believe, `dotnet` does not support the auth providers needed for VSTS feeds.

See https://github.com/dotnet/cli/issues/7629

**Comment by ajcvickers** [comment]
@Mardoxx As I'm sure you are aware since you linked the issue, this is an external issue with NuGet (tracked by https://github.com/NuGet/Home/issues/5874). There isn't much that EF Core can do here. We have discussed not requiring a successful build at length, but there are many issues with this. One thing that might help is that the dotnet command line tools only build the active project, and we have an issue to have the PMC tools do the same thing: #9716.
