### ISSUE TITLE
DBContext Constructor should take IDbContextOptions instead of DbContextOptions

### ISSUE THREAD

**Issue by CubicleJockey** [dotnet/efcore#9765]
Describe what is not working as expected.

I want to be able to do more mocking but the base class from DbContext is forcing me to use an DbContextOptions instead IDbContextOptions which DbContextOptions is already inheriting.

Forces me to do:  
```c#
AccountContext(DbContextOptions options) : base(options) { }
```
But I want to do:
```c#
AccountContext(IDbContextOptions options) : base(options) { }
```
### Further technical details
EF Core version: (Microsoft.EntityFrameworkCore" Version="2.0.0"
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0")
Operating system: Windows 10
IDE: Visual Studio 2017 15.3.3

**Comment by ajcvickers** [comment]
@CubicleJockey While the names are somewhat misleading, IDbContextOptions is not really the contract interface for DbContextOptions. It's only the interface for consuming the options from inside EF Core.

What are your goals for mocking DbContextOptions? Typically, we recommend against creating test doubles for DbContext because it quickly becomes too complex to manage properly. Instead, we would recommend creating your own repository or similar interface and mocking that.
