### ISSUE TITLE
byte[] truncation in 1.1 (SQLCE provider)

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9796]
A user reported this: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/issues/496 - but I was unable to fix in the provider code - does this issue ring a bell with you guys?

### Further technical details
EF Core version: 1.1
Database Provider: SQLCE 1.1
Operating system:

**Comment by ErikEJ** [comment]
workaround by the magic of MaxLength(-1) - I cannot see that documented anywhere?

**Comment by ErikEJ** [comment]
Error 40 👎

**Comment by smitpatel** [comment]
@ErikEJ - It was sleep time for me 😢 

I couldn't find source code for SqlCe provider.
But I have suspicion on what could have caused it. 
In commit https://github.com/aspnet/EntityFrameworkCore/commit/ae2277ed90c782500df29d2bf735491f316da9a8 check file `SqlServerByteArrayMapping`
We had to introduce field `maxSpecificSize` because of the issue. Issue was, whenever the size was passed as null, we would limit it to some max size (instead of "max"). So `varbinary(max)` became `varbinary(8000)`. That could cause such truncation. I don't know when that code was put in there. But it got fixed in 2.0 release so we correctly map the types.

**Comment by ErikEJ** [comment]
@smitpatel Thanks, it was actually a bug in the 1.1 SQLCE provider https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/73a1dd3f4a0f663fbbe8e2810c36a2c2d288d7f0#diff-9663a3ff9c341238438374a87db8ef98R78 (also present in the 2.0 provider, but I guess the change above avoids the data loss)
