### ISSUE TITLE
Could I implement extra sql functions like EF.Functions ?

### ISSUE THREAD

**Issue by PMExtra** [dotnet/efcore#9802]
In PostgreSQL, it's has a lot of practical expansion, like PostGIS and TimescaleDB.

But when I use them, I have to execute the sql string that is whole handwritten to call the sql function which is provided by the extension. Like `st_transform()` or `time_bucket()`.

On the other hand, PostgreSQL has many advanced sql statements. Like `SELECT DISTINCT ON (fields) ...`, it's also difficult to generate by EFCore, right?

So if we can custom some translator like which in the EF.Functions, it will be awesome.

**Comment by ajcvickers** [comment]
@PMExtra You can use DbFunctions (see https://github.com/aspnet/EntityFrameworkCore/issues/7368) to map functions in your application code. Other extensions to SQL translation are also possible, but harder to do since you'l likely need to implement custom code in the query translation services.

**Comment by roji** [comment]
@PMExtra I'd definitely be interested in any translation improvements which allow Npgsql to cover more PostgreSQL-specific SQL.

For any standard PostgreSQL function (as opposed to your own, custom functions added with `CREATE FUNCTION`), please consider sending a PR rather than implementing things in your own project - this will allow everyone to profit from the translation.

For other, non-function translation, as @ajcvickers said it would require a bit more work - but is definitely not impossible. You're welcome to experiment and send PRs on this kind of scenario as well.
