### ISSUE TITLE
Can not seed data in Up function of the init Migeration

### ISSUE THREAD

**Issue by 19317362** [dotnet/efcore#9828]
I created a new asp.net core 2.0 project with EF CORE.
I want to seed some init data after the DB is created.
I do this work in the Up function of the init migeration like this
```C#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            //create tables
            migrationBuilder.CreateTable(
                name: "ApplicationSetting", ....

          //seed data
          using(var db = new MyDbContext();
          {
                var item = new ApplicationSetting();
                //setup item
                db.ApplicationSetting.Add(item);
                db.SaveChanges();//exception was throw here which says ApplicationSetting not found
          }
       }
```

I think it's because at the end of the Up, Table was not createed.
Afer I moved the code somewhere after the migeration is done, It works fine. But it's not what I want.
I want the table creation and the data seeding is bundled together: All fails or All Done.

Can you help me?
The same mechnism works fine in EF6.

EF Core version: 2.0
Database Provider: SQL SERVER
Operating system: WIN10
IDE: Visual Studio 2017

Best regards.

**Comment by ajcvickers** [comment]
@19317362 Can you provide the full stack trace and exception message?

**Comment by ajcvickers** [comment]
@19317362 After discussing this, we're actually very surprised that this worked in EF6. We don't expect it to work in EF Core because the CreateTable call does not actually create a table--it adds an operation to the migration pipeline that will later be run against the database to create the table.

If you want to add seed data to your migrations, look at using the InsertData/UpdateData/DeleteData methods on the MigrationBuilder. Also, in 2.1 this should be easier with the seeding feature: #629.
