### ISSUE TITLE
Kindly review your usage of extension methods

### ISSUE THREAD

**Issue by rurapente** [dotnet/efcore#9855]
Why are there these extension methods ? 
```
db.GetInfrastructure()
db.Migrate();
db.GetAppliedMigrations();
db.GetMigrations();
db.GetPendingMigrations();

```
If they belong to DatabaseFacade, why aren't they in DatabaseFacade directly ? 

If you have a namespace 
`Microsoft.EntityFrameworkCore.Extensions;`
why aren't they int there ? 

It's bad when I read tutorials and then the methods used just aren't there. 
Tutorials should also work when I land somewhere via google, and don't read everything from top-to-bottom. 

In the end I have to guess which namespace they are in, because crawling with google doesn't help...  

Example:
```
var mig = db.GetInfrastructure().GetRequiredService<Microsoft.EntityFrameworkCore.Migrations.IMigrator>();
mig.Migrate("targetMigration");
```

Requires:
```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
```

but doesn't require 
```
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Extensions;
```

strange.

Maybe if it requires arguments, it should be its own class with requiring the context class in the constructor. 
 
I'd like to be able to write code that doesn't start with 100's of using directives.
Preferably not a single one. 

In fact, it's the "core" framework. 
That shouldn't have a single extension method in the first place. 

If any beginner reads those https://docs.microsoft.com tutorials, he doesn't have a chance...

**Comment by ajcvickers** [comment]
@COR-Management Thanks for the feedback. Extension methods are used by-design for several reasons. Two of the common ones are:
* EF Core is designed to be extended, primarily by different database providers. These providers integrate their extensions into the main API often by using extension methods.
  * A common subset of this is relational providers, for which there is a common base assembly that adds extension methods.
* Interfaces define a minimal contract that must be implemented, and extension methods are used to add common functionality to those interfaces such that any implementation can use this functionality.

With regard to namespaces, most EF extension methods are in `Microsoft.EntityFrameworkCore` since this is the namespace most people are likely to have available. Common exceptions to this are extension methods relating to external types which are often in the namespace of the type they extend, and extension methods not designed to be used in common cases, which are in the Infrastructure namespace.
