### ISSUE TITLE
Invalid Column Name

### ISSUE THREAD

**Issue by MateiNenciu** [dotnet/efcore#9866]
Executing an operation to get and "Tasks" entity from DB throws an "System.Data.SqlClient.SqlException". Task entity containd a fileld (idBedroom) representing an FK to "Bedrooms entity. The relationship between them is one to many.

The entities are defined bellow:
```c#
public partial class Tasks
{
    public Task() { }
    public int IdTask { get; set; }
    public int IdBedroom { get; set; }
    ....................
    public Bedrooms IdBedroomNavigation { get; set; }
}

public partial class Bedrooms
{
        public Bedrooms()
        {
               Tasks = new HashSet<Tasks>();
        }
        public int IdBedroom { get; set; }
        ...........................
        public ICollection<Tasks> Tasks { get; set; }
}
```
The code defining Tasks entity by modelBuilder in OnModelCreating function is:
```c#
modelBuilder.Entity<Tasks>(entity =>
{
         entity.Property(e => e.IdTask).HasColumnName("idTask");
         entity.Property(e => e.IdBedroom).HasColumnName("idBedroom");
         entity.HasOne(d => d.IdBedroomNavigation)
                  .WithMany(p => p.Tasks)
                  .HasForeignKey(d => d.IdBedroom)
                  .HasConstraintName("FK_Tasks_Bedrooms");
          .......................
}
```
Produced T-SQL query by EF is: 
```T-SQL
SELECT [t].[idTask], [t].[BedroomsIdBedroom]
FROM [Tasks] AS [t]
```
The exception is:
```
Exception message: "Invalid column name 'BedroomsIdBedroom'".

Stack trace:    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at HRPv3.Data.Services.SharedRepository.GetTask_ById(Int32 idTask, Boolean nonCancelled) in C:\Users\matei.nenciu.INTRANET\Documents\Visual Studio 2017\Projects\HRPv3.2.API\HRPv3.2.Data\Services\SharedComponents\TaskShared.cs:line 1668
```

### Steps to reproduce
Scaffolded my DB then execute the code : 
```c#
this.Context.Tasks.Where(...);
```

Can someone tells me why EF generates column name "IdBedroom" as "BedroomIdBedroom" ? Am I configuring something wrong?
I have other colums representing FK's but only this one is generated wrong. 
I also removed the connection between Bedrooms and Tasks and it works like a charm. 

### Further technical details
EF Core version: 2.0.0.
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 latest update
IDE: Visual Studio 2017 version 15.3.4

**Comment by smitpatel** [comment]
I tried reproducing above based on data provided. First error I hit was the entityTypes don't have PK configured. Once I set PKs, it works correctly for me.
Can you please modify following sample code to demonstrate issue you are seeing.
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var query = db.Tasks.ToList();
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        // Declare DBSets
        public DbSet<Tasks> Tasks { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(new LoggerFactory().AddConsole());
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
            modelBuilder.Entity<Tasks>(entity =>
            {
                entity.Property(e => e.IdTask).HasColumnName("idTask");
                entity.Property(e => e.IdBedroom).HasColumnName("idBedroom");
                entity.HasOne(d => d.IdBedroomNavigation)
                    .WithMany(p => p.Tasks)
                    .HasForeignKey(d => d.IdBedroom)
                    .HasConstraintName("FK_Tasks_Bedrooms");
            });


        }
    }

    public partial class Tasks
    {
        [Key]
        public int IdTask { get; set; }
        public int IdBedroom { get; set; }
        public Bedrooms IdBedroomNavigation { get; set; }
    }

    public partial class Bedrooms
    {
        public Bedrooms()
        {
            Tasks = new HashSet<Tasks>();
        }
        [Key]
        public int IdBedroom { get; set; }
        public ICollection<Tasks> Tasks { get; set; }
    }

}
```

**Comment by MateiNenciu** [comment]
I tested your code and worked. I'm investigating today why my full code doesn't work.

**Comment by MateiNenciu** [comment]
Ok so I made another program and I found the problem: my Bedroom model is composed with 2 partial Bedroom classes:
1. public partial class Bedroom that contains the fields described in my first post.
2. another public partial class Bedroom that contains some additional fields and methods.

I found the code causing me the invalid column problem:

``` C#
public partial class Bedrooms
    {
       .................
        public IOrderedEnumerable<Tasks> OrderedTasks
        {
            get
            {
                if (IsEmergency)
                    return this.Tasks
                        .OrderBy(t => t.IdStationStartNavigation.Name)
                        .ThenBy(t => t.DateActualStart);
                else
                    return this.Tasks.OrderBy(t => t.DateActualStart);
            }
        }
      ........................
     }
```

When I comment this code it works like a charm. Any idea what is wrong with it?

**Comment by smitpatel** [comment]
@MateiNenciu - With that code in other partial class, basically you are defining 2 navigations in `Bedrooms` pointing to `Tasks`. Hence tries to create 2 relationships. Since you have configured one of them explicitly the other one will be configured by conventions and creates a shadow property to represent the FK. (in this case it is named entityType + PK name = `Bedrooms` + `IdBedrooms`).  Looking at the code it seems like the intent of `OrderedTasks` is not to have 2 relationships but just provide related data ordered according to business logic. You can achieve that by putting `[NotMapped]` attribute on `OrderedTasks` navigation property. That way EF Core will ignore that navigation and will not try to create relationship associated with it.

Feel free to re-open if you still face issues after using `NotMapped` attribute.

**Comment by MateiNenciu** [comment]
It worked thak you for explanation!

**Comment by Grauenwolf** [comment]
While `NotMapped` is a valid work-around, this is still a bug. Creating and requesting shadow properties is not expected behavior. It isn't like we can actually access and use these new properties.

Beyond that, the error message is very misleading because nothing about it indicated what EF is doing.

**Comment by Grauenwolf** [comment]
This behavior will also occur if you have a class called `BedroomView` with a the property `public ICollection<Tasks> Tasks { get; set; }`. 

In that case every query that touches `Tasks` will break, even if  `BedroomView` is not involved in said query.

**Comment by smitpatel** [comment]
@Grauenwolf - `NotMapped` is not work-around, it is correct way to configure. Every navigation in your class defines a relationship in database. If user specifies 2 navigations then there will be 2 relationships. 

This issue only happens when you have a navigation like property for business logic but not part of the model or the example you gave, defined an entity with navigation but not wanting the relationship. When you define your domain model which is not same as your database model, you are going to run into issues. Unwanted navigations being treated as relationship is just one of the ways. You could have CamleCase properties in domain and lowercase column names in database. Or int stored as strings in database. There are many different ways, when database model does not match domain model exactly. And there is no way to find out what was incorrect in user code which caused the error. If an existing database is being targeted then its user's responsibility to map your domain model to your database model correctly. Any failures to do so can cause runtime failures.

Verifying that both models are same is cost associated with it. Most importantly, we don't want to block users from using certain features which are not supported yet. e.g. An entityType can be mapped to a view instead of table. Certainly saving data will not work but query would just work fine. That allows using views which returns ad-hoc types. If EF Core went to stricter restrictions then it will be impossible to use such things till supported.
