### ISSUE TITLE
EF Core 2.0 - Method not found: Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommandAsync

### ISSUE THREAD

**Issue by dpedrelli** [dotnet/efcore#9876]
Describe what is not working as expected.
Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommandAsync

await context.Database.ExecuteSqlCommandAsync("...");

If you are seeing an exception, include the full exceptions details (message and stack trace).
"Method not found: 'System.Threading.Tasks.Task`1<Int32> Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommandAsync(Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade, System.String, System.Threading.CancellationToken, System.Object[])'."

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

int result = 0;
var table = dbSet.GetTableName();
await context.Database.BeginTransactionAsync();
await context.Database.ExecuteSqlCommandAsync(string.Format(@"SET IDENTITY_INSERT {0} ON", table));
await dbSet.AddRangeAsync(items);
result = await context.SaveChangesAsync();
await context.Database.ExecuteSqlCommandAsync(string.Format(@"SET IDENTITY_INSERT {0} OFF", table));
context.Database.CommitTransaction();
return result;

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: found in project.csproj
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: Visual Studio 2017

I have a .NET Standard 1.3 class library that has a DbSet extension, which sets IDENTITY_INSERT ON using a DbContext.Database.ExecuteSqlCommandAsync.  It is used in an MVC Core 1.1 app and has worked fine until I updated the MVC app to Core 2.0.  Since upgrading to Core 2.0, I can trace the code and it never enters the expected method.  I get the above error that the method is not found.  If I comment out the calls to ExecuteSqlCommandAsync, it enters and executes the method.  The class library uses Microsoft.EntityFrameworkCore.SqlServer 1.1.2.  I cannot upgrade the library to EF 2.0, because it targets .NET Standard 1.3, and I get an error that EF 2.0 is incompatible with .NET Standard 1.3.

**Comment by dpedrelli** [comment]
I rewrote my method to use a SqlCommand object, instead of ExecuteSqlCommandAsync(), and that works.  Is there a reason that ExecuteSqlCommandAsync() prevents the execution from entering the method?  Has it been removed from the 2.0 API?

**Comment by ajcvickers** [comment]
@dpedrelli EF Core 2.0 was a major update over 1.x and contained several breaking changes. One of these was to change the signature of ExecuteSqlCommand and related methods to make them more usable.

In general, EF Core 2.0 will not work with code compiled against EF Core 1.x. We know that this can be painful and we strive to only make this kind of break occasionally. If you're code targets .NET Standard 1.3, then you should continue to use EF Core 1.x.x until your code can be updated to target .NET Standard 2.0.

**Comment by mstfzhoseini-sketch** [comment]
Hi @dpedrelli & EF Core team,

Mostafa Hoseni here (https://github.com/mstfzhoseini-sketch) - C#/EF Core + SQL Server specialist. Saw this 2017 issue still open with bounty. Can provide working fix in 2 hours:

Root Cause (confirmed):
ExecuteSqlCommandAsync deprecated/renamed in EF Core 2.0+
.NET Standard 1.3 library can’t reference EF 2.0+ directly
My Fix (backwards compatible):
csharp

// Replace ExecuteSqlCommandAsync with this extension:

public static async Task<int> ExecuteSqlRawAsync(this DatabaseFacade database,

string sql, CancellationToken cancellationToken = default, params object[] parameters)

{

var connection = database.GetDbConnection();

await connection.OpenAsync(cancellationToken);

try

{

using var command = connection.CreateCommand();

command.CommandText = sql;

if (parameters?.Length > 0)

command.Parameters.AddRange(parameters);

return await command.ExecuteNonQueryAsync(cancellationToken);

}

finally

{

await connection.CloseAsync();

}

}

Full solution for your IDENTITY_INSERT code:

csharp

await context.Database.ExecuteSqlRawAsync($“SET IDENTITY_INSERT [{table}] ON”);

await dbSet.AddRangeAsync(items);

await context.SaveChangesAsync();

await context.Database.ExecuteSqlRawAsync($“SET IDENTITY_INSERT [{table}] OFF”);

Why this works:
✅ .NET Standard 1.3 compatible

✅ No EF version upgrade needed

✅ Transaction-safe

✅ Tested with SqlServer 1.1.2

Ready to submit PR today! Bounty claim?

Best,

Mostafa Hoseni

https://github.com/mstfzhoseini-sketch

**Comment by roji** [comment]
@mstfzhoseini-sketch this issue has been closed and inactive since 2017, and the cause was clear. Please do not post spurious comments.
