### ISSUE TITLE
Use of reflection cache library

### ISSUE THREAD

**Issue by xaviergxf** [dotnet/efcore#9919]
Hi,

   I see that EF Core uses a lot of reflection, which is normal for a ORM and other projects. My question is why hasn't Microsoft created/used a library to cache all this reflection with getters/setters as delegates? With this library other projects could benefit from the same cache for other purposes. Is this an acceptable request? Can we please have a discussion?

Thanks!

**Comment by ajcvickers** [comment]
@xaviergxf It is not a for EF to create such a library, and it would only be of limited use to EF since while we do some simple property access, we also build and compile quite complex expressions that are very specific to EF. So closing this as an EF issue, but you may want to look at https://github.com/dotnet/corefx/issues/24390
