### ISSUE TITLE
Using ID from base model causes 'cannot be tracked' error during update

### ISSUE THREAD

**Issue by xwiz** [dotnet/efcore#9933]
If you have a base model as follows:

    [Key]
    public int Id { get; set; }

and let your main model inherit this.

During, update, you will get `InvalidOperationException: The instance of entity type 'DerivedModel' cannot be tracked because another instance...`

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by xwiz** [comment]
Very sorry about this. If the message doesn't make it rather obvious, i.e. there is nothing wrong with inheriting a key as stated from BaseModel in db context updates, then this may not help.
