### ISSUE TITLE
How to use NotMappedAttribute on Entity class? 

### ISSUE THREAD

**Issue by jhermsen** [dotnet/efcore#9949]
What I'm trying to do is use [NotMapped] on my entity so I can use a View in Sql.

If I have an entity like so:
```
[NotMapped]
public class MyEntity
{
...
}
```
It will still create MyEntity in the database.

I found where the issue is comming from, but don't know how to use it properly or that is a bug of some sorts.

Within ModelBuilder if the Entity get's created it is using ConfigurationSource.Explicit.
The NotMappedEntityTypeAttributeConvention is performing ModelBuilder.Ignore using ConfigurationSource.DataAnnotation.

The ModelBuilder Ignore checks the ConfigurationSource and just returns false, because the Entity is marked Explicit and the Ignore is set as DataAnnotation and can't override it.

So is this a bug and should it work with the attribute or should I use it in a different way?

**Comment by ajcvickers** [comment]
@jhermsen NotMapped cannot be used in this way. Using NotMapped means that the type is not included in the model at all. Currently, all queries need the target type to be in the model. See #1862 for mapping to types that are not in the model, and #9290 for using types that don't have a key.

To expand a bit more on the behavior you are seeing. Generally, if some configuration comes from a data annotation, and then there is also explicit Code First configuration for the same thing, then the Code First configuration takes precedence over the data annotation. This is because data annotations can be used for many things, not just EF mapping, so you may need a data annotation for some other reason without it impacting the EF mapping.

So even though NotMapped is saying to not include the type in the model, the Code First configuration is overriding that and is including it anyway.

**Comment by jhermsen** [comment]
Thanks @ajcvickers,

Clear on why I shouldn't use NotMapped.
Didn't see when you could use NotMapped on the Entity, but found some use.

If I understand basicly Explicit means the Entity is Defined as a DbSet in the Context.
And related entities only referenced in properties of explicit Entities can be marked with the NotMapped attribute. Is this correct or are there more uses?

**Comment by ajcvickers** [comment]
@jhermsen That is correct.
