### ISSUE TITLE
When same property is both primary and foreign key query fails 

### ISSUE THREAD

**Issue by GabrielMancik** [dotnet/efcore#9973]
I have:
```
Class1 
{
	public int Class2Id { get; set; }
	public Class2 Class2 { get; set; }
}

Class2
{
	public int doesntMatterProperty1 { get; set; }
	public int doesntMatterProperty2 { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<Class1>(entity =>
	{
		entity.HasKey(e => e.Class2Id);
	});
}
```
Query that is executed when getting all Classes1 (not including Class2) looks something like this:

```
SELECT [e].[Class2Id], [e].[Class2Id1]
FROM [Classes1] AS [e]
```
This query fails because there is no Class2Id1 column in Classes1 table. But when I add Class1 navigation property to Class2 entity:

```
Class2
{
	public int doesntMatterProperty1 { get; set; }
	public int doesntMatterProperty2 { get; set; }

	public Class1 Class1 { get; set; }
}
```
Query executes correctly. Can I avoid adding this property? Is this a bug or just how it works?

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer Version="2.0.0"
Operating system: Windows 8.1
IDE: Visual Studio 2017 Proffesional

**Comment by smitpatel** [comment]
PK property can only be used as FK when the relationship is one-to-one identifying relation so that each child record will have unique parent and can take identity from parent. For one-to-many relationships, all children will have same value of FK hence the FK cannot be PK for child table. In above configuration, you are using reference navigation on one side only. Since there is only 1 navigation on model & it is reference type, EF Core has no way to know the cardinality of the relationship. By convention it makes it one to many relationship (i.e. Each Class2 has multiple Class1 child). Since you are configuring `Class2Id` to be PK, that property cannot be used as FK anymore so EF Core will introduce a shadow property (shadow property is a property which exist in the model but does not exist on the CLR type backing the entityType). The conventional name for property is `Class2Id` but since it is already used by existing property, we name it `Class2Id1`. Even though such property does not exist in CLR type, it does exist in EF metadata and when EF creates database, it would create a column for the property. So the first query generating is _not incorrect_. It would pass successfully. It would fail only if you are managing database by yourself rather than EF to manage it (through migrations), in which case, it is mismatch between EF metadata model & store model and it is likely to fail.

Since you want to use the same property as PK & FK, you need to configure the relationship to be one-to-one. As you figured out, one way to do it is to add reference navigation `Class2.Class1`. If you don't want to add navigation then you can use fluent API. You can do it like this.
`modelBuilder.Entity<Class1>().HasOne(e => e.Class2).WithOne();`
