### ISSUE TITLE
Include() statement when related record is not found

### ISSUE THREAD

**Issue by aday12345** [dotnet/efcore#9975]
When using the Include() statement to brink back related objects i have noticed that if the related child record cannot be found then the parent record is not returned when i would expect (or would like) it to be with just a NULL value for the child record. It looks like it is just doing a JOIN instead of a LEFT JOIN.

Is there another statement I should be using to get it to do a LEFT JOIN i do like the idea of using includes.

Thanks,

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 7
IDE:Visual Studio 2017

**Comment by smitpatel** [comment]
@aday12345 - An optional relationship could have null FK value implying no associated parent row whereas a required relationship means there will be always a parent row associated. For parent side, child may or may not exist. Based on that, when we are generating query and if it is guaranteed to have associated row, we do JOIN rather than LEFT JOIN since that is optimization and it would give same results regardless, (since there are no rows would produce NULL). All this happens automatically for include and it makes sure that correct JOIN is applied. If you are seeing that there was a parent with no related child which was supposed to be returned but using include did not return it then please provide us a repro code which demonstrate that.

**Comment by aday12345** [comment]
ok, so I get that ant it makes sense.

But it this case it is (intentional) bad data and I have a required relationship (not null) and a missing child record i wish it would still return a null back so i can make the decision in my code how to handle it.

**Comment by smitpatel** [comment]
If you have bad data (missing child records) then your FK is nullable on database. If you are configuring relationship to be required in EF model then you are causing a mismatch between EF model & database. That is likely to fail. Either you can configure the relationship to be optional in EF or query manually rather than using EF.

**Comment by aday12345** [comment]
thanks, for your help
